### ISSUE TITLE
ClientId for your service account

### ISSUE THREAD

**Issue by jakko10** [MicrosoftDocs/OfficeDocs-Exchange#1000]
Hi, 

Question regarding step 3 in: Grant access to the service account for your Google tenant
What is meant by ClientId for your service account. O365 admin account? GSuite account of some sort?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by wrall** [comment]
Hi jakko10,

The ClientId is the same as the "Unique ID" for the Google Service Account that you created as a part of step 1: [Create a Google Service Account](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#create-a-google-service-account).  It should be a ~21-digit number.

I'll update the document to refer to that section when mentioning the ClientId.

Thanks
-Will
