### ISSUE TITLE
this article competes with the conditional access article on the same topic.

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1004]
See my suggestion here: https://github.com/MicrosoftDocs/azure-docs/issues/32526

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@Mike-Crowley Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @Mike-Crowley 

Thank you for reaching out!

Would you be so kind as to elaborate more on this issue? It would help us to understand it better and take appropriate steps to resolve or clarify. Thank you.

**Comment by Mike-Crowley** [comment]
See the other link I posted with my suggestion

________________________________

**Comment by sowjanya365** [comment]
Thank you!

As we can see on the URL, team is investigating on this. As both the topics relate to same issue, we can close one.

**Comment by Mike-Crowley** [comment]
Thank you!
________________________________

**Comment by sowjanya365** [comment]
Hi @scanum 

Please close this issue. Thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
