### ISSUE TITLE
Exchange support of "The PROXY protocol"

### ISSUE THREAD

**Issue by git001** [MicrosoftDocs/OfficeDocs-Exchange#1009]
Dear Microsoft team.

I haven't seen in the doc if the exchange server 2016 supports [**The PROXY protocol**](http://www.haproxy.org/download/1.9/doc/proxy-protocol.txt) . Do you know if the none HTTP Exchange modules support this protocol for incoming connections?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad23232-ca3e-3ae0-8c3d-a68fd0e29b82
* Version Independent ID: 3416f819-2a96-e639-53b8-419cfd66e7f9
* Content: [Receive connectors](https://docs.microsoft.com/en-us/exchange/mail-flow/connectors/receive-connectors?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/connectors/receive-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/connectors/receive-connectors.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@git001 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@git001 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by agowa338** [comment]
So where is the documentation?
Does exchange support this or not?

**Comment by chrisda** [comment]
@agowa338, unless you can prove that it does, or unless the documentation says that it does, then it's not supported.
