### ISSUE TITLE
DPT and excluding few default folders from it.

### ISSUE THREAD

**Issue by techiesahal** [MicrosoftDocs/OfficeDocs-Exchange#101]
is it really possible as you explained in above last point in more info section. when i raise an  call with MS, the engineer says me its not possible. above point says:
"To prevent the DPT settings from moving items in a default folder, you can create a disabled Personal Tag with the move to archive action, add it to the retention policy, and then have users apply it to the default folder"

Can you check the accuracy of this statement in this page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd067815-de9f-6c6f-a6f1-eceb78e50366
* Version Independent ID: 2ef7cd6f-bda3-58ba-c485-afc6102ee5d6
* Content: [Default folders that support Retention Policy Tags](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/default-folders)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
investigating

**Comment by techiesahal** [comment]
-------------------------------------------------------------------
Symptom:
Unable to apply a retention policy against specific folders (Calendar, Tasks, and Notes).
 
Cause:
N/A
 
Resolution:
To exclude these folders (Calendar, Tasks, and Note) from the retention policy, you need to assign a personal retention tags to the affected users then apply them to all folders except the mentioned folders.

Also, you can check the following article if it meet you requirements, if not, you can open another case with the messaging development team to modify the script to meet your requirements:
https://blogs.msdn.microsoft.com/emeamsgdev/2016/04/22/powershell-apply-retention-policies-or-auto-archive-settings-to-inbox-sub-folders/
--------------------------------------------------------

This was summary of the case

**Comment by AndreaBarr** [comment]
@techiesahal Thank you for this feedback. 

I am geting this over to the SharePoint team so we can get this article addressed and make sure it's accurate. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by dariomws306** [comment]
I have tried and it worked as expected. I assigned the "Personal never move to archive" tag to the inbox folder and MRM no longer move emails older than 2 years to the archive mailbox, but it still moves email from Sent Items to archive and other default folders.

**Comment by dariomws306** [comment]
@AndreaBarr , I think we should close this, this feature works as expected, as it's written in the documentation.

**Comment by amberru1** [comment]
sorry to reopen this, did you try it on the Calendar?  I do not have the option to select a policy for the calendar but i do for other default folders such as inbox...  At the bottom of this article that i have included it says you cannot apply retention tags to calendars.  https://support.office.com/en-us/article/retention-and-archive-policies-in-outlook-web-app-465372e4-e16b-47db-bee0-aba44799085e

**Comment by dariomws306** [comment]
Hi @amberru1,

Thank you for your comment.

I didn't try with the calendar... I can suggest that you open a new issue to check it. One of these articles should be updated so both have the same information about calendar folder.

**Comment by dariomws306** [comment]
@amberru1, I found more information about this.

You can create RPT for calendar folder from powershell:
https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance-retention/New-RetentionPolicyTag?view=exchange-ps

It's the same as Task folder, looks the article referenced in this issue, search for Task folder in the table and read the Detail column.

Also the article you are referencing is related to OWA.
