### ISSUE TITLE
Language keywords

### ISSUE THREAD

**Issue by vivesg** [MicrosoftDocs/OfficeDocs-Exchange#1013]
I'm an SE of the Exchange OnPrem team gevivesh
Working with a customer using Exchange 2010 on French environment
we found interesting that the query needs to use french keywords 

Looking to the french reference
https://docs.microsoft.com/fr-fr/exchange/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators#feedback

The keywords are wrong and does not work
http://blog.aannaque.org/2014/01/supprimer-un-message-indesirable-dun.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7393c45-1119-f0ea-67dc-36ecf42d2e08
* Version Independent ID: 29417cc2-6a03-bea3-f195-51ca55f9dc1a
* Content: [Message properties and search operators for In-Place eDiscovery](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by vivesg** [comment]
The query depends of the language of the Onprem Exchange

**Comment by markjjo** [comment]
@vivesg Please see: https://docs.microsoft.com/en-us/windows/desktop/search/-search-3x-advancedquerysyntax#keyword-use-in-local-languages 

I assume this is the issue you are encountering. Since you are using Exchange 2010, the properties in the Exchange Online topic aren't going to be applicable because In-Place eDiscovery in Exchange Online is based on KQL, not AQS.
