### ISSUE TITLE
Modern Authentication/OAuth is not supported in Office 365 MDM profiles

### ISSUE THREAD

**Issue by snorma01** [MicrosoftDocs/OfficeDocs-Exchange#1017]
Starting with iOS 12, there has been a way to enable OAuth within the Intune mail profile in order to support MFA users when pushing profiles to devices using the Intune Company Portal app. However, there is no such option in Office 365 MDM and MFA users do not seem to be supported at all in this product. Given that Microsoft recommends that MFA be used for all users, it is clear that Office 365 MDM needs to support MFA. The same OAuth/Modern Authentication options that are available to Intune administrators need to be made available to Office 365 MDM administrators.

**Comment by scanum** [comment]
@snorma01 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by snorma01** [comment]
Hi Manuela/@scanum,

I tried opening a ticket with Office 365 support, and they said the lack of
support was a known issue and there was nothing they could do until it was
developed, so I believe this does belong with this Github community. Is
there a way this ticket can be re-opened? Or should I open a new ticket?
