### ISSUE TITLE
Unclear if date must be in US format or whether it will use format local of the exchange server

### ISSUE THREAD

**Issue by JamesHoggIOH** [MicrosoftDocs/OfficeDocs-Exchange#1018]
example given is: sent&gt;=06/01/2014 AND sent&lt;=07/01/2014
Best practice for an international product would be using international format

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7393c45-1119-f0ea-67dc-36ecf42d2e08
* Version Independent ID: 29417cc2-6a03-bea3-f195-51ca55f9dc1a
* Content: [Message properties and search operators for In-Place eDiscovery](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@JamesHoggIOH - Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @JamesHoggIOH 

Thank you for helping improve the content. 

The date was mentioned as per the document locale en-US format. But to avoid confusion, we've explained the date format in the document. You will be able to see the modifications once the PR gets merged with the document. 

"Messages that were sent on July 01, 2014. The second example returns all messages sent between June 01, 2014 and July 01, 2014"

Thank you.

**Comment by scanum** [comment]
@JamesHoggIOH Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
