### ISSUE TITLE
In Step 2: Prepare for the migration > Prerequisite steps in Exchange Online > Step 4, last command

### ISSUE THREAD

**Issue by miryb** [MicrosoftDocs/OfficeDocs-Exchange#1019]
Current cmdlet:
Get-Mailbox -PublicFolder -SoftDeletedMailbox | Remove-Mailbox -PublicFolder -PermanentlyDelete:$true

Add also here the FORCE switch as above (for the replication delays exception) and specify a unique identifier for the PF mailbox (for ManagementObjectAmbiguousException).

Example of proposed command:  
Get-Mailbox -PublicFolder -SoftDeletedMailbox | % {Remove-Mailbox -PublicFolder $_.PrimarySmtpAddress -PermanentlyDelete:$true -force}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@miryb - Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @miryb 

Thank you for reaching out!

As we know that "Force" switch specifies whether to suppress warning or confirmation messages. It's not a mandatory parameter. Please let us know if you are facing any technical issue while running this command with out the above specified parameters.  Looking forward to your response. Thank you.

**Comment by miryb** [comment]
Hi, we have seen cases in support where, if we don't run the command with
the -force switch (as it is now in the article), it gives this error:

"Microsoft.Exchange.Management.Tasks.RecipientTaskException: Public folder
replication has been delayed. Please wait until replication is complete
before you remove this public folder mailbox. Replication could take up to
an hour. If you remove the mailbox before replication is complete, your
public folder deployment could be in an inconsistent state".

This is being worked around by using -force switch. Contact me on mireb
alias for further clarifications/ examples.

*Mirela Buruiana*

**Comment by sowjanya365** [comment]
Hi @miryb 

Thank you for your response. 

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs. Please follow this link to contact support for business products:

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by miryb** [comment]
I work in Microsoft Support as an SEE. This is happening to multiple
Microsoft customers who open cases with us because of the cmdlet without
force switch fails with the error that I mentioned.
PG recommendation is to use -force switch.

*Mirela Buruiana*

**Comment by msdmaguire** [comment]
@miryb I will update the article with this info. Please tie your GitHub account with your Microsoft alias so that you will be seen as an internal submitter in the future. Thank you for the feedback.

**Comment by msdmaguire** [comment]
Command has been updated and should be live by tomorrow.

**Comment by miryb** [comment]
thanks!!
