### ISSUE TITLE
Should any special OU's in ADConnect be included after working through the above procedure?

### ISSUE THREAD

**Issue by dm3942** [MicrosoftDocs/OfficeDocs-Exchange#102]
After running the scripts and Set-OrganizationConfig command. I have confirmed that the public mail contact objects have been created in o365 using o365 powershell commands. However, Public folders still aren't visible in the folder view from outlook 2016 for an o365 mail user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1812196b-e6c5-7f6e-fa82-49df2a47d73d
* Version Independent ID: cc06c76a-b7a0-7c21-0a73-c66b9b05a055
* Content: [Configure Exchange 2013 public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@dm3942  Thank you for this feedback

I want to make sure that the script works correctly for you. Support will be able to help bring this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
