### ISSUE TITLE
Explain how to get to the Exchange Management shell for O365

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-Exchange#1021]
Please Explain how to get to the Exchange Management shell for O365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 334f26cd-67c5-4ccc-3586-30b0dbe030c4
* Version Independent ID: 5f001750-0a87-1d12-265f-546da2652d36
* Content: [Enable or disable POP3 or IMAP4 access to mailboxes in Exchange Server](https://docs.microsoft.com/en-us/exchange/clients/pop3-and-imap4/configure-mailbox-access?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/pop3-and-imap4/configure-mailbox-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/pop3-and-imap4/configure-mailbox-access.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solving Issue #1021 with this PR #1047

**Comment by scanum** [comment]
@blouwagie Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
