### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/OfficeDocs-Exchange#1029]
Please provide steps for mailboxes:
SystemMailbox{2CE34405-31BE-455D-89D7-A7C7DA7A0DAA}
SystemMailbox{D0E409A0-AF9B-4720-92FE-AAC869B0D201}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca0013eb-5599-a907-9869-569f40f1e725
* Version Independent ID: 9fd23081-2830-c87b-561b-582fb16fc09e
* Content: [Recreate missing arbitration mailboxes](https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/recreate-arbitration-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@grzegorzwierzbicki Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@msdmaguire

**Comment by lindspea** [comment]
@msdmaguire any update yet?

**Comment by msdmaguire** [comment]
Re-pinging my contact. Might be the case that these mailboxes are not needed on prem anymore but I need to confirm.

**Comment by scanum** [comment]
@msdmaguire Any updates on this? Thanks !!

**Comment by msdmaguire** [comment]
@grzegorzwierzbicki One of these mailboxes is the Shard Relevancy Feature Store mailbox and the other is the Office Message Encryption Store mailbox. I couldn't get a definitive answer at this time as to what exactly these mailboxes are used for. They are only used on-premises in a non-Datacenter environment. If you need to restore one of these mailboxes, the best way forward is if you open a service ticket so this can get resolved ASAP. 
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
