### ISSUE TITLE
Error on 2012 setup

### ISSUE THREAD

**Issue by mrowancfs** [MicrosoftDocs/OfficeDocs-Exchange#1030]
Seems to be something missing from the setup instructions. If you select Anonymous Authentication, you are not prompted to enter and credentials. 

25. Select Anonymous Authentication.
26. Enter the credentials of the Office 365 user who you want to use to relay SMTP mail.
27. Select TLS Encryption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e73bb3c6-ab71-066f-18e8-f0726cebf9d2
* Version Independent ID: 16e49af3-9980-d928-7667-ee8f5e07c487
* Content: [How to configure IIS for relay with Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @SuPotter
* Microsoft Alias: **supotter**

**Comment by scanum** [comment]
@mrowancfs Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@mrowancfs  Thank you for the feedback. We have made the changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1071

**Comment by scanum** [comment]
@mrowancfs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
