### ISSUE TITLE
Numbers are wrong for the image on this page .. 

### ISSUE THREAD

**Issue by kekici** [MicrosoftDocs/OfficeDocs-Exchange#1031]
[Enter feedback here]
Numbers are wrong for the image on this page .. Should be;

3- The Transport service on Mailbox01 processes the primary message.

3a - In this example, the recipient's mailbox is located on Mailbox01, so the Transport service transmits the message to the local Mailbox Transport service.

3b - The Mailbox Transport service delivers the message to the local mailbox database.

3c - Mailbox01 queues a discard status for Mailbox03 that indicates the primary message was successfully processed, and Mailbox01 moves a copy of the primary message into the local Primary Safety Net. Note that the message moves between queues within the same queue database.

4- Mailbox03 periodically polls Mailbox01 for the discard status of the primary message.

5- When Mailbox03 determines Mailbox01 successfully processed the primary message, Mailbox03 moves the shadow message into the local Shadow Safety Net. Note that the message moves between queues within the same queue database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4eba034-4968-a5f2-db09-80a6ade78617
* Version Independent ID: 418b7713-e2f0-ea42-aa96-c1d48676b587
* Content: [Transport high availability in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/transport-high-availability/transport-high-availability?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-high-availability/transport-high-availability.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-high-availability/transport-high-availability.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@kekici Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
@kekici, thanks for the feedback. This was a TechNet to docs.microsoft.com conversion to markdown issue (the new numbered list under step 3 weren't indented properly). I fixed it (and changed them to a. b.and c. to match the picture).
