### ISSUE TITLE
Incorrect indenting

### ISSUE THREAD

**Issue by SuperTekBoy** [MicrosoftDocs/OfficeDocs-Exchange#1034]
Under "Selecting the connector for an external recipient" bullets 4, 5 and 9 should be indented under bullet 3. In addition, bullets 6, 7 and 8 should be indented under bullet 5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744b6e86-e19f-47d5-0948-e101046c161b
* Version Independent ID: 2c562d8e-dd9a-d3ba-75c1-2d83acfe477f
* Content: [Connector selection in external message routing](https://docs.microsoft.com/en-us/exchange/mail-flow/mail-routing/connector-selection?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/mail-routing/connector-selection.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/mail-routing/connector-selection.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SuperTekBoy, yes, it was an indentation problem that I fixed.

Thanks for the feedback.
