### ISSUE TITLE
Start a G Suite migration batch with the Exchange admin center (EAC)

### ISSUE THREAD

**Issue by jakko10** [MicrosoftDocs/OfficeDocs-Exchange#1035]
step 4 - a CSV is required. But what exact fields are required in the CSV? Can you please provide an example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jakko10 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by jakko10** [comment]
@scanum also step 8, where I would need to select the target delivery domain which I created earlier, the one that I created does not show up there, or as a matter of fact, none of the other domains do. I only see mydomain.mail.onmicrosoft.com there, but looks like it's fine as migration works just fine with this domain too. Maybe you updated this part but forgot to update this doc here?

**Comment by wrall** [comment]
@jakko10 

The CSV file is described in step #2 of the [PowerShell instructions](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md#create-a-migration-batch-in-office-365) and step #4 of the [EAC instructions](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md#start-a-g-suite-migration-batch-with-the-exchange-admin-center-eac).  I can add an example as well.

For the Target Delivery Domain, the value must be typed into the text box using your keyboard - it will not be listed in the dropdown automatically in this scenario.  Using the in-box mydomain.mail.onmicrosoft.com will work at first, but will not be allowed during finalization.  I'll add another note here as well.
