### ISSUE TITLE
Help with Provision users in O365 section and mail users

### ISSUE THREAD

**Issue by JosephHartley** [MicrosoftDocs/OfficeDocs-Exchange#1036]
The 'Provision users in O365' section requires me to add the users who will be migrated from Gmail as 'mail users.'

However, I can't do this as I have already added everyone as a user mailbox in O365, so I get the error message "The proxy address is already being used by the proxy addresses or LegacyExchangeDN. Please choose another proxy address."

Is there a way to add the external email address and proxy address to these existing mailboxes? Or do I have to delete the existing mailboxes and start afresh by adding them as mail users?

**Comment by scanum** [comment]
@JosephHartley thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
