### ISSUE TITLE
Couple suggestions for clarity

### ISSUE THREAD

**Issue by marklitwin** [MicrosoftDocs/OfficeDocs-Exchange#1037]
Would recommend referencing the Data Resiliency page for details on how the service is protected from quite a few scenarios that are covered here at a much higher level.
https://docs.microsoft.com/en-us/Office365/securitycompliance/office-365-exchange-data-resiliency

Might also be interesting to note the recommendations about avoiding traditional backup are also applicable to Exchange Server.
https://docs.microsoft.com/en-us/Exchange/high-availability/disaster-recovery/disaster-recovery?view=exchserver-2019

DAG comment about multiple datacenters is confusing when called a "back up", data resiliency link above even says they are not backups and better explains how they protect data as replication.

User backup section, not sure this is a best practice and perhaps a bit confusing as the talk track is typically about "archiving" older data which is different than backing up.  Users have a 100GB mailbox in EXO, this should be sufficient for most scenarios and avoids the complexity of using the archive.  

More emphasis would be useful on the default 30 day retention using single item recovery and how customers can customize and meet their requirements using retention policies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39a1f3ef-3137-603e-65ed-41a0fbd0cbb2
* Version Independent ID: c2bcddd7-cca5-3118-b810-12fda87b195f
* Content: [Back up email in Exchange Online](https://docs.microsoft.com/en-us/exchange/back-up-email#feedback)
* Content Source: [Exchange/ExchangeOnline/back-up-email.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/back-up-email.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@marklitwin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solving with PR #1046

**Comment by scanum** [comment]
@marklitwin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
