### ISSUE TITLE
Need update Cumulative Update 2 for Exchange Server 2016

### ISSUE THREAD

**Issue by Rameshrao99** [MicrosoftDocs/OfficeDocs-Exchange#1040]
Hi,

I am trying to update Exchange 2016 CU12 on existing Exchange 2016 CU2, however experiencing  Error:
Couldn't remove product with code cd981244-e9b8-405a-9026-6aeb9dcef1f1. The installation source for this product is not available. Verify that the source exists and that you can access it. Error code is 1612.

Need CU2 setup files.

**Comment by scanum** [comment]
@Rameshrao99 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Rameshrao99** [comment]
This is on-prem Exchange 2016 server not O365.

**Comment by Rameshrao99** [comment]
> @officedocsbot close
This is on-prem Exchange 2016 server not O365.

**Comment by Rameshrao99** [comment]
any update on this?
