### ISSUE TITLE
Sel-fService Device WIpe Instructions

### ISSUE THREAD

**Issue by keithbakermartin** [MicrosoftDocs/OfficeDocs-Exchange#1042]
These instructions appear to be out-of-date:

Use Outlook on the web to wipe a user's phone

Your users can use Outlook on the web to wipe their own phones.

    In Outlook on the web, select the Settings icon.

    Under Your app settings, select Mail. &lt;--- There is no "Your app settings" option

    Under Options, click to expand General if necessary, and then select Mobile devices. &lt;-- In the existing setting area, there is no "Mobile devices" option under General.

    Select the mobile phone.

    Click or tap the Wipe Device icon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92072b83-beec-a8d5-b5c0-b5900265fbc8
* Version Independent ID: 134ac1f2-0fc9-9598-b89a-72110c16c214
* Content: [Perform a remote wipe on a mobile phone](https://docs.microsoft.com/en-us/exchange/clients/exchange-activesync/remote-wipe?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/clients/exchange-activesync/remote-wipe.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/exchange-activesync/remote-wipe.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by keithbakermartin** [comment]
I failed to point out that the above problem is with "the new Outlook" slider set to On.

**Comment by scanum** [comment]
@keithbakermartin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@keithbakermartin Thank you for your feedback. We have added steps for the new outlook view via PR https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1072

**Comment by scanum** [comment]
@keithbakermartin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
