### ISSUE TITLE
/owa does not redirect to https

### ISSUE THREAD

**Issue by efpob** [MicrosoftDocs/OfficeDocs-Exchange#105]
For some reason, just adding /owa as the redirect-URL does not work, it only redirects to the http site. I needed to add the fqdn https://mail.example.com/owa for it to work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad6b073-061b-60d6-958c-e3f408aebf85
* Version Independent ID: 19356060-5edf-5eb7-6abc-97c4fc741bd5
* Content: [Configure http to https redirection for Outlook on the web in Exchange 2016](https://docs.microsoft.com/en-us/exchange/clients/outlook-on-the-web/http-to-https-redirection)
* Content Source: [Exchange/ExchangeServer/clients/outlook-on-the-web/http-to-https-redirection.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-on-the-web/http-to-https-redirection.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@efpob thank you for this feedback

I want to make sure that the redirect url works properly. Support will be able to help you with this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
