### ISSUE TITLE
Already migrated Domain 

### ISSUE THREAD

**Issue by Slidercraft** [MicrosoftDocs/OfficeDocs-Exchange#1051]
I have a situation where we have already migrated the GSUITE mail domain to o365 (MX record already cutover) however the user mailboxes still exist in GSUITE. 

The migrated users were setup to be able to send and receive as the old domain via the use of a shared mailbox in o365 with their legacy alias associated and providing the user send as rights on the shared mailbox...

I need a way to migrate all the GSUITE mailboxes into o365 and associate them to different user accounts that can be setup as a shared mailbox for the user to access.

**Comment by scanum** [comment]
@Slidercraft thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
