### ISSUE TITLE
Question about the tip in the section of scenario 2

### ISSUE THREAD

**Issue by JBalk1984** [MicrosoftDocs/OfficeDocs-Exchange#1053]
Within the TIP the following line is mentioned: "If you don't have any on-premises mailbox(es), you can safely decommission your exchange server(s)."

Why is this mentioned, the Source of Authority is only changed towards Azure AD when AADConnect has stopped syncing and the authority is handed over towards Azure AD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#feedback)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@JBalk1984 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by yurokk** [comment]
Would it be possible to introduce Ex2019 into the existing 2010 environment and then remove all 2010 servers and leave 2019 for user management?

**Comment by get-itips** [comment]
Hello @JBalk1984 
Thanks for your feedback.

Be careful that the phrase in the note is not exactly as you copied it here:

> If you don't have any on-premises mailbox(es), you can safely decommission **most of your exchange server(s), leaving one or more for user management purposes.**

About the SoA, you are right about it and the article is stating that each service will be auth users independently, I will propose thru a pull request some clarification on this.

Thank you

**Comment by chrisda** [comment]
Exchange 2010 and Exchange 2019 coexistence isn't allowed. Exchange 2019 setup will fail if it detects Exchange 2010 in AD (the Exchange version - 2 supported upgrade rule).

**Comment by yurokk** [comment]
Thanks for replying, chrisda.  Is it feasible to remove all 2010 servers and re-introduce Exchange to the environment with 2019? I'm trying to find the best way to keep the latest version of Exchange on-prem; all mailboxes have been migrated and we still have Hybrid config in place with MX pointing to on-prem.

**Comment by chrisda** [comment]
@yurokk, if it's even possible to uninstall your 2010 hybrid server, you would probably need to reconfigure hybrid all over again, so I wouldn't recommend that. The general Exchange 2010 to Exchange 2019 upgrade path would be to upgrade to Exchange 2013 or Exchange 2016 first, and then upgrade to 2019. But, there are issues:

- In-pace upgrades haven't been available for years, so you'll need at least one other server for the first migration to 2013 or 2016. You could theoretically use you now decomissioned 2010 server for 2019, but...

- The [minimum RAM requirements](https://docs.microsoft.com/Exchange/plan-and-deploy/system-requirements?view=exchserver-2019#hardware-requirements-for-exchange-2019) for Exchange 2019 Mailbox servers are very high: 128 GB.

**Comment by scanum** [comment]
@JBalk1984 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by maxzavo** [comment]
Could the tip in the section of scenario 2 have a clarification regarding Exchange CAL requirements?
 
For example:
"Exchange CALs for the remaining Exchange Servers are not needed in this case, since the users are not accessing any resources on the on-prem Exchange Servers. See <license article link> for reference."
OR
"At the minimum, Exchange Standard CALs for all users in on-prem AD who connect to the online Exchange services are still required. See <license article link> for reference."

**Comment by yurokk** [comment]
> @yurokk, if it's even possible to uninstall your 2010 hybrid server, you would probably need to reconfigure hybrid all over again, so I wouldn't recommend that. The general Exchange 2010 to Exchange 2019 upgrade path would be to upgrade to Exchange 2013 or Exchange 2016 first, and then upgrade to 2019. But, there are issues:
> 
> * In-pace upgrades haven't been available for years, so you'll need at least one other server for the first migration to 2013 or 2016. You could theoretically use you now decomissioned 2010 server for 2019, but...
> * The [minimum RAM requirements](https://docs.microsoft.com/Exchange/plan-and-deploy/system-requirements?view=exchserver-2019#hardware-requirements-for-exchange-2019) for Exchange 2019 Mailbox servers are very high: 128 GB.

chrisda - If all my mailboxes have been migrated and MX record is now pointing to 365, please help me understand the need for hybrid configuration? Also, would I be able to introduce 2016 into the environment and then remove 2010 from the environment?

**Comment by chrisda** [comment]
Identity management is another big piece of Exchange hybrid. Yeah, you can have mailboxes in the cloud and online, or even exclusively in the cloud, but which accounts are people using to login to their mailboxes? If they're using on-prem AD accounts to access cloud mailboxes, then you'll definitely need to maintain at least one on-prem Exchange server for hybrid management purposes.

I can see no reason why you shouldn't be able to upgrade your (now rather depleted) on-prem Exchange 2010 organization to Exchange 2016, but as discussed previously, you'll need a new/different server for Exchange 2016. If you want specific steps or details, you should open a support ticket.

**Comment by yurokk** [comment]
Thank you, @chrisda for taking the time to answer. Yes, on-prem AD is still the source of authority, so we’re keeping the hybrid config. New server is not an issue at all, just a matter of spinning up another VM. Thanks again :).
