### ISSUE TITLE
Unclear sentence

### ISSUE THREAD

**Issue by erjenrijnders** [MicrosoftDocs/OfficeDocs-Exchange#1054]
I have read this sentence like 10 times but not getting what you mean:

> Hybrid Modern Authentication is not supported with the Hybrid Agent. Customers will need to leverage the Classic Exchange Hybrid Topology and publish AutoDiscover, EWS, MAPI and OAB endpoints for hybrid Modern Authentication to function with various Outlook clients.

So if you use Modern Auth, you can't use the Hybrid Agent? And we need to roll back to classic Exchange Hybrid topology so that MFA won't work again? Or does it work once we deploy AutoDiscover, EWS etc? I don't understand the sentence and the relation between the hybrid agent, modern auth, deploying Autodiscover etc.

[](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#preview-constraints)

**Comment by erjenrijnders** [comment]
https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#preview-constraints

**Comment by scanum** [comment]
@erjenrijnders Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @erjenrijnders 
Thanks for your feedback.
I do not see an issue with the article, please be sure to read it throughly in detail.
Essentially, HCW comes in two flavours, Classic and Modern Hybrid Topology (Which installs the Hybrid Agent)
As this Hybrid agent is not compatible with Modern Auth, you have to use the Classic option in HCW to use it.

**Comment by scanum** [comment]
@erjenrijnders Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
