### ISSUE TITLE
Info about convert labels to categories

### ISSUE THREAD

**Issue by ecanales88** [MicrosoftDocs/OfficeDocs-Exchange#1056]
Hi, please there is a way for convert gmail labels to outlook categories in this migration process? and how to use archiving space for gmail mailbox with more than 100GB?
Thanks!

**Comment by scanum** [comment]
@ecanales88 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
