### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by mnblacklock** [MicrosoftDocs/OfficeDocs-Exchange#1057]
MSExchangeHMHost.exe line lists mailbox twice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176e9cde-47cb-31b8-9ecf-51208888a740
* Version Independent ID: 97f0327a-5dba-d810-daeb-cd976b634c8b
* Content: [Running Windows antivirus software on Exchange servers](https://docs.microsoft.com/en-us/Exchange/antispam-and-antimalware/windows-antivirus-software?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mnblacklock Mailbox server was listed twice for MSExchangeHMHost.exe and MSExchangeHMWorker.exe, so I fixed them both.

Thanks for the feedback.
