### ISSUE TITLE
feed back on folder /Deletions and /Purges 

### ISSUE THREAD

**Issue by limin365** [MicrosoftDocs/OfficeDocs-Exchange#1058]
items would have some retention duration in "/purges". MFA will hard deleted items from "/purges" out of Exchange after it reached duration based on my understanding.  May I have some discussion with you regarding following sentence? Great thanks. 
"After the deleted item retention period expires, the item is moved to the Purges folder and is no longer visible to the user. When the Managed Folder Assistant (MFA) processes the mailbox, items in the Purges subfolder are purged from Exchange Online."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbbc82b-b1c8-f2b7-9f57-9fa9137305a3
* Version Independent ID: f1ce321a-ed5e-fe57-450d-35cc7b104350
* Content: [Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@limin365 You are correct. If an item is hard deleted  before the deleted item retention period expires (and moved to the Purges folder) and if single item recovery is enabled for the mailbox, then the item won't be purged by the MFA until the deleted item retention period for the item expires.
