### ISSUE TITLE
[LOC] Multiple invalid links in esrp-storage.md

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#1059]
Could you please review and update / remove broken links from a article _esrp-storage_ ?

LiveURL: https://docs.microsoft.com/en-us/exchange/esrp-storage?view=exchserver-2019
GH: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/esrp-storage.md

examples of broken links:
 - http://en.community.dell.com/techcenter/extras/m/white_papers/20439110.aspx
 - http://en.community.dell.com/techcenter/extras/m/white_papers/20439132.aspx
 - http://en.community.dell.com/techcenter/extras/m/white_papers/20439312.aspx
 - http://en.community.dell.com/techcenter/extras/m/white_papers/20439313.aspx
 - http://en.community.dell.com/techcenter/extras/m/white_papers/20440232/download.aspx
 - http://en.community.dell.com/techcenter/extras/m/white_papers/20440259.aspx
 - http://en.community.dell.com/techcenter/extras/m/white_papers/20440260.aspx
...

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @OfficeGlobal @scanum I could succesfully retrieve new links for several linked pdf, but could not find for the following:

[Dell PowerEdge R720xd 2,000 Mailbox Exchange 2013 Mailbox Resiliency Storage Solution (Jun 5, 2013)](http://en.community.dell.com/techcenter/extras/m/white_papers/20381192.aspx)

[Dell XC Series 2,300 Mailbox Microsoft Exchange 2013 Mailbox Resiliency Storage Solution (April 11, 2016)](http://en.community.dell.com/techcenter/extras/m/white_papers/20442391)

[Dell PowerVault MD3260 15,000 Mailbox Microsoft Exchange 2013 Mailbox Resiliency Storage Solution (Apr 10, 2014)](http://en.community.dell.com/techcenter/extras/m/white_papers/20439083.aspx)

[Dell Compellent Storage Center 6.4 10K Drive 10,000 Mailbox Microsoft Exchange 2013 Mailbox Resiliency Storage Solution (Oct 24, 2013)](http://en.community.dell.com/techcenter/extras/m/white_papers/20437919.aspx)

[Dell Compellent Storage Center 6.4 10K Drive 5000 Mailbox Microsoft Exchange 2013 Mailbox Resiliency Storage Solution (Oct 24, 2013)](http://en.community.dell.com/techcenter/extras/m/white_papers/20437918.aspx)

[Dell Compellent Storage Center 6.4 7K Drive 10,000 Mailbox Microsoft Exchange 2010 Mailbox Resiliency Storage Solution (Oct 24, 2013)](http://en.community.dell.com/techcenter/extras/m/white_papers/20437921.aspx)

[Dell Compellent Storage Center 6.4 7K Drive 5000 Mailbox Microsoft Exchange 2013 Mailbox Resiliency Storage Solution (Oct 24, 2013)](http://en.community.dell.com/techcenter/extras/m/white_papers/20437920.aspx

Should we remove them?

**Comment by OfficeGlobal** [comment]
Hello @get-itips , it would help us if you could remove all invalid links from an article. We're getting lot of bugs from VaaS / CATs tools

**Comment by get-itips** [comment]
@OfficeGlobal Sure, will remove invalid links too. @scanum

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
