### ISSUE TITLE
Error when trying to complete the migration

### ISSUE THREAD

**Issue by jackieyeo23** [MicrosoftDocs/OfficeDocs-Exchange#1061]
Error when trying to complete the migration. Error: MigrationMRSPermanentException: Error: The target mailbox doesn‎'t have an SMTP proxy matching ‎'o365.ambercreative.sg‎'.

**Comment by scanum** [comment]
@jackieyeo23 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
