### ISSUE TITLE
Error in article

### ISSUE THREAD

**Issue by diggisaur** [MicrosoftDocs/OfficeDocs-Exchange#1065]
The second paragraph is referencing an old anchor link I believe. This is what it says.

"Looking for other information related to lagged mailbox database copies? Check out [Manage mailbox database copies](manage-database-copies.md."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c6b102c-5abb-32a0-da9f-dde75166e22a
* Version Independent ID: 9853dd25-84db-e1d0-9b10-ab377172e9e5
* Content: [Activate a lagged mailbox database copy](https://docs.microsoft.com/en-us/Exchange/high-availability/manage-ha/activate-lagged-db-copies?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/high-availability/manage-ha/activate-lagged-db-copies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/manage-ha/activate-lagged-db-copies.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@diggisaur Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @diggisaur thanks for noting this.
I created a pull request to correct the link.
Thank you

**Comment by scanum** [comment]
@diggisaur Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
