### ISSUE TITLE
Build numbers for Office 365 Exchange Online are missing from this list.

### ISSUE THREAD

**Issue by ecederstrand** [MicrosoftDocs/OfficeDocs-Exchange#1067]
AFAIK, they are in the 15.20.x.x range.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf984bf-df1c-bcd5-6475-54b9ef24fe74
* Version Independent ID: 00547ab9-7b3b-f6b0-fa7f-429f5e2bea56
* Content: [Exchange Server build numbers and release dates](https://docs.microsoft.com/en-us/Exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@ecederstrand Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ecederstrand Thanks for pointing this out Erik. I'll chat to the team and get them added soonest.

**Comment by chrisda** [comment]
@ecederstrand, the intent of this topic and the area where it lives is on-premises Exchange Server. We have not plans to include Exchange Online build information in this topic.

Thanks for the feedback.
