### ISSUE TITLE
Incorrect statement

### ISSUE THREAD

**Issue by mariosaelikeit** [MicrosoftDocs/OfficeDocs-Exchange#1068]
https://docs.microsoft.com/en-us/exchange/hybrid-deployment/create-cloud-based-archive#on-premises-mailbox-properties-before-the-cloud-based-archive-mailbox-is-provisioned-by-directory-synchronization

Don't think this is correct. When a user mailbox exists in Exchange Online and you run the get-mailbox command locally, you should get nothing back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dfb49c-fbb1-4e58-a94b-060f31744d6e
* Version Independent ID: 2b2de3cb-3087-c82a-f6ad-f58990a85ae0
* Content: [Create a cloud-based archive for an on-premises primary mailbox in an Exchange hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/create-cloud-based-archive#on-premises-mailbox-properties-before-the-cloud-based-archive-mailbox-is-provisioned-by-directory-synchronization)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@mariosaelikeit You are running the Get-Mailbox command for a user with an on-premises primary mailbox and a cloud-based archive mailbox. That can probably be make more clear in the intro sentence.

Change this:
You can also run the following PowerShell command in your on-premises Exchange organization to display properties related to a user's cloud-based archive mailbox.

To this:
You can also run the following PowerShell command in your on-premises Exchange organization to display properties related to the cloud-based archive mailbox of an on-premises user.

Does that address the issue?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by mariosaelikeit** [comment]
OK, I think this makes sense now. Thanks.

**Comment by markjjo** [comment]
@mariosaelikeit FYI that topic was updated to make this clearer: "You can also run the following PowerShell command in your on-premises Exchange organization to display properties related to the cloud-based archive mailbox of an on-premises user." Note also that the sample PowerShell command specifies the identity of the on-premises user: Get-Mailbox <on-premises user mailbox> | FL *archive*

https://docs.microsoft.com/en-us/exchange/hybrid-deployment/create-cloud-based-archive#step-2-verify-that-the-cloud-based-archive-mailbox-is-created
