### ISSUE TITLE
What is "OWA for devices"?

### ISSUE THREAD

**Issue by eepyaich** [MicrosoftDocs/OfficeDocs-Exchange#1073]
The page "OWA for Devices contact sync" item in the contents on the left seems to redirect to this page here, which doesn't mention this specific option at all.  However, I want to know what OWA for Devices actually is, so I can decide whether to disable it in our Exchange Online user profiles.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b221cd8e-e6d1-e383-65a2-11f7241de966
* Version Independent ID: cf978d97-c1e6-f0b7-7407-4f70d2284d17
* Content: [Outlook for iOS and Android in Exchange Online](https://docs.microsoft.com/en-gb/Exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@eepyaich Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by michevnew** [comment]
OWA for devices refers to the old "OWA for Android" and "OWA for iPhone/iPad" applications, that we used to have back in the day. Microsoft has since deprecated those. See here for more details: https://support.office.com/en-us/article/microsoft-owa-mobile-apps-are-being-retired-076ec122-4576-4900-bc26-937f84d25a4b

**Comment by j0rt3g4** [comment]
@eepyaich 
I'm pretty sure @michevnew  have solved your doubts, please let us know if you need us to expand more, I'll be adding that information into the article.

**Comment by j0rt3g4** [comment]
Solving Issue on PR #1510

**Comment by scanum** [comment]
@eepyaich Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
