### ISSUE TITLE
Can you also migrate Public Folders from Exchange 2016?

### ISSUE THREAD

**Issue by mariosaelikeit** [MicrosoftDocs/OfficeDocs-Exchange#1079]
"Exchange supports moving your public folders to Office 365 and Exchange Online from the following legacy versions of Exchange Server:
Exchange Server 2010 SP3 RU8 or later"
Is this valid for Exchange Server 2016 as well? Can't seem to find a similar document for that.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fc906e-3899-1d89-836c-a441508b1107
* Version Independent ID: fce642c6-03fb-b344-ed2b-19fcdfc323ce
* Content: [Public folders in Office 365 and Exchange Online](https://docs.microsoft.com/en-gb/exchange/collaboration-exo/public-folders/public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mariosaelikeit
 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
