### ISSUE TITLE
[LOC - Question]  Update redirect links

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#1082]
Hello,

 would it be possible to update links redirected from _SOC_ / _technet.ms.com/library_ to _DOCS_ in Exchange articles?
We're having lot of noise in VaaS reports due to redirection.

List of know redirected links is attached - in case of any future update it would be nice and helpful to change the links in the topics.

Attached list: [Exchange_LinksRedirection.xlsx](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/files/3324631/Exchange_LinksRedirection.xlsx)

Thank you

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
Internal issue. Handling internally
