### ISSUE TITLE
Missing WindowsFeature for Exch 2016 on Win 2016

### ISSUE THREAD

**Issue by nramouche** [MicrosoftDocs/OfficeDocs-Exchange#1083]
I just experience a missing WFeature while setting up using unattended setup (/mode:install /Roles:mb,mt):
NET-WCF-HTTP-Activation45
Since Install-WindowsFeature parameter -IncludeAllSubFeature is not by default, the documented list is therefore exhaustive and might be updated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites, Exchange 2019 system requirements, Exchange 2019 requirements](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prerequisites?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@nramouche Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @nramouche 

Thank you for reaching out! 

"-IncludeAllSubFeature" specifies that all subordinate role services, and all subfeatures of parent roles, role services, or features specified. And for installing the missing windows features, please use the Install-WindowsFeature command. 

If you still can't resolve the issue, contact Microsoft Customer Service and Support. To contact support, navigate to the following URL and go to Exchange Server Support and click on Exchange Server 2016.

https://support.microsoft.com/en-us/supportforbusiness/productselection

Thank you!

**Comment by scanum** [comment]
@nramouche Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
