### ISSUE TITLE
No mention of Indentity

### ISSUE THREAD

**Issue by MattBarTCS** [MicrosoftDocs/OfficeDocs-Exchange#1084]
I was trying to update the URL as it was not showing the domain we wanted to show at the end.
However when typing Set-OrganizationRelationship -TargetOWAUrl http://cloudowa.contoso.com/owa I then was prompted for the Identity.  I didn't know this and had to search to find out more, which I used this site to help https://social.technet.microsoft.com/Forums/en-US/4e2da20f-0913-4e46-b678-60b337f63d18/owa-redirect-url-incorrect?forum=onlineservicesexchange and ran this command Get-OrganizationRelationship | FL Identity,TargetOwaUrl to then find the Identity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30c4fd6-0e69-cb9a-6a21-327f0ebae3a7
* Version Independent ID: d0217aa4-a37b-8837-4310-108fbf533a5d
* Content: [Simplify the Outlook Web App URL for Office 365 Hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/simplify-owa-url#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MattBarTCS, confirmed. The [Set-Organizationship](https://docs.microsoft.com/powershell/module/exchange/sharing-and-collaboration/set-organizationrelationship) cmdlet clearly requires the *Identity* parameter, so I updated the code example and surrounding text accordingly.

Thanks for the feedback.
