### ISSUE TITLE
Exchange 2013 is not available in any known version of this MA

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/OfficeDocs-Exchange#1085]
The text and image here describe/show Exchange 2013 as an option for configuring a GalSync MA.  But the only options available in the GalSync MA are "Exchange 2007" and "Exchange 2010".  This applies to FIM from 2010 R2 SP1 through MIM 2016 SP1 (current).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 541c99ee-7428-b9d0-dcbb-8226474ef39b
* Version Independent ID: 6695e0dd-3437-4dbc-c9cd-658a6b53323b
* Content: [Deploy Exchange 2013 in a cross-forest topology: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/deploy-exchange-2013-in-a-cross-forest-topology-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/deploy-exchange-2013-in-a-cross-forest-topology-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/deploy-exchange-2013-in-a-cross-forest-topology-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jordanmills Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @jordanmills, thank you for your feedback.

I don't have a FIM/MIM in my lab to check it. Do you have a screenshot? I think the dropdown menu shows 2007 and 2010. And you can use 2010 if you are deploying 2013.

**Comment by scanum** [comment]
@jordanmills  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
