### ISSUE TITLE
Incorrect PowerShell syntax

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/OfficeDocs-Exchange#1089]
For one of the exclusions, file path - %ExchangeInstallPath%Logging, the PowerShell cmdlet shows as 'Get-MailboxServer -Server &lt;ServerName&gt; | Format-List *LogPath* '.  The correct syntax is either without the -server in front of &lt;ServerName&gt; or use the -Identity parameter instead of -server.  Like so:

Get-MailboxServer &lt;ServerName&gt; | Format-List *LogPath* 
Get-MailboxServer -Identity &lt;ServerName&gt; | Format-List *LogPath* 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176e9cde-47cb-31b8-9ecf-51208888a740
* Version Independent ID: 97f0327a-5dba-d810-daeb-cd976b634c8b
* Content: [Running Windows antivirus software on Exchange servers](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/windows-antivirus-software?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by thmeyer-msft** [comment]
Hey damianscoles, 

your right, I fixed that issue! 

Best regards, 
Thomas

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
