### ISSUE TITLE
Exchange Online MX records

### ISSUE THREAD

**Issue by familiesr4ever** [MicrosoftDocs/OfficeDocs-Exchange#109]
We have Google Suite email for our domain that we use with Outlook.  I have one user who needed to be able to sync his Outlook email/contacts/calendar with his home PC and phone. I setup an Exchange Online account for the one user. However, it modified the MX records on our domain hosted by GoDaddy. I had to go back and update the MX record to point back to Google as the email stopped working for all of the other users. GoDaddy said you cannot have two Email providers as you only want one set of MX records for one email provider. Does anyone know of another solution?

**Comment by AndreaBarr** [comment]
@familiesr4ever  - thank you for submitting feedback. 

Having two MX records can cause some odd issues. Support should be able to help you find a solution for this one user that works for your situation. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
