### ISSUE TITLE
Limit recipients in the To: and Cc: field only

### ISSUE THREAD

**Issue by charliegriffith** [MicrosoftDocs/OfficeDocs-Exchange#1093]
Is there any way to limit the number of recipients in the To and Cc fields but leave the Bcc unrestricted. Most data breaches my organisation has experienced have been users sending email on mass without using the Bcc field. Limiting To and CC to around 5 recipients would avoid this. Is it currently possible? Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a512e6f-47ab-f785-a792-ef82a552c50f
* Version Independent ID: 16869db1-342d-13f2-ce24-0e13a49ec68d
* Content: [Message size limits in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/message-size-limits?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/message-size-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/message-size-limits.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@charliegriffith Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by thmeyer-msft** [comment]
Hi Charlie, 

you can limit the Number of Recipients via Set-Mailbox -RecipientsLimits Commandlet (see here for more information [Set-Mailbox](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps#parameters)

But i think this limits the bcc to. 

A second way would be, adjust a receive connector for that. But as this is mostly organization wide, this isn't recommended. It would also effect the bcc value. 

I think there is no appropiate way to just limit the to and cc fields. 

Hope this helps a bit, 

Best regards 
Thomas

**Comment by charliegriffith** [comment]
> Hi Charlie,
> 
> you can limit the Number of Recipients via Set-Mailbox -RecipientsLimits Commandlet (see here for more information [Set-Mailbox](https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailbox?view=exchange-ps#parameters)
> 
> But i think this limits the bcc to.
> 
> A second way would be, adjust a receive connector for that. But as this is mostly organization wide, this isn't recommended. It would also effect the bcc value.
> 
> I think there is no appropiate way to just limit the to and cc fields.
> 
> Hope this helps a bit,
> 
> Best regards
> Thomas

Thank you Thomas, It doesn't look like the functionality is there at the moment, but I do think it would limit data breaches if MS were to introduce the feature to limit the To and CC fields but leave BCC unlimited.

**Comment by scanum** [comment]
@charliegriffith Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
