### ISSUE TITLE
Step 5 backwards

### ISSUE THREAD

**Issue by emfi777** [MicrosoftDocs/OfficeDocs-Exchange#1096]
Hi,
After creating new public folders on step 4, I started the migration batch of step 5. After some hours I had to stop the syncing by suspending command. The reason to suspend it is that I have to change the hierarchy and to create more public folder mailboxes, that's why I want to go back to steps 3 and 4. The question is how to do it right on the middle of migration? Can I remove the migration batch and the public folder mailboxes on my exchange server 2016 and create a new set again without any troubles?

It will be nice to have a roll back plan on every step in this article

**Comment by scanum** [comment]
@emfi777 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
