### ISSUE TITLE
GCC Users

### ISSUE THREAD

**Issue by Ian566** [MicrosoftDocs/OfficeDocs-Exchange#11]
Will GCC (Gov Cloud) users eventually be able to configure turning on the "Restrict to GCC accounts" setting? As of now, we are unable to automatically push out managed profiles via Intune due to it defaulting to the public cloud. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 959f9d6d-c4a9-ad1e-51ef-2d949e90a103
* Version Independent ID: 0c6ee675-e3f1-81e8-0bb0-e274826f87eb
* Content: [Account setup in Outlook for iOS and Android using Basic authentication](https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/account-setup#feedback)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/account-setup.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/account-setup.md)
* Product: **exchange-server-itpro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by kenwith** [comment]
@Ian566 - I am not sure on this one and I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. They can prioritize and escalate the issue you are seeing with default to public cloud and hopefully work through a solution with you.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
