### ISSUE TITLE
Update order of commands for Step 7

### ISSUE THREAD

**Issue by DarkSylph** [MicrosoftDocs/OfficeDocs-Exchange#1102]
Step 7: Finalize the public folder migration (downtime required)

I recommend removing this section from Step 7:
If you've configured a hybrid deployment between your on-premises Exchange servers and Office 365, you need to run the following command in Exchange Online PowerShell after migration is complete:
Set-OrganizationConfig -RemotePublicFolderMailboxes $Null -PublicFoldersEnabled Local

If you follow the directions as is, you'll unlock public folders for everyone in the organization first before you actually get a chance to test with any users.

This section should be moved to Step 8: Test and unlock the public folder migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@DarkSylph Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msdmaguire** [comment]
@DarkSylph Thank you for the feedback. I checked with the product group and they strongly recommend that users test their public folders, which is the following step (as you point out). And in order to test the cmdlet 'Set-OrganizationConfig -RemotePublicFolderMailboxes $Null -PublicFoldersEnabled Local' is necessary. We will add a work item to look at the transition between steps 7 and 8 and triage according to priority.
