### ISSUE TITLE
Create a migration batch in Office 365 clarification

### ISSUE THREAD

**Issue by djxspike** [MicrosoftDocs/OfficeDocs-Exchange#1103]
Under "**Create a migration batch in Office 365**"...

It should be clarified that the "EmailAddress" field is the o365 subdomain you created. Because under this instance if you attempt to put the regular domain email address the migration will fail.

With that said - the "Username" field will be required since the "EmailAddress" field is always going to be different since it has to be the o365 sub-domain email.

I figured this out via trial and error during a recent migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by wrall** [comment]
Hi @djxspike,

Could you help provide a little more information about the error that you saw when you used your primary domain?  Was it a "user not found" or "couldn't use domain" type of error?

In the example, it is assumed that there is a user@fabrikaminc.net email address for each of the MailUsers and that fabrikaminc.net is registered as an Accepted Domain for your organization.  If that is not the case, then you are correct that you will need to use a the Username column.

Thanks
-Will

**Comment by djxspike** [comment]
Hey @wrall,

I sadly don't remember the EXACT error message, but when I had the "EmailAddress" field as user@fabrikaminc.net instead of user@o365.fabrikaminc.net I received an error message along the lines of "user not found".

When I configured my mail users - I was instructed to make the "User ID" field the o365.fabrikaminc.net domain (by 365 support) and the external address the gsuite.fabrikaminc.net domain

![image](https://user-images.githubusercontent.com/52464886/60544422-bbe0e500-9ce6-11e9-8433-4aa06dee14e1.png)

Was I wrong in using the o365 domain in the User ID field?

**Comment by wrall** [comment]
Hey @djxspike,

It should be alright to use the o365 domain there, as long as you add the regular (fabrikaminc.net) domain before you update your MX record.  I'll update the documentation to recommend using the regular domain, and mention that it should at least be one of the proxy addresses for the users if another one is chosen. 
 Thanks for your quick response, I think that this explains why that EmailAddress didn't work for you.

-Will

**Comment by djxspike** [comment]
Thanks @wrall,

So I COULD have used the fabrikaminc.net domain in the "User ID" field (instead of the o365.fabrikaminc.net domain)? And just put the o365.fabrikaminc.net as proxy domain in the mail user's SMTP settings? That would make more sense...

So far the client has been happy with their move to 365, it was just kinda frustrating that the documentation was vague at times. It all worked out though!

**Comment by scanum** [comment]
@djxspike Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
