### ISSUE TITLE
Wrong Link for Online Archive?

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-Exchange#1106]
The documentation states: 
"The procedures in this topic apply to on-premises archive mailboxes. For information about archive mailboxes in Exchange Online, see Archive mailboxes in Exchange Online."

The link provided goes to "Exchange Online Protection".  There's no mention on the EOP page about In-Place Archive and so far as I know Archive is not an EOP feature.

This is probably the desired target:
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a559595-95c7-efa0-7147-e98f07415d0c
* Version Independent ID: 1d1f5a33-6b66-fae5-17f9-a2b43eddf173
* Content: [Manage In-Place Archives in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/in-place-archiving/manage-archives?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/in-place-archiving/manage-archives.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/in-place-archiving/manage-archives.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@FC-EricWeller Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
I updated the link in the topic. It was a go.microsoft.com link (what we call a fwlink). I was able to update the target without modifying the topic.
