### ISSUE TITLE
Enable Modern Authentication from Microsoft 365 Admin Portal

### ISSUE THREAD

**Issue by rprechel** [MicrosoftDocs/OfficeDocs-Exchange#1107]
Modern authentication can be enabled from the **preview** version of the Microsoft 365 Admin Portal.  This is documented on https://docs.microsoft.com/en-us/office365/admin/security-and-compliance/set-up-multi-factor-authentication?view=o365-worldwide as follows:

1. To enable modern authentication, go to the admin center at https://admin.microsoft.com.
2. Choose **Settings** > **Services & add-ins** and then choose **Modern authentication** from the list.
3. Check the **Enable modern authentication** box in the **Modern authentication** panel.

**Comment by rprechel** [comment]
I meant for the above issue to be linked to the the following page:
https://docs.microsoft.com/en-US/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online

**Comment by scanum** [comment]
@rprechelThank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@rprechel Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by worldsdream** [comment]
If you like to do the steps with screenshots:

https://www.alitajran.com/enable-modern-authentication-in-office-365-admin-center/
