### ISSUE TITLE
Mail Delivery System Error

### ISSUE THREAD

**Issue by MMM-Oway** [MicrosoftDocs/OfficeDocs-Exchange#1108]

**Comment by MMM-Oway** [comment]
After mail migration completed from G Suite to Office 365, user receive mail delivery error when they receive email from others in G Suite.

The errors details are following.

Please, kindly help and troubleshoot me.
![oway](https://user-images.githubusercontent.com/52483224/60567981-8cd37d80-9d91-11e9-8ca6-5f9ad4f4ff9d.jpeg)

**Comment by scanum** [comment]
@MMM-Oway thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
