### ISSUE TITLE
Missing Link to post migration user support

### ISSUE THREAD

**Issue by sjohnof** [MicrosoftDocs/OfficeDocs-Exchange#1109]
Excellent page on migration planning and procedure. It would be nice to see a link to the post migration process on how to help users with a template on how to authenticate, how to download or upgrade to the new Office 365 applications etc.

Thank you
John O'Farrell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@sjohnof Thank you for submitting feedback and contributing to the docs we will consider adding this when updating the document.

**Comment by scanum** [comment]
@officedocsbot close
