### ISSUE TITLE
unexpected hyphen in example

### ISSUE THREAD

**Issue by jfrmilner** [MicrosoftDocs/OfficeDocs-Exchange#111]
There is a an unexpected hyphen in this example
New-OrganizationRelationship -Name "Fourth Coffee" -DomainNames "fourthcoffee.com" -FreeBusyAccessEnabled $true -FreeBusyAccessLevel **-**AvailabilityOnly -TargetAutodiscoverEpr "https://mail.fourthcoffee.com/autodiscover/autodiscover.svc/wssecurity" -TargetApplicationUri "mail.fourthcoffee.com"

This is how it should look
New-OrganizationRelationship -Name "Fourth Coffee" -DomainNames "fourthcoffee.com" -FreeBusyAccessEnabled $true -FreeBusyAccessLevel AvailabilityOnly -TargetAutodiscoverEpr "https://mail.fourthcoffee.com/autodiscover/autodiscover.svc/wssecurity" -TargetApplicationUri "mail.fourthcoffee.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e64e56f9-fbf4-f072-637b-5fa8e827a399
* Version Independent ID: 32a37550-af95-a0ce-2941-ff9ce7ba9150
* Content: [Create an organization relationship in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/create-an-organization-relationship)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@jfrmilner - Thank you for submitting this feedback.

Thank you for pointing this out to us. We will get this document updated so the hyphen issue is corrected 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
