### ISSUE TITLE
multi-org scenario

### ISSUE THREAD

**Issue by gnerd** [MicrosoftDocs/OfficeDocs-Exchange#1110]
Does the Modern Hybrid Agent support multiple Exchange orgs to a single tenant?

**Comment by scanum** [comment]
@gnerd thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
