### ISSUE TITLE
Mail User Provisiong with Azure AD-Connect

### ISSUE THREAD

**Issue by AymanFathi** [MicrosoftDocs/OfficeDocs-Exchange#1115]
As mentioned in the documentation to perform a G-suit migration you need to provision a mail user whether manually or by DirSync. In our case we don't have an Exchange server on-primes and we just synced the users to O365. 
How can I provision a mail-user using DirSync without having Exchange on-primes?
Based on my knowledge it is possible by editing the local active directory user objects attributes to set the ExternalEmailAddress attribute and so on, but it is not supported.

**Comment by scanum** [comment]
@AymanFathi thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
