### ISSUE TITLE
Need a version of this page for Exchange Online

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1116]
There is no content available for this topic for Exchange Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a23d81-8d94-43e8-ad8e-81f267563357
* Version Independent ID: 74331aa8-a175-0be6-46ae-de9be2c83d6a
* Content: [Limits for public folders](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/limits?view=exchserver-2019&viewFallbackFrom=exchonline-ww)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/limits.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
@danmyhre, whenever you think of "Exchange Online" and "limits", think "Exchange Online Service Description":

https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-storage-limits

https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-folder-limits
