### ISSUE TITLE
Feature and Licensing Matrix

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1117]
Please add a section that shows all features that are available with the free shared mailbox license and those that require licensing.  For example - email forwarding.  Some pages say this needs a license, but the option is there even for unlicensed shared mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488ecf85-5f6d-3abd-4253-8527b5082340
* Version Independent ID: ec414c0f-4ee4-bbd1-3851-3e4db0c97593
* Content: [Shared mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @danmyhre 

Thanks for reaching out! 

Please refer to the following article. It addresses shared mail box features very well. 

https://docs.microsoft.com/office365/admin/email/create-a-shared-mailbox?view=o365-worldwide

Please let us know if you have any queries. Thank you!

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
