### ISSUE TITLE
Little typo in the cml-let

### ISSUE THREAD

**Issue by copilft** [MicrosoftDocs/OfficeDocs-Exchange#1118]
Please change "RemoteServerIdentity" to just "RemoteServer", as per the output provided (tested in my lab as well), there seem to be a little typo in the command/parameter selected:

Get-MigrationEndpoint | Format-List Identity,RemoteServerIdentity

Identity : Hybrid Migration Endpoint - EWS (Default Web Site)
RemoteServer : 087f1c2e-8711-4176-ab4f-4b1c1777a350.resource.mailboxmigration.his.msappproxy.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid agent - Preview](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@copilft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
@copilft, I fixed it as you described. But in the future, you can also make fixes like this directly in the topics. For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.

Thanks for the feedback.
