### ISSUE TITLE
Typo error in code

### ISSUE THREAD

**Issue by AleBros** [MicrosoftDocs/OfficeDocs-Exchange#1119]
Get-CAS Mailbox &lt;identity&gt; | format-list
does not work because of a space between CAS and Mailbox

This should be
Get-CASMailbox &lt;identity&gt; | Format-List

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d4c4e1-6e23-c34e-0501-7bd3b63e8037
* Version Independent ID: 0ce6814a-c5ca-9c07-08c5-eaaa30af2b3b
* Content: [Configure POP3 and IMAP4 message retrieval format options: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/configure-pop3-and-imap4-message-retrieval-format-options-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/configure-pop3-and-imap4-message-retrieval-format-options-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-pop3-and-imap4-message-retrieval-format-options-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@AleBros, OK. I fixed it. But in the future, so can you. For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.

Thanks for the feedback.

**Comment by AleBros** [comment]
Good to know, thanks :)

Alessandro Bernardi
Responsabile ICT
[logo2005-88x32]

BBros s.r.l.
via Zucchini, 79 – 44122 Ferrara
Tel: +39 0532 52337 – Web: www.bbros.it
