### ISSUE TITLE
information about 2 steps verification is not clear

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/OfficeDocs-Exchange#113]
First the article says:
“Before Office 365 can connect to Gmail or G Suites, all the account owners need to create an app password to access their account. This is because Google considers Outlook to be a less secure app and will not allow a connection to it with a password alone. For instructions, see Prepare your G Suite account for connecting to Outlook and Office 365. You'll also need to make sure your G Suite users can turn on 2-step verification.”

Which is fine.

After which:
“Step 3: Create a list of Gmail mailboxes to migrate
For this task, you create a migration file that contains a list of Gmail mailboxes to migrate to Office 365. The easiest way to create the migration file is by using Excel, so we use Excel in these instructions. You can use Excel 2013, Excel 2010, or Excel 2007.
When you create the migration file, you need to know the password of each Gmail mailbox that you want to migrate. We're assuming you don't know the user passwords, so you'll probably need to assign temporary passwords (by resetting the passwords) to all mailboxes during the migration. You must be an administrator in G Suite to reset passwords.”

Here we talk about “password” rather than “app password”. And it makes sense because, as an admin, you can’t reset the app password of the users, this can only be done by themselves. To my understanding.

And finally, when we build the migration file, in the instructions we have first mentioned we use the “password” but then Column C is depicted as the “app password”:
“7. Next enter the email address, user name, and password for each mailbox you want to migrate. Enter one mailbox per row.
•	Column A is the email address of the Office 365 mailbox. This is what's shown in the User name column in Users &gt; Active users in the Office 365 admin center. 
•	Column B is the sign-in name for the user's Gmail mailbox—for example, alberta@contoso.com. 
•	Column C is the app password for the user's Gmail mailbox. Creating the app password is described in Migration from G Suite mailboxes using the Office 365 admin center.”

Inserting the app password in column C would imply that each user would provide that to the admin, which makes useless assigning a temporary password in the previous step.
Unless I am misunderstanding and with G-suite/Gmail an admin can reset the app password as well.

Can you please advise which should be the correct procedure and eventually update the article with the appropriate terms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate G Suite mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Addressed questions in internal email.

**Comment by Migmakers** [comment]
I am really confused about all this. 

**Quote from article:** 
"Unfortunately App Passwords are no longer available on Google account that are set to use Security Key only. Maybe time to update your software to a more modern API?"

I am getting ready for migration for my company +-20 folks. I have only remote access to my folks so the preparation is the key for me. 
1. Do I need to enable the MFA in my G suite for all accounts?
2. Do I need to make pst for each user before I start?
3. How do I verify MFA for each account without contacting each user / or how does it work

Any help would be greatly appreciated. 
Thank you

**Comment by varungupta19** [comment]
Can you please post what solution you provided to @teomonda? I have the same question, i cannot create app password for each gsuite user in my organisation. Is gsuite user account password enough for migration? or app password is mandatory?

**Comment by msdmaguire** [comment]
@varungupta19 Not sure how helpful this will be but here are the responses we sought from the product team:

Question: So, by that, shall I understand that the file will be composed out of those 2 fields? EmailAddress (required) and Username (optional).
Answer: The CSV in question here is no different from the CSV you would upload while doing IMAP migrations like before. https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/csv-files-for-imap-migrations 

Question: Using a service account will result in not needing the password field anymore? And thus, it also eliminates the app-password generation by the users?
Answer: Yes, by running as a super admin, this entity would have delegated access to all users and would eliminate the need to generate or reset passwords for all users.
