### ISSUE TITLE
Exchange 2016 CU13 Information missing

### ISSUE THREAD

**Issue by NishikigoiCH** [MicrosoftDocs/OfficeDocs-Exchange#1135]
Exchange 2016 CU13 Information missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8acf2480-928a-eb4e-0c9a-8526d97c2713
* Version Independent ID: bcf47ac1-4b6e-e333-1b25-354e4cf88e8a
* Content: [Active Directory schema changes in Exchange Server](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/active-directory/ad-schema-changes?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/active-directory/ad-schema-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/active-directory/ad-schema-changes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@NishikigoiCH Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
@NishikigoiCH, I was able to confirm that there were no AD changes in CU13.

Thanks for the feedback.
