### ISSUE TITLE
Meaning of "Supported"

### ISSUE THREAD

**Issue by jreinhardtiv4** [MicrosoftDocs/OfficeDocs-Exchange#1136]
I feel this page is unclear about what is meant by the statement "Not all authentication types are supported for all protocols." For the protocols that say "n/a" for all authentication types, what does n/a mean? Normally it means not applicable. But, that doesn't make sense here since a protocol has to use some kind of authentication mechanism. Is Microsoft saying that EWS, IMAP4, OAB, OutlookAnywhere, POP3, REST, and UniversalOutlook are all entirely not supported for client access rules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9cdf39f-da71-43ab-0ceb-a816bdc19d04
* Version Independent ID: 1fff6b28-f8d8-d9b3-1730-db2cac7835a0
* Content: [Client Access Rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jreinhardtiv4, I can see how that would be confusing. I eliminated the rows in the table that were all 'n/a'.

You can certainly use Client Access Rules to block or allow the protocols that are available in the AnyOfProtocols/ExceptIfAnyOfProtocols parameters (all of the values in the original table). But, with some protocols (those in the now shortened table), you can further block or allow based on the combination of protocol AND authentication type by also using the AnyOfAuthenticationTypes/ExceptIfAnyOfAuthenticationTypes parameters.

Does this make sense?

**Comment by jreinhardtiv4** [comment]
Thank you for the quick reply, Chris. Yes, I fully understand now and that was the answer I was hoping for. I'm having a problem with the rule for blocking UniversalOutlook, and was concerned that maybe it wasn't technically supported (with no AND configuration for the AnyOfAuthenticationTypes), but glad to see that it is supported.

**Comment by chrisda** [comment]
OK. Thanks. Closing the issue.
