### ISSUE TITLE
Fix the topic "Use the Exchange Management Shell to move public folder mailboxes from Exchange 2013 to Exchange 2019 or Exchange 2019"

### ISSUE THREAD

**Issue by douglasgaigher** [MicrosoftDocs/OfficeDocs-Exchange#1139]
Update it to "Use the Exchange Management Shell to move public folder mailboxes from Exchange 2013 to Exchange 2016 or Exchange 2019".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 807f3df7-bacb-925e-c699-ec76ceed7c16
* Version Independent ID: faa8e9c5-a218-adbb-9f57-8e91694a5eca
* Content: [Migrate public folders from Exchange 2013 to Exchange 2016 or Exchange 2019](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-from-exchange-2013?view=exchserver-2019#use-the-exchange-management-shell-to-move-public-folder-mailboxes-from-exchange-2013-to-exchange-2019-or-exchange-2019)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-from-exchange-2013.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-from-exchange-2013.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@douglasgaigher Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msdmaguire** [comment]
@douglasgaigher Thanks for catching that typo. It has been fixed and should publish live within a day.
