### ISSUE TITLE
Include FastTrack Option

### ISSUE THREAD

**Issue by tcfinney** [MicrosoftDocs/OfficeDocs-Exchange#114]
Hello,

Please consider including FastTrack as an option for customers to migrate email to Office 365:

https://docs.microsoft.com/en-us/fasttrack/data-migration

Thank you,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d88bea-98ed-5884-ba22-6343f1737caa
* Version Independent ID: 40de1e1c-a2c6-590d-375f-c860aa8524d1
* Content: [Ways to migrate multiple email accounts to Office 365](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/mailbox-migration?redirectSourcePath=%252fen-us%252farticle%252fWays-to-migrate-multiple-email-accounts-to-Office-365-0a4913fe-60fb-498f-9155-a86516418842#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/mailbox-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/mailbox-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@tcfinney thank you for engaging with the community here for the docs.

I have added this request to the exchange teams backlog. They are already looking into this. I will reply back when I have more information.
