### ISSUE TITLE
Adding a description about limitation to BlindCopyTo, AddToRecipients, and CopyTo

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/OfficeDocs-Exchange#1141]
### Problem

There is any information about the limitation that we cannot use **_Add recipients_** action with DistributionGroup. If we create a TransportRule which add a DG as a recipient, we have following error.

![err1](https://user-images.githubusercontent.com/6519947/60956249-61c2ce00-a33d-11e9-94a7-6155bba9ee74.png)

The limitation is applied only for Exchange Online. We can create a similar rule on on-prem Exchange server.

### Proposal

Adding the following text to descriptions about _BlindCopyTo_, _AddToRecipients_, and _CopyTo_.

```
You can't add a distribution group as a recipient.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d245fb-eb4b-879d-4da8-7e7be414a179
* Version Independent ID: a05b031b-db9a-6f28-09a3-68640eb9c570
* Content: [Mail flow rule actions in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rule-actions)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rule-actions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rule-actions.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hishikitetsuya, I updated the topic. Thanks for the feedback.
