### ISSUE TITLE
HAB dont sync data from exchange to outlook client

### ISSUE THREAD

**Issue by tonghien22890** [MicrosoftDocs/OfficeDocs-Exchange#1144]
I chose root of HAB is Security group from AD. But on the outlook client, it hadn't been change anything for 3 days. it was updated when I download OAB latest from Exchange. Can you explain it?
And does HAB only show the users who has mail box ?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1c6ced-4d52-df69-b492-8a6a47e793ec
* Version Independent ID: acb719f5-1828-d101-bf8f-af6f7fc03758
* Content: [Hierarchical address books in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/hierarchical-address-books/hierarchical-address-books#feedback)
* Content Source: [Exchange/ExchangeOnline/address-books/hierarchical-address-books/hierarchical-address-books.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/hierarchical-address-books/hierarchical-address-books.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@tonghien22890  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@tonghien22890 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
