### ISSUE TITLE
Missing hyphen

### ISSUE THREAD

**Issue by bcrownover** [MicrosoftDocs/OfficeDocs-Exchange#1145]
Where it says:
Set-TransportRule "Sender is a member of marketing" priority "2"
It should say:
Set-TransportRule "Sender is a member of marketing" -Priority "2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736d8598-4bde-5f1c-5eef-2f9b648912f6
* Version Independent ID: eb74141c-161c-d1db-e95c-032f3dfdf8ec
* Content: [Manage mail flow rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/manage-mail-flow-rules#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-mail-flow-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bcrownover, I fixed it. But in the future, so can you For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.

Thanks for the feedback.
