### ISSUE TITLE
copy and paste issue on your page

### ISSUE THREAD

**Issue by maciek01** [MicrosoftDocs/OfficeDocs-Exchange#1146]
Last section talks about creating inbound connector. But yet the summary of this section refers mistakenly to outbound connector:

To create the inbound connector from the email add-on service in Exchange Online PowerShell, use this syntax:

Copy
New-InboundConnector -Name "&lt;Descriptive Name&gt;" -SenderDomains * -ConnectorType OnPremises -RequireTls $true -RestrictDomainsToCertificate $true -TlsSenderCertificateName &lt;CertificateDomainName&gt; [-CloudServicesMailEnabled $true]

This example creates an outbound connector with these settings:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f44c94af-aa03-b648-7c87-6f77e9ada172
* Version Independent ID: 2608dfd4-92a4-1c8e-5675-26ce9f3423a2
* Content: [Scenario Integrate Office 365 with an email add-on service](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/integrate-office-365-with-an-email-add-on-service#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/integrate-office-365-with-an-email-add-on-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/integrate-office-365-with-an-email-add-on-service.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@maciek01, I fixed it. But in the future, so can you. For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.
Thanks for the feedback.
