### ISSUE TITLE
article is from 2016 and still refers to "new"

### ISSUE THREAD

**Issue by martinagrom** [MicrosoftDocs/OfficeDocs-Exchange#115]
are the known issues still present?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@martinagrom Thank you for this feedback

I'm not certain what you are referring to as known issues but support will be able to help you find the correct answers to this. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
