### ISSUE TITLE
Uninstall the Hybrid Agent Hung - Not Working

### ISSUE THREAD

**Issue by big24fan** [MicrosoftDocs/OfficeDocs-Exchange#1150]
This is not working for me 

Uninstall the Hybrid Agent
To uninstall the Hybrid Agent, re-run Hybrid Configuration wizard from the same computer you ran the installation on and select Classic Connectivity. Selecting classic connectivity uninstalls and unregisters the Hybrid Agent from the computer and Azure. After you unregister the Hybrid Agent, you can resume setup and configure hybrid in classic mode.

When I do this to try to use the classic connectivity, it appears to start the uninstall, then it never finishes. Anyone else have this issue? Please help.

**Comment by scanum** [comment]
@big24fan thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Trapulo** [comment]
same issue here. 24 hours running...
