### ISSUE TITLE
Screenshot for G Suite migration document (JP) is incorrect

### ISSUE THREAD

**Issue by toramaro2000** [MicrosoftDocs/OfficeDocs-Exchange#1156]
EN-US document seems to be fixed.
Please fix JA-JP doc as well (I got a query from our partner).

https://docs.microsoft.com/ja-jp/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-office-365
*domain name should be "o365.fabrikaminc.net", but "gmail.fabrikaminc.net"

**Comment by scanum** [comment]
@toramaro2000 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
This is updated already.

**Comment by scanum** [comment]
@toramaro2000 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
