### ISSUE TITLE
lets try to cover the basics here

### ISSUE THREAD

**Issue by billspeers** [MicrosoftDocs/OfficeDocs-Exchange#1159]
lets try to cover the basics here:

https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/default-retention-policy#feedback

Can you configure the default limits? 

how?

It should take 30 seconds to do this and be at the top of this article.

**Comment by scanum** [comment]
@billspeers Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @billspeers 

Thanks for reaching out!

If you are looking for how to configure the retention policies, please refer to the following articles. 

https://docs.microsoft.com/exchange/security-and-compliance/messaging-records-management/create-a-retention-policy

https://docs.microsoft.com/exchange/security-and-compliance/messaging-records-management/add-or-remove-retention-tags

https://docs.microsoft.com/exchange/security-and-compliance/messaging-records-management/apply-retention-policy

Hope this clarifies your query. Kindly confirm. Thank you!

**Comment by scanum** [comment]
@billspeers Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
