### ISSUE TITLE
The document looks out of date. I tried to follow the document dot to dot and keep getting quite a few errors to be able to list here.

### ISSUE THREAD

**Issue by vmoholkar** [MicrosoftDocs/OfficeDocs-Exchange#116]
e.g. for command - $dataDisk1=New-AzureRmDisk -DiskName adVM-DataDisk1 -Disk $diskConfig -ResourceGroupName $rgName
New-AzureRmDisk : SKU StandardLRS is not supported for resource type Disk in this region. Supported SKUs for this region are Premium_LRS,StandardSSD_LRS,Standard_LRS
ErrorCode: InvalidParameter
ErrorMessage: SKU StandardLRS is not supported for resource type Disk in this region. Supported SKUs for this region are Premium_LRS,StandardSSD_LRS,Standard_LRS
ErrorTarget: sku
StatusCode: 400
ReasonPhrase: Bad Request
--------------------------------------------------
for command 
 $vm=Add-AzureRmVMDataDisk -VM $vm -Name adVM-DataDisk1 -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 1
Add-AzureRmVMDataDisk : Cannot validate argument on parameter 'ManagedDiskId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:92
+ ... VM-DataDisk1 -CreateOption Attach -ManagedDiskId $dataDisk1.Id -Lun 1
+                                                      ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-AzureRmVMDataDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Compute.AddAzureVMDataDiskCommand

--------------------------------------------
PS C:\WINDOWS\system32&gt; New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm
WARNING: Since the VM is created using premium storage or managed disk, existing standard storage account, vivekstoragegroup, is used for boot diagnostics.
New-AzureRMVM : Error converting value "StandardLRS" to type 'System.Nullable`1[Microsoft.Azure.XStoreClientHelper.StorageAccountServiceClient.StorageAccountType]'. Path
'properties.storageProfile.osDisk.managedDisk.storageAccountType', line 19, position 45.
ErrorCode: BadRequest
ErrorMessage: Error converting value "StandardLRS" to type 'System.Nullable`1[Microsoft.Azure.XStoreClientHelper.StorageAccountServiceClient.StorageAccountType]'. Path
'properties.storageProfile.osDisk.managedDisk.storageAccountType', line 19, position 45.
ErrorTarget: vm.properties.storageProfile.osDisk.managedDisk.storageAccountType
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 74e66c52-6053-4b2c-a92b-2c0559d8e6d6
At line:1 char:1
+ New-AzureRMVM -ResourceGroupName $rgName -Location $locName -VM $vm
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand

--------------------------------------------------
Also, not getting why this is not provided in terms of the GUI facilities that are already there for creating all this resourcegroup, storage, VM, Virtual Netwrok and all. That would be much easier.
-------------------------------------------
Lastly, I even tried all this from Azure Portal creating- 
resourcegroup, storage, VM, Virtual Netwrok and all
Multiple attempts of start from scratch but still landed into 
DFSR 1202 
DNS Event ID 4013
etc. referred ms pages of help internet search.
But to no avail, just could not set up VMs given in the objective of this article. DS, AD, Exchange. Have already spent 2 days. 
Why this has to be so complex to just get the dev/test environment up and running?
Please update the doc or provide pointers to doc that is reliable.
Thanks,
Vivek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45c04a0-138f-8241-0726-01fb09c3dfeb
* Version Independent ID: 730303a8-9c6f-472c-79f6-96453dea3013
* Content: [Exchange 2016 dev/test environment in Azure](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by vmoholkar** [comment]
Further, unfortunately, this is the only page I end up landing on when searching for 'How to set up Exchange 2016 dev/test environment in Azure' on internet. Badly stuck! Help please!

**Comment by vmoholkar** [comment]
Even when I tried to get the adVM created from Azure Portal, main issues are
DFSR 1202
DNS Event ID 4013
So, when I create the exVM and try to make it join the domain (Add-Computer -DomainName "corp.contoso.com"
Restart-Computer)
, it simply can not find the domain because of the above errors.
Note: I am replacing all proper names in all the commands given, resource group, VM names, virtual network name, storage name, domain name etc.

**Comment by AndreaBarr** [comment]
@vmoholkar Thank you for this feedback

I want to make sure you get help the quickest way possible for installing this Exchange environment in Azure. Support will be able to handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by ardwork** [comment]
The error here should be corrected as it's been around for a long time... 
Wherever you see "StandardLRS" (including the quotes) change to Standard_LRS (without the quotes).
