### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by StuartHyslop** [MicrosoftDocs/OfficeDocs-Exchange#1162]
"Create or edit users" hyperlink is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 296cbb00-c2d3-1b29-fddd-545440f71103
* Version Independent ID: 39910e33-72e9-e281-bf9f-c7416db8746e
* Content: [Create user mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/create-user-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/create-user-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/create-user-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by scanum** [comment]
@StuartHyslop Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@StuartHyslop Thank you for your feedback, I'll have it sorted soonest.

**Comment by scanum** [comment]
@StuartHyslop We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by russrimm** [comment]
The link to Create or Edit users is still broken. It's under the heading "Use the Microsoft 365 admin center to create a new mailbox" and the bad link is https://go.microsoft.com/fwlink/p/?LinkId=276796.
