### ISSUE TITLE
Name cannot contain spaces

### ISSUE THREAD

**Issue by AzureGuineaPig** [MicrosoftDocs/OfficeDocs-Exchange#1164]
Suggest adding a note that the Name parameter cannot contain any spaces in it.  Something changed in the discovery mailbox provisioning process recently where previously the UPN of the mailbox was a random GUID value.  Now the UPN is populated with the explicit value of the Name parameter, which will cause issues if it contains spaces or other unsupported characters for UPNs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e680d2b-6886-fe74-c36c-7472b8e1e186
* Version Independent ID: 3d5ddf56-26f5-7c9d-5e56-30e8ac6c76c2
* Content: [Create a discovery mailbox](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/create-a-discovery-mailbox)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/create-a-discovery-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/create-a-discovery-mailbox.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@AzureGuineaPig  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@AzureGuineaPig Thank you for pointing this out and helping improve MS Docs.  Just for clarification, should I just add a note stipulating this? Or are you suggesting to remove a space from the name parameter in the document?

**Comment by markjjo** [comment]
@AzureGuineaPig Note about no spaces in value for Name parameter was added.
