### ISSUE TITLE
remove-hybridconfiguration is not working on Exchange 2010

### ISSUE THREAD

**Issue by bedo1976** [MicrosoftDocs/OfficeDocs-Exchange#1165]
With Exchange 2010 the command in the manual for remove-hybridconfiguration is not working. According this other article it is supportet with exchange 2013. I suggest that this information is added in your documentation:

https://blog.kloud.com.au/2014/05/05/removing-an-exchange-hybrid-configuration-2/

**Comment by scanum** [comment]
@bedo1976  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
