### ISSUE TITLE
Good information provided team.

### ISSUE THREAD

**Issue by meghabhushansingh** [MicrosoftDocs/OfficeDocs-Exchange#1166]
I would appreciate the effort you put-in to help the IT Community.
Though recently I followed the instructions mentioned in this guide and got the project completed without any hurdle 
Bitacube Lotus Notes to Office 365 migration - https://www.bitacube.com/lotus-notes-to-office-365-migration.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce990e27-aa35-1c80-2d57-c07df2d35e88
* Version Independent ID: 78594f8e-6f98-21bd-4c68-be4facfade3e
* Content: [Migrate from Lotus Notes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-from-lotus-notes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by daisysmith250** [comment]
Get Kernel Office 365 Migrator for Lotus Notes to easily migrate mailbox data from IBM Lotus Notes/ Domino Server to Office 365 and Exchange server with ease. Free version of the software is also available to download at- https://www.nucleustechnologies.com/lotus-notes-to-office365.html

**Comment by maxbeckham** [comment]
Great but if I talk about Lotus Notes to Office 365 Migration. According to my experience and knowledge, I suggest [Shoviv Lotus Notes to Office 365 Migration Tool](https://www.shoviv.com/lotus-notes-to-office365.html). You can first try this tool, its free trial version is available and it helps to properly test the tool and also convert the first 25 data items per folder.

**Comment by davidscott851** [comment]
I'm here to recommend you this lotus notes to office 365 converter software to convert all lotus notes files into office 365 without any loss of original data. With this tool you can instantly migrate lotus notes such as mails, contacts, calendars and tasks to office 365 effectively.  **Visit here:- https://www.emailsoftwares.com/lotus-notes-to-office-365-migration.html**
