### ISSUE TITLE
Scenario 1 - MX record points to third-party spam filtering needs more detail

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-Exchange#1167]
There are a number of considerations when MX points to third party, more than this article suggests. Needs more detail.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Exchange Online](https://docs.microsoft.com/en-gb/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud#scenario-1---mx-record-points-to-third-party-spam-filtering)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@aldoug  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by lindspea** [comment]
@aldoug Thank you for reaching out and helping improve MS Docs.  Is there anything specific you are referring to that needs to be added? If you have any helpful links, please forward them and I can have them added to the article.

**Comment by scanum** [comment]
@aldoug @ We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
