### ISSUE TITLE
when add my domain in o365 when perform G Suite Migration

### ISSUE THREAD

**Issue by cfones** [MicrosoftDocs/OfficeDocs-Exchange#1168]
Hi, It's not specified in this article when I need to configure myreal domain in O365, only says that I need to create the subdomain o365.mydomain.com. But when I will migrate the mailbox the principal alias is not the mydomain. I need to add the two domains in O365 before a single match migration?

Thanks

**Comment by wrall** [comment]
Hi @cfones,

You should configure your real domain (fabrikaminc.net, in the example) on the O365 side first, before configuring the o365.fabrikaminc.net subdomain or provisioning the MailUsers.

I'll update the document to mention that.

Thanks
-Will

**Comment by wrall** [comment]
Actually, it is mentioned in the introductory section:

> All of the procedures in this article assume that your Office 365 domain has already been verified and your TXT records have been set up. For more information see [Set up your domain (host-specific instructions)](https://docs.microsoft.com/office365/admin/get-help-with-domains/set-up-your-domain-host-specific-instructions).

**Comment by scanum** [comment]
@cfones Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
