### ISSUE TITLE
Updates to document

### ISSUE THREAD

**Issue by carterhctan** [MicrosoftDocs/OfficeDocs-Exchange#1169]
Should Microsoft update the document and remove the EOL Exchange Server versions like Exchange 2003 and 2007? 

Although minimal version is 2003, but as it has EOL a long time, we should remove it.

Feel that we can highlight that during the sync process, there will not be any existing downtime as the MX records are pointing to the On-Premises Exchange Servers. 

Customers are concerned with downtime and they plan it very carefully for any migration efforts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@carterhctan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
