### ISSUE TITLE
Deleting obsolete email addresses

### ISSUE THREAD

**Issue by gnr2bernstein** [MicrosoftDocs/OfficeDocs-Exchange#1175]
Doesn't have a solution for the mobile app. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40c92567-1479-8a19-9ee6-cc3563ed5bfc
* Version Independent ID: 313638dc-b9dc-9e58-50a9-b46245c8e35e
* Content: [Fix email delivery issues for error code 550 5.1.1 through 5.1.20 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online?redirectSourcePath=%252farticle%252f79e91ade-5c83-405b-a37d-d99c7d069b13#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@gnr2bernstein Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by tseward** [comment]
@gnr2bernstein which mobile app are you referring to? Outlook mobile?

**Comment by gnr2bernstein** [comment]
Yes. Outlook Mobile for Android

**Comment by mo7373** [comment]
Anniston Tmobile

**Comment by scanum** [comment]
@gnr2bernstein The team is currently updating docs and will reflect soon.

**Comment by mattpennathe3rd** [comment]
@scanum Is there a PR for this issue?
