### ISSUE TITLE
External email address

### ISSUE THREAD

**Issue by Stavros40cy** [MicrosoftDocs/OfficeDocs-Exchange#1176]
Hello,

I am trying to migrate G-Suite to Office 365 according to the instructions found in Microsoft' s website (https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration) but i have the following problem: 

Under the "Provision users in O365" paragraph i read that "Each user should have their ExternalEmailAddress point to the user in their G Suite routing domain ("will@gsuite.fabrikaminc.net"). The users should also have a proxy address that will be used for routing to their Office 365 routing domain (such as "will@o365.fabrikaminc.net").

How do i add an external email address and a proxy address in Office 365?

I have completed all the other steps (creating alias, sub-domains etc)

Thank you in  advance

**Comment by scanum** [comment]
@Stavros40cy  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@Stavros40cy 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
