### ISSUE TITLE
Missing \ in paths

### ISSUE THREAD

**Issue by Divmar** [MicrosoftDocs/OfficeDocs-Exchange#1177]
A lot of the paths on this document are missing a \ (back slash) after the second % symbol.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176e9cde-47cb-31b8-9ecf-51208888a740
* Version Independent ID: 97f0327a-5dba-d810-daeb-cd976b634c8b
* Content: [Running Windows antivirus software on Exchange servers](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/windows-antivirus-software?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
For the record, the %ExchangeInstallPath% variable includes the trailing backslash; most other variables don't.
