### ISSUE TITLE
Cohowine

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/OfficeDocs-Exchange#1179]
The domain name example used in the video goes to a 3rd party site. The site doesn't look harmful but you should change it to one of the usual dummy organisations Microsoft uses (e.g. contoso.com) to be on the safe side!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48c969ec-e02c-70b0-59ba-a4a868a522ce
* Version Independent ID: b01cc2c1-bb5b-b443-ecfb-77a45ae7a693
* Content: [Mail flow best practices for Exchange Online and Office 365 (overview)](https://docs.microsoft.com/en-gb/exchange/mail-flow-best-practices/mail-flow-best-practices)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/mail-flow-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/mail-flow-best-practices.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@thommck, I remember cohovineyard.com from MCSE certification tests. Apparently, cohowinery.com (not cohowineinc.com) is also a fictitious Microsoft company. Anyway, I just changed it to contoso.com.

Thanks for the feedback
