### ISSUE TITLE
It is not a real signature.

### ISSUE THREAD

**Issue by TheAnahaym** [MicrosoftDocs/OfficeDocs-Exchange#118]
It is added at the end of each email. Even I reply it appears under the whole email, but I need it only under my message. I think you have to change the name of the article having excluded "signatures" so as not to confuse the users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dbf1c4-0702-250e-2097-c5663dfad762
* Version Independent ID: 505fbbcd-2a0d-b7e7-6f5b-c88c2c66fdbc
* Content: [Organization-wide message disclaimers, signatures, footers, or headers in Office 365](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/disclaimers-signatures-footers-or-headers)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/disclaimers-signatures-footers-or-headers.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/disclaimers-signatures-footers-or-headers.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@TheAnahaym Thank you for this feedback

Thank you for the suggestion on the title change. I will get this over to the Exchange team and we will get this investigated and updated. 

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by alternativesurfer** [comment]
@andreabarr
Hi, any updates on this?

**Comment by AndreaBarr** [comment]
@alternativesurfer It looks like Chris did a pull request for this. Can you look and see if your question was answered in it.

**Comment by chrisda** [comment]
@TheAnahaym, @alternativesurfer, the title of the topic is "Organization-wide message disclaimers, signatures, footers, or headers in Office 365". I would interpret that to mean "Organization-wide message disclaimers, organization-wide signatures, organization-wide footers, or organization-wide headers in Office 365". Plus, it's on docs.microsoft.com, in the Exchange Online area, so it's meant for admins, not end-users.

I tweaked the Summary, and added a link to the end-user Outlook/OWA signatures topic.

**Comment by jgwinner** [comment]
We ran into this also. No one realizes the disclaimer is there.

Can we get an enhancement added to Exchange so that it correctly inserts it under the signature? I realize the Exchange team might say this is difficult, but the MIME content does parse out the attachment from the original, more or less. OR Outlook could add a special tag inside the MIME body.

Regardless ... a disclaimer at the bottom of reply after reply will never be read. Someone is going to lose a case in court because the judge can reasonably say "It wasn't there" even though it was. 

        == John ==

**Comment by Sushil12321** [comment]
@TheAnahaym @AndreaBarr I have applied organization-wide signatures through the exchange rule. 
 The problem is signature is coming at the bottom of every email, especially when you are forwarding or replying. Is there a way to place the signature after each message. ?

**Comment by ShaneZhengNZ** [comment]
@AndreaBarr @chrisda  I think it is a terrible issue that should be addressed.

I don't think anybody wants company-wide disclaimer to stack multiple times at the bottom of every email.

Look at this:
![email](https://user-images.githubusercontent.com/2180397/69841310-89520d00-12c3-11ea-9ee9-23cf96014e4c.jpg)
