### ISSUE TITLE
Update MFA section on  Retention tags and retention policies public article

### ISSUE THREAD

**Issue by JuanGasca** [MicrosoftDocs/OfficeDocs-Exchange#1180]
On Managed Folder Assistant section, we should clarify that the value of the MaxSendSize and MaxReceiveSize set on the mailbox will impact on MRM. 

MRM won't move items larger than these values. This is by design 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c69230a4-9eaa-16db-ef8c-5e099c93bc42
* Version Independent ID: 525d597e-07a0-5510-474c-7881934f97ee
* Content: [Retention tags and retention policies](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies#managed-folder-assistant)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-tags-and-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-tags-and-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@JuanGasca Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
@JuanGasca There is not MFA section on this article. I will assume that the section is related to MRM.

**Comment by j0rt3g4** [comment]
Adding information on PR #1512

**Comment by JaiLudhani88** [comment]
Is there any graph API for getting those deleted mails from the server, if user had deleted his/her mails from "deleted items" folder.

**Comment by scanum** [comment]
@JuanGasca Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
