### ISSUE TITLE
Not all errors are listed

### ISSUE THREAD

**Issue by slaFFik** [MicrosoftDocs/OfficeDocs-Exchange#1181]
For example, there is no "5.7.708 Service unavailable. Access denied, traffic not accepted from this IP" on this page.
And I'm pretty sure other errors are missing too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6d0e4-0ea5-f8a9-bf67-bf7cacc74b3e
* Version Independent ID: c72592d3-bfd1-ddf3-793f-dcc0374db074
* Content: [Email non-delivery reports in Exchange Online](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@slaFFik Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by aldoug** [comment]
Second for the above "Service unavailable. Access denied, traffic not accepted from this IP"

**Comment by aldoug** [comment]
Also missing 550 5.2.2 Submission quota exceeded, and the 10,000 message per day indicator too

**Comment by scanum** [comment]
@MK-Kamal Hi Mohamed, could you please follow up on this issue? Thanks!

**Comment by VladimirGluten47** [comment]
Also missing status code 550 5.0.350, which seems to be a "Error reported wasn't specific enough to determine exact nature of the problem" code.

**Comment by scanum** [comment]
@slaFFik Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
