### ISSUE TITLE
Step 5 - using (get-credential)

### ISSUE THREAD

**Issue by evandimsby** [MicrosoftDocs/OfficeDocs-Exchange#1182]
The article makes no mention about tenants that use MFA. Will the "get-credential" used in Step 5.1 be able to prompt for a multi-factor login?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019#step-5-start-the-migration-request)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@evandimsby Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by msdmaguire** [comment]
@evandimsby Checked with the product team and they say that instructions in ste 5.1 should work with MFA.

**Comment by evandimsby** [comment]
Started to run through this process today (17 Aug 2019), and @msdmaguire received bad information. The get-credential portion of Step 5.1 definitely does NOT call the MFA login and results in Access Denied.
