### ISSUE TITLE
Once user is migrated, cannot deliver email back into GMail

### ISSUE THREAD

**Issue by jbaroneCM** [MicrosoftDocs/OfficeDocs-Exchange#1183]
I've got through all the steps and migrated myself as a test case.  When I try to email from my account on 0365 back into my domain within GMail, I get an authentication issue.  Is there a more detailed article that shows the steps to allowing migrated users to continue to send "internal" emails and have them delivered to all users regardless of being still on GMail or migrated to O365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jbaroneCM Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
@officedocsbot assign @scanum

**Comment by msdmaguire** [comment]
@jbaroneCM Sorry to hear that the migration didn't go as expected for you. I checked with the product team and the best thing you can at this point is open a support ticket. Hopefully working with support, you can uncover the issue.

**Comment by jbaroneCM** [comment]
Unfortunately, I went that route before coming here.  No one is willing to assist since Microsoft and Google are blaming each other.

**Comment by msdmaguire** [comment]
@jbaroneCM is there any further info you can share to help the product team troubleshoot? Is there a link to the support ticket we could look at?
