### ISSUE TITLE
Database Availability Group Support

### ISSUE THREAD

**Issue by b1tbucket** [MicrosoftDocs/OfficeDocs-Exchange#1185]
Documentation requires update on whether DAG's are supported on-prem in hybrid configurations

**Comment by msdmaguire** [comment]
@b1tbucket Can you tell us which article you are looking at? Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by b1tbucket** [comment]
No mention of whether it is supported or not in:
https://docs.microsoft.com/en-us/exchange/exchange-hybrid
https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites

**Comment by msdmaguire** [comment]
@b1tbucket Okay, I am sending out inquiries to get the official stance on DAGs in hybrid and will update the docs accordingly (yes/no) when I have an answer.

**Comment by msdmaguire** [comment]
@b1tbucket Confirmed that DAGs are on-prem only, they do not stretch into the cloud, therefore no hybrid scenarios for DAGs.
