### ISSUE TITLE
Cannot install Tools on Windows 10 1809

### ISSUE THREAD

**Issue by joeykins82** [MicrosoftDocs/OfficeDocs-Exchange#1186]
I'm trying to upgrade my local installation of the tools from CU12 to CU13 and I'm getting the following error:
There was a problem accessing the registry on this computer. This may happen if the Remote Registry service isn't running. It may also indicate a network problem or that the TCP/IP Netbios Helper service isn't running.
Win10 1809 (latest CU & servicing stack). Services in question definitely running. Tried explicitly running from elevated cmd prompt in both interactive and unattended modes.

**Comment by scanum** [comment]
@joeykins82 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
