### ISSUE TITLE
Add a note on basic authentication

### ISSUE THREAD

**Issue by josuvil** [MicrosoftDocs/OfficeDocs-Exchange#1187]
Hello, excellent article. However, I would like to recommend that you add a note about basic authentication. As you know, basic authentication supports legacy client applications. However, basic authentication protocols as described here do not support modern authentication (SAML, MFA, etc) along with sign-on policies. Organizations interested in preventing brute force attacks or password sprays usually disable these legacy protocols. Of course, this would require the use of client apps that support modern authentication (See this: https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online). Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64383249-903c-6cc5-83e1-93e0eb8ba128
* Version Independent ID: d93c4ce8-4bf4-15d0-b3ba-3d3eb11ebb37
* Content: [POP3 and IMAP4](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@josuvil Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@josuvil Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
