### ISSUE TITLE
Apply global mail flow rule disclaimer to new email messages and replies. 

### ISSUE THREAD

**Issue by Steveb10** [MicrosoftDocs/OfficeDocs-Exchange#1189]
Hi all, I've applied a new rule to some of my users to test a global email signature box. The code works great to all new email sent out. I've got an exception on it now to find specific word for the signature NOT to collect on the bottom of the emails. The signature box was being collected with all new replies. So now, my signature box only appears on the bottom of the email once on not on any replies. Has anyone figured out how to show the signature box to new and replies? Hope this makes sense. Thank you!

**Comment by scanum** [comment]
@Steveb10 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
