### ISSUE TITLE
Recovery

### ISSUE THREAD

**Issue by trapps0460** [MicrosoftDocs/OfficeDocs-Exchange#119]
so i assume i would use a spare server to recover a failed server to?? do i install exchange server on the spare server ?? same organization ? same srver name and ip ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aabf145-551a-d7a9-d986-8b411f581d90
* Version Independent ID: 020deb0e-eaf8-dae7-5953-86717dc14e0f
* Content: [Recover an Exchange Server](https://docs.microsoft.com/en-us/exchange/high-availability/disaster-recovery/recover-exchange-servers)
* Content Source: [Exchange/ExchangeServer/high-availability/disaster-recovery/recover-exchange-servers.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/disaster-recovery/recover-exchange-servers.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@trapps0460 Thank you for this feedback

I want to get your questions answered quickly. Support will be able to handle this issue to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
