### ISSUE TITLE
Restoring a user in a hybrid scenario

### ISSUE THREAD

**Issue by ernelso** [MicrosoftDocs/OfficeDocs-Exchange#120]
This section doesn't appear to be the complete instructions... Step 3 refers to &lt;GUID from new target mailbox you've created&gt; and there are no steps that specify creating a new target mailbox prior to this step

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff7fa9f-2dec-34c3-e4b3-53614755499f
* Version Independent ID: 61e856b9-12fb-bdf6-0f49-0f6cc8b4b957
* Content: [Delete or restore user mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by AndreaBarr** [comment]
@ernelso Thank you for this feedback

We appreciate you pointing this out to us. I am getting this over to the Exchange team for investigation and update. 

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by FC-EricWeller** [comment]
So wouldn't it be better to not "close" this comment until the Exchange team has responded and updated?  'Cause I have the same question @ernelso did.

**Comment by AndreaBarr** [comment]
@ernelso My apologies I didn't actually mean to close it.

**Comment by chrisda** [comment]
@ernelso I added a new step about creating a target mailbox.

Thanks for the feedback.
