### ISSUE TITLE
G Suite legacy free edition

### ISSUE THREAD

**Issue by AzureGuineaPig** [MicrosoftDocs/OfficeDocs-Exchange#1202]
Is this IMAP migration supported where the source G Suite is legacy free edition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#overview-of-the-process)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@AzureGuineaPig Can you tell us the differences between that version and standard G Suite?

**Comment by AzureGuineaPig** [comment]
Prior to December 6, 2012, Google offered a free edition of G Suite—also known as the legacy free edition—that had a reduced set of business features. As of December 6, 2012, Google stopped offering the free edition to new customers. I would like confirmation that this migration scenario is supported with the legacy free edition.

**Comment by msdmaguire** [comment]
@AzureGuineaPig We never tested the process with this version of G Suite so we can't say one way or the other definitively. However the process should work as long as your tenant supports:
1.	REST APIs for Calendar and Contacts, and either the REST API or IMAP for Mail (Gmail)
2.	Delegated authentication using a service account (“G Suite Domain-Wide Delegation of Authority”)
I hope this helps with your question.

**Comment by scanum** [comment]
@AzureGuineaPig Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
