### ISSUE TITLE
Outlook app config on Android

### ISSUE THREAD

**Issue by msomershoe** [MicrosoftDocs/OfficeDocs-Exchange#1203]
I set up an app config for managed apps, targeting Outlook for iOS and Android.  I configured settings for the Focused Inbox and Default Signature, and the settings push to the iOS devices without issue, but do not affect Android.  Is that normal, or am I missing something?

Additionally, is there a key pair to turn off the 'Organize mail by thread' setting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by smithre4** [comment]
We currently do not support admin configuration for the "organize mail by thread" setting, but that is on our list.

Outlook for Android support is included in 3.0.112 and later which is rolling out this week.
