### ISSUE TITLE
Full Access and Private Items

### ISSUE THREAD

**Issue by ckssaas** [MicrosoftDocs/OfficeDocs-Exchange#1204]
Hello,

Please elaborate upon or correct the following paragraph: "Private items: When you grant Full Access permission to a mailbox, you can decide whether to allow the delegate to see private items (private meetings, appointments, contacts, or tasks) in the mailbox." 

How does one go about setting Full Access permission on a user mailbox while also restricting access to private items? This would be a great feature. I did not know this was possible. It seems like the document may actually referring to Delegate access (set-mailboxfolderpermission) rather than Full Access (set-mailboxPermission). Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/permissions#feedback)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@ckssaas Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solution PR #1245

**Comment by scanum** [comment]
@ckssaas Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by ckssaas** [comment]
@scanum Hi! Those screens make it very clear, thank you. In the sentence "Private items: When you grant Full Access permission to a mailbox, you can decide whether to allow the delegate to see private items (private meetings, appointments, contacts, or tasks) in the mailbox." You may want to change the phrase "grant Full Access permission" to "grant Delegate permission", as that would be more accurate. Otherwise this can be closed. Thanks
