### ISSUE TITLE
Scenario 1 - Clarity

### ISSUE THREAD

**Issue by daniluvsuall** [MicrosoftDocs/OfficeDocs-Exchange#1206]
There's no information about forward routing from the third party solution to O365. What host should be used to put into the third party solution so it can route traffic to O365? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@daniluvsuall Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solved with PR #1247

**Comment by scanum** [comment]
@daniluvsuall Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
