### ISSUE TITLE
Step 2 command

### ISSUE THREAD

**Issue by crazyukman** [MicrosoftDocs/OfficeDocs-Exchange#1209]
Hello,

The command in step 2 should be:  New-Mailbox -Name SearchResults -Discovery

The current format will lead to an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e680d2b-6886-fe74-c36c-7472b8e1e186
* Version Independent ID: 3d5ddf56-26f5-7c9d-5e56-30e8ac6c76c2
* Content: [Create a discovery mailbox](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/create-a-discovery-mailbox#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/create-a-discovery-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/create-a-discovery-mailbox.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@crazyukman Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@crazyukman Thanks for the heads up. The command in step 2 has been fixed.
