### ISSUE TITLE
No info on which permissions are required for an Exchange backup or restore.

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/OfficeDocs-Exchange#121]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95186047-1823-14de-7315-5609e2037d0d
* Version Independent ID: 226e94a4-37a7-a140-f40c-e065a68106ec
* Content: [Recipients Permissions](https://docs.microsoft.com/en-us/exchange/permissions/feature-permissions/recipient-permissions)
* Content Source: [Exchange/ExchangeServer/permissions/feature-permissions/recipient-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/permissions/feature-permissions/recipient-permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Thanks for the feedback. Backup and restore permissions are actually the same as "Mailbox recovery," which is listed in the permissions article. 
We'll make a note to update the entry to "Mailbox recovery / Backup and restore"
