### ISSUE TITLE
The steps should include updating the authconfig service to use the new certificate to support Teams interoperability. 

### ISSUE THREAD

**Issue by TheBluLion** [MicrosoftDocs/OfficeDocs-Exchange#1215]
The steps should include updating the authconfig service to use the new certificate to support Teams interoperability. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b3694c-16ed-97fb-1423-16d950922396
* Version Independent ID: fd8bf16d-7ed7-c0f9-3157-e11fc0653829
* Content: [Renew the federation certificate: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/renew-the-federation-certificate-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@TheBluLion Thank you for reaching out and helping improve MS Docs.  Are you suggesting adding an additional step about using the new certificate or which step would you recommend putting this under? Any help is appreciated.

**Comment by TheBluLion** [comment]
According to the customer I was working with, the certificate is updated automatically when using the GUI/wizard, but not when following this document.

IF possible, it might improve the documentation if we added using the GUI as an alternative, and updated the powershell steps to update the oauthconfig after the certificate is updated using powershell.

﻿ -﻿ --
Eu Nice Loh
Premier Field Engineer
Office: (314) 872 5916
EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com>
IM:euloh@microsoft.com
8AM-5PM CT
[Microsoft]
﻿
If you have any feedback about my work, please let either me or my manager Annele Richards know at Annele.Richards@microsoft.com<mailto:Annele.Richards@microsoft.com>

**Comment by lindspea** [comment]
> 
> According to the customer I was working with, the certificate is updated automatically when using the GUI/wizard, but not when following this document. IF possible, it might improve the documentation if we added using the GUI as an alternative, and updated the powershell steps to update the oauthconfig after the certificate is updated using powershell. ﻿ -﻿ -- Eu Nice Loh Premier Field Engineer Office: (314) 872 5916 EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com> IM:euloh@microsoft.com 8AM-5PM CT [Microsoft] ﻿ If you have any feedback about my work, please let either me or my manager Annele Richards know at Annele.Richards@microsoft.com<mailto:Annele.Richards@microsoft.com> From: Lindsay <notifications@github.com> Sent: Wednesday, August 14, 2019 7:56 AM To: MicrosoftDocs/OfficeDocs-Exchange <OfficeDocs-Exchange@noreply.github.com> Cc: Eu Nice Loh <EuNice.Loh@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [MicrosoftDocs/OfficeDocs-Exchange] The steps should include updating the authconfig service to use the new certificate to support Teams interoperability. (#1215) @TheBluLion<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTheBluLion&data=02%7C01%7Ceunice.loh%40microsoft.com%7Cc5a6a029321746d2e53f08d720b6bad0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637013841495370628&sdata=UDG0jy6ox9hMQEdJAgPs8ehf1OSCX1kwi53kZdG9EKo%3D&reserved=0> Thank you for reaching out and helping improve MS Docs. Are you suggesting adding an additional step about using the new certificate or which step would you recommend putting this under? Any help is appreciated. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Exchange%2Fissues%2F1215%3Femail_source%3Dnotifications%26email_token%3DAKAGJIX4HMF7NX7ASUUIH53QEP6FJA5CNFSM4IJNSSA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4IWNEY%23issuecomment-521234067&data=02%7C01%7Ceunice.loh%40microsoft.com%7Cc5a6a029321746d2e53f08d720b6bad0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637013841495370628&sdata=IvbKFTLakCgQ43ntsJ8ClT2EUOH6PPnuN6Rrq84Z6Qc%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKAGJITM2NAQSN7NCDIN76DQEP6FJANCNFSM4IJNSSAQ&data=02%7C01%7Ceunice.loh%40microsoft.com%7Cc5a6a029321746d2e53f08d720b6bad0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637013841495381018&sdata=%2BLvA5bA445lqlLR4dNfBOUkA7LO12oH0OsUa%2BJcpwGA%3D&reserved=0>.

Thank you. I'll get this over to the team for an update.

**Comment by lindspea** [comment]
@TheBluLion so just a note under "update a working federation" as such:
"The Graphic User Interface/wizard can be used as an alternative to update the Teams certificate automatically." ?

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@TheBluLion Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
