### ISSUE TITLE
Wrong object versions for Configuration naming context

### ISSUE THREAD

**Issue by Sankledar** [MicrosoftDocs/OfficeDocs-Exchange#1216]
It seems that objectVersions in the table for Configuration naming context should be the following:
Exchange 2013 CU23:           16133
Exchange 2013 CU22:           16131
Exchange 2013 CU10-CU21: 16130
https://eightwone.com/references/schema-versions/
At least I`v got 16133 value of objectVersion property in CN=&lt;your organization&gt;, CN=Microsoft Exchange, CN=Services, CN=Configuration, DC=&lt;domain&gt; after running powershell scripts for CU23 installation package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7106ac-5b15-dd6b-6fa5-928424c8a8d0
* Version Independent ID: 0ef3622f-d421-f582-c617-96f38f177a33
* Content: [Prepare Active Directory and domains: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/prepare-active-directory-and-domains-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/prepare-active-directory-and-domains-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/prepare-active-directory-and-domains-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Sankledar  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Sankledar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
