### ISSUE TITLE
Load Balance in EX19

### ISSUE THREAD

**Issue by kgazar** [MicrosoftDocs/OfficeDocs-Exchange#1220]
I am working on a project for upgrade from Exchange 2013 to Exchange 2019.

For load balancing requirement, is it possible to use DNS round robin? or its a must in EX19 to use Hardware Load balancer?

**Comment by scanum** [comment]
@kgazar thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
