### ISSUE TITLE
Step 4 - How do you know this task worked?

### ISSUE THREAD

**Issue by cafigu** [MicrosoftDocs/OfficeDocs-Exchange#1221]
Should be:
Dir C:\ExchangeVolumes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889ca8e3-f105-a5fa-edf5-f456fdb98528
* Version Independent ID: fa988ca1-0e3d-6ace-e547-3f5cb3e60932
* Content: [Configure AutoReseed for a database availability group: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/configure-autoreseed-for-a-database-availability-group-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/configure-autoreseed-for-a-database-availability-group-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-autoreseed-for-a-database-availability-group-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@cafigu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@msdmaguire please can you confirm if I can make this change?

**Comment by msdmaguire** [comment]
Yes, please make the change.
