### ISSUE TITLE
Domain joined

### ISSUE THREAD

**Issue by FrankPlawetzki** [MicrosoftDocs/OfficeDocs-Exchange#1222]
There is the info: "Installing the Edge Transport server role on domain-joined computers only enables domain management of Windows features and settings. Edge Transport servers don't directly access Active Directory. Instead, they use Active Directory Lightweight Directory Services (AD LDS) to store configuration and recipient information"

It should be noted, that when Edge is run domain-joined, a user from that domain needs to be used to run EMS. If a local user is used when logging into Edge, CmdLets in the EMS result in "Access Denied". Verified using Exchange 2016 CU12

**Comment by scanum** [comment]
@FrankPlawetzki Could you please reference the document you are referring to? Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@FrankPlawetzki Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by FrankPlawetzki** [comment]
> @FrankPlawetzki Could you please reference the document you are referring to? Thanks!

https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deploy-new-installations/install-edge-transport-role?view=exchserver-2016

**Comment by lindspea** [comment]
@FrankPlawetzki Thank you for pointing this out.  I'll investigate and have the necessary changes added.

**Comment by lindspea** [comment]
@chrisda just to confirm this information is correct and I can do PR?

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@FrankPlawetzki Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
