### ISSUE TITLE
Step 3 is wrong

### ISSUE THREAD

**Issue by benoitboudeville75** [MicrosoftDocs/OfficeDocs-Exchange#1223]
If you do this you'll change the msExchRecipientDisplayType on ALL KIND of Remote Mailboxes - you should use -RecipientTypeDetails RemoteUserMailbox to avoid breaking the attribute on other types of Remote Mailboxes (e.g. RemoteRoomMailbox, RemoteSharedMailbox, etc).

Also the New/Enable/Set-RemoteMailbox cmdlet support the -ACLableSyncedObjectEnabled parameter in latest versions of Exchange 2013 and beyond.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@benoitboudeville75 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@benoitboudeville75 Thank you for reaching out and helping improve MS Docs. Are you suggesting two changes to the article? Please specify under which headings you recommend the changes.

**Comment by scanum** [comment]
@benoitboudeville75 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
