### ISSUE TITLE
This is either old or wrong.

### ISSUE THREAD

**Issue by dimforest** [MicrosoftDocs/OfficeDocs-Exchange#1224]
Now when you follow these steps you are met with a message stating "Mail domains are displayed below. To correctly add domains, use the Office 365 portal." ... ok, so where in the O365 portal? I was able to find Domains, but that is for domain I currently own. I need this for a Nutanix SMTP relay. I found another "Mail Flow" section in security and compliance but that has nothing for Authoritative Domains.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bf5c21-fd13-6458-96f1-22916748c1bf
* Version Independent ID: c9d62060-d249-9c5c-ca37-10f74175b77e
* Content: [Procedures for accepted domains in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/accepted-domains/accepted-domain-procedures?view=exchserver-2019&viewFallbackFrom=exchonline-ww#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/accepted-domains/accepted-domain-procedures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/accepted-domains/accepted-domain-procedures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@dimforest are you running the EAC in Exchange Online (part of Office 365) or in an on-premises server like Exchange 2016? If you're in Exchange Online, the message is correct, and here's the Exchange Online equivalent topic [Accepted domains in Exchange Online](https://docs.microsoft.com/Exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains).

If you're in on-premises Exchange, ignore the message;; you're in the right place.

**Comment by dimforest** [comment]
I'm using Exchange Online via 365. Following the link you provided, it says the same thing.. EAC > Mailflow. I get the same message I posted above, unfortunately.

**Comment by chrisda** [comment]
Sure. But at the very top of the Exchange Online topic, there's a link to [Add a domain to Office 365](https://docs.microsoft.com/office365/admin/setup/add-domain). That's what you want.

All you can do in the EAC in Exchange Online for accepted domains is look at the **existing** ones you've already added in the Office 365 portal, or change the Type from Authoritative to Internal Relay or vice-versa for **existing** domains. You can't add or remove existing domains in the EAC (but you can in on-premises Exchange).

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@dimforest Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
