### ISSUE TITLE
Exchange 2016 CU 13 not listed in Applies To Section

### ISSUE THREAD

**Issue by planrharman** [MicrosoftDocs/OfficeDocs-Exchange#1226]
Exchange 2016 CU 13 install points to this page, but this page does not indicate 2016 is applicable here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b95823d-417b-e774-e1ff-3e143e74a806
* Version Independent ID: 90bac39a-9a57-943d-7939-e73c6d042b14
* Content: [IIS 6 Compatibility components not installed](https://docs.microsoft.com/en-us/exchange/iis-6-compatibility-components-not-installed-longhorniis6metabasenotinstalled-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/iis-6-compatibility-components-not-installed-longhorniis6metabasenotinstalled-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/iis-6-compatibility-components-not-installed-longhorniis6metabasenotinstalled-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@planrharman  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @planrharman, thank you for your feedback.

Could you please put here the Exchange 2016 CU 13 install page?

**Comment by planrharman** [comment]
@dariomws306 I'm not sure what you mean? The page this issue links to is https://docs.microsoft.com/en-us/exchange/iis-6-compatibility-components-not-installed-longhorniis6metabasenotinstalled-exchange-2013-help

When attempting to install the management tools on a new Windows 10 1903 install I received an error regarding IIS 6 Metabase compatibility components not being installed, which had a link to that article. However, that article states it is only applicable to Exchange 2013.

**Comment by dariomws306** [comment]
Ok, I undertand now. Did you try to install this component following the steps in the article?

If it doesn't work i should kindly recommend that you to open a support ticket. We are here to help with docs issues. 

Thanks!

**Comment by planrharman** [comment]
The issue I'm raising here is about the documentation, not about my installation problems. In the top of the documentation it says that the article only applies to Exchange 2013, not to Exchange 2016. The doc just needs to be updated to say it also applies to 2016 since the error in 2016 points to the same page.

**Comment by scanum** [comment]
@planrharman  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
