### ISSUE TITLE
MRM clears deleted items before they expire

### ISSUE THREAD

**Issue by fdari** [MicrosoftDocs/OfficeDocs-Exchange#1228]
Retention action "delete after 30 days" for deleted items with no other tags applied to any folders does not work as described for my 2016 mailbox. After I applied the policy, it lets my folder grow for a while and then removes everything. According to the description, in this scenario, everything should be stamped with the current date only after arriving in the deleted items folder. Messages that were neither 30 days old or deleted 30 days ago are deleted. To confirm this, I restored an item that was deleted 1. aug. at midnight (not manually), and found that it had been received 29. jul. and could not possibly have passed any 30 day threshold (at this time it has existed for two weeks total). I have verified the policy tag situation by right clicking the crucial folders in outlook: Inbox shows no policy, deleted items shows the retention policy tag name (not the policy name). The tag by this name has these properties:
RetentionEnabled: True
RetentionAction: DeleteAndAllowRecovery
AgeLimitForRetention: 30.00:00:00

**Comment by scanum** [comment]
@fdari Could you please link the document you are referring to? Thanks.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by fdari** [comment]
https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mrm/retention-age?view=exchserver-2016
(Inbox: None; Deleted Items: Delete in 30 days; "The item is expired on 3/27/2016, which is 30 days after the user deleted or moved it to the Deleted Items folder.")

**Comment by dariomws306** [comment]
@fdari Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by fdari** [comment]
That looks specific to Office 365. Does it apply to Exchange 2016 on-premises as well?

**Comment by scanum** [comment]
@fdari Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by fdari** [comment]
Hi. Assuming that the documentation is correct, a bug exists. I have not been able to submit the support request because of the 500$ cost. We might explore, guess at causes and attempt workarounds. (Most common cause of bugs: Features that only work correctly if the Exchange service runs in en-US compatible regional settings.) I have also tried to find an Exchange-specific uservoice or similar destination for requests and reports, but find nothing but instructions to open support tickets (leading right back to the 500$).
