### ISSUE TITLE
Notes (ipm.StickyNote)

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-Exchange#1229]
Notes don't seem to be included here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ab11acd-45eb-7548-063b-a18fc59440f3
* Version Independent ID: 4d8ee4e9-7142-02e2-a58c-8a3aa6916213
* Content: [How retention age is calculated in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mrm/retention-age?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mrm/retention-age.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mrm/retention-age.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@FC-EricWeller  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by scanum** [comment]
@FC-EricWeller Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
