### ISSUE TITLE
Detailed Steps

### ISSUE THREAD

**Issue by aizatharis** [MicrosoftDocs/OfficeDocs-Exchange#123]
Would be great if there is a detailed guide to install CU. i.e Put servers in maintenance mode, activate databases to other DAG member, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d97c4a4-4693-0248-eb53-081673d56dd2
* Version Independent ID: 39f69140-d3f9-3243-c2d6-946082a13bed
* Content: [Upgrade Exchange 2016 to the latest cumulative update](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/install-cumulative-updates#install-the-exchange-2016-cumulative-update-or-service-pack)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/install-cumulative-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/install-cumulative-updates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@aizatharis Thank you for this feedback

I agree that a detailed guide should be included with this article. 

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by justadakaje** [comment]
Any updates on this request? I could really use an in-depth guide for this process.

**Comment by AimarL** [comment]
Hello. It would be really nice if You add edge server part also to this guide. I have sometimes troubles getting these servers to sync with the mailbox server after CU update. So it would be great if You add also some test examples to confirm that all is up and running.
