### ISSUE TITLE
Verify Prerequisites .NET

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-Exchange#1233]
This doc states .NET Framework 4.7.1 is required but [this link](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016) states 4.7.2 (or 4.8) is required if running CU13 . Please verify which is correct and update accordingly or maybe reference the other article?

**Comment by scanum** [comment]
@JonesMikael  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @JonesMikael, thank you for your feedback.

I cannot see the link, could you please put it here?

Thanks!

**Comment by scanum** [comment]
@JonesMikael  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by JonesMikael** [comment]
Sorry for late reply. The link is inline in the first comment but here it is in clear text: https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016

**Comment by dariomws306** [comment]
Hi @JonesMikael, don't worry.

Both are the same article (Exchange 2016 System Requirements).

CU13 requires 4.7.2 or 4.8, it looks good. Maybe you are talking about this article and both have the same table:
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#microsoft-net-framework

Thanks!

**Comment by JonesMikael** [comment]
Maybe we're not looking at the same articles.

**Exchange Server 2016 prerequisites:**
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prerequisites?view=exchserver-2016
States .NET Framework **4.7.1** should be installed

**Exchange Server 2016 system requirements:**
https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016
States .NET Framework **4.7.2 or 4.8** is supported for the current CU and says 4.7.1 is NOT supported.

**Comment by dariomws306** [comment]
Ok, I will update prerequisites article. Thanks!
