### ISSUE TITLE
G Suite Migration

### ISSUE THREAD

**Issue by soeminnwin** [MicrosoftDocs/OfficeDocs-Exchange#1235]
https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration

Hi, 

When perform a g suite migration from gmail to office 365, do I need to assign license to mailuser first?

**Comment by wrall** [comment]
Hi @soeminnwin,

No.  The license can be applied later in the migration process, or after the migration has completed if the migration period is short.
