### ISSUE TITLE
Updating Outlook Email Address Post-Migration

### ISSUE THREAD

**Issue by MattAlex151** [MicrosoftDocs/OfficeDocs-Exchange#1237]
During migration users signed in to Microsoft Outlook with their standard @domain.com email address and were given a sender address of @o365.domain.com. Now that migration is complete, MX records changed, etc. I want their Outlook accounts to point directly to @domain.com, not the subdomain. Re-adding the account gives a "This account is already added" message. I've already updated their primarysmtpaddress to @domain.com, as well as their targetAddress, so there is no trace of o365.domain.com left in the system except for these Outlook accounts. Is this something that will rectify itself in a few hours or am I missing a step? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@MattAlex151 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
