### ISSUE TITLE
When to assign O365 Exchange License?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#1241]
I follow this document and it is pretty good. However, it doesn't state at what point in the migration is best to assign the O365 Exchange license to the user?  Should that be done before the migration starts? Or while in process? Or after?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35bd8438-69fb-3da3-1c75-25576fc92fd4
* Version Independent ID: 4dd5a61d-ef30-f893-00c7-bdb9132e074d
* Content: [Move mailboxes between on-premises and Exchange Online organizations in hybrid deployments](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/move-mailboxes)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by rhymeswithmogul** [comment]
I saw a Microsoft employee posted this in Microsoft Answers:  "Usually, when assigning Exchange online license to an On-premise mailbox, an online mailbox will not be created.  It is not recommended that admins assign licenses to On-premise users before migration."  Hope this helps.

**Comment by Canis-Lupis** [comment]
Thanks for posting that. It is helpful, but still unclear.  So I don't assign licenses before migration but do I assign licenses during the migration?  Or after I get the email that the mailboxes have successfully migrated?  This might sound like splitting hairs to you but we've had some problems with our migration and I want to be clear on the proper technique.
________________________________

**Comment by rhymeswithmogul** [comment]
I'm doing a migration right now, actually.  I assigned Exchange Online licenses after running Azure AD Connect, but before starting mailbox migrations in the Exchange Admin Center.  As long as identical users exist on-premises and in Azure AD, it looks like duplicate mailboxes will not be created.

Hopefully this helps.  An official response from Microsoft would be best.

**Comment by lindspea** [comment]
@Canis-Lupis @rhymeswithmogul thank you for reaching out. I'm investigating to get an official answer for you.

**Comment by Canis-Lupis** [comment]
Thanks, lindspea!  That's exactly what I needed to know.

**Comment by Rowdy-1** [comment]
We have been using online services such as SharePoint and Teams for months now. Our users were assigned licenses that included EXO because we knew we would be migrating Exchange to the cloud. We are ready to migrate. Do we need to remove the user license before the migration and then add it back after the migration? We are using Azure AD Connect and it has been syncing properly. Thanks for any advice.

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
