### ISSUE TITLE
How do changes to an item affect the calculation

### ISSUE THREAD

**Issue by GreggRevak** [MicrosoftDocs/OfficeDocs-Exchange#1243]
What if I change an email item by editing the subject or deleting an attachment. How does this change affect the calculation of the retention age?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ab11acd-45eb-7548-063b-a18fc59440f3
* Version Independent ID: 4d8ee4e9-7142-02e2-a58c-8a3aa6916213
* Content: [How retention age is calculated in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mrm/retention-age?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mrm/retention-age.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mrm/retention-age.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
@GreggRevak Thank you for reaching out and helping improve MS Docs.  In this instance are you forwarding the e-mail to someone else, or just saving as a draft?

**Comment by GreggRevak** [comment]
Resaving in my inbox or other folder.

________________________________

**Comment by lindspea** [comment]
@GreggRevak it is calculated based on the date the email was received. So if you receive an email, edit it, and save it in a folder, the date it was received would apply. If it's a new email created and then edited, it is based on the date of creation. Hope this helps.

**Comment by scanum** [comment]
@GreggRevak Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
