### ISSUE TITLE
Room list need better documentation

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/OfficeDocs-Exchange#1244]
In the most recent versions of outlook you can not use the room finder if you do not have a room list. However this document poorly explains how to USE this beyond some abstract PowerShell command. See https://docs.microsoft.com/en-us/exchange/troubleshoot/meetings/conference-rooms-not-dispalyed 

In that article the syntax to add members to the group with $Member does not work with the O365 Exchange online. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1598a231-d154-1c94-d8aa-76084b45ed35
* Version Independent ID: 3cc7eb58-d64e-73f2-8566-f97ec30ac15e
* Content: [Create and manage room mailboxes](https://docs.microsoft.com/en-us/Exchange/recipients/room-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/recipients/room-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/room-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
@blouwagie Thank you for pointing this out and helping improve MS Docs. For more clarity, which article are you suggesting for improvements? The one referenced here or the one you mention in your comments (Room Finder in Outlook doesn't display any conference rooms when a user creates a meeting)? Please have look at these articles about room finders and room lists - https://blogs.technet.microsoft.com/educloud/2011/11/06/get-a-room-enable-room-finder-with-room-list-distribution-groups/ and https://support.microsoft.com/help/2811855/outlook-2010-room-finder-does-not-show-any-conference-rooms

**Comment by scanum** [comment]
@blouwagie We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by SnazzySnail8** [comment]
Can I ask to reopen this request?
I am wondering if for each Powershell step if you could better explain which text needs to be replaced with your own customized language and what that language is. I assume it is the blue-colored text in Powershell but, for example, what do I need to put in place of "RecipientTypeDetails"? It is unclear.
