### ISSUE TITLE
Simple typo

### ISSUE THREAD

**Issue by bkw27** [MicrosoftDocs/OfficeDocs-Exchange#1248]
Hi, There is a typo in section 4 of 'Prerequisite-steps-on-the-legacy-exchange-server' 
https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#prerequisite-steps-on-the-legacy-exchange-server

Current text "(Note that this step is only necessary if you are re-attempting a migration that failed perviously.)"
The last word should be "previously"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#prerequisite-steps-on-the-legacy-exchange-server)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@bkw27 Thanks for catching that. I have updated the article to fix this typo.
