### ISSUE TITLE
Internal document links 

### ISSUE THREAD

**Issue by ciscokeithgood** [MicrosoftDocs/OfficeDocs-Exchange#1251]
Any guidance on how to expose document links (inside documents) for updating

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer G Suite mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@ciscokeithgood Can you clarify some things? Not sure what you mean by "expose document links inside documents" and "for updating." For updating what, exactly? What do links inside documents have to do with migrating Gmail?

**Comment by ciscokeithgood** [comment]
Ah … perhaps I am in the wrong channel..?
My question relates to gsuite … where we want to move docs from an acquired companies gdrive to office365/sharepoint. There was concern around links that would be lost in the gdocs that are being migrated as they would link to other gdocs. It would be helpful to have a report on the links and their count that would no longer work. A report may allow them to be addressed manually in the source files

**Comment by msdmaguire** [comment]
@ciscokeithgood Yes, this article is only about moving Gmail. We have another article about GSuite migration, which includes mail, calendar, and contacts info, but not about migrating documents to SharePoint. We'd recommend this article to get started: https://docs.microsoft.com/en-us/sharepointmigration/migrate-to-sharepoint-online.

If that doesn't give you the info you need, we recommend opening a service ticket in your tenant so this can get resolved.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
