### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by longhairsinner** [MicrosoftDocs/OfficeDocs-Exchange#1253]
There's a typo in this command "Get-ServerHealth mailbox1.contoso.com | ?{$_.HealtSetName -like "ActiveSync*"}". It should be "Get-ServerHealth mailbox1.contoso.com | ?{$_.HealthSetName -like "ActiveSync*"}"

Also the title of many of the code blocks is "powewrshell" instead of "PowerShell"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87375366-5dd5-f352-5074-3a136aa383f4
* Version Independent ID: 47f44c3c-f192-0910-d0a6-295123aeaa55
* Content: [Troubleshooting ActiveSync Health Set](https://docs.microsoft.com/en-us/exchange/management/health/troubleshooting-activesync-health-set#feedback)
* Content Source: [Exchange/ExchangeServer2013/management/health/troubleshooting-activesync-health-set.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/management/health/troubleshooting-activesync-health-set.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@longhairsinner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
