### ISSUE TITLE
SenderID link in second last section is broken

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Exchange#1254]
The link is for https://go.microsoft.com/fwlink/p/?linkid=50977
It tries to redirect to http://www.openspf.org/SPF_Record_Syntax ... Which fails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f279ff39-e566-aab1-c962-338cdc9795a6
* Version Independent ID: a8cc2b9f-bd31-d81e-53bd-ccf668f506a6
* Content: [Sender ID: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/sender-id-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/sender-id-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/sender-id-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
@GLComputing Thank you for pointing this out and helping improve MS Docs.  I'm investigating to find the correct link to have it added to the document.

**Comment by GLComputing** [comment]
It's worse, now ... The original link is broken

**Comment by scanum** [comment]
@msdmaguire Following up on this request. Thanks!

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by mattpennathe3rd** [comment]
Closing this as fixed.
