### ISSUE TITLE
Some commands don't work

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#1255]
Trying to run these command from Exchange 2013 CU21 Management Shell but they are not working.  Problem is the commands that utilize "Get-Aduser" commands aren't recognized in the management shell.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@Canis-Lupis thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Canis-Lupis** [comment]
Figured  out that the issue here is that you don't need to run the Get-ADuser command from the exchange management shell as indicated, unless you've installed the AD modules on the server running the exchange management shell.  This is probably a "well, duh!" moment for veteran Exchange admins out there but I'm new to Exchange on prem and I tend to follow directions exactly, thus the problem.

Perhaps to avoid confusion for others, indicate in step 1 that the AD module must be installed for Get-AdUser <Identity> | Set-AdObject -Replace @{msExchRecipientDisplayType=-1073741818} to work or that this command doesn't need to be run inside the Exchange management shell but can from regular powershell (with the AD module installed, of course)?
________________________________
