### ISSUE TITLE
[LOC] Multiple invalid links

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#1257]
**Article:** esrp-storage.md
**Author:** dmaguire
**URL:**  https://docs.microsoft.com/en-us/exchange/esrp-storage?view=exchserver-2019
___

Could you please check and remove or update broken links from a list below?

**Broken links:**
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102474
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102427
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102341
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102333
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102331
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102135
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP101955
- http://www-03.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP101837
- http://www-01.ibm.com/support/docview.wss?uid=tss1prs3882
- http://www.netapp.com/us/system/pdf-reader.aspx?pdfuri=tcm:10-120427-16&amp;amp;m=tr-exchange-esrp.pdfs
- http://www.netapp.com/us/library/technical-reports/tr-fas3210-esrp-fc-storage-solution.html
- http://www.netapp.com/us/library/technical-reports/tr-esrp-netapp-fas3140-mailbox-resiliency-fc-storage-solution.html
- http://www.infortrend.com/ImageLoader/LoadSupportDoc/534?doctype=WhitePaper&amp;amp;pid=48
- http://www.infortrend.com/ImageLoader/LoadSupportDoc/520?doctype=WhitePaper&amp;amp;pid=45
- http://www.infortrend.com/ImageLoader/LoadSupportDoc/519?doctype=WhitePaper&amp;amp;pid=46
- http://www.infortrend.com/ImageLoader/LoadSupportDoc/498?doctype=WhitePaper&amp;amp;pid=30
- http://www.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102307
- http://www.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102306
- http://www.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP102097
- http://www.ibm.com/support/techdocs/atsmastr.nsf/WebIndex/WP101904
- http://www.hds.com/assets/pdf/hus-vm-dynamically-provisioned-43200-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-vm-dynamically-provisioned-24000-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-vm-dynamically-provisioned-21600-mailbox-exchange-2013-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-vm-dynamically-provisioned-120000-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-150-dynamically-provisioned-48000-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-9600-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-8000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-53600-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-4000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-36000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-20800-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-20000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-130-dynamically-provisioned-14400-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-7800-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-7200-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-4000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-40000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-27200-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-2200-mailbox-exchange-storage-solution.pd
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-15600-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hus-110-dynamically-provisioned-10400-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-vsp-dynamically-provisioned-78752-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-vsp-dynamically-provisioned-16000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-vsp-dynamically-provisioned-160000-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-vsp-dynamically-provisioned-118128-mailbox-exchange-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-uspv-dynamically-provisioned-96000-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-uspv-dynamically-provisioned-75200-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-uspv-dynamically-provisioned-32000-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-uspv-dynamically-provisioned-112000-mailbox-resiliency-storage-solution.pdf
- http://www.hds.com/assets/pdf/hitachi-unified-storage-150-dynamically-provisioned-8000-mailbox-resiliency-storage-solution.pdf
- http://www.dell.com/downloads/global/solutions/security/Dell%20PowerEdge%20R510%20ESRP%201100%20Mailbox%20Resiliency%20Exchange%202010%20Storage%20Solution.pd
- http://public.dhe.ibm.com/common/ssi/ecm/en/tsw03196usen/TSW03196USEN.PDF
- http://public.dhe.ibm.com/common/ssi/ecm/en/tsw03192usen/TSW03192USEN.PDF
- http://infortrend.com/ImageLoader/LoadSupportDoc/515?doctype=WhitePaper&amp;amp;pid=44
- http://infortrend.com/ImageLoader/LoadSupportDoc/486?doctype=WhitePaper&amp;amp;pid=37
- http://infortrend.com/ImageLoader/LoadSupportDoc/485?doctype=WhitePaper&amp;amp;pid=36
- http://infortrend.com/ImageLoader/LoadSupportDoc/484?doctype=WhitePaper&amp;amp;pid=35
- http://infortrend.com/ImageLoader/LoadSupportDoc/483?doctype=WhitePaper&amp;amp;pid=34
- http://infortrend.com/ImageLoader/LoadSupportDoc/482?doctype=WhitePaper&amp;amp;pid=33
- http://infortrend.com/ImageLoader/LoadSupportDoc/481?doctype=WhitePaper&amp;amp;pid=32
- http://infortrend.com/ImageLoader/LoadSupportDoc/480?doctype=WhitePaper&amp;amp;pid=31
- http://infortrend.com/ImageLoader/LoadSupportDoc/479?doctype=WhitePaper&amp;amp;pid=30
- http://info.nimblestorage.com/rs/nimblestorage/images/Nimble-Storage-CS700-ESRP-100000-Mailbox-Solution.pdf
- http://info.nimblestorage.com/rs/nimblestorage/images/Nimble-Storage_ESRP-40000-Mailbox-Solution.pdf
- http://info.nimblestorage.com/rs/nimblestorage/images/Nimble_Storage-CS240G-ESRP_20000_Mailbox_Solution.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA4-5186ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA4-5081ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA4-4250ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA4-4169ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA4-3116ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-5459ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-5190ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-4866ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-4765ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-4706ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-4512ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-4058ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-3371ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA3-1572ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA2-9665ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA2-1453ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA2-0623ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA2-0622ENW.pdf
- http://h20195.www2.hp.com/V2/GetPDF.aspx/4AA0-2309ENW.pdf
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA6-1069ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA6-0838ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA5-7854ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA5-6936ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA5-3366ENW&amp;amp;&amp;amp;cc=us&amp;amp;&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA5-2358ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA5-0800ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA5-0796ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA5-0564ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA4-9342ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA4-7540ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA4-7539ENW
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA4-6887ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA4-6173ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA4-1024ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA4-1019ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA3-8703ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA3-6281ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA3-5896ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA3-4053ENW&amp;amp;cc=us&amp;amp;lc=en
- http://h20195.www2.hp.com/V2/GetDocument.aspx?docname=4AA3-3953ENW&amp;amp;cc=us&amp;amp;lc=en
- http://en.community.dell.com/techcenter/extras/m/white_papers/20440709/
- http://en.community.dell.com/techcenter/extras/m/white_papers/20440261.aspx
- http://en.community.dell.com/techcenter/extras/m/white_papers/20440260.aspx
- http://en.community.dell.com/techcenter/extras/m/white_papers/20440259.aspx
- http://en.community.dell.com/techcenter/extras/m/white_papers/20438036.aspx
- http://en.community.dell.com/techcenter/extras/m/white_papers/20438034.aspx
- http://en.community.dell.com/techcenter/extras/m/white_papers/20438033.aspx
- http://content.dell.com/us/en/enterprise/d/business~solutions~whitepapers~en/Documents~r720xd-2000-mailbox-resiliency-exchange-2010.pdf.aspx
- http://content.dell.com/us/en/enterprise/d/business~solutions~whitepapers~en/Documents~r720xd-10000-mailbox-resiliency-exchange-2010.pdf.aspx

**Comment by lindspea** [comment]
@OfficeGlobal thanks, working on it.

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
