### ISSUE TITLE
Invalid PowerShell Example

### ISSUE THREAD

**Issue by mmascolino** [MicrosoftDocs/OfficeDocs-Exchange#1258]
The example:
Get-ManagementRoleAssignment -GetEffectiveUsers | Where { Get-ManagementRoleAssignment -GetEffectiveUsers | Where {$_.EffectiveUserName -Eq "Kim Akers"}.EffectiveUserName -Eq "Kim Akers"}

Doesn't appear to be valid PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdf012b5-54b6-3afe-9025-4943d4090413
* Version Independent ID: 0504a033-4441-983a-1aab-26aeb51cf099
* Content: [View effective permissions: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/view-effective-permissions-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/view-effective-permissions-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/view-effective-permissions-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
@mmascolino Thank you for pointing this out.  Just confirming you are using this PowerShell - Get-ManagementRoleAssignment -GetEffectiveUsers | Where {$_.EffectiveUserName -Eq "<name of user>"} ?It looks like there might be an error in the example.

**Comment by mmascolino** [comment]
That example is fine.  I was referring to this doc example as suspect:

Get-ManagementRoleAssignment -GetEffectiveUsers | Where {
Get-ManagementRoleAssignment -GetEffectiveUsers | Where
{$_.EffectiveUserName -Eq "Kim Akers"}.EffectiveUserName -Eq "Kim Akers"}

**Comment by lindspea** [comment]
Yes, @mmascolino apologies for the confusion, I was also referring to that example. Looks like there is duplicated info - .EffectiveUserName -Eq "Kim Akers"}. Let me know and I can do a PR to have it corrected. So it should read: Get-ManagementRoleAssignment -GetEffectiveUsers | Where { Get-ManagementRoleAssignment -GetEffectiveUsers | Where {$_.EffectiveUserName -Eq "Kim Akers"} Do you agree?

**Comment by mmascolino** [comment]
I think it should be:
`Get-ManagementRoleAssignment -GetEffectiveUsers | Where {$_.EffectiveUserName -Eq "Kim Akers"}`

**Comment by lindspea** [comment]
@scanum this can be closed thanks.

**Comment by scanum** [comment]
@mmascolino Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
