### ISSUE TITLE
Mobile Device Approval

### ISSUE THREAD

**Issue by Apex-Oil** [MicrosoftDocs/OfficeDocs-Exchange#1259]
This process only seems to work with the desktop version of office.  Are there plans or a way to approve while on the go without logging in through RDP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9389be9-edde-da61-e370-7939c1d7cf4f
* Version Independent ID: 98df220c-0e27-9498-7cee-86d8ef0f91e5
* Content: [Manage message approval in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/manage-message-approval#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-message-approval.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-message-approval.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Apex-Oil thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
