### ISSUE TITLE
Please add more detail to this document regarding free busy with hybrid agent.

### ISSUE THREAD

**Issue by kyouells** [MicrosoftDocs/OfficeDocs-Exchange#1260]
We need more detail around the requirements for free/busy if hybrid agent and on premises mailboxes.  Please add.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@kyouells Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Free/Busy information added #1297

**Comment by j0rt3g4** [comment]
Copy review @nenonix @JohanFreelancer9 is required on this one guys. Thank you in advance!

**Comment by scanum** [comment]
@kyouells Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
