### ISSUE TITLE
Hybrid Exchange statement incorrect

### ISSUE THREAD

**Issue by donkeywaffle** [MicrosoftDocs/OfficeDocs-Exchange#1263]
the part that says "In addition, a hybrid deployment can serve as an intermediate step to moving completely to an Office 365 organization."
That is not accurate. If you try to use hybrid as an intermediate step to a full cloud implementation, there is a major gotcha. You can't just remove Hybrid, you have to back track and cut-over as far as I have seen. We attempted this at my company and its been a freaking nightmare! 
Hopefully if that statement is indeed incorrect, you guys can fix that and lot lead any other sorry souls down the path that I have gone down :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c518bc-12b9-6ee8-362d-70ac54983dd6
* Version Independent ID: 102cd602-f1a6-acf9-a9b8-f47f57de3708
* Content: [Office 365 migration performance and best practices](https://docs.microsoft.com/en-us/exchange/mailbox-migration/office-365-migration-best-practices#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@donkeywaffle Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @donkeywaffle,
Actually there is nothing wrong with that statement, it really does work as an intermediate step if you don't want to go full cloud from one day to the other, or if you have more than 300 users, you can't just do a cutover migration.

Probably did you miss some steps shown here?
https://docs.microsoft.com/exchange/mailbox-migration/use-minimal-hybrid-to-quickly-migrate

**Comment by j0rt3g4** [comment]
Added useful links on PR #1288
