### ISSUE TITLE
OCT Error - Encountered errors while running organization configuration transfer. ---> System.ArgumentOutOfRangeException: Could not find property 'AddressBookPolicyRoutingEnabled' in object 'Deserialized.Microsoft.Exchange.Data.Directory.SystemConfiguration.TransportConfigContainer'.  Parameter name: AddressBookPolicyRoutingEnabled

### ISSUE THREAD

**Issue by HenrikDamslund** [MicrosoftDocs/OfficeDocs-Exchange#1264]
When running the Hybrid Configuration Wizard on a clients environment (Exchange 2010 SP3) the Error above is encountered. How do I as a partner get this resolved?

**Comment by scanum** [comment]
@HenrikDamslund thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
