### ISSUE TITLE
Move Exchange Online mailboxes to the on-premises organization

### ISSUE THREAD

**Issue by alexbell450** [MicrosoftDocs/OfficeDocs-Exchange#1265]
Opening sentence to this sub-section of Step 3 reads: "You can use the remote move migration wizard on the Office 365 tab in the EAC on an Exchange server to move existing user mailboxes in the on-premises organization to the Exchange Online organization". This is the opposite of what this part is describing. Looks like a copy and forget to edit of the first part to step 3. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35bd8438-69fb-3da3-1c75-25576fc92fd4
* Version Independent ID: 4dd5a61d-ef30-f893-00c7-bdb9132e074d
* Content: [Move mailboxes between on-premises and Exchange Online organizations in hybrid deployments](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/move-mailboxes#move-exchange-online-mailboxes-to-the-on-premises-organization)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@alexbell450 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Cleared the errors in composition on PR #1289

**Comment by j0rt3g4** [comment]
@scanum

**Comment by scanum** [comment]
@alexbell450 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
