### ISSUE TITLE
Add exchange 2016 hybrid to a legacy 2010 hybrid 

### ISSUE THREAD

**Issue by Narulans** [MicrosoftDocs/OfficeDocs-Exchange#1268]
Plz upload some documents to add new exchange 2016 hybrid to an existing exchange 2010 hybrid.. So that we can decommission 2010 after completion of migration to O365... What are all the options we will get while running the HCW ? (note its already setup on exchange 2010).. What options has to select if we do not want to make any changes to the current exchange 2010 mail flow and clients connection.... M

**Comment by scanum** [comment]
@Narulans Thanks for your feedback. I will pass it along to the team.
