### ISSUE TITLE
Bad referral at top of page

### ISSUE THREAD

**Issue by NoahsMyBro** [MicrosoftDocs/OfficeDocs-Exchange#1271]
There is a note at the top of this page that states Managed Store limits for Exchange Online are covered on the linked-to Exchange Online page. I can't find any mention of Managed Store, or sessions, or MaxConcurrency, or RCA on the linked page.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 324397b3-7807-e7d3-fdc7-74176c77dff2
* Version Independent ID: 24a0d482-f9c7-d98d-7463-1c575a5af4df
* Content: [Managed Store Limits: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/managed-store-limits-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/managed-store-limits-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/managed-store-limits-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@NoahsMyBro Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Corrected bad link on PR #1290

**Comment by j0rt3g4** [comment]
@scanum

**Comment by scanum** [comment]
@NoahsMyBro Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
