### ISSUE TITLE
O365 Migrations from Exchange - using AD Connect - need to REMOVE Exchange after 100% in the cloud

### ISSUE THREAD

**Issue by mudbob** [MicrosoftDocs/OfficeDocs-Exchange#1272]
Scenario:  We have many customers that have 10-20 users with a premise Exchange Server.  We sell the customer O365 and migrate 100% of users to O365.  We sync AD to Azure AD using AD Connect.  Once Migrated to the O365 Cloud, we would like to fully remove Exchange from the environment because hosting an Exchange server in Azure for management purposes only is at minimum $80/mo.

Question:
- How do we safely use AD Connect to sync AD and AAD, remove Exchange, and leverage O365 for all mail and mail attribute management?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mudbob thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
