### ISSUE TITLE
Missing the unlock portion

### ISSUE THREAD

**Issue by pirutgrrrl** [MicrosoftDocs/OfficeDocs-Exchange#1273]
There is no step under #8 to unlock public folders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@pirutgrrrl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@pirutgrrrl 
I see clearly the section:
[Check here!](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#step-8-test-and-unlock-the-public-folder-migration)

**Comment by j0rt3g4** [comment]
@scanum

**Comment by pirutgrrrl** [comment]
@j0rt3g4 - I did indeed see this section.  After marking the batch as complete, only test users were able to see it.  After running Set-Mailbox Mailbox1 -PublicFolder -IsExcludedFromServingHierarchy $False, all users were able to see PF.

**Comment by j0rt3g4** [comment]
Solved on PR #1370

**Comment by scanum** [comment]
@pirutgrrrl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
