### ISSUE TITLE
Migrate All G-suite at once

### ISSUE THREAD

**Issue by MarkMcPartland** [MicrosoftDocs/OfficeDocs-Exchange#1274]
I'm planning to migrate complete small company G-suite (5 users) at once.  Is the process simplified by not needing to create redirect domains?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@MarkMcPartland thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by gregmoyses** [comment]
I'm trying to understand when redirect domains are required.

My assumption is that they are only required when users are using the 365 and the GSuite platforms at the same time during a migration. If this is correct, perhaps the article could be updated to make it clearer. For people doing small migrations or moving all users over at once, this will save a lot of time.

**Comment by robertallardice** [comment]
Hello, 
The redirection method is not the proper way for migration. If you are using it then you need both G Suite and Office 365 domains all the time. The real meaning of migration is when you transfer complete user's accounts data to the destination location. I can recommend you to take help from third-party who are experts in this task. This is the safest and fastest way to solve your problem. And if you are looking for a free method then you can try the **SysTools Migrator**. First, try the migration of 2 users for testing.  https://systoolsgroup.com/migrator/
