### ISSUE TITLE
Multiple Active Directory Forests

### ISSUE THREAD

**Issue by meshkerila** [MicrosoftDocs/OfficeDocs-Exchange#1275]
Please update this article to mention the supportability of multi-forest Exchange Hybrid deployments.
The "no longer maintained" documentation (https://docs.microsoft.com/en-us/previous-versions/exchange-server/exchange-150/jj873754(v=exchg.150)) mentions the basic steps and concept of multi-forest deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server Hybrid Deployments](https://docs.microsoft.com/en-us/exchange/exchange-hybrid#feedback)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lusassl-msft** [comment]
Hi @meshkerila. The multi-forest Exchange Hybrid scenario is still supported. Let me check what we can do here.

**Comment by scanum** [comment]
@meshkerila  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@meshkerila thank you for reaching out. @lusassl-msft - just following up on this issue. Shall I investigate further?

**Comment by lusassl-msft** [comment]
@lindspea please contact me internally. I’m in discussion with @chrisda. Will come back to you after my return from vacation.

**Comment by scanum** [comment]
@lusassl-msft Hi Lusassl, Lindsay has no internal access. Any updates on this? Thanks!

**Comment by lusassl-msft** [comment]
@scanum unfortunately not. I'll ask the PM for an update and come back to you.

**Comment by lindspea** [comment]
@scanum @lusassl-msft any update yet?

**Comment by msdmaguire** [comment]
I have assigned this issue to Matt Penna (mattpennathe3rd). He is a new vendor we have for the Exchange repos.

**Comment by lindspea** [comment]
@mattpennathe3rd

**Comment by scanum** [comment]
@mattpennathe3rd

**Comment by mattpennathe3rd** [comment]
@meshkerila This article is complete and has been published [here](https://docs.microsoft.com/Exchange/hybrid-deployment/hybrid-with-multiple-forests). I expect that we will make some further additions and edits, but if you notice problems in the article, please open a new issue (or click the Edit button on the top of the page to submit a PR of your own) to let me know. Thanks for pointing out this hole in the docs.
