### ISSUE TITLE
Broken formatting

### ISSUE THREAD

**Issue by MrUzagi** [MicrosoftDocs/OfficeDocs-Exchange#1279]
The formatting of the page below "(Optional) Step 2" currently looks broken, where code is outside the code boxes and the explaining text is mostly inside, making it difficult to read.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b7bbcdd-c649-d6d0-d4ae-86a2ea6ec8b2
* Version Independent ID: aa967269-4eaa-d7cc-5835-c0c543a402d6
* Content: [Use Compliance Search to search all mailboxes in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/ediscovery/compliance-search?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/ediscovery/compliance-search.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/ediscovery/compliance-search.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@MrUzagi  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by thmeyer-msft** [comment]
@scanum 
See #1299 - Commit [f585027](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1299/commits/f585027d763d1659bb57546c52e961399b2e79cc) - this is fixed!

**Comment by MrUzagi** [comment]
Looks good live now.
