### ISSUE TITLE
Images can't be loaded.

### ISSUE THREAD

**Issue by sparkf1** [MicrosoftDocs/OfficeDocs-Exchange#128]
Hi, the images of "Exchange architecture" and "Communication between exchange servers" can't be displayed, can you help to fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d29e4f-dd0c-3ea2-13fb-5077b83b946b
* Version Independent ID: f2580bd9-66b9-52f4-6335-42d5ee08d457
* Content: [Exchange Server architecture](https://docs.microsoft.com/en-us/Exchange/architecture/architecture?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/architecture.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/architecture.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@sparkf1 Thank you for this feedback

I want to make sure the images open for you. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by AndreaBarr** [comment]
@sparkf1  Ahh I see now what you mean. Sorry for the misunderstanding on my end. I'll get this over into the Exchange teams backlog so we can look at the markdown for those images and get this fixed. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@sparkf1 this issue has been fixed.

Thanks for the feedback.
