### ISSUE TITLE
O365 Group Writeback to Security Groups

### ISSUE THREAD

**Issue by coffeemade** [MicrosoftDocs/OfficeDocs-Exchange#1280]
I have a customer that is looking to write back groups as on-prem security groups, so they can update them in O365 and then have their local AD security group updates, I am thinking this would be possible with MIM. Could you provide any insight into this?

**Comment by scanum** [comment]
@coffeemade thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by basicsbv** [comment]
I need a administrator user for do my recovery windows open
