### ISSUE TITLE
Patterns reference link

### ISSUE THREAD

**Issue by common-knowledge** [MicrosoftDocs/OfficeDocs-Exchange#1281]
Hello,
The 'patterns' property in the Property types section contains a link to the "Regular Expression Syntax". This link goes to a general regular expression page that does not correlate to the available syntax for the 'patterns' property that is available in mail transport rules in Exchange. The link provides the majority of syntax that can be used in Jscript or .NET, but mail transport rules property 'patterns' only has a select subset of all of the regular expression syntax available. I cannot find the documentation on what regex syntax is available for patterns in mail transport rules. Please update link.
Thank you,
Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65cb383c-bd27-940b-9cd5-48052d34076a
* Version Independent ID: e9e33e90-b9b9-a44c-6976-7d32cd003543
* Content: [Mail flow rule conditions and exceptions (predicates) in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mail-flow-rules/conditions-and-exceptions?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/conditions-and-exceptions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/conditions-and-exceptions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@common-knowledge  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @common-knowledge, thank you for your feedback.

I think there isn't an updated link. But you can find that information on this Exchange 2010 article:
https://docs.microsoft.com/previous-versions/office/exchange-server-2010/aa997187(v=exchg.141)

**Comment by scanum** [comment]
@common-knowledge Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
