### ISSUE TITLE
Stray asterisks and repeated text

### ISSUE THREAD

**Issue by douglasac10** [MicrosoftDocs/OfficeDocs-Exchange#1283]
Good morning,

There's a number of stray asterisks at the start of bullet list items that could be removed.

In addition, under the Change Room Mailbox Properties section General, the first bullet point reads " This name appears in the resource mailbox list in the Exchange admin centerExchange admin center" - there's one too many Exchange admin centers there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1598a231-d154-1c94-d8aa-76084b45ed35
* Version Independent ID: 3cc7eb58-d64e-73f2-8566-f97ec30ac15e
* Content: [Create and manage room mailboxes](https://docs.microsoft.com/en-us/exchange/recipients/room-mailboxes?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/recipients/room-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/room-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@douglasac10  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
This appears to have been fixed by https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1393 . Closing as done!
