### ISSUE TITLE
Exchange Online: OAB cannot be provisioned directly to users. They can only be provisioned through ABP.

### ISSUE THREAD

**Issue by HematM** [MicrosoftDocs/OfficeDocs-Exchange#1293]
In Exchange Online, an Offline Address Book (OAB) cannot be assigned directly to a user. It can only be assigned through via Address Book Policy (ABP). Therefore, the  "Set-Mailbox" option for  a mailbox to assign OAB in this document is incorrect. 

"Per mailbox: You can use the Set-Mailbox cmdlet in Exchange Online PowerShell to assign the OAB to a mailbox. You can also assign the OAB to a filtered list of mailboxes."  - This should be updated / removed as not valid for Exchange Online.

Thanks,
Hemat.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abd67f0-f80f-323d-83f4-5c310b29acf0
* Version Independent ID: 586603e3-619d-90e7-af7e-bb22296778c4
* Content: [Provision recipients for offline address book downloads in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/offline-address-books/provision-recipients)
* Content Source: [Exchange/ExchangeOnline/address-books/offline-address-books/provision-recipients.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/offline-address-books/provision-recipients.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@HematM  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @HematM, thank you for your feedback.

I have been testing with 2 tenants and looks like -OfflineAddressBook parameter doesn't exist in Exchange Online.
And we can confirm that if we look here:
https://docs.microsoft.com/powershell/module/exchange/mailboxes/set-mailbox

**Comment by scanum** [comment]
@HematM Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
