### ISSUE TITLE
[LOC] Multiple invalid fwlinks

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#1294]
Hello, could you please review articles listed below?
It contains fwlinks redirecting to 404 pages - links should be updated or removed from the articles.

FileName | FwLink
-- | --
antispam-stamps.md | https://go.microsoft.com/fwlink/p/?linkId=50977
assign-a-category-page-and-a-catalog-item-page-to-a-term.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
azure-help-identify-my-issue-with-automatic-checks-dns-records-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
build-numbers-and-release-dates.md | https://go.microsoft.com/fwlink/p/?LinkId=197012
configure-inbound-connectivity.md | https://go.microsoft.com/fwlink/?LinkId=392208
configure-result-sources-for-web-content-management.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
configure-search-web-parts.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
configure-sharepoint-health-analyzer-rules.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
configuring-push-notifications-proxying-for-owa-for-devices-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=335704
connect-a-publishing-site-to-a-catalog.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
create-query-rules-for-web-content-management.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
help-idenfity-my-issue-with-automatic-checks-adding-domains-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
help-identify-my-issue-with-automatic-checks-active-directory-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
help-identify-my-issue-with-automatic-checks-deploying-office-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
help-identify-my-issue-with-automatic-checks-directory-synchronization-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
help-identify-my-issue-with-automatic-checks-migration-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
help-identify-my-issue-with-automatic-checks-quota-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
help-identify-my-issue-with-automatic-checks-sso-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=286258
mailbox-audit-logging.md | https://go.microsoft.com/fwlink/p/?linkId=204086
mailbox-audit-logging-exchange-2013-help.md | https://go.microsoft.com/fwlink/p/?linkid=204086
mail-flow-permissions.md | https://go.microsoft.com/fwlink/p/?LinkID=335814
managing-database-availability-groups-exchange-2013-help.md | https://go.microsoft.com/fwlink/p/?linkid=179131
multiple-servers-for-a-three-tier-farm.md | https://go.microsoft.com/fwlink/p/?LinkId=259177
sender-id.md | https://go.microsoft.com/fwlink/p/?linkId=50977
storage-and-sql-server-capacity-planning-and-configuration.md | https://go.microsoft.com/fwlink/p/?LinkId=317240
storage-and-sql-server-capacity-planning-and-configuration.md | https://go.microsoft.com/fwlink/p/?LinkId=317258
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://go.microsoft.com/fwlink/?linkid=522619
view-data-in-the-logging-database.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
view-health-reports.md | https://go.microsoft.com/fwlink/p/?LinkID=246504
view-timer-job-status.md | https://go.microsoft.com/fwlink/p/?LinkID=246504

**Comment by scanum** [comment]
@OfficeGlobal  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
