### ISSUE TITLE
incorrect statement about the archive mailbox

### ISSUE THREAD

**Issue by HenrikBernhard** [MicrosoftDocs/OfficeDocs-Exchange#1295]
seems there was a copy&paste mistake, shouldn't this sentence
The archive mailbox appears as another mailbox or .pst file in Outlook and Outlook on the web.
instead be: 
The archive mailbox appears as another mailbox in Outlook and Outlook on the web.

doesn't make sense that the archive mailbox appears as a .pst file...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05081ae-deaf-239f-350b-bcd31b897195
* Version Independent ID: 41dd99fb-5d8d-83c8-ebee-15e98f26c30e
* Content: [In-Place Archiving in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/in-place-archiving/in-place-archiving?view=exchserver-2019&viewFallbackFrom=exchonline-ww#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/in-place-archiving/in-place-archiving.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/in-place-archiving/in-place-archiving.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@HenrikBernhard  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by thmeyer-msft** [comment]
@scanum I would say Henrik is right, normally the Archive doesn't appear as a .pst file. This also makes no sense. 
The only thing which is possible, is exporting the archive to a pst file.

I fix that and create a pull request.

**Comment by dariomws306** [comment]
Hi @thmeyer-msft, I think you missed the word **in** in the next line:

The archive mailbox appears as another **mailbox Outlook** and Outlook on the web or like a mounted .pst file in Outlook.

**Comment by dariomws306** [comment]
Hi @thmeyer-msft, I think you missed the word **"in"** in this sentence:

The archive mailbox appears as another **mailbox Outlook** and Outlook on the web or like a mounted .pst file in Outlook.

**Comment by scanum** [comment]
@HenrikBernhard Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
