### ISSUE TITLE
Quotation marks missing from command

### ISSUE THREAD

**Issue by ElliottLW** [MicrosoftDocs/OfficeDocs-Exchange#1298]
Section below should include Quotation marks around the value for -SubjectName:
New-ExchangeCertificate -GenerateRequest -RequestFile "\\FileServer01\Data\Contoso SAN Cert.req" -FriendlyName "Contoso.com SAN Cert" -SubjectName C=US,CN=mail.contoso.com -DomainName autodiscover.contoso.com,legacy.contoso.com,mail.contoso.net,autodiscover.contoso.net,legacy.contoso.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb6bf64-d3d6-dff6-2eb7-02074758e834
* Version Independent ID: 32b7069b-6a49-9d54-5119-b0d42aad619d
* Content: [Create an Exchange Server certificate request for a certification authority](https://docs.microsoft.com/en-us/exchange/architecture/client-access/create-ca-certificate-requests?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/create-ca-certificate-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/create-ca-certificate-requests.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ElliottLW Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@msdmaguire feel free to merge the PR and close this   issue

**Comment by SerdarSoysal** [comment]
@dplotnikov thank you. Merged the PR and closing this issue as resolved.
