### ISSUE TITLE
On-prem only?

### ISSUE THREAD

**Issue by aaronarr** [MicrosoftDocs/OfficeDocs-Exchange#13]
Does this article pertain only to on-prem Exchange servers and not Exchange Online? If so, it would be beneficial to mention it in the beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03324cd6-a5cb-f538-a882-f0c1127dbe6c
* Version Independent ID: 99a49dec-ac23-d48e-3529-4ec14d51f72b
* Content: [Mailbox imports and exports in Exchange 2016](https://docs.microsoft.com/en-us/exchange/recipients/mailbox-import-and-export/mailbox-import-and-export)
* Content Source: [Exchange/ExchangeServer/recipients/mailbox-import-and-export/mailbox-import-and-export.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/mailbox-import-and-export/mailbox-import-and-export.md)
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@aaronarr, the topic is in an area called 'Exchange Server' and the title of the topic is 'Mailbox imports and exports in Exchange 2016', so no consideration is given to Exchange Online. An Exchange Online version of the subject (if there even is such a thing), would exist in the [Exchange Online](https://docs.microsoft.com/Exchange/exchange-online) node.

Thanks for the feedback.
