### ISSUE TITLE
This vs Security and Compliance Retention (Labels/Label Policies/[retention policies?]

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#130]
Both in this article, and in this one https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies?redirectSourcePath=%252farticle%252f5e377752-700d-4870-9b6d-12bfc12d2423 - it needs to be very clear which one takes precedence over the other if both are configured.

It isn't stated anywhere as far as I can tell.  Can you please comment on this to confirm which one wins?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed28361e-0f38-bd97-1153-0295e19ddd8b
* Version Independent ID: 8342198a-1806-9f37-fd59-4fec2b417a67
* Content: [Retention tags and retention policies in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mrm/retention-tags-and-retention-policies?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mrm/retention-tags-and-retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mrm/retention-tags-and-retention-policies.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by AndreaBarr** [comment]
@JeremyTBradshaw Thank you for this feedback

It looks like Chris updated the article to reflect the answers to your question. I am going to close this issue. If the issue is not resolved please reopen the issue.

**Comment by JeremyTBradshaw** [comment]
@AndreaBarr @chrisda Thanks guys.  I'm looking at the commit a4516e14a9f9e1a2fd4fd60735fa2cb7c0a43182, and I scrolled through the whole thing.  Searched for and navigated through all instances of the word "retention".  I couldn't find anything about this.  Also in the main article, I don't see anything.

I'm trying to get official confirmation of what takes precedence - Security and Compliance Center Retention Policies vs Retention Policies/Tags in Exchange Online directly.

I have a Retention Policy setup in Security & Compliance Center, under Data Governance > Retention.  It has been in place for longer than 24 hours.  However, when I look in Exchange Admin Center, there is no sign of anything other than the default Retention Tags and Policies.

There is, from what I can tell, no visibility of Office 365 retention policies from the Exchange Online perspective.  Meanwhile all the Exchange Online Retention Tags/Policies remain visible, and the Default MRM Policy remains assigned to all mailboxes.

**Comment by AndreaBarr** [comment]
@JeremyTBradshaw That's odd the new policy should be visible.  I want to make sure you get a quick answer to this. Support can handle this to resolution and get this working properly for you. 


I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by JeremyTBradshaw** [comment]
Well this didn't go as planned.  Clever way to get content updated!
