### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by wesleykirkland** [MicrosoftDocs/OfficeDocs-Exchange#1300]
On prem vs O365 permissions - https://go.microsoft.com/fwlink/p/?LinkID=335814

That link 404's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01e59ebb-7999-f811-8bac-2daa7b256054
* Version Independent ID: c9cd0826-3402-afc5-c3bb-c50d822c1515
* Content: [Mail flow permissions](https://docs.microsoft.com/en-us/exchange/permissions/feature-permissions/mail-flow-permissions?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/permissions/feature-permissions/mail-flow-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/permissions/feature-permissions/mail-flow-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@wesleykirkland Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@msdmaguire feel free to merge the PR and close this issue

**Comment by wesleykirkland** [comment]
That link doesn't seem right to me. Shouldn't it redirect to Exchange
permissions as it relates to O365 and not O365 permissions? In on Orem
exchange you can create separate roles, and this can also be accomplished
in O365.

**Comment by dplotnikov** [comment]
@wesleykirkland I was thinking the same but this is the link that supposed to be there because there was a typo inside of it

**Comment by wesleykirkland** [comment]
While I agree with fixing the link, I feel like another doc should be
linked to for the real O365 exchange permissions.

**Comment by dplotnikov** [comment]
fyi, this is how that linked article title was updated over time

1. About Office 365 admin roles
2. About admin roles in the Microsoft 365 admin center
3. About admin roles

**Comment by scanum** [comment]
@wesleykirkland Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
