### ISSUE TITLE
Explanation needed for "Hybrid Domains" - "Auto Discover"

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/OfficeDocs-Exchange#1303]
Please clarify in which cases you would need to enable Auto Discover for a domain at step 11 "Hybrid Domains". Right now it says:

> "In most deployments you can leave the Auto Discover column set to False for each domain. Only select True next to a domain if you need to force the wizard to use the Autodiscover information from a specific domain."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8cb000-e64b-b90d-fa6f-09f2b50532b3
* Version Independent ID: b65f1351-a45c-37b6-f1a8-12894f203dd4
* Content: [Create a hybrid deployment with the Hybrid Configuration wizard](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/deploy-hybrid#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@diecknet Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@diecknet thank you for reaching out. I'll chat to the team to get clarification and revert soonest. @msdmaguire

**Comment by lindspea** [comment]
@diecknet it seems this document has been updated since your query. Please confirm and let me know if the article information is clearer now.

**Comment by diecknet** [comment]
@lindspea There was no clarification added with the latest updates.

**Comment by lindspea** [comment]
@msdmaguire could you perhaps help clarify please.

**Comment by scanum** [comment]
@dstrome @msdmaguire Hi! Wondering if there is any updates on resolution of this issue? Thanks!

**Comment by msdmaguire** [comment]
@dstrome if you don't have bandwidth to address, or know the answer, we should give this to @mattpennathe3rd to prioritize and chase down an answer.

**Comment by SerdarSoysal** [comment]
@mattpennathe3rd pls sync with David Strome before you find the answer.

**Comment by scanum** [comment]
@mattpennathe3rd  @dstrome Any update on this? Thanks!
