### ISSUE TITLE
Computer requirements for extending schema

### ISSUE THREAD

**Issue by ausotechteam** [MicrosoftDocs/OfficeDocs-Exchange#1304]
Hi,
The computer/server that you use to run the commands to extend the AD schema/Prepare AD, does it need the RSAT-ADDS feature and .NET Framework 4.5.2 installed as the requirements as well? this is according to this article https://practical365.com/exchange-server/installing-exchange-server-2016/

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f347a03-e2c5-5ae2-e409-ddb6d544ccfd
* Version Independent ID: 839ff415-2b55-e312-3121-0fd2d9ca5a88
* Content: [Prepare Active Directory and domains for Exchange Server, Active Directory Exchange Server, Exchange Server Active Directory, Exchange 2019 Active Directory](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prepare-ad-and-domains?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ausotechteam Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@ausotechteam Thank you for reaching out and helping improve MS Docs. Did @AzureGuineaPig's suggestion help solve the issue?

**Comment by ausotechteam** [comment]
Thanks, please close.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by scanum** [comment]
@ausotechteam Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
