### ISSUE TITLE
[LOC] Multiple broken links

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#1305]
Hello,
 could you please review articles below and remove or update broken links?

|1.   article | Broken links|
|-- | --|
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/jj156210.aspx#bkmk_StartGateway
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/jj156210.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/jj156088.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn630228.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn133802.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn133801.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn133800.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn133799.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn133797.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn133796.aspx
azure-vms-as-dag-witness-servers.md | https://msdn.microsoft.com/library/azure/dn133794.aspx

|2.   article | Broken links|
|-- | --|
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/library/azure/jj156210.aspx#bkmk_startgateway
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/library/azure/jj156210.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/jj156088.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/dn133802.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/dn133801.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/dn133800.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/dn133799.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/dn133797.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/dn133796.aspx
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://msdn.microsoft.com/en-us/library/azure/dn133794.aspx

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Reeced40** [comment]
@OfficeGlobal Looking into it, thanks.

**Comment by scanum** [comment]
@Reeced40 Any updates on this? Thanks!

**Comment by Reeced40** [comment]
@OfficeGlobal Please can you send me the link for the second article, I cant seem to find it? @msdmaguire Could you perhaps help with the links in the first article? https://docs.microsoft.com/exchange/high-availability/manage-ha/azure-vms-as-dag-witness-servers?view=exchserver-2019 Should I remove them or replace them? There are quite a few topics that I cant find. 
@scanum Thanks. I'm still investigating.

**Comment by OfficeGlobal** [comment]
FileName | URL
-- | --
azure-vms-as-dag-witness-servers.md | https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/azure-vms-as-dag-witness-servers?view=exchserver-2019
using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help.md | https://docs.microsoft.com/en-us/exchange/using-a-microsoft-azure-vm-as-a-dag-witness-server-exchange-2013-help
