### ISSUE TITLE
Need to article update.

### ISSUE THREAD

**Issue by sujithnair79** [MicrosoftDocs/OfficeDocs-Exchange#1307]
Cmdlet that can be used to configure **ShadowMessagePreference** is **Set-TransportConfig** instead of **Set-TransportService** and correct configurable parameter is **ShadowMessagePreferenceSettings**

Snip from article:
If the primary server is a member of a DAG, the primary server connects to a different Mailbox server in the same DAG. If the DAG spans multiple Active Directory sites, a Mailbox server in a different Active Directory site is preferred by default (the default value of the **ShadowMessagePreference** parameter on the **Set-TransportService** cmdlet is PreferRemote, but you can change it to RemoteOnly or LocalOnly).

![image](https://user-images.githubusercontent.com/53767982/64697045-937f1f00-d4bd-11e9-8272-d9dde9f7e3ac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dca513a-53fd-babd-9471-8ebc2ce7af89
* Version Independent ID: 842d6750-c124-7242-9740-ee259a4a9cf0
* Content: [Shadow redundancy in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/transport-high-availability/shadow-redundancy?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-high-availability/shadow-redundancy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-high-availability/shadow-redundancy.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@sujithnair79 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@msdmaguire feel free to merge the PR and close this issue

**Comment by scanum** [comment]
@sujithnair79 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
