### ISSUE TITLE
Adding an alias domain in GSuite takes up to 24 hours

### ISSUE THREAD

**Issue by mipopa** [MicrosoftDocs/OfficeDocs-Exchange#1310]
Please incldue a remark in the section "Create a sub-domain for mail routing to your G Suite domain" that adding the alias domain "gsuite.fabrikaminc.net" in GSuite takes up to 24 hours until all mailboxes hosted on GSuite receive their new &lt;user&gt;@gsuite.fabrikaminc.net alias address. During this time, no EXO mailuser should have their external email address attribute set to &lt;user&gt;@gsuite.fabrikaminc.net, otherwise the existing O365 users who already have their mailboxes in EXO won't be able to send emails to the GSuite users who are represented in EXO as mailusers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mipopa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
