### ISSUE TITLE
why talking about Office 365 in this documentation ?

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/OfficeDocs-Exchange#1313]
It's written "Since all of your mailboxes have been migrated to Office 365 prior to the public folder migration, we strongly recommend that you route the traffic through Office 365 (decentralized mail flow)" but, the article title is "Use batch migration to migrate Exchange 2010 public folders to Exchange 2016". I think there is a small mistake here ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6010593-c3e4-87a6-4084-27d56f23063c
* Version Independent ID: 32a2adeb-0932-3236-09d9-b7987393639b
* Content: [Use batch migration to migrate Exchange 2010 public folders to Exchange 2016](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/batch-migration-from-previous-versions?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@RomanNG Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@msdmaguire feel free to merge the PR and close this issue

**Comment by scanum** [comment]
@RomanNG Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
