### ISSUE TITLE
Does this work with non-mail enabled Public Folders..?

### ISSUE THREAD

**Issue by RescueWhale** [MicrosoftDocs/OfficeDocs-Exchange#1332]
The article doesn't specify :/

At the moment non of our public folders are mail-enabled so it would be a bit of a task to do so.

Is there a way to migration without doing this?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-gb/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders?redirectedfrom=MSDN#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@RescueWhale Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@RescueWhale Thank you for reaching out and helping improve MS Docs. Please have a look at this article and let me know if it helps at all. https://docs.microsoft.com/Exchange/collaboration/public-folders/mail-enable-or-disable?view=exchserver-2019

**Comment by scanum** [comment]
@RescueWhale Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
