### ISSUE TITLE
What happens with the mailuser once the migration batch completes and it's sync'ed from on-prem AD?

### ISSUE THREAD

**Issue by mipopa** [MicrosoftDocs/OfficeDocs-Exchange#1333]
We have the scenario where the mailusers in EXO are actually sync'ed from on-prem AD. There is no Hybrid setup with on-prem, just one greenfield Exchange 2016 server installed in order to manage the recipients' properties.
According to the first part of the article, once the migration batch completes, EXO will change the recipient from mailuser to mailbox (and the target address attribute does not exist any longer). However since the user object is sync'ed from on-prem AD, is it necessary to run some commands in Exchange on-prem so that the attributes of the corresponding user object in AzureAD are not overwritten by the sync? Or is the AADC going to write back the updated user properties from AzrueAD to on-prem AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mipopa 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by neonad** [comment]
Hi @mipopa ,

I am trying to find out the same thing? Can you let me know what was your experience with this? How you achieved this?

Thanks,
NJ

**Comment by mipopa** [comment]
Hi there,

Well, what we did was to run Enable-RemoteMailbox (https://docs.microsoft.com/en-us/powershell/module/exchange/enable-remotemailbox) in Exchange on-prem. Please note that if you have sync'ed identities you won't be able to manages man of the attributes from the Exchange Online EAC (such as: the Archive Mailbox, etc.). These attributes need to originate from on-prem AD and since they are Exchange-specific attributes the only supported way and the safest way to manage them is by using Exchange on-prem, so you'll have to install one (we installed 2016) with a free Hybrid License Key (as long as you don't host any mailboxes on your on-prem server and you'll only use it to manage recipients, email address policies, etc.).

Cheers,
M

________________________________
