### ISSUE TITLE
Can we apply personal tag to Default folder in OWA like inbox,etc?

### ISSUE THREAD

**Issue by pathak7009** [MicrosoftDocs/OfficeDocs-Exchange#1334]
Hi ,
Iread an article about retention tags and policies.
Here it is clearly mentioned that we can apply Personal tags on Custom created folder or individual item like any email in inbox, etc.

I created a personal tag and applied it to a user ( it was admin) and I can see that I can apply it to default folder and  I also applied it to INBOC and forced the MFA through powershell command start-managedfolderassistant -identity "user" and I can see that it went to In-Place Archive (inbox option on it) and my inbox is empty.

Strange , what is it?
I am so confused as it is not working according to the article.

**Comment by pathak7009** [comment]
![p-1](https://user-images.githubusercontent.com/55281214/64860803-e1299200-d64b-11e9-953e-fe2e7fee6daa.PNG)
![p-2](https://user-images.githubusercontent.com/55281214/64860804-e25abf00-d64b-11e9-9de5-8e47299acff8.PNG)
![p-3](https://user-images.githubusercontent.com/55281214/64860805-e2f35580-d64b-11e9-86fd-4fdd178e15c1.PNG)
![p-4](https://user-images.githubusercontent.com/55281214/64860807-e4bd1900-d64b-11e9-9373-c5a090fb9d3f.PNG)

**Comment by pathak7009** [comment]
![p-5](https://user-images.githubusercontent.com/55281214/64860907-34034980-d64c-11e9-8b8e-1133fc8a3f53.PNG)

**Comment by pathak7009** [comment]
You can see that test 3 is personal tag and it can be applied on inbox and above I have already shown that all emails moved to archive after start-mfa command

**Comment by scanum** [comment]
@pathak7009 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by pathak7009** [comment]
Hi Scanum, 
Thank you for your response. 

I am an Office 365 Administrator who take cares of Partners issue.

I will be waiting for your response.

**Comment by scanum** [comment]
@pathak7009 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by pathak7009** [comment]
I cant create a ticket as I am also a Microsoft Online exchange engineer.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
