### ISSUE TITLE
Ability to report who is using legacy authentication?

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/OfficeDocs-Exchange#1335]
Is there any update on reporting of users who are currently using legacy authentication?
This would be really useful to report on before disabling so IT knows just who is going to be affected.

**Comment by scanum** [comment]
@Absoblogginlutely thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
