### ISSUE TITLE
Step 5 looks different

### ISSUE THREAD

**Issue by DavePPage75** [MicrosoftDocs/OfficeDocs-Exchange#1336]
Hi Guys, I'm having issues with a migration from outlook.com mailbox to O365 instance, the error in the admin centre is "incorrect remote server" and it points to this page to resolve the issue. However I see a difference when following the document at step 5. Firstly I already have MFA setup on both the outlook.com mailbox (source) and the O365 mailbox (destination) but even if I remove this, and follow the instructions as if MFA was not enabled, I don't see the same set of screens as in this document.

In any case once I have setup MFA, and created an app password, if I put this password into the migration credentials box on the Admin Center, the system checks for a moment and then provides the same error. 

Normally this outlook.com mailbox is log into with a user name (user@gmail.com email address) and a password, with MFA using the MS authentication application, its not possible to log into outlook.com using the mailbox name, only the user name (user@gmail.com) so I'm not sure if this has a part to play in the issue, or if the document does not cater for this scenario.

Thanks
Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0d26fa-47d7-3d58-2810-52cac3ffa35d
* Version Independent ID: d2222d35-54cb-cd89-e27e-00d92838444e
* Content: [Migrating your Outlook.com account to Office 365](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/migrating-imap-mailboxes/migrating-your-outlook-com-account#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrating-your-outlook-com-account.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrating-your-outlook-com-account.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@DavePPage75 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
