### ISSUE TITLE
Outlook freezes when working in a shared mailbox

### ISSUE THREAD

**Issue by WRFLNL** [MicrosoftDocs/OfficeDocs-Exchange#1337]
This is an issue we are looking to solve sooner rather than later.

We use several shared mailboxes.
We use the office 365 platform with exchange. 
We use the outlook application on the local computer.
There is no local e-mail server.

When draging an e-mail into a sub folder in a shared mailbox, the oulook app freezes.
This happens most often to the shared mailboxes that are bigger and it most likely happens with messages with attachments. 
The freeze happens only to the user that dragged the message, other users do not notice anything, unless they're dragging as well.

Specifics to the shared mailbox that encounters this issue most frequently: 
Size: approx 10,5 GB
Average simultanious users: 7
archive: after 2 months

The webmail version might be an alternative, but there are some functionalities that are missing and the local version is far more user friendly. People are emotionally attached to Outlook as well, so if there would be an option working with the Ooutlook app, that would be ideal.

I can imagine there is a lot more information that you need for a solution. Feel free to ask. 
Can someone help us?

**Comment by scanum** [comment]
@WRFLNL thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
