### ISSUE TITLE
There is a typo in second example

### ISSUE THREAD

**Issue by zaicnupagadi** [MicrosoftDocs/OfficeDocs-Exchange#134]
"Import-ExchangeCertificate -FileName "Import-ExchangeCertificate -FileName "\\FileServer01\Data\Fabrikam.pfx" - the filename is double.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0aa4eed-e992-4cd9-0b43-4321eb65160d
* Version Independent ID: 3fe6fed7-215e-a93a-9dd5-24b59af1c815
* Content: [Import or install a certificate on an Exchange server](https://docs.microsoft.com/en-us/exchange/architecture/client-access/import-certificates?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/import-certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/import-certificates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@zaicnupagadi, thanks for the feedback. There were two examples that had the "Import-ExchangeCertificate -FileName "Import-ExchangeCertificate" typo, and I fixed them both.

**Comment by zaicnupagadi** [comment]
Good stuff.

Cheers,
J

czw., 27.09.2018, 18:16 użytkownik Chris Davis <notifications@github.com>
napisał:

**Comment by devFofo** [comment]
The powershell command examples for p7b have an extra ] at the end.
