### ISSUE TITLE
Typo - First note change "only use odern" to "only use modern"

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/OfficeDocs-Exchange#1343]
Typo - First note change "only use odern" to "only use modern"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64383249-903c-6cc5-83e1-93e0eb8ba128
* Version Independent ID: d93c4ce8-4bf4-15d0-b3ba-3d3eb11ebb37
* Content: [POP3 and IMAP4](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@bingoglossy  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msbemba** [comment]
@bingoglossy Thank you for your feedback. We have made changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1360

Thanks
Sri

**Comment by scanum** [comment]
@bingoglossy Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
