### ISSUE TITLE
New-MoveRequest with Hybrid Agent

### ISSUE THREAD

**Issue by bballpaul4work** [MicrosoftDocs/OfficeDocs-Exchange#1345]
This is included but no more details are included : 
"Performing a test mailbox move from your on-premises Exchange organization to your Office 365 tenant is also an option."
But how? What should the value of -RemoteHostname be in the New-MoveRequest cmdlet?

**Comment by scanum** [comment]
@bballpaul4work 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
