### ISSUE TITLE
128GB RAM minimum?

### ISSUE THREAD

**Issue by safeng510** [MicrosoftDocs/OfficeDocs-Exchange#135]
From the table, Exchange server 2019 mailbox role has dramatically increased minimum memory requirement to 128GB. is that a reason?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server system requirements](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by balinger** [comment]
As we discussed at Ignite 2018, we have made many changes in Exchange Server 2019 with respect to how the .NET framework allocates memory to support more processor cores with Exchange.
