### ISSUE TITLE
Problem with ExternalEmailAddress and Proxy Email Address references

### ISSUE THREAD

**Issue by robthayer** [MicrosoftDocs/OfficeDocs-Exchange#1350]
I'm attempting this migration process. We are using cloud only authentication, so not using Azure AD Connect, and in the beginning paragraphs in the section Provision Users in Office 365 (https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#provision-users-in-o365), a link is given for Manage Mail Users, which has two problems. One, the text on this page seems outdated as some of the actions referenced do not match how EAC Contacts-&gt;Mail User dialogs look and work today, or because I've missed some other setting I cannot perform the actions as described.  Secondly, it doesn't seem to adequately explain the reason I have to re-create all of the users with a new set of credentials for users I've already created in Office 365 Admin Console which show up in EAC Recipients, when all that seems necessary to continue is adding an ExternalEmailAddress, and a Proxy email addrss to the existing users. I've opened a case with my CSP, but was thinking maybe there is something here that needs to be clarified also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@robthayer 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jblot** [comment]
Hey @robthayer . Running into the same issue. Did you ever have any luck getting that resolved ?

Thanks!

**Comment by robthayer** [comment]
@jblot. No, but I found out I didn't need to perform a manual migration because our CSP (Dell) was going to do it. Dell used a third party migration solution (SkyKick), and after a few minor issues (related to their own documentation) they were able to successfully migrate us from G-Suite to O365.
