### ISSUE TITLE
Clarity at the top - no built in migration option

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-Exchange#1351]
This is a nice article. I would recommend it to a friend. What it is missing is some clarity at the very beginning, that addresses some of the feedback already posted. Why not be more explicit at the top and state that there are no built in tenant-to-tenant migration options. The current option is to make manual changes (pst, connect to two accounts) or go with a third party tool (vendor).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Office 365 tenant to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Jmartinez589  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by TokyoScarab** [comment]
@Jmartinez589 Hello and thank you for bringing up this issue.  I'll be investigating this and will be getting back to you on this issue, thanks!

**Comment by TokyoScarab** [comment]
@msdmaguire As the author, would have any insight into what option might be good to mention in a note for migration options?

**Comment by msdmaguire** [comment]
@TokyoScarab Until tenant-to-tenant is developed and released, I think the best thing would be to have a note at the top, as @Jmartinez589 says, saying this is not supported yet.

**Comment by TokyoScarab** [comment]
@msdmaguire Sounds good!  Thanks for the help!

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
