### ISSUE TITLE
Outgoing email address?

### ISSUE THREAD

**Issue by dilbertandwally** [MicrosoftDocs/OfficeDocs-Exchange#1359]
Hi,
I'm reading through this migration doc but it's not clear to me what happens to the outgoing external mails from users in the first batches of migration. Which address do they come from - is it the original, ie primary, address of user1@fabrikaminc.net? or the user1@o365fabrikaminc.net?
So when the first batch of users start using O365 what email address are their contacts receiving emails from?
Can anyone shed any light on this for me?
Thanks

**Comment by scanum** [comment]
@dilbertandwally Please link the document you are referring too. Thanks!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
