### ISSUE TITLE
Incorrect Exchange Server 2019 prerequisites

### ISSUE THREAD

**Issue by hq32x** [MicrosoftDocs/OfficeDocs-Exchange#136]
- Visual C++ 2013 components are required instead of C++ 2012
- PS cmdlet for installing Windows components does not work (invalid component for Windows 2019)
PS C:\Users\max.CONTOSO> Install-WindowsFeature AS-HTTP-Activation, Server-Media-Foundation, NET-Framework-45-Features,
RPC-over-HTTP-proxy, RSAT-Clustering, RSAT-Clustering-CmdInterface, RSAT-Clustering-Mgmt, RSAT-Clustering-PowerShell, We
b-Mgmt-Console, WAS-Process-Model, Web-Asp-Net45, Web-Basic-Auth, Web-Client-Auth, Web-Digest-Auth, Web-Dir-Browsing, We
b-Dyn-Compression, Web-Http-Errors, Web-Http-Logging, Web-Http-Redirect, Web-Http-Tracing, Web-ISAPI-Ext, Web-ISAPI-Filt
er, Web-Lgcy-Mgmt-Console, Web-Metabase, Web-Mgmt-Console, Web-Mgmt-Service, Web-Net-Ext45, Web-Request-Monitor, Web-Ser
ver, Web-Stat-Compression, Web-Static-Content, Web-Windows-Auth, Web-WMI, Windows-Identity-Foundation, RSAT-ADDS
Install-WindowsFeature : ArgumentNotValid: The role, role service, or feature name is not valid: 'AS-HTTP-Activation'.
The name was not found.
At line:1 char:1
+ Install-WindowsFeature AS-HTTP-Activation, Server-Media-Foundation, N ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (AS-HTTP-Activation:String) [Install-WindowsFeature], Exception
    + FullyQualifiedErrorId : NameDoesNotExist,Microsoft.Windows.ServerManager.Commands.AddWindowsFeatureCommand

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
False   No             InvalidArgs    {}

PS C:\Users\max.CONTOSO> Get-WindowsFeature *http*

Display Name                                            Name                       Install State
------------                                            ----                       -------------
        [X] Common HTTP Features                        Web-Common-Http                Installed
            [X] HTTP Errors                             Web-Http-Errors                Installed
            [X] HTTP Redirection                        Web-Http-Redirect              Installed
            [X] HTTP Logging                            Web-Http-Logging               Installed
            [X] Tracing                                 Web-Http-Tracing               Installed
    [ ] HTTP Activation                                 NET-HTTP-Activation            Available
    [ ] Non-HTTP Activation                             NET-Non-HTTP-Activ             Available
        [X] HTTP Activation                             NET-WCF-HTTP-Activat...        Installed
        [ ] HTTP Support                                MSMQ-HTTP-Support              Available
[X] RPC over HTTP Proxy                                 RPC-over-HTTP-Proxy            Installed

https://docs.microsoft.com/de-de/Exchange/plan-and-deploy/prerequisites?view=exchserver-2019

**Comment by AndreaBarr** [comment]
@hq32x Thank you for this feedback

I will get this investigated. 

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
