### ISSUE TITLE
What all does action "Update" include?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#1361]
Hello. I'm wondering if there is a list of actions that correspond to the "Update" action?  Ideally the action of an item becoming read or unread would be an update.

The reason I ask is that I've been asked how we can audit a mailbox that as been compromised in order to determine what all of the contents was seen.  In comparison with GroupWise, I've been given this link, which admittedly surpasses Exchange's mailbox audit capabilities, at least at a glance:

[Auditing GroupWise Account Activity](https://www.novell.com/coolsolutions/tip/9476.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6b7508-bf56-f95c-1e07-af74e7ac936d
* Version Independent ID: 0ff21c1c-2885-acda-8677-2789c60b2cd1
* Content: [Mailbox audit logging in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging?view=exchserver-2019#mailbox-actions-logged-by-mailbox-audit-logging)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@JeremyTBradshaw  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @JeremyTBradshaw, thank you for your feedback.

I don't have more information or another document for you, but "update" action includes operations like "Mark as read/unread" and retention settings for emails. Modify contact properties and meeting information.
But unfortunately I don't have an exhaustive list.

**Comment by JeremyTBradshaw** [comment]
@dariomws306 Thanks for the response.  In the end it was the MessageBind experimental audit action that I was after and hoping Update was.
