### ISSUE TITLE
New-MailboxDatabase  -EdbFilePath

### ISSUE THREAD

**Issue by 372979131** [MicrosoftDocs/OfficeDocs-Exchange#1365]
New-MailboxDatabase recdb  -Recovery:$true  -EdbFilePath "XXXX"
EdbFilePath must be local Path,Can,t use network driver,just lick NFS network driver?

In exchange New-MailboxDatabase params explanation not state This.Now I used a NFS network Driver to Create a new RDB,but show a ERR in EMS:
   FullyQualifiedErrorId : 75292D9B,Microsoft.Exchange.Management.SystemConfigurationTasks.NewMailboxDatabase

THere have some formal answer. 
Thanks.

**Comment by scanum** [comment]
@372979131 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
