### ISSUE TITLE
Improve Typo on OICE folders

### ISSUE THREAD

**Issue by nramouche** [MicrosoftDocs/OfficeDocs-Exchange#1366]
Page displays html conversion with useless backlash and space charater: "%SystemRoot%\Temp\OICE_ _\&lt;GUID\&gt;_\"
_\&lt;GUID\&gt;_\ is suppose to denote GUID such as examples from the Following article:
https://answers.microsoft.com/en-us/windows/forum/windows_7-files/unable-to-delete-oice-folders-from-temp-folder/ea01c8dd-298e-4683-932e-e4ddfb9812d4:
Example: %SystemRoot%\Temp\OICE_ea01c8dd-298e-468
== So there is no space after the first [OICE_]
== there is no backslah after the GUID
== and there is no [_\] or [\_] before and after the &lt;GUID&gt;
Hence the article may display: %SystemRoot%\Temp\OICE_&lt;GUID&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176e9cde-47cb-31b8-9ecf-51208888a740
* Version Independent ID: 97f0327a-5dba-d810-daeb-cd976b634c8b
* Content: [Running Windows antivirus software on Exchange servers](https://docs.microsoft.com/en-us/Exchange/antispam-and-antimalware/windows-antivirus-software?redirectedfrom=MSDN&view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@nramouche  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @nramouche, thank you for your feedback.

I am updating the article based on your feedback. I think there is an underscore after OICE. Example:
![image](https://user-images.githubusercontent.com/33589238/66245989-a87b5680-e6e7-11e9-92f3-732237b8efe1.png)

**Comment by scanum** [comment]
@nramouche Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by nskroger** [comment]
If adding this exclusion in an antivirus program, do you have to specify each GUID or is there a variable that will exclude all OICE_<GUID> entries if they change in the future?

**Comment by dariomws306** [comment]
Hi @nskroger, sorry but I don't have this information. I think you need to specify each GUID. Or probably in your antivirus you can apply this exclusion using wildcards, like OICE_*.
