### ISSUE TITLE
nonexistent commands: Get-PublicFolderMigrationRequest

### ISSUE THREAD

**Issue by chauzie** [MicrosoftDocs/OfficeDocs-Exchange#1368]
at least 2 commands Get-PublicFolderMigrationRequest & Get-PublicFolderMigrationRequestStatistics don't seem to exist.  
But there are Get-PublicFolderMailboxMigrationRequest & Get-PublicFolderMailboxMigrationRequestStatistics.

So the question is, are those commands equivalent? and that Microsoft doc hasn't been updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@chauzie  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @chauzie, thank you for your feedback.

Those cmdlets exist:
https://docs.microsoft.com/powershell/module/exchange/move-and-migration/get-publicfoldermigrationrequest
https://docs.microsoft.com/powershell/module/exchange/move-and-migration/get-publicfoldermigrationrequeststatistics

They were used for serial public folder migration. -PublicFolderMailboxMigrationRequest are for batch public folder migration.

**Comment by scanum** [comment]
@chauzie Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
