### ISSUE TITLE
Can't get example 1 working

### ISSUE THREAD

**Issue by mhingston** [MicrosoftDocs/OfficeDocs-Exchange#137]
I'm trying to create a rule to block attachments from a sender but it is blocking all emails from the sender as every email is coming through with a winmail.dat attachment (even plain text emails). How can I stop Outlook sending winmail.dat attachments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6db6edb-0ce9-5250-0e22-d42907394489
* Version Independent ID: 57d853a0-407f-01e5-4a6f-cdbaf7fa4fff
* Content: [Common attachment blocking scenarios for mail flow rules](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@mhingston Thank you for this feedback

I want to make sure you get the proper help blocking those attachments. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
