### ISSUE TITLE
AuthServer Names Incorrect (?)

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/OfficeDocs-Exchange#1374]
Newer versions of the Exchange Hybrid Configuration Wizard (latest version running on Exchange 2019 CU2) appear to create AuthServer objects with different values than what are specified in Step 1 of this article. Specifically, Step 1 recommends creating an AuthServer object named WindowsAzureACS, however the HCW creates one that is just named 'ACS':

[PS] C:\windows\system32&gt;Get-AuthServer | ft Name, AuthMetadataUrl

Name   AuthMetadataUrl
----   ---------------
ACS    https://accounts.accesscontrol.windows.net/&lt;GUID&gt;/metadata/json/1
EvoSts https://login.windows.net/hendrickson.onmicrosoft.com/federationmetadata/2007-06/federationmetadata.xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484887bf-a423-cb36-d8d1-712858e746bb
* Version Independent ID: c1df772a-5b5c-79d0-24fc-c89a09059497
* Content: [Configure OAuth authentication between Exchange and Exchange Online](https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help?redirectedfrom=MSDN#feedback)
* Content Source: [Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mhendric  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @mhendric, thank you for your feedback.

I think it's just the name so it's not very important. The important value here is AuthMetadataUrl.

**Comment by scanum** [comment]
@mhendric Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
