### ISSUE TITLE
misleading help text in "Add domain" step

### ISSUE THREAD

**Issue by WeiPinChai** [MicrosoftDocs/OfficeDocs-Exchange#1377]
in the "add domain" step, the help text on the right shows "Specify the fully qualified domain name. Example: myhost.contoso.com". This step is meant to add email domain name but the example used is misleading and may be misinterpreted as adding the sending server FQDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bfe7d75-e6b7-1e78-7978-5c84dcced8b1
* Version Independent ID: f41c0a31-2ae9-1ed6-5eea-40722f3bae6c
* Content: [Set up connectors for secure mail flow with a partner organization](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-for-secure-mail-flow-with-a-partner#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-for-secure-mail-flow-with-a-partner.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-for-secure-mail-flow-with-a-partner.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@WeiPinChai  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by WeiPinChai** [comment]
Hi,

Any updates on this?

Wei Pin
伟彬
+65 8200 1792

**Comment by dariomws306** [comment]
Hi @WeiPinChai, thank you for your feedback.

Are you talking about this screenshot?
![image](https://user-images.githubusercontent.com/33589238/66247187-77ebea80-e6f0-11e9-9b53-f7f85f72eadd.png)

**Comment by WeiPinChai** [comment]
Yes, specifically the misleading help text on the right that uses myhost.contoso.com

BR,
CWP

________________________________

**Comment by dariomws306** [comment]
Ok, thank you. I cannot take a new screenshot because it's live. Let me see what I can do for it.

@msdmaguire, what do you think about this issue? Could we report it?

**Comment by scanum** [comment]
@msdmaguire Following up on this? Thanks!

**Comment by scanum** [comment]
@msdmaguire Hi David! Wondering if there are any updates on this issue regarding the images and corrections? Thanks!

**Comment by msdmaguire** [comment]
Hi, sorry for the delay. I'm going to assign this to @mattpennathe3rd, and if his bandwidth allows an updated screen shot, great. However, the entire Exchange admin console is currently undergoing an update, so fixing older visuals is not a high priority right now.

**Comment by dariomws** [comment]
Hi @msdmaguire/@mattpennathe3rd, Could we close this issue? I think it was fixed in the new Admin Center:
![image](https://user-images.githubusercontent.com/33589238/79045098-a4bd1500-7bdf-11ea-88bc-57f68b270fef.png)

The issue was the popup message here:
![image](https://user-images.githubusercontent.com/33589238/79045064-82c39280-7bdf-11ea-82a1-f9a311046a80.png)

And, I understand that when the new Admin Center reaches GA these articles will be updated.

**Comment by mattpennathe3rd** [comment]
@dariomws Indeed, all of these screenshots will need to be scrapped; they either need to be updated to match the new EAC, or simply removed with the procedures modified accordingly.

I will close this issue now, but will be working in the (probably near) future on an inventory and update of all of these screenshots throughout the documentation set.
