### ISSUE TITLE
Use transport rules to inspect message attachments in eml/msg files

### ISSUE THREAD

**Issue by mrgoos** [MicrosoftDocs/OfficeDocs-Exchange#1378]
I read the [DOC](https://docs.microsoft.com/en-us/exchange/use-transport-rules-to-inspect-message-attachments-exchange-2013-help?redirectedfrom=MSDN) in `Use transport rules to inspect message attachments`.
In supported file types it doesn't state that it supports eml files.
Is it? Is it planned?
Thanks.

**Comment by scanum** [comment]
@mrgoos  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @mrgoos, thank you for your feedback.

I think it's not planed. If you think it's important I can suggest that you request this feature in the next link:
https://office365.uservoice.com/

**Comment by scanum** [comment]
@mrgoos Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mrgoos** [comment]
@scanum - thanks but it hasn't been resolved.
`suggest that you request this feature` is not really a resolution.

**Comment by dariomws306** [comment]
@mrgoos docs.microsoft.com feedback is available to provide your comments to improve/update documentation.
The right place to request new features is User Voice and for support you should open a support ticket.

Eml files aren't supported so if you want to request to add it you should go to User Voice.

Thank you for understand.

**Comment by mrgoos** [comment]
Got it @dariomws306 - can you please help me choose which forum should I put my voice in?
![image](https://user-images.githubusercontent.com/2561935/68541699-a1f99200-03ab-11ea-8181-dbfbab8c5201.png)

Thanks.

**Comment by dariomws306** [comment]
You can try "General" or "Office 365 Admin".

**Comment by mrgoos** [comment]
As you can see I couldn't find help [here](https://github.com/MicrosoftDocs/feedback/issues/2674).
Could you please LMK where can I go with this? Why is it so complicated?
Just a DIRECT link will do if you don't want to take care of it by yourself.

**Comment by dariomws** [comment]
Hi @mrgoos, I sent you the link to user's voice. This is the place where people can create/request a new idea/features:
https://office365.uservoice.com/

I can help you if you think we can improve an article in docs.microsoft.com.

**Comment by mrgoos** [comment]
Thanks, opened in `Office 365 Admin`.
