### ISSUE TITLE
Problematic cmdlets in "Use batch migration to migrate legacy public folders to Office 365 and Exchange Online"

### ISSUE THREAD

**Issue by svajda** [MicrosoftDocs/OfficeDocs-Exchange#1379]
In step 2/5, running

`Get-PublicFolder -Recurse -ResultSize Unlimited | Get-PublicFolderClientPermission | Select-Object Identity,User -ExpandProperty AccessRights | Export-CliXML C:\PFMigration\Legacy_PFPerms.xml`

will not export all required fields. The result only contains the fields "Permission" and "IsRole". To get all desired fields exported, you can run e.g. 

`Get-PublicFolder -Recurse -ResultSize Unlimited | Get-PublicFolderClientPermission | Select-Object Identity,User,AccessRights | Export-CliXML C:\PFMigration\Legacy_PFPerms.xml`

The same applies to the permission snapshot cmdlet later in the document, in section "How do I know this worked".

In step 8/6, the cmdlet is incorrect:

`Get-Mailbox -ResultSize unlimited | %{Set-Mailbox $_.UserPrincipalName -PublicFolder -IsExcludedFromServingHierarchy $False}`

as this would try to process all mailboxes in the tenant, not just public folder mailboxes. The correct syntax should be 

`Get-Mailbox -PublicFolder -ResultSize unlimited | %{Set-Mailbox $_.UserPrincipalName -PublicFolder -IsExcludedFromServingHierarchy $False}` 

In the section "How do I know this worked?", the syntax is incorrect:

`Get-PublicFolderStatistics -ResultSize Unlimited | Export-CliXML C:\PFMigration\Cloud_PFStatistics.xml`

The cmdlet "Get-PublicFolderStatistics" has no -ResultSize parameter in Exchange Online. The -ResultSize parameter should be omitted from the syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@svajda  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @svajda, thank you for your feedback.

I am not agree with the first one, ExpandProperty give more information about permissions.

I am fixing the others.

Thanks!

**Comment by svajda** [comment]
Hi @dariomws306, thanks for the update and the fixes. 
As for the first one, indeed you are right that using -ExpandProperty will export all permissions in detail to the XML file. However, in that case, is there any special syntax required to import that information back? If I just import the data using Import-CliXml into a variable, only the Permission and IsRole fields are available, while Identity and User are missing.

**Comment by dariomws306** [comment]
@svajda in the article I understand that the purpose of the export is to compare permissions to check if they were migrated successfully.

If you need an export/import process you can check this article:
https://blogs.technet.microsoft.com/mukutdas/2014/06/27/export-public-folder-permission-in-exchange-2010/

**Comment by scanum** [comment]
@svajda Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
