### ISSUE TITLE
TooManyTransientFailureRetries

### ISSUE THREAD

**Issue by rlai-royalscenic** [MicrosoftDocs/OfficeDocs-Exchange#1380]
Suddenly since yesterday, all migration batches have this error:
Error: TooManyTransientFailureRetriesPermanentException/ServerInMMException: Error: The job encountered too many transient failures ‎(62)‎ and is quitting. The most common failure is ServerInMMException with the hit count 60. --> The domain controller ‎'YQBPR01A004DC10.CANPR01A004.PROD.OUTLOOK.COM‎' is not available for use at the moment. Please try again.

Anything I could do?

Thanks
Rlai

**Comment by scanum** [comment]
@rlai-royalscenic 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
