### ISSUE TITLE
Attached script file still has the old AzureRM commands listed.

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/OfficeDocs-Exchange#1383]
Just under Phase 1 is a link to a download but this uses the old AzureRM commands and not the az ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45c04a0-138f-8241-0726-01fb09c3dfeb
* Version Independent ID: 730303a8-9c6f-472c-79f6-96453dea3013
* Content: [Exchange dev/test environment in Azure](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments?redirectedfrom=MSDN&view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Absoblogginlutely  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Absoblogginlutely, thank you for your feedback.

If I am not wrong the Azure cmdlets in this article are from the Az module. For example:
Connect-AzAccount
Get-AZSubscription
New-AZResourceGroup

**Comment by Absoblogginlutely** [comment]
That's correct, but the file that is linked to in the github document does not match the content of the document in github. See screenshot attached for the differences
![Screenshot - 10_8_2019 , 10_06_14 AM](https://user-images.githubusercontent.com/21364480/66402871-96353d00-e9b3-11e9-8d25-bba3fc609e2c.png)

Therefore the script needs to be rewritten to match the github document or the link to the script removed

**Comment by dariomws306** [comment]
@Absoblogginlutely thanks! Understand now. I don't have access to update this script so our best option is remove it.
Working on it.

**Comment by scanum** [comment]
@Absoblogginlutely Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
