### ISSUE TITLE
Missing reference for alternate download location

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/OfficeDocs-Exchange#1385]
This page lacks a reference to https://support.microsoft.com/en-us/help/2292741 which has just been republished. This page outlines how to download the antimalware updates from a non-Exchange server and stage them for non-internet connected Exchange servers so that they can keep their engines updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c17f081-e6e6-b579-e273-a17de4374114
* Version Independent ID: 3de7306a-5de2-f21a-23d6-f9f85aa6bd63
* Content: [Download antimalware engine and definition updates](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antimalware-protection/download-antimalware-updates?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/download-antimalware-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/download-antimalware-updates.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@vboyev-MSFT  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@vboyev-MSFT Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
