### ISSUE TITLE
CU 14 is missing from this page

### ISSUE THREAD

**Issue by NebulaMillennium** [MicrosoftDocs/OfficeDocs-Exchange#1386]
Exchange 2016 CU 14 was release Sep. 17 and it not listed on this page (https://docs.microsoft.com/en-us/exchange/new-features/updates?view=exchserver-2016). It should be and should include this blog post link: https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Released-September-2019-Quarterly-Exchange-Updates/ba-p/853699

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e347ab3f-fef7-a92e-4154-3c9c387bdc94
* Version Independent ID: e82d79ce-c0f2-bafd-3e18-c1bd1a1ae8cd
* Content: [Updates for Exchange Server, Cumulative Updates for Exchange Server, Exchange Server 2016 CU, Cumulative Update Exchange 2016](https://docs.microsoft.com/en-us/exchange/new-features/updates?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/new-features/updates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/updates.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
Updated. In the future, if you want to make updates like this yourself, feel free to do so (it's really no more difficult to actually make the update than it is to open an issue). For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md

Thanks for the feedback.
