### ISSUE TITLE
The custom user role assignment is not helpful for Outlook App for Android

### ISSUE THREAD

**Issue by Navesai** [MicrosoftDocs/OfficeDocs-Exchange#1388]
The custom user role assignment is not helpful for Outlook App for Android.
What is procedure to stop Outlook Android App users to add outlook add-ins ?

Thanks,
Naveen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86c9e05-c68b-8f00-3a94-c902d3352590
* Version Independent ID: e299bde7-ee34-96eb-b7f3-2ae75db017d3
* Content: [Specify the administrators and users who can install and manage add-ins for Outlook](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Navesai  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws306** [comment]
Hi @Navesai, thank you for your feedback.

@msdmaguire could you confirm this?

This article (last question):
https://www.microsoft.com/microsoft-365/blog/2017/09/08/your-favorite-apps-now-in-outlook-on-android/
Redirect you to this:
https://docs.microsoft.com/ffice365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide
And the last one redirect you to:
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins?redirectedfrom=MSDN

But looks like it doesn't work.

Thanks!

**Comment by msdmaguire** [comment]
I reached out to the sme on this, stay tuned.

**Comment by smithre4** [comment]
Hi @Navesai - the instructions as outlined do work. However, there is a currently a different in implementation on Outlook Android vs. iOS. in Outlook iOS, the user is told the administrator has blocked add-ins. In Outlook Android, the add-ins are still shown, but when a user attempts to install them, they get an error "Failed to update status. Please try again.". We are investigating improvements in this area.

**Comment by scanum** [comment]
@Navesai Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
