### ISSUE TITLE
dead link - this needs to be updated to reflect cu 23

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1389]
"To get the latest version of Exchange 2013, download and install Microsoft Exchange Server 2013 Cumulative Update 21"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97114e1-a2f9-058c-770c-ca2cf297972a
* Version Independent ID: 28933a4c-6af5-7045-6f20-d0e78a974055
* Content: [Updates for Exchange 2013: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/updates-for-exchange-2013-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/updates-for-exchange-2013-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/updates-for-exchange-2013-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
Updated. In the future, if you want to make updates like this yourself, feel free to do so (it's really no more difficult to actually make the update than it is to open an issue). For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md
Thanks for the feedback.
