### ISSUE TITLE
wrong .net version

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1390]
the current version of exchange 2013 requires .net 4.7.2, not 4.7.1 per the above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bab99a4-8e7f-5273-7c20-5307fb93d8f4
* Version Independent ID: 9c316be5-5cd9-2ade-bbde-b9c7a27d07ed
* Content: [Exchange 2013 prerequisites: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/exchange-2013-prerequisites-exchange-2013-help#windows-server-2012-r2-and-windows-server-2012-prerequisites)
* Content Source: [Exchange/ExchangeServer2013/exchange-2013-prerequisites-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/exchange-2013-prerequisites-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
OK. Fixed. Thanks for the feedback.

**Comment by Mike-Crowley** [comment]
It looks like the hyperlink goes to an older version of .Net


-Mike Crowley

________________________________

**Comment by chrisda** [comment]
Fixed again.
