### ISSUE TITLE
incorrect instruction for Exchange 2016

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-Exchange#1394]
incorrect instruction for Exchange 2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f56ca9b1-45f9-637f-8c3e-fc2c3e82bc0a
* Version Independent ID: 7ae744e3-f0b1-5e9b-855f-16246f6f7a85
* Content: [Enable and configure IMAP4 on an Exchange server](https://docs.microsoft.com/en-us/exchange/clients/pop3-and-imap4/configure-imap4?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/clients/pop3-and-imap4/configure-imap4.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/pop3-and-imap4/configure-imap4.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@copenhaus Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by chrisda** [comment]
@copenhaus, can you elaborate further on what's wrong?

**Comment by copenhaus** [comment]
there's no "Settings > Options > Mail > Accounts > POP and IMAP" in Exchange 2016

**Comment by chrisda** [comment]
I just checked in 'regular' OWA (not OWA light) on a 2016 server, and that path definitely exists as documented:

![image](https://user-images.githubusercontent.com/33166947/66154870-4f220300-e5d3-11e9-8db0-5efbb8c7955a.png)

Are you seeing something different?

**Comment by copenhaus** [comment]
![2019-10-03_13-17-16](https://user-images.githubusercontent.com/25488700/66161058-556aac00-e5e0-11e9-9f6f-a0ee8f6abcd6.png)

**Comment by chrisda** [comment]
Settings > Options > Mail > Accounts > POP and IMAP is in OWA, not the EAC. From the topic:

This step causes the external IMAP4 settings to be displayed **in Outlook on the web (formerly known as Outlook Web App)** at Settings > Options > Mail > Accounts > POP and IMAP.

**Comment by copenhaus** [comment]
I see what's wrong now...we are in the middle of Exch 2010 -> 2016 migration...using OWA does nothing for me...that's why I found the IMAP settings in EAC.

**Comment by scanum** [comment]
@copenhaus Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
