### ISSUE TITLE
Clarification On Schema Updates Required Table

### ISSUE THREAD

**Issue by PaulRNewell** [MicrosoftDocs/OfficeDocs-Exchange#1396]
Hi there, 
In looking at the table with the leading columns "_Current Exchange 2016 release installed_", "_New Exchange 2016 release being installed_", and "_Are schema updates required?_", I believe that the data in the bottom row needs to be updated to reflect the current cumulative updates, and since there were no updates to the schema in CUs 11, 12, 13, or 14.
Specifically, I think that the "_New Exchange 2016 release being installed_" block should be updated from "Cumulative Update 8 through Cumulative Update 11" to "Cumulative Update 8 through Cumulative Update **14**", and the "_Are schema updates required?_" block should be updated from "No, no schema updates are required. No schema changes are made in CU8 through CU11." to "No, no schema updates are required. No schema changes are made in CU8 through **CU14**.". 

Thanks for your time and support!

**Comment by scanum** [comment]
@PaulRNewell Please link the document you are referring to. Thanks

**Comment by PaulRNewell** [comment]
Sorry, I clicked "Open issue" on the Github issues page itself; I must have run into some weirdness when logging in.
The page in reference is here: https://docs.microsoft.com/en-us/exchange/plan-and-deploy/active-directory/ad-schema-changes?view=exchserver-2016
The GitHub issues list for that page appears to be here: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues?utf8=%E2%9C%93&q=%22bcf47ac1-4b6e-e333-1b25-354e4cf88e8a%22&in=body

**Comment by PaulRNewell** [comment]
Sorry, I thought I posted this yesterday...
When I posted my original issue, I thought I did it from the actual issues list of the page in question, but maybe I was redirected when I logged into github. In any event, I apologize for any confusion. 

The article is here: https://docs.microsoft.com/en-us/exchange/plan-and-deploy/active-directory/ad-schema-changes?view=exchserver-2016
And the issues page for it is here: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues?utf8=%E2%9C%93&q=%22bcf47ac1-4b6e-e333-1b25-354e4cf88e8a%22&in=body

**Comment by thmeyer-msft** [comment]
@scanum Hi Manuela, please see pull request #1423 as fix for this issue 😃

**Comment by scanum** [comment]
@PaulRNewell Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
