### ISSUE TITLE
Exchange ActiveSync - Update label of commands

### ISSUE THREAD

**Issue by jtnnguyen** [MicrosoftDocs/OfficeDocs-Exchange#1399]
I understand Outlook for iOS & Android only supports the "Wipe Data" and not the "Account Only Remote Wipe Device." However, can we update the label of the commands? This can be confusing when used interchangeably on native and non native email apps.

https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/manage-devices?view=exchserver-2019

**Comment by scanum** [comment]
@jtnnguyen  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
I've created a PR with #1760 for this issue

**Comment by mattpennathe3rd** [comment]
@jtnnguyen Thank you for filing this. I've submitted a substantial fix for this issue that I hope will clarify things. It should be published in the near future. Please let me know if you have any further feedback.

**Comment by jtnnguyen** [comment]
Can you please update me as soon as we have it published?

Thank you!

--
Jennifer Nguyen
Technical Account Manager, Healthcare & Life Sciences
209-406-5288 |jennifer.nguyen@microsoft.com
Microsoft
________________________________

**Comment by mattpennathe3rd** [comment]
@jtnnguyen Another team handles the publishing task, but it should be up by Friday afternoon. I'll follow up with you shortly.

**Comment by mattpennathe3rd** [comment]
@jtnnguyen The changes are now live! Please have a look and see if this helps. I'm glad to make further edits if you think things can be clarified. I also updated a handful of other articles that spoke to this topic and made sure they are all consistent.
