### ISSUE TITLE
kinarachelle@gmail.com

### ISSUE THREAD

**Issue by GitHubNicole** [MicrosoftDocs/OfficeDocs-Exchange#140]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4e18b1-5821-73a0-eef8-5cdafb3b8401
* Version Independent ID: b3534855-b60a-797f-4d65-65b514397ab5
* Content: [Create and manage distribution groups](https://docs.microsoft.com/en-za/exchange/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by AndreaBarr** [comment]
@GitHubNicole Is there an issue you want to post here or is this a test issue?
