### ISSUE TITLE
Confused about "Internal messages only" scope

### ISSUE THREAD

**Issue by capnbab** [MicrosoftDocs/OfficeDocs-Exchange#1400]
Isn't it more accurate to say:
Internal messages only: The source AND destination of the message is inside your Exchange organization.

If it were true that to be considered "Internal" only requires either the source OR the destination to be inside your Exchange organization, that would pretty much be the same as "All messages" I would think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cb6771-88cb-6bd3-98de-5872ab18c913
* Version Independent ID: e83303f6-9fe0-809d-68ba-b8a493fdd40e
* Content: [Journaling in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/journaling/journaling?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/journaling/journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/journaling/journaling.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@capnbab  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by chrisda** [comment]
Yeah, I can se the confusion around the terms 'source' and 'destination'.

The journal recipient (who you want to journal) is the key element in the journal rule. It could be a single user, members of a group, or everyone in the org. The journal recipient is the point-of-view or perspective of the rule: messages sent TO the journal recipient by others (the message source) and messages sent FROM the journal recipient to others (the message destination) are journaled. So really, the journal recipient could be called 'the journal sender/recipient': direction doesn't matter, it's the person themselves that are important.

So, based on that explanation, 'Internal' means:

- The message is FROM another internal sender TO the journal recipient (source is internal)

or

- The message is FROM the journal 'recipient' (sender, in this case) TO another internal recipient (destination is internal).

Does this explanation help? Can use suggest any updates to the text that would help clarify?

**Comment by capnbab** [comment]
Thank you much, that explanation is helpful. I understand it better now and
it functions as I would expect. I missed the part about the implicit
perspective being that of the journal 'recipient'.

**Comment by scanum** [comment]
@capnbab Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
