### ISSUE TITLE
PublicFolderMigrationRequest cmdlets are no longer availble

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/OfficeDocs-Exchange#1401]
This document includes the following:

> The following example will discover any existing serial migration requests.
> 
> Get-PublicFolderMigrationRequest | Get-PublicFolderMigrationRequestStatistics -IncludeReport | Format-List
> The following example removes any existing public folder serial migration requests.

> The following example removes any existing public folder serial migration requests.
> 
> Copy
> Get-PublicFolderMigrationRequest | Remove-PublicFolderMigrationRequest

However, both Get/Remove-PublicFolderMigrationRequests (and also PublicFolderMigrationRequestsStatistics) are no longer available. 

**Reference:**
[Get-PublicFolderMigrationRequest](https://docs.microsoft.com/en-us/powershell/module/exchange/move-and-migration/get-publicfoldermigrationrequest?view=exchange-ps)

> Serial public folder migration cmdlets are no longer available in Exchange Online.

I believe PublicFolder**Mailbox**MigrationRequest is adequate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@hishikitetsuya Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Worked on PR #1761

**Comment by mattpennathe3rd** [comment]
@hishikitetsuya Thank you for filing this issue. I'm sorry for the delay in addressing this, but this appears to have been fixed by prior edits to this article and should be no problem now. Thank you again for reporting this.
