### ISSUE TITLE
/owa does not redirect to https

### ISSUE THREAD

**Issue by cjg88** [MicrosoftDocs/OfficeDocs-Exchange#1408]
Using /owa in step 3 does not redirect to https. It must have the absolute path to /owa including https (i.e. https://mail.contoso.com/owa).

**Comment by scanum** [comment]
@cjg88 could you please linked issue you are referring to?

**Comment by mattpennathe3rd** [comment]
@cjg88 Following up on this issue. If you're able to, could you please link to the page that you are referring to so I can correct this problem? Thank you very much.

**Comment by scanum** [comment]
@cjg88 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
