### ISSUE TITLE
Cmdlet parameter "ManagedFolderWorkCycle" not applicable to Exchange 2016

### ISSUE THREAD

**Issue by svajda** [MicrosoftDocs/OfficeDocs-Exchange#1409]
Steps 4 and 7 are not appropriate for Exchange 2016/2019. The "ManagedFolderWorkCycle" parameter does not exist in these versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5010fa-a741-a1b1-979d-48e6f61fa5de
* Version Independent ID: b231b1d9-4ff5-d245-f3d2-32cbaecbb66d
* Content: [Clean up or delete items from the Recoverable Items folder](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/recoverable-items-folder/clean-up-deleted-items?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/recoverable-items-folder/clean-up-deleted-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/recoverable-items-folder/clean-up-deleted-items.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@svajda Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Added PR #1795  
@scanum  Please link the authors to solve the listing on this article on On-premises 2013 instead of 2016 or 2019.

**Comment by mattpennathe3rd** [comment]
This one will likely need some further rewriting, but I have reached out to get feedback.

**Comment by chrisda** [comment]
@svajda, the topic has been updated with appropriate instructions (stop and start the Microsoft Exchange Mailbox Assistants (MSExchangeMailboxAssistants) service.

Thanks for the feedback.

Closing
