### ISSUE TITLE
Rmb blocked my messages

### ISSUE THREAD

**Issue by GitHubNicole** [MicrosoftDocs/OfficeDocs-Exchange#141]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b002f0ce-5397-15cb-4c60-0eaaa87aaf52
* Version Independent ID: 32e3a594-2d2c-9f8a-9a38-e60e3ffaae85
* Content: [Transport routing in Exchange hybrid deployments](https://docs.microsoft.com/en-za/exchange/transport-routing)
* Content Source: [Exchange/ExchangeHybrid/transport-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/transport-routing.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by GitHubNicole** [comment]
[Gmail - Credit Risk.pdf](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/files/2431481/Gmail.-.Credit.Risk.pdf)
[Gmail - Credit Risk.pdf](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/files/2431483/Gmail.-.Credit.Risk.pdf)
[termsConditionsConsumer.pdf](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/files/2431484/termsConditionsConsumer.pdf)

**Comment by AndreaBarr** [comment]
@GitHubNicole Thank you for this feedback

I want to make sure your blocked email issue gets addressed promptly. Support can handle this to resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
