### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by JamieWilsonOurIT** [MicrosoftDocs/OfficeDocs-Exchange#1410]
> Once the domain type has been changed to Authoritative, DBEB is designed to allow any SMTP address that has been added to the service (except for mail-enabled public folders)

This is broken. If Mail-Enabled Public Folders are in the environment, the domain needs to remain as an “Internal relay” even if it is not hybrid.
If not, you get “550 5.4.1 [<InvalidAlias>@\<Domain>]: Recipient address rejected: Access denied.”
There is a lot of talk about this:
https://answers.microsoft.com/en-us/msoffice/forum/all/public-folders-stop-receiving-mails-with-reason/48e837fd-6fa2-450b-b5e6-f1278e2643ad

**Comment by j0rt3g4** [comment]
Added PR #1814

**Comment by mattpennathe3rd** [comment]
@JamieWilsonOurIT Thanks for filing this issue. DBEB does not support mail-enabled public folders that are hosted in Exchange Online, but it does work as it should for on-premises mail-enabled public folders. I've updated the article to make this caveat clearer and the changes should be published in the near future.

Please let me know if there is an angle to this that I am missing.
