### ISSUE TITLE
wrong subnet

### ISSUE THREAD

**Issue by matteoclc** [MicrosoftDocs/OfficeDocs-Exchange#1414]
In the first table the subnet mask for the replication interfaces of the mbx servers should be /24 instead of /16.
Having a /16 subnet means that you're using some sort of layer 2 spanning technology across the 2 datacenter (or any other) and this makes the static routes useless

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21463006-549e-1005-e429-ac918d7fec8b
* Version Independent ID: b247ea5e-2c1a-cab6-e5d0-c80290b892f4
* Content: [Exchange high availability, Exchange high availability step by step, Exchange site resilience, Site resilience Exchange, High availability for Exchange, High availability Exchange Server, Exchange DAG high availability, High availability DAG](https://docs.microsoft.com/en-us/exchange/high-availability/deploy-ha?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/high-availability/deploy-ha.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/deploy-ha.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@matteoclc Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by smcirvin** [comment]
I totally agree, the subnet should be 255.255.255.0.

**Comment by j0rt3g4** [comment]
Added PR #1815

**Comment by mattpennathe3rd** [comment]
@matteoclc @smcirvin Thank you for pointing this out! This has been correct and the updated article will be published shortly.
