### ISSUE TITLE
Using gMSA accounts

### ISSUE THREAD

**Issue by SuperFlue** [MicrosoftDocs/OfficeDocs-Exchange#1416]
I have been looking up and down, left and right, but I'm unable to find any documentation on using gMSA accounts for this scenario instead of a computer account.
To me this seems like the exact scenario gMSA accounts are made for....

However since MSA accounts do password management automatically the script to install the ASA account does not seem entirely applicable?

If there is a reason not to use gMSA accounts for this it would be very helpful for this to be noted in the article.
And if it is supported, please provide an example of how you would install the service account properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f017fd21-0284-df8b-145c-6d9ce21d01f1
* Version Independent ID: 57e366b8-5a87-e9c6-7527-009105dc9672
* Content: [Configure Kerberos authentication for load-balanced Client Access services](https://docs.microsoft.com/en-us/exchange/architecture/client-access/kerberos-auth-for-load-balanced-client-access?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/kerberos-auth-for-load-balanced-client-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/kerberos-auth-for-load-balanced-client-access.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SuperFlue Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by SuperFlue** [comment]
I have dug down into this myself a bit now, and i think i might have a working procedure.
But I don't have a test environment right now to try I out in....

Note that this is not meant to run as a single script and has no error checks.  
They are just working notes.  
````powershell
## Create ASA Account

# Create gMSA account and allow servers in the AD-group "Exchange Servers" access to it
# Note account name will be "exchangeASA"
New-ADServiceAccount -DNSHostName "mail.contoso.com" -Name "exchangeASA" -KerberosEncryptionType AES128,AES256 -PrincipalsAllowedToRetrieveManagedPassword (Get-ADGroup -Identity "Exchange Servers") -SamAccountName "exchangeASA" -Description "Service account for Exchange servers to allow Kerberos authentication"


# Set gMSA account on servers
# Create Credentials object with blank password
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "contoso\exchangeASA$",(new-object System.Security.SecureString)
# Get CAS servers and clear old ASA credentials
Get-ClientAccessService | Set-ClientAccessService -RemoveAlternateServiceAccountCredentials -CleanUpInvalidAlternateServiceAccountCredentials -Verbose
# Get CAS servers and add gMSA as ASA credential
Get-ClientAccessService | Set-ClientAccessService -AlternateServiceAccountCredential $Credential -Verbose

# Verify ASA credential deployment
Get-ClientAccessService -IncludeAlternateServiceAccountCredentialStatus | Format-List Name, AlternateServiceAccountConfiguration

# Set internal Auth method to "Negotiate" as this supports both NTLM and Kerberos
Get-OutlookAnywhere | Set-OutlookAnywhere -InternalClientAuthenticationMethod Negotiate

# Pre-check if the SPN are in use (checks all AD-objects).
Get-ADObject -Filter '(servicePrincipalName -like "http/mail.contoso.com") -or (servicePrincipalName -like "http/autodiscover.contoso.com")' -Properties servicePrincipalName | Select-Object Name,servicePrincipalName

# Set SPN
Set-ADServiceAccount -Identity "exchangeASA" -ServicePrincipalNames "http/mail.contoso.com","http/autodiscover.contoso.com"
# Check afterwards that SPN are assigned
Get-ADServiceAccount -Identity "exchangeASA" -Properties servicePrincipalName | Select-Object Name,servicePrincipalName


## Restart services
# Restart Client Access Service webpool and Service
Foreach ($CASExchangeHost in (Get-ClientAccessService).name){
    Invoke-Command -ComputerName $CASExchangeHost -ScriptBlock {
        Restart-WebAppPool -Name MSExchangeAutodiscoverAppPool 
        Restart-Service MSExchangeServiceHost -Force
    } 
}
````

**Comment by j0rt3g4** [comment]
Added PR in #1816

**Comment by mattpennathe3rd** [comment]
@SuperFlue Thanks very much for contributing back, but after checking with our teams internally, gMSA accounts are not a supported or tested scenario in on-premises Exchange Server environments. I will look at this article to see if I can add a note to that effect so other users are aware in the future and don't get frustrated by this.

Thank you again for opening the issue.
