### ISSUE TITLE
Does Option 3 require an on prem email server?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#1420]
The instructions for setting up an SMTP relay for Option 3 state that a connector needs to be setup.  The details show setting up a connector "from your organization's email server."  Well, what if you don't have an email server?  What if you use O365 as your sole email provider?  How do you setup a connector then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by agent6426** [comment]
Check the link directly above 'Feedback,' 'How to configure IIS for relay with Office 365.' You do not need an internal mail server, only an SMTP relay, which may be installed on any server. You'll be required to install the IIS role to gain access to an SMTP relay.

**Comment by Canis-Lupis** [comment]
@agent6426, that's not what the instructions here show.  Step-by-step instructions specifically mention email connector, not IIS.  

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#step-by-step-configuration-instructions-for-smtp-relay

While I can certainly install an IIS connector, there's nothing listed here that mentions how to use it.  Again, the instructions here mention "Your organization's email server"  If IIS can be used, then there should be a section "Using your IIS SMTP Relay."

**Comment by brianedwards71** [comment]
Login to the Office 365 Admin site. Click the "... Show all" link in the left menu. Under Admin Centers click Exchange. In Exchange Admin Center click Mail Flow then Connectors. Setup a new connector following the instructions in the article above.

**Comment by j0rt3g4** [comment]
The definition of an SMTP relay is basically that you have some kind of sort of email server internally and then you're going to be sending them out using O365.

If you do have only O365 as the only email provider you can use any licensed user or just a shared mailbox to send out emails after resetting its password.

**Comment by scanum** [comment]
@Canis-Lupis 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis I wanted to verify that the comments on this issue have clarified the doc for you. Do you still have feedback on this article?
