### ISSUE TITLE
Enable API usage in your project

### ISSUE THREAD

**Issue by jidhiar** [MicrosoftDocs/OfficeDocs-Exchange#1421]
Under
Enable API usage in your project
If your project doesn't already have all of the required APIs enabled, you must enable them.

Go to the Developer page for API Library and sign in as the Google user you used above in Create a Google Service Account.

How do I sign in using the google service account? What credentials shall I use ?  I created a service account - @xxx.iam.gservice.com, if I use that email address to sign in, I do not know the password to use, since it was never generated.

**Comment by scanum** [comment]
@jidhiar thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jidhiar** [comment]
So we are in initial stages and hence not started the migration yet.  We
are at a point to configure the Gsuite tenant and wanted some guidance
about that -

Enable API usage in your project
<https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#enable-api-usage-in-your-project>

If your project doesn't already have all of the required APIs enabled, you
must enable them.

   1.

   Go to the Developer page for API Library
   <https://console.developers.google.com/apis/library> and sign in as the
   Google user you used above in Create a Google Service Account.

When you say sign in as the Google user, what type of credentials are you
looking for? How do we generate the credentials for the service account?
