### ISSUE TITLE
The description & commands of Exchange 2010 are incorrect

### ISSUE THREAD

**Issue by Yutaka-Naito** [MicrosoftDocs/OfficeDocs-Exchange#1425]
The chapter "Exchange 2010" in this article includes some mistakes.

The msExchRecipientDisplayType value -1073741818 should only be set to user mailboxes, not for resources.
The value includes some flags that the object is usermailbox, which is not appropreate for other types of mailboxes.

**[Incorrect]**
"Exchange 2010 SP3 servers support the configuration of ACLs on remote mailboxes, however, this configuration needs to be set manually on each mailbox."
"You need to follow the steps below on any mailboxes that you've previously moved to Office 365, and on any mailboxes that will be moved from an Exchange 2010 SP3 server to Office 365 in the future."

**[Correct]**
"Exchange 2010 SP3 servers support the configuration of ACLs on remote mailboxes, however, this configuration needs to be set manually on each **user** mailbox."
"You need to follow the steps below on any **user** mailboxes that you've previously moved to Office 365, and on any **user** mailboxes that will be moved from an Exchange 2010 SP3 server to Office 365 in the future."

**[Incorrect]**
These commands may change all types of mailbox.

commandlet 2:
Get-AdUser &lt;Identity&gt; | Set-AdObject -Replace @{msExchRecipientDisplayType=-1073741818}

commandlet 3:
Get-RemoteMailbox -ResultSize unlimited | ForEach {Get-AdUser -Identity $_.Guid | Set-ADObject -Replace @{msExchRecipientDisplayType=-1073741818}}

**[Correct]**
commandlet 2:

Get-AdUser &lt;**UserMailbox's** Identity&gt; | Set-AdObject -Replace @{msExchRecipientDisplayType=-1073741818}

commandlet 3:

Get-RemoteMailbox -ResultSize unlimited | **Where-Object{$_.RecipientTypeDetails -eq "RemoteUserMailbox"}** | ForEach {Get-AdUser -Identity $_.Guid | Set-ADObject -Replace @{msExchRecipientDisplayType=-1073741818}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Yutaka-Naito Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Added all suggestion on PR #1513

**Comment by mattpennathe3rd** [comment]
Appears to be fixed in https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1513. Closing this issue as done!
