### ISSUE TITLE
IMAP synchronisation architecture

### ISSUE THREAD

**Issue by lucianf** [MicrosoftDocs/OfficeDocs-Exchange#1429]
When using IMAP4 (with a non-Exchange server), does the Outlook app sync directly with the server, or are credentials synced with an intermediate, Microsoft-owned, cloud-based service that handles the syncing?  In other words, is any data stored at rest outside the Outlook app in this case?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook Exchange Online FAQ, Outlook for iOS Exchange FAQ, Outlook for Android FAQ, Outlook for iOS security concerns, Outlook for Android security concerns, Outlook for iOS cloud architecture, Outlook for Android cloud architecture, Outlook app Office 365 architecture, Outlook app attachment faq, Outlook app contacts faq, Outlook app license faq](https://docs.microsoft.com/en-gb/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@lucianf Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
hello @lucianf 

When you are using Outlook app the credentials are stored by the operating system where you're working on on the "credential manager" :
![image](https://user-images.githubusercontent.com/5489996/68457452-f2af9600-01c5-11ea-8e1e-cb7f3c39bdd8.png)

So they are not stored on Server's site or by OWA on any place by security reasons.

**Comment by lucianf** [comment]
Thanks @j0rt3g4. Well my question was specifically about Outlook for iOS, not OWA or Windows Outlook

I guess I was expecting the opposite answer: since the app shows notifications for incoming emails, presumably these are push notifications sent from a cloud service and not produced locally by the phone app.  Following that logic, the said cloud service would need to be able to continuously authenticate and poll the IMAP server, hence the credentials would have to be stored in the cloud.  This seems to be the original design of the Acompli app on which Outlook for iOS was built, but I don't know if the architecture mentioned [in this blog post from 2015](https://blog.winkelmeyer.com/2015/01/warning-microsofts-outlook-app-for-ios-breaks-your-company-security/) is still valid today.

Can you please confirm if that is the case?

**Comment by j0rt3g4** [comment]
Ok, got it, I'm pretty sure @lucianf  it should have been changed. @scanum let's please tag the author to make sure he can say yes or no to that question @msdmaguire.

**Comment by lucianf** [comment]
I am pretty sure it's the other way round. I can't think of a way you could do push notifications unless you read the emails through a cloud service.  The device itself cannot possibly be sending the notifications to itself.

See [this more recent article](https://4sysops.com/archives/is-microsofts-outlook-app-for-ios-and-android-insecure/):

> As of the publication of this article, Yahoo, iCloud, and on-premises Exchange Server do not support OAuth. For these services, the Outlook app does store your credential in encrypted form in the Outlook cloud service. A random AES-128 key (called a device key) is generated during the first run of the app. When a user logs in to a non-OAuth service, the username, password, and device key are transmitted to the Outlook cloud service via a TLS encrypted connection. The cloud service verifies the password and then encrypts the password with the device key. The device key is then wiped from memory, never having been stored on disk. When a user checks for mail, the device key is sent to the cloud service and used to decrypt the encrypted password. After the Outlook cloud service has checked for mail, the device key is wiped from memory again.

I assume by now the Outlook cloud service would at least no longer run on AWS, but if the user's company has a strict policy against routing email via a 3rd party cloud service, then Outlook just doesn't cut it.

Happy to be proven wrong - I just can't see how..

**Comment by scanum** [comment]
@msdmaguire Hi David, could you please aid with next steps on this issue? Thanks!

**Comment by mattpennathe3rd** [comment]
@smithre4 Do you happen to have any insight on this one?

**Comment by smithre4** [comment]
I don't know where this should be published as this isn't Exchange specific, but IMAP connections follow a similar flow to the on-premises mailboxes - Outlook mobile connects to the Microsoft cloud and the Microsoft cloud connects to the IMAP endpoint. This means a portion of the mailbox data from the IMAP endpoint is synchronized into the Microsoft cloud. In terms of credential management, etc. this article applies - https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/passwords-and-security?view=exchserver-2019

**Comment by mattpennathe3rd** [comment]
@lucianf In line with Ross's comment, I don't think this applies to an Exchange environment, so I am not sure this information belongs in these docs. Is there a scenario where this comes into play in your Exchange environment?

**Comment by scanum** [comment]
@lucianf  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
