### ISSUE TITLE
JS Error in "Exchange Admin Center"

### ISSUE THREAD

**Issue by uniquelau** [MicrosoftDocs/OfficeDocs-Exchange#1430]
After I create the migration using the following steps, I recieve multiple "Critical errors".

Client Information
------------------
User Agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 10.0; WOW64; Trident/7.0; Touch; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
CPU Class: x86
Platform: Win32
System Language: en-GB
User Language: en-US
CookieEnabled: true
-----------------
Exception Details
-----------------
Date: Mon Oct 14 10:25:18 UTC+0100 2019
Message: Script error.
Url: https://r1.res.office365.com/ecp/15.20.2347.23/scripts/navigation.js
Line: 0

Call Stack
----------

Dump Event
----------
	errorMessage = Script error.
	errorUrl = https://r1.res.office365.com/ecp/15.20.2347.23/scripts/navigation.js
	errorLine = 0
	errorCharacter = 0
	errorCode = 0
	actionURL = 
	altKey = false
	altLeft = false
	behaviorCookie = 0
	behaviorPart = 0
	bookmarks = null
	boundElements = [object HTMLCollection]
	button = 0
	buttonID = 0
	cancelBubble = false
	clientX = 677
	clientY = -512
	contentOverflow = false
	ctrlKey = false
	ctrlLeft = false
	data = 
	dataFld = 
	dataTransfer = null
	fromElement = null
	keyCode = 0
	nextPage = 
	offsetX = 0
	offsetY = 0
	origin = 
	propertyName = 
	qualifier = 
	reason = 0
	recordset = null
	repeat = false
	returnValue = true
	screenX = 1941
	screenY = -1172
	shiftKey = false
	shiftLeft = false
	source = null
	srcElement = null
	srcFilter = null
	srcUrn = 
	toElement = null
	type = error
	url = 
	wheelDelta = 0
	x = 0
	y = 0
	getAttribute = 
function getAttribute() {
    [native code]
}

	removeAttribute = 
function removeAttribute() {
    [native code]
}

	setAttribute = 
function setAttribute() {
    [native code]
}

Detailed Call Stack
-------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@uniquelau Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by uniquelau** [comment]
Hi @scanum, I was able to proceed with the migration.
However, I am still getting intermittent errors on the migration page/tab.
Let me know if you need any further info from my side and I will try and assist.
Best wishes, Laurence

**Comment by scanum** [comment]
@uniquelau thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
