### ISSUE TITLE
Office Online Server supported OS and prerequsites

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-Exchange#1436]
The information about OS / prerequisites for Office Online Server in this article does not match the information in https://docs.microsoft.com/en-us/officeonlineserver/deploy-office-online-server 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e12237-20cc-007c-540b-4544269ec6a9
* Version Independent ID: 08d3e012-d918-c625-3d6c-d827636f34b5
* Content: [Install Office Online Server in an Exchange organization](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/install-office-online-server?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@shivtorov Thank you for reaching out and helping improve MS Docs. Just to clarify, are you saying that the information in the link for Exchange server pre-requisites in this article is different from the article you referenced?

**Comment by shivtorov** [comment]
@lindspea In this article the information about _Office Online Server_ (not Exchange) deployment does not match the information in the linked article.

Specifically, the sections "Office Online Server system requirements", "Install Office Online Server prerequisites" and "Install Office Online Server" should be updated.

Just some of the issues:

- Office Online Server supports Win2012R2 and Win2016 (this article says Win2012R2 only)
- Missing prerequisites ("Visual C++ Redistributable Packages for Visual Studio 2013" and "Microsoft.IdentityModel.Extention.dll")
- the "Install-WindowsFeature" PowerShell code missing many required components (NET-Framework-Features,NET-Framework-Core,NET-HTTP-Activation,NET-Non-HTTP-Activ,NET-WCF-HTTP-Activation45,Server-Media-Foundation)
- the download instructions say to use "old" source image ("Office Online Server is part of the downloads for Office Professional Plus 2016 in the Volume License Service Center"). The article  should direct readers to the latest OOS image that is part of the downloads for Office Professional Plus **2019** in the Volume License Service Center

**Comment by lindspea** [comment]
@shivtorov thank you for this. I'll get this over to the team to have the correct article updated.

**Comment by mattpennathe3rd** [comment]
@shivtorov A belated thank you for opening this issue. I've updated the article and chose to remove parts of this procedure in favor of linking to the article you mentioned (which will always be more up to date than the Exchange-focused article). The updated version should be published in the near future. Thanks again for pointing this out.
