### ISSUE TITLE
Redirect Domains

### ISSUE THREAD

**Issue by gregmoyses** [MicrosoftDocs/OfficeDocs-Exchange#1437]
I'm trying to understand when redirect domains are required.

My assumption is that they are only required when users are to be using the 365 and the GSuite platforms at the same time during a migration. If this is correct, perhaps the article could be updated to make it clearer. For people migrating all users over at once, this will save a lot of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@gregmoyses Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@scanum this can be closed thank you.

**Comment by lindspea** [comment]
Resolves #1437

**Comment by phillkOCCM** [comment]
the redirect wouldn't be needed if Exchange online support external relay like Exchange on prem. this inconsistency just bit me in the rearend today.

**Comment by mattpennathe3rd** [comment]
Appears to be fixed by https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1474. Closing this issue as done!
