### ISSUE TITLE
What provides the synchronization of "4 weeks" of email?

### ISSUE THREAD

**Issue by jasonshave** [MicrosoftDocs/OfficeDocs-Exchange#1438]
I have a colleague who is able to log into their mailbox after setting up HMA however they are missing email for the last two weeks. After further investigation there are two others out of several hundred who are missing email as well. If they log into the desktop Outlook client they get all their email. If they use the ActiveSync native mail client on iOS or Android they get all their mail. It seems as though the synchronization of their "four weeks" of email (as this article suggests) is broken in some way.

The above troubleshooting steps have been taken and no issues were found. Also, most mailboxes in the environment are not seeing this "missing email" issue. The fact that when hybrid authentication is used, email is missing tells me the copy in the cloud is stale.

So I'm wondering, what service, component, or software is responsible for the synchronization of email? Is it the Exchange server itself? If so, are there any logs that can be reviewed to understand the synchronization schedule/issues/etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0020c770-fbf0-d36b-196c-59fd0a5dbe93
* Version Independent ID: bd5c069a-c325-28cf-5a58-8ae9c34c793d
* Content: [Using hybrid Modern Authentication with Outlook for iOS and Android](https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019#troubleshooting)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jasonshave Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
