### ISSUE TITLE
Data synchronized with Outlook for iOS and Android

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-Exchange#1443]
The article says that Outlook syncs 500 items per folder minimum. I have tested this and I have asked others who have Office 365 outside of my tenant and it seems that this is not the case. I am able to load roughly 100 to 150 items before it says load more conversations. Is this document accurate or has the limit changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook Exchange Online FAQ, Outlook for iOS Exchange FAQ, Outlook for Android FAQ, Outlook for iOS security concerns, Outlook for Android security concerns, Outlook for iOS cloud architecture, Outlook for Android cloud architecture, Outlook app Office 365 architecture, Outlook app attachment faq, Outlook app contacts faq, Outlook app license faq](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by smithre4** [comment]
This is a result of moving to the native Microsoft sync technology. Originally, the native Microsoft sync technology it was designed to support only a 100 items syncing per folder (the "load more conversations" would load more, however). The Microsoft sync technology has been recently changed to sync 500 items by default. The apps have to take advantage of that sync change; Outlook for Android supports this and Outlook for iOS will in a future update.

**Comment by microsoftsearch** [comment]
Thank you so much for the clarification! Is there any chance this document would be updated to reflect that information or is there an additional roadmap link that could be published regarding a potential ETA of this feature?

**Comment by lindspea** [comment]
@msdmaguire Would you like me to add a note to this article as per the above comment or is there a roadmap link for this?

**Comment by msdmaguire** [comment]
Yes, Lindsay, thank you. That would be great.

**Comment by microsoftsearch** [comment]
Thank you all for your help! Very much appreciated.

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
