### ISSUE TITLE
Does this document apply to Exchange server 2016 as well?

### ISSUE THREAD

**Issue by agladboy** [MicrosoftDocs/OfficeDocs-Exchange#1444]
I cannot find to similar instruction regarding how to configure the add-ins on Exchange server 2016, does this instruction apply to Exchange server 2016 as well?

Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 091aeef1-4a33-1d08-66c7-0dc75b93345d
* Version Independent ID: bce258af-4065-d2b3-0eb5-f882784a0ec7
* Content: [Add-ins for Outlook in Exchange 2013](https://docs.microsoft.com/en-us/exchange/add-ins-for-outlook-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/add-ins-for-outlook-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/add-ins-for-outlook-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@agladboy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@agladboy thank you for reaching out.  Please have a look at this doc and let me know if it helps in any way. https://support.office.com/article/Get-an-Office-Add-in-for-Outlook-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8

**Comment by agladboy** [comment]
@lindspea Thank you very much, the link above helps for configuring the client side. We'd like to check if the instruction/document for on-premise Exchange Server 2013 is applied to on-premise Exchange Server 2016 as well. Many thanks!

**Comment by lindspea** [comment]
@agladboy Hi Jason. The article mentions that it's for Exchange Server 2013 but let me double check with the team if it applies to 2016 as well. I'll let you know soonest.

**Comment by lindspea** [comment]
@agladboy Hi Jason. It applies to 2016 as well. I have added clarification to the topic for other users so it should reflect in a few days.
