### ISSUE TITLE
Lost information

### ISSUE THREAD

**Issue by pear7777** [MicrosoftDocs/OfficeDocs-Exchange#1446]
HELLO!  
You forgot to add HOW online archive works on shared mailboxes.
before there was this:
Important:
A user must have an Exchange Online license in order to access a shared mailbox. Shared mailboxes don’t require a separate license. However, if you want to enable In-Place Archive or put an In-Place Hold or a Litigation Hold on a shared mailbox, you must assign an Exchange Online Plan 1 with Exchange Online Archiving or Exchange Online Plan 2 license to the shared mailbox. 

Next I see someone saw this:
Important:
A user must have an Exchange Online license in order to access a shared mailbox. Shared mailboxes don’t require a separate license. 

Which tells me NOTHING about ARCHIVE

NOW there is NOTHING TO BE FOUND rgearding Archives.

Please add information 
- Archive is standard?
- Archiving is unsupported and needs EOLP 2 E3 or E5 ( which kills "shared", hence unsupported.) 

BR

Peter Arisz

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 488ecf85-5f6d-3abd-4253-8527b5082340
* Version Independent ID: ec414c0f-4ee4-bbd1-3851-3e4db0c97593
* Content: [Shared mailboxes in Exchange Online](https://docs.microsoft.com/nl-nl/exchange/collaboration-exo/shared-mailboxes?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@pear7777 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@pear7777. Thank you for reaching out.  Not sure if you saw this, but it might help - You don't need a license for retention but you need it for archiving and litigation hold. If you want to enable the archive mailbox or put a Litigation Hold on a shared mailbox, then an Exchange Online Plan 2 license or an Exchange Online Plan 1 with Exchange Online Archiving license is required. If you want to enable the archive mailbox or put a Litigation Hold on a shared mailbox, then an Exchange Online Plan 2 license or an Exchange Online Plan 1 with Exchange Online Archiving license is required. This link has more information - https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits.
Hope this helps. Let me know if you need further assistance.

**Comment by scanum** [comment]
@pear7777 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
