### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by pear7777** [MicrosoftDocs/OfficeDocs-Exchange#1447]
Hello,

Nowadays we need powershell for anything and everything.

Hooking in to O365 is a teadeaous process, we neet to support 10 odd customers, and are quite fed up with creating sessions after session.

We would really prefer having all these things in the EAC.

B est regards

Peter Arisz

**Comment by scanum** [comment]
@pear7777 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
