### ISSUE TITLE
Direct Send issues

### ISSUE THREAD

**Issue by nitincsh** [MicrosoftDocs/OfficeDocs-Exchange#1452]
We configured Direct Send with the appropriate configurations and it seems to work but every 5th or so email seems to never be sent. It's almost like it's being throttled however I am sure that the throttling limits are much higher. I opened a support ticket but they told me it's something they cannot troubleshoot since it's a shared service between 1000s of customers.

**Comment by scanum** [comment]
@nitincsh thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
