### ISSUE TITLE
Update this article to E16/E19 content

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#1455]
For example E16 is using 9 TA by default:
[PS] C:\&gt;Get-TransportAgent

Identity                                           Enabled         Priority
--------                                           -------         --------
Transport Rule Agent                               True            1
DLP Policy Agent                                   True            2
Retention Policy Agent                             True            3
Supervisory Review Agent                           True            4
Malware Agent                                      False           5
Text Messaging Routing Agent                       True            6
Text Messaging Delivery Agent                      True            7
System Probe Drop Smtp Agent                       True            8
System Probe Drop Routing Agent                    True            9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7ecefc-dae8-3453-a4a0-3abac4d487bc
* Version Independent ID: 79641e09-8eb6-7b16-592d-8acbc845f6f9
* Content: [Transport agents: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/transport-agents-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/transport-agents-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/transport-agents-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@trudolf-msft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
hello @trudolf-msft  Could you please be a bit more clear with your requirement because this article only applies to 2013, are you willing to create a new article for 2016/19? or are you saying that we must add information for 2016/19 into this one?.

**Comment by trudolf-msft** [comment]
Hi Jose,

It’s about 2016/2019 but Chris already told me that it’s too much afford and the content was not much clicked.

Kind regards,
Thomas

**Comment by j0rt3g4** [comment]
@trudolf-msft So, can we close this one? or want me to add something in a PR?

**Comment by mattpennathe3rd** [comment]
@j0rt3g4 Let's keep this open for now. I'm investigating some 2019 content updates and this might play into that. We'll close later if this is deemed unnecessary.

**Comment by j0rt3g4** [comment]
Thank you for your comment @mattpennathe3rd  if you need something you know how to reach me :)
