### ISSUE TITLE
Simplify...

### ISSUE THREAD

**Issue by itzafugasi** [MicrosoftDocs/OfficeDocs-Exchange#1456]
I don't believe this method really simplifies anything -
Scenario:
Our environment uses on prem ADFS.  When a mailbox is in the cloud, they log into our on prem webmail URL (https://webmail.contoso.com/owa).  It then says "use the following URL to access your mailbox: https://outlook.com/owa/contoso.com.
Then, clicking on that link, it redirects to our ADFS login.  User logs in, and accesses their mailbox.
This isn't simple for the user.  They're visiting 3 pages just to access their email.
The solution proposed here does not simplify this process any further.  It just masks the Microsoft URL with a CNAME of the customer's domain so the user if familiar with it.  It does not make redirection or logging in any different.
We need a Microsoft supported redirect solution that skips the "click on this link to log into your webmail" URL and can take the user directly to ADFS (or their mailbox if they're already authenticated from a previous session).  They may still log in twice, but at least they're skipping one step in the process.
Just my 2 cents.  I'm sure others would agree based upon what I've been reading on the topic.
Thanks for any recommendations you may be able to provide!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30c4fd6-0e69-cb9a-6a21-327f0ebae3a7
* Version Independent ID: d0217aa4-a37b-8837-4310-108fbf533a5d
* Content: [Simplify the Outlook Web App URL for Office 365 Hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/simplify-owa-url#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@itzafugasi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Hello @itzafugasi.

We are a documentation team; we are not able to take action regarding this issue that you mention because it's not the popular way to do it. The correct way to do it is by asking or requesting a feature is using UserVoice of the technology you're doing.

So please go here and vote, because I found a similar request on it:

https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/12925275-please-add-the-feature-of-silent-owa-redirection-t
