### ISSUE TITLE
Different certs bound to same services

### ISSUE THREAD

**Issue by evandimsby** [MicrosoftDocs/OfficeDocs-Exchange#1459]
What if there are multiple certificates, let's say 3 certs with different subject names from different issuers with various differing attributes like Valid To/From, and they are bound to the same services? Which one takes precedence or does Exchange do a round-robin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0eab843-3d1d-5a3f-f73d-7725b831bdcc
* Version Independent ID: 91733f7a-9d49-ad70-fd8f-4e3eb738e57e
* Content: [Assign certificates to Exchange Server services](https://docs.microsoft.com/en-us/Exchange/architecture/client-access/assign-certificates-to-services?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/assign-certificates-to-services.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/assign-certificates-to-services.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@evandimsby Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Excgabge Server is based on "Service Connection Points".
That you can set using my script for example: https://gallery.technet.microsoft.com/office/Script-to-configure-the-5a58558b

You can bind only one certificate to the IIS sites at the time, no matter if you have 3 certs the only one that it will be expected by exchange is the one that you configured on those SCP.

Also as final step on any change or update of the certs you'd need to associate the certificate to the services it will provide by using 
```Powershell`
Get-ExchangeCertificate
#Get the thumbprint of the certificate that you will use and use it on the next line
Get-ExchangeCertificate -Thumbprint XXXXXXXXXX | Enable-ExchangeCertificate -Services IIS,SMTP
```
That will associate uniquely the certificate to the services, all the rest will be ignored.

**Comment by scanum** [comment]
@evandimsby Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
