### ISSUE TITLE
Download for OOS location is misleading.

### ISSUE THREAD

**Issue by TechsUK** [MicrosoftDocs/OfficeDocs-Exchange#146]
Office Online Server is part of the downloads for Office Professional Plus 2016
in the Volume License Service Center. Don't waste time looking for OOS in the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e12237-20cc-007c-540b-4544269ec6a9
* Version Independent ID: 08d3e012-d918-c625-3d6c-d827636f34b5
* Content: [Install Office Online Server in an Exchange organization](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/install-office-online-server?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@TechsUK Thank you for this feedback

Thank you for the information on this. I will make sure this gets updated into the article.

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@TechsUK I updated the download information as you suggested, and also added some more information from https://www.microsoft.com/en-us/microsoft-365/blog/2016/05/04/office-online-server-now-available/.

Thanks for the feedback.
