### ISSUE TITLE
Provide exclusions as file download

### ISSUE THREAD

**Issue by cnschindler** [MicrosoftDocs/OfficeDocs-Exchange#1467]
Copy/Paste of this long list is very cumbersome. It would help if these exclusion were provided as a downloadable text file without the explanations, etc. only paths, files and processes

**Comment by scanum** [comment]
@cnschindler thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
