### ISSUE TITLE
[LOC] Multiple invalid links

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#1468]
Article: esrp-storage.md
Author: dmaguire
URL: https://docs.microsoft.com/en-us/exchange/esrp-storage?view=exchserver-2019
___

We found several broken links in the article above, could you please check and remove or update broken links from a list below?

Related to: #1257 (already fixed)

Broken links:

- http://uk.emc.com/collateral/hardware/technical-documentation/h6717-esrp-clariion-1000-user-exchange-2010.pdf
- http://www.emc.com/collateral/hardware/technical-documentation/h6994-esrp-iomega-260-user-exchange-2010.pdf
- http://www.emc.com/collateral/hardware/technical-documentation/h7137-esrp-celerra-1500-user-exchange-2010.pdf
- http://www.emc.com/collateral/hardware/technical-documentation/h7202-esrp-clariion-60000-user-exchange-2010.pdf
- http://www.emc.com/collateral/hardware/technical-documentation/h8225-vmax-100000-user-mailbox-resiliency-esrp.pdf
- http://www.emc.com/collateral/hardware/technical-documentation/h8258-esrp-vnxe-500-user-exchange.pdf
- http://www.emc.com/collateral/hardware/technical-documentation/h8259-esrp-vnxe-1000-user-exchange.pdf
- http://www.emc.com/collateral/hardware/white-papers/h11362-esrp-vnx3150-unified-storage-exchange-2010.pdf
- http://www.emc.com/collateral/hardware/white-papers/h8813-esrp-vnx5700-60k-2gb-ex10mbx-resiliency.pdf
- http://www.emc.com/collateral/hardware/white-papers/h8849-esrp-vnx5300-20k-1-5gb-exchange-2010.pdf
- http://www.emc.com/collateral/software/technical-documentation/h6716-esrp-clariion-500-user-exchange-2010.pdf
- http://www.emc.com/collateral/white-paper/h12997-emc-vnx5400-20k-users-virtualized-ms-exchange-wp.pdf
- http://www.emc.com/collateral/white-papers/esrp-white-paper-emc-vnx5700-unified-storage-60000-users-virtualized-microsoft-exchange-server-2013-mailbox-resiliency-storage-solution.pdf

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Removed broken links on PR #1503

**Comment by mattpennathe3rd** [comment]
Appears to be fixed by https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1503 . Closing this issue as done!
