### ISSUE TITLE
Information about modifying Default Domain Controllers Policy missing.

### ISSUE THREAD

**Issue by paroola** [MicrosoftDocs/OfficeDocs-Exchange#1469]
The article is missing important information about how /PrepareDomains procedure is also modifying the Default Domain Controllers GPO to grant "Manage Auditing and Security Log policy" rights to Exchange Enterprise Servers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 062bba98-6d11-bf83-913a-fe9c16e2f201
* Version Independent ID: 9bd1f3a7-05c8-89e2-ae19-adb8e3040e9c
* Content: [What changes in Active Directory when Exchange is installed?](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/active-directory/ad-changes?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/active-directory/ad-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/active-directory/ad-changes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@paroola Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
Solving Issue on PR #1504

**Comment by scanum** [comment]
@paroola Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
