### ISSUE TITLE
Broken hyperlink

### ISSUE THREAD

**Issue by ArendvanDijk** [MicrosoftDocs/OfficeDocs-Exchange#1473]
Under "Checking the status of your hybrid agents" you do refer to "First install the PackageManagement modules". Thats a broken hyperlink.

Thanks for the great page, good info and clear instructions!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@ArendvanDijk  Thanks for submitting this. I've updated the link and the new version should be published in the near future. Please let me know if you see any other issues with this article (or with any others in this repo). Thanks again.
