### ISSUE TITLE
What does EFV:NLI mean?

### ISSUE THREAD

**Issue by joshfriend** [MicrosoftDocs/OfficeDocs-Exchange#1479]
This has been asked in a few places but never answered:

https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/211
https://github.com/MicrosoftDocs/OfficeDocs-o365seccomp/issues/929

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09f04759-af19-71c8-0656-5e9440bfecaa
* Version Independent ID: a3f13243-d858-9feb-add7-e45acadbde5c
* Content: [Antispam stamps](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antispam-protection/antispam-stamps?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/antispam-stamps.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/antispam-stamps.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by zirneklitis** [comment]
It looks like to be partly answered here:
https://github.com/MicrosoftDocs/microsoft-365-docs/issues/486

**Comment by mattpennathe3rd** [comment]
According to the linked GitHub thread and the doc, this is already answered (that is, any unlisted header is only used internally for diagnostic purposes). Closing this issue as not in need of a fix.
