### ISSUE TITLE
No Anonymous under Security on the Select Role Services page - but no worry

### ISSUE THREAD

**Issue by cheesecracker** [MicrosoftDocs/OfficeDocs-Exchange#1482]
Under the section "Set up Exchange Online as an SMTP Relay Using Windows Server 2012", it's written:
  "On the Select Role Services page, make sure that Anonymous under Security is selected, and then select Next."

There is NO Anonymous option under Security.  But NO NEED to worry about it.  Everything is still working fine!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e73bb3c6-ab71-066f-18e8-f0726cebf9d2
* Version Independent ID: 16e49af3-9980-d928-7667-ee8f5e07c487
* Content: [How to configure IIS for relay with Office 365](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by shafee005** [comment]
"" On the Delivery tab, select Outbound Security, and then do the following:
Select Anonymous Authentication.
Enter the credentials of the Office 365 user who you want to use to relay SMTP mail.
Select TLS Encryption.
Select Outbound Connections and in the TCP Port box, enter 25 and select OK.
Select Advanced and specify contoso-com.mail.protection.outlook.com as the Smart Host.""

When you select Anonymous authentication, the fields to enter credentials are greyed out. Basic authentication should be selected to enable the field.

**Comment by cheesecracker** [comment]
> 
> 
> "" On the Delivery tab, select Outbound Security, and then do the following:
> Select Anonymous Authentication.
> Enter the credentials of the Office 365 user who you want to use to relay SMTP mail.
> Select TLS Encryption.
> Select Outbound Connections and in the TCP Port box, enter 25 and select OK.
> Select Advanced and specify contoso-com.mail.protection.outlook.com as the Smart Host.""
> 
> When you select Anonymous authentication, the fields to enter credentials are greyed out. Basic authentication should be selected to enable the field.

Your comment did nothing but add to confusion.  We need **Anonymous** Authentication.  Not Basic Authentication.

**Comment by dariomws** [comment]
Hi @cheesecracker, thank you for your feedback.

This article has been completely rebuilt. Do you still think that it needs to be updated?

**Comment by mattpennathe3rd** [comment]
@cheesecracker @dariomws It looks like this content was entirely removed on December 17th and was not replaced. As such, this issue is obsolete and can be closed.
