### ISSUE TITLE
Both Roles On Singel Server

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-Exchange#1483]
This section is a little confusing to customers.

Exchange 2013: At least one server with the Mailbox and Client Access server roles installed. While it's possible to install the Mailbox and Client Access roles on separate servers, we strongly recommend that you install both roles on each server to provide additional reliability and improved performance.

Do we need to have both roles on the same machine?    The next lines then contradicts that statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@r-milne Thank you for pointing this out. It seems that this content was updated recently and this explanation was clarified. It's possible to spread these roles across multiple servers, but the recommendation is that they be on the same server.

Thanks for opening this issue and I'm sorry for the belated response. Please feel free to open a new issue if you have additional feedback on the documentation.
