### ISSUE TITLE
Test-HybridConnectivity testO365Endpoints errors at watchdog.servicebus.windows.net on port 443

### ISSUE THREAD

**Issue by MarkLofthouse** [MicrosoftDocs/OfficeDocs-Exchange#1488]
When you run 'Test-HybridConnectivity testO365Endpoints', you get the following error:-

Testing connection to watchdog.servicebus.windows.net on port 443
WARNING: Name resolution of watchdog.servicebus.windows.net failed
Performing GET on https://watchdog.servicebus.windows.net:443
Invoke-WebRequest : The remote name could not be resolved: 'watchdog.servicebus.windows.net'
At C:\Temp\HybridManagement.psm1:196 char:19
+         $result = Invoke-WebRequest -Method Get -Uri $uri
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Would appear this DNS record no longer exists - does the module need updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by devFofo** [comment]
Having the same issue. Reading the documentation on setting up the Hybrid Agent (https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#installation-prerequisites) and following the documentation.
Installation Pre-Requisite, step d is:
Test-HybridConnectivity -TestO365Endpoints

This does not work. Name resolution for 'watchdog.servicebus.windows.net' is not working.

**Comment by mattpennathe3rd** [comment]
@MarkLofthouse @devFofo Thanks for filing this issue (and my apologies for the delay in addressing it). I'll have to look into this and will report back.

**Comment by dariomws** [comment]
Hi @MarkLofthouse and @devFofo, thank you for your feedback and help us to improve docs.microsoft.com.

I reported this warning. Anyway, to report this kind of issue I suggest you open a support ticket, they will be able to help you better as here we are limited to documentation issues and improvements.

**Comment by scanum** [comment]
@MarkLofthouse Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
