### ISSUE TITLE
Cannot remove certificate from Office 365 profile in iOS Outlook

### ISSUE THREAD

**Issue by wilddev65** [MicrosoftDocs/OfficeDocs-Exchange#1489]
Outlook IOS. I tried deleting the account & app, removing it on Outlook online 365 and removing any certificate profile. When I try to import the p12 file, it says Duplicate certificate. If I try to turn on SMIME it says it cannot use the certificate. There is no obvious way to manage these certificates. It seems to recognize a certificate profile installed on iOS but not be able to use the certificate. Very frustrating as the app cannot send encrypted emails with the certificate that is installed currently.

**Comment by TK-093** [comment]
Did you figure anything out yet? I am in the same boat.

**Comment by wilddev65** [comment]
I did not. Let's just say there is next to no way to manage certificates in this client. Even if you download another user's public cert to read their encrypted emails, there is nothing to indicate where that is or how to remove it. I'm not even sure if it's using the iOS equivalent of keychain. Seems this feature isn't very well thought out.

**Comment by TK-093** [comment]
I've opened a call with them about it.  I did discover if I renewed my certificate against our PKI i can then import that new certificate, but I'm assuming the original is still there as well because i get the duplicate message if i try to reimport that one.. so now I have two sets on there... not sure which one it's using.

**Comment by TK-093** [comment]
I was told they are working on a method from within the app to remove certificates.  No specifics on a time frame though.

**Comment by mattpennathe3rd** [comment]
@wilddev65 @TK-093 It sounds like this is not a documentation problem, but please feel free to open a new docs issue if it turns out that there is a problem with the documentation that I am able to help with.
