### ISSUE TITLE
These docs work great until you try to verify you subdomain section

### ISSUE THREAD

**Issue by cotecsi** [MicrosoftDocs/OfficeDocs-Exchange#1491]
I have tried to setup my migration using this doc and everything is good until the part where you "Create a sub-domain for mail routing to Office 365" the verification never works, the subdomain does not verify so you cannot complete the steps to make this migration happen.  I verified the TXT record is published and showing up on the internet correctly using the Google DIG tool, as well as DNS Ultra tools, so I know my setup is correct, it just will not verify for some reason.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@cotecsi I'd love to help, but this does not appear to be a docs issue. Please open a support ticket if you're still having trouble, but feel free to open a new docs issue if it turns out that there is an error in the docs that I can help correct.

**Comment by tominal** [comment]
Same thing here. This doc is useless.

**Comment by JibJabMan8080** [comment]
I had this same issue. I created an account to comment on this issue. In order to get instant verification on your domain host DNS records for the TXT listing instead of you '@' as the host which is the primary use the subdomain title. 

For example:

Type-> TXT  
Host->o365 
Value-> Gsuite Verification code

This should allow for you to verify instantly with Gsuite. Hope this helps.
