### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by cloudgcp** [MicrosoftDocs/OfficeDocs-Exchange#1493]
[Enter feedback here]
Does change of mail exchange records affect the migration once the migration is in progress?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by bryanfritz** [comment]
I would think this may affect emails being delivered from outside of your organization, however syncing between GSuite and MS should not be affected as you created MX records for both the subdomains. I wouldn't make a change during the migration though as there maybe other unintended consequences by changing the MX record for you main email routing.
