### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by bacmodung** [MicrosoftDocs/OfficeDocs-Exchange#1494]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76f49f67-b2a6-90ca-ceab-9e669a8e64cd
* Version Independent ID: d69e5486-3a3c-7ce8-d82a-e7d4fd4e606c
* Content: [Mobile device mailbox policies](https://docs.microsoft.com/en-us/exchange/clients/exchange-activesync/mobile-device-mailbox-policies?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/exchange-activesync/mobile-device-mailbox-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/exchange-activesync/mobile-device-mailbox-policies.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Hi @bacmodung. What is the issue you have with this article?

**Comment by msdmaguire** [comment]
Going to close this issue. If something comes to mind, you can create a new one with details.
