### ISSUE TITLE
What about -ForwardingAddress ? 

### ISSUE THREAD

**Issue by johnsop** [MicrosoftDocs/OfficeDocs-Exchange#1497]
Should mention this: 

-ForwardingAddress 

The ForwardingAddress parameter specifies a forwarding address in your organization for messages that are sent to this mailbox. You can use any value that uniquely identifies the internal recipient. For example:

Name
Alias
Distinguished name (DN)
Canonical DN
Email address
GUID

How messages are delivered and forwarded is controlled by the DeliverToMailboxAndForward parameter.
DeliverToMailboxAndForward is $true: Messages are delivered to this mailbox and forwarded to the specified recipient.

DeliverToMailboxAndForward is $false: Messages are only forwarded to the specified recipient. Messages aren't delivered to this mailbox.

The default value is blank ($null), which means no forwarding recipient is configured.
If you configure values for both the ForwardingAddress and ForwardingSmtpAddress parameters, the value of ForwardingSmtpAddress is ignored. Messages are forwarded to the recipient specified by the ForwardingAddress parameter.

Seems odd not to mention this parameter on a page about forwarding 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afdaec1b-3f68-1f0e-db9e-1d8acf20ac4a
* Version Independent ID: fb622286-016d-86e5-a794-d2c3c9696cc5
* Content: [Configure email forwarding for a mailbox](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/email-forwarding?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@johnsop Thank you for opening this issue. We've updated the article with an additional example that showcases this parameter, so I hope this helps. The new article should be published in the near future. Thanks again for helping us improve the documentation.
