### ISSUE TITLE
Forward addresses don't seem to be created during a batch

### ISSUE THREAD

**Issue by greg-fischer** [MicrosoftDocs/OfficeDocs-Exchange#1499]
Hello, I've setup 2 small batches, only a few users to test.  The batch has finished on a couple users and I'm testing email forwarding, but noticed that no new email is flowing over to the o365 side until a new sync has run.  I looked in the accounts on both the Exchange side and the GSuite side and don't see any forwarding addresses or aliases for the subdomains. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by bryanfritz** [comment]
Greg,
I am working on a migration as well and in my testing i have found similar results. I am able to send email to my GSuite subdomain but not to my MS subdomain. I am getting a message blocked response when sending to the MS subdomain. I have not "Completed the Migration Batch" yet I have just left it in "synced" status. This is maybe why I am not able to send to the MS subdomain. However I am unsure if I "Complete" the batch if I will still receive email at G-Suite (non-subdomain address) or if they will all be routed to MS only. Have you "Completed" your batch yet? Anyone else have anything to chime in on this?
Thanks

**Comment by greg-fischer** [comment]
I have completed some of my batches, yes. I should have reported back sooner on this (will do separate reply to my first post on what I found).  But that part about a blocked message you mention sounds like your subdomains or SPF records are not setup right.  You did setup and verify your o365 subdomain in O365 admin, correct?  My primary domain is partially verified, but "incomplete setup" is the status.  However, my o365.mydomain.com subdomain is verified and "healthy".  Also, make sure the alias is setup on the user's account with an o365 subdomain address.  I had to manually do this with Powershell.  If you aren't doing this, I'd test from a totally external source, sending email to the users subdomain alias addresses. For example: greg@o365.mydomain.com and greg@gsuite.mydomain.com should both work and show up on those destinations.   Also, my primary issue was because the sync was not "completed", they don't setup the forwarding until it is.  But also my o365 user accounts didn't have o365 subdomain aliases.  Another issue, after complete, was that any users on other batches yet to complete do not have gsuite subdomains setup for reverse forwarding. I had to manually do that. (used Powershell again, because the web admin was not working on all users)

**Comment by greg-fischer** [comment]
Status from my original issue:
I created a ticket, tech support helped me and said I could not create users in O365 Admin, but I needed to create them only as MailUser contacts in Exchange Admin.  The docs do say this , but I missed it.  But this still didn't fully resolve my issues. Here's some of my findings.

1. I had one batch with standard o365 created users, which are still not "complete" in migration. They did not have forwarding setup, so emailing from o365 to gsuite did not work.  But I did manually create a reverse forward (do not save local copy) on the account, so o365 users can send back to gsuite users.  I think the docs say this should not be necessary, but it was, even for completed batches.

2. Manually created O365 Admin users did not have the subdomain o365 alias setup by migration, you have to do this!  

3. What *did* work: Powershell create all my accounts as MailUser Contacts in Exchange , WITH the alias for o365.subdomain. However, even though I specified -ExternalEmailAddress with user@gsuite.mydomain.com, it did not show up that way in o365 Admin as a forward.  so...

4.  I had to manually powershell a second script to add -ForwardingSMTPAddress for users still on gsuite so o365 completed users could send back to them. 

5. I also noticed in O365 Admin, if I edit a user and add forwarding addresses, it would work for one user. When I opened the next user, it showed cached info for the first user and in fact added a forward for first user onto the second!  So yeah, that's why I had to Powershell this.

6. I can't remember if migration completion removed the gsuite reverse forwarder or not. But on my next batches, I'll check. ( added many small batches of only a few users each)

Syncing batches do not get forwards setup right, which I suppose makes sense because they aren't moved yet.  Once you complete, the migration system adds the forward on the users Gmail to their o365 alias and they worked perfectly fine.  My main issue was the reverse forwards for batches not complete (users still on Gsuite).  Powershell was a big help , once I figured it out. It added the right aliases, but not reverse forwarders, although a second powershell script DID add them.

Assuming your domains are setup right in DNS, you just have to tweak any o365 aliases and/or gsuite forwarders. All the tweaking was on the O365 side and I don't think I had to do anything on Gsuite.

Obviously, we will not be switching over our primary domain MX records until all users are completed.

I think all those notes are right, if you need clarification let me know.

**Comment by bryanfritz** [comment]
Greg,
Thanks for all the details its helpful to have some insight from someone else working through the caveats for better clarification. One question though, did you reference anywhere specific to get the powershell commands. I am not a big powershell user so I won't be able to compile what I need from my own knowledge. 
Thanks!

**Comment by travisadvisicon** [comment]
Your comments have helped me quite a bit as well. Except I can't get my batches to sync properly, it always says it cannot find the user ID of the mailuser even though the test mailuser has aliases at both gsuite.mydomain.com and o365.mydomain.com (or at least the exchange admin center shows that they do, I did not use PowerShell). Did you guys ever have this issue?

**Comment by bryanfritz** [comment]
Travisadvisicon,
Are the email addresses the same in both GSuite and Exchange Online? Are you sure your Service account has been delegated access for your entire domain?
        "If you see an area that says Show Domain-Wide Delegation, click to expand that section. Then, enable the                      checkbox for Enable G Suite Domain-wide Delegation, and then click Save. Google is currently in the process of   updating this UI, so you may not see such an option. If you don't see such an option, then this is enabled by default." 

I know when i setup my Service Account approx 1.5 weeks ago that option was still present and needed to be checked.

**Comment by greg-fischer** [comment]
I'm glad that was some help! It's a confusing process.

@travisadvisicon , Make sure your CSV with batch emails use only the primary email address , which should be the same on both systems.  Also, I don't have an alias on O365 for gsuite.mydomain.com, only one for o365 subdomain and a forward (not alias) to gsuite subdomain. 

I had some odd issues with user account errors too. But with so many issues, I can't remember exact details.  What I do remember was that the MailUser contacts setup OK, but they didn't show up right away in O365 admin. But suddenly, maybe several minutes later they showed up as unlicensed users.  I'm fairly certain I had to assign licenses before the batch would run correctly, too.  So basically, I provisioned users, started a batch of only 1-3 users, allowed O365 Admin to sync up and show the new accounts, and then go in and assign licenses to those same 1-3 users in the current batch.

One thing to note, which may not affect you, is that one of my users had a personal microsoft.com account created with the same username/email as their work.  This user will not *complete* their batch sync, it fails every time. I only found out later that he had dual MS accounts when I helped him setup on his iPhone and it asked something like "Looks like you have 2 accounts, is this work or home?".  His account created and synced, but will not complete. I'm just cancelling that batch and moving on since he's in and working at this point.

Sorry I don't have exact details, there's just so many issues and I've been moving between several projects, and once I get something working I just move on since I'll only be doing this once.

@bryanfritz , I'll try to get a gist setup with my powershell commands later this evening.

Another note. Even though everything points to needing MailUser contacts created, the original test accounts created in O365 Admin did migrate just fine.  I don't think you actually need to create them in Exchange Admin. What wasn't working was forwards and aliases on the O365 side.  If you manually add them, it seems to work fine.  Now, I haven't actually ran the completion on that test batch (because one user is Admin, I want to wait).  So just to be clear on that, if one were to create a few users in O365 Admin, and still in O365 web Admin, add the o365 subdomain alias along with the reverse mail forward back to gsuite.subdomain, the batch migration did sync without issue.  The main problem doing this , for me, was when adding a mail forward the web interface kept cached information and messed up the forward on a second account, it just failed to add forwards correctly.  (that's why I powershell fixed those)  But you could add one, reload the admin and add another.  I don't trust the O365 Admin if that kind of stuff is happening.

**Comment by travisadvisicon** [comment]
@Greg-fischer
Thank you so much for this information. The only way to have the email address the same in both places would be to add the gsuite domain itself to O365, is that what I have to do? I thought I only had to create the o365.subdomain according to this article (though I do see it says it has to be the same for both... is it inferencing the former?).

**Comment by travisadvisicon** [comment]
It would appear that putting the gsuite domain itself in Office 365 was the issue. Once I did that and provisioned the users with the exact User ID they had in gsuite, my batches synced and completed correctly. Thank you both for your help, it really made this much easier for me.

**Comment by greg-fischer** [comment]
@travisadvisicon - Glad I could help.  And yeah, I kind of thought it was something like that.
 
Here's a gist with my Powershell commands I used:
https://gist.github.com/greg-fischer/d92c72f9d2931ba90964fcb02a2a6f0d

Its slightly modified with variables, but I tested a user and it was working fine.  There's a few notes and it has to be ran in sections.  Hopefully that helps anyone trying to do more scripting with this.

**Comment by scanum** [comment]
@greg-fischer thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
