### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by amsiutils** [MicrosoftDocs/OfficeDocs-Exchange#1500]
Missing "v" in verbose -- Important: This field is only populated if the LogLevel parameter on the Set-AdminAuditLogConfig cmdlet is set to erbose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7548351-91ef-eeba-8360-ea0df17bd93b
* Version Independent ID: b6c64430-ba37-69b9-b8bc-6ad19e86d868
* Content: [Administrator audit logging in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/admin-audit-logging/admin-audit-logging?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/admin-audit-logging/admin-audit-logging.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/admin-audit-logging/admin-audit-logging.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
Many thanks, @amsiutils. This has been fixed and you should see it in the docs, soon.
