### ISSUE TITLE
MONTI link dead

### ISSUE THREAD

**Issue by meermedia** [MicrosoftDocs/OfficeDocs-Exchange#1502]
The link to MONTI results in a 404 error. Is this application still available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce990e27-aa35-1c80-2d57-c07df2d35e88
* Version Independent ID: 78594f8e-6f98-21bd-4c68-be4facfade3e
* Content: [Migrate from Lotus Notes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-from-lotus-notes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@meermedia Thank you very much for pointing this out. I've fixed the link in the doc and the correction will be published in the near future.

For reference, the tool you're looking for can be found here: https://www.microsoft.com/download/details.aspx?id=29567
