### ISSUE TITLE
Permissions error when following the instructions on this page

### ISSUE THREAD

**Issue by southwestairsports** [MicrosoftDocs/OfficeDocs-Exchange#1505]
The page states that the following permissions for migration admin will work:

"For a cutover migration, the migration administrator account must be:
    A member of the Domain Admins group in Active Directory Domain Services (AD DS) in the on-premises organization.
    or
    Assigned the FullAccess permission for each on-premises mailbox.
    or
    Assigned the Receive As permission on the on-premises mailbox database that stores the user mailboxes."

I had to run the following cmdlets on the premises Exchange server in order to get the migration to proceed:

[PS] C:\Windows\system32&gt;Get-Mailbox -ResultSize unlimited -Filter {(RecipientTypeDetails -eq 'UserMailbox')} | Add-Mail
boxPermission -User &lt;migadminuser&gt; -AccessRights FullAccess -InheritanceType all

[PS] C:\Windows\system32&gt;Get-User -ResultSize unlimited -Filter {(RecipientTypeDetails -eq 'UserMailbox')} | Add-ADPermi
ssion -User &lt;migadminuser&gt; -AccessRights WriteProperty -Properties TargetAddress

Once these additional write/read permissions were granted the cutover migration started without errors.

Had Robinson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72dbf30b-3824-aca2-0bc3-1978c73db56a
* Version Independent ID: 906cdc60-73a2-1b8d-a2c0-149f56c06069
* Content: [Assign Exchange permissions to migrate mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/assign-permissions-for-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/assign-permissions-for-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/assign-permissions-for-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@southwestairsports Thank you for this. We'll review and let you know if we need to follow up. (And my apologies for the long wait in getting back to you.)

@chrisda Would you take a look at this one and offer any insight you might have?

**Comment by scanum** [comment]
@chrisda Hi Chris! Hope everything is well. Wondering if you have any insights on this issue? Thanks!

**Comment by mattpennathe3rd** [comment]
@scanum Chris and I spoke offline and this one needs review from a SME for further insight. It's in my queue for later work.

**Comment by get-itips** [comment]
Hello @southwestairsports 
First of all, thanks for your feedback.
I am taking over this issue that you opened and I have a question to ask you, I know some time has passed since you opened, but still, would like to know if you ran these two cmdlets at the same time and then tested the cutover migration

```
[PS] C:\Windows\system32>Get-Mailbox -ResultSize unlimited -Filter {(RecipientTypeDetails -eq 'UserMailbox')} | Add-Mail
boxPermission -User <migadminuser> -AccessRights FullAccess -InheritanceType all
```

```
[PS] C:\Windows\system32>Get-User -ResultSize unlimited -Filter {(RecipientTypeDetails -eq 'UserMailbox')} | Add-ADPermi
ssion -User <migadminuser> -AccessRights WriteProperty -Properties TargetAddress
```

Thank you

**Comment by southwestairsports** [comment]
It’s been so long I cannot remember the details but, yes, I think they fixed the cutover migration we had to do.

 

Had

**Comment by get-itips** [comment]
> It’s been so long I cannot remember the details but, yes, I think they fixed the cutover migration we had to do. Had 

Yes, I would like to understand that, because the first cmdlet run (FullAccess) is actually in the bullet list.

**Comment by scanum** [comment]
@mattpennathe3rd  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
