### ISSUE TITLE
And/Or for pattern matching

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/OfficeDocs-Exchange#1506]
I feel like this document could use some clarification, perhaps a dedicated section, discussing the combination of word and pattern matches.  As an example, it's unclear when specifying a comma-separated list of (patterns) for SubjectOrBodyMatchesPatterns, whether the list is evaluated with "AND" or "OR".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b18f30a-b22b-5f3b-8357-82690321bad0
* Version Independent ID: cf3ce6c5-bd43-380a-b162-d475032facb8
* Content: [Mail flow rule conditions and exceptions (predicates) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/conditions-and-exceptions#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/conditions-and-exceptions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/conditions-and-exceptions.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@FC-EricWeller, the topic you reference is really meant to be the big list of all available conditions/exceptions. The information that you're looking for is in the parent topic: https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules#multiple-conditions-exceptions-and-actions.

Does that help? Do you feel like similar information should also be in the conditions/exceptions topic?

**Comment by FC-EricWeller** [comment]
Well the "Multiple conditions, exceptions, and actions" section in the parent topic definitely is what I was thinking of.  I think there should at LEAST be a link-back to the section in the parent document here, because I think 1) searches designed to find the information will more likely return this document than the parent, 2) the information is really more pertinent to the "Conditions/Exceptions/Actions" subject than "Mail flow rules" generally.

**Comment by chrisda** [comment]
@FC-EricWeller, the top of the topic already contains a link back to the parent topic with the information. I added some text to it to identify the multiple condition/action information that it contains.

Thanks for the feedback.
