### ISSUE TITLE
add clarification on https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/configure-large-audience-size

### ISSUE THREAD

**Issue by sulobr** [MicrosoftDocs/OfficeDocs-Exchange#1507]
This is regarding https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/configure-large-audience-size

Can we update the statement  in "Use Exchange Online PowerShell to configure the large audience size for your organization" section to below to clarify that the large audience size is evaluated only when group is added as recipient? Individual recipient counts greater that the large audience size does not trigger this mail tip. We confirmed this with engineering team under https://o365exchange.visualstudio.com/Outlook%20Services/_workitems/edit/1244200

"When sender adds a distribution group that has more members than the configured large audience size, they are shown the Large Audience MailTip."

This clarification is included in another article : https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/mailtips#mailtips-in-exchange-online

**Comment by mattpennathe3rd** [comment]
@sulobr Thank you very much for pointing this out. I have updated the doc and the corrected version will be published in the near future.
