### ISSUE TITLE
What about forwarded or redirected emails?

### ISSUE THREAD

**Issue by DevZneb** [MicrosoftDocs/OfficeDocs-Exchange#1511]
When the forwarding is done through Use the Exchange admin center, does it forward everything to the target address?
How about those one that were received via a rule( forward or redirect from another mailbox)?
For example, 
Mail A has the forwarding done through  Exchange admin center to deliver all message to Mail B.
Then a Mail C has a rule to forward or redirect email to Mail A, does Mail A will deliver that message to Mail B?
Or is it only email directly emailed to Mail A's email address is going to get the rule?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afdaec1b-3f68-1f0e-db9e-1d8acf20ac4a
* Version Independent ID: fb622286-016d-86e5-a794-d2c3c9696cc5
* Content: [Configure email forwarding for a mailbox](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/email-forwarding?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@DevZneb thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
