### ISSUE TITLE
Powershell command is incorrect

### ISSUE THREAD

**Issue by Raffytje** [MicrosoftDocs/OfficeDocs-Exchange#1514]
In this command: 

`$OldPolicy={Get-RetentionPolicy "Old-Retention-Policy"}.distinguishedName `
the wrong brackets are used. The command needs to be:

`$OldPolicy=(Get-RetentionPolicy "Old-Retention-Policy").distinguishedName`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43992277-acf5-57ba-2386-158a4d1609a5
* Version Independent ID: 804f1866-803f-f88c-811d-11f1eea63189
* Content: [Apply a retention policy to mailboxes in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mrm/apply-retention-policies-to-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mrm/apply-retention-policies-to-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mrm/apply-retention-policies-to-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@Raffytje Thanks very much for the report. I've fixed this and the updated doc will be published in the near future. My apologies for the long lead time in getting back to you!
