### ISSUE TITLE
Misspelling in the Note area

### ISSUE THREAD

**Issue by rroddy24** [MicrosoftDocs/OfficeDocs-Exchange#1516]
It says "1 Depending on worklod, it may..."

Needs to be "workload".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bd8e7d2-4bf8-46e2-480f-9eca0c71cb65
* Version Independent ID: 60583132-eadf-5119-fc52-495cec0ba1f5
* Content: [Collaboration in Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/collaboration-exo#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/collaboration-exo.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/collaboration-exo.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@rroddy24 Thanks very much for reporting this! I've submitted a fix for this error and it should be live in the near future. Please let me know if I can help further.
