### ISSUE TITLE
Another broken link

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-Exchange#1517]
The link to "Create organization-wide safe sender or blocked sender lists in Office 365" (in other words https://docs.microsoft.com/en-us/office365/SecurityCompliance/create-organization-wide-safe-sender-or-blocked-sender-lists-in-office-365) is also broken. THe corresponding article seems to have gone missing and the only other relevant Microsoft-authored article that comes up on a quick search is an old MSDN one, so I'll defer to you folks for updating the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81c1119-165b-f408-698c-1092a781ba63
* Version Independent ID: 1a1b6d9a-a75c-e74d-ff84-ccbdf15091de
* Content: [Mail flow rules (transport rules) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@michevnew Thank you very much for pointing this out. I've corrected the link in the doc and the updated version will be published in the near future.
