### ISSUE TITLE
Exchange Online Admin should have MFA disabled in order to run all scripts from EMS

### ISSUE THREAD

**Issue by mariosaelikeit** [MicrosoftDocs/OfficeDocs-Exchange#1518]
The above should be in the "What you need to know before you begin" section. Step 5, action 1 fails if you have MFA enabled/enforced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@mariosaelikeit You are correct. Thank you very much for raising this. I've updated the article and the changes will be published in the near future.
