### ISSUE TITLE
Reporting on Basic Authentication Usage

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-Exchange#1524]
To minimize issues that arise due to disabling Basic Authentication, how can I report current usage of basic authentication in Exchange Online / Azure AD?
I want to disrupt as few applications as possible when this change is executed. How would I proceed in such a case?
Sure, for now all users that use authenticated SMTP, POP3 or IMAP4 are detectable, but these are not the only scenarios where Basic Auth is used, and it is little more than a coincidence, that currently no other protocols but Basic Auth work with SMTP, POP3 and IMAP4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online?redirectSourcePath=%252fen-us%252farticle%252fdisable-basic-authentication-in-exchange-online-bba2059a-7242-41d0-bb3f-baaf7ec1abd7#filter-on-premises-active-directory-user-accounts-that-are-synchronized-to-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by craigreilly** [comment]
I think we have all of our apps using oAuth2 and tokens - but I would like to be able to run a report and see if we have missed anything. Is this possible?

**Comment by waduphead** [comment]
Yes, i would very much like to know how to pull logs on this topic.  More so, for hybrid organization using ADFS and such.

**Comment by RascoPK** [comment]
Same here!
We are able to see some information in Azure SignIn Logs but I dont think everything is there.
We are missing full list of ActiveSync users (int not in Azure Sign In Logs)

**Comment by p0shkar** [comment]
Microsoft just recently announced how reporting can be done via the GUI [here](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282#).

Also, [this](https://github.com/p0shkar/powershell/blob/master/Office365/Get-BasicAuthLogins.ps1) is my attempt at doing it via Powershell, however there are some big disclaimers associated with that script: I've only done minimal testing and not enough reading of the documentation to be sure that this works for all types of Basic Auth. I havn't had time to verify the result with the result in the GUI.

**Comment by dariomws** [comment]
Hi @Weishaupt, thank you for your feedback.

As @p0shkar commented, there is an official article from the Exchange Team with directions to get Basic Auth usage reports:
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282#

Also, have in mind that some days ago the Exchange Team decided to postpone disabling Basic Authentication in Exchange Online:
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508

You can follow the blog to find out what's new about basic auth.

**Comment by scanum** [comment]
@Weishaupt Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
@scanum We can update this article to include more information and/or links to the blog post for clarity.
