### ISSUE TITLE
Provision users in O365 

### ISSUE THREAD

**Issue by bryanfritz** [MicrosoftDocs/OfficeDocs-Exchange#1525]
I am confused by what exactly the goal of "provisioning users" really is.  I have a working Azure AD Connect setup from my local AD to Office365 and the sync works perfectly. However when clicking on the link for "Manage Mail Users" the page gives a link for "Activating Synced Users". However that link just goes into Hybrid Identity and the Azure AD Connect tool. When talking about "provisioning users" is that simply referring to them being accessible in Azure AD so that they can be licensed and configured for mail or is there something more? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by Farooque83** [comment]
"""We recommend that the primary address (sometimes referred to as the "User Id") for each user be at the primary domain (such as "will@fabrikaminc.net"). Typically, this means that the primary email address should match between O365 and G Suite"""

IS this mean we have to add our primary domain in office 365 as well to match the Primary Email id? let's say I have my a user at Gsuite user@freelearningforall.com, so freelearningforall.com will also be added in office 365 to match the Primary email address?

**Comment by Farooque83** [comment]
Please also refer to my own Migration guide with detailed steps 
https://gallery.technet.microsoft.com/Perform-a-G-Suite-migration-4eb0ad6d

**Comment by travisadvisicon** [comment]
Yes, that is correct. You will have to have that in o365 in order for it to work.

**Comment by dariomws** [comment]
Hi @bryanfritz, thank you for your feedback.

You need to create or enable mail users for each account in Gmail. You can see it in the [Overview](https://docs.microsoft.com/exchange/mailbox-migration/perform-g-suite-migration#overview-of-the-process) section. In your case, as you have Azure AD Connect, you need to enable synced users as Mail User.

@Abdul8383 "yes" to your question. You can also see it in the [Overview](https://docs.microsoft.com/exchange/mailbox-migration/perform-g-suite-migration#overview-of-the-process) section. Also, the second picture is a good summary of all this information.

**Comment by merwindz** [comment]
We are in the process of migrating over 3000 mailboxes from G-Suite to Exchange Online and we would like to use our AD accounts so we plan to sync them to Azure AD. We have no exchange in the environment and planning to have one to support the migration. Since there is no Exchange attributes in the accounts, how would these accounts appear as Mail Users in Exchange Online? Do I need to add external address for all these accounts in on-premise AD in targetaddress attribute and sync to Azure AD so that it would appear in Exchange Online? Could you please confirm?

**Comment by dariomws** [comment]
Hi @merwindz,

In this case, as you are using Azure AD Connect, you need to install an Exchange server for management, and when you install it you will prepare you AD Schema for Exchange. In this way, you will get the Exchange attributes.
Then, you need to enable mail users on-premises using this Exchange server and they will be synced to Azure AD/Exchange Online.

Hope it helps.

**Comment by merwindz** [comment]
Thanks. Looks like the targetaddress attribute needs to be populated with alias@gsuite.compnayname.com and sync to Azure AD and the migration process will update attribute and account types during the cutover :)

**Comment by merwindz** [comment]
Hi @dariomws, I have managed to create some AD accounts and enabled them for Mail Users in Ex2016 and when we sync to Azure AD, I don't see them appearing in Exchange Online under Mail Contacts pane. When I looked at the properties of these sync account in exchange Online, I don't see external address showing up. Its pretty much exists in AD, i can see that in AADC logs as well but not in Azure AD or EXO. I have logged a call with Office 365 support today and they will check and come back to tomorrow. But wondering if you have worked on similar project and if you had any issues and how it was resolved? Thanks

**Comment by dariomws** [comment]
Hi @merwindz,

I worked on similar projects but generally, I don't see this kind of problem. Mail users should be synced to AAD/EXO if the OU is included.

**Comment by merwindz** [comment]
Hi @dariomws, the accounts are appearing in Azure AD and I can see them in admin portal under Active users but no external and proxy addresses under the account properties. Hence they are not appearing in EO under mail contact  pane. Sounds strange to me!

**Comment by dariomws** [comment]
Looks like some (or all) Exchange properties are not being synced to Azure AD. I cannot help here as docs feedback is available to improve documentation.
Please, follow this issue with support and let us know if you think there is something to update/improve in the document.

Thanks!

**Comment by merwindz** [comment]
Sure, will do :)

**Comment by merwindz** [comment]
So its fixed now! 

AADC was setup first and then Exchange 2016 schema update so it required schema refresh in AADC to sync the Exchange Attributes :)

**Comment by dariomws** [comment]
@merwindz thank you for share the resolution, I´m glad to know that it was fixed!

Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by scanum** [comment]
@bryanfritz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
@scanum To clarify this one, the user who reported the issue has not had their question addressed (the discussion above is with a different user). Please reassign this one for an edit.

**Comment by dariomws** [comment]
Hi @bryanfritz,

Do you still have some concerns about provisioning users? Can I help?

I think you are talking about these two sentences:
"To manually provision mail-enabled users without DirSync, see [Manage mail users](../recipients-in-exchange-online/manage-mail-users.md) for more information."
"Before proceeding with either method, make sure that MailUsers have been provisioned for every user in the organization who will be migrated (either now or eventually). If any users aren't provisioned, provision them using the instructions in [Manage mail users](https://docs.microsoft.com/exchange/recipients-in-exchange-online/manage-mail-users)."

To manage Exchange recipients in an environment with Azure AD Connect, you need to deploy an Exchange Server on-premises (if you don´t have it). Then, you need to create mail users on-premises and they will be synchronized to the cloud.
More information:
https://docs.microsoft.com/exchange/decommission-on-premises-exchange

**Comment by scanum** [comment]
@bryanfritz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
