### ISSUE TITLE
Updated Command

### ISSUE THREAD

**Issue by angusmclean11** [MicrosoftDocs/OfficeDocs-Exchange#1527]
The command for Set-ADSyncUnifiedGroupWritebackPermissions needs to be updated to -ADConnectorAccountName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups?redirectedfrom=MSDN#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by mattpennathe3rd** [comment]
@angusmclean11 Thank you for filing the issue!

@chrisda Would you mind taking a look at this one? Let me know if I may assist.

**Comment by chrisda** [comment]
@angusmclean11, are you saying that the *ADConnectorAccountDN* parameter in the existing command needs to be changed to *ADConnectorAccountName*?

Could you reply with the entire 3 corrected lines of the command that you want?

Thanks.

**Comment by angusmclean11** [comment]
$AzureADConnectSWritebackAccountDN = <AAD_ account DN>
Import-Module "C:\Program Files\Microsoft Azure Active Directory
Connect\AdSyncConfig\AdSyncConfig.psm1"
Set-ADSyncUnifiedGroupWritebackPermissions -ADConnectorAccountName
$AzureADConnectSWritebackAccountDN

**Comment by chrisda** [comment]
@angusmclean11, got it. Topic fixed.

Thanks for the feedback
