### ISSUE TITLE
Mail user steps don't match the current Exchange Admin Center interface

### ISSUE THREAD

**Issue by marcgoff** [MicrosoftDocs/OfficeDocs-Exchange#1528]
The create mail user steps don't match the current Exchange Admin Center interface. Specifically I don't see the UI for step 3 and step 5. I see no option to mail enable an existing user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa08719-f07a-a792-4ef3-9f9f8ae8a498
* Version Independent ID: d649e94b-e464-a4a0-b6b9-6d8ed31c2e73
* Content: [Manage mail users](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-users#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-users.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-users.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by juhap** [comment]
I'm having the same issue. I'm missing the option to choose an existing user. I ended up here from the Gsuite migration documentation. That states you should use the EAC to create new mail users before proceeding with the migration. 

![image](https://user-images.githubusercontent.com/321882/68999685-c2a27a00-08cc-11ea-9298-17ea64dc4318.png)

**Comment by mattpennathe3rd** [comment]
@marcgoff Thanks for opening this issue. The article has been updated and published, but please comment back or feel free to open a new issue if you find any further problems with the documentation.
