### ISSUE TITLE
Calendar events don't sync

### ISSUE THREAD

**Issue by ellsong** [MicrosoftDocs/OfficeDocs-Exchange#1529]
I've performed a couple of test migrations, so far everything including emails and contacts sync perfectly. Calendars don't seem to be working properly however. I understand that shared calendars will not work, but no events from the users' personal calendars show up in Outlook calendar, despite it even showing the names of shared calendars from G Suite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#finalizing-your-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by bryanfritz** [comment]
If you check the Admin Service Health Advisories you will see that there is currently an issue with Migration, Onboarding, and Sync for calendar events from Gmail accounts. The announcement indicates that there will be a fix deployed beginning Friday Nov 15. 2019. It is definitely a pain as I am right in the middle of my migration testing.

**Comment by greg-fischer** [comment]
Wow , glad I saw this! I was just about to start my *worst offenders* mailbox batch.

**Comment by mattpennathe3rd** [comment]
@ellsong I'd love to help, but this does not appear to be a Docs issue. Please open a support ticket if you're still having trouble with your migration, and if you do find a hole in the documentation, let me know and I'd be glad to fix it up.
