### ISSUE TITLE
2 of your examples have the true and false incorrectly switched

### ISSUE THREAD

**Issue by IrishClanger** [MicrosoftDocs/OfficeDocs-Exchange#1530]
"This example enables SMTP AUTH for mailbox sean@contoso.com.
Set-CASMailbox -Identity sean@contoso.com -SmtpClientAuthenticationDisabled $true"       SHOULD BE false
"This example disables SMTP AUTH for mailbox chris@contoso.com.
Set-CASMailbox -Identity chris@contoso.com -SmtpClientAuthenticationDisabled $false"      SHOULD BE true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f463d2b-dfa3-1061-4e34-01fdfd8b5032
* Version Independent ID: a1d6d284-1c4c-438d-caaa-b06f7a7fb8a8
* Content: [Enable or disable SMTP AUTH](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@IrishClanger Thank you very much for pointing this out. I have corrected these and the revised doc will be published in the near future.
