### ISSUE TITLE
Empty Note section in Common questions from end-users

### ISSUE THREAD

**Issue by gcmlpfaltaher** [MicrosoftDocs/OfficeDocs-Exchange#1533]
Under "Q: How much of my mailbox data is synchronized with Outlook for iOS and Android?", there is an empty note section without any information. 

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq?redirectedfrom=MSDN#q-how-much-of-my-mailbox-data-is-synchronized-with-outlook-for-ios-and-android

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook Exchange Online FAQ, Outlook for iOS Exchange FAQ, Outlook for Android FAQ, Outlook for iOS security concerns, Outlook for Android security concerns, Outlook for iOS cloud architecture, Outlook for Android cloud architecture, Outlook app Office 365 architecture, Outlook app attachment faq, Outlook app contacts faq, Outlook app license faq](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq?redirectedfrom=MSDN#q-how-much-of-my-mailbox-data-is-synchronized-with-outlook-for-ios-and-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@gcmlpfaltaher Thank you very much for pointing this out. I've fixed the document and you should see the corrections on the web in the near future.
