### ISSUE TITLE
Update the plans please

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/OfficeDocs-Exchange#1534]
Update that plans that have DLP, this says it's only Exchange Online Plan 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32c304f-a00c-5d66-d3e2-9ddf700d121e
* Version Independent ID: 0bb81f36-0b92-263a-6ee1-9b282f20a44d
* Content: [Data loss prevention](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@VNJoe Thanks for pointing this out. My apologies for the lengthy response time. I've clarified this article a bit to address the incorrect reference to Plan 2 and the changes should be published in the near future. Thanks again for filing the issue.
