### ISSUE TITLE
what about on-prem Exchange setups?

### ISSUE THREAD

**Issue by seamonkey420** [MicrosoftDocs/OfficeDocs-Exchange#1536]
what do we use there? BasicAuth is what i am using but i read that on some other website.  On-prem setups still exist and will continue to exist so stop pretending like they don't exist.  Also, this page should show all possible values for each setting.  seriously, how do i know what i can use for a setting if its not even listed as an option or there isn't even a list of options.  Can someone just do proper documentation for once?   What about account types?  Per example above:

com.microsoft.outlook.EmailProfile.AccountType 	This key specifies the account type being configured based on the authentication model.

Value type: String

Accepted values: ModernAuth

Required: Yes

Example: ModernAuth 	Managed devices
ie BasicAuth = on-prem non hybrid authentication.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#configuration-keys)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by seamonkey420** [comment]
accounttype  aparementers; what are the other options for this field? all you list is ModernAuth however we are not using a hybrid sso/auth scheme.  BasicAuth? WIll post back if that does it.

**Comment by seamonkey420** [comment]
btw.. this is the article that has all the proper critera. why is this one not in this section? this actually describes what the values are for AccountType and also Server Auth.

https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/account-setup?redirectedfrom=MSDN&view=exchserver-2019

**Comment by smithre4** [comment]
@seamonkey420 - Exchange Online and Exchange on-premises content are separated in our documentation as their are distinct differences between the service and the on-premises product.

**Comment by scanum** [comment]
@seamonkey420 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
