### ISSUE TITLE
Disabled Retention Tag

### ISSUE THREAD

**Issue by mramnet** [MicrosoftDocs/OfficeDocs-Exchange#1537]
The first "Note" section has a reference to a "Disabled" retention tag.  This doesn't exist, at least not on Exchange Online - there is no way to disable a tag, you either remove a tag from a policy or delete it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b2e88ce-b09f-d2b4-85e7-cd4aee7825d7
* Version Independent ID: ef06d096-2d84-893b-304a-bd55c16d22e0
* Content: [Messaging records management in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mrm/mrm?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mrm/mrm.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mrm/mrm.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by chrisda** [comment]
@mramnet, OK, but this topic is for on-prem Exchange Server 2016/2019, no? And the note clearly says "In Exchange Server...".

**Comment by chrisda** [comment]
Closing. Feel free to reopen as necessary.
