### ISSUE TITLE
Unable to Sync list of users to EAC from Azure AD Connect 

### ISSUE THREAD

**Issue by bryanfritz** [MicrosoftDocs/OfficeDocs-Exchange#1538]
My users are synced from Azure AD Connect to Azure AD online, however in the EAC under Recipients&gt;Contacts I do not show a list of users. I think this maybe why the forwarding back to Google from Office 365 is not working. Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa08719-f07a-a792-4ef3-9f9f8ae8a498
* Version Independent ID: d649e94b-e464-a4a0-b6b9-6d8ed31c2e73
* Content: [Manage mail users](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-users)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-users.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-users.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@bryanfritz I'm sorry, but this repo is only for reporting documentation problems and we are not able to provide product support here. Your best option is to open a support ticket.
