### ISSUE TITLE
404 Link

### ISSUE THREAD

**Issue by Antitribu** [MicrosoftDocs/OfficeDocs-Exchange#1539]
Section 5.7.511 contains a link for "Removing a user, domain, or IP address from a block list after sending spam email." This links to a 404 error page.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6d0e4-0ea5-f8a9-bf67-bf7cacc74b3e
* Version Independent ID: c72592d3-bfd1-ddf3-793f-dcc0374db074
* Content: [Email non-delivery reports in Exchange Online](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Antitribu Thank you very much for reporting this. I have replaced the link and the change will be published soon.
