### ISSUE TITLE
is neither a valid OPath filter nor a valid LDAP filter

### ISSUE THREAD

**Issue by stevecharon** [MicrosoftDocs/OfficeDocs-Exchange#1541]
There is no way to figure out what is wrong if this message appears. Great stuff. I want my ldapfilters back!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4305c17-0c16-17fa-5f8b-c98eca1fcbe5
* Version Independent ID: 0dfec32f-c762-ff71-92fa-3b624baad494
* Content: [View members of a dynamic distribution group](https://docs.microsoft.com/en-us/Exchange/recipients/dynamic-distribution-groups/view-dynamic-distribution-group-members?redirectedfrom=MSDN&view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/recipients/dynamic-distribution-groups/view-dynamic-distribution-group-members.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/dynamic-distribution-groups/view-dynamic-distribution-group-members.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@stevecharon thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by stevecharon** [comment]
Oh, just great. My tenant is on-premise, so should I submit a ticket with myself?
Documentation nowadays goes to the extent of covering the basics my 10year son figures and anything beyond is just support-heavy. Dont know how that works for you but on my end this is just useless.
