### ISSUE TITLE
Dialtone/Recovery merge

### ISSUE THREAD

**Issue by asampson68** [MicrosoftDocs/OfficeDocs-Exchange#1543]
I have performed every step of these instructions to the letter, and every one of them succeeded up to the final command to merge the dial tone database with the recovery database. When I execute $mailboxes | %{ New-MailboxRestoreRequest -SourceStoreMailbox $_.ExchangeGuid -SourceDatabase RDB1 -TargetMailbox $_ } - copied and pasted exactly from this page, but having replaced the -SourceDatabase with the name of my database of course, I receive the following error every time.

Cannot process argument transformation on parameter 'TargetMailbox'. Cannot convert the "New User" value of type
"Microsoft.Exchange.Data.Directory.Management.Mailbox" to type
"Microsoft.Exchange.Configuration.Tasks.MailboxLocationIdParameter".

I have reset the entire configuration from scratch several times and again everything works perfectly right up to this point. I have searched exhaustively for this error but cannot locate anything useful. Running Exchange Server 2019. Can anyone assist please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c0340f-0d45-476c-cf5d-021d3bd1cb25
* Version Independent ID: f2e88b48-e373-d74d-bcdd-0974af1ed166
* Content: [Perform a dial tone recovery](https://docs.microsoft.com/en-us/exchange/high-availability/disaster-recovery/dial-tone-recovery?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/high-availability/disaster-recovery/dial-tone-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/disaster-recovery/dial-tone-recovery.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by asampson68** [comment]
Is anyone seeing this post? 3 weeks old now...

**Comment by mattpennathe3rd** [comment]
@asampson68 I'm sorry, but this repo is only for reporting problems with the documentation and I am unable to provide product support here. Your best option is to open a support ticket to determine the cause of your trouble. If it turns out there is an error with the documentation, I will be glad to fix it.
