### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bill4344** [MicrosoftDocs/OfficeDocs-Exchange#1544]
There is a typo in the following text (located underneath the first heading):

"The recipient is a group, and ou don't have permission to send to the group or one of its subgroups."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a87ae5-749b-2f7a-8662-61c30af24742
* Version Independent ID: f2f6541e-9e10-e30a-7090-6c39e2a756dc
* Content: [Fix email delivery issues for error code 550 5.7.1 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@bill4344 Thank you for pointing this out. I have fixed this typo and the corrected doc will be published soon.
