### ISSUE TITLE
Modern Authentication for older tenants

### ISSUE THREAD

**Issue by jhueppauff** [MicrosoftDocs/OfficeDocs-Exchange#1545]
Hi,

please mention in this article, that modern Auth is disabled by default for tenants created prior 1st Aug. 2017.
https://docs.microsoft.com/en-us/office365/enterprise/modern-auth-for-office-2013-and-2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@jhueppauff Thanks very much for the suggestion. I have updated the article and the new version will be published in the near future.
