### ISSUE TITLE
More detail required about adding multiple Managed accounts.

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/OfficeDocs-Exchange#1546]
Please can you add an End user question such as 
Q. Will I be able to add a second managed account to my device?
A. Not at present. If you attempt to add a second managed account to a device, you will be prompted to remove one of the accounts from the device.

I know there is already sentance on this earlier on but a more specific question and answer about the experience would be useful. thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook Exchange Online FAQ, Outlook for iOS Exchange FAQ, Outlook for Android FAQ, Outlook for iOS security concerns, Outlook for Android security concerns, Outlook for iOS cloud architecture, Outlook for Android cloud architecture, Outlook app Office 365 architecture, Outlook app attachment faq, Outlook app contacts faq, Outlook app license faq](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq#q-can-i-add-two-different-office-365-accounts-from-different-office-365-regions-to-outlook-for-ios-and-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws** [comment]
Hi @quickclix75, thank you for your feedback.

This answer is covered here:
"Q: Can I add two different Office 365 accounts from different Office 365 regions to Outlook for iOS and Android?
Yes, provided both accounts do not have Intune App Protection Policies assigned."

But I think you want more information, right?

**Comment by scanum** [comment]
@quickclix75 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
@quickclix75 I think we can make this more specific, as you suggested. I will work on this soon and will report back.

**Comment by get-itips** [comment]
> Hi @quickclix75, thank you for your feedback.
> 
> This answer is covered here:
> "Q: Can I add two different Office 365 accounts from different Office 365 regions to Outlook for iOS and Android?
> Yes, provided both accounts do not have Intune App Protection Policies assigned."
> 
> But I think you want more information, right?

Hello @quickclix75 I am taking over this issue you created, have you seen @dariomws question to you?

Thank you

**Comment by scanum** [comment]
@quickclix75 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
