### ISSUE TITLE
pshell instructions to config enhanced filtering

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/OfficeDocs-Exchange#1547]
The Set-InboundConnector cmdlet in only available in the EXO module.  The pshell instructions should be revised to show steps how to connect to EXO (should not mention SCC).

Connecting to SCC to view/change enhanced filter settings is only relevant when using the web UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd501e4-be27-1da8-e250-7cc1ac22c8ec
* Version Independent ID: ada2e5a7-646f-3576-5834-4727151b7743
* Content: [Enhanced filtering for connectors](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@mrkeiths Thank you very much for submitting this issue.

@chrisda Would you have a look at this one, please?

**Comment by chrisda** [comment]
Confirmed. I updated all references/links to Exchange Online PowerShell.

Thanks for the feedback.
