### ISSUE TITLE
Mangled sentence on page

### ISSUE THREAD

**Issue by Sherman8tor** [MicrosoftDocs/OfficeDocs-Exchange#1548]
This link was inserted in such a way that the sentence doesn't make sense.
"And your users can Have users import their own email their own email, contacts, and other mailbox information to an Office 365 mailbox created for them."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d88bea-98ed-5884-ba22-6343f1737caa
* Version Independent ID: 40de1e1c-a2c6-590d-375f-c860aa8524d1
* Content: [Ways to migrate multiple email accounts to Office 365](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/mailbox-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/mailbox-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/mailbox-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Sherman8tor Thank you very much for submitting the issue. I've fixed this and the updated document will be published in the near future.
