### ISSUE TITLE
Public folder mailbox size

### ISSUE THREAD

**Issue by MaratMussabekov** [MicrosoftDocs/OfficeDocs-Exchange#1549]
Hello,
Public folder mailbox size should be marked as "recommended", as it is possible to use mailboxes larger than 100 Gb.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a23d81-8d94-43e8-ad8e-81f267563357
* Version Independent ID: 74331aa8-a175-0be6-46ae-de9be2c83d6a
* Content: [Limits for public folders](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/limits?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/limits.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@MaratMussabekov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@MaratMussabekov Thank you for pointing this out. I have updated the article and the revisions will be published in the near future.
