### ISSUE TITLE
 MacOS Modern Authentication supportability

### ISSUE THREAD

**Issue by gmicho** [MicrosoftDocs/OfficeDocs-Exchange#1551]
We are going to enable modern authentication and we owned some macOS users that using Native macOS mail client. Is macOS modern authenticated aware? if not, is able to failback to basic authentication using app password for MFA?

Any experiences?

**Comment by scanum** [comment]
@gmicho thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
