### ISSUE TITLE
Different Authentication?

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1552]
What about if EXO is using different authentication protocols than on-prem?  For example - many on-prem are using basic auth, but when you move to EXO, it will need to support modern auth as it is recommended to disable basic on EXO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64782645-c171-ec34-aa6c-0e721291c709
* Version Independent ID: 331957d6-f6c6-b11c-80d8-7c336ff13ff8
* Content: [Exchange ActiveSync device settings with Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/activesync-settings)
* Content Source: [Exchange/ExchangeHybrid/activesync-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/activesync-settings.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by NRPPS** [comment]
Any response on this?  I am interested in changing from Cert Based Authentication to Modern Auth.

**Comment by mattpennathe3rd** [comment]
@NRPPS @danmyhre I'm investigating this one to see if we can clarify the article on this point. I will report back as soon as I have an update, but I don't have an ETA at this time.

**Comment by brolifen** [comment]
Please also add some information on the fact that perhaps a user has an EAS profile using domainname\samaccountname as username in the original configuration which is not supported by O365 and might require a reconfiguration of the EAS profile.

**Comment by msdmaguire** [comment]
@danmyhre This article has been updated with links to scripts that support modern auth. Sorry for the delay, but thanks for pointing out the issue.
