### ISSUE TITLE
4.6.2 on 2010 and HCW issues

### ISSUE THREAD

**Issue by daesimps** [MicrosoftDocs/OfficeDocs-Exchange#1553]
This bit confuses me:

We support the installation of any **major** or minor version of the .NET Framework 4.5. If it were a **major** version it would no longer be 4.5

The reason for the question is running the HCW in a pure 2010 environment.  What is the guidance since the HCW needs 4.6.2 or later to run?  Running HCW from a workstation fails due to a version check (https://jaapwesselius.com/tag/net-framework/)

**Comment by mattpennathe3rd** [comment]
@daesimps Thanks for pointing out the documentation issue. I will update the article with a clearer description.

Regarding the second half of your question, I am unable to help and your best bet is to open a support ticket. This repo is only for reporting problems with the documentation and I am not able to provide product support.
