### ISSUE TITLE
REFS Cluster Size

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-Exchange#1558]
Can we add a note on the recommended REFS allocation unit size, since that is also called our for NTFS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0ac9a96-cfe2-d7e3-a40b-13b96af243eb
* Version Independent ID: 3e9dc9a4-a8d6-b375-6c0a-76a72c646fee
* Content: [Exchange Server storage configuration options](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/deployment-ref/storage-configuration?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deployment-ref/storage-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deployment-ref/storage-configuration.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@chrisda Hi Chris! Wondering if there are any updates on the resolution of this request? Thanks!

**Comment by whh5599** [comment]
@officedocspr officedocspr 添加了 Microsoft提交者 标签 on

**Comment by mattpennathe3rd** [comment]
@r-milne I have updated this article and the additions should be published in the near future. FYI, the recommendation for ReFS allocation unit sizes is 64KB.
