### ISSUE TITLE
If the issue is closed, why still the text?

### ISSUE THREAD

**Issue by sietec** [MicrosoftDocs/OfficeDocs-Exchange#1560]
Another person opened a (now closed) issue asking why the delivery report links even still existed if they don't go anywhere.  I certainly agree - it is not only confusing and misleading, but very a very sloppy way to redact a feature (in my humble opinion) while still leaving breadcrumbs indicitive of it still being available.

Thus, the crux of this issue:  If the links have, indeed, been removed, why is there still a disclaimer on this page stating the following (verbatim):

"Currently, there's no direct replacement for delivery reports for users, so the delivery report links in Outlook and Outlook on the web don't go anywhere."

So, at the top of the article, we are told "The feature delivery reports for administrators has been replaced by Message Trace."

Then, the first quote I placed.

Below that is are two even more bizarre 'notes' that say:

  • Delivery reports for users and administrators is still available in on-premises Exchange environments. For more information, see Track messages with delivery reports.

  • Read receipts and delivery notifications aren't related to delivery reports, and are still available in Office 365. For more information, see Add and request read receipts and delivery notifications.

Thus, in a nutshell, this page contradicts itself about 5 times in a span of several hundred characters.

Please note:  I am intentionally being somewhat sarcastic in tone; I, for one, get tired of the standard, boring error reports and current issues etc.  My sarcasm is not intended to demean anyone nor to nullify the validity of this issue.  Please take it with a grain of salt, but also apply the same logic to everything MS documents.  I find these circular references everywhere on docs.microsoft.com - it is really annoying especially considering this is supposed to be the AUTHORITATIVE location for all information Microsoft!

Thanks.  Happy Thanksgiving and Merry Christmas soon thereafter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d2c66-f9d8-7ac2-55c8-1ccfbe966bf6
* Version Independent ID: 3dc90f07-c2bb-9f37-82c2-a713f0b8f27c
* Content: [What happened to delivery reports in Office 365?](https://docs.microsoft.com/en-us/exchange/monitoring/what-happened-to-delivery-reports-in-office-365)
* Content Source: [Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by sietec** [comment]
Ping

**Comment by mattpennathe3rd** [comment]
@sietec Thanks for your patience and for the candid feedback. I've done my best to clean up the article so there is less fluff, so I hope the new version is a bit clearer. It should be published in the near future, but if you have further feedback, please report back and/or open a new issue.

I'm just the docs guy, so all I can do is help with what's in this repo. Thanks again for your feedback.
