### ISSUE TITLE
AllowBasicAuthRest

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-Exchange#1561]
When I create a new authentication policy it includes the Value `AllowBasicAuthRest` which seems to be undocumented. Is this something internal?
Apparently `-AllowBasicAuthRest` is also not a parameter within the `Set-AuthenticationPolicy` cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@Weishaupt thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Weishaupt** [comment]
@scanum can you elaborate why this is the best course of action? This is clearly related to missing documentation.

**Comment by mattpennathe3rd** [comment]
@Weishaupt This does indeed look like there might be something missing, so I have reopened this issue. I'm sorry about the delay in responding substantively. I'll need to investigate further, but will post back in the near future.

**Comment by kitleyn** [comment]
@mattpennathe3rd Any progress on this? The Powershell cmdlet still doesn't allow you to set the parameter and the docs have still not been updated

**Comment by npigit** [comment]
@mattpennathe3rd  I am facing the same issue. I want to enable AllowBasicAuthRest on my policy however the I got an error:

set-AuthenticationPolicy -Identity "Allow Basic Auth" -AllowBasicAuthRest
A parameter cannot be found that matches parameter name 'AllowBasicAuthRest'.
    + CategoryInfo          : InvalidArgument: (:) [Set-AuthenticationPolicy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-AuthenticationPolicy
    + PSComputerName        : outlook.office365.com

**Comment by radimek** [comment]
Hello I have the same issue now. Do you know when the issue (AllowBasicAuthRest - param)  will be fix? Do you have any workaround?

**Comment by cloudtroll** [comment]
Please I am also waiting for this to be fixed, I cannot set -AllowBasicAuthRest

**Comment by cloudtroll** [comment]
You can ignore that parameter 

I contacted support directly and got the following response. 

So I did do my research and below are my findings:

I would like to inform you that from November 2018, Microsoft has stopped supporting Basic Authentication in the Office 365 Outlook REST API v1.0.

And  from November 1st, 2019, Microsoft has decommissioned the Outlook REST API v1.0 in favor of Microsoft Graph and Outlook REST API v2.0. This means that new or existing apps has stopped using Basic Authentication in Outlook REST API v1.0 from November 1st, 2018 and has stopped to use Outlook REST API v1.0 at all from November 1st, 2019.

If you have been using the Outlook REST v1.0 API in your app, you should plan on transitioning to Microsoft Graph-based Outlook REST APIs to continue accessing Exchange Online data. 

Please refer this article https://docs.microsoft.com/en-us/powershell/module/exchange/set-authenticationpolicy?view=exchange-ps with the latest switched available for the command set-authenticationpolicy 

For more clarity on this, please refer the below article:

https://developer.microsoft.com/en-us/office/blogs/outlook-rest-api-v1-0-basicauth-deprecation/
https://developer.microsoft.com/en-us/office/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation/

**Comment by get-itips** [comment]
Hello everyone on this thread.
I could verify the information shared by @cloudtroll here, the cmdlet does not include that parameter anymore. Thanks @cloudtroll for sharing that info here for everyone.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
