### ISSUE TITLE
include statement on IMAP POP3

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-Exchange#1562]
whilst other clients are covered - please include a statement on the affect of modern authenticaiton enablement in EXO in relation to use of POP3 / IMAP.  (this is on the basis of as-is usage before basic auth is switched off for pop imap)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by Brain2000** [comment]
I'd like to know what the status update is as well. We are currently pulling around 2500 IMAP accounts for our customers, many which are 365 customers, and would like to know what we have to do in order to make this continue to work.

**Comment by jasonstroup2002** [comment]
Running this command WILL break IMAP/POP3 unless you set up conditional access policies in AzureAD to specifically allowing it for individual accounts.   The exchange team made a blog post in 2/2020 that support is coming for ModernAuth with imap/pop3 but is not currently available.

**Comment by Brain2000** [comment]
In October they're all going to break unless Microsoft releases IMAP with Modern Auth for O365.
As a service provider, that is concerning to me. According to this link it is not complete yet:

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282

>> We’ve completed our development work and are rolling out Modern Auth support for POP and IMAP in Exchange Online now. Documentation for developers is being finalized and we’ll link to it in this blog post when it is available.

**Comment by mattpennathe3rd** [comment]
@bakerm00 @Brain2000 @jasontroup2002 So, it appears this is covered in [this blog post](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282) in the "POP, IMAP and SMTP" section. Support for this is gradually rolling out, and as announced in [another blog post from last week](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508), Basic Auth support is now not planned to be disabled until the second half of 2021.

I am actively working on updating the documentation and I should soon have more information for you. I will report back in the near future.

**Comment by bakerm00** [comment]
If you read further - the change has been deferred TIL h2 21

Mike Baker

________________________________

**Comment by mattpennathe3rd** [comment]
@bakerm00 I've added a note to this article pointing out that IMAP and POP3 access are blocked when modern auth is enabled (at least for the time being). As mentioned, there are some future plans to make this more robust.

The update should be published later today. Please let me know if I can do anything further on this article.
