### ISSUE TITLE
No Support for Modern Auth

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1563]
This script:
Sync-MailPublicFolders.ps1

Does not support modern auth so the instructions don't work.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1812196b-e6c5-7f6e-fa82-49df2a47d73d
* Version Independent ID: cc06c76a-b7a0-7c21-0a73-c66b9b05a055
* Content: [Configure Exchange 2013 public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback.

It won't work only if you have basic authentication disabled. Basic authentication won't be disabled by Microsoft until the second half of 2021. More information:
https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508

**Comment by danmyhre** [comment]
Right, but many organizations have already done that, or are in the process of disabling it as it is best practice.  Originally it was October, but with the recent change, we do have more time.  The process still has to be updated to use modern auth / the new Exchange powershell modules.

**Comment by mattpennathe3rd** [comment]
@danmyhre You are correct. I'll try to slot in some work on this in the near future, but it might be a little while before I can fit it in. I appreciate your pointing this out.

**Comment by dariomws** [comment]
I understand that to support Modern Authentication the script should be updated as it's using New-PSSession instead of Connect-EXOPSSession or Connect-ExchangeOnline.

**Comment by dariomws** [comment]
@danmyhre the script was updated 18 days ago.

You can see that it´s called Sync-ModernMailPublicFolders.ps1 now.

Thanks again, for taking out some time to open the issue. I appreciate and encourage you to do the same in the future also.

**Comment by danmyhre** [comment]
it doesn't look like this has been updated to support modern auth and page is still saying it requires basic auth / examples use basic auth (get-credential)

**Comment by dariomws** [comment]
@danmyhre yes sorry, it was my mistake. I thought that they were updated to add Modern Auth but really the update was related to "Modern Public Folders".

I'll report this.

**Comment by msdmaguire** [comment]
@danmyhre I confirmed with the product team that the public folder sync scripts are not enabled for modern auth yet. There is a work item pending, however, with the engineering team, but right now the timeline is unknown. Sorry I can't be more helpful, other than to say the change is coming.

**Comment by danmyhre** [comment]
Sounds good, thanks for the update!

**Comment by Weishaupt** [comment]
@mattpennathe3rd @msdmaguire This issue is over a year old and the script still does not support modern authentication.

**Comment by despich** [comment]
OK some good news. I have a problem with my tenant that I cannot just reenable the older Basic authentication to solve this problem like Microsoft and everyone suggests as a solution. Like no matter what, (I have had a MS ticket open on it for over a month). 
So I discovered that the script could be rewritten slightly so if you have a existing modern V2 exchange online connection it will run. It does this by using  Module-Qualified Cmdlet Names. So basically it can run commands for both local exchange and Exchange online at the same time which is what you need for the sync script to work.
So to run this script open exchange management shell on your Exchange server. Then connect to exchange online using the new modern authentication method like this.

```
install-module -name exchangeonlinemanagement
connect-exchangeonline -UserPrincipalName "your365accountusername"
```

Then modify this script for your specific powershell module name (the mail1.ptraders.local part in the script) and run it and it should work. It worked for me after being "stuck" on this step of our migration for like a month!

[Sync-ModernMailPublicFoldersV2.txt](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/files/7086712/Sync-ModernMailPublicFoldersV2.txt)

I am sure someone could clean this up more and add some better error checking and handle doing the connect-exchangeonline part for you.

**Comment by Weishaupt** [comment]
I've also rewritten the script to work with the V2 module, but this doesn't fix it for the others out there, as the script is distributed by the MS Download servers. This should really be taken up by the Exchange team and be fixed!

**Comment by DougWBergman** [comment]
@despich - Thank you for sharing this work.

**Comment by rocmail520** [comment]
Please re-open as the Sync scripts are not updated. Its a shame on MS to not keep track and taking forever to fix

**Comment by KnowMoreIT** [comment]
Why is this closed when it was not fixed @danmyhre ?

**Comment by danmyhre** [comment]
@KnowMoreIT That is up to Microsoft, not me :)   @msdmaguire

**Comment by KnowMoreIT** [comment]
> @KnowMoreIT That is up to Microsoft, not me :) @msdmaguire 
Tagged the wrong person lol

**Comment by GitHubUser010** [comment]
@despich Hello, thank you for sharing your script.  I tried running get-module and I don't see one name "local".  Can you tell me what you are referring to by "local"?  Is it possibly the hostname of your CAS? thanks!

**Comment by markdepalma** [comment]
I created an article on using modern auth in the scipt without any modifications here: [https://blog.markdepalma.com/?p=840](https://blog.markdepalma.com/?p=840). Basically we need to create a basic-type credential with a bearer token and then pass that to EXO using the BasicAuthToOAuthConversion option.

**Comment by Weishaupt** [comment]
The product group [finally announced](https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-public-folder-migration-scripts-with-modern/ba-p/3382800) direct support for modern authentication in the provided scripts. Something which has been requested here starting in 2019. It really is a pity, that it took so long.
[Direct download link](https://www.microsoft.com/en-us/download/details.aspx?id=54855)
