### ISSUE TITLE
Missing details for Exchange Online

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1565]
Need to create a version of this page for Exchange Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8a247a-3cba-11ae-2292-f5aba59b73ac
* Version Independent ID: 635e7122-317f-1ae7-053f-774f3db998d4
* Content: [Procedures for email address policies in Exchange Server](https://docs.microsoft.com/en-us/Exchange/email-addresses-and-address-books/email-address-policies/eap-procedures?view=exchserver-2019&viewFallbackFrom=exchonline-ww#apply-email-address-policies-to-recipients)
* Content Source: [Exchange/ExchangeServer/email-addresses-and-address-books/email-address-policies/eap-procedures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/email-addresses-and-address-books/email-address-policies/eap-procedures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by martmengle** [comment]
Also need to make it work for more than just groups in Exchange Online too, please! For example.. users.  ;-)

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback.

Email Address Policies aren't available in Exchange Online Admin Center. In Exchange Online, email address policies are only available for Office 365 groups and you should use *-EmailAddressPolicy cmdlets to manage them.

**Comment by mattpennathe3rd** [comment]
@dariomws I suspect that @danmyhre was asking for an article describing how to use those cmdlets, which is documentation that we seem to lack (aside from PowerShell reference documentation). This article will need some extensive adaptation in that case, but I will look into it.

**Comment by dariomws** [comment]
@danmyhre I cannot create a new article for email address policies in Exchange Online, but you need to use PowerShell to manage them. You can check the following articles:
https://docs.microsoft.com/powershell/module/exchange/new-emailaddresspolicy
https://docs.microsoft.com/powershell/module/exchange/get-emailaddresspolicy
https://docs.microsoft.com/powershell/module/exchange/set-emailaddresspolicy
https://docs.microsoft.com/powershell/module/exchange/remove-emailaddresspolicy

@shatterednerves to request new features or improve existing, please go to user voice. For example:
https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/8426817-implement-email-address-policy

**Comment by danmyhre** [comment]
correct @mattpennathe3rd.  I would think a version of the page for EXO describing what is supported and what isn't for EXO would be good.

**Comment by mattpennathe3rd** [comment]
@danmyhre I am sorry, but I have left Microsoft and will not be able to assist any further with this issue.

**Comment by msdmaguire** [comment]
@danmyhre  That is a great suggestion, which we will add to our back log of work items for future triage.
