### ISSUE TITLE
Commands overwrite Anon permissions by accident

### ISSUE THREAD

**Issue by briankern** [MicrosoftDocs/OfficeDocs-Exchange#1566]
Section: Configure the connections as externally secured
Command: Set-ReceiveConnector "Anonymous Relay" -AuthMechanism ExternalAuthoritative -PermissionGroups ExchangeServers

If you want to set the auth mechanism to External, you have to have ExchangeServers as a permission group. However, running Set-ReceiveConnector like this blows away the Anonymous permission group from Step 2/part 1; 
Set-ReceiveConnector "Anonymous Relay" -PermissionGroups AnonymousUsers

A better way to proceed is to combine these steps, like:
Set-ReceiveConnector "Anonymous Relay" -AuthMechanism ExternalAuthoritative -PermissionGroups ExchangeServers,AnonymousUsers 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 532fc1f6-dd6e-7c9c-0483-db61afcd7918
* Version Independent ID: 95b7e7f4-b515-0ad2-27fd-080055250855
* Content: [Allow anonymous relay on Exchange servers](https://docs.microsoft.com/en-us/Exchange/mail-flow/connectors/allow-anonymous-relay?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/connectors/allow-anonymous-relay.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/connectors/allow-anonymous-relay.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws** [comment]
Hi @briankern, thank you for your feedback.

You have to choose one method, anonymous or external, not both.

From the article:
"As described in the introduction, there are two different methods you can use to configure the required permissions on the Receive connector:

- Configure the connections as anonymous.

- Configure the connections as externally secured.

Choose one method or the other."

**Comment by mattpennathe3rd** [comment]
@briankern These two commands are mutually exclusive; you should only be using one, as described in the article.

I believe the article is correct, so I will close this issue now, but please comment back if we have misunderstood or need further clarification on something in the article.
