### ISSUE TITLE
Change MX record before migrating data.

### ISSUE THREAD

**Issue by undoneph** [MicrosoftDocs/OfficeDocs-Exchange#1567]
Greetings, are there negative effects if we point the MX records to the new email address before migrating the data over? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer G Suite mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@undoneph I am sorry, but I am unable to answer product support questions here. This repository is only for reporting problems with the documentation. Please open a support ticket to obtain help with your question.
