### ISSUE TITLE
Documantation mistake

### ISSUE THREAD

**Issue by Inbalsas** [MicrosoftDocs/OfficeDocs-Exchange#1570]
The behavior described in "the Holds and email forwarding" section of the article currently only applies to Exchange Online. In Exchange on-premises, the RediredctHoldAgent is not active, so a copy of a forwarded item is not placed in Recovreable Items, but in the Inbox. Can the article be corrected to state this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0957d8b7-cb89-0aa7-f8ac-329aa3c2b085
* Version Independent ID: 21e5f86c-104d-bdec-8092-c2efc7e0574c
* Content: [In-Place Hold and Litigation Hold in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/holds/holds?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/holds/holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/holds/holds.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Inbalsas Thank you for pointing this out. I've corrected the article and the revised text will be published in the near future. Thank you, again.
