### ISSUE TITLE
Modern Hybrid Certificate Renewal

### ISSUE THREAD

**Issue by jmrita** [MicrosoftDocs/OfficeDocs-Exchange#1572]
Suggest adding some info regarding Modern Hybrid Certificate, namely how it is renewed and if this task is done automatically or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#additional-information)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@jmrita Thanks for filing this issue. I'll investigate your suggestion and will report back in the near future.

**Comment by mattpennathe3rd** [comment]
@jmrita I believe this information is covered in [Certificate Requirements](https://docs.microsoft.com/en-us/exchange/certificate-requirements). Certificates must be purchased from a 3rd-party certificate authority.
