### ISSUE TITLE
It looks like there is a mistake in the syntax of the cmdlet to remove the SCP

### ISSUE THREAD

**Issue by humbeglez** [MicrosoftDocs/OfficeDocs-Exchange#1575]
Shouldn't it be Get-ClientAccessService | Set-ClientAccessService -AutoDiscoverServiceInternalUri $Null instead of "Get-Get-ClientAccessService | Set-Get-ClientAccessService -AutoDiscoverServiceInternalUri $Null" and the cmdlet would be the same for all server versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#feedback)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@chrisda Would you mind taking a look at this one, please?

**Comment by chrisda** [comment]
Yes, very much a mistake. I fixed it.

@humbeglez, in the future, you, too can make updates like this directly in the topic; no need to open a GitHub Issue first. For instructions, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.

Thanks for the feedback.
