### ISSUE TITLE
SMTP relay Option1 will not be longer work with Baseline security

### ISSUE THREAD

**Issue by mozilla0** [MicrosoftDocs/OfficeDocs-Exchange#1581]
The SMTP relay Option1 with Office 365 (Exchange Online) is not longer working if your enable "Baseline security policy: Block legacy protocols".
https://docs.microsoft.com/de-ch/azure/active-directory/conditional-access/concept-baseline-protection

 How is the way to work like option1 with enabled baseline security in AAD?

**Comment by scanum** [comment]
@mozilla0 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
