### ISSUE TITLE
Gmail App for Android

### ISSUE THREAD

**Issue by Niels-NL** [MicrosoftDocs/OfficeDocs-Exchange#1582]
Please add the Gmail App for Android to the list as support apps, as it is now supported.
If you are mentioning Mail for IOS, you must do the same for Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online?source=docs#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Niels-NL Thanks for filing the issue. Can you point me to something that shows where this has been introduced as a feature in GMail for Android so I can get more background information? As of just a few weeks ago, this was not yet implemented in the app.

**Comment by Niels-NL** [comment]
Thanks for the reply, i wasnt able to find any background information on this. But it does work.

**Comment by p0shkar** [comment]
Does not work for us. Been trying to find info about support for MA but can't find anything concrete. After MFA approval by the ADFS, gmail tries to fetch emails and gets error "Can't reach server".

**Comment by Niels-NL** [comment]
@p0shkar are you testing it on a android device or apple?
We have already about 664 users who are using it in our tenant.
See screenshot i created in the cloud app portal.
![image](https://user-images.githubusercontent.com/58592262/74437823-1e978300-4e69-11ea-8d6e-545e0c328b8d.png)

**Comment by p0shkar** [comment]
@niels-NL Android device, non-corporate managed. Created the Authentication Policy with default settings (no basic auth allowed) and as soon as it got activated for the test users it stopped working with the gmail app (not g-suite).

**Comment by mattpennathe3rd** [comment]
@Niels-NL @p0shkar I've done a lot of research on this around the web and the experience seems to be very inconsistent. It looks like it was possibly once supported, then broken, then fixed, or users restored functionality using various workarounds. But it still does not seem to work universally.

I'm going to close this issue for now, but once this is officially supported, I'll be very glad to update the article. Please feel free to open a new issue when the situation stabilizes.
