### ISSUE TITLE
AD Environment version clarification

### ISSUE THREAD

**Issue by crk5070** [MicrosoftDocs/OfficeDocs-Exchange#1583]
I noticed under the "Supported Active Directory environments" section that Server 2008 R2 SP1 was listed above Server 2008 R2 SP2 in that table. For newer Exchange 2016 CUs (like CU12 and later), it gives the appearance that SP1 is supported, but SP2 is not. Should I assume it's the other way around?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@crk5070 The table is correct as written. The (admittedly easy to miss) difference is that it is Windows Server 2008 R2 SP1 versus Windows Server 2008 SP2 (that is, SP2 of the first release of Windows Server 2008 and not SP2 of R2). I'm uncertain how to make this distinction more obvious given the very similar product names, but I am certainly open to suggestions.

Let me know if you run into any other problems with the documentation and I'd be glad to take a look at them.
