### ISSUE TITLE
Exchange Online Requirements

### ISSUE THREAD

**Issue by Weychris** [MicrosoftDocs/OfficeDocs-Exchange#1588]
Looking for official document that states which Office versions work with Exchange Online.

The page: (https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/clients-and-mobile-devices?redirectedfrom=MSDN#Microsoft%20Outlook) links here with the following text:
For information about which Outlook clients are supported by Exchange 2016 and Exchange Online, see "Supported clients" in Exchange 2016 system requirements.

There's nothing on this page that mentions Exchange Online - requesting clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?redirectedfrom=MSDN&view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Weychris I apologize, but can you clarify your question? 

The article at https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?redirectedfrom=MSDN&view=exchserver-2019 does not contain information about Exchange Online because that is the on-premise Exchange Server documentation. Did I misunderstand?

**Comment by scanum** [comment]
@Weychris We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
