### ISSUE TITLE
Rule Priority

### ISSUE THREAD

**Issue by asampson68** [MicrosoftDocs/OfficeDocs-Exchange#1589]
Taken directly from this page... "In the EAC, rules are processed in the order that they're displayed (the first rule has the Priority value 0). To change the priority of a rule, move the rule up or down in the list (you can't directly modify the Priority number in the EAC)."  Well, I'm in the EAC right now and looking at a "Priority" value when I double-click the rule, and it IS configurable (tested by changing it and saving the rule). Clearly it can be directly modified in the EAC. Furthermore, selecting the rule and just clicking the "move up" and "move down" arrows does NOT change the priority value, it appears to only change the processing order. In other words, the first rule may process FIRST, but if the second rule has a higher priority and there is a conflict, the second rule will override. Please clarify and/or update your documentation. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ba6e34-c183-fbfb-149a-52144a0a66f4
* Version Independent ID: 8c325a7f-e6a9-64fc-b8e3-96f136bab959
* Content: [Procedures for mail flow rules in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mail-flow-rules/mail-flow-rule-procedures?view=exchserver-2019#what-do-you-need-to-know-before-you-begin)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/mail-flow-rule-procedures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/mail-flow-rule-procedures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by asampson68** [comment]
Correction - using the arrows to move is in fact changing the priority, but the value is still directly configurable in the EAC by double-clicking the rule and changing its value, then saving the rule.

**Comment by get-itips** [comment]
Thanks for your feedback @asampson68 ! I tested and verified.
