### ISSUE TITLE
Steps referenced, but not linked

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/OfficeDocs-Exchange#159]
In the implementation steps, it says:
1.  The first policy allows Outlook for iOS and Android, and it blocks OAuth capable Exchange ActiveSync clients from connecting to Exchange Online. See "Step 1 - Configure an Azure AD conditional access policy for Exchange Online."
2.  The second policy prevents Exchange ActiveSync clients leveraging basic authentication from connecting to Exchange Online. See "Step 2 - Configure an Azure AD conditional access policy for Exchange Online with Active Sync (EAS)."
Neither of these steps is listed in the article nor are they links to other articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0020c770-fbf0-d36b-196c-59fd0a5dbe93
* Version Independent ID: bd5c069a-c325-28cf-5a58-8ae9c34c793d
* Content: [Using hybrid Modern Authentication with Outlook for iOS and Android](https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019#implementation-steps)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@WillMartin58 thanks for the feedback. I added the links. The target topic was mentioned in the previous paragraph, but I can see how it would be hard to miss.
