### ISSUE TITLE
Incorrect command

### ISSUE THREAD

**Issue by mumische** [MicrosoftDocs/OfficeDocs-Exchange#1590]
Invoke-MonitoringProbe UM.Protocol\UMSelfTestMonitor -Server server1.contoso.com | Format-List

Instead of UMSelfTestMonitor there must be UMSelfTestProbe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98239503-1fb1-4ec8-496b-6fc1642b8da8
* Version Independent ID: 0e934e68-f458-751d-e548-f9e787bbc602
* Content: [Troubleshooting UM.Protocol Health Set](https://docs.microsoft.com/en-us/exchange/management/health/troubleshooting-um-protocol-health-set#feedback)
* Content Source: [Exchange/ExchangeServer2013/management/health/troubleshooting-um-protocol-health-set.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/management/health/troubleshooting-um-protocol-health-set.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@mumische Thanks for the report. I will investigate further and a fix should be published in the near future.

**Comment by arielmoisis** [comment]
This doco is still out of date with the incorrect command.

**Comment by michelderooij** [comment]
Doc has been updated; perhaps your clone of the doc needs updating to reflect the changes?

**Comment by arielmoisis** [comment]
Hi The public docs website has the wrong info still. https://docs.microsoft.com/en-us/exchange/management/health/troubleshooting-um-health-set
