### ISSUE TITLE
forwardingsmtpaddress vs forwardingaddress

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/OfficeDocs-Exchange#1591]
google hits this page when looking for info.
Looking for answer as to the change on the new admin system. 
You used to be able to change the forwarding address directly from the user in the admin system which changed the attribute forwardingsmtpaddress but it appears now that you can only do forwarding from EAC via the method outlined above.
The issue with that is that all our forwarding was always done via the admin center so we have no way to see without powershell what the existing attribute is or if there is even one set!
This appears to be a most annoying over sight!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afdaec1b-3f68-1f0e-db9e-1d8acf20ac4a
* Version Independent ID: fb622286-016d-86e5-a794-d2c3c9696cc5
* Content: [Configure email forwarding for a mailbox](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/email-forwarding?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@webstaff According to the documentation, the forwarding attribute should also be viewable in the admin center, in addition to PowerShell. Is this not the case?

**Comment by scanum** [comment]
@webstaff We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by webstaff** [comment]
Not sure if the something was wrong on the new partner page but the admin pages reappeared the next day and we could make changes as we used to.
Apologies for the delay getting back to you but yes please feel free to close the note.
Best Regards
Dave
