### ISSUE TITLE
Multiple domains on one tenancy

### ISSUE THREAD

**Issue by JonBrown-61** [MicrosoftDocs/OfficeDocs-Exchange#1592]
I have followed these instruction and have enabled  modern authentication - when I run the Get-OrganiztionConfig command to verify the change I only see the onmicrosoft.com domain listed .

What do I need to do to enable / check for my main domain?

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-gb/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@JonBrown-61 I'm sorry you're having trouble, but this doesn't appear to be a documentation problem; the command should work as written. If you need help in getting this to work in your environment, please open a Support ticket.
