### ISSUE TITLE
Missing Information under "What's a bare line feed?"

### ISSUE THREAD

**Issue by JackBergman** [MicrosoftDocs/OfficeDocs-Exchange#1593]
Under the section "What's a bare line feed?" there is no data. https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-6-11-in-exchange-online#whats-a-bare-line-feed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ef3b65-383a-be3d-f5fb-f4294717826e
* Version Independent ID: 36f25162-c9fd-5518-ae0e-487119aeaec9
* Content: [Fix email delivery issues for error code 550 5.6.11 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-6-11-in-exchange-online#whats-a-bare-line-feed)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-6-11-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-6-11-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@JackBergman Thanks for pointing this out. I'll look into this in the near future and will keep you posted.

**Comment by chrisda** [comment]
Fixed. Thanks for the feedback.
