### ISSUE TITLE
"This property returns messages that were sent by with the specified Sent time stamp."

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/OfficeDocs-Exchange#1594]
Sent by who? Appears to be missing a word :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13ed7898-855a-097c-8959-98913a1c645e
* Version Independent ID: 551dd77c-73a9-a306-1501-8b904311fcea
* Content: [Filterable properties for the -ContentFilter parameter](https://docs.microsoft.com/en-us/exchange/filterable-properties-for-the-contentfilter-parameter?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeServer2013/filterable-properties-for-the-contentfilter-parameter.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/filterable-properties-for-the-contentfilter-parameter.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@campbellkerr Thank you very much for submitting this issue! I have fixed this and the revised article will be published in the near future.
