### ISSUE TITLE
Open questions about file content scanning

### ISSUE THREAD

**Issue by GiantCrocodile** [MicrosoftDocs/OfficeDocs-Exchange#1596]
Hello,

what about raw/plain file types like CSV, SVG? They are missing here (https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/inspect-message-attachments#supported-file-types-for-mail-flow-rule-content-inspection) and there is no general statement regarding raw/plain file types given.

What kind of content is detected in a PDF: What about meta data within the PDF, embedded images, bookmarks/generated Table of Content, etc.?

> Note that the 1 MB limit refers to the extracted text, not the file size of the attachment. For example, a 2 MB file may contain less than 1 MB of text, so all of the text would be inspected.

Where is this limit mentioned? These are the only sentences which talk about a text limit in file content inspection.

> All of these conditions will scan compressed archive attachments.

What kind of archives are supported (which file formats)?

Thank you for clarifying this!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd230cd-1717-a932-a5c9-02db4f1b050c
* Version Independent ID: 24dcb706-d0d9-61d3-e99d-289db401ffaa
* Content: [Use mail flow rules to inspect message attachments in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/inspect-message-attachments#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@GiantCrocodile thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by GiantCrocodile** [comment]
Service request (Ticket-ID # 18753425) has been opened.

**Comment by GiantCrocodile** [comment]
Hi @scanum! I tried to ask the support to answer these questions. This didn't go well so far:

First they stated that they have only the same information as me in the online documentation. I complained about that. Then they stated that the information can't be published or given out to customers as it's sensitive information regarding security and product information. I once again complained and after that the support person escalated my service request and they tell me now that they can either help with debugging if a specific sensitive info type is broken or if the compliance function can't scan certain files but they won't answer theoretical questions.

I'm sorry but this is no support at all. If I have to tell the support three times why this information is important and that it's not just their job to read an online documentation it's disappointing and nowhere-going. Can we have someone to discuss this issue with the responsible support engineer and escalation team so they will answer these questions? As stated in my previous reply, service request id is 18753425.

Thank you!

**Comment by mattpennathe3rd** [comment]
@GiantCrocodile I'm sorry for your trouble. I cannot promise anything on the support side of things, as I don't have much access to that team, but I am looking into your questions to see if we can get more details into this article. I will report back and will let you know what's possible here.

**Comment by mattpennathe3rd** [comment]
@GiantCrocodile I've dug into this and because this kind of information is subject to change as the service evolves, it's just too detailed to document reliably. I'm sorry that I can't be of more help on your question.

**Comment by GiantCrocodile** [comment]
@mattpennathe3rd I'm not sure this is true: PDF is such a widespread standard that we won't see major changes there and the same is true for raw/plain file types like CSV files or XML files (SVG). Also it's not much work to list the one or two archive types you do support. Furthermore it's still unclear what limit this article refers to.

I have to say that this makes (from a technical point of view) no sense at all. This information will be valid for years.
