### ISSUE TITLE
Request for clarification on ediscovery/delete-messages.md

### ISSUE THREAD

**Issue by tp-seiso** [MicrosoftDocs/OfficeDocs-Exchange#1597]
Line 45 in [delete-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/ediscovery/delete-messages.md) states that compliance search and delete is not "intended to clean up user mailboxes" but rather it is a tool for incident response. It does not offer an alternative. Is there a tool for mailbox clean up that can be offered as a solution for that use case?

**Comment by markjjo** [comment]
@tp-seiso An admin can use the Search-Mailbox -DeleteContent command to "clean up" user mailboxes. See https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/search-mailbox?view=exchange-ps

**Comment by markjjo** [comment]
Another useful topic on search-mailbox: https://docs.microsoft.com/en-us/Exchange/search-for-and-delete-messages-exchange-2013-help
