### ISSUE TITLE
Please Add Additional Details on Outbound Proxy Configuration

### ISSUE THREAD

**Issue by sgreenlee11** [MicrosoftDocs/OfficeDocs-Exchange#1598]
Hello,

This article calls out that the Hybrid Agent can use an outbound proxy for requests as long as authentication is not required. However, details on how to configure this links to generic guidance for Azure AD Application Proxy. That documentation indicates the .config file to be modified is "C:\Program Files\Microsoft AAD App Proxy Connector\ApplicationProxyConnectorService.exe.config". However, this file isn't present with the Hybrid Agent config and the correct file looks to be "C:\Program Files\Microsoft Hybrid Service\Microsoft.Online.EME.Hybrid.Agent.Service.exe.config". Additionally it looks a PowerShell script is installed with the Agent that makes configuring the proxy much easier. It would be great if the article could note that the script should be used and provide an example instead of linking to the AAD App Proxy documentation.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@sgreenlee11 Thanks for submitting this issue. I'm going to look into this and will report back on what I can do to clarify this article.

**Comment by get-itips** [comment]
Hello @sgreenlee11 I am looking into this. Thanks
