### ISSUE TITLE
Edit on step two

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/OfficeDocs-Exchange#16]
the second cmdlet should include -resultsize unlimited

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6010593-c3e4-87a6-4084-27d56f23063c
* Version Independent ID: 32a2adeb-0932-3236-09d9-b7987393639b
* Content: [Use batch migration to migrate public folders to Exchange 2016 from previous versions](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/batch-migration-from-previous-versions)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md)
* Product: **exchange-server-itpro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Thank you for your feedback. We are currently verifying this point with the product team and will update the article accordingly.
