### ISSUE TITLE
Add details

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1602]
setting default sharing level
Free/busy only or free/busy + subject

options to delete the subject, organizer in subject, etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1598a231-d154-1c94-d8aa-76084b45ed35
* Version Independent ID: 3cc7eb58-d64e-73f2-8566-f97ec30ac15e
* Content: [Create and manage room mailboxes](https://docs.microsoft.com/en-us/exchange/recipients/room-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/recipients/room-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/room-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback and help us to improve docs.microsoft.com.

I don't understand very well your request but I think that the options that you are mentioning can be configured using the Set-CalendarProcessing cmdlet. In the article for this cmdlet, you can find more detail and is referenced here.

**Comment by scanum** [comment]
@danmyhre  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by danmyhre** [comment]
This was an old issue, but I think I was saying that this page should include details on setting those options for room resources.  It is also missing a version of the page for Exchange Online (Worldwide)
