### ISSUE TITLE
mailtips for Outlook on iOS

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/OfficeDocs-Exchange#1604]
Does any of the above settings also apply to Outlook on iOS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c34a8f0-2eca-250c-f85a-b1b53e7f0ec9
* Version Independent ID: 0bbb9cef-0e4b-6107-5eac-41e5ee3e1f89
* Content: [MailTips](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/mailtips)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/mailtips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/mailtips.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@sebhe Thanks for filing the issue. The docs are indeed not very specific, so I am looking into this and will get back to you in the near future.

**Comment by mattpennathe3rd** [comment]
@sebhe I have verified that Outlook Mobile supports the External Recipients MailTip for Office 365 and for on-premises Exchange mailboxes that use Hybrid Modern Authentication (HMA). I've updated the doc and the change will be published in the near future. Thank you again for raising this issue!
