### ISSUE TITLE
Script errors

### ISSUE THREAD

**Issue by chawkins99** [MicrosoftDocs/OfficeDocs-Exchange#1606]
There are errors in both of the scripts here.
In the first script, the line:
$CloudEmailAddress = $user.EmailAddresses | ?{($_ -match 'onmicrosoft') -and ($_ -cmatch 'smtp:')}
Should read
$CloudEmailAddress = $user.EmailAddresses | ?{($_ -match 'onmicrosoft') -and ($_ -match 'smtp:')}

The second script produces errors creating the proxy addresses. It doesn't appear to correctly parse the addresses.

An updated script is available at 

https://gist.github.com/ned1313/5e998a983b447246c73a

The updated script correctly creates all proxy addresses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e3b4d0-a18c-2cef-f81e-26535a0cdadc
* Version Independent ID: 381d80b9-9223-4928-0b95-1326402a0116
* Content: [Convert Exchange 2007 mailboxes to mail-enabled users](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-a-staged-migration/convert-exchange-2007-mailboxes?redirectSourcePath=%252farticle%252fa1f79f3c-4967-4a15-8b3a-f4933aac0c34#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-a-staged-migration/convert-exchange-2007-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-a-staged-migration/convert-exchange-2007-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by chrisda** [comment]
@chawkins99, OK. Fixed.

Thanks for the feedback.
