### ISSUE TITLE
Cannot prepend a disclaimer

### ISSUE THREAD

**Issue by AnnaMillerCSBS** [MicrosoftDocs/OfficeDocs-Exchange#1607]
I do not have the option to "put your disclaimer at the top of the email message instead of the bottom, in Do the following, select Apply a disclaimer to the message &gt; prepend a disclaimer." Append is my only option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dbf1c4-0702-250e-2097-c5663dfad762
* Version Independent ID: 505fbbcd-2a0d-b7e7-6f5b-c88c2c66fdbc
* Content: [Organization-wide message disclaimers, signatures, footers, or headers in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/disclaimers-signatures-footers-or-headers#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/disclaimers-signatures-footers-or-headers.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/disclaimers-signatures-footers-or-headers.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by decturau** [comment]
@AnnaMillerCSBS You need to go to the + then create a new rule. Then below the "choose a mode for this rule" there is a "More Options" button. Once you click it, you will then have the chose to append or prepend under "Apply a disclaimer ....."

**Comment by AnnaMillerCSBS** [comment]
I found it.  Thank you
