### ISSUE TITLE
Rollback procedure missing a step

### ISSUE THREAD

**Issue by dannyp14** [MicrosoftDocs/OfficeDocs-Exchange#1609]
At the end during the rollback procedure, you also need to set the public folders to Remote on E16:

From Exchange 2016 server:
"Set-OrganizationConfig -PublicFoldersEnabled Remote"

**Comment by scanum** [comment]
@dannyp14 Could you please link the documentation you are referring to? Thanks!

**Comment by dannyp14** [comment]
https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/batch-migration-from-previous-versions?view=exchserver-2016

**Comment by mattpennathe3rd** [comment]
@dannyp14 I'm not sure this applies in this case, but I will verify with some of the technical folks to be sure. Thanks for submitting this.
