### ISSUE TITLE
New CU and RollUp for Exchange Server

### ISSUE THREAD

**Issue by mariankral** [MicrosoftDocs/OfficeDocs-Exchange#1610]
Hi,
When will the next release be for Exchange Server 2013 CU24 and also Update Rollup 30 for Exchange Server 2010 SP3?
Thanks.

**Comment by mattpennathe3rd** [comment]
@mariankral I am sorry, but this repository is only for reporting documentation problems. I am unable to answer product or support questions here. For help with your question, please open a support ticket.
