### ISSUE TITLE
likely incorrect wording regarding the role of legacy pf databases after a migration

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1612]
"If you choose to keep mail flow centralized, it could cause delivery issues to your public folders, since you've removed the public folder mailbox databases from your on-premises organization."

Since when are databases related to mail flow? It’s my understanding that Exchange 2010 SP3 RU8 and Exchange 2013 CU 15 have logic within the transport service to use the (objects in the MESO container + the PublicFolderDestination_… accepted domain) to route email. Exchange 2013+ doesn’t even have such a thing as Public Folder databases, and the mail routes fine after a migration. Is this just imprecise wording in the article, or do we literally need to refrain from removing Exchange 2010 Public folder Databases for some reason? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders?source=docs#remove-public-folder-databases-from-the-legacy-exchange-servers)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by milkshakespoon** [comment]
For us keeping the mail flow centralized did break mail delivery. MS support confirmed mail flow is required to be decentralized after migrating the PFs...

We didn't delete our on prem database. After switching the mail flow everything is working.

Related to #1684

**Comment by Mike-Crowley** [comment]
@milkshakespoon mail delivery definitely works fine with centralized mail flow, but there are two main caveats: 

1. MEPFs created ADFER the migration will not be able to receive internet mail unless you create the MESO\MEPF object on-premises, for which there is no supported tool. This sounds like a deal breaker if you do this a lot, but if you only need to preserve functionality for existing MEPFs, its fine.

2. If any of your MEPFs have emailaddresspolicyenabled set to false, you'll need to manually add an onmicrosoft address that matches their alias.

**Comment by milkshakespoon** [comment]
> @milkshakespoon mail delivery definitely works fine with centralized mail flow, but there are two main caveats:
> 
> 1. MEPFs created ADFER the migration will not be able to receive internet mail unless you create the MESO\MEPF object on-premises, for which there is no supported tool. This sounds like a deal breaker if you do this a lot, but if you only need to preserve functionality for existing MEPFs, its fine.
> 2. If any of your MEPFs have emailaddresspolicyenabled set to false, you'll need to manually add an onmicrosoft address that matches their alias.

Interesting... We were using Exchange 2010 and we completely broke mail flow. MS support suggested this configuration was not correct and could not work. The solution was to move mail flow to EXO.

**Comment by Mike-Crowley** [comment]
Feel free to contact me directly if you would like to discuss this offline


-Mike Crowley

________________________________

**Comment by mattpennathe3rd** [comment]
@Mike-Crowley Thanks for filing this one. I'll have to look into this further, but I will report back and we'll see what we can do to clean this up.

**Comment by scanum** [comment]
@Mike-Crowley  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
