### ISSUE TITLE
can now have 1k pf mailboxes

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1613]
"We don't support the migration of public folders to Exchange Online when there are more than 100 unique public folder mailboxes in Exchange Online."

I believe this number was raised to 1000. ref: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#mailbox-storage-limits

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019#known-issues)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Mike-Crowley Thank you for raising this. I double-checked with the team and the article is correct as written; 1000 public folders are supported when they're created new, but only 100 are supported when they are being migrated from Exchange Server.

Even so, this distinction is a point of confusion and I've made some changes to the article to try to clarify. These changes should be published soon.

**Comment by Mike-Crowley** [comment]
aha, yes, that'd be great. I think adding that distinction would be a helpful addition.
