### ISSUE TITLE
-SourcePfPrimaryMailboxGuid not available

### ISSUE THREAD

**Issue by aaronseals** [MicrosoftDocs/OfficeDocs-Exchange#1614]
I'm to the point where we need to create a New-MigrationBatch but it fails because the "-SourcePfPrimaryMailboxGuid' is non-existent on our tenant.

How do i get around this?

_**New-MigrationBatch -Name PublicFolderMigration -CSVData $bytes -SourceEndpoint $PfEndpoint.Identity -SourcePfPrimaryMailboxGuid <HierarchyMailboxGUID> -AutoStart -NotificationEmails <email addresses for migration notifications>**_

**Comment by FrogThomas** [comment]
I am having the same issue. Have a look at an [old version](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/b95c75fcfcba78763febb9efb360b239ed3b0ce4/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md) of the document. Within Step 5 you will find a couple additional lines of code.

**Comment by mattpennathe3rd** [comment]
@aaronseals @FrogThomas Thanks for reporting this. We are working on a revision to this article that should help. I'll report back shortly once it is ready.

**Comment by Batre-MSFT** [comment]
> I'm to the point where we need to create a New-MigrationBatch but it fails because the "-SourcePfPrimaryMailboxGuid' is non-existent on our tenant.
> 
> How do i get around this?
> 
> _**New-MigrationBatch -Name PublicFolderMigration -CSVData $bytes -SourceEndpoint $PfEndpoint.Identity -SourcePfPrimaryMailboxGuid -AutoStart -NotificationEmails **_

The issue happens if the RBAC for your tenant is not updated yet. Either wait for the RBAC to be updated or open support ticket to update the RBAC immidiately

**Comment by mattpennathe3rd** [comment]
@aaronseals This document has been updated (the changes will be live in the near future) and should now enable you to complete the procedure on your tenant. If you continue to have trouble completing the procedure, please feel free to reopen this issue.
