### ISSUE TITLE
Sending email using C# code with SmtpException error

### ISSUE THREAD

**Issue by Sannioy** [MicrosoftDocs/OfficeDocs-Exchange#1615]
I currently use ***@microsoft.com mail, send mail in C #, and finally get the following error:
System.Net.Mail.SmtpException: "The SMTP server requires a secure connection or the client is not authenticated. The server response is: 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [HK2PR0401CA0011.apcprd04.prod.outlook .com] "

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-ca/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Sannioy I am sorry, but I am unable to provide product support here. This repository is only for reporting problems with the documentation. For help with your question, please open a support ticket.
