### ISSUE TITLE
CAN search across all public folders

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1616]
Is this still accurate: 

"public folder content isn't searchable across public folders and the content isn't indexed by Exchange Search"

should this say  "(outside of Office 365 eDiscovery)" ?

Per this article from 2015, public folder content is searchable, just maybe not in Outlook.
 https://www.microsoft.com/en-us/microsoft-365/blog/2015/07/02/announcing-compliance-toolset-for-public-folders/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fc906e-3899-1d89-836c-a441508b1107
* Version Independent ID: fce642c6-03fb-b344-ed2b-19fcdfc323ce
* Content: [Public folders in Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/public-folders?source=docs)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @Mike-Crowley, thank you for your feedback.

I am applying an update, let's see if gets approval. Please, if you don't mind check the pull request to see if you agree.

Thanks again!

**Comment by mattpennathe3rd** [comment]
@Mike-Crowley This has been clarified and the updated article will be published in the near future, but please let me know if you have further suggestions and I'd be glad to incorporate them. Thank you very much for filing this issue!
