### ISSUE TITLE
several dead links

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1618]
such as the timezone tool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ebc62f4-829e-06c6-bc9d-44609e2a4a50
* Version Independent ID: 44787479-5d86-5b3c-f67e-b86ce22d90a7
* Content: [Update Exchange organization when Daylight Saving Time or time zone changes](https://docs.microsoft.com/en-us/exchange/update-your-exchange-organization-when-daylight-saving-time-or-the-time-zone-changes-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/update-your-exchange-organization-when-daylight-saving-time-or-the-time-zone-changes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/update-your-exchange-organization-when-daylight-saving-time-or-the-time-zone-changes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Mike-Crowley Thanks for submitting this issue. I've updated the article and the new version should be published soon.
