### ISSUE TITLE
Links for to 2013 info

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Exchange#1621]
The links at the top for Collaboration and Sharing go to 2013 info.
So does the link in Exch2019 ECP &gt; Organization &gt; Sharing &gt; Learn More

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe945cb-89c4-1381-05b8-3977c073cb16
* Version Independent ID: 51f46f4c-49cd-692b-2c10-88766c28a8a9
* Content: [Sharing and collaboration permissions](https://docs.microsoft.com/en-us/Exchange/permissions/feature-permissions/sharing-and-collaboration-permissions?view=exchserver-2019&source=docs)
* Content Source: [Exchange/ExchangeServer/permissions/feature-permissions/sharing-and-collaboration-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/permissions/feature-permissions/sharing-and-collaboration-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @GLComputing, thank you for your feedback.

I updated collaboration link, not sharing link because there isn't new content for Exchange 2016/19.

**Comment by GLComputing** [comment]
The Collaboration link is still 2013 ... In fact, most of the "in-product" help links are 2013. Isn't it time MS produced full docs for 2019?

**Comment by dariomws306** [comment]
It's no live yet, it needs to follow a process, first need to be approved then will go live.

**Comment by mattpennathe3rd** [comment]
@GLComputing Thanks for filing this issue. The "Collaboration" link has been updated and will be published in the near future. The "Sharing" link is a longer-term problem because there is no updated article available for that content. I'll see if I can help resolve that, in time, but for now, there is no fix available.

Thank you again for filing this and please let me know if I can help further.
