### ISSUE TITLE
Command missing from step 5.4

### ISSUE THREAD

**Issue by mariosaelikeit** [MicrosoftDocs/OfficeDocs-Exchange#1622]
The below command is missing and therefore the $PfEndpoint variable is empty and the following commands fail.

$PfEndpoint = New-MigrationEndpoint -PublicFolder -Name PublicFolderEndpoint -RemoteServer &lt;remote server&gt; -Credentials $Source_Credential

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by FrogThomas** [comment]
This issue has already been reported...

Have a look at issue #1614.

**Comment by Biocas2007** [comment]
When running the command in 5.4 "New-MigrationBatch -Name PublicFolderMigration -CSVData $bytes -SourceEndpoint $PfEndpoint.Identity -SourcePfPrimaryMailboxGuid <HierarchyMailboxGUID> -AutoStart -NotificationEmails <email addresses for migration notifications>" I am receiving the error "A parameter cannot be found that matches parameter name 'SourcePfPrimaryMailboxGuid' I have piped through all the commands for New-MigrationBatch and that doesn't even come up as a command to be used. If I remove the command, I get an error that "Source public folder PrimaryMailboxGuid is required for public folder migration." Any idea what I am missing?

**Comment by christiandekker** [comment]
I've encountered this issue too. The reason for this error is that the SourcePfPrimaryMailboxGuid parameter is missing in the Management Role Entry for the Migration Role. You can check this with the command:
Get-ManagementRoleEntry "Migration\New-MigrationBatch" | Select -ExpandProperty Parameters

I had to go through support (Case ID: 18151458) to fix this issue.

**Comment by mattpennathe3rd** [comment]
@mariosaelikeit Thank you for reporting this. We are working on a revision to this article that might help with your issue. I'll report back when it is ready.

**Comment by mattpennathe3rd** [comment]
@FrogThomas @mariosaelikeit This article has been updated and will be published shortly. If the updated procedure does not help you resolve your problem, please feel free to reopen this issue.

**Comment by Rameshrao99** [comment]
Hi,
Do we have to run $Source_RemoteServer= "mail.domain.com" before running the below command as running command $Source_RemoteServer is not listed in the step 5 and dur to this the command failed to create endpoint.

$PfEndpoint = New-MigrationEndpoint -PublicFolder -Name PublicFolderEndpoint -RemoteServer $Source_RemoteServer -Credentials $Source_Credential

**Comment by mattpennathe3rd** [comment]
@Rameshrao99 The article has been extensively updated, so please review and see if your problem has been resolved with the article as it is now.

**Comment by Rameshrao99** [comment]
Thank you Sir.

**Comment by Rameshrao99** [comment]
> This issue has already been reported...
> Have a look at issue #1614.

This is a different issue.
