### ISSUE TITLE
Get Recoverable Items folder statistics for all mailboxes on Litigation Hold

### ISSUE THREAD

**Issue by pete-fordway** [MicrosoftDocs/OfficeDocs-Exchange#1623]
This section requires an addition filter for the script otherwise returns all folders not limited to Recoverable Items. I added -FolderScope RecoverableItems

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e54735fc-f085-e39f-6343-2ed9260b18ae
* Version Independent ID: e4cc7bb1-e7a9-8468-cbc1-2d0b45b4da13
* Content: [Get Recoverable Items folder statistics: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/get-recoverable-items-folder-statistics-exchange-2013-help#get-recoverable-items-quota-for-a-mailbox)
* Content Source: [Exchange/ExchangeServer2013/get-recoverable-items-folder-statistics-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/get-recoverable-items-folder-statistics-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@pete-fordway Thanks very much for this contribution! I have updated the doc and the updated version will be published in the near future.
