### ISSUE TITLE
Recommend alternative to public folders that meets this need

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#1624]
Q: Does mailbox audit logging work against public folders?
A: No. Not at this time.

Suggested answer: No. Not at this time. Consider using a Microsoft Team, O365 Group, or shared mailbox for auditing capabilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd73dfc1-fa96-8d62-6504-e97ab046a738
* Version Independent ID: 658e73b8-3dfe-aeef-678d-5bb227d91ffa
* Content: [FAQ: Public folders](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/faq?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/faq.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @jonwbstr, thank you for your feedback.

Reviewing the entire article, I see that at no time is there any mention of alternative solutions to public folders. I think this question should follow the same line.

**Comment by jonwbstr** [comment]
Good point. My suggestion was to provide an alternative and avoid just
saying no, similar to other answers in this article
For example, the question 'Can public folders be accessed using smart
phones or mobile phones' could also be answered with 'no, not at this time'
and isn't.

The alternative is migrate the public public folders to something o365
groups, which I also notice isn't listed as a migration scenario. Perhaps
that option could be added and mentioning why migrating to groups could be
beneficial (auditing). So at least the information is on the same page?


https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-office-365-groups?view=exchserver-2019

**Comment by dariomws306** [comment]
Agree. I had not seen those 2 lines, I think we can add something similar to this question.

**Comment by mattpennathe3rd** [comment]
@jonwbstr Thanks for filing this issue. I've updated the article and the changes should be published in the near future. Please let me know if you need anything further and I'd be glad to help out.
