### ISSUE TITLE
How to compare snapshots

### ISSUE THREAD

**Issue by FrogThomas** [MicrosoftDocs/OfficeDocs-Exchange#1626]
With step 2 and 9 I take snapshots of the public folders on-premises and Exchange Online. To verify the success of the migration I should compare the data of the resulting XML-files.

The files differ clearly from each other in file size and content. Having a look inside the migrated public folders I cannot find any differences between on-premises an Exchange Online content.

I tried to compare the files in powershell with `compare-object` Cmdlet. The output is not helpful, as it is just the input object. How am I supposed to compare to compare the snapshots?

**Comment by mattpennathe3rd** [comment]
@FrogThomas I'm sorry, but can you be more specific about which article you are having a problem with?

**Comment by scanum** [comment]
@FrogThomas We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
