### ISSUE TITLE
The below doesnt make sense to me, please rephrase

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-Exchange#1628]
Note:

Send As permission is also needed to comply with the following on-premises Exchange server and AAD Connect requirements:

Auto-mapping: Enables Outlook to automatically open any mailboxes that a user has been granted Full Access to on startup.

Folder permissions: Grants access to the contents of a particular folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/permissions#mailbox-permissions-and-capabilities-not-supported-in-hybrid-environments)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@michevnew Thanks for filing this issue. It looks like this can be clarified, so I will investigate and report back. Thank you again for pointing this out.

**Comment by get-itips** [comment]
Thanks for your feedback, will propose an improvement thru a pr. @michevnew
