### ISSUE TITLE
Restricting who can send to an email group

### ISSUE THREAD

**Issue by only1rache** [MicrosoftDocs/OfficeDocs-Exchange#1630]
I'd like to see functionality in Exchange where we can add certain users or groups to a deny list. 
Currently in exch 2010 I have to set message approval but then add lots of groups to the auto approved senders but I'd just like to be able to set the group to internal and then block a couple of people/groups from emailing the email group instead. 

**Use case:** an individual is due to leave the business and we want to prevent them from emailing out to the entire organisation

**Comment by mattpennathe3rd** [comment]
@only1rache I'm sorry, but this repository is only for reporting problems with the documentation and I am unable to answer product or support questions here. Please consider opening a support ticket for help with your scenario.
