### ISSUE TITLE
Error when running command in 5.4

### ISSUE THREAD

**Issue by Biocas2007** [MicrosoftDocs/OfficeDocs-Exchange#1631]
When running the command in 5.4 "New-MigrationBatch -Name PublicFolderMigration -CSVData $bytes -SourceEndpoint $PfEndpoint.Identity -SourcePfPrimaryMailboxGuid -AutoStart -NotificationEmails " I am receiving the error "A parameter cannot be found that matches parameter name 'SourcePfPrimaryMailboxGuid' I have piped through all the commands for New-MigrationBatch and that doesn't even come up as a command to be used. If I remove the command, I get an error that "Source public folder PrimaryMailboxGuid is required for public folder migration." Any idea what I am missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mariosaelikeit** [comment]
Check my comment below.

**Comment by Biocas2007** [comment]
I have used the information below and created the migration endpoint. The command still fails with the errors posted above. It is like the command doesn't exist for SourcePfPrimaryMailboxGuid. The error is not with the $PfEndpoint but not recognizing the SourcePfPrimaryMailboxGuid command as being valid.

**Comment by christiandekker** [comment]
I've encountered this issue too. The reason for this error is that the SourcePfPrimaryMailboxGuid parameter is missing in the Management Role Entry for the Migration Role. You can check this with the command:
Get-ManagementRoleEntry "Migration\New-MigrationBatch" | Select -ExpandProperty Parameters

I had to go through support (Case ID: 18151458) to fix this issue.

**Comment by mattpennathe3rd** [comment]
@Biocas2007 @christiandekker We are working on an updated version of this article that should solve this issue. I'll get back to you when it is ready.

**Comment by mattpennathe3rd** [comment]
@Biocas2007 This article has been updated and will be published shortly. If the updated procedure does not help you resolve your problem, please feel free to reopen this issue.
