### ISSUE TITLE
If you actually want to delete

### ISSUE THREAD

**Issue by andocromn** [MicrosoftDocs/OfficeDocs-Exchange#1632]
The command provided above actually moves the content.  If you came here because actually want to delete the dumpster content as I do, just exclude the TargetMailbox and TargetFolder

Search-Mailbox -Identity "Gurinder Singh" -SearchDumpsterOnly -DeleteContent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c21112a-deb5-83b3-160e-0149a1e510f6
* Version Independent ID: 4edc9fcd-4971-470b-c56e-e1a2e78b8854
* Content: [Clean up or delete items from the Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/clean-up-deleted-items)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @andocromn, thank you for your feedback.

There is a note in the article about this:
"To delete items from the mailbox without copying them to another mailbox, use the preceding command without the TargetMailbox and TargetFolder parameters."
