### ISSUE TITLE
Example is still missing quotes

### ISSUE THREAD

**Issue by ProfileX** [MicrosoftDocs/OfficeDocs-Exchange#1633]
The SAN example is missing opening quotes: 
-DomainName autodiscover.contoso.com

 The string values have closing quotes but not opening quotes: 
-DomainName "autodiscover.contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb6bf64-d3d6-dff6-2eb7-02074758e834
* Version Independent ID: 32b7069b-6a49-9d54-5119-b0d42aad619d
* Content: [Create an Exchange Server certificate request for a certification authority](https://docs.microsoft.com/en-us/exchange/architecture/client-access/create-ca-certificate-requests?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/create-ca-certificate-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/create-ca-certificate-requests.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@ProfileX Thanks for pointing this out. It looks like the prior fix overlooked this one. I've corrected the article and the revisions will be published soon. Thanks again for submitting the issue and please let me know if you find anything else in the docs that needs attention.
