### ISSUE TITLE
EAC changes

### ISSUE THREAD

**Issue by nickinenglish** [MicrosoftDocs/OfficeDocs-Exchange#1634]
Hi,

In the EAC the "send as" options have been removed. I've tried every command other webdites suggested, I can't grant the permission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe24386f-86cc-5073-dc17-ad8ece0e3dc7
* Version Independent ID: 88a529c7-c6e6-8438-8eb4-c6fc2a20f722
* Content: [Manage permissions for recipients in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-permissions-for-recipients#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @nickinenglish, thank you for your feedback.

I have just verified in my lab environment and Send As is there:
![image](https://user-images.githubusercontent.com/33589238/74774928-60fafe80-5273-11ea-8807-ec9619905ce3.png)

**Comment by nickinenglish** [comment]
Thank you for the response, I do apologize, the user account I was using 
was not the default administrator account so the "send as" option was 
not there.

Thank you
