### ISSUE TITLE
Example 1 Block messages with attachments

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-Exchange#1635]
Example 1 will cause almost all mail to be blocked because everything else than normal ASCI characters, like embedded images from a signature, will be seen as attachments and are larger than 1kb.
There is no good way to block all incoming email with an attachment and this Transport rule will trigger on emails without attachments as a result of how TNEF works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6db6edb-0ce9-5250-0e22-d42907394489
* Version Independent ID: 57d853a0-407f-01e5-4a6f-cdbaf7fa4fff
* Content: [Common attachment blocking scenarios for mail flow rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios?source=docs#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @JeroenDronkers, thank you for your feedback.

@mattpennathe3rd could you kindly help with to confirm this information?

**Comment by scanum** [comment]
@JeroenDronkers  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
