### ISSUE TITLE
Use EMS and you're supported...?

### ISSUE THREAD

**Issue by g-karas** [MicrosoftDocs/OfficeDocs-Exchange#1637]
I want to keep using DirSync / Azure AD Connect so I can manage identity of on-prem and Exchange users from a single place. The article clearly states that: "The Exchange Management Console, the Exchange admin center (EAC), and the Exchange Management Shell are the only supported tools that are available to manage Exchange recipients and objects."

Clearly, as long as I install and use Exchange Management Shell to manage things then I'm fully supported. So why the need to have a full installation of Exchange?

I have managed a number of Dirsynced clients over the years and never not even once felt the need to have Exchange on-prem.

Can anyone point me at a list of specific functionality that relies on having  Exchange server(s) on-prem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#feedback)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by g-karas** [comment]
...in response to myself :-) - of course you can't use EMS if there's no on-prem Exchange to connect to... doh!

**Comment by mattpennathe3rd** [comment]
@g-karas Sounds like you've answered your own question, but just to verify, is there any change or clarification you would like to see mad to this article?

**Comment by scanum** [comment]
@g-karas We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
