### ISSUE TITLE
Permisisons for Migration EndPoint Creation (Hybrid Mailbox Move)

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-Exchange#1638]
In Hybrid Mailbox Move, Recipient Management Role Group and Local Admin should be good enough to create Migration End Point and Move mailboxes. Can you please confirm it and make changes to the document accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95186047-1823-14de-7315-5609e2037d0d
* Version Independent ID: 226e94a4-37a7-a140-f40c-e065a68106ec
* Content: [Recipients Permissions](https://docs.microsoft.com/en-us/Exchange/permissions/feature-permissions/recipient-permissions?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/permissions/feature-permissions/recipient-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/permissions/feature-permissions/recipient-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @3novsan, thank you for your feedback.

You don't require Organization Management and Recipient Management, you require Organization Management or Recipient Management.
Organization Management includes all the permissions granted to Recipient Management.

**Comment by mattpennathe3rd** [comment]
@dariomws I assume this refers to the table at the end of the article, so is this true for all of the entries in the table? If it only requires one of these and not both, then I think we can clarify that.

**Comment by dariomws** [comment]
@mattpennathe3rd yes, table at the end. It's true, I think it's a good idea, I will do.

**Comment by dariomws** [comment]
@mattpennathe3rd I double checked this and it's explained at the top of the article:

----------------------------------------------------------------------
To find out what permissions you need to perform the procedure or run the cmdlet, do the following:

1. In the table below, find the feature that is most related to the procedure you want to perform or the cmdlet you want to run.

2. Next, look at the permissions required for the feature. **You must be assigned one of those role groups, an equivalent custom role group, or an equivalent management role**. You can also click on a role group to see its management roles. If a feature lists more than one role group, you need to be assigned to only one of the role groups to use the feature. For more information about role groups and management roles, see [Understanding Role Based Access Control](https://technet.microsoft.com/library/dd298183.aspx).

3. Now, run the **Get-ManagementRoleAssignment** cmdlet to look at the role groups or management roles assigned to you to see if you have the permissions that are necessary to manage the feature.

**Comment by mattpennathe3rd** [comment]
@dariomws Thank you for pointing this out. Looking at this again, the article seems clear as written. I'd like to clarify the request to make sure I understand the issue.

@3novsan Can you clarify your question? The article seems to already say what you described. If there is something that is wrong or unclear, please point it out.

**Comment by mattpennathe3rd** [comment]
@3novsan Following up on this once again. Can you provide any more clarity on your question?

**Comment by mattpennathe3rd** [comment]
@3novsan Closing this issue out for now, but please feel free to follow up in the future if you need further documentation help.
