### ISSUE TITLE
Platform Access Control Documentation

### ISSUE THREAD

**Issue by RSteeno** [MicrosoftDocs/OfficeDocs-Exchange#164]
We were recently under attack by a botnet that was trying to connect to our mailboxes via legacy protocols (basic authentication) and POP/SMTP.  There are a number of control points within Azure AD and Exchange Online that could help mitigate the attach, but they are applied to different points within the access pipeline.  For instance, AAD Conditional Access and EXO Client Access Rules are both evaluated AFTER an authentication request when a 3rd Party Federation Provider (i.e. Okta) is configured for a domain.

The only control we could identify to stop the attack from hitting the 3rd Party Fed Provider was to use the Set-OrganizationConfig -IPListBlocked and add the source IPs.

My ask is can we get a overall flow chart of the auth pipeline and the various controls that are in place within EXO and AAD?  throughout our call with MS Premier engineers, i have created a [diagram ](https://1drv.ms/u/s!AqFapWvVD9U_j55m3OqsZIhicBI57w) based on our testing, but i'd like to see MS maintain an official document as things in this space seem to be changing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9cdf39f-da71-43ab-0ceb-a816bdc19d04
* Version Independent ID: 1fff6b28-f8d8-d9b3-1730-db2cac7835a0
* Content: [Client Access Rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@RSteeno Thank you for this inquiry. 

I am not sure if we have the roadmap your requesting/suggesting. I'll get this over to the exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @RSteeno , I think you should check these articles:
