### ISSUE TITLE
Domain in O365 Admin Center not in Exchange Online Accepted Domains

### ISSUE THREAD

**Issue by Q916** [MicrosoftDocs/OfficeDocs-Exchange#1640]
I have added a domain to O365 Admin Center some time ago. The domain is used in several aliases of mailboxes and Distribution Lists.

The domain is now still in O365, but missing from Exchange Online Accepted Domains.

We can no longer edit the mailboxes and I have no way to re-add the domain to Accepted Domains. I might have the option to remove the domain from O365 and add it again, but then I have to remove the aliases from all mailboxes and DLs.

I use a hybrid environment and the domain is visible in Exchange On-Premise. It is not visible when I run the Hybrid Setup Wizard.

Is there some way to re-add the domain to the Accepted Domains in Exchange Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bf5c21-fd13-6458-96f1-22916748c1bf
* Version Independent ID: c9d62060-d249-9c5c-ca37-10f74175b77e
* Content: [Procedures for accepted domains in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/accepted-domains/accepted-domain-procedures?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/accepted-domains/accepted-domain-procedures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/accepted-domains/accepted-domain-procedures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Q916 I'm sorry, but I am unable to provide product support here. This repository is only for reporting problems with the documentation. For help with your question, please open a support ticket.
