### ISSUE TITLE
Rule "Notify the recipient with a message" does not exist in Exchange 2013 

### ISSUE THREAD

**Issue by IT373** [MicrosoftDocs/OfficeDocs-Exchange#1643]
Rule "Notify the recipient with a message" does not exist in Exchange 2013 and appears to have been added in 2016.  None of the Exchange 2013 servers I service have this is an option and it is included as a new action in the "What's new in Exchange 2016" article here https://docs.microsoft.com/en-us/exchange/new-features/new-features?view=exchserver-2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa636046-f4ff-7f41-a403-535ebab8cc97
* Version Independent ID: 9d1c15a6-237a-c90b-34c4-5e9635096e1d
* Content: [Transport rule actions in Exchange 2013: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/mail-flow-rule-actions-in-exchange-2013-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/mail-flow-rule-actions-in-exchange-2013-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/mail-flow-rule-actions-in-exchange-2013-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@IT373 Thanks for filing the issue. I've removed this rule from the page and the fix should be published in the near future.
