### ISSUE TITLE
Request confirmation or modification on the statement: “This list doesn't apply to already added guest members, this will be enforced for all the guests added after the list is set-up. However, you can remove them through the script.”

### ISSUE THREAD

**Issue by Michael-Bai** [MicrosoftDocs/OfficeDocs-Exchange#1647]
This article says: “This list doesn't apply to already added guest members, this will be enforced for all the guests added after the list is set-up. However, you can remove them through the script.”

However, as we test, we are unable to remove guest members through the script. Please double confirm if the statement above is correct, if it’s not, please modify this statement.

We understand that we can remove domains from the policy but unable to remove guest members through the script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08bf021-f95a-ab2f-85e3-4f4c44374501
* Version Independent ID: 2d7ea71a-f42c-693a-eb4e-c1d9336b44eb
* Content: [Allow/Block guest access to Office 365 groups](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-group-access-to-office-365-groups#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-office-365-groups.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Michael-Bai Just so you know, this has been corrected and the updated article will be published in the near future. Thank you very much for submitting this. 谢谢您。
