### ISSUE TITLE
How can admin see the DSC value?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/OfficeDocs-Exchange#1648]
Does not tell that in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40bce01-0b1f-1952-5198-d5a15211b533
* Version Independent ID: 3f0ac568-cfbd-5255-d803-b7883c32c50f
* Content: [Track and Prevent Migration Data Loss](https://docs.microsoft.com/en-us/exchange/mailbox-migration/track-prevent-data-loss-dcs)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@ArttuArstila The article answers this question. As it says, "Microsoft is constantly tuning these thresholds to ensure that problematic data loss does not occur during migrations. The details of these thresholds are not presented to Exchange Online administrators."

**Comment by ArttuArstila** [comment]
Thanks for the reply! I think I was not clear enough. I am not asking about the detailed values, but where the overall grade will be shown to admins?

**Comment by ChrisStoneham** [comment]
I'm just doing a migration now - if you View setails on a Migration batch the Data consistency score is shown against the mailboxes in this screen.

**Comment by ajacks88** [comment]
Is there a way to pull the details of a poor DCS through PowerShell?

**Comment by mattpennathe3rd** [comment]
@ArttuArstila @ChrisStoneham @ajacks88 The article has been updated and I hope the new context helps you. You can indeed view the DCS from PowerShell as well as in EAC.

I will close this issue now, but please feel free to open a new issue if you have further suggestions on this content.
