### ISSUE TITLE
Notify the recipient with a message not an option in Exchange 2013

### ISSUE THREAD

**Issue by IT373** [MicrosoftDocs/OfficeDocs-Exchange#1649]
This document incorrectly states that the rule action to "Notify the recipient with a message" is available in Exchange 2013.  This rule action was added in Exchange 2016. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 237d64ca-06c7-fd0e-96cb-d567e9b8cd00
* Version Independent ID: e91a828c-022f-993c-f49e-5a5c8d2e8cfd
* Content: [Mail flow rule actions in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mail-flow-rules/actions?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/actions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/actions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@IT373 Thank you for pointing this out. I've corrected the article and the updated version should be published in the near future.
