### ISSUE TITLE
Exchange federation page has invalid link about 21V

### ISSUE THREAD

**Issue by CarolZixinWang** [MicrosoftDocs/OfficeDocs-Exchange#1652]
Hi team, 

The link in the following text is invalid. Please kindly check and update if possible. This may affect several pages in the federation related pages.
_This feature of Exchange Server 2013 isn't fully compatible with Office 365 operated by 21Vianet in China and some feature limitations may apply. For more information, see **Learn about Office 365 operated by 21Vianet**._

https://docs.microsoft.com/en-us/exchange/federation-exchange-2013-help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2761dd7-6fd8-e8b8-1cb0-16d2e9e42dac
* Version Independent ID: 76699da3-11f6-0955-3652-eb263e8fb36e
* Content: [Federation: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/federation-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/federation-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/federation-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@CarolZixinWang Thank you for pointing this out. I've corrected the link in the article and the updated version will be published in the near future. Please let me know if I can do anything further.
