### ISSUE TITLE
IRM Protection for external messages ¿?

### ISSUE THREAD

**Issue by ecanales88** [MicrosoftDocs/OfficeDocs-Exchange#1654]
Hello MS Team
In this article, section "Scenarios for IRM Protection" shows that "Sending messages to external recipients" is not supported for IRM. This is correct?
In this article https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-irmconfiguration?view=exchange-ps the cmdlet -ExternalLicensingEnabled $true, says: "IRM features are enabled for external messages" and  apply Exchange Server 2016, 2019
So it's confusing, I need to know if Can I use ADRMS and Exchange 2019 Onpremise to protect messages to external or internal recipients. 
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1713567-ffd9-a976-fd93-532f1cce8bde
* Version Independent ID: 3f1c019f-7ab0-f9ca-4121-ec1506569899
* Content: [Information Rights Management in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/information-rights-management?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/information-rights-management.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/information-rights-management.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@ecanales88 Thanks for filing the issue. You're correct; this does seem to conflict. I'm already working on getting an answer so I can update this article and I will post back soon, after I have news.

**Comment by mattpennathe3rd** [comment]
@ecanales88 Sorry this took so long, but the PowerShell documentation was incorrect. The PowerShell cmdlet is related to denial of service attack protection and does not seem to be related to your scenario.

I have submitted a fix for the PowerShell documentation and it will be merged in the near future.
