### ISSUE TITLE
Finalizing your migration

### ISSUE THREAD

**Issue by travisadvisicon** [MicrosoftDocs/OfficeDocs-Exchange#1656]
It notes you can switch your primary MX record to point to Office 365 once all users are successfully migrated. Does this same setting matter if you're switching from one domain name to another? Like switching from contoso.com to fabrikaminc.net, since they carry with them separate DNS records?

If not, then can someone confirm that I can just remove the o365 and "before" domains without having to change any DNS records?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by Rameshrao99** [comment]
If you don't want to use contoso.com after the migration then the MX record change is not needed. As you are going to use fabrikaminc.net in the target O365 tenant just update the MX pointing to target tenant. However all the emails which are coming in for contoso.com will land in to source O365 tenant. You can remove the domain contoso.com from source if you don't want to use it, however first confirm all the data is migrated to target tenant.

**Comment by travisadvisicon** [comment]
@Rameshrao99
Thank you for the confirmation. All the data has been migrated that needs to be so I will carry on with finalization.

**Comment by mattpennathe3rd** [comment]
@travisadvisicon Thanks for the question. I'm only able to help with documentation updates in this repo, but if after you have finished your migration, you feel that there's something that could have been clearer in this article, please let me know and I would be glad to improve the article.

**Comment by travisadvisicon** [comment]
@mattpennathe3rd
The only thing that confused me was because my migration was not the same as the migration example in this document. This document is assuming you're migrating from one place to another using the same domain name, whereas mine was two different names.

To combat this confusion, I would like to see a note after the "Finalizing your migration"  section mentioning that it would not apply if you are moving to a separate domain with separate DNS records.

**Comment by scanum** [comment]
@travisadvisicon thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
