### ISSUE TITLE
Tip for Rollback

### ISSUE THREAD

**Issue by olmitt** [MicrosoftDocs/OfficeDocs-Exchange#1658]
For rollback you should better use parameter "-Permanent $true" for "remove-mailbox", otherwise you leave the mailbox in the database without disconnectreason. I wasn't able to delete them afterwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6010593-c3e4-87a6-4084-27d56f23063c
* Version Independent ID: 32a2adeb-0932-3236-09d9-b7987393639b
* Content: [Use batch migration to migrate Exchange 2010 public folders to Exchange 2016](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/batch-migration-from-previous-versions?redirectedfrom=MSDN&view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @olmitt, thank you for your feedback.

I am thinking that it doesn't add real value as it shouldn't affect the rollback process.

**Comment by mattpennathe3rd** [comment]
@dariomws Not too consequential, but it's a straightforward addition and it can prevent much user anguish after the rollback, so I think it's good to add. I've updated the article and the revisions will be published in the near future.

Thank you for filing this issue, @olmitt! Please let us know if you have any further feedback.
