### ISSUE TITLE
Configuring a group domain

### ISSUE THREAD

**Issue by yacooob** [MicrosoftDocs/OfficeDocs-Exchange#1659]
Hello,
There is a full and detailed paragraph about creating and configuring dedicated groups domain. 
It says "If you want to add a dedicated groups domain, you can…", but doesn't explain why one would like to do that or if it is recommended by Microsoft for whatever reason. Could you please add any additional comments to that? 
Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @yacooob, thank you for your feedback.

If you click on the "Multi-domain support for Office 365 Groups" link you can find this information.
