### ISSUE TITLE
Wildcard certificate support

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/OfficeDocs-Exchange#1660]
Please clarify if Wildcard certificates are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fee8aac-fb8d-452b-7c1d-56db8cd1c3ff
* Version Independent ID: 61edeeae-af33-1074-ac0e-9311f9ddeca7
* Content: [Certificate requirements for hybrid deployments](https://docs.microsoft.com/en-us/exchange/certificate-requirements)
* Content Source: [Exchange/ExchangeHybrid/certificate-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/certificate-requirements.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by diecknet** [comment]
@mattpennathe3rd looks like this issue is still unassigned

**Comment by mattpennathe3rd** [comment]
@diecknet Thanks for filing the issue. I will have to investigate and post back. If you have a pressing need for getting such a certificate working in your environment, please be sure to open a support ticket.

**Comment by mattpennathe3rd** [comment]
@diecknet There are no certificate requirements for a hybrid deployment other than what Exchange requires (and wildcard certificates are supported on Exchange Server). Hybrid does not require new or additional certificates and only checks that certificates are valid - that is, not expired and not self-signed. That being the case, there isn't really anything I can add to this article, as in the context of a hybrid deployment, this isn't a consideration.

Please feel free to open a new issue if there are any other docs questions I can help with.
