### ISSUE TITLE
.NET 4.8 detectiong not working correctly

### ISSUE THREAD

**Issue by JulioQc** [MicrosoftDocs/OfficeDocs-Exchange#1661]
Even with .NET 4.8 installed (Windows 10 1903), confirmed by value 528040 for value "Release" at "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" the installed still complains it requires .NET 4.8 to be installed. 

Confirmed by many users: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1619 
Please fix. And try to release a CU that will work smoothly for one... Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@JulioQc I heard back from Support that this is a known issue. It's slated to be fixed in the next CU, but beyond that, I don't have any more solid information. (I'm only the documentation guy.)
