### ISSUE TITLE
Additional requirements for untrusted cross-forest topology

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/OfficeDocs-Exchange#1663]
Can you cross reference this technote that if you don't publish the SCP from one forest to the other that an AutoDiscover Anchor reference needs to be added to at least one mailbox in the target forest please?

https://support.microsoft.com/en-us/help/3010570/cross-forest-free-busy-lookup-fails-when-target-forest-is-exchange-ser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859ffd66-5517-0fc9-8e9b-5ecdb8fb1968
* Version Independent ID: 503b8795-1b4d-d07d-038f-ba6aad08794e
* Content: [Configure the Availability service for cross-forest topologies](https://docs.microsoft.com/en-us/Exchange/architecture/client-access/availibity-service-for-cross-forest-topologies?view=exchserver-2019&source=docs)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/availibity-service-for-cross-forest-topologies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/availibity-service-for-cross-forest-topologies.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by qnquocanh** [comment]
We have nearly the same issue for Free/Busy configuration for untrusted forests with same error message like on your link. Did you configured it on your environment and does it solve the problem ?

Thanks.

**Comment by mattpennathe3rd** [comment]
@quickclix75 Thanks for filing this issue. I'm working on updating this article and the edits should be published in the near future.

**Comment by quickclix75** [comment]
@qnquocanh I did indeed configure a maibox object with the guids and it resolved my issue.
