### ISSUE TITLE
User account required for untrusted cross-forest topology

### ISSUE THREAD

**Issue by quickclix75** [MicrosoftDocs/OfficeDocs-Exchange#1664]
Please can you affirm that the user account for the Untrusted Cross forest free busy must NOT be a mail enabled object.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 859ffd66-5517-0fc9-8e9b-5ecdb8fb1968
* Version Independent ID: 503b8795-1b4d-d07d-038f-ba6aad08794e
* Content: [Configure the Availability service for cross-forest topologies](https://docs.microsoft.com/en-us/Exchange/architecture/client-access/availibity-service-for-cross-forest-topologies?view=exchserver-2019&source=docs)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/availibity-service-for-cross-forest-topologies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/availibity-service-for-cross-forest-topologies.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@quickclix75 I need a bit more information on this. Can you provide more context as to what you would like changed in this article?

**Comment by quickclix75** [comment]
Hey @mattpennathe3rd its in relation to the OrgWideFB user account on the untrusted availability address space.. The one we had setup was a mail enabled contact which stopped the availability lookup working.

**Comment by get-itips** [comment]
Hello @quickclix75 how are you?
I am taking over this issue, I know that some time has passed since you opened it, to understand better what you experienced and see if we have to improve the documentation, you provided a "mail enabled contact" to _Set-AvailabilityConfig -OrgWideAccount_ cmdlet and not a regular user account?
Thanks for clarifying

**Comment by get-itips** [comment]
Hello @quickclix75 returning to see if you could see my question here, thanks

**Comment by scanum** [comment]
@quickclix75 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
