### ISSUE TITLE
ms-Exch-SMTP-Accept-Authoritative-Domain-Sender - Not working anymore 

### ISSUE THREAD

**Issue by damtrx** [MicrosoftDocs/OfficeDocs-Exchange#1665]
Bug in ms-Exch-SMTP-Accept-Authoritative-Domain-Sender permission.
If you have frontend Receive Connector and remove this permission, the sender can still use authoritative domains to send emails to internal users without authentication. This is the case for Anonymous receive connector facing the internet and users that are trying to abuse the system (spammers).
The anonymous connector is not Open Relay!

According to this documentation removing this permission should forbid establishing session. This is not the case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6df02f0e-7bd3-f636-db39-12ac12f1538e
* Version Independent ID: 00403f36-ec82-b293-65b9-1674a47a4078
* Content: [Receive connector permissions: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/receive-connector-permissions-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/receive-connector-permissions-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/receive-connector-permissions-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@damtrx This sounds like a product bug or a configuration issue rather than a documentation problem. I am only able to help with documentation issues here in this repo (I'm not a support person), so please open a support ticket.

If there is in fact a docs problem, please let me know and I'd be glad to help.
