### ISSUE TITLE
Add Video

### ISSUE THREAD

**Issue by pupara** [MicrosoftDocs/OfficeDocs-Exchange#1666]
Please add video on how to do this on the EAC. Watching video is often more helpful then following all the steps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c92752-7e76-3f33-2e93-42eb13e63a1a
* Version Independent ID: 0b4de7ea-4982-30a3-4c69-b42dcfa73416
* Content: [Manage on-premises mailbox moves in Exchange Server](https://docs.microsoft.com/en-us/Exchange/architecture/mailbox-servers/manage-mailbox-moves?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/manage-mailbox-moves.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/manage-mailbox-moves.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@pupara Thank you for the feedback. We don't usually use video guides in this documentation set, but it's definitely something we can look at. I'm the writer who maintains this docs set, so I appreciate your suggestion and will start exploring whether it's viable.
