### ISSUE TITLE
Add info about Admin Audit Log storage

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#1667]
SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca0013eb-5599-a907-9869-569f40f1e725
* Version Independent ID: 9fd23081-2830-c87b-561b-582fb16fc09e
* Content: [Recreate missing arbitration mailboxes](https://docs.microsoft.com/en-us/Exchange/architecture/mailbox-servers/recreate-arbitration-mailboxes?view=exchserver-2019&source=docs)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@trudolf-msft Can you elaborate on what this refers to? Let me know if there is a change that needs to be made or if this issue was opened by accident.

**Comment by trudolf-msft** [comment]
Hello Matt,

Please find this article and I would like to have some more information about this specific mailbox in the article if possible.
In Exchange 2010, the Microsoft Exchange system mailbox is an arbitration mailbox used to store organization-wide data such as administrator audit logs, metadata for eDiscovery searches, and Unified Messaging data, such as menus, dial plans, and custom greetings. The Microsoft Exchange system mailbox is named SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9} ; the display name is Microsoft Exchange.  See Move the Exchange 2010 system mailbox to Exchange 2013<https://technet.microsoft.com/en-us/library/dn249849(v=exchg.150).aspx>.
See https://docs.microsoft.com/en-us/archive/blogs/rmilne/arbitration-mailboxes-lay-of-the-land

Kind regards,
Thomas

**Comment by get-itips** [comment]
Thanks for your feedback @trudolf-msft
