### ISSUE TITLE
compliance boundaries for eDiscovery 

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/OfficeDocs-Exchange#1669]
Whats the difference between this and the article below.
https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 755b30f7-e10a-4bab-db4e-28810dfc9cdc
* Version Independent ID: d8857a11-031d-9930-277f-7060837b47f9
* Content: [Create a custom management scope for In-Place eDiscovery searches](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/create-custom-management-scope#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/create-custom-management-scope.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/create-custom-management-scope.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@stephenc01 These are different articles covering different scenarios for different products. If there are errors in the Exchange Online article, please let me know and I'd be glad to address them.
