### ISSUE TITLE
"If your organization uses a hybrid Exchange environment, you should use the on-premises Exchange admin center (EAC) to create and manage shared mailboxes."

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/OfficeDocs-Exchange#1671]
Can you add context to this statement, listing reason why the on-premises EAC should be used (as opposed to O365)?  This seems counter-intuitive for organization that are migrated to EXO but still maintain hybrid.  Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 683bd24a-56fc-4998-bf71-628884be0c89
* Version Independent ID: fc9270d5-2ad0-889c-d6f0-b28c114e7bf4
* Content: [Create shared mailboxes in the Exchange admin center](https://docs.microsoft.com/en-us/Exchange/collaboration/shared-mailboxes/create-shared-mailboxes?view=exchserver-2019&viewFallbackFrom=exchserver-2019.#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/shared-mailboxes/create-shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/shared-mailboxes/create-shared-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@dagroll Thanks for filing the issue. I'll investigate and see if there are ways to clarify this.

**Comment by get-itips** [comment]
Thanks for your feedback @dagroll
