### ISSUE TITLE
SMTP Relay

### ISSUE THREAD

**Issue by erihnbapsjfdb** [MicrosoftDocs/OfficeDocs-Exchange#1674]
Please clarify the licensing requirements for SMTP Relay. 
These two sections seem to contradict each other.

"Features of Office 365 SMTP relay
Office 365 SMTP relay does not require the use of a licensed Office 365 mailbox to send emails."

"Requirements for Office 365 SMTP relay
Licensing: SMTP relay doesn't use a specific Office 365 mailbox to send email. This is why it's important that only licensed users send email from devices or applications configured for SMTP relay. If you have senders using devices or LOB applications who don't have an Office 365 mailbox license, obtain and assign an Exchange Online Protection license to each unlicensed sender. This is the least expensive license that allows you to send email via Office 365."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@erihnbapsjfdb Thank you for pointing this out. I will look into this soon and will follow up.

**Comment by AdamWyzgol** [comment]
For me it's clear, you don't need additional license for "service account" that is used for authentication, but any named user need to have assigned license to send mail using this service.

**Comment by mattpennathe3rd** [comment]
@erihnbapsjfdb @AdamWyzgol Thanks for your help in pointing this out. I found some ways to clarify this part of the article and the updated version should be published in the near future.
