### ISSUE TITLE
Exchange Mail flow rules (transport rules) impact on EOP + ATP 

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/OfficeDocs-Exchange#1675]
Please add to this page a note regarding the impact Exchange Mail flow rules (transport rules) can have on EOP + ATP. Specifically call out the scenario where an Exchange Mail Flow rule could whitelist an email address and the impact is that EOP + ATP would allow that email through (i.e., bypass the protections). Any other comments around Exchange Mail flow rules and their relationship to the protections EOP+ATP would be appreciated. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81c1119-165b-f408-698c-1092a781ba63
* Version Independent ID: 1a1b6d9a-a75c-e74d-ff84-ccbdf15091de
* Content: [Mail flow rules (transport rules) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@tfurstms Thanks for filing this issue. I'll look into this soon and will follow up.

**Comment by msbemba** [comment]
@tfurstms  Thank you for your feedback, We have modified the document with more clarity on Bypassing ATP. This can be tracked via PR # https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1732


Thanks
Sri

**Comment by mattpennathe3rd** [comment]
@tfurstms I believe we have a fix in place and the revised article will be published soon. Thanks again for filing this and please let me know if you have further comments on the content.
