### ISSUE TITLE
Hybrid Considerations

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1676]
Please add details on how to deal with room lists in Hybrid scenarios since they are not synced to EXO from EXS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1598a231-d154-1c94-d8aa-76084b45ed35
* Version Independent ID: 3cc7eb58-d64e-73f2-8566-f97ec30ac15e
* Content: [Create and manage room mailboxes](https://docs.microsoft.com/en-us/Exchange/recipients/room-mailboxes?redirectedfrom=MSDN&view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/recipients/room-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/room-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by JeremyTBradshaw** [comment]
Room lists are in fact synced between on-premises and EXO.  I just verified this, and where I'm looking we have 100+ room lists synced.   RecipientTypeDetails on them is 'RoomList ' in both places.  We needed these in order to be able to find Rooms properly in EXO's OWA (and it was painful before that, so it's a familiar topic for me, but I digress).

**Comment by JeremyTBradshaw** [comment]
I should also include, resource mailboxes that are members of the Room Lists, whether they are migrated or not (on-premises or EXO) - they are members of the room lists and are fully functional, excluding standard mailbox limitations for cross-premises that apply to all mailboxes.  As far as what room lists do though - everything syncs and works as expected.

**Comment by danmyhre** [comment]
Thanks for validating @JeremyTBradshaw .  It must have been some old documentation that showed that they were not synced.  Glad to hear it works now!
