### ISSUE TITLE
EWS Clients

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#1679]
There are no details on how to deal with EWS clients in hybrid scenarios.  For example, many 3rd party products integrate with Exchange using EWS.  If they only support a single EWS URL, how can that work in hybrid?  What should EWS clients be doing - always using autodiscover to determine the proper EWS endpoint?  These sorts of system integration should be listed in the considerations section as many could turn out to be show-stoppers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server Hybrid Deployments](https://docs.microsoft.com/en-us/exchange/exchange-hybrid)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@danmyhre Thanks for filing this issue. This one will take a bit of digging, but I will follow up.

**Comment by TyNavarre** [comment]
We have a similar situation where we need to deal with EWS as it relates to third party products

**Comment by dariomws** [comment]
Hi @danmyhre and @TyNavarre, thank you for your feedback and help us to improve docs.microsoft.com.

I'm not positive to add detail about how different 3rd party products interact with Exchange Hybrid to this article. As you commented, the 3rd party app should use autodiscover to find the Exchange endpoint/s it needs. Exchange (hybrid) works in this way.

Also, 3rd party app should have documented if it supports Exchange hybrid or not.

**Comment by scanum** [comment]
@TyNavarre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
