### ISSUE TITLE
Security Defaults block or disable Legacy auth?

### ISSUE THREAD

**Issue by Jhines09** [MicrosoftDocs/OfficeDocs-Exchange#1680]
In the top of the article it states:
If you've enabled security defaults in your organization, Basic authentication is already disabled in Exchange Online. 

I was under the impression that security defaults blocks legacy authentication with Conditional Access. Or does security defaults actually disable legacy auth at the Exchange level?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by arh0770** [comment]
What I've recently learned is that blocking legacy authentication with conditional access doesn't actually block the authentication requests.  It only blocks it once a correct password is received.  So, if you have an attacker trying to brute force your account with legacy auth (i.e. IMAP) the attack keeps coming and then account lockout policies will still apply.  I currently have a ticket open with Microsoft to try to block IMAP and prevent the account lockouts.

**Comment by mattpennathe3rd** [comment]
@Jhines09 Thanks for filing this issue. I'll have to investigate further, but will follow up.

**Comment by msbemba** [comment]
@Jhines09 Thank you for your feedback. You are correct, Enabling Security defaults will disable Legacy authentication in Exchange Online.

Thanks
Sri

**Comment by sixfivemil** [comment]
I'd be interested in discovering how this will be handled as I don't want to use security defaults either.

**Comment by msbemba** [comment]
@sixfivemil Thank you for your feedback. There is another document that talks about Moving away from legacy authentication without security defaults. 

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-block-legacy-authentication

Hope this helps!
Thanks
Sri

**Comment by VLG17** [comment]
@Jhines09 another thing to keep in mind is [the last update](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508) about disabling Basic Authentication in Exchange Online for tenant that actually use it:

> **we have decided to postpone disabling Basic Authentication in Exchange Online for those tenants still actively using it until the second half of 2021**. We will provide a more precise date when we have a better understanding of the impact of the situation.

> **We will continue to disable Basic Authentication for newly created tenants by default** and begin to disable Basic Authentication in tenants that have no recorded usage starting October 2020.

**Comment by scanum** [comment]
@sixfivemil  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
