### ISSUE TITLE
Theoretical question around MRS endpoints

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-Exchange#1681]
Via EWS by way of the MRS... is it possible to create a connection to migrate mailbox data from one exchange server to many separate O365 tenants? If so would it be possible to have that highlights here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dee0d453-e476-7b64-f0bb-d0135887916f
* Version Independent ID: 506a0b80-19db-21c8-aee3-071b7827a342
* Content: [Enable the MRS Proxy endpoint for remote moves](https://docs.microsoft.com/en-us/Exchange/architecture/mailbox-servers/mrs-proxy-endpoint?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/mrs-proxy-endpoint.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/mrs-proxy-endpoint.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@jebalert Thanks for filing this issue. I'm not sure I can address this one in this article, but I'll look into it and will report back.

**Comment by VLG17** [comment]
@jebalert You can leverage the architecture described [here](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-connect-topologies#each-object-only-once-in-an-azure-ad-tenant). But you must keep the following in mind:

> This topology has the following restrictions on otherwise supported scenarios:
> 
> Only one of the Azure AD tenants can enable an Exchange hybrid with the on-premises Active Directory instance.

So that means you can create a hybrid with one of the configured ADConnect instances, migrate the mailboxes to Tenant 1, remove the hybrid, configure another hybrid with another ADConnect instance, move mailboxes to Tenant 2 and so on. But i think there are some caveats with removing the hybrid (maybe even not supported scenario) so you would need to double-check that.

**Comment by jebalert** [comment]
So when talking about migrating mailboxes it’s important to think of hybrid as two swim lanes. You’re looking at this mostly from a identity standpoint, and the facts you highlighted are accurate. Hence my initial question.. at the time I originally wrote this I was exploring architectural design choices around the feasibility of circumventing the use of the hybrid exchange wizard to accomplish the task of migrating a mailbox to another tenant that wasn’t in “full hybrid”. After exploring MRS, org relationships and the hybrid configuration engine a bit more thoroughly the answer appears to be yes, it’s possible, when done manually. Albeit it is not technically “supported” by Microsoft. 

This can be closed.

**Comment by mattpennathe3rd** [comment]
@jebalert Thanks for following up in detail. If you find further docs shortcomings in the future, please feel free to open a new issue.
