### ISSUE TITLE
Insufficent Information on Alternate Journaling Mailbox Procedures

### ISSUE THREAD

**Issue by jreinhardtiv4** [MicrosoftDocs/OfficeDocs-Exchange#1683]
Under the alternate journaling mailbox, there is insufficient details on what to do to retry sending failed journal reports. First, the reference to "Send Again" is a little vague. Probably a simple screenshot and steps would help. Second, there is no details on how to overcome error '550 5.7.101 RESOLVER.RST.JournalReportFromUnauthorizedSender; not authorized to send journal reports' Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d4ec80-7a55-398a-22e9-3f5df24a867b
* Version Independent ID: 4543c414-41d1-b8fe-8a58-4dc61ccf61ff
* Content: [Journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/journaling#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@jreinhardtiv4 Thank you for filing this issue. I will investigate and will report back on what I an do to clarify this.

**Comment by get-itips** [comment]
Hello @jreinhardtiv4 how are you?
An image of the "Send Again" feature was added by me recently, on the [Configure Journaling](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/configure-journaling) article.
About the error message that you received, I could not reproduce to be able to add information to the article, can you kindly describe the scenario where you stumble upon that error to understand better if we can improve the article? Thank you

**Comment by jreinhardtiv4** [comment]
Hi, when I tried to use the Send Again feature to resend messages I received that error. I don't recall how I resolved the issue. I was having journaling messages sent to an on-premises journaling mailbox in a hybrid environment, but the NDRs were sent to a cloud mailbox in O365. So, i was trying to send again a message from the cloud mailbox to the on-premises mailbox. I'm not sure what else I can tell you as the issue was a long time ago now. Thank you for your efforts.

**Comment by get-itips** [comment]
> Hi, when I tried to use the Send Again feature to resend messages I received that error. I don't recall how I resolved the issue. I was having journaling messages sent to an on-premises journaling mailbox in a hybrid environment, but the NDRs were sent to a cloud mailbox in O365. So, i was trying to send again a message from the cloud mailbox to the on-premises mailbox. I'm not sure what else I can tell you as the issue was a long time ago now. Thank you for your efforts.

Thanks for returning and sharing that information, if you happen to get that error again in the future I encourage you to return again and share more information so we are able to update the article. Thank you again!

**Comment by scanum** [comment]
@jreinhardtiv4 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
