### ISSUE TITLE
Mail flow breaks if not in decentralized configuration and routing mail through Exchange Online

### ISSUE THREAD

**Issue by milkshakespoon** [MicrosoftDocs/OfficeDocs-Exchange#1684]
Recently performed these tasks while still flowing mail through our on prem server. After the public folder migration is complete the on premise server is no longer aware of them. All mail fails to send to them.

We had MS support help us with this case. To fix the mail flow we were required to switch the mail flow straight into Exchange Online (decentralized) which fixed the issues.

This document does not make it clear this is a required step. It should be highlighted at the very top of this document before going ahead with the migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@milkshakespoon I'll have to look into this further, as it's not clear this is a general rule or something specific to your environment. I'll report back and see if there's anything I can do to improve the article.

**Comment by VLG17** [comment]
@milkshakespoon I see you asked the following question in the [related issue](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1612) you pointed out.

"The PFs no longer exist on prem... so how would it know where to route mail?"

I think the below step, from the [initial article](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#prerequisite-steps-on-the-legacy-exchange-server) has the answer. I assume you did this, right? And still the problem appeared.

> **On the legacy Exchange server, make sure that routing to the mail-enabled public folders that will exist in Office 365 or Exchange Online continues to work until all DNS caches over the internet are updated to point to the Office 365 or Exchange Online DNS where your organization now resides**. To do this, run the following command to configure an accepted domain with a well-known name that will properly route email messages to the Office 365 or Exchange Online domain.

> **New-AcceptedDomain -Name "PublicFolderDestination_78c0b207_5ad2_4fee_8cb9_f373175b3f99" -DomainName contoso.onmicrosoft.com -DomainType InternalRelay**

> **If you're expecting your mail-enabled public folders in Exchange Online to receive external emails from the Internet, you have to disable Directory Based Edge Blocking (DBEB) in Exchange Online and Exchange Online Protection (EOP)**. See Use Directory Based Edge Blocking to reject messages sent to invalid recipients for more information.

**Comment by milkshakespoon** [comment]
> @milkshakespoon I see you asked the following question in the [related issue](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1612) you pointed out.
> 
> "The PFs no longer exist on prem... so how would it know where to route mail?"
> 
> I think the below step, from the [initial article](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#prerequisite-steps-on-the-legacy-exchange-server) has the answer. I assume you did this, right? And still the problem appeared.
> 
> > **On the legacy Exchange server, make sure that routing to the mail-enabled public folders that will exist in Office 365 or Exchange Online continues to work until all DNS caches over the internet are updated to point to the Office 365 or Exchange Online DNS where your organization now resides**. To do this, run the following command to configure an accepted domain with a well-known name that will properly route email messages to the Office 365 or Exchange Online domain.
> 
> > **New-AcceptedDomain -Name "PublicFolderDestination_78c0b207_5ad2_4fee_8cb9_f373175b3f99" -DomainName contoso.onmicrosoft.com -DomainType InternalRelay**
> 
> > **If you're expecting your mail-enabled public folders in Exchange Online to receive external emails from the Internet, you have to disable Directory Based Edge Blocking (DBEB) in Exchange Online and Exchange Online Protection (EOP)**. See Use Directory Based Edge Blocking to reject messages sent to invalid recipients for more information.

You're right, that does make sense. In our scenario we are using a third party spam appliance which our MX records point to. This means we never touch DNS during a migration. I think maybe that could be implemented into the article to explain this if you don't need to update DNS.

**Comment by scanum** [comment]
@bratsche  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by tonire1702** [comment]
We run into the same problem. The local exchange is not aware of the public folders in the cloud anymore when you have multiple domains in place. It will create a huge mess. It should be mentioned that a contact on-premises is necessary for the correct mailflow.
