### ISSUE TITLE
Search-Mailbox is being depreciated, how can we do this with the new commands

### ISSUE THREAD

**Issue by doverton12** [MicrosoftDocs/OfficeDocs-Exchange#1686]
Reading the information on the Search-Mailbox page on docs, this command stops working on 1st April 2020.

New Search and Compliance information can be found at https://docs.microsoft.com/en-gb/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization, but can you share how to achieve the above with the new supported compliance commands?

**Comment by mattpennathe3rd** [comment]
@doverton12 I'm sorry, but I cannot answer support questions here. If your question applies to PowerShell examples in specific articles in this repository, please open issues on those articles so I know what you're referring to. I'll be much better equipped to improve the articles, in that case.
