### ISSUE TITLE
Booking delegates feature not documented fully.

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/OfficeDocs-Exchange#1687]
Instead of allowing automatic booking from All users.
Instead of requiring a specific user or group of users to manually accept bookings.

You are able to choose specific users or groups to allow automatic bookings.
We use this for executive board rooms, so only the Executive Assistants can book those rooms.

There is a PowerShell method to update this, which I've used previously, but can't find the code at the moment.
Or you can use ECP, which I'll outline here.

Step 1. As a user with admin privileges on the resource.
Step 2. Go to https://outlook.office.com/ecp
Step 3. In the upper right hand side of the screen, click on your initials.
Step 4. Select "Another User..." and select the room you want to work on.
Step 5. Select "Settings" under the "Options" heading.
Step 6. Under the "Scheduling Permissions" heading you will see this text:
Choose users and groups that have permission to schedule this resource by sending a meeting request.
Step 7. Select the option "Selected users and groups" under the heading: 
"These users can schedule automatically if the resource is available."

Step 8. Select and save any users or groups who should be able to book the room automatically without requiring any approval.

If you modify other settings related to booking in the Admin.Microsoft.com portal or in the Outlook.office.com/ecp portal, you can break this configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1598a231-d154-1c94-d8aa-76084b45ed35
* Version Independent ID: 3cc7eb58-d64e-73f2-8566-f97ec30ac15e
* Content: [Create and manage room mailboxes](https://docs.microsoft.com/en-us/exchange/recipients/room-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/recipients/room-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/room-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Krytical13 Thanks for submitting this. I'm going to review this one and see what I can do to clarify the article.

**Comment by msbemba** [comment]
@Krytical13  Thank you for your feedback. We have added the steps in detail to the document via PR#https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1733

Thanks
Sri

**Comment by mattpennathe3rd** [comment]
@Krytical13 We've added many descriptions surrounding this feature, so this should resolve your issue. Thanks again or opening this issue. The updated article will be published in the near future.
