### ISSUE TITLE
Broken hyperlink for Option 2: Get status via the Hybrid Management PowerShell Module

### ISSUE THREAD

**Issue by Corina-Ionescu** [MicrosoftDocs/OfficeDocs-Exchange#1688]
The hyperlink for "the PackageManagement modules" redirects to https://www.microsoft.com/en-us/download/404Error.aspx . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Corina-Ionescu Thanks for submitting this. I've updated the link and the new version should be published in the near future. Please let me know if you see any other issues with this article (or with any others in this repo). Thanks again.
