### ISSUE TITLE
Please fix supported version for "AddressBookPolicyRoutingEnabled"

### ISSUE THREAD

**Issue by psykokwak4** [MicrosoftDocs/OfficeDocs-Exchange#1689]
[Enter feedback here]
Found this through internal work items via customer complain, [looks like E14 does not support AddressBookPolicyRoutingEnabled](https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/set-transportconfig?view=exchange-ps), please remove "Exchange 2010" for it. And also, please fix the format by adding a space after "Exchange 2016," for all attributes
![image](https://user-images.githubusercontent.com/6261280/73762694-52fe9700-4725-11ea-9b42-a0695bd016cc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da70217-e750-7ea9-5a53-7b35236f6145
* Version Independent ID: 0466f6a0-4e47-ffca-20b1-07b00050371e
* Content: [Transport Config attributes](https://docs.microsoft.com/en-us/exchange/org-config-transfer-attributes/transport-config)
* Content Source: [Exchange/ExchangeHybrid/org-config-transfer-attributes/transport-config.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/org-config-transfer-attributes/transport-config.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by psykokwak4** [comment]
And also, please fix the format by adding a space after "Exchange 2016," for all attributes

should be:
And also, please fix the format by adding a space after "2016," for all attributes

**Comment by mattpennathe3rd** [comment]
@psykokwak4 Thank you very much for submitting this. I've updated the article and the new version will be published in the near future.

Just so you know, in the future for simple fixes like this, you can edit the content and submit a pull request of your own. On each article, look for the Edit button in the upper right corner and that will walk you through the process.

Thanks again for filing this issue.

**Comment by psykokwak4** [comment]
thanks... and a friendly reminder, clone the repository, setup GPG signing key, follow corresponding GitHub documents, then you'll have all the commits shown as signed :D
