### ISSUE TITLE
Mailbox permissions supported in hybrid environments (Outlook on the web)

### ISSUE THREAD

**Issue by azizakyavas** [MicrosoftDocs/OfficeDocs-Exchange#1691]
Hi Team,

Is it possible to elaborate on this statement "Cross-premises mailbox permissions aren't fully supported in Outlook on the web".
Our users in-cloud are able to access mailbox content cross-premises in a hybrid environment but unable to access the mailboxes settings/options to modify the on-prem mailboxes rules, signature and any other mailbox settings.

Thanks

**Comment by mattpennathe3rd** [comment]
@azizakyavas I'm sorry, but I'm unable to answer support questions here. If there's a deficiency with a specific article, please open an issue from that article page so I can more easily remedy the problem with the documentation, but it sounds like you are having a configuration problem and you should open a support ticket.
