### ISSUE TITLE
Incorrect Command Syntax

### ISSUE THREAD

**Issue by stuntguy3000** [MicrosoftDocs/OfficeDocs-Exchange#1692]
Under the example for "Use Windows Powershell to permanently delete a user mailbox", the 'true' parameter needs to be removed as it is a switch and not a boolean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff7fa9f-2dec-34c3-e4b3-53614755499f
* Version Independent ID: 61e856b9-12fb-bdf6-0f49-0f6cc8b4b957
* Content: [Delete or restore user mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes#use-windows-powershell-to-permanently-delete-a-user-mailbox)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@stuntguy3000 Thank you very much for pointing this out. I've corrected this command and the updated article will be published in the near future.
