### ISSUE TITLE
External backup

### ISSUE THREAD

**Issue by alnelsonau** [MicrosoftDocs/OfficeDocs-Exchange#1693]
Can Microsoft provide official guidance to enterprise customers here on external backup (cloud to cloud or on-premise)?

**Comment by mattpennathe3rd** [comment]
@alnelsonau This is a big question. I'm not sure we can address this need here, but I will investigate and see if it's practical.

**Comment by VLG17** [comment]
@alnelsonau what is the article you are referring to or where would you have this information added? I'm trying to understand more about the context of this backup requirement.

**Comment by alnelsonau** [comment]
It would be great to see some clear guidance in the Exchange Online availability documentation. A lot of vendors provide cloud backup for Exchange and Microsoft doesn’t comment publicly on the benefits of this compares with retention.

**Comment by VLG17** [comment]
@alnelsonau could you please link the specific document you are referring to? That way i can check and see where i could potentially add something about what you're requesting.

**Comment by alnelsonau** [comment]
There is no document that I am aware of ... it would be good to create one.
