### ISSUE TITLE
Cannot automap shared mailbox to users outlook when permission is granted via mail-enabled sec group

### ISSUE THREAD

**Issue by mbuor2020** [MicrosoftDocs/OfficeDocs-Exchange#1697]
Hello, 

I have a shared mailbox created. I can grant individual permissions via user accounts in O365, the account then automaps within an hour or so to the users Outlook client, no problem at all. 
However, if I create a mail enabled sec group (which I believe is the correct type of group to do this) add a user to said group, then grant said group full access to the shared mailbox, the shared mailbox does not automap to the users Outlook client. 

Please can you advise?

Thanks, 
Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8492161-f0c6-e3e6-9f1e-c006e4edc99c
* Version Independent ID: c792e360-d35a-8aa8-a361-a05f01e0b6b7
* Content: [Manage permissions for recipients](https://docs.microsoft.com/en-us/exchange/recipients/mailbox-permissions?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/recipients/mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@mbuor2020 I'm sorry, but this repo is only for reporting problems with the documentation and I am unable to answer product support questions here. Please open a support ticket if you require assistance with this problem.
