### ISSUE TITLE
Variable $Source_RemoteServer not set

### ISSUE THREAD

**Issue by andy2002a** [MicrosoftDocs/OfficeDocs-Exchange#1698]
#4 on Step 5: Start the migration request says to enter "...RemoteServer $Source_RemoteServer..."

$Source_RemoteServer is not referenced anywhere else in the guide. The guide should provide instructions on what that variable should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@andy2002a Thanks for filing this issue. I'm going to investigate this and will report back in the near future.

**Comment by msbemba** [comment]
@andy2002a  Thank you for the feedback. We have modified the doc to update Step 5. This can be tracked via PR#https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1734

Thanks
Sri
