### ISSUE TITLE
UserScopeTo and UserScopeFrom - Clarify Difference Between Inside and External

### ISSUE THREAD

**Issue by jreinhardtiv4** [MicrosoftDocs/OfficeDocs-Exchange#1699]
I found that the explanation of the difference between inside the organization and outside the organization was ambiuous enough that I had to setup a test to clarify. The descriptions of the inside versus outside are not mutually exclusive as they surely must be in Exchange. For example, what if a mail user had an email address that was outside the organization (and this is a common experience). Would that be classified as inside or outside? In testing, I found as I suspected that any address to a non-accepted domain, whether it was on an AD object or not, was treated as an outside the organization. I would suggest review and clarification. At a minimum, perhaps the inside the organization condition statemetn could be clarified as something like this if it is accurate: "The recipient is a mailbox, mail user, group, or mail-enabled public folder that exists in the organization's Active Directory and has an e-mail address that is an accepted domain in the organization that is not of the external relay type."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65cb383c-bd27-940b-9cd5-48052d34076a
* Version Independent ID: e9e33e90-b9b9-a44c-6976-7d32cd003543
* Content: [Mail flow rule conditions and exceptions (predicates) in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mail-flow-rules/conditions-and-exceptions?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/conditions-and-exceptions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/conditions-and-exceptions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@jreinhardtiv4 Thanks for filing this. I will investigate soon and will report back on how we might be able to clarify this article.

**Comment by msbemba** [comment]
@jreinhardtiv4  Thank you for the feedback. We have modified the document via PR# https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1735 and Waiting for Author's suggestion/approval to merge it.

Thanks
Sri

**Comment by mattpennathe3rd** [comment]
@jreinhardtiv4 We've updated this article, but I want to make sure we've addressed all your concerns. Specifically, I'm not sure how the UserScopeFrom section can be improved. This issue will be closed when the existing changes are merged, BUT please comment back (or open a new issue and reference this one in the description) if you feel there's a need for more changes. I might need some additional guidance from you in that case and I'm happy to work with you further if there is a need. Thank you for your feedback!
