### ISSUE TITLE
Why is the Contact Microsoft, regarding SMTP domains, necessary in this documentation?

### ISSUE THREAD

**Issue by the-blesss** [MicrosoftDocs/OfficeDocs-Exchange#170]
This step does not appear to be technically necessary, since we have modern auth enabled for both on-prem and EO and mailbox data is caching for users with on-prem mailboxes (into the Outlook Mobile app). Can you explain what procedure is done on the MS side, or why it is necessary? Is there a specific scenario that this applies to in some cases?  https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019#contact-microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0020c770-fbf0-d36b-196c-59fd0a5dbe93
* Version Independent ID: bd5c069a-c325-28cf-5a58-8ae9c34c793d
* Content: [Using hybrid Modern Authentication with Outlook for iOS and Android](https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019#contact-microsoft)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
The product team is currently working on an update that will make it no longer necessary to contact Microsoft Support in this situation. We'll update the article when that functionality is released.
