### ISSUE TITLE
Include row for 'Saves to Sent Items folder' In 'Compare the options'

### ISSUE THREAD

**Issue by craig-martin** [MicrosoftDocs/OfficeDocs-Exchange#1701]
Some options for sending email result in the sent email being copied to the sender's Sent Items folder (sending to smtp.office365.com for example) while other options do not have this functionality (direct-send for example)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@craig-martin Thanks for this. Can you follow up and clarify what aspects of this article should be clarified? I think I need more to go on.

**Comment by msbemba** [comment]
@craig-martin Thank you for your feedback. We have added the row via PR#https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/1736. This is waiting for the authors' approval/suggestion to merge.

Thanks
Sri

**Comment by mattpennathe3rd** [comment]
@craig-martin This has been updated and the revised article should be published in the near future.
