### ISSUE TITLE
Out bound through Exchange online

### ISSUE THREAD

**Issue by phillkOCCM** [MicrosoftDocs/OfficeDocs-Exchange#1702]
Why isn't there a clearly identified 'centralized Online' mode?
I am in an org that has something configured this way through trial & error, but It seems here, it shouldn't be possible? However we want that because we want to leverage EOP & OME for all our mail traffic. It has been a complex setup, but not impossible. Please let me know why its not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b002f0ce-5397-15cb-4c60-0eaaa87aaf52
* Version Independent ID: 32e3a594-2d2c-9f8a-9a38-e60e3ffaae85
* Content: [Transport routing in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/transport-routing)
* Content Source: [Exchange/ExchangeHybrid/transport-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/transport-routing.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@phillkOCCM Thanks for submitting this issue. I'll have to investigate further, but will report back on what might be possible here.

**Comment by SignorelliDenis** [comment]
@phillkOCCM The scenario that you want to deploy is document: https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-for-multiple-locations#scenario-1-mx-record-points-to-office-365-and-office-365-filters-all-messages

Probably what is not documented is that Hybrid Configuration Wizard will not do this for you, if you want to force all on-prem outbound messages through Exchange Online you must add “*” (wildcard) on “Outbound to Office 365” Send Connector Address Space and add your tenant’s name as smart host (for example contoso-com.mail.protection.outlook.com).

To find your tenant's name: Admin Portal -> Setup > setting up your domain -> MX Record

**Comment by get-itips** [comment]
Hello @phillkOCCM how are you? You can find more information in the article that @SignorelliDenis Denis kindly shared and also I kindly redirect you to read here [Set up your email server to relay mail to the Internet via Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail#2-set-up-your-email-server-to-relay-mail-to-the-internet-via-microsoft-365-or-office-365) for more information.
Thank you

**Comment by scanum** [comment]
@phillkOCCM Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
