### ISSUE TITLE
Export-ModernPublicFolderStatistics.ps1 - AdminDisplayVersion is a String in Exchange 2013 Build 1395.4

### ISSUE THREAD

**Issue by PJNield** [MicrosoftDocs/OfficeDocs-Exchange#1703]
function AssertMinVersion expects to find the properties Major, Minor and Build of the AdminDisplayVersion property of the results of Get-ExchangeServer.

After the line "$version = $server.AdminDisplayVersion;"  (~Line 254)
added:
        $VersionRegex="^Version (?&lt;Major&gt;\d{1,2})\.(?&lt;Minor&gt;\d{0,4}) \(Build (?&lt;Build&gt;[\d\.]{3,6})\)$"
        if ($version -match $VersionRegex) {
          $Version = new-object PSObject -Property @{Major=$Matches["Major"];Minor=$Matches["Minor"];Build=$Matches["Build"]}
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@PJNield thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by PJNield** [comment]
Hi,

I added my patch to get past the issue.

**Comment by mattpennathe3rd** [comment]
@PJNield To clarify your situation, were you using scripts that were provided with an on-premises installation, or did you download the latest scripts and then you still encountered this problem? If you're able to reproduce with the latest scripts, please let us know (if this is feasible for you).

**Comment by PJNield** [comment]
Hi,

I downloaded the latest script.  I’ll have a look a reproducing the issue.

**Comment by mattpennathe3rd** [comment]
@PJNield Thanks for helping us nail this down. Let me know how it goes with reproducing the issue.

**Comment by mattpennathe3rd** [comment]
@PJNield Just following up to see if you've had the opportunity to retry this with the latest scripts. Please let me know how it is going for you.

**Comment by get-itips** [comment]
Hello @PJNield how are you?
Were you able to repro with the latest version of the scripts?
Thank you

**Comment by PJNield** [comment]
Sorry, no, finished the migration before I had a chance to.

**Comment by scanum** [comment]
@PJNield Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
