### ISSUE TITLE
Is there any reason there's no updated version for this?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#1704]
I'm just wondering why this page doesn't have the Exchange version selector at the top left and it seems to be dedicated to Exchange 2013, while this topic is still a thing in newer versions.  Can it be updated?  Or, can a note be added to confirm that everything is still the same with newer versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b3694c-16ed-97fb-1423-16d950922396
* Version Independent ID: fd8bf16d-7ed7-c0f9-3157-e11fc0653829
* Content: [Renew the federation certificate: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/renew-the-federation-certificate-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by JeremyTBradshaw** [comment]
I will also take this opportunity to blast Microsoft for re-using Exchange 2013's OWA/ECP and not even updating any of of the "learn more" links.  On a fully-current Exchange 2016 server, in ECP, all the Learn More links go to Exchange 2013 pages that have the purple banner on them stating:

"We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported."

and

"This page was permanently redirected to docs.microsoft.com"

This is very aggravating, and not acceptable.

The same issue is true for so much of the rest of Exchange 2016/2019 - it is a very poorly executed re-brand of Exchange 2013.  Every day I run into more and more nonsense within the Exchange product like these examples.  I feel the Exchange team of yesterday has retired and moved on or something.

**Comment by mattpennathe3rd** [comment]
@JeremyTBradshaw Just to let you know, I am actively investigating this behind the scenes. I don't have much authority outside of this repo, but I've escalated this and will report back (though I don't have an ETA). I appreciate the candid feedback!

**Comment by JeremyTBradshaw** [comment]
Hi @mattpennathe3rd , thanks for the update.  And please don't take my harsh messages to heart.  I tend to write comments way more ferociously that I would intend to behave in real life.

FYI/update - I've just gone through this process in 2 fairly large production environments with Exchange 2016/2010 coexistence, using the renew still-valid certificate procedure.  The process worked, however in both cases it took about 1.5 hours before `Test-FederationTrust -UserIdentity <mailbox ID>` would succeed in its 6th of 6 steps.  In that interim period, on-premises mailboxes could NOT lookup Free/Busy for EXO mailboxes, while EXO mailboxes COULD lookup Free/Busy for on-premises mailboxes.

I'm not sure if it was just good old time, but we did find in researching online this command has solved the same error message for others:

`Get-FederationTrust | Set-FederationTrust –RefreshMetadata` (or just do Set-FedererationTrust with -identity)

It kind of makes sense to me that we would want to run this command after promoting the OrgNextPrivCertificate to the current (OrgPrivCertificate), similarly to how it was refreshed earlier in the procedure upon adding the new cert into the Federation Trust in the first place.  Would be nice to know if that step is recommended / necessary.  Next time I do this, I'll be planning to wait 2 hours without doing anything.  Doing that might drive clarity on whether or not the additional command was needed or not.

That was taken from here - [](https://social.technet.microsoft.com/Forums/lync/en-US/cbf7a94b-0064-4ed5-92ea-a5d86521ebca/federated-trust-failing-handing-out-null-tokens?forum=exchangesvrgeneral) - however it didn't solve it for some people in that thread, nor did it solve anything for us immediately.  We waited about 1 hour after having tried that and the issue magically disappeared.  So I think we were just waiting on the Microsoft Federation Gateway's end to 'replicate' or refresh etc.

**Comment by mattpennathe3rd** [comment]
@JeremyTBradshaw Thanks for all of these details. Still working on this.

Regarding your comment above about the "Learn More" links in 2016 server going to outdated content, do you also see this problem in 2019 Server?

**Comment by JeremyTBradshaw** [comment]
Hi @mattpennathe3rd , I don't have a 2019 install available to go check.  I will stand one up though soon, but 'soon' could shift in shape/size so didn't want to leave you hanging without disclaimer.  Hopefully by next week's end.

**Comment by mattpennathe3rd** [comment]
@JeremyTBradshaw There's no rush. I appreciate your input! If I'm able to fix the Learn More link problem at all, it will require help from several others outside my team and that always takes time, so any possible fix will not be quick, in any case.

**Comment by scanum** [comment]
@JeremyTBradshaw  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
