### ISSUE TITLE
Incorrect: The Graphical User Interface/Wizard can be used as an alternative to update the Microsoft Teams certificate automatically.

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#1705]
FYI that note is just false, you can't use the GUI to update the Federation certificate at all, period.  In fact, it's just a design oversight that the "Renew" link even shows up where it does for this certificate.

I realize in the older issue @TheBluLion said something about doing it in the GUI makes the process support Teams yada yada,, but he/she went silent and never confirmed your question so this note just never belonged on this page.  It's a false statement.

Please remove it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b3694c-16ed-97fb-1423-16d950922396
* Version Independent ID: fd8bf16d-7ed7-c0f9-3157-e11fc0653829
* Content: [Renew the federation certificate: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/renew-the-federation-certificate-exchange-2013-help#update-a-working-federation-certificate)
* Content Source: [Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by TheBluLion** [comment]
The note wasn’t about supporting teams, it was that the powershell process is missing the step to associate the certificate with the service, where using the GUI automatically completes all the required steps for you.
Let me know if you would like the customer comments/notes from this comment again- I thought I had sent them before but would be happy to resend.

﻿ -﻿ --
Eu Nice Loh
Premier Field Engineer
Office: (314) 872 5916
EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com>
IM:euloh@microsoft.com
8AM-5PM CT
[Microsoft]
﻿
If you have any feedback about my work, please let either me or my manager Annele Richards know at Annele.Richards@microsoft.com<mailto:Annele.Richards@microsoft.com>

**Comment by JeremyTBradshaw** [comment]
@TheBluLion  "the note" I'm referring to is the purple box note on the docs page, which was out there as a response to the issue you opened.  I'm not saying "the note" as in "what you said" I'm talking about the literal Note on the page.  

And what I meant by saying you went silent - they asked you if adding this note would suffice to address the issue you raised, but then you never responded (at least in the GitHub issue comments, and then they went ahead and added the purple box note, which simply has no validity.

**Comment by TheBluLion** [comment]
Ah, that makes sense.
I must have missed a notification on that response- I’m on the same page now.

﻿ -﻿ --
Eu Nice Loh
Premier Field Engineer
Office: (314) 872 5916
EuNice.Loh@microsoft.com<mailto:EuNice.Loh@microsoft.com>
IM:euloh@microsoft.com
8AM-5PM CT
[Microsoft]
﻿
If you have any feedback about my work, please let either me or my manager Annele Richards know at Annele.Richards@microsoft.com<mailto:Annele.Richards@microsoft.com>

**Comment by mattpennathe3rd** [comment]
@JeremyTBradshaw Thanks for submitting this and for the correction. I've removed the note and the updated article should be published soon.
