### ISSUE TITLE
Modern Public Folder Coexistence and THEN Migration with Office 365

### ISSUE THREAD

**Issue by kevinblumenfeld** [MicrosoftDocs/OfficeDocs-Exchange#1706]
*** I would ask that the articles state plainly what the goal is and which article to follow next. ***

There are two things we need to be able to do.  

A. Create coexistence between Modern Public Folder and Exchange Online (So that those with mailboxes on-premises and those with mailboxes in Exchange Online can all see the same Public Folders).

B. After the last mailbox has been migrated to Exchange Online, completely migrate modern Public Folders to Office 365.  At that point, only Exchange Online mailboxes will be able to see the Public Folders.

*There are many articles and this is more than a little confusing.*

1. Configure Exchange 2013 public folders for a hybrid deployment - https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders

Which contain the scripts:
    Sync-MailPublicFolders.ps1
    SyncMailPublicFolders.strings.psd1

2. Configure Exchange Server public folders for a hybrid deployment - https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders

3. Use batch migration to migrate Exchange Server public folders to Exchange Online - https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019

Which contain the scripts:
    Sync-ModernMailPublicFolders.ps1
    SyncModernMailPublicFolders.strings.psd1

Official guidance would be appreciated! 
Thank you.
Kevin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1812196b-e6c5-7f6e-fa82-49df2a47d73d
* Version Independent ID: cc06c76a-b7a0-7c21-0a73-c66b9b05a055
* Content: [Configure Exchange 2013 public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@kevinblumenfeld Thanks for filing this issue. I'll have to investigate further, but will report back on what we might be able to do. Please note that I can't answer support questions here, as I only work on the docs, but I'll do what I can.

**Comment by kevinblumenfeld** [comment]
@mattpennathe3rd Thank you.  I would only be looking for clarification that any other consultant/admin would require - not support.  I would say most are looking for how setup coexistence then ultimately migrate public folders to office 365.  The script names introduce confusion. Also, three articles to do two things.  I have done many public folder coexistence preps and migrations and while I have notes on what to do - Microsoft should clarify.  I re-read these articles and it makes me second guess my own notes.

**Comment by msdmaguire** [comment]
@kevinblumenfeld Thank you for your patience. The Exchange 2013 article has been updated and now points to the same scripts as the other articles you cited. Additionally, I will follow up with the product team to get the articles more consistent with each other, as you raise a good point. We appreciate the feedback.

**Comment by kevinblumenfeld** [comment]
@msdmaguire 

 Thank you however this article still shows the wrong scripts:

https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders

These are the legacy PF scripts

The words Sync-Modern* should be in the script names.

**Comment by msdmaguire** [comment]
@kevinblumenfeld Understood. That article will fixed very soon.
