### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ildrosos** [MicrosoftDocs/OfficeDocs-Exchange#1707]
Hello please change the command 
Set-OrganizationConfig -PublicFoldersEnabled Remote -RemotePublicFolderMailboxes PFMailbox1,PFMailbox2,PFMailbox3
To:
Set-OrganizationConfig -PublicFoldersEnabled Remote -RemotePublicFolderMailboxes 'PFMailbox1','PFMailbox2','PFMailbox3' since it's not working if multiple mailboxes are specified or if they contain spaces or dashes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders?redirectedfrom=MSDN#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@ildrosos Thank you very much for pointing this out. I've corrected the article and the changes should be published in the near future.
