### ISSUE TITLE
How is the default policy changed?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#1708]
I understand how to change current mailbox deletion setting from this article but how is it changed so that all new mailboxes get the changed setting?  For example, I can run Get-Mailbox -ResultSize unlimited -Filter "RecipientTypeDetails -eq 'UserMailbox'" | Set-Mailbox -RetainDeletedItemsFor 30 to set the deletion time for all to 30 days.  But what about a new account created after that?  Do I have to keep re-running one of the commands here to set theirs from 14 to 30 days?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a43744-eddc-762f-d3c7-6f8732141ad7
* Version Independent ID: c20377ab-03ae-62ed-96bd-04a9bc653286
* Content: [Change how long permanently deleted items are kept for an Exchange Online mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis An excellent question. I've searched quite a lot, but the docs seem to dance around this issue; they state in several places that it is possible to change this setting for the mailbox database as a whole (and thus apply it automatically to new user accounts and mailboxes), but then do not go into the needed detail for actually doing it.

I'll see if I can get some insight from the more technical folks here and will report back.

**Comment by Canis-Lupis** [comment]
Thank you for your efforts.

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis Thanks for your patience!

To cover mailboxes created in the future, you should be able to use a mailbox plan that has the new retention policy that you wish to apply to new mailboxes.

https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans

https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/set-mailboxplan?view=exchange-ps

This should help in your situation, but let me know if this is not what you are looking for. If this works for you, I will add a note to this article pointing this out and linking to these two articles.

**Comment by scanum** [comment]
@Canis-Lupis  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis Thanks again for your patience. If you have any feedback on my comment above, please let me know. I will update this article in the near future, regardless, and I hope that's some help to you.
