### ISSUE TITLE
do we have a timeframe to replace the parameters ?

### ISSUE THREAD

**Issue by ViniciusSipoli** [MicrosoftDocs/OfficeDocs-Exchange#1710]
[Enter feedback here]
Hi, i see "The BadItemLimit and LargeItemLimit parameters will be completely replaced by DataConsistencyScore at a future date." 
it would be good if we have a time-frame to be documented so we can be prepared to the change accordingly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40bce01-0b1f-1952-5198-d5a15211b533
* Version Independent ID: 3f0ac568-cfbd-5255-d803-b7883c32c50f
* Content: [Track and Prevent Migration Data Loss](https://docs.microsoft.com/en-us/exchange/mailbox-migration/track-prevent-data-loss-dcs)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@ViniciusSipoli An excellent request and we definitely will do so. To my knowledge, this timeline has not been set in stone yet. As soon as we have this finalized, this article will be updated with that information.

**Comment by ViniciusSipoli** [comment]
Thanks for the quick response Matt, we will wait for the updates.
