### ISSUE TITLE
Exchange and AD Attributes

### ISSUE THREAD

**Issue by danfoxley** [MicrosoftDocs/OfficeDocs-Exchange#1714]
This implies it is ok to have Exchange 2003 installed to manage AD attributes.  Please clarify, as I would think Exchange 2016 HCW is the only "supported" solution.

"If you implement a single sign-on solution, it is strongly recommended that you maintain at least one Exchange Server so that you can access Exchange System Manager (Exchange 2003) or the Exchange Management Console/Exchange Management Shell (Exchange 2007) to manage mail-related attributes on the on-premises mail-enabled users. For Exchange 2007, the Exchange Server that you maintain should have the Hub Transport, Client Access, and Mailbox server roles installed."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38ef0d5-c0c1-b1cf-f687-f4f856157713
* Version Independent ID: 38f4deee-3b23-206d-df63-8fa6a4935419
* Content: [What you need to know about a staged email migration to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/what-to-know-about-a-staged-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/what-to-know-about-a-staged-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/what-to-know-about-a-staged-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@danfoxley Thanks for submitting the issue. I will have to check into this, but will report back soon and will see if we can clarify the article.

**Comment by get-itips** [comment]
Hello @danfoxley Dan, how are you?
This article is talking exclusively about staged migration.
Which, you could perform from 2003 and 2007 server versions (**Out of support in reality as you can see noted in the article**).

Hybrid Configuration Wizard or HCW is not mentioned in the article (to migrate from 2010 to 2019), which is a tool used in another different migration path, and in that case the hybrid environment is managed thru the EAC from an on-premises Exchange Server, more info here https://docs.microsoft.com/en-us/exchange/hybrid-management

Thank you

**Comment by scanum** [comment]
@danfoxley Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
