### ISSUE TITLE
what about NDR and other system messages ?

### ISSUE THREAD

**Issue by joker226** [MicrosoftDocs/OfficeDocs-Exchange#1715]
what about NDR and other system messages, can a rule be applied on them ? I have an issue and if the answer to "Can a rule be applied" is No, I would like to see it there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9125c4e-9bd8-e991-efd4-3fb21213f368
* Version Independent ID: 11b0bc29-a2de-90c7-3e57-7eb90b88da87
* Content: [Mail flow rules in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mail-flow-rules/mail-flow-rules?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@joker226 Thanks for filing this issue. I will need to investigate, but I will report back.

**Comment by dariomws** [comment]
Hi @joker226, thank you for your feedback and help us to improve docs.microsoft.com.

I think transport rules apply to any message. Did you open a support ticket to work on this issue?

**Comment by scanum** [comment]
@joker226 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
