### ISSUE TITLE
Clarification on G Suite automatic mail forwarding

### ISSUE THREAD

**Issue by born-slippy** [MicrosoftDocs/OfficeDocs-Exchange#1716]
Re:
"On the G Suite side, automatic mail forwarding has been set up for migrated users, so that new emails sent to their G Suite address will be delivered instead to the Office 365 address via the routing domain. This is shown by the green arrows in the above diagram."

Please note that if an organization has disabled user's ability to set forwarding addresses due to policy, that the 365 G Suite migration tool does not appear to be able to set the forwarder successfully.  We needed to enable permissions to set SMTP forwarding in order for this to work properly.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@born-slippy Thanks for filing this issue. I'll investigate this one and will report back.

**Comment by ishfaq19** [comment]
I need a clarification regarding the Forwarding that happens after the Final Sync,

After the Final sync, on Gsuite, is the option set to "Store and forward or just Forward without delivering the emails in Gsuite mailbox"?

**Comment by born-slippy** [comment]
Hello:
After we enabled the option to allow user forwarding of mail, and after a
final sync of our test user, the option 'Forward a copy of incoming mail to
<365 routing address>' and 'keep <organization name>'s copy in the Inbox'
is set on the mailbox.  This was verified via the User mailbox options ->
'Forwarding and POP/IMAP' blade.  Hope that helps - not sure if the
question was for me.

**Comment by Joepvtilburg** [comment]
Since this week i noticed this is no longer working

TooManyTransientFailureRetriesPermanentException/BadRequestWebTransientException/WebException: Error: The job encountered too many transient failures ‎(65)‎ and is quitting. The most common failure is BadRequestWebTransientException/WebException with the hit count 59. --> The web server responded with a 400 Bad Request error. Uri: https://www.googleapis.com/gmail/v1/users/*redacted*/settings/forwardingAddresses --> The remote server returned an error: ‎(400)‎ Bad Request.

**Comment by mattpennathe3rd** [comment]
@ishfaq19 The default behavior should be store and forward; messages will be in the GSuite mailbox and also forwarded.

@born-slippy Thanks again for opening the issue. I'm sorry that this took some time to address. The behavior you described is correct and expected, but we should definitely call this out in the article, so the updated version will be published in the near future. Thank once more for letting us know about this.
