### ISSUE TITLE
URL for link to 'Virtual Directory Management' from 'Default settings for Exchange virtual directories' is invalid

### ISSUE THREAD

**Issue by OftKilted** [MicrosoftDocs/OfficeDocs-Exchange#172]
Link at bottom of page in the 'See Also' section:

"Virtual directory management" has an invalid URL. 

https://https//technet.microsoft.com/library/ff952752(v=exchg.150).aspx

Should be:

https://technet.microsoft.com/library/ff952752(v=exchg.150).aspx

Note: The reference page does not reference Exchange Server 2016 in the 'Other versions' dropdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49e79dae-29d0-b4a7-489d-83529e750c15
* Version Independent ID: 14fabcf0-5751-a091-5432-2d550932973a
* Content: [Default settings for Exchange virtual directories](https://docs.microsoft.com/en-us/Exchange/clients/default-virtual-directory-settings?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/default-virtual-directory-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/default-virtual-directory-settings.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@OftKilted Thank you for this feedback

I took a look at your changes and merged your pull request. Thank you again for making to docs better.
