### ISSUE TITLE
-FreeBusyAccessLevel switches 

### ISSUE THREAD

**Issue by zerodrool** [MicrosoftDocs/OfficeDocs-Exchange#1720]
Remove hyphen from commands for free busy access level
"-FreeBusyAccessLevel -LimitedDetails" should be "-FreeBusyAccessLevel LimitedDetails"

It is correct in the first command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e75a151d-8833-820a-f896-2bda90639c7a
* Version Independent ID: c098487b-e9bd-c12f-9674-c2a6f97f83b8
* Content: [Create an organization relationship: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/create-an-organization-relationship-exchange-2013-help?redirectedfrom=MSDN#feedback)
* Content Source: [Exchange/ExchangeServer2013/create-an-organization-relationship-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/create-an-organization-relationship-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
Fixed by #1721 . Thanks again, @zerodrool.
