### ISSUE TITLE
Message Tracking docs out-of-date?

### ISSUE THREAD

**Issue by PrayingMoses** [MicrosoftDocs/OfficeDocs-Exchange#1722]
Source: SMTP EventId:SENDEXTERNAL not within the docs.

**Comment by mattpennathe3rd** [comment]
@PrayingMoses Thank you for submitting this issue. I will investigate this further and will post back in the near future.

**Comment by scanum** [comment]
@PrayingMoses Hi! Could you please link the documentation you are referring to? Thanks!

**Comment by lindspea** [comment]
@PrayingMoses please send us the link to the document you are referring to so we can investigate further.

**Comment by mattpennathe3rd** [comment]
I believe this refers to this doc:

https://docs.microsoft.com/en-us/exchange/mail-flow/transport-logs/message-tracking

...which actually has a duplicate issue for the exact same problem: #1771

As such, I'm closing this issue as a duplicate, but we will explore a fix in #1771.
