### ISSUE TITLE
Missing Modern Public Folder Hybrid

### ISSUE THREAD

**Issue by CThreadgill** [MicrosoftDocs/OfficeDocs-Exchange#1725]
Glaring omission on how to configure Exchange 2013-2019 Modern Public Folder for hybrid per this article 
https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2503f71a-ca17-de82-0f15-b0477ad43012
* Version Independent ID: 5c8c6837-7893-ad85-87b2-98f4ce879be9
* Content: [Public folder procedures](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/procedures?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/procedures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/procedures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@CThreadgill I'm sorry, but I'm not sure what issue you're pointing out. This is the on-premises Exchange Server documentation and your scenario only applies to hybrid deployments, which is a separate documentation set that you linked to. Am I misunderstanding?

**Comment by CThreadgill** [comment]
The scenarios go from setting up New, Legacy Hybrid, then skips to migration.  Orgs running 2013/16/19 have to follow different coexistence steps that are not mentioned here at all, but found elsewhere (link above)
