### ISSUE TITLE
Scenario 4: On-prem Linux mail server, some mailboxes moved to O365 and DirSync

### ISSUE THREAD

**Issue by ekzp** [MicrosoftDocs/OfficeDocs-Exchange#1729]
What if there is a non-Microsoft Linux-based on-prem mail solution (e.g. Postfix/Dovecot), some mailboxes moved to O365, shared namespace for mail flow coexistence, and DirSync for SSO and simplified management?

In this scenario:
1. There are no Exchange attributes because there has never been an Exchange server installed in the on-prem, system.
2. With DirSync in place and no Exchange attributes on-prem, one cannot manage cloud mailboxes properly.
3. We extend the schema.
4. Then what?

Since IMAP migration from non-Microsoft solutions has been mentioned, such a scenario should also be included.

**Comment by scanum** [comment]
@ekzp thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
