### ISSUE TITLE
#1708 closed without resolution.

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#1731]
@scanum #1708 was not resolved before you closed it.  Last status was from @mattpennathe3rd who stated, "I'll see if I can get some insight from the more technical folks here and will report back."  So far, he was not reported back.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a43744-eddc-762f-d3c7-6f8732141ad7
* Version Independent ID: c20377ab-03ae-62ed-96bd-04a9bc653286
* Content: [Change how long permanently deleted items are kept for an Exchange Online mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@Canis-Lupis An apology about that. Will re-open.

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis I will close this issue now so we can keep the discussion on your original issue (which has been reopened).
