### ISSUE TITLE
Configuration key for OneDrive

### ISSUE THREAD

**Issue by Dzysta** [MicrosoftDocs/OfficeDocs-Exchange#1739]
Hi, 

I'm not able to find configuration key for Outlook mobile app on iOS (using Intune)  which allows me to configure automatic connection to OneDrive when user login. 

Is this even possible?

**Comment by scanum** [comment]
@Dzysta thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
