### ISSUE TITLE
Jerry S. Wilkinson

### ISSUE THREAD

**Issue by BenWilk87** [MicrosoftDocs/OfficeDocs-Exchange#174]
Stepped on a toad.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c41fca7-c13b-20fe-83e6-34d91c5f9227
* Version Independent ID: 0844eadb-236e-15cb-5bbf-4963dc30a347
* Content: [Exchange Server Privacy Statement](https://docs.microsoft.com/en-us/Exchange/about-documentation/privacy-statement?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/about-documentation/privacy-statement.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/about-documentation/privacy-statement.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by QuyenNguyenCDA** [comment]
Ok
