### ISSUE TITLE
Specify that the onmicrosoft.com address should be used

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/OfficeDocs-Exchange#1742]
Under the "Apply to a small set of users" section, there is a note explaining that enhanced filtering only applies if the specific email address matches, and that for a user with multiple addresses it would be necessary to enter each of those addresses separately in order to ensure enhanced filtering applies.  That's correct, but I think it needs to go a little further.  With support's assistance, I recently discovered that in a hybrid environment (where enhanced filtering is likely to be applied), it is necessary to enter the user's remote routing address, rather than their actual email address.  When exchange on-prem routes the email to exchange online using the remote routing address, exchange online actually looks at that address rather than the original address in the To field. 
If you only enter the user's normal email address (e.g. USERNAME@MYDOMAIN.COM), enhanced filtering will never be applied since all mail routed from on-prem to online will be using the remote routing address (e.g. USERNAME@MYDOMAIN.mail.onmicrosoft.com).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd501e4-be27-1da8-e250-7cc1ac22c8ec
* Version Independent ID: ada2e5a7-646f-3576-5834-4727151b7743
* Content: [Enhanced filtering for connectors](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@NeighborGeek  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@NeighborGeek Does the second note under "Apply to a small set of users" section not address this?

> This option is only affective on the actual email address that you specify. For example, if a user has five email addresses associated with their mailbox (**also known as proxy addresses**), you'll need to specify all five of their email addresses here. Otherwise, messages that are sent to the four other email addresses will go through normal filtering.

The remote routing address is in fact a proxy address, right?

https://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/new-remotemailbox?view=exchange-ps

![image](https://user-images.githubusercontent.com/41186174/81152997-27d94d00-8f8b-11ea-84fe-c4326ad0388b.png)

If you feel this is not enough, what else whould you add? I'm thinking in terms of a Note.

**Comment by mattpennathe3rd** [comment]
@NeighborGeek Thanks very much for reporting this. We've updated the article and the new version should be published in the near future.
