### ISSUE TITLE
PKCS #7 Powershell examples have an extra ] characters at the end of the line

### ISSUE THREAD

**Issue by devFofo** [MicrosoftDocs/OfficeDocs-Exchange#1743]
Right line is probably: 
Import-ExchangeCertificate -FileData ([Byte[]](Get-Content -Encoding Byte -Path "&lt;FilePathOrUNCPath&gt;" -ReadCount 0))
with no ] at the end

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0aa4eed-e992-4cd9-0b43-4321eb65160d
* Version Independent ID: 3fe6fed7-215e-a93a-9dd5-24b59af1c815
* Content: [Import or install a certificate on an Exchange server](https://docs.microsoft.com/en-us/exchange/architecture/client-access/import-certificates?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/import-certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/import-certificates.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@devFofo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@devFofo You are correct! Thank you for submitting this. I have updated the commands the revisions will be published in the near future. Thanks again for pointing this out.
