### ISSUE TITLE
Error 5.7.708 - access denied

### ISSUE THREAD

**Issue by JonasDewit** [MicrosoftDocs/OfficeDocs-Exchange#1745]
The information in this paragraph is unclear. What is the low reputation of the IP addresses based on? Which IP addresses does this refer to? Which licenses does this refer to? How to request an exception? And an exception to what exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf9a643-6f4b-c052-8d93-380d85d17b70
* Version Independent ID: 23792aa8-ec12-4fc0-2a3b-6f41373a1761
* Content: [Fix email delivery issues for error codes 5.7.700 through 5.7.750 in Exchange Online](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-7-700-through-5-7-750#57708-access-denied-traffic-not-accepted-from-this-ip)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-7-700-through-5-7-750.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-7-700-through-5-7-750.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@JonasDewit  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by linlu** [comment]
A more complete explanation of the steps to take for 5.7.705 are located here: https://support.microsoft.com/en-us/help/4498191/tenant-has-exceeded-threshold-error-when-you-send-mail  
All suggested actions in this article should include links to specific step-by-step actions to take. I found several articles via Google to various Microsoft support areas that specifically address the lack of detail in this article.

**Comment by get-itips** [comment]
Thanks for your feedback @JonasDewit Jonas, will propose a better explanation thru a pr.
