### ISSUE TITLE
Outlook for iOS and Android

### ISSUE THREAD

**Issue by vsmusic2000** [MicrosoftDocs/OfficeDocs-Exchange#1746]
In the list of unsupported clients, why does it say that Outlook for iOS and Android do not support modern authentication?

**Comment by scanum** [comment]
@vsmusic2000 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
