### ISSUE TITLE
This Cmdlet is no longer valid on Exchange Online

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-Exchange#1747]
The cmdlet New-GlobalAddressList or Get-GlobalAddressList is no longer available for Exchange Online.
![image](https://user-images.githubusercontent.com/5489996/74863401-7293e300-5313-11ea-943f-9ed6f47289dd.png)

![image](https://user-images.githubusercontent.com/5489996/74863437-87707680-5313-11ea-916f-7142f97aa69f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0ed59f-71c5-de9b-2b26-bbe12848514d
* Version Independent ID: 39c67675-d3b8-9a3a-a2cc-87eb372b8d59
* Content: [Create a global address list in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-lists/create-global-address-list)
* Content Source: [Exchange/ExchangeOnline/address-books/address-lists/create-global-address-list.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/address-lists/create-global-address-list.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by j0rt3g4** [comment]
The solution was on the EAC (Portal > Show All > Exchange > Permissions > (On tab Admin Roles) select Organization Management)
![image](https://user-images.githubusercontent.com/5489996/74955352-29eb3100-53ca-11ea-9c29-d02851dcf3db.png)

Then Add: Address List and press ok as shown:
![image](https://user-images.githubusercontent.com/5489996/74955487-569f4880-53ca-11ea-8d50-61e5d1bef7f8.png)

**Comment by mattpennathe3rd** [comment]
@j0rt3g4 I'd like to investigate this one further, so I have reopened the issue. I will follow up in the near future.

**Comment by j0rt3g4** [comment]
@mattpennathe3rd  Excellent Matt, If you require me to do any Pull Request to make the doc better I'll be up to do so.
I work with Mr @kenwith  on the documentation team as well, but this repo is out of our scope at the moment.

**Comment by mattpennathe3rd** [comment]
@j0rt3g4 Thank you! This looks good, after all. I believe that the process you documented in your screenshots is alluded to in the PowerShell documentation, so this should work as expected.

**Comment by j0rt3g4** [comment]
That process is not on the documentation
We just have a note there.
![image](https://user-images.githubusercontent.com/5489996/75597259-18ed9000-5a5a-11ea-9ee5-2cd818555391.png)


I still thinks there's a need of those screenshots on the documentation for new users :)

**Comment by mattpennathe3rd** [comment]
@j0rt3g4 We avoid screenshots whenever possible because they tend to make procedures harder to follow instead of easier.

To recap, is there a problem with this document? As you quoted, it mentions that the role groups need to be modified, and then we link to an article explaining how to do that using PowerShell (which also links to another article showing how to do it through the EAC GUI), so it seems complete to me, unless I am missing something.

**Comment by j0rt3g4** [comment]
If I didn't know where the roles were.
I would be totally lost.
That's all I'm saying, the documentation should be to make people's life easier and not navigating through several iterations wherein the end people will not understand a thing :) and get lost. It's my opinion.

**Comment by IamAliBaba** [comment]
$UserCredential = Get-Credential
 
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
 
Import-PSSession $Session
