### ISSUE TITLE
Sun Java System Messaging Server 6.3 CSV files for IMAP migration

### ISSUE THREAD

**Issue by tszafran** [MicrosoftDocs/OfficeDocs-Exchange#175]
Looking at CSV files for IMAP migration batches there is sample formats for various IMAP systems. I was wondering if Sun Java System Messaging Server 6.3 is a supported IMAP migration path and is there a CSV format sample that can be provided?

**CSV files for IMAP migration batches**
https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/csv-files-for-imap-migrations

**Sun Java System Messaging Server 6.3 Administration Guide**
https://docs.oracle.com/cd/E19566-01/819-4428/index.html

**Comment by AndreaBarr** [comment]
@tszafran Thank you for this inquiry.

I am not sure if Sun Java System Messaging Server 6.3 is a supported IMAP path. I'll get this in front of the Exchange team though so we can get this answered. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @tszafran , thanks for your feedback.

Any server using the standard IMAP protocol is supported, so you can use it to migrate from Sun Java System Messaging Server 6.3. You should use the CSV format you can see in the article.
