### ISSUE TITLE
Working with soft deleted mailboxes: connect-mailbox not possible

### ISSUE THREAD

**Issue by J-a-k-o-b** [MicrosoftDocs/OfficeDocs-Exchange#1752]
Hi, 
when i try to connect a soft deleted mailbox via connect-mailbox this isn´t possible. The connect-mailbox command can´t find the disconnected mailbox. This is also whats described in:
https://docs.microsoft.com/en-us/exchange/recipients/disconnected-mailboxes/disconnected-mailboxes?view=exchserver-2016#working-with-soft-deleted-mailboxes
But in the table:
https://docs.microsoft.com/en-us/exchange/recipients/disconnected-mailboxes/disconnected-mailboxes?view=exchserver-2016#summary-of-working-with-disconnected-mailboxes
is written that you can use connect-mailbox for soft deleted mailboxes
and the Link to the documentation:
https://docs.microsoft.com/en-us/exchange/recipients/disconnected-mailboxes/disconnected-mailboxes?view=exchserver-2016#disconnected-mailbox-documentation
also contains the word connect

The Link "Connect or Restore a Soft-Deleted Mailbox" leads to a Exchange 2013 Documentation, where it was maybe possible to use connect for soft deleted mailboxes

**Comment by scanum** [comment]
@J-a-k-o-b thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
