### ISSUE TITLE
Delivery notification or delivery receipts for O365 Groups

### ISSUE THREAD

**Issue by apanzalovic** [MicrosoftDocs/OfficeDocs-Exchange#1754]
Can we get clarity on the Delivery notifications/receipts on a MS Group? Seems to be dropped by the server with a very ambiguous error stating that an InboxRule deleted the message but perhaps it should state the same error as we have for DLs to indicate that delivery receipts are not applicable for Groups. 
You guys created a complex Chimera of a product but some of the logic seems to not have followed.

thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d2c66-f9d8-7ac2-55c8-1ccfbe966bf6
* Version Independent ID: 3dc90f07-c2bb-9f37-82c2-a713f0b8f27c
* Content: [What happened to delivery reports in Office 365?](https://docs.microsoft.com/en-us/exchange/monitoring/what-happened-to-delivery-reports-in-office-365)
* Content Source: [Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@apanzalovic Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @apanzalovic how are you?
Hope you are doing good. I am taking over this issue, I know that some time has passed, can you please clarify if you refer to _Read receipts and delivery notifications_ that you configure from Outlook? If that's it, I could succesfully receive a delivery notification from a 365 group. Please kindly let me know. Thanks

**Comment by get-itips** [comment]
Hello @apanzalovic returning to check if you could read my last message. Thanks

**Comment by scanum** [comment]
@apanzalovic Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
