### ISSUE TITLE
Converting a Classic to a Modern Deployment

### ISSUE THREAD

**Issue by jreinhardtiv4** [MicrosoftDocs/OfficeDocs-Exchange#1756]
The note under Running setup that claims that the modern option is not presented when a classic deployment has already been deployed doesn't seem to be holding true for me. When a pre-existing Exchange 2010 Classic deployment is enabled and the wizard is run connecting to an Exchange 2016 server to upgrade the deployment to Exchange 2016, there is a request on whether to setup classic or modern hybrid. I'm not certain whether the article is wrong or not, but I do wonder if it needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#running-setup)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@jreinhardtiv4 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
