### ISSUE TITLE
GCC High availability?

### ISSUE THREAD

**Issue by rmaldon626** [MicrosoftDocs/OfficeDocs-Exchange#1757]
Great article! do we have any idea when google migration (Gmail) will be available on GCC High?

I could not find any information in the M365 RoadMap page: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Launched%2CWorldwide%20(Standard%20Multi-Tenant)

Thanks in advance

/RAF

**Comment by scanum** [comment]
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mattpennathe3rd** [comment]
This one was resolved after closure through internal email.
