### ISSUE TITLE
Wrong link for more info on Set-ClientAccessRule.

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Exchange#1762]
The link for - "For detailed syntax and parameter information, see Set-ClientAccessRule." goes to Set-Clutter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337b2115-1684-2259-5fb7-548cf4bfa7ee
* Version Independent ID: 0ca2abb6-2148-f085-5385-34ed580631e3
* Content: [Procedures for Client Access Rules in Exchange 2019](https://docs.microsoft.com/en-us/exchange/clients/client-access-rules/procedures-for-client-access-rules?view=exchserver-2019#use-the-exchange-management-shell-to-set-the-priority-of-client-access-rules)
* Content Source: [Exchange/ExchangeServer/clients/client-access-rules/procedures-for-client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/client-access-rules/procedures-for-client-access-rules.md)
* Service: **exchange-server-it-pro**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@GLComputing  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@GLComputing thank you for pointing this out and helping improve MS Docs. I'll have a look and get it sorted shortly.
