### ISSUE TITLE
Authentication types and protocols - The table has no data and formatting is off

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Exchange#1763]
As per subject

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e48342-ca51-4710-a47b-678ae06dbdc1
* Version Independent ID: cdf19120-9f92-2fe2-a4b7-2fb24072b8d1
* Content: [Client Access Rules in Exchange 2019](https://docs.microsoft.com/en-us/exchange/clients/client-access-rules/client-access-rules?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/client-access-rules/client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/client-access-rules/client-access-rules.md)
* Service: **exchange-server-it-pro**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@GLComputing I'm not seeing that here. The table is populated and displaying correctly in my browser.
