### ISSUE TITLE
WitnessServer is a mandatory parameter

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#1766]
Hello,

All the points about not having to specify the WitnessServer are false.  It is a mandatory parameter whether you use the GUI or PowerShell.  I'm talking Exchange 2016, CU 15.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c67924e-f4a7-d018-bd7a-7f52ff9fc418
* Version Independent ID: 7668d147-7bb5-b67c-7206-2be59ccd46da
* Content: [Create a database availability group](https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/create-dags?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/high-availability/manage-ha/create-dags.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/manage-ha/create-dags.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@JeremyTBradshaw  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @mattpennathe3rd 
I could verify that, on Exchange 2016, both the GUI and the Ps cmdlet won't let you continue without specifying Witness server.

EAC
![image](https://user-images.githubusercontent.com/36666927/76887643-55462c00-6861-11ea-9961-b0c31403153f.png)

PS
![image](https://user-images.githubusercontent.com/36666927/76887994-de5d6300-6861-11ea-8891-59d57f6e0aac.png)

Get-Help
![image](https://user-images.githubusercontent.com/36666927/76887797-8c1c4200-6861-11ea-877c-df4cb43658b7.png)

Do you think is worth it to clarify the article specifying that, in Exchange 2016, the Witness Server is a required parameter and this 

> If you leave this field blank, the system will attempt to automatically select an Exchange server with Client Access services that is in the local Active Directory site

Is not true in that case? I wasn't able to test this in Ex2019 yet...

**Comment by get-itips** [comment]
@mattpennathe3rd Matt, could you see my question? Thank you

**Comment by scanum** [comment]
Hi @msdmaguire! Could you please take a look at Andres's question? Thanks

**Comment by msdmaguire** [comment]
@get-itips The behavior will be the same in 2019, I know that much. Let me bring this to PG.
