### ISSUE TITLE
Breaking change in Phase 1 Step 6

### ISSUE THREAD

**Issue by jeremieweldin** [MicrosoftDocs/OfficeDocs-Exchange#1767]
WARNING: Breaking changes in the cmdlet 'New-AzVirtualNetworkSubnetConfig' :
WARNING:  - Update Property Name

WARNING: Cmdlet invocation changes :
 Old Way : -ResourceId
 New Way : -NatGatewayId
WARNING:  - Update Property Name

WARNING: Cmdlet invocation changes :
 Old Way : -InputObject
 New Way : -NatGateway
WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45c04a0-138f-8241-0726-01fb09c3dfeb
* Version Independent ID: 730303a8-9c6f-472c-79f6-96453dea3013
* Content: [Exchange dev/test environment in Azure](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@jeremieweldin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jeremieweldin Jeremie how are you?

The link that is included when running New-AzVirtualNetworkSubnetConfig says

> Breaking change warnings are a means for the cmdlet authors to communicate with the end users any upcoming breaking changes in the cmdlet. Most of these changes will be taking effect in the next breaking change release.

So it is notifying us that they will soon change some parameter names, however, the parameter names that will be changed are not being used in the step. (ResourceId or InputObject)

Thanks

**Comment by get-itips** [comment]
@scanum Manuela, I think we can now close this issue. Thanks
