### ISSUE TITLE
Still a bit confusing

### ISSUE THREAD

**Issue by upmyoung** [MicrosoftDocs/OfficeDocs-Exchange#1768]
Although it is much improved now. This topic suffers from the lack of overall documentation on the connection mechanism for each client type to Exchange Online, and the connection endpoints available in Exchange Online. Such documentation would allow customers to be clearer on how connections from MacOS-based Outlook are different from Windows-based Outlook, for instance.

I agree with the people who have said that it's necessary to read between the lines in order to be confident in what will happen when you execute 'Set-OrganizationConfig -OAuth2ClientProfileEnabled "$true"'.

And it's not clear at all why Windows-based Outlook 2013 and later would need this turned on, from this documentation. There are third-party sites that hint at what's going on, but Microsoft is silent on this.

So my vote would be to include more architectural discussion, and clarify the connection mechanisms for all clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@myoung-pugetsound-edu  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @mattpennathe3rd Matt 👍 Can you please step in here to review @myoung-pugetsound-edu suggestions? I appreciate.

**Comment by dariomws** [comment]
Hi @upmyoung, thank you for your feedback and help us to improve docs.microsoft.com.

Sorry for the delay. The last months this article has suffered a lot of updates. Do you still think that we need to update/improve it? In case your answer is yes, could you kindly provide more detail?

Thank you so much!

**Comment by scanum** [comment]
@upmyoung We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
