### ISSUE TITLE
Wrong calculations on page

### ISSUE THREAD

**Issue by pka23** [MicrosoftDocs/OfficeDocs-Exchange#1769]
1024\*1024 = 1048576 not 1048756
so example with 89478486 (64\*4/3\*1048756) not right too. The correct one 89478486 (64\*4/3\*1048576)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee5dfea-ce93-b800-b21c-1323559e17d0
* Version Independent ID: 458e568f-9bff-e24b-3395-77fa19734f71
* Content: [Configure client-specific message size limits: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/configure-client-specific-message-size-limits-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/configure-client-specific-message-size-limits-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-client-specific-message-size-limits-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@pka23  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @pka23 Thanks for that
