### ISSUE TITLE
Event type Sendexternal 

### ISSUE THREAD

**Issue by ondrejdrobilek** [MicrosoftDocs/OfficeDocs-Exchange#1771]
Hello, I miss here eventid send external, which is available on exchange 2016 on some earlier CU. On exchange 2019 is it present since beginning. Please check and update. Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a835d54-db8a-5c1c-a3f9-244e3a363475
* Version Independent ID: cc95465f-0969-7815-ff1e-243f3412e2a2
* Content: [Message tracking](https://docs.microsoft.com/en-us/exchange/mail-flow/transport-logs/message-tracking?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-logs/message-tracking.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-logs/message-tracking.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@ondrejdrobilek  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
