### ISSUE TITLE
How to check when a mailbox was put on inplace hold?

### ISSUE THREAD

**Issue by ii-batman** [MicrosoftDocs/OfficeDocs-Exchange#1772]
Hi Team, 
when running the new EXO commands, I can see that we can we have a "LitigationHoldDate" property but not a "InplaceHoldDate".
- Is there a way to find out when a mailbox was set InPlaceHold
- Is this something that can be added to Powershell ASAP?

I need to produce reports based on which mailbox is on hodld, when it was set, etc and not having this property for my hold it's really imparing my work flow.

Many thanks, ii

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f9f27d-572d-f259-cf1c-12697ddf6fcc
* Version Independent ID: 0875b460-4f28-a81f-3e4e-1f6af7ab0bd3
* Content: [Place a mailbox on Litigation Hold](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/holds/litigation-holds?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/holds/litigation-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/holds/litigation-holds.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@ii-batman  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ii-batman 👍 
I reviewed the properties of both the MailUser and MailboxSearchObject (Get-MailboxSearch) objects and could not find one property belonging to Creation date, the most approximate was MailboxSearchObject.LastModifiedTime

I would recommend submitting your request [here](https://office365.uservoice.com/)

Hope this info helps you.

**Comment by get-itips** [comment]
Hello @scanum Manuela, I think we can close this thread now, thank you

**Comment by mattpennathe3rd** [comment]
@ii-batman I've reached out to see if this functionality is hiding somewhere and will report back once I find out if this is something we can document. Thanks for opening this issue.

**Comment by scanum** [comment]
@ii-batman Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
