### ISSUE TITLE
Does the intro paragraph, last sentance make sense

### ISSUE THREAD

**Issue by wobblewobble** [MicrosoftDocs/OfficeDocs-Exchange#1773]
The Hybrid Agent supports free/busy and mailbox migrations; mail flow, directory synchronization, and other hybrid features are not included.

Not sure the value that the statement "and other hybrid features are not included" is correct. Or has something been missed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@wobblewobble  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @wobblewobble how are you? 👍 
To my understanding (I am not the author of the article) is clarifying that you have to leverage other tools to, for example accomplish directory sync or configure the mail flow between onpremises and online, does that makes more sense for you now? If I understood you correctly.

**Comment by wobblewobble** [comment]
Andres, for some reason I missed the semicolon and it makes sense now. apologies

**Comment by mattpennathe3rd** [comment]
@wobblewobble We appreciate the report, nonetheless! Let us know if you have trouble anywhere else in the docs.
