### ISSUE TITLE
Search-Mailbox appears to have been deprecated with documentation not properly on how to use its replacement.

### ISSUE THREAD

**Issue by Scaraban** [MicrosoftDocs/OfficeDocs-Exchange#1774]
Most resources now point towards using Compliance Search to perform this task but with no defined path towards doing so, only generic links to Compliance Search documentation. Referenced documentation offers no clear answer on how to perform the task defined on both this page and the "mailboxes on hold" version of page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c21112a-deb5-83b3-160e-0149a1e510f6
* Version Independent ID: 4edc9fcd-4971-470b-c56e-e1a2e78b8854
* Content: [Clean up or delete items from the Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/clean-up-deleted-items#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@Scaraban  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by markjjo** [comment]
@scaraban Thanks for the heads up about this article. Yes, Search-Mailbox is being retired on April 1, 2020, as per this article: https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?view=o365-worldwide#search-mailbox-cmdlet

To delete content, you will have to use *ComplianceSearch and *ComplianceSearchAction cmdlets as per this topic about using cmdlets for search and purge scenarios: https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide

You will have to configure your search query to return the the items in the recoverable items folder that you want to delete. 

You might also try to run the script in the topic below to get the folderid for the recoverable items folder and use the folderid:<value for recoverable items> property:value pair to narrow the search to the recoverable items folder. I haven't tried this, but it might be worth looking into.

https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide

**Comment by mattpennathe3rd** [comment]
@markjjo Is there a reason this issue was closed? If the article needs updating with this information, it should remain open so we know to address the problem.

**Comment by markjjo** [comment]
@Scaraban Just an FYI that the retirement of the Search-Mailbox cmdlet has been delayed until July 1, 2020. For more information, see: https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement
