### ISSUE TITLE
Add missing migration scenario

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#1775]
The section above and below this heading details supported scenarios. The best one is missing, public folders to o365 groups
https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-office-365-groups?view=exchserver-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd73dfc1-fa96-8d62-6504-e97ab046a738
* Version Independent ID: 658e73b8-3dfe-aeef-678d-5bb227d91ffa
* Content: [FAQ: Public folders](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/faq?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/faq.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by jonwbstr** [comment]
Oops, above and below this heading

"What are the supported public folder migration scenarios?"

**Comment by scanum** [comment]
@jonwbstr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
