### ISSUE TITLE
Include a Cloud Based e-mail delivery scenario

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-Exchange#1776]
I've recently worked a request where a cloud based mail service was sending as alias@domain.com to the same alias@domain.com inside Office 365. The issue it appears is that it is an illegal move (unsupported configuration) as there is no authentication to the account, and adding the service (mandrillapp.com) to the SPF and allowed senders domain was not enough to allow the e-mail to go through.

This article would be greatly improve if that scenario was added to this article with clear declarative statements that the above mentioned scenario is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 884ccdaf-c60f-293a-b7f7-b4edc559546c
* Version Independent ID: 6265a100-939a-75b3-d2ae-86798aaf79b4
* Content: [Manage mail flow using a third-party cloud service with Exchange Online and on-premises mailboxes](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Jmartinez589, thank you for your feedback and help us to improve docs.microsoft.com.

Maybe I don´t understand your scenario very well, but I think there is a configuration mistake here in the third-party cloud-based mail service. In this configuration, the third-party service is allowed to relay to Office 365 without double anti-spam check. If it´s configured in the right way, it must prevent sending from alias@domain.com to the same alias@domain.com.

Please, check also the following scenario and let me know if I´m not understanding you:
https://docs.microsoft.com/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud

**Comment by scanum** [comment]
@Jmartinez589 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
