### ISSUE TITLE
Access from local Outlook?

### ISSUE THREAD

**Issue by jeremieweldin** [MicrosoftDocs/OfficeDocs-Exchange#1777]
How would I adjust things to be able to test with Outlook? It would be sufficient to be able to install it on the exVM or adVM and be able to log in as either of the test accounts. I'm looking to be able to test Outlook AddIns against Exchange's Global Address List functionality. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45c04a0-138f-8241-0726-01fb09c3dfeb
* Version Independent ID: 730303a8-9c6f-472c-79f6-96453dea3013
* Content: [Exchange dev/test environment in Azure](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@jeremieweldin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by haflidif** [comment]
If you have a Visual Studio Pro / Enterprise subscription, you are able to deploy Windows 10 VM in Azure, you should be able to test local outlook from that computer if it's joined to your test domain.

**Comment by VLG17** [comment]
@jeremieweldin As mentioned above, you could create another VM (client) in the same subnet, install Outlook on this VM and test what's needed. Remember to [shutdown the VMs](https://docs.microsoft.com/en-us/azure/automation/automation-solution-vm-management) after testing, so you don't burn through all your Azure credit.

**Comment by dariomws** [comment]
@jeremieweldin Thank you for submitting feedback and contributing to the docs.

Despite that technically you can install Outlook (and even a domain controller) in the same box for testing purposes, it´s recommended that you deploy 3 boxes in this scenario:
- Domain Controller
- Exchange Server
- Windows client with Outlook
This way, you will reproduce a more realistic environment.

**Comment by scanum** [comment]
@jeremieweldin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
