### ISSUE TITLE
Uninstalling Hybrid Agent (Switching from Modern to Classic) Runs and Never Ends

### ISSUE THREAD

**Issue by mbenadiba** [MicrosoftDocs/OfficeDocs-Exchange#1783]
Hello
I have a very new Exchange 2019 organization and I have deployed Hybrid Modern in this organization.
I am looking to enable Hybrid Modern Authentication and I wish to switch to Classic.
I have followed the steps in this guide but the steps do not work.
The Uninstalling Hybrid Agent status window displays and never advances.
Is there some other step that must be taken to successfully complete the switch from Modern to Classic which is not documented in this article?

**Comment by scanum** [comment]
@mbenadiba thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
