### ISSUE TITLE
Re:Open of issue #327 (PowerShell and Exchange Online)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#1784]
I'm trying to get a clear answer on this.  For regular customers (i.e. not partners, not delegated admins, etc.) - if they disable Basic Authentication, is it really as simple as just not enabling MFA for their automation account and they will be able to continue using Basic Authentication even after October 13th 2020?

Or is there something else coming, similar to Secure App Model, but for regular customers, instead of just for Partners doing delegated admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@JeremyTBradshawthank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JeremyTBradshaw** [comment]
It's a real problem for all customers.  I'm not having an issue.  Wish I could just forcibly reopen this issue here.

Microsoft have announced that they will stop allowing basic authentication on October 13 2020.  They have yet to publish how to connect with modern authentication non-interactively , except for partners, who they have published info for.

It is similarly aggravating to how they publish articles on how to check your Azure AD Sign-Ins to see if you have any basic auth clients to worry about before October 13th, but then only AAD premium customers can use Sign-Ins.  Just this week they have now announced they'll give access to non-premium customers for 7 days of Sign-Ins data.  That's a start at least.

And now people are still scrambling about this EXO PowerShell scripts problem.  

So no, I won't go open a support ticket and instead I'll wait and see, disgruntled.

**Comment by mattpennathe3rd** [comment]
@JeremyTBradshaw The best I can do is refer you to better places to help address these questions. We don't currently have guidance that can be documented here.

I can refer you to some recent blog posts. Further news regarding your questions will most likely be posted there in the future, and then changes will trickle down to the docs, so please be sure to keep an eye on the blogs.

Check out this post, if you've not seen it already:

https://techcommunity.microsoft.com/t5/exchange-team-blog/faster-and-more-reliable-exchange-online-management-using/ba-p/1198604

I believe this post answers some your questions about basic auth, as well:

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282

**Comment by JeremyTBradshaw** [comment]
What timing for the second link, it was just posted yesterday!  That is how my luck works.  So I will change my approach - I'll now go wait and watch there for updates regarding the app-only topic they mentioned at the end.

Thanks.
