### ISSUE TITLE
Accessing the Discovery Mailbox

### ISSUE THREAD

**Issue by asampson68** [MicrosoftDocs/OfficeDocs-Exchange#1785]
Could you please add documentation indicating how one is supposed to add the Discovery Mailbox to an Outlook client so the copied results can be viewed? It's rather buried in the properties of an existing account, and I'm seeing some forums online indicating that it can be accessed through OWA but I've tried everything and can not find any method of doing so. I also cannot find any documentation about how to hide, or un-hide a manually created Discovery Mailbox from the GAL. I see some users saying that they WERE able to access theirs after un-hiding it from the GAL, but I can't find any option to do so. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a00e04-81bf-41e7-cc2b-457619050258
* Version Independent ID: a2e14849-b894-a630-2382-5fc69035bad3
* Content: [Copy eDiscovery search results to a discovery mailbox](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/ediscovery/copy-results-to-discovery-mailboxes?redirectedfrom=MSDN&view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/ediscovery/copy-results-to-discovery-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/ediscovery/copy-results-to-discovery-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@asampson68  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@asampson68 The recommended way of viewing the results is exporting them to a .pst file as mentioned in the article you provided and [described here](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/ediscovery/export-results-to-pst?view=exchserver-2019).

You could also open the Discovery Search Mailbox in Outlook, as described [in this article](https://docs.microsoft.com/en-us/previous-versions/exchange-server/exchangeserver-149/ff959692(v=exchsrvcs.149)?redirectedfrom=MSDN), which is quite old and not updated. Although giving yourself Full Access permissions on the Discovery Search Mailbox should do the trick to have it added to your mailbox via Automapping and visible within Outlook, i would not use this method but the documented and recommended one of exporting the results to .pst and afterwards importing the .pst file within Outlook and doing what's needed with the items.

**Comment by dariomws** [comment]
@asampson68 Thank you for submitting feedback and contributing to the docs.

You can find more update information in the following articles:
https://docs.microsoft.com/Exchange/create-a-discovery-mailbox-exchange-2013-help#step-2-assign-permissions-to-a-discovery-mailbox
https://docs.microsoft.com/exchange/security-and-compliance/in-place-ediscovery/create-a-discovery-mailbox#step-3-assign-permissions-to-a-discovery-mailbox

**Comment by scanum** [comment]
@asampson68 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
