### ISSUE TITLE
Authorization Method doesn't reference OAuth

### ISSUE THREAD

**Issue by cammurray** [MicrosoftDocs/OfficeDocs-Exchange#1789]
Autodiscover and Web Services in Exchange 2013 and above prefer OAuth for authentication over DAuth. This page only refers to WS-Security Authentication (DAuth).

Page probably needs to be updated. Also, if using OAuth, does the root EWS path (/ews/exchange.asmx) support pre-authentication? I assume the answer is no but this needs to be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@cammurray  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @cammurray, thank you for your feedback.

I will try to get more information to update this article. In the meantime, I think you've probably read the following article but just in case:
https://techcommunity.microsoft.com/t5/exchange-team-blog/deep-dive-how-hybrid-authentication-really-works/ba-p/606780

**Comment by scanum** [comment]
@cammurray Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
