### ISSUE TITLE
Batch scored as investigate - next steps

### ISSUE THREAD

**Issue by jackvdbuk** [MicrosoftDocs/OfficeDocs-Exchange#1790]
The article states that when receiving a DSC of investigate and how to proceed however there is no in between bit. Is there anything we can do to improve the DSC or improve the situation? should we be checking ACLs in a particular report? or just proceed and hope for the best like the article mentions how to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40bce01-0b1f-1952-5198-d5a15211b533
* Version Independent ID: 3f0ac568-cfbd-5255-d803-b7883c32c50f
* Content: [Track and Prevent Migration Data Loss](https://docs.microsoft.com/en-us/exchange/mailbox-migration/track-prevent-data-loss-dcs)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@jackvdbuk  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@jackvdbuk I think the [Exchange Team Blog](https://techcommunity.microsoft.com/t5/exchange-team-blog/improving-migrations-using-data-consistency-scoring/ba-p/1105920) can provide more context here:

> We’ve historically used a configurable parameter called the ‘Bad Item Limit’ to define the number of items that you, the admin, are okay with dropping during migrations. We allow the admin to use their discretion to set this bad item limit to as low or as high as they feel comfortable with. On the service side, we can see that many migrations hit a large number of ‘bad items’ **which are simply inconsistencies in metadata that the end-user may not even notice.** This then resulted in many admins running their migrations with a very high Bad Item Limit by default. The problem is that the current implementation has limited capabilities to alert the admin when there are bad items that the end-user will notice, or significant amounts of truly ‘bad items’.


Keeping in mind that you can view the DataConsistencyScore for your migration at a per-user level, you could try and check ACLs, Folder level permissions and any other things you could think of in your own environment, which could be unique and play a role and afterwards retry and see if it helps.

There is also the posibility of opening a support ticket and having support look into it, but as the article states, that should be used for cases where DataConsistencyScore = Poor.

In theory, to exclude data (mails) loss, you could do an item count using powershell and compare prior and after migration. Something like this:

**_get-mailbox | get-mailboxstatistics | ft displayname, totalitemsize, ItemCount_**

**Comment by scanum** [comment]
@jackvdbuk  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@jackvdbuk  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
