### ISSUE TITLE
Option 3 doesn't talk much about SMTP Relay authentication by Client Certificate

### ISSUE THREAD

**Issue by bauersystems** [MicrosoftDocs/OfficeDocs-Exchange#1792]
Option 3 focuses purely on the IP address sides of identification for connectors and completely ignores Client Certificates. When creating a connector, the Client Certificate method has the label of: "By verifying that the subject name on the certificate that the sending server uses to authenticate with Office 365 matches this domain name (recommended)". Considering it is the recommended method of identification, why is it not mentioned in the documentation?

I specifically ask because we have an app hosted in Azure App Services and we need to send emails from it as the user. Either saving the users email credentials or asking them to continuously add them is undesirable, so we opted for a connector. We managed to get the connector to work with Client Certificates, however cannot find any information about how to prevent emails sent through Client Certificate connectors from being marked as Junk/Spam. Do we need to assign a static IP address to the app and add it to the SPF record regardless of whether we are using Client Certificates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@bauersystems  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@bauersystems I went over this with one of our engineers and we've written a new section with a few more details on using certificates for relays. The updated article will be published in the near future. If the new article still doesn't cover what you need, please feel free to open a new issue.
