### ISSUE TITLE
Clairification

### ISSUE THREAD

**Issue by davehagel** [MicrosoftDocs/OfficeDocs-Exchange#1793]
Under the "Guidance for grades of Investigate or Poor" section you state:

If the migration receives a grade of Investigate, then you can approve skipped items manually to allow the migration to succeed.
If you are using batches, then run:
Set-MigrationBatch -ApproveSkippedItems or Set-MigrationUser -ApproveSkippedItems

Could you provide a full sample?  If I'm using batches, I assume I'd need to specify the name of the batch in the syntax somewhere.  An example of the full command to execute would be helpful.  I'm assuming "Set-MigrationBatch -Id batchname -ApproveSkippedItems ?????

Also in the "Migration and DataConsistencyScore" section you state that a rating of "poor" requires intervention from MS Support.  Please provide more information about what that looks like.  Is it simply opening a case with support and they force it through?  I'm assuming that it's just a powershell command that uses the old -acceptlargedataloss switch that gets it going again, and if so, why am I contacting support?  Just give the command and your cautionary statement.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40bce01-0b1f-1952-5198-d5a15211b533
* Version Independent ID: 3f0ac568-cfbd-5255-d803-b7883c32c50f
* Content: [Track and Prevent Migration Data Loss](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/track-prevent-data-loss-dcs#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@davehagel Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by davehagel** [comment]
Are you seriously responding to this more than 6 months after the post just to clear your queue?  You can disregard the post...at this point the migration has been complete for almost 6 months.  🤦‍♂️
