### ISSUE TITLE
Disable SafetyNet on Edge Server

### ISSUE THREAD

**Issue by gbordier** [MicrosoftDocs/OfficeDocs-Exchange#1794]
It looks like Edge Servers have safety net enabled by default. It seems we should either disable safetynet on edge by default or instruct administrators to disable it after installation. This could otherwise lead to safetynet queue database filling the underlying storage for no reason

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006ae2b1-446d-bf91-54ea-189d3203ff5f
* Version Independent ID: 07e36db2-e105-6ae9-ef1f-257eff033473
* Content: [Safety Net in Exchange Server](https://docs.microsoft.com/en-gb/exchange/mail-flow/transport-high-availability/safety-net?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-high-availability/safety-net.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-high-availability/safety-net.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@gbordier  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@gbordier I don't think the recommendation should be to disable SafetyNet on Edge Servers. If the mail.queue is growing too large, then we can leverage the **SafetyNetHoldTimeInterval** parameter.

One thing to keep in mind is [this issue](https://support.microsoft.com/en-au/help/3019650/safety-net-hold-time-settings-are-not-synced-to-exchange-server-2013-e), which could still apply to Exhhange 2016/2019: 

> The minimum value for the SafetyNetHoldTime parameter is two days, and the maximum value is 10 days. **If you set it lower than two days, the system will default back to seven days.**

> Even though the change is applied through the EdgeTransport.exe.config file, if you run the Get-TransportConfig cmdlet in Exchange Management Shell, it still reflects seven days as the SafetyNetHoldTime parameter.

> **To reduce the size of the mail.que file, make sure that you drain all the messages from the server, and then delete or re-create the Queue database**. To do this, see the How to drain messages from the server section in this article.

**Comment by gbordier** [comment]
I may be wrong but it seems SafetyNet does not actually do anything on edge servers.  quotiing for the documentation "Safety Net is designed to protect message delivery on Exchange Servers hosting end-user mailboxes. Customers who have deployed a hub and spoke routing topology should disable Safety Net on transport servers in hub sites to avoid a large growth in the size of the transport database in hub locations."  I fail to see how edge servers are different from hub transport servers in hub sites.
Guillaume

**Comment by VLG17** [comment]
@gbordier I think the confusion comes from the fact that you are refering to the **hub-and-spoke scenario**. [This article ](https://docs.microsoft.com/en-us/exchange/route-mail-between-active-directory-sites-exchange-2013-help#implementing-hub-sites) describes this scenario and what it involves. It's not about Edge servers, but more about how you design the mailflow and which servers in needs to go through. In this case, the transport servers in the hub site will handle a lot of traffic, so it makes sense to disable Safety Net on them, keeping in mind you have Safety Net enabled on the other transport servers involved, so you are safe in case of a transport failure.

According to [this article](https://docs.microsoft.com/en-us/exchange/mail-flow/queues/queues?view=exchserver-2019), we know that:

> **Queues exist in the Transport service on Mailbox servers and on Edge Transport servers**. Mailbox servers and Edge Transport servers are called transport servers throughout this topic.

So the same logic for SafetyNet functionality should apply also to Edge servers, right?

**Comment by gbordier** [comment]
Well, an exchange server in an hub site, without mailboxes is functionally really close to an edge server, from the doc I don’t see any added value of safety net on edge servers.

From what I understand SafetyNet without a mailbox server in range does not do anything except filling up disk space, so it should be disabled.

@Pascal L'Huriec<mailto:phuriec@microsoft.com>, @Didier Akakpo<mailto:didakakp@microsoft.com> do you concur ?
Thanks
Guillaume

**Comment by gbordier** [comment]
Hello,
Yes I agree. If there is no mailbox in the AD site, it is not useful to keep SafetyNet enabled. If you keep it enabled, that will fill the disk space, but SafetyNet will not help you for anything else.
If your AD site is dedicated to Message Relay you should disable SafetyNet on these servers. It’s written here:
https://docs.microsoft.com/en-us/Exchange/mail-flow/transport-high-availability/safety-net?view=exchserver-2019#safety-net-maximum-supported-sizes
It applies to Edge as well.

Hope that helps,
Pascal.

From: Guillaume Bordier <g_bordier@hotmail.com>
Sent: mardi 5 mai 2020 17:28
To: MicrosoftDocs/OfficeDocs-Exchange <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-Exchange <OfficeDocs-Exchange@noreply.github.com>; Didier Akakpo <didakakp@microsoft.com>; Pascal L'Huriec <phuriec@microsoft.com>
Cc: Mention <mention@noreply.github.com>; Guillaume Bordier <gbordier@microsoft.com>
Subject: [EXTERNAL] RE: [MicrosoftDocs/OfficeDocs-Exchange] Disable SafetyNet on Edge Server (#1794)

Well, an exchange server in an hub site, without mailboxes is functionally really close to an edge server, from the doc I don’t see any added value of safety net on edge servers.

From what I understand SafetyNet without a mailbox server in range does not do anything except filling up disk space, so it should be disabled.

@Pascal L'Huriec<mailto:phuriec@microsoft.com>, @Didier Akakpo<mailto:didakakp@microsoft.com> do you concur ?
Thanks
Guillaume

**Comment by VLG17** [comment]
@gbordier In this case, do you think adding a note to [this segment](https://docs.microsoft.com/en-gb/exchange/mail-flow/transport-high-availability/safety-net?view=exchserver-2016#safety-net-maximum-supported-sizes) like below would be enough?

**Note! 
Valid also for Edge Servers. (or something similar)**

Disabling it by default would need to be adressed via UserVoice in order for it to reach the Product Group.

**Comment by mattpennathe3rd** [comment]
@VLG17 These are MS employees, so I will handle this one from here. Thanks for all the follow up!

**Comment by dariomws** [comment]
Hi @gbordier and @VLG17, thank you for your comments.

From the same article:
"Safety Net is a queue that's associated with the Transport service on a Mailbox server"

Are you sure that Safety Net is available in Edge servers? Even if it seems to be enabled, are you sure that it's something that works in Edge server? Did you experience large mail queue DBs in Edge servers due to Safety Net?

**Comment by scanum** [comment]
@gbordier We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
