### ISSUE TITLE
Security defaults with Azure AD blocks App Password

### ISSUE THREAD

**Issue by John-D1** [MicrosoftDocs/OfficeDocs-Exchange#1799]
After enabling the Security defaults with Azure AD, all App Passwords were blocked thereby blocking SMTP relay option 1.

** App passwords are only available in per-user MFA with legacy authentication scenarios only if enabled by administrators.
https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-mfa-get-started

**Comment by scanum** [comment]
@John-D1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
