### ISSUE TITLE
$PfEndpoint = New-MigrationEndpoint -PublicFolder -Name PublicFolderEndpoint -RPCProxyServer $Source_OutlookAnywhereExternalHostName -Credentials $Source_Credential -SourceMailboxLegacyDN $Source_RemoteMailboxLegacyDN -PublicFolderDatabaseServerLegacyDN $Source_RemotePublicFolderServerLegacyDN -Authentication Basic 

### ISSUE THREAD

**Issue by VinodSP1980** [MicrosoftDocs/OfficeDocs-Exchange#1800]
The commandlet ask to use Basic authentication. But it fails if authentication is NTLM so we have to use as NTLM. please update the document with this information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@VinodSP1980 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@VinodSP1980 a note has been added above this cmdlet to adress that:

![image](https://user-images.githubusercontent.com/41186174/80793776-b8391b80-8ba0-11ea-8d62-23aa39ec07b6.png)

**Comment by mattpennathe3rd** [comment]
@VinodSP1980 Thanks for pointing this out. I believe this article has already been updated to address your issue, so I will close this now, but please feel free to comment back or to open a new issue if you run into any other problems with the documentation.
