### ISSUE TITLE
Does the default policy affect hybrid synced on-prem users?

### ISSUE THREAD

**Issue by p0shkar** [MicrosoftDocs/OfficeDocs-Exchange#1801]
So the topic "How Basic authentication is blocked in Exchange Online" provides an example where it is a Hybrid environment and the on-prem users does not exist in O365. In this case the on-prem user is understandably not affected by the authentication policy. 

However, what happens in the case where you have a Default Authentication Policy and a Hybrid environment syncs all on-prem users to O365 but does not migrate the mailbox for all users and only the Cloud users are assigned a license? Does the policy affect on-prem users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#filter-on-premises-active-directory-user-accounts-that-are-synchronized-to-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@p0shkar thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by VLG17** [comment]
@p0shkar A hybrid environment implies synchronized identities, and you have 3 options here: Password Hash Sync, Pass-through Authentication and Federation. The fact that the user mailbox still resides onpremises and was not migrated to the cloud does not change anything in terms of where it gets authenticated - either in the cloud (password hash sync) or onpremises (pass-through authentication and federation). 

So if you block basic authentication you are in one of the 2 scenarios described within the article, and in both cases the request will be blocked before it reaches Azure Active Directory or the onpremises Identity provider.

**Comment by dariomws** [comment]
Hi @p0shkar, thank you for your feedback.

Federated authentication scenario is not related to an Exchange hybrid environment, you can have it with or without Exchange hybrid. It´s when you have deployed AD FS (Azure AD connect is a requirement). In this case you, AD FS is your on-premises identity provider.
For more information, please see [Choose the right authentication method for your Azure Active Directory hybrid identity solution](https://docs.microsoft.com/azure/active-directory/hybrid/choose-ad-authn#federated-authentication) and [What is federation with Azure AD?](https://docs.microsoft.com/azure/active-directory/hybrid/whatis-fed).

In an Exchange hybrid deployment, you need to understand how autodiscover works: 
- Autodiscover points to your on-premises Exchange environment.
- If the mailbox is located on-premises, it will be authenticated on-premises and Exchange Online authentication policies won´t apply. 
- If the mail is located in Exchange Online, it will connect first to the autodiscover endpoint (located on-premises) and will be redirected to the Exchange Online autodiscover endpoint. Authentication policies will apply here.

**Comment by p0shkar** [comment]
Thank you both for the clarification, it is indeed a hybrid-adfs situation.

**Comment by dariomws** [comment]
You´re welcome @p0shkar. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

Also, if you need more information about how autodiscover works in an Exchange hybrid deployment you can check this old but useful article:
https://blogs.technet.microsoft.com/rmilne/2015/04/29/office-365-autodiscover-lookup-process/

**Comment by scanum** [comment]
@p0shkar Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
