### ISSUE TITLE
Step 8: Test and unlock the public folder migration-Missing Exchange 2016 cmdlet

### ISSUE THREAD

**Issue by QM-75** [MicrosoftDocs/OfficeDocs-Exchange#1802]
After point 5 in Step 8, there should be a cmd to set the Exchange 2016 Organisation to;
"Set-OrganizationConfig -PublicFoldersLockedForMigration:$False"
The default for Exchange 2016 is True. If this is left at True, emails sent to mail enabled public folders (MEPFs) fails. 
The other access to the Exchange 2016 public folders, such posting items, viewing the hierarchy etc is not affected by leaving the setting to True, so it is not an obvious first place to start troubleshooting.

Thanks

Alexis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6010593-c3e4-87a6-4084-27d56f23063c
* Version Independent ID: 32a2adeb-0932-3236-09d9-b7987393639b
* Content: [Use batch migration to migrate Exchange 2010 public folders to Exchange 2016](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/batch-migration-from-previous-versions?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@QM-75 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@QM-75 According to the [documentation for Set-OrganizationConfig](https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-organizationconfig?view=exchange-ps), **the default is $false**.

> The PublicFoldersLockedForMigration parameter specifies whether users are locked out from accessing down level public folder servers. When you set the PublicFoldersLockedForMigration parameter to $true, users are locked out from accessing down level public folder servers. This is used for public folder migration during final stages. **The default value is $false, which means that the user is able to access public folder servers.**

**Comment by mattpennathe3rd** [comment]
@QM-75 As mentioned above, the default is $false, so this should not have been set to to $true on your 2016 server. This was most likely something unique to your environment and should not affect others, so I will close this issue now. If you uncover any further issues in the docs, please feel free to open a new issue.

**Comment by QM-75** [comment]
Thank you for your updates and feed back on this. I have a few forthcoming similar migrations to do and will check this.
