### ISSUE TITLE
Please give clarity on IMAP and POP

### ISSUE THREAD

**Issue by janvanveldhuizen** [MicrosoftDocs/OfficeDocs-Exchange#1803]
I am trying to get clarity on IMAP and POP.
The messages are a quite contradictory. Some say: Microsoft is working on enabling OAuth with IMAP and POP. Others say: IMAP and POP will be disabled altogether. 
Who can I believe? I have to advice development teams on how they have to handle the upcoming changes.

**Comment by scanum** [comment]
@thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mattpennathe3rd** [comment]
@janvanveldhuizen I am not aware of any plans to eventually disable POP and IMAP. In terms of authentication plans, this is still a bit fluid, but I am actively working document this. Have a look at my comments on https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1562 for a little more detail and links to authoritative sources.
