### ISSUE TITLE
Is this article still relevant Since users are now hosted in Cloud Voicemail ?

### ISSUE THREAD

**Issue by rickleye** [MicrosoftDocs/OfficeDocs-Exchange#1806]
Seeking clarity if this article is relevant since UM has been decommissioned and voicemail now hosted in Cloud Voicemail. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 332316b2-6fd5-8428-db0b-a55708126696
* Version Independent ID: ad2015cc-423a-ffa3-0854-d83cf4c0976c
* Content: [Enable or disable multimedia playback of protected voice messages in Exchange Online](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-or-disable-multimedia-playback)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-or-disable-multimedia-playback.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-or-disable-multimedia-playback.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@rickleye Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@rickleye Your question is well timed! I'm already working on some major updates to all of this content because UM will be going away completely in the near future. UM is mentioned in many places in the docs, so this is a big job and it will take time, but the changes are coming soon.

**Comment by rickleye** [comment]
Thanks Matt for the update.
I totally understand the herculean task ahead. The Issue we face is that while we are informing clients of the change we are constantly having this and other docs slammed in our face while they are still up.

Regards

**Comment by mattpennathe3rd** [comment]
@rickleye Understood. I'll do what I can to move it along. I'm planning to have this mostly worked out in the next couple of weeks, if all goes well.

**Comment by rickleye** [comment]
Thanks 😊
