### ISSUE TITLE
winmail.dat file created for attachments not readable on Mac outlook

### ISSUE THREAD

**Issue by gmyershere** [MicrosoftDocs/OfficeDocs-Exchange#1818]
Finally found a solution that works. This blog entry has a registry edit solution that works on Outlook 360 and Win 10.  Its about halfway through the article.

https://blog.gimm.io/how-to-fix-winmail-dat-attachments-in-outlook/

**Comment by scanum** [comment]
@gmyershere thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
