### ISSUE TITLE
Cannot provision Mail Users

### ISSUE THREAD

**Issue by jblot** [MicrosoftDocs/OfficeDocs-Exchange#1820]
Hi,
We are currently using Gsuite and looking to Migrate to O365 Exchange Online (cloud only). 
We already add users provisioned in O365 for licensing Office Apps (O365 Business license).

I went through all the steps in that guide to prep for migration up until the "Provision users in O365". It appears that because I already have all my users created in O365 (but not in Exchange Online), I am unable to create Mail Users Contact as instructed. I tried through both EAC and Powershell (see command below) but get the same error (see below)

New-MailUser -Name "&lt;Display Name&gt;" -Alias &lt;Alias&gt; -ExternalEmailAddress &lt;Alias&gt;@gsuite.domain.com -FirstName &lt;First Name&gt; -LastName &lt;Last Name&gt; -MicrosoftOnlineServicesID &lt;Alias&gt;@domain.com -Password (ConvertTo-SecureString -String '&lt;Password&gt;' -AsPlainText -Force)

The proxy address "SMTP:&lt;email address&gt;" is already being used by the proxy addresses or LegacyExchangeDN. Please choose another proxy address.

Did anyone run into that issue ? Any idea appreciated !

Thanks!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@jblot thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Granty50** [comment]
jblot, did you get anywhere with this?  We're facing the same issue.   I would love to hear how this went.

**Comment by jblot** [comment]
Hi,

Unfortunately I had to delete all O365 user accounts I had created manually. Then when syncing them back through AzureADConnect, it created the Mail users contact properly.

[Logo]<https://totalnorth.ca/>
Julien Blot
IT Managed Services Manager
phone: (867) 668-5175<tel:+18676685175>
mobile: (867) 334-9774<tel:+18673349774>
email: jblot@totalnorth.ca<mailto:jblot@totalnorth.ca>
127 Copper Road<https://g.page/Total-North?share>
Whitehorse, YT Y1A 2Z7<https://g.page/Total-North?share>
[Youtbue icon]<https://www.youtube.com/channel/UCl6lAzm0M8ulk-5ayP1IIPw>  [Instagram icon] <https://www.instagram.com/totalnorthcom/>

________________________________
