### ISSUE TITLE
Create Mail Users not working

### ISSUE THREAD

**Issue by jblot** [MicrosoftDocs/OfficeDocs-Exchange#1821]
Hi,
We are currently using G Suite. Looking to migrate all our mailboxes to O365 Exchange online. I have followed all steps in https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration

At the "Provision users in O365" I am running into issues creating Mail Users. I have tried both from EAC and Powershell with command:

New-MailUser -Name "<Display Name>" -Alias <Alias> -ExternalEmailAddress <Alias>@gsuite.domain.com -FirstName <First Name> -LastName <Last Name> -MicrosoftOnlineServicesID <Alias>@domain.com -Password (ConvertTo-SecureString -String '[password]' -AsPlainText -Force)

But I am getting error:
The proxy address "SMTP:<Alias>@domain.com" is already being used by the proxy addresses or LegacyExchangeDN. Please choose another proxy address.

All my users were already created in O365 Admin center because we used that to license Office Apps (Business license) hence all users are already in Azure Directory (we are not using Azure AD connect, strictly cloud only).

Any ideas ?

Thanks

**Comment by scanum** [comment]
@jblot thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
