### ISSUE TITLE
Schedule Send/Receive interval missing

### ISSUE THREAD

**Issue by jfgoodhew1** [MicrosoftDocs/OfficeDocs-Exchange#1822]
If I set up send/receive every xx minutes, it works on my main inbox but I cannot select my shared mailboxes to send/receive under the account group. I would like to know how to schedule send/receive for the shared mailbox too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb78b621-ad88-04ad-c449-4d8c7e1b2d24
* Version Independent ID: 7259a9a9-4589-194e-5b9b-b32a807788d4
* Content: [Shared mailboxes](https://docs.microsoft.com/en-us/exchange/collaboration/shared-mailboxes/shared-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/collaboration/shared-mailboxes/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/shared-mailboxes/shared-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@jfgoodhew1 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by VLG17** [comment]
@jfgoodhew1 Are you testing with an on-premises mailbox which has an added shared mailbox also residing onpremises? What Exchange server version is it? Or are we talking about Exchange Online?

Did you try with other shared mailboxes (maybe a test one) just to check if it's not related to that specific shared mailbox?

As far as i know, there is no explicit option for shared mailboxes related to Send/Receive interval.

**Comment by jfgoodhew1** [comment]
Hello,

I don't know much about it, I just know we're all on Office 365 Business
Premium, and it's Exchange Online always updated because it's a 365 license.
We want that option, because we want to send emails to a shared mailbox
from our CRM to trigger VBA code / events. This inbox must be able to be
checked by other users.
The events are time-sensitive, so we can't really wait 5 minutes until
Outlook decides to send/receive on the shared mailbox.

What I've done as a workaround is created calendar events with reminders,
then when triggered it deletes the reminder and checks for emails, then
creates the next reminder.
This is not satisfactory since the reminders pop up in Outlook for all
users with access to that mailbox, and disabling the popup doesn't seem to
work.

I think I logged this as a suggestion on user voice, but can't remember for
sure.

James Goodhew

**Comment by VLG17** [comment]
@jfgoodhew1 thank you for your response. As far as i know, this option already exists, that's why i recommended to test with another shared mailbox (a new one would be best) to check if you can reproduce the issue or not (if not, then the problem comes from using that specific shared mailbox).

I would also recommend [reaching out to support](https://docs.microsoft.com/en-us/microsoft-365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=online), so they can check if this is a known issue or not and propose a solution.

**Comment by jfgoodhew1** [comment]
Hello.

You just told me in the email before this one:
"As far as i know, there is no explicit option for shared mailboxes related
to Send/Receive interval."
Now in this last email, you say:
"As far as i know, this option already exists"

I can't work with that kind of information, so I'm going to stop emailing
you and make sure it's on User Voice.

Thank you for your time and all the best.
James Goodhew

**Comment by VLG17** [comment]
@jfgoodhew1 I guess you misunderstood me. With 

> "As far as i know, there is no explicit option for shared mailboxes related to Send/Receive interval."

I meant there is no explicit box which you need to select in order for the change you do for Send/Receive interval to apply also for shared mailbox. It will apply automatically.

**Comment by jfgoodhew1** [comment]
That's fine, but it doesn't tell me which Send/Receive interval will
Outlook automatically apply. The one for the main Outlook user's account,
the one for the Outlook Profile currently in use, or a random one Microsoft
decides?

Ideally I want to specify 1min (or less) for the shared mailbox, but
currently there can be emails in the shared mailbox Exchange inbox that
don't come into the same inbox in Outlook for 4 minutes or longer. I know
that because I tested it with another machine both using the same Outlook
profile settings, same mailboxes open. I manually hit send/receive
regularly (every 5s) on one machine, and allowed the email to come into the
other automatically. The difference was sometimes as much as 4min in the
shared mailbox.

Thank you.

**Comment by VLG17** [comment]
@jfgoodhew1 Thank you for your answer and for taking the time to test this behavior. Let's see what the feedback from UserVoice is and afterwards let's check what needs to be added to the documentation.

**Comment by mattpennathe3rd** [comment]
@jfgoodhew1 This sounds like a problem with your mail client rather than Exchange Server. This GitHub repo is for documentation feedback on Exchange Server and Exchange Online and I'm unable to provide help with product support here (I'm only a technical writer).

I will close this issue now, but if you uncover something that we might be able to document for Exchange Server or Exchange Online, please feel free to open a new issue.
