### ISSUE TITLE
Hybrid permissions

### ISSUE THREAD

**Issue by RazvanB-MS** [MicrosoftDocs/OfficeDocs-Exchange#1823]
In the old article we also had permissions for account that was used by the endpoints in Hybrid environments. Here is the info we had :
"Remote move migration in Exchange hybrid deployments
For remote move migrations, the migration administrator account must be:
A member of the Domain Admins group in Active Directory in the on-premises organization.
Or
A member of the Exchange Recipients Administrators group in Active Directory in the on-premises organization.
Or
A member of the Organization Management or Recipient Management group in Exchange 2010 and Exchange 2013."

Is there a particular reason this info was removed ?

Thanks,
Razvan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72dbf30b-3824-aca2-0bc3-1978c73db56a
* Version Independent ID: 906cdc60-73a2-1b8d-a2c0-149f56c06069
* Content: [Assign Exchange permissions to migrate mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/assign-permissions-for-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/assign-permissions-for-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/assign-permissions-for-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@RazvanB-MS Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@RazvanB-MS Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
