### ISSUE TITLE
Missing Step for Performing Maintenance on DAG Members?

### ISSUE THREAD

**Issue by alexleach** [MicrosoftDocs/OfficeDocs-Exchange#1824]
Hi, I've found that when verifying that the cluster node is paused, it will always show as up.

`Get-ClusterNode &lt;ServerName&gt; | Format-List`

To ensure the cluster is paused, I have found the last step in 'To begin maintenance procedures on a DAG member' should be to run the following:-

`Get-ClusterNode &lt;ServerName&gt; | Suspend-ClusterNode`

Then, the first step when I'm 'ready to restore the DAG member to full production status', is to run:-

`Get-ClusterNode &lt;ServerName&gt; | Resume-ClusterNode`

Are these steps not recommended when performing maintenance on DAG members?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb3a712-50d2-74d9-b319-8900b6b01bae
* Version Independent ID: aa5f5c47-b8f0-f623-fb6e-a30eec11cee9
* Content: [Manage database availability groups](https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/manage-dags?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/high-availability/manage-ha/manage-dags.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/manage-ha/manage-dags.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@alexleach Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by richmcd** [comment]
The StartDAGServerMaintenance.ps1 script should pause the cluster node through the Call-ClusterExe cmdlet, but requires the "PauseClusterNode" switch to do so.  The StopDAGServerMaintenance.ps1 script attempts to resume the cluster node using Call-ClusterExe by default, which may display an error if the PauseClusterNode switch wasn't used when starting maintenenace or if the cluster node wasn't paused manually before running the stop script.

Suggest adding the PauseClusterNode switch to the StartDAGServerMaintenance.ps1 command in step 5 of the starting maintenance steps.

**Comment by mattpennathe3rd** [comment]
@richcmd Thank you very much for pointing this out. I will update the article right away.

@alexleach The comment by @richmcd seems to address your question in a very clear way, so I will add the missing switch to the article and it should solve your problem. Please feel free to comment back (or to open a new issue) if you have any other feedback on the article.

**Comment by alexleach** [comment]
@richmcd yes thanks for the tip, that seems like the solution here.

@mattpennathe3rd yes, richmcd's comment was indeed very clearly written, thanks. I wasn't aware of the switch, but tbh I am surprised that this isn't the default option. Surely, with a script named `startDAGServerMaintenance.ps1`, it is implied that we want to suspend the cluster on the server. Actually, on that point, there is a section in the article that says:

> The StartDagServerMaintenance.ps1 script performs the following tasks:
> [...]
> - Pauses the node in the cluster, which prevents the node from being and becoming the PAM.

I think it is worth clarifying in this point, that the `PauseClusterNode` switch is required.

On a more general comment, I have bookmarked this article as performing maintenance on Exchange servers is a fairly frequent task (new CU every 3 months, etc.). I personally think the whole section under: "To begin maintenance procedures on a DAG member" should have its own page, as before I'd bookmarked this page, I have found it quite hard to find this procedure.

**Comment by mattpennathe3rd** [comment]
@alexleach You are absolutely correct. I just realized how lengthy this article is, so it makes some sense to split it up, in any case. I will make a note to split out the maintenance procedure, but I'll also undertake a bigger review of this; it might make sense to split this into several articles with their own topics.

Thanks again for the great feedback. I was an Exchange admin some years ago, but I rely on input from admins currently in the field to make sure our docs are meeting their needs. It's very much appreciated!
