### ISSUE TITLE
PowerShell 7 side-by-side support?

### ISSUE THREAD

**Issue by shivtorov** [MicrosoftDocs/OfficeDocs-Exchange#1825]
There is a section "Windows PowerShell", and it says "If there are other installed versions of **Windows** PowerShell that support side-by-side operation, Exchange will use only the version that it requires."

Note: the above statement, only covers **Windows** PowerShell versions, but not mentioning at all PowerShell **Core** versions (6.x/7.x) installed side-by-side.

Could you please update the article and explicitly specify whether it is supported to have PowerShell 7 installed side-by-side on the server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#windows-powershell)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@shivtorov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
