### ISSUE TITLE
Missing source value "RESOLVER"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#1831]
I just happen to be wondering what this source is and means since I'm troubleshooting a message that was sent but where the sender claims they didn't actually send the message.  The first event (based on timestamp) is EventId "RECIPIENTINFO", from source "RESOLVER".  I guess my investigation ends here, woohoo, ha ha.  But seriously, any idea what "RESOLVER" for the source means?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a835d54-db8a-5c1c-a3f9-244e3a363475
* Version Independent ID: cc95465f-0969-7815-ff1e-243f3412e2a2
* Content: [Message tracking](https://docs.microsoft.com/en-us/exchange/mail-flow/transport-logs/message-tracking?view=exchserver-2019#source-values-in-the-message-tracking-log)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-logs/message-tracking.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-logs/message-tracking.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@JeremyTBradshaw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by VLG17** [comment]
@JeremyTBradshaw "**The component of the categorizer that's responsible for recipient resolution is frequently called _the resolver_.**" from [this article](https://docs.microsoft.com/en-us/exchange/mail-flow/mail-routing/recipient-resolution?view=exchserver-2019)

**Comment by JeremyTBradshaw** [comment]
@VLG17 thanks for the reference.  I could close this now with that, but will leave it to the mods in case there's any updating of this page worth doing.

**Comment by mattpennathe3rd** [comment]
@JeremyTBradshaw It looks like we can update this page with a couple of details on this. I'll follow up and see what can be done.

**Comment by mattpennathe3rd** [comment]
@scanum Can you reassign this one to get further details added to this article? Many thanks.
