### ISSUE TITLE
Whe should be We

### ISSUE THREAD

**Issue by jarogers-msft** [MicrosoftDocs/OfficeDocs-Exchange#1832]
Small typo.  "Whe" should be "We"

**Comment by scanum** [comment]
@jarogers-msft Please link documentation you are referring to.

**Comment by mattpennathe3rd** [comment]
@scanum I was able to track it down!

@jarogers-msft Thanks for pointing this out. I've submitted a PR to correct this and the updated article should be published in the near future.

**Comment by scanum** [comment]
Thanks @mattpennathe3rd !
