### ISSUE TITLE
2 Member DAG, lost quorum

### ISSUE THREAD

**Issue by redamaleki** [MicrosoftDocs/OfficeDocs-Exchange#1834]
Can you add a link here to the steps for bringing the quorum back online when " If a majority of the voters can't communicate with each other, the DAG's underlying cluster loses quorum, and the DAG will require administrator intervention to become operational again."?
The scenario in which a two member DAG (plus a fileshare witness), loses one member server that happened to have the most up to date copy of the data.  What is the process of getting the DAG operational while working on the downed server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63b8b93a-0f82-38c0-9546-a291aafceccc
* Version Independent ID: f5b63275-ecdf-9d2f-077f-bb20729ce9b4
* Content: [Database availability groups](https://docs.microsoft.com/en-us/Exchange/high-availability/database-availability-groups/database-availability-groups?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/high-availability/database-availability-groups/database-availability-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/database-availability-groups/database-availability-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@redamaleki  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@redamaleki Thank you for opening this issue! We've added some links that should help with your questions and the updated article will be published in the near future.

Thanks again for helping us improve the documentation. If you run into other problems with the docs in the future, please feel free to open a new issue.
