### ISSUE TITLE
Set-PopSettings command doesnt have switch called "identity" 

### ISSUE THREAD

**Issue by Madushka** [MicrosoftDocs/OfficeDocs-Exchange#1835]
Set-PopSettings command doesnt have switch called "identity"  it should be "Server"

**Comment by scanum** [comment]
@Madushka thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mattpennathe3rd** [comment]
@Madushka Sorry for the confusion on this issue.

You were correct. I found a handful of errors with this parameter in several articles in this repo and I have submitted fixes for all of them. They should be published in the near future.

Thank you very much for submitting this issue. We appreciate the feedback.
