### ISSUE TITLE
However, a maximum of 100 public folders is supported for migration from Exchange Server.

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/OfficeDocs-Exchange#1836]
However, a maximum of 100 public folders "mailboxes" is supported for migration from Exchange Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da991095-e3e4-6cc4-14ae-d98a0521a947
* Version Independent ID: c8552026-4fed-592a-3b66-446daac2df8d
* Content: [Exchange public folder migration, migrate public folders to Office 365, public folder migration Exchange to Office 365, migrate Exchange public folders to Microsoft 365](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-exchange-online.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@bakerm00 The purpose of this sentence is distinguish between the two. Public folders and public folder mailboxes are not the same; they have different limits when being migrated. Have I misunderstood your question?

**Comment by bakerm00** [comment]
yes - if you don't say public folder mailboxes - you are basically saying you can only migrate 100 public folders from onpremise to o365;   if you state public folder mailboxes you are declaring the limit the number of targets the synchronisation can handle (which is way below the service 1000 limit)

**Comment by mattpennathe3rd** [comment]
@bakerm00 "you are basically saying you can only migrate 100 public folders from onpremise to o365"

That is correct. 100 public folders is the supported limit for migrations (at least at this time). This point was just added on February 19th in response to another issue: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1613

I verified this limit with the Engineering team while working to update this content. Migrations of more than 100 public folders might or might not work and are not supported.

Again, if I'm misunderstanding, please follow up, but I am confident this particular point (if I'm understanding your question) is up to date.

**Comment by bakerm00** [comment]
so you have published a method that cannot be used in most environments? 10,000+ folders cannot work.   You need to provide direction in those scenarios - probably in table format to make it 100% clear

**Comment by bakerm00** [comment]
however, based upon #1613, i still think you are confusing the number of source public folders within hierarchy that contain data with the limits on number of PF storage mailboxes in o365.

**Comment by decturau** [comment]
@mattpennathe3rd I have this concern also. It looks as if this should be 100 Public Folder Mailboxes (Not public folder mailboxes) based on #1613?

**Comment by get-itips** [comment]
Hello everyone here,
The sentence has been updated to reflect the public folder _mailboxes_.
@scanum please close

**Comment by scanum** [comment]
@bakerm00  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
