### ISSUE TITLE
Uodate to monile version

### ISSUE THREAD

**Issue by sarahcocks** [MicrosoftDocs/OfficeDocs-Exchange#1838]
Hi all
There has been an update this month in outlook and since this you aren't able to approve microsoft exchange emails to an applicable distribution list. This now has to be done on PC only. Please can you reservse this or allow the update to approve requests
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9389be9-edde-da61-e370-7939c1d7cf4f
* Version Independent ID: 98df220c-0e27-9498-7cee-86d8ef0f91e5
* Content: [Manage message approval in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/manage-message-approval#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-message-approval.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-message-approval.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@sarahcocks thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
