### ISSUE TITLE
migrate Exchange 2013 to 2019

### ISSUE THREAD

**Issue by xuanhien1894** [MicrosoftDocs/OfficeDocs-Exchange#1839]
I want to upgrade the server from 2013 to 2119 and upgrade the server

**Comment by scanum** [comment]
@xuanhien1894 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
