### ISSUE TITLE
Choose server languages

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/OfficeDocs-Exchange#1840]
What are the pro and contra of choosing a server language other than English?
- Active Directory Language
- Hybrid Scenario
- Exchange Migration (other Exchange Server's Language)
- Default Mailbox Language
- Log Files (Log Management)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57930947-1fd2-b494-f00c-73499501bfd2
* Version Independent ID: 70917208-5b40-0f14-cd3a-dd502c229267
* Content: [Exchange Server language support](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deployment-ref/language-support?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deployment-ref/language-support.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deployment-ref/language-support.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@weyCC81 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
