### ISSUE TITLE
which region is used for device key and password operations  

### ISSUE THREAD

**Issue by sccmfan** [MicrosoftDocs/OfficeDocs-Exchange#1842]
can you please clarify:
- which region is used to process user password encryption/decryption and storage operation (is it the same rule as for synchronizing user data)?
- is it Azure data center or external?
- is it the same data center for iOS and Android devices?
- how is the username stored in the system?

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221571c5-0fc2-8087-2766-c34352167570
* Version Independent ID: 6c91bfa7-ea52-9afe-9a6f-c54fb038082c
* Content: [Passwords and security in Outlook for iOS and Android for Exchange Server](https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/passwords-and-security?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/passwords-and-security.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/passwords-and-security.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@sccmfan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @sccmfan, thank you for your feedback and sorry for the delay.

I'm almost sure the same rule/information you see here applies for password encryption/decryption and storage operation:
https://docs.microsoft.com/exchange/clients/outlook-for-ios-and-android/use-basic-auth

**Comment by dariomws** [comment]
@scanum this issue can be closed.
