### ISSUE TITLE
synchronized data location fro on-prem only

### ISSUE THREAD

**Issue by sccmfan** [MicrosoftDocs/OfficeDocs-Exchange#1843]
could you please clarify the location of synchronized user data when using Exchange on-premise only? is it also Outlook.com as in case of hybrid setup without HMA?

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b5db977-3944-f327-234e-bf5d84554542
* Version Independent ID: d4b39a70-960a-31e3-c586-2e48410e6164
* Content: [Using Basic authentication with Outlook for iOS and Android](https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/use-basic-auth?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-basic-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-basic-auth.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@sccmfan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @sccmfan, thank you for your feedback and help us to improve docs.microsoft.com.

Yes, I understand that for pure on-premises Exchange environments, data is store into Oulook.com too. Anyway, I'm double-checking.
