### ISSUE TITLE
is this scenario still supported after oct. 13 2020?

### ISSUE THREAD

**Issue by sccmfan** [MicrosoftDocs/OfficeDocs-Exchange#1844]
Could you please clarify if we can or cannot continue using Outlook app on iOS and Android devices to access on-premise only Exchange after Microsoft drops support for Basic auth in Exchange online on oct. 13 2020?

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b5db977-3944-f327-234e-bf5d84554542
* Version Independent ID: d4b39a70-960a-31e3-c586-2e48410e6164
* Content: [Using Basic authentication with Outlook for iOS and Android](https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/use-basic-auth?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-basic-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-basic-auth.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@sccmfan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@sccmfan Two items to note:

1. Disabling basic auth for IMAP and POP will not affect on-premises Exchange Server at all. This change only applies to Exchange Online.

2. This change has been delayed until the second half of 2021, as per [this blog post](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508) from a few days ago.

I will close this issue now, but please feel free to open a new issue if you find problems elsewhere in the documentation.
