### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by JimM1920** [MicrosoftDocs/OfficeDocs-Exchange#1845]
I've tried these instructions, which are not accurate, and I still can't authenticate the account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62f5860-4f99-6794-f8d6-2207b7f19979
* Version Independent ID: c28b87f8-1984-6522-021f-bae92e46d08c
* Content: [Prepare your Gmail or G Suite account for connecting to Outlook and Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@JimM1920 I'd be glad to help fix the article, but I need a bit more to go on. Where is the problem in the procedure?

**Comment by JimM1920** [comment]
I've tried to add the two step authentication, which I was finally able to find, and it doesn't appear to work.  I've just upgraded to Outlook 365, which pops up a box, but when I go to my phone and click on "It was me", the pop-up never clears.

**Comment by mattpennathe3rd** [comment]
@JimM1920 It sounds like this is a problem with Outlook, but this GitHub repo is only for documentation issues with Exchange Online and Exchange Server, so I am unable to help with this. Please contact support for help with your issue.

If you find that there are problems with the documentation, please open a new issue and I'd be glad to help address them.
