### ISSUE TITLE
Partner Domain Name??

### ISSUE THREAD

**Issue by darylzero** [MicrosoftDocs/OfficeDocs-Exchange#1848]
"Under Address space, click Add Add Icon. In the Add domain window, make sure SMTP is listed as the Type. For Fully Qualified Domain Name (FQDN), enter the name of your partner domain. Click Save."

What is the "Partner Domain"??  My domain?  my .onmicrosoft.com domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5352499b-cfcf-fa03-6e00-67ff30a19c27
* Version Independent ID: 49e84cba-5683-12a4-183b-0dcc0e2687f2
* Content: [Create a Send connector to send email to a partner, with Transport Layer Security applied](https://docs.microsoft.com/en-us/exchange/create-a-send-connector-to-send-email-to-a-partner-with-transport-layer-security-tls-applied-exchange-2013-help?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeServer2013/create-a-send-connector-to-send-email-to-a-partner-with-transport-layer-security-tls-applied-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/create-a-send-connector-to-send-email-to-a-partner-with-transport-layer-security-tls-applied-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@darylzero Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@darylzero This article explains how to set up a send connector to a partner domain. A partner domain is the domain that belongs to an organization you communicate with and with whom you want to enforce security restrictions.

Is there something about the article that is not clear?

**Comment by mattpennathe3rd** [comment]
@darylzero I'm going to assume that you are all set and worked through your problem. Please feel free to open a new issue if you have further feedback on the documentation.
