### ISSUE TITLE
Clarification on personal contact support in Outlook and GAL contact support in OWA with free busy

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-Exchange#1849]
1) Need to add comment or clarification for customers that the step documented are although enough for setting up org relationship between two tenants, when using Outlook, personal contacts are not supported for free busy lookup and only GAL contacts would work.

Related work item-
Bug 3912768: Issue Severity: 2 HOTFIX: [JPN] Personal Outlook contact no longer works in Outlook for free busy sharing

2) Further with , OWA, org relationship is not enough for free busy lookup and adding calendar ie OWA does not support neither personal contact nor GAL contact

Related work item
Issue 1426155: [Customer Escalation] Issue Severity: 2 Online: [JPN] Cross tenant external Calendar added for free busy sharing disappears with browser is refreshed in OWA

**Comment by scanum** [comment]
@qaehtesh Please link the documentation you are referring to. Thanks!

**Comment by qaehtesh** [comment]
Article in question is as below - 
This provides step by step guidance on enabling free busy between two different tenant and it's pre-requisite however does not tell what would work or not work from client side such as OWA and Outlook so adding above would help customer to have one stop shop when they performing this in their tenant.

Enable Free/Busy information between the Office 365 users from two different tenants, when the Autodiscover of one of them is pointing On-Premise

https://docs.microsoft.com/en-us/archive/blogs/ehlro/enable-freebusy-information-between-the-office-365-users-from-two-different-tenants-when-the-autodiscover-of-one-of-them-is-pointing-on-premise

**Comment by mattpennathe3rd** [comment]
@qaehtesh You've linked to an old blog posting. These are never updated.

The only documentation I can assist with are the articles posted in this GitHub repo. Does your question apply to one of these articles? I do not have easy access to the bug databases, so if you find holes in any of the existing documentation, please click the Edit button at the top right of any article in which you find problems and submit a fix (or open an issue on that specific article by using the feedback form at the bottom of that article's page).

You can also contact me internally if you need to discuss. I'm happy to help with any areas that I am able to, or I will try to refer you to the best contact for the problem.
