### ISSUE TITLE
invalid character

### ISSUE THREAD

**Issue by hakimtaoussi** [MicrosoftDocs/OfficeDocs-Exchange#185]
Hi,
Could you remove the "`" character please?
=&gt; Install-WindowsFeature Server-Media-Foundation`
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prerequisites?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hakimtaoussi I removed the trailing \` from `Install-WindowsFeature Server-Media-Foundation`. It was difficult to see.

Thanks for the feedback.
