### ISSUE TITLE
Only allow admin managed addins

### ISSUE THREAD

**Issue by andreaslarssonliu** [MicrosoftDocs/OfficeDocs-Exchange#1850]
Before this change was done, you were able to only allow addins that the admin has made available. 
How would we achive this setting again?

As now right now we are forced to block users from adding addins, as legally we cant allow users from downloading any app they want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86c9e05-c68b-8f00-3a94-c902d3352590
* Version Independent ID: e299bde7-ee34-96eb-b7f3-2ae75db017d3
* Content: [Specify the administrators and users who can install and manage add-ins for Outlook](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@andreaslarssonliu Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by gp92** [comment]
Have the same problem. It would be nice to restore this settings again and permit only admin-managed addins

**Comment by andreaslarssonliu** [comment]
If you in the exchange roles prevent users from customizing their addons (there is a checkbox for that). After that is done users should be able to add addons in owa (that are published by the admin), and those addons will be synced to the office365 client on the computer. However, this causes the "addons" option in outlook to stop working. Its a workaround, so if they dont come up with anything better that might be your only choice.

**Comment by gp92** [comment]
this is my current situation in Exchange user roles:
![image](https://user-images.githubusercontent.com/5497444/78789910-1150cd80-79ae-11ea-8e3f-c8603129c160.png)
Also in this case I still have the option on my outlook client to add non-admin managed addins

**Comment by andreaslarssonliu** [comment]
We have the same settings, unsure why it works for us, are you certain that the user you are testing with is assigned with that role.

**Comment by gp92** [comment]
Yes, I checked the role assignment policy of the user and it contains the policy with my custom settings as showed in the image attached above

**Comment by mattpennathe3rd** [comment]
@andreaslarssonliu @gp92 I'd love to help, but this sounds more like a product issue than a documentation issue. I'm only able to help with docs problems in this repo. Was there a specific change in this article that you're referring to?

**Comment by andreaslarssonliu** [comment]
@mattpennathe3rd , well there was documentation for how to define what we are discussing, then microsoft decided that this no longer applies for Outlook and there is no longer any documentation on how to achieve this, so I would say this is very much a document issue.

**Comment by mattpennathe3rd** [comment]
@andreaslarssonliu I'm sorry, but can you tell me what documentation you are referring to? I checked the history of this article and I cannot see that anything substantive has been removed (at least not for over a year).

If there is something missing or that was removed incorrectly (whether from this article or from another), please point it out to me and I will look into it.

**Comment by andreaslarssonliu** [comment]
Hello again to clarify, how to managed addins are described here: https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide

This was concerning Outlook as well, then Microsoft decided that Outlook will work another way. But its no longer documented on how to properly manage addons.

Do you see the problem? There has not been a change in this page, this page is missing information that is accessible from the other site, if you are to change how something work, you cant just stop documenting how to preform certain tasks.

**Comment by nitzdaniel** [comment]
Same Problem here. We have now a situation where we have the same situation but somes users are still able to add Addins and others are blocked correctly. Our scenario looks like this: We want to prevent users from installing apps unless they have been approved by an Administrator.

> this is my current situation in Exchange user roles:
> ![image](https://user-images.githubusercontent.com/5497444/78789910-1150cd80-79ae-11ea-8e3f-c8603129c160.png)
> Also in this case I still have the option on my outlook client to add non-admin managed addins

**Comment by mattpennathe3rd** [comment]
@andreaslarssonliu @gp92 @nitzdaniel I have reached out to some of my contacts to see if we can figure out what's happening here. I will report back. Thanks for all the details!

**Comment by mattpennathe3rd** [comment]
@andreaslarssonliu @gp92 @nitzdaniel I have reviewed this several times and I am sorry to say that I still do not clearly understand the problem.

The page that was linked in one of the comments explains [how to manage deployment of Office add-ins](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins), but there is a note on that page explaining that, "Outlook add-in installation is managed by a different process." That note then links to [this page](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins), which this GitHub issue has been opened on.

What information is missing or incorrect from the procedures on this article? It sounds like these procedures are working for some who have commented on this issue, so if there are problems with this article, please let me know what they are.

If you are seeing unexpected behavior in your tenant, then that is something you should raise in a support ticket.

**Comment by andreaslarssonliu** [comment]
Before Outlook was not handled by a different process. So before this change we had documentation.
But after the change we stopped having documentation as this document does not explain how to properly manage add ins.

That is the problem, its not a bug its missing documentation.

**Comment by mattpennathe3rd** [comment]
@andreaslarssonliu Now I'm seeing where the problem is. Thanks for clarifying.

It will take some time to address this and write the missing content, but I will report back.

**Comment by nitzdaniel** [comment]
Are we speaking about the same issue? So I basically need a documentation how to restrict apps that users can add only apps approved by the administrator. Today here is no documentation that explains this use case.
Are we on the same page?

**Comment by nitzdaniel** [comment]
Any Updates @mattpennathe3rd ?

**Comment by alexcher84** [comment]
Hi there, this guide is not very clear. I think I figured out the steps required, but would like to confirm.

Can you please provide step by step instructions on what exactly needs to be done to prevent users from being able to install Add-Ins for the Windows Outlook applications? 

For example:

1. Login to EAC as Global Admin (or an account that is at least an Exchange Admin)
2. Navigate to Permissions / User Roles and create a new Policy, giving it a name such as "Default Role with Add-Ins Management" 
3. Enable ALL roles within this new policy
3. Modify "Default Role Assignment Policy" by deselecting My Custom Apps, My MarketPlace Apps and My ReadWriteMailbox Apps. Doing this, all existing users with the default policy will no longer be able to install or manage Add-Ins for Outlook.

Are the above steps accurate? Will removing these 3 roles accomplish what we are looking for?

Also, please confirm whether this will also cover add-ins installed within Outlook on the Web (OWA), which as far as I understand is handled through a different process outlined below (as mentioned here:https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide):

1. In the admin center, go to the Settings > Services & add-ins page.
2. Select User owned apps and services.
3. Clear the option to let users access the Office store.


Thank you,
Alex

**Comment by nitzdaniel** [comment]
Hey @alexcher84 ,

we already configured the policy like this but not all users are blocked even if all have the Default policy assigned. Any idea?

![image](https://user-images.githubusercontent.com/21982714/81539850-17e9b080-9371-11ea-83d5-ae3df884fbc3.png)

**Comment by alexcher84** [comment]
Bitzdaniel,

It took about 24 hours, but it looks like Outlook Add-Ons installation
appears to have been blocked now.

Have you had a chance to test again since last time?

**Comment by nitzdaniel** [comment]
Yes @alexcher84 No change. For some users it works, for some not. But we set it up exactly as discussed here.

**Comment by msdmaguire** [comment]
Thanks everyone for your input. I am adding steps for how to prevent Outlook add-in downloads by turning off the Office Store across Outlook to this article.
