### ISSUE TITLE
Can an Active Directory Group automatically update to an auth policy?

### ISSUE THREAD

**Issue by AMagee-BJC** [MicrosoftDocs/OfficeDocs-Exchange#1854]
The description here is using the group membership to find and update the members. It appears to be a one-time setting the auth policy for those users. How would you recommend having the group membership (for example a group that is provisioned during the onboarding process for a particular department) cause the auth policy to be assigned to that user? The process here seems static - I'm looking for dynamic. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@AMagee-BJC Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@AMagee-BJC I looked into this with the team and verified that there is no way to do this dynamically. Your options are to create a PowerShell script to loop through a list of users, or have a tenant-level default policy which applies to all users who don’t have user-level policies.

I hope that's helpful to you. I'm not sure there's anything I can add to the article, so I will close this issue now, but please follow up or open another issue if you find any other problem areas in the documentation.
