### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#1858]
"Assign delegate permission via PowerShell: Updates to the Add-FolderPermissions cmdlet so administrators can assign delegate permissions."

This parameter is available only in the cloud-based service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9adfb815-bc64-46f2-97df-ff9af957e7cf
* Version Independent ID: 9e1758f6-118a-5d01-edff-8d9638719de5
* Content: [What's new in Exchange Server](https://docs.microsoft.com/en-us/Exchange/new-features/new-features?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/new-features/new-features.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/new-features.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@trudolf-msft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@trudolf-msft Thanks very much for the correction! I will make sure this line is removed.
