### ISSUE TITLE
Hybrid Exchange 2019 on Azure VM

### ISSUE THREAD

**Issue by cubspsycho85** [MicrosoftDocs/OfficeDocs-Exchange#1859]
Having a hard time finding any MS official documentation about running an Exchange 2019 Hybrid VM in Azure. We have no user mailboxes left in our onprem org, and only the system mailboxes. We would like to move to 1 hybrid server, only in Azure. I know how to set it up, but want to make sure it's supported. Thanks!

**Comment by scanum** [comment]
@cubspsycho85 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cubspsycho85** [comment]
I have done this previously, stating the reason it's not documented (that I
can find), and they said I couldn't open a ticket for an advisory inquiry.
