### ISSUE TITLE
ADFS fallback

### ISSUE THREAD

**Issue by amdf777** [MicrosoftDocs/OfficeDocs-Exchange#1860]
There is next Note in this article:

> In the event AD FS can't connect to your on-premises Active Directory for any reason, clients will attempt to fall back and authenticate against usernames and passwords synchronized to Office 365.

Which is simply false. if ADFS goes down, authentication simply times out because ADFS is unreachable. You can manually switch domain from federated to managed domain, but it require manual steps and take time.

**Comment by scanum** [comment]
@amdf777 Thank you for submitting feedback. Could you please link the documentation you are referring to? Thanks!

**Comment by amdf777** [comment]
> @amdf777 Thank you for submitting feedback. Could you please link the documentation you are referring to? Thanks!
Here it is:
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/tutorial-phs-backup

**Comment by mattpennathe3rd** [comment]
@amdf777 Thanks very much for pointing this out. I've corrected this note in a pull request and it should be published in the near future. Thank you again for helping to improve the docs!
