### ISSUE TITLE
Does enabling this feature force all users to re-authenticate?

### ISSUE THREAD

**Issue by kabadisha** [MicrosoftDocs/OfficeDocs-Exchange#1861]
We are looking to enable this feature on our tenant, but I can't find anything in the documentation (or anywhere else) about whether or not this will trigger re-authentication for all users (or at least Windows users) at the point we turn it on. My guess is no, but would be good to have that confirmed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-US/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@kabadisha thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by corykenedy** [comment]
@kabadisha, want to enable this for my tenant but not sure what to expect. Did you enable this and did you have any issues with users authenticating or using legacy MFA passcodes?

**Comment by mattpennathe3rd** [comment]
@kabadisha Thanks for opening this issue. I've reached out for some clarification from those more in the know on this question and I will report back soon.

**Comment by mattpennathe3rd** [comment]
@kabadisha @corykenedy I double checked this and your users will be asked to re-authenticate (both Windows and Mac clients). The authentication dialog box also looks different from the basic auth dialog box. Check [this blog post](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282) and do a Find on the page for "modern auth dialog" and you will see screenshots showing the differences, so if you expect concern from your users at seeing a different dialog box, perhaps you can forewarn them with visual aids.

Note that I am assuming your Outlook clients support modern auth. If the clients are very old and don't support modern auth, the user will get stuck in a password prompts loop.

I'll look into adding some of this to this article for clarification. Thanks for opening this issue.

**Comment by kabadisha** [comment]
Thanks Matt,

We actually scheduled a change to turn this on today. Hopefully the service desk doesn't get swamped with people who have forgotten their password. 
Will report back on how it went and any issues for posterity.

Thanks for following this one up though :-)

**Comment by kabadisha** [comment]
For anyone who finds this thread, we enabled this feature on our tenant (approx 2000 users) and found no issues. Users were not signed out. In fact, nobody noticed anything.

**Comment by mattpennathe3rd** [comment]
@kabadisha Thanks for reporting back. Can you share which clients your users are using to connect?

**Comment by kabadisha** [comment]
We've got a bit of a mixed bag, all modern clients though, we've managed to keep most people up to date.
Mostly Windows users (all Win 10) with some Mac users (myself included). I think all office clients are version 2016 and above.

**Comment by kabadisha** [comment]
Final follow-up on this for anyone who finds this thread.
We did have some issues with some users who were using the native mail client on old iOS devices. These did not support 2FA, so we have had to upgrade these users or use an app specific password. Not a biggie tho, just one to watch out for.
