### ISSUE TITLE
The article should be corrected

### ISSUE THREAD

**Issue by thorstd** [MicrosoftDocs/OfficeDocs-Exchange#1862]
According to the article:

&gt; A recipient is considered to be outside the organization if either of the following conditions is true:
&gt; • The recipient's email address isn't in an accepted domain.
&gt; • The recipient's email address is in an accepted domain that's configured as an external relay domain.

If there is a remote domain for the recipient is considered as outside the organization ONLY IF the property IsInternal of the remote domain is not set to $true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65cb383c-bd27-940b-9cd5-48052d34076a
* Version Independent ID: e9e33e90-b9b9-a44c-6976-7d32cd003543
* Content: [Mail flow rule conditions and exceptions (predicates) in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mail-flow-rules/conditions-and-exceptions?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/conditions-and-exceptions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/conditions-and-exceptions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@thorstd  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msdmaguire** [comment]
@thorstd Sorry for the delay and thank you for your patience. Can you clarify the change you are requesting please? Are you saying that the first bullet you quote is correct, but the second one should be replaced with verbiage to the effect of (your comment): "If there is a remote domain for the recipient is considered as outside the organization ONLY IF the property IsInternal of the remote domain is not set to $true"?

Or would this be an additional, third condition in which a recipient is considered external?

**Comment by thorstd** [comment]
Hello David,

> Are you saying that the first bullet you quote is correct,

No, I'm not. Let me try to put it this way:

The recipient is considered to be outside the org if:

The recipient's email address isn't in an accepted domain AND it's not in a remote domain for which the property IsInternal is set to true

OR

The recipient's email address is in an accepted domain that's configured as an external relay domain.

Thorsten

Von: David Maguire <notifications@github.com>
Gesendet: Mittwoch, 5. August 2020 18:25
An: MicrosoftDocs/OfficeDocs-Exchange <OfficeDocs-Exchange@noreply.github.com>
Cc: Thorsten Dietrichkeit <Thorsten.Dietrichkeit@microsoft.com>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/OfficeDocs-Exchange] The article should be corrected (#1862)


@thorstd<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthorstd&data=02%7C01%7CThorsten.Dietrichkeit%40microsoft.com%7Ceab69fe79f3d4547887b08d8395c2322%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637322415174718522&sdata=VBA3EEEVgxWns7yK0faiLBOFyxZaYLsa35xgkhJE0Ag%3D&reserved=0> Sorry for the delay and thank you for your patience. Can you clarify the change you are requesting please? Are you saying that the first bullet you quote is correct, but the second one should be replaced with verbiage to the effect of (your comment): "If there is a remote domain for the recipient is considered as outside the organization ONLY IF the property IsInternal of the remote domain is not set to $true"?

Or would this be an additional, third condition in which a recipient is considered external?

**Comment by msdmaguire** [comment]
@thorstd Thank you for clarifying. I have updated the article accordingly. We appreciate your feedback.
