### ISSUE TITLE
Rollback step missing

### ISSUE THREAD

**Issue by luebberm** [MicrosoftDocs/OfficeDocs-Exchange#1863]
If the mailboxes are migrated to Exchange 2016, you will need to run the following on an Exchange 2016 server to point the users back to Exchange 2010 to access the public folders.
  Set-OrganizationConfig -PublicFoldersEnabled Remote -RemotePublicFolderMailboxes PFDiscoveryMbx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6010593-c3e4-87a6-4084-27d56f23063c
* Version Independent ID: 32a2adeb-0932-3236-09d9-b7987393639b
* Content: [Use batch migration to migrate Exchange 2010 public folders to Exchange 2016](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/batch-migration-from-previous-versions?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@luebberm  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
