### ISSUE TITLE
broken URL

### ISSUE THREAD

**Issue by SultanRayes** [MicrosoftDocs/OfficeDocs-Exchange#1865]
The URL : Choose the right authentication method for your Azure Active Directory hybrid identity solution. is not found !!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50117f9a-45dd-90fb-a592-6a12c6104875
* Version Independent ID: d07fe199-59af-86bf-fe79-c7e2d342a463
* Content: [Single sign-on with hybrid deployments](https://docs.microsoft.com/en-us/Exchange/single-sign-on#feedback)
* Content Source: [Exchange/ExchangeHybrid/single-sign-on.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/single-sign-on.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@SultanRayes  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@SultanRayes Thank you for pointing this out! I have submitted a fix and the updated version will be published in the near future.
