### ISSUE TITLE
Ex 2019 CU5 Download

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Exchange#1866]
Is there a link for this for those not on VLSC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf984bf-df1c-bcd5-6475-54b9ef24fe74
* Version Independent ID: 00547ab9-7b3b-f6b0-fa7f-429f5e2bea56
* Content: [Exchange Server build numbers and release dates](https://docs.microsoft.com/en-us/Exchange/new-features/build-numbers-and-release-dates?redirectedfrom=MSDN&view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@GLComputing  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@GLComputing The only other way to download CUs is through the Visual Studios Subscriptions site. Do you have a use case where this doesn't work for you?

**Comment by GLComputing** [comment]
I found the full ISO on the Partner site. I assume this will work as an upgrade?

**Comment by mattpennathe3rd** [comment]
@GLComputing I'm sorry, but I'm not certain what you've downloaded, so I can't answer definitively. 

The CUs themselves are full installers and are usable as first-time installs or as upgrades of an existing server, but according to the support person I pinged, they are only obtainable through VLSC or the Visual Studios Subscriptions site; they are not distributed through any other channels.
