### ISSUE TITLE
Section 3 is incorrect

### ISSUE THREAD

**Issue by i-windows** [MicrosoftDocs/OfficeDocs-Exchange#1867]
Section 3 needs to be run on an exchange server, and cannot be run remotely as the certificate is stored in the cert store on the servers, and therefore to export the cert you must run the script on the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484887bf-a423-cb36-d8d1-712858e746bb
* Version Independent ID: c1df772a-5b5c-79d0-24fc-c89a09059497
* Content: [Configure OAuth authentication between Exchange and Exchange Online](https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by i-windows** [comment]
also if you use MFA to exhange online then section 7
$UserCredential = Get-Credential
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
Import-PSSession $Session

is incorrect, you should use Connect-EXOPSSession from the exchange online powershell

**Comment by scanum** [comment]
@i-windows  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
