### ISSUE TITLE
HCW IntraOrganizationConnector

### ISSUE THREAD

**Issue by pbreitenberger** [MicrosoftDocs/OfficeDocs-Exchange#1869]
This part is not needed if HCW was already done:

$ServiceDomain = Get-AcceptedDomain | where {$_.DomainName -like "*.mail.onmicrosoft.com"} | select -ExpandProperty Name
New-IntraOrganizationConnector -name ExchangeHybridOnPremisesToOnline -DiscoveryEndpoint https://outlook.office365.com/autodiscover/autodiscover.svc -TargetAddressDomains $ServiceDomain

There should already be an existing IntraOrganizationConnector

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484887bf-a423-cb36-d8d1-712858e746bb
* Version Independent ID: c1df772a-5b5c-79d0-24fc-c89a09059497
* Content: [Configure OAuth authentication between Exchange and Exchange Online](https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help?redirectedfrom=MSDN#feedback)
* Content Source: [Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@pbreitenberger  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @pbreitenberger, thank you for your feedback.

Really, you don´t need to run these steps if you run the HCW. From the article:
"If your on-premises organization is running only Exchange 2013 servers with Cumulative Update 5 or later installed, run the Hybrid Deployment Wizard instead of performing the steps in this topic."

The same applies for Exchange 2016 and 2019.

**Comment by scanum** [comment]
@pbreitenberger Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
