### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by asampson68** [MicrosoftDocs/OfficeDocs-Exchange#1871]
I believe there is a typo in your first example on this page, the -AddressLists parameter of the Set-OfflineAddressBook cmdlet contains a space between "Address" and "Lists". Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b904aaa3-52bb-1fee-df91-ae0e6592db4f
* Version Independent ID: a0d1a92c-f44c-2ebd-4834-63c70959f8e2
* Content: [Add an address list to or remove an address list from an offline address book in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/offline-address-books/add-or-remove-an-address-list#use-exchange-online-powershell-to-add-and-remove-address-lists-from-offline-address-books)
* Content Source: [Exchange/ExchangeOnline/address-books/offline-address-books/add-or-remove-an-address-list.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/offline-address-books/add-or-remove-an-address-list.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@asampson68 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@asampson68 You are correct! Thank you for pointing this out. I have submitted a fix and the updates should be published in the near future.
