### ISSUE TITLE
<your tenant name> should be <your verified domainname in step 1

### ISSUE THREAD

**Issue by jaapwess** [MicrosoftDocs/OfficeDocs-Exchange#1872]
The second command in step 1 is not correct. It says &lt;your tenant name&gt; but this fails, if you enter &lt;your verified domainname&gt; it succeeds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484887bf-a423-cb36-d8d1-712858e746bb
* Version Independent ID: c1df772a-5b5c-79d0-24fc-c89a09059497
* Content: [Configure OAuth authentication between Exchange and Exchange Online](https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@jaapwess Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@jaapwess Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
