### ISSUE TITLE
Exchange server 2019 on windows server 2019 core

### ISSUE THREAD

**Issue by SashkaNebesny** [MicrosoftDocs/OfficeDocs-Exchange#1873]
Hello.
Please tell me if there are any restrictions for using the Office online server functionality in Exchange server 2019 on windows server 2019 core?
My documents do not open for viewing. Error - document not found or deleted.
But, on SharePoint, everything works great.
WACDiscoveryEndpoint pointed to Set-OrganizationConfig

**Comment by scanum** [comment]
@SashkaNebesny thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
