### ISSUE TITLE
Should there be a comma btwn "multi-factor authentication (MFA)" and "using smart cards" in the first sentence?

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/OfficeDocs-Exchange#1878]
Should there be a comma btwn "multi-factor authentication (MFA)" and "using smart cards" in the first sentence?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@bingoglossy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@bingoglossy Thanks for pointing this out. This sentence definitely needed clarifying, so I've rephrased this part slightly and the fixes should be published in the near future. Thanks again for opening this issue.
