### ISSUE TITLE
Documentation is inaccurate and uses incorrect naming and formats

### ISSUE THREAD

**Issue by RayBrindley** [MicrosoftDocs/OfficeDocs-Exchange#188]
_folder_mapping.csv_ Under Step 5 isn't referenced anywhere and not made clear
Step 5 has multiple incorrect numbers for the headers

User accounts don't make sense if you have already migrated to Office 365 there is no local mailbox with Public Folder Access

Document just isn't clear and fails!

**Comment by AndreaBarr** [comment]
@RayBrindley Thank you for this feedback

We deffinatly want to make sure the articles are clear. I'm going to get this over to the Exchange team for investigation and clerification. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@RayBrindley which topic are we talking about?

**Comment by RayBrindley** [comment]
Hey Chris, the page is for the Exchange Legacy Public Folder Migration to
Exchange Online. Half of the instructions are incorrectly numbered or have
conflicting information.

https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders

In particular at heading
Step 5: Start the migration request

**Comment by msdmaguire** [comment]
@RayBrindley the formatting errors in this article have been fixed. Thanks for bringing them to our attention.
