### ISSUE TITLE
ViewDNS.info integration

### ISSUE THREAD

**Issue by hughesey** [MicrosoftDocs/OfficeDocs-Exchange#1880]
Hi guys,

I run the site https://viewdns.info/ and we're getting a number of emails asking us to unblock users that have been blocked by our anti abuse scripts.  On further investigation, it seems that the Exchange Hybrid Configuration Wizard has been configured to screen scrape our website when verifying domain name ownership.

We were never informed of this by Microsoft so we weren't able to allow your users.  Can someone reach out to us on feedback@viewdns.info ASAP to discuss this please.  We have serious concerns about how this has been implemented in the Exchange Hybrid Configuration Wizard.

Regards,
Michael Hughes
ViewDNS.info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8cb000-e64b-b90d-fa6f-09f2b50532b3
* Version Independent ID: b65f1351-a45c-37b6-f1a8-12894f203dd4
* Content: [Create a hybrid deployment with the Hybrid Configuration wizard](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/deploy-hybrid#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@hughesey I'm only a technical writer, so I only work on the documentation, but I'll see what I can do to get this in front of the right person. (This might take some time, but I will report back.)

**Comment by hughesey** [comment]
Thanks @mattpennathe3rd!

**Comment by mattpennathe3rd** [comment]
@hughesey I passed your information along. I'm sorry that I can't be of more direct help myself, but the team has been made aware of this.
