### ISSUE TITLE
How to allow specific 3rd party clients? (Apple Mail on MacOS)

### ISSUE THREAD

**Issue by jelmerS2** [MicrosoftDocs/OfficeDocs-Exchange#1881]
Hi

We are limiting how users can access their outlook/exchange accounts and are blocking all third party apps from accessing Exchange accounts. 
However, we would like to make an exception for certain programs, such as Mail on MacOS. 
Is this possible? If so: could someone provide an example? 
I've checked https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules but don't see a way to do this here..

**Comment by scanum** [comment]
@jelmerS2 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
