### ISSUE TITLE
Disabling Integrated Windows Authetication

### ISSUE THREAD

**Issue by KaushikDas19860216** [MicrosoftDocs/OfficeDocs-Exchange#1884]
I don't see any mention about Integrated Windows Authentication whether to keep that enable or disabled on the EWS virtual directory. I found keeping it disabled gives an error "connection to server xxxx couldn't be completed" while creating migration endpoint. Also from the security angle is it advisable to  keep it disabled or enabled to avoid attack. If someone could clarify on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dee0d453-e476-7b64-f0bb-d0135887916f
* Version Independent ID: 506a0b80-19db-21c8-aee3-071b7827a342
* Content: [Enable the MRS Proxy endpoint for remote moves](https://docs.microsoft.com/en-us/Exchange/architecture/mailbox-servers/mrs-proxy-endpoint?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/mrs-proxy-endpoint.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/mrs-proxy-endpoint.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@KaushikDas19860216 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
