### ISSUE TITLE
404 from Related Topics Link

### ISSUE THREAD

**Issue by pjrcdf** [MicrosoftDocs/OfficeDocs-Exchange#1885]
When clicking the "Mail flow insights in the Office 365 Security & Compliance Center" link under related Topics, the link redirects to a 404 error

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb585f32-3cd9-2d99-d989-9abb99fb2a7b
* Version Independent ID: aa9e599b-3c5b-b0d0-e4e9-23d7e8ab3894
* Content: [Customize and schedule mail protection reports in Office 365 to be automatically sent to your inbox](https://docs.microsoft.com/en-gb/exchange/monitoring/customize-and-schedule-mail-protection-reports?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@pjrcdf Thank you very much for pointing this out. We appreciate it! I've submitted a fix and it should be published later today.
