### ISSUE TITLE
Link to Exchange Online equivalent

### ISSUE THREAD

**Issue by TimAbmgf** [MicrosoftDocs/OfficeDocs-Exchange#1887]
I was trying to find where to view the current settings for my organization (which is in Exchange Online). 

I didn't notice at the beginning of this article (stating the platform that this applies to). I only noticed on the left hand menu that this is for Exchange 2019 (I was directed here from a websearch for: 'configure exchange online dumpster')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba50998c-7b9a-bc1f-81af-05ade620793c
* Version Independent ID: 46a00993-86e7-4d06-bff4-bc16b1df2c96
* Content: [Configure Deleted Item retention and Recoverable Items quotas](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@TimAbmgf There is more than one article covering this material in Exchange Online, but I believe you'll find what you need [here](https://docs.microsoft.com/exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder) and [here](https://docs.microsoft.com/exchange/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention). There are other articles covering similar material in that area of the table of contents, as well, so this should cover all of your bases.
