### ISSUE TITLE
Want to know more about cross-premises permission in OWA

### ISSUE THREAD

**Issue by Birbfeeder** [MicrosoftDocs/OfficeDocs-Exchange#1888]
According to the page "Cross-premises mailbox permissions aren't fully supported in Outlook on the web."
I have tested accessing "Options" of an on-prem mailbox (Exchange 2010)  via online full-access delegate is not supported. 
It will help a lot if there is any specific settings that inaccessible or list of limitation for cross premises mailbox permission in outlook on the web. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/permissions#feedback)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws** [comment]
Hi @Birbfeeder, thank you for your feedback and help us to improve docs.microsoft.com.

For more information, please see [Overview of delegation in an Office 365 hybrid environment](https://docs.microsoft.com/exchange/troubleshoot/delegates/overview-delegation-office-365-hybrid).
I added it to this article.

Thanks again!

**Comment by scanum** [comment]
@Birbfeeder Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
