### ISSUE TITLE
Need to rename the .edb file after relocate them in different database

### ISSUE THREAD

**Issue by Birbfeeder** [MicrosoftDocs/OfficeDocs-Exchange#1889]
After copy the database and logs here and there, we need to rename the file and then we could mount the database with file from other database.
And we need to run Set-MailboxDatabase "identity" -AllowFileRestore $true, otherwise the database won't mount and we will get MSExchangeIS Event 1047 and 1048 in application log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c0340f-0d45-476c-cf5d-021d3bd1cb25
* Version Independent ID: f2e88b48-e373-d74d-bcdd-0974af1ed166
* Content: [Perform a dial tone recovery](https://docs.microsoft.com/en-us/Exchange/high-availability/disaster-recovery/dial-tone-recovery?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/high-availability/disaster-recovery/dial-tone-recovery.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/disaster-recovery/dial-tone-recovery.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Birbfeeder Thank you very much for pointing this out. Can you tell me where in the procedure you needed to perform these extra steps?

**Comment by mattpennathe3rd** [comment]
@birbfeeder Following up again to see if you can provide further details on this issue. Can you explain where in the procedure these steps were needed for you?

**Comment by dariomws** [comment]
@Birbfeeder Following up again to see if you can provide further details on this issue. Can you explain wherein the procedure these steps were needed for you?

I've reviewed the steps I think you don't need to use the AllowFileRestore parameter.

Thanks!

**Comment by scanum** [comment]
@Birbfeeder We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
