### ISSUE TITLE
HCW issue with previously uninstalled HybridAgent

### ISSUE THREAD

**Issue by Ragnar157** [MicrosoftDocs/OfficeDocs-Exchange#1892]
Due to issues getting ModernHybrid working i try to switch back to classic mode.
but it always tries the msappproxy url for MRS!

HCW log
2020.04.10 07:18:48.450         10386 [Client=UX, Thread=6] Previous Connector Application Name found: ba6a948b-6ceb-4d30-bda5-fc7314ab9d04
2020.04.10 07:18:49.107         10332 [Client=UX, fn=SendAsync, Thread=6] START GET https://graph.microsoft.com/edu/73bc63a4-4ce1-4500-b4ec-13114951c6cb/applications/ba6a948b-6ceb-4d30-bda5-fc7314ab9d04/onPremisesPublishing 
2020.04.10 07:18:49.703         10333 [Client=UX, fn=SendAsync, Thread=6] FINISH Time=596.3ms Results=OK {"@odata.context":"https://graph.microsoft.com/edu/$metadata#applications('ba6a948b-6ceb-4d30-bda5-fc7314ab9d04')/onPremisesPublishing","externalUrl":"https://ba6a948b-6ceb-4d30-bda5-fc7314ab9d04.resource.mailboxmigration.his.msappproxy.net/","internalUrl":"https://mail.gkxy.de/","externalAuthenticationType":"passthru","isTranslateHostHeaderEnabled":false,"isTranslateLinksInBodyEnabled":false,"isOnPremPublishingEnabled":true,"isHttpOnlyCookieEnabled":false,"isSecureCookieEnabled":false,"isPersistentCookieEnabled":false,"applicationServerTimeout":"Default","verifiedCustomDomainCertificatesMetadata":null,"verifiedCustomDomainKeyCredential":null,"verifiedCustomDomainPasswordCredential":null,"applicationType":null,"singleSignOnSettings":{"SingleSignOnMode":"none","KerberosSignOnSettings":null}}

i can also see this object exists:

PS C:\temp> $uri = "https://graph.microsoft.com/edu/connectorGroups?`$expand=members"
PS C:\temp> $result = Invoke-RestMethod -Uri $uri -Headers $authHeader -Method Get
PS C:\temp> $result

@odata.context                                                       value
--------------                                                       -----
https://graph.microsoft.com/edu/$metadata#connectorGroups(members()) {@{id=8cfed851-792f-4ceb-a691-b60a6bc29789; nam...

PS C:\temp> $result|fl
@odata.context : https://graph.microsoft.com/edu/$metadata#connectorGroups(members())
value          : {@{id=8cfed851-792f-4ceb-a691-b60a6bc29789; name=Default group for Exchange Online;
                 connectorGroupType=exchangeOnline; isDefault=False; members=System.Object[]}}

PS C:\temp> $uri2="https://graph.microsoft.com/edu/73bc63a4-4ce1-4500-b4ec-13114951c6cb/applications/ba6a948b-6ceb-4d30-bda5-fc7314ab9d04/onPremisesPublishing "
PS C:\temp> $result2 = Invoke-RestMethod -Uri $uri2 -Headers $authHeader -Method Get
...

And why does HCW IGNORE my setting of "Classic mode" just because it finds this object?!?!
Seems like a incorrect IF/THEN in the code.
maybe switch back from modern to classic is not implemented fully?

so how can i delete the msapproxy object for it to work again?

thanks
Thorsten

**Comment by mattpennathe3rd** [comment]
@Ragnar157 I'm sorry, but this is not a documentation issue. I am not a support engineer and I can only help with documentation problems in this repo. For help with your issue, please open a support ticket.
