### ISSUE TITLE
Retired notice

### ISSUE THREAD

**Issue by lawrencegripper** [MicrosoftDocs/OfficeDocs-Exchange#1898]
Hi, 

This page would be better removed or carrying a notice that this functionality is now retired. Portal displays the following when using it:

```
 As per the original notice announced on July 31, 2017, the In-Place eDiscovery & Hold functionality in the Exchange Admin Center is being retired. During this process, for a better customer experience, we encourage your organization to start using the eDiscovery search and hold features in the Microsoft 365 Compliance Center. Learn more
Here are the key milestones for this process:
April 1, 2020 - You won't be able to create new searches and holds, but you can still run, edit and delete existing searches at your own risk. Microsoft Support will no longer provide assistance per this notice.
July 1, 2020 - The In-Place eDiscovery & Hold functionality in the Exchange admin center will be placed in a read-only mode. This means you'll only be able to remove existing searches and holds.
```

Kind regards,
Lawrence

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afa9584b-0025-474c-66b0-a1df9233e8b3
* Version Independent ID: e4604c40-df8a-37d1-521b-13d5797da453
* Content: [Export eDiscovery search results to a PST file](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/ediscovery/export-results-to-pst?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/ediscovery/export-results-to-pst.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/ediscovery/export-results-to-pst.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@lawrencegripper Thanks, but this page is for Exchange Server (on-premises) and nothing should be changing with this product. Please let me know if there is indeed expected breakage in Server and I'll look into it further.

The Exchange Online pages already have warnings about this, so I think we're all set.

**Comment by lawrencegripper** [comment]
Sorry, my bad - thanks for the quick response and sorry for wasting your time

**Comment by mattpennathe3rd** [comment]
@lawrencegripper Not a waste of time at all! I appreciate the issue. Things change quickly around here and I always wonder if I'm missing something. Many times, the answer is yes. 😉
