### ISSUE TITLE
.NET 4.7.2

### ISSUE THREAD

**Issue by xstaindx** [MicrosoftDocs/OfficeDocs-Exchange#19]
Can you advise the state of the support for .NET 4.7.2.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange 2016 system requirements](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
We don't support .NET 4.7.2 at this time. We support only the versions of .NET explicitly defined in the .NET Framework section of this topic. If future releases of Exchange 2016 support .NET 4.7.2, we'll update this topic to include that version.
