### ISSUE TITLE
How to use Microsoft service account to send email.

### ISSUE THREAD

**Issue by ruowan** [MicrosoftDocs/OfficeDocs-Exchange#1902]
I requested a Microsoft service account. I want to send email from scripts. And I refer to [doc](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3?redirectSourcePath=%252farticle%252fHow-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4).  Could you pls take a look or give me some ideas about service account?

But I got the error message .

```
  console.log node_modules/nodemailer/lib/shared/index.js:492
    [2020-04-14 09:24:36] DEBUG [DArryGTES8E] Closing connection to the server using "end"

  console.log node_modules/nodemailer/lib/shared/index.js:492
    [2020-04-14 09:24:36] ERROR Send Error: Invalid login: 535 5.7.3 Authentication unsuccessful [HK2PR04CA0069.apcprd04.prod.outlook.com]

  console.log node_modules/nodemailer/lib/shared/index.js:492
    [2020-04-14 09:24:38] INFO  [DArryGTES8E] Connection closed
```

Here is the code example:

```
 const transporter = nodemailer.createTransport({
      host: "smtp.office365.com",
      port: 587,
      secure: false,
      // secureConnection: false,
      tls: {
        ciphers: 'SSLv3'
      },
      auth: {
        user: "fake@microsoft.com", 
        pass: "xxxx" 
      },
      requireTLS: true,
      debug: true,
      logger: true
    });

    // send mail with defined transport object
    let info = await transporter.sendMail({
      from: "fake@microsoft.com", // sender address
      to: "example@microsoft.com", // list of receivers
      subject: "Hello ✔", // Subject line
      text: "Hello world?", // plain text body
      html: "<b>Hello world?</b>" // html body
    });
    console.log(info);
```

**Comment by mattpennathe3rd** [comment]
@ruowan I am sorry, but this is not a documentation problem. I am only able to provide help with documentation problems in this GitHub repository and I am not a member of the support staff. Please seek help internally or contact support for assistance with your problem. If you find a problem with the documentation, please open a new issue on the article that contains the problem and I would be glad to help.
