### ISSUE TITLE
Trouble With Signatures

### ISSUE THREAD

**Issue by josemoreno90** [MicrosoftDocs/OfficeDocs-Exchange#1905]
I am trying to add the following code to the disclaimer:

&lt;div style="font-size:9pt;  font-family: 'Calibri',sans-serif;"&gt;
%%displayname%%&lt;br/&gt;
%%title%%&lt;br/&gt;
%%company%%&lt;br/&gt;
%%street%%&lt;br/&gt;
%%city%%, %%state%% %%zipcode%%&lt;/div&gt;
&nbsp;&lt;br/&gt;
&lt;div style="background-color:#D5EAFF; border:1px dotted #003333; padding:.8em; "&gt;
&lt;div&gt;&lt;img alt="Fabrikam"  src="http://fabrikam.com/images/fabrikamlogo.png"&gt;&lt;/div&gt;
&lt;span style="font-size:12pt;  font-family: 'Cambria','times new roman','garamond',serif; color:#ff0000;"&gt;HTML Disclaimer Title&lt;/span&gt;&lt;br/&gt;
&lt;p style="font-size:8pt; line-height:10pt; font-family: 'Cambria','times roman',serif;"&gt;This message contains confidential information and is intended only for the individual(s) addressed in the message. If you aren't the named addressee, you should not disseminate, distribute, or copy this e-mail. If you aren't the intended recipient, you aren'tified that disclosing, distributing, or copying this e-mail is strictly prohibited.  &lt;/p&gt;
&lt;span style="padding-top:10px; font-weight:bold; color:#CC0000; font-size:10pt; font-family: 'Calibri',Arial,sans-serif; "&gt;&lt;a href="http://www.fabrikam.com"&gt;Fabrikam, Inc. &lt;/a&gt;&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;
&lt;/div&gt;

But nothing shows up except the display name.  Not sure what I am doing wrong...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a56bae-a3fc-43e8-1e5e-69c38971b2d8
* Version Independent ID: c68cbbac-56f7-32f5-1e9a-bbc1d58d091d
* Content: [Organization-wide disclaimers, signatures, footers, or headers in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mail-flow-rules/signatures?redirectedfrom=MSDN&view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/signatures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/signatures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@josemoreno90 I'm sorry, but this isn't a documentation question, so I'm unable to help with this in this repo. I only maintain the docs and I'm not a support person, so I can't help solve specific implementation problems here.
