### ISSUE TITLE
Set Cloud Mailbox for PF Mailbox

### ISSUE THREAD

**Issue by garmoz** [MicrosoftDocs/OfficeDocs-Exchange#1911]
It will be very useful to mention to Set-Mailbox DefaultPublicFolders from Exchange Online... at the end of the process.

thanks a lot,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws** [comment]
Hi @garmoz, thank you for your feedback.

I think you are talking about "Set-Mailbox -Identity <MailboxId> -DefaultPublicFolderMailbox <RecipientId>".
By default, the public folder mailbox used by a user is automatically selected by an algorithm that load-balances users across all public folder mailboxes.

I think we shouldn´t add this cmdlet here as I think it´s a good idea to leave default public folder mailbox for each mailbox.
