### ISSUE TITLE
Delivery of external mail to a group can fail if you've enabled centralized mail flow

### ISSUE THREAD

**Issue by tyusaf** [MicrosoftDocs/OfficeDocs-Exchange#1913]
We need to know why this statement says CAN fail rather than DOES fail.
If O365 groups are supposed to replace distribution groups, and -requiresenderauthentication $false currently works to Internet enable current DLs, this statement needs to be clarified
- is there a configuration that does work?
- why does it sometimes fail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@tyusaf Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
