### ISSUE TITLE
Organizational unit field not available

### ISSUE THREAD

**Issue by PacoBell** [MicrosoftDocs/OfficeDocs-Exchange#1914]
I want to create a dynamic distribution group based on a specific OU, but it's not showing up as a configurable option in EAC. It's clearly referenced several times in this document. Where did it go?

**Comment by scanum** [comment]
@PacoBell thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
