### ISSUE TITLE
The section on customizing the language selection page is incorrect.

### ISSUE THREAD

**Issue by KarlBystrak** [MicrosoftDocs/OfficeDocs-Exchange#1915]
It says to edit %ExchangeInstallPath%ClientAccess\Owa\Current2\version\resources\styles\languageselection.css but that is the wrong file.  If you read the code in the languageselection.aspx file you will see this:
&lt;link type="text/css" rel="stylesheet" href="&lt;%=OwaUrl.ApplicationRoot.GetExplicitUrl(Request)%&gt;prem/&lt;%=OwaVersion%&gt;/resources/styles/languageselection.css"&gt;
which is actually in a totally different location.   
The correct file to edit is %ExchangeInstallPath%\ClientAccess\Owa\prem\&lt;ExchangeVersion&gt;\resources\styles\languageselection.css

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc39e241-23c3-9e81-f680-aad251625e99
* Version Independent ID: 0e33dc96-518a-8b5a-8bf0-fd060b2bd6e2
* Content: [Customize the Outlook on the web sign-in, language selection, and error pages in Exchange Server](https://docs.microsoft.com/en-us/exchange/clients/outlook-on-the-web/customize-outlook-on-the-web?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/clients/outlook-on-the-web/customize-outlook-on-the-web.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-on-the-web/customize-outlook-on-the-web.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@KarlBystrak thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mattpennathe3rd** [comment]
@scanum This is a documentation issue and not a support issue.

**Comment by mattpennathe3rd** [comment]
@KarlBystrak Thank you very much for reporting this. We've updated this article and the new version should be published in the near future.

Thanks again for helping us improve the documentation. If you find any other problems, please feel free to open a new issue and we'll gladly take a look at it.
