### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by mpowrie** [MicrosoftDocs/OfficeDocs-Exchange#1917]
The link to "Getting Started with Log Parser Studio" is broken (points to a generic "archived blogs" page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b946a8f-95c0-db27-df0c-9fa3eaf80be4
* Version Independent ID: 3468d939-ae42-5ea9-4da5-8a1192690ac8
* Content: [IIS Logs and Log Parser Studio Reports: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/iis-logs-and-log-parser-studio-reports-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/iis-logs-and-log-parser-studio-reports-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/iis-logs-and-log-parser-studio-reports-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@mpowrie Thank you for pointing this out. I've updated the link with something much more current and the article should be published in the near future.
