### ISSUE TITLE
Distribution list migration 

### ISSUE THREAD

**Issue by merwindz** [MicrosoftDocs/OfficeDocs-Exchange#1919]
Migration limitation section in the document doesn't talk about Distribution List migration so just wondering if this migration process support DL migration? Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-gb/exchange/mailbox-migration/perform-g-suite-migration#overview-of-the-process)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@merwindz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @merwindz, thank you for your feedback and help us to improve docs.microsoft.com.

This article details the steps to migrate users or mail accounts from G Suite to Microsoft 365. To migrate groups or lists, I think you should export them with their members to a CSV file, and then you can recreate them in Microsoft 365 with PowerShell.

Hope it helps.

**Comment by scanum** [comment]
@merwindz Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
