### ISSUE TITLE
Exchange 2016 Management Tools on Windows Server 2019

### ISSUE THREAD

**Issue by ioanstavar** [MicrosoftDocs/OfficeDocs-Exchange#1921]
Is there a way to install Exchange 2016 Management Tools only on a Windows Server 2019 Standard (GUI) ?

Thank You

**Comment by scanum** [comment]
@ioanstavar thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
