### ISSUE TITLE
What "Microsoft 365 admin permissions" ?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/OfficeDocs-Exchange#1922]
To access the Exchange Admin center "You must have Microsoft 365 admin permissions". OK, but *what* admin permissions? Is it Exchange Admin only? If so, why not state just that? I am for instance a Security Admin, but I have no access to EAC.
So based on the text above I assume I'm OK. But it is just not so...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe03d3b-31dc-90a2-2a78-1e48947b86d8
* Version Independent ID: 2873f6e9-6979-31d1-5622-0ae47cd9d965
* Content: [Exchange admin center in Exchange Online](https://docs.microsoft.com/en-us/exchange/exchange-admin-center?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/exchange-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/exchange-admin-center.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@andrePKI thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by mattpennathe3rd** [comment]
@scanum This is a documentation issue.

@andrePKI Thanks for filing this. I will look into it and see if we can make this more specific.
