### ISSUE TITLE
Outlook for Mac for Office 365 support for Public Folder Hybrid

### ISSUE THREAD

**Issue by jwood-msft** [MicrosoftDocs/OfficeDocs-Exchange#1924]
Outlook for Mac for Office 365 guidance should be aligned with Outlook 2016 for Mac. Outlook for Mac for Office 365 is now at ver 16.36 and Outlook 2016 is at ver 16.16.20.

Include Outlook 2019.

Also replace O365 with Office 365 in Step 2.

https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders

**Comment by scanum** [comment]
@jwood-msft  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@jwood-msft Thanks for opening this. The guidance for Outlook for Mac seems to reflect version 2016 already. Which elements of the article are you referring to?

As for the typo, I've submitted a fix and that should be corrected in the near future. Thanks for pointing this out.

**Comment by mattpennathe3rd** [comment]
@jwood-msft Scratch the prior comment. I've reorganized and clarified some of the existing content, which should help with this.

Regarding Outlook for Mac for Office 365, do you know when support for cross-prem public folders was introduced?

**Comment by mattpennathe3rd** [comment]
@jwood-msft I rephrased the section in question to be much more current. This should help immensely and the updated version should be published in the near future, but if you see any further issues with this article, please let me know and I'd be glad to fix them.
