### ISSUE TITLE
Heading does not match TOC

### ISSUE THREAD

**Issue by swxxii** [MicrosoftDocs/OfficeDocs-Exchange#1927]
TOC - Manage group access to Microsoft 365 groups
Page Heading - Allow/Block guest access to Microsoft 365 groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08bf021-f95a-ab2f-85e3-4f4c44374501
* Version Independent ID: 2d7ea71a-f42c-693a-eb4e-c1d9336b44eb
* Content: [Allow/Block guest access to Microsoft 365 groups](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-group-access-to-office-365-groups#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-office-365-groups.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@swxxii  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by mattpennathe3rd** [comment]
@swxxii Thank you for pointing this out. I have corrected the title.

Many of our article titles don't exactly,align with the table of contents, but I think this one definitely needed to be fixed. Thanks very much for submitting this.
