### ISSUE TITLE
Clarification on section "Network and directory requirements" section

### ISSUE THREAD

**Issue by ita-tomi** [MicrosoftDocs/OfficeDocs-Exchange#1929]
"You can't install the Exchange server and then remove the domain controller from the Active Directory site."

I think this means you cannot remove domain controller ROLE from Exchange server after installing Exchange?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@mattpennathe3rd Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ita-tomi, thank you for your feedback and help us to improve docs.

All this section is related to Active Directory site:
"The Active Directory site where you install the Exchange Server must contain at least one writeable domain controller that's also a global catalog server, or the installation will fail. Furthermore, you can't install the Exchange server and then remove the domain controller from the Active Directory site."

You need at least one writeable domain controller in the AD site where you install the Exchange Server. After you install it, you can´t remove the domain controller from this AD site.
The same applies for Exchange Server installed in a domain controller. But have in mind that it´s not recommended:
https://docs.microsoft.com/exchange/plan-and-deploy/system-requirements#installing-exchange-2019-on-directory-servers

**Comment by ita-tomi** [comment]
@dariomws Ok thanks. I opened this ticket originally because customer asked if this means that they cannot remove any of their current domain controllers from site after installing Exchange and thus never be able to migrate to newer DC:s.

**Comment by dariomws** [comment]
@ita-tomi "The Active Directory site where you install the Exchange Server must contain at least one writeable domain controller that's also a global catalog server".

If you have only 1 domain controller in the AD site where you have installed Exchange, you can't remove it. If you install a new writeable domain controller that's also a global catalog server in this AD site, then you can remove the older DC.

**Comment by scanum** [comment]
@ita-tomi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
