### ISSUE TITLE
Where is..?

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/OfficeDocs-Exchange#1930]
Regarding: "If your organization requires that users on hold be informed, you can add a notification message to the mailbox user's Retention Comment property and use the RetentionUrl property to link to a web page for more information." - a link to the PowerShell cmdlets would be useful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c38acb1-6f67-3c4c-fa3f-7d0ca7b257c0
* Version Independent ID: 673af28f-4de4-ec12-6428-6346142d20d3
* Content: [In-Place Hold and Litigation Hold](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-and-litigation-holds)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@challengelogic Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@challengelogic Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
