### ISSUE TITLE
update

### ISSUE THREAD

**Issue by fpolikavo** [MicrosoftDocs/OfficeDocs-Exchange#1931]
Altought is a well knonw site, it will be nice to supplement the article by adding a link reference to the testconnectivity.microsoft.com address, so people shall not jump pages around

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21b5e59e-b1df-376c-22f3-fedf3a1e2fe9
* Version Independent ID: 459dc342-6e86-2a47-3552-bfafdf968710
* Content: [Remote Connectivity Analyzer tests for Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/remote-connectivity-analyzer-tests)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/remote-connectivity-analyzer-tests.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/remote-connectivity-analyzer-tests.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@fpolikavo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@fpolikavo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
