### ISSUE TITLE
This text is not in a blue box like the other call outs

### ISSUE THREAD

**Issue by isuckatscripting** [MicrosoftDocs/OfficeDocs-Exchange#1933]
Important: The values that you enter for the selected attribute must exactly match those that appear in the recipient's properties. For example, if you enter Washington for State or province, but the value for the recipient's property is WA, the condition will not be met. Also, text-based values that you specify aren't case-sensitive. For example, if you specify Contoso for the Company attribute, messages will be sent to a recipient if this value is contoso.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0f79a0-4e3e-f72e-fb3d-dc0a7a47b7ec
* Version Independent ID: 1882bc12-05d5-02c5-da27-bc48479825b2
* Content: [Manage dynamic distribution groups](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-dynamic-distribution-groups/manage-dynamic-distribution-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/manage-dynamic-distribution-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/manage-dynamic-distribution-groups.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@isuckatscripting Thanks for pointing this out! I'm not sure why that was left that way, but I have submitted a fix and it should be published in the near future.

Thank you again for submitting this. Also, I love the username. :-)
