### ISSUE TITLE
Exchange 2016 Mailbox servers on Windows Server 2016

### ISSUE THREAD

**Issue by NavishkarSadheo** [MicrosoftDocs/OfficeDocs-Exchange#1936]
Why do I need to install "Visual C++ Redistributable Package for Visual Studio 2012" for Windows Server 2016 when it clearly states on the "Visual C++ Redistributable Package for Visual Studio 2012" product page that the support OS's are "Windows 7 Service Pack 1, Windows 8, Windows 8.1, Windows Server 2003, Windows Server 2008 R2 SP1, Windows Server 2008 Service Pack 2, Windows Server 2012, Windows Vista Service Pack 2, Windows XP"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites, Exchange 2019 system requirements, Exchange 2019 requirements](https://docs.microsoft.com/en-za/Exchange/plan-and-deploy/prerequisites?view=exchserver-2016#windows-server-2016-prerequisites-for-exchange-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@NavishkarSadheo Thanks for opening this issue. I believe the article is correct (in spite of the confusing supported OSes), but I am double checking and will report back.

**Comment by mattpennathe3rd** [comment]
@NavishkarSadheo I have verified that this is correct. VC++ 2012 redistributable is required, the system requirements on the download page notwithstanding. I agree this is confusing and I will add some notes to this page explaining this.

**Comment by mattpennathe3rd** [comment]
@NavishkarSadheo Thank you again for opening this issue. I've updated the article and the new version should be published later today. If you see any other problems with the documentation, please open a new issue and I'll gladly take a look at it.
