### ISSUE TITLE
Confirm all the commands are wrong!

### ISSUE THREAD

**Issue by trevevs** [MicrosoftDocs/OfficeDocs-Exchange#1938]
The amended commands posted above are correct and work. (you are missing " before /custom binding & at end to close it off.)
Please update the doc.
Errors produced are:
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )
ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The @position specifier is optional, and be '@start', '@end', o
r '@N' where N is a numeric index into the collection. )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee5dfea-ce93-b800-b21c-1323559e17d0
* Version Independent ID: 458e568f-9bff-e24b-3395-77fa19734f71
* Content: [Configure client-specific message size limits: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/configure-client-specific-message-size-limits-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/configure-client-specific-message-size-limits-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-client-specific-message-size-limits-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@trevevs You are absolutely correct. The other issue that included the corrections was closed for reasons unknown, but I have gone back and incorporated all of these into the article. The updated version will be published later today.

Thanks for drawing attention to this. If you find any other problems in the documentation, please feel free to open up new issues and I will look into them.
