### ISSUE TITLE
Instructions on how to generate an CSR for ECC

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/OfficeDocs-Exchange#1939]
Under the "What you need to know" section of this article, it states:  
"Exchange generates a PKCS #10 request (.req) file that uses Base64 (default) or Distinguished Encoding Rules (DER) encoding, with an RSA public key that's 1024, 2048 (default), or 4096 bits.  Note that encoding and public key options are only available in the Exchange Management Shell."  
Can you provide instructions in this article on how to generate an ECC public key request using the Exchange shell?  
From this article:  https://docs.microsoft.com/en-us/Exchange/architecture/client-access/certificates?view=exchserver-2019  we see the in Exchange 2016 and later, the cryptography is inherited from the config in the OS, but it would be nice to see how to use the new-exchangecertificate commandlet to generate the CSR for and ECC cert in addition to an RSA.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb6bf64-d3d6-dff6-2eb7-02074758e834
* Version Independent ID: 32b7069b-6a49-9d54-5119-b0d42aad619d
* Content: [Create an Exchange Server certificate request for a certification authority](https://docs.microsoft.com/en-us/Exchange/architecture/client-access/create-ca-certificate-requests?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/create-ca-certificate-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/create-ca-certificate-requests.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@dagroll Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dagroll, thank you for submitting feedback and contributing to the docs.

You have the encoding (-BinaryEncoded) and public key size (-KeySize) parameter in the [New-ExchangeCertificate](https://docs.microsoft.com/powershell/module/exchange/new-exchangecertificate) cmdlet. But I think you cannot request an ECC certificate/key using this cmdlet.

So, I understand there is no way to do it. I´m trying to get more information about ECC support on Exchange.

**Comment by dariomws** [comment]
Hi @dagroll,

More information about this subject:
"TLS 1.2 is the only version that's enabled by default: Exchange Server 2019 includes important changes to improve the security of client and server connections. The default configuration for encryption will enable TLS 1.2 only and disable support for older algorithms (namely, DES, 3DES, RC2, RC4 and MD5). It will also configure elliptic curve key exchange algorithms with priority over non-elliptic curve algorithms. In Exchange Server 2016 and later, all cryptography settings are inherited from the configuration specified in the operating system. For additional information, see [Exchange Server TLS Guidance](https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-tls-guidance-part-1-getting-ready-for-tls-1-2/ba-p/607649)."

From here: https://docs.microsoft.com/exchange/new-features/new-features#whats-new-when-upgrading-from-exchange-2013-to-exchange-2019

**Comment by scanum** [comment]
@dagroll Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
