### ISSUE TITLE
Example incorrect

### ISSUE THREAD

**Issue by liquidkristal** [MicrosoftDocs/OfficeDocs-Exchange#1940]
Get-MailboxStatistics -Database <recovery Database> | Format-Table Name,MailboxGUID -AutoSize

needs to be

Get-MailboxStatistics -Database <recovery Database> | Format-Table DisplayName,MailboxGUID -AutoSize

On Exchange 2016 CU15 (maybe on other versions as well)

**Comment by mattpennathe3rd** [comment]
@liquidkristal I assume you're speaking about this article: https://docs.microsoft.com/en-us/exchange/high-availability/disaster-recovery/restore-data-using-recovery-dbs

I'll look into this further and will report back.

**Comment by liquidkristal** [comment]
HI

Yes that’s the article.

Regards

Mike.

**Comment by mattpennathe3rd** [comment]
@liquidkristal Mike, thanks for pointing this out! I've corrected this and the updated article will be published in the near future. I also checked the rest of our Exchange documentation set and (fortunately) this was the only instance of this error. Thanks again for opening this issue and please feel free to open others for any other problems you run across in the docs.
