### ISSUE TITLE
Exchange documentation need update for performance counters

### ISSUE THREAD

**Issue by kekici** [MicrosoftDocs/OfficeDocs-Exchange#1941]
TCPv6\Connection Failures
Shows the number of TCP connections for which the current state is either ESTABLISHED or CLOSE-WAIT. The number of TCP connections that can be established is constrained by the size of the nonpaged pool. When the nonpaged pool is depleted, no new connections can be established. 

Not applicable
-- | -- | --

Above description is wrong it should be like below;

TCPv6\Connection Failures
Shows the number of times TCP connections have made a direct transition to the CLOSED state from the SYN-SENT state or the SYN-RCVD state, plus the number of times TCP connections have made a direct transition to the LISTEN state from the SYN-RCVD state. 

An increasing number of failures, or a consistently increasing rate of failures, can indicate a bandwidth shortage.
-- | --

exact page uri is;
https://docs.microsoft.com/en-us/exchange/exchange-2013-performance-counters-exchange-2013-help
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d70cd8-c8f1-460d-01dc-b701337e5d52
* Version Independent ID: 47745e8a-02bb-e813-6704-6b58b592efec
* Content: [Exchange 2013 Performance Counters: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/exchange-2013-performance-counters-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/exchange-2013-performance-counters-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/exchange-2013-performance-counters-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@kekici Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@kekici Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
