### ISSUE TITLE
Clarity request

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-Exchange#1944]
Can we confirm by statement whether this statement is also true if the mailbox used to authenticate has SendAs permissions on the account it is impersonating?

"Error: Client was not authenticated to send anonymous mail during MAIL FROM

This error indicates that your printer connects to the SMTP client submission endpoint (smtp.office365.com). However, your printer must also logon to a mailbox to send a message. This error occurs when you have not entered mailbox logon credentials in the printer's settings. If there is no option to enter credentials, this printer does not support SMTP client submission; use either direct send or Office 365 SMTP relay instead. See How to set up a multifunction device or application to send email using Office 365."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b5e01ad-4656-ca35-3b3d-41efdae39cd9
* Version Independent ID: 54b8031d-44b9-296e-f006-47e8cc835d1e
* Content: [Fix issues with printers, scanners, and LOB applications that send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @aldoug, thank you for your feedback.

I think the scenario you commented is more suitable for this error:
"Error: 5.7.60 SMTP; Client does not have permissions to send as this sender"

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
