### ISSUE TITLE
FQDN of Exchange Server

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/OfficeDocs-Exchange#1945]
In NDR external users getting, "The following organization rejected your message: edge.contoso.com." How to remove/change this line from NDR? I dont want to show my server names to senders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27a93c3c-15f2-8bca-90f4-c4b8abf2d588
* Version Independent ID: e683fa27-017f-910f-ca48-e0231ad5b259
* Content: [DSNs and NDRs in Exchange 2013: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/dsns-and-ndrs-in-exchange-2013-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/dsns-and-ndrs-in-exchange-2013-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/dsns-and-ndrs-in-exchange-2013-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@mzafzal1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @mzafzal1, thank you for your feedback.

You can change it in the properties of your receive connectors using:
https://docs.microsoft.com/powershell/module/exchange/set-receiveconnector
Or from the Admin Center, when you edit a Receive Connector you have the option in the Scoping tab.

Hope it helps you.

**Comment by scanum** [comment]
@mzafzal1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
