### ISSUE TITLE
restart IIS

### ISSUE THREAD

**Issue by AndreyNov** [MicrosoftDocs/OfficeDocs-Exchange#1946]
The question about Step 5. Why are you calling to stop "was" service and then start another "w3svc" service?
First action stop 3 services (including w3svc).
Therefore after second action we have 2 services stopped and not restarted:
- Net.Tcp Listener Adapter
- Net.Pipe Listener Adapter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad6b073-061b-60d6-958c-e3f408aebf85
* Version Independent ID: 19356060-5edf-5eb7-6abc-97c4fc741bd5
* Content: [Configure http to https redirection for Outlook on the web in Exchange Server](https://docs.microsoft.com/en-us/exchange/clients/outlook-on-the-web/http-to-https-redirection?view=exchserver-2016#step-5-use-iis-manager-to-restart-iis)
* Content Source: [Exchange/ExchangeServer/clients/outlook-on-the-web/http-to-https-redirection.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-on-the-web/http-to-https-redirection.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@AndreyNov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@AndreyNov Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
