### ISSUE TITLE
Mailbox usage "More options" not available

### ISSUE THREAD

**Issue by ncasa-johnj** [MicrosoftDocs/OfficeDocs-Exchange#1947]
"More options" is not available as part of the Mailbox usage tab when I view accounts from EAC. Is this a configurable item?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba50998c-7b9a-bc1f-81af-05ade620793c
* Version Independent ID: 46a00993-86e7-4d06-bff4-bc16b1df2c96
* Content: [Configure Deleted Item retention and Recoverable Items quotas](https://docs.microsoft.com/en-us/Exchange/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@ncasa-johnj Are you using the modern EAC or the classic EAC? We're still working on updated docs for the modern EAC, as it's brand new, but please let me know if you're still using classic and I will look into it.

**Comment by ncasa-johnj** [comment]
It feels classic.  Screenshot attached. 

![Capture](https://user-images.githubusercontent.com/64867250/81123035-045cc680-8ee7-11ea-818e-0682f46c013d.PNG)

**Comment by mattpennathe3rd** [comment]
@ncasa-johnj Forgive me. I misread your issue and didn't realize this was for an article dealing with on-premises Exchange Server; the modern EAC is only for Exchange Online.

I'll dig a little and will report back. Thanks for your patience.

**Comment by ncasa-johnj** [comment]
On-premise Exchange would explain the issue.  We are O365 hosted.

Regards,

JOHN JOYNT
Sr. Director of Information Technology & Operations
206.774.7226  |  johnj@nationalcasagal.org<mailto:johnj@nationalcasagal.org>
NATIONAL CASA/GAL ASSOCIATION FOR CHILDREN
100 West Harrison Street, North Tower, Suite 500, Seattle, WA 98119
800.628.3233  |  nationalcasagal.org<https://nationalcasagal.org/>

My email address has recently changed to johnj@nationalcasagal.org<mailto:johnj@nationalcasagal.org>.
Please update your address book to reflect the new email address.

**Comment by mattpennathe3rd** [comment]
@ncasa-johnj That would do it! I will close this issue now, but please feel free to open new issues if you run into holes in the Online/O365/M365 documentation.
