### ISSUE TITLE
Biometrics (Fingerprint and Facial Recognition)

### ISSUE THREAD

**Issue by justin-fb** [MicrosoftDocs/OfficeDocs-Exchange#1949]
Is there a setting that requires a password but will allow biometrics such as a fingerprint sensor or facial recognition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8953d102-718c-d28a-976a-5906000567c3
* Version Independent ID: 0a13e776-9b35-7b46-5bb5-86b4ba8ddbe5
* Content: [Mobile device mailbox policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by justin-fb** [comment]
I should add, this option is not indicated in the docs. That is why I am asking.

**Comment by smithre4** [comment]
Exchange mobile device mailbox policies do not controlling whether biometrics can be used in lieu of typing the device PIN. Mobile device mailbox policies can be configured to require a device PIN. Users can control whether they can use biometrics after complying with the device PIN requirement. Customers that need advance control over the user of biometrics should consider device enrollment solutions, like Microsoft Intune.

**Comment by mattpennathe3rd** [comment]
@justin-fb Ross's comment above should answer your questions, but please follow up if this still isn't clear. I try to add some details to this article to make this obvious, also.
