### ISSUE TITLE
Supportability of .NET Framework 4.7.2	

### ISSUE THREAD

**Issue by jhasaurab** [MicrosoftDocs/OfficeDocs-Exchange#195]
Can you please mention supportability of .NET Framework 4.7.2 for Exchange 2013 CU 21  ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcdf59c9-1922-ecf5-fc36-caafb16423ff
* Version Independent ID: 62557ef7-d03e-50b9-00f7-ffdc244e1fc7
* Content: [Exchange Server Supportability Matrix: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/exchange-server-supportability-matrix-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by jhasaurab** [comment]
Can you please confirm if Microsoft .NET Framework 4.7.2 is supported with Exchange 2013 CU 21. There is no official statement that which .net framework versions are supported with Exchange 2013 CU21?

**Comment by michelderooij** [comment]
That information is contained in the Ex2016CU11 announcement:
_"We have validated .NET Framework 4.7.2 on the previously released Exchange Server 2013 Cumulative Update 21 and are announcing .NET Framework support with Exchange Server 2013 Cumulative Update 21 as well."_
Source: https://blogs.technet.microsoft.com/exchange/2018/10/16/released-october-2018-quarterly-exchange-updates/
Support matrix should be updated.

**Comment by chrisda** [comment]
@jhasaurab, @michelderooij the topic has been updated.

Thanks for the feedback.
