### ISSUE TITLE
Received this error followng MS docs re: Migration from G-Suite to Office 365

### ISSUE THREAD

**Issue by peterwilson69** [MicrosoftDocs/OfficeDocs-Exchange#1950]
I suspect this problem is occuring because of a mail-protection bug. Possibly a DNS misconfiguration with the TXT record "v=spf1 include:spf.protection.outlook.com -all".  I could be wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9428237-4e3c-8d0e-d64e-4c40b4a5e560
* Version Independent ID: 8a2e802c-c072-9e37-2c1f-524d22467ba5
* Content: [Fix email delivery issues for error code 550 5.4.1 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-4-1-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-4-1-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-4-1-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by peterwilson69** [comment]
Should I be using a separate SPF TXT record on the o365.example.com domain (used for migration) and it's root, example.com?
I've just tried experimenting by adding multiple servers to the spf TXT record on the root of my domain name. I'm really taking guesses here.

**Comment by mattpennathe3rd** [comment]
@peterwilson69 I'm sorry, but these are questions you will need to work out with support. Please open a support ticket to get help with your configuration. I will close this issue now, but if you discover problems in our documentation, please feel free to open a new ticket.
