### ISSUE TITLE
role or roles?

### ISSUE THREAD

**Issue by Jodyl1971** [MicrosoftDocs/OfficeDocs-Exchange#1953]
The first instance says to run:  Setup /roles:&lt;Failed Server Role&gt;
But later, it says : Setup.com /role:HubTransport /Mode:Install

so is it /role, or /roles ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64f3a8f1-b5fe-db28-787f-be1e42ff085a
* Version Independent ID: 34b31be9-078b-8580-a167-f6dd86ce365e
* Content: [Setup failure occurred while installing a server role](https://docs.microsoft.com/en-us/exchange/setup-failure-occurred-while-installing-a-server-role-installwatermark-exchange-2013-help?redirectedfrom=MSDN#feedback)
* Content Source: [Exchange/ExchangeServer2013/setup-failure-occurred-while-installing-a-server-role-installwatermark-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/setup-failure-occurred-while-installing-a-server-role-installwatermark-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Jodyl1971 It should be "role", singular. Thanks for pointing this out. I will update this article and the fixed version will be published in the near future.
