### ISSUE TITLE
Computer

### ISSUE THREAD

**Issue by Maryis665** [MicrosoftDocs/OfficeDocs-Exchange#1955]
I can't login on my computer, it's showing my old address jeraldjohnson60@gmail.com my phone is fine. It's showing jeraldjohnson690@gmail.com if you can't help me with this, who can? I can't even login computer. Thx Jerald Johnson 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1640bb5-ca97-15ff-28e5-5efe4e73193f
* Version Independent ID: e957bd3e-5d4c-333c-45ff-6fd694f34670
* Content: [Manage accepted domains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Maryis665 I'm sorry, but this GitHub repository is for feedback on the documentation for the Microsoft Exchange product. We are unable to provide technical support here. Please contact the support team for help with your issue.
