### ISSUE TITLE
Check of mailbox sync status

### ISSUE THREAD

**Issue by pmeuser** [MicrosoftDocs/OfficeDocs-Exchange#1958]
I run into issues with adding the HMA account to Outlook iOS. Is there any way for a customer to check the mailbox sync status as initiated by the Exchange Online Mailbox Replication Service other than opening a support ticket with Microsoft Support? The Powershell script https://aka.ms/TestHMAEAS seems not to do the job (btw: The script looks like being broken and needs some tweaking) - in my case all script results are as expected. Would be nice to have a feature, that is not just like a black box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0020c770-fbf0-d36b-196c-59fd0a5dbe93
* Version Independent ID: bd5c069a-c325-28cf-5a58-8ae9c34c793d
* Content: [Using hybrid Modern Authentication with Outlook for iOS and Android](https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@pmeuser I'm sorry, but I'm unable to answer this one here, as it's more of a support issue than a documentation issue. You will need to contact support with your questions. This repo is only for providing feedback on the Exchange documentation and I'm not equipped to answer support questions here.

The PowerShell script you linked is not from Microsoft, so I don't believe anyone on our end would be able to assist with troubleshooting that.

If you encounter any problems with the documentation, please feel free to open a new issue and let me know how I can help resolve that.

**Comment by pmeuser** [comment]
@mattpennathe3rd Matt, you mean a script linked with aka.ms/TestHMAEAS is not supported by Microsoft? Then you better should remove the Microsoft shortcut and any link from documentation.

My suggestion is to add a troubleshooting guide about HMA for Outlook iOS/Android in the section "Administrating and monitoring Outlook for iOS and Android in your organization". Seems to be missing here.

Is this better relating to documentation tasks?

Thanks a lot for your support!
Peter

**Comment by mattpennathe3rd** [comment]
@pmeuser Where is this script linked from? I cannot find a reference to it in this GitHub repo.

**Comment by pmeuser** [comment]
@mattpennathe3rd [Using hybrid Modern Authentication with Outlook for iOS and Android](https://gallery.technet.microsoft.com/scriptcenter/Validating-Hybrid-Modern-ad4c2b16)

In either scenario, verify that your on-premises environment is correctly configured. To do this: from the TechNet Gallery, download and execute the script for [Validating Hybrid Modern Authentication setup for Outlook for iOS and Android](https://gallery.technet.microsoft.com/scriptcenter/Validating-Hybrid-Modern-ad4c2b16).

**Comment by mattpennathe3rd** [comment]
@pmeuser Thanks for that. I wasn't aware of this and we're looking into some changes for the script.

Regarding your original question, I have submitted some changes to this article that might help provide the information you're looking for (in the form of some PowerShell cmdlets), and the updated article should be published in the near future. If I can do anything further to help or if you find other problems in the documentation, please feel free to open a new issue and I will gladly look into it.

And thank you for helping us to improve the documentation! We really appreciate it.
