### ISSUE TITLE
opinia

### ISSUE THREAD

**Issue by marecki01** [MicrosoftDocs/OfficeDocs-Exchange#196]
ok

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: b8d4ec80-7a55-398a-22e9-3f5df24a867b
* Version Independent ID: 4543c414-41d1-b8fe-8a58-4dc61ccf61ff
* Content: [Journaling in Exchange Online](https://docs.microsoft.com/pl-pl/exchange/security-and-compliance/journaling/journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@marecki01 I am unsure if there is a request or issue here. I am going to close this issue. If there is a issue please re-open this issue and let us know what is going on. Thank you.
