### ISSUE TITLE
Internal IP Addresses cannot be used for Skip Listing with Enhanced Filtering for Connectors

### ISSUE THREAD

**Issue by richardjgreen** [MicrosoftDocs/OfficeDocs-Exchange#1960]
When trying to configure the Skip List for Enhanced Filtering for Connectors, regardless of whether it is done via the GUI in the Security and Compliance Center or via PowerShell, you cannot specify internal IP addresses or ranges.

![image](https://user-images.githubusercontent.com/5471987/81551643-1a9cd380-937a-11ea-83d1-8c6d4acc2b85.png)

Trying to enter either a single address (e.g. 192.168.1.1) or a CIDR range (e.g. 192.168.1.0/24) yields an error. This affects all RFC 1918 ranges (e.g. 10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16).

All documentation uses 192.168.0.0/16 addresses as examples illustrating that it should be possible and skip listing on-premises Exchange environments for hybrid deployments is listed as a use case so skipping internal IP addresses is required for this scenario.

**Comment by scanum** [comment]
@richardjgreen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by SignorelliDenis** [comment]
@richardjgreen  You don’t need to enter internal IPs, Skip Listing is smart enough to know that internal IP should be bypassed. For hybrid scenario, just assign the Public IP which Exchange On-Prem uses. 
Regarding the example mentioned in the docs (192.168.1.1) agree with you that are not valid examples, I’ll open a pull request to change that.

**Comment by mattpennathe3rd** [comment]
@richardjgreen Thanks very much for opening this issue and helping us improve the docs. We've updated this article and the new version will be published in the near future.

If you run into any other problems, please feel free to open a new issue and we'll gladly take a look at it.
