### ISSUE TITLE
scenario 2 with on-prem long gone: can we disable hybrid safely?

### ISSUE THREAD

**Issue by themarkdiesel** [MicrosoftDocs/OfficeDocs-Exchange#1961]
I inherited an environment where scenario 2 would be the closest description of where we are (currently have NO on-prem Exchange servers, and we use AD Sync to sync our on-prem AD to Azure AD), but before we go forth with running Remove-HybridConfiguration and disabling the org relationship from the EO admin panel, do we need to worry about anything? As stated, we have absolutely no on-prem Exchange, and would like to be able to manage Exchange attributes via EXO admin (or third party tool, namely Adaxes).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#feedback)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@themarkdiesel I apologize, but I have no way of providing a good answer to this question here. This repo is only for providing feedback on the documentation and you'd be best off contacting support with your question.

If you find that the docs were not adequate, please feel free to open a new issue about the docs problem you encountered and I'd be glad to have a look at it.
