### ISSUE TITLE
Guest Users Writeback

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-Exchange#1963]
This article doesn't mention what happens to the Guest's account who are part of Office 365 group, Would they be synced back to local AD as part of Group writeback ? Also if someone from On-premises sends email to this O365 Group would Guest users who are part of this O365 Group will receive it? There should be more details provided about the behavior of "Distribution Group" which is created On-premises as part of Group writeback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Microsoft 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups#known-issues)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @3novsan how are you?
AFAIK guest users are not synced back to on-premises, but I am looking deeper into this and I will get back to you if I get more information.
Thanks

**Comment by get-itips** [comment]
@3novsan Hello again, I could confirm internally that guests users who are part of a 365 group are not synced back to on-premises, and also the guest user should receive the e-mail in the scenario that you asked.
Hope this information helps you,
