### ISSUE TITLE
Option 3 Connector O365 not compatible with Azure Services

### ISSUE THREAD

**Issue by cstainie** [MicrosoftDocs/OfficeDocs-Exchange#1964]
In the document, the following item is described: 

"You can't use SMTP relay to send email directly to Office 365 from a third-party hosted service, such as Microsoft Azure"

Are you sure this is correct if you can limit the outbound IP address to one single IP address? 

Can you also comment why it would not be supported? I understand that sending from Shared IP is not supported, but there are solutions for that. 

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3?fireglass_rsn=true#how-office-365-smtp-relay-works)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@cstainie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @cstainie how are you? I could dig this internally, I am adding thru a pull request a link to more information where this is explained.
Thank you
