### ISSUE TITLE
.\Sync-MailPublicFolders.ps1 Won't Remove Remote Objects if no Local Objects

### ISSUE THREAD

**Issue by shady247** [MicrosoftDocs/OfficeDocs-Exchange#1966]
I did a sync where there were several legacy public folders that got synced over to online and caused Mailbox1 to fail.

Error: FailedToMailEnablePublicFoldersException: Error: There are 8 mail public folder'(s)' in Active Directory that were not linked to any public folder during migration.

After deleting all the public folder MESO objects and re-running the script, it simply reported there were no local objects and did nothing.

Examining the script I could see that it would only continue on and check remote objects if there were one or more local objects or if the -Force option were used.

Re-running with -Force did the trick and removed the failing remote objects and allowed the sync to complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@shady247 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @shady247, thank you for your feedback and help us to improve docs.microsoft.com.

Sorry for the delay.

The prerequisites contain the instructions to clean the previously synced or created public folders in Exchange Online:
"Make sure no public folders or public folder mailboxes exist in Microsoft 365 or Office 365."

**Comment by scanum** [comment]
@shady247 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
