### ISSUE TITLE
E2010 supported ? 

### ISSUE THREAD

**Issue by tonivervloet** [MicrosoftDocs/OfficeDocs-Exchange#1967]
at the top e2010 is specified as a supported platform for multi-forest hybrid. But a bit lower it states that at least a 2013 server should be there ? Could you please clarify ? 
"Exchange servers: At least one Exchange 2013 server with the Client Access server role, or one Exchange 2016 or later server with the Mailbox role, must be installed in each Active Directory forest configured for hybrid deployment."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa1d495-fac4-cd81-06a9-cb031107b1c4
* Version Independent ID: a20a0eff-0792-a3a2-8aa9-f21979fd0801
* Content: [Hybrid deployments with multiple forests](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-with-multiple-forests#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-with-multiple-forests.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-with-multiple-forests.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by michelderooij** [comment]
I think this is aimed at configuration of OAuth. However, it is not mandatory (and not available in Ex2010).

**Comment by tonivervloet** [comment]
In an older version of this document, it does mention E2010 in that server chapter as well (https://docs.microsoft.com/en-us/previous-versions/exchange-server/exchange-150/jj873754(v=exchg.150)?redirectedfrom=MSDN). 
For me the question still stays: can an Exchange 2010 org participate in a multi-org hybrid setup (the first org is 2013 btw) and be fully supported?

**Comment by scanum** [comment]
@michelderooij  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi everyone,

Thank you for your feedback and sorry for the delay.

I removed Exchange 2010 from the article as reached its end of support on October 13, 2020.
