### ISSUE TITLE
% sign missing in Microsoft.Exchange.Imap4.exe path

### ISSUE THREAD

**Issue by peterhuerlimann** [MicrosoftDocs/OfficeDocs-Exchange#1968]
Hi,

There is a %-sign missing on the line "Microsoft.Exchange.Imap4.exe	ExchangeInstallPath%FrontEnd\PopImap".

Kind regards
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176e9cde-47cb-31b8-9ecf-51208888a740
* Version Independent ID: 97f0327a-5dba-d810-daeb-cd976b634c8b
* Content: [Running Windows antivirus software on Exchange servers](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/windows-antivirus-software?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/windows-antivirus-software.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@peterhuerlimann  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
