### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by MalcolmRivett** [MicrosoftDocs/OfficeDocs-Exchange#197]
All IOS Microsoft IOS Apps should support App Configuration for mdm distribution, to preset user credentials to the app.
From what I can see, only Outlook is supported? based on this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@MalcolmRivett Thank you for this feedback

I'm not clear if this is an issue with a feature that should be working or if it's a feature you would like to see . If it's a feature that should be working we need you to contact support. They have more resources to help figure out what is going on and find a solution.  If it's a feature you would like to see in the future we are always open for suggestions. I would say create a user voice item and upvote it. The more upvotes the quicker the features are looked at for adding to the application. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

 They keep a close tab on User Voice [https://office365.uservoice.com/](https://office365.uservoice.com/) and if you don't mind it would be awesome if you could look through and give your input in User Voice and if you don't see a similar request already you could open one. Let us know and we can up-vote your request too. 
 
Thank you for your contribution to make the docs better! Much appreciated!
