### ISSUE TITLE
PublicFolderMailboxesLockedForNewConnections VS PublicFoldersLockedforMigration

### ISSUE THREAD

**Issue by ghostmdb** [MicrosoftDocs/OfficeDocs-Exchange#1970]
Hello,
in these days I was migrating Exchange 2013 CU23 to 365, and following your guide I had an issue with the final testing.
Infact, using only PublicFolderMailboxesLockedForNewConnections $true, I could test PF with a native 365 user, but not with a migrated user (autodiscover and MX point to local Exchange). Also OWA said that there were no PF on 365.
After a bit of testing, I found that enabling also PublicFoldersLockedforMigration $true, immediately migrated users start navigating migrated PF (and OWA starts working).
I don't know if PublicFoldersLockedforMigration will be set to $true by PublicFolderMailboxesLockedForNewConnections (and in my enviroment for any strange reason it didn't), but if not I think that this step might be in the guide.
Thanks for the feedback

**Comment by scanum** [comment]
@ghostmdb  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ghostmdb thanks for your feedback, can you please tell me what is the article you refer to? Thank you I appreciate.

**Comment by get-itips** [comment]
Hello @ghostmdb 
I could confirm with the Product Group that _PublicFolderMailboxesLockedForNewConnections_ should be enough, could this be related to maybe some delay in this configuration to replicate at the time you tested?

**Comment by scanum** [comment]
@ghostmdb Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
