### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rogermicrosoft** [MicrosoftDocs/OfficeDocs-Exchange#1972]
Hi, the link in this article https://go.microsoft.com/fwlink/p/?LinkId=623595 named "New access and security controls for Outlook for iOS and Android" does not work. Best regards Roger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeec798c-00f4-df45-da44-47e5aac06ff9
* Version Independent ID: 4cdfab74-fce7-f298-c3df-51da100c2162
* Content: [Account setup with modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@rogermicrosoft Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @rogermicrosoft Roger, thanks for noticing and reporting.
A fix to the link is on the way.
Thank you again!
