### ISSUE TITLE
Scenario two: Why do I still need an on prem Exchange server?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#1973]
It is unclear to me why an on prem exchange server is still needed.  We have a hybrid environment and have recently migrated all mailboxes to O365 as well as changing DNS records to point there.  We still use AADConnect to sync Active Directory to O365.  So what is the Exchange server required for? Can't we manage user settings with AD/AADConnect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#feedback)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Canis-Lupis How are you?
Hope you are doing great. 👍 

Yes, currently, you still need to leave a Exchange Server for management in that scenario.

As the article currently states

> [...] If you don't have any on-premises mailbox(es), you can safely decommission most of your exchange server(s), leaving one or more for user management purposes, **because the source of authority is still defined as on-premises**.

and also

> **Can third-party management tools be used?**
The question of whether a third-party management tool or ADSIEDIT can be used is often asked. The answer is you can use them, but they are not supported. **The Exchange Management Console, the Exchange admin center (EAC), and the Exchange Management Shell are the only supported tools that are available to manage Exchange recipients and objects**. If you decide to use third-party management tools, it would be at your own risk. Third-party management tools often work fine, but Microsoft does not validate these tools.

I also found two uservoice suggestions that talks about this, please see [this](https://office365.uservoice.com/forums/264636-general/suggestions/13616214-decommission-exchange-server-after-migration-to-of) and [this](https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/31225783-allow-managing-user-properties-in-office-365-even).

Hope this information helps you.
Thanks for your feedback.

**Comment by Canis-Lupis** [comment]
There needs to be clarification on this, please. Specifically, why we must keep paying for on prem Exchange servers that we aren't using for email, simply to act as "source of authority" when all our mailboxes are now in the cloud.  This makes no sense technically nor financially.  We already have AD syncing with AAD Connect, so what are the reasons that's not good enough and a full exchange server is needed?
________________________________

**Comment by StevenCA256** [comment]
I agree. It looks like the only reason to keep the on-premise Exchange is for the EMC. Otherwise you will be managing all the attributes through the attribute editor or powershell for an user object. I'm sure this is unsupported by MS. I will be following a mixture of Scenario 2 and 1 this weekend to completely remove Exchange 2010 this weekend.

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis @StevenCA256 I'm sorry to say that the server is still needed in certain scenarios and that's simply the way the product works for the time being. You do have access to a free license for Exchange by way of the Hybrid Configuration Wizard, so you should not need to continue paying for that server.

There are a few details in this section as to what's going on with the on-prem server and why it's needed: https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#why-you-may-not-want-to-decommission-exchange-servers-from-on-premises

Looking to the future, there is attention to this on the dev team, so I encourage you to keep an eye on the Exchange blogs for any news that might help in your situation.

I wish I could do more, but this is a product issue and there's nothing I can help with regarding the documentation, so I will close this issue for now.

**Comment by vin-cheesel** [comment]
I've been following this post for over a year now and there still hasn't been an update regarding this issue.
For smaller clients who want the added benefit of directory and password sync  - AD Connect is the best option.
I'm disappointed how Microsoft still require a local exchange server when using AD connect - especially after all the recent Exchange vulnerabilities. As an MSP - we have to deal with many clients who want password sync and to not worry about the extra management that follows with an exchange server. Please review.
