### ISSUE TITLE
Enable outlook to access gmail as a less secure app

### ISSUE THREAD

**Issue by chiraniya** [MicrosoftDocs/OfficeDocs-Exchange#1975]
I had authentication issue. I tried turning on lesssecureapps setting in google on all user accounts, and that helped. Sharing that here for everyone's benefit. https://myaccount.google.com/lesssecureapps?pli=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer G Suite mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@chiraniya Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @chiraniya

**Comment by scanum** [comment]
@chiraniya Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
