### ISSUE TITLE
Test-HybridConnectivity -TestO365Endpoints fails due to expired Cert

### ISSUE THREAD

**Issue by MDAMatt** [MicrosoftDocs/OfficeDocs-Exchange#1977]
When running the Test-HybridConnectivity -TestO365Endpoints the test fails with the error below because the certificate expired on 3/12/2020. Today is 5/29/2020.

`Performing GET on https://aadap-portcheck-seaus.connectorporttest.msappproxy.net:8080`
`Invoke-WebRequest : The underlying connection was closed: An unexpected error occurred on a send.`
`At C:\Service\HybridManagement.psm1:196 char:19`
`+         $result = Invoke-WebRequest -Method Get -Uri $uri`
`+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException`
`    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by scanum** [comment]
@MDAMatt Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@MDAMatt Thank you very much for posting this issue. Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by MDAMatt** [comment]
@dariomws, this is not a tenant side check, it is a Microsoft public site. I fail to understand why this is a problem with my tenant. The URL used by the script included in this documentation page references a check to a server that Microsoft maintains that is not tenant specific, and has an expired certificate. 

This feedback was meant for the document https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent. I don't know if it's linked on your side properly. When I clicked on the feedback page to raise this issue, I had to create github account and it may have lost the association in the process. I don't see this thread listed under it's feedback page.  

In any event, it's not an issue with my tenant it's an issue with the certificate at https://aadap-portcheck-seaus.connectorporttest.msappproxy.net which is not my site.

**Comment by dariomws** [comment]
Sorry about that @MDAMatt, you are right. I´ve tested it on my lab and get the same error, and I can see that the certificate expired on 12/03/2020. In my first reading, it seemed to be a typical support case.

I will report this issue to the respective team so they can check it. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by mcavasin** [comment]
...still broken :(

Also, this script really should give some kind of final results or log file rather than take the "if it doesn't fail it's OK" approach.

Things like this embarrass me and MS in front of clients...

**Comment by mattpennathe3rd** [comment]
@MDAMatt @mcavasin I've verified with our technical teams that this test is deprecated and will be removed from the script in the next build release, so this will be resolved shortly with no action needed.

Thanks for reporting this.
