### ISSUE TITLE
Complete the migration batch in Office 365

### ISSUE THREAD

**Issue by nhoj01** [MicrosoftDocs/OfficeDocs-Exchange#1979]
After the initial sync completes successful, when I try to complete the batch it fails with the error: "Error: TargetDeliveryDomainMismatchPermanentException: Error: The target mailbox doesn‎'t have an SMTP proxy matching o365.yourdomain.com. 

I thought this might be because of the step "create sub-domain for mail routing to office 365" but that step was completed successfully. Is there some other steps that need to be completed when adding that sub-domain? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@nhoj01 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by wrall** [comment]
The [Provision users in Microsoft 365 or Office 365 step](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md#provision-users-in-microsoft-365-or-office-365) mentions that "The users should also have a proxy address that will be used for routing to their Microsoft 365 or Office 365 routing domain (such as "will@o365.fabrikaminc.net")."  It appears that part was missed.

**Comment by dariomws** [comment]
@nhoj01 thank you for your feedback.

@wrall thank you for your answer.

@scanum I think this issue can be closed.

**Comment by scanum** [comment]
@nhoj01 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
