### ISSUE TITLE
Step 5: Start the migration request - when creating the migration batch the -AutoStart parameter should not be included

### ISSUE THREAD

**Issue by gabymuntean** [MicrosoftDocs/OfficeDocs-Exchange#1980]
Step 5: Start the migration request - when creating the migration batch the -AutoStart parameter should not be included, as we manually start the migration at step. 6 (Start-MigrationBatch PublicFolderMigration), or keep the AutoStart parameter at the migration batch creation and omit step. 6.

![image](https://user-images.githubusercontent.com/14187423/82442446-50dc0080-9aa8-11ea-8603-f8feeb0548ee.png)

-AutoStart
The AutoStart switch immediately starts the processing of the new migration batch. You don't need to specify a value with this switch.
If you don't use this switch, you need to manually start the migration batch by using the Start-MigrationBatch cmdlet.
From https://docs.microsoft.com/en-us/powershell/module/exchange/new-migrationbatch?view=exchange-ps

Thank you,
Gabriel

**Comment by scanum** [comment]
@gabymuntean Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by ssssss7693** [comment]
[متجر فور جي للاتصالات ](https://mobility4-sa.com/) # @gabymuntean

**Comment by ssssss7693** [comment]
> [متجر فور جي للاتصالات ](https://mobility4-sa.com/) # @gdams

**Comment by scanum** [comment]
@gabymuntean Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
