### ISSUE TITLE
Is O365 SMTP AUTH client submission supported in Exchange Hybrid environment?

### ISSUE THREAD

**Issue by myNGU** [MicrosoftDocs/OfficeDocs-Exchange#1984]
Hello,

We have a Exchange Hybrid Environment set up, just wonderring if Option 1 in the link below would work. 

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#option-1-recommended-authenticate-your-device-or-application-directly-with-an-office-365-mailbox-and-send-mail-using-smtp-auth-client-submission

Can we set up SMTP AUTH client submission by below configuration?

Server/smart host --------smtp.office365.com
Port | Port -----------------587 (recommended) 
TLS/StartTLS --------------Enabled
Username/email address and password-------Enter the sign in credentials of the hosted mailbox being used

Thanks.

**Comment by scanum** [comment]
@myNGU thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
