### ISSUE TITLE
Deploying Outlook app config for IOS using VMWare UEM

### ISSUE THREAD

**Issue by dharma9639** [MicrosoftDocs/OfficeDocs-Exchange#199]
Hi Team

we are using VMWare UEM to manage IOS devices and we are using O365, I am trying to add app config mention in the document to save contacts to the device and also by default the email address should be present when I open the app. For some reason it is not working. Could you please help for us to achieve. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@dharma9639 Thank you for this feedback

I want to make sure your archiving issue is addressed properly. Support has more resources then we do here to dig in and help figure out what is going on. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by rpenaf01** [comment]
Hi Andrea, I know this is an old post but wanted to see if you have received any updates on this?

Thanks

**Comment by AndreaBarr** [comment]
@rpenaf01 No I didn't get word back on what the resolution was. The originator of this issue went and got help from support with the above link. If you are having a similar or the same issue please contact support since we don't have the tools to help with this type of issue here in the docs.
