### ISSUE TITLE
Also works with (applies to) Exchange 2016

### ISSUE THREAD

**Issue by CloudHotShot** [MicrosoftDocs/OfficeDocs-Exchange#1993]
When the team initially saw this article, we skipped over it because the 'Applies to' only mentions Exch 2013. We performed steps 1-7 with on-prem Exch 2016 CU 16 which resolved issue regarding calendar not showing in Teams for on-prem mailboxes. Seems like the 'Applies to' should include Exch 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484887bf-a423-cb36-d8d1-712858e746bb
* Version Independent ID: c1df772a-5b5c-79d0-24fc-c89a09059497
* Content: [Configure OAuth authentication between Exchange and Exchange Online](https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@CloudHotShot  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @CloudHotShot Mark, the current navigation makes this article under _ExchangeServer2013_ folder, that is the reason of the _applies to_, will pass this information on.

**Comment by scanum** [comment]
@CloudHotShot  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
