### ISSUE TITLE
Who performed the message trace

### ISSUE THREAD

**Issue by Lucky121983** [MicrosoftDocs/OfficeDocs-Exchange#1996]
Hi,

Is there a way to find out who did the message trace. For instance, there are 3 administrators who has necessary permissions to perform message trace. Can we find out who did it?

Thanks,
Lucky

**Comment by scanum** [comment]
@Lucky121983 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
