### ISSUE TITLE
What about federation trust?

### ISSUE THREAD

**Issue by MaratMussabekov** [MicrosoftDocs/OfficeDocs-Exchange#1997]
**Hybrid deployment protocols, ports, and endpoints** section doesn't contain requirements for outbound https traffic required for federation trust

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@MaratMussabekov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @MaratMussabekov How are you ? 👍 

Federation Gateway URLs currently are

> https://nexus.microsoftonline-p.com 
https://login.microsoftonline.com
https://domains.live.com/service/managedelegation2.asmx

[Source](https://techcommunity.microsoft.com/t5/exchange-team-blog/how-to-address-federation-trust-issues-in-hybrid-configuration/ba-p/1144285)

and as the article currently states

> **The Office 365 endpoints are vast, ever-changing, and aren't listed here**. Instead, see O[ffice 365 URLs and IP address ranges](https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges).

You will already find those URLs I mentioned on that link as common endpoints that you should already enabled for outbound connections. (domains.live.com will be found on [Additional endpoints not included in the Office 365 IP Address and URL Web service ](https://docs.microsoft.com/en-us/office365/enterprise/additional-office365-ip-addresses-and-urls)

Let me know if this answers your question.

**Comment by MaratMussabekov** [comment]
Hello @get-itips ,
when I whitelised all these URLs, federation fails on the domain ownership stage.
Trace shows that Exchange tries to go to viewdns.info to do a dns query via https.
And it looks like it is not only me- https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1880
I think one more row should be added to the [table](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites#hybrid-deployment-protocols-ports-and-endpoints), to show requirements for the federation trust.

Thank you

**Comment by get-itips** [comment]
@MaratMussabekov Thanks for adding that reference, will pass that information along.

**Comment by get-itips** [comment]
> Hello @get-itips ,
> when I whitelised all these URLs, federation fails on the domain ownership stage.
> Trace shows that Exchange tries to go to viewdns.info to do a dns query via https.
> And it looks like it is not only me- #1880
> I think one more row should be added to the [table](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites#hybrid-deployment-protocols-ports-and-endpoints), to show requirements for the federation trust.
> 
> Thank you

@MaratMussabekov how are you? hope you are doing good!

Please see this past techcommunity post about the dns verification method used

https://techcommunity.microsoft.com/t5/exchange-team-blog/march-2020-significant-update-to-hybrid-configuration-wizard/ba-p/1238753

It seems the endpoint was changed on HCW 17.x build, do you want to check your build? were you able to pass that error?
Thank you

**Comment by scanum** [comment]
@MaratMussabekov We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
