### ISSUE TITLE
Exchange Hybrid Agent - Team's Calendaring features that require access to on premises mailboxes are not supported

### ISSUE THREAD

**Issue by willemsen-it** [MicrosoftDocs/OfficeDocs-Exchange#1999]
I am aware that "Team's Calendaring features that require access to on premises mailboxes are not supported" when using the Exchange Hybrid Agent. (official ms doc site: https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent) 
Please fix this. If this is fixed it would make my Exchange Hybrid project a lot easier because I won't have to battle against the firewall/network guys.

Greetings, Marc Willemsen.
IT Pro

**Comment by scanum** [comment]
@willemsen-it thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
