### ISSUE TITLE
Public Folders Poorly Implemented in Outlook on the Web

### ISSUE THREAD

**Issue by TG352** [MicrosoftDocs/OfficeDocs-Exchange#2]
While it is possible to add a Public Folder to your Outlook on the Web UI, it is not possible to actually do anything useful with the Public Folder when accessing Contacts, for example searching for a Contact does not return any results from any section of the UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1322ea00-e4ee-5858-c224-c8b886f6a7d0
* Version Independent ID: 059da329-0f7f-cd54-31d7-cdec5eda9141
* Content: [Use favorite public folders in Outlook on the web](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/use-favorite-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/contribute/Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Hi. Sorry for your less than optimal public folder experience. I will pass your feedback along to the product team.
