### ISSUE TITLE
Apparent limitation on number of resource mailboxes allowed

### ISSUE THREAD

**Issue by ichinaparker** [MicrosoftDocs/OfficeDocs-Exchange#2000]
This isn't stated anywhere. 
It currently limits you to 16 resource boxes. You can make more, but it deletes the oldest mailbox very silently. I wouldn't have noticed except that resource boxes which I knew I'd made were not linking up.

**Comment by scanum** [comment]
@ichinaparker Thank you for your feedback. Could you please link the documentation you are referring to? Thanks!

**Comment by scanum** [comment]
@ichinaparker We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
