### ISSUE TITLE
Update for Modern Auth support for POP and IMAP

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/OfficeDocs-Exchange#2004]
[Enter feedback here]
Hi,

Based on this article:https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-auth-and-exchange-online-february-2020-update/ba-p/1191282, Modern Authentication for POP and IMAP is now rolling out, but I don't see this reflected in the documentation yet? Correct? or am I at the wrong page?

/Kenneth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64383249-903c-6cc5-83e1-93e0eb8ba128
* Version Independent ID: d93c4ce8-4bf4-15d0-b3ba-3d3eb11ebb37
* Content: [POP3 and IMAP4](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@kennethvs Thank you for your feedback. Could you please link the documentation you are referring to? Thanks!

**Comment by kennethvs** [comment]
Hi @scanum, that would be: https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4

**Comment by get-itips** [comment]
Hello @kennethvs How are you?
You are correct, the feature is currently rolling out, once the rolling out is complete the documentation will reflect that.

Please see this other more recent blog post for more information

https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-oauth-2-0-support-for-imap-and-smtp-auth-protocols-in/ba-p/1330432

Hope this information helps you,

**Comment by scanum** [comment]
@kennethvs Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
