### ISSUE TITLE
Exchange 2019 License

### ISSUE THREAD

**Issue by Usety-cmd** [MicrosoftDocs/OfficeDocs-Exchange#2008]
Hello,

For the deployment of a new Exchange 2019 solution, I am writing to you about its license.
I wanted to know if I would need to have a single license that activates Exchange MBX1, MBX2 and Edge1 installed on different servers (3 servers), or, one license for each server - IE: three licenses in total-

Thanks for your help!

**Comment by Usety-cmd** [comment]
Bonjour;

Dans le cadre du déploiement d'une nouvelle solution échange 2019, je m'adresse vers vous concernant sa licence.
Je voulais savoir si j'aurais besoin d'avoir une seule licence qui active Échange MBX1, MBX2 et Edge1 installés sur des serveurs différents (3 serveurs), ou bien, une licence pour chaque serveur - CAD: trois licences en global-
Merci pour votre collaboration !

**Comment by scanum** [comment]
@Usety-cmd thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
