### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by JasonBBG** [MicrosoftDocs/OfficeDocs-Exchange#201]
The doc does not tell you what to do if you see this error when executing the Shell command:
"Couldn't delete mailbox policy &lt;OWApolicy&gt; because it is associated with users"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23e0e3f4-7c0e-6661-e12b-30c55e6ab983
* Version Independent ID: 03d72745-d540-b084-d350-ae4d577f4944
* Content: [Remove an Outlook Web App mailbox policy from Exchange](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/remove-outlook-web-app-mailbox-policy)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/remove-outlook-web-app-mailbox-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/remove-outlook-web-app-mailbox-policy.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@JasonBBG Thank you for this feedback

I am not sure what to do with this error either. Lets get this over to the Support team for investigation and documentation. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
