### ISSUE TITLE
Outlook App Configuration for Android Enterprise Work Profile & Fully Managed device - Save Contacts -feature

### ISSUE THREAD

**Issue by RikuVuorela** [MicrosoftDocs/OfficeDocs-Exchange#2014]
When configuring a App Configuration policy for AE Work Profile & Fully Managed devices, you configure the Save contacts -setting to Yes.
Documentation says that in order for this feature to work automatically, you must grant the following permissions:

- READ_CONTACTS
- WRITE_CONTACTS. 

This does not seem to be correct. When going to Outlook -> Settings -> Press your account -> Sync contacts is greyed out, and you see "Open Settings" below the settings -> Press "Open Settings" and you get an error stating that "...contact permissions are not fully granted. Contact your IT admin for assistance".

What solves the problem? You must grant GET_CONTACTS permissions for Outlook as well and then the save contacts feature will auto-enable as it should. I think this should be added to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@RikuVuorela Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks @RikuVuorela for your feedback.

**Comment by get-itips** [comment]
Hello @RikuVuorela 
I checked and the GET_CONTACTS permissions is not showing up for me on my lab, for Outlook 

![image](https://user-images.githubusercontent.com/36666927/87212890-5a8b2300-c2f7-11ea-898e-4da84fc7855e.png)

Can you kindly check if it is still present for you in your configuration? Thanks

**Comment by get-itips** [comment]
Hello @RikuVuorela how are you? did you have chance to review my last message? Thanks

**Comment by scanum** [comment]
@RikuVuorela We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
