### ISSUE TITLE
Setting Individual forwarding doesn't work for a BCC message

### ISSUE THREAD

**Issue by vgpaul** [MicrosoftDocs/OfficeDocs-Exchange#2015]
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding?redirectedfrom=MSDN

The procedure defined works great... But not on BCC messages, If you want a BCC message forwarded you have to set forwards by server rule..  Would be nice to have the option as part of the user forward.

**Comment by scanum** [comment]
@vgpaul Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @vgpaul How are you?
I tried to reproduce and I could not. I set up forwarding for a mailbox like the article describes, and BCC messages were also forwarded. Can you kindly double check ?

**Comment by vgpaul** [comment]
Maybe It’s because I was forwarding to a group consisting of contacts?

This was happening with 6 different people The only ones I’ve had to set like this so I don’t think it was a one shot thing.

The mail is addressed to an individual.  That individual has the forward marked to deliver to a Group. The Group consists of two contacts.  Neither of the contacts received the BCC messages.

I’m not at work for the next couple of days but will set up a test as soon as I can and let you know what happens.

Thank You

Victor


[cid:AC_logo-150ppi_b0554e81-2d50-477d-8264-0219cbd8ac34.png]<http://www.alachuacounty.us/Pages/AlachuaCounty.aspx>     Victor G. Paul
Network Supervisor
Information and Telecommunication Services
26 NE 1st ST • Gainesville • FL • 32601
352-491-4659 (office) • 352-338-7365(fax)
[cid:home_page_150ppi_c93d2f0c-a636-4c7c-a777-a6d8edd72602.png]<http://www.alachuacounty.us/Pages/AlachuaCounty.aspx>  [cid:fb_logo_150ppi_9dd00851-99d8-4342-8932-10cac01030c6.png] <https://www.facebook.com/AlachuaCounty/>   [cid:twitter_150ppi_9c3d56ae-20c9-4509-b852-4aaed5522edd.png] <https://twitter.com/alachuacounty>   [cid:insta_150ppi_5be81f1b-b06b-49ca-b309-54edd0545f55.png] <https://www.instagram.com/alachuacounty/>   [cid:youtube_150ppi_0da7ed3a-56a8-459c-b04c-ed8dfa1a388a.png] <https://www.youtube.com/user/alachuacounty>   [cid:county_news_150ppi_14250fe5-78c3-4aa5-b059-283cc85fd4ea.png] <http://www.alachuacounty.us/depts/communications/pages/updatenewsletter.aspx>

PLEASE NOTE: Florida has a very broad public records law (F.S.119).
All e-mails to and from County Officials and County Staff are kept as public records. Your e-mail
communications, including your e-mail address, may be disclosed to the public and media at any time.

**Comment by scanum** [comment]
@vgpaul Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
