### ISSUE TITLE
Room not appearing in Room finder in outlook on the web

### ISSUE THREAD

**Issue by nhoj01** [MicrosoftDocs/OfficeDocs-Exchange#2017]
[Enter feedback here]

I have created a bunch of rooms
![image](https://user-images.githubusercontent.com/5090624/83298808-b623a600-a1ba-11ea-87f0-1fa9f03a5edb.png)

But none of them are showing up in Room finder
![image](https://user-images.githubusercontent.com/5090624/83298729-8eccd900-a1ba-11ea-8835-fb98d071f7a1.png)

Do they need to be on a list? The articles does not specify if a list is required for display in room finder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfdb9772-2bc8-840e-44c0-c2c9ed3cd018
* Version Independent ID: a18a10fe-3290-15de-99d1-e5513087cbe7
* Content: [Create and manage room mailboxes](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-room-mailboxes?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-room-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-room-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@nhoj01 thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
