### ISSUE TITLE
Article content seems incorrect

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-Exchange#2019]
The content of this article seems incorrect:
"Recipient limits between authenticated senders and recipients (typically, internal message senders and recipients) are exempt from the organizational message size restrictions."

Testing this on Exchange 2016 we can see that the limit set in TransportConfig (get-TransportConfig) takes priority.
Also receiveconnector settings will enforce MaxMessageSize.

---
#### Document Details:

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a512e6f-47ab-f785-a792-ef82a552c50f
* Version Independent ID: 16869db1-342d-13f2-ce24-0e13a49ec68d
* Content: [Message size and recipient limits in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/message-size-limits?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/mail-flow/message-size-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/message-size-limits.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@JeroenDronkers Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JeroenDronkers, thank you for your feedback.

I tried it with Outlook and it works for me:
- Exchange 2016 with the latest CU
- Org. limit = 50MB
- 2 test mailbox limit = 200MB
- I could send a 90MB PDF attachment

**Comment by JeroenDronkers** [comment]
Hello Dario,

Have you tried with using OWA?
I can easily reproduce it using OWA:

[cid:image001.png@01D63D71.EFBF78B0]

Thanks,


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

**Comment by dariomws** [comment]
Hi @JeroenDronkers, thanks your comment.

I cannot see the picture but yes, I have tried with OWA and then I changed to Outlook because there are more limits that apply to OWA:
https://docs.microsoft.com/exchange/architecture/client-access/client-message-size-limits#outlook-on-the-web

**Comment by JeroenDronkers** [comment]
Hello Dario,

Using Outlook, trying to send an attachment of 19mb internally, I get:

[cid:image002.png@01D63E4C.18360B80]

TransportConfig is configured as follows:
MaxReceiveSize                               : 10 MB (10,485,760 bytes)
MaxRecipientEnvelopeLimit                    : 5000
MaxSendSize                                  : 10 MB (10,485,760 bytes)

Both the sending and recipient mailboxes are configured as follows:
MaxSendSize       : Unlimited
MaxReceiveSize    : Unlimited

Exchange Server version:
Name                : EXCHANGE2016
Edition             : Enterprise
AdminDisplayVersion : Version 15.1 (Build 1913.5)


Many thanks


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

**Comment by JeroenDronkers** [comment]
Hello Dario,

I have raised the outlook limit since I expected that an outlook limit could interfere by adding a dword registry key: MaximumAttachmentSize and I set this to 30mb
Outlook 2016: HKEY_CURRENT_USER \ Software \ Microsoft \ Office \ 16.0 \ Outlook \ Preferences
Afterwards I was able to send an email of 18mb but got the following NDR for the (internal) email using Outlook

Delivery has failed to these recipients or groups:

administrator@ehlo365.co.uk (administrator@ehlo365.co.uk)<mailto:administrator@ehlo365.co.uk>
Your message is too large to send. To send it, make the message smaller, for example, by removing attachments.


The maximum message size that's allowed is 10 MB. This message is 18 MB.

Diagnostic information for administrators:

Generating server: Exchange2016.Contoso.lab

administrator@ehlo365.co.uk<mailto:administrator@ehlo365.co.uk>
Remote Server returned '550 5.2.3 RESOLVER.RST.RecipSizeLimit; message too large for this recipient'


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

From: Jeroen Dronkers
Sent: 09 June 2020 11:20
To: MicrosoftDocs/OfficeDocs-Exchange <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-Exchange <OfficeDocs-Exchange@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-Exchange] Article content seems incorrect (#2019)

Hello Dario,

Using Outlook, trying to send an attachment of 19mb internally, I get:

[cid:image002.png@01D63E5C.75C1B230]

TransportConfig is configured as follows:
MaxReceiveSize                               : 10 MB (10,485,760 bytes)
MaxRecipientEnvelopeLimit                    : 5000
MaxSendSize                                  : 10 MB (10,485,760 bytes)

Both the sending and recipient mailboxes are configured as follows:
MaxSendSize       : Unlimited
MaxReceiveSize    : Unlimited

Exchange Server version:
Name                : EXCHANGE2016
Edition             : Enterprise
AdminDisplayVersion : Version 15.1 (Build 1913.5)


Many thanks


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).

**Comment by dariomws** [comment]
Hi @JeroenDronkers, I cannot see your images.

From here:
https://docs.microsoft.com/powershell/module/exchange/set-mailbox
"In on-premises Exchange, the default value unlimited indicates the maximum receive size for the mailbox is imposed elsewhere (for example, organization, server, or connector limits)."

I also had to change the registry value. Also, remember that you need need to wait some hours after you change limits. Wait at least 2 hours.

But I cannot provide this help here as I confirmed that the article information about this behaviour is ok. Considering the nature of the issue, it is advised that please open a service ticket and follow with them for the resolution. We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by JeroenDronkers** [comment]
Hello Dario,

There is a Support ticket opened for this issue: 20102675

And, I believe that I (and the customer) can prove that the Organizational settings (transport config) are not ignored for internal email.

But anyway, if you want the article to stay as it is, fine with me.

Thanks,


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>

[abc]
﻿
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).
