### ISSUE TITLE
Please mention what does the user need to do to get it after this setting  and what to do if no public folder is showing in outlook ? 

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/OfficeDocs-Exchange#202]
Please mention what does the user need to do to get it after this setting  and what to do if no public folder is showing in outlook ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0f6d99e-005a-235f-dad0-ea1182669ab9
* Version Independent ID: 7bad943c-d900-84e2-95af-fa1bb0137110
* Content: [Set up public folders in a new organization](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@seaSide974 Thank you for this feedback

I will get this on over to the Exchange team for investigatoin and clerification. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jabrenneis** [comment]
Greeting. I'm wondering the same as @AndreaBarr - I have followed all the instructions in this document creating a public folder "Organizational Forms;" however, no one is able to view this form. I can view the public folder as it's listed under "Public Folders" > "Organizational Forms" > Mailbox = PFHierarcy.

In summary, what's the missing step that will allow all my users to view this folder in Outlook. Doesn't show for either 2013 or 2016 Outlook.

**Comment by AndreaBarr** [comment]
@MK-Kamal could you please investigate this issue?

**Comment by j0rt3g4** [comment]
Solving Issue on PR #1509

**Comment by mattpennathe3rd** [comment]
Appears to be fixed by #1509, but fee free to reopen if there is a remaining problem with this doc.
