### ISSUE TITLE
Not really fit for purpose for signatures

### ISSUE THREAD

**Issue by rcmpgi** [MicrosoftDocs/OfficeDocs-Exchange#2020]
It should be made clearer that the disclaimer is always added to the bottom of the entire message, and not the bottom of the most recent email body. This fact makes this feature unsuitable for use for mail signatures. Disclaimers, maybe, but not signatures.

It does seem crazy that the only way to sensibly add a centrally-managed mail signature in 365 email is by routing all your email through a third party service. So much for the high availability of Office 365 itself if I'm now at the mercy of somebody else's cloud service. Quite aside from the fact that the top-whack E5 package should come with "proper" signature functionality built-in.
Disappointing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a56bae-a3fc-43e8-1e5e-69c38971b2d8
* Version Independent ID: c68cbbac-56f7-32f5-1e9a-bbc1d58d091d
* Content: [Organization-wide disclaimers, signatures, footers, or headers in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mail-flow-rules/signatures?redirectedfrom=MSDN&view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/signatures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/signatures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@rcmpgi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @rcmpgi, thank you for your feedback and help us to improve docs.microsoft.com.

I think there are some information in the article:
"To make sure only the first message in a conversation gets a disclaimer, add an exception that prevents the disclaimer text from being applied to the same messages over and over again."

**Comment by rcmpgi** [comment]
No that doesn't help at all. If the first message in the conversation is inbound to my organisation, i.e. somebody emails me, and I then reply to this, my signature is placed **underneath their message**. The flow of content in the email from me back to them becomes as follows (with current functionality):
Reply from me
Their original message
Their signature
My signature

whereas it should obviously be:
Reply from me
My signature
Their original message
Their signature

But as far as I can tell the ability to detect the end of the body of the most recently sent email from me, and insert the signature there, does not exist, which is the missing piece of code to make this entire functionality useful for (I should imagine) the majority of users.

Even if you could just search for a predefined text string in the email and replace it with the signature that'd be better - at least then in Outlook and OWA all users could be told to put that same text string in, e.g. "##!!MyCompanySignature!!##" and the rule would just replace that text with the HTML signature for every message.

**Comment by dariomws** [comment]
Thank you for this information @rcmpgi. I can update the document with more information about how it works now.
To request a new feature or update the best place to leave your ideas is uservoice:
https://office365.uservoice.com/

**Comment by dariomws** [comment]
Also, server signatures are finally coming: 
https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=60371
https://outlook.uservoice.com/forums/322590-outlook-2016-for-windows/suggestions/19686520-email-signature-sync-across-devices

Maybe the next step will be manage this cloud signatures using PowerShell.

**Comment by scanum** [comment]
@rcmpgi Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
