### ISSUE TITLE
Inconsistent Powershell examples

### ISSUE THREAD

**Issue by 91jme** [MicrosoftDocs/OfficeDocs-Exchange#2022]
The Powershell commands under the "Enable ACLs on remote mailboxes" examples for Exchange 2013 and Exchange 2016 include the required filter for RemoteUserMailbox (Step 3 specifically), which prevents administrators applying the change to Resource Mailboxes.

The examples for Exchange 2010 don't include the filter, which they should.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions#enable-acls-on-remote-mailboxes)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@91jme  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @91jme, thank you for your feedback and help us to improve docs.microsoft.com.

I think that with Exchange 2010 you only have one object type returned by Get-RemoteMailbox: RemoteMailbox.

I don´t have a lab environment with Exchange 2010, if you have please could you share a screenshot when you run "Get-RemoteMailbox | ft RecipientTypeDetails"?

Thanks!

**Comment by dariomws** [comment]
@91jme, I got an Exchange 2010 and 2013 mixed environment to confirm it. But could you kindly share a screenshot if you have 2010 too?

Thanks!

**Comment by scanum** [comment]
@91jme  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
