### ISSUE TITLE
Option 3 licensing question

### ISSUE THREAD

**Issue by omeriniit** [MicrosoftDocs/OfficeDocs-Exchange#2024]
I got trial version from https://products.office.com/en-us/exchange/exchange-email-security-spam-protection
Now I have 25 EOP licenses and cannot assign them to anyone because "Exchange Online Protection (These licenses do not need to be individually assigned)." I can make contacts and connector but there's no difference if I have 1 license or 25 licenses. But that is true that EOP - This is the least expensive license that allows you to send email via Office 365.

Also it does not make sense if one paragraph says that sender does not need to be associated with an actual mailbox but another paragraph says that "If you have senders using devices or LOB applications who don't have an Office 365 mailbox license, obtain and assign an Exchange Online Protection license to each unlicensed sender."

"Your device or application can send email using any address (including ones that can't receive mail), as long as the address uses one of your domains. The email address doesn't need to be associated with an actual mailbox. For example, if your domain is contoso.com, you could send from an address like do_not_reply@contoso.com."

Please clarify how many licenses are needed and how can they be assigned to user accounts.

_Originally posted by @omeriniit in https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/1690#issuecomment-638986899_

**Comment by scanum** [comment]
@omeriniit  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @mattpennathe3rd Looks like we have a disparity here between what the UI states and the documentation states, can we get a confirmation from a SME on EOP Licensing if the EOP licenses need to be actually assigned ? Thanks

**Comment by get-itips** [comment]
Hello @omeriniit just wanted to tell you that I am still looking into this.

**Comment by tigattack** [comment]
This is still an issue and is pretty confusing for anyone reading the docs. What's the latest on this?
