### ISSUE TITLE
Add helpful images for NDR mailbox, Resend Process

### ISSUE THREAD

**Issue by MrsKay007** [MicrosoftDocs/OfficeDocs-Exchange#2027]
Please add an image of a mailbox containing NDRs with the Resend option. 
It would clarify these confusing instructions.  The journal terminology is repetitive making it difficult to understand.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598506d9-01d0-fd2e-2600-9b5557e427f1
* Version Independent ID: 88fdfd05-dcde-4745-03f4-fb271a3c7094
* Content: [Configure Journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/configure-journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/configure-journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/configure-journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@MrsKay007  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @MrsKay007 Thanks for your feedback. I am proposing thru a pull request the addition of an image I prepared. If it gets approval, it will be shown on the published version of the article.
Thanks

**Comment by scanum** [comment]
@MrsKay007 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
