### ISSUE TITLE
Countable nouns

### ISSUE THREAD

**Issue by rubberbenn** [MicrosoftDocs/OfficeDocs-Exchange#2028]
> >  Note
> 
> Even though cutover migration supports moving up to 2000 mailboxes, due to length of time it takes to create and migrate 2000 users, it is more reasonable to migrate 150 users or less.
> 

*150 users or _fewer_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@rubberbenn Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @rubberbenn

**Comment by scanum** [comment]
@rubberbenn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
