### ISSUE TITLE
Add additional clarity

### ISSUE THREAD

**Issue by sulobr** [MicrosoftDocs/OfficeDocs-Exchange#2030]
[Enter feedback here]
Can we please include more details on what OWA url needs to be used to login the mailbox after this change? I know there is a small note section under changes for organization relationship that mentions to use http:// and not https:// but it is not clear that customer will need to use http://cloudowa.contoso.com/owa in their browser when users need to access their mailbox and not just for the organization relationship settings.

Customers are expecting https://cloudowa.contoso.com/owa to continue working as they are used to with their onprem environment and this article doesn't state about having to use http://cloudowa.contoso.com/owa instead. 
Therefore it would cause less confusion if we can add clarification about need to use http://cloudowa.contoso.com/owa instead to login to mailbox and why they cannot use https://

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30c4fd6-0e69-cb9a-6a21-327f0ebae3a7
* Version Independent ID: d0217aa4-a37b-8837-4310-108fbf533a5d
* Content: [Simplify the Outlook Web App URL for Office 365 Hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/simplify-owa-url#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@sulobr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @sulobr, thank you for your feedback and help us to improve docs.microsoft.com.

The objective of this article is to continue using the same OWA URL they are using now on-premises. For example, https://mail.contoso.com/owa. I added a sentence to confirm it.

Also, they can use the HTTP URL.

**Comment by sulobr** [comment]
@dariomws Hi Dario, My understanding is they cannot use https:// version of the url. https://mail.contoso.com/owa user. If they do, they will get a cert error indicating the cert presented is only valid for O365 domains and not customer's domain. See sample error.

![image](https://user-images.githubusercontent.com/32208482/84073248-4913cb80-a985-11ea-9a12-907280b7fbad.png)

**Comment by dariomws** [comment]
There is an incorrect configuration scenario in which you can get this certification warning. I cannot provide you with this kind of help here, we only can update docs.microsoft.com articles.

Considering the nature of the issue, it is advised that please open a service ticket in your tenant and follow with them for the resolution. If you wish to know how to open the service ticket, please follow this link: https://docs.microsoft.com/office365/admin/contact-support-for-business-products
We will be very happy if you can share the outcome or resolution with us. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by scanum** [comment]
@sulobr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
