### ISSUE TITLE
Please clarify text

### ISSUE THREAD

**Issue by ArendvanDijk** [MicrosoftDocs/OfficeDocs-Exchange#2031]
Quote: > For example, Exchange Online uses the Exchange Server feature known as Database Availability Groups (DAGs) to replicate Exchange Online mailboxes to multiple databases in separate Microsoft datacenters.

Please clarify if the Exchange data is spread over multiple continents, or just multiple datacenters..

Regards,
Arend
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39a1f3ef-3137-603e-65ed-41a0fbd0cbb2
* Version Independent ID: c2bcddd7-cca5-3118-b810-12fda87b195f
* Content: [Back up email in Exchange Online](https://docs.microsoft.com/en-us/exchange/back-up-email#feedback)
* Content Source: [Exchange/ExchangeOnline/back-up-email.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/back-up-email.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@ArendvanDijk Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@ArendvanDijk Arend, how are you? Hope you are doing good.
I think this article will clarify the sentence for you https://docs.microsoft.com/en-us/office365/Enterprise/office-365-exchange-data-resiliency#database-availability-groups

**Comment by ArendvanDijk** [comment]
@get-itips Hi, I'm fine, you? Thanks for asking!
That's what I was looking for indeed, thanks! I need it for a design I am writing for a customer. Here I only want to refer to official Microsoft documentation. Thanks again!

**Comment by get-itips** [comment]
> @get-itips Hi, I'm fine, you? Thanks for asking!
> That's what I was looking for indeed, thanks! I need it for a design I am writing for a customer. Here I only want to refer to official Microsoft documentation. Thanks again!

Glad to help you! 
@scanum this thread can be closed.

**Comment by scanum** [comment]
@ArendvanDijk Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
