### ISSUE TITLE
System Requirements links to outdated KB article

### ISSUE THREAD

**Issue by JetzeMellema** [MicrosoftDocs/OfficeDocs-Exchange#2037]
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2019

Contains a link to KB2269838, https://support.microsoft.com/en-us/help/2269838/microsoft-exchange-compatibility-with-single-label-domains-disjointed. That KB article is outdated, discusses products that are no longer supported and contains broken links.

**Comment by scanum** [comment]
@JetzeMellema  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JetzeMellema Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
