### ISSUE TITLE
Can anyone help to figure out if I got hacked? (Not sure if I'm posting in the correct forum)

### ISSUE THREAD

**Issue by susanlbk** [MicrosoftDocs/OfficeDocs-Exchange#2039]
Trying to figure out where the trunk code is in this no that called me +60 84-818 606.
 +60 is country code for Malaysia & their NSN is 7 digits.
84- is the mobile prefix for Democrat of Congo with a ? mark for their NSN digits.
60-84 of the above phone no. does match part of this though, 60-84-BD MAC or OUI address look up. Did I just get hacked??? (I answered and was on line about a min.)
I may be on the wrong platform,but,Please,if someone can help me(I can't figure out the trunkcode)
Thank you
Susan
susanlbk62@gmail.com

**Comment by scanum** [comment]
@susanlbk Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by susanlbk** [comment]
I quite sure that I posted my question in the wrong forum.

Susan Bonk
