### ISSUE TITLE
Wrong Azure AD Connect Sync Interval

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-Exchange#2041]
This sync time is horribly outdated.  Has not been 3 hours for years...

Active Directory synchronization between the on-premises organization and the cloud, which is performed every three hours by a server running Azure Active Directory Connect, is a requirement for configuring a hybrid deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server hybrid deployments](https://docs.microsoft.com/en-us/exchange/exchange-hybrid#exchange-hybrid-deployment-considerations)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing and reporting @r-milne

**Comment by scanum** [comment]
@r-milne Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
