### ISSUE TITLE
Typo in para 6 of the SSO section

### ISSUE THREAD

**Issue by nonodename** [MicrosoftDocs/OfficeDocs-Exchange#2046]
...Outlook for iOS **for** Android will... 

should be 
...Outlook for iOS **and** Android will...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeec798c-00f4-df45-da44-47e5aac06ff9
* Version Independent ID: 4cdfab74-fce7-f298-c3df-51da100c2162
* Content: [Account setup with modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@nonodename  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing and reporting @nonodename

**Comment by scanum** [comment]
@nonodename Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
