### ISSUE TITLE
there is no way to search for Fax partners on the link provided

### ISSUE THREAD

**Issue by bertsawicki** [MicrosoftDocs/OfficeDocs-Exchange#2050]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1b95716-d62a-5b7b-5324-75eed5f4f10b
* Version Independent ID: da1f6e50-8015-0afa-1294-6427e7468300
* Content: [Setting up incoming faxing in Exchange Online](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-client-voice-mail-features/set-up-incoming-faxing)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/set-up-incoming-faxing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/set-up-incoming-faxing.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@bertsawicki  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @bertsawicki, thank you for your feedback.

The Unified Messaging service in Exchange Online is out of support as of February 28, 2020, at 5 PM Pacific Time. All voicemail accounts have been migrated to Cloud Voicemail service by Microsoft.
I have added a note in this article to explain this situation.

**Comment by scanum** [comment]
@bertsawicki Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
