### ISSUE TITLE
Please put large banners up on pages like this one for a deprecated feature - its misleading to customers.

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/OfficeDocs-Exchange#2052]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fbfc5e-6947-c63c-6fe0-7a512c126692
* Version Independent ID: d5aa7a08-14e8-f44a-3443-dbf4215b326f
* Content: [Navigating menus with Outlook Voice Access in Exchange Online](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-client-voice-mail-features/navigating-menus-with-outlook-voice-access)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/navigating-menus-with-outlook-voice-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/navigating-menus-with-outlook-voice-access.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@chrislehr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@chrislehr Chris, how are you?
Currently, the [top level](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/voice-mail-unified-messaging) section article of the article you referenced has a banner (note) stating the following:

> Cloud Voicemail takes the place of Exchange Unified Messaging (UM) in providing voice messaging functionality for Skype for Business 2019 voice users who have mailboxes on Exchange Server 2019 or Exchange Online, and for Skype for Business Online voice users. For more information please check Plan Cloud Voicemail service and Retiring Unified Messaging in Exchange Online.

![image](https://user-images.githubusercontent.com/36666927/84899961-c7f0be80-b07f-11ea-93b3-2384523d70be.png)


With links to other articles on retiring the service, and [one](https://docs.microsoft.com/en-us/skypeforbusiness/plan/exchange-unified-messaging-online-migration-support) of them mentions what is not supported:

> PSTN subscriber access is not supported in CVM. 

I understand that you are looking for something with more emphasis maybe?

**Comment by scanum** [comment]
@chrislehr We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
