### ISSUE TITLE
Incomplete information - PrimarySmtpAddress

### ISSUE THREAD

**Issue by 9073241516** [MicrosoftDocs/OfficeDocs-Exchange#2055]
[Enter feedback here]

Can you update this article to instruct how to set the 'PrimarySmtpAddress'??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488ecf85-5f6d-3abd-4253-8527b5082340
* Version Independent ID: ec414c0f-4ee4-bbd1-3851-3e4db0c97593
* Content: [Shared mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@9073241516  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @9073241516 
How are you?
You can find information on how to set email addresses [here](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/email-addresses?view=exchserver-2019&viewFallbackFrom=exchonline-ww), the process is no different from the general process of adding  and setting email addresses for a mailbox.

> The address with the case-sensitive qualifier SMTP is the primary SMTP address. You have to include all email addresses for the mailbox when you use this command syntax. If you don't, the addresses specified in the command will overwrite the existing addresses.

Hope this information helps you,

**Comment by scanum** [comment]
@9073241516 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
