### ISSUE TITLE
DBEB (Directory Based Edge Blocking) change on June 9, 2020 affecting Dynamic Distribution Groups

### ISSUE THREAD

**Issue by bubba198** [MicrosoftDocs/OfficeDocs-Exchange#2056]
Hi everyone,

On June 9, 2020 some change occurred with DBEB (Directory Based Edge Blocking) affecting Dynamic Distribution Groups ONLY. I'm very certain of the date since I have traces going back a year as evidence that Dynamic Distribution Groups were able to receive e-mail just fine. Now access denied NDR. After days of dysfunctional exchanges with the vendor outsourced support the recommendation was to either a) disable DBEB (Directory Based Edge Blocking) for the entire tenant or b) change my-domain.onmicrosoft.com under Accepted domain management from Authoritative to "Internal Relay"

I would like this issue resolved so that neither DBEB is disabled NOR set the domain to "Internal Relay" for Dynamic Distribution Groups to accept outside e-mail? Just like it was for the past 3 years or so

Whatever happened on June 9 there were other anomalies such as new users NOT replicating to DBEB and as a result getting NDR while internal e-mail to those newly added users worked just fine. Support "did something" to force the replication of newly added users and eventually it worked but I find this to be too coincidental with Dynamic Distribution Groups stopping to work?

Theretofore the document which says that Dynamic Distribution Groups are not replicated to DBEB is false (how did it work for the past 3 years then)

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking

Thank you

**Comment by scanum** [comment]
@bubba198 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by bubba198** [comment]
@scanum Thank you, I did. No coherent outcome, support claims that the current state of DBEB functionality regarding dynamic groups has always been this way and it is by design - which is false of course since it worked for years before June 9, 2020. Maybe it was broken all this time and Microsoft fixed it - wither way it is a major problem now for dynamic group administrators.
