### ISSUE TITLE
PowerShell Fix

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#2057]
For fixing the on-prem GAL issue, the PowerShell actually needs to use the DN of the group, not the group name

Instead of :
Update-Recipient "[group name]"

It should be:
Update-Recipient -Identity "[group DN from AD]"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Microsoft 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback and help us to improve docs.microsoft.com.

I understand that the possible values for the -Identity parameter are:
- Name
- Alias
- Distinguished name (DN)
- Canonical DN
- Email address
- GUID
So, the group name should work. More information:
https://docs.microsoft.com/powershell/module/exchange/update-recipient

Also, you can avoid writing the -Identity parameter and use the value directly.

**Comment by danmyhre** [comment]
Using the name doesn't work.  You get an error that the object couldn't be found.  This happens in a multi-domain AD forest (which many hybrid environments will have).  If you use the -IgnoreDefaultScope param, you must us DN, not name.

Understood on the shorthand, but docs should always be verbose and include the actual parameters.

**Comment by mattpennathe3rd** [comment]
@danmyhre Thank you for submitting this. Dario completed a fix and I will merge it shortly, so the updates should be published in the near future. Thanks again for your help.
