### ISSUE TITLE
Clarify the retention of Purges folder

### ISSUE THREAD

**Issue by dmyers-smartstart** [MicrosoftDocs/OfficeDocs-Exchange#2064]
Can something be added the clarifies the retention period of items in the Purges folder when Single Item recovery is turned on?
It is not clear to me if items remain in the Purges folder an additional 14 days by default, or if it uses the same retention date the item had in the Deletions folder.
e.g. With Single Item recovery turned on, would an item that has been in the deletions folder for 14 days be purged from the system? or moved to the Purges folder for another 14 days?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbbc82b-b1c8-f2b7-9f57-9fa9137305a3
* Version Independent ID: f1ce321a-ed5e-fe57-450d-35cc7b104350
* Content: [Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder#recoverable-items-mailbox-quotas)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@dmyers-smartstart @ Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dmyers-smartstart, thank you for your feedback and help us to improve docs.microsoft.com.

There is only a deleted item retention period for the entire Recoverable Items folder and their subfolders. If single item recovery is enabled, messages that are permanently deleted (purged) by the user are retained in the Purge subfolder of the mailbox until the deleted item retention period expires.

The following sentences are currently in the article and detail this information I think:

 > Items remain in the Deletions subfolder until the deleted item retention period is reached.

> After the deleted item retention period expires, the item is moved to the Purges subfolder and is no longer visible to the user. When the Managed Folder Assistant (MFA) processes the mailbox, items in the Purges subfolder are purged from Exchange Online.

> If an item is removed from the Deletions subfolder, either by a user purging the item by using the Recover Deleted Items feature or by an automated process such as the Managed Folder Assistant, the item can't be recovered by the user. When the Managed Folder Assistant processes the Recoverable Items folder for a mailbox that has single item recovery enabled, any item in the Purges subfolder isn't purged if the deleted item retention period hasn't expired for that item. This means that an admin can still recover the item by using an eDiscovery tool such as In-Place eDiscovery or Content Search.

If you don't agree, please let me know.

**Comment by scanum** [comment]
@dmyers-smartstart  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
