### ISSUE TITLE
Square brackets for some versions on version page

### ISSUE THREAD

**Issue by maaaaz** [MicrosoftDocs/OfficeDocs-Exchange#2067]
Hello,
Some square brackets recently appeared for some versions on https://docs.microsoft.com/en-US/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019

For instance `"[Exchange Server 2019 CU4]"`.

Can you remove them ?
Cheers.

**Comment by scanum** [comment]
@maaaaz Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Fixed on https://github.com/MicrosoftDocs/OfficeDocs-Exchange/commit/f5c146c15a672f869db2e42551e4a32c4e8222cd
Thanks!
@scanum please close
