### ISSUE TITLE
Google UI Changes

### ISSUE THREAD

**Issue by KRSIT-KO** [MicrosoftDocs/OfficeDocs-Exchange#2072]
Currently doing another GSuite migration after having done one a few months ago. Some google steps need to be updated:

- In "Create a Google Service Account," step 5, the option to create a key no longer shows. You have to create the service account first, go into the service account, then click the Edit button in order to enable domain-wide delegation and create a key. It also asks to configure a consent screen when enabling delegation.

- In "Grant access to the service account for your Google tenant", I could not find "Manage API client access" anywhere on the Google Admin dashboard. I had to Google and punch in the direct URL: https://admin.google.com/AdminHome?chromeless=1#OGX:ManageOauthClients. However, after making the change, it appears that screen reflects this item in the new interface: Security > Advanced Settings > Manage Domain-Wide Delegation. There is also no indication of permissions--just a list of scopes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@KRSIT-KO Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @KRSIT-KO, thank you for your feedback and help us to improve docs.microsoft.com.

This article was updated 10 days ago to reflect updates on Google UI. Please, let us know if you think that there are still missing updates:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2118

**Comment by scanum** [comment]
@KRSIT-KO  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
