### ISSUE TITLE
Please replace AD Connect with ADFS

### ISSUE THREAD

**Issue by fabrizob** [MicrosoftDocs/OfficeDocs-Exchange#2073]
This sentence

"In addition to a server running Azure AD Connect, you'll also need to deploy a web application proxy server if you choose to configure AD FS. This server should be placed in your perimeter network and will act as an intermediary between your internal **Azure AD Connect server** and the Internet."

should be changed to
"In addition to a server running Azure AD Connect, you'll also need to deploy a web application proxy server if you choose to configure AD FS. This server should be placed in your perimeter network and will act as an intermediary between your internal **ADFS servers** and the Internet."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server hybrid deployments](https://docs.microsoft.com/en-us/exchange/exchange-hybrid)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by fabrizob** [comment]
Adding screenshot

![image](https://user-images.githubusercontent.com/41018953/85618983-e2b7ca00-b661-11ea-8988-3036f274e47d.png)

**Comment by scanum** [comment]
@fabrizob Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your report @fabrizob
