### ISSUE TITLE
The Article Setup A Multifunction Device is no longer available 404 error

### ISSUE THREAD

**Issue by microsoftsearch** [MicrosoftDocs/OfficeDocs-Exchange#2074]
The related article
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office

Is completely missing and I hope it can be reinstated because it contains information not in any additional articles. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b5e01ad-4656-ca35-3b3d-41efdae39cd9
* Version Independent ID: 54b8031d-44b9-296e-f006-47e8cc835d1e
* Content: [Fix issues with printers, scanners, and LOB applications that send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @microsoftsearch 
Here it is

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365

The filename was renamed it seems, that was the reason of the 404, but it works from the link on the referenced article and from the TOC.

Thanks

**Comment by scanum** [comment]
@microsoftsearch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
