### ISSUE TITLE
Nothing on here about Azure AD "Secure Defaults" being able to block SMTP auth irrespective of these settings.

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/OfficeDocs-Exchange#2075]
As per title. We enabled "secure defaults" in Azure AD recently. Later on a particular application failed to authenticate against an office 365 mailbox. Searching the particular error leads to this documentation suggesting SMTP auth needs to be enabeld against the mailbox. It was enabled. There was nothing in this doc to suggest that the setting may be completely redundant by Azure AD Secure Defaults.

Arguably this should even be a product enhancement. If SMTP authentication is blocked by a conditional access policy (or Azure Defaults) in Azure AD, it would be nicer if the UI showed some indication of this when you try to change the SMTP authentication setting on the mailbox. Perhaps when enabling SMTP authentication it could also provide a "validate" or "test" button, that attempts to connect to the mailbox by smtp to verify its working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f463d2b-dfa3-1061-4e34-01fdfd8b5032
* Version Independent ID: a1d6d284-1c4c-438d-caaa-b06f7a7fb8a8
* Content: [Enable or disable SMTP AUTH](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws** [comment]
Hi @dazinator, thank you for your feedback and help us to improve docs.microsoft.com.

There is a note in the article about security defaults:
"If you've enabled security defaults in your organization, SMTP AUTH is already disabled in Exchange Online. For more information, see What are security defaults?."

It was there since Dec 5, 2019.

**Comment by dazinator** [comment]
@dariomws that's right! Not sure how I missed that to be honest. Thanks for clarifying, closing
