### ISSUE TITLE
Circle of false claims - "Organization allowed accounts mode"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#2076]
This page says this:

> Organization allowed accounts mode settings
> Outlook for iOS and Android offers administrators the ability to restrict email and storage provider accounts to only corporate accounts. For more information on organization allowed accounts mode, please see [Account setup with modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication#organization-allowed-accounts-mode).

However, that page says this:

> For more information on the settings that need to be configured to deploy Organization Allowed Accounts mode, please see the Organization allowed accounts mode section in [Deploying Outlook for iOS and Android App Configuration Settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#organization-allowed-accounts-mode-settings).

So both pages think they got off the hook easy, BUT, eventually one of these two  pages is going to have to cough up the details.  Supplemental FYI: there's a user voice request about this feature and something fairly negative about it.  Here's that link: https://microsoftintune.uservoice.com/forums/291681-ideas/suggestions/38793805-allow-shared-mailbox-in-app-configuration-profile.  Essentially, when you enable Work accounts only mode, users are unable to add a new Shared mailbox.  So you have to turn off Work accounts only mode if you want users to be able to add Shared mailboxes.

I propose the following changes, which I can do, or you can - whichever is best (just let me know):

1.) Put explanations and screenshots here on this page about "Organization allowed accounts mode settings" (i.e. "Allow only work or school accounts" in Intune App Configuration profile for Outlook mobile app).

2.) Within that section, a purple informational note about how, to enable users to add Shared mailboxes, you must also allow them the capability to add personal accounts.

Would you like to take a stab at this, or would you be OK with or rather me do it?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#organization-allowed-accounts-mode-settings)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@JeremyTBradshaw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @JeremyTBradshaw Jeremy, how are you?

As the documentation is open-sourced, anyone can contribute to it thru a Pull Request, feel free to submit a pull request, and it will be reviewed by the team and if it gets approval, your contributions will be shown on the online version of the article.

Thanks

**Comment by JeremyTBradshaw** [comment]
@get-itips I am good thanks, and you?  Also, sounds good.  I will take a stab at this and submit a PR soon.  Thanks.
