### ISSUE TITLE
Update Note on Dynamic Distribution Groups

### ISSUE THREAD

**Issue by lonstev** [MicrosoftDocs/OfficeDocs-Exchange#2078]
The second note section indicates:

"In hybrid environments, dynamic distribution groups do not sync to AAD and are therefore blocked by DBEB. As a work around, you can create a mail contact with the same external email address of the blocked dynamic distribution group."

This is misleading for customers because it infers that it is only applicable in a hybrid environment when this functionality exists for Exchange Online regardless of whether the environment is hybrid or not.  Can we change the note as follows?

"Dynamic distribution groups do not sync to AAD and are therefore blocked by DBEB. As a work around in a hybrid environment, you can create a mail contact with the same external email address of the blocked dynamic distribution group."

This will help clarify the workaround and highlight that this applies to Exchange Online whether or not the customer has configured hybrid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb394c8-1004-a253-7806-71fdc9406478
* Version Independent ID: 1f4e3200-3025-5def-851e-3d56f815c2ff
* Content: [Use Directory Based Edge Blocking to reject messages sent to invalid recipients](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@lonstev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @lonstev 
How are you?
Hope you are doing good.

The current sentence states

> **In hybrid environments**, dynamic distribution groups do not sync to AAD and are therefore blocked by DBEB. As a work around, you can create a mail contact with the same external email address of the blocked dynamic distribution group.

And you are proposing this

> "Dynamic distribution groups do not sync to AAD and are therefore blocked by DBEB. As a work around **in a hybrid environment**, you can create a mail contact with the same external email address of the blocked dynamic distribution group."

That is essentially moving the _In a hybrid environment_ sentence.

However at the beginning of the article it says in bold

> If all recipients for your domain are in Exchange Online, DBEB is already in effect, and you don't need to do anything. 

To my understanding, it is clear that you have to apply that workaround in a hybrid environment scenario only, however if I misunderstood you please clarify it to me.

Thanks

**Comment by lonstev** [comment]
Hello Andres,

Thank you for the follow up.   What I am trying to communicate with this change is that DBEB does not work with dynamic distribution groups—at all.  While yes, it is enabled by default, whether the environment itself is hybrid or not is irrelevant.  DBEB does not work with dynamic distribution groups in O365.  The wording on that workaround suggests that dynamic distribution groups don’t work in hybrid environments only, when really that workaround is specific to hybrid environments.

This why I propose moving the ‘In hybrid environments’.  As suggested, it would clarify that DBEB does not work with DDGs in Office 365 and that this workaround is applicable to hybrid environments.

Please let me know if that helps or if I can provide any additional information.

Thanks,

Lonny

**Comment by get-itips** [comment]
@lonstev Lonny,
Let's do this, I will make a PR to propose your idea, someone from the team will review the change, and if it goes thru, it will be published.
Thanks
