### ISSUE TITLE
Old URL for this page not redirecting to new URL

### ISSUE THREAD

**Issue by jmeddy** [MicrosoftDocs/OfficeDocs-Exchange#2079]
The old URL for this page:

https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3

does not redirect to the new URL:

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365

and 404s with a MS Robot page which also has a broken URL. Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0e0099d-a943-ac86-dca6-ec20616abfcb
* Version Independent ID: dbe3869c-054a-500d-094d-b00e8509e88a
* Content: [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@jmeddy Thanks for pointing this out. I've submitted a fix and it should be functional in the near future. Thanks again for your help.
