### ISSUE TITLE
Double mention of a migration batch status

### ISSUE THREAD

**Issue by ArendvanDijk** [MicrosoftDocs/OfficeDocs-Exchange#2082]
Good afternoon, first of all thank you for the great documentation. Fortunately it keeps getting better.

Under migration batches > Column 'status' you will see twice the status '**stopped**', with different explanations. Please correct this!

Tnx!
Regards,
Arend
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a684ff-29af-b532-deea-01fecbd6b8cb
* Version Independent ID: a90ceb5c-8553-2636-ab85-14688435ee4d
* Content: [Manage migration batches](https://docs.microsoft.com/en-us/exchange/mailbox-migration/manage-migration-batches)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/manage-migration-batches.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/manage-migration-batches.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@ArendvanDijk Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@ArendvanDijk  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
