### ISSUE TITLE
.Count property doesn't work properly with this script

### ISSUE THREAD

**Issue by 50monkeys** [MicrosoftDocs/OfficeDocs-Exchange#2087]
If I use this script with the .count property, it works only if the Dynamic Distribution Group contains 0 or 2 or more members, but not with 1 member. If the group contains only one member, (Get-Recipient -RecipientPreviewFilter $FTE.RecipientFilter -OrganizationalUnit $FTE.RecipientContainer).Count returns nothing. If the group is empty, the value is correctly returned as 0. If the group has 2 or more members, the value is correct. Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a9ec7c-b6a2-11bc-00a8-66c0b762a5d8
* Version Independent ID: ce530938-ecfd-c52b-e70f-5db0ccd6e880
* Content: [View members of a dynamic distribution group](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-dynamic-distribution-groups/view-group-members)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/view-group-members.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/view-group-members.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@50monkeys Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
