### ISSUE TITLE
Unclear Documentation concerning Mailusers.

### ISSUE THREAD

**Issue by alphaz18** [MicrosoftDocs/OfficeDocs-Exchange#2089]
At the very top of the documentation of this GSuite migration page that , it is mentioned that azure ad connect is required. 
that means that users are sync'ed from AADC. which is fine. then further down it says you must create/provision the Mailusers for all the users. however it does not say how. 

If your users are on-prem sync'ing to Azure Ad, how can you provision them as a Mailuser without exchange hybrid on-prem? This is because you can only run enable-mailuser if you have exchange onprem installed. but if your mail is on Gsuite. No one would have exchnage hybrid on-prem installed.. 

The documentation does not mention anything about this fact or how to provision users as mailusers for users sync'ed from Azure AD Connect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@alphaz18 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@alphaz18  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
