### ISSUE TITLE
Slowing down emails

### ISSUE THREAD

**Issue by PhillStone9** [MicrosoftDocs/OfficeDocs-Exchange#209]
Hello, I would like to know on how can I change the rate and number of emails that I receive on my Outlook email? 
Thank you.

**Comment by AndreaBarr** [comment]
@PhillStone9 Thank you for this feedback

I am not quite sure how to chang ethe rate and number of emails recieved to an Outlook email. Let me get this over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@PhillStone9 do you have a question about a specific topic? If not, I would suggest filing a support case with Microsoft.
