### ISSUE TITLE
Is Gmail for Outllook Web discontinued?

### ISSUE THREAD

**Issue by sagarpomal** [MicrosoftDocs/OfficeDocs-Exchange#2090]
Is Gmail for Outllook Web discontinued? I'm not able to connect my gmail to Outlook web in my office 365 account. Please refer the below link:
https://support.microsoft.com/en-us/office/connect-email-accounts-in-outlook-on-the-web-microsoft-365-d7012ff0-924f-4f78-8aca-c3912d886c4d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62f5860-4f99-6794-f8d6-2207b7f19979
* Version Independent ID: c28b87f8-1984-6522-021f-bae92e46d08c
* Content: [Prepare your Gmail or G Suite account for connecting to Outlook and Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@sagarpomal Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by sagarpomal** [comment]
@scanum I reached out to the support and they said that Gmail or any other email accounts in OWA has been discontinued.
