### ISSUE TITLE
Reference to offboarding as opposed to onboarding 

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-Exchange#2091]
This link doesn't make sense
For more information about how to move mailboxes in an Exchange 2010-based hybrid deployment, see Move an Exchange Online mailbox to the on-premises organization. That's offboarding. Do you have links for onboarding in a purely 2010 hybrid scenario? Not mixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server hybrid deployments](https://docs.microsoft.com/en-us/exchange/exchange-hybrid)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jebalert Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jebalert Joseph, how are you?
Thanks for your feedback.

If you click on the provided link you will find this at the beginning of the article

> To learn how to move a mailbox to the Exchange Online organization, see the topic for the version of Exchange installed in your on-premises organization:
> Move or create mailboxes in an Exchange 2003 hybrid deployment
> Move or Create a Mailbox for an Exchange 2007 Hybrid Deployment
> Move or Create a Mailbox for an Exchange 2010 Hybrid Deployment

Those links, however not anymore regularly updated, still work.

Hope this information helps you,
Thanks

**Comment by jebalert** [comment]
Hey, maybe there was some confusion. I’m looking for some more reasoning behind 2016 hybrid being strongly recommended in this article. Trying to understand if it’s simply stance due to exchange 2010 EOL approaching in October or if it’s something deeper than that. Thanks.

**Comment by get-itips** [comment]
Hello again @jebalert Joseph
I am not the author of the article however from my experience and point of view, other than the benefits of running the most updated and supported version of a piece of software, general procedure articles like that one usually reflect and mention the latest version of a product as the main reference, (yes, this article should be updated soon to mention Ex2019 however the process is the same for Ex2016), although the procedure for previous versions is still provided (on the referenced link).
Hope this information clarifies it to you. Thank you

**Comment by scanum** [comment]
@jebalert Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
