### ISSUE TITLE
What is the logic behind the strong recommendation of using 2013 in conjunction with 2010?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/OfficeDocs-Exchange#2092]
If it's not a requirement please backup the strong recommendation

**Comment by scanum** [comment]
@jebalert Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jebalert** [comment]
Hey, maybe there was some confusion. I’m looking for some more reasoning behind 2016 hybrid being strongly recommended in this article. Trying to understand if it’s simply stance due to exchange 2010 EOL approaching in October or if it’s something deeper than that. Thanks.
