### ISSUE TITLE
Typographical error

### ISSUE THREAD

**Issue by qosobrin** [MicrosoftDocs/OfficeDocs-Exchange#2093]
There is a missing "m" letter after the comma in the first line of the first paragraph of this page. 

> In Exchange Online organizations, **ail** contacts are mail-enabled objects

should change to

> In Exchange Online organizations, **mail** contacts are mail-enabled objects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 601b7a39-638c-759b-4ba2-47171cdfd542
* Version Independent ID: f2f399ee-5d99-212b-5b21-0feb1c8aee08
* Content: [Manage mail contacts](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-contacts?source=docs)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-contacts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-contacts.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@qosobrin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
