### ISSUE TITLE
GAL name is wrong

### ISSUE THREAD

**Issue by bobdonkey** [MicrosoftDocs/OfficeDocs-Exchange#2097]
'You can't modify the GAL named Default Offline Address Book'
This should read: 
'You can't modify the GAL named Default Global Address List'
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2985bc-3016-dc63-efe6-56f221b2eb04
* Version Independent ID: e2af137a-79ed-63c7-2d13-6f9ced8d71d7
* Content: [Configure global address list properties in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-lists/configure-global-address-list-properties)
* Content Source: [Exchange/ExchangeOnline/address-books/address-lists/configure-global-address-list-properties.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/address-lists/configure-global-address-list-properties.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@bobdonkey Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing and reporting @bobdonkey
