### ISSUE TITLE
"Add" button missing after selecting public folder to add to OWA (after adding to Outlook 2016).

### ISSUE THREAD

**Issue by knyhus** [MicrosoftDocs/OfficeDocs-Exchange#2098]
[Enter feedback here]
I can right-click "Folders" and say "Add public folder"
I can nav and locate the PF
I can select it
but THERE IS NO 'ADD' BUTTON (Firefox latest ver - 78 or something) so the action FAILS
I have minimized my screen to tiny (cntrl - minussign) and nothing
have clicked 'tab' and 'enter' to try to find an invisible button (no)
have tried clicking in blank space (no)
please advise
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1322ea00-e4ee-5858-c224-c8b886f6a7d0
* Version Independent ID: 059da329-0f7f-cd54-31d7-cdec5eda9141
* Content: [Use favorite public folders in Outlook on the web](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/use-favorite-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by knyhus** [comment]
Just figured it out: the 'add public folder' is ABOVE the list of PFs.
This looked like a *title bar* to, so it didn't occur to me this was an action button. It should be BELOW and TO THE RIGHT of the PFs list (like every other 'SAVE,' 'ADD' etc. button on the web. IMHO.
Thanks

**Comment by scanum** [comment]
@knyhus Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
