### ISSUE TITLE
Outlook 2010 updates

### ISSUE THREAD

**Issue by hoogenboom** [MicrosoftDocs/OfficeDocs-Exchange#21]
Outlook 2010 Updates KB2956191 and KB2965295 have been superseded by KB4022137 and KB4022205 respectively as of July 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange 2016 system requirements](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by kenwith** [comment]
@hoogenboom - great catch, and thanks for submitting. I added a clarifying for latest updates with this PR: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/47   My thinking was that the latest updates should be called out since updates can change. Thanks!
