### ISSUE TITLE
Clarification on Internal Relay

### ISSUE THREAD

**Issue by jdfoxmicro** [MicrosoftDocs/OfficeDocs-Exchange#210]
This article says you have to set a domain to Internal Relay, wait until you have all your users loaded or synced, and then change it to Authoritative.

But why would that be here in an article about how to use DBEB?  It doesn't say this process of toggling your domain applies specifically to a migration to Office 365, which is where you might use Internal Relay.  Bringing this up makes it confusing.  It should just say that so long as your domain is set to Authoritative, DBEB will be in effect, and messages to any user accounts that aren't present in Office 365 yet will be rejected.  The way it's written, it implies you have to toggle to Internal Relay and back just to enable DBEB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb394c8-1004-a253-7806-71fdc9406478
* Version Independent ID: 1f4e3200-3025-5def-851e-3d56f815c2ff
* Content: [Use Directory Based Edge Blocking to reject messages sent to invalid recipients](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by AndreaBarr** [comment]
@jdfoxmicro Thank you for this feedback

I will get this over to the Exchange team for investigation for the placement and working of this in the article. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@jdfoxmicro I fixed this.

Thanks for the feedback.
