### ISSUE TITLE
 App password  not hidden properly

### ISSUE THREAD

**Issue by svandegar** [MicrosoftDocs/OfficeDocs-Exchange#2100]
[Enter feedback here]
The app password is not hidden properly in this tutorial. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62f5860-4f99-6794-f8d6-2207b7f19979
* Version Independent ID: c28b87f8-1984-6522-021f-bae92e46d08c
* Content: [Prepare your Gmail or G Suite account for connecting to Outlook and Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@svandegar Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for noticing and reporting @svandegar
