### ISSUE TITLE
Link to "see Validate connectors" just reloads the same page

### ISSUE THREAD

**Issue by marcusmills** [MicrosoftDocs/OfficeDocs-Exchange#2102]
Can it link to something a bit more informative, please?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e113579e-5da4-50e4-bb37-cfd0a8907b50
* Version Independent ID: 4c59d5fe-ebc6-9fc3-bee5-2db0c5cac501
* Content: [Validate connectors](https://docs.microsoft.com/en-gb/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/validate-connectors)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/validate-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/validate-connectors.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@marcusmills We appreciate any feedback that improves the content in the Microsoft docs and will take this into consideration on new updates.
