### ISSUE TITLE
Organization Sharing with Individual Sharing

### ISSUE THREAD

**Issue by TimAbmgf** [MicrosoftDocs/OfficeDocs-Exchange#2103]
At this time, I have an Organization Sharing policy for 2 tenants between each-other to show Limited Details.

within Individual Sharing 'Sharing with All Domains' is listed with only free busy.

when any user tries to view limited details for a mailbox in the other tenant, they are only seeing free busy data.

If there are some processes that force the default individual sharing to supersede configurations in Organizational Sharing; it should be in the documentation.

I currently have a ticket opened for this; still trying to figure this out.

**Comment by scanum** [comment]
@TimAbmgf Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
