### ISSUE TITLE
Journal mailbox location

### ISSUE THREAD

**Issue by santcliff** [MicrosoftDocs/OfficeDocs-Exchange#2104]
Previous Journaling documentation says that the journal mailbox cannot be in Exchange Online.   But this page does not mention that.  

Experimentally it looks like it is still not possible to use an Exchange Online mailbox as the destination of the Journal.  

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d49df7f-4717-d51e-b1b9-5a5a4768a1d9
* Version Independent ID: af6d6557-eb97-6aba-4511-c64e951ab31f
* Content: [Manage journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/manage-journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by michelderooij** [comment]
Linked article "Journaling in Exchange Online" states, "You can't designate an Exchange Online mailbox as a journaling mailbox."

**Comment by scanum** [comment]
@santcliff  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
