### ISSUE TITLE
Azure AD-Connect "Exchange Hybrid Deployment" unaddressed? Missed Step?

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/OfficeDocs-Exchange#2105]
Maybe I've missed it,
But the documentation does not tell the user if they should leave the "Exchange Hybrid Deployment" option enabled in Azure AD Connect, or if it should be disabled.

It seems very relevant for this page, since it's about disabling Hybrid.
Seems like a missed step.

Edit--- I think this somehow got posted in the wrong section? (not on the page I was referencing)
https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange

**Comment by michelderooij** [comment]
What page are you referring to? Is this about if you need to reconfigure ADConnect after decomissioning Exchange?
Unless I misread your question, it's mentioned in scenarios section in that same doc, e.g. https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#common-scenarios

**Comment by Krytical13** [comment]
We have followed Scenario 2 steps 1-5.

However, these steps do not inform us of the necessity to go back into the "Azure AD Connect" utility, and un-check the box for "Exchange Hybrid Deployment"

Or if that box should remain checked, even after we have removed the Hybrid configuration.
[https://i.imgur.com/GpxH923.png](url)

**Comment by scanum** [comment]
@Krytical13  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Krytical13, thank you for your feedback and help us to improve docs.microsoft.com.

The Exchange Hybrid Deployment feature allows for the co-existence of Exchange mailboxes both on-premises and in Office 365. Azure AD Connect is synchronizing a specific set of [attributes](https://docs.microsoft.com/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#exchange-hybrid-writeback) from Azure AD back into your on-premises directory.

I'll add a note about this, but it's recommended that you leave this feature enabled in Azure AD Connect.

**Comment by Krytical13** [comment]
So if I understand correctly, as long as we have no mailboxes on-premises (Scenario 2), then that check box shouldn't matter one way or another as the attributes it is syncing are related to mailboxes.

We will leave the box checked at this time,  but if I ever left the company, I could see another admin un-checking that box, 
as it is no longer accurate to say we are in a hybrid deployment.

Happy to help with the docs when I can! they/you help me more then I help them/you!
Thank you for the quick response!

**Comment by dariomws** [comment]
@Krytical13, yes, but remember that in this scenario you'll always have to create Exchange Online mailboxes in your on-premises admin center (or PS) as remote mailboxes. Then AAD Connect will sync the attributes to Azure AD, then you can enable the EXO license.
I think you won't have an impact if you disable this feature, but I have some doubts about msDS-ExternalDirectoryObjectID and msExchArchiveStatus attributes. I'm trying to confirm it.
