### ISSUE TITLE
The Gsuite Migration guide needs to be updated

### ISSUE THREAD

**Issue by CordlezToaster** [MicrosoftDocs/OfficeDocs-Exchange#2106]
Hi Team,

This guide needs to be updated ASAP as Google has changed a lot of things on their side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@CordlezToaster Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by CordlezToaster** [comment]
Awesome thats great news!, i attempted a migration over the weekend for a customer and ran into issues with the guide being out of date and Microsoft Exchange Migrations being in a degraded state.

**Comment by dariomws** [comment]
Hi @CordlezToaster, thank you for your feedback and help us to improve docs.microsoft.com.

This article was updated 10 days ago to reflect updates on Google UI. Please, let us know if you think that there are still missing updates.

**Comment by scanum** [comment]
@CordlezToaster  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
