### ISSUE TITLE
Could you add clarity as to whether INTERNAL domains are supported using these sharing policies?

### ISSUE THREAD

**Issue by ryanwga** [MicrosoftDocs/OfficeDocs-Exchange#2107]
What about sharing with INTERNAL people?  The article only talks about sending to external email/domains.  Does that mean you can't use/edit the policy so that internal domains can be specified?  I've read about using delegate access, but that also provides send on behalf permission.  From what I've read about Sharing Calendars, it doesn't grant that additional level of permission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff83223-f09a-7e1a-8c44-d0f8dee5df54
* Version Independent ID: bdbb368f-1254-75ce-26b3-e3e17779142b
* Content: [Sharing policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/sharing-policies/sharing-policies)
* Content Source: [Exchange/ExchangeOnline/sharing/sharing-policies/sharing-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/sharing-policies/sharing-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ryanwga Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ryanwga How are you? The current article states

> Sharing policies control how your users share their calendars with people **outside your organization**.

For that matter I think you will have to explore into https://docs.microsoft.com/en-us/powershell/module/exchange/add-mailboxfolderpermission?view=exchange-ps cmdlet against the calendar folder with an specific accessright, maybe ReadItems?

Hope this information gets you in the right direction to solve your inquiry.

Thank you!

**Comment by ryanwga** [comment]
Hi @get-itips and @scanum, 

Thanks for responding.  If the "Share Calendar" option and the sharing policies are just for sharing **outside your organization**, could you add something stating what is needed to share internally, like Delegate access or the Powershell article you provided me?  Just to help out anyone else running down this same issue.  

Other comments/thoughts:

1. Why are these sharing policies specific to external access only?  If sharing policies are going to be used, incorporate functionality for both internal and external.
2. The "Share Calendar" feature is a bit misleading to me and others!  MS should add some additional context to the tip or ribbon option.  In my version of Outlook for Office 365 (16.0.11929.20836) 64bit, it states "Share this calendar **with other people**." when you hover over the option in the ribbon.  Not very accurate is it?  Because you can't share this calendar with anyone inside your organization.

**Comment by get-itips** [comment]
> 1. Why are these sharing policies specific to external access only?  If sharing policies are going to be used, incorporate functionality for both internal and external.
> 2. The "Share Calendar" feature is a bit misleading to me and others!  MS should add some additional context to the tip or ribbon option.  In my version of Outlook for Office 365 (16.0.11929.20836) 64bit, it states "Share this calendar **with other people**." when you hover over the option in the ribbon.  Not very accurate is it?  Because you can't share this calendar with anyone inside your organization.

Hello @ryanwga how are you?

For any suggested changes to how the product works I need to kindly redirect you to [Office 365 UserVoice](https://office365.uservoice.com/) as here we are limited to documentation updates, fixes and changes.
That way, your suggestion can reach the product team.

Thank you

**Comment by ryanwga** [comment]
Hi @get-itips,

Thanks for the link to the UserVoice, I've used it a few times.  

I added the comments/thoughts so that you had more information as to why I was requesting the clarity in the documentation.
