### ISSUE TITLE
Different settings from another MS page for IMAP

### ISSUE THREAD

**Issue by javicartin** [MicrosoftDocs/OfficeDocs-Exchange#2111]
[Enter feedback here]
The settings like TLS, etc are different from this page, please check for proper settings on both pages, thank you.
https://support.microsoft.com/en-us/office/pop-and-imap-email-settings-for-outlook-8361e398-8af4-4e97-b147-6c6c4ac95353

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64383249-903c-6cc5-83e1-93e0eb8ba128
* Version Independent ID: d93c4ce8-4bf4-15d0-b3ba-3d3eb11ebb37
* Content: [POP3 and IMAP4](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@javicartin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @javicartin an update to the article is on the way.
