### ISSUE TITLE
Step 4 "Configure directory synchronization" Access Denied with MFA enabled account

### ISSUE THREAD

**Issue by dam012345** [MicrosoftDocs/OfficeDocs-Exchange#2115]
Got an error when using account with MFA Enabled with this command :

.\Sync-MailPublicFolders.ps1 -Credential (Get-Credential) -CsvSummaryFile:sync_sumary.csv

[17/07/2020 11:19:02] Creating an Exchange Online remote session...
InitializeExchangeOnlineRemoteSession : Unable to create a remote shell session to Exchange Online. The error is as follows: "La connexion au serveur distant a échoué avec le message d'erreur suivant : Accès refusé. Pour plus d'informations, voir la rubrique d'aide about_Remote_Troubleshooting.".
Au niveau de D:\AdminExchange\Mail-enabled Public Folders - directory sync script\Sync-MailPublicFolders.ps1 : 506 Cara
ctère : 42
+     InitializeExchangeOnlineRemoteSession <<<< ;
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,InitializeExchangeOnlineRemoteSession

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-gb/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dam012345 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
