### ISSUE TITLE
Article is incomplete

### ISSUE THREAD

**Issue by gabelong** [MicrosoftDocs/OfficeDocs-Exchange#212]
You stopped after setting up 2FA. The user is expecting to see instructions on how to configure that IMAP thing... so please complete the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0d26fa-47d7-3d58-2810-52cac3ffa35d
* Version Independent ID: d2222d35-54cb-cd89-e27e-00d92838444e
* Content: [Migrating your Outlook.com account to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrating-your-outlook-com-account)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrating-your-outlook-com-account.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrating-your-outlook-com-account.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@gabelong Thank you for this feedback

I will get this over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by benediktbrandt** [comment]
@AndreaBarr The article is still incomplete

**Comment by AndreaBarr** [comment]
@msdmaguire Any updates on this?

**Comment by deonlewisduke** [comment]
We are working on I.T.! )+(

**Comment by scanum** [comment]
@deonlewisduke @msdmaguire Any updates on this?

**Comment by deonlewisduke** [comment]
Not sure, I'll check later

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by virtualdaisy** [comment]
Six months later, this still hasn't been resolved? Sure could use those instructions on migration. I'm sure they would have saved me time.

**Comment by deonlewisduke** [comment]
What is the exact issue you are having?

Need 22 people proficient in MICROSOFT OFFICE 365 to help train a few hundred people in DYNAMICS 365 use so I can hire a good 100,000 people for my company OPTION and its partners )+( subsidaries.

VILLIAN

"Some stories, should never be told."

________________________________

**Comment by msdmaguire** [comment]
@gabelong Sorry for the delay on this. We now recommend to all customers that they contact Microsoft FastTrack https://www.microsoft.com/en-us/fasttrack/?rtc=1 for assistance with their email migrations.

**Comment by deonlewisduke** [comment]
Thank you


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
