### ISSUE TITLE
Use the Microsoft 365 admin center to generate a rules report

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-Exchange#2122]
In the Article:

Use the Microsoft 365 admin center to generate a rules report
In the Microsoft 365 admin center, select Reports.

In the Rules section, select Top rule matches for mail or Rule matches for mail.

This is no longer in the admin center where stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736d8598-4bde-5f1c-5eef-2f9b648912f6
* Version Independent ID: eb74141c-161c-d1db-e95c-032f3dfdf8ec
* Content: [Manage mail flow rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/manage-mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-mail-flow-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dkotars Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
