### ISSUE TITLE
Data Privacy and CJIS

### ISSUE THREAD

**Issue by Dagriff** [MicrosoftDocs/OfficeDocs-Exchange#2124]
This is an absolute violation of data privacy.  This should **never** be turned on as a default not least  because no-one has any control over what Farcebook does with the data. 

And I want to know about specific CJIS data - Is this is shared by default??  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4feffdd2-0d18-ebe2-1768-e9458f8f1481
* Version Independent ID: d23070a5-0372-654d-34b6-306aeed66bc1
* Content: [Manage Facebook contact sync in your organization](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-facebook-contact-sync)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-facebook-contact-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-facebook-contact-sync.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Dagriff Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
