### ISSUE TITLE
Custom retention policy tag (RPT) on the Inbox

### ISSUE THREAD

**Issue by eric92315** [MicrosoftDocs/OfficeDocs-Exchange#2125]
We would like to have anything in the Inbox deleted after two years.  If an email is moved to a subfolder, that should be kept indefinitely.  If we put a custom retention policy tag (RPT) on the Inbox and move an email from the Inbox to the subfolder, will the tag go with the email and the email still get deleted after two years?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd067815-de9f-6c6f-a6f1-eceb78e50366
* Version Independent ID: 2ef7cd6f-bda3-58ba-c485-afc6102ee5d6
* Content: [Default folders that support Retention Policy Tags](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/default-folders)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@eric92315 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by eric92315** [comment]
I did find out that if I apply something to the Inbox, the subfolders of the Inbox will also be affected.  

Also found that a user can change the policy on a subfolder by right-clicking on it - selecting Properties, Policy Tab, and pick the appropriate policy.
