### ISSUE TITLE
this section is incomplete and the article is misleading

### ISSUE THREAD

**Issue by IhavenoideawhatImdoingvdash** [MicrosoftDocs/OfficeDocs-Exchange#2129]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86c9e05-c68b-8f00-3a94-c902d3352590
* Version Independent ID: e299bde7-ee34-96eb-b7f3-2ae75db017d3
* Content: [Specify the administrators and users who can install and manage add-ins for Outlook](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by IhavenoideawhatImdoingvdash** [comment]
I have tenant admins trying to follow the document thinking they can be the Exchange admin and use centralized deployment to push Add-ins to Outlook when this is not true. I have to inform then they must have Global Administrative Privilege to do so.  Also, there is a section missing wording. Please review this section:
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins#use-the-eac-to-assign-permissions-to-administrators

**Comment by scanum** [comment]
@IhavenoideawhatImdoingvdash Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by IhavenoideawhatImdoingvdash** [comment]
@scanum   I am not a tenant. I am the support agent assisting a tenant. Thanks for the input.
