### ISSUE TITLE
Amend Constraints

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-Exchange#2132]
Under "Constraints" it says: "Team's Calendaring features that require access to on premises mailboxes are not supported with the Hybrid Agent. You will need to leverage the Classic Exchange Hybrid Topology and publish AutoDiscover and EWS to support these features."

The reference to the Classic Exchange Hybrid Topology is misleading and confusing. The reference to publishing Autodiscover and EWS is unclear.

1. You do not need to establish a hybrid at all. What you do need is OAuth authentication between Azure AD and on-premises Exchange. One way to achieve this is by using the Hybrid Configuration Wizard, BUT only if you use one of the two types of hybrid that use OAuth: Classic Full or Modern Full \(see: [Hybrid Configuration Wizard options](https://docs.microsoft.com/en-us/exchange/hybrid-configuration-wizard-options)\)
2. You also need to use the Azure AD Connect Exchange hybrid option, which is not configured by running the Hybrid Configuration wizard
3. You need all mailboxes on Exchange 2016+
4. And Autodiscover and EWS endpoints published _externally_. Some organisations may publish these endpoints, but only internally.

The accurate requirements for Teams calendaring with Exchange on-premises are given in this Exchange Team Blog: [Configuring Teams calendar access for Exchange on-premises mailboxes](https://techcommunity.microsoft.com/t5/exchange-team-blog/configuring-teams-calendar-access-for-exchange-on-premises/ba-p/1484009).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Air-Git, thank you for your feedback and help us to improve docs.microsoft.com.

It´s very similar to https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/5368. I'm also applying an update to this article based on the other issue feedback:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2126

**Comment by Air-Git** [comment]
Yes, it's all the same root issue. There is no single document that describes accurately what you need to do to integrate the Teams calendar with Exchange on-premises (except the one Exchange team blog). The various documents say "you need xyz", for example you need OAuth, or you need a hybrid, without saying what else you need. As a result, people conclude that you ONLY need OAuth, or only need to run the HCW, which is not the case.

**Comment by dariomws** [comment]
I'm improving the [How Exchange and Microsoft Teams interact](https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact) as I commented in the other issue. Please be patient, they will be live in the next couple of days, I'm also working with some colleagues to confirm but you have the information as we discused in the other issue.
It's **recommended** that you have a (full classic) hybrid Exchange deployment in place as it includes all the requirements for Team's calendaring.

**Comment by Air-Git** [comment]
Thanks for all the changes. It is now fully clear.
