### ISSUE TITLE
Give more details for -MAPIEnabled

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/OfficeDocs-Exchange#2136]
There are different flavors of the MAPI protocol
MAPI over HTTP (MAPI/HTTP) 
RPC over HTTP (Outlook anywhere)

Does this parameter affect both or only one of them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f48209-24ef-9e93-351a-c13fabd809b6
* Version Independent ID: 419545b7-e0f3-585d-1c98-603125018a12
* Content: [Enable or disable MAPI for a mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-mapi)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-mapi.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-mapi.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@joergrenn Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by joergrenn** [comment]
My experience with the support can be called mediocre at best. Most of the time they don't even understand the question. They have no connection to the product group and cannot answer questions like this. Believe me I have tried.
Is it too much to ask to have decent documentation for the products?
When I point out room for improvement I should find out myself and then report? 
That is not a good experience.
