### ISSUE TITLE
Please update the article as Search-Mailbox is a deprecated cmdlet

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/OfficeDocs-Exchange#2139]
The article is still mentioning Search-Mailbox and this is a deprecated cmdlet in Exchange Online. Please update the article to reflect the new way of deleting data from Recoverable Items, which assumes the use of New-ComplianceSearch and New-ComplianceSearchAction.

Searching emails specifically from a certain folder (Search-Mailbox had "SearchDumpsterOnly), is described here: https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide. Please unify the content or explain the steps clearly as to how customers can use New-ComplianceSearch and New-ComplianceSearchAction to delete data only from Recoverable Items and not from the entire mailbox.

The overview of the steps would be:

1. Connect Powershell to SCC
2. Connect Powershell to EXO
3. Run in Powershell connected to EXO the script found in article https://docs.microsoft.com/en-us/microsoft-365/compliance/use-content-search-for-targeted-collections?view=o365-worldwide to get the FolderID of the specific folder under Recoverable Items (DiscoveryHolds, Deletions or Purges)
4. In the Powershell session connected to SCC, run the following:

- New-ComplianceSearch -Name "name of the search" -ExchangeLocation user@domain.com -ContentMatchQuery "FolderID:<GUID value corresponding to the folder you want to search from the mailbox>"

- Start-ComplianceSearch -Identity "name of the search"

- New-ComplianceSearchAction -SearchName "name of the search" -Purge -PurgeType HardDelete - this is just an example

Referrences:

https://docs.microsoft.com/en-us/microsoft-365/compliance/keyword-queries-and-search-conditions?view=o365-worldwide
https://docs.microsoft.com/en-us/microsoft-365/compliance/search-for-and-delete-messages-in-your-organization?view=o365-worldwide
https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearchaction?view=exchange-ps
https://docs.microsoft.com/en-us/powershell/module/exchange/new-compliancesearch?view=exchange-ps
https://docs.microsoft.com/en-us/powershell/module/exchange/start-compliancesearch?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c21112a-deb5-83b3-160e-0149a1e510f6
* Version Independent ID: 4edc9fcd-4971-470b-c56e-e1a2e78b8854
* Content: [Clean up or delete items from the Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/clean-up-deleted-items)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Alex-Catalin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dawilhoit** [comment]
Doing a targeted search for the recoverable items folder isn't a workable solution for 5000 mailboxes.

**Comment by Alex-Catalin** [comment]
> Doing a targeted search for the recoverable items folder isn't a workable solution for 5000 mailboxes.

I agree, but the article still needs to be clarified as the Search-Mailbox cmdlet had the ability to Search Dumpster, while New-ComplianceSearchAction, uses a more complicated mechanism to do the same thing.

We need to be very clear in articles like these that discuss way to purge data from customers mailboxes.

**Comment by dawilhoit** [comment]
> > Doing a targeted search for the recoverable items folder isn't a workable solution for 5000 mailboxes.
> 
> I agree, but the article still needs to be clarified as the Search-Mailbox cmdlet had the ability to Search Dumpster, while New-ComplianceSearchAction, uses a more complicated mechanism to do the same thing.
> 
> We need to be very clear in articles like these that discuss way to purge data from customers mailboxes.

Agreed. Unfortunately, the docs don't address it at all. Addressing 1 single mailbox, when you already had a way to address 10k mailboxes and their dumpster. It should be clear that they are not allowing the new-compliancesearchaction to purge from the recoverable items folder, and explain why.

**Comment by get-itips** [comment]
Hello everyone on this thread, thanks for your feedback.
I can confirm the article has been heavily updated recently with current available cmdlets.
Thanks

**Comment by get-itips** [comment]
@scanum please close this one. Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
