### ISSUE TITLE
Multigeo support

### ISSUE THREAD

**Issue by kf4ape** [MicrosoftDocs/OfficeDocs-Exchange#2141]
Is there any support for this module in regards to MultiGeo offering and making modifications to users in different regions? having issues with adjusting some inactive users in EUR while my admin is in NAM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a137ee50-f3b9-07e1-7214-58d282896a66
* Version Independent ID: 70fc82e3-88f8-bc68-a094-37b81c778038
* Content: [Create or remove an In-Place Hold](https://docs.microsoft.com/en-us/exchange/security-and-compliance/create-or-remove-in-place-holds)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@kf4ape Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
