### ISSUE TITLE
Documentation is woefully out of date for the macOS platform...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/OfficeDocs-Exchange#2142]
There have been some considerable changes to Outlook since 2011. I am also, more specifically, finding it very hard to find any real information regarding GAL replication, especially with regards to how your supported macOS clients handle it. I have a case open with your support team and am getting nowhere, despite escalating this to a "senior engineer" who is still using language such as "as far as we know"!? If this stuff isn't up to date and adequate then what chance do we stand, never mind your own engineers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d52e882-9b75-3091-79c5-c6733aa924b1
* Version Independent ID: 42c575aa-bb89-3aa2-21f1-adf4771ec10b
* Content: [Address book policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-book-policies/address-book-policies)
* Content Source: [Exchange/ExchangeOnline/address-books/address-book-policies/address-book-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/address-book-policies/address-book-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@deejerydoo  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
