### ISSUE TITLE
GSuite Interface Cues Wrong

### ISSUE THREAD

**Issue by pseudoelvis** [MicrosoftDocs/OfficeDocs-Exchange#2143]
Hi, the GSuite interface steps have been deprecated, GSUITE has new steps required to accomplish his task, and customers will be confused by these directions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer G Suite mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@pseudoelvis  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Tammychmarney** [comment]
My MICROSOFT OUTLOOK EMAIL ACCOUNT ADMINISTRATOR ON ASUS DESKTOP COMPUTER LOST INTERNET CONNECTION PROVIDERS ERRORS ON YAHOO ACCOUNT CHOCSANTAGRAMMA@ROGERS.COM

**Comment by get-itips** [comment]
Hello @pseudoelvis Shane, how are you?
I see that the article has been heavily updated to reflect current interface instructions. Kindly tell me if you could have a chance to look at the updated article.
Thank you

**Comment by scanum** [comment]
@pseudoelvis  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
