### ISSUE TITLE
Older version

### ISSUE THREAD

**Issue by nimikaul** [MicrosoftDocs/OfficeDocs-Exchange#2144]
The steps mentioned here do not seem to be an updated version, especially the screenshot.
As per the new version of EAC, there is Migration, where we create a new Migration batch and then follow the wizard.
Please update articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration?branch=dmaguire-gsuite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@nimikaul  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @CordlezToaster, thank you for your feedback and help us to improve docs.microsoft.com.

When you enter to the current Admin Center (https://outlook.office365.com/ecp/) you can see this message:
"We have a simple wizard-based migration experience in the new Exchange admin portal. You can try to **preview** the experience for G-Suite migration."
This wizard is still in preview and this is why the screenshots weren't added here.

**Comment by scanum** [comment]
@nimikaul  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
