### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by gh0stwalker** [MicrosoftDocs/OfficeDocs-Exchange#2146]
The link to the script download is dead. Please update to point to the correct location to download the scripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@gh0stwalker  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @gh0stwalker 
Do you refer to

> Download the following files from Mail-enabled Public Folders - directory sync script: 

?

the link works for me, can you check again?

Thank you

**Comment by gh0stwalker** [comment]
Thanks. It wasn't working prior to today (I did try multiple times over the last month or so).

**Comment by get-itips** [comment]
> Thanks. It wasn't working prior to today (I did try multiple times over the last month or so).

Thanks for reporting, I encourage you to do the same in the future if this happens again.

**Comment by scanum** [comment]
@gh0stwalker Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
