### ISSUE TITLE
Reference "Add info about Admin Audit Log storage #1667"

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#2149]
Unfortunately nothing was added regarding "Admin Audit Log". Please review.
Thanks!

**Comment by scanum** [comment]
@trudolf-msft Thanks for the feedback, could you please reference the issue? thanks!

**Comment by trudolf-msft** [comment]
Please see issue 1667 which was closed but not fixed.
Article does not contain any information about Admin Audit Log or where it's stored (all details in the old issue description)

**Comment by al3teoi11** [comment]
My name is abody

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
