### ISSUE TITLE
Condition missing in second table

### ISSUE THREAD

**Issue by manicottiK** [MicrosoftDocs/OfficeDocs-Exchange#2150]
The second table shows conditions for Password Length <6 and for >6, but not for ==6, <=6, or >=6 (except for the last case). Please address which security level is set when Password Length is 6.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8953d102-718c-d28a-976a-5906000567c3
* Version Independent ID: 0a13e776-9b35-7b46-5bb5-86b4ba8ddbe5
* Content: [Mobile device mailbox policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@manicottiK  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @manicottiK 
How are you? Hope you are doing good.
Thanks for your feedback.
To my understanding, the last row is implying that a min password of 6 = high, and as a value can't have two different levels, I conclude:

4 and 5 = Medium
6, 7 and 8 = High

Does that makes sense?

Thanks

**Comment by manicottiK** [comment]
It looks like @smithre4 fixed the table on September 22, 2020. One of his two update comments was "Updated Android 10 password complexity table." It now reads fine to me. Thanks to all involved.

**Comment by get-itips** [comment]
> It looks like @smithre4 fixed the table on September 22, 2020. One of his two update comments was "Updated Android 10 password complexity table." It now reads fine to me. Thanks to all involved.

Thanks for returning and sharing your feedback!

**Comment by get-itips** [comment]
@scanum please close this one.

**Comment by manicottiK** [comment]
The table is correct now, thanks. The edit history shows that smithre4 fixed is on 22 September 2020. One of his two comments about the edits was “Updated Android 10 password complexity table”.

Thanks,
Ken

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
