### ISSUE TITLE
Does not cover using recently released HCW 17.x

### ISSUE THREAD

**Issue by ChrisAtMAF** [MicrosoftDocs/OfficeDocs-Exchange#2151]
There is a 'significant' update to the Hybrid Configuration Wizard, version 17.x, which fixes various serious bugs:

https://techcommunity.microsoft.com/t5/exchange-team-blog/march-2020-significant-update-to-hybrid-configuration-wizard/ba-p/1238753

This new version is not available from within ECP (which will always supply version 16), - you currently have to use the external link instead: http://aka.ms/hybridwizard

It would help if the documentation would reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8cb000-e64b-b90d-fa6f-09f2b50532b3
* Version Independent ID: b65f1351-a45c-37b6-f1a8-12894f203dd4
* Content: [Create a hybrid deployment with the Hybrid Configuration wizard](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/deploy-hybrid#use-the-exchange-admin-center-and-hybrid-configuration-wizard-to-create-a-hybrid-deployment)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ChrisAtMAF  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
