### ISSUE TITLE
Outdated file needs removed ASAP

### ISSUE THREAD

**Issue by tmoen2015** [MicrosoftDocs/OfficeDocs-Exchange#2155]
This is old, inaccurate content, it confuses customers and our internal support people- please remove it! https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/in-place-ediscovery?redirectedfrom=MSDN#throttle

**Comment by scanum** [comment]
@tmoen2015  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @tmoen2015
