### ISSUE TITLE
Users whose mailboxes are in Exchange Online won't be able to access on-premises public folders using Outlook on the web 

### ISSUE THREAD

**Issue by kiwiant** [MicrosoftDocs/OfficeDocs-Exchange#2165]
After reporting an issue to the Office 365 support their response was "Users whose mailboxes are in Exchange Online won't be able to access on-premises public folders using Outlook on the web (formerly known as Outlook Web App).".

This is an important piece of information to be aware of when using public folders in a hybrid scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@kiwiant  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @kiwiant how are you? Thanks for your feedback.
Can you clarify what you think needs to be done to this article based on that sentence?
Many thanks

**Comment by get-itips** [comment]
Hello @kiwiant how are you? Returning to check if you could see my last message, thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by kiwiant** [comment]
I believe the article must clearly state that if a mailbox is located in Exchange Online, and the public folders are located on-prem, that mailbox will have no access to Public Folders from Outlook on the web. Also, the ECP for Exchange Online will not show the public folder hierarchy or the public folder mailboxes.

**Comment by get-itips** [comment]
Hello @kiwiant how are you, hope you are good, the article currently states the answer you received from support

> In addition, users whose mailboxes are in Exchange Online won't be able to access on-premises public folders using Outlook Web App or Outlook on the web.

Thanks
