### ISSUE TITLE
Organize By Thread configuration variable not working

### ISSUE THREAD

**Issue by floyager** [MicrosoftDocs/OfficeDocs-Exchange#2166]
We've successfully implemented several other configuration variables but disabling the Organize By Thread using the Boolean 'false' does not seem to apply. Saw another user on reddit running InTune with the same issue posted 6 days ago. We're running Cisco/Meraki MDM deployed to iOS Outlook

Other Boolean values appear to work just fine (like disabling Focused Inbox and removing the default signature).

com.microsoft.outlook.mail.organizebythreadenabled  Boolean false

**Comment by scanum** [comment]
@floyager Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
