### ISSUE TITLE
How to add ExternalEmailAddress?

### ISSUE THREAD

**Issue by goertzenator** [MicrosoftDocs/OfficeDocs-Exchange#2167]
In the section "Provision users in Microsoft 365 or Office 365" the text says to set `ExternalEmailAddress` for each user but gives no indication about how to go about this.  My exploration of the UI did not reveal where this could be entered.  How is this done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@goertzenator Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by goertzenator** [comment]
It turns out our problem was that everyone was provisioned with standard Mailbox accounts prior to approaching the gsuite migration procedure. The solution is to wipe all those accounts and start with MailUsers just as the procedure says.
