### ISSUE TITLE
WARNING: Name resolution of http://watchdog.servicebus.windows.net failed -- Status: No such host is known

### ISSUE THREAD

**Issue by ltoddnelson** [MicrosoftDocs/OfficeDocs-Exchange#2168]
Receiving "WARNING: Name resolution of http://watchdog.servicebus.windows.net failed -- Status: No such host is known" during pre-req tests of hybrid agent.  All other tests pass.

If I comment out the "watchdog" URI in the script MS provides per the reference below, the command proceeds and completes without further issue.

Does "watchdog" host even exist?
Should the pre-req script be updated?
What is your recommendation?

Ref: https://windowstechpro.com/invoke-webrequest-the-remote-name-could-not-be-resolved-watchdog-servicebus-windows-net/

![image](https://user-images.githubusercontent.com/12664242/89591960-540d9f80-d800-11ea-82bf-ef52b6336475.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#running-setup)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ltoddnelson Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by pavelrozenberg** [comment]
This happening to everyone. Since this case was open nothing was done.
Why do they have to open a service case on their tenant when it is clearly a global issue?
