### ISSUE TITLE
About MaxConcurrentMigrations maximum      

### ISSUE THREAD

**Issue by mikumeda** [MicrosoftDocs/OfficeDocs-Exchange#2169]
Hi Publishers,

Isn't the maximum of -MaxConcurrentMigrations 300 for Set-MigrationEndPoint?
In my ExO tenant, I was able to set the value up to 300. But when setting it to 301, I got an error following.

```
PS C:\Users\mikumeda> Set-MigrationEndpoint -Identity "Hybrid Migration Endpoint - EWS (Default Web Site)" -MaxConcurrentMigrations　300
PS C:\Users\mikumeda> Get-MigrationEndpoint | fl max*


MaxConcurrentMigrations       : 300
MaxConcurrentIncrementalSyncs : 10



PS C:\Users\mikumeda> Set-MigrationEndpoint -Identity "Hybrid Migration Endpoint - EWS (Default Web Site)" -MaxConcurrentMigrations　301
このエンドポイントによって同時移行の最大数が '301' になり、種類 'ExchangeRemoteMove' のエンドポイントで許可されている上
限 '300' を超えてしまいます。
    + CategoryInfo          : NotSpecified: (:) [Set-MigrationEndpoint], MaximumConcurre...ceededException
    + FullyQualifiedErrorId : [Server=OSBPR01MB2886,RequestId=4e13becb-b025-4432-b0c8-daf0901b47da,TimeStamp=2020/08/0
   7 0:59:24] [FailureCategory=Cmdlet-MaximumConcurrentMigrationLimitExceededException] 54BBD8AC,Microsoft.Exchange.M
  anagement.Migration.MigrationService.Endpoint.SetMigrationEndpoint
    + PSComputerName        : outlook.office365.com
``` 
The docs explains that MaxConcurrentMigrations ranges are 1 to 100 in "Factor 3: Migration engine".
Would like to know which value (maximum) will be true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c518bc-12b9-6ee8-362d-70ac54983dd6
* Version Independent ID: 102cd602-f1a6-acf9-a9b8-f47f57de3708
* Content: [Microsoft 365 and Office 365 migration performance and best practices](https://docs.microsoft.com/en-us/exchange/mailbox-migration/office-365-migration-best-practices)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by miryb** [comment]
Max Concurrent Migration at the tenant level is 300 by default and can be increased to 1000 by support, you can read more on this in this doc: https://docs.microsoft.com/en-gb/archive/blogs/brad_hughes/understanding-migration-concurrency 
However, you need to ensure that the on-premises servers support it:
https://support.microsoft.com/en-us/help/3091026/mailbox-replication-proxy-service-can-t-process-this-request-because-i

**Comment by mikumeda** [comment]
Had a talk with @miryb , and organized the point.
The points we need to clarify are:
- Why MaxConcurrentMigrations in non-hybrid migrations is 100.
- Why this info (that is 300 and can be raised to 1000 if MRSProxy onpremises supports it) is not also under "Hybrid deployment" .

**Comment by scanum** [comment]
@miryb Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
