### ISSUE TITLE
Office 365 user throttling

### ISSUE THREAD

**Issue by miryb** [MicrosoftDocs/OfficeDocs-Exchange#2171]
Section: Microsoft 365 and Office 365 user throttling

We should be more clear in our statement that none of our Native Migrations in Exchange Online are not affected by User Throttling: Hybrid, Cutover/Staged (RPC/HTTP) and IMAP/G suite. Also PST imports using Office 365 Import Service and Public Folder Migrations. Only 3rd party migrations are affected by User Throttling in M365/O365.
And mention that for 3rd party migrations that use EWS protocol, they can lift it by themselves as we have enabled a support central diagnostics so customers can now self-serve EWS throttling relaxation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c518bc-12b9-6ee8-362d-70ac54983dd6
* Version Independent ID: 102cd602-f1a6-acf9-a9b8-f47f57de3708
* Content: [Microsoft 365 and Office 365 migration performance and best practices](https://docs.microsoft.com/en-us/exchange/mailbox-migration/office-365-migration-best-practices)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@miryb  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @miryb Mirela, how are you?
Thanks for your feedback that makes Docs better.

To my understanding, it is clear that user throttling only affects third party migration tools, based on these sentences:

> User throttling affects most third-party migration tools and the client-uploading migration method. 

and

> Migration-service throttling affects all Microsoft 365 or Office 365 migration tools. Migration-service throttling manages migration concurrency and service resource allocation for Microsoft 365 or Office 365 migration solutions.

However please let me know if I misunderstood you in any way.

For the temporary lift of EWS throttling, I will propose adding a sentence about that in this article, based on your feedback. Thank you

**Comment by miryb** [comment]
Hi Andres, to me it's clear as well, but from my experience in support,
many people don't really know this. I am thinking at a more specific Note /
highlighted paragraph where we clearly mention our native methods and that
these 5 migrations are not affected by this type of throttling.

**Comment by get-itips** [comment]
> Hi Andres, to me it's clear as well, but from my experience in support, many people don't really know this. I am thinking at a more specific Note / highlighted paragraph where we clearly mention our native methods and that these 5 migrations are not affected by this type of throttling.
> […](#)


@miryb Mirela, I will try to come up with a note and propose thru a PR. Thanks
