### ISSUE TITLE
Recommended addition. 

### ISSUE THREAD

**Issue by jackedwards97** [MicrosoftDocs/OfficeDocs-Exchange#2176]
It's also worth mentioning that in 365, in licences, the first thing to check would be that the user has:
A) A licence assigned to them (Exchange Online, E3, etc). 
B) That at the very bottom of the licence settings in 365, if the licence assigned is E3, ensure that all the sub-licence options are ticked, particularly the Exchange Online one. 

![image](https://user-images.githubusercontent.com/60427294/89874989-90e8e600-dbb4-11ea-9286-cd1d19ede30f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2943f17-2dd1-0864-07ca-716eb0892647
* Version Independent ID: ce2a378e-89c5-cd14-697e-20a2ea3e6230
* Content: [Fix email delivery issues for error code 5.4.6 or 5.4.14 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-4-6-through-5-4-20-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-4-6-through-5-4-20-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-4-6-through-5-4-20-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jackedwards97  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@scanum please close, thanks

**Comment by scanum** [comment]
@jackedwards97 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
