### ISSUE TITLE
Put Address Policy INTO THE GUI

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/OfficeDocs-Exchange#2178]
There's no reason after 4 years to have to go to PowerShell for Address Book Policies. It's no longer a beta feature and shouldn't be in a beta management form, it should be in the Office 365 GUI.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 898cf967-a7a6-b71a-193d-ae1f2718e42f
* Version Independent ID: 67cb1b4e-849d-8f97-c2fe-2996fa44e34f
* Content: [Create an address book policy in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-book-policies/create-an-address-book-policy)
* Content Source: [Exchange/ExchangeOnline/address-books/address-book-policies/create-an-address-book-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/address-book-policies/create-an-address-book-policy.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@VNJoe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@VNJoe Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
