### ISSUE TITLE
Sent items appearing as drafts on Exchange 2016

### ISSUE THREAD

**Issue by SS88** [MicrosoftDocs/OfficeDocs-Exchange#2181]
After setting right the DNS, Imap, Pop and Smtp settings my locally installed Exchange 2016 is still not able to send emails.

What might be the problem ?

Thank you.

**Comment by scanum** [comment]
@SS88 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
