### ISSUE TITLE
Permissions through non mail-enabled security groups

### ISSUE THREAD

**Issue by itpro-tips** [MicrosoftDocs/OfficeDocs-Exchange#2182]
Hello,

>Note: Although you might be able use Exchange Online PowerShell to assign some or all of these permissions to other delegate types on other kinds of recipient objects, this topic focuses on the delegate and recipient object types that produce useful results. 

This page has a note about the use of PowerShell to assign permissions. But we also have another method to add permissions: Office 365 admin portal allows us to add 'Members' to shared mailboxes and it will set FullAccess/SendAs.

These members can be to any type, included security groups (non mail-enabled). 
I don't even know if this setting works but it is very confusing because the documentation tell us we have to use _Mail-enabled security groups_ but Office 365 portal allows any type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe24386f-86cc-5073-dc17-ad8ece0e3dc7
* Version Independent ID: 88a529c7-c6e6-8438-8eb4-c6fc2a20f722
* Content: [Manage permissions for recipients in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-permissions-for-recipients)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@itpro-tips Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
@itpro-tips Bastien, wanted to reach out again to see if you could review my comment.

**Comment by scanum** [comment]
@itpro-tips We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
