### ISSUE TITLE
Setting "com.microsoft.outlook.Mail.PlayMyEmailsEnabled" wrong!?!

### ISSUE THREAD

**Issue by GNeubecker** [MicrosoftDocs/OfficeDocs-Exchange#2183]
The setting "com.microsoft.outlook.Mail.PlayMyEmailsEnabled" is not working. It seems that the setting is one digit to long, because allways when I insert the setting into the designated field it deletes the hole string if I try to insert the last digit.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by smithre4** [comment]
Hi @GNeubecker, the key name is correct as it is defined in the document. As it's not clear from the brief description which UEM solution you're utilizing, I recommend starting with a support case with that product.

**Comment by scanum** [comment]
@GNeubecker  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
