### ISSUE TITLE
Please indicate what the time zone is for times and dates!

### ISSUE THREAD

**Issue by codemonkey2k5** [MicrosoftDocs/OfficeDocs-Exchange#2186]
Please indicate on the migration batch page what the time zone is that is displayed when showing last good sync.  Or better yet, allow the user to select their time zone.   

Thank you!

**Comment by scanum** [comment]
@codemonkey2k5 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by codemonkey2k5** [comment]
Hi Scanum, I think there may have been a miscommunication here.  What I am talking about is that when you are running a migration batch the batch status shows times and dates but does not indicate what timezone those times and dates are for.  I think it might be UTC, but it's not documented anywhere.
