### ISSUE TITLE
Sync-MailPublicFoldersCloudToOnprem.ps1 need -CsvSummaryFile parameter.

### ISSUE THREAD

**Issue by Takojio** [MicrosoftDocs/OfficeDocs-Exchange#2187]
In "Step 2: Configure directory synchronization" , This section describes "Sync-MailPublicFoldersCloudToOnprem.ps1".
  Sync-MailPublicFoldersCloudToOnprem.ps1 -Credential (Get-Credential)

But, in "Sync-MailPublicFoldersCloudToOnprem.ps1" I guess you need -Credential and -CsvSummaryFile parameter.
Title : Mail-enabled Public Folders - directory sync from EXO to On-Prem script.
URL : https://www.microsoft.com/en-us/download/details.aspx?id=52037

---
  - Install Instructions 
  Required parameters:
    Credential - Exchange Online user name and password
    CsvSummaryFile - The file path where sync operations and errors will be logged in a CSV format
  Example 1: .\Sync-MailPublicFoldersCloudToOnprem.ps1 -Credential (Get-Credential) -CsvSummaryFile:sync_summary.csv

---

Example (My Machine)

  ----------
  .\Sync-MailPublicFoldersCloudToOnprem.ps1 -Credential (Get-Credential)

  cmdlet Get-Credential at command pipeline position 1
  Supply values for the following parameters:
  Credential

  cmdlet Sync-MailPublicFoldersCloudToOnprem.ps1 at command pipeline position 1
  Supply values for the following parameters:
  CsvSummaryFile:

  ----------

Please correct that you need -Credential and -CsvSummaryFile parameter in Sync-MailPublicFoldersCloudToOnprem.ps1 in the docs.

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeeb3268-af97-fad5-1310-2265f2955d53
* Version Independent ID: 9cf5f8ac-3d50-2896-0380-42aaf9cadd58
* Content: [Configure Exchange Online public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders?view=exchserver-2019)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Takojio Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
