### ISSUE TITLE
Org Relationship is Needed in Both Org

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-Exchange#2188]
I have setup Organization Relationship between two EXO tenant, But it doesn't work untill i create Org Reationship on both sides. Is there any recent change in design?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c02125f4-2bb2-0631-93e2-93ccce4f1cb5
* Version Independent ID: 03192cfe-7d7e-82ec-d048-b4ac7d08d9df
* Content: [Organization relationships in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/organization-relationships)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
