### ISSUE TITLE
Sharing Policy 

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-Exchange#2189]
Based on our testing Option "Free/busy information with time, subject, and location" and "Free/busy information, including time, subject, location, and title" don't work for external users (e.g. Hotmail, gmail). Is this Default Product behavior?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff83223-f09a-7e1a-8c44-d0f8dee5df54
* Version Independent ID: bdbb368f-1254-75ce-26b3-e3e17779142b
* Content: [Sharing policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/sharing-policies/sharing-policies)
* Content Source: [Exchange/ExchangeOnline/sharing/sharing-policies/sharing-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/sharing-policies/sharing-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@3novsan Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
