### ISSUE TITLE
Clarification on sub-domain for mail routing to Microsoft 365 or Office 365

### ISSUE THREAD

**Issue by bubixb** [MicrosoftDocs/OfficeDocs-Exchange#2191]
[Enter feedback here]

I've followed the instruction in the section "Create a sub-domain for mail routing to Microsoft 365"
As recommended, I've created sub-domain of my primary domain and it's automatically verified as expected.
However, in the doc, it says "making sure that the status is shown as Active"
But the status of the newly create sub-domain is "Verified"

So Can I continue with "verified" status or should I do something more in order to get Active status?
To Active status, it seems I have two options

Set up Google MX records
Skip Google MX setup
I think I shouldn't do option 1 since this subdomain should point to Microsoft 365. So I just wonder if I can just select "skip Google MX setup" option to get Active status

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-microsoft-365-or-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@bubixb Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
