### ISSUE TITLE
Admin roles not visible in admin center

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/OfficeDocs-Exchange#2194]
The admin roles listed for managing store add-ins and custom add-ins are not listed in either the M365 Admin Center Roles page or in Azure AD Roles and Administrators. They don't appear to be part of the options available under New Custom Role in Azure AD either. 

I've subsequently found them as part of the Exchange Admin Center under the admin roles available for admin role groups. As Add-ins are managed from the M365 admin center this is not obvious.

Please clarify in the doc where these roles can be managed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86c9e05-c68b-8f00-3a94-c902d3352590
* Version Independent ID: e299bde7-ee34-96eb-b7f3-2ae75db017d3
* Content: [Specify the administrators and users who can install and manage add-ins for Outlook](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ChrisParrBIE  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
