### ISSUE TITLE
Modify Step No. 12

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-Exchange#2195]
As per https://techcommunity.microsoft.com/t5/exchange-team-blog/march-2020-significant-update-to-hybrid-configuration-wizard/ba-p/1238753 , HCW will no longer enable Federation Trust by default for all installations. Instead, it will only enable Federation Trust if there are Exchange 2010 servers on premises. HCW will call Get-ExchangeServer and if no Exchange 2010 servers are reported, the workflow to enable Federation Trust and subsequently require domain proof will not execute. Note that organization relationships are still created

Please amend step 12 accordingly.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8cb000-e64b-b90d-fa6f-09f2b50532b3
* Version Independent ID: b65f1351-a45c-37b6-f1a8-12894f203dd4
* Content: [Create a hybrid deployment with the Hybrid Configuration wizard](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/deploy-hybrid)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@3novsan  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
