### ISSUE TITLE
Full Access is now called Read and manage

### ISSUE THREAD

**Issue by mattgaspar** [MicrosoftDocs/OfficeDocs-Exchange#2196]
In the Office 365 admin portal and the new EAC portal, the "Full Access" permission is now called "Read and manage".
This is much more accurate as Full Access implies that you can also Send As, but you can't (which is a really poor design)!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488ecf85-5f6d-3abd-4253-8527b5082340
* Version Independent ID: ec414c0f-4ee4-bbd1-3851-3e4db0c97593
* Content: [Shared mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mattgaspar  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@mattgaspar  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
