### ISSUE TITLE
Theres no mention of DKIM signing when using SMTP relay

### ISSUE THREAD

**Issue by viniciusferrao** [MicrosoftDocs/OfficeDocs-Exchange#2199]
Hello, there's missing information in this page on how Office365 uses DKIM signing when relaying messages with Option 3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365?redirectSourcePath=%252farticle%252fHow-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by michelderooij** [comment]
Channeling all outbound transport through Office 365 as Internal, so irrelevant as DKIM signing will be done at EXO layer.

**Comment by viniciusferrao** [comment]
Sorry, but I don't understood what you've said.

You mean that when there's proper receive and send connectors configured on both side, like in the Option 3 of this page, DKIM signature is automatically added? So because of this there's no need to add any information about DKIM alignment on this page, because it's irrelevant?

If that was what you want to say, this is not what happens, at least on all my three tenants, in practice.

**Comment by scanum** [comment]
@viniciusferrao  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @viniciusferrao Vinicius, how are you?
Hope you are doing good.

There is this [specific article](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide) of how Microsoft 365 uses DKIM.

Are you seeing something different in your scenario to what is described on that article?

Thank you

**Comment by viniciusferrao** [comment]
Hello @get-itips; yes the behaviour is not what's documented there. That's why I opened this issue to properly explain how DKIM works when option 3 of this article is used.

I have some own findings, that are basically, when using option 3 the domains can be configured in two ways, authoritative and internal relay. But, this is what happens:

* Authoritative: DKIM works as expected, but it breaks all transport rules that relays to external MTAs, since some mailboxes or addresses may not be available on EOP.
* Internal Relay: DKIM is not signed at all, but any transport rule works as expected.

So this is a problem when deploying Option 3. I have an open support ticket with Microsoft regarding this issue, after my findings, they are looking deeper. So anyway I think the documentation should explain how DKIM will work, or not, when using option 3. If DKIM is properly supported or not, because I was hoping properly DKIM alignment and signing when using Option 3.

**Comment by get-itips** [comment]
Hello again @viniciusferrao , thanks for sharing further information.

I will try to get an SME on this. Also, in your tests, did you try creating a mail user object for the corresponding sending device?

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains

**Comment by msdmaguire** [comment]
@viniciusferrao, adding @arindamthokder of MSFT to look into your case for you.  Arindam would like to confirm that there has been an update to improve what you experienced. Can you provide your case # so he can look into this further? He will keep you updated here.

**Comment by msdmaguire** [comment]
Hi @viniciusferrao, just checking in to see if this is still an issue for you. @arindamthokder can look into it further if you can provide your case #.

**Comment by scanum** [comment]
@viniciusferrao  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
