### ISSUE TITLE
Can only have 256K of Mailbox rules? Rediculous new limitation

### ISSUE THREAD

**Issue by silversword411** [MicrosoftDocs/OfficeDocs-Exchange#2206]
This wasn't the case in the past. Apparently another question I have to decide between recommending Hosted exchange and G Suite is if any users make lots of rules. If they do, then Office 365 and Hosted Exchange is a non-starter.

#ByeByeBusiness

**Comment by scanum** [comment]
@silversword411 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
