### ISSUE TITLE
Still missing any information regarding how GAL is handled for macOS Outlook...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/OfficeDocs-Exchange#2207]
Thanks for removing references to ancient versions of Outlook. However, ignoring the fact that you guys have absolutely zero documentation regarding how GAL works with your macOS Outlook client does not mean it is going to go away.

I have had it confirmed to me, recently, in a Microsoft support case, with one of your Mac SMEs that they are aware there is no documented resources for them to refer to to be able to even confirm the expected behaviour of the macOS clients, in relation to the Exchange default handling of the GAL, never mind any custom GAL policies we may set up.

Why is Microsoft being so bad (arguably negligent) at providing even basic information about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d52e882-9b75-3091-79c5-c6733aa924b1
* Version Independent ID: 42c575aa-bb89-3aa2-21f1-adf4771ec10b
* Content: [Address book policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-book-policies/address-book-policies)
* Content Source: [Exchange/ExchangeOnline/address-books/address-book-policies/address-book-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/address-book-policies/address-book-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@deejerydoo Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by deejerydoo** [comment]
Guys, The ONLY reason I have come here to tell you you need to update your documentation is because your own support SMEs, on an already existing tenant service ticket have said to me, in clear terms, they cannot help me any further because there is currently no documentation regarding how this works. So, currently, it is you, as the documentation team, being responsible for documenting how this product works, who are preventing us from being able to resolve this case. Let me make this clear. YOUR DOCUMENTATION IS PREVENTING US FROM PROCEEDING TO A RESOLUTION FOR THIS CASE< AS PER YOUR OWN SMEs.
