### ISSUE TITLE
Meeting providers displayed in the New Event screen on Android - Priority

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/OfficeDocs-Exchange#2209]
There should be an option for Admins allow users to choose between any of the meeting providers, opposed to just a single one.

Some Orgs are split on their preferred meeting providers. Sometimes, some meeting providers are better for certain circumstances. 

Maybe a PowerShell cmdlet for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e6be4a-8597-5129-7b8f-de44d2026bae
* Version Independent ID: 5292ca3c-1c6f-09e2-5347-716bb46ee1b8
* Content: [Using third-party add-ins for online meetings in Outlook for iOS and Android](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/online-meeting-add-ins-for-ios-and-android#meeting-providers-displayed-in-the-new-event-screen)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/online-meeting-add-ins-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/online-meeting-add-ins-for-ios-and-android.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@haneef95 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by msdmaguire** [comment]
@haneef95 We can also tell you that there are some changes planned in this space. Thanks again for the feedback.
