### ISSUE TITLE
ResultSize "Unlimited" is not a valid Search-AdminAuditLog value

### ISSUE THREAD

**Issue by mrkeiths** [MicrosoftDocs/OfficeDocs-Exchange#2210]
The Search-AdminAuditLog ResultSize parameter does not support 'Unlimited'.  Requesting that this note be removed from this support doc.

Thank you,
Keith

Search-AdminAuditLog -StartDate 8/25/2020 -EndDate 8/26/2020 -ResultSize unlimited -StartIndex 0
Cannot process argument transformation on parameter 'ResultSize'. Cannot convert value "unlimited" to type
"System.Int32". Error: "Input string was not in a correct format."
    + CategoryInfo          : InvalidData: (:) [Search-AdminAuditLog], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Search-AdminAuditLog
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39588ea7-e1ad-d9bf-4f8b-6c7d18bc4bc6
* Version Independent ID: 1672644e-3dbd-f02c-b149-15331dfeab52
* Content: [Search the role group changes or administrator audit logs in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/search-role-group-changes)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/search-role-group-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/search-role-group-changes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mrkeiths Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@mrkeiths Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
