### ISSUE TITLE
cut-over migration for google

### ISSUE THREAD

**Issue by nimikaul** [MicrosoftDocs/OfficeDocs-Exchange#2211]
For gsuite migration, can you please enter steps required or to be skipped if i have just 10 to 20 users and want to do a cut-over migration. Migrate them all in a single go.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration?source=docs)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@nimikaul Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @nimikaul, thank you for your feedback.

The only coexistence configuration that you perform here is related to the new subdomains for mail flow: gsuite.fabrikaminc.net and o365.fabrikaminc.net in the article.
If you don't want this coexistence, you can avoid the creation of these subdomains and add them as alias/ExternalEmailAddress/ForwardingSmtpAddress to GSuite/M365 users.

Hope it helps.

**Comment by nimikaul** [comment]
Hi Dario,

Just to check that I have got it right:
If i want a cutover migration from GSuite to Office365, then i have to
perform the following steps:

   1. Create users in Office 365 with the onmicrosoft.com email addressess.
   2. Create a project and service account in Google with all the APIs and
   access setup. (Quick question: Does the service account need to have a
   mailbox?)
   3. Login to Exchange Admin as Global Admin.
   4. In Migration Batch creation, if i select the manual option for GSuite
   migration, i need to provide the key JSON key file, and set a migration
   point.
   5. Once the migration is successful, then we can update MX records in
   the DNS server to complete the migration.


Please feel free to correct what ever step is incorrect or anything that i
might have missed.

Thanks & Regards,
Nimi Kaul

**Comment by dariomws** [comment]
Hi @nimikaul, thank you for your comment. Here we are limited to documentation issues and improvements so I must recommend that you contact support, consultancy or a forum to get more help with this process.

Anyway, to give you a small tip, these are the steps I think you need to run (using the titles in the article):

1. Create a Google Service Account
2. Enable API usage in your project
3. Grant access to the service account for your Google tenant
4. Provision users in Microsoft 365 or Office 365 (read the last paragraph in detail please, you have a mistake in your instructions)
5. "Start a G Suite migration batch with the Exchange admin center (EAC)" or "Start a G Suite migration with Exchange Online PowerShell"
6. Finalizing your migration

As you can see, I removed the titles/steps "Create a sub-domain for mail routing to Microsoft 365 or Office 365" and "Create a sub-domain for mail routing to your G Suite domain". Also, remember that you won't add these subdomains to the accounts in O365 and GSuite.

Please read each title in detail as it's a quick tip, I couldn´t read and analyse the article carefully.

**Comment by scanum** [comment]
@nimikaul  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
