### ISSUE TITLE
O365 warning disclaimer in heading

### ISSUE THREAD

**Issue by aliozturk9** [MicrosoftDocs/OfficeDocs-Exchange#2212]
Dear all,

How do i write a condition in O365 to add warning disclaimer in heading only sent by outside and delete in replies? Currently, when we delete it in replies, it deletes both replied by sender and recipient. i want to delete it on replies only replied by insider?

**Comment by scanum** [comment]
@aliozturk9 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
