### ISSUE TITLE
certified fax partner not an option

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/OfficeDocs-Exchange#2217]
I like how you ask us to look up a certified fax partners at https://www.microsoft.com/en-us/solution-providers/home yet there is no such thing as a "certified fax partners" in the search.  What are we searching for?  Could you please update the document not to drive your customers crazy?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1b95716-d62a-5b7b-5324-75eed5f4f10b
* Version Independent ID: da1f6e50-8015-0afa-1294-6427e7468300
* Content: [Setting up incoming faxing in Exchange Online](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-client-voice-mail-features/set-up-incoming-faxing)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/set-up-incoming-faxing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/set-up-incoming-faxing.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Karr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Karr, thank you for your feedback.

Cloud Voicemail takes the place of Exchange Unified Messaging (UM), there is a note about this at the top of the article. Also, I know that fax integration with Azure Cloud Voicemail is not available. There are other third-party solutions that can help you but I'm not able to mention them here, sorry.

**Comment by scanum** [comment]
@Karr  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
