### ISSUE TITLE
Update Documentation to Reflect Azure Sizing & Requirements

### ISSUE THREAD

**Issue by Pher0ah** [MicrosoftDocs/OfficeDocs-Exchange#2218]
Hi, please update the docs to give recommended Azure VM sizing and also any other requirements to run in for Azure; as most customers would like to run an Exchange server for management; and/or internal SMTP relay for their MFPs and Legacy Apps.

**Comment by scanum** [comment]
Hi @Pher0ah Thanks for the feedback, could you please link the documentation you are referring to? Thanks!

**Comment by get-itips** [comment]
Hello @Pher0ah Hany, how are you ? Please as @scanum Manuela says here, tell us which is the article you are talking about. Thank you!

**Comment by Pher0ah** [comment]
This is the article: https://docs.microsoft.com/en-us/exchange/plan-and-deploy/virtualization?view=exchserver-2019

**Comment by get-itips** [comment]
Hello @Pher0ah Harry, how are you?

I will pass along this feedback to the team, in the meantime, please have a look at [this article](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments?view=exchserver-2019), be aware that this is for a dev/test environment and it also mentions a recommendation storage for a production environment in a note in Phase 2.

Hope this information helps you.

**Comment by scanum** [comment]
@Pher0ah  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Pher0ah** [comment]
Hi, I do not see any change in the document; @get-itips comment was for dev/test environment. Microsoft is telling people that they can spin up Exchange servers in Azure, but the information in the article lacks details of the sizing process.

1. Section titled" Requirements for hardware virtualization"
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/virtualization?view=exchserver-2019#requirements-for-hardware-virtualization

The important note there is more suited in the "Exchange storage requirements" section as it talks about how to configure storage in Azure.

2. Section titled "Exchange Memory Requirements & Recommendations"
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/virtualization?view=exchserver-2019#exchange-memory-requirements-and-recommendations

This states that Quote: "As a result, using dynamic memory or memory overcommit features for Exchange isn't supported."
An azure environment by default uses dynamic memory, and memory overcommit; so we need to have a note in there to explain Microsoft's stance on this, and what needs to be done in Azure to ensure that the Exchange VM is supported.

Hope this makes sense, and we can clear this up for everyone in the world.
