### ISSUE TITLE
Disabling Directory Sync Makes 72 hours of Wait? (G Suite Migration with Directory Sync)

### ISSUE THREAD

**Issue by neonad** [MicrosoftDocs/OfficeDocs-Exchange#2221]
Hi Team,

As mentioned in the article "Perform a G Suite Migration", it requests admin to disable directory synchronization: "Once the Mail Users have been created in Microsoft 365, the Azure AD Connect may need to be disabled in order to allow the migration process to convert these users into mailboxes - see Turn off directory synchronization for Microsoft 365."

However, disabling Directory Synchronization will make it disable for 72 hours before we can start it back. This is pretty much conflicting when you perform batch wise migration and if any user wanted to reset the password at the time it will not sync back to Office 365 (Azure AD).

Kindly propose clear solution for this? How to achieve this properly when there is a directory synchronization enabled? Step by step

"Set-MsolDirSyncEnabled -EnableDirSync $false
Note:If you use this command, you must wait 72 hours before you can turn directory synchronization back on."

Thanks,
Nimesha J

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@neonad Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
