### ISSUE TITLE
Please provide clear explanation when and why you would need to create security groups

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/OfficeDocs-Exchange#2222]
The documentation states 
> The administrator prepares the servers for a cutover migration and creates empty mail-enabled security groups in Microsoft 365 or Office 365.

and also

> Create security groups and clean up delegates: Because the email migration service can't detect whether on-premises Active Directory groups are security groups, it can't provision any migrated groups as security groups in Microsoft 365 or Office 365. If you want to have security groups in Microsoft 365 or Office 365, you must first provision an empty mail-enabled security group in Microsoft 365 or Office 365 before starting the cutover migration.

Please clarify when and why one would need to provision such groups in regard of a Cut Over migration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@diecknet  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @diecknet, thank you for your feedback and help us to improve docs.microsoft.com.

I'm not sure how to clarify this. The second sentence explains your question I think:

> Create security groups and clean up delegates: Because the email migration service can't detect whether on-premises Active Directory groups are security groups, it can't provision any migrated groups as security groups in Microsoft 365 or Office 365. If you want to have security groups in Microsoft 365 or Office 365, you must first provision an empty mail-enabled security group in Microsoft 365 or Office 365 before starting the cutover migration.

- **When?** "before starting the cutover migration"

- **Why?** "Because the email migration service can't detect whether on-premises Active Directory groups are security groups, it can't provision any migrated groups as security groups in Microsoft 365 or Office 365"

You need to create manually the mail-enabled security groups before starting the migration because the migration service won't create them, but I'll update the membership.

Hope it helps.

**Comment by diecknet** [comment]
Hi @dariomws, thanks for your reply.
1. After some testing I understand that the Cutover migration attempts to create the distribution groups that are present in the On-Premise Exchange system. IMO this doc should be clear about that.

2. The doc should be clear about that the migration service tries to re-create the group memberships of the migrated mailboxes (users).

If these infos are there, then the initial wording seems okay.

**Comment by dariomws** [comment]
@diecknet,

Also from the article:

> Additionally, this migration method only moves mailboxes, mail users, mail contacts, and **mail-enabled groups**. If any other Active Directory object, such as user mailbox that is not migrated to Microsoft 365 or Office 365 is assigned as a manager or delegate to an object being migrated, you must remove them from the object before migration.

This migration method doesn't migrate security groups that are not mail-enabled. If you have mail-enabled security groups on-premises, they'll be created as distribution groups. This is why if you want mail-enabled security groups, you need to create them manually before the migration.

I applied a minor update to the article to let the reader know that the mail-enabled groups are migrated with their membership (based on your feedback). For more information also read:
https://docs.microsoft.com/exchange/mailbox-migration/what-to-know-about-a-cutover-migration
