### ISSUE TITLE
UM is Retired

### ISSUE THREAD

**Issue by 3novsan** [MicrosoftDocs/OfficeDocs-Exchange#2224]
My understanding is UM is retired and has already been transitioned to Cloud Voicemail. Is this Article still relevant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64682808-e62f-b40c-7dde-c06bc99276f7
* Version Independent ID: a1545444-4b0a-43fb-5e11-9ee051dce0b0
* Content: [Voice mail in Exchange Online Unified Messaging](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/voice-mail-unified-messaging)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/voice-mail-unified-messaging.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/voice-mail-unified-messaging.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@3novsan thank you for your feedback. Yes, you are correct that UM in Exchange has been retired. However, we are leaving this and other related articles available for the near future, for those customers who have older versions of Exchange, and who are using that legacy UM functionality.
