### ISSUE TITLE
Dead link in section 7 for Office 365

### ISSUE THREAD

**Issue by mcnabsystems** [MicrosoftDocs/OfficeDocs-Exchange#2225]
I get all the way down to the crucial step of linking my G Suite account to my new Office 365 email so I can migrate and the article ends with a dead link.  Argh!!  No idea how to finish this process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62f5860-4f99-6794-f8d6-2207b7f19979
* Version Independent ID: c28b87f8-1984-6522-021f-bae92e46d08c
* Content: [Prepare your Gmail or G Suite account for connecting to Outlook and Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mcnabsystems  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @mcnabsystems
