### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by dscam** [MicrosoftDocs/OfficeDocs-Exchange#2226]
The link for 'Recover deleted items or email in Outlook on the web' goes to page about opening and using a shared mailbox rather than https://support.microsoft.com/en-gb/office/recover-deleted-items-or-email-in-outlook-web-app-c3d8fc15-eeef-4f1c-81df-e27964b7edd4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496c2124-3973-e6d1-385e-4ec25228dc49
* Version Independent ID: cd70012a-5cdf-bac5-3a29-df38b19df1cb
* Content: [Recover deleted messages in a user's mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dscam  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
