### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by aaashgrieve** [MicrosoftDocs/OfficeDocs-Exchange#2228]
There is a dead link under the Migration limitations section in the sentence "To increase this limit, see Office 365 now supports larger email messages." It points to https://www.microsoft.com/microsoft-365/blog/2015/04/15/office-365-now-supports-larger-email-messages-up-to-150-mb/ which doesn't seem to exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-US/exchange/mailbox-migration/perform-g-suite-migration?WT.mc_id=365AdminCSH)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Hi @aaashgrieve, thank you for your feedback. The link is working fine for me. It brings me to "Office 365 now supports larger email messages—up to 150 MB" as expected. Please verify your connection and try again?
