### ISSUE TITLE
Add step to raise ProhibitSendQuota and ProhibitSendReceiveQuota

### ISSUE THREAD

**Issue by officebuilder19** [MicrosoftDocs/OfficeDocs-Exchange#2230]
This doc is very helpful. However I would advise you add the step of increasing the ProhibitSendQuota and ProhibitSendReceiveQuota. Doing this step resolved a recent issue for our team, where a worker's Recoverable Items folder failed to process items on to her Archive mailbox.

We followed each step of the doc, but nothing moved beyond the Purges subfolder. We opened an MS case, and the Support Engineer instructed us to increase the ProhibitSendQuota and ProhibitSendReceiveQuota on the mailbox. Our normal setting is 50GB, and we raised it to 100GB. Once we did that, the Managed Folder Assistant processed the items.

I suspect our SE pulled this step from the MS doc on cleaning/deleting items for Exchange on-prem. It's in the section on using Exchange Management Shell, steps 1 and 5.

https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/recoverable-items-folder/clean-up-deleted-items?view=exchserver-2019#use-the-exchange-management-shell-to-clean-up-the-recoverable-items-folder-for-mailboxes-that-are-placed-on-hold-or-have-single-item-recovery-enabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c21112a-deb5-83b3-160e-0149a1e510f6
* Version Independent ID: 4edc9fcd-4971-470b-c56e-e1a2e78b8854
* Content: [Clean up or delete items from the Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/clean-up-deleted-items)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by officebuilder19** [comment]
I understand this type of subject is posted to Pull Requests. I posted here because the Feedback button for "This page" on the article links to directly to Issues.

**Comment by scanum** [comment]
@officebuilder19 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officebuilder19 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
