### ISSUE TITLE
Missing section

### ISSUE THREAD

**Issue by stalks** [MicrosoftDocs/OfficeDocs-Exchange#2239]
In Step 2, under "Prerequisite steps on the legacy Exchange server" there is an internal note to the writer of this document to add an extra section:

"Add an additional step here suggesting to run Source Side Validation script at mailbox server on Exchange Server 2010. Please use the examples as documented here: https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Making-your-public-folder-migrations-faster-and-more-reliable/ba-p/917622"

This needs turning into that "extra step"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Microsoft 365 or Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders?view=exchserver-2019#step-1-download-the-migration-scripts)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@stalks Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @stalks, thank you for your feedback and help us to improve docs.microsoft.com.

I have fixed this issue 4/5 days ago:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2241

**Comment by scanum** [comment]
@stalks  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
