### ISSUE TITLE
Update note on AAD Connect timing

### ISSUE THREAD

**Issue by SuperTekBoy** [MicrosoftDocs/OfficeDocs-Exchange#2242]
https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders
In Step 3 there is a note that mentions:

"You must wait until ActiveDirectory synchronization has completed to see the changes. This process can take up to 3 hours to complete. If you don't want to wait for the recurring synchronizations that occur every three hours, you can force directory synchronization at any time. For detailed steps to do force directory synchronization, see Azure AD Connect sync: Scheduler."

AAD Connect is every 30 minutes by default. No longer 3 hours.

**Comment by scanum** [comment]
@SuperTekBoy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @SuperTekBoy
