### ISSUE TITLE
Japanese translation is inacurate

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/OfficeDocs-Exchange#2244]
For the section below, the Japanese translation is missing "Apps". Please edit.

Microsoft 365 or Office 365: Hybrid deployments are supported in all Microsoft 365 and Office 365 plans that support Azure Active Directory synchronization. All Microsoft 365 Business Standard, Business Basic, Enterprise, Government, Academic and Midsize plans support hybrid deployments. Microsoft 365 **_Apps_** for business and Home plans don't support hybrid deployments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@UKayo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@officeglobal Could you kindly help with this issue. Thanks!

**Comment by rbstrachan** [comment]
Hello @scanum. I see the problem, there's just a word missing in the Japanese translation. I can add it in quickly, but I don't know which file to add it into, can you help me out?

:)

**Comment by OfficeGlobal** [comment]
@UKayo article was updated and published live

**Comment by scanum** [comment]
@rbstrachan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
