### ISSUE TITLE
Open Public Folder in new OWA

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#2245]
I can't connect to Public Folder in OWA!
![image](https://user-images.githubusercontent.com/43539433/93046744-e2c0d800-f65a-11ea-803a-2ac4ef2831a2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1322ea00-e4ee-5858-c224-c8b886f6a7d0
* Version Independent ID: 059da329-0f7f-cd54-31d7-cdec5eda9141
* Content: [Use favorite public folders in Outlook on the web](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/use-favorite-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
