### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by sammie-p** [MicrosoftDocs/OfficeDocs-Exchange#225]
The link "Using Windows Server Backup to back up and restore Exchange data" goes to the wrong place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39a1f3ef-3137-603e-65ed-41a0fbd0cbb2
* Version Independent ID: c2bcddd7-cca5-3118-b810-12fda87b195f
* Content: [Backing up email in Exchange Online](https://docs.microsoft.com/en-us/exchange/back-up-email)
* Content Source: [Exchange/ExchangeOnline/back-up-email.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/back-up-email.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by chrisda** [comment]
@sammie-p I fixed this. The change should be visible soon.
