### ISSUE TITLE
Outlook can't download multiple OABs on the same computer?

### ISSUE THREAD

**Issue by AblerJi** [MicrosoftDocs/OfficeDocs-Exchange#2250]
[Enter feedback here]
In the article, it says the following.
>Outlook supports only one OAB per user account on a computer. If you have multiple profiles, only one profile can download the OAB. If you have to use two or more profiles that use Cached Exchange Mode, **make sure that one of the profiles is configured to not download the OAB.**

![image](https://user-images.githubusercontent.com/20233530/93153836-1116e400-f73d-11ea-94f1-e7c60ec0b799.png)
As shown in above Photo, it seems Outlook can download multiple OABs on the same computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9985dd-585c-6cbe-6964-02f0b5d1c53d
* Version Independent ID: 96727ac8-6e44-0450-c505-7234483529fa
* Content: [Offline address books in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/offline-address-books/offline-address-books)
* Content Source: [Exchange/ExchangeOnline/address-books/offline-address-books/offline-address-books.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/offline-address-books/offline-address-books.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@AblerJi Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
