### ISSUE TITLE
"How do I know it worked" shall use on-prem user rather than Online user

### ISSUE THREAD

**Issue by jformacek** [MicrosoftDocs/OfficeDocs-Exchange#2253]
Section wrongly specifies online user instead of onprem user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5e98d1-4f1a-b0dc-5abc-218895903ecf
* Version Independent ID: a273e1f9-03e6-721d-e3f3-4af949a9c8c0
* Content: [Configure Exchange Online public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-exo-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-exo-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-exo-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jformacek Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @jformacek Jiri
