### ISSUE TITLE
Exchange Server Deployment Assistant Link is broken

### ISSUE THREAD

**Issue by HumbleSage0** [MicrosoftDocs/OfficeDocs-Exchange#2255]
In the important section this link is broken.

**Comment by scanum** [comment]
@HumbleSage0 Could you please link the documentation you are referring to. Thanks!

**Comment by dariomws** [comment]
@HumbleSage0 Could you please link the documentation you are referring to. Thanks!

**Comment by HumbleSage0** [comment]
@scanum I'm not ignoring you guys, I'm trying to find where that broken link was. I was doing research for an Exchange Server 2019 Hybrid deployment and the page that takes you to the assistant wasn't working.

**Comment by dariomws** [comment]
Thanks, @HumbleSage0!

Maybe it was a temporary outage. I think we can close this issue and if you find the link you can always reopen this issue or open a new one, don't worry.

**Comment by HumbleSage0** [comment]
@dariomws Agreed. If I stumble on it again, I'll report it.
