### ISSUE TITLE
This is only doable over powershell, where's the code?

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-Exchange#2257]
IMO, the example is incomplete, since the only wasy to do this is over powershell, and no PS commands are provided in here so the documentation is incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d52e882-9b75-3091-79c5-c6733aa924b1
* Version Independent ID: 42c575aa-bb89-3aa2-21f1-adf4771ec10b
* Content: [Address book policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-book-policies/address-book-policies)
* Content Source: [Exchange/ExchangeOnline/address-books/address-book-policies/address-book-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/address-book-policies/address-book-policies.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@j0rt3g4 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @j0rt3g4 Jose, how are you?
PowerShell Procedures for ABP are indeed provided on a link in that article

> Implementing an ABP is a multi-step process that requires planning. For more information, see [Address book policy procedures in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-book-policies/address-book-policy-procedures).

Hope this information helps you,

**Comment by scanum** [comment]
@j0rt3g4  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
