### ISSUE TITLE
Suggest including error messages or expected behavior should the max rule size be exceeded. 

### ISSUE THREAD

**Issue by DatabaseAsAService** [MicrosoftDocs/OfficeDocs-Exchange#2260]
Suggest including error messages or expected behavior should the max rule size be exceeded. 

Would like to see the page document what happens if you (attempt to) exceed the maximum rule size. What error message you see, or if the rules are simply ignored past the maximum, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d76e96a-b0a9-552b-e0cf-fa5a1caeee85
* Version Independent ID: 93a0041c-a6ea-0255-0127-a2ad8d4ba436
* Content: [Modify the space used by Inbox rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@DatabaseAsAService  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @DatabaseAsAService how are you, the article currently says

> When you reach the 256 KB limit, you'll be warned that you can't create any more rules or that you can't update a rule.

and I tested it on OWA and is consistent to what is says there 

![image](https://user-images.githubusercontent.com/36666927/93603979-00a37b00-f982-11ea-8cba-b896e2f5ad36.png)

Hope this information clarifies it to you! Thanks for your feedback

**Comment by scanum** [comment]
@DatabaseAsAService  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
