### ISSUE TITLE
Needlessly gendered

### ISSUE THREAD

**Issue by ThomasSaintThomas** [MicrosoftDocs/OfficeDocs-Exchange#2265]
This can just say their, it doesn't have to say his or her.
"Members of this role group can only manage the configuration each user can manage on his or her own mailbox."
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f333b76-dca6-5f8d-2cf2-6e3d01faba4c
* Version Independent ID: e4286faa-224b-06aa-994d-29ee568c0aca
* Content: [Permissions in Exchange Online](https://docs.microsoft.com/en-us/exchange/permissions-exo/permissions-exo)
* Content Source: [Exchange/ExchangeOnline/permissions-exo/permissions-exo.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/permissions-exo/permissions-exo.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ThomasSaintThomas  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
