### ISSUE TITLE
port 143 is no longer available for IMAP connection in Office365 Exchange online environment.

### ISSUE THREAD

**Issue by NeoZhuMSFT** [MicrosoftDocs/OfficeDocs-Exchange#227]
"Port: This is the TCP port number used to connect to the IMAP server. Use port 143 for unencrypted connections, port 143 for Transport Layer Security (TLS) connections, or port 993 (the default), for SSL connections. Port 993 is appropriate for most IMAP servers."

[Enter feedback here]

The port 143 is not longer available for IMAP connection in Office 365 Exchange online.  The setting should be Port 993 for Transport Layer Security (TLS) connections only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b46ddbf-612b-f477-9316-f4c5ae16ce5a
* Version Independent ID: b493f85c-5f92-e80c-246e-31ec59698771
* Content: [Learn more about setting up your IMAP server connection](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/setting-up-your-imap-server-connection)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/setting-up-your-imap-server-connection.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/setting-up-your-imap-server-connection.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@NeoZhuMSFT Thank you for this feedback

We appriciate you letting us know when the aritcles needs to be updated. I will get this information over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by DesmondLimHH** [comment]
How do you add an IMAP connection that does not use encryption?  There's no option for "None".

**Comment by chrisda** [comment]
@NeoZhuMSFT, I updated the topic. Thanks for the feedback.
