### ISSUE TITLE
Needs sovereign cloud overlay

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/OfficeDocs-Exchange#2275]
While this article is extremely helpful, it's problematic in the GCCH/DoD space as all the endpoints referenced are from the commercial cloud instance.  Having some type of sovereign cloud overlay with the correct endpoint values to use (primarily for the auth server cmdlets) would definitely increase it's utility.

**Comment by scanum** [comment]
@drdenson  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
