### ISSUE TITLE
Documentation Public Folder access in OWA 

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#2281]
Follow-up on: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2245
Support case: #21986161 

Please update the Docs article accordingly:

Right click the folders option in OWA
cid:image_d89da268-c333-4efb-8ca7-fd6e06bc8858.png
Choose the option Add Public Folders to Favorites
Choose the public folder you want to add and click the Option Add Public Folder the one highlighted below.
cid:image_7a98ccb1-6bcc-425d-a726-416d5a39fd54.png

**Comment by trudolf-msft** [comment]
![image](https://user-images.githubusercontent.com/43539433/93879444-febc1d80-fcdb-11ea-8e66-76742e6ed27e.png)
![image](https://user-images.githubusercontent.com/43539433/93879480-10052a00-fcdc-11ea-9afa-e00e1b9a49e6.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
