### ISSUE TITLE
Journaling Clarification

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-Exchange#2282]
You may want to consider adding documentation in line with exchange On-Premise Journalling:

From the Exchange 2013 Article:

In an Exchange 2013 organization, all email traffic is routed by Mailbox servers. All messages traverse at least one server running the Transport service in their lifetime. The Journaling agent is a compliance-focused transport agent that processes messages on Mailbox servers. It fires on the OnSubmittedMessage and OnRoutedMessage transport events.

There is no indication where the journaling actually occurs in Exchange Online in this article and would help to determine what gets journalled when delivered to EXO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d4ec80-7a55-398a-22e9-3f5df24a867b
* Version Independent ID: 4543c414-41d1-b8fe-8a58-4dc61ccf61ff
* Content: [Journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dkotars  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by Kateyanne** [comment]
@dkotars Thank you for your suggestion. After reviewing the ask, we believe the level of detail in the article is sufficient for Exchange Online.
