### ISSUE TITLE
Missing details on Audit setting

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#2289]
Please add details on the "Audit this rule with severity level"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81c1119-165b-f408-698c-1092a781ba63
* Version Independent ID: 1a1b6d9a-a75c-e74d-ff84-ccbdf15091de
* Content: [Mail flow rules (transport rules) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback and help us to improve docs.microsoft.com.

Could you kindly provide more detail? I cannot found the sentence "Audit this rule with severity level" in this article.

**Comment by danmyhre** [comment]
Right, it should be added to this section  :)

https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules#mail-flow-rule-properties
