### ISSUE TITLE
Support for Exchange 2010?

### ISSUE THREAD

**Issue by mprentice22153** [MicrosoftDocs/OfficeDocs-Exchange#2291]
Will the HCW continue to support Exchange 2010 SP3 after the end of life date Oct 13, 2020?  The wizard is a critical tool for many partners migrating customers to M365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec121a3-cccf-1164-777e-be5e4dc9d2c5
* Version Independent ID: 37c911be-c56e-8975-260b-6f8ddc497ee9
* Content: [Hybrid Configuration wizard FAQs](https://docs.microsoft.com/en-us/exchange/hybrid-configuration-wizard-faqs)
* Content Source: [Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
