### ISSUE TITLE
mail flow (transport) rules limitations?

### ISSUE THREAD

**Issue by steve-bg** [MicrosoftDocs/OfficeDocs-Exchange#2295]
Hi there,
I wondered what are the size limitations on mail flow rules e.g. in kilobytes per rule or total?
For example what if we create a rule to delete emails coming from address1 or address 2 or address3 etc ,  thousands of addresses?
Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81c1119-165b-f408-698c-1092a781ba63
* Version Independent ID: 1a1b6d9a-a75c-e74d-ff84-ccbdf15091de
* Content: [Mail flow rules (transport rules) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by steve-bg** [comment]
Thanks for the answer but our Exchange is on premise. What would be the link to ask the proper people then?
