### ISSUE TITLE
Ambiguity on "message source"

### ISSUE THREAD

**Issue by jvplopper** [MicrosoftDocs/OfficeDocs-Exchange#2297]
Under "Use the Security & Compliance Center to configure Enhanced Filtering for Connectors on an inbound connector", step 2b there are three settings given.  In the first setting (automatically detect...) I'm curious what is meant by "one message source."  For example, we have just one 3rd party spam solution but it has multiple IP addresses (redundancy) that it can send to o365 from.  So my question is whether a "message source" is considered the single spam solution (i.e. one hop previous to o365) or is it considered the number of individual IP addresses.  Maybe an example to help users decide?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd501e4-be27-1da8-e250-7cc1ac22c8ec
* Version Independent ID: ada2e5a7-646f-3576-5834-4727151b7743
* Content: [Enhanced filtering for connectors](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jvplopper Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @jvplopper will try to clarify the sentence.
