### ISSUE TITLE
Staging migration information needs to be corrected.

### ISSUE THREAD

**Issue by IpsitoDutta** [MicrosoftDocs/OfficeDocs-Exchange#2299]
I wanted to address the following two issues with this document. 

Feedback 1: Under staging migration it says, "_Staged migrations are best for organizations running Exchange 2003 or Exchange 2007 **with fewer than 2000 mailboxes** who want to move mailboxes over in batches over a couple weeks._"

This is incorrect. You will see as per the article; https://docs.microsoft.com/en-us/exchange/mailbox-migration/what-to-know-about-a-staged-migration, it says:

A staged migration is recommended when:

- Your source email system is Microsoft Exchange Server 2003 or Microsoft Exchange Server 2007.
- You have **more than 2,000 mailboxes**.

Feedback 2: It also says, "**While you can do staged migrations with later versions of Exchange**, we strongly recommend that you use the Minimal hybrid migration option instead."

However, the article ; https://docs.microsoft.com/en-us/exchange/mailbox-migration/what-to-know-about-a-staged-migration will also say: "**You can't use a staged migration to migrate Exchange 2013 or Exchange 2010 mailboxes to Microsoft 365 or Office 365**.You can't use a staged migration to migrate Exchange 2013 or Exchange 2010 mailboxes to Microsoft 365 or Office 365."

The article needs to be corrected to indicate that staged migrations only allow for migrations from Exchange 2003-07 with no restrictions on the no: of mailboxes that can be migrated, as staged migration allows for 2000 mailboxes per batch and an admin can create multiple batches.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac90643-c8f6-2d5a-0113-27a48db85d5a
* Version Independent ID: 29a5b3fb-16df-df30-5eac-7b82b1b55a08
* Content: [Use the Microsoft 365 and Office 365 mail migration advisor](https://docs.microsoft.com/en-us/exchange/mail-migration-jump)
* Content Source: [Exchange/ExchangeHybrid/mail-migration-jump.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/mail-migration-jump.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@IpsitoDutta Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
