### ISSUE TITLE
RemoveOMEv2 action is not documented. Please add.

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-Exchange#230]
Please get full details how it works with OMEv2, since it's a *core* change from how RemoveOME used to work for OMEv1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8d245fb-eb4b-879d-4da8-7e7be414a179
* Version Independent ID: a05b031b-db9a-6f28-09a3-68640eb9c570
* Content: [Mail flow rule actions in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rule-actions)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rule-actions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rule-actions.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@hudish Thank you for this feedback

I will get this request for more details over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@hudish I updated the topic.

Thanks for the feedback.
