### ISSUE TITLE
Missing one word.

### ISSUE THREAD

**Issue by IpsitoDutta** [MicrosoftDocs/OfficeDocs-Exchange#2300]
"Exchange 2010: At least instance of Mailbox, Hub Transport, and Client Access server roles installed (separately or on one server; we strongly recommend on one server)." Needs to be replaced with:

"Exchange 2010: At least **one** instance of Mailbox, Hub Transport, and Client Access server roles installed (separately or on one server; we strongly recommend on one server)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@IpsitoDutta Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @IpsitoDutta !
