### ISSUE TITLE
Clarify Subject Name of Certificate

### ISSUE THREAD

**Issue by Air-Git** [MicrosoftDocs/OfficeDocs-Exchange#2306]
At the end of the document, it gives the suggested subject name of the certificate as the actual name of the domain i.e. contoso.com. i.e. no hostname portion.

In the text, it does not say this. It says that "The subject name is the FQDN that the certificate is issued to and should use the primary SMTP domain that is shared between the on-premises and Exchange Online organizations." This is like a normal certificate, with the proviso that the domain portion of the FQDN should be the same as the primary SMTP domain. In this case, the subject name would just be the normal name e.g. mail.contoso.com.

Can you clarify whether the Subject name requires to be in the format specified, without a hostname, or whether that is a mis-statement of the text?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fee8aac-fb8d-452b-7c1d-56db8cd1c3ff
* Version Independent ID: 61edeeae-af33-1074-ac0e-9311f9ddeca7
* Content: [Certificate requirements for hybrid deployments](https://docs.microsoft.com/en-us/exchange/certificate-requirements)
* Content Source: [Exchange/ExchangeHybrid/certificate-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/certificate-requirements.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Air-Git Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Air-Git, thank you for your feedback and help us to improve docs.microsoft.com.

It's recommended that you use your primary shared SMTP domain in the subject name. If you don't use O365 to relay messages, you can use your hybrid name instead of.
For more information see:
https://docs.microsoft.com/exchange/troubleshoot/email-delivery/office-365-notice
https://techcommunity.microsoft.com/t5/exchange-team-blog/office-365-message-attribution/ba-p/749143

**Comment by Air-Git** [comment]
Yes. The comment I am providing is that the web page shows using the SMTP domain AS the certificate subject, not IN the certificate subject. It shows as the example "contoso.com", where you would expect to see "smtp.contoso.com".

**Comment by dariomws** [comment]
@Air-Git I'm updating (https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2320) the following sentence:
"The subject name is the FQDN that the certificate is issued to and should use the primary SMTP domain that is shared between the on-premises and Exchange Online organizations."
To:
"The subject name is the primary SMTP domain that is shared between the on-premises and Exchange Online organizations."

You should use the SMTP domain as the certificate subject. If you want to use something like "smtp.contoso.com", please read the following article in detail:
https://docs.microsoft.com/exchange/troubleshoot/email-delivery/office-365-notice
