### ISSUE TITLE
Primary shared SMTP domain

### ISSUE THREAD

**Issue by WakeyField** [MicrosoftDocs/OfficeDocs-Exchange#2307]
Can you confirm if the Primary Shared SMTP Domain is genuinely required in the Certificate for Hybrid and what purpose it serves, or is this a mistake?

I have configured a certificate with simply the exchange namespace as the subject and SAN and this does not appear to impact Hybrid services?

Service | Suggested FQDN | Field
-- | -- | --
**Primary shared SMTP domain | contoso.com | Subject name**
Autodiscover | Label that matches the external Autodiscover FQDN of your Exchange 2013 Client Access server, such as autodiscover.contoso.com | Subject alternative name
Transport | Label that matches the external FQDN of your Edge Transport servers, such as edge.contoso.com | Subject alternative name

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
