### ISSUE TITLE
The Google Contacts API is now deprecated

### ISSUE THREAD

**Issue by FamousBern** [MicrosoftDocs/OfficeDocs-Exchange#2309]
![depricated_contact_API](https://user-images.githubusercontent.com/32365949/95330457-441e4480-08b1-11eb-808b-58ab3ab6101d.PNG)

Is it safe to use it?  in the doc guide you have included it's Oauth scope URI.

**Comment by FamousBern** [comment]
Is it recommended to use the legacy Oauth scope https://www.google.com/m8/feeds/ in migration process?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
