### ISSUE TITLE
Can you clarify on this topic please

### ISSUE THREAD

**Issue by RamlingaReddy** [MicrosoftDocs/OfficeDocs-Exchange#2316]
Please clarify if we can block access from Outlook on iOS and Android using Client Access Rules. Below information is not very clear. Customer is a financial organization and would like to restrict access to O365 only from their corporate LAN/Public IPs.

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules
---------------------------------------------
Scope | n/a | Specifies the type of connections that the rule applies to. Valid values are:• Users: The rule only applies to end-user connections.• All: The rule applies to all types of connections (end-users and middle-tier apps).
---------------------------------------------

Client Access Rules and middle-tier applications
Many applications that access Exchange Online use a middle-tier architecture (clients talk to the middle-tier application, and the middle-tier application talks to Exchange Online). A Client Access Rule that only allows access from your local network might block middle-tier applications. So, your rules need to allow the IP addresses of middle-tier applications.

Middle-tier applications owned by Microsoft (for example, Outlook for iOS and Android) will bypass blocking by Client Access Rules, and will always be allowed. To provide additional control over these applications, you need to use the control capabilities that are available in the applications.
----------------------------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9cdf39f-da71-43ab-0ceb-a816bdc19d04
* Version Independent ID: 1fff6b28-f8d8-d9b3-1730-db2cac7835a0
* Content: [Client Access Rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by RamlingaReddy** [comment]
Thank you @smithre4 

Customer would like to restrict access to O365 from specific IP (from Windows 10 or iOS devices).  Once the user authenticates (and pass conditional access based IP checks), they can access email from other IP addresses. Set-CASMailBox disables access completely. Any pointers if this can be achieved ?

**Comment by smithre4** [comment]
You've already answered your own question :) - conditional access location condition - https://docs.microsoft.com/azure/active-directory/conditional-access/location-condition.

**Comment by smithre4** [comment]
See https://docs.microsoft.com/azure/active-directory/conditional-access/concept-continuous-access-evaluation
