### ISSUE TITLE
Resource is spelled incorrectly

### ISSUE THREAD

**Issue by ESC-Adam** [MicrosoftDocs/OfficeDocs-Exchange#2317]
For the Question below, "Resource" is spelled incorrectly.

Q: What do I need to consider when my OnPremise Environment is running in a Resoruce Forest Scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook for iOS and Android in Exchange Online: FAQ](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ESC-Adam  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for reporting @ESC-Adam

**Comment by get-itips** [comment]
@scanum The question was removed from the article, the PR is not needed anymore. Please close.
