### ISSUE TITLE
Identify where Exchange F3 Licenses Fall

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-Exchange#2318]
Documentation makes no mention of F3. Can we clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec37e4b-e81e-ac6a-e435-575b2320e553
* Version Independent ID: 49f631d2-e881-d368-a91a-acd1429baa8b
* Content: [Mailbox plans in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dkotars Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
