### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by ickthwart** [MicrosoftDocs/OfficeDocs-Exchange#2324]
Not just for this page, but the dates at the top of all your documentation pages appear to be in US format, i.e. mm/dd/yyyy, regardless of PC/browser regional settings.
This is confusing for most of the world.
Could they be displayed in international format, e.g. 20 Oct 2020 to avoid any doubt?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ickthwart Thanks for the feedback, we will consider adding this to the documentation.
