### ISSUE TITLE
"Installation Prerequisites" part is outdated

### ISSUE THREAD

**Issue by BeatBrunner** [MicrosoftDocs/OfficeDocs-Exchange#2329]
the command "Test-HybridConnectivity -TestO365Endpoints" ends in a failure because it seems that the host watchdog.servicebus.windows.net is no longer in service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@BeatBrunner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @BeatBrunner, thank you for your feedback and help us to improve docs.microsoft.com.

I reported this warning. Anyway, to report this kind of issue I suggest you open a support ticket, they will be able to help you better as here we are limited to documentation issues and improvements.

Support URL: https://docs.microsoft.com/microsoft-365/admin/contact-support-for-business-products.

Thank you!
