### ISSUE TITLE
Cleanup test repos created during migration

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/OfficeDocs-Exchange#233]
Looks like a few repos got created to test migrating the content https://github.com/MicrosoftDocs?utf8=%E2%9C%93&q=OfficeDocs-Exchange-Test-pr&type=&language=
These repos show up when trying to search content in the MicrosoftDocs repo and in https://open.microsoft.com/ portal

**Comment by AndreaBarr** [comment]
@nschonni Thank you for pointing this out to us

I will get this over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@nschonni duly noted.

**Comment by nschonni** [comment]
@chrisda should this stay open till they're cleaned up, or is it a "won't fix"?

**Comment by nschonni** [comment]
hmm, I guess the bot likes me :stuck_out_tongue:

**Comment by chrisda** [comment]
@nschonni it's more like a 'can't fix': yes, everyone should delete branches that they're no longer using, but no, I can just go through now and start blitzing out branches. We'll spread the word (again) to delete unused branches.

**Comment by chrisda** [comment]
@nschonni, I'm recategorizing this as "Won't Fix". I brought this up, and the response for clean-up was underwhelming. Nothing is going to be done about it.
