### ISSUE TITLE
This page is out of date. Google has changed how they tools are working and this instruction leave You with nothing. 

### ISSUE THREAD

**Issue by michalsarna** [MicrosoftDocs/OfficeDocs-Exchange#2332]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-migration-endpoint-in-microsoft-365-or-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@michalsarna , thank you for the feedback. Google is always updating their Web properties and we are always working to catch up and keep our visuals and instructions updated. We will add another round of updates to our upcoming work queue. Thank again for pointing this out.
