### ISSUE TITLE
Items being moved from Deletions to Purges after the retention period expires

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/OfficeDocs-Exchange#2333]
We have these 2 paragraphs in the article which are related:

_Items remain in the Deletions subfolder until the deleted item retention period is reached. The default deleted item retention period for Exchange Online is 14 days. You can modify this period for mailboxes up to a maximum of 30 days. In addition to a deleted item retention period, the Recoverable Items folder is also subject to quotas. To learn more, see Recoverable Items mailbox quotas later in this topic.

**After the deleted item retention period expires, the item is moved to the Purges folder and is no longer visible to the user.** When the Managed Folder Assistant (MFA) processes the mailbox, items in the Purges subfolder are purged from Exchange Online._

As far as I know, after 14 days in Deletions folder, the items are completely deleted from store based on RetainDeletedItemsFor setting on the mailbox, they are not moved to Purges. This is something that I verified using mailbox Store Events logs. If you manually delete the items from Deletions using the Outlook feature "Recover deleted items" to access the Deletions area, then the item is moved to Purges, where it stays again 14 days because the retention period is reset based on last modified time (and the item IS modified, because it is moved from Deletions to Purges).

Please confirm with Engineering what the correct behavior is an update the article accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbbc82b-b1c8-f2b7-9f57-9fa9137305a3
* Version Independent ID: f1ce321a-ed5e-fe57-450d-35cc7b104350
* Content: [Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Alex-Catalin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Alex-Catalin, thank you for your feedback and help us to improve docs.microsoft.com.

I think the trick here is when the Managed Folder Assistant (MFA) run. On Exchange Server MFA process all mailboxes every day, while in Exchange Online it runs once a week.
This is why I think you see that the items are being removed when the end of the deleted item retention period is reached in Exchange Server.

Anyway, I appreciate if you can share you mailbox Store Events logs to check.

**Comment by Alex-Catalin** [comment]
Hi Dario,

I don’t have those Store Events logs anymore, they were from customer cases that I was troubleshooting. This should not have anything to do with the period that the MFA takes to process a mailbox and in EXO, the SLA is 7 days, it’s not that the mailboxes are processed once a week, it’s that we usually process them daily, but if this is not possible for resource reasons (server overloaded etc), we still need to process it at least once in 7 days.

Please check the information with Engineering 😊. I am 99% sure that I am right on what I said in my initial note.

Thank you,

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+3)
[cid:image001.png@01D6B13A.5C578F30]

**Comment by dariomws** [comment]
Hi @Alex-Catalin, 

I didn't know that you are a Microsoft employee. I know that it could be more than once every 7 days, but I told you the public (documented) information for the final customer.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=npherson

I'll try to confirm it with the product group, but it could take some time.

**Comment by Alex-Catalin** [comment]
Hi Dario,

Thanks for the info! I followed the steps (hopefully in a correct way) and linked the accounts.

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+3)
[cid:image001.png@01D6B1D3.A258C230]

**Comment by dariomws** [comment]
Hi @Alex-Catalin,

Thank you!

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=Alex-Catalin

**Comment by Alex-Catalin** [comment]
Thanks Dario!

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+3)
[cid:image001.png@01D6B1E9.EB5FD1B0]

**Comment by dariomws** [comment]
@Alex-Catalin this is the information I got:

```
After 14 days (the value of the RetainDeleteItemsFor setting on the mailbox) the items are completely deleted from the Deletions folder; they are not moved to the Purges folder. If you use "Recover deleted items" in Outlook to manually delete the items from Deletions, then the items are moved to Purges, where they stay for 14 days (the value of the RetainDeleteItemsFor setting on the mailbox) because the retention period is reset based on last modified time (and the item IS modified, because it is moved from Deletions to Purges).

In on-prem, the RetainDeletedItemsUntilBackup (mailbox or database) and RetainDeletedItemsFor (database) also come into play in terms of how long the deleted messages are retained.
```

Conclusion: You're right, I'll update the article tomorrow.

**Comment by dariomws** [comment]
Sorry, the articleS:
https://docs.microsoft.com/exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder
https://docs.microsoft.com/exchange/policy-and-compliance/recoverable-items-folder/recoverable-items-folder
https://docs.microsoft.com/exchange/recoverable-items-folder-exchange-2013-help

**Comment by Alex-Catalin** [comment]
Thank you Dario!

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+3)
[cid:image001.png@01D6B27C.41E8E840]

**Comment by dariomws** [comment]
@Alex-Catalin done.

Any feedback will be appreciated, you can clearly see the updates here:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2340/files

**Comment by Alex-Catalin** [comment]
Hi Dario,

I would add some extra info (see bolded text):

=====================================
### Single item recovery


If an item is removed from the Deletions subfolder, either by a user purging the item by using the Recover Deleted Items feature or by an automated process such as the Managed Folder Assistant (retention tag set to permanently delete for example), the item is moved to the Purges subfolder, and it can't be recovered by the user. When the Managed Folder Assistant processes the Recoverable Items folder for a mailbox that has single item recovery enabled, any item in the Purges subfolder isn't purged if the deleted item retention period hasn't expired for that item. This means that an admin can still recover the item by using an eDiscovery tool such as In-Place eDiscovery or Content Search.

=====================================

The rest I think is ok 😊.

Thank you,

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+3)
[cid:image001.png@01D6B2CD.B63673B0]

**Comment by dariomws** [comment]
Done!
