### ISSUE TITLE
NDR code 5.1.1 vs 5.4.1?

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/OfficeDocs-Exchange#2336]
Are these NDR codes correct? I received an NDR with

`550 5.4.1 Recipient address rejected: Access denied. AS(xxxxxxx)`

which is quite different from 5.1.1 as mentioned above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6d0e4-0ea5-f8a9-bf67-bf7cacc74b3e
* Version Independent ID: c72592d3-bfd1-ddf3-793f-dcc0374db074
* Content: [Email non-delivery reports in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@andrePKI Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
