### ISSUE TITLE
This documentation of the Exchange Mobile device policy is pretty terrible

### ISSUE THREAD

**Issue by Axilla-the-HUN** [MicrosoftDocs/OfficeDocs-Exchange#2341]
This is basically a list of features, and not documentation for how to use.. Why can't Microsoft take this kind of document over the finish line and provide clear direction for usage cases. Every engineer I work with has to find 3rd party documentation to cobble together the information Microsoft provides and real use cases in order to make the MS products work.

For example some screenshots with the location of the feature in the console would be a start. Drilling into the policy and showing where to define things. Instead it becomes some reading a list to interpret data to implement the function...this documentation is not helpful actualizing in the real world. I have been trying to figure out how to add or edit the Family devices in the Exchange online Mobile Device Access policies and there is nothing about this.

Here's an idea for Microsoft why don't you have an interactive model of the entire Exchange Admin center. Then link documentation to it in a GUI with how to videos and step by step guides for each feature. This glossary list of features is not really helpful at all.  

The GitHub Doc repository is better than technet by a mile but you are still way off the mark in providing full featured workable documentation useful for engineers deploying your tools.  

Hun out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8953d102-718c-d28a-976a-5906000567c3
* Version Independent ID: 0a13e776-9b35-7b46-5bb5-86b4ba8ddbe5
* Content: [Mobile device mailbox policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Axilla-the-HUN Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
