### ISSUE TITLE
On-prem/hybrid configuration

### ISSUE THREAD

**Issue by b-col** [MicrosoftDocs/OfficeDocs-Exchange#2348]
> If your organization uses an on-premises Exchange or hybrid Exchange environment, you should use the on-premises Exchange admin center (EAC) to **create and manage shared mailboxes**.

Should the above **bold** text read "configure email forwarding"? The article does not relate to shared mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0712dfaf-5113-e50d-19b9-c79ca780e22f
* Version Independent ID: 5482a4ff-b479-69a9-2abe-c7fe253f9fee
* Content: [Configure email forwarding for a mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/configure-email-forwarding.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@b-col  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
