### ISSUE TITLE
"Step 5: Add users to the appropriate groups in the HAB" is wiping all the DG members not replacing or adding

### ISSUE THREAD

**Issue by riohedfield** [MicrosoftDocs/OfficeDocs-Exchange#2349]
Hello, the Cmdlet from Step 5 is removing all the existing members and not adding new ones if the -members parameter includes "users" or "users+groups", it updates the membership list only when adding "Groups"
Update-DistributionGroupMember -Identity "Corporate Office" -Members @{Add="aalberts@contoso.com","dhamilton@contoso.com","rmpatel@contoso.com"} 

I suggest:

$Userslist = Import-CSV C:\Temp\Distribution-Groups-Members.csv
ForEach ($User in $Userslist)
{
Add-DistributionGroupMember -Identity "Corporate Office" -Member $User.PrimarySmtpAddress
}

Or 

Add-DistributionGroupMember -Identity "Corporate Office" -Member "aalberts@contoso.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe9eef8a-3acf-ed01-ddec-c1bc1f0a7f73
* Version Independent ID: f6c9ef82-8b91-2b3c-ec21-8675a3f25386
* Content: [Enable or disable hierarchical address books in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/hierarchical-address-books/enable-or-disable-hierarchical-address-books#step-5-add-users-to-the-appropriate-groups-in-the-hab)
* Content Source: [Exchange/ExchangeOnline/address-books/hierarchical-address-books/enable-or-disable-hierarchical-address-books.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/hierarchical-address-books/enable-or-disable-hierarchical-address-books.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@riohedfield  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @riohedfield I could reproduce, thanks for the feedback, editing the example now.
