### ISSUE TITLE
Start-MailboxSearch, Stop-MailboxSearch, and Set-MailboxSearch won't be available from the 1. October 2020

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/OfficeDocs-Exchange#2351]
WARNING: Warning: As of July 1, 2020, the *-MailboxSearch cmdlets are being retired. You will no longer be able to create new searches using the New-MailboxSearch cmdlet
and Microsoft Support will no longer provide assistance as per the notice in the link below.  You may continue to use these cmdlets at your own risk.  On October 1, 2020,
Start-MailboxSearch, Stop-MailboxSearch, and Set-MailboxSearch won't be available. Only Remove-MailboxSearch will be available to delete searches and holds. See
https://go.microsoft.com/fwlink/?linkid=2113221 to learn more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a137ee50-f3b9-07e1-7214-58d282896a66
* Version Independent ID: 70fc82e3-88f8-bc68-a094-37b81c778038
* Content: [Create or remove an In-Place Hold](https://docs.microsoft.com/en-us/exchange/security-and-compliance/create-or-remove-in-place-holds?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@uz-it Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
