### ISSUE TITLE
Summary report output

### ISSUE THREAD

**Issue by SiboneloJunior** [MicrosoftDocs/OfficeDocs-Exchange#2355]
The documentation states that the new mail trace has the 'Export all results' option, whilst in reality it does not exist

> You can export the results after you've selected one or more rows by clicking Export results and then selecting Export all results, Export loaded results, or Export selected.

![new_mail_trace](https://user-images.githubusercontent.com/60383036/99198697-fa275900-27a2-11eb-857c-db79a9b4891c.png)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b171f582-bbe1-0ddf-2b0b-cd43769dd3ca
* Version Independent ID: 2a03592e-719c-5004-655a-ce71e28ccbc0
* Content: [Message trace in the modern EAC](https://docs.microsoft.com/en-us/Exchange/monitoring/trace-an-email-message/message-trace-modern-eac)
* Content Source: [Exchange/ExchangeOnline/monitoring/trace-an-email-message/message-trace-modern-eac.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/trace-an-email-message/message-trace-modern-eac.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@SiboneloJunior Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by chrisda** [comment]
@SiboneloJunior, I updated the statement in the topic so it now just says:

 You can export the results after you've selected one or more rows by clicking **Export results**.

Thanks for the feedback.
