### ISSUE TITLE
Missing document or link about Exchange online

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/OfficeDocs-Exchange#2357]
---
**Issue moved from MicrosoftDocs/feedback#3237**
- Please respond to @ttkuc1.

---

_From @ttkuc1 on Friday, October 30, 2020 5:30:56 AM_

**Describe the bug**
The docs about Exchange Online Resource mailbox can not be seen with a 404 error

**To Reproduce**
tried to access below docs but got a 404 error
both English and Japanese version got error
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-room-mailboxes
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-equipment-mailboxes
https://docs.microsoft.com/ja-jp/exchange/recipients-in-exchange-online/manage-room-mailboxes
https://docs.microsoft.com/ja-jp/exchange/recipients-in-exchange-online/manage-equipment-mailboxes

**Expected behavior**
they can be seen

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 1909
 - Browser Microsoft Edge
 - Version 86.0.622.51 (64bit)

**Additional context**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3237**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Friday, October 30, 2020 5:30:57 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
Looks like redirects weren't put in place when these files were deleted.

**Comment by dariomws** [comment]
Hi @ttkuc1, thank you for your feedback.

Could you kindly let me know where did you find these links? These articles do not exist for Exchange Online.

Thanks!

**Comment by scanum** [comment]
@ttkuc1  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
