### ISSUE TITLE
New room resource maillboxes set to AutoUpdate

### ISSUE THREAD

**Issue by runely** [MicrosoftDocs/OfficeDocs-Exchange#2358]
Microsoft has started to migrate our mail data from EUR datacenters to NOR datacenters.

After this job started all new mailboxes are created in NOR datacenter.

New room resource mailboxes created with the following PowerShell command will automatically set the AutomateProcessing for the calendar to AutoUpdate.
```powershell
New-Mailbox -DisplayName "new-room" -Alias "new-room" -PrimarySmtpAddress "new-room@....no" -Name "new-room" -Room
```

[The documentation](https://docs.microsoft.com/en-us/Exchange/recipients/room-mailboxes?redirectedfrom=MSDN&view=exchserver-2019#create-a-room-mailbox) states the following:
```text
By default, it'll automatically accept or decline requests depending on whether the requests conflict with any existing meetings on its calendar.
````

New mailboxes in NOR servers are setup with AutpUpdate when it should be setup with AutoAccept

![Skjermbilde 2020-11-18 kl  08 22 36](https://user-images.githubusercontent.com/25814673/99498590-03b5ea00-2978-11eb-8519-4d9ed64e5a89.png)

**Comment by scanum** [comment]
@runely Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by runely** [comment]
Just an FYI.

Support, or more correct the product team, found a bug in NOR data centers which causes new room mailboxes to be created with AutomateProcessing set to `AutoUpdate` instead of `AutoAccept`
