### ISSUE TITLE
Add warning/note on switching to Exchange Online PowerShell for step 3

### ISSUE THREAD

**Issue by dab-vie** [MicrosoftDocs/OfficeDocs-Exchange#2359]
In "**Step 4: Create the public folder mailboxes in Exchange Online**" it's not clear that one has to switch to the Exchange Online PowerShell. Steps 1-3 have to be done on the local Exchange. For step 4 one would have to connect to the Exchange Online organization. However, there's no hint that this is the case. And I'm seeing several customers getting stuck at this very point.

A short note highlighting that this step has to be executed in an Exchange Online PowerShell would certainly prevent more people from getting stuck here.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Microsoft 365 or Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dab-vie Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Looks like you already create a PR for it.

**Comment by scanum** [comment]
@dab-vie  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
