### ISSUE TITLE
is it possible to mark synced / exported contacts as "managed contacts" in iOS

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/OfficeDocs-Exchange#236]
Since iOS 11.3 it is possible to mark contacts as manages if they come from a managed mail profile. How can we have the same capabilities with Outlook for iOS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@pedrr I am not sure how to mark contacts as managed when using an IOS. Let me get this over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by smithre4** [comment]
Managed contacts can only be created via a managed EAS profile.

**Comment by AndreaBarr** [comment]
@pedrr it looks like this issue has been resolved. I am going to close this issue at this time. If this is not resolved please re-open this issue.
