### ISSUE TITLE
Would be nice to see the default settings for all Mailbox Plans

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#2361]
It doesn't seem to be documented anywhere what the default settings are.  For example, the default MaxSendSize seems to be 35MB and default MaxReceiveSize seems to be 36MB.  But the Exchange Online Limits only show 150MB.

Is there any chance the actual default settings can be posted on this page, and maintained?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec37e4b-e81e-ac6a-e435-575b2320e553
* Version Independent ID: 49f631d2-e881-d368-a91a-acd1429baa8b
* Content: [Mailbox plans in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@JeremyTBradshaw Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by JeremyTBradshaw** [comment]
@scanum completely disagree.  This isn't a support request, I'm simply asking to know what the default mailbox plan settings are.  It should be documented.

Would reopen if I could.
