### ISSUE TITLE
Viewing Skipped Items

### ISSUE THREAD

**Issue by jackaogle** [MicrosoftDocs/OfficeDocs-Exchange#2362]
After a migration batch has a Data Inconsistency Score of "Investigate" you can click on the _View details_ link, then select the mailbox with skipped items, then click the _Skipped item details_ link. Only "There are no items to show in this view." displays.

I can also attempt to view the skipped items using the cmdlet "Get-MigrationUserStatistics" and it returns:
SkippedItemCount : 182
SkippedItems     : {}

How can you view skipped items to know what is being skipped?

**Comment by scanum** [comment]
@jackaogle Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
