### ISSUE TITLE
Error when completing batch

### ISSUE THREAD

**Issue by jackaogle** [MicrosoftDocs/OfficeDocs-Exchange#2363]
Getting error when trying to complete a batch:

Error: UnableToUsePrimaryGmailForwardingAddressException/DisallowedForwardingAddressPermanentException/BadRequestWebTransientException/WebException: Error: Couldn't use the primary address as the forwarding address "user@mydomain.com". Please select a different target delivery domain. --> The requested forwarding address is not allowed. --> The web server responded with a 400 Bad Request error. Uri: https://www.googleapis.com/gmail/v1/users/user@mydomain.com/settings/forwardingAddresses --> The remote server returned an error: (400) Bad Request.

**Comment by scanum** [comment]
@jackaogle Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
