### ISSUE TITLE
"Add and request read receipts and delivery notifications" is not working!

### ISSUE THREAD

**Issue by pappjanos** [MicrosoftDocs/OfficeDocs-Exchange#2367]
[Enter feedback here]
Hello! The "Add and request read receipts and delivery notifications." link is not working. It jumps to https://support.microsoft.com/office/a34bf70a-4c2c-4461-b2a1-12e4a7a9214 
but there is an error message in that page.
I need the information how can I add request and read receipts. Please direct me to the correct page, or update the link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d2c66-f9d8-7ac2-55c8-1ccfbe966bf6
* Version Independent ID: 3dc90f07-c2bb-9f37-82c2-a713f0b8f27c
* Content: [What happened to delivery reports?](https://docs.microsoft.com/en-us/exchange/monitoring/what-happened-to-delivery-reports-in-office-365)
* Content Source: [Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Hi @pappjanos thanks for pointing out that broken link. We will update it shortly.

The article you are looking for is here: https://support.microsoft.com/en-us/office/add-and-request-read-receipts-and-delivery-notifications-a34bf70a-4c2c-4461-b2a1-12e4a7a92141

Thanks again for the feedback.

**Comment by pappjanos** [comment]
Hello David!
I think the link you provided is about using the outlook client.
I would be interested in how to set this in GRAPH api programmatically.
regards: János
