### ISSUE TITLE
Configuration Step Mismatch

### ISSUE THREAD

**Issue by FamousBern** [MicrosoftDocs/OfficeDocs-Exchange#2368]
Hello!

In this guide, on "STEP 5: Create a migration batch and start migrating Gmail mailboxes" number 8, information on that step is false for newbies. When you create migration endpoint for the first time or have only one migration endpoint created, exchange online does not prompt or present "Set the migration endpoint page" to select the migration endpoint you have created, it skips that step. But if you create more than one migration endpoint, that is when the exchange online presents you "Set the migration endpoint page". As an expert in IMAP systems, this runtime error should be solved, hence the "Set the migration endpoint page" be presented to the user or simply add this information as a tip, so users won't be worried why they can't see that page, and the documentation refers it.

 I believe this should be a pull request.

Thank you.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by FamousBern** [comment]
Hello!

This issue is well known, the way system is configured, is not inline with the docs. Therefore a need to update docs.
