### ISSUE TITLE
Things To Consider Before Mailbox Migration From Google Workspace to MS365/O365

### ISSUE THREAD

**Issue by FamousBern** [MicrosoftDocs/OfficeDocs-Exchange#2369]
Hello!

In this guide, you have defined ways perform consumer mailbox migration from google workspace to Ms365. There is most important information that has not been addressed well, this information is not even documented by google themselves. On opening support service is when you get the explanation. The information to be added is as follows:

1 Google does not use the same structure as Exchange online in storing email messages. Whichever method you choose to migrate mailboxes from google workspace/gmail to exchange online, you still end up having duplicate emails in exchange online hence, mailbox size end up being doubled.

2 Google workspace/gmail users should be let know that, "All Mails" instance/label translates to "Archive" folder in exchange online. After migration this folder adds a copy of each messages in other instances/labels that either are system or user created labels/instances. That is a big that i tried to figure out the solution on my own, i had no valid respond to client.

3 All system or user created instances/labels in google workspace/gmail once migrated to exchange online, exchange online creates a folder that takes up extra size. Technically its impossible to delete system labels/instances in google workspace, thus users should be let know, before they perform migration to disable all user created instances/labels. This instances/labels do not occupy space in google workspace but in exchange online they occupy.

4 Its a good idea for users to have the correct pre-requisites done before preforming the migration and end up in exchange online storage size dilemma in midst of migration therefore causing more than service ticket opened for a problem that should be dealt in the docs.

5 In this guide, there is added information about how to troubleshoot this issues, but users don't know why they are being asked to exclude [Gmail] folder under "excluded folder page".

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
