### ISSUE TITLE
Translation is not accurate

### ISSUE THREAD

**Issue by ChuixinZeng** [MicrosoftDocs/OfficeDocs-Exchange#237]
"邮件限制引用一组的邮件和可以处理由 Exchange 服务器的连接数设置限制。"Should be changed to"邮件限制指的是对Exchange服务器可以处理的消息和连接数量设置的一组限制。"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3d340941-d016-a179-a8ae-91324b7e1c8b
* Version Independent ID: 503ba34b-c8a2-75d3-0548-3642fa566bbe
* Content: [消息速率限制和限制](https://docs.microsoft.com/zh-cn/Exchange/mail-flow/message-rate-limits?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/message-rate-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/message-rate-limits.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@ChuixinZeng Thank you for pointing this out to us. 

I am going to get this translation issue over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by ChuixinZeng** [comment]
The error rate of machine translation is high, and I will try my best to help improve it

**Comment by OfficeGSX** [comment]
Hello,

The reported translation is no longer present in the article, therefore we cannot fix the issue.

Best regards,

Jiri

**Comment by OfficeGSX** [comment]
The article is HumanTranslated and published live
