### ISSUE TITLE
DIrectory Sync section out of date

### ISSUE THREAD

**Issue by david-tap** [MicrosoftDocs/OfficeDocs-Exchange#2372]
Looks like the section on Directory Sync needs to be updated for the current sync tools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc6de85c-181e-3f88-cc88-216b77c253b0
* Version Independent ID: cc3516fd-4bac-5ee3-f792-8e4437f2a3fe
* Content: [Fix email delivery issues for error code 550 5.1.10 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@david-tap Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @david-tap
