### ISSUE TITLE
Duplicate article

### ISSUE THREAD

**Issue by b-col** [MicrosoftDocs/OfficeDocs-Exchange#2373]
This article seems to be a duplicate of the below:
https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/configure-legacy-public-folders-for-hybrid

This article has more recent updates but I am unable to leave feedback on the linked article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@b-col Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @b-col 
How are you? Hope you are doing good.
I could get information from the team, the articles are intended for different content sets (one is for EXO and the other is for Exchange On-Premises), so both articles will remain as is.
Many thanks for your feedback.
@scanum please close.
