### ISSUE TITLE
Scripts not working anymore

### ISSUE THREAD

**Issue by simonhess93** [MicrosoftDocs/OfficeDocs-Exchange#2374]
I am thinking that both scripts mentioned in the article are outdated as they do not work anymore. I am getting several error messages while executing it. For example:
```
Cannot process argument transformation on parameter 'Identity'. Cannot convert the "Berner Bildungszentrum Pflege"
value of type "Deserialized.Microsoft.Exchange.Data.Directory.Management.MailPublicFolder" to type
"Microsoft.Exchange.Configuration.Tasks.MailPublicFolderIdParameter".
    + CategoryInfo          : InvalidData: (:) [Disable-MailPublicFolder], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Disable-MailPublicFolder
    + PSComputerName        : outlook.office365.com
```

Could you please investigate this? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e5e98d1-4f1a-b0dc-5abc-218895903ecf
* Version Independent ID: a273e1f9-03e6-721d-e3f3-4af949a9c8c0
* Content: [Configure Exchange Online public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-exo-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-exo-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-exo-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
