### ISSUE TITLE
Translation is not accurate

### ISSUE THREAD

**Issue by ChuixinZeng** [MicrosoftDocs/OfficeDocs-Exchange#238]
"这些限制包括消息处理率、 SMTP 连接率和 SMTP 会话超时值。这些限制协同工作来防止 Exchange 服务器接受并传递邮件而产生过载。尽管邮件和连接的大型积压可能正在等待处理，邮件限制限制启用 Exchange 服务器中有序的方式处理的消息和连接。"Should be changed to"这些限制包括消息处理速率、SMTP连接速率和SMTP会话超时值。这些限制协同工作，以保护Exchange服务器不会因为接受和传递邮件而过载。尽管可能积压有大量的邮件和连接正在等待处理，邮件限制使得Exchange服务器能够以一种有序的方式处理邮件和连接。"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3d340941-d016-a179-a8ae-91324b7e1c8b
* Version Independent ID: 503ba34b-c8a2-75d3-0548-3642fa566bbe
* Content: [消息速率限制和限制](https://docs.microsoft.com/zh-cn/Exchange/mail-flow/message-rate-limits?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/message-rate-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/message-rate-limits.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@ChuixinZeng Thank you for pointing this out to us.

I am going to get this translation issue over to the Exchange team for investigation.

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by OfficeGSX** [comment]
Hello,

The reported translation is no longer present in the article, therefore we cannot fix the issue.

Best regards,

Jiri

**Comment by OfficeGSX** [comment]
The article is HumanTranslated and published live
