### ISSUE TITLE
Lack of link/clarity in article.

### ISSUE THREAD

**Issue by ChrisParrBIE** [MicrosoftDocs/OfficeDocs-Exchange#2381]
[Enter feedback here]
https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/inspect-message-attachments 
AttachmentHasExecutableContent entry in the "Inspect the file properties of attachments" section says "This condition matches messages that contain executable files as attachments. The supported file types are listed here." "Listed here" implies that there will be a link to the "Supported executable file types for mail flow rule inspection" section. May be clearer to say 'Listed in the section below' if there isn't going to be a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd230cd-1717-a932-a5c9-02db4f1b050c
* Version Independent ID: 24dcb706-d0d9-61d3-e99d-289db401ffaa
* Content: [Use mail flow rules to inspect message attachments in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/inspect-message-attachments)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ChrisParrBIE Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @ChrisParrBIE
