### ISSUE TITLE
Wrong step screenshots and instructions

### ISSUE THREAD

**Issue by DaveWut** [MicrosoftDocs/OfficeDocs-Exchange#2384]
Hi, 

Both 

https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration?branch=dmaguire-gsuite-migration#create-a-sub-domain-for-mail-routing-to-microsoft-365-or-office-365

and 

https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration?branch=dmaguire-gsuite-migration#create-a-sub-domain-for-mail-routing-to-your-g-suite-domain

has the same screenshots. The first link seems to be for Office 365, but instead I have mixed step that seems to be designed for G Suite. 

Could you please look at this? 

Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration?branch=dmaguire-gsuite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@DaveWut How did you come to view my private branch of this content (?branch=dmaguire-gsuite-migration)? I'm doubly confused because I deleted that branch a while ago. Pretty sure the true public version of the content is more up-to-date.

**Comment by DaveWut** [comment]
Hi @msdmaguire I think I found the page while looking via Google or elsewhere under the administrative panels. Nonetheless, the same problem can be viewed without the branch name : 
https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-microsoft-365-or-office-365
https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-your-g-suite-domain

**Comment by msdmaguire** [comment]
@DaveWut Thanks for the background information. A real head-scratcher. As for the issue you've raised, I'm comparing the two sections and the screen shots from Google are not identical. Under "Create a sub-domain for mail routing to your G Suite domain" the visual is for a dialog titled "Add a domain alias for <your domain>," whereas under "Create a sub-domain for mail routing to Microsoft 365 or Office 365" it is a dialog titled "Add a Domain."

**Comment by DaveWut** [comment]
Hey @msdmaguire  maybe I misunderstood the documentation. On our current setup, I've added o365.example.com to Microsoft 365 and not G Suite, so that G Suite can forward all emails to that domain. Sorry for the interruption. You can close this incident. 🙂
