### ISSUE TITLE
Migration batches in Office 365 from Bluehost

### ISSUE THREAD

**Issue by AssaadLutf** [MicrosoftDocs/OfficeDocs-Exchange#2385]
When Using Migration batches in Office 365 through uploading the users and passwords using a CSV file, the suggested format in the community page is not clear, so in order to do so to migrate from blue host to office 365 using the same domain and same users email id's, we need to copy the same email id with same domain in both fields of EmailAddress and UserName columns, not as shown in the demonstration to add user name only it should be associated with the domain name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a62d4e4-616e-3f98-e5b6-5544f923480d
* Version Independent ID: 3f90a7c2-6130-6b55-1cfa-d7a9f4386cd5
* Content: [Migrate other types of IMAP mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@AssaadLutf Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @AssaadLutf, thank you for your feedback.

I think there is some information to warn you about that in the present article. I want to sand out them:

- We'd give you the exact steps if we could, but there are so many different email systems out there that you need to find this out on your own. When you find the list of mailboxes, keep this window open.

- > [!NOTE]
   > A lot of email systems use the entire email address as the sign-in name. Note also, if you are using the same domain in Microsoft 365 or Office 365 and your source email system, the columns A and B can be identical.

There is also a link to the following article:
https://docs.microsoft.com/exchange/mailbox-migration/migrating-imap-mailboxes/csv-files-for-imap-migrations

**Comment by AssaadLutf** [comment]
> Hi @AssaadLutf, thank you for your feedback.
> 
> I think there is some information to warn you about that in the present article. I want to sand out them:
> 
> * We'd give you the exact steps if we could, but there are so many different email systems out there that you need to find this out on your own. When you find the list of mailboxes, keep this window open.
> * **NOTE:** A lot of email systems use the entire email address as the sign-in name. Note also, if you are using the same domain in Microsoft 365 or Office 365 and your source email system, the columns A and B can be identical.
> 
> There is also a link to the following article:
> https://docs.microsoft.com/exchange/mailbox-migration/migrating-imap-mailboxes/csv-files-for-imap-migrations

Thanks for your comment, I didn't understand that this is what was meant from that note.
It would be great to add that this is the case for such a scenario when migrating from Bluehost to O365 using the same domain.
It will be a useful hint for others

Best regards

**Comment by dariomws** [comment]
Thanks @AssaadLutf, we want to avoid to talk about a specific provider as there are a lot of them around the world and we cannot test some of them as they are external systems. This note is generic to each one that uses the email address as the sign-in name, such as Bluehost.

**Comment by scanum** [comment]
@AssaadLutf Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
