### ISSUE TITLE
please update ticket at: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2366

### ISSUE THREAD

**Issue by markcalleran** [MicrosoftDocs/OfficeDocs-Exchange#2386]
I submitted ticket 2366 two weeks ago. You recommended that I log a ticket with MS Support. I did, they recommended I bring this back to you as only you can action the ticket. I undated 2366, but have had no update from you. So now a new ticket to refocus the mind.

Thanks, Mark.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c518bc-12b9-6ee8-362d-70ac54983dd6
* Version Independent ID: 102cd602-f1a6-acf9-a9b8-f47f57de3708
* Content: [Microsoft 365 and Office 365 migration performance and best practices](https://docs.microsoft.com/en-us/exchange/mailbox-migration/office-365-migration-best-practices)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@markcalleran We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by markcalleran** [comment]
Please do not yet close this ticket.

The details you need to add to this page are as follows:


Company name: BCC Collaboration Company
Website:             www.bcchub.com<http://www.bcchub.com>
Blurb:                  Helping companies by supporting their collaboration migration strategy. Best in class supplier of migration tools based on Domino platform, for migrating to Microsoft Exchange and Office365.


I would appreciate if, as offered, this could be added to the page at: OfficeDocs-Exchange/office-365-migration-best-practices.md at public · MicrosoftDocs/OfficeDocs-Exchange (github.com)<https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/office-365-migration-best-practices.md>

Thanks,

Mark.

**Comment by markcalleran** [comment]
Company name: BCC Collaboration Company
Website: 	www.bcchub.com
Blurb:		Helping companies by supporting their collaboration migration strategy. Best in class supplier of migration tools based on Domino platform, for migrating to Microsoft Exchange and Office365.

**Comment by msdmaguire** [comment]
@markcalleran Your info was added to the article. The change should be live within 24 hours.
