### ISSUE TITLE
No help for "investigate" score

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/OfficeDocs-Exchange#2389]
"A small amount of significant data loss..." -- huh?  Is it a small amount or is it significant? 
Oh, is it like an insignificant blizzard with massive snowfall?  Or, more like a minor virus with half a million deaths.

The "guidance" for investigate does not provide any  -guidance- on how to -investigate-.

If the recommendation is to simply approve all scores of "investigate", then there is no need for this score. How do I see how many items, or which items, or which kind of items are causing the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40bce01-0b1f-1952-5198-d5a15211b533
* Version Independent ID: 3f0ac568-cfbd-5255-d803-b7883c32c50f
* Content: [Track and Prevent Migration Data Loss](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/track-prevent-data-loss-dcs)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@boomalator Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by boomalator** [comment]
So there’s no purpose for the links encouraging feedback on the documentation page?

It is not a product support issue that someone used small and significant in the same sentence. That’s just bad documentation.

The documentation also does not appear to describe what happens when large items are detected and then the migration batch is approved.

This GitHub issue is all about the doc not the product.

On Dec 6, 2020, at 10:16 PM, Manuela Scanu <notifications@github.com> wrote:

﻿

@boomalator<https://github.com/boomalator> Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
