### ISSUE TITLE
Contradictory information regarding age of message traces for immediate results

### ISSUE THREAD

**Issue by michaelhensley** [MicrosoftDocs/OfficeDocs-Exchange#239]
The document "Run a Message Trace and View Results" says (in several places) results for messages less than 7 days old are displayed in the EAC. The document "Message Trace FAQ" says results for messages less than 10 days old are displayed in the EAC.

I believe 10 is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7684ef8f-2f6d-7c73-fddb-19b94096e82a
* Version Independent ID: 9910c94c-df87-74c1-fa32-e153857a64ab
* Content: [Run a Message Trace and View Results](https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results)
* Content Source: [Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@michaelhensley Thank you for this feedback

We apricate you pointing out the discrepancy on when old messages are displayed in the EAC. I'm going to get this over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@michaelhensley I asked those in the know, and here's what's going on:

- The real-time limit in the EAC is 7 days; anything greater than 7 days is returned in a downloadable CSV.

- The real-time limit in the Security & Compliance Center is 10 days.

- The real-time limit for the Get-MessageTrace cmdlet in Exchange Online PowerShell is 10 days; after that, you need to use the \*-HistoricalSearch cmdlets.

I updated the Message Trace FAQ topic accordingly.

Thanks for the feedback.
