### ISSUE TITLE
Data loss prevention - Installation prerequisites - licensing

### ISSUE THREAD

**Issue by adrianwells** [MicrosoftDocs/OfficeDocs-Exchange#2392]
Hi. Please review and expand the [Installation prerequisites](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention#installation-prerequisites) as the links do not appear to link to helpful Microsoft licensing documents regarding the licensing requirements to enable the described features. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32c304f-a00c-5d66-d3e2-9ddf700d121e
* Version Independent ID: 0bb81f36-0b92-263a-6ee1-9b282f20a44d
* Content: [Data loss prevention](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention?source=docs)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@adrianwells  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
