### ISSUE TITLE
Please add detail for ##Receive, FilteredAsSpam status

### ISSUE THREAD

**Issue by S-Berens** [MicrosoftDocs/OfficeDocs-Exchange#2393]
Good day,

I'd like to request adding a definition and description for the "##Receive, FilteredAsSpam" status.  

With multiple systems to handle spam in Office 365, it'd be helpful to know if this was delivered to the user, and their Outlook client Filtered it as spam and the user can find the message in their Junk Email folder, or was NOT delivered to the user, they shouldn't expect to see this message in their mailbox, and instead find it in their next Quarantine report.

Stay safe and be well.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7684ef8f-2f6d-7c73-fddb-19b94096e82a
* Version Independent ID: 9910c94c-df87-74c1-fa32-e153857a64ab
* Content: [Run a message trace and view the results in the Exchange admin center](https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results)
* Content Source: [Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@S-Berens  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
