### ISSUE TITLE
Missing information in "What do you need to know before you begin?"

### ISSUE THREAD

**Issue by pkothree** [MicrosoftDocs/OfficeDocs-Exchange#2394]
In the segment "What do you need to know before you begin?", therre is a reference to "Domains" in the linked article (https://docs.microsoft.com/en-us/exchange/permissions-exo/feature-permissions). The is no mention of "domain" in the linked article.

This section needs more clarification:
"You need to be assigned permissions before you can perform this procedure or procedures. To see what permissions you need, see the "Domains" entry in the Feature permissions in Exchange Online topic."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1640bb5-ca97-15ff-28e5-5efe4e73193f
* Version Independent ID: e957bd3e-5d4c-333c-45ff-6fd694f34670
* Content: [Manage accepted domains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@pkothree  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
