### ISSUE TITLE
The term 'get-recoverableitems' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/OfficeDocs-Exchange#2395]
```
get-recoverableitems : The term 'get-recoverableitems' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a
path was included, verify that the path is correct and try again.
```

Is this command no longer available?
I connected to Exchange **Online** using modern authentication, using the v2 module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496c2124-3973-e6d1-385e-4ec25228dc49
* Version Independent ID: cd70012a-5cdf-bac5-3a29-df38b19df1cb
* Content: [Recover deleted messages in a user's mailbox in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by michelderooij** [comment]
It's available, and not part of the module but of imported cmdlets after establishing your session. 
You are assigned the Mailbox Import/Export role, as also mentioned in the docs article? 
https://docs.microsoft.com/en-us/powershell/module/exchange/get-recoverableitems?view=exchange-ps

**Comment by jbostoen** [comment]
I did before reconnecting.

How long does it take before it comes available? Or do I need to connect in a special way?

Thanks!

**Comment by jbostoen** [comment]
Seems it took some time, but it’s fixed!
