### ISSUE TITLE
Authentication Policy Parameter cannot be found

### ISSUE THREAD

**Issue by Rohit-MITA** [MicrosoftDocs/OfficeDocs-Exchange#2397]
Getting this error while applying a authentication policy for a specific user:

Set-User -Identity test@exapmle.com -AuthenticationPolicy "Block Basic Auth"
A parameter cannot be found that matches parameter name 'AuthenticationPolicy'.
    + CategoryInfo          : InvalidArgument: (:) [Set-User], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-User
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Rohit-MITA Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
