### ISSUE TITLE
Windows Server 2016 Prerequisites

### ISSUE THREAD

**Issue by DelectableMechanisations** [MicrosoftDocs/OfficeDocs-Exchange#24]
Under the 'Windows Server 2016 Prerequisites' the 'Mailbox server role' is missing .NET Framework 4.7.1 as a prerequisite as recommended here: https://support.microsoft.com/en-nz/help/4099852/cumulative-update-10-for-exchange-server-2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange 2016 prerequisites](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prerequisites)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi!

Thanks for bringing this to our attention! I've updated the topic to include .NET 4.7.1 for Windows Server 2016.
