### ISSUE TITLE
Need to indicate what Office apps currently using legacy auth will do when it is blocked

### ISSUE THREAD

**Issue by knyhus** [MicrosoftDocs/OfficeDocs-Exchange#2401]
The doc says how to config O2K13 (regedit) and that O2K16+ are compliant (i.e., CAN do modern auth) but
a) is it possible they are config'd to use an old protocol and therefore are NOT compliant, and if so,
b) what will the user experience be when legacy auth is blocked? In my case it's autodiscover, MAPI over HTTP, OAB, Exchange Web Services.

[Enter feedback here] <-- does feedback go below or above "here"?

The doc says how to config O2K13 (regedit) and that O2K16+ are compliant (i.e., CAN do modern auth) but
a) is it possible they are config'd to use an old protocol and therefore are NOT compliant, and if so,
b) what will the user experience be when legacy auth is blocked? In my case it's autodiscover, MAPI over HTTP, OAB, Exchange Web Services.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@knyhus Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @knyhus how are you? Hope you are doing good.

I would like to ask you a question to get some clarifications so I can analyze if any improvement to the article is needed

> The doc says how to config O2K13 (regedit) and that O2K16+ are compliant (i.e., CAN do modern auth) but
> a) is it possible they are config'd to use an old protocol and therefore are NOT compliant, and if so,

Do you mean, if Outlook 2016+ can be configured intentionally to try to use and old protocol?


Thanks

**Comment by knyhus** [comment]
Yes, I mean is there another way to config OL2016 that ends up using IMAP or SMTP, for ex., bcuz if so then we need to know how to undo/fix that.Thanks.

-------- Original message --------

**Comment by get-itips** [comment]
> Yes, I mean is there another way to config OL2016 that ends up using IMAP or SMTP, for ex., bcuz if so then we need to know how to undo/fix that.Thanks.

Hello @knyhus I am not aware of settings in Outlook 2016+ to force legacy auth, at least did not find anything official.
If I am an administrator and I force MA, Outlook 2013 (with reg) and Outlook 2016+ will use it, if for any reason, you do not use the registry (Outlook 2013) or find a way to force Outlook 2016 to not use MA, they won't successfully connect to ExOn.

I hope that answers your inquiry.

**Comment by knyhus** [comment]
Thanks. I was rememberng the (very pre-MFA) days of manual config of OL where you could select, among other things, "basic auth."

-------- Original message --------

**Comment by scanum** [comment]
@knyhus Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
