### ISSUE TITLE
Constituent@atg.in.gov

### ISSUE THREAD

**Issue by AmsterdamnoordBuurtbuddyCie-ABC** [MicrosoftDocs/OfficeDocs-Exchange#2403]
[](https://secure.in.gov/attorneygeneral/2353.htmurl)
[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 40c92567-1479-8a19-9ee6-cc3563ed5bfc
* Version Independent ID: 313638dc-b9dc-9e58-50a9-b46245c8e35e
* Content: [Fix email delivery issues for error code 550 5.1.1 through 5.1.20 in Exchange Online](https://docs.microsoft.com/nl-nl/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AmsterdamnoordBuurtbuddyCie-ABC** [comment]
koninkrijk.amsterdam | Office 365 | Constituent
-- | -- | --
Action Required |   | Recipient
  |   |   |   |   |  
  |   |   |   |  
Unknown To address |   |

**Comment by AmsterdamnoordBuurtbuddyCie-ABC** [comment]
`554 5.4.14`

**Comment by scanum** [comment]
@AmsterdamnoordBuurtbuddyCie-ABC Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
