### ISSUE TITLE
Issue with changing group of users 

### ISSUE THREAD

**Issue by chadwanderson** [MicrosoftDocs/OfficeDocs-Exchange#241]
Tried running this.
$Users = Get-User -ResultSize unlimited -Filter {(RecipientType -eq 'UserMailbox') -and (Department -like 'IT Department')}
$Users | foreach {Set-User -Identity $_ -AuthenticationPolicy BlockBasicAuth}

Got this error.
Cannot process argument transformation on parameter 'Identity'. Cannot convert the "Chad Anderson" value of type
"Deserialized.Microsoft.Exchange.Data.Directory.Management.User" to type
"Microsoft.Exchange.Configuration.Tasks.UserIdParameter".

Been digging into this but I am not the greatest at PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Product: **office-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chadwanderson** [comment]
That did work for me.  Thank you.

**Comment by chrisda** [comment]
@chadwanderson thanks for the follow-up. I modified the topic accordingly, although I used MicrosoftOnlineServicesId instead of WindowsEmailAddress.
