### ISSUE TITLE
The hold setting may take up to 240 minutes to take effect

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/OfficeDocs-Exchange#2411]
It would seem that we now get the message "the hold setting may take up to 240 minutes to take effect" whenever enabling litigation hold on a mailbox. Can you verify with Engineering if the 60 minutes period has changed to 240 and update the article?

Thank you,
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31918102-e76c-a57a-dddd-3363e7bee90e
* Version Independent ID: 6bc7b86d-53b5-3426-9f93-db1f0be83cbe
* Content: [Run a per-mailbox litigation hold report](https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/per-mailbox-litigation-hold-report#how-do-you-know-this-worked)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/per-mailbox-litigation-hold-report.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/per-mailbox-litigation-hold-report.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Alex-Catalin** [comment]
Thank you Manuela (@scanum)! According to https://o365exchange.visualstudio.com/IP%20Engineering/_workitems/edit/1515210, it seems to have indeed changed to 240 minutes...
