### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ongpok** [MicrosoftDocs/OfficeDocs-Exchange#2412]
Typo at "
5. There are two options for this step:

Use Enhanced Filtering for Connectors (highly recommended): Use **Enahnced
![Snipaste_2020-12-17_19-33-50](https://user-images.githubusercontent.com/20814939/102482903-e53e2e00-409e-11eb-968b-68ed2e60ba31.png)
** Filtering for Connectors (also known as... "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ongpok Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
