### ISSUE TITLE
Cloud only environment - workaround

### ISSUE THREAD

**Issue by iku899** [MicrosoftDocs/OfficeDocs-Exchange#2413]
>>In cloud-only environments, this workaround will not work. To use dynamic distribution groups that receive email from external senders in cloud-only environments, you need to disable DBEB (change the domain from Authoritative to Internal relay).<<

You can change email address of dynamic group to xxx@company.onmicrosoft.com and then create an ordinary distribution list with desired email address xxx@company.com. Then put DDG as a member to ordinary distribution list.
With this workaround you can stay in authoritative mode.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb394c8-1004-a253-7806-71fdc9406478
* Version Independent ID: 1f4e3200-3025-5def-851e-3d56f815c2ff
* Content: [Use Directory Based Edge Blocking to reject messages sent to invalid recipients](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
