### ISSUE TITLE
Migration is stages

### ISSUE THREAD

**Issue by BobDobal** [MicrosoftDocs/OfficeDocs-Exchange#242]
Is it possible to migrate users in stages?

How would mail routing work if some users in my domain have their email on g suite, and some on office 365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate G Suite mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@BobDobal Thank you for this inquiry

I am not sure how a partial migration would affect your environment. Let me get this over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msdmaguire** [comment]
@BobDobal Staged migrations are not currently possible with G Suite migrations, which means partial mail routing is not supported. We hope to release new functionality in the near future that will allow staged migrations for G Suite users, and that would include the ability for mail routing to be configured to support proper routing by creating sub-domains.

**Comment by BobDobal** [comment]
Thanks David

**Comment by qyubee169** [comment]
Does migrating the mailboxes from Gsuite include google drive?

**Comment by msdmaguire** [comment]
@qyubee169  No, currently we only support migrating mail from G Suite. Soon we will be releasing new functionality to migrate mail, calendar, and contacts to Office 365 from G Suite.

**Comment by qyubee169** [comment]
Thanks a lot.

**Comment by BobDobal** [comment]
> 
> 
> @qyubee169 No, currently we only support migrating mail from G Suite. Soon we will be releasing new functionality to migrate mail, calendar, and contacts to Office 365 from G Suite.

@msdmaguire any idea when the new functionality to migrate calendar and contacts as well will be going live?

**Comment by msdmaguire** [comment]
@BobDobal There is no firm release date but this functionality *should* be available in the first half of 2019.

**Comment by BobDobal** [comment]
Thanks
