### ISSUE TITLE
Staged Migration doesn't set forwarding on G Suite

### ISSUE THREAD

**Issue by cjb2k1** [MicrosoftDocs/OfficeDocs-Exchange#2422]
I've been running a staged migration from G Suite to O365 and have been getting stuck trying to complete the batch. After talking to Support they inform me that the tool doesn't actually set the forwarding address on the G Suite mailbox and this needs to be completed manually.

The documentation clearly states that the tool does automatically set the forwarding address but it appears to not be the case. The documentation needs to be updated to reflect this.

It would be beneficial to advise exactly where to set the forwarding address as there are multiple ways of doing this within G Suite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cjb2k1** [comment]
I did raise a service ticket within my tenancy and this is the outcome that the G Suite migration tool apparently doesn't set the automatic forwarding on the G Suite Mailbox at the end of the migration process.

**Comment by joe429mama** [comment]
Got it.



Sent from my T-Mobile 5G Device



-------- Original message --------
