### ISSUE TITLE
Umar Duzz Duzz

### ISSUE THREAD

**Issue by umarduzzofficial** [MicrosoftDocs/OfficeDocs-Exchange#2424]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e4d207-3c34-02c7-5a9b-3689267c866a
* Version Independent ID: c086dd8e-8fc4-fc3b-de38-ec4b13968d13
* Content: [Enable mail flow for subdomains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
