### ISSUE TITLE
Hybrid Aclable Delegate permissions

### ISSUE THREAD

**Issue by jahube** [MicrosoftDocs/OfficeDocs-Exchange#2426]
Hi,

Related to below article
https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions

in the provided script to set Aclable remoterecipienttype
A) ForEach {Get-AdUser -Identity $_.**Guid** is incorrect

GUID  a CLOUD property not existing onprem
Onprem it is ObjectGUID

B) undocumented option how to use the below
get-remotemailbox | Set-RemoteMailbox -ACLableSyncedObjectEnabled

included some details under
[github.com/jahube/Hybrid-Delegation](https://github.com/jahube/Hybrid-Delegation)

see [Set-ADuser Documentation](https://docs.microsoft.com/en-us/powershell/module/addsadministration/set-aduser)
accepted Identity values
A distinguished name
A GUID (objectGUID)
A security identifier (objectSid)
A SAM account name (sAMAccountName)

Best regards.
Jan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
