### ISSUE TITLE
The picture is not what I see on the website

### ISSUE THREAD

**Issue by panmq122** [MicrosoftDocs/OfficeDocs-Exchange#2428]
Where can I find the tabs shown in the picture? Where is the report tab? where is send again button? This page is totally out-of-date!!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc6de85c-181e-3f88-cc88-216b77c253b0
* Version Independent ID: cc3516fd-4bac-5ee3-f792-8e4437f2a3fe
* Content: [Fix email delivery issues for error code 550 5.1.10 in Exchange Online](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@panmq122 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @panmq122 how are you? Hope you are doing good.
I forced a 550 5.1.10 error on my EXO lab and I was able to successfully see the Report tab and the Send Again button:
 
![image](https://user-images.githubusercontent.com/36666927/104664871-f1191200-5695-11eb-8db2-8a023382abb7.png)

Can you kindly check if you are receiving a 550 5.1.10 error as the article covers?

Thank you!

**Comment by get-itips** [comment]
@panmq122 Hello, returning to check if you could see my last question, thank you!

**Comment by scanum** [comment]
@panmq122 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
