### ISSUE TITLE
Please elaborate on Delivery Date or date of creation verbiage

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#2430]
Hello,

How does this work exactly, does it use delivery date or date of creation?

We are migrating email messages, they will all have the same creation date, and potentially all move to the archive in 90 days, which is a very different experience from if they move to archive using the delivery date.

I'm hoping it uses delivery date, unless it is not set in which case it uses date of creation which would be primarily "drafts". Not sure about sent items. Maybe you could talk about using MFCMapi and the specific properties that are checked.

Thanks!
-jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a659b815-705f-fa0f-9867-db506cc2c474
* Version Independent ID: d85dba9c-c8d1-7d31-2af3-1a26a13c713f
* Content: [How retention age is calculated](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-age)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-age.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-age.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jonwbstr** [comment]
Hello, I opened [Case #:23586510] and with supports help we came to the following conclusions:

The preceding paragraph says,
> The retention age of mailbox items is calculated from the date of delivery or in the case of items like drafts that aren't delivered but created by the user, the date an item was created.

I suggest including that information in the table, which is where I looked and had questions. Also, the current description does not address how sent item retention age is calculated. See below for my suggested edit.

The retention age is calculated based on...
| Type | The retention age is calculated based on... |
| ------------- | ------------- |
| Email Messages | ```message-received date``` or if that is blank such as for draft messages, ```message-creation date``` <br/>Sent items have the same date for both ```message-received date``` and ```message-sent date```. |

**Comment by jonwbstr** [comment]
I'm not sure why you closed this issue before I had a chance to open a ticket and provide an update. If I don't hear from someone in the next day I'll open a new ticket in github since that's how how quickly you expected an update from me, it seems only fair. :)

**Comment by jonwbstr** [comment]
Please help me understand why was this closed, again?
