### ISSUE TITLE
Suggestion: Add clarification for people picker with SendAs.

### ISSUE THREAD

**Issue by Krytical13** [MicrosoftDocs/OfficeDocs-Exchange#2432]
Related to adding SendAs Permissions in a hybrid environment mentioned under the heading:
"Mailbox permissions and capabilities not supported in hybrid environments"

It's very clear that SendAs permissions are 'unsupported' in Hybrid, and that the attributes do not synchronize between on-premise and cloud environments.

It's also clear, that if you want to make use of SendAs permissions, you are able, but you must apply the permissions separately both on-premise and Exchange Online.

What's not so clear is that the people picker in Exchange Admin Center on-premise _cannot_ be used to add SendAs delegates to a mailbox that has already been migrated to Exchange Online, and you can ONLY use PowerShell to accomplish this.

This is confusing as the people picker works correctly for selecting and adding users as Members to the group, it works for selecting users for other delegated permissions like Full Access and Send on Behalf.

And even though "unsupported" when you try to add users for Send As permissions, lots of "Groups" show up, and we are ABLE to add them with Send As permissions.

This is a very inconsistent experience that is not clearly explained.
This lead us to thinking we had permission issues between Exchange and Active Directory so we spent time searching Technet forums and other resources and finally putting in a premier support ticket with MS, in which we were told it's by design.

Clarification might be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/Exchange/permissions)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Krytical13 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Krytical13 How are you? Hope you are doing good.
So I can test this and see if we need to clarify the article, on which version of Exchange did you experience this:

> And even though "unsupported" when you try to add users for Send As permissions, lots of "Groups" show up, and we are ABLE to add them with Send As permissions.

I understand that you were "able" to use the EAC to add send as permission to a mailbox already migrated to EXO, is that right?

Thanks for helping me clarify.

**Comment by Krytical13** [comment]
Hi Andres,
I’m doing well thanks!  I hope you are also doing well!

We are using Exchange Server 2016 CU17.

To clarify, we had no desire to grant a Security Group SendAs permissions.
We had the desire to grant an individual user SendAs permissions.

Since EAC is not supported for adding SendAs for migrated mailboxes, one might expect the option to not be there, or to not function.

However when we do try to add SendAs permissions for migrated mailboxes,
EAC allows us to select any “Security Group” to add, but no individual users or other groups or contacts show up in the picker.

As expected, when we add one of the “Security Groups” to the SendAs permissions, they are not synchronized to Exchange Online.
The confusion is from the unsupported option seeming to function partially but not completely. (security groups, but no users)

Thanks!

**Comment by get-itips** [comment]
Hello @Krytical13 
Thanks for returning and sharing more details about your scenario.
I could not reproduce that in my lab. What I can do is to propose to clarify that the Send As permission **must** be added using PowerShell, and we will see if it gets approval from reviewers.
Thank you
