### ISSUE TITLE
Updated instructions request

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/OfficeDocs-Exchange#2441]
[Enter feedback here]

If it hasn't already, can instructions for the new Exchange admin center be added?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4e18b1-5821-73a0-eef8-5cdafb3b8401
* Version Independent ID: b3534855-b60a-797f-4d65-65b514397ab5
* Content: [Create and manage distribution groups](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Hi @rconiv , we are in the process of updating all of our Exchange Online content to reflect the modern (ie, "new") EAC. So the answer to your question is yes, and most articles should be updated in the next month or two, depending on the release schedule for new EAC features.
