### ISSUE TITLE
Disabling Legacy Authentication in Exchange Server 2019 with a DAG

### ISSUE THREAD

**Issue by skreel** [MicrosoftDocs/OfficeDocs-Exchange#2442]
If you have a DAG and you're using a frontend load balancer or DNS round robin, disabling legacy auth at the organization level will not work and will cause everything to go haywire. Be careful disabling legacy auth at the org level if you have a cluster. The work around can be found [here]([http://kreelbits.blogspot.com/2021/01/disabling-legacy-authentication-in.html])

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a28048b1-794c-024d-0a32-ee09818880c8
* Version Independent ID: b3548be5-0cab-0872-9747-e7c8288ad57d
* Content: [Block legacy authentication in Exchange 2019 hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/block-legacy-auth-2019-hybrid)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/block-legacy-auth-2019-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/block-legacy-auth-2019-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by skreel** [comment]
I already have a support ticket open with the onpremise exchange team. Disabling legacy auth at the org level does not work if you have a cluster and proxy connections between nodes. Your engineering team is working on a fix but as of right now it does not work. You should add that to the documentation.

**Comment by chrisda** [comment]
@skreel, what is the workaround? Your original post looked like it would contain a link off to more information.

**Comment by skreel** [comment]
It did contain a link. You need to create a new authorization policy that
allows legacy auth. Then you need to set the msExchAuthPolicyLink on the
exchange server computer objects in AD to use the newly created policy so
that the proxied connection uses legacy authentication. Clients will then
be able to authenticate properly but the server will continue to get
unhandled duplicate key exceptions. Greg Taylor, the Director of Product
Marketing for Exchange Server, acknowledged this as a fix but does not
recommend doing it. Thus, the feature doesn't work... he recommends
disabling legacy auth on all the users individually until disabling legacy
auth at the org level works in a clustered environment.

**Comment by chrisda** [comment]
@skreel, it did contain a link, but the formatting was slightly off, so the link wasn't hot (I fixed it). Thanks.
