### ISSUE TITLE
Not working and not supported by Microsoft - the document should clearly state that this is an unsupported method.

### ISSUE THREAD

**Issue by jamesfreeman959** [MicrosoftDocs/OfficeDocs-Exchange#2445]
[Enter feedback here]
Fundamentally this didn't work - I set this up exactly as per the documentation but it kept timing out and failing. I approached Microsoft support about this and they wouldn't even entertain this document - they pointed me to another which was basically a glorified IMAP sync and didn't sync Calendar, Contacts, and required the password to be in the clear for every user synced. This is not what I wanted, yet given that this document fundamentally doesn't work and isn't even supported by Microsoft tech support, I would question why it exists in this form. Surely if Microsoft won't support this method of migration (which is far better) then this document should be deleted, or at least a warning placed on it that this is unsupported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#start-a-g-suite-migration-batch-with-the-exchange-admin-center-eac)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
