### ISSUE TITLE
Articles Never Explain what Submit message button does

### ISSUE THREAD

**Issue by techlogik** [MicrosoftDocs/OfficeDocs-Exchange#2446]
There are multiple articles, including this one, which talks about what the new Message trace tool does, options etc. But in the results, you can select an email with the 3 ellipse burger, and Submit Message is an option. What does this do?

Can find this anywhere before I press a button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7684ef8f-2f6d-7c73-fddb-19b94096e82a
* Version Independent ID: 9910c94c-df87-74c1-fa32-e153857a64ab
* Content: [Run a message trace and view the results in the Exchange admin center](https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results)
* Content Source: [Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
