### ISSUE TITLE
What happened to delivery reports?

### ISSUE THREAD

**Issue by glrotate** [MicrosoftDocs/OfficeDocs-Exchange#2449]
It seems almost too strange to be true that users can't view the exchange transmission log for an email.  The Outlook desktop client displays a 404 error when you try to read a report.  Not very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d2c66-f9d8-7ac2-55c8-1ccfbe966bf6
* Version Independent ID: 3dc90f07-c2bb-9f37-82c2-a713f0b8f27c
* Content: [What happened to delivery reports?](https://docs.microsoft.com/en-us/exchange/monitoring/what-happened-to-delivery-reports-in-office-365)
* Content Source: [Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
