### ISSUE TITLE
문구 수정 요청 합니다.-20181101

### ISSUE THREAD

**Issue by AnnTaeYoun** [MicrosoftDocs/OfficeDocs-Exchange#245]
현재 글

DAG를 만드는 실제 사서함 서버 및 가상화 된 사서함 서버를 포함 하는 서버와 솔루션의 Exchange Server 시스템 요구 사항 및 에 명시 된 요구 사항을 준수 지원 됩니다. Exchange 서버 가상화합니다. 모든 Exchange 고가용성 구성에서와 마찬가지로 모든 사서함 서버는 DAG에 예약 된 및 예약 되지 않은 중단 하는 동안 필요한 작업 부하를 처리 하려면 적절 하 게 크기는 확인 해야 합니다.

수정 요청 글

서버와 솔루션이 Exchange Server 시스템 요구 사항 및 Exchange Server 가상화에 명시된 요구 사항을 준수하는 경우 물리적 사서함 서버와 가상화 사서함 서버의 조합을 포함하는 DAG를 만드는 것이 지원됩니다.
모든 Exchange 고 가용성 구성과 마찬가지로 DAG의 모든 사서함 서버가 예정된 중단 및 예정되지 않은 중단 중에 필요한 작업을 처리 할 수 있도록 적절하게 크기를 조정해야합니다.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 63b8b93a-0f82-38c0-9546-a291aafceccc
* Version Independent ID: f5b63275-ecdf-9d2f-077f-bb20729ce9b4
* Content: [데이터베이스 가용성 그룹](https://docs.microsoft.com/ko-kr/Exchange/high-availability/database-availability-groups/database-availability-groups?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/high-availability/database-availability-groups/database-availability-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/database-availability-groups/database-availability-groups.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@AnnTaeYoun Thank you for this suggestion

I will get this suggestion over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by OfficeGSX** [comment]
The suggested translation was implemented and is visible on the live site see the screenshot below. We have also uplifted the topic to HT since the topic was previously MT.

![image](https://user-images.githubusercontent.com/16706698/52122088-0f5ce300-2622-11e9-9409-3f65fe3113d0.png)


Best regards,

Jiri
