### ISSUE TITLE
Cross forest mailbox permissions for Exchange 2010 hybrid

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/OfficeDocs-Exchange#2450]
In this article https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions?redirectedfrom=MSDN we state that Exchange 2010 is no longer supported for configuring mailbox permissions in a hybrid deployment, yet in the article for which I'm giving feedback right now https://docs.microsoft.com/en-us/exchange/permissions, we say this:

Exchange 2010 | Exchange 2010 SP3 servers need the following:The latest update rollup (RU), or the immediately previous RU, installed. Exchange 2010 SP3 servers running older RU aren't supported and may not work with delegated mailbox permissions in a hybrid deployment.On-premises remote mailboxes associated with Microsoft 365 or Office 365 mailboxes need to be configured to support ACLs. This needs to be done for each on-premises remote mailbox that's associate with an Microsoft 365 or Office 365 mailbox.

Please consult with Engineering and correct the article to have matching information in all places. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/permissions)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Alex-Catalin  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Alex-Catalin 
Thanks for reporting this, investigating, I see that another Microsoft submitter, @reikor0x is the author of the recent commit that removed Exchange 2010 as a valid option on the first article you shared, as that PR [was reviewed and approved](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2378), I will propose in a PR the same change on the other article you kindly shared.
Thank you

**Comment by reikor0x** [comment]
Exchange 2010 is not supported anymore. Information for Exchange 2010 remains for mistake. I'll create a PR to remove references to Exchange 2010. Thanks

**Comment by reikor0x** [comment]
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2456 created

**Comment by get-itips** [comment]
> https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/2456 created

Vincenzo thanks for sharing your comments here!, yesterday I created and referenced a PR to close this issue.

**Comment by get-itips** [comment]
@scanum please close

**Comment by scanum** [comment]
@reikor0x  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
