### ISSUE TITLE
Plus Addressing only works with one +

### ISSUE THREAD

**Issue by zayn008** [MicrosoftDocs/OfficeDocs-Exchange#2451]
I have a popular software which uses plus addressing to organise incoming emails. but it will often use multiple pluses such as one+two+three@email.uk, this works with gmail and the incoming email is handled properly however with Office365 I understand plus addressing has just been an added feature but it currently seems to only support one+two@example.uk... it would be nice to update this to allow multiple pluses in one email

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
