### ISSUE TITLE
Clarification is required.

### ISSUE THREAD

**Issue by JoseMonteiroMS** [MicrosoftDocs/OfficeDocs-Exchange#2452]
There is a contradiction in this sentence and more information is missing, can you please clarify?

Investigate | **A small amount of significant data loss was detected, caused by some common inconsistency types. You must approve the migration for it to complete.**
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b40bce01-0b1f-1952-5198-d5a15211b533
* Version Independent ID: 3f0ac568-cfbd-5255-d803-b7883c32c50f
* Content: [Track and Prevent Migration Data Loss](https://docs.microsoft.com/en-us/exchange/mailbox-migration/track-prevent-data-loss-dcs)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/track-prevent-data-loss-dcs.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@JoseMonteiroMS  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @JoseMonteiroMS, thank you for your feedback and help us to improve docs.microsoft.com.

My apologies, but I cannot see the contradiction. Could you kindly provide more detail? Thanks!

**Comment by JoseMonteiroMS** [comment]
@Katarzyna Wojtyczka<mailto:Katarzyna.Wojtyczka@microsoft.com> -  can you please shime in since you brought this one up?

Best Regards,

José Monteiro
FTC EMEA MVM Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically generated]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149229758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7nkKb7lO6Hs3U%2FBiSQVzBamMyN%2BVDEIv0JD1AaIAxEs%3D&reserved=0>[cid:image002.png@01D6F317.F64E91F0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6H5AKiGBE4rpex2loI4kzMgyk%2Bi6FkwCIMvudplNxcI%3D&reserved=0>
[cid:image003.png@01D6F317.F64E91F0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YDJKh3tFKGYc%2BAns7WZgIQQCjsDJmuYgbjqP1mRkWxU%3D&reserved=0>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149249750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yq5C%2F4sXDBFmaiKIt1aEzvAOsrWcxbiSHj%2BAaaczc2A%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149259753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S7%2B1lUDgMYQeJjDEvUNwqmUvE9dQB7xzZpwMHJVyiUo%3D&reserved=0>

**Comment by JoseMonteiroMS** [comment]
Hello Team, All,

The concern relates to what is meant with the below quoted description - the cause and effect relationship is unclear in it:
"A small amount of significant data loss was detected, caused by some common inconsistency types."

I see two points that cause confusion:

  1.  the phrase "small amount of significant data loss" is a contradiction. Either we are looking at small or significant amount of data loss.
  2.  And "common inconsistency types" is vague and doesn't explain what is meant. What caused the data loss? What type of data will be lost?

I tried to paraphrase this, when asked to explain what is meant - and I am still unable to do so. Could you please help out here? Could share what is the message given to our customers? When we read the description for all scores, the explanation of what data is signaled as 'going to be lost' is unclear.

I am including @Sindhuri Suresh Kumar<mailto:sisuresh@microsoft.com>, who is communicating with the PG Team about DCS and the concerns described above. If there is anything you would like to add or raise, please go ahead.

Thank you all in advance for your support.

Best Regards, | Cordialement, | Mit freundlichen Grüßen

Katarzyna Wojtyczka
FTC EMEA MVM
FastTrack Center
Office: +351 (21) 0491 509
Mobile: +351 9279 777 83
Email: kawojtyc@microsoft.com<mailto:kawojtyc@microsoft.com>
[A close up of a wheel  Description automatically generated]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=02%7C01%7Cv-kawojt%40microsoft.com%7C5fe2a7330f9543a58f5e08d7e6c76067%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637231616297698356&sdata=PijrMGQ5Kqjm%2BgUYdDxBUmIyUPx1AjQFesJQIwvaqS4%3D&reserved=0>[cid:image005.png@01D6F48A.84EA2550]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft%2F&data=02%7C01%7Cv-kawojt%40microsoft.com%7C5fe2a7330f9543a58f5e08d7e6c76067%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637231616297708350&sdata=2gbqlmZ0KXW6WMxZbPtFQcAlDXB2aQjBuipqohBwTho%3D&reserved=0>
[cid:image006.png@01D6F48A.84EA2550]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=02%7C01%7Cv-kawojt%40microsoft.com%7C5fe2a7330f9543a58f5e08d7e6c76067%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637231616297718344&sdata=FQnowhPsYy1v%2BvWGCdJX8MLF6bJ2cdmdlXFFkHnvEEQ%3D&reserved=0>
Upcoming leave: None

Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=02%7C01%7CKatarzyna.Wojtyczka%40microsoft.com%7Cc60fa28f147d43b3eec108d84f20bafd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637346349294590831&sdata=Naa5Lsdnj0ct5X71%2BRWetr730yPBsrCePZ0unsz3gmY%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=02%7C01%7CKatarzyna.Wojtyczka%40microsoft.com%7Cc60fa28f147d43b3eec108d84f20bafd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637346349294600823&sdata=V1WX2XBO8OTzTKN78JCxRZCoBbOhoMOw4p2cV8z7bI0%3D&reserved=0>

**Comment by dariomws** [comment]
Thank you @JoseMonteiroMS!

About "small amount of significant data loss":
- I think it's because some items as meetings or emails were lost (significant), but only a small number of items.
- With Poor grade, you lost a greater number of significant items.
- With Good, only metadata or folder permissions (not significant).
Anyway, I think it could be improved. I'll try it.

About "some common inconsistency types":
- I need to get this information, I'll also try with the PG.

**Comment by JoseMonteiroMS** [comment]
Thanks Kat. Will check with PG team and let you know for details.

Regards
Sindhuri S

**Comment by JoseMonteiroMS** [comment]
Adding to the thread the email below.

@Katarzyna Wojtyczka<mailto:Katarzyna.Wojtyczka@microsoft.com> - can you check Dario's inputs?

Best Regards,

José Monteiro
FTC EMEA MVM Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically generated]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149229758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7nkKb7lO6Hs3U%2FBiSQVzBamMyN%2BVDEIv0JD1AaIAxEs%3D&reserved=0>[cid:image011.png@01D6F4AF.6B2FD7C0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6H5AKiGBE4rpex2loI4kzMgyk%2Bi6FkwCIMvudplNxcI%3D&reserved=0>
[cid:image012.png@01D6F4AF.6B2FD7C0]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YDJKh3tFKGYc%2BAns7WZgIQQCjsDJmuYgbjqP1mRkWxU%3D&reserved=0>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149249750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yq5C%2F4sXDBFmaiKIt1aEzvAOsrWcxbiSHj%2BAaaczc2A%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149259753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S7%2B1lUDgMYQeJjDEvUNwqmUvE9dQB7xzZpwMHJVyiUo%3D&reserved=0>

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by JoseMonteiroMS** [comment]
Hello All,

Thank you so much for sharing your thoughts. Here are my 5 cents:


About "small amount of significant data loss":

  *   I think it's because some items as meetings or emails were lost (significant), but only a small number of items.
  *   With Poor grade, you lost a greater number of significant items.
  *   With Good, only metadata or folder permissions (not significant).
Anyway, I think it could be improved. I'll try it.
Kat: with your interpretation (very logical one!), would we be looking at small loss of insignificant value data? I must admit, that knowledge about the type of data could direct us to a simple sounding message.

About "some common inconsistency types":

  *   I need to get this information, I'll also try with the PG.
Kat: thank you again for your effort Dario and Team. Have you had any feedback from PG? As I mentioned above, this could be the key to this query.

Best regards,
Kat
Upcoming leave: None

**Comment by dariomws** [comment]
Hi @JoseMonteiroMS,

> Kat: with your interpretation (very logical one!), would we be looking at small loss of insignificant value data? I must admit, that knowledge about the type of data could direct us to a simple sounding message.
Sorry but I think I don't understand this.

> Kat: thank you again for your effort Dario and Team. Have you had any feedback from PG? As I mentioned above, this could be the key to this query.
No feedback yet from the PG, sorry. I agree that more information about the typo of inconsistencies can really help here.

**Comment by JoseMonteiroMS** [comment]
Looping in @Katarzyna Wojtyczka<mailto:Katarzyna.Wojtyczka@microsoft.com> for following this topic


Best Regards,

José Monteiro
FTC EMEA MVM Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically generated]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149229758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7nkKb7lO6Hs3U%2FBiSQVzBamMyN%2BVDEIv0JD1AaIAxEs%3D&reserved=0>[cid:image005.png@01D6FBA4.840CD490]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6H5AKiGBE4rpex2loI4kzMgyk%2Bi6FkwCIMvudplNxcI%3D&reserved=0>
[cid:image006.png@01D6FBA4.840CD490]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YDJKh3tFKGYc%2BAns7WZgIQQCjsDJmuYgbjqP1mRkWxU%3D&reserved=0>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149249750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yq5C%2F4sXDBFmaiKIt1aEzvAOsrWcxbiSHj%2BAaaczc2A%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149259753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S7%2B1lUDgMYQeJjDEvUNwqmUvE9dQB7xzZpwMHJVyiUo%3D&reserved=0>

**Comment by JoseMonteiroMS** [comment]
Thank you @Jose Monteiro<mailto:Jose.Monteiro@microsoft.com>. Let me try to clarify my earlier comment:

Kat: with your interpretation (very logical one!), would we be looking at small loss of insignificant value data? I must admit, that knowledge about the type of data could direct us to a simple sounding message.
Dario: Sorry but I think I don't understand this.
Kat: I was thinking about how we could improve the phrase "small amount of significant data loss". To be able to improve it we have to know what the author is trying to communicate with it.

Let's not loose traction here and make sure we manage to get the explanation from PG, so that our customers have access to accurate pieces of information. Let's discuss the PG feedback as soon as it comes. Do you have an ETA?
Thanks.

Best regards,
Kat
Upcoming leave: None

From: Jose Monteiro <Jose.Monteiro@microsoft.com>
Sent: Friday, February 5, 2021 9:55 AM
To: MicrosoftDocs/OfficeDocs-Exchange <reply@reply.github.com>; MicrosoftDocs/OfficeDocs-Exchange <OfficeDocs-Exchange@noreply.github.com>; Katarzyna Wojtyczka <Katarzyna.Wojtyczka@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-Exchange] Clarification is required. (#2452)

Looping in @Katarzyna Wojtyczka<mailto:Katarzyna.Wojtyczka@microsoft.com> for following this topic


Best Regards,

José Monteiro
FTC EMEA MVM Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically generated]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CKatarzyna.Wojtyczka%40microsoft.com%7C1d8f20f49b2440af3eba08d8c9bc366f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481157492041667%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cRuTrk%2BUPIgMqaYFv2cvUdpBIA3OkCLcJN4ucLOQ8e0%3D&reserved=0>[cid:image004.png@01D6FBDA.130B2C70]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft%2F&data=04%7C01%7CKatarzyna.Wojtyczka%40microsoft.com%7C1d8f20f49b2440af3eba08d8c9bc366f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481157492051653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i%2FpTDp7B83mwHCcmMV3p2oN2IExoERgA6soxshO5uIY%3D&reserved=0>
[cid:image006.png@01D6FBDA.130B2C70]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CKatarzyna.Wojtyczka%40microsoft.com%7C1d8f20f49b2440af3eba08d8c9bc366f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481157492051653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=78qtQDaRNlvPdayCNqCxyyl93rJnJXSB3QZYZF42Jto%3D&reserved=0>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=04%7C01%7CKatarzyna.Wojtyczka%40microsoft.com%7C1d8f20f49b2440af3eba08d8c9bc366f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481157492061657%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n6F50H0mfC5kfV0E9AwDPQ3WX1k9zbpX3NbBUjOgff0%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=04%7C01%7CKatarzyna.Wojtyczka%40microsoft.com%7C1d8f20f49b2440af3eba08d8c9bc366f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637481157492061657%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uVPuKjurJSov%2BJuD5foU4U6tmZ7pNRj%2BDJiQaeZmzNY%3D&reserved=0>

**Comment by chrios** [comment]
I agree with the sentiment from Jose here. This documentation is not very exact. Also, it's lacking further information about the types of failed items, the Kinds, and the Failure messages. A table explaining the ScoringClassifications would be useful.

**Comment by dariomws** [comment]
@chrios thank you for your feedback.

@JoseMonteiroMS could you get any explanation from the PG? No luck here yet. Thank you!

**Comment by dariomws** [comment]
@Benny-54 maybe you can kindly help to provide more information. Thank you!

**Comment by Benny-54** [comment]
@dariomws let me check with the product owner for more details, thank you.

**Comment by dariomws** [comment]
@Benny-54 Do you have any update there? Thanks!

**Comment by Benny-54** [comment]
@dariomws the concerned team said they'll update it at the earliest. For more information, please check with Sruthi Sreeram <ssreeram@microsoft.com>. Thank you.

**Comment by dariomws** [comment]
Thank you @Benny-54!

**Comment by dariomws** [comment]
@Benny-54 @JoseMonteiroMS Do you think we should keep the issue open? Thanks!

**Comment by dariomws** [comment]
@Benny-54 @JoseMonteiroMS Do you think we should keep the issue open? Thanks!

**Comment by JoseMonteiroMS** [comment]
Sorry Dario,

Not sure to what you are referring, can you please help me to understand?

Best Regards,

José Monteiro
FTC Migrations Lead
FastTrack Center
+351 934 010 038
+351 210 602 167
[A close up of a wheel  Description automatically ***@***.***D7789D.A69CC710]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fmicrosoft%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6H5AKiGBE4rpex2loI4kzMgyk%2Bi6FkwCIMvudplNxcI%3D&reserved=0>
***@***.***D7789D.A69CC710]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2FPt-PT%2F&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149239755%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YDJKh3tFKGYc%2BAns7WZgIQQCjsDJmuYgbjqP1mRkWxU%3D&reserved=0>
Modern Work Support
Microsoft Edge
The browser for business | Standardize on one browser with Microsoft security and innovation
Get assistance from FastTrack<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Ffasttrack&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149249750%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yq5C%2F4sXDBFmaiKIt1aEzvAOsrWcxbiSHj%2BAaaczc2A%3D&reserved=0> | Learn about Edge<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fedge&data=04%7C01%7CJose.Monteiro%40microsoft.com%7C6ab5be2df00f458ba81d08d88bd9447f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637413114149259753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S7%2B1lUDgMYQeJjDEvUNwqmUvE9dQB7xzZpwMHJVyiUo%3D&reserved=0>

**Comment by dariomws** [comment]
I think we can close this issue as some updates were applied to the document after this issue was opened.

"A small amount of significant data loss was detected" was replaced by "A small amount of noticeable data loss was detected".

A new column was added to the table: Approval Required?.

Do you think it's enough and we can close this issue?

**Comment by chrios** [comment]
I don't agree Dario. 

There is still no information available for the Kinds. For instance, MissingItemInTarget or MissingFolderInTarget. I had to contact premier support to get the information about those types of skipped items. Unless this information is available elsewhere, the only other spot is a comment on a technet article about IMAP migrations.

**Comment by Benny-54** [comment]
@dariomws please contact ssreeram@microsoft.com for this issue, thank you.
