### ISSUE TITLE
Audit log to show access by which devices or browser

### ISSUE THREAD

**Issue by Terry188** [MicrosoftDocs/OfficeDocs-Exchange#2455]
Hi,

Is there any audit report which can show the access browser ID or device ID?
Currently, I would like to have report to show my online exchange account is access by which IP, region, and the browser (with ID) or the hardware device (with ID). So, even the password and 2FA is compromised. I still have an audit log to detect the email is accessed by other parties.

Cheers
Terry188

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
