### ISSUE TITLE
Mail Enabled Public Folders

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#2457]
Is this still accurate: "Azure AD Connect sync doesn't synchronize mail-enabled public folders to Exchange Online"

With the GA release in 2019, does Azure AD Connect handle syncing all public folder data so we don't need these scripts or is the AD Connect function only for directory based edge blocking?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by OSuperfly** [comment]
hi danmyhre,

I'm in the same boat... but actually the scripts won't work (the don't find the cmdlets i.e. Remove-EXOSyncMailPublicFolder.

In my understanding you still need the scripts.
If you click the questionmark in AADConnect under "Optional Features" you can read that the object itself aren't created.

I've got a screenshot of the AADConnec dialog there, but it's in german ;-)

![image](https://user-images.githubusercontent.com/80822304/111510337-f7874100-874d-11eb-9b92-f4223bf29102.png)
