### ISSUE TITLE
Get-EXOMailPublicFolder is not recognized - Exchange 2013 CU23

### ISSUE THREAD

**Issue by dougr73** [MicrosoftDocs/OfficeDocs-Exchange#2458]
Public Folders are not visible to mailboxes migrated to 365, so I am following Configure Exchange Server public folders for a hybrid deployment | Microsoft Docs

 

The issue is the script gives the following error:

[1/26/2021 1:24:39 PM] Creating an Exchange Online remote session...
[1/26/2021 1:24:44 PM] Exchange Online remote session created successfully.
[1/26/2021 1:24:44 PM] Enumerating local mail enabled public folders...
[1/26/2021 1:24:48 PM] Mail public folders enumeration completed: 312 local folder(s) found.
[1/26/2021 1:24:48 PM] Enumerating Exchange Online mail enabled public folders...
Get-EXOMailPublicFolder : The term 'Get-EXOMailPublicFolder' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Users\drathbone\Desktop\O365\PF\Sync-ModernMailPublicFolders.ps1:550 char:24
+ $remoteFolders = @(Get-EXOMailPublicFolder -ResultSize:Unlimited | Sort OnPr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (Get-EXOMailPublicFolder:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

 

 

I've searched for "Get-EXOMailPublicFolder" on the Internet, with no mention of this PS command.  What am I missing?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by dougr73** [comment]
My reported issue was due to the account used to connect to Exchange Online did not have Global Admin role activated before running the script (we use PIM with eligible assignments).
