### ISSUE TITLE
SRV cleanup post cutover

### ISSUE THREAD

**Issue by screamtracker** [MicrosoftDocs/OfficeDocs-Exchange#2460]
For post cleanup tasks there is no mention of removing Autodiscover SRV records in on-prem DNS, but this is the guidance no? All I can find right now is this old chestnut but Ive seen it referenced in a 2013 hybrid article as well: https://docs.microsoft.com/en-us/previous-versions/technet-magazine/dn249970(v=msdn.10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365#complete-post-migration-tasks)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
