### ISSUE TITLE
Got 24-hour limit on messages 

### ISSUE THREAD

**Issue by tedcloak** [MicrosoftDocs/OfficeDocs-Exchange#2465]
I sent to nowhere near 10,000 recipients. Maybe three or four thousand.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a66c853-d567-ac8c-2bbc-f1cfa2dd4f10
* Version Independent ID: 949cea29-a3bb-9682-8f9a-8ac395dff759
* Content: [Fix 'sender's submission quota exceeded' errors in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-for-submission-quota-exceeded-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-for-submission-quota-exceeded-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-for-submission-quota-exceeded-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tedcloak** [comment]
Hello, Manuela,
I followed your instructions. The page that came up had a box:
 Important
You must be an admin for a business subscription to use these support methods. If you're not a business admin, please use this support page<https://support.microsoft.com/help/contactus>.
Not being a business admin, I clicked on the link. Result: “Page Not Found”.
Please continue to help me.
Ted
