### ISSUE TITLE
GCC?

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/OfficeDocs-Exchange#2467]
This article states that Sensitivity labeling for Android/iOS is not supported for GCC clouds. Is this still true for GCC Moderate? I believe we either have announced a date, or have recently released this. Can we add clarity here to identify which cloud supports what level of sensitivity labeling?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2a05a7-4cff-8198-b6f8-1f068b3b1d51
* Version Independent ID: 549cd4fb-c9b9-d590-d85f-f6a0b5ee864e
* Content: [Sensitivity labeling and protection in Outlook for iOS and Android](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/sensitive-labeling-and-protection-outlook-for-ios-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/sensitive-labeling-and-protection-outlook-for-ios-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/sensitive-labeling-and-protection-outlook-for-ios-android.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@dotnick365 thank you for your feedback. As it happens, the note you cite is being removed from the article, because you are correct about GCC Moderate. The updated article should publish in the near future.
