### ISSUE TITLE
Missing information: Mail-enabled public folders

### ISSUE THREAD

**Issue by gable44** [MicrosoftDocs/OfficeDocs-Exchange#2468]
How to assign retention policy to mail enabled public folders?

The command should be something:
Set-MailPublicFolder -Identity "Finance Public Folder" -RetentionPolicy "RetentionPolicy-PublicFolder-Finance"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d901572a-dd54-8968-4c9c-4e524dda485d
* Version Independent ID: 9f03490e-5aae-ec98-19b6-8caca2b83a4e
* Content: [Apply a retention policy to mailboxes](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/apply-retention-policy)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/apply-retention-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/apply-retention-policy.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@gable44 Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
