### ISSUE TITLE
How are partner IP addresses identified when creating a connector?

### ISSUE THREAD

**Issue by davidhiston** [MicrosoftDocs/OfficeDocs-Exchange#2470]
Hi, 

I am having an issue when I create a connector as it identifies my IP addresses as belonging to a partner and I am wondering how O365 makes this determination? 
Thanks,
Dave

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
