### ISSUE TITLE
Redundant SPAM Filtering/Impact on SRS

### ISSUE THREAD

**Issue by AaqibIqbal** [MicrosoftDocs/OfficeDocs-Exchange#2471]
Will the email that reaches O365 from 3rd Party SPAM filtering service be subject to further anti-spam filtering by EOP/ATP?
To implement SRS, SPF needs to pass, does this help the case?
What happens when the outbound email is also routed through a 3rd part filtering service? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bd501e4-be27-1da8-e250-7cc1ac22c8ec
* Version Independent ID: ada2e5a7-646f-3576-5834-4727151b7743
* Content: [Enhanced filtering for connectors](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/enhanced-filtering-for-connectors.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
