### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by muchirajunior** [MicrosoftDocs/OfficeDocs-Exchange#2472]
[Enter feedback here]
is there a youtube tutorial for this hard for me to read

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc6de85c-181e-3f88-cc88-216b77c253b0
* Version Independent ID: cc3516fd-4bac-5ee3-f792-8e4437f2a3fe
* Content: [Fix email delivery issues for error code 550 5.1.10 in Exchange Online](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-10-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by muchirajunior** [comment]
okey fine thanks
