### ISSUE TITLE
plus address support for Groups and DL

### ISSUE THREAD

**Issue by lart2150** [MicrosoftDocs/OfficeDocs-Exchange#2475]
This page states support for + aliases for DL and groups will be available by the end of December 2020 that should either be updated to state it is available or the updated expected release date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2481-2a27-06f3-976c-90614a863d81
* Version Independent ID: a3c4f846-0578-54ed-f2a8-c511be3605af
* Content: [Plus Addressing in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by scanum** [comment]
@lart2150 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @SeanMSFT Sean, how are you? Hope you are doing good. Can you kindly confirm if support for Groups and DLs has already been rolled out? I appreciate it.

**Comment by get-itips** [comment]
Hello @Benny-54 Benny, how are you? Hope you are doing good, can you kindly help me confirm this? Thank you!

**Comment by Benny-54** [comment]
Hi @get-itips, I'll check with the SME and then fix this. Thank you, have a great day

**Comment by Benny-54** [comment]
Hi @get-itips, got it confirmed from the concerned team. This was released in December 2020. The updated note will be live at the earliest. Thank you.

**Comment by dariomws** [comment]
The following note:

>[!NOTE]
> Currently, plus addresses are only supported for mailboxes but support for Groups and DLs is being rolled out and will be available by the end of December 2020. 

Was updated to:

>[!NOTE]
> Plus addresses are only supported for mailboxes and Groups. 

8 days ago.

@scanum this issue can be closed.

**Comment by get-itips** [comment]
@scanum please close this one. Thanks
