### ISSUE TITLE
Missing instructions for enabling cloud archive for migrated mailbox (remote user mailbox).

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/OfficeDocs-Exchange#2476]
It seems that the article is missing the details on how to correctly provision cloud archive for a migrated mailbox (remote mailbox in on premise).

We describe the steps on how to create a cloud archive for a new on premise user mailbox and how to create a cloud archive for an existing on premise user mailbox. We should also include the steps on how to create a cloud archive for a migrated mailbox (user is seen as a Remote Mailbox in on premises).

Management continues to be done from the on premise Exchange server even after the user was migrated, so enabling a cloud archive for the migrated user, should be performed from the on premise Exchange server and not from Exchange Online.

Example: Enable-RemoteMailbox -Identity migrated@contoso.com -Archive

More details about the cmdlet here: https://docs.microsoft.com/en-us/powershell/module/exchange/enable-remotemailbox?view=exchange-ps.

PS: This should work from the on premise Exchange Admin Center as well, not only from Exchange Management Shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dfb49c-fbb1-4e58-a94b-060f31744d6e
* Version Independent ID: 2b2de3cb-3087-c82a-f6ad-f58990a85ae0
* Content: [Create a cloud-based archive for an on-premises primary mailbox in an Exchange hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/create-cloud-based-archive)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by dariomws** [comment]
Hi @Alex-Catalin, thank you for your feedback.

The article title is "Create a cloud-based archive for an **on-premises** primary mailbox in an Exchange hybrid deployment" so I think the possible scenarios are covered.

I'll check if there is another article with this information.

**Comment by Alex-Catalin** [comment]
Hi Dario,

We don’t have an article covering that specific scenario as far as I know 😊.

Thank you,

Alexandru Cazacu
Sr. Support Escalation Engineer
Exchange Online
M365 EMEA Customer Service & Support
alexandru.cazacu@microsoft.com<mailto:alexandru.cazacu@microsoft.com>
9 AM - 6 PM (GMT+2)
[cid:image001.png@01D70913.39D09AC0]

**Comment by dariomws** [comment]
@Alex-Catalin I agree.

I'm trying to get the ok to go, we have two options:
- Create new article
- Update this one including the title

**Comment by dariomws** [comment]
Hi @msdmaguire,

Could you kindly help here? Could we edit this article including the title to add instructions for enabling cloud archive for a EXO mailbox in a hybrid environment? Thanks!

**Comment by msdmaguire** [comment]
If @Alex-Catalin can help our vendor writers with the technical details, then yes we can.
