### ISSUE TITLE
Everything on this page is out of date

### ISSUE THREAD

**Issue by JmSMI** [MicrosoftDocs/OfficeDocs-Exchange#2477]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a137ee50-f3b9-07e1-7214-58d282896a66
* Version Independent ID: 70fc82e3-88f8-bc68-a094-37b81c778038
* Content: [Remove an In-Place Hold](https://docs.microsoft.com/en-us/exchange/security-and-compliance/create-or-remove-in-place-holds)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by nam31** [comment]
@msdmaguire, can you help with this?
Thank you
