### ISSUE TITLE
Its not clear when to add the licenses

### ISSUE THREAD

**Issue by dcuasquer** [MicrosoftDocs/OfficeDocs-Exchange#2478]
Hi, the documentation its not clear about the moment the ExO license needs to be applied and also, not clear about what happens with large mailboxes bigger than 100Gb...  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by dariomws** [comment]
Hi @dcuasquer, thank you for your feedback.

I'm adding the information about the moment when you need to assign the license. If you have mailboxes with more than 100 GB you won't be able to migrate them. You have some options. Some of them are:
- Clean the mailbox before the migration
- User the -ExcludeFolder parameter to migrate only some folders
