### ISSUE TITLE
Full Report

### ISSUE THREAD

**Issue by TeriHarrison** [MicrosoftDocs/OfficeDocs-Exchange#2479]
It is not generating a report that can be shared or referenced.

**Comment by nam31** [comment]
@TeriHarrison, can you please share the link to the document that you're having trouble with?

**Comment by nam31** [comment]
@TeriHarrison We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.
Please feel free to re-open this issue if there is a specific content change you can suggest to improve the docs. Thank you.
