### ISSUE TITLE
How much of my mailbox data is synchronized with Outlook for iOS ...

### ISSUE THREAD

**Issue by mailgut** [MicrosoftDocs/OfficeDocs-Exchange#2480]
[Enter feedback here]

You are saying:
---
Q: How much of my mailbox data is synchronized with Outlook for iOS and Android?For initial folder synchronization, Outlook for iOS and Android synchronizes 500 items per folder, with up to 1000 items per folder if the user taps Load more conversations. The app periodically trims the items per folder down to the default number, in order to ensure optimal app performance.
---
At least with IOS and onPrem Mailbox this is not true: An Folder with about 20 old Objects OLK for PC is empty in the OLK app (my settings: no inbox with relevanz, no sorting for thread).

The oldest Object in my inbox on ios is about 2 month old. there seem to be rather an timelimit than an itemcountlimit. 

With O365 Mailboxes the Objects in IOS can be older.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook for iOS and Android in Exchange Online: FAQ](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by get-itips** [comment]
Hello @mailgut 
How are you? hope you are doing great.
Please take into account that this article applies **only** to EXO. Said that, I could confirm with the team that the 500 items initial sync is still valid.
Hope this information helps you.
