### ISSUE TITLE
New-RoleGroup command not working from Azure Automation session

### ISSUE THREAD

**Issue by jopgommans** [MicrosoftDocs/OfficeDocs-Exchange#2481]
Trying to run the New-RoleGroup command with just the "Name" and "CustomRecipientWriteScope" parameters does not work from Azure Automation. If I recreate the exact command in a regular Powershell session it works fine. Tried it with both ExchangeOnlineManagement module versions 2.0.3 and 2.0.4 .
Someone already reported this issue here (https://answers.microsoft.com/en-us/msoffice/forum/all/unable-to-create-a-new-role-group/6b542c45-1b2f-4c05-92c4-5f0deba54019) but it was closed immediately, no idea why?

The error I get is:
"The group "EURPR03A007.PROD.OUTLOOK.COM/Microsoft Exchange Hosted Organizations/corphost.onmicrosoft.com/RG-MEE-RecipientAdmin" can't be managed by recipient "SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}". The owner of the group should have the following recipient type details: UserMailbox,LegacyMailbox,SharedMailbox,TeamMailbox,MailUser,LinkedMailbox,User,UniversalSecurityGroup,RoleGrou p,MailUniversalSecurityGroup,LinkedUser + CategoryInfo : NotSpecified: (EURPR03A007.PRO...-RecipientAdmin:ADObjectId) [New-RoleGroup], RecipientTaskException + FullyQualifiedErrorId : [Server=AM0PR03MB4676,RequestId=d434bb07-a610-48a0-98d0-86b1b1bafb70,TimeStamp=2/15/2021 10:39:20 AM] [FailureCategory=Cmdlet-RecipientTaskException] 513C7369,Microsoft.Exchange.Management.RbacTasks.NewRoleGroup + PSComputerName : outlook.office365.com"

Upon using command: New-RoleGroup -Name RG-MEE-RecipientAdmin -CustomRecipientWriteScope MEE-Recipients -Roles "User Options", "Message Tracking", "Mail Recipients", "Distribution Groups"

**Comment by nam31** [comment]
@jopgommans Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
