### ISSUE TITLE
Generating an Alert for Sharing policy set in Exchange Online

### ISSUE THREAD

**Issue by Shwet88** [MicrosoftDocs/OfficeDocs-Exchange#2482]
It would be also good to know if there is a way to get alerts or notifications in O365 Security & Compliance/ MCAS portals for activities where user has shared their calendars with other users.  Basically  is there a way  to integrate the Sharing Policy created in Exchange Online with policies present in Office 365 Security & Compliance to see an alert there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff83223-f09a-7e1a-8c44-d0f8dee5df54
* Version Independent ID: bdbb368f-1254-75ce-26b3-e3e17779142b
* Content: [Sharing policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/sharing-policies/sharing-policies)
* Content Source: [Exchange/ExchangeOnline/sharing/sharing-policies/sharing-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/sharing-policies/sharing-policies.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by get-itips** [comment]
Hello @Shwet88 how are you? Hope you are doing good.
As far as I know and I could dig in, there isn't currently a way to do that, the best option for your request to reach the team would be to create a uservoice entry [here](https://office365.uservoice.com/).
Hope you find this information helpful,
Andrés
