### ISSUE TITLE
Both sides require relationship

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#2483]
Based on my testing, both sides (both EXO tenants) must setup a relationship before free-busy will start working. Having the org sharing setup on one side only does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c02125f4-2bb2-0631-93e2-93ccce4f1cb5
* Version Independent ID: 03192cfe-7d7e-82ec-d048-b4ac7d08d9df
* Content: [Organization relationships in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/organization-relationships)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by michelderooij** [comment]
Isn't that obvious from "When you set up the organization relationship, you are setting up your side of the relationship and specifying the level of information that the users in the external organization can view."

**Comment by danmyhre** [comment]
Uh, no - setting up 1 side of the relationship does nothing. In order for either side to work, both must be setup. Just setting up your side doesn't allow the other organization to see anything, which is why that statement isn't obvious or correct.

**Comment by michelderooij** [comment]
The example makes it quite clear imho: "For example, if Contoso creates an **organization relationship** with Tailspin Toys .. However, before Contoso can also see availability for users at Tailspin Toys, their administrator needs to set up an **organization relationship** with Contoso."

**Comment by danmyhre** [comment]
That example is saying it will work with only 1 side of it being present. The first two sentences:

"For example, if Contoso creates an organization relationship with Tailspin Toys, the users at Tailspin Toys will be able to schedule meetings with the users at Contoso by adding their email address to the meeting invitation. **The availability of the invited Contoso user would display to the Tailspin Toys user.**"

That is a false statement.

**Comment by get-itips** [comment]
Hello @danmyhre Dan, how are you? Hope you are doing good.
From my understanding, the text in the article expresses clearly that you need both sides to perform the relationship, also based on the quotes that @michelderooij Michel kindly includes here.
Thank you for your feedback!

**Comment by danmyhre** [comment]
Okay, I tried. You can close it then.

**Comment by nam31** [comment]
@danmyhre The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
