### ISSUE TITLE
Outlook Mobile (iOS) URL Scheme to open specific message ID

### ISSUE THREAD

**Issue by mozziemozz** [MicrosoftDocs/OfficeDocs-Exchange#2484]
Hello, I would like to be able to create links, which open a specific Email in Outlook for iOS directly. It's basically the very same a Push Notification does on iOS. It shows me that there is a new email and if i click on the notification, it opens this specific new email (the one i was notified for) in outlook for iOS. I know that the URL scheme for Outlook mobile is ms-outlook:// but I can't figure out the rest of the syntax. It has to be possible because To Do is doing exactly what I want to achieve. If you flag an Email, a Task in To Do will be created under flagged email. If I open that, it shows me a button "Open in Outlook" and once I click on it, the associated email opens in Outlook Mobile on iOS. I want to be able to do the same, so I can have Power Automate send me Push Notifications containing a link to new Emails in subfolders. (There's no notification for new emails which are not delivered directly into the inbox.) I would greatly appreciate it if you could track down the correct deep link url scheme to open specifc outlook Items on iOS. Thanks in Advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook for iOS and Android in Exchange Online: FAQ](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mozziemozz Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
