### ISSUE TITLE
Prefix vs Suffix

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-Exchange#2487]
When detailing the use of wildcards at the end of the article, it looks to me like you've confused the prefix vs suffix notation? As in, prefix is something in the beginning of a string, not the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7393c45-1119-f0ea-67dc-36ecf42d2e08
* Version Independent ID: 29417cc2-6a03-bea3-f195-51ca55f9dc1a
* Content: [Message properties and search operators for In-Place eDiscovery](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@michevnew Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
