### ISSUE TITLE
Missing next steps

### ISSUE THREAD

**Issue by hsbsandrecv** [MicrosoftDocs/OfficeDocs-Exchange#2489]
This doc is missing the what next!, and at least some info on how to migrate from Lotus Notes. Although this MONTI info is good, is not enough to plan a migration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce990e27-aa35-1c80-2d57-c07df2d35e88
* Version Independent ID: 78594f8e-6f98-21bd-4c68-be4facfade3e
* Content: [Migrate from Lotus Notes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-from-lotus-notes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@hsbsandrecv  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.
