### ISSUE TITLE
Update article endpoints for sovereign clouds, this request specific to GCCHigh/DoD

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/OfficeDocs-Exchange#2490]
Hi Team - came across a customer trying to implement this guidance today - they were stymied a bit as the direction provided for DNS record creation doesn't apply to their M365 environment in the GCCH space as the target hosts are different.  Could this article be updated to contain alternate endpoints for GCCH/DoD, and perhaps expanding that to other sovereign clouds (germany, etc)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459e11a9-aa70-1757-15d6-45e3292aad09
* Version Independent ID: 13a6d8d0-1a41-1c75-6042-f96d1855facf
* Content: [Configure Microsoft 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-microsoft-365-groups#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@drdenson  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @drdenson, thank you for your feedback.

Could you confirm that Microsoft 365 Groups with on-premises Exchange hybrid or groups writeback is supported on these instances?
I found this article:
https://docs.microsoft.com/azure/active-directory/hybrid/reference-connect-instances
It says that other Azure AD Premium services feature than Password Writeback are not available in the Microsoft Cloud Germany. Maybe this feature is not available there.

**Comment by kosaimgmg2021** [comment]
> Hi Team - came across a customer trying to implement this guidance today - they were stymied a bit as the direction provided for DNS record creation doesn't apply to their M365 environment in the GCCH space as the target hosts are different. Could this article be updated to contain alternate endpoints for GCCH/DoD, and perhaps expanding that to other sovereign clouds (germany, etc)?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 459e11a9-aa70-1757-15d6-45e3292aad09
> * Version Independent ID: 13a6d8d0-1a41-1c75-6042-f96d1855facf
> * Content: [Configure Microsoft 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-microsoft-365-groups#feedback)
> * Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md)
> * Product: **exchange-server-it-pro**
> * Technology: ****
> * GitHub Login: @msdmaguire
> * Microsoft Alias: **dmaguire**

**Comment by dariomws** [comment]
@kosaimgmg2021 I think you missed something. Do you want to add more information here?

**Comment by dariomws** [comment]
Hi @drdenson, thank you for your feedback.

Could you confirm that Microsoft 365 Groups with on-premises Exchange hybrid or groups writeback is supported on these instances?
I found this article:
https://docs.microsoft.com/azure/active-directory/hybrid/reference-connect-instances
It says that other Azure AD Premium services feature than Password Writeback are not available in the Microsoft Cloud Germany. Maybe this feature is not available there.

**Comment by dariomws** [comment]
@kosaimgmg2021 I think you missed something. Do you want to add more information here?

Hi @drdenson, thank you for your feedback.

Could you confirm that Microsoft 365 Groups with on-premises Exchange hybrid or groups writeback is supported on these instances?
I found this article:
https://docs.microsoft.com/azure/active-directory/hybrid/reference-connect-instances
It says that other Azure AD Premium services feature than Password Writeback are not available in the Microsoft Cloud Germany. Maybe this feature is not available there.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
