### ISSUE TITLE
Legacy G Suite and miscellaneous fixes

### ISSUE THREAD

**Issue by ralish** [MicrosoftDocs/OfficeDocs-Exchange#2491]
A couple of suggestions:

1. It should be noted that the instructions will not work for the legacy free edition of G Suite. The reason why is accounts still on the free edition are unable to add additional domains, only domain aliases, and so are unable to setup the required mail routing.
2. The link for "Office 365 now supports larger email messages" is broken. The correct link appears to be: https://www.microsoft.com/en-us/microsoft-365/blog/2015/04/15/office-365-now-supports-larger-email-messages-up-to-150-mb/

Regarding 1), it'd be great if the native Google Workspace migration support were enhanced to support migrating without the more complex mail routing configuration enabling both mail systems to function concurrently during the migration. Instead, the customer would simply ensure all Google Workspace mailboxes exist on Exchange Online, update MX and related DNS records, then initiate the migration.

This would still provide the benefit of calendar and contact synchronisation afforded by using Google's APIs, while only resulting in users being migrated temporarily missing historical mail while being synced. For smaller migrations, that may not be a significant issue, particularly if the migration is being done over a weekend.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ralish  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @ralish Samuel, thanks for your feedback, an improvement to the article is on the way.
About your feedback about the migration itself, I would suggest sharing your idea [here](https://office365.uservoice.com/) that way it can reach the team.
Thank you!
