### ISSUE TITLE
Delay reason overview will be help ful

### ISSUE THREAD

**Issue by prontohostau** [MicrosoftDocs/OfficeDocs-Exchange#2493]
We are using SMTP email relay server and email stuck in send server queue, some times get delayed to reach Office 365 server.
Could you add some details, if this is normal things to consider. If you can include the analysis, how to know that delay is coming from sending side or it might be remote server delay? Could you kindly add an help section/FAQ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b5e01ad-4656-ca35-3b3d-41efdae39cd9
* Version Independent ID: 54b8031d-44b9-296e-f006-47e8cc835d1e
* Content: [Fix issues with printers, scanners, and LOB applications that send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off?source=docs)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/fix-issues-with-printers-scanners-and-lob-applications-that-send-email-using-off.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
