### ISSUE TITLE
Express migration is no longer available

### ISSUE THREAD

**Issue by MihaiGrigoruta** [MicrosoftDocs/OfficeDocs-Exchange#2494]
Hello,

My name is Mihai and I am support escalation engineer for BC Exchange Online. At the moment I have confirmed with Mukesh Kumar, who is PM for Hybrid Wizard, that Express migration has been removed for almost an year from HCW.

This article will need to be changed since we have some customers opening cases stating that express is missing from HCW. Also Data migration has been moved in the portal so most of the article needs to be changed.

Minimal only works with installing AAD Connect.

Thank you,

Mihai G 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852cee18-246c-8c33-9834-fd96595b3e71
* Version Independent ID: 094c2d24-81dc-41c7-48be-c61df7b25fbc
* Content: [Use Minimal Hybrid to quickly migrate Exchange mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/use-minimal-hybrid-to-quickly-migrate)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@MihaiGrigoruta  I will follow up with you internally.
