### ISSUE TITLE
4.7.500 Server busy S77719

### ISSUE THREAD

**Issue by AaqibIqbal** [MicrosoftDocs/OfficeDocs-Exchange#2499]
Is this NDR 451-4-7-500-699-asxxx same as 4.7.500 Server busy. Please try again later from [IP]. (S77719)

If yes, is the solution the same to create a connector? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 141b632d-00e4-5443-49ce-5ea73dc2375a
* Version Independent ID: c8f6c257-eee6-b6fe-2e33-e4fd6a7b9466
* Content: [Fix email delivery issues for error code 451 4.7.500-699 (ASxxx) in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-451-4-7-500-699-asxxx-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-451-4-7-500-699-asxxx-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-451-4-7-500-699-asxxx-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
