### ISSUE TITLE
FolderBind or Open Folder

### ISSUE THREAD

**Issue by MJAMALQA** [MicrosoftDocs/OfficeDocs-Exchange#25]
When we run audit logging in ECP we see 'Open Folder' whereas when we run PS for the same it gives output as 'FolderBind' is there any bug in the exchange which gives two totally different confusing results also what does accessed means & what does ECP Open Folder means in the MS Exchange world ?? please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f6b7508-bf56-f95c-1e07-af74e7ac936d
* Version Independent ID: 0ff21c1c-2885-acda-8677-2789c60b2cd1
* Content: [Mailbox audit logging in Exchange 2016](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by chrisda** [comment]
@MJAMALQA, according to my research, FolderBind in the audit log or in PowerShell = "Open Folder" in the Exchange admin center (EAC). Similarly, MessageBind in PowerShell = "Open Message" in the EAC.

I wouldn't call the differences a bug; it's just an effort to make things look more friendly in the EAC, whereas if you're in PowerShell, the raw values are used.

'Accessed' is really another word for 'opened'. The folder or message doesn't need to be 'opened' or 'accessed' by a user (for example, eDiscovery searches or activity by service accounts).

**Comment by MJAMALQA** [comment]
Thank you Chris for the clarifications however, its very confusing open folder with the user names (not ediscocery or service a.c but user a.c) seems tobe that user has opened and of course has viewed the contents as well.. one of my colleague almost got fired EAC friendliness was not that good for her.... She was secretary of one of the big guy in the Organisation later moved to another department and forgot to inform IT to clean up also governance laps as well but when checked through EAC it was disaster for her...


Best regards,

M. JAMAL



Get Outlook for Android<https://aka.ms/ghei36>

**Comment by kenwith** [comment]
@MJAMALQA - Thank you very much for this feedback and the discussion.  I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. And sorry for the long delay!

I made a note to request the team to update this when the work is complete.

**Comment by SerdarSoysal** [comment]
Upon further investigation, unfortunately we won't be able to fix the UI in EAC in the near term.
