### ISSUE TITLE
Domain functional level requirements

### ISSUE THREAD

**Issue by RadioActiveLamb** [MicrosoftDocs/OfficeDocs-Exchange#250]
What is the minimum AD functional level required for Exchange 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f347a03-e2c5-5ae2-e409-ddb6d544ccfd
* Version Independent ID: 839ff415-2b55-e312-3121-0fd2d9ca5a88
* Content: [Prepare Active Directory and domains for Exchange Server](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prepare-ad-and-domains?view=exchserver-2019#exchange-active-directory-versions)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RadioActiveLamb the second bullet in the "What do you need to know before you begin?" section linked to the correct information, but the bullet doesn't set the stage correctly. I split the bullet out into 2 separate bullets (one for computer requirements, the other for AD requirements).

Although it can be a bit inconvient at times, I support the theory that it's best to state values like the forest functional level in just one place and then link back to it so you only need to update one topic when it inevitably changes in the future.

Thanks for the feedback.
