### ISSUE TITLE
No longer accurate doesn't exist

### ISSUE THREAD

**Issue by techlogik** [MicrosoftDocs/OfficeDocs-Exchange#2505]
This feature has vanished from Exchange Online admin center and the User Phone and Features Options on their user ID in the cloud Exchange Admin. 404 not found message in the old Exchange admin when you click on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb88828-a7b0-382c-2261-c884c948ad7d
* Version Independent ID: b732e2ef-d1fc-1bda-a6fa-56e59ac85b6e
* Content: [Enable or disable Play on Phone for Outlook Voice Access users in Exchange Online](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-or-disable-play-on-phone)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-or-disable-play-on-phone.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-or-disable-play-on-phone.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by get-itips** [comment]
Hello @techlogik Thanks for your feedback, you are correct, the whole Unified Messaging functionality is being replaced by Cloud VoiceMail, a Note has been added to the Unified Messaging section about this. https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/voice-mail-unified-messaging
Thanks

**Comment by scanum** [comment]
@techlogik  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
