### ISSUE TITLE
CNAME update

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/OfficeDocs-Exchange#2506]
Should the CNAME "points to" be updated to outlook.office.com instead of mail.office365.com?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30c4fd6-0e69-cb9a-6a21-327f0ebae3a7
* Version Independent ID: d0217aa4-a37b-8837-4310-108fbf533a5d
* Content: [Simplify the Outlook Web App URL for Microsoft 365 or Office 365 Hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/simplify-owa-url)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
