### ISSUE TITLE
Dates of Retirement of Classic Exchange Admin Center

### ISSUE THREAD

**Issue by vicslive** [MicrosoftDocs/OfficeDocs-Exchange#2507]
Customers are asking if we will retire the Classic Admin Center, since they are missing things from the classic and are afraid that we are publishing new center, they need to know if a decomission date is know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe03d3b-31dc-90a2-2a78-1e48947b86d8
* Version Independent ID: 2873f6e9-6979-31d1-5622-0ae47cd9d965
* Content: [Exchange admin center in Exchange Online](https://docs.microsoft.com/en-us/exchange/exchange-admin-center)
* Content Source: [Exchange/ExchangeOnline/exchange-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/exchange-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
