### ISSUE TITLE
Users with Application Impersonation Role assigned will also be able to install the Outlook Add-Ins

### ISSUE THREAD

**Issue by amanrajay** [MicrosoftDocs/OfficeDocs-Exchange#2508]
[Users with Application Impersonation Role assigned will also be able to install the Outlook Add-Ins , Tried and tested on my test tenant, may be a bug, or you could add this command line in the article as well.
Get-ManagementRoleAssignment -Role "ApplicationImpersonation" -GetEffectiveUsers
All the listed users in the above list have access to office add-ins even after blocking from the default role assignment policy for EXO and integrated apps & add-ins from M365 admin center..
Also please specify that the Org Market place apps cannot be removed from the organization management as it is inbuilt role, even after removing the role from Organization management , it will still show under it when the command is run and Please note , this is tested on more than 3-4 tenants.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86c9e05-c68b-8f00-3a94-c902d3352590
* Version Independent ID: e299bde7-ee34-96eb-b7f3-2ae75db017d3
* Content: [Specify the administrators and users who can install and manage add-ins for Outlook](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
