### ISSUE TITLE
Standard or Premium Journaling

### ISSUE THREAD

**Issue by dbranscome** [MicrosoftDocs/OfficeDocs-Exchange#251]
In the subheading "**Decrypt IRM-protected messages to enforce messaging policies**", it says:

_Journal report decryption: Allows standard or premium journaling to save a clear-text copy of IRM-protected messages in journal reports. For more information, see Enable journal report decryption._

However, at this site: https://products.office.com/en-us/exchange/microsoft-exchange-server-licensing-licensing-overview?rtc=1 it indicates that Journal decryption is only available when a customer buys the Standard + Enterprise CAL. Can we clarify which one is correct?

**Comment by chrisda** [comment]
@dbranscome it's premium journaling only. I updated the topic.

Thanks for the feedback

**Comment by chrisda** [comment]
@dbranscome it's premium journaling only. I updated the topic.

Thanks for the feedback.
