### ISSUE TITLE
How to configure outbound mail through 3rd party

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/OfficeDocs-Exchange#2514]
You describe the #scenario2 as follows:

> I plan to use Exchange Online to host all my organization's mailboxes. All email that's sent to my domain from the internet must first flow through a third-party archiving or auditing service before arriving in Exchange Online. All outbound email that's sent from my Exchange Online organization to the internet must also flow through the service. However, the service doesn't provide a spam filtering solution.

Your are describing only how to configure inbound connectors via "Enhanced Filtering for Connectors".
But I am missing how to configure outbound connectors in case I have all mailboxes in Exchange Online but want to route all outgoing mail to the internet trough a 3rd party service.

best regards
Joerg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by joergrenn** [comment]
Thank you for your reply. Sadly that is not the answer I was expecting.
My point for this request was, that your publicly available documentation is incomplete and I was hoping that there is the interest to provide complete and up to date documentation Microsoft products.
Then I could read about the configuration necessary for my specific case. 
There should be internal communication channels for you to get better information then I can externally.
Sadly this is well above the skill level or understanding that I experience regularly with the MS support that you recommend.
