### ISSUE TITLE
Issue Editing Email Properties/Deleting a Distribution List

### ISSUE THREAD

**Issue by rhamnik** [MicrosoftDocs/OfficeDocs-Exchange#2515]
In the new EAC, for a distribution list I had created, I am unable to edit email addresses (primary/aliases) or even just delete the distribution list.  Membership (owners/members) mgmt is fine.  The issue does not occur in the "Classic" EAC.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
