### ISSUE TITLE
Feedback on retention tags

### ISSUE THREAD

**Issue by BeckyThompson** [MicrosoftDocs/OfficeDocs-Exchange#2516]
This documentation is so hard to understand and poorly written, it is basically useless.  After reading the full document, I have no understanding of how to use this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c69230a4-9eaa-16db-ef8c-5e099c93bc42
* Version Independent ID: 525d597e-07a0-5510-474c-7881934f97ee
* Content: [Retention tags and retention policies](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-tags-and-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/retention-tags-and-policies.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@BeckyThompson Thanks for your feedback we appreciate it and we will consider it while updating the documentation.
