### ISSUE TITLE
connector type

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/OfficeDocs-Exchange#2518]
On this page your describe how to Integrate Microsoft 365 or Office 365 with an email add-on service.
There are different types of connectors. 
The connectors used in the description are "-ConnectorType OnPremises"
Shouldn't the connector type be "Partner" instead? 
According the description in the exchange admin center (see screenshot) "on premises" means:
> Your organization's email server: This is an email server that you manage. It's often called an on-premises server.

and "partner" means:
> Partner organization: A partner can be an organization you do business with, such as a bank. **It can also be a cloud email service provider that provides services** such as archiving, anti-spam, and so on.

Is this a documentation error? Shouldn't the connector type be "partner" Because its not my email server, but a partner providing a signature service.
If "on premises" is correct. Please add an explanation why it is correct in this case.

<img width="688" alt="grafik" src="https://user-images.githubusercontent.com/62641471/111451666-f6d0b980-8711-11eb-868d-8be111931da0.png">

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f44c94af-aa03-b648-7c87-6f77e9ada172
* Version Independent ID: 2608dfd4-92a4-1c8e-5675-26ce9f3423a2
* Content: [Scenario Integrate Microsoft 365 or Office 365 with an email add-on service](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/integrate-office-365-with-an-email-add-on-service)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/integrate-office-365-with-an-email-add-on-service.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/integrate-office-365-with-an-email-add-on-service.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by joergrenn** [comment]
sorry to bother you.
