### ISSUE TITLE
Powershell Commands not available in Exchange Online

### ISSUE THREAD

**Issue by OSuperfly** [MicrosoftDocs/OfficeDocs-Exchange#2519]
Hi Team,

I'm currently in the process migrating OnPrem Exchange public folders to M365.
My problem is, that the provided PowerShell script "Sync-ModernMailPublicFolders.ps1" referres to the EXO Powershell command "Remove-EXOSyncMailPublicFolder" but this seems not to be available anymore?

So the execution of "Sync-ModernMailPublicFolders.ps1" results in:

(translated)
RemoveMailEnabledPublicFolder : The name "Remove-EXOSyncMailPublicFolder" was not recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name or whether the path is correct (if included) and try again.

Other referred EXO cmds which are not available are:

New-EXOSyncMailPublicFolder
Set-EXOMailPublicFolder

 I'm stuck in the migration so any help would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
