### ISSUE TITLE
Error in Folder/Path to Forms folder

### ISSUE THREAD

**Issue by GLComputing** [MicrosoftDocs/OfficeDocs-Exchange#252]
You miss the "root" in each of the four examples. Eg With Office2016 x64/x64 or x32/x32, it would be:
C:\Program Files\Microsoft Office\root\Office16\FORMS\1033

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9601e5-52f6-d694-b28f-d03767f0f11c
* Version Independent ID: 6520d47a-d8e8-cff3-d765-a1f9d0f4ce41
* Content: [Configure Outlook to show the original sender in the spam quarantine mailbox](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antispam-protection/show-quarantined-message-original-senders?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/show-quarantined-message-original-senders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/show-quarantined-message-original-senders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@GLComputing I fixed it. Thanks for the feedback.
