### ISSUE TITLE
Need this to be automated and continuous

### ISSUE THREAD

**Issue by mgalhouse** [MicrosoftDocs/OfficeDocs-Exchange#2521]
In a modern threat environment, this data needs to be accessible in almost real time to a SIEM. **_Please_** devise some sort of connector to accomplish that.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48638216-9e8d-81ad-9e87-19b878f36ced
* Version Independent ID: 3561ef40-f0af-c484-1df0-9b4f0c3aa57e
* Content: [Export mailbox audit logs](https://docs.microsoft.com/en-us/Exchange/security-and-compliance/exchange-auditing-reports/export-mailbox-audit-logs)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/export-mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/export-mailbox-audit-logs.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
