### ISSUE TITLE
When does a rule activate when using 'Activate this rule on'

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#2522]
The following section talks about activating and deactivating a rule at the specified date. 
Two comments:
1) We can actually set date and time, not just date. 

And more importantly,

2) What timezone does this use? local time, UTC, something else?

> If you want this rule to take effect after a certain date, click Activate this rule on the following date: and specify a date. Note that the rule will still be enabled prior to that date, but it won't be processed.
>
> Similarly, you can have the rule stop processing at a certain date. To do so, click Deactivate this rule on the following date: and specify a date. Note that the rule will remain enabled, but it won't be processed.

Also, I notice the powershell module documentation leaves the same question.
> Activate this rule on the following date: Specifies the date range when the rule is active.
https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jonwbstr** [comment]
Hello,

I received the following update from Support this morning,
> The transport rule time is based on the organization timezone which can be found by visiting admin.microsoft.com > settings > org settings > organization information and noting the organization "State"

For more information about organization settings, see the article below
https://docs.microsoft.com/en-US/microsoft-365/admin/manage/change-address-contact-and-more

**Comment by jonwbstr** [comment]
@scanum do you get the new comment because you're a participant in the ticket, or do I need to mention them?
I'm wondering how long to wait before creating a new ticket requesting this ticket be reopened. I'm going with 7 days till someone suggests a different time period ;). 

The practice of closing tickets that aren't resolved is something I've seen from multiple content owners and I'm not really clear on how to reopen.
