### ISSUE TITLE
Details on Matched Spam Rules

### ISSUE THREAD

**Issue by oliverrahner** [MicrosoftDocs/OfficeDocs-Exchange#2524]
I have seen MicrosoftDocs/OfficeDocs-o365seccomp/issues/230, but the answer just links back to this site.
Is there any pointer as to what each individual rule checks for?
We are currently optimizing sent mail and for some reason that we don't understand, it gets classified as spam.
The only details we get are as helpful as `SFS:(42882007)(966005)(26005)(16799955002)(15188155005)(33964004)(19627405001)(103116003)(6666004)(1096003)(6916009)(9686003)(76236003)(83380400001)(66574015)(336012)(19810500001)(5660300002)(166002)(6266002)(956004)(7066003)(356005)(1076003)(7636003)(7596003)(83170400001)(53862002)(175423001)(131040200001)(559001)(579004)(15585785002)(12968915004)(19623215001)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7684ef8f-2f6d-7c73-fddb-19b94096e82a
* Version Independent ID: 9910c94c-df87-74c1-fa32-e153857a64ab
* Content: [Run a message trace and view the results in the Exchange admin center](https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results)
* Content Source: [Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
