### ISSUE TITLE
Improve text for « Create a subdomain for mail routing to Microsoft 365 or Office 365 »

### ISSUE THREAD

**Issue by FrancoisMongeau** [MicrosoftDocs/OfficeDocs-Exchange#2525]
Fairly good documentation for a quite complex process.
I could follow the instructions until this paragraph:
« 5. Log into your DNS provider and update your DNS records so that you have an MX record at the domain you created above in step 3, pointing to Microsoft 365 or Office 365. Ensure that this domain that you created above is an accepted domain in Microsoft 365 or Office 365. Follow the instructions in Add a domain to Microsoft 365 to add the Microsoft 365 or Office 365 routing domain ("o365.fabrikaminc.net") to your organization and to configure DNS to route mail to Microsoft 365 or Office 365.»
This paragraph packs too many steps unto a simple paragraph.
1 Should it not say « Log into your DNS provider and update your DNS records so that you have an MX record **for** the domain you created above in step 3 »
2 What MX record? what should the content of that record be? And it's priority?
3 and then « pointing to Microsoft 365 or Office 365 » - what does that mean? Assuming it's the target what's the value?
4. and then « configure DNS to route mail to Microsoft 365 or Office 365 » - what does that mean in more details - or is this repeating the same previous instruction?
I'm stuck there. I hope I can figure it out before Monday morning when my users will ask for their emails ;)
... and why is my text showing in bold ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
