### ISSUE TITLE
I think there is an error

### ISSUE THREAD

**Issue by ideoLAB** [MicrosoftDocs/OfficeDocs-Exchange#2526]
[Enter feedback here]
The paragraph "Create a subdomain for mail routing to Microsoft 365 or Office 365" explains how to create a subdomain in GSuite and not in M365 ...
Also, when everything is ready for migration, the M365 alias does not receive the forwarder's mail from GSuite ... there is something missing in the procedure description ...

Thanks for reply
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@ideoLAB Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@ideoLAB thank you for reaching out. I see the article has been updated recently and there is information regarding M365. Please have a look and let me know if you think there is still information missing, and I'll look into it.

**Comment by Reeced40** [comment]
@scanum this can be closed thank you.
