### ISSUE TITLE
Typo in: Configure connection filtering on Edge Transport servers that aren't directly connected to the Internet:

### ISSUE THREAD

**Issue by odedkalev** [MicrosoftDocs/OfficeDocs-Exchange#253]
"For example, your organization might send email traffic through an antipam server".
should be: antispam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3da80137-b2f5-6c0c-2da9-9519902fed09
* Version Independent ID: 0a7f6d68-de1b-d89a-fed8-cb0f98c6bd70
* Content: [Connection filtering on Edge Transport servers](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antispam-protection/connection-filtering?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/connection-filtering.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/connection-filtering.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@odedkalev I fixed it. Thanks for the feedback.
