### ISSUE TITLE
Set-DistributionGroup

### ISSUE THREAD

**Issue by sivan-koren** [MicrosoftDocs/OfficeDocs-Exchange#2531]
It's great to know how to use a cmdlet, but if it's not built into PowerShell, the article should include instructions for installing the cmdlet or at least where to find information about the cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4e18b1-5821-73a0-eef8-5cdafb3b8401
* Version Independent ID: b3534855-b60a-797f-4d65-65b514397ab5
* Content: [Create and manage distribution groups](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by michelderooij** [comment]
Top of article mentions, "To connect to Exchange Online PowerShell, see Connect to Exchange Online PowerShell." (with link).

**Comment by sivan-koren** [comment]
Actually it links to an article that explains how to connect with the
module if it's already installed.

It suggests "Import" which doesn't seem to work.

It seems like you have to install it first, or at least that was the case
for me.

I was able to get this to work using third party documentation that offered
the correct installation procedure.

It would be great if the installation process or a link to it was simply
provided in the docs.

**Comment by joe429mama** [comment]
Ok

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scanum** [comment]
@sivan-koren Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
