### ISSUE TITLE
the article by mistake says  Enable-Mailbox -RemoteArchive -ArchiveDomain archive.contoso.com

### ISSUE THREAD

**Issue by jahube** [MicrosoftDocs/OfficeDocs-Exchange#2532]
Hi,
minor but import correction 

the article by mistake says  -ArchiveDomain archive.contoso.com

while the screenshot shows the correct value "tenant.MAIL.onmicrosoft.com"

correct

Enable-Mailbox -Identity ayla@contoso.com -RemoteArchive -ArchiveDomain "tenant.MAIL.onmicrosoft.com"
 
Br Jan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dfb49c-fbb1-4e58-a94b-060f31744d6e
* Version Independent ID: 2b2de3cb-3087-c82a-f6ad-f58990a85ae0
* Content: [Create a cloud-based archive in an Exchange hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/create-cloud-based-archive)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jahube Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@jahube thank you for reaching out and helping improve MS Docs. It looks like the error has been fixed in the interim. Please confirm from your side. Thanks.

**Comment by Reeced40** [comment]
@scanum this can be closed thank you.
