### ISSUE TITLE
Google Workspace Migration: Configuration Section is missing new Screenshots in modern Admin Console

### ISSUE THREAD

**Issue by matsimon** [MicrosoftDocs/OfficeDocs-Exchange#2534]
Hi

The Screenshots in the "Configuration" Step for setting up a migration batch in the modern Exchange Admin Console don't match up with the reality such as the Targetdelivery domain.

Additionaly typing the required target delivery domain is not possible in the modern EAC while is is possible and actually required for successfully configuring the mail forwarding during the completion phase.

Looking forward to get this updated to reduce the possible pitfals and thus support requests on your end.

Regards
Mathieu

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
