### ISSUE TITLE
Recommendation to clear auto-complete list

### ISSUE THREAD

**Issue by woodyarray** [MicrosoftDocs/OfficeDocs-Exchange#2535]
In the "End-user communications" section, you mention:

> After migration, the Auto-Complete List (also known as the nickname cache) **will have to be cleared on all Outlook clients**. To remove all recipients from your Auto-Complete list in Outlook 2010 later, see Manage suggested recipients in the To, Cc, and Bcc boxes with Auto-Complete.

Can you explain WHY you need to clear this and the implications if one does not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Microsoft 365 or Office 365 organization to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by michelderooij** [comment]
When addressing recipients internally in an organization, Outlook caches the internal address of that recipient. That address stems from an attribute legacyExchangeDN. Unless you stamp that address as X500:<address> address on the migrated object, Exchange Online cannot find that recipient when delivering the message, hence will result in non-delivery reports. Note that you can remotely clear this cache (OWA and Outlook AutoComplete stream), but Outlook needs to be closed for this to be effective as it uses a local copy, see https://github.com/michelderooij/Clear-AutoComplete
