### ISSUE TITLE
Should link to 'Classic Exchange Admin Center'

### ISSUE THREAD

**Issue by 1RedOne** [MicrosoftDocs/OfficeDocs-Exchange#2536]
There is a section on the page that says 'do these steps in the Classic Exchange Admin center', it isn't clear if this is avilable to people with a personalized e-mail address from Outlook.com.  

Also, it should have a link to classic exchange admin center, for ease of use!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer Google Workspace (formerly G Suite) mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@1RedOne Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
1RedOne thank you for reaching out. Would this link suffice? - https://docs.microsoft.com/exchange/exchange-admin-center. I also see that the article was updated in April. Please let me know if you still think something is missing and I'll look into it.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
