### ISSUE TITLE
Error code 5.4.14 - additional cause

### ISSUE THREAD

**Issue by mav-cloud** [MicrosoftDocs/OfficeDocs-Exchange#2539]
Hi, not sure if this is the appropriate location but I was able to reproduce error code 5.4.14 using Outlook Delegation. If a user is a delegate and the user is disabled but remains as a delegate, people accepting meeting invites will receive 5.4.14 NDRs. Might want to add this as a possible cause under this subheading: https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-4-6-through-5-4-20-in-exchange-online#causes-for-ndr-5414-and-what-does-this-error-mean
![image](https://user-images.githubusercontent.com/72559026/112632639-bf979200-8e0e-11eb-958d-59100194e0b8.png)

**Real world example:**
Outlook power user administrative assistant has the necessary permissions on the CEO's user mailbox. The administrative assistant can add themselves to Outlook Delegates on the CEO Outlook profile. If the administrative assistant leaves the company, their account is disabled, this delegation is not removed from the CEO's Outlook profile and anytime the CEO sends a new meeting the accepting party will receive 5.4.14 NDRs since the delegate no longer exists in Exchange. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2943f17-2dd1-0864-07ca-716eb0892647
* Version Independent ID: ce2a378e-89c5-cd14-697e-20a2ea3e6230
* Content: [Fix email delivery issues for error code 5.4.6 or 5.4.14 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-4-6-through-5-4-20-in-exchange-online#causes-for-ndr-5414-and-what-does-this-error-mean)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-4-6-through-5-4-20-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-5-4-6-through-5-4-20-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
