### ISSUE TITLE
Error in page in Step 2: Connect Microsoft 365 or Office 365  to your email system

### ISSUE THREAD

**Issue by SergePoint** [MicrosoftDocs/OfficeDocs-Exchange#2540]
In this section : **Step 2: Connect Microsoft 365 or Office 365 to your email system,** the rest of the documentation is also showing the old way to do cutover migration.
you should change the steps for:
Go to the Exchange admin center.
In the Exchange admin center, go to Migration > Batch > Add Batch Migration
and add the steps for the batch migration.
Serge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.
