### ISSUE TITLE
Missing Info About Target Mailbox

### ISSUE THREAD

**Issue by squrl33** [MicrosoftDocs/OfficeDocs-Exchange#2542]
This article repeatedly mentions that you CAN recover deleted messages to a target discovery mailbox, how to know if recovering to discovery mailbox worked, and what to do after doing so, etc. - all great info - but it doesn't say how to actually go about recovering the messages to the discovery mailbox. It only shows how to recover to the user's mailbox, using Restore-RecoverableItems. How do you specify the target mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496c2124-3973-e6d1-385e-4ec25228dc49
* Version Independent ID: cd70012a-5cdf-bac5-3a29-df38b19df1cb
* Content: [Recover deleted messages in a user's mailbox in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
