### ISSUE TITLE
Migration Batch Page lack of information

### ISSUE THREAD

**Issue by useyourblinker** [MicrosoftDocs/OfficeDocs-Exchange#2543]
[Enter feedback here]

Dear Microsoft - your page about migration batches would do well to have some additional information and links on it. It leaves people (in partial migration states) hugely void of information.

-It does not list the fact that when migration batches are removed (after 60 days of inactivity) that ALL THE HISTORICAL DATA from them is also removed. You cannot see what users had been partially migrated (or have data synced), what the dates of those partial or incomplete migrations were, or the dates they were deleted.

-There's no reference to information about what happens to the mailboxes that were Synced in the meantime. For a couple of completed batches, there might actually be completed users showing up in Mailboxes. But what about the rest? Whether or not they're licensed - dos any data still exist in some theoretical mailbox? If Get-Mailbox (in powershell) is empty, is there still data to clear out before re-starting a migration?

This page leaves many questions like this, and the rest of the documentation surrounding these migrations seems woefully inadequate to fill in the gaps, as far as we've found.

Any improvements here would be appreciated, long-term, as people flee from on-prem Exchange and go to the cloud!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a684ff-29af-b532-deea-01fecbd6b8cb
* Version Independent ID: a90ceb5c-8553-2636-ab85-14688435ee4d
* Content: [Manage migration batches](https://docs.microsoft.com/en-us/exchange/mailbox-migration/manage-migration-batches)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/manage-migration-batches.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/manage-migration-batches.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@useyourblinker Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hello @useyourblinker, thank you for your feedback and help us to improve docs.microsoft.com.

The following note is included in the article:
> [!IMPORTANT]
> Migration batches with a status of **Synced** that have no administrator-initiated activity (for example, no administrator has stopped and restarted a migration batch or edited a migration batch) for the last 60 days will be stopped. All batches with **Stopped** or **Failed** status will be removed after 90 days. All batches with **Completed** status will be removed after 60 days.

After 60/90 days, the migration batch object is removed, and I think there is no other place to get information about it.

About your second question, I'm trying to get more information.

**Comment by dariomws** [comment]
@Benny-54, could you kindly help here? Thanks!

**Comment by Benny-54** [comment]
Hi @dariomws I'll check with the product owner and fix this. Thank you, have a great day.

**Comment by useyourblinker** [comment]
> Hello @useyourblinker, thank you for your feedback and help us to improve docs.microsoft.com.
> 
> The following note is included in the article:
> 
> > [!IMPORTANT]
> > Migration batches with a status of **Synced** that have no administrator-initiated activity (for example, no administrator has stopped and restarted a migration batch or edited a migration batch) for the last 60 days will be stopped. All batches with **Stopped** or **Failed** status will be removed after 90 days. All batches with **Completed** status will be removed after 60 days.
> 
> After 60/90 days, the migration batch object is removed, and I think there is no other place to get information about it.
> 
> About your second question, I'm trying to get more information.

@darionmws I have come to the conclusion you're describing by accident - but it should note in the article that there will be no record of the previous migrations in any kind of log or archive that is accessible by anyone (including Microsoft).

Sometimes, you are trying to finish a migration from another IT staff with poor documentation and no case notes. When you pick up a situation like that, it's useful to at least know that there's no way to find out if they were doing a Move migration or Cutover or what has happened (and for what mailboxes). So although it says that they will be removed after 90 days, **I am suggesting it should say that additionally there will be no log of what happened or what was migrated** anywhere - even if you contact Microsoft support (which was my experience). You simply have to guess what kind of migration was done (and use other context to figure out whose mailboxes were migrated vs created 'in the cloud') in this situation, and hope that it's inconsequential to the rest of your project.

**Comment by dariomws** [comment]
Hi @useyourblinker, thank you again for your comment.

I'm not describing by accident. I understood your request very well. I respect your opinion, but I do not fully agree. I think It's understandable that if the only place to see migration information and statistics is the migration batch itself, you lose that information after you remove it. Also, I've verified, and I couldn't find similar feedback or request on this article.

But again, I am kindly sharing my thoughts. I hope you can understand. I can propose an update to the note, and another colleague will check it to approve or close it. Do you think that can help?

I can add a new line, for example:

> [!IMPORTANT]
> Migration batches with a status of **Synced** that have no administrator-initiated activity (for example, no administrator has stopped and restarted a migration batch or edited a migration batch) for the last 60 days will be stopped. All batches with **Stopped** or **Failed** status will be removed after 90 days. All batches with **Completed** status will be removed after 60 days.
> After a batch is removed, no records, logs or information are kept about them.

Do you think this can work?

Thank you so much!

**Comment by Benny-54** [comment]
@Swatyario

**Comment by Benny-54** [comment]
Hi @dariomws, @Swatyario is the product owner for EAC. He said he'll look into this and get back to you. Thank you.

**Comment by dariomws** [comment]
Thank you @Benny-54!

**Comment by dariomws** [comment]
@Benny-54 any update here? Thanks!

**Comment by Benny-54** [comment]
@dariomws the concerned team said they'll update it at the earliest. For more information, please check with Aditya Mukund <Aditya.Mukund@microsoft.com>. Thank you.

**Comment by dariomws** [comment]
Thank you @Benny-54!

**Comment by Swatyario** [comment]
Hi Dario,

I was sick OOF for quite a few days and I am back to work now.
Could you please share with me here the link of the issue?
I will take care of it and let you know the target timeline for the same.

Aditya
________________________________

**Comment by dariomws** [comment]
Hi @Swatyario,

I hope you're well now. Thank you for your reply.

You can find the first comment on this issue here:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2543

I would appreciate it if you can share your thoughts on the first comment and more information on the second.

Thank you again!

**Comment by Swatyario** [comment]
@useyourblinker : Thanks for pointing us to the migration page issues. 1st point has already been taken up it seems. For the 2nd point, here is the update: We have started working on making the migration documentation page much better and legible. We are starting from Google Workspace migration and will make other changes as well before June, 2021 ends.

**Do let us know the other troubles that you are facing**. That will give us better understanding of user pain-points and we will work that out.

**Comment by dariomws** [comment]
@Swatyario do you have any update here to share with us? Thanks a lot!

**Comment by Swatyario** [comment]
Adding @Joanne ***@***.***> here.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dariomws** [comment]
@JoanneHendrickson do you think you can help here? Thanks!

**Comment by tiburd** [comment]
We’ve passed on this information to the product team. 

Closing this issue.
