### ISSUE TITLE
Outdated documentation around plus addressing

### ISSUE THREAD

**Issue by ethanbradley** [MicrosoftDocs/OfficeDocs-Exchange#2544]
This page says in one of the notes

> support for Groups and DLs is being rolled out and will be available by the end of December 2020.

At the time of writing it's March 2021, so this may need udpated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2481-2a27-06f3-976c-90614a863d81
* Version Independent ID: a3c4f846-0578-54ed-f2a8-c511be3605af
* Content: [Plus Addressing in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by scanum** [comment]
@ethanbradley Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
@ethanbradley thank you so much for your feedback.

@seanws could you kindly help me confirm if this was released in December? I cannot find related information.

Thanks!

**Comment by dariomws** [comment]
@SeanMSFT could you kindly help me confirm if this was released in December? I cannot find related information.

Thanks!

**Comment by Benny-54** [comment]
Hi @dariomws, got it confirmed from the concerned team. This was released in December 2020. The updated note will be live at the earliest. Thank you.

**Comment by dariomws** [comment]
Thank you @Benny-54!

**Comment by dariomws** [comment]
The following note:

>[!NOTE]
> Currently, plus addresses are only supported for mailboxes but support for Groups and DLs is being rolled out and will be available by the end of December 2020. 

Was updated to:

>[!NOTE]
> Plus addresses are only supported for mailboxes and Groups. 

8 days ago.

@scanum this issue can be closed.

**Comment by dariomws** [comment]
@scanum this issue can be closed.
