### ISSUE TITLE
How do partners access this?

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/OfficeDocs-Exchange#2546]
Under the 'classic' exchange admin center we could navigate to the pages via the partner center > 365 admin > exchange admin (classic) and then make changes to the tags and policy. 
Now we are unable to access the same settings so how are we supposed to edit this using our partner access?
Or is this another, we'll sort our partners out later on?..

Workaround would be use a tenant admin account, with reduced security as we can't do 2fa as its badly implemented when many users might need to access the same account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5be8284-bc52-a254-97eb-ef44b3cb002a
* Version Independent ID: 25c499c9-c274-933d-6c56-ae126c32079e
* Content: [Default Retention Policy in Exchange Online and Exchange Server](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/default-retention-policy)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-retention-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-retention-policy.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
