### ISSUE TITLE
bad page title in the content list

### ISSUE THREAD

**Issue by gjuwindev** [MicrosoftDocs/OfficeDocs-Exchange#2549]
on the page https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-group-access-to-microsoft-365-groups

there is a item "Manage GROUP access to Microsoft 365 groups", and the title of actual page is "Manage GUEST access to Microsoft 365 groups"

so, GROUP vs GUEST :-)
![msdoc error](https://user-images.githubusercontent.com/20825928/113729995-c7511380-96f7-11eb-9848-14c907c8ef5f.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28bc43ec-5fbf-f8a1-19c6-06ec377e452e
* Version Independent ID: 88ed9745-0bc0-08d5-2481-f5e166a6b8ea
* Content: [Manage guest access to Microsoft 365 groups](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-group-access-to-microsoft-365-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-microsoft-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-microsoft-365-groups.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@gjuwindev Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@scanum this can be closed thanks.
