### ISSUE TITLE
Version updates out of date

### ISSUE THREAD

**Issue by leighmo** [MicrosoftDocs/OfficeDocs-Exchange#255]
Hi,

Just confirming that CU23 and CU24 are out for Exchange 2010 SP3 however they're not listed on the docs page. 

Cheers,
Leigh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf984bf-df1c-bcd5-6475-54b9ef24fe74
* Version Independent ID: 00547ab9-7b3b-f6b0-fa7f-429f5e2bea56
* Content: [Exchange Server build numbers and release dates](https://docs.microsoft.com/en-us/Exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@leighmo I added Ru23 and RU24 for 2010 SP3. Thanks for the feedback.
