### ISSUE TITLE
Client Access Rules and EWS Impersonation

### ISSUE THREAD

**Issue by EgorEmeliyanov** [MicrosoftDocs/OfficeDocs-Exchange#2552]
It is important to note here that EWS Impersonation is not affected by Client Access Rules. So one of the most popular use cases -- locking down a sensitive service account which has access to a number of mailboxes to a predefined set of source IP addresses -- won't work. This is by design and confirmed by M365 support (ticket 24968099).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9cdf39f-da71-43ab-0ceb-a816bdc19d04
* Version Independent ID: 1fff6b28-f8d8-d9b3-1730-db2cac7835a0
* Content: [Client Access Rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@EgorEmeliyanov Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@EgorEmeliyanov thank you for reaching out. I see this article was updated with some information recently. Please can you clarify if you think a note should still be added here.

**Comment by EgorEmeliyanov** [comment]
Hello @Reeced40 Since the new version still doesn't describe how Client Access Rules interoperate with EWS impersonation, I do believe a note is still needed.

**Comment by Reeced40** [comment]
@msdmaguire please can you confirm?

**Comment by Reeced40** [comment]
@msdmaguire

**Comment by dariomws** [comment]
Hi @EgorEmeliyanov, thank you for your feedback.

I agree. I'm going to propose an update and ask for confirmation. Even Exchange Web Services (EWS) is being deprecated and no longer receiving feature updates. Maybe it will be finally disabled someday instead of adding the ability to block EWS impersonation.
