### ISSUE TITLE
Article needs updating - new step required

### ISSUE THREAD

**Issue by PWHenne** [MicrosoftDocs/OfficeDocs-Exchange#2553]
There is a new configuration step that is not yet included in this article.

For Option 3, Configure a connector, there is an additional step that is required, but not mentioned in the article, as follows:

The IP address of the customer's mail system must be entered into the IP Allow list in the Anti-Spam Connection filter policy in the Security portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@PWHenne Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @PWHenne, thank you for your feedback.

The article contains a recommendation to add the on-premises device/server's IP address to the SPF record. This is intended to prevent these emails from being filtered as suspicious. Did you have problems even though you added it to the SPF?

**Comment by dariomws** [comment]
You're welcome @PWHenne!

Adding the IP to the Allow List has a stronger impact. I think adding it to the SPF record should be enough. Please, continue working with support to double-check it as I cannot provide you with more help. Here we are limited to documentation issues and improvements, and we don't have enough evidence to update the article.

Also, for more information:
https://docs.microsoft.com/microsoft-365/security/office-365-security/configure-the-connection-filter-policy
https://docs.microsoft.com/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365

**Comment by dariomws** [comment]
@scanum I think this issue can be closed.
