### ISSUE TITLE
Open another User's mailbox is not there

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-Exchange#2555]
Documentation states that:

"The new, modern EAC now has an Open another user’s mailbox option, which adjusts Inbox rules and out-of-office messages on behalf of a user, without requiring that user to grant full admin access to their mailboxes." 

But seems that this functionality is by clicking on profile and selecting "View another mailbox." 

Needs Clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa40ca38-c70b-6f85-b323-76d8205f2d4f
* Version Independent ID: d4f35834-02c6-84b1-17bc-b50531bc5141
* Content: [What's new in Exchange admin center](https://docs.microsoft.com/en-us/Exchange/whats-new)
* Content Source: [Exchange/ExchangeOnline/whats-new.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/whats-new.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dkotars Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @dkotars
