### ISSUE TITLE
Terms have changed in 365, cannot locate "Compliance Management"

### ISSUE THREAD

**Issue by mntorq** [MicrosoftDocs/OfficeDocs-Exchange#2556]
I see Compliance Manager, Communication Compliance, Records Management, but no **Compliance Management**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d3268bb-2ad4-7c02-3454-a412e97b30e9
* Version Independent ID: 43ad9df1-e641-f8ee-d2be-4f2ce9d8e8c2
* Content: [Modify archive policies](https://docs.microsoft.com/en-us/exchange/security-and-compliance/modify-archive-policies)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/modify-archive-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/modify-archive-policies.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@mntorq Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@mntorq thank you for reaching out. Please can you help clarify what is missing in this article and I'll have it added.

**Comment by mntorq** [comment]
I see, it's referencing the EAC -
I think I was still in Security & Compliance.

Having very similar, and overlapping functions in various pages/areas is confusing to say the least.
________________________________

**Comment by Reeced40** [comment]
@scanum this can be closed thank you. @mntorq thank you for reaching out. We will endeavor to continuously improve MS Docs.

**Comment by Reeced40** [comment]
@scanum this can be closed thanks.
