### ISSUE TITLE
Missing details on hybrid

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#2558]
Please add details on what is required to support this in a hybrid environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2481-2a27-06f3-976c-90614a863d81
* Version Independent ID: a3c4f846-0578-54ed-f2a8-c511be3605af
* Content: [Plus Addressing in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @danmyhre, thank you for your feedback.

Plus addressing was released (and supported in) for Exchange Online. Exchange on-premises (and therefore hybrid) does not support it. More information is included in the article:

> [!NOTE]
> This feature was rolled out behind a setting because, historically, customers have been able to use plusses in addresses for mailboxes in Exchange Online and on-premises servers. When this feature is enabled, Exchange Online will first check if the full address can resolve to a mailbox that the service is aware of. It is only when that resolution fails, that a plus is looked for and a second attempt to resolve the address without the plus and tag is done. This means that the feature is compatible with addresses containing plusses that Exchange Online knows about. If you relay messages to a mailbox on-premises that does not resolve in Exchange Online, message delivery will be affected. The messages will be parsed and addressed to the parsed address e.g. sean@contoso.com instead of the full sean+newsletter@contoso.com, using the example above.

**Comment by danmyhre** [comment]
Okay, thanks for the info. I would recommend adding a big note that this is totally not supported for hybrid and EXS scenarios. That is important for many enterprise customers.

**Comment by SeanMSFT** [comment]
There is partial support for on-premises recipients so long as the message first passes through Exchange Online. I've submitted a PR to update a note to explain that. Thanks

**Comment by dariomws** [comment]
Thanks @SeanMSFT!

**Comment by dariomws** [comment]
@scanum this issue can be closed.
