### ISSUE TITLE
Explicitly stating that Azure AD Connect Cloud Sync is not supported

### ISSUE THREAD

**Issue by henascim** [MicrosoftDocs/OfficeDocs-Exchange#2560]
With GA for Azure AD Connect cloud sync, it would be great to have an explicit statement about supportability of that feature in the context of the Exchange Hybrid.
The documentation mentions that the Exchange write-back is not possible, but I've seen at least one customer asking what would break in the Hybrid if Cloud Sync is used. 
A statement saying that Azure AD Connect cloud sync is not supported for Exchange Hybrid would help avoid any potential issues caused by customers trying to make both features work together.
Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by henascim** [comment]
Hi @scanum ! Thanks for the update :) I actually work in Microsoft, and the customers that ask me about this, I redirect them to open a service ticket, as you mentioned.
My objective was to have explicit statement on the documentation, so that customers know straight away that Cloud Sync is not supported (or doesn't work) with Exchange Hybrid. 
One of the more common scenarios for our customers is using Azure AD Connect for Exchange Hybrid, so it's normal for them to be curious if Cloud Sync can be used in this context.
Thanks!
