### ISSUE TITLE
Alternate command(s) for forcing item clean-up

### ISSUE THREAD

**Issue by jmeddy** [MicrosoftDocs/OfficeDocs-Exchange#2561]
In cases where the current headings don't apply, I would recommend that a blurb be added or a new section be created with the following command which would simply kick off the native clean-up functionality immediately:

Start-ManagedFolderAssistant -Identity <username>

The command which forces a prior stuck hold clean-up to be removed could also be referenced:

Start-ManagedFolderAssistant -Identity <username> -StopHoldCleanup

https://docs.microsoft.com/en-us/powershell/module/exchange/start-managedfolderassistant?view=exchange-ps

The section could be named something like "Use Exchange Online PowerShell to clean-up the Recoverable Items folder for mailboxes that aren't placed on hold or don't have single item recovery enabled"

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c21112a-deb5-83b3-160e-0149a1e510f6
* Version Independent ID: 4edc9fcd-4971-470b-c56e-e1a2e78b8854
* Content: [Clean up or delete items from the Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/clean-up-deleted-items)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jmeddy Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jmeddy, thank you for your feedback and help us to improve docs.microsoft.com.

The Managed Folder Assistant (MFA) applies and processes the message retention settings. It cleans the Recoverable Items folder when the retention period ends.
This article is intended to delete the items before the retention period end is reached.
