### ISSUE TITLE
Add Outlook UX to Cutover Migration documentation

### ISSUE THREAD

**Issue by JRVcr** [MicrosoftDocs/OfficeDocs-Exchange#2563]
This document needs to describe what the Outlook user experience is when autodiscover and Set-ClientAccess are changed. Have to restart Outlook? Create a new Outlook profile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@JRVcr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
