### ISSUE TITLE
Incorrect CU supportability statement

### ISSUE THREAD

**Issue by jonbutle** [MicrosoftDocs/OfficeDocs-Exchange#2564]
We should remove the last statement from this paragraph, it directly contradicts every CU announcement in the Exchange Team blog for quite a long time now. We only support the latest CU for hybrid deployments:

Exchange server releases: Hybrid deployments require the latest Cumulative Update (CU) or Update Rollup (RU) that's available for your version of Exchange. If you can't install the latest update, the immediately previous release is also supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites?source=docs)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jonbutle  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by serafing** [comment]
@scanum - I spoke to @jonbutle about this and this was just a misunderstanding in the wording on the Exchange team blog.  You can close this.  There is no need to change anything.
