### ISSUE TITLE
Clarity is required for the routing domains

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/OfficeDocs-Exchange#2567]
This article could use more clarity.

There is a section in the "how it works" section where there is discussion of specific routing domains with arrows.
But there are no clear steps as to what are the required steps.

Specifically, "To prepare for the migration, new routing domains have been created: the gsuite.fabrikaminc.net domain points to Google Workspace and the o365.fabrikaminc.net domain points to Microsoft 365 or Office 365."

But then later in the article there is discussion of "Create a subdomain for mail routing to your Google Workspace domain" Is this not the same thing?

I write this because towards the end there is this section "In the fields under Move configuration, name your migration batch, and enter the target delivery domain, which is the domain you created for routing mail to the Microsoft 365 or Office 365 target organization from the Google Workspace source organization." The issue is that you cannot enter the target delivery domain. There is only a drop down and if a step were missing from before, there is nothing that can be done here. You cannot enter and you cannot select a drop down.

Effectively some steps are missing or it there were not followed it's because they were not clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Jmartinez589 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Jmartinez589, thank you for your feedback.

In the **Overview of the process** section, there is a long explanation and diagrams about how these routing domains are used during the migration. But it's an overview to explain how it works, not step by step.

Then in the **Create a subdomain for mail routing to Microsoft 365 or Office 365** and **Create a subdomain for mail routing to your Google Workspace domain** sections, you can find the step-by-step to create these routing domains on each platform.

If you performed the steps under **Create a subdomain for mail routing to Microsoft 365 or Office 365**, you should be able to add the target delivery domain in step 9 of the **Start a Google Workspace migration batch** sections. In particular, you may have forgotten step 5.
