### ISSUE TITLE
Translation is not accurate.

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-Exchange#257]
[フィードバックをこちらに入力してください]
Japanese translation for the following part is not accurate.
It would be appreciated if you could modify the current to the expected one.

<English>
The user mailbox's associated Azure active directory user account has been hard deleted but the Exchange Online mailbox is in a litigation hold or eDiscovery hold.

<Current>
ユーザー メールボックスの関連した Azure Active Directory のユーザーのアカウントは物理的に削除されたが、Exchange Online のメールボックスは訴訟ホールドまたは電子情報開示ホールドになっていない。

<Expected>
ユーザー メールボックスの関連した Azure Active Directory のユーザーのアカウントは物理的に削除されたが、Exchange Online のメールボックスが訴訟ホールドまたは電子情報開示ホールドになっている。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: eff7fa9f-2dec-34c3-e4b3-53614755499f
* Version Independent ID: 61e856b9-12fb-bdf6-0f49-0f6cc8b4b957
* Content: [Exchange Online でユーザー メールボックスを削除または復元する](https://docs.microsoft.com/ja-jp/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by AndreaBarr** [comment]
@AkikoTsukahara Thank you for this feedback

I will get this information about the translation to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by OfficeGSX** [comment]
The suggested translation was implemented and is visible on the live site see the screenshot below. We have also uplifted the topic to HT since it was previously MT.

![image](https://user-images.githubusercontent.com/16706698/52122302-d5401100-2622-11e9-8ebf-2302f8363244.png)

Best regards,

Jiri

**Comment by OfficeGSX** [comment]
The article is HumanTranslated and published live
