### ISSUE TITLE
Submit Message in new EAC Message Trace

### ISSUE THREAD

**Issue by tlourey** [MicrosoftDocs/OfficeDocs-Exchange#2570]
Previous message trace in SCC had a submit message button (when doing an online search and not request for report). See below. 

![image](https://user-images.githubusercontent.com/9435779/115344631-018adc80-a1f1-11eb-9e80-28e135e62a59.png)

This allowed you to put message quickly into submission for review / analysis. 

Message trace in EAC doesn't have that. It should be added.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by tlourey** [comment]
It's not an issue in my tenant or the docs, its feedback for the product (new EAC) - feature needs to be added. Docs lead me here. Please let me know where the correct place is for feedback of new EAC
