### ISSUE TITLE
Broken link: /en-us/ was added but then removed

### ISSUE THREAD

**Issue by gcaringal** [MicrosoftDocs/OfficeDocs-Exchange#2571]
Hi there,
Issue #1972 was fixed by changing the URL (and including '/en-us/'), but this change was not included in the subsequent commit 0a345704aca4ee8a21bdf99f1864953d52a89902. So now, when it's clicked, the link doesn't work in other localizations just as the note says in PR #1981.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeec798c-00f4-df45-da44-47e5aac06ff9
* Version Independent ID: 4cdfab74-fce7-f298-c3df-51da100c2162
* Content: [Account setup with modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@gcaringal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@Reeced40

**Comment by Reeced40** [comment]
@gcaringal thank you for pointing this out and helping improve MS Docs. Are you suggesting adding the en-us again to the link?

**Comment by gcaringal** [comment]
> @gcaringal thank you for pointing this out and helping improve MS Docs. Are you suggesting adding the en-us again to the link?

@Reeced40 Yes, that's my suggestion. Otherwise, users will be forwarded to a broken link.

**Comment by Reeced40** [comment]
@scanum this can be closed thank you.
