### ISSUE TITLE
Is this article still relevant since exchangeUM no longer exist in ExchangeOnline ? 

### ISSUE THREAD

**Issue by richardojel** [MicrosoftDocs/OfficeDocs-Exchange#2573]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee09d6b4-3996-741f-006e-0b474932a657
* Version Independent ID: 7977f7aa-3240-1242-5f79-06dee6f8e75e
* Content: [UM mailbox policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-voice-mail/um-mailbox-policies)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-voice-mail/um-mailbox-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-voice-mail/um-mailbox-policies.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
