### ISSUE TITLE
We shouldn't need an onprem exchange server alongside AD Connect 

### ISSUE THREAD

**Issue by vin-cheesel** [MicrosoftDocs/OfficeDocs-Exchange#2579]
For smaller clients who want the added benefit of directory and password sync  - AD Connect is the best option.
I'm disappointed how Microsoft still recommend a local exchange server when using AD connect for a base exchange setup - especially after all the recent Exchange vulnerabilities. As an MSP - we have to deal with many clients who want password sync and to not worry about the extra management that follows with an exchange server (which was supposed to be one of the benefits of moving to M365 in the first place. I've called Microsoft support in the past and they've helped me decommission an exchange server while leaving AD connect in sync. 

It wouldn't be too difficult to create a tool or incorporate within AD connect to manage scenarios where on-prem attribute editing is required.

Please review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
