### ISSUE TITLE
Only valid for the classic Exchange management web

### ISSUE THREAD

**Issue by PerEdner** [MicrosoftDocs/OfficeDocs-Exchange#2582]
Hi,
You should make it clear that this guide is for the classic Exchange admin center. Otherwise I as a customer will not find what I are looking for and that creates ill will towards you.
Best regards
Per

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488ecf85-5f6d-3abd-4253-8527b5082340
* Version Independent ID: ec414c0f-4ee4-bbd1-3851-3e4db0c97593
* Content: [Shared mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@PerEdner Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @PerEdner thanks for your feedback, I am looking into this.
