### ISSUE TITLE
CSP issue when a HTTPS link used for Company Logo

### ISSUE THREAD

**Issue by BristolITDave** [MicrosoftDocs/OfficeDocs-Exchange#2584]
When loading:
https://admin.exchange.microsoft.com/#/homepage
If you have setup your O365 theme to link to your corporate website to get your logo - the CSP directive on this page will not allow your logo to load, and it will cause a broken image, looking rather unprofessional.
Note that this is fine in the old ECP.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
