### ISSUE TITLE
TLS 1.2 now seems to be mandatory for Direct Send (option 2)

### ISSUE THREAD

**Issue by DeTetlow** [MicrosoftDocs/OfficeDocs-Exchange#2585]
Presumably as per the general notice:
https://docs.microsoft.com/en-US/microsoft-365/compliance/prepare-tls-1.2-in-office-365?view=o365-worldwide

And in practice I can no longer use Direct Send unless I specifically use TLS 1.2. As your page says that Direct Send is the best option to use if your appliance doesn't support TLS 1.2, this is now incredibly misleading.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
