### ISSUE TITLE
New Exchange Admin Center Staged Migration not working

### ISSUE THREAD

**Issue by AndreasRogge** [MicrosoftDocs/OfficeDocs-Exchange#2586]
Hello,

when you try to use staged migration in new Exchange Admin Center you have to choose a "Target delivery domain":
![image](https://user-images.githubusercontent.com/2961807/116847969-eace8780-abeb-11eb-8d02-c24908e9936e.png)
![image](https://user-images.githubusercontent.com/2961807/116847991-f91ca380-abeb-11eb-9353-4f95a2214711.png)

But at the end you get an error:
![image](https://user-images.githubusercontent.com/2961807/116848036-0b96dd00-abec-11eb-887e-0d037ec097a7.png)

"The 'TargetDeliveryDomain' parameter isn't supported for migrations using the 'ExchangeOutlookAnywhere' protocol."

Please fix this issue because I cannot use new admin center with staged migration.

Thanks in advance.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
