### ISSUE TITLE
Removing Additional Hybrid Agents

### ISSUE THREAD

**Issue by LukeAllinson-NS** [MicrosoftDocs/OfficeDocs-Exchange#2592]
Hello,

Can I ask for some additional clarification/steps related to removing additional Hybrid Agents please?

I have a customer where a new Exchange 2016 server has been installed in a different datacentre as the existing server was owned by their previous supplier. The Hybrid Agent has been successfully installed onto the new server and the "Get-HybridAgent" command returns both instances.
I am now in the process of decommissioning the old server but the instructions on this page do not tell me how to remove the Hybrid Agent from the old server (and more importantly, de-register it in Azure).

The documented steps to remove the Hybrid Agent appear to assume there is a single agent and that we are switching from "Modern" Hybrid back to "Classic" Hybrid. Obviously in my current situation this is not applicable, It is odd that the documentation provides 2 methods to add additional Agents (i.e. HCW or manual install) but nothing about removing those additional agents.

Since there is no option to remove Agents within the HCW (other than the above method of switching back to "Classic" hybrid), I have removed the Agent from the old server before decommissioning using "Programs and Features", however the Agent still persists when running the "Get-HybridAgent" command (albeit now in an "inactive" state).

I note that in the Hybrid Agent installation folder (default C:\Program Files\Microsoft Hybrid Service) there is a "RegisterConnector.ps1" script which runs an additional command "Register-AppProxyConnector"; I assume that this is run at the end of the installation. I note that the "Unregister-AppProxyConnector" command does exist, but I am unsure of the parameters to pass and obviously I don't want to run this in a customers' production environment without some official documentation. Is this even necessary (see below)?

The following discussion (https://docs.microsoft.com/en-us/answers/questions/58815/azure-ad-application-proxy-1.html) is related to Azure AD Application Proxy connectors, but seems to suggest that inactive connectors are removed after 10 days. Since the Exchange Hybrid Agent is based on these Azure AD Application Proxy connectors, is this also true for them?

Many thanks in advance,
Luke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by get-itips** [comment]
Hello @LukeAllinson-NS how are you? Hope you are doing good 👍 
First of all, thanks for your feedback and also sorry for the late response.
While I try to reproduce to see if we have to impact the article, as some time has passed since your connector has been marked as inactive, was it removed automatically after 10 days? Found information that backed that also in Docs:

> You don't have to manually delete connectors that are unused. When a connector is running, it remains active as it connects to the service. Unused connectors are tagged as inactive and are removed after 10 days of inactivity. If you do want to uninstall a connector, though, uninstall both the Connector service and the Updater service from the server. Restart your computer to fully remove the service.

Source https://docs.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-connectors

Thank you
