### ISSUE TITLE
Add Warning/Info about System messages with "<tenant>onmicrosoft.com" and Centralized Mail Transport issues 

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-Exchange#2594]
The last section "Route Internet-bound messages from Exchange Online through your on-premises organization (Centralized mail transport enabled)" is a good descrption but it misses a special case.
Other Services like teams/groups  are sending messages a "<identity>@<tenantname>.onmicrosoft.com" or "<identity>@<tenantname>.mail.onmicrosoft.com". These messages are routed via OnPremises to the internet. Problem here: The OnPrem services are not authorized to send messages with that domain (mainly SPF) and so these message are not reliable. 

We should add a warning here about such messages. (I'm not aware, that teams will ignore the "Centralized mail transport setting" :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b002f0ce-5397-15cb-4c60-0eaaa87aaf52
* Version Independent ID: 32e3a594-2d2c-9f8a-9a38-e60e3ffaae85
* Content: [Transport routing in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/transport-routing)
* Content Source: [Exchange/ExchangeHybrid/transport-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/transport-routing.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by get-itips** [comment]
Hello @FrankCarius Frank, how are you? Hope you are doing good.
Thanks for your feedback.
I am trying to reproduce to add this to the article, would you be so kind in giving me more details in which situations you identified the messages from teams/groups are being sent as those addresses?
I appreciate it,
Thank you

**Comment by FrankCarius** [comment]
Oh long lime :-)  Simply configure a Exchange OnPremises and Exchange Online Tenant with Centalized mail transport. To the online Tenants is hidden behind the onpremises deployment. MX-Record points to Exchange OnPremises and is forwarding messages to the Exchange Online recipients.  (and EXo Users send outgoing messages via the onpremises system.
The onPremises System has an OnPremises SpamFilter which checks SPF. 

Now use one of the cloud Services (Like SharePoint notifications), which are sending messages "on behalf "of the user. I have seen messages in may, which did not pass the OnPrem Spamfilter, because they were not routet through the hybrid connector. They were routet via the MX-Record and the Spamfilter handles them as not trusted.
It does not affect exchange online senders like shared Mailboxes or rooms.  Only other services. 
I tried to find a sample message but was not successful for now.  I will try to reproduce it. But it looks like some services has changed their behavior. I'll check that with a customers, who still has Centralized Mailrouting active. Stay tuned
Frank
