### ISSUE TITLE
How are archives really handled and processed?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/OfficeDocs-Exchange#2598]
Please Elaborate more on how different forms of archive files (.zip, .rar, .gz, .7z etc.) har handled and processed.

For content inspection it clearly say that the inspection of the content is done on the content of the files included in the archive, but but there is no info on how achieves har handled and processed for the other types of conditions you can apply for an attachment.

For example:

1. If you use the "Any attachment's file name matches..." condition, is then the condition matched with the file name of the archive file or the file names within the archive, or perhaps both to the archive file name and to filenames in the archive?
2. It say that "... only the first 1 megabyte (MB) of text extracted from an attachment is inspected.", does that mean that all you have to do to bypass the inspection is to include a 1MB dummy text document as the first file in an archive, and then none of the text in any other file in the archive would be inspected?
3. For the condition "size is greater than or equal to" it say that it is applied to individual attachments. Is an archive file an "individual attachment"? Could you circumvent this condition by adding an attachment to an archive and then split the archive into, lets say, 128 bytes files (or just split it up without putting it in an archive)?
4. Word and other Office document are also archives. What about files in a zip-file inside a word document? Or a document in an embedded (OLE2 Object Linking and Embedding) Excel sheet in a word document?

Those where just examples, there are many more issues in the article where it is not clear how an archive is handled (what about archives in archives?)

I suggest you start the article with a flowchart where ,you show how the processing works in detail. The flowchart should deal with nested files, archives split into parts and which files/data the different conditions are applied to.

Those users who have access to the most sensitive information is also in many cases the users with most technical knowledge, so unless we should only be able to check attachments from people without technical knowledge it seems like this feature/functionality needs some improvements.

Basic checks like if stuff is nested in strange ways, or if there are very many small attachments etc.

In a few hours I could easily write a small application that takes any file as input and produce a zip-archive where the filenames of the files in the archive is used to encode the data from the original file. Or I could use the length of files to encode data, or the created and modified date of the files, or the use and position of capital letters in the file names...the possibilities are endless, so there need to be a way to detect things that seem strange and not normal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd230cd-1717-a932-a5c9-02db4f1b050c
* Version Independent ID: 24dcb706-d0d9-61d3-e99d-289db401ffaa
* Content: [Use mail flow rules to inspect message attachments in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/inspect-message-attachments)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @Bartolomeus-649, thank you for your feedback.

@Benny-54 could you kindly help here? I cannot provide this detailed information. Thanks!

**Comment by Benny-54** [comment]
Hi @Swatyario could you please look into this? Thank you.

**Comment by dariomws** [comment]
Hi @Swatyario could you please look into this? Thank you.

**Comment by Swatyario** [comment]
Adding @Joanne ***@***.***> to help us here.


Thanks and kind regards,

Aditya Mukund
Program Manager
EAC & EXO Manageability
Stay safe, stay healthy, stay fit!
________________________________

**Comment by JoanneHendrickson** [comment]
Researching.

**Comment by dariomws** [comment]
@JoanneHendrickson do you have any updates here? Thanks!

**Comment by JoanneHendrickson** [comment]
Thank you for this suggestion!  We will include it in our content planning discussions.
