### ISSUE TITLE
Confusing documentation on "Enable or disable authenticated client SMTP submission (SMTP AUTH) in Exchange Online"

### ISSUE THREAD

**Issue by maitra** [MicrosoftDocs/OfficeDocs-Exchange#2599]
According to the documentation as currently written, 
`
If your authentication policy disables basic authentication for SMTP, clients cannot use the SMTP AUTH protocol even if you enable the settings outlined in this article. For more information, see Disable Basic authentication in Exchange Online.
`
But then, later on, we have instructions on how to `Enable modern AUTH for SMTP `for specific mailboxes -- this seems very confusing. Why would we have a section on how to enable modern authentication for specific mailboxes if the weaker basic AUTH is disabled organization-wide and that automatically means that modern AUTH cannot be enabled for specific mailboxes. This seems very confusing and one of the statements needs more clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f463d2b-dfa3-1061-4e34-01fdfd8b5032
* Version Independent ID: a1d6d284-1c4c-438d-caaa-b06f7a7fb8a8
* Content: [Enable or disable SMTP AUTH](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission#enable-smtp-auth-for-specific-mailboxes)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @maitra, thank you for your feedback.

That note was added to prevent readers from using the steps detailed in this article if their authentication policy disables basic authentication for SMTP.
