### ISSUE TITLE
Confirming default authentication policy was applied to users

### ISSUE THREAD

**Issue by greendx** [MicrosoftDocs/OfficeDocs-Exchange#2605]
[Enter feedback here]

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online

Can you please clarify expected behavior when configuring default authentication policy to block all basic authentication methods following example in this document: **Set-OrganizationConfig -DefaultAuthenticationPolicy "Block Basic Auth"**

Specifically, when doing this and then looking up an individual user via **Get-User -Identity first.last@yourdomain.com | select authen** that is otherwise not assigned to any authentication policy and should now be assigned default authentication policy, are you supposed to see: 

Blank under AuthenticationPolicy?

AuthenticationPolicy
--------------------
![image](https://user-images.githubusercontent.com/35792006/118053955-71553880-b353-11eb-8c26-a40b35a29a5d.png)

OR default policy name under AuthenticationPolicy?

AuthenticationPolicy
--------------------
Block Basic Auth

![image](https://user-images.githubusercontent.com/35792006/118053976-7adea080-b353-11eb-8d10-71fef4ba824b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#create-and-apply-authentication-policies)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@greendx Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @greendx how are you?
You will see a value in AuthenticationPolicy whenever a specific policy is applied to the user, if blank, the default is the one applied (if any)
Hope this information helps you.

**Comment by greendx** [comment]
Hi @get-itips

Has anyone else requested that this change and when looking up a user their assigned policy is displayed regardless of how it was assigned, directly or indirectly? If not, I'd like to be the first.

Also would it be possible to update the documentation to say something like: 

- When you set a default policy at org level any user that is not assigned a policy will be added to it. However, default policy name will not be displayed for each user automatically assigned to the policy.
- Adding user to the default policy takes up to 24 hours and can be expedited via Set-User -Identity first.last@yourcompany.com -STSRefreshTokensValidFrom $([System.DateTime]::UtcNow)

**Comment by get-itips** [comment]
Hello @greendx how are you?

> Has anyone else requested that this change and when looking up a user their assigned policy is displayed regardless of how it was assigned, directly or indirectly? If not, I'd like to be the first.

I am afraid I can only be of help with documentation issues, not feature requests. I can redirect you to this [other resource](https://support.microsoft.com/en-us/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a) for that. 

> When you set a default policy at org level any user that is not assigned a policy will be added to it. However, default policy name will not be displayed for each user automatically assigned to the policy.

If I am not mistaken, this is the default behavior for every solution as it is inherited from PowerShell. I am not fully convinced of adding this to the article but will propose it and let's see if it gets approval.

> Adding user to the default policy takes up to 24 hours and can be expedited via Set-User -Identity first.last@yourcompany.com -STSRefreshTokensValidFrom $([System.DateTime]::UtcNow)

This is already in the article.

Thank you
