### ISSUE TITLE
Its regarding Recoverable Items folder quota limit. Two different statement is written in two different place.

### ISSUE THREAD

**Issue by Amartya-Karan** [MicrosoftDocs/OfficeDocs-Exchange#2608]
https://docs.microsoft.com/en-us/exchange/policy-and-compliance/recoverable-items-folder/recoverable-items-folder?view=exchserver-2019#recoverable-items-mailbox-quotas
Here its is mentioned - **When an item is moved to the Recoverable Items folder, its size is deducted from the mailbox quota and added to the size of the Recoverable Items folder**.

https://docs.microsoft.com/en-us/exchange/policy-and-compliance/holds/litigation-holds?view=exchserver-2019#:~:text=When%20you%20place%20a%20mailbox,eDiscovery%20in%20Exchange%20Server%20search.
here it's written - **The Recoverable Items folder has its own storage limit, so items in the folder don't count towards the mailbox storage limit.**

So, which one is actually true?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbbc82b-b1c8-f2b7-9f57-9fa9137305a3
* Version Independent ID: f1ce321a-ed5e-fe57-450d-35cc7b104350
* Content: [Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/recoverable-items-folder.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@Amartya-Karan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Amartya-Karan, thank you for your feedback.

I think both sentences are saying the same using different words.

Maybe the first sentence is confusing for you, but in other words:
"If you move an item to the Recoverable Items folder, this will reduce the size for the mailbox quote and increase it for the Recoverable Items folder."
