### ISSUE TITLE
Build Numbers - Appear out of date 11/5/2018

### ISSUE THREAD

**Issue by brink668** [MicrosoftDocs/OfficeDocs-Exchange#261]
Missing 2010 RU23 & RU24
https://support.microsoft.com/en-us/help/4458321/update-rollup-24-for-exchange-server-2010-service-pack-3

Are you also missing for Exchange 2013 and Exchange 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf984bf-df1c-bcd5-6475-54b9ef24fe74
* Version Independent ID: 00547ab9-7b3b-f6b0-fa7f-429f5e2bea56
* Content: [Exchange Server build numbers and release dates](https://docs.microsoft.com/en-us/Exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@brink668 Exchange 2010 has been fixed. I'm pretty sure 2013 is accurate (CU21 is latest). 2016 now has CU11.

Thanks for the feedback.
