### ISSUE TITLE
Online meetings add-in in Outlook for iOS cannnot shown

### ISSUE THREAD

**Issue by jean-wujingyi** [MicrosoftDocs/OfficeDocs-Exchange#2610]
I wanna set up moblie add-in for outlook to create online meetings. But this add-in could only be shown on Android, how could I enable our addin on IOS?
According to the article: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting , mobile add-in is supported on IOS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e6be4a-8597-5129-7b8f-de44d2026bae
* Version Independent ID: 5292ca3c-1c6f-09e2-5347-716bb46ee1b8
* Content: [Using third-party add-ins for online meetings in Outlook for iOS and Android](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/online-meeting-add-ins-for-ios-and-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/online-meeting-add-ins-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/online-meeting-add-ins-for-ios-and-android.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
