### ISSUE TITLE
Litigation hold "report" is not a "REPORT"

### ISSUE THREAD

**Issue by LittleJoeVA** [MicrosoftDocs/OfficeDocs-Exchange#2611]
For the MS docs page below, I'm directed to Github to give feedback.
https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/per-mailbox-litigation-hold-report#use-the-eac-to-run-a-litigation-hold-report

The above feature is NOT a true "report." A true report is something you can download and export. I want ability to actually run and export reports of users that are on, or off of Litigation hold; when then went on hold; the duration; who placed them on hold; when lithold expired (or expires), etc.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
