### ISSUE TITLE
Query policy

### ISSUE THREAD

**Issue by rdiazel** [MicrosoftDocs/OfficeDocs-Exchange#262]
Hi Chris. I went through everything and when using Authentication policy as a filter, to view all users in the policy, it throws an empty result. I can query users and use different filters to view the policy applied to them one by one, but I cannot filter by Authentication policy. In my test I created a policy named "disable legacy" and here are the results.

Users are part of a AD group named "developers"

PS &gt; Get-User -filter {(Title -eq 'developers')} | select -Property name

Name               
----               
***stuserB        
******e registration
****rigal       

I can view all their properties and filter based on them, but if I try to filter using the property 'Authenticationpolicy' it wont show anything

&gt; Get-User -filter {(AuthenticationPolicy -eq 'disable legacy')}
&gt;
Another example
&gt; Get-User -filter {(Title -eq 'developers')} | select -Property authenticat*

AuthenticationPolicy
--------------------
disable legacy      
disable legacy      
disable legacy      

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Product: **office-online**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rdiazel the fundamental lesson I learned when writing the topic about the [Filter](https://docs.microsoft.com//powershell/exchange/exchange-server/recipient-filters/filter-properties) parameter for on-premises Exchange Server: use the distinguished name (DN) of the object. Other unique values like Name, Alias, EmailAddress, etc. that _should_ work don't.

So, run the command:

```
Get-AuthenticationPolicy | Format-List Name,DistinguishedName
``

And then use the DN value for the filter:

```
Get-User -filter {AuthenticationPolicy -eq '<DN of Disable Legacy auth policy>'}
```

I tested this in my own environment and it worked: the Name value of the authentication policy returned no error but a blank result; the DistinguishedName value of the authentication policy returned the users who had it assigned to them.

**Comment by rdiazel** [comment]
Thanks a lot. It worked.
