### ISSUE TITLE
Covering "omicrosoft.com" Sender domain with centralized mailrouting

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-Exchange#2622]
Hello,

The page is well written and easy to understand. It also makes clear, how "centralized Mailrouting works". Thanks.

But it is missing one big issue with centralized mailrouting. There can be senders on ExchangeOnline, using a Adddress with the Domain "<tenantname>.onmicrosoft.com". Microsoft teams are sending such messages, if a channel meeting invitation is sent.
This messages are also handled via centralized mailrouting and routed via the OnPrem systems to the internet.

Issue::  The onprem systems cannot be added to the SPF-Record of "<tenantname>.onmicrosoft.com" and delivery to external people (like guests) is blocked (if they are not checking DKIM/DMARC, too)
I have found no way to exclude this messages from centralized Mailrouting.

Th solution for teams ist eas: change the teams primarySMTPAddress (unified Group). But it might affect other senders still using a <tenantname>.onmicrosoft.com-Address.
Maybe this is worth to add a information section about handling "<tenantname>.onmicrosoft.com" with "Centralized Mail Routing.

Frank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b002f0ce-5397-15cb-4c60-0eaaa87aaf52
* Version Independent ID: 32e3a594-2d2c-9f8a-9a38-e60e3ffaae85
* Content: [Transport routing in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/transport-routing)
* Content Source: [Exchange/ExchangeHybrid/transport-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/transport-routing.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@FrankCarius Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
