### ISSUE TITLE
Mail flow should be clearer

### ISSUE THREAD

**Issue by FaffeF** [MicrosoftDocs/OfficeDocs-Exchange#2625]
It would be helpful if certain scenarios are explained.

What happens if there is a "Bob@contoso.com" in both on-prem and M365, when sending and receiving mail?

What happens if bob tries to send mail from on-prem when residing in M365?

What happens when receiving mail for an account that doesn't exist on any server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc74a5d-5f48-0d14-d80b-d654dd33c934
* Version Independent ID: 2eb3f77f-f4e2-03c9-9bb2-e108aadce39f
* Content: [Configure mail flow using connectors](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
