### ISSUE TITLE
Link broken - Transport routing in Exchange hybrid deployments

### ISSUE THREAD

**Issue by NeilPetersen** [MicrosoftDocs/OfficeDocs-Exchange#2627]
The 'Transport routing in Exchange hybrid deployments' link is currently pointing to 'Sensitive information type entity definitions'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05dac701-d68c-429a-4d10-725272b1645c
* Version Independent ID: 75d81a52-02ad-fa6f-a4d8-76a15d4d737b
* Content: [Transport options in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/transport-options)
* Content Source: [Exchange/ExchangeHybrid/transport-options.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/transport-options.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@NeilPetersen Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
