### ISSUE TITLE
OAB gen schedule

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#263]
Please add OAB generation schedule in Exchange Online.
In Exchange 2016/2019 it's by default 8 hours.

https://github.com/MicrosoftDocs/OfficeDocs-Exchange/edit/public/Exchange/ExchangeOnline/address-books/offline-address-books/offline-address-books.md

**Comment by chrisda** [comment]
@trudolf-msft it appears you added this yourself in PR #272, so I'm closing this issue.
