### ISSUE TITLE
API missing from intrstruction

### ISSUE THREAD

**Issue by SPilcher86** [MicrosoftDocs/OfficeDocs-Exchange#2630]
Under the section for Enable API usage in project, People API need to be added into that list as well. I am going through a migration right now and received a failure notice saying that the People API was disabled. When I looked into the APIs on the Google Dev Console, it was in fact disabled. I did a resync after enabling the API, and now all of the mailboxes that were in a failed migration status are now in a Synced state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#grant-access-to-the-service-account-for-your-google-tenant)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@SPilcher86 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
