### ISSUE TITLE
Document Update Request |  New EAC does not support Client Access Rule  (ExchangeAdminCenter) Protocol

### ISSUE THREAD

**Issue by qaehtesh** [MicrosoftDocs/OfficeDocs-Exchange#2636]
New EAC does not support Client Access Rule  (ExchangeAdminCenter) Protocol. Thus IP restriction etc by CAR which works with Classic EAC will be bypassed in New EAC. The feature is planned to be added in future however meanwhile the comparison document for EAC needs to be updated to reflect this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05fe1b-9603-8917-d02b-e41218a97920
* Version Independent ID: ed98f261-9010-60f8-4066-2d254ff1aad7
* Content: [Differences between the Classic admin center (Classic EAC) to the new admin center (new EAC)](https://docs.microsoft.com/en-us/exchange/changes-in-exchange-admin-center)
* Content Source: [Exchange/ExchangeOnline/changes-in-exchange-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/changes-in-exchange-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by scanum** [comment]
@officedocspr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @qaehtesh how are you?
I could successfully verify what you mention, thank you!
As the article you opened the issue for is intended more to visual differences, I will update this other article https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/procedures-for-client-access-rules adding a note to clarify that applies to classic EAC.
Thank you!

**Comment by qaehtesh** [comment]
Thank you Andres, that will work. Let me know once PR is complete and this is updated.

Regards,
Qazi

**Comment by qaehtesh** [comment]
Hi Andres,
I looked at the updated documentation however it still does not highlight that this is Classic only and will not work in modern EAC.

I assuming this is the updated comment, however this only indicate this could be setup for Classic EAC however does not bring out the fact modern EAC will not work.
This example creates a new Client Access Rule named Restrict EAC Access that blocks access for the Classic Exchange admin center,
Procedures for Client Access Rules in Exchange Online | Microsoft Docs<https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/procedures-for-client-access-rules>


Regards,
Qazi
