### ISSUE TITLE
Why can't we delete more than 10 emails using new-compliancesearcaction

### ISSUE THREAD

**Issue by mangadala** [MicrosoftDocs/OfficeDocs-Exchange#2638]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c21112a-deb5-83b3-160e-0149a1e510f6
* Version Independent ID: 4edc9fcd-4971-470b-c56e-e1a2e78b8854
* Content: [Clean up or delete items from the Recoverable Items folder in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/recoverable-items-folder/clean-up-deleted-items)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/recoverable-items-folder/clean-up-deleted-items.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@mangadala Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
