### ISSUE TITLE
Japanese translation is not accurate

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-Exchange#264]
[フィードバックをこちらに入力してください]
Japanese translation is not accurate for the following part.
It would be appreciated if you could change the current to expected one.

<English>
A soft-deleted user mailbox is a mailbox that has been deleted using the Office 365 admin center or the Remove-Mailbox cmdlet in Exchange Online PowerShell, and has still been in the Azure active directory (Azure AD) recycle bin for less than 30 days.

<Current>
ソフト削除されたユーザーのメールボックスは、メールボックスを PowerShell を使用して Office 365 の管理者センターか、またはリンクの削除されたメールボックスExchange オンライン、削除されており、まだされて Azure active directory (AD の Azure) のごみ箱で 30 日以内です。
<Expected>
ソフト削除されたユーザーのメールボックスとは、Office 365 の管理者センターを使用して削除されたか、または　Exchange Online PowerShell のRemove-Mailbox コマンドレットを使用し削除されたもので、かつ Azure active directory (Azure AD)  のごみ箱に移動してから30日以内のものを指します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: eff7fa9f-2dec-34c3-e4b3-53614755499f
* Version Independent ID: 61e856b9-12fb-bdf6-0f49-0f6cc8b4b957
* Content: [Exchange Online でユーザー メールボックスを削除または復元する](https://docs.microsoft.com/ja-jp/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by AndreaBarr** [comment]
@AkikoTsukahara Thank you for this feedback

I will get this information about the translation over to the Exchange team. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by OfficeGSX** [comment]
The suggested translation was implemented and is visible on the live site see the screenshot below. We have also uplifted the topic to HT since it was previously MT.

![image](https://user-images.githubusercontent.com/16706698/52122394-23551480-2623-11e9-8210-a870cb86602b.png)

Best regards,

Jiri

**Comment by OfficeGSX** [comment]
The article is HumanTranslated and published live
