### ISSUE TITLE
Perform a Google Workspace migration - use case

### ISSUE THREAD

**Issue by tibibaraboi** [MicrosoftDocs/OfficeDocs-Exchange#2643]
[Enter feedback here]

Hello,

In the *"Overview of the process section"* a distinction might be needed between empty tenants and existing O365 tenants with mailbox users . During merges companies using Google G Suite might need to migrate to existing O365 tenants having multiple users provisioned with mailboxes fro mother domains e.g. fabrikam.co.uk. 

In the provision users in **Microsoft 365 or Office 365** section additional steps are needed:

admin.microsoft.com --> add domain fabrikaminc.net, either skip DNS setttings, 
When we prove domain ownership it will add in EAC as accepted domain with Domain type=Authorative.

In EAC check if the domain fabrikaminc.net, is Authorative and  change the domain type from to InternalRelay
Without this change the mails from other O365 mail users in other domains will not reach the G Suite users to be migrated.

If the customer has AD connect synch with an onprem AD forest than we need to provision the MailUsers from fabrikaminc.net, only in AAD, let the migration batch to complete so users are changed to Mailbox users and just after that create the users on the onprem AD  paying attention to ensure consistency (soft / hard match). 

After the completion and the switch of MX record from Google to Microsoft O365 we can change in EAC the domain type to Authorative. 

Cleanup
Aliases in o365.fabrikamin.net can be deleted  (script to remove from  ProxyAddresses attribute smtp: user@o365.fabrikaminc.net ). 

Domain o365.fabrikam.net can be deleted from managed domain.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer Google Workspace (formerly G Suite) mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@tibibaraboi Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
