### ISSUE TITLE
Link not working on page

### ISSUE THREAD

**Issue by PratikD21** [MicrosoftDocs/OfficeDocs-Exchange#2647]
[Enter feedback here]
 MONTI application and accompanying documentation <Link Not Working>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce990e27-aa35-1c80-2d57-c07df2d35e88
* Version Independent ID: 78594f8e-6f98-21bd-4c68-be4facfade3e
* Content: [Migrate from Lotus Notes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-from-lotus-notes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-from-lotus-notes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@PratikD21 Thank you for submitting feedback and contributing to the docs. We are currently investigating this

**Comment by dariomws** [comment]
Hi @PratikD21, thank you for your feedback.

@Benny-54 could you kindly help me here to contact the right team? Thank you!

**Comment by Benny-54** [comment]
Hi @dariomws, please contact @JoanneHendrickson for this, thank you.

**Comment by dariomws** [comment]
@Benny-54 thank you!

@JoanneHendrickson could you kindly help me here? Thank you!

**Comment by dariomws** [comment]
Hi @JoanneHendrickson, could you please help here? Thank you!

**Comment by PratikD21** [comment]
Hi, Team,

Any update on this?

Thanks,
Pratik Darak

**Comment by JoanneHendrickson** [comment]
Working to get this content restored to the download center -- it isn't just because it is a broken link.  Recent security updates on the Download Center, including retiring expired downloads, may have caused this.

**Comment by JoanneHendrickson** [comment]
This link is now functioning again.

**Comment by dariomws** [comment]
Thanks a lot @JoanneHendrickson!

@scanum could you kindly close this issue? Thanks!

**Comment by dariomws** [comment]
@scanum could you kindly close this issue? Thanks!
