### ISSUE TITLE
Japanese translation is not accurate.

### ISSUE THREAD

**Issue by AkikoTsukahara** [MicrosoftDocs/OfficeDocs-Exchange#265]
[Enter feedback here]
Japanese translation is not accurate for the following part.
It would be appreciated if you could change the current one to expected one.

<English>
If you run the Azure cmdlet Remove-MsolUser with the -RemoveFromRecycleBin parameter in order to remove a user from the Azure AD recycle bin, it will always put an existing Exchange Online mailbox associated with the Azure AD user in a soft-deleted state, as long as the user's license was not removed. However, if you remove the user's license prior to removing the user from the recycle bin, the user will not go into a soft-deleted user mailbox state.

<Current>
Azure コマンドレットを実行する場合はRemove-MsolUserで、 -RemoveFromRecycleBin 、Azure AD のごみ箱からユーザーを削除するのにはパラメーター ユーザーのライセンスがある限り、常にソフト削除された状態では、Azure AD ユーザーに関連付けられている既存の Exchange Online メールボックスを配置してはありませんが削除されます。ただし、ごみ箱からユーザーを削除する前にユーザーのライセンスを削除する場合ユーザーがソフト削除されたユーザーのメールボックスの状態に移動できません。
<Expected>
Azure ADのごみ箱からユーザーを削除する目的で　Azure コマンドレットの　Remove-MsolUser　を　-RemoveFromRecycleBin　パラメーター付きで実行する場合、ユーザーのライセンスを削除しない限り、 Azure AD　ユーザーに関連付けられた Exchange Online のメールボックスは常にソフト削除の状態になります。ただし、ゴミ箱からユーザーを削除する前にユーザーのライセンスを削除した場合、そのユーザーのメールボックスはソフト削除の状態にはなりません。

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff7fa9f-2dec-34c3-e4b3-53614755499f
* Version Independent ID: 61e856b9-12fb-bdf6-0f49-0f6cc8b4b957
* Content: [Delete or restore user mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by OfficeGSX** [comment]
Hello,

The translation was updated and the reported string is no longer present in the article. This is not repro.

Best regards,

Jiri

**Comment by OfficeGSX** [comment]
The article is HumanTranslated and published live
