### ISSUE TITLE
mention which kind of services will support SmtpClientAuthenticationDisabled 

### ISSUE THREAD

**Issue by alanlivio** [MicrosoftDocs/OfficeDocs-Exchange#2650]
[Enter feedback here]
It is interesting say witch kind of services benefits from this tutorial.
I understand, for instance, that it helps Gmail web client access Exchange Online mail.
Best,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f463d2b-dfa3-1061-4e34-01fdfd8b5032
* Version Independent ID: a1d6d284-1c4c-438d-caaa-b06f7a7fb8a8
* Content: [Enable or disable SMTP AUTH](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@alanlivio Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
