### ISSUE TITLE
Problem using cutover migration wizard. Need CSV

### ISSUE THREAD

**Issue by Tolle3000** [MicrosoftDocs/OfficeDocs-Exchange#2652]
During the migration wizard, I have selected 'Cutover Migration'. In later steps I have to upload a CSV file.

According to this article: "A cutover Exchange migration doesn't support using a CSV file because all on-premises user mailboxes are migrated to Microsoft 365 or Office 365 in a single batch.". 

Article says no need, wizard says need. Please correct page, or correct wizard.
I prefer correct wizard, because the text is clear. All mailboxes are migrated, so why upload a list?

Kind regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ab48543-ee14-846d-c52a-d63ed9ef74ba
* Version Independent ID: 117e5534-f05b-7def-1d0b-e494c6e7325e
* Content: [CSV files for mailbox migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/csv-files-for-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/csv-files-for-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/csv-files-for-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
