### ISSUE TITLE
Missing code https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-Exchange#2654]
Missing a DBEB response described in link below

https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking

If a message is sent to a valid email address in Microsoft 365 or Office 365, the message continues through the rest of the service filtering layers: anti-malware, anti-spam, and mail flow rules (also known as transport rules). If the address doesn't exist, the service blocks the message before filtering even occurs, and a non-delivery report (also known as an NDR or bounce message) is returned to the sender. The NDR looks like this: **550 5.4.1 Recipient address rejected: Access denied.**

550 5.4.1 should be added to the NDR response page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6d0e4-0ea5-f8a9-bf67-bf7cacc74b3e
* Version Independent ID: c72592d3-bfd1-ddf3-793f-dcc0374db074
* Content: [Email non-delivery reports in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @aldoug, thank you for your feedback.

I see the error code 5.4.1 in the table. It references the following article for more detail:
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-4-1-in-exchange-online

**Comment by aldoug** [comment]
Hi @dariomws  . Yep, but it doesn't mention it as a "550 5.4.1 Recipient address rejected: Access denied " (Directory based edge blocking) response... which will be a very common one

**Comment by dariomws** [comment]
@aldoug you are right, I'm adding another line for this NDR reponse.

**Comment by aldoug** [comment]
Nice one, cheers!

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
***@***.******@***.***>
Working hours: Monday - Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers ***@***.******@***.***>)
Team Manager | Frances Early ***@***.******@***.***>) +44 (0) 7876 657707

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via 'Support' (headset icon)/'View service requests'/'Ticket #' (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG
