### ISSUE TITLE
Request for clear statement to advise that running DirSync / AD Connect without an Exchange Server for Object Management is an unsupported scenario

### ISSUE THREAD

**Issue by aldoug** [MicrosoftDocs/OfficeDocs-Exchange#2655]
An MS Partner is requesting the above statement to be made clear on the page in question. Whilst I have shared the areas in the document where this is referenced (I believe, clearly) they believe these to be a 'grey area' and as such would like the document to state this clearly. Happy to discuss the requirement and circumstances leading to it in more detail if anyone needs to reach out

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@aldoug Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @aldoug Al, how are you? Hope you are doing great.

The article you opened the issue for has this statement that, to my opinion, clearly states the not supported scenario:

> The question of whether a third-party management tool or ADSIEDIT can be used is often asked. The answer is you can use them, **but they are not supported.** **The Exchange Management Console, the Exchange admin center (EAC), and the Exchange Management Shell are the only supported tools that are available to manage Exchange recipients and objects.** If you decide to use third-party management tools, it would be at your own risk. Third-party management tools often work fine, but Microsoft does not validate these tools.

Let me know if I understood you well,

Thank you

**Comment by aldoug** [comment]
Hi Andres

I understand that it states that those tools are needed to manage objects BUT the issue is that there is a belief out there that you don't necessarily need to manage the objects and therefore the Exchange Server is not required (and indeed, you can pretty much and it is only in a very specific set of circumstances that it will cause an issue). There are still lots of people out there deploying in this manner.

Happy to discuss the requirements behind this and the impact if you'd like to discuss further

Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
***@***.******@***.***>
Working hours: Monday - Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers ***@***.******@***.***>)
Team Manager | Frances Early ***@***.******@***.***>) +44 (0) 7876 657707

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via 'Support' (headset icon)/'View service requests'/'Ticket #' (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG

**Comment by get-itips** [comment]
Hello @aldoug Al, how are you? hope you are doing good!

> BUT the issue is that there is a belief out there that you don't necessarily need to manage the objects and therefore the Exchange Server is not required

quoting the article:

> When directory synchronization is enabled for a tenant and a user is synchronized from on-premises, most of the attributes cannot be managed from Exchange Online **and must be managed from on-premises**. This is not due to the hybrid configuration, but it occurs because of directory synchronization. In addition, even if you have directory synchronization in place without running the Hybrid Configuration Wizard, **you still cannot manage most of the recipient tasks from the cloud**.

To my understanding, that other extract from the article, clearly states that you need to do at least some management of objects, the discussion goes around if it is either on-premises or in the cloud, but -no management at all- it's not present on the table. Do you see the same as me?

Thank you

**Comment by aldoug** [comment]
Hi Andres. I do see your point, it’s more about the many  customers and consultant services carrying out deployments that don’t 😉 Basically, you can manage users on premises and provision mailboxes in the cloud without actually having to manage any attributes at all, you just license the users (it’s very common out there, believe me)

The only issue occurs in creating DLs. Unbeknown to those people creating groups on premises, the group in the cloud is created with insufficient attributes to populate the return path should it be required. Populating the return path of a DL is a recommendation (not a requirement) on our side, BUT it is a requirement if complex routing scenarios involving connectors and third party add on products (such as signature services) are  involved, it then causes problems. The reason behind this is the Exchange Attributes will be missing totally from on premises if Exchange is not present, so something to state that the Exchange Attributes must be present in the on premises side would be 100% clear.

Let me check with my on premises colleagues to see exactly what is required and I will come back to you



Alisdair Douglas
Support Escal Eng
Eq-Uk Gtsc Bizapps Server Customer Services and Support
Office: +44 (118) 9095190
***@***.******@***.***>
Working hours: Monday – Friday 08:00 - 16:30
[Microsoft Logo]
Backup | Jeroen Dronkers ***@***.******@***.***>)
Team Manager | Frances Early ***@***.******@***.***>) +44 (0) 7876 657707

Did you know? You can submit your feedback for this Support ticket from the Navigation menu in the Microsoft 365 admin center via ‘Support’ (headset icon)/‘View service requests’/‘Ticket #’ (see subject of this email).


This and subsequent emails on the same topic are for discussion and information purposes only. Only those matters set out in a fully executed agreement are legally binding. This email may contain confidential information and should not be shared with any third party without the prior written agreement of Microsoft. If you are not the intended recipient, take no action and contact the sender immediately.

Microsoft Limited (company number 01624297) is a company registered in England and Wales whose registered office is at Microsoft Campus, Thames Valley Park, Reading RG6 1WG
