### ISSUE TITLE
'Gmail filters' setting not covered

### ISSUE THREAD

**Issue by Kav7** [MicrosoftDocs/OfficeDocs-Exchange#2657]
Hi team,

There is a setting which does receive any coverage or mention in this article, here is a screenshot:
https://snipboard.io/YvopXj.jpg

The article says 'gmail filters' are not migrated, but setting relates to 'gmail filters', can you clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
I am looking into this, thank you

**Comment by get-itips** [comment]
Hello @Kav7 it was announced [today](https://techcommunity.microsoft.com/t5/exchange-team-blog/google-workspace-to-exchange-online-migrations-now-support-gmail/ba-p/2519358), and the article has already been updated. Thank you!
@scanum please close

**Comment by Kav7** [comment]
amazing, thank you!
