### ISSUE TITLE
Sync-ModernMailPublicFolders - "Connecting to remote server outlook.office365.com failed with the following error message : Access is denied.

### ISSUE THREAD

**Issue by trwagner1** [MicrosoftDocs/OfficeDocs-Exchange#2660]
I've been in a Microsoft Support call now for almost 6 weeks with no resolution.

When running Step 5:  https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-exchange-online?view=exchserver-2016

Item 1:  .\Sync-ModernMailPublicFolders.ps1 -Credential (Get-Credential) -CsvSummaryFile:sync_summary.csv

When using the Exchange Online "Organization Management" user, no MFA enabled, cloud only user, remote management shell enabled, the following error results:

InitializeExchangeOnlineRemoteSession : Unable to create a remote shell session to Exchange Online. The error is as
follows: "Connecting to remote server outlook.office365.com failed with the following error message : Access is
denied. For more information, see the about_Remote_Troubleshooting Help topic.".
At E:\EXO-Migration\Sync-ModernMailPublicFolders.ps1:506 char:5
+     InitializeExchangeOnlineRemoteSession;
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,InitializeExchangeOnlineRemoteSession

Exchange Online Management Shell v2 has been used as well as EMS with Exchange 2016 (Exchange Server 2016 CU20, March 16, 2021, 15.1.2242.4)  (Powershell version 5.1)

Logging in as the same account in the EXO admin console works fine, using Exchange Online Management Shell v2 to perform other tasks works just fine.  All the steps leading up to Step 5, item 1 worked just fine.  So, the account works with no issues, except when using the Sync-ModernMailPublicFolders.ps1 script.

So far, no solutions from Microsoft.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
