### ISSUE TITLE
Exchange Deployment Assistant gets a certificate error

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/OfficeDocs-Exchange#2661]
Hi team,

This is just a feedback that I have met with a certificate error when trying to open the Exchange Deployment Assistant via the link:https://assistants.microsoft.com/
Hope you can carefully check and resolve it.

**Error is** 
NET::ERR_CERT_REVOKED
**Detailed error is:**
assistants.microsoft.com uses encryption to protect your information. When Microsoft Edge tried to connect to assistants.microsoft.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be assistants.microsoft.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Microsoft Edge stopped the connection before any data was exchanged.

You can't visit assistants.microsoft.com right now because its certificate has been revoked. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
