### ISSUE TITLE
Plus addressing shows Mailtip error in Windows Outlook

### ISSUE THREAD

**Issue by martinek-stepan** [MicrosoftDocs/OfficeDocs-Exchange#2666]
Hi, I apologies if there is actual repository or proper place to report Mailtip bugs, I would be happy to report it there too. But for now I think documentation for plus addressing should mention this.

If you use plus within your domain Mailtip wont recognize the mailbox and shows error message that "mailbox is no longer valid". It is purely informational since the mail (event) can be sent and will be send to proper mailbox, but it is huge problem since we are getting big amount of user queries about this.

https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/b624bff857882563a86e42f0be1f8916fd65029c/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
