### ISSUE TITLE
Missing information on what happens when a license is removed but the user is not deleted.

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/OfficeDocs-Exchange#2667]
This page is not clear about what happens to a user / mailbox when a license is removed, but the user is not deleted. The page contains a section on this topic, but does not provide any information:	

> "For info on removing a license from a user in Microsoft 365 or Office 365 and Exchange Online, see **Delete a user from your organization**."

The page that the reader is directed to doesn't contain any additional/relevant information.

> "Note: If the Microsoft 365 or Office 365 or Exchange Online license is removed from a user, the user's mailbox is no longer searchable by using an eDiscovery tool such as Content Search or Advanced eDiscovery. For more information, see the "Searching disconnected or de-licensed mailboxes" section in Content Search."

	
The Content Search page doesn't contain a section "Searching disconnected or de-licensed mailboxes" any longer.

Please include information in this page on what happens when a license is removed. Is the mailbox retained but no longer accessible or is it deleted? In the latter case, it it recoverable? How? Is there a retention period after which it will be purged? Will the mailbox be restored automatically once the license is applied again. Will mail still be delivered into the mailbox?  ...

Also please fix the (description of the) links to additional information or remove them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff7fa9f-2dec-34c3-e4b3-53614755499f
* Version Independent ID: 61e856b9-12fb-bdf6-0f49-0f6cc8b4b957
* Content: [Delete or restore user mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @niderost, thank you for your feedback and help us to improve docs.microsoft.com.

When a license is removed from a user, Exchange online data that is associated with that account is held for 30 days. After the 30-day grace period, the data is deleted and can't be recovered.
You cannot search it using Get-Mailbox either restore it using Undo-SoftDeletedMailbox. You need to reassign the license.

I'll try to add this information to the article.
