### ISSUE TITLE
Testing - How do I know this worked?

### ISSUE THREAD

**Issue by QM-75** [MicrosoftDocs/OfficeDocs-Exchange#267]
As this article deals with on-premises access to public folders hosted in Exchange Online (EOL), should the testing include testing public folder access from Outlook for an on-premises mailbox? 
Also, should the testing include mail enabled public folders (MEPFs) for example, sending email to an MEPF from an external email address, and from an internal email address ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeeb3268-af97-fad5-1310-2265f2955d53
* Version Independent ID: 9cf5f8ac-3d50-2896-0380-42aaf9cadd58
* Content: [Configure Exchange Online public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@QM-75 Thank you for the inquiry. 

I am not sure how see if this has worked. I'll get this inquiry over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msdmaguire** [comment]
@Qm-75, I suggest starting with one or both of the "How Do I know This Worked?" sections in the following articles:
https://docs.microsoft.com/Exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders
https://docs.microsoft.com/Exchange/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders
