### ISSUE TITLE
Default anti-spam policies prevent forwarding

### ISSUE THREAD

**Issue by rscs** [MicrosoftDocs/OfficeDocs-Exchange#2671]
While a mailbox is being migrated, forwarding is enabled that points to the Google Workspace routing domain; however, users already on O365 will get an NDR if they try to email this mailbox because the new outbound spam policy defaults to not allowing forwarding.

`Remote Server returned '550 5.7.520 Access denied, Your organization does not allow external forwarding. Please contact your administrator for further assistance. AS(7555)'`

The migration guide should suggest to run the following or explain how to do it via the GUI:

Enable-OrganizationCustomization
Set-HostedOutboundSpamFilterPolicy -Identity Default -AutoForwardingMode on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#finalizing-your-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback @rscs

**Comment by get-itips** [comment]
@scanum please close
