### ISSUE TITLE
Adding a note concerning the default sender of notify messages from mail flow

### ISSUE THREAD

**Issue by Nicolas-Innocent** [MicrosoftDocs/OfficeDocs-Exchange#2674]
After some time investigating with the support [case 26271151], It appears that there is a quirk not indicated anywhere that might require a mention (maybe in the what else should I know in the bottom of the mail flow page.

If a rule sends a message (for exemple a notify rule (notify the sender the message was deleted for exemple), it uses the postmaster@domain.ext email to do so. But if the postmaster@ is defined as an alias, because O365 simplify the display by replacing aliases by primary email, the notification seems to come from the individual instead of an automated system. It seems completly logical now that I know, but it's never mentionned anywhere and there is no ability to change the defaut email (postmaster@). And since during my research, I found quite a few posts looking for an explanation, I feel it deserves to be written somewhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81c1119-165b-f408-698c-1092a781ba63
* Version Independent ID: 1a1b6d9a-a75c-e74d-ff84-ccbdf15091de
* Content: [Mail flow rules (transport rules) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @Nicolas-Innocent, thank you for your feedback and help us to improve docs.microsoft.com.

I couldn't understand. Could you kindly provide me with more detail about what you think we should add to the article? Thank you!

**Comment by Nicolas-Innocent** [comment]
So, Exchange will ALWAYS send notifications generated by rules from the postmaster@domain.ext (this is apparently harcoded and cannot be changed). If that address is defined as an alias, this means the notification will appear to lambda users to have been sent from that user.

exemple, I have a rule that blocks any mail incoming in our org with risky attachment (exe/cab/...), copy them to an external mailbox, and notify the recipient that he should contact the IT dept to retrieve the mail if it's important, and the sender that this email was blocked.

Because postmaster@... was an alias on my account, the sender outside our org. would receive a notification, seemingly from me, stating I blocked an email he sent. Which created unnecessary confusion.

I would add a note in the 'What else should I know?' section stating something like,
- Notifications generated by a mail flow rule may originate from the postmaster@yourdomain.ext address. If that address is an alias of an existing user, such notifications would appear to come from that user.

**Comment by dariomws** [comment]
@Nicolas-Innocent thank you so much for this new comment. Now I understand very well.

About the postmaster address, you can change it in Exchange Online:
https://docs.microsoft.com/exchange/mail-flow-best-practices/configure-external-postmaster-address

I've been testing this behaviour. I added postmaster@mydomain.com to a user account as a secondary email address (or alias), but I'm still getting the NDR from postmaster@mydomain.com with no information about the user account.
I'm not convinced to add this information to the article, but if you insist, I can test it again after a couple of hours and suggest an update to see if it gets approval.

**Comment by Nicolas-Innocent** [comment]
HI-

MS Support confirmed to us that you could change the postmaster address for most stuff (like NDR), but not for notification created by the mail flow rule itself, hence my request.
If they were wrong, (and the behavior during our testing does seem to agree with them), then I agree it wouldn't need to be mentionned.

rule in question :
![Sans titre](https://user-images.githubusercontent.com/72034321/124915571-fbd3b480-dff1-11eb-948d-8519583613cc.png)

and here is the received email (Hyperion being an exchange account to which the postmaster alias is attached)
![Sans titre2](https://user-images.githubusercontent.com/72034321/124916050-85838200-dff2-11eb-9216-b93243f86696.png)

**Comment by dariomws** [comment]
Thanks @Nicolas-Innocent, I understand even better after your last comment.

I've tried it on my demo tenant by adding postmaster to an account (Adele), and this is what I see with the default postmaster address:
![image](https://user-images.githubusercontent.com/33589238/124958840-e3c45b00-e01a-11eb-8020-6acc6510b106.png)

If I change the default postmaster address using Set-TransportConfig:
![image](https://user-images.githubusercontent.com/33589238/124958923-fccd0c00-e01a-11eb-88b6-5704f17755c9.png)
So it seems that the change has impacted the notification for this kind of mail flow rule.

If you add the postmaster address to an internal account, other internal accounts see the Display Name for the mail coming from that address. It's expected.

**Comment by Nicolas-Innocent** [comment]
hmmm, that would be what was expected yes, but not what was happening with our testing, 
I'm guessing that there was something else then, and that support took a shortcut.

As it's working as expected, I'm closing the ticket. Thanks for the test and sorry for the bother.

**Comment by dariomws** [comment]
@Nicolas-Innocent thank you for engaging with the community here for the docs. I appreciate and encourage you to do the same in the future also.
