### ISSUE TITLE
Could you replace newest operation in creating a group?

### ISSUE THREAD

**Issue by MiyukiAmino** [MicrosoftDocs/OfficeDocs-Exchange#2682]
about this doc:
https://docs.microsoft.com/en-us/exchange/recipients/mail-enabled-security-groups?view=exchserver-2019

------------
[ Use the EAC to create a mail-enabled security group ] section
------------
The operation described in the docs is too old, so cx is confusing.Could you replace newest operation? This page is useful for unfamiliar admistrators.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @MiyukiAmino, thank you for your feedback.

I've verified the steps, and they are accurate. Where did you see a mistake?

**Comment by MiyukiAmino** [comment]
Thanks @dariomws. I see there is current EAC operation in the docs. I need the steps in new exchange admin center.

![image](https://user-images.githubusercontent.com/84189892/125597123-0cc4554f-5e3d-4029-a46f-258b97923444.png)

**Comment by dariomws** [comment]
@MiyukiAmino I think the screenshot you are sharing is for the new EAC in Exchange Online. This article is for Exchange Server (on-premises).

**Comment by MiyukiAmino** [comment]
Oh...so sorry it's my misunderstanding. I found the docs I need.
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-enabled-security-groups

Thank you for your kindly help while you're busy, thank you so much.
