### ISSUE TITLE
"Data migration" doesn't exist on this page

### ISSUE THREAD

**Issue by harrysileoni** [MicrosoftDocs/OfficeDocs-Exchange#2683]
The documentation is extremely outdated! "Data migration" doesn't exist under Setup and hasn't  been there for a long time. It's always such a pain in the butt to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed16f16-09d6-ad84-7c01-50ef9232ced9
* Version Independent ID: e794838b-02fa-9dce-d7bb-f05c6145f047
* Content: [IMAP migration in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@harrysileoni Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @harrysileoni
