### ISSUE TITLE
Add section to require AADC sync

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#2684]
Customer raised the question why he needs a AADC sync for this!?
Technically I explained it but the article should reflect this requirement as well.

See https://techcommunity.microsoft.com/t5/exchange-team-blog/demystifying-hybrid-free-busy-what-are-the-moving-parts/ba-p/607704

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59be6f6e-75b7-68cc-e158-c22a7e2508a6
* Version Independent ID: 4dfeded2-fdb7-3f34-fb81-79d50f71b776
* Content: [Shared free/busy in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/shared-free-busy)
* Content Source: [Exchange/ExchangeHybrid/shared-free-busy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/shared-free-busy.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@trudolf-msft Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
