### ISSUE TITLE
Missing information on the actual settings

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-Exchange#2687]
This document mentions that web mailbox policies are available to apply settings, but there is no discussion of what the settings are.  The settings should be descried/explained here in this document or there should be a link to the document where that information exists.

Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458f1476-ddd9-d2cc-885c-256c50d7207c
* Version Independent ID: c816274c-2300-993b-1e01-ed85989c1ab7
* Content: [Create an Outlook on the web mailbox policy in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/create-outlook-web-app-mailbox-policy)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/create-outlook-web-app-mailbox-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/create-outlook-web-app-mailbox-policy.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@ssmiller60  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
