### ISSUE TITLE
You can't use EAC to delete or restore user mailboxes?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#2689]
The article says,
> You can't use EAC to delete or restore user mailboxes.

That isn't remotely accurate
Can you use the **new** exchange admin center to **delete** mailboxes? Yes
Can you use the **new** exchange admin center to **restore** mailboxes? No

Can you use the **classic** exchange admin center to **delete** mailboxes? Yes
Can you use the **classic** exchange admin center to **restore** mailboxes? Yes

Deleting is easy, click a mailbox, click delete. works in new and classic EAC
Restoring is easy too, click classic admin center > recipients > "..." (elipsis) > deleted mailboxes
Pick a mailbox, then click "restore mailbox"

Also, I really hope they bring this capability into the new exchange admin center before getting rid of the classic admin center!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eff7fa9f-2dec-34c3-e4b3-53614755499f
* Version Independent ID: 61e856b9-12fb-bdf6-0f49-0f6cc8b4b957
* Content: [Delete or restore user mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/delete-or-restore-mailboxes)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/delete-or-restore-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@jonwbstr  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @jonwbstr how are you? hope you are doing good
I could not find the delete option that you mention, in the new or classic EAC, can you share a screenshot? thank you

**Comment by jonwbstr** [comment]
Sure, will share it later today

**Comment by jonwbstr** [comment]
Hi Mark, 

While collecting this screenshot below, I noticed the delete option only appears in the New EAC when accessing an organization using Delegated Access Permission (DAP). 
Also, I don't see the delete option in the classic EAC. I probably miss-read "Deleted Mailboxes" as "Delete Mailbox" my mistake! 

![image](https://user-images.githubusercontent.com/15677312/126020563-8b12474b-4421-4177-8bb6-44f2deead8c7.png)

Since deleting mailboxes is only available with DAP and it's probably not by design ignore that one.

Let's start over =D
That ~~isn't remotely~~ is mostly accurate.

Can you use the new exchange admin center to delete mailboxes? ~~Yes~~ No
Can you use the new exchange admin center to restore mailboxes? No

Can you use the classic exchange admin center to delete mailboxes? ~~Yes~~ No
Can you use the classic exchange admin center to restore mailboxes? Yes

**Comment by get-itips** [comment]
@jonwbstr Hello how are you? Thanks for returning and updating with further information from your side.
I understand what you say, however in the old and classic eac, users are encouraged to use the 365 admin center to restore user mailboxes:

> For Exchange Online customers, please use the Office 365 admin center to recover deleted mailboxes.

**Comment by jonwbstr** [comment]
Hello,

I presume the "old" and "classic" eac are the same portal.

As the article correctly points out, the Office 365 admin center can be used to "restore a user account" the only way to restore a mailbox without using the classic EAC is through powershell.

I am familiar with recovering users + mailbox using the Office 365 admin center. When the user is deleted while the mailbox is on litigation hol after 30 days the user is no longer recoverable through the O365 admin center, but the mailbox is still recoverable using the classic EAC and via powershell.

It sounds like the documentation is intended to exclude methods available in the classic EAC portal that Microsoft has evidently chosen not to bring into the new EAC. If they were planning to bring this feature over I would expect the content in this article to reference the legacy method as a place holder until the new method is introduced.

It's hard to tell when to start giving feedback on the new portal since I'm not familiar with any roadmap that shows what features are planned it's hard to know what features did not make the cut and I didn't want to share feedback on a bunch of missing features that were planned just because it's an early preview.

Guess it's not preview any more and no new features are planned so I'll start sharing feedback more agressively!
