### ISSUE TITLE
incorrect information in one of the screenshots

### ISSUE THREAD

**Issue by ViliusS** [MicrosoftDocs/OfficeDocs-Exchange#2690]
Third Excel screenshot in "Create a list of user mailboxes using admin credentials to access them" paragraph incorrectly says that you need to specify password of mailboxes you want to migrate. For this method you actually have to specify admin password for all mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a62d4e4-616e-3f98-e5b6-5544f923480d
* Version Independent ID: 3f90a7c2-6130-6b55-1cfa-d7a9f4386cd5
* Content: [Migrate other types of IMAP mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes#create-a-list-of-user-mailboxes-using-admin-credentials-to-access-them)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @ViliusS, thank you for your feedback.

Could you kindly let me know the step with the incorrect information? Is it included in the following screenshot?
![image](https://user-images.githubusercontent.com/33589238/126568169-b99aadb0-eafe-486a-81d8-5ff11004e3ad.png)

**Comment by ViliusS** [comment]
Hi, @dariomws, the incorrect information is not in the text but in one of the images. Check the text in black background in Excel screenshot in step 7 just below step 6 you have posted.

**Comment by dariomws** [comment]
Thanks for your comment @ViliusS!

I'm removing the image in that section to avoid confusion. It seems to be fine for the previous section. (Create the list of user mailboxes when you know the user passwords). The section after "Create a list of user mailboxes using admin credentials to access them" has several examples for different IMAP servers.
