### ISSUE TITLE
Need instructions for new Exchange Admin Center

### ISSUE THREAD

**Issue by TheS0upDrag0n** [MicrosoftDocs/OfficeDocs-Exchange#2691]
This page needs to include instructions using the new Exchange Admin Center as well as the old version.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a62d4e4-616e-3f98-e5b6-5544f923480d
* Version Independent ID: 3f90a7c2-6130-6b55-1cfa-d7a9f4386cd5
* Content: [Migrate other types of IMAP mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @TheS0upDrag0n
