### ISSUE TITLE
a note regarding autodetect should be included as part of the prerequisites when migrating from another platform to office365

### ISSUE THREAD

**Issue by javicartin** [MicrosoftDocs/OfficeDocs-Exchange#2693]
for the Gsuite migration to office365, it should be added a note regarding that if they are using Outlook app for mobile, a correction must be done to the autodetect service because it will be pointing to google as the service and it has to be corrected to office365, this must be a requisite, thank you.
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/setup-with-modern-authentication#autodetect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a Google Workspace migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @javicartin, thank you for your feedback and help us to improve docs.microsoft.com.

When you migrate from Google to Microsoft 365/Exchange Online, you need to reconfigure your account (add new) again in Outlook (mobile and desktop). Autodetect/Autodiscover will apply the settings automatically based on your e-mail address and password.

**Comment by dariomws** [comment]
@scanum could you kindly close this issue? Thanks!
