### ISSUE TITLE
No permission requirements noted in Kerberos ASA articles

### ISSUE THREAD

**Issue by PaulRNewell** [MicrosoftDocs/OfficeDocs-Exchange#2694]
Hi there, 
I have a recommendation for updates to the "Configure Kerberos authentication for load-balanced Client Access services" articles (for all Exchange versions). The documentation does not call out which permissions are required to successfully run the RollAlternateServiceAccountPassword.ps1 script, and I think it would be helpful to include them. 
I was working with a customer last week where Exchange and AD are managed by separate teams. The AD admin created the new ASA object, but the Exchange admin (who was in the Organization Management group) could not successfully run the script. It resulted in an "Access Denied" error. 
Aside: the Exchange Trusted Subsystem is not used when running the RollAlternateServiceAccountPassword.ps1. It is run under the context of the person running the script. This may explain why they didn't encounter other issues with the Organization Management group managing Exchange servers. 

In addition to the standard Exchange permissions added to AD when installing Exchange, the "Reset Password" permission must be granted on the ASA object to the person running RollAlternateServiceAccountPassword.ps1 (or preferably, a group including that user, such as Organization Management). 

The 2013, 2016, and 2019 versions of the article do reference the 2013 version of the [Using the RollAlternateserviceAccountCredential.ps1 Script in the Shell](https://docs.microsoft.com/en-us/Exchange/using-the-rollalternateserviceaccountcredential-ps1-script-in-the-shell-exchange-2013-help?view=exchserver-2016) (but only in reference to the script being the only supported method to deploy the ASA, so I understand why it would be over-looked), which states "_This will require the account running the script to have permissions to reset either Active Directory computer account passwords or user account passwords, depending on whether your alternate service account is a computer account or a user account._". It doesn't call out the specific permission of "Reset Password", as there is also a "_Change Password_" permission, which also tripped up the customer. 

Below are the links for ease of reference. I appreciate your time and consideration!
2019 version: https://docs.microsoft.com/en-us/Exchange/architecture/client-access/kerberos-auth-for-load-balanced-client-access?view=exchserver-2019
2016 version: https://docs.microsoft.com/en-us/Exchange/architecture/client-access/kerberos-auth-for-load-balanced-client-access?view=exchserver-2016
2013 version: https://docs.microsoft.com/en-us/exchange/configuring-kerberos-authentication-for-load-balanced-client-access-servers-exchange-2013-help
2010 version (unsupported, I know): https://docs.microsoft.com/en-us/previous-versions/office/exchange-server-2010/ff808313(v=exchg.141)

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @PaulRNewell Paul, how are you?
Thanks for all the detailed information you provided, I am looking into this.
