### ISSUE TITLE
Transition from MRM to Compliance Center Policies

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/OfficeDocs-Exchange#2695]
How do I get my old and new exchange accounts in E365 to use the retention policies I have created in the Admin Center/Compliance/Information Governance area.  When I go in to the account, and select the option for retention, the only options are the default MRM, and two that we had created in the classic view (which crashes in Edge Chromium).  

I have found documentation on how to use, though told not to, MRM, and how to set up the policies in the compliance area, but not what to do if if they are not offered in the dropdown, just that they should be there.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
