### ISSUE TITLE
Please, clarify step 1 on session "Configuring hybrid deployments in multi-forest organizations"

### ISSUE THREAD

**Issue by Rodrigo30Horas** [MicrosoftDocs/OfficeDocs-Exchange#2696]
Dear all,

Documentations about ADConnect deployment always have pointed out that a Tenant cannot support 2 ADConnect servers simultaneously.
> For instance: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-connect-topologies#multiple-forests-multiple-sync-servers-to-one-azure-ad-tenant
> "Having more than one Azure AD Connect sync server connected to a single Azure AD tenant is not supported. The exception is the use of a staging server."

However, when reading the document which I am opening this ticket to, it says on step 1 for the session "Configuring hybrid deployments in multi-forest organizations":
> "A server with Azure Active Directory Connect (Azure AD Connect) with Active Directory Federation Services (AD FS) **must be installed in each forest** to enable single sign-on if a two-way forest trust isn't configured between the forests."

Please, better explain how to achieve 2 ADConnect servers on the same tenant or re-write the session with more information to explain the real intent behing this instruction.

Regards,
Rodrigo Dias(FTC)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baa1d495-fac4-cd81-06a9-cb031107b1c4
* Version Independent ID: a20a0eff-0792-a3a2-8aa9-f21979fd0801
* Content: [Hybrid deployments with multiple forests](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-with-multiple-forests)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-with-multiple-forests.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-with-multiple-forests.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by michelderooij** [comment]
Connecting the 2nd AD Connect instance to the same tenant is just like the first AD Connect instance. Just keep the basic rules in mind when using multiple AD Connect instances from the same source (directly, indirectly), such as to avoid crossing the streams. IMHO, this supported topologies doc doesn't need more (tech) explaining.

**Comment by Rodrigo30Horas** [comment]
Thanks for your input, Michel.

However, from my point of view, the problem remains the same.

One doc says it is not supported to have 2 instances of ADConnect configured against the same tenant (except by having the 2nd as a staging server).
This doc says to install 2 AD Connect servers in different forest for the same tenant.

One of these 2 documents is not accurately sharing the supported (I am not considering whether it works, but rather if Microsoft explicitly supports it [the 1st document says it won't be supported]) ways to achieve multi-forest with 365.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Rodrigo30Horas, thank you for your feedback and help us to improve docs.microsoft.com.

I agree with you. I understand there is a 1:1 relationship between (Active/non-staging) Azure AD Connect instance/server and an Azure AD tenant. I don't want to remove that sentence before confirming it with something else. Please give me a couple of days.
