### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ThijsLecomte** [MicrosoftDocs/OfficeDocs-Exchange#2698]
[Enter feedback here]
The text: Create safe sender lists in EOP. refers to the following link https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365.md, which is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d2d2006-3af2-366e-50f8-c42a007a1e66
* Version Independent ID: 8d4ec857-121f-163f-9691-93668cd6f9a2
* Content: [Use mail flow rules to the SCL in messages](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/use-rules-to-set-scl)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-set-scl.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-set-scl.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ThijsLecomte, it was the trailing '.md' that was messing it up. The corrected URL works fine:

 <https://docs.microsoft.com/microsoft-365/security/office-365-security/create-safe-sender-lists-in-office-365>

I updated the link in the topic.

Thanks for the feedback.

Closing
