### ISSUE TITLE
Windows Server 2019 Active Directory servers?

### ISSUE THREAD

**Issue by sime3000** [MicrosoftDocs/OfficeDocs-Exchange#270]
Can you please update this to reflect the "Supported Active Directory environments" section to show Windows Server 2019 Active Directory servers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcdf59c9-1922-ecf5-fc36-caafb16423ff
* Version Independent ID: 62557ef7-d03e-50b9-00f7-ffdc244e1fc7
* Content: [Exchange Server Supportability Matrix: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/exchange-server-supportability-matrix-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by chrisda** [comment]
@sime3000 we're working on an updated version of this topic that will live within the 2016/2019 content and will contain the same info but updated. It's currently in a private repo and we are working on it.

**Comment by sime3000** [comment]
Thanks for your response chrisda.  We are doing some major upgrade planning and are looking for this information now.  Can you tell A) What is the target date for this to be published ? and B) What are the support requirements for Exchange 2010 in the presence of Windows 2019 domain controllers  ?   The latter should have been published the day Windows Server 2019 was released if not earlier.  Some of us have planning to do : - )    Thanks.

**Comment by AndreaBarr** [comment]
@chrisda Do you have an answer for sime300's above question?

**Comment by sime3000** [comment]
@chrisda 
You may have missed the questions posted a week ago...
We are doing some major upgrade planning and are looking for this information now. Can you tell us A) What is the target date for this to be published ? and B) What are the support requirements for _Exchange 2010_ in the presence of _Windows 2019 domain controllers_ ? The latter should have been published the day Windows Server 2019 was released if not earlier. Some of us have planning to do : - ) Thanks.

**Comment by chrisda** [comment]
@sime3000 as the topic is currently written, Exchange 2010 support tops out at Windows Server 2012 R2 for supported Active Directory environments (writable DCs, writeable GCs, and maximum forest functional level). In other words, any AD site that contains an Exchange 2010 server must contain at least one Windows 2012 R2 or earlier writeable DC and writeable GC. The presence of other Windows 2016 or later DCs in the site or forest is OK, as long as your forest functional level stays at Windows 2012 R2 or lower.

**Comment by sime3000** [comment]
@chrisda 
Hi Chris.  That's not accurate.  Windows 2016 domain controllers AND functional levels are supported as of rollup 22 for Exchange 2010.  Are Exchange 2010 servers supported in the presence of Windows 2019 domain controllers or will they be?  Why is it so hard to get answers to basic questions like these answered and added to the Exchange support matrix so that it clearly show what's combinations are and aren't supported, rather than having to search multiple web pages and post questions in forums such as this one ?

**Comment by scorp508** [comment]
There are no plans at this time to support Windows Server 2019 Domain Controllers / Global Catalog servers with Exchange Server 2010.

**Comment by haodeon** [comment]
What about Exchange 2016 with Server 2019 DC's?

**Comment by decturau** [comment]
What about Exchange 2013? Can I install a 2019 DC in the same forest, domain and site, while also keeping 2012, 2012R2 or 2016 Domain Controller in the same site for Exchange to communicate with? @chrisda

**Comment by chrisda** [comment]
@decturau, I wouldn't chance it. If Windows Server 2019 is listed as 'not supported' for Exchange 2016, then it would be even less supported for Exchange 2013.

**Comment by decturau** [comment]
@chrisda Thank you for the response. 
I see you mentioned above that as long as the functional level stays within support, as well as there is a supported writable DC/Global Catalog for Exchange to communicate with, then we can install the DC. 
Does this mean that a 2019 DC can be installed in the forest, it just wont be able to talk to Exchange? Exchange will continue communication with the DC's that are supported. 
Or that if we install a 2019 DC in a forest with Exchange 2013, it is unsupported (Even if there are supported DC's in the same forest and the forest level is supported).

Thanks.

**Comment by chrisda** [comment]
@decturau, 'unsupported' can mean two different things:

- Actively tested and found to have problems.
- Not tested. This is likely the reason in this case.

The problem is: you do as you described, everything works fine for a while, something goes wrong, and you need to open a support case. When they find out that you're in an unsupported configuration, they can't really help you.

The best way to force the issue and get a definitive answer to your question is to open a support ticket.

**Comment by decturau** [comment]
@chrisda thank you for the reply. Much appreciated.
