### ISSUE TITLE
Default authentication policy and future users

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-Exchange#2701]
It's [defined](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online) as: "The default authentication policy is assigned to all users who don't already have a specific policy assigned to them."

I took that to also mean that all future users would automatically be included in that default policy, but that doesn't appear to be the case based on running the command to check who is in the policy (new users aren't included). This is tested in a tenant with only this policy.

Is there any way to have new users automatically included rather than periodically having to manually include new users in the default policy? It would seem to me that would be _far_ better.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by rpodric** [comment]
Since that's likely to be a fiasco, can you at least say which interpretation of this section of the documentation is correct?
