### ISSUE TITLE
No Print Option

### ISSUE THREAD

**Issue by ranabanerjee15** [MicrosoftDocs/OfficeDocs-Exchange#2702]
No option to print (which was available in older versions). I have tried with different browsers.
we can print individual sections via browser options, but it is not at all productive.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
