### ISSUE TITLE
Mobile device quarantine/approving mobile devices on user card

### ISSUE THREAD

**Issue by Tekwhat** [MicrosoftDocs/OfficeDocs-Exchange#2708]
[Enter feedback here]
Where do we access the mobile device quarantine now? Its completely gone, there is no option to manage mobile devices on the user cards in the new eac. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa40ca38-c70b-6f85-b323-76d8205f2d4f
* Version Independent ID: d4f35834-02c6-84b1-17bc-b50531bc5141
* Content: [What's new in Exchange admin center](https://docs.microsoft.com/en-us/Exchange/whats-new)
* Content Source: [Exchange/ExchangeOnline/whats-new.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/whats-new.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
