### ISSUE TITLE
Exchange 2019 ?

### ISSUE THREAD

**Issue by sime3000** [MicrosoftDocs/OfficeDocs-Exchange#271]
Can you please add Exchange 2019 to this page?  This page seems to be the only comprehensive Supportability Matrix for Exchange.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcdf59c9-1922-ecf5-fc36-caafb16423ff
* Version Independent ID: 62557ef7-d03e-50b9-00f7-ffdc244e1fc7
* Content: [Exchange Server Supportability Matrix: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/exchange-server-supportability-matrix-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by chrisda** [comment]
@sime3000 we're working on an updated version of this topic that will live within the 2016/2019 content and will contain the same info but updated. It's currently in a private repo and we are working on it.
