### ISSUE TITLE
Does authentication policy block both modern & basic authentication or not?

### ISSUE THREAD

**Issue by Yutaka-Naito** [MicrosoftDocs/OfficeDocs-Exchange#2711]
[Enter feedback here]
I think the description below is bit ambiguous. 
>"If your authentication policy disables basic authentication for SMTP, clients cannot use the SMTP AUTH protocol even if you enable the settings outlined in this article." 

There are 2 different ways to interpret it:
a) The authentication policy somehow blocks **both modern & basic authentication** of SMTP AUTH. The clients cannot use SMTP AUTH in any ways.

b) The authentication policy just blocks basic authentication, **but not for modern authentication**.  The clients can continue to  use SMTP AUTH with modern authentication.

I think the b is correct, but could you take a look and provide a clear description?
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f463d2b-dfa3-1061-4e34-01fdfd8b5032
* Version Independent ID: a1d6d284-1c4c-438d-caaa-b06f7a7fb8a8
* Content: [Enable or disable SMTP AUTH](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Yutaka-Naito** [comment]
Thanks for comment but this is not a product question. The b pattern is correct, as I tested , so this article is wrong.
Could you re-open to check if you can change the statement? or I'll re-post this request.

**Comment by Yutaka-Naito** [comment]
I think the post below may not be checked because the closed case is not tracked - I will repost the request.
