### ISSUE TITLE
Protocol combinations are not clear or not properly documented

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/OfficeDocs-Exchange#2713]
Hello

Trying to create a rule below

**New-ClientAccessRule "test" -Priority 3 -Enabled $false -Action DenyAccess -AnyOfProtocols OutlookWebApp -ExceptAnyOfAuthenticationTypes BasicAuthentication**

Getting the error 

**New-ClientAccessRule: Chosen authentication type and protocol combination is invalid. See 'https://go.microsoft.com/fwlink/p/?linkid=869219' for supported combinations.**

BasicAuthentication is listed as a supported method for OutlookWebApp.

What is the problem and where the supported combinations are documented?

**Comment by get-itips** [comment]
Hello @PM735 how are you?
Can you kindly detail if you are trying to run this in Exchange Server (Which version?) or Exchange Online?
Thank you

**Comment by PM735** [comment]
Hello,

The test was done on Exchange Online.
I tried on two different O365 with default settings and get the same error.

Thank you

**Comment by get-itips** [comment]
Hello @PM735 how are you?
Please correct me if I am wrong, from what I could conclude, you want to block OutlookWebApp except if the authentication type is Basic, is that right?

I could successfully ran the cmdlet specifying the auth type I am blocking, like this:

`New-ClientAccessRule "test" -Priority 3 -Enabled $false -Action DenyAccess -AnyOfProtocols OutlookWebApp -ExceptAnyOfAuthenticationTypes BasicAuthentication -AnyOfAuthenticationTypes AdfsAuthentication`

`OutlookWebApp` supports `AdfsAuthentication` and `BasicAuthentication`

Hope this information helps you

**Comment by PM735** [comment]
Thnak you for the response.

Yes, correct.
We want to disable **all types** of authentication for OWA except for Basic.

The suggested rule uses a different logic and blacklisting ADFS method vs whitelisting Basic.
Two points:

1 - The problem is that it won't block a 3rd authentication method if Microsoft decides to add it tomorrow, a change which already happened in the past for Client Access Rules and might go unnoticed.

2 - We do not have the explanation why the original syntax is not working. The documentation does not mention that ExceptAnyof parameters must be accompanied by AnyOf parameters. All parameters are documented as optional, no dependencies. So what is the isssue: documentation or powershell bug?

**Comment by get-itips** [comment]
Hello @PM735 how are you?

I can understand what you say.

Also noted this in the linked article

> **-AnyOfProtocols**
> Note: If you don't use this condition in a rule, the rule is applied to all protocols.

such note is not present for `AnyOfAutenticationTypes` / `ExceptAnyOfAuthenticationTypes` so that should imply that you always need to specify the auth type to be denied.

Made further tests with different Protocols and it seems `AnyOfAutenticationTypes` is only required when using `ExceptAnyOfAuthenticationTypes` with `DeniedAccess` condition.

Will propose an improvement to the article.

Thanks

**Comment by PM735** [comment]
Please note, there are multiple arcticles involved in this issue

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules
https://docs.microsoft.com/en-us/powershell/module/exchange/new-clientaccessrule?view=exchange-ps
https://docs.microsoft.com/en-us/powershell/module/exchange/set-clientaccessrule?view=exchange-ps

As for parameters and what is mandatory or not, there is no need to imply, as we are referring to the BNF form of the following Powershell commands which defines everything in square brackets as optional and anything between signs <> as mandatory.

New-ClientAccessRule
   [-Name] <String>
   -Action <ClientAccessRulesAction>
   [-AnyOfAuthenticationTypes <MultiValuedProperty>]
   [-AnyOfClientIPAddressesOrRanges <MultiValuedProperty>]
   [-AnyOfProtocols <MultiValuedProperty>]
   [-AnyOfSourceTcpPortNumbers <MultiValuedProperty>]
   [-Confirm]
   [-DomainController <Fqdn>]
   [-Enabled <Boolean>]
   [-ExceptAnyOfAuthenticationTypes <MultiValuedProperty>]
   [-ExceptAnyOfClientIPAddressesOrRanges <MultiValuedProperty>]
   [-ExceptAnyOfProtocols <MultiValuedProperty>]
   [-ExceptAnyOfSourceTcpPortNumbers <MultiValuedProperty>]
   [-ExceptUserIsMemberOf <MultiValuedProperty>]
   [-ExceptUsernameMatchesAnyOfPatterns <MultiValuedProperty>]
   [-Priority <Int32>]
   [-Scope <ClientAccessRulesScope>]
   [-UserIsMemberOf <MultiValuedProperty>]
   [-UsernameMatchesAnyOfPatterns <MultiValuedProperty>]
   [-UserRecipientFilter <String>]
   [-WhatIf]
   [<CommonParameters>]


Set-ClientAccessRule
   [-Identity] <ClientAccessRuleIdParameter>
   [-Action <ClientAccessRulesAction>]
   [-AnyOfAuthenticationTypes <MultiValuedProperty>]
   [-AnyOfClientIPAddressesOrRanges <MultiValuedProperty>]
   [-AnyOfProtocols <MultiValuedProperty>]
   [-AnyOfSourceTcpPortNumbers <MultiValuedProperty>]
   [-Confirm]
   [-DomainController <Fqdn>]
   [-Enabled <Boolean>]
   [-ExceptAnyOfAuthenticationTypes <MultiValuedProperty>]
   [-ExceptAnyOfClientIPAddressesOrRanges <MultiValuedProperty>]
   [-ExceptAnyOfProtocols <MultiValuedProperty>]
   [-ExceptAnyOfSourceTcpPortNumbers <MultiValuedProperty>]
   [-ExceptUserIsMemberOf <MultiValuedProperty>]
   [-ExceptUsernameMatchesAnyOfPatterns <MultiValuedProperty>]
   [-Name <String>]
   [-Priority <Int32>]
   [-Scope <ClientAccessRulesScope>]
   [-UserIsMemberOf <MultiValuedProperty>]
   [-UsernameMatchesAnyOfPatterns <MultiValuedProperty>]
   [-UserRecipientFilter <String>]
   [-WhatIf]
   [<CommonParameters>]

**Comment by get-itips** [comment]
@PM735 Yes, I noticed. However, once I get approval on the suggested change I'll review and add a note to the other articles, if needed. Thanks
