### ISSUE TITLE
Issue with the rule processing sequence

### ISSUE THREAD

**Issue by PM735** [MicrosoftDocs/OfficeDocs-Exchange#2716]
Hello

We tried to put 2 simple client access rules below that allow OWA with Basic Authentication.

**New-ClientAccessRule "Allow OWA with Basic" -Priority 1 -Action AllowAccess -AnyOfProtocols OutlookWebApp -AnyOfAuthenticationTypes BasicAuthentication
New-ClientAccessRule "Restrict All except PS" -Priority 2 -Action DenyAccess -ExceptAnyOfProtocols RemotePowershell**

We also created an account onmicrosoft.com and tested OWA with Basic auth.

The documentation article states that the processing will stop after the first matching rule (Allow) and won't process the following rule (Restrict)

We tested OWA access with Basic Authentication and onmicrosoft.com account and observe the opposite behaviour. 
The processing does NOT stop after the first matching Allow and continues to Restrict, which causes access denied.

This was tested in two different tenants with default settings and we are getting the same behaviour that does not match documentation.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by PM735** [comment]
Why the issue is closed so fast?

I have indicated that the documentation contains errors.
The rule processing does NOT stop after the first matching rule, while documentation says it does.

Please reopen the issue and check with your internal teams.
