### ISSUE TITLE
view-group-members

### ISSUE THREAD

**Issue by marguchy** [MicrosoftDocs/OfficeDocs-Exchange#2719]
[Enter feedback here]
I believe there is a much simpler cmdlet that can be used for this - get-dynamicdistributiongroupmember. There is no doc on this cmdlet but I have tested this in my lab and it works just fine and get the same results:

![image](https://user-images.githubusercontent.com/85628242/128254973-fd7a5804-db1f-4cde-b6b8-98c93b5c541e.png)

![image](https://user-images.githubusercontent.com/85628242/128255006-64acba96-e46a-417a-bc24-d2d0863af151.png)

Can we deprecate or add a note to this document? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0f79a0-4e3e-f72e-fb3d-dc0a7a47b7ec
* Version Independent ID: 1882bc12-05d5-02c5-da27-bc48479825b2
* Content: [Manage dynamic distribution group](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-dynamic-distribution-groups/manage-dynamic-distribution-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/manage-dynamic-distribution-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/manage-dynamic-distribution-groups.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
