### ISSUE TITLE
Journaling documentation is for the old admin center

### ISSUE THREAD

**Issue by faboo** [MicrosoftDocs/OfficeDocs-Exchange#2720]
[Enter feedback here]
The Exchange Admin Center (had to do a web search for "EAC", but I think that's what the doc means) doesn't have a "Compliance management" section anymore. It looks like these instructions are aimed at the old Admin Center. It would be helpful for this to called out at the start of the document (preferably with a link to current documentation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d49df7f-4717-d51e-b1b9-5a5a4768a1d9
* Version Independent ID: af6d6557-eb97-6aba-4511-c64e951ab31f
* Content: [Manage journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/manage-journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @faboo Ray, how are you?

At the beginning of the Journaling section, https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/journaling there is an **Important Note** at the top of the article, informing the users where to go now for journaling.

Thank you
