### ISSUE TITLE
Article about plus addressing in Exchange doesn't discuss how this works distribution lists (if it all or slated for future compatibility) 

### ISSUE THREAD

**Issue by EugenePerson** [MicrosoftDocs/OfficeDocs-Exchange#2725]
Excited about plus addressing working in exchange. Two questions I had when reading the article that I had to google to learn more. 

- Are distribution lists (and other groups) supported?
- How do I look up if my organization already has this feature enabled? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2481-2a27-06f3-976c-90614a863d81
* Version Independent ID: a3c4f846-0578-54ed-f2a8-c511be3605af
* Content: [Plus Addressing in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by michelderooij** [comment]
> 
> 
> Thank you for submitting feedback.
> I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
> Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
> Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Did you actually read the comment? Eugene is not reporting an issue, rather a question about plus addressing relation to DGs, and perhaps implies if it works/doesn't shouldn't be clarified in the doc.
