### ISSUE TITLE
Please add NDR 5.1.90

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-Exchange#2729]
[Enter feedback here]

Hello. Please clarify what 5.1.90 NDR is for, and which limit (assuming the daily Recipient Rate Limit of 10,000 messages) a sender exceeds when they get this NDR. 

**'550 5.1.90 Your message can't be sent because you've reached your daily limit for message recipients'**

Ref: https://techcommunity.microsoft.com/t5/exchange/550-5-1-90-ndr/m-p/2631003

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6d0e4-0ea5-f8a9-bf67-bf7cacc74b3e
* Version Independent ID: c72592d3-bfd1-ddf3-793f-dcc0374db074
* Content: [Email non-delivery reports in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online?source=docs)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
