### ISSUE TITLE
Clarify "You can specify all subdomains when you create a remote domain."

### ISSUE THREAD

**Issue by aut0pil0t** [MicrosoftDocs/OfficeDocs-Exchange#2731]
Could you please clarify the statement "You can specify all subdomains when you create a remote domain." more in the document? Is this referring to the possibility of using the wildcard or something else?

It's also better if you can add details about the use of wildcards here as it explains about the Remote Domains in general or provide links to find that additional information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f41f96e-25f1-b5b2-0183-973d1f8e511e
* Version Independent ID: 22a4972e-4bab-c38f-0a96-5c9d97728f38
* Content: [Remote domains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/remote-domains/remote-domains)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/remote-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/remote-domains.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hello @aut0pil0t, thank you for your feedback.

There is a dedicated article that instructs you about how to create remote domains, including subdomains. You can find it in the left bar, and there is also a link in the "See also" section.
![image](https://user-images.githubusercontent.com/33589238/129875050-73ae06f8-df43-49c0-90d0-c0aeb043a7e3.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
