### ISSUE TITLE
sender address matches regular expression does not work 

### ISSUE THREAD

**Issue by nhoj01** [MicrosoftDocs/OfficeDocs-Exchange#2732]
Hello:

I'm using exchange online to create a mail flow rule, targeting a sender's domain/sub-domain. I followed the steps outlined in this article for "The sender's domain is" predicate. 

I used the regular expression described in the article ('\.domain\.com$') replacing domain with my domain, and I get an error message (see below). I get this error whether I use quotes (single or double), or without using any quotes.

The steps in the article should be amended if they are not correct.

error 
Domain name(s) ''\.mydomain\.com$'' contain(s) invalid characters. Domain names may contain only ASCII letters 'a' through 'z', 'A' through 'Z', the digits '0' through '9', the hyphen '-' and the underscore '_'. Domain predicates handle subdomain match, no wildcard is required.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by michelderooij** [comment]
1) "The sender's domain is" is SenderDomainIs, which doesn't support expressions nor wildcards. You should use "The sender address matches" (FromAddressMatchesPatterns).
2) @scanum This is a Q about correctness of examples in Docs; why would ppl need to submit tickets when they are also stimulated to use Github for Q&A and submitting PRs?

**Comment by nhoj01** [comment]
@michelderooij Thanks for the response, I see my mistake. I misread the section, it does say to use "the sender address matches".
