### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by zachh-uo** [MicrosoftDocs/OfficeDocs-Exchange#2733]
"Try the new Exchange adminn center using the URL" has a typo where "adminn' should be replaced with "admin".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe03d3b-31dc-90a2-2a78-1e48947b86d8
* Version Independent ID: 2873f6e9-6979-31d1-5622-0ae47cd9d965
* Content: [Exchange admin center in Exchange Online](https://docs.microsoft.com/en-us/exchange/exchange-admin-center)
* Content Source: [Exchange/ExchangeOnline/exchange-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/exchange-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
