### ISSUE TITLE
We should specify which mailbox plans are used by default when creating different types of mailboxes

### ISSUE THREAD

**Issue by Alex-Catalin** [MicrosoftDocs/OfficeDocs-Exchange#2734]
For example, here https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans#use-exchange-online-powershell-to-specify-the-default-mailbox-plan, on below paragraph we state:

_The default mailbox plan is used as the default template for new mailboxes that you create without a license (because the license specifies the mailbox plan)._

This is not entirely true, because only user mailboxes will benefit of the default mailbox plan. If we create a shared mailbox, it will not use the default mailbox plan if we have an Enterprise subscription for example, instead it will use the Exchange Online Plan 1 mailbox plan template.

If I create a shared mailbox with cmdlet **New-Mailbox -DisplayName SharedE5 -Alias SharedE5 -FirstName Shared -LastName E5 -Name SharedE5**, the assigned mailbox plan will be ExchangeOnline-6f80d0c7-ca03-4cc6-83a2-3150b5dce30c, with a 50GB mailbox quota.

If I create a user mailbox with cmdlet **New-Mailbox -DisplayName UserMbxE5 -Alias UserMbxE5 -FirstName UserMbx -LastName E5 -Name UserMbxE5 -MicrosoftOnlineServicesID usermbxe5@domain.onmicrosoft.com**, the assigned mailbox plan will be ExchangeOnlineEnterprise-a4bcc7a1-348c-4207-a593-c40c09859bbb, with a 100GB quota.

Notice that I have not specified in any of the above cmdlets, the -MailboxPlan parameter which would allow me to manually assign a mailbox plan.

Looking at the properties of the above 2 mailbox plans, we see that the Enterprise plan is the default one, however when it comes to creating shared mailboxes, it will not be used:

Name      : ExchangeOnline-6f80d0c7-ca03-4cc6-83a2-3150b5dce30c
IsDefault : False

Name      : ExchangeOnlineEnterprise-a4bcc7a1-348c-4207-a593-c40c09859bbb
IsDefault : **True**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec37e4b-e81e-ac6a-e435-575b2320e553
* Version Independent ID: 49f631d2-e881-d368-a91a-acd1429baa8b
* Content: [Mailbox plans in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/mailbox-plans.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @Alex-Catalin
