### ISSUE TITLE
Instructions for section do not seem to show how to perform the action

### ISSUE THREAD

**Issue by shawnzzzy** [MicrosoftDocs/OfficeDocs-Exchange#2736]
Correct me if i'm wrong but it seems as if this section: "Change how long permanently deleted items are kept using the new Exchange admin center" doesn't describe a way to make changes to a mailbox using the GUI, just a way in which to search for the deleted items in the mailbox.
Thanks,
Shawn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a43744-eddc-762f-d3c7-6f8732141ad7
* Version Independent ID: c20377ab-03ae-62ed-96bd-04a9bc653286
* Content: [Change how long permanently deleted items are kept for an Exchange Online mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
