### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by adrianprattuk** [MicrosoftDocs/OfficeDocs-Exchange#274]
The formatting on this pages seems to be off.
There are some commands to copy, that that '''' before and after them. Step 5 has empty boxes. And step 8 is in a copy box.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-gb/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#step-2-prepare-for-the-migration)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@adrianprattuk I think I fixed most of the formatting errors.

Thanks for the feedback.

**Comment by adrianprattuk** [comment]
Hi, there are still issues I'm afraid.

**Comment by chrisda** [comment]
@adrianprattuk I made the changes, which are visible on GitHub, but they aren't visible on docs.microsoft.com. I'm attempting to publish those changes.
