### ISSUE TITLE
Exchange & Windows Server 2022 Support

### ISSUE THREAD

**Issue by micoolpaul** [MicrosoftDocs/OfficeDocs-Exchange#2741]
Hi,

Can someone clarify if Exchange Server 2019 is supported with Windows Server 2022 now it is GA? Or if everyone will have to wait for Exchange Server 2022 to use with Windows Server 2022.

Thanks!

**Comment by scanum** [comment]
Hi @micoolpaul Could you please link the article you are referring to? thanks.

**Comment by micoolpaul** [comment]
Hi,

https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2019 Has reference to Windows Server 2019, now that Windows Server 2022 has been released I’m trying to confirm the support status of Windows Server 2022 with Exchange Server 2019 please :)

Thanks!

**Comment by dariomws** [comment]
Hi @micoolpaul, thank you for your comment.

Exchange Server 2019 does not support Windows Server 2022 yet. The article will be updated once the support is confirmed. You can also stay tuned in the Exchange Team blog:
https://techcommunity.microsoft.com/t5/exchange-team-blog/bg-p/Exchange
Maybe next cumulative update the team adds support for Win 2022.
