### ISSUE TITLE
Plus addressing in Exchange online

### ISSUE THREAD

**Issue by hedigardi** [MicrosoftDocs/OfficeDocs-Exchange#2743]
Hi.

Question about this plus addressing in Exchange online:
https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online

From reading that document, if enabled, text after plus sign is considered as a TAG.
And starting in January 2022, plus addressing will be turned on for all customers.

We have external service in our company, where users can use plus like internal number prefix.
It’s not an Exchange online user or distribution list, but messages are usually sent via Ofice365.
Like:
+354865123522@sms.contoso.com

Does this mean that this complete address format becomes useless for all Office365 users or does this only effect email addresses on Office365?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
