### ISSUE TITLE
Requirement for *at least* one DC/GC per AD site is not documented here/nor anywhere else

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/OfficeDocs-Exchange#275]
Setup will fail. It's also unsupported to install Exchange into an AD site with a domain controller and then remove the DC.  I have a premier customer asking for public documentation of the requirement to have a DC in each Exchange site..... and I can't find any Microsoft docs that are public stating such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server system requirements](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016#network-and-directory-servers-1)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@vboyev-MSFT Thank you for pointing this out. 

I will get this information over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@vboyev-MSFT I added the DC/GC in AD site requirement for Ex2016 and Ex2019.
