### ISSUE TITLE
Missing information - automatically email reports.

### ISSUE THREAD

**Issue by ssmiller60** [MicrosoftDocs/OfficeDocs-Exchange#2757]
The document is titled "Customize and schedule mail protection reports to be automatically sent to your inbox" and there is a link provided on how to customize, but there is not actually any info provided on how to schedule mail protection reports to be automatically emailed.

Please provide the steps or a link to a document about how to schedule mail protection reports to be automatically emailed.

Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb585f32-3cd9-2d99-d989-9abb99fb2a7b
* Version Independent ID: aa9e599b-3c5b-b0d0-e4e9-23d7e8ab3894
* Content: [Customize and schedule mail protection reports to be automatically sent to your inbox](https://docs.microsoft.com/en-us/exchange/monitoring/customize-and-schedule-mail-protection-reports)
* Content Source: [Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @ssmiller60 how are you?
Thanks to your feedback I noticed a link was broken in the article.
I noticed you can create a schedule while being a specific report, for example

![image](https://user-images.githubusercontent.com/36666927/132047255-e1c8a572-9271-4ed2-9a0f-fac73912e60e.png)

However I'll look if I can find an specific article that talks about scheduling them.

Thanks
