### ISSUE TITLE
Incorrect options specified in documentation

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/OfficeDocs-Exchange#2758]
The "Recipients" item is a category; if you click it you toggle its subcategories - so you do not get a mailbox list when you click that.

There is no "Unified messaging" option when I click the user - it doesn't matter if the user e.g. has a Phone System license or not.

Was the document revised after deprecation of UM? A date of 20 aug 2021 should imply that ....!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6062509f-31ed-6758-c2e6-204e6783c568
* Version Independent ID: 15891fdd-57c0-78c3-b1ff-6d7bd4185f95
* Content: [Disable voice mail for a user in Exchange Online](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-voice-mail/disable-voice-mail)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-voice-mail/disable-voice-mail.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-voice-mail/disable-voice-mail.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
