### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by jennsljsher** [MicrosoftDocs/OfficeDocs-Exchange#276]
I am very satisfied with Microsoft Exchange and Sharepoint. I am trying to regain control of my OS and files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8953d102-718c-d28a-976a-5906000567c3
* Version Independent ID: 0a13e776-9b35-7b46-5bb5-86b4ba8ddbe5
* Content: [Mobile device mailbox policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/exchange-activesync/mobile-device-mailbox-policies.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@jennsljsher Thank you for this feedback

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
