### ISSUE TITLE
Article seems to indicate Outlook 2013 only

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/OfficeDocs-Exchange#2761]
"Sender's message client program is Microsoft Outlook 2013."

Is that a typo? Should it be 2013 and later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2914fc20-5202-1611-d66e-5310cd01f9f8
* Version Independent ID: 31162c84-0d4f-483a-ccf9-04da60275c67
* Content: [Manage policy tips](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/manage-policy-tips)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/manage-policy-tips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/manage-policy-tips.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @campbellkerr
