### ISSUE TITLE
No longer relevant

### ISSUE THREAD

**Issue by expta** [MicrosoftDocs/OfficeDocs-Exchange#2770]
Reports can no longer be scheduled to go to the admin's mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb585f32-3cd9-2d99-d989-9abb99fb2a7b
* Version Independent ID: aa9e599b-3c5b-b0d0-e4e9-23d7e8ab3894
* Content: [Customize and schedule mail protection reports to be automatically sent to your inbox](https://docs.microsoft.com/en-us/exchange/monitoring/customize-and-schedule-mail-protection-reports)
* Content Source: [Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @expta, thank you for your feedback.

The option to create schedules and manage them is still available:
![image](https://user-images.githubusercontent.com/33589238/132309222-6c80655d-58e6-4e8c-a129-19b52e643c0f.png)
![image](https://user-images.githubusercontent.com/33589238/132309249-cebd4caf-4bc3-486c-8a9d-00654b90ca78.png)
