### ISSUE TITLE
Error creating new journal rule in EXO

### ISSUE THREAD

**Issue by bharatsuneja** [MicrosoftDocs/OfficeDocs-Exchange#2774]
Error when creating a new journal rule: and specifying an external address:
`new-journalrule -Name JournalRuleTest-1 -JournalEmailAddress foo@live.com -Recipient joe@mydomain.com -Scope internal`

Error:
`The JournalEmailAddress can only be a mail user, a mail contact or an external address.
    + CategoryInfo          : InvalidOperation: (:) [New-JournalRule], InvalidOperationException
    + FullyQualifiedErrorId : [Server=BY5PR13MB3858,RequestId=e42657f2-1bfc-487b-828c-5c220e592cf3,TimeStamp=9/8/2021
   7:46:31 AM] [FailureCategory=Cmdlet-InvalidOperationException] FC07E026,Microsoft.Exchange.MessagingPolicies.Journ
  aling.NewJournalRule
    + PSComputerName        : outlook.office365.com`

Believe specifying an external smtp address for JournalEmailAddress used to work in the past.

**Comment by bharatsuneja** [comment]
This works when you specify a non-consumer/free webmail address (e.g. hotmail.com/live.com, gmail.com, etc. don't work). Specifying an address from another tenant worked. 

On further investigation, consumer/free webmail accounts are blocked from being used as journaling mailboxes for Journal Rules. But the same aren't blocked from being backup journaling mailboxes (specified using Set-TransportConfig).

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
