### ISSUE TITLE
Allow contacts to be synced with conditional access

### ISSUE THREAD

**Issue by schemert15** [MicrosoftDocs/OfficeDocs-Exchange#2775]
HI,

We implemented conditional access on access to our corporate email. Only Outlook is allowed to access the O365 email.
This also implies contacts are not available on IOS. Now Whatsap also doesnt have those contacts anymore.

Is there a way to do sync the contacts to IOS but prevents email to be used in the default IOS app?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
