### ISSUE TITLE
wrong image 

### ISSUE THREAD

**Issue by mmujahed** [MicrosoftDocs/OfficeDocs-Exchange#2776]
Example 1 : image is wrong , its mentioned 1.00 KB where it should be 1024 KB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6db6edb-0ce9-5250-0e22-d42907394489
* Version Independent ID: 57d853a0-407f-01e5-4a6f-cdbaf7fa4fff
* Content: [Common attachment blocking scenarios for mail flow rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/common-attachment-blocking-scenarios.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Thanks for your feedback @mmujahed
