### ISSUE TITLE
EAC > Compliance manager vs Classic EAC > Compliance manager

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#2780]
The sections for managing journaling say things like,
> Use the classic EAC to create a journal rule

But the steps say,
> In the EAC, go to Compliance management > Journal rules

I skimmed the title and went straight to step 1 and had to do a double take because EAC doesn't have a compliance manager, Classic EAC does!

minor suggestion, adding the word classic to the step in addition to the title until this is brought into the modern EAC
> In the Classic EAC, go to Compliance management > Journal rules

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d49df7f-4717-d51e-b1b9-5a5a4768a1d9
* Version Independent ID: af6d6557-eb97-6aba-4511-c64e951ab31f
* Content: [Manage journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/manage-journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @jonwbstr, thank you for your feedback.

This is how the article looks:
![image](https://user-images.githubusercontent.com/33589238/133862006-02712e8a-3131-4629-b311-ed00726072fb.png)

Let's keep the article as it's because classic EAC will be deprecated in less than 1 year:
https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-the-classic-exchange-admin-center-in-ww-service/ba-p/2736358

**Comment by jonwbstr** [comment]
Suit yourself, I did a double take because the instructions are 'confusing'

Maybe I'm just weird.
