### ISSUE TITLE
Encrypted email impact

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-Exchange#2786]
Please add some information about how encrypted email needs to be addressed during a migration
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Microsoft 365 or Office 365 organization to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @DeanGross, thank you for your feedback.

This is a good question and there is no easy answer. Or maybe there is one: "you need to remove the encryption, move content, and then encrypt it again in the new tenant with the new encryption keys". Depending on the way you encrypted the messages, export them to a PST could be a possible solution as well.

But this is what I understand, let me forward it to an SME and try to get more information.

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the product team. 

Closing this issue.
