### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by Talerith** [MicrosoftDocs/OfficeDocs-Exchange#2791]
There are NEVER any links to the actual location in any of these articles. That's great that you _tell_ me how to get there, but not actually give me a link to get to that page as well. 

It would be way more helpful to have a LINK to the actual location in the article because Microsoft moves these around constantly. I can't find the location noted here because I go to Compliance > Audit (Not the verbiage in the article) and there is not an option for what is stated in the article.
https://compliance.microsoft.com/auditlogsearch?viewid=Test%20Tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31918102-e76c-a57a-dddd-3363e7bee90e
* Version Independent ID: 6bc7b86d-53b5-3426-9f93-db1f0be83cbe
* Content: [Run a per-mailbox litigation hold report](https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/per-mailbox-litigation-hold-report)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/per-mailbox-litigation-hold-report.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/per-mailbox-litigation-hold-report.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @Talerith, thank you for your feedback.

I think you are looking for this feature in the new Exchange Admin Center. Please search for it in the classic Admin Center. I'm updating the article to reflect it.

**Comment by Talerith** [comment]
Hello 

Thank you for updating it. 

Cheers

Stephanie Norton
