### ISSUE TITLE
authoritative or internal-relay domain

### ISSUE THREAD

**Issue by fgcgithub** [MicrosoftDocs/OfficeDocs-Exchange#2793]
Exchange Hybrid - 50% of mailboxes on-premises, 50% in Exchange Online. How should I configure accepted domains in both worlds?
Assumed the MX-record for my domain is pointing to Microsoft 365 EOP, how should the accepted domain in Exchange Online be configured. Must it be internal relay domain, cause Exchange on-premises is there with the same namespace. Or is "authoritative domain" correct, cause Azure-AD-Sync has created  mail enabled user objects in Microsoft 365 - and therefore Exchange Online "knows" where to send emails to these users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1640bb5-ca97-15ff-28e5-5efe4e73193f
* Version Independent ID: e957bd3e-5d4c-333c-45ff-6fd694f34670
* Content: [Manage accepted domains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/manage-accepted-domains.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
