### ISSUE TITLE
Report stopped working about a month ago

### ISSUE THREAD

**Issue by dippolds** [MicrosoftDocs/OfficeDocs-Exchange#2795]
This report stopped working about a month ago. Simply runs forever. Logged a case with support but they didn't understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8532cf2-3378-d826-7f4d-568575b9577d
* Version Independent ID: b969f952-9848-5190-1007-c851dc2009b5
* Content: [Run a non-owner mailbox access report in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @dippolds, thank you for your feedback.

The classic Exchange Admin Center is being deprecated in favour of the new Exchange Admin Center:
https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-the-classic-exchange-admin-center-in-ww-service/ba-p/2736358

It's better if you use the Microsoft 365 Compliance Center instead to search for audit logs:
https://docs.microsoft.com/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance

You can search for the following activity:
- Exchange mailbox activities - Accessed mailbox items: Messages were read or accessed in the mailbox. Audit records for this activity are triggered in one of two ways: when a mail client (such as Outlook) performs a bind operation on messages or when mail protocols (such as Exchange ActiveSync or IMAP) sync items in a mail folder. This activity is only logged for users with an Office 365 or Microsoft 365 E5 license. Analyzing audit records for this activity is useful when investigating compromised email account.
