### ISSUE TITLE
Incorrect statement

### ISSUE THREAD

**Issue by tudorh** [MicrosoftDocs/OfficeDocs-Exchange#2798]
We got feedback from customers, so I did some testing and confirmed the below statement is incorrect:

"Users can only see a GAL that they belong to (the recipient filter of the GAL includes them). "

This is incorrect, because users will still see the GAL that is assigned to them through an Address Book Policy, no matter if the recipient filter of the GAL includes them or not. 

Please make an edit to remove that phrase.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4e7552-5725-e5ad-0e75-6ca39d8e8d66
* Version Independent ID: 418ba58b-b27d-29c5-eed4-d20b8779dc6f
* Content: [Address lists in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/address-lists/address-lists?source=docs)
* Content Source: [Exchange/ExchangeOnline/address-books/address-lists/address-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/address-lists/address-lists.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @tudorh, thank you for your feedback.

I'm trying to reproduce it in my lab but no luck. I have an ABP assigned to a user with a GAL where the account is not included and I still have the Default GAL.
Could you kindly provide more detail about what you have tested?

**Comment by tudorh** [comment]
Hi @dariomws , thanks for looking into this.

Repro steps are:
1. Create a GAL based on a RecipientFilter that does not include UserA 
2. Create an ABP that contains the GAL from step 1
3. Assign the ABP to UserA

Outcome: UserA sees the GAL from step 1 and all its members.
Notes: You might need to wait a bit for the settings to replicate and even tickle UserA (ie. run Set-Mailbox UserA with no other parameters) for changes to be applied.

**Comment by dariomws** [comment]
Hi @tudorh, thank you for this information. Yes, after some hours I could finally test it.
