### ISSUE TITLE
Report Message Add-In - Does it just send an email...?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#2799]
I'm wondering, about the [Report Message add-in](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/enable-the-report-message-add-in?view=o365-worldwide)...

Based on this article, is it safe to say that reporting messages via the add-in just silently behind the scenes sends emails to the corresponding email address (i.e., junk@/not_junk@/phish@/abuse@office365.microsoft.com)?  Just curious, and if so I might submit a PR to mention this, so the two articles are more related to each other).

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92319831-9982-62a6-2f2f-73ee8614a4fa
* Version Independent ID: 06d7f96b-0c59-3179-cc9f-a97abe4f7fb7
* Content: [Use mail flow rules to see what your users are reporting to Microsoft](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/use-rules-to-see-what-users-are-reporting-to-microsoft)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-see-what-users-are-reporting-to-microsoft.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-see-what-users-are-reporting-to-microsoft.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, checking. I'm pretty confident that the older Junk Email Reporting add-in for Microsoft Outlook worked that way. But. the fact that [user submissions](https://docs.microsoft.com/microsoft-365/security/office-365-security/user-submission) can intercept/divert reported messages to a custom mailbox gives me pause.

**Comment by chrisda** [comment]
@JeremyTBradshaw, I was told that the newer add-ins still use those email addresses to report messages.

**Comment by JeremyTBradshaw** [comment]
@chrisda thanks for the quick verification.  I'm going to ponder it and might submit a PR to mention this, potentially from the other page, referencing this one.  So as to guide admins holistically around the options for the add-in.
