### ISSUE TITLE
SMTP setting needs update

### ISSUE THREAD

**Issue by davidfedsledsol** [MicrosoftDocs/OfficeDocs-Exchange#28]
Encryption Method for SMTP on POP3 needs to be "AUTO".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64383249-903c-6cc5-83e1-93e0eb8ba128
* Version Independent ID: d93c4ce8-4bf4-15d0-b3ba-3d3eb11ebb37
* Content: [POP3 and IMAP4](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/pop3-and-imap4/pop3-and-imap4.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Hello. I asked our customer support team to verify this setting change, and they don't believe a change in the documentation is necessary. Can you give us some detail on your experience with the product that led you to request this change? Any info appreciated.

**Comment by scorp508** [comment]
It does read oddly when you think about the technology in use and what's really happening, but it does match the same odd way many clients have their settings displayed.  Sure, clients do actually go through a Negotiation of what encryption protocol to use and it may not be TLS in the end (though O365 is only allowing TLS at this time), but often clients just ask for something like NTLM or TLS or NONE when setting up an account.

**Comment by davidfedsledsol** [comment]
Simply this, your documentation states TLS.  If you select TLS, it does not connect to SMTP.  If set to AUTO, it connects.

David

David G. Antonacci

VP of Sales & Marketing/Dir., Technology Solutions Group

Corporate Headquarters

Federal and SLED Solutions LLC

p:

(315) 237-6744 Ext. 701

a:

8 John St.



Auburn, NY 13021-2724

w:

www.fedsledsol.com<http://www.fedsledsol.com/>  e: david@fedsledsol.com<mailto:david@fedsledsol.com>

[http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/facebook_sig.png]<https://www.facebook.com/fedsledsol/>  [http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/twitter_sig.png] <https://twitter.com/FedSLEDSol>   [http://cdn2.hubspot.net/hubfs/184235/dev_images/signature_app/linkedin_sig.png] <https://www.linkedin.com/in/davidgantonacci/>

**Comment by tweekerz** [comment]
@davidfedsledsol 
In most cases TLS and SSL are used interchangeably until you start talking about specific versions of the protocols. Are you using Outlook for Windows? If so the correct setting that Outlook uses is STARTTLS for SMTP to connect to Exchange Online. Auto will negotiate that method for you. However when it comes to this page we are not citing a specific email client here. There are many different clients that may call things different in their own respective interfaces.
