### ISSUE TITLE
incorrect information

### ISSUE THREAD

**Issue by MattRose-CC** [MicrosoftDocs/OfficeDocs-Exchange#2800]
Step 2 contains a typo at the following section:

If it's an on-premises mailbox:

PowerShell

Get-Mailbox <on-premises user mailbox> | FL *archive*

If it's an online mailbox:

PowerShell

Get-MailUser <on-premises mail user> | FL *archive*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56dfb49c-fbb1-4e58-a94b-060f31744d6e
* Version Independent ID: 2b2de3cb-3087-c82a-f6ad-f58990a85ae0
* Content: [Create a cloud-based archive in an Exchange hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/create-cloud-based-archive)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/create-cloud-based-archive.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @MattRose-CC, thank you for your feedback.

Sorry, but I couldn't realize what is the typo. Could you kindly provide more detail?
