### ISSUE TITLE
Include information for multiple recipients - How does the rule affect them?

### ISSUE THREAD

**Issue by KwikChk** [MicrosoftDocs/OfficeDocs-Exchange#2801]
The page is fine, except that it does not give you the details of what happens with multiple recipients. It would be nice to know what happens when the condition is met and how it affects all others to the email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81c1119-165b-f408-698c-1092a781ba63
* Version Independent ID: 1a1b6d9a-a75c-e74d-ff84-ccbdf15091de
* Content: [Mail flow rules (transport rules) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @KwikChk, thank you for your feedback.

My apologies but I'm not sure if I understand your question. If the email meets the condition(s), the action(s) will be applied no matter if there are one or multiple recipients.

**Comment by KwikChk** [comment]
Hello Dario,

Thanks for your response, and please accept my apologies for not being clearer in my email.

If there are 4 recipients, one being myself (i.e. in the TO field), and I have a rule stating that they should only sent to the company admin address and not my personal email address, I accept that the rule will be applied for me, and that the email sender will receive this response.

However, what happens to the other recipients, with they also receive the same response (i.e. they are all informed not to send to me, or just the original sender)?

Hopefully this is clearer?

I look forward to hearing from you in due course.

Best regards,

Graham Hobson
Managing Director
For and on behalf of:
Nutra Stat (UK) Limited
Tel (UK): 0845 2300 717
Mob: +44 (0)7710 044066
Email: ***@***.******@***.***>




​Best regards,
Graham Hobson (Nutrastat Man. Dir.)

For and on behalf of
Nutra Stat (UK) Limited
Tel (UK): 0845 2300 717
Tel (INTL):+44 (0)845 2300 717
Mobile (UK): +44 (0)7710 044066
​

​    Please consider the environment: do you need to print this email?
 
Disclaimer:
 This message (and any associated files) is intended only for the use of the individual or entity to which it is addressed and may contain information that is confidential, subject to copyright or constitutes a trade secret. If you are not the intended recipient you are hereby notified that any dissemination, copying or distribution of this message, or files associated with this message, is strictly prohibited. If you have received this message in error, please notify us immediately by replying to Nutrastat Admin ***@***.***)  and deleting it from your computer. Messages sent to and from us may be monitored. 
 Internet communications cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Therefore, we do not accept responsibility for any errors or omissions that are present in this message, or any attachment, that have arisen as a result of e-mail transmission. If verification is required, please request a hard-copy version. Any views or opinions presented are solely those of the author and do not necessarily represent those of the company.
​
Company Name: Nutra Stat (UK) Limited
 Registered office: c/o Ayres Bright Vickers, Bishopstoke, 36 Crescent Road, Worthing, West Sussex, BN11 1RL, United Kingdom   Registered No.: 02894963.      VAT Registration No.: GB 620 8622 58
 Incorporated in England: Companies House,  Crown Way, Maindy, Cardiff, CF14 3UZ     (DX 33050)
 Office Address: Hangar 4, 3 Cecil Pashley Way, Shoreham Airport, Shoreham-by-Sea, West Sussex, BN43 5FF, United Kingdom
 Professional Association: National Pest Technicians Association, NPTA House, Hall Lane, Kinoulton, Nottingham, NG12 3EF, United Kingdom.  Membership No.: 504
​

**Comment by dariomws** [comment]
Hi @KwikChk,

Thank you for your answer. I think I cannot help you here as we are limited to documentation issues and improvements. What will happen with the email from the point of view of transport rules, depends on the actions that you are applying:
https://docs.microsoft.com/exchange/security-and-compliance/mail-flow-rules/mail-flow-rule-actions

For example:
|Action in the EAC|Action parameter in PowerShell|Property|Description|
|---|---|---|---|
|**Redirect the message to** <p> **Redirect the message to** \> **these recipients**|_RedirectMessageTo_|`Addresses`|Redirects the message to the specified recipients. The message isn't delivered to the original recipients, and no notification is sent to the sender or the original recipients.|
