### ISSUE TITLE
Exchange 2010 to 2016 Migration - Easy way

### ISSUE THREAD

**Issue by maxbeckham** [MicrosoftDocs/OfficeDocs-Exchange#2805]
As everyone knows, Microsoft has stopped the maintenance for Exchange Server 2010. As a result, this may be one of the main reasons for the [Exchange 2010 to 2016 migration](https://www.shoviv.com/blog/migrate-exchange-2010-to-2016-using-exchange-admin-center/).

Manually, one might assume that this is not an easy task, but a professional third-party software solution makes Exchange 2010 to Exchange 2016 migration easy. 

Shoviv Exchange Migration Tool:

This multitasking utility is a rewarded solution for managing all Exchange Server instances well. It has various user-centric features.

First a most outstanding feature:

•	There is an incremental export option to resume the interrupted migration process without any duplicates.

More features:

- It appears among the best user-centric options like Filter and search options with preview ability to make the process easier.
- It displays a preview of the added Exchange mailbox data before migration. 
- Perform Exchange 2010 to 2016 migration fastly with a folder mapping option.
- Using its free demo version, one can process the first 50 items per folder.

For more details, visit:- [Exchange Migration](https://www.shoviv.com/exchange-migration.html)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
