### ISSUE TITLE
Add details about the Reports 

### ISSUE THREAD

**Issue by carloxsf** [MicrosoftDocs/OfficeDocs-Exchange#2807]
What are the format of the reports e-mailed?
The Reports are Attached o embeded into the e-mail?
From what alias is comming the e-mail which sends the reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb585f32-3cd9-2d99-d989-9abb99fb2a7b
* Version Independent ID: aa9e599b-3c5b-b0d0-e4e9-23d7e8ab3894
* Content: [Customize and schedule mail protection reports to be automatically sent to your inbox](https://docs.microsoft.com/en-us/exchange/monitoring/customize-and-schedule-mail-protection-reports)
* Content Source: [Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/customize-and-schedule-mail-protection-reports.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
