### ISSUE TITLE
Intune: iOS Notifications - Block Org Data blocks even when unlocked 

### ISSUE THREAD

**Issue by ryanhelmer** [MicrosoftDocs/OfficeDocs-Exchange#2809]
How might one go about setting a policy to block sensitive data in notifications at the lock screen, but show them once the device is unlocked? This capability exists, but once Block Org Data in notifications is set in Intune, you cannot see anything other than tens of e.g. "Outlook: Notification" notifications even once unlocked, rendering notifications useless beyond "something happened"; Block Org Data might as well be Block All Notifications. Once the device is unlocked, one can proceed to the app (unless further auth is required), so there is little reason to continue blocking the notification details. 

Is there a combo of settings to allow the content of notifications to be displayed at the lock screen once unlocked?

Thank you,
Ryan

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
