### ISSUE TITLE
Two Edge Extensions?

### ISSUE THREAD

**Issue by PWC-allan** [MicrosoftDocs/OfficeDocs-Exchange#2810]
Our tenant points to this extension:
https://microsoftedge.microsoft.com/addons/detail/microsoft-smime/gamjhjfeblghkihfjdpmbpajhlpmobbp

What's the difference with:
maafgiompdekodanheihhgilkjchcakm;https://outlook.office.com/owa/SmimeCrxUpdate.ashx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db0df87-55f0-94ec-70a9-1448fecf0643
* Version Independent ID: e3e3f11b-ca34-e57c-e7b7-6d7bf0848028
* Content: [Configure S/MIME](https://docs.microsoft.com/en-us/exchange/security-and-compliance/smime-exo/configure-smime-exo?view=o365-worldwide)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/smime-exo/configure-smime-exo.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/smime-exo/configure-smime-exo.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@PWC-allan, I changed this recently based on an email request. Here's what they said:

> The id of gamjhjfeblghkihfjdpmbpajhlpmobbp is the one from the Store
> https://microsoftedge.microsoft.com/addons/detail/microsoft-smime/gamjhjfeblghkihfjdpmbpajhlpmobbp
>
> The correct id must match what we serve from https://outlook.office.com/owa/SmimeCrxUpdate.ashx which is maafgiompdekodanheihhgilkjchcakm

**Comment by PWC-allan** [comment]
Thanks.  The later once seems to be the updated version as well.  I should tell O365 support to update the link in Outlook settings > S/MIME page.

**Comment by tiburd** [comment]
It sounds like this issue was resolved. 

Closing this issue due to age and inactivity.

cc: @scanum
