### ISSUE TITLE
MRM policies for archive mailboxes

### ISSUE THREAD

**Issue by RoyceLithgo** [MicrosoftDocs/OfficeDocs-Exchange#2818]
At the top of this document is this sentence:
"You should continue using messaging records management to move messages to archive mailboxes."

Then the articles describes features that no longer exist in the new EAC. I wasted considerable time trying to remember how I configured our archive MRM policies years ago. The only way to do this is via Classic EAC, which I assume will be removed at some point. 

Classic EAC is the perfect UI for getting things done. Modern is pretty and useless.

**Comment by scanum** [comment]
@RoyceLithgo Please link the article you are referring to. Thanks

**Comment by dariomws** [comment]
Hi @RoyceLithgo, thank you for your feedback.

Please refer to the [Microsoft 365 security center](https://security.microsoft.com/homepage) and the [Microsoft 365 compliance center](https://compliance.microsoft.com/homepage) for Exchange security and compliance features. They are no longer available in the new [Exchange admin center](https://admin.exchange.microsoft.com).

All of these features will be fully moved to the Compliance Center prior to the classic EAC deprecation.

**Comment by RoyceLithgo** [comment]
Hi @dariomws. 

The MRM policies that are currently in use by my tenant are not viewable in the Retention Policies section of the new Compliance Center. They are no where to be found other than in classic EAC (compliance management - retention policies).
What's happened to them?

**Comment by dariomws** [comment]
The information that I have is that all of these features will be fully moved to the Compliance Center before the classic EAC deprecation.

**Comment by dariomws** [comment]
Some more information from the product team:

"While we encourage customers to use retention policies in the Compliance Center, we are aware that we don't yet have full parity for some scenarios (namely archiving policies and setting default labels on system folders). We will be working on migrating this functionality out of the legacy ECP before it's deprecated and more guidance around it will be released through Message Center posts."

**Comment by RoyceLithgo** [comment]
Thanks for that. The last paragraph gives me some confidence that our Archive MRM policies will survive the EAC deprecation.
