### ISSUE TITLE
is it possible to mark "Save Contacts" as true by default with app configurations through MDM in iOS

### ISSUE THREAD

**Issue by jhernandob** [MicrosoftDocs/OfficeDocs-Exchange#282]
We are trying to configurate through profile manager (Apple MDM) Outlook accounts, we want to configure the option of "Save Contacts" on Outlook for iOS by default to true. There is a key-value in app configurations for this option? We see on documentation some options for Contact Field Sync but not for this option.
![file-1](https://user-images.githubusercontent.com/44995370/48397868-705dd480-e71f-11e8-942d-b41a4390ff3d.jpeg)

**Comment by MishaTravis** [comment]
@jhernandob  - Thank you for submitting feedback.

I think the best way forward with this is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind, please keep us posted here on the resolution - I really want to get this information you are discovering back into the docs.
