### ISSUE TITLE
Sync-ModernMailPublicFolders.ps1

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/OfficeDocs-Exchange#2822]
The Sync-ModernMailPublicFolders.ps1 script uses Basic Authentication, which now fails.  Is there going to be a new version and soon?

Ed Crowley
Former MVP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @curspice I am looking into this.

**Comment by get-itips** [comment]
Hello @curspice please see here https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2835

@scanum please close
