### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by mohfarid85** [MicrosoftDocs/OfficeDocs-Exchange#2827]
Hi All, 
In this documentation (https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-groups-membership-azure-portal) it's mentioned that (Adding distribution groups in nesting scenarios is not supported), however in this current documentation when you go to (Use the Classic EAC to modify distribution list groups), then (Membership), it's mentioned (To add members, click Add Add icon.. In the dialog that appears, find, and select a recipient or group,).
I'd like to know if adding distribution groups in nesting scenarios supported ?
Thanks in advance

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @mohfarid85 how are you? What I can tell you is about the articles under this repo (Exchange) and I can confirm you I could follow the instructions in [this article](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-distribution-groups/manage-distribution-groups). Did you try also?

**Comment by mohfarid85** [comment]
Hello Andria,

Thanks for reaching me , I didn't try the steps practically but my concern was regarding if it's supported by Microsoft or not.
I realised that this article is talking about Exchange and the other one is talking about Azure Active Directory , is that the difference ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chrisda** [comment]
@mohfarid85, @get-itips, you are both correct. Azure AD groups do not support nesting of other groups. Distribution groups (lists) and/or mail-enabled security groups in Exchange Online have historically (10+ years?) supported nested groups, at least in the old/classic Exchange admin center and PowerShell.

So I guess it depends on what you're going to use the groups for. In particular, I would say this is more interesting for mail-enabled security groups, which are more closely related to groups in Azure AD. Distribution groups are email-only, so who cares if you nest distribution groups in other distribution groups?

If you're going to use your mail-enabled security groups in other Azure AD contexts, then you shouldn't add other groups as members, even if you can. This will quickly become a moot point as the new Exchange admin center does not allow you to add other groups as the members of the group, but you can still do it in PowerShell.

**Comment by get-itips** [comment]
Thanks for your comments @chrisda !
