### ISSUE TITLE
Hybrid Scripts no longer work

### ISSUE THREAD

**Issue by RayBrindley** [MicrosoftDocs/OfficeDocs-Exchange#2835]
As Basic Authentication is disabled the scripts that are available from Microsoft no longer work. The scripts need to be updated to reflect the Exchange Online Module which supports MFA and OAuth instead of Basic authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by chrisda** [comment]
@RayBrindley, I'm told this is a known issue, and there are plans to update the script. ETA is by end of this year, but that's just an estimate.

**Comment by RayBrindley** [comment]
Thanks @chrisda thats great to hear that it's at least acknowledged as an issue/known problem I've been able to get things working but I know it will help others in the future.

**Comment by markdepalma** [comment]
I created an article on using modern auth in the scipt without any modifications here: [https://blog.markdepalma.com/?p=840](https://blog.markdepalma.com/?p=840). Basically we need to create a basic-type credential with a bearer token and then pass that to EXO using the BasicAuthToOAuthConversion option.
