### ISSUE TITLE
Add some clarification to the document

### ISSUE THREAD

**Issue by nsymms** [MicrosoftDocs/OfficeDocs-Exchange#2846]
The page offers 3 options for sending emails from an automated device.

You might want to add some clarification / caveats regarding the options:
- Option 1 will NOT work if MFA is enabled for the sending account.
- Option 2 will cause all incoming emails to be treated as "external" regardless of the specified sender email address. So if you are sending to a distribution list, that list must have "allow external senders" or the emails will be rejected.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365?redirectSourcePath=%252fen-gb%252farticle%252fhow-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-365-69f58e99-c550-4274-ad18-c805d654b4c4#option-1-authenticate-your-device-or-application-directly-with-a-microsoft-365-or-office-365-mailbox-and-send-mail-using-smtp-auth-client-submission)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @nsymms, thank you for your feedback.

There is a note in the Option 1 section which mentions security defaults (which includes MFA). There is also a sentence about support for OAuth, if your device/app support, it will work with MFA.

The article explains that you should use option 2 when:
"You only need to send messages to recipients in your own organization who have mailboxes in Microsoft 365 or Office 365; you don't need to send email to people outside of your organization."
