### ISSUE TITLE
Set-AuthenticationPolicy missing Authentication Policy Name

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-Exchange#2849]
Concerning this section:
https://docs.microsoft.com/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#manage-basic-authentication-in-the-microsoft-365-admin-center

The first PowerShell there doesn't work as is:

```powershell
Set-AuthenticationPolicy -AllowBasicAuthReportingWebServices:$false -AllowBasicAuthOutlookService:$false
```

Because, for the same reason as the command that follows it, it requires an Authentication Policy Name:

```powershell
Set-AuthenticationPolicy -Identity "AuthenticationPolicyName" -AllowBasicAuthReportingWebServices:$false -AllowBasicAuthOutlookService:$false
```

So, I'd suggest moving up the part mentioning "Get-AuthenticationPolicy" so that it precedes both commands, not just the second one. In addition to making the needed command line change for the first command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online?source=docs#manage-basic-authentication-in-the-microsoft-365-admin-center)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by chrisda** [comment]
Fixed.

Thanks for the feedback.

Closing
