### ISSUE TITLE
Remote Wipe and Device Management

### ISSUE THREAD

**Issue by technonath** [MicrosoftDocs/OfficeDocs-Exchange#2850]
This documentation is out of date - the Remote Wipe and Device Management is missing from the NEW exchange admin console.  - So where are we supposed to find this when the classic Exchange admin console is removed ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721907bb-1706-db07-bbd8-6676e3151a60
* Version Independent ID: a61afc61-ba69-e5a8-7b6d-e2fc1af5e97f
* Content: [Perform a remote wipe on a mobile phone in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mobile-access/remote-wipe-on-mobile-phone)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mobile-access/remote-wipe-on-mobile-phone.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mobile-access/remote-wipe-on-mobile-phone.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @technonath, thank you for your feedback.

I need to confirm, but I understand that after the classic EAC is deprecated, you'll need to use PowerShell (or Intune if you have the license).

**Comment by dariomws** [comment]
@technonath, you should use PowerShell or classic EAC so far. The option to wipe mobile devices using the new EAC will be available before classic EAC deprecation.

Thank you again for your feedback!
