### ISSUE TITLE
This page does not work!

### ISSUE THREAD

**Issue by AlexNodex** [MicrosoftDocs/OfficeDocs-Exchange#2855]
[Enter feedback here]

This is what is inside the migrations page, there is nowhere to migrate imap or other exchange mailboxes to your platform (which is what the documentation page is about). You should update your documentation when you update parts of your service!

![image](https://user-images.githubusercontent.com/17162626/140885529-0252dfba-f1ac-4752-9f31-828847f5fcda.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852cee18-246c-8c33-9834-fd96595b3e71
* Version Independent ID: 094c2d24-81dc-41c7-48be-c61df7b25fbc
* Content: [Use Minimal Hybrid to quickly migrate Exchange mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/use-minimal-hybrid-to-quickly-migrate)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @AlexNodex I am looking into this.

**Comment by get-itips** [comment]
Hello @AlexNodex how are you? Hope you are doing well

I could dig into this, and I was informed that an update to the article is being planned.
In the meantime, you can use [Mail Migration Advisor](https://docs.microsoft.com/en-us/exchange/mail-migration-jump) to get going as far as a more guided experience goes

Also, as Minimal Hybrid Configuration is a feature from the HCW, you can still follow those steps from it.

Hope this information helps you, and I'll update here when the article is refreshed.

**Comment by get-itips** [comment]
Hello @AlexNodex 

The **e-mail** option has appeared in **_Setup > Migrations > Email_**

I'll propose updating the article.
