### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by SYSprime** [MicrosoftDocs/OfficeDocs-Exchange#286]
While this article is very complete and useful, it doesn't take in any consideration international localization of parameters: in no single place on internet (not only docs.ms) a comprehensive list of localized (e.g. Italian or German) searchable email properties (e.g. localized keywords for "from" or "received" properties) can be found! And  while some of them can be guessed by literal translation, some remain absolutely unknown (even the simple  "Received" date keyword...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f0a23e-30ed-52d8-62b8-bb90980276dd
* Version Independent ID: 533ffa30-d35f-d46b-7a04-67807de8da42
* Content: [Message properties and search operators for In-Place eDiscovery in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/ediscovery/message-properties-and-search-operators?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/ediscovery/message-properties-and-search-operators.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/ediscovery/message-properties-and-search-operators.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by MishaTravis** [comment]
@SYSprime  - Thanks for submitting this feedback.

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @SYSprime , thank you for your feeback.

Could you elaborate further?

I think you cannot use these properties name in different language.

**Comment by dariomws306** [comment]
Hi @AndreaBarr , I think we can close it.

**Comment by SYSprime** [comment]
Hello,

Sorry for my late reply!

I am in trouble scripting an archive & delete solution on localized (Italian) Exchange installation (working like a charm on Intl.English installations):
while the New-MailboxEportRequest:

New-MailboxExportRequest -Mailbox '@ Journal' -Name ExportPST -ContentFilter {(Received -lt $DataArchivio)}

accepts and processes correctly the “{(Received -lt $DataArchivio)” filter, the Search-mailbox one:

     Search-Mailbox $Aliases -SearchQuery "Received:<$DataEliminazione" –DeleteContent

refuses the “Received:” token, because it’s waiting for the Italian translation for it (which could be: “data”, “ora”, “arrivato”, and many others I tried without success) but it’s absolutely undocumented, anywhere.
(just for diagnostics, I tried and it accepts the italianization “Da:” in place of “From:” and so on for many tokens: I was unable to find the corresponding “received” time token.

Thank you very much for your attention and best regards,

[cid:image001.png@01D4C3BC.0C07E920]

Da: Dario Woitasen [mailto:notifications@github.com]
Inviato: sabato 2 febbraio 2019 00:23
A: MicrosoftDocs/OfficeDocs-Exchange
Cc: Emanuele Gnali - SYSprime s.r.l.; Mention
Oggetto: Re: [MicrosoftDocs/OfficeDocs-Exchange] Localization (#286)


Hi @SYSprime<https://github.com/SYSprime> , thank you for your feeback.

Could you elaborate further?

I think you cannot use these properties name in different language.

**Comment by dariomws306** [comment]
If you try "Received<$DataEliminazione" or "Received<=$DataEliminazione"?
