### ISSUE TITLE
Set-ExternalInOutlook also enables the External Sender MailTip

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#2860]
It seems like the Exchange Team no longer recommends just using just the Mailtip, which is set using Set-OrganizationConfig.

https://techcommunity.microsoft.com/t5/exchange-team-blog/native-external-sender-callouts-on-email-in-outlook/ba-p/2250098

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c34a8f0-2eca-250c-f85a-b1b53e7f0ec9
* Version Independent ID: 0bbb9cef-0e4b-6107-5eac-41e5ee3e1f89
* Content: [MailTips in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/mailtips)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/mailtips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/mailtips.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by jonwbstr** [comment]
Apologies for the misleading title, this command does the infobar, and tag.
The Mailtip is still set with set-organizationconfig.

The feedback is these two commands should direct people to the sister
command for the full experience.

**Comment by chrisda** [comment]
@jonwbstr, @dariomws, I'm not making the connection here.

Set-ExternalInOutllook is identifies external SENDERS with a graphic/icon for messages that appear in your Inbox.

The MailTipsExternalREcipientsTipsEnabled parameter on Set-OrganizationConfig identifies the presence of one or more external RECIPIENTS in the To: Cc: or Bcc: fields as you compose an email message (much like when one of the recipients is sending automatic replies). If you feel the message is inappropriate for external recipients, you can remove them before you send the message.

So, the two features aren't related to each other.

Furthermore, that blog post has no mention of MailTipsExternalRecipientsTipsEnabled, other than a single unanswered question in the comments.

**Comment by dariomws** [comment]
@chrisda my mistake, one is for outbound and the other one for inbound emails.

Let's remove the sentence in MailTipsExternalRecipientsTipsEnabled and keep the removal of ExternalInOutlookEnabled in Set-OrganizationConfig.

**Comment by jonwbstr** [comment]
When you reply to a message sent by an external sender, you start composing
a message to an external Recipient.

I have yet to meet a customer that does not see the relationship between
these two features but hey, we get paid to help translate Microsoft docs
and make those connections Microsoft doesn't see so feel free to close
without any changes!

**Comment by chrisda** [comment]
@jonwbstr, you can always reopen the issue if you like, but the two features are wholly unrelated to each other, other than the concept that external senders are involved. Turning one on or off does not affect the other, and one is not a replacement for the other.

A feature in the transport pipeline that marks delivered messages from external senders as external is way different than a tip that says, "This message contains external recipients" as you are composing a message, and before you even send the message (new messages or replies to message).

Unless you have other information?
