### ISSUE TITLE
Need for Mutual Organizational Relationship

### ISSUE THREAD

**Issue by boyejoayo-MSFT** [MicrosoftDocs/OfficeDocs-Exchange#2861]
_"An organization relationship is a one-to-one relationship between businesses to allow users in each organization to view calendar availability information. When you set up the organization relationship, you are setting up your side of the relationship and specifying the level of information that the users in the external organization can view. The external organization may set up the same or different settings on their side. For example, if Contoso creates an organization relationship with Tailspin Toys, the users at Tailspin Toys will be able to schedule meetings with the users at Contoso by adding their email address to the meeting invitation. The availability of the invited Contoso user would display to the Tailspin Toys user. However, before Contoso can also see availability for users at Tailspin Toys, their administrator needs to set up an organization relationship with Contoso."_

According to the article section quoted above, Tailspin Toys does not have to create organizational relationship if they only want to see Contoso's free/busy information and not share theirs. However, we see that organization relationship needs to be created at both ends for this to work.
@dstrome @chrisda @Benny-54 @msdmaguire 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c02125f4-2bb2-0631-93e2-93ccce4f1cb5
* Version Independent ID: 03192cfe-7d7e-82ec-d048-b4ac7d08d9df
* Content: [Organization relationships in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/organization-relationships#feedback)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @boyejoayo-MSFT I am looking into this
