### ISSUE TITLE
Doesn't explain how to delete the contacts

### ISSUE THREAD

**Issue by jasonrdunn** [MicrosoftDocs/OfficeDocs-Exchange#2865]
I turned off the policy to sync LinkedIn contacts with my Exchange account, restarted Outlook, and all 3400+ LinkedIn contacts are still there. This page doesn't explain how to actually solve the problem of all the LinkedIn contacts I don't want to have in my contact list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bffe144-b23d-bcdb-81c6-88e1b58be732
* Version Independent ID: 94f09a10-2074-f537-0fb6-cc0fe34687c7
* Content: [Manage LinkedIn contact sync in your organization in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-linkedin-contact-sync)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-linkedin-contact-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-linkedin-contact-sync.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
v
