### ISSUE TITLE
Instructions don't mention to check ContentMailboxName and ContentMailboxGuid

### ISSUE THREAD

**Issue by despich** [MicrosoftDocs/OfficeDocs-Exchange#2868]
In the preparation you should mention to check all public folders onsite to ensure that they all have a valid ContentMailboxName and ContentMailboxGuid even the ones in the NON_IPM_SUBTREE, even if you are doing a migration with -ExcludeDumpsters migration option.  If any have a blank value or incorrect value the migration will fail with a rather vague "Transient error EndpointNotFoundTransientException has occurred" . These folders can be fixed using the Set-PublicFolder -OverrideContentMailbox command.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by despich** [comment]
I am confused, the issue is already resolved and that was the resolution, I have had two support tickets regarding this issue and they never found this solution. I just want someone to update the documentation so someone else does not have to go through the same mess as I did, it’s obvious that none of the Microsoft techs assigned to my case knew to look for this as a potential cause of my problem.  The two support cases involved were a pay per incident Exchange on premise support ticket #27927088 and an Exchange online ticket #26909889. The Exchange online case was open for more then 3 months and escalated many times…

Thank you

Dan Espich
