### ISSUE TITLE
ECP not EAC

### ISSUE THREAD

**Issue by tlourey** [MicrosoftDocs/OfficeDocs-Exchange#2869]
This article refers to EAC but Mailtips isn't available in EAC, only ECP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4cf8892-771b-e40d-2036-79672516de05
* Version Independent ID: fe2f2228-34b5-e10f-bca9-ce76deefd2d8
* Content: [Configure custom MailTips for recipients in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/configure-custom-mailtips)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/configure-custom-mailtips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/configure-custom-mailtips.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @tlourey 
How are you?
"EAC" here is referring to the _classic Exchange Admin Center_, and when you see "new EAC" in other articles is referring to the _new exchange admin center_. For more information https://docs.microsoft.com/en-us/exchange/changes-in-exchange-admin-center

What I'll do is propose editing it to "classic EAC",

thank you!
