### ISSUE TITLE
Clarify scope of example applies to inbound email flows as well

### ISSUE THREAD

**Issue by MathewBamford** [MicrosoftDocs/OfficeDocs-Exchange#2870]
[Enter feedback here]
This article is really comprehensive and very helpful. The one thing it would be great if you can clarify whether this exact scenario can be applied to inbound emails coming into Exchange Online from an external party. There is no documentation anywhere else that I can find that can clarify whether this is supported or not. 

It seems like auto labelling could be used and a DLP custom policy could make it work. Is it possible if you can clarify whether this exact scenario wold also work for inbound email coming into Exchange online from an external party? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3cb473-82a7-2332-f538-f08eefaa8eac
* Version Independent ID: a9a71fd6-c163-48f6-0c06-81f662ed79a4
* Content: [How DLP rules are applied to evaluate messages in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/dlp-rule-application)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/dlp-rule-application.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/dlp-rule-application.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @MathewBamford Mathew,

This [article](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/integrate-sensitive-information-rules) in the same section says

> Redirecting **inbound** and outbound messages for inspection before delivery.

but I understand that you want a confirmation for the exact scenario in the article?

Thanks for clarifying

**Comment by MathewBamford** [comment]
Hi,
Yes the article mentions but its impossible to find any working example or any further documentation as to how this would be done.
We even logged a support call with Unified Support to ask them for an example policy of how it would be applied for inbound messages from an external organisation and they said it wasn't a supported configuration.

If there is documentation somewhere that deals with it can you maybe reference it in this document, or at least expand in a little more detail how a policy would be created that deals with inbound mail flows. The outbound mail flow is well documented in all the various examples that exist for DLP.

Regards,
Mathew Bamford

________________________________

**Comment by get-itips** [comment]
@MathewBamford I'll try to dig into that

**Comment by get-itips** [comment]
> We even logged a support call with Unified Support to ask them for an example policy of how it would be applied for inbound messages from an external organisation and they said it wasn't a supported configuration. 

Also to note, if support already gave an answer to you I'll probably receive the same but I'll give it a try.

**Comment by MathewBamford** [comment]
my guess is they tried to review the documentation and got lost like we did 😄

Regards,
Mathew Bamford


________________________________

**Comment by MathewBamford** [comment]
Any update on this one?

Regards,
Mathew Bamford

________________________________

**Comment by chrfox** [comment]
per the above, Support says this is an unsupported configuration and we only document supported configurations. closing this issue
