### ISSUE TITLE
Missing IPs / URLs for antimalware engine and definition updates

### ISSUE THREAD

**Issue by FrogThomas** [MicrosoftDocs/OfficeDocs-Exchange#2871]
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/db89d2fe91a1a5856b453c8412cb150204d4bc73/Exchange/ExchangeServer/antispam-and-antimalware/antimalware-protection/download-antimalware-updates.md?plain=1#L31

**Comment by lindspea** [comment]
@FrogThomas thank you for reaching out and helping to improve Microsoft Docs. The document in question - https://docs.microsoft.com/Exchange/antispam-and-antimalware/antimalware-protection/download-antimalware-updates?view=exchserver-2019 - there are two links at the bottom of the page regarding updates. Please let me know if this helps or if you think anything else needs to be added.

**Comment by FrogThomas** [comment]
@lindspea Thank you very much for your hint. Unfortunately the links don't help. A connection on port 80 is obviously required for an Exchange server in order to download updates. For security reasons it would be better to limit the connection to certain IPs or URLs.

**Comment by lindspea** [comment]
@FrogThomas sorry for the delayed response. I've been doing some more research. Would you recommend having a note added to the article mentioning that port 80 is required, to help other users?

**Comment by FrogThomas** [comment]
@lindspea For Office 365 there is an overview of the [required URLs and IPs](https://docs.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide) which must be accessible in connection with certain services. I would like something comparable for the functions of the Exchange Server. Obviously, this overview would be considerably shorter.

**Comment by lindspea** [comment]
Thank you @FrogThomas. I'll do some research to see if there is any official documentation for this.

**Comment by lindspea** [comment]
@FrogThomas I see the article has been updated. Please let me know if you need any further assistance.

**Comment by FrogThomas** [comment]
@lindspea There have only been some changes to the metadata. So I am still missing a specification of IPs or URLs.

**Comment by lindspea** [comment]
@scanum please can you ask the author for assistance.

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.

cc: @scanum
