### ISSUE TITLE
Referenced instructions for Implementation Steps no longer exist on linked page

### ISSUE THREAD

**Issue by robmacf** [MicrosoftDocs/OfficeDocs-Exchange#2873]
Issue for this page: https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019

Under Implementation Steps, the subsection Create a Conditional Access Policy links to another docs page and provides direction to "Follow "Step 1: Configure an Azure ..." and "Follow "Step 2: Configure a..." and then a link for a page that is supposed to contain steps for the reader to follow.

The linked page is https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/app-protection-based-conditional-access#scenario-1-office-365-apps-require-approved-apps-with-app-protection-policies

The linked page no longer contains the referenced text "Step 1" or "Step 2", making it impossible to follow the implementation steps.

**Comment by lindspea** [comment]
@robmacf thank you for reaching out and helping to improve Microsoft Docs. I see the linked page was updated 2 days ago with information. Please can you have a look and let me know if something still needs to be changed.

**Comment by robmacf** [comment]
No, the updated page doesn't contain the necessary information. The "Create a Conditional Access Policy" steps reference sections on the linked page that say '1. Follow "Step 1:...' and then '2. Follow "Step 2:..." 

The quoted text "Step 1" and "Step 2" don't exist on the linked page. Nor does the quoted headline "Scenario 1"

**Comment by robmacf** [comment]
Here's a web archive of what the linked page used to look like. Note that the Scenario 1 section is there with Step 1 and Step 2. You'll need to zoom in to read it.
![Web capture_17-11-2021_141245_cc bingj com](https://user-images.githubusercontent.com/2865919/142637923-c16d9a7e-7956-46bf-85df-f77189a3892b.jpeg)

**Comment by lindspea** [comment]
@robmacf thank you for clearing this up.  @tiburd please can you help with this. I see the linked article was updated on the 17th November and the scenarios were removed. Please can you check with the team which article needs updating/changes.

**Comment by tiburd** [comment]
Sent email to author. I'll update when I receive a response.

**Comment by tiburd** [comment]
We've passed on this information to the team.

Closing this issue.

cc: @scanum
