### ISSUE TITLE
Add another scenario: Keeping Exchange + AADSync but no ADFS

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/OfficeDocs-Exchange#2877]
Even though available on multiple blogs it would be great if docs.microsoft.com could provide another scenario which we see is absolutely the most common since most customers have moved away from ADFS already:
**Scenario X: Keeping Exchange + AADSync but no ADFS.**

I think this would be pretty easy for you to document (since it is not very different from Scenario One) and would be great so we can reference this post instead of 3rd party blogs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @JonesMikael, thank you for your feedback.

In fact, it's there. But it's different from scenario one and the same as scenario two. In the last one, you can read: "This scenario would apply to any customer that is planning on keeping directory synchronization".

**Comment by JonesMikael** [comment]
Hi @dariomws - that is very true and thanks for clarifying this. I did not realize that phrase and the ADFS in the mix made me disregard this scenario. 

You can go ahead and close this issue. Thanks!

**Comment by dariomws** [comment]
@JonesMikael, it is also important to also read the following two sections:
- [Why you may not want to decommission Exchange servers from on-premises](https://docs.microsoft.com/exchange/decommission-on-premises-exchange#why-you-may-not-want-to-decommission-exchange-servers-from-on-premises)
- [Can third-party management tools be used?](https://docs.microsoft.com/exchange/decommission-on-premises-exchange#can-third-party-management-tools-be-used)
