### ISSUE TITLE
Moving Shared Mailbox from Exchange Online to Exchange On-Premises

### ISSUE THREAD

**Issue by Chefaq** [MicrosoftDocs/OfficeDocs-Exchange#2879]
Hello, i neeed to move some Shared Mailboxes to the On-Premise site and i receive the following error.

Cannot find a recipient that has mailbox GUID.

I'm trying to change de ExchangeGUID for tha NEW local Shared Mailbox and i cant.

regards,

Aquiles

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
