### ISSUE TITLE
example email used, right

### ISSUE THREAD

**Issue by Webandappdesign** [MicrosoftDocs/OfficeDocs-Exchange#288]
in this command:
Set-Mailbox -Identity -douglas@contoso.com -RulesQuota 256kb

maybe a stupid question, but the email used is an example email right? nowhere this is made clear.
in addition to apply this rule you need to login using powershell. maybe also a stupid question, but which account do you need to use to login? the account of the user you need to change memory to, or use the admin account? should be made clear for newbies to powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d76e96a-b0a9-552b-e0cf-fa5a1caeee85
* Version Independent ID: 93a0041c-a6ea-0255-0127-a2ad8d4ba436
* Content: [Increase the space used by Inbox rules](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@Webandappdesign , thanks for the feedback. Yes, it is an example account. And for your second question, you need to use an admin account.
