### ISSUE TITLE
Is Organization relationships between WW and other cloud such as Office 365 operated by 21Vianet supported?

### ISSUE THREAD

**Issue by wubofrank** [MicrosoftDocs/OfficeDocs-Exchange#2884]
[Enter feedback here]
In this article, it mentioned:
Organization relationships with GCC High
Tenants in the GCC High cloud can now create organization relationships with tenants in the World Wide and the GCC clouds.
 Important
Organization relationships between the DoD cloud and other clouds is not supported.

I would like to know if Organization relationships between World Wide and Office 365 operated by 21Vianet (i.e. O365China) supported?
If Not, why? and Any other method to archive the same purpose to share Free/Busy between cross cloud  tenant? (CC B2B is not accepted as it has not landed in 21Vianet yet) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e64e56f9-fbf4-f072-637b-5fa8e827a399
* Version Independent ID: 32a37550-af95-a0ce-2941-ff9ce7ba9150
* Content: [Create an organization relationship in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/create-an-organization-relationship?source=docs#feedback)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @wubofrank, thank you for your feedback.

Based on the information in the following article, it seems that it's supported:
https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet#exchange-online-features

**Comment by wubofrank** [comment]
Hi Dario,

Would you please describe it more in detail? Which information you mentioned in the link as reference?

Thanks

-Frank

发件人: Dario Woitasen ***@***.***>
发送时间: 2021年12月2日 14:27
收件人: MicrosoftDocs/OfficeDocs-Exchange ***@***.***>
抄送: Frank Wu ***@***.***>; Mention ***@***.***>
主题: Re: [MicrosoftDocs/OfficeDocs-Exchange] Is Organization relationships between WW and other cloud such as Office 365 operated by 21Vianet supported? (Issue #2884)


Hi @wubofrank<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwubofrank&data=04%7C01%7CFrank.Wu%40microsoft.com%7C8c587218cac841a7e69308d9b55cd0d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637740232570998410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ewx7hmPKYz0W7F75x00bxyEWk1E%2FkGMt13DF5ATGY2E%3D&reserved=0>, thank you for your feedback.

Based on the information in the following article, it seems that it's supported:
https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-operated-by-21vianet#exchange-online-features<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Foffice365%2Fservicedescriptions%2Foffice-365-platform-service-description%2Foffice-365-operated-by-21vianet%23exchange-online-features&data=04%7C01%7CFrank.Wu%40microsoft.com%7C8c587218cac841a7e69308d9b55cd0d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637740232570998410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=38eRWOeowgnmajhbmOgp9Pgj805ZT%2FSYFlzyyFpRRsc%3D&reserved=0>

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-Exchange%2Fissues%2F2884%23issuecomment-984331115&data=04%7C01%7CFrank.Wu%40microsoft.com%7C8c587218cac841a7e69308d9b55cd0d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637740232570998410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lK4J1o2xVm676ElpkrSwgf6r8KQNt4blRU5RhyJDCnk%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAM4FNE4PZKXVLF7AKSCIUSDUO4GVBANCNFSM5JCQBREA&data=04%7C01%7CFrank.Wu%40microsoft.com%7C8c587218cac841a7e69308d9b55cd0d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637740232570998410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nPYmCxZVoNbmFV4u4Bg4WarkmEHqGKXasp2y2MfbbXo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CFrank.Wu%40microsoft.com%7C8c587218cac841a7e69308d9b55cd0d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637740232570998410%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uIov3AonlCDZcTv0P3wbaJqZF23xKw49TMHNl2ozaLY%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CFrank.Wu%40microsoft.com%7C8c587218cac841a7e69308d9b55cd0d3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637740232571048406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yVyezFuG1htHSVecfIsOZ%2FWrqhNQTKTrVQ7aPj4bIvE%3D&reserved=0>.

**Comment by wubofrank** [comment]
Federated sharing?

**Comment by dariomws** [comment]
Yes, I'm talking about federated sharing.

**Comment by wubofrank** [comment]
According to https://docs.microsoft.com/en-us/microsoft-365/admin/services-in-china/services-in-china?view=o365-21vianet
It mentioned:
Coexistence and Free/Busy Sharing | Sharing calendar free/busy information between two or more on-premises Exchange organizations or sharing between two 21Vianet Office 365 tenants isn't supported. This feature is coming soon!
Any comments on this document?

**Comment by dariomws** [comment]
I'll try to confirm.

**Comment by CarolWangMS** [comment]
Hello,
I have tried this before, the organization relationship will not be successfully established. 
If you want to share free/busy between these tenants, it's suggested to config Availability Service.

**Comment by tiburd** [comment]
I sent email seeking answers on 12/8 and today....
