### ISSUE TITLE
Clarity On 'Approval' of Investigation Batches

### ISSUE THREAD

**Issue by Alastair-Bailey** [MicrosoftDocs/OfficeDocs-Exchange#2888]
Could you please explain what is happening when we click 'Approve this migration batch'. Is there any human involvement or is it a completely automated system?
If it is an automated system, can you please explain why it can take hours for the batch to get passed this process and complete?
If there is human involvement, can you please let us know a SLA for this job.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
