### ISSUE TITLE
It's unclear how to finish an IMAP migration in the Microsoft 365 admin center.

### ISSUE THREAD

**Issue by ryanjaeb** [MicrosoftDocs/OfficeDocs-Exchange#2889]
I think this doc could be improved by giving a better explanation of what to do after a migration batch has finished syncing.  Everything is very simple until you finish step 8 and start the migration, but once you hit step 9 I've never been able to find good, concise, definitive instructions on how to update MX and perform a final sync of the migration batch.

Step 10 links to docs that describe how to update DNS / MX records, but if someone stops the migration or closes the connection in step 9, they won't get a complete sync of old data.  The only way to get an idea of what really needs to be done is to read the linked doc for [migrate other types of IMAP mailboxes](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes).

That doc does an ok job showing what the process should be, but doing a final sync of a migration batch isn't described well.  That doc says to wait 72h before completing the migration batch, which is way too long to be useful, and this doc simply says the batch will sync *periodically* which could mean anything.  Other docs I've read say incremental sync happens every 24h.  I've never seen documentation that describes a way to force a final sync of data from the old IMAP provider after updating MX.

It's also unclear what `Close Connection` actually does.  The doc says that it allows you to start another migration batch, but doesn't make it clear if it permanently stops/finalizes the existing batch or if it'll be possible to resume it.  If I remember correctly, it stops the migration batch and removes the migration endpoint, but it's been a while since I used it.  Since step 10 and the other linked docs hint that MX updates should happen *after* running a migration batch, there needs to be an assumption that every migration batch created eventually needs a final sync.

I think it would be better if the steps were:

8. Start migration.
9. Wait for `synced` statuses.
10. Update DNS.
11. Perform or wait for final sync.  It's important to explain where to discover the *last synced* time because it needs to happen after MX updates (and TTL expirations).  If you're able to give feedback to the product team, that info needs to be in the UI.
12. Close connection.

I hope that's useful / constructive feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed16f16-09d6-ad84-7c01-50ef9232ced9
* Version Independent ID: e794838b-02fa-9dce-d7bb-f05c6145f047
* Content: [IMAP migration in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @ryanjaeb, thank you for your feedback.

I'm applying an update on the article based on your comments. The information about the time we recommend waiting after you delete the batch is as you said 72 hours, and synchronization updates run once a day. This information is included in the other article you shared:

- Let the migration batch run for at least 72 hours before you delete it. This makes the following two things much more likely:

  - Your source email system and Microsoft 365 or Office 365 mailboxes were synchronized at least once (they synchronize once a day).

  - The email systems of your customers and partners have recognized the changes to your MX records and are now properly sending email to your Microsoft 365 or Office 365 mailboxes.
