### ISSUE TITLE
Auto forwarded message details

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#2895]
No explanation is given as to how to interpret what the Details property of Auto forwarded message details means.  I only see blanks or a long number, such as  8754395095991580000 or 11200132070573600000.  What does this mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c10f6e93-cb4a-1f68-36b9-0a86a8c07df0
* Version Independent ID: c077a7ba-44ed-c8dc-80de-4f0944417476
* Content: [Auto forwarded messages report in the new EAC in Exchange Online](https://docs.microsoft.com/en-us/exchange/monitoring/mail-flow-reports/mfr-auto-forwarded-messages-report)
* Content Source: [Exchange/ExchangeOnline/monitoring/mail-flow-reports/mfr-auto-forwarded-messages-report.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/mail-flow-reports/mfr-auto-forwarded-messages-report.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
@Canis-Lupis, I was told this for the Details value:

> If the message was auto-forwarded by a mail flow rule, the ID of the rule is shown. Otherwise, this value is blank.

Does this help? Are you able to correlate this rule ID value to the actual rule?

**Comment by get-itips** [comment]
Thanks @chrisda

**Comment by Canis-Lupis** [comment]
No, I cannot.  I tried Get-TransportRule and Get-InboxRule and neither could find anything based on the value.

________________________________

**Comment by get-itips** [comment]
Hello @Canis-Lupis 
I could relate with Get-InboxRule:

![image](https://user-images.githubusercontent.com/36666927/146448596-aec3d3cf-798e-40e3-aaa9-d55440eab9ac.png)

**Comment by Canis-Lupis** [comment]
Not sure what you're attempting to do there.  Have you tried get-inboxrule with the rule identity # given from a AutoForward Report in O365 Exchange instead of with the mailbox name?  Example:


Get-InboxRule -identity [redacted]\8754395095991580000

The operation couldn't be performed because '[redacted]\8754395095991580000' couldn't be found.

________________________________

**Comment by get-itips** [comment]
Yes, I could get it using the alias\given#

![image](https://user-images.githubusercontent.com/36666927/146453447-c0cbc2cb-91fa-47ec-96d5-4a506419b07a.png)

**Comment by chrisda** [comment]
Yes, it appears my source told me wrong; it's not mail flow rules (transport rules) it's Inbox rules. And as Andres described, they use strange syntax for Identity. I updated the topic accordingly:

>  **Details**: If the message was auto-forwarded by an Inbox rule, the ID of the rule is shown. Otherwise, this value is blank. In [Exchange Online PowerShell](https://docs.microsoft.com/powershell/exchange/connect-to-exchange-online-powershell), you can use the [Get-InboxRule](/powershell/module/exchange/get-inboxrule) cmdlet to identify the rule by running the following command: `Get-InboxRule -Identity <MailboxAlias>\<RuleID>`. For example, `Get-InboxRule -Identity lila\8754395095991580000`.

Thanks for the feedback.

Closing
