### ISSUE TITLE
Does not apply to EXO!

### ISSUE THREAD

**Issue by pvernocchi** [MicrosoftDocs/OfficeDocs-Exchange#29]
All this section does not apply to Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456cfa99-b997-3d51-6497-dcf57cafdb33
* Version Independent ID: 2c43bb56-b110-e0c1-13b4-cc8ae9b6d2c6
* Content: [Update offline address book](https://docs.microsoft.com/en-us/exchange/address-books/offline-address-books/update-offline-address-book)
* Content Source: [Exchange/ExchangeOnline/address-books/offline-address-books/update-offline-address-book.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/offline-address-books/update-offline-address-book.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by msdmaguire** [comment]
Thank you for your feedback. We will look into removing this file from the Exchange Online content set.
