### ISSUE TITLE
Retired Feature?

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/OfficeDocs-Exchange#2906]
Is this process still usable?  When I go to in-place eDiscovery & hold in EAC, it says it is retired, and to go to eDiscovery in M365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b80ed4f-4341-edf1-773b-4e2f9da151d5
* Version Independent ID: a50e764e-64b6-6dc4-c3d0-291abcf310b8
* Content: [Export eDiscovery search results to a PST file in the Exchange admin center in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/export-search-results)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/export-search-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/export-search-results.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @rconiv, thank you for your feedback.

This feature was retired, I'm adding a note to the article:

> [!IMPORTANT]
>  As we continue to invest in different ways to search for mailbox content, we're announcing the retirement of In-Place eDiscovery in the Exchange admin center (EAC) in Exchange Online. Starting July 1, 2020, you won't be able to create new In-Place eDiscovery searches. But you'll still be able to manage In-Place eDiscovery searches in the EAC or by using the **Set-MailboxSearch** cmdlet in Exchange Online PowerShell. However, starting October 1, 2020, you won't be able to manage In-Place eDiscovery searches. You'll only be able to remove them in the EAC or by using the **Remove-MailboxSearch** cmdlet. Using In-Place eDiscovery in Exchange Server and Exchange hybrid deployments will still be supported. For more information about the retirement of In-Place eDiscovery in Exchange Online, see [Retirement of legacy eDiscovery tools](/microsoft-365/compliance/legacy-ediscovery-retirement).
