### ISSUE TITLE
Need your assistance to update the Exchange Server supportability matrix 

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/OfficeDocs-Exchange#2907]
Hello experts, 

since we have got the new Office 2021 this October, shall we update the table for customers to refer to? For example, they are using exchange 2013 and want to buy office 2021, they will wonder if it is supported. 

The source link is : https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#clients

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by CarolWangMS** [comment]
Thanks for replying @scanum  The issues itself is resolved. This is just a suggestion.
