### ISSUE TITLE
Target Endpoint step

### ISSUE THREAD

**Issue by NazTeqdup** [MicrosoftDocs/OfficeDocs-Exchange#2915]
The target endpoint step is missing and this is a problem as it halts the progression of the migration. you are unable to select a target destination or manually type it in like the Old EAC therefore you cannot continue or get to the scheduling and complete the migration wizard.

https://docs.microsoft.com/en-us/exchange/mailbox-migration/automated-migration-neweac

**Comment by dariomws** [comment]
Hi @NazTeqdup, thank you for your feedback.

I have verified and the option to add a new migration endpoint is there:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/33589238/147511387-ecd461a6-9a22-429c-b32a-7bf1570d8f8c.png">
<img width="917" alt="image" src="https://user-images.githubusercontent.com/33589238/147511392-229fe069-4f9e-44a0-9233-fc3c584e278d.png">
