### ISSUE TITLE
Not applicable to new Exchange Admin Center

### ISSUE THREAD

**Issue by kf4ape** [MicrosoftDocs/OfficeDocs-Exchange#2920]
In the document you state that this applies to the "Exchange Admin Center (EAC)" however with MS trying to deprecate this and move admins to the new Exchange Admin Portal, it was discovered that the current iteration of "Client Access Rules" does not govern https://admin.exchange.microsoft.com access but only governs https://outlook.office.com/ecp

I recommend updating documentation to reflect the correct admin portal

MS CASE 29011944
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9cdf39f-da71-43ab-0ceb-a816bdc19d04
* Version Independent ID: 1fff6b28-f8d8-d9b3-1730-db2cac7835a0
* Content: [Client Access Rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/client-access-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @kf4ape, thank you for your feedback.

Are you talking about the following sentence?
"Block access to the Exchange admin center (EAC) for users in a specific country or region."

**Comment by kf4ape** [comment]
Correct, with Microsoft deprecating the current Exchange Admin Center this year. With the new one being online, the existing published document could lead one to believe it governed by Client Access Rules also

https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-the-classic-exchange-admin-center-in-ww-service/ba-p/2736358
