### ISSUE TITLE
I'm confused about the instruction to go to 'Compliance Management' and then retention policies, when the only menu I can find is "Compliance Manager" which does not have a section for retention policies.  The first step in the process ends in "and then." ... The sentence literally ended on an adverb.

### ISSUE THREAD

**Issue by kprivigyi** [MicrosoftDocs/OfficeDocs-Exchange#2921]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d3268bb-2ad4-7c02-3454-a412e97b30e9
* Version Independent ID: 43ad9df1-e641-f8ee-d2be-4f2ce9d8e8c2
* Content: [Modify archive policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/modify-archive-policies)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/modify-archive-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/modify-archive-policies.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @kprivigyi, thank you for your feedback.

I'm fixing the article, these are the correct instructions:

## Use the classic EAC to modify the default archive policy

1. Navigate to **Compliance management** \> **Retention tags**.

2. In the list view, select the tag **Default 2 year move to archive** and then click **Edit**.
