### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by PeteGuam** [MicrosoftDocs/OfficeDocs-Exchange#2923]
I started procedure and just completed the TXT record verification. After about 20 minutes our Premises Outlook clients started receiving a prompt to sign in to Microsoft Office. How did this occur? Outlook client is connected to the premises exchange and no MX records such as autodiscover or protection were added to our NetSol DNS table.   I removed the intended domain from Admin, setup, domains and outlook went back to normal.

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852cee18-246c-8c33-9834-fd96595b3e71
* Version Independent ID: 094c2d24-81dc-41c7-48be-c61df7b25fbc
* Content: [Use Minimal Hybrid to quickly migrate Exchange mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/use-minimal-hybrid-to-quickly-migrate#step-3-run-directory-synchronization-to-create-users-in-microsoft-365-or-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @PeteGuam how are you?
As here we are limited to documentation changes and improvements, I think the best in your case would be to open a support ticket from your tenant, so they can help you in your specific scenario.
Thank you
