### ISSUE TITLE
Authenticate an IMAP, POP or SMTP connection using OAuth why this is in the Note it is so misleading 

### ISSUE THREAD

**Issue by karimzaki** [MicrosoftDocs/OfficeDocs-Exchange#2924]
i tried this many times in this article first 2 methods worked for some scenarios but in the note 
Authenticate an IMAP, POP or SMTP connection using OAuth
original post 

https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365

and the comment on this part 
https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth

very useless no steps so why it is there

**Comment by get-itips** [comment]
Hello @karimzaki how are you?

I am not sure I understand sorry, do you think the link to the article _Authenticate an IMAP, POP or SMTP connection using OAuth_ is not providing enough information?

Thanks for clarifying,

**Comment by karimzaki** [comment]
Yes details more and troubleshooting cause simply when you try you got no errors. Also I think more details or tech community is needed for real scenarios.also shall mention SMTP is has been deprecated cause clients still asking

**Comment by get-itips** [comment]
Hello @karimzaki Karim,

To my understanding, the link to _Authenticate an IMAP, POP, or SMTP connection using OAuth_ is included to learn how to enable an application to use OAuth to authenticate against Exchange, which is one of the possible scenarios, also to learn how OAuth works.

Other than the ones listed at the bottom of the article under "Recommended content", you can find more Exchange Troubleshooting articles on this other location https://docs.microsoft.com/en-us/exchange/troubleshoot/exchange-server-welcome

About basic auth deprecation for SMTP you can find the latest information here

https://docs.microsoft.com/en-us/lifecycle/announcements/exchange-online-basic-auth-deprecated

Hope this information helps you,
