### ISSUE TITLE
Content edit

### ISSUE THREAD

**Issue by SROWardly** [MicrosoftDocs/OfficeDocs-Exchange#2925]
[In Note: "Azure AD Connect cloud sync does not support hybrid migrations due to its inability to handle Exchange hybrid writeback" should read Azure AD Connect Cloud Sync to prevent confusion with Azure AD Connect. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server hybrid deployments](https://docs.microsoft.com/en-us/exchange/exchange-hybrid)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @SROWardly, thank you for your feedback.

Are you suggesting adding capital letters to the first letter? My problem is that this is how we reference this service everywhere in the documentation. For example:
https://docs.microsoft.com/azure/active-directory/cloud-sync/what-is-cloud-sync

And the article clearly states that Azure AD Connect is a requirement but cloud sync is not supported.

**Comment by SROWardly** [comment]
Without familiarity of the product/service/tool prior to reading the article, the sentence structure does not differentiate these statements:

Azure AD Connect cloud sync [understood as synchronization to the cloud] does not support hybrid migrations due to its inability to handle Exchange hybrid writeback.
Azure AD Connect [C]cloud [S]sync does not support hybrid migrations due to its inability to handle Exchange hybrid writeback -This would be understood as an entity.
Azure AD Connect cloud sync [service/tool/software] does not support hybrid migrations due to its inability to handle Exchange hybrid writeback -This would also be understood as an entity.
Azure AD Connect cloud-sync does not support hybrid migrations due to its inability to handle Exchange hybrid writeback -This would also be understood as an entity.

Thank you for all your efforts.
Regards,
SROWardly

**Comment by dariomws** [comment]
@SROWardly, 

We appreciate your feedback, but this is the first time we've received this type of feedback about Azure AD Connect cloud sync. We will certainly consider it if we receive more similar feedback from the community.

Thank you so much!
