### ISSUE TITLE
Cannot access imap migration tool

### ISSUE THREAD

**Issue by rkorczykowski** [MicrosoftDocs/OfficeDocs-Exchange#2926]
We're trying to follow the steps here but there is no "email sources". It just points to the migration batch tool. How can we find the tool described in this article?

![image](https://user-images.githubusercontent.com/44030992/148599385-5c7c3ea3-5c45-4a71-ae92-bba796a0c95d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed16f16-09d6-ad84-7c01-50ef9232ced9
* Version Independent ID: e794838b-02fa-9dce-d7bb-f05c6145f047
* Content: [IMAP migration in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
