### ISSUE TITLE
Create a Public Folder

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/OfficeDocs-Exchange#2930]
How do I create a public folder in Outlook?  The instructions are a bit lacking.  Where do I go, which folders do I expand, and where do I click to get the option to create a public folder?  I am using Outlook 365 with the latest updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a273f1fd-9cb5-f7f1-d8f5-8b7e159d1ab3
* Version Independent ID: e9cb295a-eb94-ad6c-80f9-7f8d38ab4876
* Content: [Create a public folder calendar in Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/public-folders-calendar)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders-calendar.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders-calendar.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @cichur
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @rconiv, thank you for your feedback.

I have verified the steps under "Create a public folder calendar" and they are accurate. I was able to create a public folder following them without any issue.
