### ISSUE TITLE
Email Migration in Admin Center is deprecated?

### ISSUE THREAD

**Issue by JMCA2** [MicrosoftDocs/OfficeDocs-Exchange#2931]
The Email Migration option in Microsoft 365 Admin Center is not showing. Instead, it redirects you to the Exchange Admin Center.
According to Microsoft Support [Case #:29058557] they know this option is not available right now but they are unsure if it will return or the docs are obsolete and this feature is deprecated.

If the feature is indeed removed, this page (and others) regarding Email migration in M365 Admin Center should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed16f16-09d6-ad84-7c01-50ef9232ced9
* Version Independent ID: e794838b-02fa-9dce-d7bb-f05c6145f047
* Content: [IMAP migration in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @JMCA2 

Email migration is present on my lab tenants, in the past I already handled an issue reporting the same and sometime later the option appeared again. Is it still not showing for you?

Thanks

**Comment by JMCA2** [comment]
@get-itips Yeah, I experienced the same back in October. Back then the option was not showing.
Now there's a message suggesting going to the Exchange Admin Center:
![image](https://user-images.githubusercontent.com/802183/149368611-f03a50d1-b63c-46d8-addb-b893aec1426a.png)

**Comment by get-itips** [comment]
@JMCA2 Ok I thought you were referring to the e-mail option after clicking migrations, will review if an update is required to the article. thanks

**Comment by JMCA2** [comment]
An update on my support case [Case #:29058557].
After escalating it to Engineering, they confirmed that the option won't be coming back this time. And apparently they said they would update the docs.
