### ISSUE TITLE
Documentation does not mention process to accomplish the same via Admin Portal.

### ISSUE THREAD

**Issue by QuickBASIC** [MicrosoftDocs/OfficeDocs-Exchange#2939]
Settings > Org Settings > Modern Authentication > "Turn on modern authentication for Outlook 2013 for Windows and later (recommended)" checkbox.

This setting will also allow you to change the `OAuth2ClientProfileEnabled ` setting to `$true` w/o needing to use PowerShell (this could be supremely useful for users on Mac or Linux without easy access to PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable or disable modern authentication for Outlook in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
thanks for your feedback, I am looking into this.
