### ISSUE TITLE
legacy endpoint gives same speedbump error message

### ISSUE THREAD

**Issue by jpinkham1** [MicrosoftDocs/OfficeDocs-Exchange#2943]
I have a system that can be configured to send smtp mail via configurable hostname and some other well known smtp parameters easily, but there is no facility to set that other new parameter.  I suspect mine is not the only such system.

Perhaps it would make more sense if the default AllowLegacyTLSClients were true for this host?   (Why else would we be using the 'smtp**-legacy**.office365.com' hostname)

If we could do that, we could probably just as easily be done with it via this instead and wouldn't bother with the -legacy hostname.
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 950369cf-a20f-3079-23f9-bc52fc043873
* Version Independent ID: ab0315ac-b4d0-cb35-f29e-857ed9796ab9
* Content: [Opt in to the Exchange Online endpoint for legacy TLS clients using SMTP AUTH](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/opt-in-exchange-online-endpoint-for-legacy-tls-using-smtp-auth)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/opt-in-exchange-online-endpoint-for-legacy-TLS-using-SMTP-AUTH.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/opt-in-exchange-online-endpoint-for-legacy-TLS-using-SMTP-AUTH.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
