### ISSUE TITLE
You can enable plus addressing in the Exchange admin center

### ISSUE THREAD

**Issue by giggio** [MicrosoftDocs/OfficeDocs-Exchange#2946]
Contrary to what is mentioned on the page, you can enable plus addressing in the Exchange admin center. Url is: https://admin.exchange.microsoft.com/#/settings

It is mentioned here:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/b7cde9651d9e32e02666ee3b23129e9158931f8a/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md?plain=1#L29

An example:
![exchange admin center settings - plus addresses](https://user-images.githubusercontent.com/334958/150156580-83d029fa-d9df-4031-ba82-096420e940ae.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2481-2a27-06f3-976c-90614a863d81
* Version Independent ID: a3c4f846-0578-54ed-f2a8-c511be3605af
* Content: [Plus Addressing in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by dariomws** [comment]
Hi @giggio, thank you for your feedback.

I have updated the article 9 days ago with the steps to enable plus addressing in the Exchange admin center.

**Comment by giggio** [comment]
Great, it probably wasn't published yet when I viewed the page. Thanks!

**Comment by dariomws** [comment]
@giggio, yes, once the update is confirmed in GitHub it could take a couple of hours to appear in Docs.

Thanks again, it's very important for us to have this kind of feedback.
