### ISSUE TITLE
The Script has been modified recently and now basic authentication is not supporting so the command is failing

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-Exchange#2948]
Please run the script 
.\Sync-ModernMailPublicFolders.ps1 -Credential (Get-Credential) -CsvSummaryFile:sync_summary.csv

you will find parameter credential will fail because basic authentication is turn off in script. 

we had to run without credential parameter.
.\Sync-ModernMailPublicFolders.ps1  -CsvSummaryFile:sync_summary.csv

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @robinpoulose1, thank you for your feedback.

I'm testing the script and it seems to be still using basic auth:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/33589238/151124330-043e2d5f-cb9d-4b15-9e3e-248f9d3a6034.png">

**Comment by robinpoulose1** [comment]
Please remove the credentials parameter and run

**Comment by dariomws** [comment]
@robinpoulose1, in the screenshot, you can see that I have run the script without any parameters.

**Comment by robinpoulose1** [comment]
Script has been modified and i believe this is the second time this happen. I have the back up the the script that I downloaded and attached here. 
But now, actually the new one is rectified, However basic auth is turn off for new tenants.
Backup script attached>
[Sync-ModernMailPublicFolders.txt](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/files/7941701/Sync-ModernMailPublicFolders.txt)
.

**Comment by robinpoulose1** [comment]
![image](https://user-images.githubusercontent.com/17806101/151166457-ba645ec0-935c-4d07-ab55-0fba42f5e75b.png)

**Comment by dariomws** [comment]
The feedback to update this script to use Modern Auth instead of basic was done by other people. The team is aware of it and is working on the update.

**Comment by robinpoulose1** [comment]
![image](https://user-images.githubusercontent.com/17806101/151551844-11982e0c-ee67-43fe-a117-e1aad395e951.png)
The script fails and we cannot run through basic authentication. We cannot enable basic authentication again for the tenant.  The previous script the one that I shared used to connect with web authentication.

**Comment by dariomws** [comment]
Thank you @robinpoulose1, I'm told this is a known issue, and there are plans to update the script.

**Comment by tiburd** [comment]
Sharing info with the team again, and closing this issue.

cc: @scanum
