### ISSUE TITLE
420 4.2.0 Recipient deferred because there is no Mdb

### ISSUE THREAD

**Issue by brauer84** [MicrosoftDocs/OfficeDocs-Exchange#2952]
Please add the following detail:

NDR code is caused by having external email address configured in proxyAddresses attribute (SMTP:username@externaldomain.com) on local Active Directory account where the email domain/email address is not hosted with any mailbox within the Exchange On-Premises organization.  Troubleshooting for this started with Exchange Online mailbox where mail flows outbound through Exchange Hybrid server On-Premises.

420 4.2.0 Recipient deferred because there is no Mdb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6d0e4-0ea5-f8a9-bf67-bf7cacc74b3e
* Version Independent ID: c72592d3-bfd1-ddf3-793f-dcc0374db074
* Content: [Email non-delivery reports in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
@brauer84 Could you see my question here? thanks

**Comment by get-itips** [comment]
@scanum
