### ISSUE TITLE
Problem with Video embedded

### ISSUE THREAD

**Issue by rabbyn** [MicrosoftDocs/OfficeDocs-Exchange#2954]
It seems that you have a problem with the video embedding on this page

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9077cdcf-3d7c-76b3-8973-1fc26e77cc4f
* Version Independent ID: 12697174-ef70-7e60-46c4-3d832fdc1f4c
* Content: [Policy Tips in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/policy-tips)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/policy-tips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/policy-tips.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for the feedback!
