### ISSUE TITLE
Rollout in progress?

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#2957]
I can't see this report at the moment. Support case 29351850 raised and referred to you.
Please ping me on Teams or via e-mail: trudolf

Thanks, Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4415d972-e123-6bf0-bfbc-3c555dc9bf51
* Version Independent ID: 3a79fad5-4ac5-9263-2ac8-8607a6f7ddf3
* Content: [Exchange transport rule report in the new EAC in Exchange Online](https://docs.microsoft.com/en-us/exchange/monitoring/mail-flow-reports/mfr-exchange-transport-rule-report)
* Content Source: [Exchange/ExchangeOnline/monitoring/mail-flow-reports/mfr-exchange-transport-rule-report.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/mail-flow-reports/mfr-exchange-transport-rule-report.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
Checking

**Comment by chrisda** [comment]
Confirmed report isn't fully rolled out everywhere yet. Added Preview note to the top of the topic.

Thanks for the feedback.

Closing
