### ISSUE TITLE
Does not appear to work for Microsoft 365 family

### ISSUE THREAD

**Issue by DanZee** [MicrosoftDocs/OfficeDocs-Exchange#2959]
Hi,

I have a consumer Google Workspace account and custom domain for my family. I am trying to move this to Microsoft 365 Family, but step 1 (register custom domain) requires a business or enterprise plan. It seems that this article is not actually about consumers, but businesses -  it would be good to clarify this at the start of the page.

Kind regards,
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer Google Workspace (formerly G Suite) mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @DanZee, thank you for your feedback.

All this documentation is dedicated to Microsoft 365 for Business and Enterprise.
