### ISSUE TITLE
Current default behaviour for saving sent items in delegate and shared mailboxes is suboptimal

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/OfficeDocs-Exchange#2967]
Current default behaviour is for emails to only be saved in the sent items of the email sender. I am struggling to think of how this could have ever been seen as the sensible default behaviour?

You have an article that covers this subject: https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/automatically-save-sent-items-in-delegator-s-mailbox

In my experience, without exception, people who discover this are dumbfounded by it being the default behaviour and request that the setting be changed.

**Comment by dariomws** [comment]
@deejerydoo, thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft Exchange better. They keep a close tab on user feedback and it would be awesome if you could add your voice in the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/forum/89a8afa3-2e1c-ec11-b6e7-0022481f8472#.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by deejerydoo** [comment]
Thanks for the reply @dariomws. However, unfortunately, there isn't even a forum on the feedback website for Exchange. Also, the feedback site seems to be awash with feedback from consumers, amongst the IT professionals; somewhat watering down the quality of feedback in the process.

**Comment by dariomws** [comment]
@deejerydoo, that is the official site to provide feedback on Microsoft products, you can try in Outlook for example. Another option could be https://techcommunity.microsoft.com/. Here we are limited to documentation issues and improvements.

**Comment by deejerydoo** [comment]
The Feedback site is woeful. Sadly another example of an MVP gone too minimal.

Please refer to my post here:
https://techcommunity.microsoft.com/t5/microsoft-365/current-default-behaviour-for-saving-sent-items-in-delegate-and/m-p/3114579

**Comment by dariomws** [comment]
Thanks, @deejerydoo. Do you think I can help in some way with the article in Docs?

**Comment by deejerydoo** [comment]
No, thanks. However, you did say "You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request."

So, just letting you know about the feedback.

**Comment by michelderooij** [comment]
Disagree with deejerydoo. The default always works, deejerydoo's default suggestion works under certain conditions. Saving in shared/delegate mailbox doesn't work when both are not located in the same location for example (hybrid).

**Comment by deejerydoo** [comment]
@michelderooij
> The default always works
Whether it works or not is not the point. We know it works currently. It's whether having the default set as it currently is makes sense or not (i.e. Covers the majority of scenarios and better adheres to privacy and legal requirements).

> works under certain conditions
My argument is that the current default, to not have emails sent by a delegate, using send as or send on behalf of rights, easily available to the delegator, by having a copy placed into their own Sent Items folder, doesn't work in the majority of conditions and makes less sense in terms of privacy and legality. Since when has it been considered legal or honouring someone's privacy to have a delegate able to send an email as a delegator and not have a copy of that email easily available to the delegator, in their Sent Items folder?

> Saving in shared/delegate mailbox doesn't work when both are not located in the same location for example (hybrid)
This sounds to me more about a technical limitation, limited to hybrid environments only. Not a business, legal or reporting limitation that applies to the majority of entities that do not run hybrid environments.

However, this thread is not in the right location and I have already posted a link to a more suitable location. Please feel free to continue the discussion there.
