### ISSUE TITLE
Not up to date with current O365 admin UX

### ISSUE THREAD

**Issue by cloverenergy** [MicrosoftDocs/OfficeDocs-Exchange#2968]
The page refers to non-existing menus which have been presumably been moved around in the incesent redesign of the Admin Center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f463d2b-dfa3-1061-4e34-01fdfd8b5032
* Version Independent ID: a1d6d284-1c4c-438d-caaa-b06f7a7fb8a8
* Content: [Enable or disable SMTP AUTH in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @cloverenergy Clover, how are you?
I could successfully follow these instructions

>Open the [Microsoft 365 admin center](https://admin.microsoft.com/) and go to Users > Active users.

>Select the user, and in the flyout that appears, click Mail.

>In the Email apps section, click Manage email apps.

>Verify the Authenticated SMTP setting: unchecked = disabled, checked = enabled.

>When you're finished, click Save changes.

Were you referring to that?

Thank you

**Comment by get-itips** [comment]
@cloverenergy Hello, returning to this thread to understand if you could see my last comment, thank you

**Comment by cloverenergy** [comment]
Sorry - not exactly sure anymore what was my issue with documentation 
but it had to do with SMTP authentication settings.

Regrettably I will not manage to be more specific. I’ll make sure to 
go into more details next time as apparently you do follow up :)

Best regards

On 18 Feb 2022, at 23:08, Andres Mariano Gorzelany wrote:

> Hello @cloverenergy Clover, how are you?
> I could successfully follow these instructions
>
>> Open the [Microsoft 365 admin center](https://admin.microsoft.com/) 
>> and go to Users > Active users.
>
>> Select the user, and in the flyout that appears, click Mail.
>
>> In the Email apps section, click Manage email apps.
>
>> Verify the Authenticated SMTP setting: unchecked = disabled, checked 
>> = enabled.
>
>> When you're finished, click Save changes.
>
> Were you referring to that?
>
> Thank you
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2968#issuecomment-1045255586
> You are receiving this because you were mentioned.
>
> Message ID: 
> ***@***.***>

Alexandre Takacs
t: +41 (22) 552 58 53 | m: +41 (79) 451 66 49
e: ***@***.*** | w: www.cloverenergy.ch
a: Rue de la Cloche 8, CH-1201 Geneva Switzerland

**Comment by get-itips** [comment]
Thanks for returning and sharing your feedback @cloverenergy
