### ISSUE TITLE
Mention that mail flow SCL bypass isn't respected for high confidence phish and malware

### ISSUE THREAD

**Issue by ajh0912** [MicrosoftDocs/OfficeDocs-Exchange#2971]
This page makes no mention that EOP will not respect the SCL bypass for messages deemed as `High Confidence Phishing`, although it does mention malware scanning.

Instead [Advanced Delivery](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-advanced-delivery?view=o365-worldwide#use-the-microsoft-365-defender-portal-to-configure-third-party-phishing-simulations-in-the-advanced-delivery-policy) would be used for the scenario where `High Confidence Phishing` emails need to bypass EOP.

As per the secure by default changes:
https://techcommunity.microsoft.com/t5/microsoft-defender-for-office/mastering-configuration-in-defender-for-office-365-part-two/ba-p/2307134

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d2d2006-3af2-366e-50f8-c42a007a1e66
* Version Independent ID: 8d4ec857-121f-163f-9691-93668cd6f9a2
* Content: [Use mail flow rules to the SCL in messages in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/use-rules-to-set-scl?view=o365-worldwide)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-set-scl.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-set-scl.md)
* Product: **m365-security**
* Technology: **mdo**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by ajh0912** [comment]
Also not sure about this part of the caution admonition - other than a scenario where emails don't get flagged as High Confidence Phishing or Malware due to a false negative?

> Attackers can use this vulnerability to send phishing and other malicious messages into your organization.

**Comment by chrisda** [comment]
@ajh0912, OK, fixed. Updates should publish Th 2/3 ~11:00 AM PST.

Thanks for the feedback.

Closing
