### ISSUE TITLE
Rebuild Offline Address Book

### ISSUE THREAD

**Issue by MatthewBrown0** [MicrosoftDocs/OfficeDocs-Exchange#2972]
Please add a section to the documentation on the powershell commands to rebuild the offline address book.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c8500b-c731-054e-d1c1-9b5f14114f7a
* Version Independent ID: 218fc166-2aee-132e-1a2a-6d4784734a0b
* Content: [Offline address book procedures in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/offline-address-books/offline-address-book-procedures)
* Content Source: [Exchange/ExchangeOnline/address-books/offline-address-books/offline-address-book-procedures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/offline-address-books/offline-address-book-procedures.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @MatthewBrown0, thank you for your feedback.

There is no way to regenerate the OAB in Exchange Online. 

This cmdlet is not available in Exchange Online:
https://docs.microsoft.com/powershell/module/exchange/update-offlineaddressbook
