### ISSUE TITLE
Check Domain Wide Delegation

### ISSUE THREAD

**Issue by bharto** [MicrosoftDocs/OfficeDocs-Exchange#2973]
[Enter feedback here]
Can someone check step # 6 here -https://docs.microsoft.com/en-us/exchange/mailbox-migration/manually-configuring-gsuite-for-migration#create-a-google-service-account

In my latest configuration Domain-Wide Delegation redirected me to the Google Admin console to enable under Security. Looks like this particular step may be out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57da3fb1-2554-0eee-b754-098e9d2702f4
* Version Independent ID: 702d8739-366a-9cb6-9ac6-4737fc333beb
* Content: [Perform manual Google Workspace migration in Classic Exchange admin center in Exchange Online](https://docs.microsoft.com/en-us/exchange/mailbox-migration/manual-gspace-migration-classiceac)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/manual-gspace-migration-classiceac.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/manual-gspace-migration-classiceac.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by dariomws** [comment]
Hi @bharto, thank you for your feedback.

It seems that these 2 steps are not needed. Manage Domain Wide Delegation is accessed in the next section.
