### ISSUE TITLE
wrong infromations

### ISSUE THREAD

**Issue by datapack** [MicrosoftDocs/OfficeDocs-Exchange#2974]
[Menu changed and informations are wrong on this page]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ed16f16-09d6-ad84-7c01-50ef9232ced9
* Version Independent ID: e794838b-02fa-9dce-d7bb-f05c6145f047
* Content: [IMAP migration in the Microsoft 365 admin center](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/imap-migration-in-the-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello, please see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/2931#issuecomment-1013290812 for status updates about this issue
