### ISSUE TITLE
S/MIME version upgrade history

### ISSUE THREAD

**Issue by brethvoice** [MicrosoftDocs/OfficeDocs-Exchange#2976]
Please update this page to specify when the last upgrade(s) to S/MIME were implemented in Outlook.  Specifically, I am wondering whether you upgraded to at least version 4 following the e-fail reveal here:

https://youtu.be/jRb54Xb7TCI?t=2449

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146e1dad-3eff-cf6b-19aa-a859c92ac178
* Version Independent ID: 01f13ce8-3d11-9a09-5c3c-a01d9a51f887
* Content: [S/MIME in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/smime-exo/smime-exo)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/smime-exo/smime-exo.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/smime-exo/smime-exo.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @brethvoice I am looking into this
