### ISSUE TITLE
Highlight SMTP AUTH exception more clearly

### ISSUE THREAD

**Issue by MelTheFruitFly** [MicrosoftDocs/OfficeDocs-Exchange#2979]
It would really be nice if the fact that SMTP AUTH is **not** being disabled for tenants using it was called out more clearly, if not explained much sooner in the notification. This is causing a LOT of confusion for folks using apps that still only offer Basic SMTP AUTH and is causing panic among some IT teams. Not even kidding, I've seen absolute panic about it. 

It's just a buried paragraph here below the fold and app developers are then having to point customers to that paragraph to explain that no, SMTP AUTH is NOT being disabled for you. 

Suggestions: 

- Mention that it's NOT being disabled in tenants where it's in use at the same space where you say it's being disabled for nonuse. 
- Call it out when you do explain that in use it's not being disabled. Make it a notice with colors. Something like how it's clearer here: https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#option-1-authenticate-your-device-or-application-directly-with-a-microsoft-365-or-office-365-mailbox-and-send-mail-using-smtp-auth-client-submission

Thank you for considering. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19cf826a-aaf1-91ed-8a8f-637d869e47df
* Version Independent ID: 61d69fb6-184d-acf5-8b02-39b3d885d28b
* Content: [Deprecation of Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @MelTheFruitFly, thank you for your feedback.

I understand that the article clearly states that SMTP Auth basic auth won't be disabled for tenants that are using it. There are three sections with some words about that:

- "We're also disabling SMTP AUTH in all tenants in which it's not being used."
- "SMTP Auth will also be disabled if it is not being used."
- "SMTP AUTH will still be available when Basic authentication is permanently disabled on October 1, 2022. The reason SMTP will still be available is that many multi-function devices such as printers and scanners can't be updated to use modern authentication. However, we strongly encourage customers to move away from using Basic authentication with SMTP AUTH when possible. Other options for sending authenticated mail include using alternative protocols, such as the [Microsoft Graph API](https://docs.microsoft.com/graph/api/user-sendmail)."
