### ISSUE TITLE
Could you please describe how to select a specific S/MIME certificate for signing when composing an e-mail in the Outlook app for iOS?

### ISSUE THREAD

**Issue by ViennaX** [MicrosoftDocs/OfficeDocs-Exchange#2982]
Could you please describe how to select a specific S/MIME certificate for signing when composing an e-mail in the Outlook app for iOS?
Example: you have installed two certificates (one from an internal CA and one from an third party CA). For sending an e-mail to external people I can select in Outlook for Windows the third party CA certificate and for company internal e-mails I can select the certificate from the internal CA). How does this work in the Outlook for iOS app. Currently the Outlook for iOS app is automatically using the certificate from the internal CA for signing. There is no popup “Which certificate should be used?”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 166f2cf0-69e9-2a39-1d2b-1f647fe17dbe
* Version Independent ID: a2fc4fc6-bcb7-d90b-1b53-0621a0258037
* Content: [S/MIME for Outlook for iOS and Android in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/smime-outlook-for-ios-and-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/smime-outlook-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/smime-outlook-for-ios-and-android.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @ViennaX 
I am looking into this, I am trying to confirm if that is currently possible.
Thanks

**Comment by ViennaX** [comment]
Hello @get-itips,
Thank you!

**Comment by get-itips** [comment]
Hello @ViennaX 
I could confirm that currently, is not in the feature set but is in development, I do not have a timeline.
