### ISSUE TITLE
New Exchange Admin - Access to shared mailboxes

### ISSUE THREAD

**Issue by ServiceDeskRunshaw** [MicrosoftDocs/OfficeDocs-Exchange#2983]
The new exchange admin centre feels like a backward step for editing mailbox access.  There are multiple steps to get to where you want (rather than just right click on the mailbox & edit).  You can't edit Read & manage and Send as access on the same screen like you could before & if you want to give someone access if you edit one of them & then click back to see the other you just get a loading message so you have to go all the way out and back in again.
![Screenshot_3](https://user-images.githubusercontent.com/99484421/153595785-39865fe7-cd2f-4d54-a489-7438b142fe95.png)

**Comment by dariomws** [comment]
Hi @ServiceDeskRunshaw, thank you for your feedback.

Here we are limited to documentation issues and improvements. You can provide your feedback about the new EAC directly on it using the feedback option on the lower right-hand side of the screen.
