### ISSUE TITLE
Create RSS feeds on the Updates for Exchange Server Updates and Exchange build numbers and release dates

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/OfficeDocs-Exchange#2995]
It is hard to keep up to date with the changes in Exchange. It would be helpful to have an RSS feed that provided a summary of the change with link to relevant Microsoft docs page.

It is the tables in the following pages that need RSS feeds 

- https://docs.microsoft.com/en-us/exchange/new-features/updates?view=exchserver-2019
- https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019

The Azure AD page already has an RSS feed so you can keep up with changes https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new. 
The output JSON is:
{
    "title": "What's new? Release notes - Azure Active Directory",
    "primaryLink": "https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new",
    "links": [
      "https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new"
    ],
    "updatedOn": "0001-01-01 00:00:00Z",
    "publishDate": "2022-01-31 00:00:00Z",
    "summary": "Learn what is new with Azure Active Directory; such as the latest release notes, known issues, bug fixes, deprecated functionality, and upcoming changes.",
    "copyright": "",
    "categories": []
  }
It would be good to have the same format

**Comment by get-itips** [comment]
Hello @nikki-c 
Thanks for your feedback, as this is not an specific edit to an article I'll pass this suggestion on to the Docs team.
Thank you!

**Comment by get-itips** [comment]
Suggestion to the Docs team was submitted.
Thanks!
