### ISSUE TITLE
in-place eDiscovery articles refers to the retired option

### ISSUE THREAD

**Issue by NazTeqdup** [MicrosoftDocs/OfficeDocs-Exchange#2997]
[Enter feedback here]
The feature says it's been retired and to use the new compliance centre e-discovery. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b80ed4f-4341-edf1-773b-4e2f9da151d5
* Version Independent ID: a50e764e-64b6-6dc4-c3d0-291abcf310b8
* Content: [Export eDiscovery search results to a PST file in the Exchange admin center in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/export-search-results)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/export-search-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/export-search-results.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @NazTeqdup, thank you for your feedback.

Could you kindly elaborate? There is a note at the begging of the article saying that this feature is retired.
