### ISSUE TITLE
Tôi đang khám phá và cần tìm hiểu thêm

### ISSUE THREAD

**Issue by xuanhoang77** [MicrosoftDocs/OfficeDocs-Exchange#3]
[Nhập phản hồi vào đây]
Tôi chưa am hiểu nhiều. Vì còn học đọc . Và mong giúp đỡ về ứng dụng này. Và hỗ trợ xử lý lỗi của tôi. 
 Thank you 

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 4c41fca7-c13b-20fe-83e6-34d91c5f9227
* Version Independent ID: 0844eadb-236e-15cb-5bbf-4963dc30a347
* Content: [Exchange Server 2016 Privacy Statement](https://docs.microsoft.com/vi-vn/Exchange/about-documentation/privacy-statement)
* Content Source: [Exchange/ExchangeServer/about-documentation/privacy-statement.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/about-documentation/privacy-statement.md)
* Product: **exchange-server-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by msdmaguire** [comment]
Thanks for commenting on our article. If you need help or assistance with Exchange, you can try our Exchange forums on TechNet: https://social.technet.microsoft.com/Forums/home .
