### ISSUE TITLE
Does not apply!

### ISSUE THREAD

**Issue by pvernocchi** [MicrosoftDocs/OfficeDocs-Exchange#30]
This section does not apply to Exchange Online!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 093d57ad-1546-f82e-84a1-df770425d5e8
* Version Independent ID: 5d288e36-fb55-00d0-5081-6e4e3223af51
* Content: [Change the offline address book generation schedule](https://docs.microsoft.com/en-us/exchange/address-books/offline-address-books/change-address-book-generation-schedule)
* Content Source: [Exchange/ExchangeOnline/address-books/offline-address-books/change-address-book-generation-schedule.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/offline-address-books/change-address-book-generation-schedule.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by msdmaguire** [comment]
Thank you for your feedback. We will look into removing this file from the Exchange Online content set.

**Comment by pstasik** [comment]
I agree.  This cmdlet is not available in Exchange Online.  Please update and show us how to perform this for Office 365.

**Comment by msdmaguire** [comment]
Thank you for your feedback. We will look into adding this information.
