### ISSUE TITLE
Missing info about target delivery domain.

### ISSUE THREAD

**Issue by GraemMcduff** [MicrosoftDocs/OfficeDocs-Exchange#3001]
Step 8 on this page is very unclear. It just says "On the Move configuration page, enter the details and then click Next."

There are a couple problems with this:
1. It should be stated that a Google Workspace migration requires a custom target delivery domain which we are instructed to set up in [Google Workspace migration prerequisites](https://docs.microsoft.com/en-us/exchange/mailbox-migration/googleworkspace-migration-prerequisites)
2.  The new EAC doesn't seem actually provide any functionality to use anything but the default onmicrosoft.com domain as the target delivery domain. It can only be done in the old ecp or via Powershell. So until that is fixed using the new EEAC for a Google Workspace migration isn't actually feasible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c741294b-65a6-e854-def3-dfff716495c6
* Version Independent ID: b45d93d1-bfc8-ffdf-b191-70fcaba31117
* Content: [Perform an automated Google Workspace migration to Microsoft 365 or Office 365 in the new EAC in Exchange Online](https://docs.microsoft.com/en-us/exchange/mailbox-migration/automated-migration-neweac)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/automated-migration-neweac.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/automated-migration-neweac.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by dariomws** [comment]
Hi @GraemMcduff, thank you for your feedback.

As you highlighted, the steps to create the subdomains are in the following article:
https://docs.microsoft.com/exchange/mailbox-migration/googleworkspace-migration-prerequisites

You should complete that article before running the steps in this one.

**Comment by GraemMcduff** [comment]
Hi. I would not have left the feedback if I had not already followed those
instructions, and at least at the time I wrote that comment, adding a
subdomain as outlined in the previous article did not make it available as
an option for the target delivery domain when creating a new migration
batch.

Nor were any of the other domains I have added options. The only option was
the default onmicrosoft.com domain, which the earlier article explicitly
states not to use. And I feel like the instructions to "enter the details
and then click Next." in this article are unclear enough that a lot of
people would just use the default domain even if other domains were
available in the drop-down. It should explicitly state to use the subdomain
created in the earlier article.

**Comment by dariomws** [comment]
Hi,

My apologies but you should be able to use the subdomain in the EAC. If you are having problems with that, please open a support ticket as here we are limited to documentation issues and improvements.

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products.

Please keep us posted here on the resolution to feed whatever information you discover into the content.

**Comment by technion** [comment]
I just want to +1 that if you follow the "prerequisite" steps @dariomws provided, the new routing domains can not be entered in the new Exchange Admin Center. These instructions are not usable, it says "enter the details and click next", but you cannot use any supplied information to provide the form with data that it accepts in order to make the "next" button work.

The resolution is that this must be done using the classic ECP or Powershell, therefore the document in its current state cannot be used.

**Comment by lantrix** [comment]
Totally concur. These instructions are unable to be used at all.

> 8. On the Move configuration page, enter the details and then click Next.

This is what the new EAC looks like at this point - you are UNABLE to _enter the details_ and click next. The pop down selector has nothing to select and the field can't be populated:
![Screen Shot 2022-04-14 at 21 35 02](https://user-images.githubusercontent.com/117008/163384343-6a5fc356-d5b9-4849-9255-372c00e2dc3c.png)

This is not an isolated problem that support will resolve, as there seems to be a longstanding bug doing this process in the new EAC as listed elsewhere ([Microsoft Answers](https://answers.microsoft.com/en-us/msoffice/forum/all/gsuite-to-office-365-new-exchange-admin-center/6f427590-f3aa-48fd-9d40-0ef7bf26d1ae), [Microsoft Docs Questions](https://docs.microsoft.com/en-us/answers/questions/463876/target-delivery-domain-missing-o365-migration.html?childToView=812744#comment-812744)).

**Comment by dariomws** [comment]
Hi everyone,

I'll report this issue.

Thanks!

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.

cc: @scanum @dariomws

**Comment by rohrsh** [comment]
So the documentation will warn users that they cannot use the new EAC for Google migrations?

**Comment by FaberfoX** [comment]
@tiburd please re open this ticket and leave open until it works, as stated, instructions provided DON'T work!
