### ISSUE TITLE
out of date

### ISSUE THREAD

**Issue by sjpals** [MicrosoftDocs/OfficeDocs-Exchange#3003]
[Enter feedback here] there is no 2-step verification

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a437a2a0-990b-ac03-40f1-3d15797d70a3
* Version Independent ID: bcebb73e-7960-32ca-e964-a6c30e25ea25
* Content: [Enable 2-step verification for your Google apps users in Exchange Online](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/enable-2-step-verification-for-google-apps)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/enable-2-step-verification-for-google-apps.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/enable-2-step-verification-for-google-apps.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @sjpals how are you?
While I dig into this, can you please detail on which step could you not follow the instructions so I try to reproduce, thank you

**Comment by get-itips** [comment]
Hello @sjpals could you see my last comment? thank you

**Comment by sjpals** [comment]
I honestly cant remember as I moved on from it and found another way. I think I was trying to follow the document and the document was out of date and very different to what I was seeing on my screen.

**Comment by get-itips** [comment]
Closing for now @scanum
