### ISSUE TITLE
COMPLETELY unclear whether options for "Choose this option when" are AND or OR 

### ISSUE THREAD

**Issue by sarahmcm** [MicrosoftDocs/OfficeDocs-Exchange#3004]
[Enter feedback here]
COMPLETELY unclear whether options for "Choose this option when" are AND or OR 
eg
Choose this option when:

Your environment has SMTP AUTH disabled.
SMTP client submission (Option 1) is not compatible with your business needs or with your device.
You only need to send messages to recipients in your own organization who have mailboxes in Microsoft 365 or Office 365; you don't need to send email to people outside of your organization.
Other scenarios when direct send may be your best choice:
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#option-2-send-mail-directly-from-your-printer-or-application-to-microsoft-365-or-office-365-direct-send)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @sarahmcm 

To my understanding, that depends on your specific situation/scenario

_Your environment has SMTP AUTH disabled_

_SMTP client submission (Option 1) is not compatible with your business needs or with your device._

Both these situations can appear at the same time or only one can be in your environment, just for example, some incompatibility to configure your device with Option 1

AND

_You only need to send messages to recipients in your own organization who have mailboxes in Microsoft 365 or Office 365; you don't need to send email to people outside of your organization._

the article later confirms:

> If your device uses direct send to try to relay an email for a recipient who doesn't have a Microsoft 365 or Office 365 mailbox, the email will be rejected.

Does that help to clarify?

Thank you and let me know if I understood you correctly,

**Comment by sarahmcm** [comment]
so that’s an OR then !

**Comment by get-itips** [comment]
@scanum
