### ISSUE TITLE
Outlook 2021 Support with Exchange 2016?

### ISSUE THREAD

**Issue by thywidi** [MicrosoftDocs/OfficeDocs-Exchange#3007]
We would like to check internally if we can migrate to the new Office 2021.
Unfortunately, the Exchange Server support matrix is still missing an entry under "Clients" for Office 2021/Outlook 2021. Could you add this?
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019

Or can you tell me directly if Outlook 2021 is supported with Exchange 2016?

Thanks a lot

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
