### ISSUE TITLE
No information on which roles are required

### ISSUE THREAD

**Issue by arbrctb** [MicrosoftDocs/OfficeDocs-Exchange#3009]
It would be helpful to know what roles are required, when retaining an Exchange server purely for management purposes. Can all roles be removed, except for the management tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @arbrctb, thank you for your feedback.

You need a fully functional Exchange server for this purpose. If you have Exchange 2013, you need at least one server with the Client Access and Mailbox roles. If you have 2016 or later, you have only one role (Mailbox).
