### ISSUE TITLE
ariticle need a review to make it strictly compliant to exchange online

### ISSUE THREAD

**Issue by francescopoli** [MicrosoftDocs/OfficeDocs-Exchange#301]
this article has been ported from the OnPremises versions of Exchange and need some fixes. 
in "Holds and the Recoverable Items folder" it mentions the quota is there to protect from potential database growth: that shall not be a concern for customers, in exchange online at least.
In "Holds and mailbox quotas" it mention to use the Set-MailboxDatabase, to fix the quota, other than the individually to the mailboxes. the command is clearly not available to EXO admins, to change DB properties.
It also mention "an event is logged in the Application event log of the Mailbox server", again app log is not exposed to exo tenant admins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c38acb1-6f67-3c4c-fa3f-7d0ca7b257c0
* Version Independent ID: 673af28f-4de4-ec12-6428-6346142d20d3
* Content: [In-Place Hold and Litigation Hold](https://docs.microsoft.com/en-us/Exchange/security-and-compliance/in-place-and-litigation-holds)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@francescopoli thanks for the heads up. Topic has been updated to align with Exchange Online; references to Exchange on-premises functionality removed.
