### ISSUE TITLE
Contradictory information about AAD Connect and syncing Public Folders - coexistence KB

### ISSUE THREAD

**Issue by Corina-github** [MicrosoftDocs/OfficeDocs-Exchange#3012]
Hi, 

We would like to signal a documentation discrepancy that one our customers complained through a support ticket. 
This is related to the information from this KB under Step 2 : **_Azure AD Connect sync doesn't synchronize mail-enabled public folders to Exchange Online. Running the following script will synchronize the mail-enabled public folders across your on-premises environment and Exchange Online._** 
and this KB https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-install-custom#optional-features under optional features mentioning 
**_Exchange mail public folders | The Exchange mail public folders feature allows you to synchronize mail-enabled public-folder objects from your on-premises instance of Active Directory to Azure AD._**

The request would be to append the reason why the sync scripts should be used or to have a modification in the other KB mentioning if it should be used or not, preferably with an explanation.

For a bit of background, the discrepancy between these 2 KBs have caused this customer to deal with duplicates caused by the sync option for PFs from the AAD Connect while believing that the  AAD Connect does not sync PFs. This caused delays in the investigation for the duplicates and could prove an issue for other customers that are not aware. 

Thank you, 
Corina Ionescu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @Corina-github, thank you for your feedback.

Actually, the difference is there in each sentence, but hard to notice:
- Azure AD Connect sync doesn't synchronize mail-enabled public folders to **Exchange Online**
- The Exchange mail public folders feature allows you to synchronize mail-enabled public-folder objects from your on-premises instance of Active Directory to **Azure AD**

You need to synchronize PFs to Azure AD if you want to use:
https://docs.microsoft.com/exchange/mail-flow-best-practices/use-directory-based-edge-blocking
More information:
https://techcommunity.microsoft.com/t5/exchange-team-blog/office-365-directory-based-edge-blocking-support-for-on-premises/ba-p/606740

**Comment by Corina-github** [comment]
Thank you for the clarification, Dario.
So I understand the 2 options serve different purposes and relate to
different backend components, therefore the info in the KB is not to be
changed.
Do you by any chance know if they can be used together without expecting
issues?

Thank you again,
Corina

**Comment by dariomws** [comment]
Hi @Corina-github,

I think so but I'm not sure. They are different processes so I think you should be able to use them together.

**Comment by Corina-github** [comment]
Thank you for your help, Dario!
Much appreciated :)

I'll go back with this to the customer and see if I can find out more about
using the 2 options together, as that was also a concern point when we
thought it was contradicting info.

We can consider this closed.

Have a great day/weekend!
Corina

**Comment by dariomws** [comment]
Thank you for your feedback again @Corina-github, we appreciate it!

Have a great day/weekend!
