### ISSUE TITLE
The email address published in this article blocks external senders

### ISSUE THREAD

**Issue by MattRose-CC** [MicrosoftDocs/OfficeDocs-Exchange#3014]
The email address published in this article blocks external senders. why include it?

modernddgsupport@service.microsoft.com

Reported error: | 550 5.7.193 UnifiedGroupAgent;   Delivery failed because the sender isn't a group member or external senders   aren't permitted to send to this group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b225d9c-90c7-4b93-b66c-47b435c83e90
* Version Independent ID: 3f6ad047-c00c-df59-4886-9d827f7a147a
* Content: [Modern dynamic distribution groups in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-dynamic-distribution-groups/modern-dynamic-distribution-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/modern-dynamic-distribution-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/modern-dynamic-distribution-groups.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by MattRose-CC** [comment]
That Email address is included in the messaging sent in bulk to all tenant admins yesterday, it is included in this DOC obviously, and included in the admin center notification pane. It really should be available to external senders. a big oversight on someone's part.

That being said, if you could forward the following to that team, since ther is no way for the public to reach them at the moment:


Hello,
Since you are reworking dynamic distribution groups, It would be extremely important to address the long standing issue that the object for a DDG is not present in Azure AD.

Right now the only option to allow external senders to email DDGs is to disable DBEB - REDUCING the overall security posture for the tenant.

To be able to have external senders not be blocked by DBEB while emailing DDGs would be ideal

Source:
Dynamic distribution groups do not sync to Azure AD and are therefore blocked by DBEB. As a workaround in hybrid environments, you can create a mail contact with the same external email address of the blocked dynamic distribution group. In cloud-only environments, this workaround will not work. To use dynamic distribution groups that receive email from external senders in cloud-only environments, you need to disable DBEB (change the domain from Authoritative to Internal relay).
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking

**Comment by get-itips** [comment]
Hello @MattRose-CC 
The email address you mention was removed from the article in a recent edit https://github.com/MicrosoftDocs/OfficeDocs-Exchange/commit/5477b224c1508abe5a6f8fdc58432360166d7209

Thank you for your feedback!
