### ISSUE TITLE
Steps for creating mail-enabled security are wrong

### ISSUE THREAD

**Issue by Baryczka** [MicrosoftDocs/OfficeDocs-Exchange#3015]
Link to anchor [here](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-enabled-security-groups#use-the-new-eac-to-create-a-mail-enabled-security-group)

Steps for creating mail-enabled security are wrong and probably copied from M365 group.
There is no step to add members(can be added later), neither Microsoft Teams support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0dd3fb4-76a1-4983-dc7a-f5cd7fb35507
* Version Independent ID: 469b3ec9-f9b1-ff8a-baaa-712114808755
* Content: [Manage mail-enabled security groups in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-enabled-security-groups)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-enabled-security-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-enabled-security-groups.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by lindspea** [comment]
@Baryczka thank you for reaching out. I'll do some investigating, but in the meantime do you have any suggestions for the change you recommend for the article to be more accurate.

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.

cc: @scanum
