### ISSUE TITLE
Ambiguous and potentially incorrect information given here...

### ISSUE THREAD

**Issue by deejerydoo** [MicrosoftDocs/OfficeDocs-Exchange#3017]
"Use the new EAC to automatically save sent items in the delegator's mailbox
In the new EAC, navigate to Recipients > Mailboxes.
In the list of user mailboxes, click the mailbox that you want to configure the sent items to be saved for the delegator. A display pane is shown for the selected user mailbox.
Under Mailbox settings, click Manage mailbox delegation.
In the Manage mailbox delegation settings, do the following.
In the Send on behalf row, click Edit.
Click Add permissions.
Check the checkbox of the person whom you want to configure as the delegate.
Click Save to save your change. A message Manage mailbox delegation settings updated successfully is displayed. Click Close to exit."

This strikes me as ambiguous and potentially wrong. Are we applying the delegate privileges here or are we setting the sent items behaviour? This looks suspiciously like we are just setting the delegate rights, there is nothing in the EAC UI to suggest what we are actually doing here has any effect on the sent items behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d3a998a-6ea1-b3b2-76d2-4de65962bbda
* Version Independent ID: 2911c776-0c9a-06f3-a4ab-99713ed87b76
* Content: [Automatically save sent items in delegator's mailbox in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/automatically-save-sent-items-in-delegator-s-mailbox)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/automatically-save-sent-items-in-delegator-s-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/automatically-save-sent-items-in-delegator-s-mailbox.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by deejerydoo** [comment]
The more I read this article the more I am coming to the conclusion that the key point of failure is one of the headings simply wrong:

"Use the new EAC to automatically save sent items in the delegator's mailbox"

This section doesn't cover how to use the new EAC to automatically save sent items in the delegator's mailbox. All this section covers is how to set the delegate, in the EAC.

There is actually no way, currently, to use the EAC to set Exchange to automatically save sent items in the delegator's mailbox.

The only place I have been able to find, anywhere on the Microsoft portal, where the sent items behaviour can be modified is for shared mailboxes only, under "Sent items". When you select to edit this item you are presented with a page that states: Manage sent items
Copy items sent as this mailbox, or on behalf of this mailbox, to the mailbox's Sent Items folder. This lets shared mailbox members see the email other members have sent.
If you don't copy sent items to the mailbox, they will only be saved to the sender's Sent Items folder."

The new EAC is missing this feature completely, for regular user mailboxes and even for shared mailboxes.

**Comment by get-itips** [comment]
Hello @deejerydoo looking into this

**Comment by deejerydoo** [comment]
To receive an email that simply states "Closed" and nothing else strikes me as unnecessarily curt.

Thanks for your help in resolving this matter everyone.

I appreciate we're all very busy here but a little courtesy goes a long way. We're all real people in this process...

**Comment by chrisda** [comment]
@deejerydoo, @get-itips, honest to God, I did not close this, at least not on purpose. I merged the corresponding pull request (#3033), but I swear I didn't muck with this issue.

**Comment by get-itips** [comment]
> To receive an email that simply states "Closed" and nothing else strikes me as unnecessarily curt.
> 
> Thanks for your help in resolving this matter everyone.
> 
> I appreciate we're all very busy here but a little courtesy goes a long way. We're all real people in this process...

Hello @deejerydoo 
The issue is closed when the Pull Request that updates the article is merged, you can see the update [here](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/3033) 
Thanks to your feedback, we could update the article with the current behavior.
Thanks again!
