### ISSUE TITLE
Translated sentence in japanese contains opposite meaning

### ISSUE THREAD

**Issue by az13ogura** [MicrosoftDocs/OfficeDocs-Exchange#3019]
Although digital signatures provide data integrity, they don't provide confidentiality. 
デジタル署名はデータの整合性を提供しますが、機密性は提供されます。

I think

NG 提供されます。
OK 提供されません。
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 146e1dad-3eff-cf6b-19aa-a859c92ac178
* Version Independent ID: 01f13ce8-3d11-9a09-5c3c-a01d9a51f887
* Content: [S/MIME in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/smime-exo/smime-exo#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/smime-exo/smime-exo.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/smime-exo/smime-exo.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by TinaMcN** [comment]
@az13ogura thank you for providing the feedback.   The Japanese article has and appears to be fixed now.  The text is デジタル署名はデータの整合性を提供しますが、機密性は提供されません。
![image](https://user-images.githubusercontent.com/53281468/168877816-8ca51fd8-2af0-4825-a726-d33f21902e84.png)
Can you please confirm if it is ok now?

**Comment by TinaMcN** [comment]
I believe this issue is fixed now.  @scanum can you please close it?

**Comment by tiburd** [comment]
@TinaMcN 
Thank you! Closing this issue.

cc: @scanum
