### ISSUE TITLE
Document needs to include details about eDiscovery & Legal Hold considerations

### ISSUE THREAD

**Issue by jwojan** [MicrosoftDocs/OfficeDocs-Exchange#3023]
[Enter feedback here]
This document is incomplete. It should have in it a section on considerations for mailboxes that are on Legal Hold in both Core and Advanced eDiscovery. There are some specific concerns around the prerequisites as noted in the following documentation: (https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide#prerequisites-for-target-user-objects) that state that the RecoverableItems over 30Gb may fail to migrate, but nothing is noted or linked to in this material about how to preserve/migrate those Legal Hold/eDiscovery settings in order to maintain the full continuity of chain of custody with regards to these legal considerations on these mailbox(es)/item(s).

This is a gap in the current documentation and one that is asked several times on Social.Technet without any definitive answers or guidance. As a result, this is a need we need to fill in our documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Microsoft 365 or Office 365 organization to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.

cc: @scanum @dariomws

**Comment by jwojan** [comment]
It doesn't look like anything was changed. Why are we just passing around suggestions instead of actually correcting the holes in the content?
