### ISSUE TITLE
Witness server version

### ISSUE THREAD

**Issue by perhof** [MicrosoftDocs/OfficeDocs-Exchange#303]
This articles states that _"The witness server must be running Windows Server 2012, Windows Server 2008 R2, Windows Server 2008, Windows Server 2003 R2, or Windows Server 2003."_

This information feels a bit dated.
Is it really true that a brand new product requires an operating system that is six years old?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb3a712-50d2-74d9-b319-8900b6b01bae
* Version Independent ID: aa5f5c47-b8f0-f623-fb6e-a30eec11cee9
* Content: [Manage database availability groups](https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/manage-dags?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/high-availability/manage-ha/manage-dags.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/manage-ha/manage-dags.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by MishaTravis** [comment]
@perhof  - Thank you for submitting this feedback.

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by dariomws306** [comment]
Hi @perhof , thank you for your feedback. I am removing Windows Server 2003 from this article.
