### ISSUE TITLE
IgnoreNamingPolicy not done on Exchange Admin Centre (EAC)

### ISSUE THREAD

**Issue by haneef95** [MicrosoftDocs/OfficeDocs-Exchange#3030]
Hi,

The classic ECP used to `IgnoreNamingPolicy`, however, the new EAC does not `IgnoreNamingPolicy` as suggested in this article,

Please fix the doc or the new EAC.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3788cc9-87d3-6634-95f6-8227f74642a3
* Version Independent ID: 5fc77421-6377-eb9d-b523-d718cb1d3843
* Content: [Override the distribution group naming policy in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-distribution-groups/override-group-naming-policy)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/override-group-naming-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-distribution-groups/override-group-naming-policy.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback that improves docs!

**Comment by haneef95** [comment]
to be honest, I would prefer that the new EAC is fixed with an additional checkbox to `IgnoreNamingPolicy`, which the old ECP used to do by default, or at least the same behaviour as the old ECP.

**Comment by get-itips** [comment]
> Welcome, happy to! To be honest, I would prefer that the new EAC is fixed with an additional checkbox to `IgnoreNamingPolicy`, which the old ECP used to do by default, or at least the same behaviour as the old ECP.

Hello @haneef95 we are limited to documentation changes and improvements.

**Comment by haneef95** [comment]
No way for you guys to raise this with thy relevant team internally? @get-itips

**Comment by get-itips** [comment]
> No way for you guys to raise this with thy relevant team internally? @get-itips

Hello @haneef95 Haneef, unfortunately I can not reach the team, the best way to provide feedback to reach the product team is the [feedback portal](https://feedbackportal.microsoft.com/feedback/) and also the feedback option inside Microsoft 365 admin.

**Comment by haneef95** [comment]
Yes done the feedback option on the admin portal... A while back... No response still!
