### ISSUE TITLE
Make Up Your Minds!!!!

### ISSUE THREAD

**Issue by MHCLV** [MicrosoftDocs/OfficeDocs-Exchange#3040]
[Enter feedback here]
Separately from why you insist on enabling something by default that used to be disabled by default. e.g., Plus Addressing, why do you not do it right and put the setting in the Exchange Admin center???   

There is already a setting in it, so why not expend just a teeny, tiny bit of effort to make the thing work the way you require everyone to use PowerShell to do.   Strange is it might seem to you, there are a lot of folks who do not spend their lives staring at a command prompt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2481-2a27-06f3-976c-90614a863d81
* Version Independent ID: a3c4f846-0578-54ed-f2a8-c511be3605af
* Content: [Plus Addressing in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by BuckNYC** [comment]
Totally agreed! There are times MSFT does not take into account the needs of smaller companies that don't have "endless access" to deep IT departments.   21st century problems require 21st century solutions.  C'mon MSFT, do better!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
