### ISSUE TITLE
Mail Flow Rules and "Plus Addressing"

### ISSUE THREAD

**Issue by thaBo77** [MicrosoftDocs/OfficeDocs-Exchange#3041]
The Plus Addressing is a nice feature for End Users. Not sure if I like it from an administrator's perspective. Any 'Mail Flow Rule' can now easyly be bypassed. How to avoid this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2481-2a27-06f3-976c-90614a863d81
* Version Independent ID: a3c4f846-0578-54ed-f2a8-c511be3605af
* Content: [Plus Addressing in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/plus-addressing-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by get-itips** [comment]
Hello @thaBo77 
A method to opt-out of/disable this feature has been added to the article.
Let me know if you could see it and if it answers your question.
Thank you

**Comment by get-itips** [comment]
@scanum
