### ISSUE TITLE
Manage Delegation GUI only shows display name instead of UPN

### ISSUE THREAD

**Issue by speckles0** [MicrosoftDocs/OfficeDocs-Exchange#3042]
Not exactly specific to this page but EAC as a whole; the new GUI for managing delegation only shows the display name of a user instead of the UPN when you go to add a member. This should be updated to show the UPN so that people with the same name, like in my screenshot, are not given permissions by accident. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe24386f-86cc-5073-dc17-ad8ece0e3dc7
* Version Independent ID: 88a529c7-c6e6-8438-8eb4-c6fc2a20f722
* Content: [Manage permissions for recipients in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-permissions-for-recipients)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr*
![delegation1](https://user-images.githubusercontent.com/88895472/159303507-9759932f-6d3c-48fb-ad09-d800ab3d93e7.png)
![delegation2](https://user-images.githubusercontent.com/88895472/159303511-35b20b88-d130-44b6-8f43-763c49a57bc0.png)
*

**Comment by get-itips** [comment]
Hello @speckles0 how are you?

Thanks for your feedback, here, we are limited to documentation changes and improvements, I think your inquiry it's better suited for the product team, to reach the product team, the best way to provide feedback is the [feedback portal](https://feedbackportal.microsoft.com/feedback/) and also the feedback option inside Microsoft 365 admin.

Hope this information helps you,

**Comment by get-itips** [comment]
@scanum
