### ISSUE TITLE
Application passwords

### ISSUE THREAD

**Issue by lesnikowski** [MicrosoftDocs/OfficeDocs-Exchange#3044]
There is no information if application passwords would work after this or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19cf826a-aaf1-91ed-8a8f-637d869e47df
* Version Independent ID: 61d69fb6-184d-acf5-8b02-39b3d885d28b
* Content: [Deprecation of Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @lesnikowski, thank you for your feedback.

The deprecation of basic authentication will also prevent the use of app passwords with apps that don't support two-step verification. I'm adding a note to the article.
