### ISSUE TITLE
Navigate to Compliance management > In-Place eDiscovery & hold.

### ISSUE THREAD

**Issue by fixx-er** [MicrosoftDocs/OfficeDocs-Exchange#3045]
[Enter feedback here]
The New EAC does not show Compliance management as described

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a137ee50-f3b9-07e1-7214-58d282896a66
* Version Independent ID: 70fc82e3-88f8-bc68-a094-37b81c778038
* Content: [Remove an In-Place Hold in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/create-or-remove-in-place-holds)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/create-or-remove-in-place-holds.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @fixx-er, thank you for your feedback.

There is a note at the beginning of the article:

> [!IMPORTANT]
>  As we continue to invest in different ways to preserve mailbox content, we're announcing the retirement of In-Place Holds in the Exchange admin center (EAC) in Exchange Online. Starting July 1, 2020, you won't be able to create new In-Place Holds. But you'll still be able to manage In-Place Holds in the EAC or by using the **Set-MailboxSearch** cmdlet in Exchange Online PowerShell. However, starting October 1, 2020, you won't be able to manage In-Place Holds. You'll only be remove them in the EAC or by using the **Remove-MailboxSearch** cmdlet. Using In-Place Holds in Exchange Server and Exchange hybrid deployments will still be supported. For more information about the retirement of In-Place Holds in Exchange Online, see [Retirement of legacy eDiscovery tools](/microsoft-365/compliance/legacy-ediscovery-retirement).

We are keeping this article for legacy reference. The steps here are using the classic EAC which will be retired in September.
I recommend that you use Remove-MailboxSearch cmdlet if you need to remove In-Place Holds.

More information:
https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-the-classic-exchange-admin-center-in-ww-service/ba-p/2736358

**Comment by fixx-er** [comment]
thanks very much.  I will review in some days here.  I believe it is all good 🙂
________________________________
