### ISSUE TITLE
Cannot find the roles

### ISSUE THREAD

**Issue by danim-hub** [MicrosoftDocs/OfficeDocs-Exchange#3049]
I am trying to follow your instructions, but it is not clear how to add the roles for the service account.
The Create Service Account is under the category "Service Accounts", and the "Create Project" I understand that should be under "Resource Manager" but I am cannot find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec9bdfa-e5f7-a869-514d-0e6ae50ff7e9
* Version Independent ID: 87521d1b-8d1b-0648-9059-347cdae9d3f7
* Content: [Google Workspace migration prerequisites in Exchange Online](https://docs.microsoft.com/en-us/exchange/mailbox-migration/googleworkspace-migration-prerequisites)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/googleworkspace-migration-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/googleworkspace-migration-prerequisites.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by get-itips** [comment]
Hello @danim-hub I am looking into this

**Comment by stryqx** [comment]
Both roles should be added by navigating to IAM & Admin > Manage Resources.
The appropriate resource should then be selected and in the right-hand pane under the Permissions tab click on Add Principal.
Enter the Google Migration Admin principal, type in "project creator" into the Filter and select Project Creator.
Click Add Another Role, type in "create service accounts" into the Filter and select Create Service Accounts.
Click Save.
Expand Create Service Accounts and Project Creator under the Role/Principal panel and verify that the Google Migration Admin principal has been added to these roles.
You should then be able to proceed with the migration.

**Comment by get-itips** [comment]
Thanks @stryqx Chris for your contribution!
