### ISSUE TITLE
Required role not stated

### ISSUE THREAD

**Issue by rufioIK708** [MicrosoftDocs/OfficeDocs-Exchange#3053]
This document does not state what roles are able to make this change.  Global Administrator is obvious, but what about Exchange Administrator or any other role?  If it was explicitly stated that the GA could make the change, it would at least be implied that no other role could.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable or disable modern authentication for Outlook in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @rufioIK708 

I used this other article
[Use PowerShell to find the permissions required to run a cmdlet](https://docs.microsoft.com/en-us/powershell/exchange/find-exchange-cmdlet-permissions?view=exchange-ps#use-powershell-to-find-the-permissions-required-to-run-a-cmdlet)

and that reveals that Organization Management is the required role group to be able to run `Set-OrganizationConfig -OAuth2ClientProfileEnabled $true`

More information https://docs.microsoft.com/en-us/exchange/permissions-exo/permissions-exo

Hope this information helps you

**Comment by get-itips** [comment]
@scanum
