### ISSUE TITLE
Emphasize bi-directional organization relationship setup is mandatory

### ISSUE THREAD

**Issue by jianhsieh** [MicrosoftDocs/OfficeDocs-Exchange#3054]
Hi Team,

I would like to suggest adding the requirement that organization relationship needs to be setup bi-directionally as I've recently came across a service request which customer went through the document to setup only one-way as they didn't need Free/Busy in the opposite direction. However, it will not work at all unless bi-directionally setup.

Thanks.

Regards,
Andy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e64e56f9-fbf4-f072-637b-5fa8e827a399
* Version Independent ID: 32a37550-af95-a0ce-2941-ff9ce7ba9150
* Content: [Create an organization relationship in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/create-an-organization-relationship)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @jianhsieh, thank you for your feedback.

That information is included in the overview article: https://docs.microsoft.com/exchange/sharing/organization-relationships/organization-relationships

"An organization relationship is a one-to-one relationship between businesses to allow users in each organization to view calendar availability information. When you set up the organization relationship, you're responsible for setting up your side of the relationship. You specify the level of information that users in the external organization can view in your organization. The external organization is responsible for setting up their side of the relationship and specifying their level of information that's visible to users in your organization (which might be different than yours). The point is: the organization relationship must be set up at both ends for calendar availability information to be shared."
