### ISSUE TITLE
Feedback on mentioning license requirements

### ISSUE THREAD

**Issue by singhishita** [MicrosoftDocs/OfficeDocs-Exchange#3055]
[Hi team, I don't see any specific license requirements mentioned in this page. Whereas, in the article that talks about creating alert policies from the Defender Portal (https://docs.microsoft.com/en-us/microsoft-365/compliance/alert-policies?view=o365-worldwide), we have specific license requirements. Can we assume the same requirements here as well, since the purpose is same? Request your comment on this. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e441f38-8a36-7e4d-2729-647064dc906a
* Version Independent ID: 6e2fc705-0baf-b2be-aba3-97cbbf3cb0ea
* Content: [Alert policies in Exchange Online](https://docs.microsoft.com/en-us/exchange/monitoring/mail-flow-insights/alert-policy-and-its-configuration#create-alert-policy)
* Content Source: [Exchange/ExchangeOnline/monitoring/mail-flow-insights/alert-policy-and-its-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/mail-flow-insights/alert-policy-and-its-configuration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @v-smandalika
* Microsoft Alias: **v-smandalika**

**Comment by get-itips** [comment]
Hello @singhishita how are you?

In the _Alert policies_ in the new EAC, a link "learn more about alert policies" takes you to the article that you linked about creating alert policies **from the Defender Portal**, and also Exchange alert policies show up in the defender portal as mail flow category so I think, for the ones related to Exchange we can think the same licensing is required, however, I'll try to confirm.

**Comment by get-itips** [comment]
FYI An update is coming to the article
