### ISSUE TITLE
Video and Page text do not match

### ISSUE THREAD

**Issue by BlueVaGTO** [MicrosoftDocs/OfficeDocs-Exchange#3056]
[Enter feedback here]
The video says that Exchange 2013 and 2016 is supported on a Hybrid deployment.  1:58 in the video.

The document on the page does not mention 2016.  We can assume that 2013 is the same as 2016, but IT guys know that assumptions cause errors.  Be specific and mention 2016 if it is supported, and 2019 if it is supported.

Quoted from the page:

Migrate using an integrated Exchange Server and Microsoft 365 or Office 365 environment (hybrid)

Use this type of migration to maintain both on-premises and online mailboxes for your organization and to gradually migrate users and email to Microsoft 365 or Office 365. Use this type of migration if:

You have Exchange 2010 and more than 150-2,000 mailboxes.

You have Exchange 2010 and want to migrate mailboxes in small batches over time.

You have Exchange 2013.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54d88bea-98ed-5884-ba22-6343f1737caa
* Version Independent ID: 40de1e1c-a2c6-590d-375f-c860aa8524d1
* Content: [Ways to migrate multiple email accounts to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/mailbox-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/mailbox-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/mailbox-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by BlueVaGTO** [comment]
Why is this closed with no assistance?

Wayne
Wayne Hedrick, MCP, SBS
JK Technologies
www.jktechnologies.com<blocked::blocked::http://www.jktechnologies.com/>
Office: 757-291-5545
Fax: 757-299-8205
***@***.******@***.***>
Microsoft Teams:  ***@***.******@***.***>
Skype name:  waynehedrick
**************

**Comment by dariomws** [comment]
@BlueVaGTO, the article was updated based on your feedback.
