### ISSUE TITLE
original Deck for this image?

### ISSUE THREAD

**Issue by dcaddick** [MicrosoftDocs/OfficeDocs-Exchange#3057]
Hi,

Any idea where I might be able to find the original Deck for this image? just a random Q as I'm trying to build a comprehensive process for helping customers understand the before/after "vision" of the change to MDO and this way we can "leverage" MS's docs/library/images to help the customer understand what they have now vs. what we are proposing.

It's somewhat concerning that most clients don't understand their own current/existing mailflow - so in one way we can add value just by helping them understand what it is *now* - but at the same point it helps us, and then also helps the client in understanding how the switch to MDO will benefit them.

![image](https://user-images.githubusercontent.com/19640455/160793494-d85176e5-dc99-4076-ba95-d07fa1456a4c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6130dd-6f13-b63d-2733-9bf91fd4a6e0
* Version Independent ID: 58835922-47d9-79df-0239-b38b53506193
* Content: [Manage mail flow with mailboxes in multiple locations (Exchange Online and on-premises Exchange) in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-for-multiple-locations)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-for-multiple-locations.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-for-multiple-locations.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @dcaddick David, how are you?

I tried to track down the original (editable) format of that file but unfortunately I could not. (File was created more than 4 years ago). I could recognize it was made in Visio.

Hope this information helps you,

**Comment by get-itips** [comment]
@scanum
