### ISSUE TITLE
Scripts perform Basic Authentication to Exchange Online

### ISSUE THREAD

**Issue by kortamon** [MicrosoftDocs/OfficeDocs-Exchange#3061]
Hello, I have noticed the scripst included in this article use Basic Authentication to connect to EXO.
Is there any plan to update this?
The current MSFT's recommendation is to move away from these protocols. It will be fully deprecated on October this year
Depending on the feature used to control/block basic authentication, sometimes you won't have a sign-in log, complicating the troubleshooting.

If there is no plan to update the scripts, it would be appropiate to notify this caveat in the article

Looking forward hearing from you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders#step-1-download-the-scripts)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
@kortamon, thank you for your feedback.

I'm told this is a known issue, and there are plans to update the script. I cannot provide an ETA, but it should be available soon.

**Comment by dariomws** [comment]
Hi @kortamon,

The script was updated, please check the following article:
https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-public-folder-migration-scripts-with-modern/ba-p/3382800
