### ISSUE TITLE
Incorrect reference to Permissions menu option in EAC

### ISSUE THREAD

**Issue by ConstantGH** [MicrosoftDocs/OfficeDocs-Exchange#3068]
The Exchange admin center has no "Permissions" option, as described in the text. The old EAC portal had, but the new one doesn't. The text should be updated since the new EAC is swichted on by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a3732b-86d4-53eb-22a6-8e6feec5ceeb
* Version Independent ID: 1a67364d-2277-1253-23ff-28b0acfe861b
* Content: [View or configure Outlook on the web mailbox policy properties in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/configure-outlook-web-app-mailbox-policy-properties)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/configure-outlook-web-app-mailbox-policy-properties.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/configure-outlook-web-app-mailbox-policy-properties.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
