### ISSUE TITLE
exchange 2019 prereq article - iis rewrite module step needs needs to go after step 3

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#3070]
in this article: https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prerequisites?view=exchserver-2019#windows-server-2019-prerequisites-for-exchange-2019

step 1.d needs to go after step 3, otherwise it will throw an error complaining about the lack of iis

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Mike-Crowley** [comment]
I do not have a technical problem, am filing a doc bug and you closed it without even understanding when I wrote.

**Comment by Mike-Crowley** [comment]
@scanum  please re-open this issue. As I mentioned above, this article is incorrect. You obviously cannot install an IIS module before IIS is present. Here is the error someone would get if they followed this article.

https://imgur.com/a/loG6N5u
