### ISSUE TITLE
Mailtips |  online version of outlook

### ISSUE THREAD

**Issue by Skurrvie** [MicrosoftDocs/OfficeDocs-Exchange#3071]
It's not possible to activate mailtips when using the online version of outlook. Currently on a linux-machine with ubuntu 21.10. 
The only thing I can add (through o365) is a "mailtip" that just displays a message when sending a mail to the chosen mail-address.
Is there no way (while using the online-version of outlook) to add some sort of safeguard to sending mail to many recipients?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
