### ISSUE TITLE
Document is uncompleted and bug

### ISSUE THREAD

**Issue by walvis-am** [MicrosoftDocs/OfficeDocs-Exchange#3072]
Hello team, 
I want to report an incomplete documentation and a bug.

I am referring to the article "**Perform an automated Google Workspace migration to Microsoft 365 or Office 365 in the new EAC in Exchange Online**" https://docs.microsoft.com/en-us/exchange/mailbox-migration/automated-migration-neweac

Specifically, at the point **8. On the Move configuration page, enter the details and then click Next.**
There, admins should add the **Target delivery domain** manually since the dropdown list will not show any domain.
The Classic EAC has the same issue with the dropdown list but at least the classic EAC allows you to write the domain needed and the documentation for this legacy wizard makes mention about it **but the documentation for this new EAC makes not mention at all about this limitation** and **the bug there doesn't allow you to wring anything**

Classic EAC 
Perform Google Workspace Migration to Microsoft 365 or Office 365 in Classic EAC in Exchange Online
https://docs.microsoft.com/en-us/exchange/mailbox-migration/manual-gspace-migration-classiceac

See point 9 note: 
The target delivery domain you will want to use will not automatically show up in the dropdown - instead you should click within the text box and type it in. The target delivery domain must be different from the primary domain of the users in Google Workspace.

Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by walvis-am** [comment]
Hello Manuela, 
My apologies, I guess you didn't understand my feedback. I am submitting a request for something that is missing in the documentation that also is a bug. I am not submitting a bug with this team, I am a Microsoft Full time employee I am know where to submit a bug. My intention, again, is that the team working on public documentation be aware about what is missing. 
If providing feedback through public documentation is not the best way to fix a Microsoft article, please let me know how can I provide feedback to the correct team to finally add something that is missing from the article and our clients are looking for to see since the article about do the same thing but using the Classic EAC, has the correct note. 
thanks
