### ISSUE TITLE
PQMT: [Exchange admin center]The description of "original_client_ip" is not appropriate

### ISSUE THREAD

**Issue by Sayuri-Kaseda** [MicrosoftDocs/OfficeDocs-Exchange#3080]
[Document URL]
https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/message-trace-modern-eac 

[Description]
The description of "original_client_ip" is not appropriate.
In the public information, it is "The IP address of the sender's client", but the information actually obtainable in the report was the IP address of the server, etc., from which the message was generated.
The current explanation may mislead people into thinking that it is possible to obtain the IP address of a PC.

[Actual result]
original_client_ip: The IP address of the sender's client.

[Expected result]
original_client_ip: The IP address of the server or other entity from which the message was generated.

[Repro]
1. Access to Exchange admin center.
2. Click "Mail Flow" > Message trace to download reports.

[Source]
Japan Internal Feedback

[Copied from]
https://microsoft.sharepoint.com/:li:/t/ntojapan/pqmt/EwehEcsMTSVOnTy7k5uC0_QBmzKMzUWNlGe_bgDvUHBwLw?e=NgOkbb
![20220420](https://user-images.githubusercontent.com/103735276/164183796-7bf1fd87-2c45-4167-b5c0-dcf6387946c0.jpg)

**Comment by get-itips** [comment]
Hello @Sayuri-Kaseda I am looking into this, thanks
