### ISSUE TITLE
1st sentence is wrong?

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#3081]
The first sentence says:

"In Exchange Hybrid environments, you must have an active Exchange Server to manage recipients attributes."

but then the rest of the article goes on to demonstrate how this is not true. Perhaps it should say: "PREVIOUSLY, in Exchange Hybrid environments..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dee5b3e-6d8d-ca7e-a0c3-96d01c9a95f1
* Version Independent ID: f160f2ac-f965-c218-eba3-59909c4336bb
* Content: [Manage recipients in Exchange Server 2019 Hybrid environments](https://docs.microsoft.com/en-us/Exchange/manage-hybrid-exchange-recipients-with-management-tools)
* Content Source: [Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @Mike-Crowley, thank you for your feedback.

I am proposing some updates in this paragraph. The situation is not really related to the Exchange hybrid environment but to directory synchronization.
By definition, if you have an Exchange Hybrid environment it's expected that you have mailboxes on-premises and Exchange servers.

**Comment by Mike-Crowley** [comment]
Thanks for the conversation. I don't agree with this however:

>By definition, if you have an Exchange Hybrid environment it's expected that you have mailboxes on-premises and Exchange servers.

a hybrid environment is the result of running the hybrid configuration wizard, which includes ~100 different settings within. Also the term is often used generically throughout. I know many customers that remain in a hybrid environment specifically for cloud recipient management, which is the reason they would be interested in this article.

**Comment by dariomws** [comment]
I agree with this "Also the term is often used generically throughout.", this was always a matter of confusion. But the reason to keep the Exchange on-premises never was the Exchange Hybrid or HCW itself, it was directory synchronization.
The following article was updated several times and now it's well explained I think:
https://docs.microsoft.com/exchange/decommission-on-premises-exchange#why-you-may-not-want-to-decommission-exchange-servers-from-on-premises

Why and how will we run the HCW if there are no mailboxes on-premises?

**Comment by Mike-Crowley** [comment]
I'm just saying that hybrid is the natural state of any migration, even after the last mailbox is moved. often customers still use the on-prem servers for various administrative functions, such as ECP's recipient administration, various smtp scenarios, autodiscover, etc.

**Comment by dariomws** [comment]
This is what I'm proposing:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/3136/files

**Comment by Mike-Crowley** [comment]
This addresses my concern, thank you!
