### ISSUE TITLE
More clarity on needing an exchange server or not

### ISSUE THREAD

**Issue by yayoi-k** [MicrosoftDocs/OfficeDocs-Exchange#3085]
These lines under "Will this work for me" are somewhat confusing and could appear to contradict one another:

_An updated version of the Exchange Management Tools can eliminate the need for running Exchange server if all of the following are true:
- Run only one Exchange server and only for recipient management purposes
- Want to manage recipients without running any Exchange servers._

Is this saying that if you are in the 'state' of only running one exchange server only for recipient mgmt purposes, you can then get to a new state of not having to run the one exchange server if one installs just the exchange 2019 mgmt tools?  The new state requires shutting down the exchange server and erasing it, but not uninstalling exchange from it?

Is an exchange 2019 license required in order to run the exchange 2019 mgmt tools.  Previously an Exchange 2016 or prior key was available when running Hybrid mode, but not Exchange 2019 or newer.  Is a license required to run just the mgmt tools?  If you cannot answer the licensing question, please do address my first feedback above.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dee5b3e-6d8d-ca7e-a0c3-96d01c9a95f1
* Version Independent ID: f160f2ac-f965-c218-eba3-59909c4336bb
* Content: [Manage recipients in Exchange Server 2019 Hybrid environments](https://docs.microsoft.com/en-us/Exchange/manage-hybrid-exchange-recipients-with-management-tools)
* Content Source: [Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JoanneHendrickson** [comment]
@yayoi-k   Thank you for your feedback!  I have added more info that hopefully will make this clearer.  There was a warning at the very end about not uninstalling the server but that info needs to be called out earlier and be more prominent.

First, shutting down the server is optional.  You can still use this method to manage your recipients and leave your server running if you only run the Exchange server for recipient management. 

No new license is required.

**DO NOT** uninstall the last server. You can choose to shut down the server, and use the script to clean up, but DO NOT uninstall. Uninstalling the server removes critical information out of Active Directory that results in breaking the management tool package to manage Exchange attributes.

Hope this helps!  Thanks again for your feedback.  Joanne
