### ISSUE TITLE
Fix Acronym

### ISSUE THREAD

**Issue by MicrosoftGuyJFlo** [MicrosoftDocs/OfficeDocs-Exchange#3087]
Acronym should never be AAD https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25369

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dee5b3e-6d8d-ca7e-a0c3-96d01c9a95f1
* Version Independent ID: f160f2ac-f965-c218-eba3-59909c4336bb
* Content: [Manage recipients in Exchange Server 2019 Hybrid environments](https://docs.microsoft.com/en-us/Exchange/manage-hybrid-exchange-recipients-with-management-tools)
* Content Source: [Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback!
