### ISSUE TITLE
Adding info about Outlook client 

### ISSUE THREAD

**Issue by nitishkanu820** [MicrosoftDocs/OfficeDocs-Exchange#3088]
Can we add somewhere like a note or something telling this will impact Outlook client as well? 
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d2c66-f9d8-7ac2-55c8-1ccfbe966bf6
* Version Independent ID: 3dc90f07-c2bb-9f37-82c2-a713f0b8f27c
* Content: [What happened to delivery reports? in Exchange Online](https://docs.microsoft.com/en-gb/exchange/monitoring/what-happened-to-delivery-reports-in-office-365)
* Content Source: [Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
hello @nitishkanu820 how are you?

I believe that is covered by 

> Delivery reports for users have been discontinued and there is currently no direct replacement. 

Thanks for your feedback,

**Comment by get-itips** [comment]
@scanum
