### ISSUE TITLE
Details on Internal Routing

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#309]
Please add details on how internal mail is transported, specifically with centralized transport enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b002f0ce-5397-15cb-4c60-0eaaa87aaf52
* Version Independent ID: 32e3a594-2d2c-9f8a-9a38-e60e3ffaae85
* Content: [Transport routing in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/transport-routing)
* Content Source: [Exchange/ExchangeHybrid/transport-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/transport-routing.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by danmyhre** [comment]
I don't see any changes related to internal email flow.

**Comment by AndreaBarr** [comment]
@danmyhre Thank you for checking 

I will get this over to the Exchange writing team for investigation then.

**Comment by AndreaBarr** [comment]
@sonika24 Could you please investigate this?

**Comment by amystrable** [comment]
Hi - is there an update on this documentation? We are looking for information on how intra-organization (cloud user to cloud user) email is routed in a hybrid deployment with centralized mail transport turned on. I cannot find documentation that states whether these messages stay in Exchange Online and are delivered between two users directly or whether they are routed back to on-premise before being delivered to a user within the same cloud tenant.

**Comment by danmyhre** [comment]
Any update on this? 

Based on this: "Except for messages sent to other recipients in the same Exchange Online organization, all messages sent from recipients in the Exchange Online organization are sent through the on-premises organization." 

it seems that EXO to EXO mails would NOT be routed through central transport.  Please confirm.

**Comment by danmyhre** [comment]
Also, if that is actually the case, it should be noted that any compliance archiving needs to happen in both organizations (EXO and on-prem).  Care will need to be taken to avoid duplicates because of this scenario.

**Comment by ckssaas** [comment]
I also request details regarding intraorganizational mail flow in hybrid. Particularly I seek details regarding whether or not cloud to on-prem internal mail flow is scanned by and originates from EOP servers.

**Comment by j0rt3g4** [comment]
IntraOrganization traffice with central
![image](https://user-images.githubusercontent.com/5489996/59016578-2cd7ce80-8807-11e9-8610-d80c7af1eb46.png)

And 

![image](https://user-images.githubusercontent.com/5489996/59016646-55f85f00-8807-11e9-8f9c-2f75df4467af.png)

**Comment by chk1982** [comment]
Hi @j0rt3g4 was that in response to my inquiry? The focus of my inquiry was Exchange Online Protection specifically and I do not see that in your diagram. When hybrid mail is centralized on-prem, does Exchange Online Protection scan intraorganizational mail (diagram #1)? I know it scans mail sent to external recipients even though mail is centralized through on-prem, but what about internal to internal in that scenario? Thanks

**Comment by chk1982** [comment]
Hi @j0rt3g4 , to further clarify I mean would intraorganizational mail be subject to the same EOP scanning and rules as other mail leaving Exchange Online. Thanks

**Comment by j0rt3g4** [comment]
@chk1982  On internal (on O365) to intenal (On-premises) the email is managed via "connectors" between them so they shouldn't pick any rule, at least you set a transport rule and reference the connectors.
And the same is from the other way (from On-premises to O365) it's internal it's being sent over the connector between them.

**Comment by chk1982** [comment]
j0rt3g4 I may not be making myself clear. Let's assume my customer has a greenfield tenant with no transport rules in place and then they add a few mailboxes in O365 and start sending mail to external (anonymous) users. By default, EOP will scan all of those outbound messages and apply Microsoft intelligence logic, etc. to make sure the customer isn't sending out spam, correct? Please correct me if I am wrong there, but let's assume the answer is yes as I believe it is. Then a merger takes place and I build a hybrid with centralized transport. Will internal (O365) to internal (on-prem) mail still be scanned using the same outbound EOP Microsoft spam intelligence and logic even though the mailboxes are "internal" and the users are trusted entries in the GAL? This is the heart of what I'm getting at. Thanks

**Comment by j0rt3g4** [comment]
@chk1982 Yes if the greenfield tenant with o365 mailboxes sents out emails to external recipients EOP will scan the messages.

So what's the flow?
1. Internal O365 mailbox sends out an email to internal On-premises recipient. This query will fail, and since the Domain is configured as "Internal Relay", it will use the Connectors to redirect the messages from O365 to On-premises
2. When this redirection using connectors takes place **it won't scan any message* because, from the O365 Perspective, the message is going "internal => internal". EOP only takes protagonism when an external recipient is involved


So the query to your question, the answer is no.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
