### ISSUE TITLE
Please help with two points of non-clarity

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#3091]
Hello,

I would like to understand more on two topics that are loosely mentioned in this article:

**1. Direct your Hybrid Agent(s) to the load balancer instead of a specific server**

What would be the logic/reason for doing this.  Isn't the agent's purpose to A) avoid needing to publish autodiscover/EWS externally and B) not have to worry about going through or around the load balancer?

**2. Multi Agent Deployment**

What is the guidance here.  Should we install 1 agent per 1 server up to some maximum recommended number of agents?  Or should we follow some kind of performance metric and add agents as necessary?  Or is 2 best, because it gives redundancy but avoids some other issues?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent#multi-agent-deployment)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @JeremyTBradshaw 
How are you?
For the first question I think the key is in the article 

> You can use the Hybrid Management PowerShell module to configure your Hybrid Agent(s) **to direct requests to your load balancer instead of a specific Exchange Client Access Server.**

This is for the **internal** communication Hybrid Agent -> CAS or LB of CAS to be able to load balance traffic to more than one CAS Server.

Remember that , the hybrid agent should be:

> Capable of establishing HTTPS connections to the Client Access Server (CAS) chosen for hybrid configuration.

For the second question, let me look into that if there is any special recommendation

Thanks

**Comment by JeremyTBradshaw** [comment]
💡thanks for that!  Makes perfect sense all of a sudden.  In that case both questions are well related I suppose.  I'll be happy to hear back.  Much appreciated.

**Comment by get-itips** [comment]
Hello @JeremyTBradshaw Jeremy, I couldn't find any specific recommendation, I think that is up to every specific scenario, and based on [App proxy own guidelines](https://docs.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-connectors#performance-and-scalability)

Hope this information helps you

**Comment by JeremyTBradshaw** [comment]
Thanks @get-itips .  Yikes, you just made me realize another unknown - if/when we add additional agents, are we in need to do something to ensure they end up in a Connector Group?  I'm not actually asking you now, just mentioning it since I noticed it in the linked article you gave.  Seems like this is some undocumented stuff by the Exchange Team here, or just not thought of yet and not enough customers asking.

Where this is coming from is that I feel as though I'm perceived as out of date when I tell clients that I prefer the Classic vs Modern for long term Hybrid Config customers who will remain Hybrid for the foreseeable future.  I will at least have this issue to refer them to (hello future client!).  As I dig into Modern, there are some unknowns like these ones that keep me happy to stick with Classic for now.  I'll reserve Modern for the clients who insist on it vs the added requirements of Classic.

Thanks again.
