### ISSUE TITLE
Can this be a module and not a snapin?

### ISSUE THREAD

**Issue by rmcgovern07** [MicrosoftDocs/OfficeDocs-Exchange#3092]
If I load the Exchange Online v2 module along with this new Exchange hybrid snapin in the same session, there are now duplicate commands - for example New-DistributionGroup and Set-DistributionGroup exist in both. Previously, we would import the on-premise Exchange module with the -Prefix switch to add a prefix and get around this. Now we can't do that because these replacement commands are packaged as a snapin and not a module. We could start loading the EOL commands with -Prefix, but then I'd have to rewrite 50+ scripts and 20+ functions.

Why was this released as a snapin and not a module? Will it ever be a module? I didn't realize Microsoft was still releasing commands as snapins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dee5b3e-6d8d-ca7e-a0c3-96d01c9a95f1
* Version Independent ID: f160f2ac-f965-c218-eba3-59909c4336bb
* Content: [Manage recipients in Exchange Server 2019 Hybrid environments](https://docs.microsoft.com/en-us/Exchange/manage-hybrid-exchange-recipients-with-management-tools)
* Content Source: [Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/manage-hybrid-exchange-recipients-with-management-tools.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
