### ISSUE TITLE
It is missing 550 5.5.3 status code

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/OfficeDocs-Exchange#3108]
I received a report of failed message sender from my user with the status 550 5.5.3. I tried to find solution about this code, but there is no documentation mentioning this code.

I need help.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6d0e4-0ea5-f8a9-bf67-bf7cacc74b3e
* Version Independent ID: c72592d3-bfd1-ddf3-793f-dcc0374db074
* Content: [Email non-delivery reports in Exchange Online](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/non-delivery-reports-in-exchange-online.md)
* Service: **o365-administration**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
