### ISSUE TITLE
How to Run a non-owner mailbox access report

### ISSUE THREAD

**Issue by omegagx** [MicrosoftDocs/OfficeDocs-Exchange#3109]
At the top of the page it says that it's recommended to search the audit log in the Microsoft Purview compliance portal. However, there is no documentation at https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide to show the steps to "Run a non-owner mailbox access report" that is available in the EAC. Additionally, the report in EAC should still work since it's still available there but it throws an error when trying to run it.  I opened case 30938627 and they are saying that it no longer works because it was deprecated. But then why wasn't the documentation updated if it was already deprecated and no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8532cf2-3378-d826-7f4d-568575b9577d
* Version Independent ID: b969f952-9848-5190-1007-c851dc2009b5
* Content: [Run a non-owner mailbox access report in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @omegagx, thank you for your feedback.

Please follow these instructions:
https://docs.microsoft.com/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance

You can search for the following activity:
- Exchange mailbox activities - Accessed mailbox items: Messages were read or accessed in the mailbox. Audit records for this activity are triggered in one of two ways: when a mail client (such as Outlook) performs a bind operation on messages or when mail protocols (such as Exchange ActiveSync or IMAP) sync items in a mail folder. This activity is only logged for users with an Office 365 or Microsoft 365 E5 license. Analyzing audit records for this activity is useful when investigating compromised email account.
