### ISSUE TITLE
Additional details for "The native Microsoft sync technology"

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#311]
Hello,

Is this "native Microsoft sync technology" something other than the Exchange ActiveSync protocol?   Any additionally clear information you could provide would be greatly appreciated.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca9af29f-c472-ebfd-e166-66a7d2b8bf0c
* Version Independent ID: 958cc7b8-3330-52a0-26fd-5717cba1df2f
* Content: [Outlook for iOS and Android in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@JeremyTBradshaw Update: sorry for the delay. I am following up with the product team for a definitive answer.

**Comment by msdmaguire** [comment]
@JeremyTBradshaw native Microsoft synch technology is a new proprietary protocol. It is not Exchange ActiveSync. Thanks for your patience.

**Comment by JeremyTBradshaw** [comment]
Thanks for confirming.  Interesting.....

**Comment by kpizaaz** [comment]
By chance, will the new changes allow us to determine what type of device is running the Outlook Mobile app.  For instance, in the DeviceModel field of EAS logs will we be able to determine device models such as iPhones or Androids which are running the APP?
