### ISSUE TITLE
The "Where did my report go?" link is broken

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-Exchange#3111]
In the note on this page, the "Where did my report go?" link points to https://support.microsoft.com/office/4f7ce026-8be0-4800-849c-28071df0b85f, but that results in a 404.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206471ee-963a-333f-6941-415a443b273c
* Version Independent ID: c0cd8f8a-5cdd-24f3-eace-3cb0930d65b5
* Content: [Monitoring, reporting, and message tracing in Exchange Online](https://docs.microsoft.com/en-us/exchange/monitoring/monitoring)
* Content Source: [Exchange/ExchangeOnline/monitoring/monitoring.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/monitoring.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback @joshtransient
