### ISSUE TITLE
Our expreience says differently

### ISSUE THREAD

**Issue by Kadirbyek** [MicrosoftDocs/OfficeDocs-Exchange#3112]
[Enter feedback here]
it is stated that "3. The public folders in this configuration cannot be accessed using Outlook on the web (formerly known as Outlook Web App)."  Our expreience says differently. Did a project  recently showing that  in contrast PFs are being shown up in OWA not on Outlook Client. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @Kadirbyek, thank you for your feedback.

Could you clarify where the user mailbox is located and where are the PFs they are trying to access?

**Comment by tiburd** [comment]
We've passed on this information to the team.

Closing this issue.

cc: @scanum
