### ISSUE TITLE
Basic Authentication is not listed in the Azure AD Sign-In report - only Legacy Authentication.

### ISSUE THREAD

**Issue by richard-artes** [MicrosoftDocs/OfficeDocs-Exchange#3118]
You say "The best place to get the most up-to-date picture of Basic authentication usage by tenants is by using the Azure AD Sign-In report" but the reports don't list Basic Authentication as an option. You can select various Legacy Authentication options (ActiveSync, POP, SMTP, IMAP etc) but nothing that says Basic. Which options should you choose to see Basic Authentication?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19cf826a-aaf1-91ed-8a8f-637d869e47df
* Version Independent ID: 61d69fb6-184d-acf5-8b02-39b3d885d28b
* Content: [Deprecation of Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by jonwbstr** [comment]
Agreed, instructions are unclear. I believe all legacy authentication protocols use basic auth of some form and will be impacted.

1. Open Azure portal > **Azure Active Directory > Sign-ins**
2. Add the Client App column if it is not shown by clicking on **Columns > Client App**
3. Apply filter for Client appClick **filters > Client App**, then click Apply
4. Select all of the legacy authentication protocols, then click Apply

**Comment by get-itips** [comment]
Hello @richard-artes Richard, how are you?
Basic auth is covered by the Legacy Authentication clients filter

currently in the article:

> For many years, applications have used Basic authentication (also known as Legacy authentication)...

for more information

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-block-legacy-authentication
