### ISSUE TITLE
Where is this in the new Admin Console

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-Exchange#3122]
Does this functionality exist in the current admin consoles or only in the old one?  Where will we get this when the old ones are turned off?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8532cf2-3378-d826-7f4d-568575b9577d
* Version Independent ID: b969f952-9848-5190-1007-c851dc2009b5
* Content: [Run a non-owner mailbox access report in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/non-owner-mailbox-access-report.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @kelemvor33, thank you for your feedback.

Please follow these instructions:
https://docs.microsoft.com/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance

You can search for the following activity:
- Exchange mailbox activities - Accessed mailbox items: Messages were read or accessed in the mailbox. Audit records for this activity are triggered in one of two ways: when a mail client (such as Outlook) performs a bind operation on messages or when mail protocols (such as Exchange ActiveSync or IMAP) sync items in a mail folder. This activity is only logged for users with an Office 365 or Microsoft 365 E5 license. Analyzing audit records for this activity is useful when investigating compromised email account.
