### ISSUE TITLE
About issue #3069 and #3116.

### ISSUE THREAD

**Issue by mayanagi** [MicrosoftDocs/OfficeDocs-Exchange#3123]
I raised the issue #3069 and it has been fixed in #3116.
I checked the fixed statement but it should be still wrong.
Even if the organization has Exchange 2013 servers, outbound requests towards Exchange Online are from mailbox servers not from CAS.
So all Exchange servers ,regardless of their versions, must be able to reach outbound to Exchange Online.

_All Exchange Servers (**or Client Access Servers if you have Exchange 2013**) must be able to reach outbound to Microsoft 365 or Office 365 endpoints via HTTPS (TCP) 443,_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @mayanagi, thank you for your feedback.

What is your source of information to confirm this?

This is what I found and I think you're right:
"The Availability Service on the on-premises Exchange server (Client Access Server if Ex2010 or Mailbox Server if 2013/2016) in Contoso then checks to see if there is a path to query Jane’s Free/Busy information for Contoso’s cloud side."
https://techcommunity.microsoft.com/t5/exchange-team-blog/demystifying-hybrid-free-busy-what-are-the-moving-parts/ba-p/607704

**Comment by mayanagi** [comment]
Hi @dariomws, thank you for your reply.
I couldn't find official docs which explicitly mention the behavior.
My sources are my support experience and the fact that I checked the actual behavior in my test environment. In my test environment, the request for Free/Busy information is from mailbox servers not client access servers.
The blog post you shared is also good resource I think.

**Comment by dariomws** [comment]
@mayanagi, thanks. Anyway, I'm applying the update.
