### ISSUE TITLE
An exception occurred when sending mail using SMTP server

### ISSUE THREAD

**Issue by ShiKe11** [MicrosoftDocs/OfficeDocs-Exchange#3124]
We are trying to use the SMTP server to send mail. We used non-people account and the account and password are correct also the permission is granted, while we received below exception when sending Email, could you please help to investigate and advise? Thanks!

**Error Message**: The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.57 Client not authenticated to send mail. Error: 535 5.7.139 Authentication unsuccessful, SmtpClientAuthentication is disabled for the Tenant. Visit https://aka.ms/smtp_auth_disabled for more information.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
