### ISSUE TITLE
MIssing information on how to authenticate to use "Reports using reporting web services"

### ISSUE THREAD

**Issue by Steltek** [MicrosoftDocs/OfficeDocs-Exchange#3127]
The "Reports using reporting web services" part doesn't work anymore due to Microsoft having turned off Basic Authentication and seemingly not provided any replacement authentication method yet. (Neither this page, nor the referenced [Reports using reporting web services](https://docs.microsoft.com/en-us/previous-versions/office/developer/o365-enterprise-developers/jj984325(v=office.15)) page provide any information on how one can authenticate now.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 206471ee-963a-333f-6941-415a443b273c
* Version Independent ID: c0cd8f8a-5cdd-24f3-eace-3cb0930d65b5
* Content: [Monitoring, reporting, and message tracing in Exchange Online](https://docs.microsoft.com/en-us/exchange/monitoring/monitoring)
* Content Source: [Exchange/ExchangeOnline/monitoring/monitoring.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/monitoring.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @Steltek, thank you for your feedback.

From the Message Center:

(Updated) OAuth interface for Office 365 Reporting web service
**MC318316** · Published 26 Jan 2022 · Last updated 5 Apr 2022

Message Summary
Updated April 05, 2022: We have updated the rollout timeline below and provided additional details for clarity. Thank you for your patience.

Currently, users accessing Reporting Web service use “Basic Authentication” and must provide their credentials. With this feature update, Microsoft will improve the security of your tenant by replacing “Basic Authentication” access in favor of the recommended OAuth user interface which is where we will continue to invest our development resources.

Key points

Timing: Rollout will begin in early May (previously mid-March) and is expected to be complete by late May (previously late March).

How this will affect your organization:

No immediate action required. Users could start migrating their programmatic access to Office 365 Reporting Web Service from "Basic Authentication" to "OAuth".

https://admin.microsoft.com/AdminPortal/home?ref=MessageCenter/:/messages/MC318316
