### ISSUE TITLE
Check the admin center?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#3128]
Hello,

It's now mid 2022, does the admin center have the section this article indicates would be available early 2022?

Check the admin center
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#check-the-admin-center

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19cf826a-aaf1-91ed-8a8f-637d869e47df
* Version Independent ID: 61d69fb6-184d-acf5-8b02-39b3d885d28b
* Content: [Deprecation of Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @jonwbstr, thank you for your feedback.

@JoanneHendrickson, could you give an update for this section please? Thanks!
