### ISSUE TITLE
Wo ist die Funktion zum Bearbeiten?

### ISSUE THREAD

**Issue by ngzero** [MicrosoftDocs/OfficeDocs-Exchange#313]
Früher konnte man doch mal Vorschläge zu Änderungen/Überstzung abgeben. Die maschinelle Übersetzung ist nicht schlecht, aber da sind eine Stellen die schlecht übersetzt wurden und sogar Parameter übersetzt worden die nicht übersetzt werden dürfen. Stellenweise fehlt sogar was.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4a835d54-db8a-5c1c-a3f9-244e3a363475
* Version Independent ID: cc95465f-0969-7815-ff1e-243f3412e2a2
* Content: [Nachrichtenverfolgung](https://docs.microsoft.com/de-de/exchange/mail-flow/transport-logs/message-tracking?view=exchserver-2019#Source)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-logs/message-tracking.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-logs/message-tracking.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@ngzero Thank you for pointing this out to us

I'll get this translation issue over to our Exchange writing team for investigation. Also if it's something that you wanted to change you can submit a pull request as well. 


Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by OfficeGSX** [comment]
Hello,

We have uplifted the topic to HT and it will be translated by us.

Best regards,

Jiri

**Comment by OfficeGSX** [comment]
The article has been HumanTranslated and published live.

Best Regards,
Michal
