### ISSUE TITLE
About License question

### ISSUE THREAD

**Issue by ecanales88** [MicrosoftDocs/OfficeDocs-Exchange#3138]
Hello team, about question
"Does the Exchange hybrid server in my on-premises organization require an Exchange license?"
according to the following article, with CU12 is possible get free license for Exchange 2019:
https://techcommunity.microsoft.com/t5/exchange-team-blog/released-2022-h1-cumulative-updates-for-exchange-server/ba-p/3285026
_**CU12 includes a change to the Exchange Server License Terms. We have updated our licensing to add a product key for Exchange 2019 hybrid servers at no additional charge! This was previously available only for Exchange 2010, Exchange 2013, and Exchange 2016. Exchange Server 2019 CU12 and the [Hybrid Configuration wizard](https://docs.microsoft.com/exchange/hybrid-configuration-wizard) have been updated to support this change.**_

Please update this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec121a3-cccf-1164-777e-be5e4dc9d2c5
* Version Independent ID: 37c911be-c56e-8975-260b-6f8ddc497ee9
* Content: [Hybrid Configuration wizard FAQs](https://docs.microsoft.com/en-us/exchange/hybrid-configuration-wizard-faqs#does-the-exchange-hybrid-server-in-my-on-premises-organization-require-an-exchange-license-)
* Content Source: [Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.yml](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.yml)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by ecanales88** [comment]
Hi
But I don't have a issue with my tenant, just only suggest to update the FAQ page according to updates from last Exchange CUs
Regards!
