### ISSUE TITLE
Zimbra CSV file format

### ISSUE THREAD

**Issue by Corina-github** [MicrosoftDocs/OfficeDocs-Exchange#3144]
Hi, 

I'm with the EXO CSS team and we've recently had a support case regarding an IMAP migration from Zimbra. 
The customer would appreciate it if we were to look in to adding Zimbra in this KB as well, as it's a rather well known and spread source in this type of migrations. 
The format that worked for him is the same as for Mirapoint and it would have saved time/effort if our documentation would have included that from the start. 

Thank you!
Corina Ionescu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a62d4e4-616e-3f98-e5b6-5544f923480d
* Version Independent ID: 3f90a7c2-6130-6b55-1cfa-d7a9f4386cd5
* Content: [Migrate other types of IMAP mailboxes to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes#format-mailbox-admin-credentials-for-different-imap-servers)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-other-types-of-imap-mailboxes.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
