### ISSUE TITLE
Article is unclear where to create connectors and the connector workflow doesn't match exchange

### ISSUE THREAD

**Issue by yayoi-k** [MicrosoftDocs/OfficeDocs-Exchange#3148]
[Enter feedback here]

Regarding this section:
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail#for-new-eac-1

#1) It's unclear if one creates the receive connector in Office 365 or in Exchange Admin Center in on-prem exchange

#2) On exchange 2013 AND exchange 2019 admin centers, the new receive connector screen does not match the screens shown in the instructions for the new admin center or classic admin center
![Receive connector issues](https://user-images.githubusercontent.com/2354113/170626568-e5243197-264b-419b-a761-b60bdac272bf.jpg)

Need working instructions to create the receive connector on on-prem exchange to allow intra-org mallow from Office 365 due to Hybrid Configuration Wizard failing to create the receive connector on on-prem exchange server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498774ba-06b8-5087-f884-bab065225d63
* Version Independent ID: a54b404b-0ade-45e8-3282-402c1a3bb0d0
* Content: [Set up connectors to route mail between Microsoft 365 or Office 365 and your own email servers](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @yayoi-k, thank you for your feedback.

When we talk about new and classic EAC we are always talking about Exchange Online. All the steps in this article must be performed in Exchange Online except for the section "Set up your email server to relay mail to the internet via Microsoft 365 or Office 365".

**Comment by yayoi-k** [comment]
> Hi @yayoi-k, thank you for your feedback.
> 
> When we talk about new and classic EAC we are always talking about Exchange Online. All the steps in this article must be performed in Exchange Online except for the section "Set up your email server to relay mail to the internet via Microsoft 365 or Office 365".

I strongly disagree with the practice of saying EAC and not indicating whether you mean on-prem or cloud EAC in an article that deals with both on-prem and cloud.  The management tool of on-prem Exchange is called "EAC" Exchange Admin Center.  It's the definition on ambiguous to have two tools called the exact same thing, but whenever you say the tool name you don't indicate whether it's the cloud tool or the on-prem tool.  Simply indicate in your article every time you mention EAC whether you mean on-prem or cloud.  Is that inconvenient, or too much work?  Perhaps it is inconvenient, but Microsoft's choose to name the tools what they did, so you/they need to own it and make articles people can understand outside of Microsoft.  I'd strongly suggest every time you state "EAC" indicate if it's on-prem or cloud, otherwise I think its worth having a meeting and asking who these articles are written for and what the purpose of them is, is Microsoft-employee-only colloquialism knowledge required like "EAC always means exchange online EAC" in order to use them.

In doing IT consulting, I find my mind is constantly asking "do these instructions mean this, or that" this is a constant problem, lack of clarity, it's what actually drives work, ambiguity.  Then someone who's done it before has to be hired because the information or documentation is ambiguous.  Ironically I've done dozens of Exchange migrations going back to Exchange 5.5 and hybrid migrations since when those first became possible in the mid 2000's and would be that person thats done it before, yet this article and the generally ambiguous writing style of Microsoft articles has been a challenge throughout my 25 year career.  It drives the multi billion dollar IT services industry and the millions of third party posts in online forums, blogs, etc.  But just keep at it, keep saying a term that exists in both pieces of software that the article is about and never indicate which one you mean.  

Where in the article does it indicate how to create the connectors on on-prem Exchange to make on-prem exchange able to send intra-organization email to Office 365?  This would be part of making on-prem exchange communicate with office 365.

Regards

**Comment by dariomws** [comment]
Hi @yayoi-k, thank you again for your feedback.

The article is always talking about Microsoft 365 and the connectors to connect with your own email server which could be Exchange or not. I think that's clear all around the article, that's why there is no need to specify if the EAC is for Exchange on-premises or online.
For example, the article starts with:

![image](https://user-images.githubusercontent.com/33589238/174006437-4e83ea52-66a2-49ac-a8ef-25662364da57.png)

There is only one section that mentions Exchange on-premises: "Set up your email server to relay mail to the internet via Microsoft 365 or Office 365". But it's just an example because your own email server could be something different than Exchange Server on-premises.

**Comment by tiburd** [comment]
@dariomws 
Thank you for resolving.

Closing this issue.

cc: @scanum

**Comment by yayoi-k** [comment]
I disagree that its clear that anytime EAC is mentioned it's speaking of the Exchange Online EAC, the fact the article is discussing both On-Prem Exchange and Exchange Online should bode toward making it obvious which one is being described.  Further, the fact actions must be taken in on-prem Exchange (which has a management tool called EAC) further supports the idea that it should be made clear which products "EAC" the described actions are related to.  

Why are clarifying words so rare, expensive, precious and restrained in the content Microsoft writes.  Can this style and culture be changed?  Have you ever surveyed the IT community outside of Microsoft to ask if they feel MS content tends to be clear or ambiguous?

Who are you proving what to in insisting "it's clear", that's great you think its clear, you wrote it or work there, etc.  I found this article when needing to manually create connectors between Exchange on-prem and Exchange online in a hybrid scenario and wasted time trying to perform the steps against exchange on-prem.  The actual specific content where actuals must be taken in on-prem exchange is also ambiguous and difficult to tell its speaking about on-prem exchange in the section where the steps are made against on-prem.  

It would be also great if this article indicated whether it is relevant to Hybrid or not as well, rather than leaving that ambiguous.

Think about the multi-billion IT consulting industry, the countless blogs and third party content to help people through products like this one.  Microsoft also has hundreds of thousands of articles.  Why would all this third party content exist if the Microsoft content was clear?  It exists because MS content tends to be very difficult to understand and a lot of that has to do with assumptions and ambiguity, that could incredibly easily be fixed by leaning toward stating things vs not.

Why is there such a strong bias to rationalize that everything written here is perfect?  Why not consider external feedback more seriously, the external world is where the revenue is coming from.

Again the mgmt tool is called EAC on both of the products this article is about and actions have to be taken on both products, yet somehow you believe its clear which product is being discussed when EAC is mentioned?  It absolutely isn't, and you fail to quote anything that clarifies this.

@dariomws I think the way you're thinking is really obtuse.  You pasted part of the content, but nowhere in that content is clarity that EAC is always talking about cloud.  The section you quote merely says "Microsoft 365" first in the sentence preceding "your own email servers".  It could equally be said this way:
_Set up connectors to route mail between your own email servers and Microsoft 365 or Office365._

Communication between Office 365 and on-prem is bi-directional, both sides are _equal_.  There's no conceptual strength to indicate the first term mentioned is referring to Office 365 vs on-prem.

The arrogance culture there is really really growing old, and ultimately hurts sales.  Businesses weather it, but consumers won't stand for it, and that's shown in the lack of success in the consumer space (Zune, Windows Phone, IE, many renditions of tablets preceding the Surface).  I remember running into the arrogance when providing feedback related to the Windows 8 Phone, and how its email setup wizard was specific to Hotmail without it indicating that was the case, so one basically could not setup their email after buying the phone.  I brought it up at launch and was told "we all use Hotmail".

Every Microsoft application on Windows starts with the word "Microsoft" making it difficult to find the application you want because apps sort alphabetically and all MS apps start with M...  how about the brevity there where it would actually help UX?  Your happy to state your brand repeatedly in front of every application yet against stating the product name in this article or providing extra clarity where it would help people.   Your brands style 'states the obvious' where it reduces UX (putting Microsoft in front of every installed application in windows), but neglects to 'state the obvious' where it would increase UX such as this article.  I can't think of any software applications that one installs where the brand name is actually in the application name post install except Microsoft products, but where's that 'over stating it' style when it comes to this article?
