### ISSUE TITLE
Please post EMC (exchange mgmt shell) commands for creating receive connector

### ISSUE THREAD

**Issue by yayoi-k** [MicrosoftDocs/OfficeDocs-Exchange#3149]
Please post EMC commands for creating the receive connector in this section: 
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail#for-new-eac

EMC is always helpful because instructions and screens can be wrong or instructions don't match various versions of exchange.  For example the instructions don't match what one see's in Exchange 2013 or Exchange 2019...  Not sure what version of exchange the "New EAC" and "Classic EAC" UX screenshots and flows were taken from.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498774ba-06b8-5087-f884-bab065225d63
* Version Independent ID: a54b404b-0ade-45e8-3282-402c1a3bb0d0
* Content: [Set up connectors to route mail between Microsoft 365 or Office 365 and your own email servers](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @yayoi-k 

Classic EAC/new EAC always refers to Exchange Online, not to Exchange On-Premises (Server versions).

Instructions to create receive connectors on-premises are in the article

> If you're using Exchange, see [Receive connectors](https://docs.microsoft.com/en-us/exchange/mail-flow/connectors/receive-connectors) for more information.

Hope this clarifies it to you,

**Comment by get-itips** [comment]
@scanum
