### ISSUE TITLE
Please indicate what versions of exchange would be classic EAC and which version would be New EAC

### ISSUE THREAD

**Issue by icscript** [MicrosoftDocs/OfficeDocs-Exchange#3150]
[Enter feedback here]

Please indicate what versions of exchange would be classic EAC and which version would be New EAC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05fe1b-9603-8917-d02b-e41218a97920
* Version Independent ID: ed98f261-9010-60f8-4066-2d254ff1aad7
* Content: [Differences between the Classic admin center (Classic EAC) to the new admin center (new EAC) in Exchange Online](https://docs.microsoft.com/en-us/exchange/changes-in-exchange-admin-center)
* Content Source: [Exchange/ExchangeOnline/changes-in-exchange-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/changes-in-exchange-admin-center.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @Benny-54
* Microsoft Alias: **v-bshilpa**

**Comment by get-itips** [comment]
Hello @icscript 
Classic EAC and new EAC correspond to Exchange Online version, not to Exchange On-Premises. Let me know if I understood you correctly.

**Comment by get-itips** [comment]
@scanum
