### ISSUE TITLE
https://docs.microsoft.com/en-us/powershell/module/exchange/get-offlineaddressbook?view=exchange-ps

### ISSUE THREAD

**Issue by brunoalbuquerque91** [MicrosoftDocs/OfficeDocs-Exchange#3151]
This Command, no longer works : 
![image](https://user-images.githubusercontent.com/49884301/170739917-31bd806c-28be-4d58-8151-4eb7a47029f4.png)

anyone else have any ideas?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a2d4039-81e6-8134-97db-cb3f1878c1d1
* Version Independent ID: b09aea1b-0895-cf5f-17f9-29c26c891784
* Content: [Remove an offline address book from Exchange in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/offline-address-books/remove-offline-address-book)
* Content Source: [Exchange/ExchangeOnline/address-books/offline-address-books/remove-offline-address-book.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/offline-address-books/remove-offline-address-book.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @brunoalbuquerque91, thank you for your feedback.

Do you have the Address Lists role assigned?

"By default, the Address List role isn't assigned to any role groups in Exchange Online. To use any cmdlets that require the Address List role, you need to add the role to a role group."

**Comment by tiburd** [comment]
@dariomws 
Thank you for the information.

Closing this issue.
