### ISSUE TITLE
MS outlook Add-ins, lots of docs not links of where to get them.

### ISSUE THREAD

**Issue by bmazak** [MicrosoftDocs/OfficeDocs-Exchange#3154]
A bing search should return the actual link to WHERE I can get the Add-ins not a bunch of rhetoric on what it is.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b208cbdc-d46e-af0f-3d99-b1627277d3f0
* Version Independent ID: 4e43510d-946b-83cc-da53-a6416145f7a5
* Content: [Add-ins for Outlook in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/add-ins-for-outlook#:~:text=Add-ins%20for%20Outlook%20are%20applications%20that%20extend%20the,file%20or%20URL%20or%20from%20the%20Office%20Store.)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/add-ins-for-outlook.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/add-ins-for-outlook.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @bmazak Brian,
How are you?
Here, we are limited to documentation fixes and improvements, said that, you can get add-ins from the Office Store, as the article says (and in newer versions there is a button called Get Add-ins)
Hope this information helps you

**Comment by get-itips** [comment]
@scanum
