### ISSUE TITLE
Instructions to Migrate from GSuite to Microsoft 365 No longer valid

### ISSUE THREAD

**Issue by michael-crawford** [MicrosoftDocs/OfficeDocs-Exchange#3158]
[Enter feedback here]
I've been trying to follow the instructions on https://docs.microsoft.com/en-us/exchange/mailbox-migration/googleworkspace-migration-prerequisites, and they are not only difficult to follow (note: I'm a 30 year architect, AWS SA Pro for 8 years, and I can't follow them easily), but many of the steps reference GUI actions that do not match the current GUI design in GCP. This process is not really described at a high-level, for example, I was surprised to see it jump into Google Cloud, when I thought I was only dealing with GSuite and was not aware of how it might be integrated with GCP. It's quite confusing due to not having enough overview material, even without not having up-to-date instructions which can be followed.

Given that I, like many, are looking at a 6/27/22 deadline to move off GSuite Legacy, you really should fix this quickly, so users attempting to migrate off the free GSuite can follow it before the time to move or pay for a plan is up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0b140ec-7770-5047-3e57-b9f1f2647b10
* Version Independent ID: 3542b0ec-4e55-d833-9dd1-7211cbca9406
* Content: [Manually configuring G-Suite for migration to Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/manually-configuring-gsuite-for-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/manually-configuring-gsuite-for-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/manually-configuring-gsuite-for-migration.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
