### ISSUE TITLE
What is the necessary permission to run Recovery Deleted Items?

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/OfficeDocs-Exchange#3159]
Hi!
The docs https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages state: 

![image](https://user-images.githubusercontent.com/50090959/171518534-6936003a-d372-4361-9ff0-27fb1f1d18d2.png)

When I check the link https://docs.microsoft.com/en-us/exchange/permissions-exo/feature-permissions, I search for the "In-Place eDiscovery" entry, and the document state:

![image](https://user-images.githubusercontent.com/50090959/171518120-689e33e2-06c8-4a1e-8576-c19f245b4c53.png)

However, I add the Global Admin user to the Discovery Management role group and still not working. In other blogs, I found that the correct role is Mailbox Import Export: https://techcommunity.microsoft.com/t5/exchange-team-blog/a-new-recoverableitems-experience-comes-to-exchange-online/ba-p/1505353

I think that the docs is wrong. Can you clarify it? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496c2124-3973-e6d1-385e-4ec25228dc49
* Version Independent ID: cd70012a-5cdf-bac5-3a29-df38b19df1cb
* Content: [Recover deleted messages in a user's mailbox in Exchange Online](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/recover-deleted-messages.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @FernandoGualano I could verify that the exchange team blog post that you link is right in requiring mailbox import export, I'll propose an update to the article.

Thanks for your feedback

**Comment by FernandoGualano** [comment]
Thank you @get-itips!
