### ISSUE TITLE
MS365 subdomain linking instructions missing

### ISSUE THREAD

**Issue by GokulNC** [MicrosoftDocs/OfficeDocs-Exchange#3162]
Both the subsections look similar. (both are instructions for G-suite)
The instructions for linking MS365 subdomain is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec9bdfa-e5f7-a869-514d-0e6ae50ff7e9
* Version Independent ID: 87521d1b-8d1b-0648-9059-347cdae9d3f7
* Content: [Google Workspace migration prerequisites in Exchange Online](https://docs.microsoft.com/en-us/exchange/mailbox-migration/googleworkspace-migration-prerequisites)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/googleworkspace-migration-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/googleworkspace-migration-prerequisites.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by tiburd** [comment]
We’ve passed on this suggestion to the documentation team. 

Closing this issue.

cc: @scanum @get-itips
