### ISSUE TITLE
Need to update documentation

### ISSUE THREAD

**Issue by dbrewer89** [MicrosoftDocs/OfficeDocs-Exchange#3172]
[Enter feedback here]
The details listing where to find the Exchange Transport Rule Report is incorrect.
Finally found it at https://admin.exchange.microsoft.com/#/reports/transportruledetails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 736d8598-4bde-5f1c-5eef-2f9b648912f6
* Version Independent ID: eb74141c-161c-d1db-e95c-032f3dfdf8ec
* Content: [Manage mail flow rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/manage-mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-mail-flow-rules.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback!
