### ISSUE TITLE
Clarification on retirement of exchange dlp rule management

### ISSUE THREAD

**Issue by Rykimaruh** [MicrosoftDocs/OfficeDocs-Exchange#3174]
reading up the article regarding the retirement of the policies in exchange, I got  a question for the following statements:

- Starting April 1, 2022, admins will no longer be able to make configuration changes to DLP policies in the classic Exchange admin center. Existing rules will continue to work as-is.

- Starting August 1, 2022, the DLP policy management experience in the classic Exchange admin center will be retired. Admins will still be able to view the associated rules in read-only mode using the mail flow rule (transport rule) experience._

From my understanding, I will not be able to manage these Exchange DLP rules from the Classic Exchange Admin center, however, I can continue to use them in the modern exchange admin center, yes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32c304f-a00c-5d66-d3e2-9ddf700d121e
* Version Independent ID: 0bb81f36-0b92-263a-6ee1-9b282f20a44d
* Content: [Data loss prevention in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by JeanMS** [comment]
> reading up the article regarding the retirement of the policies in exchange, I got a question for the following statements:
> 
> * Starting April 1, 2022, admins will no longer be able to make configuration changes to DLP policies in the classic Exchange admin center. Existing rules will continue to work as-is.
> * Starting August 1, 2022, the DLP policy management experience in the classic Exchange admin center will be retired. Admins will still be able to view the associated rules in read-only mode using the mail flow rule (transport rule) experience._
> 
> From my understanding, I will not be able to manage these Exchange DLP rules from the Classic Exchange Admin center, however, I can continue to use them in the modern exchange admin center, yes?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: a32c304f-a00c-5d66-d3e2-9ddf700d121e
> * Version Independent ID: 0bb81f36-0b92-263a-6ee1-9b282f20a44d
> * Content: [Data loss prevention in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention)
> * Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md)
> * Service: **exchange-online**
> * Technology: ****
> * GitHub Login: @JoanneHendrickson
> * Microsoft Alias: **jhendr**

Don't need to save any Exchange data from server

**Comment by Rykimaruh** [comment]
> > reading up the article regarding the retirement of the policies in exchange, I got a question for the following statements:
> > 
> > * Starting April 1, 2022, admins will no longer be able to make configuration changes to DLP policies in the classic Exchange admin center. Existing rules will continue to work as-is.
> > * Starting August 1, 2022, the DLP policy management experience in the classic Exchange admin center will be retired. Admins will still be able to view the associated rules in read-only mode using the mail flow rule (transport rule) experience._
> > 
> > From my understanding, I will not be able to manage these Exchange DLP rules from the Classic Exchange Admin center, however, I can continue to use them in the modern exchange admin center, yes?
> > #### Document Details
> > ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> > 
> > * ID: a32c304f-a00c-5d66-d3e2-9ddf700d121e
> > * Version Independent ID: 0bb81f36-0b92-263a-6ee1-9b282f20a44d
> > * Content: [Data loss prevention in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention)
> > * Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md)
> > * Service: **exchange-online**
> > * Technology: ****
> > * GitHub Login: @JoanneHendrickson
> > * Microsoft Alias: **jhendr**
> 
> Don't need to save any Exchange data from server



Could you clarify what you mean by that? I am still unclear as to what that means for me as a global admin. Do I lose access to manage the Exchange DLP rules? Can I still use the Exchange DLP rules?

**Comment by get-itips** [comment]
@scanum
