### ISSUE TITLE
This setting used to be accessible from partner admin accounts.

### ISSUE THREAD

**Issue by webstaff** [MicrosoftDocs/OfficeDocs-Exchange#3177]
For the longest time this setting was visible and configurable from a partner admin account.

it's now not visible from those account types so there needs to be a note added for those of us who have spend 4 years accessing it that way.

Once again, hurray for being a MS partner I feel so loved by this org.. :(

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
