### ISSUE TITLE
Incorrect URL in Q&A?

### ISSUE THREAD

**Issue by SuperTekBoy** [MicrosoftDocs/OfficeDocs-Exchange#3181]
The first Q&A has 3 links with 3 separate titles. However, two of the links point to the exact same place. It looks like the "More endpoints not included in the Microsoft 365 or Office 365 IP Address and URL Web service" points to the same URL as "Microsoft 365 and Office 365 URLs and IP address ranges"

"Q: My organization has a security policy that requires Internet inbound connections to be restricted to approved IP addresses or FQDNs. Is that configuration possible with this architecture?"

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SuperTekBoy** [comment]
That is not my question. That question is quoted directly from the Q&A from the document.  The answer to that question, I quoted here, has three URLs with 3 separate titles. But two of the URLs end up on the same articles. The three URLs in the answer need verified.
