### ISSUE TITLE
New certificate request for CA from ECP is deprecated in latest versions of Exchange

### ISSUE THREAD

**Issue by Lee-MSFT** [MicrosoftDocs/OfficeDocs-Exchange#3191]
It should be noted that with the latest versions of Exchange (2019-CU12, 2016-CU23), the option to generate a certificate request from ECP is no longer available.

**Comment by tiburd** [comment]
@Lee-MSFT 
Thank you for your submission. Because you are Microsoft-internal and have a PR in process, we are closing this issue.

cc: @scanum
