### ISSUE TITLE
Exchange documentation missing changes to autodiscover process

### ISSUE THREAD

**Issue by Kav7** [MicrosoftDocs/OfficeDocs-Exchange#3197]
The documentation https://docs.microsoft.com/en-us/exchange/troubleshoot/outlook-issues/cannot-set-up-profile-autodiscover?source=docs is missing information about the new 'autodetect' service that is used preferentially in both Outlook and Outlook mobile to determine what service a mailbox is on. This 'autodetect' service is only used for '[simplified account creation](https://support.microsoft.com/en-us/topic/how-to-disable-simplified-account-creation-in-outlook-2016-outlook-2019-and-outlook-for-office-365-662bf4f8-c357-dbc8-53b3-ff8f445e8247)'.

The issue is covered in these posts:
https://c7solutions.com/2021/05/outlook-autodetect-and-broken-autodiscover
https://masterandcmdr.com/2018/08/15/outlook-autodiscover-weirdness/

The problem is that when you migrate from say G Suite to 365, even though the DNS records have long been updated, the autodetect service has not updated and Outlook when trying to add the 365 account, still tries to connect to G Suite.

This new autodiscover process needs to be documented, so people are able to troubleshoot this problem effectively.

EDIT: this 'autodetect' uses the 'Acompli' service

**Comment by tiburd** [comment]
Thank you for bringing this to our attention. We have passed on the information to the team.

Closing this issue.

cc: @scanum
