### ISSUE TITLE
Localized content is wrong - Exchange 2013 AD support

### ISSUE THREAD

**Issue by hishikitetsuya** [MicrosoftDocs/OfficeDocs-Exchange#3199]
This is feedback for localized content.  Exchange 2013 does not support Windows Server 2022 AD as follows.

[English - Exchange 2013 system requirements](https://docs.microsoft.com/en-us/exchange/exchange-2013-system-requirements-exchange-2013-help#network-and-directory-servers)

> ![image](https://user-images.githubusercontent.com/6519947/179883359-49893788-204d-4f80-a4de-adbb8c948ad7.png)

However, localized content is different - it includes Windows Server 2022.

[Japanese - Exchange 2013 system requirements](https://docs.microsoft.com/ja-jp/exchange/exchange-2013-system-requirements-exchange-2013-help#network-and-directory-servers)

> ![image](https://user-images.githubusercontent.com/6519947/179883764-2c082199-557c-4f70-80bf-94fb42af5427.png)

We also confirmed that Exchange 2013 does not support Win2022 AD with a [supportability matrix](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#supported-active-directory-environments).

>![image](https://user-images.githubusercontent.com/6519947/179885673-3ad818ba-a206-4250-b780-716901c376ad.png)

## Ask

Could you remove Win2022 AD support from [Japanese content](https://docs.microsoft.com/ja-jp/exchange/exchange-2013-system-requirements-exchange-2013-help#network-and-directory-servers), please?

**Comment by get-itips** [comment]
Hello @hishikitetsuya 
It seems it was removed, can you please confirm? Thanks

**Comment by get-itips** [comment]
Closing as I see it corrected
