### ISSUE TITLE
Invalid prerequisites are listed for Window 2019 Core OS

### ISSUE THREAD

**Issue by damianscoles** [MicrosoftDocs/OfficeDocs-Exchange#321]
AS-HTTP-Activation is still listed above even though there was a case to remove it.
RSAT-Clustering-Mgmt is listed in the PowerShell code - it is not a valid feature for Windows 2019 Core as far as I can tell.
Windows-Identity-Foundation is also listed in the PowerShell section - it also does not appear valid for Windows 2019 Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prerequisites?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by peterjlay** [comment]
Also, Visual C++ Redistributable Package for Visual Studio 2012 is wrong, as I got this message on Windows Server 2019 Core: Visual C++ 2013 Redistributable Package is a required component. Please install the required binaries and re-run the
setup. Use URI https://www.microsoft.com/download/details.aspx?id=40784 to download the binaries.
For more information, visit: http://technet.microsoft.com/library(EXCHG.150)/ms.exch.setupreadiness.VC2013RedistDependencyRequirement.aspx

**Comment by AndreaBarr** [comment]
@sonika24 Could you please investigate this issue?

**Comment by lusassl-msft** [comment]
@AndreaBarr I think we can close this because documentation was updated.
