### ISSUE TITLE
Modern authentication with IMAP / SMTP 

### ISSUE THREAD

**Issue by thomashvmw** [MicrosoftDocs/OfficeDocs-Exchange#323]
Hi!
The office365 IMAP- and SMTP servers advertize XOAUTH2 as an authentication method, together with the documentation it lead me to believe that modern authentication would be supported, given that the email client supported it. However that doesn't seem to be the case, since the servers are refusing authentication with valid access tokens. Could  you please clarify?

**Comment by AndreaBarr** [comment]
@thomashvmw What articles are you referencing? I want to get this addressed properly and you opened an issue on the base repo instead of an article so I can get the appropriate attention on your issue.

**Comment by lindspea** [comment]
@thomashvmw Please can you confirm the article you are referring to so that I can have this sorted as soon as possible. Thank you for your valuable contribution in helping improve MS Docs.

**Comment by lindspea** [comment]
@thomashvmw We would really like to get this resolved for you so if you still need assistance please re-open the issue when you have the additional information for us and we will gladly assist.

**Comment by lindspea** [comment]
@AndreaBarr @scanum You can close this issue.
