### ISSUE TITLE
missing .\ from Sync-MailPublicFolders.ps1 command

### ISSUE THREAD

**Issue by miryb** [MicrosoftDocs/OfficeDocs-Exchange#324]
step-5-start-the-migration-request, the cmdlet "Sync-MailPublicFolders.ps1 -Credential (Get-Credential) -CsvSummaryFile:sync_summary.csv" doesn't start with .\ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4977532-9e3b-a1c3-3d00-563e01892417
* Version Independent ID: fc52a739-429e-730f-236d-29fe8da80db9
* Content: [Use batch migration to migrate legacy public folders to Office 365 and Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders#step-5-start-the-migration-request)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-legacy-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@miryb I fixed it. Thanks for the feedback.
