### ISSUE TITLE
Off prem exchange source systems

### ISSUE THREAD

**Issue by danderson95** [MicrosoftDocs/OfficeDocs-Exchange#325]
would be nice if you all could include consideration for off-perm exchange solutions like Intermedia.   There seems to be some online doc on using staged and owa, but not sure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 112349e0-4e03-7fd5-0ad8-bf94fef819b2
* Version Independent ID: 34d75478-b734-b814-59e3-b01dd2c7687d
* Content: [Decide on a migration path](https://docs.microsoft.com/en-us/exchange/mailbox-migration/decide-on-a-migration-path)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/decide-on-a-migration-path.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/decide-on-a-migration-path.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@danderson95 Thank you for this suggestion

I will get this sudgestion over to the Exchange writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by msdmaguire** [comment]
@danderson95 Thanks for the suggestion. In many cases, we don't get too in-depth in mentioning third-party products and services because we can't officially support those configurations, should something go wrong. We do document how to migrate from another Exchange server. Thanks again.
