### ISSUE TITLE
User experience when when ABP's exist but none are assigned

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#326]
I have found in testing that if we setup Address Book Policies, additional Address Lists, OAB, GAL, etc. and then leave any users with no policy assigned, these users will see ALL Address Lists.

I think this caveat could be added to the list on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c303bc4b-85f1-0946-287b-3dee7435c559
* Version Independent ID: 359332d1-e8e7-3320-7467-1edec873a18e
* Content: [Scenario Deploying address book policies in Exchange Server](https://docs.microsoft.com/en-us/exchange/email-addresses-and-address-books/address-book-policies/abp-scenarios?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/email-addresses-and-address-books/address-book-policies/abp-scenarios.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/email-addresses-and-address-books/address-book-policies/abp-scenarios.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@JeremyTBradshaw Thank you for this suggestion. 

I'll get this suggestion over to the Exchange team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@JeremyTBradshaw I updated the topic as you described.

Thanks for the feedback.
