### ISSUE TITLE
Warning - not all steps can be scripted in a straightforward manner

### ISSUE THREAD

**Issue by svajda** [MicrosoftDocs/OfficeDocs-Exchange#329]
While most configuration steps in this article can be performed from the command line or Powershell as listed above, Step 2 (enabling Active Directory Client Certificate Authentication) is indeed best performed manually in IIS manager (as correctly suggested by the article). While it may seem that this step can also be performed with a Powershell cmdlet (e.g.: Set-WebConfigurationProperty -PSPath "MACHINE/WEBROOT/APPHOST" -Filter "system.webServer/security/authentication/clientCertificateMappingAuthentication" -Name "enabled" -Value "True"), the Powershell method will actually not set the DefaultFlags value under "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\HTTP\Parameters\SslBindingInfo\0.0.0.0:443" to "1", which is crucial for certificate based authentication to work. So it is best to stick to the manual IIS Manager method in Step 2 (or at least verify the DefaultFlags value as suggested here: https://blogs.msdn.microsoft.com/friis/2017/01/16/the-complete-list-of-changes-to-make-to-activate-client-certificate-mapping-on-iis-using-active-directory/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8139d70-01f2-007d-5630-6287bcd28f10
* Version Independent ID: e7736fce-a1f0-0b6f-40ae-57fc2f34def3
* Content: [Configure certificate based authentication in Exchange 2016](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/post-installation-tasks/configure-certificate-based-auth?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-certificate-based-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-certificate-based-auth.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@svajda Thank you for this feedback

I will get this information over to the Exchange writing team for investigation. 


Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@svajda, thanks for the feedback. I incorporated your comments in Step 2.
