### ISSUE TITLE
legacy.contoso.com: No longer needed for Exchange 2010/2016 coexistence

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftDocs/OfficeDocs-Exchange#33]
Paragraph: "legacy.contoso.com: This host name is required in a coexistence scenario with Exchange 2010. If you'll have clients with mailboxes on Exchange 2010 servers, configuring a legacy host name prevents your users from having to learn a second URL during the upgrade process." should be removed from section "Best practices for Exchange certificates"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86e0c7c-8d35-6385-49f4-b75ade2ed887
* Version Independent ID: fef2f0e5-b17a-c2e1-3a36-6480d03f6106
* Content: [Digital certificates and encryption in Exchange 2016](https://docs.microsoft.com/en-us/Exchange/architecture/client-access/certificates#best-practices-for-exchange-certificates)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/certificates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@MSFT-MarcoEs, OK. Done.
