### ISSUE TITLE
Option 2 needs to be clarified

### ISSUE THREAD

**Issue by RomanNG** [MicrosoftDocs/OfficeDocs-Exchange#330]
It's written that "Direct send cannot be used to deliver email to external recipients, for example, recipients with Yahoo or Gmail addresses." but it's also said before that "Direct send also works for external recipients with mailboxes in Office 365".

So do we have to understant that Direct Send will work for any organization that is hosted on Office 365 ? or is there a mistake about what external récipients means exactly ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3?redirectSourcePath=%252fen-us%252farticle%252fHow-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@RomanNG according to what the topic says, direct send is designed to work with Office 365 mailboxes in *your* organization, but also happens to work with *other* Office 365 organizations (so your second sentence is correct). 

It sounds like if mail from an SMTP source is identified correctly by an SPF record and accepted into one Office 365 organization, that same email source is OK for other Office 365 organizations (but likely could be filtered by other policies/rules that are specific to each organization). At a basic level, that makes sense to me.

But remember, that statement is buried deep within the direct send description. The fundamental point of direct send that is repeated more than once: it isn't designed to work with recipients that are external to *your* Office 365 org. The fact that it *likely* works with *other* Office 365 organizations is a bonus.
