### ISSUE TITLE
Shared mailboxes?

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/OfficeDocs-Exchange#332]
This definitely needs more detailed instructions on shared mailboxes and the steps needed to make them appear as migration options and provisioning (if needed).

There's barely any information to be found. Should we sync them with AAD Connect? I did, because they didn't show up in the migration GUI before. They then appear as used, 'blocked' (disabled) by default, similar to their on-prem versions. I assigned a license, tried to migrate (I know shared mailboxes shouldn't require licenses).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35bd8438-69fb-3da3-1c75-25576fc92fd4
* Version Independent ID: 4dd5a61d-ef30-f893-00c7-bdb9132e074d
* Content: [Move mailboxes between on-premises and Exchange Online organizations in hybrid deployments](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/move-mailboxes)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@jbostoen Thank you for this feedback

I'll get this request for more detailed information on the shared mailboxes over to the Exchange writing team for investigation. 


Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@MK-Kamal Could you please investigate this?

**Comment by ggianelli** [comment]
Any update in shared mailboxes information?

**Comment by scanum** [comment]
@jbostoen Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
