### ISSUE TITLE
DNS change

### ISSUE THREAD

**Issue by mtscheidler** [MicrosoftDocs/OfficeDocs-Exchange#334]
Performing a hybrid migration is designed such that it is more of a transition (over time) versus a cut-over.  Your article, however; does not mention this and glosses over the strategy for updating the DNS records.  If I am moving mailboxes over the course of several weeks, when do I adjust the DNS records? What are the implications of doing so? What if anything needs to be adjusted on the client-side (Outlook desktop/mobile installations)?  Please discuss the real-world impacts.
Also, what if anything needs to be adjusted on the internal DNS architecture?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852cee18-246c-8c33-9834-fd96595b3e71
* Version Independent ID: 094c2d24-81dc-41c7-48be-c61df7b25fbc
* Content: [Use Minimal Hybrid to quickly migrate Exchange mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/use-minimal-hybrid-to-quickly-migrate#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/use-minimal-hybrid-to-quickly-migrate.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@mtscheidler Thank you for this feedback

I will get this request for more details about the hybrid migration over to the Exchange writing team for investigation. 


Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@MK-Kamal Could you please investigate this?

**Comment by fmacbeth** [comment]
Hi
We are about to migrate email to 365. Has there been any more info on the original query about when to change the DNS records?

**Comment by msdmaguire** [comment]
@fmacbeth We are recommending to customers that they work with Microsoft FastTrack for assistance with their email migrations. https://www.microsoft.com/en-us/fasttrack/?rtc=1 Thank you.
