### ISSUE TITLE
Fix the how do you know this worked?

### ISSUE THREAD

**Issue by sunilkms** [MicrosoftDocs/OfficeDocs-Exchange#335]
It should be...

Get-AcceptedDomain | Format-List Name,MatchSubdomains

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e4d207-3c34-02c7-5a9b-3689267c866a
* Version Independent ID: c086dd8e-8fc4-fc3b-de38-ec4b13968d13
* Content: [Enable mail flow for subdomains in Exchange Online](https://docs.microsoft.com/en-gb/exchange/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-accepted-domains/enable-mail-flow-for-subdomains.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @Sirkkuw
* Microsoft Alias: **sirkkuw**

**Comment by chrisda** [comment]
@sunilkms, I fixed it.

Thanks for the feedback.
