### ISSUE TITLE
Article information is not correct and not updated since long time.

### ISSUE THREAD

**Issue by rajee037** [MicrosoftDocs/OfficeDocs-Exchange#336]
Your article says "Exchange 2016 No additional configuration is required."
I am using Exchange 2016 CU 9 and the Organization wide configuration by default has set to "False". I have to manually set this parameter to "True" using below command as you mentioned for Exchange 2013. Also, I found this article is not updated since long time.

Set-OrganizationConfig -ACLableSyncedObjectEnabled $True

To cross verify, I have checked one of the remote-mailbox user (created initially using new-remotemailbox) and found the corresponding AD user has still msExchRecipientDisplayType       : -2147483642 instead of msExchRecipientDisplayType       : -1073741818 

msExchRecipientDisplayType | Value
============================
SyncedMailboxUser                | -2147483642
ACLableSyncedMailboxUser  | -1073741818

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-gb/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@rajee037 Thank you for this feedback

I will get this synced mailbox information over to the Exchange writing team for investigation. 


Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chk1982** [comment]
The new-remotemailbox command creates a remote mailbox in cloud. The article states in the blue bubble: "ACLs aren't enabled on remote mailboxes created in Office 365. If you create a remote mailbox in Office 365, you'll need to follow the steps in the Enable ACLs on remote mailboxes section to enable ACLs on that remote mailbox." What rajee037 is experiencing is exactly as described in the article.

**Comment by AndreaBarr** [comment]
@MK-Kamal Could you please investigate this?
