### ISSUE TITLE
Mail flow reports are great but how to get them programmatically?

### ISSUE THREAD

**Issue by ivanfioravanti** [MicrosoftDocs/OfficeDocs-Exchange#337]
Hi,
Mail flow and in general all reports under Protection center are great. Is there a way to get them programmatically through PowerShell or other APIs? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a45470c-39ed-4c12-2ea9-bff5eef71a65
* Version Independent ID: ca683bed-c6fc-12c1-bcf3-dda1b050d94c
* Content: [Use mail protection reports in Office 365 to view data about malware, spam, and rule detections](https://docs.microsoft.com/en-us/exchange/monitoring/use-mail-protection-reports)
* Content Source: [Exchange/ExchangeOnline/monitoring/use-mail-protection-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/use-mail-protection-reports.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by chrisda** [comment]
@ivanfioravanti depending on the report, you can use [Microsoft Graph](https://go.microsoft.com/fwlink/p/?LinkID=865135) or cmdlets (go [here](https://docs.microsoft.com/powershell/exchange/) and type 'report' in the search box to see what's available).

Some of the reporting cmdlets were deprecated in January. [This blog post](https://techcommunity.microsoft.com/t5/Office-365-Blog/Announcing-the-General-Availability-of-Microsoft-Graph-reporting/ba-p/137838) provides a detailed mapping of the Microsoft Graph replacements (if any) for the deprecated reporting cmdlets.

**Comment by RobLW** [comment]
Just a shame that Power BI cannot easily connect to Microsoft Graph. I had so much hassle trying to set it up (including following a guide that didn't work to create an API connector) that we just gave up.
