### ISSUE TITLE
Spray attack expectations

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-Exchange#339]
This feature is a response to spray attacks against Exchange Online, but does it stop them?

We have had basic auth disabled for all accounts for days, and while we did see a slight slowdown in the attacks over time, and even a cessation for over 24 hours straight, they ultimately continued.

The Azure portal reports them in exactly the same way as before (see below).

Is modern authentication being used for these attacks now (there appears to be no way to tell)?  Is that even possible?  Or is there a flaw in what this policy does?

Username: One of various legit accounts of ours
Application:  Office 365 Exchange Online
Location: Ganhezhen, Shaanxi, CN (as an example)
Status: Failure
Sign-in error code: 50053
Failure reason: Account is locked because user tried to sign in too many times with an incorrect user ID or password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@rpodric Thank you for this inquiry

I am not sure what is handling the spray attacks now. Let me get this over to the Exchange writing team for investigation. 


Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by toledotown** [comment]
I believe the best approach is Modern Auth and MFA. Modern auth alone does not do enough to secure the accounts.

**Comment by rpodric** [comment]
Yes, but MFA is not going to stop the attempts. The question remains about why disabling basic auth, at least for us, seems to have made no reduction in the attempts. It should have made for a night-and-day difference in the logs, as some others have reported in places like Reddit.

**Comment by rpodric** [comment]
@andreabarr

Just wanted to drop a note to mention that despite no basic auth, we're still seeing all kinds of activity (failed logins, lockouts) from all over the world hammering away at Exchange Online's IMAP, as reported by the AAD Sign-in page. This would seem to be in direct contradiction with:

>When it's blocked, Basic authentication in Exchange Online is blocked at the first pre-authentication step (Step 1 in the previous diagrams) before the request reaches Azure Active Directory or the on-premises IdP. The benefit of this approach is brute force or password spray attacks won't reach the IdP (which might trigger account lock-outs due to incorrect login attempts).

Oddly enough, IMAP failed login attempts by me (I tried with a couple of our accounts, including the same ones used by the hackers) with Outlook against our tenant do NOT show up in the Sign-in log at all. This is correct behavior according to the quote above, which states that when Basic Auth is disabled, login attempts using blocked protocols will not reach the IdP. 

This doesn't explain why what the hackers are doing is being logged.

**Comment by ajhstn** [comment]
Same experience as @AndreBarr and @rpodric..

**Comment by ajhstn** [comment]
How is using the authentication policy different to Set-CASMailbox -SmtpClientAuthenticationDisabled $true.

**Comment by ajhstn** [comment]
What's the difference in using set-authenticationpolicy vs set-casmailboxplan

**Comment by rpodric** [comment]
@ajhstn, if it's of any help, ours did finally stop not long after I posted that last message, and I think it's been long enough now that it won't pick up again, but who knows, really. In all, it took about 2-3 weeks once the policy was put into affect and applied (applying it supposedly means that it should be in effect within the hour) for the attempts to stop (all IMAP).

I have heard from someone else that attacks using fake usernames might still reflect in the logs, but we never had any of those (since I've been paying attention to this), for some reason, so that's far from sure. All of ours were using legit accounts. In terms of the log, I don't really know why it would matter.

**Comment by rpodric** [comment]
Stops...for a while. But it always returns. This feature simply must be flawed.
https://i.imgur.com/aLZj44C.jpg

**Comment by rdiazel** [comment]
for anyone facing password spray attacks, I recommend opening a case with MS support. Many different ways can be used for that not only using Exchange legacy clients. I have seen this happening using RDP or going through SSCM. Investigation is required.

**Comment by rpodric** [comment]
They were of no help and just engaged me in a circular discussion over a period of days.

In this case, it's really easy to see exactly what they use in the attacks, since the AAD logs mention it by name: IMAP.  Using RDP would be difficult without an RDS to attack.

**Comment by afield1235** [comment]
Thinking about doing this but if it's not helping then there is no point. MFA and Conditional access only kick in after Successful login, they are essential but only part of the inner layer. The spray attacks are brutal and locking every senior  account. Every IP in the world, China, Brazil, Nigeria, etc. They are all the IMAP protocol which I would block along with POP, we still have too many legacy devices (network scanners, alert sensors, appliances, monitoring etc.) to fully shut down Basic Auth unless we moved those to a different domain. What's the solution here?

**Comment by afield1235** [comment]
Also you need to pay for support now apparently separately if you want to try and resolve this with the Azure AD team. Office365 and Azure AD Premium is not enough anymore, that is really disappointing.

**Comment by rpodric** [comment]
IMAP seems to be their go-to (I'm not sure if I've ever seen an attack using anything else), so if disabling that isn't disruptive, you have nothing to lose by doing it.

Just don't be surprised if the logs still look ugly, since they probably will, defying my understanding of this feature.

**Comment by afield1235** [comment]
well I wonder, are accounts still being locked? Or it's just the logging is noisy?

**Comment by rpodric** [comment]
Lockouts still do occur. Fortunately, they release quickly enough that I haven't received complaints.
https://i.imgur.com/XqQimVb.jpg

**Comment by afield1235** [comment]
@AndreaBarr, @sonika24

What's the deal here? This has been opened for a while and there has been no feedback at all from Microsoft. This thread is the entire reason why you'd want to disable Basic Authentication. Can we please get a clear answer from Microsoft? I don't understand the radio silence.

**Comment by rpodric** [comment]
Take a look at that screenshot in my last post. By saying that's just noise ignores the crux of the issue, which is that users--using legit user accounts--are leveraging BASIC auth (note that it says IMAP, so we're not talking Modern at all) despite it being universally disabled in our tenant. It shouldn't be there to use.

You say there's no way to stop it, but disabling basic auth should, by definition, stop use of basic auth.

Either the log is completely bogus, which is an issue in itself, though a different one; or, this method of disabling basic auth is flawed.

I don't quite follow what you're saying at the end. Is it that disabling basic auth isn't supposed to block anyone who tries to use basic auth?  If so, I don't understand the feature at all. The plumbing that allows making IMAP attempts is severed.

**Comment by afield1235** [comment]
@TechB0t It doesn't help and its anecdotal because you are not Microsoft. No one is asking to "pre block" someone. We are simply requesting a confirmation that a user trying to make a repeated "basic" authentication attempt to a client will not lock their account with basic authentication disabled. 

@rpdoric you provided screenshots that shows accounts are locked, but are the users actually getting locked out or is just "logging" that a locked would've occurred had basic authentication been enabled? What is you intentionally try and lock your account with basic requests? Do you get locked out.

**Comment by afield1235** [comment]
@rpodric you provided screenshots that shows accounts are locked, but are the users actually getting locked out or is just "logging" that a locked would've occurred had basic authentication been enabled? What is you intentionally try and lock your account with basic requests? Do you get locked out.

**Comment by rpodric** [comment]
That's a good question. I'll try to figure out a way to use basic auth to do it. I thought of trying Thunderbird (IMAP), but that didn't even trigger a lockout according to the log. Perhaps it wasn't fast enough?  Any better way to do this?  Here are the rules:

> After 10 unsuccessful sign-in attempts with the wrong password, the user is locked out for one minute. Further incorrect sign-in attempts lock out the user for increasing durations of time. Smart lockout tracks the last three bad password hashes to avoid incrementing the lockout counter for the same password. If someone enters the same bad password multiple times, this behavior will not cause the account to lockout.

**Comment by afield1235** [comment]
I was able to, I used OSX mail and just failed over and over, slightly changing the password each time:
"Account is locked because user tried to sign in too many times with an incorrect user ID or password."

I have IMAP Disabled (Basic is still enabled) though for this user, once again, not sure why authentication attempts are allowed and the account still locks.

**Comment by rpodric** [comment]
Was that an actual lockout?

I was testing with the opposite: a user with IMAP enabled (which is the default, so that's what most tenants are going to have) but basic auth disabled for all protocols and users.

I was doing the same thing as you described but with Thunderbird. Not sure why it didn't trigger anything. To be clear, IMAP most definitely does not work.

**Comment by dstrome** [comment]
hi all,

I'm afraid we can't provide product support in topic comments. If your deployment of Exchange isn't functioning as expected, please contact Microsoft support for assistance.

**Comment by jimhill10** [comment]
Why was an open issue closed?  Are you saying that it was a bug in the software system? We have this same issue going on.  I posted it on https://social.msdn.microsoft.com but answers are not forthcoming.   Guess I'll raise a support ticket.
