### ISSUE TITLE
Ediscovery Export -documentation issue

### ISSUE THREAD

**Issue by brianTGrant** [MicrosoftDocs/OfficeDocs-Exchange#34]
https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/export-search-results
I can see  the date for this page being less than a month  old which makes we wonder ... why ?
You can no longer export .pst from the Old Compliance as pictured and mentioned  - you need to use the new version as you get either objects errors or prompted for domain access against office 365 like you would for an exchange server.
You can go to the new Compliance Center and under Export ; switch bacl to the Legacy where you will in the dialogue recieve  the key and then are able to export
 IE 10 runs very iffy and haven't gotten the Click-one

**Comment by markjjo** [comment]
@brianTGrant - the topic you linked to is about exporting the results of an In-Place eDiscovery in the Exchange admin center in Exchange 2016 Server (on-premises). But your comment sounds like you're trying to export Content Search results from the Security & Compliance Center in an Office 365 cloud-based org. Here are the steps to do that from the new content search UI: [Export search results](https://support.office.com/en-us/article/eDiscovery-cases-in-the-Office-365-Security-Compliance-Center-8dd335ab-29d0-41c3-8dd8-9f7c7481e60c#step5_1) -- and here are export steps for the legacy content search UI: [Export Content Search results](https://support.office.com/en-us/article/eDiscovery-cases-in-the-Office-365-Security-Compliance-Center-8dd335ab-29d0-41c3-8dd8-9f7c7481e60c#step5_1).

**Comment by brianTGrant** [comment]
Hi Mark,
No, I am referring to E-Discovery & I check the URL/location  before posting ..to make sure it referenced Exchange Online
[cid:image006.png@01D4240E.90D55870]See screenshot… maybe I was wrong to assume that was mean for Exchange Online


[cid:image001.png@01D4240E.56F780B0]

Med venlig hilsen / Best regards,
Brian T. Grant

Senior Cloud  Architect

ProActive A/S
MICROSOFT PARTNER OF THE YEAR 2017
MICROSOFT PARTNER OF THE YEAR 2017 - CLOUD INFRASTRUCTURE
MICROSOFT PARTNER OF THE YEAR 2017 – DIGITAL TRANSFORMATION – EMPOWERING EMPLOYEES
Mobile: +45 41723309  •  E-mail:brian.grant@proactive.dk<mailto:brian.grant@proactive.dk> •  Internet: www.proactive.dk<http://www.proactive.dk/>

[Description: Description: Description: \\pafil01.proactive.local\documents\Communication\Marketing\Signature\facebook_16.png]<https://www.facebook.com/pages/ProActive-AS/50229439574>[Description: Description: Description: Follow ProActive on Linkedin]<http://www.linkedin.com/company/proactive-as>[Description: Description: Description: Follow ProActive on Twitter]<https://twitter.com/#!/ProActiveIT>

**Comment by markjjo** [comment]
Hi Brian,

Ok, so it sounds like you are trying to export search results to a PST file from an In-Place eDiscovery search in the Exchange admin center in Exchange Online? Yesterday, I was not able to repro your issue. I was able to successfully export search results to a PST file as per the documentation. Maybe you coud send me some screen shots and/or the steps you are using that are not working. Sorry for the hassle and that I'm probably not understanding the issue.

**Comment by kenwith** [comment]
@brianTGrant  - thank you for submitting feedback and for clarification.

Sorry for the delay on this. I am afraid your issue will go stale in this list as this is for documentation. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

If I made a mistake and you are referring to a change that needs to happen in the article please let me know and I will get it added to the backlog so the writing team can prioritize it and get it into a sprint. Thanks again!
