### ISSUE TITLE
Migration batch hang in 'Starting' state.

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/OfficeDocs-Exchange#342]
We have had 2 hours troubleshooting phone call with MS. Please add a comment somewhere, where the following check must be in the pre-requirements ("before you begin"):
(get-mailbox -Arbitration -Identity Migration.*).servername = (hostname)
If the 'Migration' Arbitration mailbox is not moved to the Exchange 2016 server, the migration batch will hang in the 'Starting' state. No error showed, no log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6010593-c3e4-87a6-4084-27d56f23063c
* Version Independent ID: 32a2adeb-0932-3236-09d9-b7987393639b
* Content: [Use batch migration to migrate Exchange 2010 public folders to Exchange 2016](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/batch-migration-from-previous-versions?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@uz-it can you give some context for this?

They run the cmdlet "(get-mailbox -Arbitration -Identity Migration.*).servername = (hostname)" without the quotes, in order it identify the Arbitration mailbox, correct? And they take this information and make sure that that mailbox is migrated from 2010 or else you may hang in the 'Starting' state.

Also what do you mean by "'Migration' Arbitration mailbox'"?

**Comment by uz-it** [comment]
((get-mailbox -Arbitration -Identity Migration.*).servername -eq (hostname) )
Should return $True.
" 'Migration' Arbitration mailbox "means a Mailbox name starting with 'Migration' when you run the command: Get-Mailbox -Arbitration

**Comment by msdmaguire** [comment]
@uz-it thanks for the info. Also, can you link your GitHub account to your MSFT alias? That way we know when content requests are internal versus external, which is a metric we measure.

I will add this to the article for 2016/2019 and for 2013.
