### ISSUE TITLE
Updating Response to first question

### ISSUE THREAD

**Issue by sar9199** [MicrosoftDocs/OfficeDocs-Exchange#343]
As it's mentioned in response to first question explaining the difference between owner & moderator. 
"The owner of a distribution group is responsible for managing the distribution group membership, but he or she might not be able to moderate messages sent to it"
Slight correction, if you're one of the owner and you send message it will NOT go to moderator for approval. Save you couple of hours troubleshooting time :) 
Tested & validated with OnPrem Exchange 2016.
Cheers, Salman [Notes from Field]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9389be9-edde-da61-e370-7939c1d7cf4f
* Version Independent ID: 98df220c-0e27-9498-7cee-86d8ef0f91e5
* Content: [Manage message approval](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/manage-message-approval)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-message-approval.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/manage-message-approval.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by chrisda** [comment]
@sar9199, I updated the topic as you described.

Thanks for the feedback.
