### ISSUE TITLE
SPF record format

### ISSUE THREAD

**Issue by modangsr2** [MicrosoftDocs/OfficeDocs-Exchange#347]
Hi, 
The SPF record examples of the "Best Practices" section looks invalid. First example uses the mechanism "ipv4" the valid mechanisms:  a, mx, ptr (do not use), ip4, ip6, exists - based on https://tools.ietf.org/html/rfc7208#section-5.6. The second example starts with "v= ipv4" it should be v=spf1 and ipv4 should not be used (ip4 instead).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 884ccdaf-c60f-293a-b7f7-b4edc559546c
* Version Independent ID: 6265a100-939a-75b3-d2ae-86798aaf79b4
* Content: [Manage mail flow using a third-party cloud service with mailboxes on Office 365 and on-prem](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @tirich
* Microsoft Alias: **tirich**

**Comment by chrisda** [comment]
@modangsr2 I made the corrections as you described.

Thanks for the feedback.
