### ISSUE TITLE
Bad link in mail flow troubleshooter section

### ISSUE THREAD

**Issue by timheuer** [MicrosoftDocs/OfficeDocs-Exchange#349]
In the mail flow troubleshooter section (https://docs.microsoft.com/en-us/exchange/fix-outlook-connection-problems-in-office-365/fix-outlook-connection-problems-in-office-365/find-and-fix-email-delivery-issues-as-an-office-365-for-business-admin#use-the-mail-flow-troubleshooter-to-find-missing-email-from-the-past-week---10-minutes) it has a link to the mail flow troubleshooter, but that fails as configure.office.com is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc925ac7-8ca7-2cdf-ab02-2fc40a262924
* Version Independent ID: 3b0d617f-4f3f-68f7-3267-1219a4713d86
* Content: [Find and fix email delivery issues as an Office 365 for business admin](https://docs.microsoft.com/en-us/exchange/fix-outlook-connection-problems-in-office-365/fix-outlook-connection-problems-in-office-365/find-and-fix-email-delivery-issues-as-an-office-365-for-business-admin#use-the-mail-flow-troubleshooter-to-find-missing-email-from-the-past-week---10-minutes)
* Content Source: [Exchange/ExchangeOnline/fix-outlook-connection-problems-in-office-365/fix-outlook-connection-problems-in-office-365/find-and-fix-email-delivery-issues-as-an-office-365-for-business-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/fix-outlook-connection-problems-in-office-365/fix-outlook-connection-problems-in-office-365/find-and-fix-email-delivery-issues-as-an-office-365-for-business-admin.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @scotvidican
* Microsoft Alias: **scotv**

**Comment by chrisda** [comment]
@timheuer, it would appear the mail flow troubleshooter is no more, so I completely removed that section with the bad link from the topic.

**Comment by timheuer** [comment]
👍
