### ISSUE TITLE
Please simply state how to input several keywords to search message body and subject.

### ISSUE THREAD

**Issue by missilelaunchr** [MicrosoftDocs/OfficeDocs-Exchange#35]
Common use case: need to search for several keywords.  This is made incredibly complex by this document, no where in here does it appear to say how to simply input keywords and search message body and subject as is a common use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f0a23e-30ed-52d8-62b8-bb90980276dd
* Version Independent ID: 533ffa30-d35f-d46b-7a04-67807de8da42
* Content: [Message properties and search operators for In-Place eDiscovery in Exchange 2016](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/ediscovery/message-properties-and-search-operators)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/ediscovery/message-properties-and-search-operators.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/ediscovery/message-properties-and-search-operators.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by kenwith** [comment]
@missilelaunchr - I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. And sorry for the long delay and confusion you experienced in the article. The feedback is much appreciated so it can be clarified.

I made a note to request the team to update this when the work is complete.

**Comment by SerdarSoysal** [comment]
@missilelaunchr this article is a reference article and is not really a guide for doing searches. You may find the following article to be more useful:
https://docs.microsoft.com/en-us/exchange/policy-and-compliance/ediscovery/create-searches?view=exchserver-2019
