### ISSUE TITLE
Issuance Transform Rules

### ISSUE THREAD

**Issue by nischl** [MicrosoftDocs/OfficeDocs-Exchange#36]
where is the documentation on that you need to provide two claim rules (upn and sid) to make it work? In my test environment one single rule for upn is sufficient. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb6e204-9bfe-c2b3-410f-fefec93e9d6e
* Version Independent ID: 5b206477-5a90-6982-c5fb-e11d1be4ea95
* Content: [Use AD FS claims-based authentication with Outlook on the web](https://docs.microsoft.com/en-us/Exchange/clients/outlook-on-the-web/ad-fs-claims-based-auth)
* Content Source: [Exchange/ExchangeServer/clients/outlook-on-the-web/ad-fs-claims-based-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-on-the-web/ad-fs-claims-based-auth.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nischl, the answer I got was: the SID claim rule had to do with group membership, and possibly resource forest deployments. It's one of those situations where that's what was tested, so that's what's supported.

**Comment by nischl** [comment]
interesting, so no one knows how that stuff actually works but all use it for security-related things

**Comment by kenwith** [comment]
@nischl - I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

**Comment by nischl** [comment]
@kenwith I can't follow you. There is no issue to be resolved. I am looking for documentation. Here should be the place to find it. 
In addition, I do not know what " in your tenant" means. The video addresses office 365, this documentation is for on-premises Exchange

**Comment by kenwith** [comment]
@nischl - please open a support request through your normal channels then and they can work with you to make sure what you need is resolved. When you open a support request your issue will be escalated to an engineer for that particular area. If the documentation doesn't already exist then they will open a service item to get it created.

I wish I could answer your question regarding this particular issue but I don't know the answer. The escalation engineers will know the answer.
