### ISSUE TITLE
What are my options on what to do with the user account once placed on legal hold

### ISSUE THREAD

**Issue by cfizz34** [MicrosoftDocs/OfficeDocs-Exchange#364]
If in a hybrid environment, once all mailboxes are on legal hold or in-place hold can I remove the license and also delete the AD account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c31e2ef-896e-edde-bbd9-2f9054cc41b0
* Version Independent ID: 9417809f-106c-bf7d-206f-d057320edf6a
* Content: [Place all mailboxes on hold](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/holds/place-all-mailboxes-on-hold?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/holds/place-all-mailboxes-on-hold.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/holds/place-all-mailboxes-on-hold.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by AndreaBarr** [comment]
@cfizz34 Thank you for this inquiry

@MK-Kamal Could you please look into this issue?

**Comment by MK-Kamal** [comment]
@cfizz34 Thank you for your  inquiry

If you are using one of these office365 License Plans “ Exchange Online Plan 2 Or Office 365 Enterprise E3 or E5 subscriptions “ you can Use  Inactive Mailboxes Feature in Office 365 which will retain Users Email Even if you remove user Office 365 License or Delete the AD account 

[Overview of Inactive Mailboxes in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/inactive-mailboxes-in-office-365)

If you use "Exchange Online Plan 1" and you would like to use Inactive Mailbox,  you will have to assign a separate Exchange Online Archiving license to the mailbox 

Thanks

**Comment by cfizz34** [comment]
Is using the Inactive method over converting the mailbox to a shared mailbox a better alternative if the end goal to release the E3 license and delete the AD account while also being able to do e-discovery and re-assign that mailbox to a new user if taking the place of the old user?
