### ISSUE TITLE
An article for Exchange Online shouldn't reference Windows Server backup

### ISSUE THREAD

**Issue by scorp508** [MicrosoftDocs/OfficeDocs-Exchange#365]
https://docs.microsoft.com/en-us/Exchange/back-up-email

This entire section seems irrelelvant to the article.

**Backing up Exchange Server**
Read Using Windows Server Backup to back up and restore Exchange data for more info about backing up Exchange Server 2016 and Exchange Server 2019.

It also seems a bit odd of us to suggest users move/copy/export data to PST files in the "How do users backup Outlook data?" section. This suggestion goes against all of our technology investments for the last few years of ingesting content and helping customres get rid of PST files. We want to help remove PST files as much as possible to prevent data being stored in unknown unmanaged locations making it harder to discover and easier for the customer to lose control of.

**Comment by scorp508** [comment]
Thanks @chrisda , I just happened to catch this one as the official MSFTExchange twitter handle tweeted it out over the weekend. : )

**Comment by chrisda** [comment]
@scorp508, that Backup topic has been reconfigured for as an Exchange Online only topic (all on-prem references removed) and generally modernized.
