### ISSUE TITLE
More detail needed -- throttling settings

### ISSUE THREAD

**Issue by schnitz76** [MicrosoftDocs/OfficeDocs-Exchange#369]
Please update documentation to include more details on when and how the changes will be applied.  I have created a throttling policy and associated it to a user.  It took days for the throttling policy to apply.  I have updated the throttling policy and need to know how to get the changes to apply to the user.  I can see through powershell that the values of the throttling policy have changed, but they clearly have not been applied.  

The 'How do you know this worked?' section is a bit misleading.  There are differences between how powershell tells you it is working and how the actual Exchange server is processing mail (how it is actually working).

What do I need to do to get real world results, restart the server, restart one or more services, restart IIS, wait for Exchange replication, wait for Active Directory replication, migrate the mailbox, or some combination of the above?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d33763-239e-1759-b3df-0ebad213bc79
* Version Independent ID: e07350ee-f70c-2900-e182-3b7b0f9d72f4
* Content: [Change user throttling settings for specific users: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/change-user-throttling-settings-for-specific-users-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/change-user-throttling-settings-for-specific-users-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/change-user-throttling-settings-for-specific-users-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by AndreaBarr** [comment]
@schnitz76 Thank you for this inquiry. 

@sonika24 Could you please work on this?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@sonika24 Any updates on this? Thanks!

**Comment by j0rt3g4** [comment]
@scanum

**Comment by j0rt3g4** [comment]
@scanum What's the status of this?
This should be closed already :)

**Comment by j0rt3g4** [comment]
Hello @scanum  any update on this?

**Comment by scanum** [comment]
@schnitz76 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
