### ISSUE TITLE
Step 4: Configure directory synchronization

### ISSUE THREAD

**Issue by student-forever** [MicrosoftDocs/OfficeDocs-Exchange#37]
Directory synchronization now supports syncing mail enabled public folder: 
Please see:

https://blogs.technet.microsoft.com/exchange/2017/05/19/office-365-directory-based-edge-blocking-support-for-on-premises-mail-enabled-public-folders/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e1da85-b81e-53d3-776a-3f31a15953ff
* Version Independent ID: 64d910e2-a9b2-452a-c290-331b68722b5d
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-us/Exchange/collaboration/public-folders/configure-legacy-public-folders-for-hybrid)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/configure-legacy-public-folders-for-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/configure-legacy-public-folders-for-hybrid.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scorp508** [comment]
Unless something recently changed the sync isn't all the way to EXO. AAD Connect does sync MEPFs to AAD, but they are not forward sync'd from AAD to EXO. The PowerShell scripts are still required to get MEPF objects into EXO.

**Comment by student-forever** [comment]
Hey Brian, Thank your for replying. The article I had referenced, says that the purpose of syncing MEPF is to ensure DBEB    doesn't reject emails addressed to MEPF. Unless the MEPF syncs from AAD to EXO, that wouldn't be possible, as DBEB is an EXO feature not AAD.

**Comment by scorp508** [comment]
That is correct, MEPF objects are sync'd to AAD in order to make DBEB work within EOP. However, the interesting thing is EOP does not utilize the EXO AD database to find/read mail enabled objects. That probably sounds a bit odd. Instead, EOP uses AAD to find/read those objects. When mail enabled objects are created directly inside of EXO, meaning objects which aren't sync'd into EXO via AAD Connect, those objects go through a write-back mechanism where the object is copied from EXO's Active Directory database to AAD so it can then be discovered by EOP and included in the DBEB feature.

**Comment by student-forever** [comment]
That does sound interesting and makes me wonder as to why th EOP servers wouldn't connect to the EXO AD and instead rely on AAD as the primary objective of EOP is to protect the mail enabled objects only AAD could host both mail enabled and disabled objects. I would also appreciate if you could point me to any public article which explains how O365 EXO, AAD, SPO SFBO and other workloads replicate among themselves.

**Comment by scorp508** [comment]
I suspect it has to do with the fact that EOP can be purchased as a standalone offering, so it has to be able to operate on its own as not every customer using it uses EXO. I'm not personally aware of a documented breakdown of how the different environments sync across each other as its normally just behind-the-scenes work which doesn't typically offer much value to know. :) This is a bit if a corner case here.

**Comment by student-forever** [comment]
That does sound like a distinct possibility. Well, I appreciate your time and thank you so much for indulging me.
