### ISSUE TITLE
Modern auth either is or isn't enabled by default

### ISSUE THREAD

**Issue by rpodric** [MicrosoftDocs/OfficeDocs-Exchange#371]
This article says: "Verify that modern authentication for Outlook desktop clients is enabled in your Exchange Online organization (it's disabled by default). For more information, see Enable or disable modern authentication in Exchange Online."

But it links to an article that says this: "Modern authentication is enabled by default in Exchange Online, Skype for Business Online and SharePoint Online."

Offhand, I don't recall which is true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/Exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@rpodric, Modern Auth is enabled by default in Exchange Online. I think there might have been some mixing of Outlook vs. the Exchange Online organization going on in that sentence, so I changed it to:

> Verify that modern authentication is enabled in your Exchange Online organization (it's enabled by default). For more information, see Enable or disable modern authentication in Exchange Online."

Thanks for the feedback.
