### ISSUE TITLE
OWA Region and time zone settings tab makes a change by default

### ISSUE THREAD

**Issue by sm5por** [MicrosoftDocs/OfficeDocs-Exchange#373]
I'm an Outlook Web App end user (thus I have no control over my site's Exchange Server configuration). Version information may be obtainable, but I don't want to call our support staff over this minor issue if it isn't really necessary. "?" -> "Privacy notice" -> "Product Feedback" led me here.
When I browse the settings in the General section (from "My account" to "Text messaging") without making any changes, I'm allowed to leave every tab except "Region and time zone settings" where I'm asked to either Save or Discard a change I didn't knowingly make (or Cancel the action). It appears the "Rename default folders so their names match the specified language" checkbox is checked automatically as I enter the tab, because when I manually uncheck it, the Save and Discard icons turn light gray and the exit alert goes away. When I reenter the tab, the checkbox is checked again, rinse and repeat.
I'm using Firefox under Linux and I have my OWA interface language set to English (in spite of being in Sweden). Checking with a colleague who uses the Swedish interface, he was able to reproduce the behaviour using Firefox, Edge and (I think) Google Chrome under Microsoft Windows. Another colleague was unable to reproduce it, but we didn't do any substantial comparison of environment factors.
Is it a bug or a misunderstood feature? Seems unintuitive to me to be asked to confirm a change I'm not aware of, especially one that is likely to have a permanent effect, though my default folders seem to be in English already (Drafts, Inbox etc).

**Comment by lindspea** [comment]
@sm5por. Hi Anders.  Please can you confirm if this issue has been resolved.  If not I would like to investigate further for you to have it resolved soonest.

**Comment by lindspea** [comment]
@sm5por. Hi Anders.  If this issue has not been resolved yet, please re-open the issue and we will gladly assist to have it sorted as soon as possible.

**Comment by lindspea** [comment]
@scanum  @AndreaBarr this can be closed.

**Comment by corebase22** [comment]
> `[https://m.youtube.com/](https:/www.youtube.com/maps3d) `

**Comment by corebase22** [comment]
> I'm an Outlook Web App end user (thus I have no control over my site's Exchange Server configuration). Version information may be obtainable, but I don't want to call our support staff over this minor issue if it isn't really necessary. "?" -> "Privacy notice" -> "Product Feedback" led me here.
> When I browse the settings in the General section (from "My account" to "Text messaging") without making any changes, I'm allowed to leave every tab except "Region and time zone settings" where I'm asked to either Save or Discard a change I didn't knowingly make (or Cancel the action). It appears the "Rename default folders so their names match the specified language" checkbox is checked automatically as I enter the tab, because when I manually uncheck it, the Save and Discard icons turn light gray and the exit alert goes away. When I reenter the tab, the checkbox is checked again, rinse and repeat.
> I'm using Firefox under Linux and I have my OWA interface language set to English (in spite of being in Sweden). Checking with a colleague who uses the Swedish interface, he was able to reproduce the behaviour using Firefox, Edge and (I think) Google Chrome under Microsoft Windows. Another colleague was unable to reproduce it, but we didn't do any substantial comparison of environment factors.
> Is it a bug or a misunderstood feature? Seems unintuitive to me to be asked to confirm a change I'm not aware of, especially one that is likely to have a permanent effect, though my default folders seem to be in English already (Drafts, Inbox etc).

translate.
