### ISSUE TITLE
Please increase the rule space limit

### ISSUE THREAD

**Issue by gmfricke** [MicrosoftDocs/OfficeDocs-Exchange#374]
256 KB translates to just over 100 rules on average. I correspond with many more people and organizations than that and would like my email system to automatically put emails in the right folders.

It would also be good if there were some feedback to the user when the space is exceeded. Currently, rules just fail to get applied.

All the best,

Matthew Fricke

**Comment by scanum** [comment]
@gmfricke Hi Matthew! Thank you very much for your kind feedback. We recommend that you submit this feedback into Outlook [Uservoice](https://outlook.uservoice.com/). Exchange does not have a UseVoice channel, however, the Outlook team works with Exchange to add features when needed. The team will evaluate and take the appropriate action, as per their schedule. We strongly appreciate you for taking time and sharing your feedback.
