### ISSUE TITLE
Issue in Step 3

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/OfficeDocs-Exchange#375]
https://www.mwit.co.nz/blog/
1) Remember that the new Public Folders are stored in User Mailboxes which are associated with AD user accounts. If you aren’t syncing your entire Active Directory forest then the Public Folder Mailbox objects may not be synced to Exchange Online. So where are these stored by default? Well in the Users container in your exchange enabled domain of course.
It’s likely that you haven’t synced this but you CAN move these objects to an OU that is being synced without any impact. Unfortunately this requirement isn’t included in the documentation. If these objects aren’t synced to Exchange Online then you’ll get the following message

Set-OrganizationConfig -PublicFoldersEnabled Remote -RemotePublicFolderMailboxes PFMailbox1
Couldn't find object "PFMailbox1". Please make sure that it was spelled correctly or specify a different object.
    + CategoryInfo          : NotSpecified: (:) [Set-OrganizationConfig], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : [Server=SYAPR01MB2717,RequestId=d79eaa00-ff32-4076-8791-54ba22e3cb76,TimeStamp=26/11/201
   8 7:13:26 AM] [FailureCategory=Cmdlet-ManagementObjectNotFoundException] C4302B7C,Microsoft.Exchange.Management.Sy
  stemConfigurationTasks.SetOrganizationConfig
    + PSComputerName        : outlook.office365.com

Please Update the article with more information in Step 3. 
Microsoft PS case id: REG:118120819433003] PREM| Exchange Server Enterprise 2016 | users migrated to O365 cannot see or get access to on premier public folder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@uz-it We've added a note to the "What do you need to know before you begin" section that tells users to synch their container with their public folder mailboxes in it. Should publish by end of week. Thanks again.
