### ISSUE TITLE
Mailbox: 128GB minimum recommended  

### ISSUE THREAD

**Issue by emilabbas** [MicrosoftDocs/OfficeDocs-Exchange#376]
Hi, could you please clarify this requirement?
For installation of Exchange I need minimum 128GB of ram?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server system requirements](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by khorne3** [comment]
Hi @emilabbas. You're correct in that 128 GB of RAM (min) is recommended if you're installing the Mailbox Exchange role (which it seems like you are based on the title of your post.

**Comment by khorne3** [comment]
@AndreaBarr Will clarify and update doc if necessary.

**Comment by chrisda** [comment]
@emilabbas, also keep in mind that Exchange 2019 is designed and optimized for large organizations.

**Comment by emilabbas** [comment]
> Hi @emilabbas. You're correct in that 128 GB of RAM (min) is recommended if you're installing the Mailbox Exchange role (which it seems like you are based on the title of your post.

Hi @khorne3  I don't understand one thing this requirement for big organizations or for small too?
If i want to use Exchange 2019 for 30 employees it is ok to run server with 16 GB or 32?
If i will have problems with server and ask Microsoft Support for help it will be the problem?

**Comment by emilabbas** [comment]
> @emilabbas, also keep in mind that Exchange 2019 is designed and optimized for large organizations.

Hi @chrisda I understand that all Exchanges versions for big organizations. But on Exchange 2016 there was minimum requirement for ram 16 GB, i understand that i cant use 16 GB for corporation with 1000 users. But it is clear that i can launch server with 16 GB RAM and expand on demand. But on Exchange 2019 technet writes that minimum RAM is 128.  So 128 for 1000 users? and it is supported that i can run Exchange 2019 for 10-30 users with 16 or 32 GB RAM. Please clarify
