### ISSUE TITLE
Video about mailbox migration across tenants is unavailable

### ISSUE THREAD

**Issue by jpawlowski** [MicrosoftDocs/OfficeDocs-Exchange#377]
The overview video won't play :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Office 365 tenant to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@jpawlowski thanks for bringing to our attention. We will look into this.

**Comment by msdmaguire** [comment]
@jpawlowski Thanks again for alerting us to this. The team that owns the video took it down for revisions. I will remove references to the video from the article until we're ready to post it again.

**Comment by marilometa** [comment]
Still waiting for the video (it's been a year)
