### ISSUE TITLE
Possible Bad Link

### ISSUE THREAD

**Issue by jpozzoli** [MicrosoftDocs/OfficeDocs-Exchange#378]
When clicking on the link "Force directory synchronization" it takes me to a page on Hybrid Identity (https://docs.microsoft.com/en-us/azure/active-directory/hybrid/whatis-hybrid-identity)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by jamesrhea** [comment]
@jpozzoli, thanks for raising this issue. I agree the link looks incorrect. Here's a Microsoft Support article that explains how to force directory synchronization. See "Method 1": https://support.microsoft.com/en-us/help/2882421/directory-synchronization-to-azure-active-directory-stops-or-you-re-wa
