### ISSUE TITLE
Using Resource Mailboxes for Team Calendars

### ISSUE THREAD

**Issue by jwckauman** [MicrosoftDocs/OfficeDocs-Exchange#38]
In the documentation, it says "If your organization wants to use a room mailbox like a team calendar, consider using Exchange's shared calendar features."   Are you saying that resource mailboxes (either room or equipment) are no longer the preferred method for team calendars?   I thought Microsoft used to encourage using resource mailboxes for team calendars.

**Comment by kenwith** [comment]
@jwckauman - thank you for submitting feedback. 

This is a good point you bring up and I want to make sure it gets addressed properly for you and escalated. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs please let me know.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
