### ISSUE TITLE
contradiction with ci-directional sync note?

### ISSUE THREAD

**Issue by chwilfing** [MicrosoftDocs/OfficeDocs-Exchange#380]
&lt;snip&gt;Note
Outlook for Android supports bi-directional contact synchronization. If a user edits a field in the native contacts app that is restricted (such as the Notes field), then that data will not synchronize back into Outlook for Android.
&lt;/snip&gt;

I guess this should be 'does NOT support bi-directional' or it should so 'Data will synchronize back' ... this way It's a contradiction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@chwilfing Thanks for pointing this out. It actually DOES support bi-directional, Outlook for Android, but the second sentence needed a clarifying "However" added to it. Article will be updated.
