### ISSUE TITLE
Configuration does not work as expected

### ISSUE THREAD

**Issue by DavidOgborne** [MicrosoftDocs/OfficeDocs-Exchange#381]
Following this configuration means that mail flow is received by the Exchange Server and proxied via the Client Connector over port 465. This is not expected as the traffic should not be classified as being from a client. The mail flow should be treated as internal Exchange traffic and picked up by the internal 'hidden' proxy connector. 
Can you please update the documentation with the correct configuration or remove the article as it is miss leading (and wasted a lot of time effort and re-work). I have raised this to premier support who have also re-created the same issue and have said that the documentation is incorrect. 
I normally delete the client receive connectors as they are usually not used. Deleting these connectors means that mail flow from the Edge server to the Exchange Server does not work. Also trying to use TLS and basic authentication does not work in the above article. 
Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fa1930-78e3-6fc7-0d1d-3a1bb0ab5753
* Version Independent ID: d33fd006-3fcf-519f-f970-d02462e89277
* Content: [Configure Internet mail flow through Edge Transport servers without using EdgeSync](https://docs.microsoft.com/en-us/exchange/architecture/edge-transport-servers/configure-without-edgesync?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/edge-transport-servers/configure-without-edgesync.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/edge-transport-servers/configure-without-edgesync.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@DavidOgborne, surely there are some steps in the topic that are still correct (e.g. Step 1 on the Edge Transport server where you create a Send connector for the internet).

Since you've obviously gone through this recently, can describe what's wrong with a specific step and how it should be corrected?

That topic has been kicked forward since Exchange 2007, and the architecture change in 2013 probably didn't do it any favors, but I'm pretty sure that topic just describes how to recreate or modify the Send connectors and Receive connectors that are created or modified by EdgeSync, anyway?

Thanks for the feedback.

**Comment by DavidOgborne** [comment]
@chrisda Thanks for the reply. You are correct in that some of the steps do work. 
The from Edge to Exchange uses the a frontend connector. The message is received but the proxied through to the client connector. You can see this in the logs as the message comes through. The next issue was that the Exchange certificates was self signed and not trusted. Removing TLS meant that the email was accepted. Support did not fix the issue and advised the following: 

Hi David,
 
I’m able to repro the issue from my side. This is how I tested:
 
1.	Enable basic auth on the receive connect.
2.	Create a test account and grant it local admin permission.
3.	Telnet 25 port and input user and password in Base64 encoding (https://www.ndchost.com/wiki/mail/test-smtp-auth-telnet).
4.	In the SMTP log, 
 
2018-11-29T01:53:23.535Z,E16A\Default Frontend E16A,08D6559619724FA3,6,[::1]:25,[::1]:34479,>,334 <authentication response>,
2018-11-29T01:53:28.951Z,E16A\Default Frontend E16A,08D6559619724FA3,7,[::1]:25,[::1]:34479,*,SMTPSubmit SMTPSubmitForMLS SMTPAcceptAnyRecipient SMTPAcceptAuthenticationFlag SMTPAcceptAnySender SMTPAcceptAuthoritativeDomainSender BypassAntiSpam BypassMessageSizeLimit SMTPSendEXCH50 SMTPAcceptEXCH50 AcceptRoutingHeaders AcceptForestHeaders AcceptOrganizationHeaders SendRoutingHeaders SendForestHeaders SendOrganizationHeaders SendAs SMTPSendXShadow SMTPAcceptXShadow SMTPAcceptXProxyFrom SMTPAcceptXSessionParams SMTPAcceptXMessageContextADRecipientCache SMTPAcceptXMessageContextExtendedProperties SMTPAcceptXMessageContextFastIndex SMTPAcceptXAttr SMTPAcceptXSysProbe,Set Session Permissions
2018-11-29T01:53:28.951Z,E16A\Default Frontend E16A,08D6559619724FA3,8,[::1]:25,[::1]:34479,*,johnzhu@tailspintoys.com,authenticated
2018-11-29T01:53:28.951Z,E16A\Default Frontend E16A,08D6559619724FA3,9,[::1]:25,[::1]:34479,*,,Setting up client proxy session to destination(s): E16B.tailspintoys.com;E16A.tailspintoys.com
 
So I believe using basic authentication is not the correct way to configure internal mail flow between O365 and onprem. The Technet article is misleading and I will feedback to the KB team to correct this.
 
After some research, there are 2 ways to enable internal mail flow in Hybrid environment:
 
1.	Enable Edge Sync. So the mail flow is O365 ---TLS with cert---> Edge ---Edgesync---> Exchange server.
2.	Use “Externally Secured”. The mail flow is O365 ---TLS with cert---> Edge ---Externally Secured---> Exchange server.  
 
Here is the document to enable anonymous relay with externally secured enabled: 
 
Allow anonymous relay on Exchange servers
https://docs.microsoft.com/en-us/exchange/mail-flow/connectors/allow-anonymous-relay?view=exchserver-2019 
 
Please let me know if there is anything unclear.

We have opted to use EdgeSync but it means that we have spent a lot of time on troubleshooting the issue. It doesnt look like many people use Edge or manual EdgeSync.

**Comment by chrisda** [comment]
@DavidOgborne, interesting that one of the suggestions was to use EdgeSync; the whole point of the topic is if you don't want to or can't use EdgeSync. Externally Secured is definitely an option, but if you don't configure the external encryption, the traffic isn't encrypted.

I incorporated most of this information into the topic.

Thanks for the feedback.
