### ISSUE TITLE
SPE still referenced

### ISSUE THREAD

**Issue by edbakermct** [MicrosoftDocs/OfficeDocs-Exchange#383]
Under item 5 of the tech and licensing requriements.

 Microsoft Secure Productive Enterprise (SPE) includes all licenses necessary for Office 365 and EMS.

SPE is circa 2015/16

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0020c770-fbf0-d36b-196c-59fd0a5dbe93
* Version Independent ID: bd5c069a-c325-28cf-5a58-8ae9c34c793d
* Content: [Using hybrid Modern Authentication with Outlook for iOS and Android](https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/use-hybrid-modern-auth?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/use-hybrid-modern-auth.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by nenonix** [comment]
@edbakermct  Thank you for your feedback.  I will work with you to address this issue but can you provide more detail or help me by explaining how to make that clearer in the text?

**Comment by edbakermct** [comment]
Not sure what more you need SPE was a marketing title for what is now Microsoft 365 (less Windows) as far as I am aware it is no longer marketed like that, if it is can you point me to the SKUs to buy SPE , thanks Ed

**Comment by edbakermct** [comment]
when i search for spe online any links take me to M365 page and the only blog i can find is a US partner blog from early 2017

**Comment by nenonix** [comment]
@edbakermct  Thank you for clarifying the issue.  I work as a technical writer to improve the content so I am trying to get a sense of how this can be fixed.  Would removing the sentence - which appears to be redundant -  address the issue to your satisfaction?

**Comment by edbakermct** [comment]
i would remove it is  not relevant at all. especially as not all editions of M365 include all licenses needed

**Comment by nenonix** [comment]
@edbakermct Thank You for your patience in explaining the issue and for helping to improve the content.  I will submit the change you suggest.
