### ISSUE TITLE
Does Outlook app encrypt it's data at rest on the mobile device?

### ISSUE THREAD

**Issue by TheRobinCM** [MicrosoftDocs/OfficeDocs-Exchange#387]
I'm particularly interested if the email data and attachments are stored securely on the mobile device, i.e. encrypted by the Outlook app itself to prevent interference from other apps on the phone.
The device itself may be fully encrypted, but if other apps on the device are able to read the files (e.g. a file manager or malicious app), full device encryption doesn't help.
I don't like the idea of having company data sat in plain text on a BYOD phone or tablet.
Please can you clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook for iOS and Android in Exchange Online FAQ](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@TheRobinCM I'm going to try to get clarity from the product team on this.

**Comment by msdmaguire** [comment]
@TheRobinCM Intune App Protection Policies can be used to encrypt corporate data. For more information, see “What about encryption?” section in https://docs.microsoft.com/en-us/intune/mam-faq. Hope this helps.
