### ISSUE TITLE
Calendar sharing supported

### ISSUE THREAD

**Issue by GuyGroeneveld** [MicrosoftDocs/OfficeDocs-Exchange#389]
What you say is not clear
"Private items When adding a delegate the option can be configured to allow a user with folder permissions to see private calendar items."

Can you be more explicit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/Exchange/permissions)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by chrisda** [comment]
@GuyGroeneveld, I updated the topic to say:

When you grant **Full Access** permission to a mailbox, you can decide whether to allow the delegate to see private items (private meetings, appointments, contacts, or tasks) in the mailbox.
