### ISSUE TITLE
Documentation Neglects to mention adding Custom theme to stylemanifest.xml

### ISSUE THREAD

**Issue by Freazeorburn** [MicrosoftDocs/OfficeDocs-Exchange#390]
After creating a custom theme it needs to be added to stylemanifest.xml (located at: %ExchangeInstallPath%ClientAccess\OWA\prem\<ExchangeVersion>\manifest) for theme to be chosen from the menu by the user. I'm using Server 2016 (1607) and Exchange 2016 (15.1.1531.3).

**Comment by chrisda** [comment]
@Freazeorburn, I added your suggestion to the topic. I don't remember needing to modify that file to see the new theme in the list when I wrote the topic, but I may have been too focused on forcing the new theme as the default theme.

Thanks for the feedback.
