### ISSUE TITLE
Are mailbox import requests journaled?

### ISSUE THREAD

**Issue by TimHL** [MicrosoftDocs/OfficeDocs-Exchange#391]
I don't see in the documentation for journaling or new-MailboxImportRequest whether imported emails are written to Journal mailboxes.  I read that Imports use advanced queue throttling, and I know journaling is tied to the transport queues, so I suspect it might, but I'd like to have this confirmed.

As we migrate users into Exchange, we'd like their email to be added to the journal as well.

**Comment by chrisda** [comment]
@TimHL, My gut reaction is no. Even though queues might be involved, migrated messages aren't "sent" (don't flow through the categorizer and the transport pipeline) like regular email messages.

If you've got everything setup to do the PST igestion, you could try a single mailbox to see what happens, report back here, and I'll update the Journaling topic(s).

I'm trying to get absolute confirmation.

**Comment by scanum** [comment]
@chrisda any updates on this issue? Thanks!!

**Comment by chrisda** [comment]
Closing
