### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nizzol4shizzol** [MicrosoftDocs/OfficeDocs-Exchange#393]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9108de4-e74c-0d0f-a380-0a9a8a2f0b22
* Version Independent ID: 51dc0b18-03e3-e9e2-d427-e559e56e10a1
* Content: [Troubleshoot Office 365 mail flow](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/troubleshoot-mail-flow)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/troubleshoot-mail-flow.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/troubleshoot-mail-flow.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@nizzol4shizzol, if there's something wrong with the topic, we can help. If you're have a service issue or a technical problem, you should open a support case.
