### ISSUE TITLE
how long will the "Day" change take?

### ISSUE THREAD

**Issue by Thomas-Titan** [MicrosoftDocs/OfficeDocs-Exchange#394]
In this article you are changing the Exchange default 14 day deletion to 30 days. I am running your commands and they seem to be completing successfully except I get this warning message when I run this command

 “Get-Mailbox -ResultSize unlimited -Filter {(RecipientTypeDetails -eq 'UserMailbox')} | Set-Mailbox -RetainDeletedItemsFor 10”

WARNING: The command completed successfully but no settings of 'titan.local/MyBusiness/Users/SBSUsers/Tom Phillips'
have been modified.

I am trying to reduce the “day” to deletion to 10 days (or less if I can). We are planning to migrate our Exchange to a new server and I’m asking users to slim down there current Inbox so this migration time is minimized.

Why do I get the “Warning”?

I'm working with a SMB server 2011 with exchange 2010

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a43744-eddc-762f-d3c7-6f8732141ad7
* Version Independent ID: c20377ab-03ae-62ed-96bd-04a9bc653286
* Content: [Change how long permanently deleted items are kept for an Exchange Online mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/change-deleted-item-retention.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @serdars
* Microsoft Alias: **serdars**

**Comment by chrisda** [comment]
@Thomas-Titan, what happens when you run this command?

```
Get-Mailbox "Tom Phillips" | FL RetainDeletedItemsFor
```

The error could mean he already had the value 10 days. So you ran the command on all user mailboxes in the organization and you only got this one error for this one user? I would take that to mean everyone else's mailbox was modified except Tom's.

**Comment by Thomas-Titan** [comment]
Thanks for your response. I think I have this solved, I'll have to wait and see. I was able to change a number in the Exchange Management Console - Microsoft Exchange On-Premises - Organization Configuration - Mailbox, then right clicking on the our Mailbox Database. The Properties dialog box has a Limit tab with "Deletion Settings". I have reduce the number to what I'm wanting (default is 30). I then ran this command - "Get-Mailbox tom | Format-List RetainDeletedItemsFor" in the shell and got the number of days I am wanting. If I am doing this wrong please let me know.

**Comment by markjjo** [comment]
@Thomas-Titan You should be good to go.
