### ISSUE TITLE
Enable IMAP for Gmail accounts

### ISSUE THREAD

**Issue by IshaKhaira** [MicrosoftDocs/OfficeDocs-Exchange#400]
Please add the section below to make sure IMAP is enabled before migration is initiated. Failure to enable IMAP will result in migration issues. 

Enable Gmail or G Suite Accounts for IMAP:

Sign in to your Gmail account by using a browser that is supported 
Choose or click the gear icon on the top right.
Choose Settings &gt; Forwarding and POP/IMAP.
Select Enable IMAP, and then choose Save Changes.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62f5860-4f99-6794-f8d6-2207b7f19979
* Version Independent ID: c28b87f8-1984-6522-021f-bae92e46d08c
* Content: [Prepare your Gmail or G Suite account for connecting to Outlook and Office 365](https://docs.microsoft.com/en-ca/exchange/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by khorne3** [comment]
@AndreaBarr I'll take this one
