### ISSUE TITLE
Full Access permissions still not supported in OWA?

### ISSUE THREAD

**Issue by chk1982** [MicrosoftDocs/OfficeDocs-Exchange#404]
According to this Ignite video from 2017 OWA Full Access permissions are supported. Paragraph 5 in this document says they are not. Does this document need to be updated?

Start at 34:00

https://www.youtube.com/watch?v=pN6lsxKRrJQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1959e5-a0c2-3431-4fe4-3e4e7843a594
* Version Independent ID: 33dd3686-3b92-0393-837b-dfd76152151f
* Content: [Permissions in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/permissions#mailbox-permissions-supported-in-hybrid-environments)
* Content Source: [Exchange/ExchangeHybrid/permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws306** [comment]
Hi @chrisda , I think we can close it. Thanks.
