### ISSUE TITLE
cmdlet wrong

### ISSUE THREAD

**Issue by jxnx888** [MicrosoftDocs/OfficeDocs-Exchange#406]
Under "Use Exchange Online PowerShell to view or modify a journal rule"
The cmdlets miss ""  , it should be

 Set-JournalRule "JR-Sales" -Name "TraderVault" -Recipient traders@woodgrovebank.com -JournalEmailAddress tradervault@woodgrovebank.com -Scope Internal
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d49df7f-4717-d51e-b1b9-5a5a4768a1d9
* Version Independent ID: af6d6557-eb97-6aba-4511-c64e951ab31f
* Content: [Manage journaling](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/manage-journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/manage-journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by chrisda** [comment]
@jxnx888, I fixed it.

Thanks for the feedback.
