### ISSUE TITLE
Error in page

### ISSUE THREAD

**Issue by deanmresource** [MicrosoftDocs/OfficeDocs-Exchange#407]
"As a result, users can't log into it them directly. "
either delete IT or THEM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb78b621-ad88-04ad-c449-4d8c7e1b2d24
* Version Independent ID: 7259a9a9-4589-194e-5b9b-b32a807788d4
* Content: [Shared mailboxes](https://docs.microsoft.com/en-us/exchange/collaboration/shared-mailboxes/shared-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/collaboration/shared-mailboxes/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/shared-mailboxes/shared-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by get-itips** [comment]
Hi Dean, thanks for your contribution, I will handle this issue. @AndreaBarr

**Comment by chrisda** [comment]
Issue resolved in PR #409
