### ISSUE TITLE
Mention failing certifications

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/OfficeDocs-Exchange#410]
As credentials are transmitted to outlook services, it should be mentioned, that this could result in failing important certifications like PCI (Payment-card-industry) or ISO/IEC 27001.
And especially this part `the service can then connect to the Exchange server to synchronize mail, calendar, and other mailbox data` can also be a problem in conjunction with GDPR, as private information (inside of emails/calendar items/...) is most likely at some point in time included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221571c5-0fc2-8087-2766-c34352167570
* Version Independent ID: 6c91bfa7-ea52-9afe-9a6f-c54fb038082c
* Content: [Passwords and security in Outlook for iOS and Android for Exchange Server](https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/passwords-and-security?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/passwords-and-security.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/passwords-and-security.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by khorne3** [comment]
@AndreaBarr I can look into this.
