### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by lemazzag** [MicrosoftDocs/OfficeDocs-Exchange#411]
On last sentence:
To learn more about hosted management solutions, including validated solution vendors, see Exchange Server 2013 hosting and multi-tenancy solutions and guidance, the link must point to https://www.microsoft.com/en-us/download/details.aspx?id=36790

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecb54697-3aaa-c41c-ff6e-d9e458ac892e
* Version Independent ID: 9bc9bad8-b51f-27c4-627b-8a0c959012af
* Content: [Multi-tenancy in Exchange 2013: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/multi-tenancy-in-exchange-2013-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/multi-tenancy-in-exchange-2013-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/multi-tenancy-in-exchange-2013-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by get-itips** [comment]
Hi lemazzag thanks for your feedback, I will take care of it. @AndreaBarr

**Comment by chrisda** [comment]
Fix

**Comment by chrisda** [comment]
Fixed in PR #412
