### ISSUE TITLE
Groups Location

### ISSUE THREAD

**Issue by dariomws306** [MicrosoftDocs/OfficeDocs-Exchange#415]
I think this article could have a note to specify where these groups are created. I understand they are created on "Microsoft Exchange Security Groups" container in the forest root domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24f6b31-75be-86bd-f2cd-23904838318e
* Version Independent ID: b60d6e4b-c64a-94f8-1fe2-6ca5a2a7c41a
* Content: [Understanding management role groups: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/understanding-management-role-groups-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/understanding-management-role-groups-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/understanding-management-role-groups-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by nenonix** [comment]
@dariomws306 Thank you for your feedback. I will work with you to clarify the content. Can you give me some more detail about where this note should appear?

**Comment by dariomws306** [comment]
Hi @nenonix , I have done it. You can check it on the step 1:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/understanding-management-role-groups-exchange-2013-help.md#role-group-creation-workflow

It was merged into the public but I don't know why it doesn't appear here:
https://docs.microsoft.com/en-us/exchange/understanding-management-role-groups-exchange-2013-help#role-group-creation-workflow

**Comment by nenonix** [comment]
@dariomws306 Great, thank you!
