### ISSUE TITLE
Use the Exchange Management Shell to configure the action for sender filtering for blocked senders from SafeList aggregation

### ISSUE THREAD

**Issue by TricompPoland** [MicrosoftDocs/OfficeDocs-Exchange#42]
I think there is a mistake in the command below (after the explanation):
-----------------------------
This example configures the Sender Filter agent to reject messages that contain blocked senders that are defined by SafeList aggregation with a non-delivery report (also known as an NDR, delivery status notification, DSN or bounce message).

Set-SenderFilterConfig -Action Reject
-----------------------------
The correct command should be:
Set-SenderFilterConfig -RecipientBlockedSenderAction Reject

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662bcb7d-16c9-5f4e-cadc-27c1c4874de3
* Version Independent ID: e070603b-37f4-0dee-a38c-3f4fea9f880b
* Content: [Sender filtering procedures](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antispam-protection/sender-filtering-procedures)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/sender-filtering-procedures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/sender-filtering-procedures.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@TricompPoland you are correct. I fixed it.

Thanks for the feedback.
