### ISSUE TITLE
IMAP flow

### ISSUE THREAD

**Issue by hmoffatt** [MicrosoftDocs/OfficeDocs-Exchange#429]
It appears that Outlook for Android is currently doing IMAP via the protocol translator also. (In my IMAP server logs I see Outlook users’ connections come from a Microsoft host.) How will this be affected by the change to the sync protocol? Will the clients ever implement native IMAP? It appears that an Australian user accessing an Australian server is going through an offshore intermediary which is not very efficient.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca9af29f-c472-ebfd-e166-66a7d2b8bf0c
* Version Independent ID: 958cc7b8-3330-52a0-26fd-5717cba1df2f
* Content: [Outlook for iOS and Android in Exchange Online](https://docs.microsoft.com/en-au/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@hmoffatt  Thanks for the feedback. I checked with the product group. Outlook for iOS and Android (Outlook mobile) has always been a cloud-backed application. Processing information in our service fabric enables advanced features and capabilities, such as the categorization of email for the Focused Inbox, improved search speed, artificial intelligence scenarios, and more. It enhances Outlook’s performance and stability, relying on the Outlook service for intensive processing and minimizing the resources required from users' devices. Lastly, it allows Outlook to build features that work across all email accounts, regardless of the technological capabilities of the underlying messaging platforms (e.g. different versions of Exchange, 3rd party email systems like Yahoo! Mail and Gmail, etc.).

The new native Microsoft sync technology is only for Exchange accounts. 

IMAP accounts connect to an architecture similar to what is described in https://docs.microsoft.com/en-us/Exchange/clients/outlook-for-ios-and-android/use-basic-auth?view=exchserver-2019.
