### ISSUE TITLE
HABs in OWA

### ISSUE THREAD

**Issue by SquanJRP** [MicrosoftDocs/OfficeDocs-Exchange#433]
Do HABs only work in Outlook client or are they available in OWA also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1c6ced-4d52-df69-b492-8a6a47e793ec
* Version Independent ID: acb719f5-1828-d101-bf8f-af6f7fc03758
* Content: [Hierarchical address books in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/hierarchical-address-books/hierarchical-address-books)
* Content Source: [Exchange/ExchangeOnline/address-books/hierarchical-address-books/hierarchical-address-books.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/hierarchical-address-books/hierarchical-address-books.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@SquanJRP, it appears that HABs are still only available in the Outlook client; they aren't available in OWA (now known as Outlook on the web).
