### ISSUE TITLE
Admin Role for Manage Mailbox Permissions

### ISSUE THREAD

**Issue by hsbsandrecv** [MicrosoftDocs/OfficeDocs-Exchange#434]
Which Admin Role is necessary for Manage Mailbox Permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe24386f-86cc-5073-dc17-ad8ece0e3dc7
* Version Independent ID: 88a529c7-c6e6-8438-8eb4-c6fc2a20f722
* Content: [Manage permissions for recipients](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-permissions-for-recipients)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-permissions-for-recipients.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by chrisda** [comment]
@hsbsandrecv the required permissions break down as follows:

- **Assign Full Access permissions**: You need to be assigned the Mail Recipients role, which you typically get from membership in the Organization Management or Recipient Management role groups.

- **Assign Send As permssions**: You need to be assigned the Mail Recipients role, which you typically get from membership in the Organization Management or Recipient Management role groups.

- **Assign Send on Behalf permissions**: You need be assigned different roles depending on the recipient type: Distribution Groups and/or Mail Recipients, both of which you typically get from from membership in the Organization Management or Recipient Management role groups.

I did a bunch of updates to the topic, and the topic now lists the correct place to go to see the permissions you need (membership in the Organization Management or Recipient Management role groups).
