### ISSUE TITLE
Process Optimization

### ISSUE THREAD

**Issue by matthieumartineau** [MicrosoftDocs/OfficeDocs-Exchange#436]
Why don't you talk about the Move-TransportDatabase.ps1 PS script located inside the "Scripts" folder of Exchange Installation Path?

This script can automate the whole process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66db97d2-8963-10ff-f478-c3796d9efb51
* Version Independent ID: 7cecf49d-39fc-c9ea-c7b4-ec0d4239b1e2
* Content: [Change the location of the queue database](https://docs.microsoft.com/en-us/exchange/mail-flow/queues/relocate-queue-database?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/mail-flow/queues/relocate-queue-database.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/queues/relocate-queue-database.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dariomws306** [comment]
Hi @chrisda , do you need help with this? Thanks.

**Comment by chrisda** [comment]
@dariomws306, by all means, feel free work on this (and assign it to yourself). Thanks!

**Comment by chrisda** [comment]
@matthieumartineau topic was update per PR #521. Closing
