### ISSUE TITLE
Scenario 1 is incomplete

### ISSUE THREAD

**Issue by ge33ek** [MicrosoftDocs/OfficeDocs-Exchange#437]
Scenario 1 provides no meaningful description or context as to how to configure O365 for this scenario. 

If the primary MX server is different, how does one configure O365 to access e-mails addressed to the domain when it is not the authority? Currently the SMTP or EOP service rejects e-mails because it is not the primary MX. 

Some meaningful descriptions of how to configure this are required.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Exchange Online](https://docs.microsoft.com/en-au/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by nenonix** [comment]
@ge33ek Thank you for your contribution.  I am going to research this issue and work with you on improving the content.

**Comment by dariomws306** [comment]
Hi @ge33ek , thank you for your feedback. I am adding the article "Set up connectors for secure mail flow with a partner organization" in the "See also" section. There you can see more information about how to configure O365 connector for this scenario.

Also I have to suggest that you check your Hosted Email Security provider documentation, they have different recommendations. For example:
https://esupport.trendmicro.com/media/13940262/Integration_Guide_HESandO365_Aug%202018.pdf
https://campus.barracuda.com/product/emailsecuritygateway/doc/39822576/how-to-configure-office-365-for-inbound-and-outbound-mail/
