### ISSUE TITLE
No documentation around configuring / setting up MCDB as mentioned in the Preferred Architecture

### ISSUE THREAD

**Issue by m49808** [MicrosoftDocs/OfficeDocs-Exchange#439]
The 2019 Preferred Architecture has many references to its new SSD storage tiering and storing the Metacache Database (MCDB) on the SSDs. Great. But i cant find any documentation on how to configure it? Am i missing something? Is this feature available yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ca43756-5b4d-0e29-9d15-a27b2c51a487
* Version Independent ID: de049b98-08d3-7358-3fb9-35957b30bc3e
* Content: [Exchange 2019 preferred architecture](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deployment-ref/preferred-architecture-2019?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deployment-ref/preferred-architecture-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deployment-ref/preferred-architecture-2019.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@m49808, MCDB is available in Exchange 2019 RTM. The MCDB content is being worked on as we speak (W 1/2). No ETA yet for delivery, but it is coming.

**Comment by Artnabaz** [comment]
i was about to ask for an update but then i found this :
https://docs.microsoft.com/en-us/exchange/high-availability/database-availability-groups/metacachedatabase-setup?view=exchserver-2019
Maybe a link could be introduced in the PA ?
