### ISSUE TITLE
Szenario 1 is not complete

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-Exchange#44]
SCenario 1 describes incoming mails via a 3rd Party Spamfilter but it misses the required configuration in Office 365 to bypass the O365 Spamfilter at all. I assume i need a Inbound Connector and now word how to prevent bad guys still ignoring the MX-record and sending to Office 365, bypassing my 3rd PArty AV/AntiSpam/Journaling solution.
And Scenario 1 assumes, that outbound messages are delivered direct. This is alos not a common case. The customers want to rout outgoing messages via the same 3rd Party solution to "learn" about message conversations etc. I can do that with a ountbound connector in combination with a transport rule.
I'ld like to have a more detailed desriptions about how to configure my tenant to run a "supported" Scenario.

Frank @carius.de

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud#Scenario1)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @tirich
* Microsoft Alias: **tirich**

**Comment by kenwith** [comment]
@FrankCarius - Thank you for taking the time to provide this feedback. It is much appreciated.

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
