### ISSUE TITLE
Holds and mailbox quotas

### ISSUE THREAD

**Issue by rtxcupid** [MicrosoftDocs/OfficeDocs-Exchange#446]
In Exchange Online, the default limits for the Recoverable Items quota are the same as Exchange Server: a soft limit of 20 GB and a hard limit of 30 GB. However, the quotas for the Recoverable Items folder are automatically increased to 90 GB and 100 GB, respectively, when you place a mailbox on Litigation Hold or In-Place Hold. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0957d8b7-cb89-0aa7-f8ac-329aa3c2b085
* Version Independent ID: 21e5f86c-104d-bdec-8092-c2efc7e0574c
* Content: [In-Place Hold and Litigation Hold in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/holds/holds?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/holds/holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/holds/holds.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by rtxcupid** [comment]
@nenonix Sorry for the confusion. I was referring to the section called Holds and Mailbox quotas and the information within that section. In that section it does not explain that the quotas will automatically increase if an in-place hold is applied to a mailbox. 
My initial statement was copied from the recoverable items documentation explaining that. This information should be noted in the quotas section since it would apply if the hold was enabled.

**Comment by nenonix** [comment]
@rtxcupid  Thanks for the clarity. I apologise for the delay in responding. I will try to reflect this in the content asap.

**Comment by tseward** [comment]
@rtxcupid I placed a single mailbox on hold and I'm not seeing the values for `RecoverableItemsWarningQuota` or `RecoverableItemsQuota` changing from 20GB and 30GB, respectively. This is on Exchange 2019 RTM.

Can you outline the process you took (preferably PowerShell) to see the quota automatically increase?
