### ISSUE TITLE
Tenant to Tenant migration using migration option in EAC

### ISSUE THREAD

**Issue by Elangamban** [MicrosoftDocs/OfficeDocs-Exchange#449]
In the article, the title is referring to "Scenario: Migrate using a third party migration tool", How about the Scenario using the inbuilt migration tool in Office 365 EAC. Will the same CSV file work in that scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Office 365 tenant to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by dariomws306** [comment]
Hi @Elangamban , thanks for your feedback. It's not possible to use Office 365 EAC for cross tenant migration. You have to use a third party tool, now it's the only way.

(there are some rumors that Microsoft is working on it)
