### ISSUE TITLE
Update documentation for Exchange Server 2019

### ISSUE THREAD

**Issue by MaximeRastello** [MicrosoftDocs/OfficeDocs-Exchange#450]
Hello,
Could you please update this doc to reflect the publication of Exchange Server 2019 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by nenonix** [comment]
@MaximeRastello Thank you for contributing to making MS documents better and more accurate, As a member of the writing team I will research this issue further and post back here when the missing information is reflected in the document.

**Comment by brolifen** [comment]
Not only that can it also include whether or not HCW can run on an Exchange 2019 installed on Windows Server Core.

**Comment by scanum** [comment]
@MaximeRastello Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
