### ISSUE TITLE
Article needs updated for Windows 10

### ISSUE THREAD

**Issue by smiller329** [MicrosoftDocs/OfficeDocs-Exchange#454]
The date on the article is 12/21/2018, I expected to find information regarding Windows 10, with links to "Previous versions of Windows 8,7, etc"  Instead it shows that I have to "swipe right", which is obviously a Windows 8 option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497b0b89-0e74-8e62-296f-0093bfdd84f8
* Version Independent ID: d1c880e6-a3ea-8a24-6a73-6c037f36c55f
* Content: [Fix Outlook connection problems in Office 365 and Exchange Online](https://docs.microsoft.com/en-us/Exchange/fix-outlook-connection-problems-in-office-365/fix-outlook-connection-problems-in-office-365?redirectSourcePath=%252farticle%252fb3e740b9-171d-4179-bcd1-e279a363fa75)
* Content Source: [Exchange/ExchangeOnline/fix-outlook-connection-problems-in-office-365/fix-outlook-connection-problems-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/fix-outlook-connection-problems-in-office-365/fix-outlook-connection-problems-in-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @scotvidican
* Microsoft Alias: **scotv**

**Comment by nenonix** [comment]
@smiller329  Thank you for your helpful feedback. I am going to ask @dariomws306  to look into this. While we research the issue, do you have any specific edits to suggest?
