### ISSUE TITLE
completed migration batch

### ISSUE THREAD

**Issue by XixiHuang333** [MicrosoftDocs/OfficeDocs-Exchange#459]
Hi Team,
Customer has a list of completed migration batch. Those batches were done a few of month ago and the kept staying there. Suddenly some of completed batches were cleaned up by system. This make customer very confused as customer may want to keep the information for migration project. As confirmed, it is part of Migration Service inactive job cleanup. When Migration Service cleanup starts, the job that is inactive for more than 60 days will be cleaned up. Could you please update the document to clarify this scenario on document for customers who may encounter this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a684ff-29af-b532-deea-01fecbd6b8cb
* Version Independent ID: a90ceb5c-8553-2636-ab85-14688435ee4d
* Content: [Manage migration batches in Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/manage-migration-batches)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/manage-migration-batches.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/manage-migration-batches.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@XixiHuang333 Thanks for pointing this out. The article has been updated to be more clear about expiration of batches, depending on their status. You should see changes within a day.

**Comment by XixiHuang333** [comment]
Thanks for your update!

Regards,
Xixi Huang
