### ISSUE TITLE
Public folders in Outlook on the web don't load calendar items

### ISSUE THREAD

**Issue by adamzea** [MicrosoftDocs/OfficeDocs-Exchange#46]
The "Add favorite public folders in Outlook on the web" doesn't seem to work for public folder calendars.  The public calendar does show up in the "other calendars" section, but none of the calendar items that exist in that public folder will load in Outlook Web Access.  This is on Office 365 Business Essentials accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1322ea00-e4ee-5858-c224-c8b886f6a7d0
* Version Independent ID: 059da329-0f7f-cd54-31d7-cdec5eda9141
* Content: [Use favorite public folders in Outlook on the web](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/use-favorite-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/use-favorite-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by kenwith** [comment]
@adamzea - thank you for submitting feedback. 

This is good information and I want to make sure the feature is working correctly in your environment. This is great information about Business Essentials accounts.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
