### ISSUE TITLE
Update with Windows Server 2019

### ISSUE THREAD

**Issue by bencorley** [MicrosoftDocs/OfficeDocs-Exchange#460]
Please update the article and add Windows Server 2019, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcdf59c9-1922-ecf5-fc36-caafb16423ff
* Version Independent ID: 62557ef7-d03e-50b9-00f7-ffdc244e1fc7
* Content: [Exchange Server Supportability Matrix: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/exchange-server-supportability-matrix-exchange-2013-help#supported-active-directory-environments)
* Content Source: [Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/exchange-server-supportability-matrix-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by dariomws306** [comment]
Hi @bencorley , thank you for your contribution, I will research this issue further and post back here when the missing information is reflected in the document.

**Comment by chrisda** [comment]
@bencorley, we are working on a updated version of the topic that will live in the 2016/2019 content, and this version that lives in 2013 content will be retired and redirected to the new version.

I'll leave this issue open and close/comment when the switch is complete.

Thanks for the feedback.

**Comment by dariomws306** [comment]
Hi @chrisda , so it does not make sense to update this article, right? Thanks.

**Comment by chrisda** [comment]
@dariomws306, correct; don't bother updating the existing topic in the 2013 node.

**Comment by chrisda** [comment]
@bencorley, @dariomws306 the topic has been moved, redirected and updated in the Exchange 2016/2019 area. Feel free to make any further corrections there.
