### ISSUE TITLE
Article not complete

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-Exchange#461]
This article should mention that it is not supported to run Hybrid Deployment with 3rd party servers between on-premise and Office 365. We still have customers doing this which breaks hybrid functionality like Anti-Spam cross premise, Auto-accept agent, Moderation of mail, Internal OOF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 884ccdaf-c60f-293a-b7f7-b4edc559546c
* Version Independent ID: 6265a100-939a-75b3-d2ae-86798aaf79b4
* Content: [Manage mail flow using a third-party cloud service with Exchange Online and on-premises mailboxes](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-on-office-365-and-on-prem.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TokyoScarab** [comment]
Hello!  Thank you for pointing this out.  We will update the page to better clarify the issue.

**Comment by scanum** [comment]
A PR has been created #555
