### ISSUE TITLE
Exchange admin center missing options

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-Exchange#464]
The "Configure deleted item retention for a mailbox" section describes an area of the exchange admin center that is not available in our tenant. Looks like powershell is the only way to check this now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba50998c-7b9a-bc1f-81af-05ade620793c
* Version Independent ID: 46a00993-86e7-4d06-bff4-bc16b1df2c96
* Content: [Configure Deleted Item retention and Recoverable Items quotas](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/user-mailboxes/deleted-item-retention-and-recoverable-items-quotas.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TokyoScarab** [comment]
Hello!  Would you be able to clarify that the version of Exchange that you're using matches the version of Exchange that is being used in the page that you are referencing?  Please get back to me when you can so that we can fully address your issue.  Thanks!

**Comment by chrisda** [comment]
@jonwbstr, you used the word "tenant" which I interpret to mean you're using Exchange Online. The topic you referenced is an Exchange Server 2016/2019 topic in the Exchange Server 2016/2019 area of docs.microsoft.com. That would explain why your EAC UI is different. Were you linked to this on-premises topic from a link an Exchange Online topic?
