### ISSUE TITLE
Expand Acronyms

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-Exchange#465]
Please correctly expand all acronyms when they are first used on every page.

Examples

SHCW 
RPS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent – Preview](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by lusassl-msft** [comment]
Done. See pull #469 (https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/469)

**Comment by TokyoScarab** [comment]
There were a few missed. See pull [#545](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/545)
