### ISSUE TITLE
Windows 2019 AD Forest Functional Level ?

### ISSUE THREAD

**Issue by sime3000** [MicrosoftDocs/OfficeDocs-Exchange#466]
Why is a Windows 2019 AD forest functional level listed in the chart above when that FFL does not exist?

Or are you announcing something here ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by technion** [comment]
Just came across the same thing. It appears contradictory to support a Windows 2019 AD functional level with Exchange 2016 when Windows 2019 Active Directory servers are not supported with Exchange 2016.

**Comment by chrisda** [comment]
@sime3000, @technion, it was a copy/paste error. I removed it from the topic.

Thanks for the feedback.
