### ISSUE TITLE
Direct Send and TLS

### ISSUE THREAD

**Issue by jveynde** [MicrosoftDocs/OfficeDocs-Exchange#470]
In the compare table and features of Direct send (option 2) TLS is optional.
However in the settings it is configured as Enabled.

Does the change that since October 31st 2018 Office 365 will only allow TLS 1.2 impact this option ?
(As for the SMTP connections?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TokyoScarab** [comment]
Yes, the October 31st, 2018 update reflects a big change in how TLS compatibility will be in Office 365 going forward.  You can read a full, detailed description of this change [here](https://support.microsoft.com/en-us/help/4057306/preparing-for-tls-1-2-in-office-365).  I hope this answers your question.  Thanks!

**Comment by dyerseve** [comment]
Not sure why this was closed when the information in the compare table is still incorrect versus the information above, can someone edit the document to reflect that all 3 options require TLS 1.2?

**Comment by chrisda** [comment]
@dyerseve, I updated the table. Thanks for the feedback.

**Comment by acbrownit** [comment]
Direct Send certainly doesn't require TLS to work unless Exchange Online has started requiring TLS when receiving messages over SMTP. The direct send method uses Opportunistic TLS, just like it is receiving from every other server on the Internet. With opp. TLS, if the sending server doesn't issue the STARTTLS verb, the SMTP session will continue unencrypted. This is a basic standard across every email server on the Internet at this point, and O365 would be causing their clients to reject numerous emails sent by improperly configured or out of date mail servers if they didn't allow unencrypted messages send to the EOP endpoint (Which is what direct send does). 

The linked article regarding TLS 1.2 in October 2018 does not impact that fact. The change there is that opp. TLS will start requiring TLS 1.2 connectivity to work. Servers that send to Exchange Online that don't support TLS 1.2 will revert to unencrypted mode. The article preceding the graph at the bottom states in a few places that TLS is not required for direct send. This is beyond confusing for people and needs to be definitively resolved.
