### ISSUE TITLE
Shared Mailbox Doesn't Send Deleted "Sent Items" to "Deleted Items" folder

### ISSUE THREAD

**Issue by donnaTN** [MicrosoftDocs/OfficeDocs-Exchange#474]
The above command will send a copy of the email sent from the shared account into the "Sent Items" folder for the shared account.  The problem lies in that if that email is deleted it does not go to the "Deleted Items" folder.  I can see the owners of the shared account accidentally deleting these emails with no way to recover them.  Is there a script for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d3a998a-6ea1-b3b2-76d2-4de65962bbda
* Version Independent ID: 2911c776-0c9a-06f3-a4ab-99713ed87b76
* Content: [Automatically save sent items in delegator's mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/automatically-save-sent-items-in-delegator-s-mailbox)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/automatically-save-sent-items-in-delegator-s-mailbox.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/automatically-save-sent-items-in-delegator-s-mailbox.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by TokyoScarab** [comment]
Here is a link that should be exactly what you are looking for.  If, for some reason you are still having trouble, please post a comment and we will get back to you.  Thanks!
https://support.microsoft.com/en-us/help/202517/items-that-are-deleted-from-a-shared-mailbox-go-to-the-wrong-folder-in

**Comment by PeteMX** [comment]
When I send a meeting send on behalf a shared mailbox, the meeting invitiaion is not in the sent items folder of the shared mailbox. Is this by design?
