### ISSUE TITLE
Individual calendar management

### ISSUE THREAD

**Issue by SCS-sysadmin** [MicrosoftDocs/OfficeDocs-Exchange#478]
For the note section in purple: did this change? When I look at my Outlook there's no longer a "Default" permission. The article below looks more like mine: "My Organization" instead of Default.

https://support.office.com/en-us/article/share-an-outlook-calendar-with-other-people-353ed2c1-3ec5-449d-8c73-6931a0adab88

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c02125f4-2bb2-0631-93e2-93ccce4f1cb5
* Version Independent ID: 03192cfe-7d7e-82ec-d048-b4ac7d08d9df
* Content: [Organization relationships in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/organization-relationships)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/organization-relationships.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by khorne3** [comment]
@SCS-sysadmin Thanks, I'll update doc from 2014 w/ newer instructions.
