### ISSUE TITLE
Outlook Licensing for Business Essentials

### ISSUE THREAD

**Issue by ajwreinhardt** [MicrosoftDocs/OfficeDocs-Exchange#48]
Should the question regarding licensing be updated because now Business Essentials and E1 include access to the mobile apps on phones and tablets smaller than 10.1"? This is a major boon to BE users in that now any Exchange Online user who has BE can legally use the Outlook app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook for iOS and Android in Exchange Online FAQ](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by kenwith** [comment]
@ajwreinhardt - Thank you for submitting this feedback.

It is a very good catch regarding the plans and I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by SerdarSoysal** [comment]
The corresponding question in the topic was updated. It now reads: 
"Commercial users with the following subscriptions are allowed to use the Outlook mobile app on devices with integrated screens 10.1" diagonally or less: **Office 365 Enterprise E1**, Office 365 F1, **Office 365 Business Essentials**, Office 365 A1, and if you only have an Exchange Online license (without Office). "
