### ISSUE TITLE
Link the "Managing mailbox database copies" seems to be pointing to an invalid linke

### ISSUE THREAD

**Issue by ravensorb** [MicrosoftDocs/OfficeDocs-Exchange#480]
Right now it is pointing to 
http://technet.microsoft.com/library/06df16b4-f209-4d3a-8c68-0805c745f9b2.aspx

looks like it should be pointing to
https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/manage-database-copies?view=exchserver-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e46eb1c-9e59-6978-f324-16229faead5e
* Version Independent ID: f2e64be2-fd47-6973-cca5-e641075b75d4
* Content: [Mailbox database copies](https://docs.microsoft.com/en-us/exchange/high-availability/database-availability-groups/database-copies?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/high-availability/database-availability-groups/database-copies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/database-availability-groups/database-copies.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
Hi @ravensorb.  Thank you for your valuable contribution and suggestion in trying to improve MS docs.  I will investigate and update the link.
