### ISSUE TITLE
Code correct?

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#481]
Command 1 = Get-AdUser &lt;Identity&gt; | Set-AdObject -Replace @{msExchRecipientDisplayType=-1073741818}  .... this shows as a local on-prem command .... 
Command 2 = Get-RemoteMailbox .... this shows as a remote

Both have the same value for displaytype .... so your saying we should make this value the same for All on-prem and All O365?

So we should be running Get-AdUser -filter * | Set-AdObject -Replace @{msExchRecipientDisplayType=-1073741818} ?????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dariomws306** [comment]
Hi @SquirrelAssassin , thanks for your feedback.

You should run these onpremises ("Open the Exchange Management Shell on an Exchange 2013 or Exchange 2016 server running the latest available CU, or the immediately previous CU.").

First command apply to one user ("To enable ACLs on a single mailbox").

Second to all users ("To enable ACLs on all mailboxes moved to Office 365").
