### ISSUE TITLE
Not a issue - Question about limiting IMAP traffic when importing from Google Apps Mail

### ISSUE THREAD

**Issue by useridtaken** [MicrosoftDocs/OfficeDocs-Exchange#483]
Hey everyone!

**Is possible to limit IMAP traffic in Exchange 365 when is synchronizing with gmail IMAP ?**
What I need is avoid reach to Gmail IMAP daily limit of 2500 MegaByte. I've got several account which more than 8 gigs of email.

According to gmail documentation, once an account reach IMAP limit, Google system suspends automatically that account for 24 hours. Administrator can reactivate it anytime, but, if an account violates 5 times in a calendar year this limits, is locked by the system and none can reactivate it during the next 24 hours. If an account is suspended can not sent/receive message. 

I would like avoid this issue, so, it would be helpful to me that exchanges automatically stops at 2000 MegaBytes each day.

**Can I automatically do that?**

**Comment by MK-Kamal** [comment]
@useridtaken   Thank you for your valuable contribution . As Office365 don't have restrictions on data transfer Speed or limit the size in transferring data Per Day .  you can  use alternative method to migrate the users That Has the Large Mailbox  I had create PR to update article to include the alternative method   https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/557 . For more information about alternative method , see [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/office365/securitycompliance/use-network-upload-to-import-pst-files) and [Third-party tools for Office 365 migrations](https://docs.microsoft.com/exchange/mailbox-migration/office-365-migration-best-practices#third-party-tools-for-office-365-migrations).

@scanum @AndreaBarr
