### ISSUE TITLE
Hybrid Deployment/Schema Preparation

### ISSUE THREAD

**Issue by miketheitguy** [MicrosoftDocs/OfficeDocs-Exchange#488]
Hi! This document doesn't seem to take into account the situation/instructions provided here:

https://support.microsoft.com/en-us/help/3121439/error-when-you-run-setup-prepareschema-to-prepare-the-schema-for-an-ex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f347a03-e2c5-5ae2-e409-ddb6d544ccfd
* Version Independent ID: 839ff415-2b55-e312-3121-0fd2d9ca5a88
* Content: [Prepare Active Directory and domains for Exchange Server, Active Directory Exchange Server, Exchange Server Active Directory, Exchange 2019 Active Directory](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prepare-ad-and-domains?view=exchserver-2019&viewFallbackFrom=exchange-ps)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by miketheitguy** [comment]
Mostely, the doc is separated into Step 1 and Step 2. The error, however, will occur at Step 1 before Step 2 is reached, and Step 2 is the only place where the Tenant Org config is mentioned in the doc.

**Comment by TokyoScarab** [comment]
The support ticket you mention in your post refers to using PowerShell with Exchange in the setup.  The doc page you made this issue from has a note at the top of the page saying, 

    "The requested page is not available for Exchange PowerShell. You have been redirected to the newest product version this page is available for."

Even though this page says this information will apply to Exchange Server 2016 (as the support ticket is made for), this will not include any of the given PowerShell information of the ticket.  I hope this helps.
