### ISSUE TITLE
Text boxes

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/OfficeDocs-Exchange#489]
Some regular text shows up in script boxes.  It would be nice if that were to be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5fa52a5-478a-21ad-0b16-5a114aca76e2
* Version Independent ID: 59c84b80-c5eb-3da4-77ab-8ab99d0ad139
* Content: [Restore data using a recovery database](https://docs.microsoft.com/en-us/Exchange/high-availability/disaster-recovery/restore-data-using-recovery-dbs?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/high-availability/disaster-recovery/restore-data-using-recovery-dbs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/disaster-recovery/restore-data-using-recovery-dbs.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by nenonix** [comment]
@curspice  Thank You for pointing this out, Please check back once the changes are merged and let us know if that works for you.

**Comment by curspice** [comment]
Nicole,

 

Just trying to make things better!  It’s great that you guys have been so responsive!


Ed Crowley, MVP
