### ISSUE TITLE
Missing UR

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/OfficeDocs-Exchange#490]
Exchange 2010 SP3 UR25 is not listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf984bf-df1c-bcd5-6475-54b9ef24fe74
* Version Independent ID: 00547ab9-7b3b-f6b0-fa7f-429f5e2bea56
* Content: [Exchange Server build numbers and release dates](https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
Hi @curspice. Thank you for your valuable contribution in improving MS docs.  I will have the missing Exchange added as soon as possible.

**Comment by lindspea** [comment]
@curspice  Please could you let me know where you see UR 25?  Is it on Microsoft Update Catalog? I can't seem to find it.

**Comment by chrisda** [comment]
@lindspea, I saw mention of it in an MVP thread. It was released on 1/8: https://www.microsoft.com/en-us/download/details.aspx?id=57759.

**Comment by curspice** [comment]
Lindsay,

 

I was surprised as well.  It was just released.

 

https://support.microsoft.com/en-us/help/4468742/update-rollup-25-for-exchange-server-2010-service-pack-3

 

https://www.microsoft.com/en-us/download/details.aspx?id=57759

 

Ed Crowley (MVP)

**Comment by lindspea** [comment]
@curspice Excellent!  Thank you so much.  Working to have it added to the list now.
