### ISSUE TITLE
Rollout Best Practices

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#494]
Please add details on what the best practices are for installing a CU.  For example, how many servers can you run the on at once?  What install order?  Support for patched and unpatched servers in the same org?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d97c4a4-4693-0248-eb53-081673d56dd2
* Version Independent ID: 39f69140-d3f9-3243-c2d6-946082a13bed
* Content: [Upgrade Exchange to the latest Cumulative Update](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/install-cumulative-updates?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/install-cumulative-updates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/install-cumulative-updates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TokyoScarab** [comment]
@chrisda Do you know if there is an already established set of practices for this that may not be published?  I have pulled together some things online that users of the service tend to do, but nothing official from Microsoft.  Any incite on this would be helpful.

**Comment by chrisda** [comment]
@TokyoScarab, I know of nothing. If you have something, feel free to add.

**Comment by TokyoScarab** [comment]
Thanks @danmyhre for bringing this up!  We will be updating this page to add in some information that will be helpful to people looking to run CU on their servers.  I would also advice you to check out [this](https://practical365.com/exchange-server/faq-order-install-service-packs-update-rollups-cumulative-updates/) page which outlines many useful practices for rolling out updates and maintaining your Exchange servers.

**Comment by scanum** [comment]
A PR has been created #590
