### ISSUE TITLE
this page seems very outdated

### ISSUE THREAD

**Issue by ac10000** [MicrosoftDocs/OfficeDocs-Exchange#496]
this page seems very outdated
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b221cd8e-e6d1-e383-65a2-11f7241de966
* Version Independent ID: cf978d97-c1e6-f0b7-7407-4f70d2284d17
* Content: [OWA for Devices contact sync](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/owa-for-devices-contact-sync?redirectSourcePath=%252fen-us%252farticle%252fLet-users-sync-email-contacts-with-their-iPhone-or-iPad-DE9CD26C-1A52-4FE1-B04C-B001693E20D6)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/owa-for-devices-contact-sync.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/owa-for-devices-contact-sync.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by TokyoScarab** [comment]
@msdmaguire Being one of the contributors to this article, I'd love your input on this so we can go about updating this page.  The page is from 2014 and there no doubt have been differences in the app since the writing of this article.

**Comment by msdmaguire** [comment]
@TokyoScarab Perhaps we can delete this article all together. There is no longer an OWA for iPhone/iPad app. It's all about Outlook mobile now.

**Comment by AndreaBarr** [comment]
@ac10000 Thank you for catching this. We have gotten this page taken down.
