### ISSUE TITLE
Does not work if any organisation has Primary and secondary hierarchy of Public folder.

### ISSUE THREAD

**Issue by Sumeetshinde18** [MicrosoftDocs/OfficeDocs-Exchange#497]
[https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-exchange-2013-public-folders#step-4-create-the-public-folder-mailboxes-in-exchange-online](url)

Above code throw error when Exchange on-premises has two Public folder Mailbox . I.e Primary and secondary Hierarchy. 

It basically mapped primary but in case of secondary mapping it throws error. Does any one has solution for it.

Below is dump : 
PS C:\Users\splus> $mappings = Import-Csv C:\PFScripts\map.csv
PS C:\Users\splus> $primaryMailboxName = ($mappings | Where-Object FolderPath -eq "\" ).TargetMailbox
PS C:\Users\splus> New-Mailbox -HoldForMigration:$true -PublicFolder -IsExcludedFromServingHierarchy:$false $primaryMailboxName ($mappings | Where-Object TargetMailbox -ne $primaryMailboxName).TargetMailbox | Sort-Object -unique | ForEach-O
bject { New-Mailbox -PublicFolder -IsExcludedFromServingHierarchy:$false $_ }
A positional parameter cannot be found that accepts argument 'Mailbox2'.
    + CategoryInfo          : InvalidArgument: (:) [New-Mailbox], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,New-Mailbox
    + PSComputerName        : ps.outlook.com

**Comment by scanum** [comment]
@Sumeetshinde18 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
