### ISSUE TITLE
Monitor effectiveness of the client access rule

### ISSUE THREAD

**Issue by sub2d** [MicrosoftDocs/OfficeDocs-Exchange#499]
I can create rule. Test condition to verify if it works. However, how can I historically audit to see, for example how many attempts have I blocked? In other words how can we validate effectiveness of a rule. There are no metrics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32e2775b-5234-4f90-ee01-304ce2545fd0
* Version Independent ID: 6292ef01-dd65-937c-74d9-5767f8107c83
* Content: [Procedures for Client Access Rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/client-access-rules/procedures-for-client-access-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/procedures-for-client-access-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/client-access-rules/procedures-for-client-access-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TokyoScarab** [comment]
There is documentation here on how to set up mailbox auditing [here](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mailbox-audit-logging/mailbox-audit-logging?view=exchserver-2019).  This will allow you to monitor any one who successfully accesses mailboxes you have it set up on.  From there, you can then see what kind of people are accessing each mailbox and then set up your rules to best shape the access you want for each box.  You can monitor the effectiveness of the rules by comparing current and previous audit logs and seeing if the rule has been effective or needs changing.
