### ISSUE TITLE
Should warn about port 25 being blocked

### ISSUE THREAD

**Issue by austinmccollum** [MicrosoftDocs/OfficeDocs-Exchange#503]
Great article on testing Exchange in Azure VMs, but a warning would be helpful about port 25 outgoing being blocked and without exception for certain subscriptions. https://docs.microsoft.com/en-us/azure/virtual-network/troubleshoot-outbound-smtp-connectivity 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45c04a0-138f-8241-0726-01fb09c3dfeb
* Version Independent ID: 730303a8-9c6f-472c-79f6-96453dea3013
* Content: [Exchange dev/test environment in Azure](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by dariomws306** [comment]
Hi @austinmccollum , good finding. Thank you for your contribution!

I will update this article to add a note about this.

**Comment by dariomws306** [comment]
I am adding this article to See also section, what do you think? Thanks.

**Comment by austinmccollum** [comment]
Yeah, I think that's good enough. The testing mail flow section is right before the See Also section so it gives a pretty good clue. Thanks!

**Comment by dariomws306** [comment]
Good to know! Thank you for your collaboration!

**Comment by scanum** [comment]
PR has been created #556
