### ISSUE TITLE
Wrong Exchange Powershell defined

### ISSUE THREAD

**Issue by pier62350** [MicrosoftDocs/OfficeDocs-Exchange#506]
Hello!
In the part "2. Set up your email server to relay mail to the Internet via Office 365", The documentation said we need to create send connector on the On-Premise Exchange Server... Using Exchange Online Powershell.. It can drive some administrators Crazy!
So please use your Exchange Management Shell to run the "New-SendConnector -Name &lt;DescriptiveName&gt; -AddressSpaces * -CloudServicesMailEnabled $true -Fqdn &lt;CertificateHostNameValue&gt; -RequireTLS $true -DNSRoutingEnabled $false -SmartHosts &lt;YourDomain&gt;-com.mail.protection.outlook.com -TlsAuthLevel CertificateValidation" Command! :) 

Pier

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498774ba-06b8-5087-f884-bab065225d63
* Version Independent ID: a54b404b-0ade-45e8-3282-402c1a3bb0d0
* Content: [Set up connectors to route mail between Office 365 and your own email servers](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail#2-set-up-your-email-server-to-relay-mail-to-the-internet-via-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@pier62350, this was evidently a global search and replace typo. I fixed it.

Thanks for the feedback.
