### ISSUE TITLE
Exchange 2016 CU 11 .Net 4.7.2 Support

### ISSUE THREAD

**Issue by deegee72** [MicrosoftDocs/OfficeDocs-Exchange#507]
Is .Net 4.7.2 supported in CU11?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-gb/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016#network-and-directory-servers)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by MK-Kamal** [comment]
Hello @deegee72 
Yes Exchange 2016 CU11 or later Support  .NET Framework 4.7.2 Please find below Article Exchange Server supportability matrix

https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#Microsoft%20.NET%20Framework

**Comment by scanum** [comment]
PR has been created #508

**Comment by chrisda** [comment]
@deegee72, I further updated the System Requirement topic with this information, and I also refactored the one big table .NET table in the Supportability Matrix topic into separate tables by on Exchange version (the table was getting too wide).
