### ISSUE TITLE
Missing VC2012 pre-requisite for Exchange 2016

### ISSUE THREAD

**Issue by steven-snider** [MicrosoftDocs/OfficeDocs-Exchange#509]
Recent updates to Exchange 2016 installations have changed the Visual C 2012 as a prerequisite to installation.  The docs site needs to be updated to reflect the new prerequisite.

Blog reference which outlines the changes to VC 2012 requirements which needs to be included in the article:
https://blogs.technet.microsoft.com/exchange/2018/10/16/released-october-2018-quarterly-exchange-updates/

**Comment by chrisda** [comment]
@steven-snider the topic has been updated in accordance with the blog post.

Thanks for the feedback.
