### ISSUE TITLE
Scripts link doesn't work

### ISSUE THREAD

**Issue by snipazer** [MicrosoftDocs/OfficeDocs-Exchange#512]
Link for the scripts doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a91350-4f21-d657-2a17-4700fce20acb
* Version Independent ID: 47f55e0e-a94b-c435-9174-c78d107e20c6
* Content: [Configure Exchange Server public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-modern-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
@snipazer Thank you for pointing this out and for your valuable contribution in helping improve MS docs.  Please check this link and see if it works: https://www.microsoft.com/en-us/download/details.aspx?id=46381

**Comment by lindspea** [comment]
@AndreaBarr @scanum please assign to me.

**Comment by lindspea** [comment]
@AndreaBarr @scanum you can close this issue, thank you.
