### ISSUE TITLE
Microsoft recommended best practice?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#517]
Hello,

I'm wondering if Microsoft recommends one vs the other as a best practice between assigning recipient permissions directly to users or to a security group.

My opinion is that direct offers more benefits and the security group approach is more of a carryover from Active Directory resource permissions best practices (shares, printers, etc.), which doesn't quite hold as much value in Exchange.

But I can't find any official direction so just wondering if Microsoft is completely agnostic or if the prefer one vs the other.

Benefits of direct include:. Exchange-managed RBAC control of who can grant mailbox permissions; easier reporting of permission assignments; AutoMapping control (on or off).

One could argue that permission assignment reporting is just as easy when using groups, as long as the groups are easily identifiable for their purpose.  However, there's no way to tell by looking at the group memberships if there have been any direct assignments, so querying with Get-Mailbox, Get-MailboxPermission, Get-RecipientPermission is necessary anyway for full visibility. So that means more queries overall are required for reporting when using the group approach.

The benefits of the group approach are the same benefits that are applicable to shares and printers.  The major difference between shares/printers and mailboxes/groups is that Exchange offers all of the management tools necessary for the task of permission assignment.  Groups are necessary for shares/printers as soon as there are a few users as it gets to hard to manage.  Not the case in Exchange.

The one area the group approach does definitely Trump the direct approach is when truly using full-on role based access control where a user's group memberships are predetermined by their actual job.

I won't go on and list cons but anyway, just wondering if Microsoft has a default stance or is indifferent.

Thanks in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8492161-f0c6-e3e6-9f1e-c006e4edc99c
* Version Independent ID: c792e360-d35a-8aa8-a361-a05f01e0b6b7
* Content: [Manage permissions for recipients](https://docs.microsoft.com/en-us/exchange/recipients/mailbox-permissions?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/recipients/mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JeremyTBradshaw, I don't think we recommend one way vs. the other. It's a venerable old IT axiom that it's always 'better' and certainly easier to assign permissions to groups, because it's so much easier to add or remove permissions for a user simply by adding them to or removing them from the proper group (even if that group only contains one person).

So, I would say Microsoft is rather agnostic on the subject. Each organization's requirements are different, and what works well for one place might be a pain and not work well in another (typically related to size, although good security/permission design should be mostly size agnostic).
