### ISSUE TITLE
Require Third Party Tools?

### ISSUE THREAD

**Issue by Jason9973** [MicrosoftDocs/OfficeDocs-Exchange#519]
Hello Microsoft,
These days Mergers and Acquisitions of companies owning O365 is becoming commonplace.  I cannot understand after all of the years of feedback from customers why Microsoft has no native tools to accomplish this routine task?  Playing around with export/imports of PST's is no solution unless you only have a few mailboxes.  Right now I already own a market leader tool for Sharpoint migrations and merges.  Now it looks like we must also add one of the Exchange migration tools.  So to me this is just like the case of Visual Studio many years was lacking effective IOS DEV tools.  Xamarin was acquired and merged into the VS stack.  I see a similar need and situation here..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Office 365 tenant to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@Jason9973 Instead of third-party tools, we will soon begin emphasizing Fast Track https://www.microsoft.com/en-us/fasttrack/?rtc=1 for most customer email migrations. Thanks for your feedback.

**Comment by marilometa** [comment]
@msdmaguire Fast Track is only for tenants with 150+ licenses
