### ISSUE TITLE
SCEP implementation of antimalware exclusions

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/OfficeDocs-Exchange#52]
Guidance for those using SCEP for Antimalware would be helpful. Specifically, the GUI for adding file and folder exceptions in SCCM Antimalware Policies doesn't allow %ExchangeInstallPath%BIN\etc\etc and other paths because it insists on a \ after all environmental variables. This seems likely not to work correctly since %ExchangeInstallPath% already contains a \ at the end. The work-around I plan to use is to add the unwanted \ after %ExchangeInstallPath% and then export the policy as an xml, remove the unwanted backslash, and re-import the policy.

**Comment by kenwith** [comment]
@gaknigge - Thank you for submitting this feedback.

This is a really good idea regarding antimalware policies and more information.

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
