### ISSUE TITLE
powreshell command wrong

### ISSUE THREAD

**Issue by ThemDiversity** [MicrosoftDocs/OfficeDocs-Exchange#525]
the powershell line of code 
Invoke-MonitoringProbe UM.CallRouter\UMCallRouterTestMonitor -Server server1.contoso.com | Format-List
 is wrong 
it should  be 

Invoke-MonitoringProbe UM.CallRouter\UMCallRouterTestProbe -Server server1.contoso.com | Format-List and you need to have the test extensions  listed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3972ddf2-deaa-dfe3-9313-4074bb6712e5
* Version Independent ID: 92fd16d2-461a-b5b6-3f84-a6db9d4f2d28
* Content: [Troubleshooting UM.CallRouter Health Set](https://docs.microsoft.com/en-us/exchange/management/health/troubleshooting-um-callrouter-health-set)
* Content Source: [Exchange/ExchangeServer2013/management/health/troubleshooting-um-callrouter-health-set.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/management/health/troubleshooting-um-callrouter-health-set.md)
* Product: **exchange**
* GitHub Login: @dstrome2

**Comment by chrisda** [comment]
@ThemDiversity, fixed. Thanks for the feedback.
