### ISSUE TITLE
adding more details

### ISSUE THREAD

**Issue by sulobr** [MicrosoftDocs/OfficeDocs-Exchange#527]
In the above article, is it possible to add details/Note as below? I am not sure if this is going to be internal only information but if we can add some  information on this, it will be helpful as none of our current documentation talk about this and customer open support ticket seeking clarification on expected behavior.

These were the findings from engineering team from discussion under VSO 
Issue 952029. and subsequent follow up for additional clarification.

1) When multiple journal rules are configured and an email matches the scope of multiple journal rules, all matching rules will be triggered. Thus, journal report will be sent to each journal mailbox specified the journal rules triggered.

2) If same journal mailbox is specified in multiple rules and the email triggers these rules, only 1 journal report will be sent to this journal mailbox.

3) Journal rules use SMTP mailFrom address to identify if the email is internal or external. If the SMTP from address shows the domain that is added as accepted domain or remote domain in their Exchange Online, it will be treated as internal email although it was originated externally (For example spoof email from external source with X-MS-Exchange-Organization-AuthAs:Anonymous). Therefore, any journal rule scoped for external emails will not be triggered for these spoof email sent from external source if the SMTP from address shows the domain name that is accepted domain/remote domain.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d4ec80-7a55-398a-22e9-3f5df24a867b
* Version Independent ID: 4543c414-41d1-b8fe-8a58-4dc61ccf61ff
* Content: [Journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
A PR has been created #591

**Comment by chrisda** [comment]
Already fixed.
