### ISSUE TITLE
URL for new agent isn't working

### ISSUE THREAD

**Issue by mobernberger** [MicrosoftDocs/OfficeDocs-Exchange#528]
Hi,
the URL https://aka.ms/modernhybrid isn't working correctly and is redirected to this documentation page instead of the new Agent download page. Could you please correct the Redirection.
Thanks
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174147a5-effb-136b-cd43-e4da0c02a27a
* Version Independent ID: 01f56623-efbc-6e8b-766c-691b16f34a13
* Content: [Microsoft Hybrid Agent – Preview](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/hybrid-agent)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/hybrid-agent.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by TokyoScarab** [comment]
Hello!  Would you be able to provide us a little information about the link so we can resolve this?  It appears you are using a shortened link.  Where did this shortened link come from?  Without knowing the source of the link and the page where it came from (if applicable), we won't be able to assist you further.  We look forward to hearing back from you!

**Comment by mobernberger** [comment]
Hi, this article was updated 4 days ago and now the link is gone from this article. So it seems, that the Agent isn't downloadable right now. so you could close this issue
