### ISSUE TITLE
Incomplete step : proxy mailbox creation without providing an email address

### ISSUE THREAD

**Issue by Raton-Laveur** [MicrosoftDocs/OfficeDocs-Exchange#529]
Step 1.3 states an incomplete Exchange PowerShell command : "New-Mailbox -Name &lt;PFMailbox1&gt; -Database &lt;NewMDBforPFs&gt;"  should be "New-Mailbox -Name &lt;PFMailbox1&gt; -Database &lt;NewMDBforPFs&gt; -EmailAddresses PFMailbox1@domain.com -UserPrincipalName PFMailbox1@domain.com -password password ".
As it is, Exchange PowerShell asks for missing parameters Password and UserPrincipalName, but not for the email address, creating an unusable Mailbox for this role. Has been confirmed during Microsoft CritSit case number 119012619595128, where providing missing EmailAddresses parameter fixed the issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a3a32a-93af-8a1d-f5fa-efdc3475c771
* Version Independent ID: 3038df6a-4076-3886-7b99-f2eb680b5956
* Content: [Configure legacy public folders when user mailboxes are on Exchange 2013 servers](https://docs.microsoft.com/en-us/exchange/configure-legacy-public-folders-where-user-mailboxes-are-on-exchange-2013-servers-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/configure-legacy-public-folders-where-user-mailboxes-are-on-exchange-2013-servers-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-legacy-public-folders-where-user-mailboxes-are-on-exchange-2013-servers-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by scanum** [comment]
A PR has been created #592
