### ISSUE TITLE
Verify command failing

### ISSUE THREAD

**Issue by jantoney** [MicrosoftDocs/OfficeDocs-Exchange#530]
Verify command failing. The enable works, but when you try to verify it comes up as below:

PS C:\WINDOWS\system32&gt; Get-OrganizationConfig | Format-Table -Auto Name,OAuth*
out-lineoutput : The method or operation is not implemented.
    + CategoryInfo          : NotSpecified: (:) [out-lineoutput], NotImplementedException
    + FullyQualifiedErrorId : System.NotImplementedException,Microsoft.PowerShell.Commands.OutLineOutputCommand

-------------------- 
This command works though, so it's just the parameters being requested that don't
Get-OrganizationConfig

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jantoney, the command worked fine for me on a Windows 10 1809 PC connected to a tenant.

The only part of the command that could be a bit weird is the placement of the -Auto switch; it really belongs at the end, so I moved it there.

As far as the rest, even if you run the command:

```
Get-OrganizationConfig | Format-Table BlahBlahBlah,YeahYeahYeah
```

you won't get an error; the command will simply return empty output like this:

```
Get-OrganizationConfig | Format-Table BlahBlahBlah,YeahYeahYeah

BlahBlahBlah YeahYeahYeah
------------ ------------

```
