### ISSUE TITLE
AccountType 

### ISSUE THREAD

**Issue by lin-art** [MicrosoftDocs/OfficeDocs-Exchange#531]
com.microsoft.outlook.EmailProfile.AccountType accepts "ModernAuth" as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 959f9d6d-c4a9-ad1e-51ef-2d949e90a103
* Version Independent ID: 0c6ee675-e3f1-81e8-0bb0-e274826f87eb
* Content: [Account setup in Outlook for iOS and Android using Basic authentication](https://docs.microsoft.com/en-us/exchange/clients/outlook-for-ios-and-android/account-setup?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/outlook-for-ios-and-android/account-setup.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-for-ios-and-android/account-setup.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@lin-art Yes it does. We have that documented in http://aka.ms/omappconfig. Thanks for your feedback.
