### ISSUE TITLE
Clarity Needed

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#532]
It is not clear on this document or in the HCW which endpoints must be exposed to the internet for hybrid mail flow between EXO and on-prem exchange.  For example, the HCW has you pick 1:M servers to host the receive connector. So do each of those require a public IP that EXO can connect to directly?  Then the HCW asks for your environments FQDN and says it is using that for mail flow.  Which is it?  If we connect via the FQDN, you end up going to a load balancer which would then not line up with the servers that you selected for the on-prem receive connectors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498774ba-06b8-5087-f884-bab065225d63
* Version Independent ID: a54b404b-0ade-45e8-3282-402c1a3bb0d0
* Content: [Set up connectors to route mail between Office 365 and your own email servers](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TokyoScarab** [comment]
@SharS I thought I might reach out to you to see if you might be able to collaborate on this being one of the authors of the page.  If any changes need to be made on the page, I will be happy in make those edits.

**Comment by TokyoScarab** [comment]
I would highly recommend checking out the [link](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow#what-if-i-have-my-own-email-servers) that is in the note on the top of that page.  It links to a great deal of information including this [page](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail) that has all the information I believe you are looking for.
