### ISSUE TITLE
Details on EXO to On-Prem Transport

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#533]
Can you add some details on how EXO determines what endpoint (DNS name) is used to deliver mail to the on-prem org?  Is it always only the "Organization FQDN" that is setup in the hybrid configuration wizard?  If that is the case, should a dedicated DNS/VIP be setup on the load balancer to only include the servers that are setup with the receive connector that were configured in the HCW?  Are there any restrictions on load balancing the SMTP endpoint between EXO and on-prem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b002f0ce-5397-15cb-4c60-0eaaa87aaf52
* Version Independent ID: 32e3a594-2d2c-9f8a-9a38-e60e3ffaae85
* Content: [Transport routing in Exchange hybrid deployments](https://docs.microsoft.com/en-us/exchange/transport-routing)
* Content Source: [Exchange/ExchangeHybrid/transport-routing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/transport-routing.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by TokyoScarab** [comment]
@msdmaguire Would you be able to share some insight on this issue?  If the document in question requires some editing to expand upon this, I am willing to fill in any gaps.  I figured I would ask your advice on it being one of the original contributors to the page.  Thanks!

**Comment by TokyoScarab** [comment]
Hello!  I believe the information you are looking for can be found on this doc page [here](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail).  If you have any further questions, please contact [Microsoft Support](https://support.microsoft.com/en-us).  Thanks!
