### ISSUE TITLE
High Availability Details Needed

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#534]
How to make hybrid connectivity highly available
- multiple paths / load balancing for SMTP from EXO to on-prem
- EWS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec121a3-cccf-1164-777e-be5e4dc9d2c5
* Version Independent ID: 37c911be-c56e-8975-260b-6f8ddc497ee9
* Content: [Hybrid Configuration wizard FAQs](https://docs.microsoft.com/en-us/exchange/hybrid-configuration-wizard-faqs)
* Content Source: [Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@danmyhre Hi Dan.  Thank you. We are looking into this as well and will give you feedback as soon as possible.

**Comment by lindspea** [comment]
@dariomws306 @MK-Kamal 06 @danmyhre  Right now the AD connect can be: 
1. Synchronization - while you can't do AD connect highly available, at least you have multiple tenants.  Please see this document for reference: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/plan-connect-topologies 
2. Hybrid connection - you can't do a "high available" hybrid connection. You need to make sure your systems goes to the internet. 
For HA you'll just need on-prem, not hybrid.  See this article for reference: https://practical365.com/exchange-server-high-availability/
Load balancing is not a high availability, you're just making sure you have a path to the internet (so it can hit EXO) which is internal to each enterprise. 
Please let me know if you agree with this or if you have any further suggestions.

**Comment by danmyhre** [comment]
I wasn't referring to AD Connect, I was referring to making the SMTP path for EXO to On-Prem highly available.  As this is a critical connection in hybrid scenarios, having it go to a single server is not practical. 

The referenced article is not official MSFT documentation.  it also has nothing to do with hybrid HA.  We need to get this updated with what is supported for hybrid mail flow and EWS connectivity.

**Comment by lindspea** [comment]
@dariomws306 @MK-Kamal

**Comment by dstrome** [comment]
hi @danmyhre. Thanks very much for your feedback. We'll be doing some work on the hybrid content set soon and will include this as an area of improvement to consider.

David.
