### ISSUE TITLE
More details needed

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#536]
Please explain this more:

On the Organization FQDN page, enter the externally accessible FQDN for your Internet-facing Exchange server. Office 365 uses this FQDN to configure the service connectors for secure mail transport between your Exchange organizations. For example, enter "mail.contoso.com". Click Next.

For most organizations, "mail.domain.com" would be pointing to the hardware load balancer for web traffic.  

Please add some details around:
- does this HAVE to be a public IP nat'd to an exchange server OR an edge server?  Or can this go through a load balancer?
- how do you add more than 1?  A single point of failure is not realistic in any environment except very small orgs or non-prod
- does this need to match the server that you selected to have the receive connector?  If not, how would it work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb8cb000-e64b-b90d-fa6f-09f2b50532b3
* Version Independent ID: b65f1351-a45c-37b6-f1a8-12894f203dd4
* Content: [Create a hybrid deployment with the Hybrid Configuration wizard](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/deploy-hybrid)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/deploy-hybrid.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by lindspea** [comment]
@danmyhre Hi Dan.  Thank you for your suggestions and your valuable contribution in helping to improve MS docs.  I'm investigating with the team so see where we can update the information.  I will revert soonest.

**Comment by lindspea** [comment]
@MK-Kamal @dariomws306 @danmyhre I think in the States they have an Edge server, but elsewhere - 95% have the Internet-facing Exchange server, and 4% would have a firewall. So if I'd change that, I'd change it to your "preferential firewall" where you have the open ports required for O365 to connect to your internal exchange server. 
You don't publicly use your "load balancer", you use the next device (of security which is a firewall, a strong one like FortiGate, Cisco or Netgear). O365 uses the FQDN to move mailboxes from one site to the other or to route emails to on-prem, but as long as you have a firewall configured correctly, EXO will find its way. Please have a look at this article for reference: https://practical365.com/exchange-server-high-availability/.  Let me know what you think, or if you have any other suggestions.

**Comment by danmyhre** [comment]
I think we still need clarity in the documentation.  The link isn't relevant to the question about hybrid.

**Comment by lindspea** [comment]
@dariomws306 @MK-Kamal

**Comment by dariomws306** [comment]
Hi @dstrome , Will your team be working on this article too? (related to Exch hybrid too)

Thanks!

**Comment by dstrome** [comment]
hi @danmyhre ,

Thanks for your question. The Organization FQDN is specific to secure mail; while it may also be the same FQDN as the one you use for OWA traffic, this specific page is related to secure transport only. For secure transport, you must specify the FQDN of an on-premises Exchange server. No hardware or services that process or modify SMTP traffic can be placed between Office 365 and your on-premises Exchange server. For more information, see https://docs.microsoft.com/en-us/exchange/transport-routing.
