### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#537]
Add screenshots of what the user flow will look like

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30c4fd6-0e69-cb9a-6a21-327f0ebae3a7
* Version Independent ID: d0217aa4-a37b-8837-4310-108fbf533a5d
* Content: [Simplify the Outlook Web App URL for Office 365 Hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/simplify-owa-url)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/simplify-owa-url.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
@danmyhre Hi Dan.  Thank you for reaching out.  I'm looking into your request and will revert soonest.

**Comment by scanum** [comment]
@danmyhre Thank you for your feedback, it is really appreciated. At this stage we will not be putting screenshots in, however, we have addressed it with the author for future updates.

**Comment by lindspea** [comment]
@AndreaBarr @scanum this can be closed thank you.
