### ISSUE TITLE
Mail flow

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#538]
How about adding some details for troubleshooting hybrid mail flow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe9b5a0-e41d-b92a-b221-cc12a3945618
* Version Independent ID: 6ff00d15-7376-c2b6-0d3f-c71a5ff1c7dd
* Content: [Troubleshoot a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/troubleshoot-a-hybrid-deployment)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/troubleshoot-a-hybrid-deployment.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/troubleshoot-a-hybrid-deployment.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
@MK-Kamal

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@officdeocsbot reopen

**Comment by scanum** [comment]
@officedocsbot reopen

**Comment by sowjanya365** [comment]
Hi @danmyhre 

Thank you for reaching out! 

Please refer to the following documentation for troubleshooting email flow. 

https://docs.microsoft.com/exchange/mail-flow-best-practices/troubleshoot-mail-flow

https://docs.microsoft.com/Exchange/fix-outlook-connection-problems-in-office-365/find-and-fix-email-delivery-issues-as-an-office-365-for-business-admin

Thank you!

**Comment by danmyhre** [comment]
Thanks but neither of those cover anything about hybrid

This page in particular could really use some additional / more inf depth content
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/troubleshoot-mail-flow

**Comment by sowjanya365** [comment]
Hi @danmyhre 

Thank you for response. 

Yes, we were both referring to the same URL. If you observer my first message, I've referred the same URL. 

https://docs.microsoft.com/exchange/mail-flow-best-practices/troubleshoot-mail-flow

Thank you. Hope we can close this issue now. Kindly confirm.

**Comment by danmyhre** [comment]
Hi - I am saying that neither of those pages provide the content needed.  So this is not ready to be closed yet.

**Comment by scanum** [comment]
@sowjanya365

**Comment by scanum** [comment]
@sowjanya365 Following up on this issue. Thanks!

**Comment by lindspea** [comment]
@sowjanya365

**Comment by sowjanya365** [comment]
Hello @danmyhre 

The following article explains troubleshooting issues with certificates and Troubleshooting specific errors of the Hybrid Configuration wizard. 

https://docs.microsoft.com/exchange/hybrid-deployment/troubleshoot-a-hybrid-deployment

If you are looking for any specific issue troubleshooting, open a service ticket in your tenant so this can get addressed ASAP. 

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Thank you!

**Comment by mattpennathe3rd** [comment]
@danmyhre I'll dive into this one a bit and see if I can find some further information for you. I'll report back.

**Comment by SignorelliDenis** [comment]
@danmyhre Agree with you and the good news is that we are preparing a deep dive about Hybrid mail flow to be published on EHLO blog, it’s in the final review and almost ready, stay tuned.

**Comment by SignorelliDenis** [comment]
> @danmyhre Agree with you and the good news is that we are preparing a deep dive about Hybrid mail flow to be published on EHLO blog, it’s in the final review and almost ready, stay tuned.

https://techcommunity.microsoft.com/t5/exchange-team-blog/demystifying-and-troubleshooting-hybrid-mail-flow-when-is-a/ba-p/1420838
