### ISSUE TITLE
Pass-through Authentication

### ISSUE THREAD

**Issue by kayleeefish** [MicrosoftDocs/OfficeDocs-Exchange#54]
Hi. Could you please update this document to include pass-through authentication? If there are limitations with multi-forest Exchange hybrid configurations (as I suspect there are), those would be useful to know too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50117f9a-45dd-90fb-a592-6a12c6104875
* Version Independent ID: d07fe199-59af-86bf-fe79-c7e2d342a463
* Content: [Single sign-on with hybrid deployments](https://docs.microsoft.com/en-us/exchange/single-sign-on)
* Content Source: [Exchange/ExchangeHybrid/single-sign-on.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/single-sign-on.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by kayleeefish** [comment]
By multi-forest, I realise only one forest will be able to participate in a hybrid.

**Comment by kenwith** [comment]
@kayleeefish - I have captured this info and was able to get it added to backlog for the Exchange team. This is good info for clarification. Thanks for taking the time and also for the follow up!
