### ISSUE TITLE
Support for Office 365 in mail flow conditions and exceptions

### ISSUE THREAD

**Issue by Pulsarrrr** [MicrosoftDocs/OfficeDocs-Exchange#541]
Microsoft is putting a lot of effort into encouraging people to make a transition from distribution groups to Office 365 groups. It would not make any sense if the mail flow rules in EAC did not support Office 365 groups.
I have successfully tested Office 365 groups, and they can be added to all the group-related conditions (such as The sender is a member of...). The only issue is that, by default, the group picker available when defining these conditions does not show Office 365 groups. You can type the Office 365 group email address manually, though, and click Check names to add it (see an example here: https://www.codetwo.com/kb/add-groups-transport-rule-office-365/#groups-not-available). The Exchange admin center will recognize the group and everything will work just fine. It's quick and easy to test this, can you confirm this and update the article, please? Also, it would be nice if MS made it possible to display Office 365 groups directly in the group picker in conditions/exceptions.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b18f30a-b22b-5f3b-8357-82690321bad0
* Version Independent ID: cf3ce6c5-bd43-380a-b162-d475032facb8
* Content: [Mail flow rule conditions and exceptions (predicates) in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/conditions-and-exceptions#senders)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/conditions-and-exceptions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/conditions-and-exceptions.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@Pulsarrrr, I did some testing. Office 365 groups are basically a special type of mailbox that also functions as a group. I confirmed the 'O365 group by email address in the EAC' method worked for the following conditions/exceptions:

- The sender is

- The sender is a member of

- The recipient is a member of

- The To/Cc box contains

- The To/Cc box contains a member of

- The message is between members of these groups

I also confirmed an O365 group does not work with 'The recipient is' (which corresponds to the 'doesn't work with groups' behavior).

I updated the topic accordingly.

Thanks for the feedback.

**Comment by Pulsarrrr** [comment]
Thanks a lot, @chrisda! Looking forward to seeing your updates in the article (guess it takes a while before they are visible online). Anyway, is there any chance Microsoft's going to update the group picker so that Office 365 groups are visible directly? Using the _Check names_ button does not seem too intuitive...

**Comment by chrisda** [comment]
@Pulsarrrr, my guess is that adding the Check names button was the mitigation for the problem, and there likely won't be any more improvements to the recipient picker in the EAC.
