### ISSUE TITLE
Broken Link: Supported Browsers for Outlook Web App

### ISSUE THREAD

**Issue by ran-dall** [MicrosoftDocs/OfficeDocs-Exchange#542]
This link for [Supported Browsers for Outlook Web App](https://go.microsoft.com/fwlink/p/?LinkId=402700); that should display the browser the requirements for the ”Outlook Web App” isn’t working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe03d3b-31dc-90a2-2a78-1e48947b86d8
* Version Independent ID: 2873f6e9-6979-31d1-5622-0ae47cd9d965
* Content: [Exchange admin center in Exchange Online](https://docs.microsoft.com/en-us/exchange/exchange-admin-center)
* Content Source: [Exchange/ExchangeOnline/exchange-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/exchange-admin-center.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by MK-Kamal** [comment]
Hi @ran-dall  Thank you for your contribution!
I will update this article with the  correct Url .

https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/558

Thanks

**Comment by chrisda** [comment]
@MK-Kamal @AndreaBarr, I'm closing this issue as the link now seems to work correctly
