### ISSUE TITLE
ToolTips on non enrolled devices (pretty please)

### ISSUE THREAD

**Issue by stevep4** [MicrosoftDocs/OfficeDocs-Exchange#543]
"com.microsoft.outlook.Mail.ExternalRecipientsToolTipEnabled"
"This capability only works with enrolled devices"

Any idea why? Will that change?
We have many users using the Outlook app via MAM-WE and it'd be great to have the tool tips available, but it seems we can't...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#general-app-configuration-settings)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by TokyoScarab** [comment]
Hello!  I'm unable to speak to the reason why support for this is currently only on enrolled devices.  Microsoft has a service set up for issues just like this called UserVoice.  UserVoice gives users and customers a platform to share their ideas for improving current software and services.  You can head to the [Outlook UserVoice](https://outlook.uservoice.com/) and see if this issue has already been brought up.  If it hasn't, I would suggest making a post.
