### ISSUE TITLE
Complete-MigrationRequest 

### ISSUE THREAD

**Issue by mohanra1** [MicrosoftDocs/OfficeDocs-Exchange#546]
This is not a valid command. please correct the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51c92752-7e76-3f33-2e93-42eb13e63a1a
* Version Independent ID: 0b4de7ea-4982-30a3-4c69-b42dcfa73416
* Content: [Manage on-premises mailbox moves in Exchange Server](https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/manage-mailbox-moves?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/manage-mailbox-moves.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/manage-mailbox-moves.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mohanra1, confirmed. I changed the reference to Start-MigrationRequest and Complete-MigrationRequest to Start-MigrationBatch and Complete-MigrationBatch.

Thank for the feedback.
