### ISSUE TITLE
Monitoring mailboxes on litigation hold

### ISSUE THREAD

**Issue by NavishkarSadheo** [MicrosoftDocs/OfficeDocs-Exchange#550]
The article states - "We recommend that you monitor mailboxes that are placed on Litigation Hold on a weekly basis to ensure they don't reach the limits of the Recoverable Items quotas."

How does one goes about monitoring this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f9f27d-572d-f259-cf1c-12697ddf6fcc
* Version Independent ID: 0875b460-4f28-a81f-3e4e-1f6af7ab0bd3
* Content: [Place a mailbox on Litigation Hold](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/holds/litigation-holds?view=exchserver-2019#)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/holds/litigation-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/holds/litigation-holds.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by markjjo** [comment]
YOu can run the Get-MailboxFolderStatistics  -FolderScope RecoverableItems | fl folderpath,foldersize,folderandsubfoldersize command (see https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-mailboxfolderstatistics?view=exchange-ps) - I will add link to this cmdlet help topic from the litigation hold topic.
