### ISSUE TITLE
Re-enable an archive mailbox

### ISSUE THREAD

**Issue by mailgut** [MicrosoftDocs/OfficeDocs-Exchange#551]
Re-enable an archive mailbox -&gt; the sugestet soluton does not work. You willl get an empty Archiv. You say the following:
you can have Exchange automatically select a mailbox database for the re-enabled archive mailbox or you can click Browse to specify one.
-&gt; If you selct a different mailboxdatabas as the original -How should the contens of the deleted Archiv get into the new Archive?

A solution which is working is the following:

Enable-mailbox -identity "Kalle, Blomquist" -ArchiveGUID X0a104ef-75d3-4XXXXXX-XXXXa79f3 -ArchiveDatabase SVXXX-MBDB01 -Archive

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a559595-95c7-efa0-7147-e98f07415d0c
* Version Independent ID: 1d1f5a33-6b66-fae5-17f9-a2b43eddf173
* Content: [Manage In-Place Archives in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/in-place-archiving/manage-archives?view=exchserver-2019#re-enable-an-archive-mailbox)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/in-place-archiving/manage-archives.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/in-place-archiving/manage-archives.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Jcoetsee** [comment]
@SerdarSoysal Can you please review the above question and should we consider adding the PowerShell CMDlet as an item into the original article to be used in this scenario?

**Comment by Jcoetsee** [comment]
@SerdarSoysal Just another follow up regarding this. please see previous comment.

**Comment by SerdarSoysal** [comment]
I think the article is correct as is. At the beginning of the pertinent section, we state: "By default, Exchange retains disconnected archive mailboxes for 30 days. Within 30 days of disabling an archive mailbox, you can reconnect it to the user's primary mailbox by re-enabling the archive. In this case, the original contents of the archive mailbox are restored. However after 30 days of disabling a mailbox, the contents of the original archive mailbox are permanently deleted (purged from the mailbox database) and can't be recovered. So if you re-enable the archive more than 30 days after disabling it, a new archive mailbox is created when you re-enable it."

Therefore, if you re-enable an archive mailbox past the 30 days, you will get an empty archive mailbox. Once you are past the 30 days, even the proposed solution will not work. Recommend leaving this content as is and responding to the issue with the above.

**Comment by kenwith** [comment]
@mailgut - we are going to go ahead and close this as the Microsoft author described above. If you feel strongly please go ahead and re-open and we can discuss further. Thank you for taking the times to open issues against content and helping the community. Please don't get discouraged on this one and keep up the good work. Thank you!
