### ISSUE TITLE
Wrong information in Supported Active Directory environments?

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/OfficeDocs-Exchange#552]
When trying to install the AD Schema updates, your information seems to be wrong.  When I install 2016 CU 11, it doesn't work on Windows Server 2008 (not R2) as it indicates it will on your chart.  The information in your chart conflicts with information from https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#supported-active-directory-environments)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mattdreher, I'm afraid I'm going to need more specifics.

Are you saying that you're attempting to use Exchange 2016 CU11 to do schema updates on a Windows 2008 server? Or actually install Exchange 2016 CU11 on a Windows 2008 server? All of the information I can see in both topics regarding Exchange 2016 and Windows 2008 says Windows 2008 R2 (OS requirements, forest functional level requirements, etc.).

Am I missing something?

**Comment by mattdreher** [comment]
If you read the two tables from https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#supported-active-directory-environments
It makes it seem like you can install **Exchange 2016 CU11** when you are using **Windows Server 2008 SP2 Active Directory** servers in a **Windows Server 2008 SP2** forest functional level which isn't the case. The installer complains it cannot update the schema on anything less than **Windows Server 2008 R2**.

**Comment by chrisda** [comment]
@mattdreher, I see the issue now. I updated the table headings so 2008 AD/FFL is for Exchange 2016 CU3 to CU6 (it used to say CU3 or later), and 2008 R2 AD/FFL is CU7 or later (it used to say CU12 or later).

Thanks for the feedback.
