### ISSUE TITLE
AD Schema information conflicts with your on websites.

### ISSUE THREAD

**Issue by mattdreher** [MicrosoftDocs/OfficeDocs-Exchange#553]
The information here conflicts with information from https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#supported-active-directory-environments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by mattdreher** [comment]
If you read the two tables from https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#supported-active-directory-environments
It makes it seem like you can install **Exchange 2016 CU11** when you are using **Windows Server 2008 SP2 Active Directory** servers in a **Windows Server 2008 SP2** forest functional level which isn't the case.  The installer complains it cannot update the schema on anything less than **Windows Server 2008 R2**.

**Comment by chrisda** [comment]
@mattdreher, I see the issue now. I updated the table headings so 2008 AD/FFL is for Exchange 2016 CU3 to CU6 (it used to say CU3 or later), and 2008 R2 AD/FFL is CU7 or later (it used to say CU12 or later).

Thanks for the feedback.
