### ISSUE TITLE
Microsoft Remote Connectivity Analyzer is down

### ISSUE THREAD

**Issue by mjafferx** [MicrosoftDocs/OfficeDocs-Exchange#559]
Microsoft Remote Connectivity Analyzer is down with a service unavailable 503 error for the last two days. Can someone please reset it? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
I'm able to access https://testconnectivity.microsoft.com/. Please try again.

**Comment by fixerivan** [comment]
![image](https://user-images.githubusercontent.com/29037777/53803532-543ba880-3f45-11e9-95e0-72e9c5a90485.png)

it is down again

**Comment by AtarianComputing** [comment]
Down here as well.

**Comment by pgenova** [comment]
Still down...

**Comment by salmosS** [comment]
One more time its out of service with error 503

**Comment by AZphanus** [comment]
It has been down for me for the past couple of days.

**Comment by bfegger** [comment]
and again. Service unavailable. Could someone please reset or fix it? Or at least tell us why and when? 
thx
