### ISSUE TITLE
404 error on link

### ISSUE THREAD

**Issue by jasonshave** [MicrosoftDocs/OfficeDocs-Exchange#56]
Getting 404 error on the following link in this article: https://docs.microsoft.com/azure/active-directory/active-directory-conditional-access-mam#exchange-online-policy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247b0890-a1fe-6243-5ed5-09caa093e942
* Version Independent ID: 5abcab3a-5288-d497-e56b-b0cc1d5eb2b8
* Content: [Securing Outlook for iOS and Android in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/secure-outlook-for-ios-and-android#setting-up-outlook-for-ios-and-android)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/secure-outlook-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/secure-outlook-for-ios-and-android.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by kenwith** [comment]
@jasonshave - I got this on the backlog so it can be tracked and get addressed. Or if you know off the top of your head where the link should go I can add it as a Pull Request or if you are open to it I can guide you to add it as a Pull Request. It is really easy to make quick changes like this.

We put together instructions on creating a Pull Request in the README in the root of the repo here: https://github.com/MicrosoftDocs/OfficeDocs-Exchange

You can get to the source content in the link above in the issue. Just ping me and I can do it or show you how so you can make these quick fixes anytime.

It is on the backlog for the writing team though so even if we don't do anything immediately it will still be addressed. Thanks for catching this!
