### ISSUE TITLE
App Passwords

### ISSUE THREAD

**Issue by tfcarlin** [MicrosoftDocs/OfficeDocs-Exchange#560]
Unfortunately App Passwords are no longer available on Google account that are set to use Security Key only. Maybe time to update your software to a more modern API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e62f5860-4f99-6794-f8d6-2207b7f19979
* Version Independent ID: c28b87f8-1984-6522-021f-bae92e46d08c
* Content: [Prepare your Gmail or G Suite account for connecting to Outlook and Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/prepare-gmail-or-g-suite-accounts.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@tfcarlin Thank you very much for your kind feedback. We recommend that you submit this feedback into Outlook [Uservoice](https://outlook.uservoice.com/). Exchange does not have a UseVoice channel, however, the Outlook team works with Exchange to add features when needed. The team will evaluate and take the appropriate action, as per their schedule. We strongly appreciate you for taking time and sharing your feedback.
