### ISSUE TITLE
Recreate Discovery system mailbox command is missing.

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-Exchange#561]
That section has the setup.exe /prepareAD steps but looks like the mailbox enable command was forgotten.  This works:

Enable-Mailbox "SystemMailbox{e0dc1c29-89c3-4034-b678-e6c2
9d823ed9}" -Discovery -Database MDB001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca0013eb-5599-a907-9869-569f40f1e725
* Version Independent ID: 9fd23081-2830-c87b-561b-582fb16fc09e
* Content: [Recreate missing arbitration mailboxes](https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/recreate-arbitration-mailboxes?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@JeremyTBradshaw, looking at the topic and also the [2013 version](https://docs.microsoft.com/exchange/re-create-the-discovery-system-mailbox-exchange-2013-help), the implication appears to be that running Setup.exe /PrepareAD in and of itself will **automatically** recreate the mailbox. Are you saying that's incorrect?

**Comment by JeremyTBradshaw** [comment]
Hi Chris,

Yep that is what I mean.  However I missed that it is the 2013 version, as I was thinking 2016.  I did /PrepareAD but still had to recreate that account's mailbox manually, telling me the PrepareAD step doesn't do it automatically.

I could have mis-concluded that fact, but if you scan through the entire article you can see all steps except this one show the PrepareAD step (with two options to choose between), then some form of an Enable-Mailbox command.  That is what initially caught my attention, and then it seemed to unfold in accordance with my assumption.

I could go test again and report back, but only with 2016 so maybe not worth the bother.

**Comment by chrisda** [comment]
@JeremyTBradshaw as far as I could tell, the only persisted capability on the SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9} mailbox is UMDataStorage. I created a new arbitration mailbox, removed UMDataStorage from SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}, and added it to the new arbitration mailbox. I still can't use Remove-Mailbox to remove SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}; I get: `The arbitration mailbox "SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}" is used by Exchange and can't be removed.`.

So how were you able to remove SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}?

**Comment by JeremyTBradshaw** [comment]
Hi @chrisda,

It was when a database became corrupt, and the arbitration/system mailboxes that were on it were lost.  It is not production or anything, just a lab, but that is how I ended up at the article.  Since there were no backups available, I was doing a new database and recreating the mailboxes.  Everything went perfectly, minus that one mailbox needed the extra Enable-Mailbox command.

**Comment by chrisda** [comment]
@JeremyTBradshaw, OK I updated the topic.

Thanks for the feedback.
