### ISSUE TITLE
Capitalization in Boolean values

### ISSUE THREAD

**Issue by In-FinIT** [MicrosoftDocs/OfficeDocs-Exchange#566]
The first letters in the "Accepted Values" of certain Boolean values are capitalized in the documentation, but InTune only accepts them in all lower case. Eg the Accepted Values for com.microsoft.outlook.Mail.ExternalRecipientsToolTipEnabled should be:

true, false

and NOT:

True, False

Having them capitalized results in InTune throwing an error and not allowing the configuration to be saved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@In-FinIT, OK. Fixed. Thanks for the feedback.
