### ISSUE TITLE
Step 19 says to move PF data from 2013 to 2013

### ISSUE THREAD

**Issue by philliprenouf** [MicrosoftDocs/OfficeDocs-Exchange#569]
This should say Move public folder data from Exchange 2007 to Exchange 2013

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d1e602b-f2bb-7ffe-efdf-c7f7ec5db121
* Version Independent ID: e9496b8d-af3c-ff53-1b05-0580de3165f6
* Content: [Checklist: Upgrade from Exchange 2007: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/checklist-upgrade-from-exchange-2007-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/checklist-upgrade-from-exchange-2007-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/checklist-upgrade-from-exchange-2007-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by chrisda** [comment]
@philliprenouf, corrected. Thanks for the feedback.
