### ISSUE TITLE
Outlook 2019 support

### ISSUE THREAD

**Issue by OneCyrus** [MicrosoftDocs/OfficeDocs-Exchange#570]
Outlook 2019 is missing in the support matrix. Which Exchange version does it officially support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@OneCyrus, Exchange Server 2010 or later. I updated the topic.

Thanks for the feedback.
