### ISSUE TITLE
Skype Server / Pool Information

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#576]
Need to add details on which this should point to - enterprise edition pool FQDN or the director pool FQDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fea5d42d-7fdc-3f4e-621f-2b032f9686e8
* Version Independent ID: 8c2bd6ee-210a-b3d8-3e86-5cb280719daa
* Content: [Configure instant messaging integration with Outlook on the web in Exchange](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by j0rt3g4** [comment]
@danmyhre  can you specify what do you mean with "which this should point to"

**Comment by danmyhre** [comment]
Depending on your SfB topology, you may have multiple FE pools and possibly a director pool.  You may also have Exchange across multiple AD sites.  I am referring to what is the guidance on which SfB endpoint (which pool FQDN) should be used in this section.  Should it be regional (e.g. closest pool to the exchange AD site), should it be the director pool?

IMServerName=<Skype server/pool  name>

**Comment by j0rt3g4** [comment]
@danmyhre I've added information about in the PR #695
