### ISSUE TITLE
Missing Details

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#577]
This is missing details on the SfB side of the configuration.  Should at least provide a link to the appropriate SfB documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fea5d42d-7fdc-3f4e-621f-2b032f9686e8
* Version Independent ID: 8c2bd6ee-210a-b3d8-3e86-5cb280719daa
* Content: [Configure instant messaging integration with Outlook on the web in Exchange](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/configure-im-integration-with-owa.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by TokyoScarab** [comment]
Thanks for bringing this up!  The documentation will be updated with a link for the Skype For Business side of the configuration.

**Comment by scanum** [comment]
PR #688
