### ISSUE TITLE
visual C++ 2013 required for Edge 2016 cu10

### ISSUE THREAD

**Issue by MikeHynek** [MicrosoftDocs/OfficeDocs-Exchange#580]
The docs say I only need Visual C++ 2012.
When I try to install the edge server.... I get this
Error:
Visual C++ 2013 Redistributable Package is a required component. Please install the required binaries and re-run the setup. Use URI https://www.microsoft.com/download/details.aspx?id=40784 to download the binaries.
For more information, visit: http://technet.microsoft.com/library(EXCHG.150)/ms.exch.setupreadiness.VC2013RedistDependencyRequirement.aspx

**Comment by Jcoetsee** [comment]
Hi @MikeHynek - Would you be able to possibly link the article that you are referring to with regards to this question?

**Comment by Jcoetsee** [comment]
Hi @MikeHynek Just another follow up to see if you could provide more information on the article you had been referring to?

**Comment by MikeHynek** [comment]
yea,
the doc says you only need one of the two c++ runtimes when you are installing the EDGE version of exchange

I found in my lab that both 2012 and 2013 version are needed.
https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prerequisites?view=exchserver-2016

so this is wrong, it should be like the mailbox server, both version of visual studio are needed.

[cid:c32b4368-8ab1-495b-a090-167b7b0e7aec]

Mike Hynek
Senior Consultant | Business Productivity Cloud Solutions
Mobile: 608-444-1391 | Mike.Hynek@Microsoft.com


________________________________
