### ISSUE TITLE
Add Office ProPlus to the client support mattrix 

### ISSUE THREAD

**Issue by JaroncMicrosoft** [MicrosoftDocs/OfficeDocs-Exchange#581]
The client support matrix calls out Office Professional or Office 2016 but does not call out Office ProPlus. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-au/Exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@JaroncMicrosoft, when clients in the supportability matrix topic, are really about what versions of Outlook (more so than Office) are supported with what versions of Exchange Server.

Office 365 ProPlus is a subscription that includes Outlook 2016 (if you bought it a year ago) and Outlook 2019 (if you bought it today). To your point, Outlook 2019 was missing from the table, so I added it.

Thanks for the feedback

**Comment by JaroncMicrosoft** [comment]
Not wanting to be pedantic but there is a difference between Office Professional 2019 and Office ProPlus. Thanks for adding Office Professional 2019 but can you also add Office ProPlus

JC
