### ISSUE TITLE
If I enable archive mailboxes does it unlock all the limitations (quota limits and retation limits)? 

### ISSUE THREAD

**Issue by christiangomez92** [MicrosoftDocs/OfficeDocs-Exchange#583]
Can you help me to understand how it will be structured the subtrees ? Also, what license do I need if I already have a Entreprise E2 license in my organisation to enamble archie mailboxes ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef58ac9b-e0a9-51e9-787e-ce2a4e6b6bfa
* Version Independent ID: c567570c-1214-38a8-8a5c-9cae85b7aece
* Content: [Recoverable Items folder in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/recoverable-items-folder/recoverable-items-folder?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/recoverable-items-folder/recoverable-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/recoverable-items-folder/recoverable-items-folder.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by Jcoetsee** [comment]
@christiangomez92 I wanted to check with you just to confirm what the question is about and if you could provide more information, please?

I believe the question revolves specifically around archive mailboxes however the link it was used from or the article it relates to in this opened issue focuses on recoverable items folder?

**Comment by christiangomez92** [comment]
Hello @Jcoetsee 
I would like to know the archive quota and retention limitations for my mailboxes with a E2 license. I read something about "enable archive mailboxes" and I didn't totally understand please 

Thank you

**Comment by Jcoetsee** [comment]
@SerdarSoysal Would you mind reviewing the above question asked and see if you can provide some insight as to what the individual is looking for? I think the answer will likely be in another article that specifically focuses on archive mailboxes etc..?

**Comment by Jcoetsee** [comment]
@christiangomez92 There is no E2 license that's specific to Office365 or the exchange side of things, you would likely have something like an E3 license. in that regard I can direct you to the below link that will for sure answer your questions around your mailbox and size limitations/quotas

https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits

**Comment by Jcoetsee** [comment]
@christiangomez92 Just another follow up regarding this.
