### ISSUE TITLE
New options of Out of Office are promised but unavailable on Exchange 2019!

### ISSUE THREAD

**Issue by FunkEinstein** [MicrosoftDocs/OfficeDocs-Exchange#584]
I've got a question about new options for Out of Office feature. They are already works on Exchange Online, but on Exchange 2019 they are unavailable.

When I say that they are unavailable I mean that documentation of Set-MailboxAutoReplyConfiguration says that new options(AutoDeclineFutureRequestsWhenOOF for example) are available only on Exchange Online and when I try to use these options I get next error: "A parameter cannot be found that matches parameter name <name of option>".

But microsoft's documentation says that they was added in new version, you can see that in "Calendar - Better Out of Office" section on page: https://docs.microsoft.com/en-us/exchange/new-features/new-features?view=exchserver-2019.

I do not understand what's going on. Do i do something wrong?

**Comment by FunkEinstein** [comment]
Hey, I need an answer! What's going on? I need that functionality but I can't use it. Because Set-MailboxAutoReplyConfiguration cmdlet wasn't modified for Exchnage 2019 new options of out of office doesn't work for on-premise OWA! So that can't be my fault and I need to know what happened!

**Comment by Jcoetsee** [comment]
@dstrome Would you mind reviewing the questions asked by this individual and see if you can provide clarity?

It relates to the article 
https://docs.microsoft.com/en-us/exchange/new-features/new-features?view=exchserver-2019.

**Comment by FunkEinstein** [comment]
I already find answer from one Exchange blogger who contacting with Microsoft. More than that update with fixes already available and I have updated my server. So no more need in your help, but I was really disappointed with tech support here and on technet forum!
