### ISSUE TITLE
Migration Endpoint - GCC High

### ISSUE THREAD

**Issue by Surf-Solana** [MicrosoftDocs/OfficeDocs-Exchange#586]
Following instructions on migrate : https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes

Verified domain.

Step 4, the connection to imap.gmail.com times out.

**Comment by msdmaguire** [comment]
@Surf-Solana Changes on the G Suite side have made some of our older procedures out of date. We are working to update them. In the meantime, consider contacting Microsoft Fast Track for assistance with your migration. http://fasttrack.microsoft.com/ Hope this helps.
