### ISSUE TITLE
Table Size

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#589]
The table doesn't display correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/Exchange/hybrid-deployment-prerequisites#hybrid-deployment-protocols-ports-and-endpoints)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by chrisda** [comment]
@danmyhre, I looked at the raw markdown for both tables in the topic, and both appeared OK.

If you're talking about the width of the second table, the trick is to scroll horizontally using the left and right arrow keys on your keyboard.
