### ISSUE TITLE
Email field sync

### ISSUE THREAD

**Issue by dandavey** [MicrosoftDocs/OfficeDocs-Exchange#593]
Email field still sync's even when setting (com.microsoft.outlook.ContactSync.EmailAllowed) to false. Ticket raised but no solution yet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@dandavey  Thank you very much for your kind feedback. We recommend that you submit this feedback into Outlook [Uservoice](https://outlook.uservoice.com/). Exchange does not have a UseVoice channel, however, the Outlook team works with Exchange to add features when needed. The team will evaluate and take the appropriate action, as per their schedule. We strongly appreciate you for taking time and sharing your feedback.
