### ISSUE TITLE
"All Address Lists" - pulled from GAL or OGAL/OAB?

### ISSUE THREAD

**Issue by bingoglossy** [MicrosoftDocs/OfficeDocs-Exchange#594]
[Enter feedback here]
When Outlook (Win) is in cached mode and entries under "All Address Lists" are used, are those being pulled from the GAL or the OGAL/OAB?

We still have a huge problem when users use anything but the GAL for picking recipients, with the OAB and Auto-Complete List being the biggest culprits.

We are creating documentation and screencasts of best practices and need to know this definitively.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66817077-ba33-6014-75b6-cdb6b5335ea5
* Version Independent ID: 34572375-a8f3-b16e-b1d3-3fa9d708c8c6
* Content: [Address lists in Exchange Server](https://docs.microsoft.com/en-us/exchange/email-addresses-and-address-books/address-lists/address-lists?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/email-addresses-and-address-books/address-lists/address-lists.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/email-addresses-and-address-books/address-lists/address-lists.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@bingoglossy, you could have knocked me over with a feather, but I disconnected my laptop from WiFi, and when I attempted to browse to All Address Lists or anything under it, I received the following error:

![image](https://user-images.githubusercontent.com/33166947/52678141-6d70ac80-2ee5-11e9-93fa-464e51be7ac4.png)

I'm Outlook 2016 connected to Office 365 where Cached Mode is required, but I can't imagine it's any different for on-premises Exchange server.

You can generate the OAB more frequently by following the steps in this topic: [Change the offline address book generation schedule in Exchange](https://docs.microsoft.com/Exchange/plan-and-deploy/post-installation-tasks/change-oab-generation-schedule). Additional details are available in [Administering the offline address book in Outlook](https://support.microsoft.com/help/841273/administering-the-offline-address-book-in-outlook).

Issues with the Auto-Complete List should come in fits and starts (for example, after a migration or mass conversion of groups from mail-enabled security to distribution or vice-versa). The best you can do is make users aware that those pop-up/drop-down entries aren't authoritative. Additional details are available in [Information about the Outlook AutoComplete list](https://support.microsoft.com/help/841273/administering-the-offline-address-book-in-outlook).
