### ISSUE TITLE
Add in Exchange 2010 SP3 RU26 Support For Windows Server 2012 R2

### ISSUE THREAD

**Issue by r-milne** [MicrosoftDocs/OfficeDocs-Exchange#596]
Now that SP3 RU26 is out, please update the matrix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@r-milne, the information was added in PR #595.

Thanks for the feedback.

**Comment by dariomws306** [comment]
Hi @r-milne @chrisda , are you sure that Exchange 2010 is supported on Windows Server 2012 R2 OS?

Did you try to install it on 2012 R2?

I think it's only supported on 2012 R1 (non R2). You should install SP3 first then latest UR, and I think SP3 install won't work on 2012 R2.

**Comment by r-milne** [comment]
Yup - supported as of Exchange 2010 SP3 RU26.  We need that OS support for the Hybrid Agent.  

Cheers,
Rhoderick

**Comment by dariomws306** [comment]
@r-milne it's true, thank you! I found it:
https://blogs.technet.microsoft.com/exchange/2019/02/05/the-microsoft-hybrid-agent-public-preview/

**Comment by dariomws306** [comment]
Good information for HCW:
https://jaapwesselius.com/2018/12/04/the-version-of-the-client-access-server-selected-is-not-supported/

**Comment by r-milne** [comment]
Yes - I installed this the other week.  May I ask why?

**Comment by dariomws306** [comment]
I am running a project where we need to install Exchange 2010 and I want to be sure that it works on W2012 R2. Thank you!

**Comment by guru-b-prasad** [comment]
Our exchange envoirnment is still running with Exchange 2010 RU22. We have our Domain controller OS 2012 R2 and FFL and DFL 2012 R2. We are not looking to change these, but all we are looking to do is to implement the schema modifcations for 2019.

Since we are adding new classes and attributes, it should not be any issues with lower versions. However, We would like to know if there is any risk to Exchange 2010 RU22 if we upgrade the schema 2019?

**Comment by chrisda** [comment]
@guru-b-prasad, I'm not sure if what you're trying is even possible. If Exchange 2019 Setup detects Exchange 2010 in the AD forest, the process can't continue (at least that was my understanding).
