### ISSUE TITLE
Which Exchange Server need to be upgraded ?

### ISSUE THREAD

**Issue by ninhvuonglinh-linhnv** [MicrosoftDocs/OfficeDocs-Exchange#599]
We have 3 Exchange Server 2013:
* 2 Exchange Mailbox server
* 1 Exchange Client Access server.

In the document above
*The latest Exchange 2013 CU needs to be installed on at least one server running both the Mailbox and Client Access server roles. *
In our context, which is server(s) we need to install the latest Exchange 2013 CU ?? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec121a3-cccf-1164-777e-be5e4dc9d2c5
* Version Independent ID: 37c911be-c56e-8975-260b-6f8ddc497ee9
* Content: [Hybrid Configuration wizard FAQs](https://docs.microsoft.com/en-us/exchange/hybrid-configuration-wizard-faqs)
* Content Source: [Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-configuration-wizard-faqs.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by xuantrai** [comment]
My customer is also got this case. Hope MS guys can give us the final information!

**Comment by TokyoScarab** [comment]
Hello! Thanks for bringing up this question.  The wording of that line in the documentation is a little misleading.  The line is stating that you need to install the CU on at least one of your servers because the update needs to affect at least 1 mailbox and client access role.  So the wording used here would be a condensing of that information.  Just to clarify, in cases where you have these multiple server roles within your Exchange installation, each of these mailbox and client access servers will need updated to ensure a proper CU.  The documentation page linked will be updated to reflect this.

**Comment by scanum** [comment]
PR#686

**Comment by kohei-watanabe-ms** [comment]
Please check one point. For example, if we want to set up a hybrid configuration with Exchange 2016, 
do we need to apply the latest CU to all Exchange servers in the organization, or  apply the latest CU  at least one hybrid server in the organization

For example In case there are  three exchange server 2016, can I apply the latest CU to only one server?

As long as I look at the following URL, it seems that we need to apply the latest CU to all Exchange servers in our organization.

https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites

=====
On-premises Exchange releases: Hybrid deployments require the latest cumulative update or update 
rollup available for the version of Exchange you have installed in your on-premises organization. 
If you can't install the latest cumulative update or update rollup, the immediately previous release is also supported. 
Older cumulative updates or update rollups aren't supported.
=====

As long as I look at the URL below, it seems that we need to apply the latest CU to at least one Exchange Server in our organization.

https://docs.microsoft.com/en-us/exchange/hybrid-configuration-wizard-faqs

=====
Exchange 2016: The latest release of Exchange 2016 needs to be installed on at least one server running the Mailbox server role.
=====

I think that the preparation time for the migration will be completely different.

**Comment by michelderooij** [comment]
> As long as I look at the following URL, it seems that we need to apply the latest CU to all Exchange servers in our organization.

Apart from the fact that there is no such thing as "Hybrid server" and keeping only those "Hybrid servers" current not making much sense, the statement "at least one server" applies to where you should run the Hybrid Configuration wizard. Overall, for Hybrid you need to keep the environment current or n-1.
