### ISSUE TITLE
SMTP Relay without TLS

### ISSUE THREAD

**Issue by daxxial** [MicrosoftDocs/OfficeDocs-Exchange#600]
In the 3rd option of this article TLS is defined as optional. However, when attempting to configure the connector without TLS we are met with the following message "You did not select any restriction. If you don‎'t want to apply any restriction to emails from your partner, you do not need to create this connector". Is TLS no longer optional for the SMTP Relay option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@daxxial, you used **From your organization's email server** and **To Office 365**? I used those values and That's what the topic recommends, and I was able to go all the way through without receiving an error.

**Comment by 4rtorias** [comment]
According to this, TLS is required for SMTP Relay:

https://blogs.technet.microsoft.com/exchange/2016/03/29/important-notice-for-office-365-email-customers-who-have-configured-connectors/

**Comment by chrisda** [comment]
@daxxial, @4rtorias, according to the blog post, TLS is one of the required options. The other is to configure the sender's email domain as an accepted domain in your Office 365 organization.

And, according to the blog post, TLS is basically required in all hybrid environments if you want the following functionality:

- Your organization needs to send non-delivery reports (also known as NDRs or bounce messages) to internet recipients and needs to relay them through Office 365.

- You need to send emails on behalf of domains that do not belong to your organization.

- Your on-premises users have forwarding rules configured, and messages need to be relayed through Office 365.

**Comment by scanum** [comment]
@daxxial Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
