### ISSUE TITLE
WRONG CODE

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/OfficeDocs-Exchange#601]
Should be Get-RemoteMailbox -resultsize unlimited  | ForEach { Get-AdUser -Identity $_.Guid | Set-ADObject -Replace @{msExchRecipientDisplayType=-1073741818}}

Note the -resultsize unlimited is VERY IMPORTANT!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions#EnableACLs)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by chrisda** [comment]
OK. Added.
