### ISSUE TITLE
Unknown AD forest functional level Windows Server 2008 R2 SP1 and Windows Server 2008 R2 SP2

### ISSUE THREAD

**Issue by Arno33** [MicrosoftDocs/OfficeDocs-Exchange#602]
In your matrix about Supported Active Directory environments / AD forest functional level you are use forest functional levels that I don’t know. I know about forest functional levels like Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 and Windows Server 2016 but not about Windows Server 2008 R2 SP1 and Windows Server 2008 R2 SP2 with Service Pack.

Here in this documentation there is the Active Directory forest functional level: Windows Server 2008 R2 or higher.
https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016#network-and-directory-servers-1

**Comment by chrisda** [comment]
@Arno33, yes, it was a simple copy/paste error from the previous table. I fixed it. 

Thanks for the feedback.
