### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by jacobyoby** [MicrosoftDocs/OfficeDocs-Exchange#604]
PS C:\Users\jacobd&gt; $mbx.EmailAddresses.Item(1) -="eum:tsmith@contoso.com;phone-context=MyDialPlan.contoso.com"
Cannot convert value "SIP:michaels@smh.org" to type "System.Int32". Error: "Input string was not in a correct format."
At line:1 char:1
+ $mbx.EmailAddresses.Item(1) -="eum:tsmith@contoso.com;phone-context=M ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355b8652-d797-32f6-aa41-a1f7f3cc557a
* Version Independent ID: d2efc4e7-1a3e-01b2-d3bf-bc2fbfc273f1
* Content: [Remove a SIP address](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-voice-mail/remove-sip-address)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-voice-mail/remove-sip-address.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-voice-mail/remove-sip-address.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by dplotnikov** [comment]
Hello @jacobyoby I've made a pull request to the repo with updated PS example and I confirmed it's okay on my end now
