### ISSUE TITLE
Retention tag(s) for personal items 

### ISSUE THREAD

**Issue by skarai** [MicrosoftDocs/OfficeDocs-Exchange#605]
Is there a way to create a retention tag for (i.e. notes) only? This in light of a general delete policy for email items past a certain hold period which in some cases should retain notes over a longer period of time and/or in other case notes should be deleted before email items reach their permanent deletion point.

**Comment by TokyoScarab** [comment]
Hello!  I have gone over your question and I believe the information on [this](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/retention-tags-and-policies) page should shed some light on this.  If not, feel free to comment back here with more information on your specific case.  For a faster and more direct communication solution to this issue, you can always contact [Microsoft Support](https://support.microsoft.com/en-us). Thanks!
