### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by DCAggar** [MicrosoftDocs/OfficeDocs-Exchange#608]
Forcing a user to create a Github account to leave any sort of feedback is forced and terrible. I created an account for the purpose of letting you know it's a crap thing to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7684ef8f-2f6d-7c73-fddb-19b94096e82a
* Version Independent ID: 9910c94c-df87-74c1-fa32-e153857a64ab
* Content: [Run a message trace and view the results in the Exchange admin center](https://docs.microsoft.com/en-us/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results)
* Content Source: [Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/trace-an-email-message/run-a-message-trace-and-view-results.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
OK. Thanks for the feedback. If it's any consolation, you can also use that GitHub account to make corrections to topics. Your updates need to be approved before they go live, but you can now easily correct any mistakes that you see.
