### ISSUE TITLE
SSD Filesystem

### ISSUE THREAD

**Issue by makauf** [MicrosoftDocs/OfficeDocs-Exchange#610]
Is it possible that the script does not utilize the PA for the formatted filesystem of the SSD drives?

PA says:
Whether Traditional or Solid-State, all disks that houses an Exchange data are formatted with ReFS (with the integrity feature disabled)

or do i get that screenshot wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9143a35-a7db-43f6-6a76-47a5ea08fc91
* Version Independent ID: 0cbd5f28-45fb-b438-0510-8958816d2995
* Content: [MetaCacheDatabase (MCDB) setup](https://docs.microsoft.com/en-us/Exchange/high-availability/database-availability-groups/metacachedatabase-setup?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/high-availability/database-availability-groups/MetaCacheDatabase-setup.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/database-availability-groups/MetaCacheDatabase-setup.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lusassl-msft** [comment]
MCDB SSD drives will be NTFS formated which is expected / by-design in this case.

**Comment by makauf** [comment]
well, but should not the script format the SSDs with ReFS to meet the preferred architecture? Because there must be some reason ReFS is preferred for exchange data - and not NTFS. (Yes i know, almost none impact as far as i have tested and reviewed different blog posts about NTFS <-> ReFS with Exchange)..

**Comment by toklima** [comment]
The guidance you refer to is accurate for E16 and referred to primary EDBs that were stored on either HDD or SSD (i.e. when MCDB did not exist). E19 is supported on both ReFS and NTFS and as pointed out by Lukas, the script will format the MCDB volumes with NTFS by design. I will see if we can disambiguate what's written in the PA.

**Comment by msdmaguire** [comment]
@makauf Thank you for your feedback on the article. I hope this thread has answered your questions.
