### ISSUE TITLE
Ability to rename a policy

### ISSUE THREAD

**Issue by bazookadaver** [MicrosoftDocs/OfficeDocs-Exchange#611]
Would love for the ability to rename a policy.  We created a test policy that ended up being used as the default.  While not a big deal, we'd love to run a quick command to rename the policy to something more appropriate. 

Thanks for everything you've created here.

**Comment by scanum** [comment]
@bazookadaver Thank you very much for your kind feedback. We recommend that you submit this feedback into Outlook [Uservoice](https://outlook.uservoice.com/). Exchange does not have a UseVoice channel, however, the Outlook team works with Exchange to add features when needed. The team will evaluate and take the appropriate action, as per their schedule. We strongly appreciate you for taking time and sharing your feedback.
