### ISSUE TITLE
Databases Maxed out at 5

### ISSUE THREAD

**Issue by mistyq** [MicrosoftDocs/OfficeDocs-Exchange#612]
We have Exchange 2010 standard and 5 databases already so cannot mount anymore databases. Can this user be created in an already existing database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by TokyoScarab** [comment]
Hello!  Thank you for posting this question.  From what this sounds like, this is an issue better suited for [Microsoft Support](https://support.microsoft.com/en-us/contactus/).  If you find that support wasn't able to address this issue or they did and something pertaining to this would warrant an update in documentation, please leave another comment. Thanks!
