### ISSUE TITLE
Invalid prerequisites are listed for Window 2019  for Mailbox Installation 

### ISSUE THREAD

**Issue by pdhewaju** [MicrosoftDocs/OfficeDocs-Exchange#613]
Instead of installing the software of 
Visual C++ Redistributable Package for Visual Studio 2013.
it need to be change for 
Visual C++ Redistributable Package for Visual Studio 2012

for the mailbox installation on exchange 2019

**Comment by RussC19** [comment]
@AndreaBarr 

Edited as per https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/640
