### ISSUE TITLE
Invalid prerequisites are listed for Window 2019 for Mailbox Installation 

### ISSUE THREAD

**Issue by pdhewaju** [MicrosoftDocs/OfficeDocs-Exchange#614]
Instead of installing the software of
Visual C++ Redistributable Package for Visual Studio 2013.
it need to be change for
Visual C++ Redistributable Package for Visual Studio 2012

for the mailbox installation on exchange 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites, Exchange 2019 system requirements, Exchange 2019 requirements](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prerequisites?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lusassl-msft** [comment]
Visual C++ Redistributable Packages for Visual Studio 2012 + 2013 is required on Mailbox role as described here:
https://support.microsoft.com/en-us/help/4295081/add-a-new-visual-c-prerequisite-to-exchange-for-third-party-files
https://blogs.technet.microsoft.com/exchange/2018/10/16/released-october-2018-quarterly-exchange-updates/

Visual C++ Redistributable Package for Visual Studio 2012 only is required on Edge transport server role

**Comment by pdhewaju** [comment]
Hi there,

I was only able to install Exchange 2019 Mailbox  on Server 2019 after removing VS 2013 and VS 2012.
while installing VS 2013 i had this error.
![image](https://user-images.githubusercontent.com/18259080/53470011-4b039500-3a88-11e9-99f5-fb85871cc4b7.png)

**Comment by lindspea** [comment]
@pdhewaju thank you for pointing this out and for your valuable contribution in helping improve MS docs.  Please confirm if this issue has been resolved or if there is anything that needs to be changed or added to the document.

**Comment by kenwith** [comment]
@pdhewaju and @lusassl-msft -- we aren't sure what to do with this topic and it seems there might be conflicting use cases where something works for one but not the other. We are going to leave the article as-is for now but please feel free to re-open this issue or better yet if you can submit a Pull Request if you feel strongly the article needs to be updated. For particular cases that work or don't work we would recommend a call to support for your environment. If you do hear the article needs something updated please let us know.
