### ISSUE TITLE
Domain key

### ISSUE THREAD

**Issue by MacPhistopt** [MicrosoftDocs/OfficeDocs-Exchange#615]
Under MX record you provide as example:
&lt;domainKey&gt;-com.mail.protection.outlook.com

Consider rephrasing this example as the domain key should also include the DNS suffix for the custom domain

"&lt;domainKey&gt;.mail.protection.outlook.com
For example, the domain contoso.com should have the MX record contoso-com.mail.protection.outlook.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb636ab-88a0-56dd-b5c3-95dedafb947a
* Version Independent ID: aaa648c5-0a9f-5989-d0f7-8babe9712228
* Content: [Manage all mailboxes and mail flow using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mailboxes-with-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mailboxes-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mailboxes-with-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @tirich
* Microsoft Alias: **tirich**

**Comment by lindspea** [comment]
@scanum @AndreaBarr  please assign to me.

**Comment by lindspea** [comment]
@MacPhistopt Thank you for pointing this out and for helping improve MS docs.  Just to be clear, the only wording to be changed/removed is the first 'com' after <domainKey>, from this example?
<domainKey>-com.mail.protection.outlook.com

**Comment by MacPhistopt** [comment]
@Lindsay

    yes that is correct.
    thank you for reaching back about this

    Citando Lindsay <notifications@github.com>:
>
> @MacPhistopt[1] Thank you for pointing this out and for helping  
> improve MS docs. Just to be clear, the only wording to be  
> changed/removed is the first 'com' after , from this example?
>    -com.mail.protection.outlook.com
>
> —
>    You are receiving this because you were mentioned.
>    Reply to this email directly, view it on GitHub[2], or mute the thread[3].
>




Ligações:
---------
[1] https://github.com/MacPhistopt
[2]  
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/615#issuecomment-465155541
[3]

**Comment by lindspea** [comment]
@AndreaBarr  @scanum this can be closed thank you.
