### ISSUE TITLE
location of  audit logs

### ISSUE THREAD

**Issue by ralfdo** [MicrosoftDocs/OfficeDocs-Exchange#620]
It  would  be good to inform our customer about  the facts, where these Audit  logs are normally  written, so that they  can be retrieved. This  helps in troubleshooting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48638216-9e8d-81ad-9e87-19b878f36ced
* Version Independent ID: 3561ef40-f0af-c484-1df0-9b4f0c3aa57e
* Content: [Export mailbox audit logs](https://docs.microsoft.com/en-us/Exchange/security-and-compliance/exchange-auditing-reports/export-mailbox-audit-logs)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/export-mailbox-audit-logs.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/exchange-auditing-reports/export-mailbox-audit-logs.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@ralfdo Please click the Edit button at the top of the article and make any revisions to the topic and then submit a pull request, particularly what troubleshooting issues can be resolved by know the location of the admin audit log.

**Comment by markjjo** [comment]
I should have said "mailbox audit logs".
