### ISSUE TITLE
Why is the button for Delivery Reports even available still??

### ISSUE THREAD

**Issue by ejacobsen-glofin** [MicrosoftDocs/OfficeDocs-Exchange#622]
Confusing for end users to have a button about message details, only to get redirected to a page telling you the feature is no longer available. Remove the button! Or at least show on the redirect that it's been replaced by message trace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707d2c66-f9d8-7ac2-55c8-1ccfbe966bf6
* Version Independent ID: 3dc90f07-c2bb-9f37-82c2-a713f0b8f27c
* Content: [What happened to delivery reports in Office 365?](https://docs.microsoft.com/en-us/exchange/monitoring/what-happened-to-delivery-reports-in-office-365)
* Content Source: [Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/monitoring/what-happened-to-delivery-reports-in-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@ejacobsen-glofin Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
