### ISSUE TITLE
Default folders

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/OfficeDocs-Exchange#623]
Can you please add a link to the "default folders that support tags" page on the left nav menu? This one: https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/default-folders

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed28361e-0f38-bd97-1153-0295e19ddd8b
* Version Independent ID: 8342198a-1806-9f37-fd59-4fec2b417a67
* Content: [Retention tags and retention policies in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mrm/retention-tags-and-retention-policies?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mrm/retention-tags-and-retention-policies.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mrm/retention-tags-and-retention-policies.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
@chrisda How do we add that into the docs? (left panel item menu?)

**Comment by chrisda** [comment]
@j0rt3g4 the left nav is the table of contents (TOC). The TOC for Exchange Server is this file: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/servertoc/toc.md

However, the request (taken literally) is to add an **Exchange Online** topic into the Exchange Server content area. Not good for a variety of reasons. Don't do that.

But, the spirit of the request is to create a new on-premises Exchange Server version of that topic. That is certainly worth consideration.

**Comment by scanum** [comment]
@michevnew Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
