### ISSUE TITLE
Port 587 appears not to be functional

### ISSUE THREAD

**Issue by GustavBrock** [MicrosoftDocs/OfficeDocs-Exchange#636]
While a connection via port 25 works flawlessly, I cannot get through using port 587.
I test with basic code like this:
```
Dim Message As CDO.Message

Set Message = New CDO.Message

Message.Subject = "Test mail to me, sent " & CStr(Now) & "."
Message.From = "myname@mydomain.dk"
Message.To = "someone@externaldomain.dk"
Message.CC = ""
Message.TextBody = "This is yet a test."

Dim Configuration As New CDO.Configuration

Call Configuration.Load(CdoConfigSource.cdoDefaults)

Configuration.Fields.Item(CdoConfiguration.cdoSendUsingMethod).Value = CdoSendUsing.cdoSendUsingPort
Configuration.Fields.Item(CdoConfiguration.cdoSMTPServer) = "smtp.office365.com"

' This works:
Configuration.Fields.Item(CdoConfiguration.cdoSMTPServerPort) = 25

' This fails with:
'	Run-time error '-2147220973 (80040213)': 
'	The transport couldn't establish a connection to the server.
Configuration.Fields.Item(CdoConfiguration.cdoSMTPServerPort) = 587

Configuration.Fields.Item(CdoConfiguration.cdoSMTPAuthenticate) = CdoProtocolsAuthentication.cdoBasic
Configuration.Fields.Item(CdoConfiguration.cdoSendUserName) = "myname@mydomain.dk"
Configuration.Fields.Item(CdoConfiguration.cdoSendPassword) = "mypassword"
Configuration.Fields.Item(CdoConfiguration.cdoSMTPUseSSL) = True
Configuration.Fields.Update

Set Message.Configuration = Configuration

Message.Send
``` 
Port 587 is not blocked. And I have tried turning the firewall off; still no cigar.
So, **is using the Direct method via port 587 wishful thinking** only?

Also, sending mail in a similar manner using smtp.gmail.com and port 465 works.

**Comment by scanum** [comment]
@GustavBrock  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
