### ISSUE TITLE
Missed call email notifications cannot be customised

### ISSUE THREAD

**Issue by marc-fom** [MicrosoftDocs/OfficeDocs-Exchange#637]
We have added custom branding to UM activation and voice message reception emails but can't do the same for missed call notification email. Can it be done at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd485b22-ac06-0efc-c733-65e8bff62e4d
* Version Independent ID: 79054dc7-dc7b-8e7a-4920-23ce7d5ce7dc
* Content: [Enable missed call notifications for a user](https://docs.microsoft.com/en-us/exchange/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-missed-call-notifications)
* Content Source: [Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-missed-call-notifications.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/voice-mail-unified-messaging/set-up-client-voice-mail-features/enable-missed-call-notifications.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @tonysmit
* Microsoft Alias: **tonysmit**

**Comment by lindspea** [comment]
@marc-fom I will have an answer for you once I have done some investigating.  Thanks for reaching out.

**Comment by scanum** [comment]
@marc-fom  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
