### ISSUE TITLE
I do not see a TOOLS section from my EAC, looking for the ExBPA

### ISSUE THREAD

**Issue by toddellisn** [MicrosoftDocs/OfficeDocs-Exchange#645]
Have these tools been removed or are they only accessible to certain Office 365 customers?  
Is the ExBPA accessible another way?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b8d4e5-6aae-5174-d924-b1d550d534b5
* Version Independent ID: d9b4b71c-b5d0-2462-8c44-9b3d6a4d4dd0
* Content: [About the Office 365 Best Practices Analyzer for Exchange Server](https://docs.microsoft.com/en-us/exchange/about-the-office-365-best-practices-analyzer-for-exchange-server#next-steps)
* Content Source: [Exchange/ExchangeHybrid/about-the-office-365-best-practices-analyzer-for-exchange-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/about-the-office-365-best-practices-analyzer-for-exchange-server.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
@toddellisn I will have answers to your questions shortly.  Thank you for reaching out.

**Comment by scanum** [comment]
@toddellisn  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
