### ISSUE TITLE
Update doc - typo

### ISSUE THREAD

**Issue by hdeanmurray** [MicrosoftDocs/OfficeDocs-Exchange#652]
In step 6 change the second occurrence of 
Set-Group -Identity "Accounting Group" -SeniorityIndex 25 
to 
Change Set-Group -Identity "Administrative Group" -SeniorityIndex 25.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe9eef8a-3acf-ed01-ddec-c1bc1f0a7f73
* Version Independent ID: f6c9ef82-8b91-2b3c-ec21-8675a3f25386
* Content: [Enable or disable hierarchical address books in Exchange Online](https://docs.microsoft.com/en-us/exchange/address-books/hierarchical-address-books/enable-or-disable-hierarchical-address-books)
* Content Source: [Exchange/ExchangeOnline/address-books/hierarchical-address-books/enable-or-disable-hierarchical-address-books.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/address-books/hierarchical-address-books/enable-or-disable-hierarchical-address-books.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hdeanmurray, OK. Done. But remember, you can, too. See the instructions here:  https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md
