### ISSUE TITLE
Is it me?

### ISSUE THREAD

**Issue by susan3702** [MicrosoftDocs/OfficeDocs-Exchange#653]
I really don’t know what to say. I have requested support more times from Microsoft in the last year than I have my whole life, and uncannily every single time I’m left more confused, in more dizzy circles than before. I can’t get a straight answer to what I’m connected to or what my server is or even what a server is or what any of this means. I thought I had a plain email inbox - seriously, that’s how stupid I am. I try to teach myself these things and it’s like trying to read Chinese. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f940132d-a51f-3c8e-2af3-e32832968cd0
* Version Independent ID: 49df53e3-3ae7-2afc-055f-dd6cc6a2c249
* Content: [Antispam and antimalware protection in Exchange Server](https://docs.microsoft.com/en-us/Exchange/antispam-and-antimalware/antispam-and-antimalware?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/antispam-and-antimalware.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/antispam-and-antimalware.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@susan3702  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs, or if there is anything specific that needs to be clarified.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

Thanks,

Manuela
