### ISSUE TITLE
Incomplete steps

### ISSUE THREAD

**Issue by Smartboss88** [MicrosoftDocs/OfficeDocs-Exchange#654]
Need to add acs auth server in addition to evosts.

Also at step one when creating evosts auth server, need to add type azuread.

Step 1:

Run the following in EXO Shell Get-AcceptedDomain | fl Domainname,InitialDomain

 

Step 2:

Replace &lt;contoso&gt;.onmicrosoft.com with whatever domain is marked as IntialDomain True from step one and run this from the on-premises server Exchange Management Shell

New-AuthServer -Name EvoSts -Type AzureAD -AuthMetadataUrl "https://login.windows.net/&lt;contoso&gt;.onmicrosoft.com/federationmetadata/2007-06/federationmetadata.xml"

 

Step3:

From AAD Shell

$x = get-MSOLServicePrincipal - -AppPrincipalId 00000002-0000-0ff1-ce00-00000000000

$x.ServicePrincipalnames.Add(“https://mail.contoso.com/”)

Set-MSOLServicePrincipal -AppPrincipalId 00000002-0000-0ff1-ce00-000000000000 -ServicePrincipalNames $x.ServicePrincipalNames

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 484887bf-a423-cb36-d8d1-712858e746bb
* Version Independent ID: c1df772a-5b5c-79d0-24fc-c89a09059497
* Content: [Configure OAuth authentication between Exchange and Exchange Online](https://docs.microsoft.com/en-us/exchange/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-oauth-authentication-between-exchange-and-exchange-online-organizations-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by lindspea** [comment]
@Smartboss88 thank you for pointing this out.  Will look into it and have the changes implemented soonest.

**Comment by lindspea** [comment]
@j0rt3g4

**Comment by j0rt3g4** [comment]
@lindspea I've addressed this issue and another really old issue on the documentation that can be found here: #753 I had to do the whole implementation to figure out all those errors that the documentation had.

Please feel free to add the author and reference the PR #754

**Comment by tweekerz** [comment]
@lindspea @j0rt3g4 @scanum 
I had already fixed this and i have submited a new pull request to revert the documentation back to the correct steps as they were updated incorrectly. I also cleaned up the MD. https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/786 is the new pull request.

**Comment by scanum** [comment]
@Smartboss88 Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
