### ISSUE TITLE
Typo: "hadow redundancy"

### ISSUE THREAD

**Issue by h-david-a** [MicrosoftDocs/OfficeDocs-Exchange#655]
Safety Net takes over some responsibility from shadow redundancy in DAG environments: hadow redundancy 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 006ae2b1-446d-bf91-54ea-189d3203ff5f
* Version Independent ID: 07e36db2-e105-6ae9-ef1f-257eff033473
* Content: [Safety Net in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/transport-high-availability/safety-net?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-high-availability/safety-net.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-high-availability/safety-net.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@h-david-a, I fixed it, but so can you. See https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.
