### ISSUE TITLE
-CloudServicesMailEnabled parameter don't exist in Exchange 2010

### ISSUE THREAD

**Issue by jiuq01** [MicrosoftDocs/OfficeDocs-Exchange#658]
Please add the powershell when the hybrid Exchange servers are in 2010 version; because the -CloudServicesMailEnabled parameter in New-SendConnector command in the Exchange 2010 powershell don't exist. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 498774ba-06b8-5087-f884-bab065225d63
* Version Independent ID: a54b404b-0ade-45e8-3282-402c1a3bb0d0
* Content: [Set up connectors to route mail between Office 365 and your own email servers](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/set-up-connectors-to-route-mail.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jiuq01, OK. Done. Thanks for the feedback.
