### ISSUE TITLE
Was unable to migrate exchange online public calendar to Groups. 

### ISSUE THREAD

**Issue by minhho90** [MicrosoftDocs/OfficeDocs-Exchange#659]
I did everything on this list but the group calendar is not updated. Can anyone reach out to me to assist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a64bc33-37b2-5448-76b4-ec6bdb7a5f5a
* Version Independent ID: 1da420e5-5ad8-3484-5a3b-5f1d44ca97f0
* Content: [Use batch migration to migrate Exchange Online public folders to Office 365 Groups](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-exchange-online-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-exchange-online-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-exchange-online-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@minhho90 Sorry to hear about your migration issue. Please open a support ticket and a support engineer can help you troubleshoot the issue. https://support.microsoft.com/en-us/hub/4343728/support-for-business
