### ISSUE TITLE
Setting Encryption Protocol to TLS 1.2 - Integration (Communication) between OOS 2018 (NOV) and Exchange Server 2019

### ISSUE THREAD

**Issue by shmohajerani** [MicrosoftDocs/OfficeDocs-Exchange#662]
On Subject of Integration between Office Online Server 2018 NOV and Exchange Server 2019, OOS wont be able to communicate with Exchange because there are of some mismatches in choosing Encryption Protocols . The solution is to set both on using TLS 1.2 (which is the most secure protocol here).

I can confirm that opposite of what is claimed in documents when it comes to communication between OOS and Exchange Server 2019 (Installed on Windows Server  2019), it seems Exchange DOES NOT Automatically use TLS 1.2 in negotiation,, I tested it by I locking my OOS to use only TLS 1.2 and exchange couldn't communicate with it, Exchange was basically using TLS 1.0 and it would go to SSL by default (no TLS 1.2 packets was traced between them).

I had to lock both machines to use only TLS 1.2 (Disable: SSL 2.0, SSL 3.0, TLS 1.1 and TLS 1.0) to get them integrated.

You can test it for yourself, [Run it through wireshark and set the filter for IP.Addr & ssl.record.version if in doubt.]

Solution (which needed to be added to this page), is to suggest, setting the following registry keys:

Disable TLS 1.0

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0]
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
Disable TLS 1.1:

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1]
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
Disable SSL 2.0:

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
Disable SSL 3.0

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Client]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server]
"DisabledByDefault"=dword:00000001
"Enabled"=dword:00000000
Enable TLS 1.2:

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2]
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Server]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
Enable Strong Encryption .NETFRAMWORK

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001

  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e12237-20cc-007c-540b-4544269ec6a9
* Version Independent ID: 08d3e012-d918-c625-3d6c-d827636f34b5
* Content: [Install Office Online Server in an Exchange organization](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/install-office-online-server?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@shmohajerani thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Peterkr-SOA** [comment]
Thanks @shmohajerani, that solved my issue after trying to troubleshoot it for more than a day.
Would be helpful if those instructions were published in the docs article...
