### ISSUE TITLE
Inbound on port 25

### ISSUE THREAD

**Issue by albourg34** [MicrosoftDocs/OfficeDocs-Exchange#664]
I understand the outbound port 25 (smtp send), I don't understand why the inbound on port 25 from the internet is needed. It is the best way to be blacklisted for spam abuse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c06c27d-22fa-911b-db81-233ee4a16529
* Version Independent ID: c9136fcc-9cd7-d36a-1097-f3b82265f68a
* Content: [Network ports for clients and mail flow in Exchange](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deployment-ref/network-ports?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deployment-ref/network-ports.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deployment-ref/network-ports.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@albourg34, are you talking about clients or servers? Inbound TCP/25 is required on any internet-facing email server (or security appliance, or device) to receive anonymous email from the internet. The messages would still be subject to (possibly blocked or quarantined by) anti-spam/anti-malware/anti-virus filtering.

**Comment by albourg34** [comment]
I don't agree with anonumous e-mail, it is the open door for sending spam.
SMTP allowed from inside the company to send using outlook, OK. But not from the internet to connect to the exchange server. Why does exchange need that?

**Comment by chrisda** [comment]
@albourg34, do you have an alternative suggestion? If not inbound TCP/25 to your internet-facing email server, how do you get email from the internet to your email server as shown in the diagrams in the topic? You certainly can't restrict by source IP address (how can you specify where any/all email on the internet is coming from?) and you have to use TCP/25 (how else could internet email server send email to you)?

Exchange uses Receive connectors to listen for SMTP connections from other email servers. In particular, the default connector named "Default Frontend \<Servername\> on a Mailbox server is configured to listen for anonymous SMTP connections from any source. Furthermore, the permissions on the Receive connector do not allow anonymous clients/servers to relay through this connector (the ms-Exch-Accept-Any-Recipient permission is not assigned to the Anonymous users permission group).

These concepts are all explained in the topics:

- [Receive connectors](https://docs.microsoft.com/Exchange/mail-flow/connectors/receive-connectors)

- [Allow anonymous relay on Exchange servers](https://docs.microsoft.com/Exchange/mail-flow/connectors/allow-anonymous-relay)
