### ISSUE TITLE
OAuth2ClientProfileEnabled $true | Disable Basic Auth

### ISSUE THREAD

**Issue by geoC42** [MicrosoftDocs/OfficeDocs-Exchange#667]
Documentation states:

Run this command to enable modern authentication connections (disable basic authentication connections) to Exchange Online by Outlook 2013 or later clients:
Set-OrganizationConfig -OAuth2ClientProfileEnabled $true

My understanding is that this command only enabled the OAuth2 provider but does NOT disable basic auth.   if this is correct then the statement in parentheses confuses the issue.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-us/Exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online?redirectSourcePath=%252farticle%252f58018196-f918-49cd-8238-56f57f38d662#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@geoC42, you are correct. A similar point was raised in Issue #408, and I updated the text as you described.

Thanks for the feedback.
