### ISSUE TITLE
Mistyping on Organizational limits subtitle (configuration)

### ISSUE THREAD

**Issue by mustafayevtural** [MicrosoftDocs/OfficeDocs-Exchange#669]
Cmdlets: New-TransportRule, Set-TransportRule 
Parameter: AttachmentSizeOver
On ECP configuration analog there should be &gt;&gt; Apply this rule if &gt; Has Attachement that's larger than or equal to and enter a value in kilobytes (KB). (NOT Apply this rule if &gt; The message &gt; size is greater than or equal to, and enter a value in kilobytes (KB).)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a512e6f-47ab-f785-a792-ef82a552c50f
* Version Independent ID: 16869db1-342d-13f2-ce24-0e13a49ec68d
* Content: [Message size limits in Exchange Server](https://docs.microsoft.com/en-us/exchange/mail-flow/message-size-limits?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/message-size-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/message-size-limits.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@mustafayevtural, you are correct. I changed the line "Apply this rule if > **The message** > size is greater than or equal to, and enter a value in kilobytes (KB)" to Apply this rule if > **Any attachment** > size is greater than or equal to, and enter a value in kilobytes (KB)".

In the future, you, too can make these types of changes to topics. For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.
