### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by Dave247** [MicrosoftDocs/OfficeDocs-Exchange#671]
There is a broken URL link for the "Install Office Online Server in an Exchange organization" topic.
Instead the display text reads,
`[Install Office Online Server in an Exchange organization](../plan-and-deploy/install-office-online-server.md`

The problem originated from a previous commit here on line 29,
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/commit/1d05b9142f031339f70df89423b2f2f56cef6cbe#diff-4be55cac7d9a2b561878db6ef3d44100R29

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9882eda8-450a-d9a8-1348-25c906ee46bf
* Version Independent ID: 06740c7b-d017-b9d7-da34-6418b49dcfbf
* Content: [Clients and mobile in Exchange Server](https://docs.microsoft.com/en-us/exchange/clients/clients?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/clients/clients.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/clients.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@Dave247, the issue was caused by a missing trailing ) at the end of the link. I fixed it.

Thanks for the feedback.

**Comment by Dave247** [comment]
Happy to help.
