### ISSUE TITLE
So, OWA has to be 2013 or newer to work with ADFS 4.0 (2016)?

### ISSUE THREAD

**Issue by songyen20** [MicrosoftDocs/OfficeDocs-Exchange#672]
So, OWA has to be 2013 or newer to work with ADFS 4.0 (2016)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8814165c-8438-b93f-3f23-4ad5e03b6373
* Version Independent ID: 34b519a0-8d64-8036-914c-3df7948f8979
* Content: [Using AD FS claims-based authentication with Outlook Web App and EAC](https://docs.microsoft.com/en-us/exchange/using-ad-fs-claims-based-authentication-with-outlook-web-app-and-eac-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/using-ad-fs-claims-based-authentication-with-outlook-web-app-and-eac-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/using-ad-fs-claims-based-authentication-with-outlook-web-app-and-eac-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@songyen20 "Co-Existing with Other Versions of Exchange
It's possible to use AD FS authentication for Outlook Web App and EAC when you have more than one version of Exchange deployed in your organization. This scenario is only supported for Exchange 2010 and Exchange 2013 deployments, and only if all clients are connecting through the Exchange 2013 servers and those Exchange 2013 servers have been configured for AD FS authentication."

**Comment by scanum** [comment]
@songyen20  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Narulans** [comment]
Hi,

Can you please confirm if the same is applicable for hybrid ( w/ Exchange 2010). Alll Users and shared mailboxes on O365, only application mailboxes are left in On-Prem.
