### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by lukewelden** [MicrosoftDocs/OfficeDocs-Exchange#677]
This article was great! Very easy to follow, this was my first time setting up an SMTP Relay server and the above article helped me greatly. Thanks Guys!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e73bb3c6-ab71-066f-18e8-f0726cebf9d2
* Version Independent ID: 16e49af3-9980-d928-7667-ee8f5e07c487
* Content: [How to configure IIS for relay with Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @SuPotter
* Microsoft Alias: **supotter**

**Comment by scanum** [comment]
@lukewelden We really appreciate your feedback! Glad our content meets your expectations. Thank you.
