### ISSUE TITLE
Mapping rule dependencies and effectiveness 

### ISSUE THREAD

**Issue by thezedwards** [MicrosoftDocs/OfficeDocs-Exchange#68]
Thanks much for all this amazing documentation! :D I'm trying to figure out a high-level problem and after going through a bunch of these docs here, I still don't exactly know the answer. Basically, let's say a .gov or .org entity was using Exchange 2016 or a stack that included Outlook. Is it possible to either:
1.) Create an importable rule so that if anyemail@abc.org is added to an Outlook account, no additional email accounts can be added to that same account.
2.) Create an importable rule to prevent someone with an Outlook account (or potentially another MS tool) that has anyemail@abc.org domain from being able to download the email locally, switch the sender email and then forward through a different SMPT account. 

From a high-level, I'm trying to figure out auditability of locally-downloaded and then re-forwarded emails via options to change sender accounts, and largely trying to figure out what rules allow blocking of scenarios like that as an internal security/accountability measure. 

Is there some chart or way you could help me understand how rules propagate across the mail ecosystem and/or how Enterprise Exchange can create rules to facilitate that 1-domain restriction described above? Thanks again for the time and opportunity to engage with your great documentation! cheers~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d29e4f-dd0c-3ea2-13fb-5077b83b946b
* Version Independent ID: f2580bd9-66b9-52f4-6335-42d5ee08d457
* Content: [Exchange 2016 architecture](https://docs.microsoft.com/en-us/exchange/architecture/architecture)
* Content Source: [Exchange/ExchangeServer/architecture/architecture.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/architecture.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dstrome** [comment]
hi @thezedwards ,

Thanks for your question. I believe the best option to get an answer to your question is to post it to the Exchange Server forums on the Office TechCenter here - https://social.technet.microsoft.com/Forums/office/en-US/home?category=exchangeserver. Many people, including Exchange MVPs, monitor these forums and should be able to help answer this for you.

**Comment by thezedwards** [comment]
Thank you very much, David! I'll post that question there and future issues as well. Much appreciated!
