### ISSUE TITLE
Please research how SPF works and correct this article

### ISSUE THREAD

**Issue by dajones70** [MicrosoftDocs/OfficeDocs-Exchange#682]
The SPF record is based on the envelope-from domain (SMTP MAIL FROM).  See https://tools.ietf.org/html/rfc7208#section-2.4 .
The SPF record tells receiving Internet edge mail servers approved sources of senders for the envelope-from domain.  In scenario 1, the outbound Internet edge delivery is Office 365 so all that is needed is the normal "include:spf.protection.outlook.com".  The red line mail flow above should never have your own envelope-from domain.  That mail should originate inside Office 365 (webmail and Outlook) and flow in the direction of the green line.
https://blog.returnpath.com/how-to-explain-spf-in-plain-english/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@dajones70, yeesh. You're right. It's surprising that no one ever called that out.

Clearly, the third-party filtering service isn't a source of email for the domain in the scenario. Outbound email is sent directly from Office 365 to the internet, so only Office 365 is the source of email for the domain. Now, if outbound email was also sent out through the service, that would be a different story.

I updated the art and explanation. Thanks for the feedback.

**Comment by aldoug** [comment]
Please ensure the following is considered

https://docs.microsoft.com/en-us/office365/SecurityCompliance/how-office-365-uses-spf-to-prevent-spoofing

Requirements for your SPF TXT record and Office 365


If you set up mail when you set up Office 365, you already created an SPF TXT record that identifies the Microsoft messaging servers as a legitimate source of mail for your domain. This record probably looks like this:


Copy
v=spf1 include:spf.protection.outlook.com -all
If you're a fully-hosted Office 365 customer, that is, you have no on-premises mail servers that send outbound mail, this is the only SPF TXT record that you need to publish for Office 365.
If you have a hybrid deployment (that is, you have some mailboxes on-premises and some hosted in Office 365), or if you're an Exchange Online Protection (EOP) standalone customer (that is, your organization uses EOP to protect your on-premises mailboxes), you should add the outbound IP address for each of your on-premises edge mail servers to the SPF TXT record in DNS.

**Comment by aldoug** [comment]
The same is true for other services sending outbound through O365 for your domains
