### ISSUE TITLE
128 GB Memory?

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/OfficeDocs-Exchange#683]
What is the reason for that requirement? Can we expect it to be lowered with one of the next CU updates?
If not, should we evaluate moving to Open-Xchange (12GB) instead of Exchange 2019 coming from Exchange 2013/2016 (8GB to 192GB)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by j0rt3g4** [comment]
@agowa338  I Absolutely think that it was a typo there.
There's no reason why an exchange server would require 128GB in a single installation at least there's a really big environment.

The recommended size for the memory should be 8gb + 16 MB per mailbox.

**Comment by chrisda** [comment]
@agowa338, @j0rt3g4, there's no typo. 128GB is the minimum recommended RAM for Exchange Server 2019.

**Comment by j0rt3g4** [comment]
I could install exchange 2019 on a 8gb ram virtual machine. It's tremendous amount of memory. So can we know why is that big? What has exchange server 2019 different from 2016 that makes it  so demanding on resources?

**Comment by agowa338** [comment]
For everyone reading, there are now four options:

1. Provide much more memory, which will increase to total cost
2. Just 8-12GB of ram and if you someday need to open a ticket at microsoft, just temporarily increase it to 128GB (they will like that for sure :p)
3. Switch to openXchange or anything else
4. Stick with Exchange 2016
