### ISSUE TITLE
Lots of public folders

### ISSUE THREAD

**Issue by briankronberg** [MicrosoftDocs/OfficeDocs-Exchange#685]
If you have a lot of public folders then the commands under "Step 2: Prepare for the migration" will not work.  Here are some suggested replacements.

Get-PublicFolder -Recurse | Export-CliXML C:\PFMigration\Legacy_PFStructure.xml
Get-PublicFolder -Recurse -ResultSize Unlimited | Export-CliXML C:\PFMigration\Legacy_PFStructure.xml

Get-PublicFolderStatistics | Export-CliXML C:\PFMigration\Legacy_PFStatistics.xml
Get-PublicFolderStatistics -ResultSize Unlimited | Export-CliXML C:\PFMigration\Legacy_PFStatistics.xml

Get-PublicFolder -Recurse | Get-PublicFolderClientPermission | Select-Object Identity,User -ExpandProperty AccessRights | Export-CliXML C:\PFMigration\Legacy_PFPerms.xml

This one is harder because you run into a pipelining issue and the error "The total data received from the remote client exceeded allowed maximum".  So we need to do it in two steps.  I also had an error and had to specific the exact public folder server so I added that in.

$PFs = Get-PublicFolder -Recurse -ResultSize Unlimited
$PFs | %{$_ | Get-PublicFolderClientPermission -Server EXCH1 | Select-Object Identity,User -ExpandProperty AccessRights} | Export-CliXML C:\PFMigration\Legacy_PFPerms.xml

**Comment by scanum** [comment]
@briankronberg  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Exchange better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://office365.uservoice.com/. The Office 365 team works with Exchange.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close
