### ISSUE TITLE
The supported UCC certs link no longer works

### ISSUE THREAD

**Issue by chrislehr** [MicrosoftDocs/OfficeDocs-Exchange#687]
This section:
"Choose a CA that says it supports "Unified Communications" (UC) certificates for use with Exchange. For more information, see Unified Communications certificate partners."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86e0c7c-8d35-6385-49f4-b75ade2ed887
* Version Independent ID: fef2f0e5-b17a-c2e1-3a36-6480d03f6106
* Content: [Digital certificates and encryption in Exchange Server](https://docs.microsoft.com/en-us/Exchange/architecture/client-access/certificates?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/certificates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@chrislehr, I removed that bullet from the list.

Thanks for the feedback.
