### ISSUE TITLE
Azure AD Object Limit of 300,000 Incorrect

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/OfficeDocs-Exchange#689]
This article says there is a limit of 300,000 objects per Azure AD Directory. This statement is no longer in sync with actual Azure AD limits (50,000 initial, 500,000 for all tenants after verification, and unlimited for Azure Premium):

https://azure.microsoft.com/en-us/pricing/details/active-directory/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server Hybrid Deployments](https://docs.microsoft.com/en-us/Exchange/exchange-hybrid#directory-synchronization-and-single-sign-on)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@mhendric, I updated it. You, too can also make these kinds of changes to topics. For more information, see https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.
