### ISSUE TITLE
Work around?

### ISSUE THREAD

**Issue by TertiusR** [MicrosoftDocs/OfficeDocs-Exchange#69]
I'm a member of Enterprise Admins, Domain Admins, and Schema admins, and I'll getting this error. Even after rebooting. This document is simply repeating, in longer sentences, the error message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8275401d-32e9-f69b-855f-c48679a47415
* Version Independent ID: 2c6fd97f-7d93-0256-d3a3-178af66a7d04
* Content: [The logged-on user is not a member of the Schema Admins group \[SchemaUpdateRequired\]](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deployment-ref/user-not-member-of-schema-admins)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deployment-ref/user-not-member-of-schema-admins.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deployment-ref/user-not-member-of-schema-admins.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
Hi @TertiusR ,

If Setup is telling you that you're not a member of one of the specified groups when the account you're using to install Exchange is a member, there may be an issue elsewhere in your Active Directory's configuration. Please contact Microsoft Support to help you resolve this issue - https://support.microsoft.com/en-us/assistedsupportproducts.
