### ISSUE TITLE
Clarify statement in scenario 2: because it causes Office 365 spam filtering not to work properly.

### ISSUE THREAD

**Issue by philbert66** [MicrosoftDocs/OfficeDocs-Exchange#690]
This seems to indicate:  
"if a 3rd party is used that does not scan for spam, the email will not be filtered correctly by Office 365"
so it follows that...
"spam *not detected* by a 3rd party scanner will not be filtered correctly by Office 365."  
furthermore: 
"if my 3rd party company is poor at spam filtering, we will get a lot of spam, because Office 365 will not make up for a poor 3rd party scanner."

Is there a detailed explanation of what breaks in this scenario?
Thank you!

Phil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc3d3a13-1d99-fa59-d1e0-6262eac0a985
* Version Independent ID: 54659913-2547-f6ce-e8df-bbecd97c61f5
* Content: [Manage mail flow using a third-party cloud service with Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/manage-mail-flow-using-third-party-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@philbert66, the main reason the scenario breaks Office 365 spam/phish filtering is because the third-party service is taking the message, altering it, and re-delivering the message, the third-party service effectively becomes the new source of the message. The true source of the message is obfuscated. I updated the topic to explain this.

**Comment by philbert66** [comment]
Chris, I get that it is not supported.  I was rather extending the implication of what you're saying to this scenario:  let's say the 3rd party does a *bad* job and some spam and malware gets through and is sent on to Office365.  The point you make above is still true,  to quote:
_the third-party service is taking the message, altering it, and re-delivering the message, the third-party service effectively becomes the new source of the message. The true source of the message is obfuscated_  
the point being, **this missed spam is likely to get through to my users** because this act of altering and re-delivering by the 3rd party makes the O365 spam filter not work as well

**Comment by chrisda** [comment]
@philbert66, correct.
