### ISSUE TITLE
The internal links do not work. Kindly verify.

### ISSUE THREAD

**Issue by ranjithpothu** [MicrosoftDocs/OfficeDocs-Exchange#693]
The internal links do not work. Kindly verify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c535a571-01a4-9c3f-0a59-5f26102b18f1
* Version Independent ID: 6fb6bd97-18d2-7049-c539-55adaa0d2556
* Content: [Exchange Online and Exchange Online Protection service upgrade](https://docs.microsoft.com/en-us/exchange/exchange-online-and-exchange-online-protection-service-upgrade#feedback)
* Content Source: [Exchange/ExchangeOnline/exchange-online-and-exchange-online-protection-service-upgrade.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/exchange-online-and-exchange-online-protection-service-upgrade.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by chrisda** [comment]
@ranjithpothu that topic appears very old, and probably shouldn't have been migrated from TechNet to docs.microsoft.com. The FOPE to EOP migration happened 4+ years ago. I'll take the topic out of the table of contents (TOC) and hide it from search results.

Thanks for the feedback.
