### ISSUE TITLE
Please Support Exchange 2016 with Windows 2019 AD Controllers

### ISSUE THREAD

**Issue by mailgut** [MicrosoftDocs/OfficeDocs-Exchange#694]
We want to Update our Domaincontrollers for the root domain an the child domain with windows 2019. Could you please support this?

**Comment by chrisda** [comment]
@mailgut, I'm sure it's coming. It's just a matter of testing and verifying. We'll be sure to update the documentation when Windows 2019 DCs are supported with Exchange 2016.

Thanks for the feedback.
