### ISSUE TITLE
OWA does not allow searching both primary and in-place archive

### ISSUE THREAD

**Issue by labanex** [MicrosoftDocs/OfficeDocs-Exchange#696]
In fact I noticed that when searching in any mailbox, you have to be in that mailbox to search a mailbox. In-Place Archive the same way as shared mailboxes. In Outlook, searching primary and archived mailbox does work in Outlook 2016. Have not tested 2010 or 2013.
https://docs.microsoft.com/en-us/exchange/in-place-archiving-in-exchange-2013-exchange-2013-help#in-place-archives-and-other-exchange-features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54971ef-2166-5af2-c8d3-12ba2ddc31e0
* Version Independent ID: ebbf2eff-a187-95fd-a97a-d442af728cca
* Content: [In-Place Archiving in Exchange 2013: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/in-place-archiving-in-exchange-2013-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/in-place-archiving-in-exchange-2013-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/in-place-archiving-in-exchange-2013-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by afield1235** [comment]
Archive searching does not WORK AT ALL on a mac which is a big oversight. With the webmail same experience as original posted. You have to specifically select the archive to search it, and when you do, it won't include any results from your regular inbox or folders. The archive is a really bad experience right now.

**Comment by dstrome** [comment]
hi @labanex and @afield1235 - we're unfortunately not able to provide support in these comments. If your deployments aren't functioning as expected, please contact Microsoft support for assistance.
