### ISSUE TITLE
Table under "Properties of the default self-signed certificates" not displayed correctly

### ISSUE THREAD

**Issue by robderickson** [MicrosoftDocs/OfficeDocs-Exchange#698]
The table under "Properties of the default self-signed certificates" is exploded on docs.microsoft.com. The table looks fine in GitHub, and in VS Code Markdown preview. Maybe there is an issue with rendering `\&lt;ServerName\&gt;`? Could try `&lt;ServerName&gt;` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b86e0c7c-8d35-6385-49f4-b75ade2ed887
* Version Independent ID: fef2f0e5-b17a-c2e1-3a36-6480d03f6106
* Content: [Digital certificates and encryption in Exchange Server](https://docs.microsoft.com/en-us/exchange/architecture/client-access/certificates?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/certificates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/certificates.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by robderickson** [comment]
Never mind. It looks like the issue is around line 155; col 166. Backtick left open..

**Comment by robderickson** [comment]
Issue address in PR #699.

**Comment by scanum** [comment]
@robderickson  Thank you for submitting this feedback and also providing a solution.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
