### ISSUE TITLE
Ask user to confirm attachments to 3rd parties

### ISSUE THREAD

**Issue by bayesfactor** [MicrosoftDocs/OfficeDocs-Exchange#70]
It would be highly desirable to allow admins to create a Mail Rule that screens emails that have attachments and are to a 3rd party (outside domain). I would like Outlook to pop up a confirmation window to ask the user to confirm. It is my understanding that this is not currently possible.

**Comment by chrisda** [comment]
That appears to be correct. The pop-up would be either a MailTip or a PolicyTip. You could do a MailTip for external recipients, but that doesn't specify only those messages that contain attachments. The PolicyTip would require to classify every type of attachment as sensitive, which has obvious drawbacks.
