### ISSUE TITLE
Incorrect Powershell commands

### ISSUE THREAD

**Issue by AndyFriar** [MicrosoftDocs/OfficeDocs-Exchange#700]
Lots of Set-Set-RemoteDomain rather than Set-RemoteDomain, i'm sure most people would have guessed but to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03f55019-577c-7488-4ea9-ac54761a4834
* Version Independent ID: 6fb44d44-204c-c2a1-31ec-f875e469367e
* Content: [Manage remote domains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/remote-domains/manage-remote-domains#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/manage-remote-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/manage-remote-domains.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndyFriar** [comment]
Pull Request #701

**Comment by chrisda** [comment]
@AndyFriar, fixed. Thanks for the feedback. And remember, you can fix stuff like this in topics, too. See https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.
