### ISSUE TITLE
Hybrid Keys with Exchange 2019

### ISSUE THREAD

**Issue by pstasik** [MicrosoftDocs/OfficeDocs-Exchange#703]
Nowhere is it listed that Exchange 2019 MUST be fully licensed BEFORE attempting to run the HCW because MSFT is not providing Hybrid keys for Exchange 2019.  What are we supposed to do if we've already installed Exchange 2019 in a Hybrid environment short of buying a pricey license we will never get full use of?

**Comment by scanum** [comment]
@pstasik - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
