### ISSUE TITLE
Please add originator info for the incomming hybrid traffic

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-Exchange#704]
For security reasons we need to limit who has access to our infrastructure. Currently EWS, Autodiscover, etc, are not published publically. When we setup the hybrid we have to be able to allow only Office 365 to connect to our published infrastructure. To do this we need a list of IPs of Office 365 services that will connect to the service. Can you add to the "Hybrid deployment protocols, ports, and endpoints" table a columnd with information about origin of the connection - which Office 365 service is connecting and which IP addresses are being used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/Exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by mcavasin** [comment]
Yeah, that would be REALLY helpful as I can't think of a single client who would be OK with just opening up those ports to Exchange for connections from ANYWHERE...

**Comment by dstrome** [comment]
hi @Larryngolog & @mcavasin - if I understand the question correctly, the information you're looking for is in the https://go.microsoft.com/fwlink/?LinkId=823100  link at the bottom of the paragraph above the protocols/ports/endpoints table in the topic. 

Please let me know if this isn't the information you're looking for.

David.

**Comment by mcavasin** [comment]
The thing is, it MAY be. That doc specifically states it's ONLY for reference for client (Outlook) connectivity and NOT for Hybrid.

It would be nice if the wording made clear for inbound port 25/80/443 traffic what the originating DNS/IP range were. It makes it confusing when giving documentation to clients and/or dealing with configurations where those ports aren't just open to the Internet in general as part of normal Exchange operations.

Networking admins especially want to see a nice, standard five-tupple ACL table or as close as possible.

Mike Cavasin
647-991-4620

Sent from mobile

________________________________
