### ISSUE TITLE
What is an SMTP URL?

### ISSUE THREAD

**Issue by vboyev-MSFT** [MicrosoftDocs/OfficeDocs-Exchange#709]
is the author attempting to convey SMTP namespaces? I've never seen the term SMTP URL used before, it does not seem to be common use in the context of SMTP. For HTTP workloads, sure....

"The necessary services must be defined in the second datacenter. For example, if the first datacenter has three different SMTP URLs on different transport servers, the appropriate configuration must be defined in the second datacenter to enable at least one (if not all three) transport server to host the workload."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6f31ced-6f2a-bc29-fb5d-9ac8a3b0204f
* Version Independent ID: e4e84ffc-3f49-2b6a-a25f-e66d9b81429b
* Content: [Planning for high availability and site resilience: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/planning-for-high-availability-and-site-resilience-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/planning-for-high-availability-and-site-resilience-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/planning-for-high-availability-and-site-resilience-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by chrisda** [comment]
@vboyev-MSFT, yeah, that's a bit odd, and it goes all the way back to the Exchange 2010 version of the topic. I changed it to "SMTP destintations" as in, inbound mail is round-robin or load-balanced to three different destination transport servers.

Thanks for the feedback.
