### ISSUE TITLE
Information Wrong

### ISSUE THREAD

**Issue by musashiharuno** [MicrosoftDocs/OfficeDocs-Exchange#71]
If you create a remote mailbox in Office 365
-&gt; remote mailbox creation is only available OnPrem, it's not available in EXO.
-&gt; EXOPS, there is no such command for you to create, also, I did not see this command is available for EXOPS from Technethttps://docs.microsoft.com/en-us/powershell/module/exchange/federation-and-hybrid/get-remotemailbox?view=exchange-ps

------------------
Important

ACLs aren't enabled on remote mailboxes created in Office 365. If you create a remote mailbox in Office 365, you'll need to follow the steps in the Enable ACLs on remote mailboxes section to enable ACLs on that remote mailbox. To avoid this extra step, we recommend that you create the mailbox on an on-premises Exchange server and then move the mailbox to Office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d8bb0b-6656-9565-598c-4b82018f6a1c
* Version Independent ID: fca6d1ff-0764-fcf6-d459-16473131f3a0
* Content: [Configure Exchange to support delegated mailbox permissions in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-delegated-mailbox-permissions)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-delegated-mailbox-permissions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi @musashiharuno ,

The instructions in the "Enable ACLs on remote mailboxes" indicate the commands must be run on an Exchange Server in the on-premises organization.
