### ISSUE TITLE
Active Sync Experience is Horrible w/ Modern Auth

### ISSUE THREAD

**Issue by afield1235** [MicrosoftDocs/OfficeDocs-Exchange#710]
Hello,
We currently are using MFA and leverage App passwords which permanently lock the user's username and password into the device. This persists even through password changes and the experience is **great.**

With Modern auth, users are prompted to re enter their credentials and perform a MFA challenge (manually, copy paste code) every 30 days. This experience is really poor and wastes time. Is there a way Active Sync can challenge less??

We have our MFA set to remember locations for 30 days, this is fine for Web Browsers and other apps but absolutely **not** OK for Active Sync.

What is the solution here? Otherwise I'll just be expecting complains from users for the rest of my career.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online#modify-authentication-policies)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by afield1235** [comment]
Is anybody there?

**Comment by scanum** [comment]
@afield1235  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by afield1235** [comment]
This isn't a Service ticket related request. I guess this would be best for Microsoft Voice feedback which is a useless democratic process. How do we actually get in touch with decision makers behind these decisions?
