### ISSUE TITLE
What about Set-CASMailboxPlan

### ISSUE THREAD

**Issue by ajhstn** [MicrosoftDocs/OfficeDocs-Exchange#712]
Hello, how is the EO authenticationPolicy differ to the CAS Mailbox Plan? for example

`Set-CASMailboxPlan -ImapEnabled $false -PopEnabled $false`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ajhstn, it has to do with where in the authentication chain that access is blocked. Authentication policies are better suited to block connection attempts in the pre-authentication phase, which would help to prevent account lock-outs during brute-force or password spray attacks. If you only blocked POP/IMAP access using the CAS mailbox plan, attacks could still hammer against usernames and passwords, which would lock-out the accounts.

But, fundamentally, they would both block POP and/or IMAP access to mailboxes.

**Comment by booklegger** [comment]
> @ajhstn, it has to do with where in the authentication chain that access is blocked. Authentication policies are better suited to block connection attempts in the pre-authentication phase, which would help to prevent account lock-outs during brute-force or password spray attacks. If you only blocked POP/IMAP access using the CAS mailbox plan, attacks could still hammer against usernames and passwords, which would lock-out the accounts.
> 
> But, fundamentally, they would both block POP and/or IMAP access to mailboxes.

@chrisda - This information on the authentication phases is very helpful, thanks.  Do you happen to know if failed logins, i.e. logins blocked by authentication policies during the pre-authentication phase, are logged?  Are they visible via the AAD portal, or via SigninLogs in Log Analtyics?

**Comment by chrisda** [comment]
@booklegger, I'm told that pre-auth login denails are currently not being logged. There is thought being given to the idea, however.

**Comment by ajhstn** [comment]
@chrisda i understand the CASMailboxPlan is post auth and the AuthenticationPolicy is pre-auth and the obvious benefits of blocking pre-auth..

In saying that, in the SigninLogs i can see repeating failed auths from bad actors using IMAP & POP.  In some cases i see a Successful auth (and yes i understand i am talking about about compromise here), but i do NOT see a MailboxLogin in the Mailbox Audit Log, am i to assume here that the auth against AAD was successful, but because of the CAS Mailbox plan, the successful connection was dropped and therefore no MailboxLogin was seen?

**Comment by chrisda** [comment]
@ajhstn, yes, that's correct.

**Comment by ajhstn** [comment]
@chrisda ok great, are there any plans to make that explicit in the logs and include a log that says "token was blocked due to policy" or something?
