### ISSUE TITLE
DefaultAuthenticationPolicy clarification

### ISSUE THREAD

**Issue by ajhstn** [MicrosoftDocs/OfficeDocs-Exchange#713]
Hello, please clarify these sentences from this document.

The default authentication policy is assigned to all users who don't already have a specific policy assigned to them.
Note that the authentication policies assigned to users take precedence to the default policy. To configure the default authentication policy for the organization, use this syntax:"

Set-OrganizationConfig -DefaultAuthenticationPolicy "Disable Basic Auth"

A) My tenant has no DefaultAuthenticationPolicy value set under Get-OrganizationConfig.

B) If I Set-OrganizationConfig -DefaultAuthenticationPolicy "Disable Basic Auth", all existing and all new users will be forced to use modern auth going forward.

C) Unless i create another AuthenticationPolicy and set it at the user mailbox level with "Set-User", in which case this new Policy will over-rule the default policy?

Is B and C TRUE?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd0905ff-a481-c566-3869-595e8cf125cb
* Version Independent ID: 4c688d1c-87ba-9c82-3258-9ee8de0e6b1a
* Content: [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ajhstn, you are correct. The authentication policy at the org level applies to everyone **until** you create and apply specific authentication policies to users. At that point, whatever you configure in those policies overrides the default policy at the org level. So, if you disable Basic Auth at the org level, but enable Basic Auth at the user level, the user level authentication policies take precedence.

**Comment by scanum** [comment]
@ajhstn Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
