### ISSUE TITLE
SPF support for 3rd party Exchange Hybrid mode

### ISSUE THREAD

**Issue by GregLeonard** [MicrosoftDocs/OfficeDocs-Exchange#714]
This page is confusing and misleading customers as it is blurring supported configurations, versus where Microsoft support can assist in SPF related cases.  Can we please update this page for clarity purposes.

This is my personal view and is to be cleared formally by Microsoft support.

SPF is a method to prove email domain authenticity.  In simple terms, organisations can nominate a supported list of IP Addresses that are authorised to send mail from a domain (i.e. customers can nominate a supported list of authorised IP addresses for outbound email).  Organisations receiving that email can lookup those supported IP addresses and determine if the email is from an authentic source.

This article is referring to the configuration of SPF in Exchange hybrid mode, and showing the two scenarios where Outbound mail is delivered from Exchange Online, and from On-Premises via a 3rd party email gateway.

The support cases referred to would relate to mail being sent by customers and received by organisations, and those organisations having issues proving the authenticity of the customers outbound email services.

Scenario 1 (Outbound mail via Exchange Online) is a Microsoft supported routing configuration, and supported by Microsoft for SPF related cases, as it uses the Microsoft Exchange Online services for outbound mail services.

Scenario 2 (Outbound mail via 3rd party gateway) is a Microsoft supported routing configuration, that is customers can configure a hybrid Exchange environment  with 'Centralized Mail Transport' to route mail out via on-premises email gateways; however it is not recommended by Microsoft support as SPF is configured using DNS records of the outbound email services (i.e. in this scenario the 3rd Party gateway solution).  As Microsoft are not controlling the 3rd party email gateways, then any SPF related support cases raised should be resolved by the customer and their 3rd party email gateway provider - not Microsoft.  As Microsoft support cannot resolve issues related to 3rd party changes\products, SPF issues in this routing configuration are therefore not supported by Microsoft.

Additional information:  
- [Sender Policy Framework](https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spoofing-protection )
- [Centralised Mail Transport](https://docs.microsoft.com/en-us/exchange/transport-options)

**Comment by dstrome** [comment]
hi @GregLeonard - could you please post a link to the topic you're referring to? Unfortunately the metadata included when this issue was opened was delete so we're unable to determine which topic this issue is referring to.

**Comment by scanum** [comment]
@GregLeonard  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
