### ISSUE TITLE
Licensing requirements

### ISSUE THREAD

**Issue by MikeParker365** [MicrosoftDocs/OfficeDocs-Exchange#716]
Would be good to have clear indication of the licensing requirements for placing mailboxes under hold, both litigation and in-place, for different mailbox types, i.e. Shared Mailbox vs. User mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0957d8b7-cb89-0aa7-f8ac-329aa3c2b085
* Version Independent ID: 21e5f86c-104d-bdec-8092-c2efc7e0574c
* Content: [In-Place Hold and Litigation Hold in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/holds/holds?view=exchserver-2019&viewFallbackFrom=exchonline-ww)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/holds/holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/holds/holds.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by chrisda** [comment]
@MikeParker365, are you talking about on-premises Exchange licensing and the affect of having different types of mailboxes on hold?

Apparently, in on-premises Exchange, there's no concept of an inactive mailbox (where you put the mailbox on hold, delete the account, and the mailbox stays around indefinitely). The best you can do in on-prem is to disable the account and hide the mailbox from the GAL. It would follow that the mailbox would still consume a license.

If you're talking about mailboxes without accounts that don't require licenses (resource mailboxes or shared mailboxes), then even when they are on hold, they likewise shouldn't require a license.

**Comment by MikeParker365** [comment]
@chrisda I'm talking about in Exchange Online, for Shared Mailboxes, do they need an EXO P2 license to be placed under In-Place Hold. Do they require a license for Litigation Hold? Would also be good to clarify the difference in licensing requirements for a hold created from EXO Admin Center vs. Security and Compliance Center.

**Comment by pminnebach** [comment]
@MikeParker365 You can find a full feature comparison of all O365 and all standalone EXO plans at the following link: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description#feature-availability-across-exchange-online-standalone-plans

Under In-Place Hold and Litigation Hold it clearly says No for EXO P1, and yes for EXO P2.

And the smallprint says: (17) Exchange Online Plan 1 has a size limit on the mailbox and archive. Exchange Online Archiving for Exchange Online add-on adds unlimited cloud-based archive and In-Place Hold. 

You can purchase a seperate Archive license to combine with a EXO P1, but i'm fairly sure that it would be equaly or more expensive than a single EXO P2 license. https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/exchange-online-archiving-service-description

**Comment by danfrax** [comment]
Is there a minimum requirement in relation to how long a license needs to be applied to a user in O365 before litigation will be honored?

I have read somewhere but cannot locate the source that 90 days is the minimum.

Otherwise technically I could migrate a departed user, assign a license, enable litigation hold and then delete the user. Effectively I could do this hundreds of times and only require 1 license.

Would really like to clarify this, obviously the idea is to conform to the requirements. However how long I have a user licensed effects the technical process.

Thank you
