### ISSUE TITLE
Missing details on selective wipe

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#717]
Please add details on the "Account Only Remote Wipe Device" option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92072b83-beec-a8d5-b5c0-b5900265fbc8
* Version Independent ID: 134ac1f2-0fc9-9598-b89a-72110c16c214
* Content: [Perform a remote wipe on a mobile phone](https://docs.microsoft.com/en-us/exchange/clients/exchange-activesync/remote-wipe?view=exchserver-2019&viewFallbackFrom=exchonline-ww#feedback)
* Content Source: [Exchange/ExchangeServer/clients/exchange-activesync/remote-wipe.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/exchange-activesync/remote-wipe.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by lindspea** [comment]
@danmyhre Thank you for pointing this out.  Do you have any suggestions for details that need to be added?

**Comment by danmyhre** [comment]
Some of the key things would be - what exactly the selective wipe will remove, any limitations or client requirements in order for it to work, what happens when the client doesn't support selective wipe, permissions needed to perform the action, and any consideration that should be made when the device is managed by Intune

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@danmyhre Still looking into having this updated for you.  Just need to get the correct information.

**Comment by jm15502** [comment]
Hi. What about the Account Only Remote Wipe Device? The article should explain the differences.

**Comment by scanum** [comment]
@danmyhre Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
