### ISSUE TITLE
Documentation for Search-Mailbox missing

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#718]
Cmdlet is still available (O365 too) but I cannot find any documentation.

Same with PowerShell help:

PS C:\Users\trudolf> Get-Help Search-Mailbox
Get-Help : Exception calling "Invoke" with "0" argument(s): "Cannot find path '' because it does not exist."
At line:1 char:1
+ Get-Help Search-Mailbox
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Help], MethodInvocationException
    + FullyQualifiedErrorId : CmdletInvocationException

**Comment by chrisda** [comment]
@trudolf-msft, there's a known Windows PowerShell 5.1 problem that affects Get-Help in Exchange Online PowerShell (the error message you quoted). This problem doesn't affect Office 365 Security & Compliance Center PowerShell. This problem has been going on for a while, and has only been recently identified.

**Comment by trudolf-msft** [comment]
Hi Chris,
there is no documentation (TechNet or Docs) at all for this still existing cmdlet.
Please fix.
Thanks, Thomas

**Comment by chrisda** [comment]
@trudolf-msft, all Exchange cmdlet reference topics were migrated from TechNet to docs.microsoft.com at the end of March, 2018. The Search-Mailbox cmdlet topic is alive and well here:

https://docs.microsoft.com/powershell/module/exchange/mailboxes/search-mailbox

The first search result in both Bing and Google for "Search-Mailbox" is this topic.

Any previous links to the TechNet versions of this topic for Exchange 2010, Exchange 2013, Exchange 2016 and Exchange Online should automatically redirect to this location.
