### ISSUE TITLE
it was really helpfull

### ISSUE THREAD

**Issue by halavehzadeh** [MicrosoftDocs/OfficeDocs-Exchange#719]
thanks for Microsoft for this document ,it was really answer my question related to install Exchange 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f347a03-e2c5-5ae2-e409-ddb6d544ccfd
* Version Independent ID: 839ff415-2b55-e312-3121-0fd2d9ca5a88
* Content: [Prepare Active Directory and domains for Exchange Server, Active Directory Exchange Server, Exchange Server Active Directory, Exchange 2019 Active Directory](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prepare-ad-and-domains?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@halavehzadeh, you are most welcome.
