### ISSUE TITLE
TLS 1.1 & 1.2 Support not enabled by default in Windows 7 - Causes Outlook not to work

### ISSUE THREAD

**Issue by lrandall-gillsch** [MicrosoftDocs/OfficeDocs-Exchange#722]
I think there should be a note under "Supported clients" to say that for Windows 7 you need KB3140245 and to apply registry keys to enable TLS 1.1 & 1.2 support for Windows 7, otherwise Outlook (2013 and 2016 from my testing) does not work on Windows 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
@lrandall-gillsch thank you for contributing and improving MS docs. I'll make the changes and have them reviewed soonest.

**Comment by scanum** [comment]
@lrandall-gillsch  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
