### ISSUE TITLE
Please include that Dynamic Distribution Group are objects that do not sync to AAD and therefore blocked by DBEB. 

### ISSUE THREAD

**Issue by hudish** [MicrosoftDocs/OfficeDocs-Exchange#723]
Please include that external/Hybrid Exchange Server Dynamic Distribution Group are objects that do not sync to AAD and therefore blocked by DBEB. To work around, a contact object is created with External SMTP address of that group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb394c8-1004-a253-7806-71fdc9406478
* Version Independent ID: 1f4e3200-3025-5def-851e-3d56f815c2ff
* Content: [Use Directory Based Edge Blocking to reject messages sent to invalid recipients](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-directory-based-edge-blocking#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-directory-based-edge-blocking.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
@hudish Thank you for reaching out.  Are you suggesting adding that note to the article?

**Comment by hudish** [comment]
Hi. Yes, a) as an example of a scenario why DBEB would not work and b) an official work around the scenario would help administrators self-resolve such issues.

**Comment by hudish** [comment]
To be clear, I’m not from Engineering. I’m from Support.
You would confirm this action with Engineering first.

From: Alex Hudish
Sent: Friday, April 5, 2019 8:07 AM
To: MicrosoftDocs/OfficeDocs-Exchange <reply@reply.github.com>
Subject: RE: [MicrosoftDocs/OfficeDocs-Exchange] Please include that Dynamic Distribution Group are objects that do not sync to AAD and therefore blocked by DBEB. (#723)

Hi. Yes, a) as an example of a scenario why DBEB would not work and b) an official work around the scenario would help administrators self-resolve such issues.

**Comment by hudish** [comment]
Yes, I work in Microsoft Support and based on my conversations with our customers, I'm offering the added value of that note a) as an example of a scenario why DBEB would not work and b) to help administrators in the future to address such scenarios.

**Comment by scanum** [comment]
@hudish  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
