### ISSUE TITLE
Save Contacts in Android policy

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-Exchange#724]
Hello,
Save Contacts in Android don't work well, tested in 2x tenants.
When enable Save Contacts, then save policy and open policy again, option is not selected at all for section of "Save Contacts";
See print screen here: https://techcommunity.microsoft.com/t5/Intune-Customer-Success/New-Outlook-for-iOS-and-Android-App-Configuration-Policy/ba-p/370481

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndyH16** [comment]
I'm not able to get the new settings to take effect, apart from the mailbox setup (mail server, auth type, etc.)

I've configured the Focused Inbox (Off) and Sync Contacts (On), then when I go back in to view them they all show as 'Not configured'. If I go into the JSON data view I can see the entries though.

**Comment by capnjax21** [comment]
I am having the same issue for Outlook on Android managed devices.

**Comment by lightupdifire** [comment]
Hello,
For me settings for Save Contacts not just like "Not configured", they like dis-selected

![image](https://user-images.githubusercontent.com/39700914/54976339-57511400-4f9a-11e9-9fb8-3ae489163a39.png)

**Comment by smithre4** [comment]
Thanks for the report. This is now functioning correctly; were dependent on the rollout of Outlook for Android build 3.0.34 and this wasn't completed until yesterday. You can now use the Intune Portal to configure the app configuration policy appropriately.
