### ISSUE TITLE
Shared Mailboxes and Office 365 Retention Policies

### ISSUE THREAD

**Issue by TymWongPSNinja** [MicrosoftDocs/OfficeDocs-Exchange#727]
Is it possible to use office 365 retention policies as configured in the security & compliance portal to ensure data is kept for a number of years for a Shared Mailbox under the free licence? Or does this require licensing the shared mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 488ecf85-5f6d-3abd-4253-8527b5082340
* Version Independent ID: ec414c0f-4ee4-bbd1-3851-3e4db0c97593
* Content: [Shared mailboxes in Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/shared-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by lindspea** [comment]
@TymWongPSNinja you don't need a license for retention but you need it for archiving and litigation hold. If you want to enable the archive mailbox or put a Litigation Hold on a shared mailbox, then an Exchange Online Plan 2 license or an Exchange Online Plan 1 with Exchange Online Archiving license is required. If you want to enable the archive mailbox or put a Litigation Hold on a shared mailbox, then an Exchange Online Plan 2 license or an Exchange Online Plan 1 with Exchange Online Archiving license is required. Hope this helps.  Let me know if you need further assistance.

**Comment by scanum** [comment]
@TymWongPSNinja  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
