### ISSUE TITLE
EAC website DLP vs Protection website DLP

### ISSUE THREAD

**Issue by adamgriffingit** [MicrosoftDocs/OfficeDocs-Exchange#729]
The documentation should reference https://protection.office.com as there is at least one default policy contained there that is not in the EAC data-loss-prevention section. Also, is one of them becoming deprecated? It wasn't clear which one is preferred.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2914fc20-5202-1611-d66e-5310cd01f9f8
* Version Independent ID: 31162c84-0d4f-483a-ccf9-04da60275c67
* Content: [Manage policy tips](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/manage-policy-tips#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/manage-policy-tips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/manage-policy-tips.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@adamgriffingit Moving forward, we recommend creating DLP policies in the Office 365 Security & Compliance Center, not the Exchange admin center. For more information - https://docs.microsoft.com/office365/securitycompliance/data-loss-prevention-policies.
For DLP in O365 vs. DLP in Exchange - https://docs.microsoft.com/office365/securitycompliance/how-dlp-works-between-admin-centers.

**Comment by scanum** [comment]
@adamgriffingit  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
