### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by curspice** [MicrosoftDocs/OfficeDocs-Exchange#731]
The command in step 2 should begin with .\, as in:
.\Sync-MailPublicFolders.ps1 ...

because it's a PowerShell script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1812196b-e6c5-7f6e-fa82-49df2a47d73d
* Version Independent ID: cc06c76a-b7a0-7c21-0a73-c66b9b05a055
* Content: [Configure Exchange 2013 public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by dstrome** [comment]
hi @curspice - thanks very much for your feedback. I've updated the topic and the change will be live within the next couple days.
