### ISSUE TITLE
Licensing requirement

### ISSUE THREAD

**Issue by benoitms** [MicrosoftDocs/OfficeDocs-Exchange#734]
Is the domain restriction feature still in preview and subject to AAD Premium licence? I do not see any mention in the official documentation: https://docs.microsoft.com/en-us/azure/active-directory/b2b/allow-deny-list 
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08bf021-f95a-ab2f-85e3-4f4c44374501
* Version Independent ID: 2d7ea71a-f42c-693a-eb4e-c1d9336b44eb
* Content: [Allow/Block guest access to Office 365 groups](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-group-access-to-office-365-groups#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-group-access-to-office-365-groups.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @dianef77
* Microsoft Alias: **dianef**

**Comment by lindspea** [comment]
@benoitms. Thank you for reaching out. Yes, we are in GA now and it doesn’t require premium license, it is part of AAD basic SKU.  Let me know if you need further assistance.

**Comment by benoitms** [comment]
thanks a lot

**Comment by lindspea** [comment]
@scanum you can close thank you.

**Comment by scanum** [comment]
@benoitms  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

@officedocsbot close
