### ISSUE TITLE
Powershell block doesn't contain powershell code

### ISSUE THREAD

**Issue by nnpcYvIVl** [MicrosoftDocs/OfficeDocs-Exchange#737]
Text examples on this page are erroneously marked as powershell blocks.

https://docs.microsoft.com/en-us/exchange/pickup-directory-and-replay-directory-exchange-2013-help

Here's an example:

```
This example shows a plain text message that uses acceptable formatting for the Replay directory.
```
```
PowerShell
```
```
X-Receiver: <mary@contoso.com> NOTIFY=NEVER ORcpt=mary@contoso.com
```

**Comment by dstrome** [comment]
hi @nnpcYvIVl - thanks very much for your feedback. I've updated the topic and the changes should be live within the next day or two.
