### ISSUE TITLE
Public folders in "New" Outlook on the web

### ISSUE THREAD

**Issue by slovelett** [MicrosoftDocs/OfficeDocs-Exchange#739]
Does the process for adding public folders to favorites using outlook on the web (https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/use-favorite-public-folders#add-favorite-public-folders-in-outlook-on-the-web) work in the "New Outlook". After selecting the option to try the new outlook, public folders do not appear to be showing up, and I can't find a way add new ones?

**Comment by scanum** [comment]
@slovelett  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
