### ISSUE TITLE
would be helpful to have number of hours to complete

### ISSUE THREAD

**Issue by spacklewoof** [MicrosoftDocs/OfficeDocs-Exchange#74]
It would be nice to know about how long it would take for a successful upgrade, maybe even based on the number of users in the domain or some other easily identifiable characteristic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f347a03-e2c5-5ae2-e409-ddb6d544ccfd
* Version Independent ID: 839ff415-2b55-e312-3121-0fd2d9ca5a88
* Content: [Prepare Active Directory and domains](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prepare-ad-and-domains#what-do-you-need-to-know-before-you-begin)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prepare-ad-and-domains.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi @spacklewoof ,

Thanks for the suggestion! It's difficult to provide estimates on how long an installation will take given the variety of sizes, types, and configurations of organizations. I'll bring this up with the rest of our writing team to see if there's a way to give you a way to estimate installation time based these various factors.

**Comment by spacklewoof** [comment]
Totally get it.  Thank you for responding.
