### ISSUE TITLE
Microsoft Exchange Server Deployment Assistant not support for Exchange 2019

### ISSUE THREAD

**Issue by ianc911** [MicrosoftDocs/OfficeDocs-Exchange#741]
The second tip in the article recommends going to the "Microsoft Exchange Server Deployment Assistant" to create a customized checklist for your installation. Unfortunately the wizard does not support Exchange 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites, Exchange 2019 system requirements, Exchange 2019 requirements](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prerequisites?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dstrome** [comment]
hi @ianc911 - thanks very much for your feedback. We're actively working on updating the Deployment Assistant to include Exchange 2019. I unfortunately can't share an ETA at this time.
