### ISSUE TITLE
O365 SMTP relay for on-premise applications

### ISSUE THREAD

**Issue by ausotechteam** [MicrosoftDocs/OfficeDocs-Exchange#742]
Hi,

We have Exchange 2010 running on-premise in hybrid mode (all our users mailboxes are in O365), currently we use our exchange servers to relay email from on-premise applications/MFDs to O365). We are planning to use our Exchange server for management purposes only, and setup email relay using the three methods described in this article. However, towards the end of the article it mentioned "If you have mailboxes in Office 365 and an email server that you manage (also called an on-premises email server), always configure your devices and applications to use your local network and route email through your own email server."

Does this mean that using Exchange server on-premise for email relay is our only option? and if it is can you please explain the reason behind this.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ausotechteam, that statement is probably worded a bit too strongly. It is certainly easier and more flexible to configure SMTP relay using an on-premises email server instead of Office 365. But, the whole point of that topic is how to configure SMTP relay using Office 365, so using an on-premises email server is definitely not your only option. If I was going to update that statement, it would say:

> If you happen to have an on-premises email server, you should seriously consider using that server for SMTP relay instead of Office 365. A local email server that you have physical access to is much easier to configure for SMTP relay by devices and applications on your local network.
 
Any comments or clarifications you would like in that statement?

**Comment by ausotechteam** [comment]
Thanks @chrisda, yes that makes it clearer.  The reason why we want to use O365 for SMTP relay is because we are planning to have only one Exchange server on-premise (for management purposes),  and in case we need to perform maintenance or bring the server down, our applications/MFDs will still be able to send emails using O365 relay.

**Comment by chrisda** [comment]
@ausotechteam, thanks. I'm closing the issue because I updated the topic.
