### ISSUE TITLE
Create-PublicFolderMailboxesForMigration.ps1 -Database

### ISSUE THREAD

**Issue by uz-it** [MicrosoftDocs/OfficeDocs-Exchange#743]
Hi
Just a wish:
If it is possible could You please add -Database parameter to the script?
In some cases it is relevant to create a new PF mailbox in a dedicated database.
Why:
Cause current script creates a PF mailbox in a random database and  it sometimes needs to be moved to another DB.
or: if you do not move the PF MBX after migration process it can cause back pressure situation on disk in case of if the legacy PF DB size is quite big...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6010593-c3e4-87a6-4084-27d56f23063c
* Version Independent ID: 32a2adeb-0932-3236-09d9-b7987393639b
* Content: [Use batch migration to migrate Exchange 2010 public folders to Exchange 2016](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/batch-migration-from-previous-versions?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/batch-migration-from-previous-versions.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hi @uz-it 
We are not able to add this directly since is not related to documentation.
For request of this type you must use the O365 user voice:
https://office365.uservoice.com/

**Comment by uz-it** [comment]
https://office365.uservoice.com/forums/273493-office-365-admin/suggestions/37558273-add-database-parameter-to-the-script-create-publi

**Comment by j0rt3g4** [comment]
@uz-it Exactly we are the documentation team and we don't have access to the Cmdlets themselves. Thank you for understanding.
