### ISSUE TITLE
Restrict app to GCC accounts setting is missing on the new update for iPhone. 

### ISSUE THREAD

**Issue by KinberlyC** [MicrosoftDocs/OfficeDocs-Exchange#744]
Restrict app to GCC accounts setting is missing on the new update for iPhone.

**Comment by JamesS42** [comment]
I have the same issue on Android, if I try to install my Gov account it fails.

**Comment by scanum** [comment]
@KinberlyC  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
