### ISSUE TITLE
Typo in "Create and configure remote domains" section

### ISSUE THREAD

**Issue by therealscottcarlow** [MicrosoftDocs/OfficeDocs-Exchange#747]
Section link: https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/remote-domains/manage-remote-domains#create-and-configure-remote-domains

The first bullet point in "notes" contains the following:

&gt;You can configure a remote domain for any domain that's listed on the Office 365 admin center &gt; Domains page. For example, if fabrikam.com is one of your accepted domains, you can't create a remote domain for fabrikam.com.

One sentence is affirmative, and the second is negative. Considering context, both should be negative. Suggested edit below:

&gt;You can't configure a remote domain for any domain that's listed on the Office 365 admin center &gt; Domains page. For example, if fabrikam.com is one of your accepted domains, you can't create a remote domain for fabrikam.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03f55019-577c-7488-4ea9-ac54761a4834
* Version Independent ID: 6fb44d44-204c-c2a1-31ec-f875e469367e
* Content: [Manage remote domains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/remote-domains/manage-remote-domains#create-and-configure-remote-domains)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/manage-remote-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/manage-remote-domains.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by lindspea** [comment]
@therealscottcarlow Thank you for pointing this out.  I'll make the changes and have them reviewed soonest.  Thank you for your valuable contribution in helping improve MS Docs.

**Comment by aratliff** [comment]
From the testing I've done, it looks like an accepted domain CAN be added as a remote domain which can be leveraged to implement control of message formatting internally within a given O365E domain.  The bullet should be removed or both sentences within the bullet should be modified to an affirmative assertion.

**Comment by aratliff** [comment]
Correct.

Prior to adding a remote domain corresponding to the accepted domain/tenant e-mail address domain, all messages sent to external and internal recipients would always come across in the same message format for both recipients.

To test this uncertainty, I've set the default remote domain RTF format option to "Always" & set same setting on the remote domain that reflects the internal domain to "Never".  RTF formatted messages sent to an external domain recipient were received as RTF, while the internal domain recipient received these same messages as HTML.

Deleting the remote domain reflecting the internal domain resulted in the previous behavior of both messages being received as RTF once more.

**Comment by aratliff** [comment]
As an afterthought & on the topic of whether or not this bullet even needs to be included; this draws parallels to the no-U turn dilemma: https://en.wikipedia.org/wiki/No_U-turn_syndrome.

I believe that therealscottcarlow (as did I initially) interpreted this bullet's mere presence, although containing two conflicting assertions, to imply that this activity was prohibited (the "U-turn ok unless posted otherwise" mindset).

On a larger scale, it may be more intuitive to entirely re-dub the concept of "remote domains" to "recipient domains" wherein an exclusion of internal domains is not implied by the overarching name of the configuration item.

**Comment by lindspea** [comment]
Ok thanks @aratliff . Just so I don't miss anything, what is the final PR I must do and must it just include the original wording I suggested above? What other wording?

**Comment by chrisda** [comment]
@aratliff, @therealscottcarlow, @lindspea, the first issue was a simple typo (the intent was for both sentences to say "can't"). I would have sworn up and down there was a period of time where you couldn't configure an accepted domain as a remote domain.

I can say that the obvious intent of remote domains is just that: message options for external domains. You can also tell by many of the settings (e.g., what good is it to allow only external OOF messages for recipients in an internal domain?). Looking at old Exchange 2010 documentation, I think the intent of allowing internal domains as accepted domains is related to Hybrid (on-premises + cloud) environments, but that's more of a guess.

I guess the best course of action is to remove that entire bullet and other such language in the topic (and its parent conceptual topic).

Thanks for the feedback.
