### ISSUE TITLE
Will Exchange 2013 eventually be supported with DCs running Windows 2019?

### ISSUE THREAD

**Issue by turbosnute** [MicrosoftDocs/OfficeDocs-Exchange#748]
Will Exchange 2013 eventually be supported With DCs running Windows 2019? We are in a situation where we want to upgrade the DCs to 2019 but we can't upgrade Exchange to 2019 yet.

**Comment by scanum** [comment]
@turbosnute  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
