### ISSUE TITLE
dsacls.exe not on Azure AD Connect server

### ISSUE THREAD

**Issue by mardahl** [MicrosoftDocs/OfficeDocs-Exchange#749]
The powershell commands required, faile because DSACLS is not on the Azure AD DS Connect server. 
I have manually run the DSACLS commands on a Domain Controller, but am unsure if this is enough, or the script wanted to do more...
Please fix the documentation to support those that have standalone Azure AD Connect servers, that have no other roles installed.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/da-dk/exchange/hybrid-deployment/set-up-office-365-groups#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by mardahl** [comment]
MAybe add to the documentation, that one could install RSAT on the AAD Connect server.

**Comment by j0rt3g4** [comment]
Hello, @mardahl I'm sorry can you give us a bit more information on what script were you running?

is it listed on this article?

From my perspective, if you have Azure AD connected it **syncronizes** what is on your AD with the cloud (O365, or Azure AD). It doesn't have to be installed anything else on the Azure AD Connect server to work correctly.
Now, if you wanted to use DSACLS, that's something that should be done on a computer with RSAT or AD DS roles installed.  Not sure why you want to update this document when doesn't have references to DSACLS.

**Comment by mardahl** [comment]
I understand the confusion.
But on a brand new plain Windows Server 2016, with ONLY AAD Connect installed.
Following this guide, lead me to alot of errors in setting permissions on the OU I designated as the Groups Writeback OU.

Specifically stating something about DSACLS.exe missing

The errors are not clear in my head now, and I dont have a lab running for this sort of stuff. Unfortunately.

But if the latest version of AAD Connect already sets the permissions without the commands in this doc, then all is well I guess :)

**Comment by j0rt3g4** [comment]
@mardahl  I've added it as a "known issue" that if it's required to manage permissions with DSACLS.exe must have RSAT or Latest AAD Connect.

**Comment by scanum** [comment]
@mardahl Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
