### ISSUE TITLE
SMTP relay using IIS with Office 365

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-Exchange#750]
This article is fundamentally incorrect:
This article mentions that we use port 587 for SMTP relay which should be port 25. (Port 587 is used for the Client Submission scenario).
It also mentions that we need to use Basic authentication on the Outbound Security tab which is incorrect, this should be anonymous.
Outbound connections is port 25.
Smarthost address [SMTP.office365.com] is also incorrect. The Smarthost to be used is the domains EOP MX record like contoso-com.mail.protection.outlook.com

Basically this article currently describes the "Client Submission" scenario implemented on IIS instead of "SMTP Relay" while the title says: "Set up Exchange Online as an SMTP Relay Using Windows Server".
This is the article that describes SMTP Relay with Office 365 (without the IIS part)
https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#option-3-configure-a-connector-to-send-mail-using-office-365-smtp-relay

This article has always been incorrect. I thought to mention this since there is a lot to improve in it.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e73bb3c6-ab71-066f-18e8-f0726cebf9d2
* Version Independent ID: 16e49af3-9980-d928-7667-ee8f5e07c487
* Content: [How to configure IIS for relay with Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-configure-iis-for-relay-with-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @SuPotter
* Microsoft Alias: **supotter**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by FuryoftheStars** [comment]
I'm glad I saw this comment down here as this article is titled exactly for what I was looking for, "How to configure IIS for relay with Office 365".  Following the corrections Jeroen pointed out has allowed this to work as I desired.

It would definitely be good to get this article properly updated for the method in the article title, and maybe also update it for your newer releases of Windows Server, like 2016 and 2019 (2019 being what I'm using).

**Comment by TokyoScarab** [comment]
Hello!  Thank you for raising this issue!  I will be looking into this and updating the documentation.

**Comment by MCFHTAGENTS** [comment]
It seems this IIS component does not support IPv6. When we are running a full IPv6 network what is the recommended approach?

**Comment by scanum** [comment]
@TokyoScarab

**Comment by TokyoScarab** [comment]
Hey @JeroenDronkers !  Just wanted to check in with your IPv6 question.  I would suggest checking out this [page](https://docs.microsoft.com/office365/enterprise/ipv6-support) for more information on IPv6 support in Office 365.  If you have any further questions, make sure to follow up with us!  Thanks!

**Comment by JeroenDronkers** [comment]
Hello,

I don’t think my question was IPv6 related tbh.
The comment about IPv6 came from MCFHTAGENTS<https://github.com/MCFHTAGENTS>

https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/750



Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>
[Microsoft Logo]
Backup | Alisdair Douglas (Alisdair Douglas (aldoug@microsoft.com)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

**Comment by TokyoScarab** [comment]
@JeroenDronkers  Sorry, I had tagged the wrong name in my post.

**Comment by TokyoScarab** [comment]
> 
> 
> It seems this IIS component does not support IPv6. When we are running a full IPv6 network what is the recommended approach?

Hey @MCFHTAGENTS , I just wanted to check in with your IPv6 question.  I would suggest checking out this [page](https://docs.microsoft.com/office365/enterprise/ipv6-support) for more information on IPv6 support in Office 365.  If you have any further questions, make sure to follow up with us!  Thanks!

**Comment by MCFHTAGENTS** [comment]
Hi there - this isn’t about IPv6 support in office 365 but about the fact the SMTP relay component in IIS doesn’t support IPv6
Thanks
Nark

**Comment by TokyoScarab** [comment]
The page I linked goes into detail about what to consider when using IPv6 with Office 365.  The page states that even though Office 365 is compatible with both IPv4 and IPv6, it recommends using both IPv4 as well as IPv6 since not all features in Office 365 are fully enabled with IPv6.

**Comment by JeroenDronkers** [comment]
Hello All

Please forget IPv6!
My original request to change the article has ended up in an unrelated IPv6 discussion!

I don’t care about IPv6 and IIS and most customers that are implementing relay with O365 using IIS won’t be interested in it either. The rest of the article needs to be updated as per my comments since the entire article is incorrect.


Kind regards

--
Jeroen Dronkers
Support Escal Eng
Eq-Uk Gtsc Bizapps Server
Customer Services and Support
Office: +44 (118) 9095507
jedronke@microsoft.com<mailto:jedronke@microsoft.com>
[Microsoft Logo]
Backup | Alisdair Douglas (Alisdair Douglas (aldoug@microsoft.com)
Team Manager | Frances Early (francese@microsoft.com<mailto:francese@microsoft.com>) +44 (20) 34251539

**Comment by scanum** [comment]
@JeroenDronkers 
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by jonimattila** [comment]
We had this configured like previous documentation and was working until today "dropped by remote host" failure, changed to anonymous and port 25 then smtp relay started working again after iis reset.
