### ISSUE TITLE
Outlook for iOS and Android - Deploy app config settings

### ISSUE THREAD

**Issue by Peadarp** [MicrosoftDocs/OfficeDocs-Exchange#751]
If I create an app configuration policy for Outlook on iOS Managed Devices, the additional configuration settings are not retained when saved.
Settings as described here:

**App Configuration Policy**
**Device enrollment type:** Managed devices
**Platform:** iOS
**Associated app:** Microsoft Outlook
**Configuration settings format:** Use configuration designer

**Additional configuration** 
**CONFIGURATION KEY:** IntuneMAMUPN
**VALUE TYPE:** String
**CONFIGURATION VALUE:** {{UserPrincipalName}}

This has worked previously, but after saving and closing the policy, the settings are not visible when the policy is reopened.

Document referenced:

Outlook for iOS and Android
- Deploy app config settings

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#organization-allowed-accounts-mode-settings-1

**Comment by smithre4** [comment]
This is a side effect of “Allow only work or school accounts” as that setting configures IntuneMAMUPN automatically behind the scenes for the policy. A configuration key cannot be configured automatically and exposed manually in the Additional Configuration grid. However, even though IntuneMAMUPN appears to disappear after saving the policy, your manual configuration is preserved.  You can verify using MobileAppConfiguration PowerShell module. We're investigating how we can improve this.

See https://techcommunity.microsoft.com/t5/Intune-Customer-Success/New-Outlook-for-iOS-and-Android-App-Configuration-Policy/ba-p/370481 for more information.

**Comment by Peadarp** [comment]
Thanks Ross.
You've answered my question, but it throws up another question for me.
The Cut/Copy/Paste restriction via App Protection Policy isn't working for Outlook on iOS. I can copy Org data and paste it into unmanaged native apps. I was working off the assumption that the IntuneMAMUPN setting was the root cause. Back to the investigation.

Cheers
P

**Comment by smithre4** [comment]
That's odd and not an issue we're tracking presently (it works in my lab and production environments). The policy may not be correctly applied. Either through the managed browser or Edge, you can use about:intunehelp to view the policy that is applied to Outlook. ClipboardSharingLevel is the setting and if it is set to 3 that means any app. A support case may be needed to troubleshoot, otherwise.

**Comment by Peadarp** [comment]
Thanks again, Ross.
On the face of it, everything looks right. All my checks have reported back the settings as per required configuration. For whatever reason, the ClipboardSharing isn't enforced at level 2 for Outlook Mobile on iOS, but is for all other Office apps. All apps are targetted with the same policy. I'll keep digging.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Peadarp  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
