### ISSUE TITLE
MSOnlineExtended module doesn't exists

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-Exchange#753]
This module name is incorrect and it has been a long time around without a response from Microsoft.

https://social.msdn.microsoft.com/Forums/en-US/73512b3a-b186-4ad0-9b1d-507c285b4103/how-to-install-msonlineextended-module-?forum=WindowsAzureAD

**Comment by j0rt3g4** [comment]
This error will be addressed on the PR #754

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hi there @scanum .
can you ask for copy review or close this issue (since has been resolved with PR #754 .
Ty!

**Comment by j0rt3g4** [comment]
@scanum Solving this issue on PR #803
