### ISSUE TITLE
[LOC] Broken link in multiple articles

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#755]
Invalid links across multiple articles

**Repro steps:**
Go to https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/manage-ha?view=exchserver-2019 , https://docs.microsoft.com/en-us/exchange/exchange-admin-center , https://docs.microsoft.com/en-us/exchange/architecture/client-access/exchange-admin-center?view=exchserver-2019
Search the source of the pages for "http://technet.microsoft.com/library/06df16b4-f209-4d3a-8c68-0805c745f9b2.aspx" link
Click on the link
**Actual results:**
Link is not working

**Expected results:**
Link should be working

**GH articles:**
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/manage-ha/manage-ha.md
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/exchange-admin-center.md
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/exchange-admin-center.md

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
Broken link found in these topics:

exchange-admin-center.md
activate-db-copies.md
activate-lagged-db-copies.md
add-db-copies.md
configure-activation-policies.md
configure-db-properties.md
manage-ha.md
remove-db-copies.md
suspend-resume-db-copies.md
update-db-copies.md

Valid topic is Manage mailbox database copies (manage-database-copies.md). Relative location varies depending on the topic that holds the link (in which folder structure).

Closing
