### ISSUE TITLE
[LOC] Broken link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#756]
there is a broken link in an article

**repro steps**
1. Go to https://docs.microsoft.com/en-us/exchange/clients/pop3-and-imap4/configure-pop3?view=exchserver-2019
2. Search for "Client access protocol architecture"
3. Click on the link

**Actual results:**
Link is not working
**Expected results:**
Link should be working

**GH article**
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/pop3-and-imap4/configure-pop3.md

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
This was a old-style bookmark link in a known, good topic. I simply changed the link to the current GitHub syntax (architecture.md#client-access-protocol-architecture).

Closing
