### ISSUE TITLE
[LOC] Invalid link across multiple topic

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#757]
Nonfunctional link in multiple articles

Could you please scan the whole repository for the following link "http://technet.microsoft.com/library/4abde67b-4995-4a57-894f-ba76aa72341c.aspx" and fix the link ?

Thank you.

Example of an article where the link is - https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/configure-dag-network-properties?view=exchserver-2019

**GH link**
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/manage-ha/configure-dag-network-properties.md

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
Found in the following ExchangeServer topics:

exchange-admin-center.md
recover-dag-member-servers.md
configure-dag-autoreseed.md
configure-dag-network-properties.md
create-dag-networks.md
create-dags.md
dag-memberships.md
manage-ha.md
remove-dags.md

Replaced all with "Manage database availability groups" (manage-dags.md); location varies depending on where the source topic lives.

Closing
