### ISSUE TITLE
Table needs to be cleaned up

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-Exchange#76]
The table "What if I have EOP or Exchange Online and my own email servers?" needs to be cleaned up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cc74a5d-5f48-0d14-d80b-d654dd33c934
* Version Independent ID: 2eb3f77f-f4e2-03c9-9bb2-e108aadce39f
* Content: [Configure mail flow using connectors in Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @SuPotter
* Microsoft Alias: **supotter**

**Comment by dstrome** [comment]
hi @dkotars ,

Thanks for your feedback! We just corrected the table and it should be readable again.
