### ISSUE TITLE
verified DNS before migration

### ISSUE THREAD

**Issue by enjbookkeeping** [MicrosoftDocs/OfficeDocs-Exchange#765]
How do I still migrate or get all my emails over from GSuite to 365?
I need to cancel my gsuite account but haven't until i figure out how to get my emails. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate G Suite mailboxes to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@enjbookkeeping We are encouraging all customers to contact Microsoft FastTrack https://www.microsoft.com/fasttrack/?rtc=1 for help with their migrations. They could answer your questions about mail flow during a migration.
