### ISSUE TITLE
Sufiyang

### ISSUE THREAD

**Issue by yang980** [MicrosoftDocs/OfficeDocs-Exchange#767]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 50117f9a-45dd-90fb-a592-6a12c6104875
* Version Independent ID: d07fe199-59af-86bf-fe79-c7e2d342a463
* Content: [Single sign-on with hybrid deployments](https://docs.microsoft.com/th-th/Exchange/single-sign-on)
* Content Source: [Exchange/ExchangeHybrid/single-sign-on.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/single-sign-on.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by chrisda** [comment]
ฉันใช้ Google แปลสิ่งนี้: คุณมีความคิดเห็นเฉพาะเกี่ยวกับหัวข้อนี้หรือไม่?

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@yang980  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
