### ISSUE TITLE
So can I install PowerShell 5.0 on Exchange 2013 or not?

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/OfficeDocs-Exchange#768]
That section about PowerShell doesn't say enough. Be explicit. This page is called "Supportability Matrix". Make a "matrix" and specify what is and is not compatible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cparker4486, do you have any specific suggestions or clarifications you'd like to see? The point is: use the version of Windows PowerShell that's included on your version of Windows Server; don't download and install other versions of the WMF. It doesn't really matter which version of Windows PowerShell is included in a particular version of Windows.

**Comment by cparker4486** [comment]
Hi Chris,

My suggestion was to `make a "matrix" and specify what is and is not compatible`. (I don't repeat that as sarcasm.)

Having said that, I like the summary you just wrote.

Looking back at the original, I believe my confusion was over the use of the word "system". You wrote "Windows Server" which is more specific. I interpreted "system" to mean "installed version of Exchange" thinking Exchange brought its own version with it.

Thank you.

**Comment by chrisda** [comment]
@cparker4486, I can see how that "system" language would be confusing. I updated the text a bit to clarify Windows where appropriate. I'd really rather not add a Windows and Windows PowerShell table to that section. The supported versions of Windows are well documented elsewhere in the topic, and the version of Windows PowerShell that's included in that version of Windows is basically a side effect.

Thanks for the feedback.
