### ISSUE TITLE
Archive Mailboxes in Exchange Online 

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-Exchange#77]
The Link for "Archive Mailboxes in Exchange Online" redirects to "https://docs.microsoft.com/en-us/office365/securitycompliance/eop/exchange-online-protection-overview"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad9b8bf-d3d8-fe08-9c6f-04cd7643ac3e
* Version Independent ID: 516f4807-102e-aa11-9669-c379305045d1
* Content: [Security and compliance for Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/security-and-compliance)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/security-and-compliance.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/security-and-compliance.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
fixed; this link now points to enable archive mailbox topic on support.office.com

https://docs.microsoft.com/en-us/exchange/security-and-compliance/security-and-compliance  

Note that on Aug. 21st this topic on enabling archive mailboxes will be migrated to docs.
