### ISSUE TITLE
Migrate to SCC Retention Policy

### ISSUE THREAD

**Issue by toddjohnson39** [MicrosoftDocs/OfficeDocs-Exchange#770]
Is there guidance on how to migrate from Litigation and In-place Hold to SCC Retention Policy? For instance, create/apply new SCC Retention Policy, then clean up remove Litigation Hold or In-Place Hold from mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c38acb1-6f67-3c4c-fa3f-7d0ca7b257c0
* Version Independent ID: 673af28f-4de4-ec12-6428-6346142d20d3
* Content: [In-Place Hold and Litigation Hold](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-and-litigation-holds)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@toddjohnson39 The content and engineering team is currently looking into this documentation gap. Until this is addressed, here's a few things to keep in mind.
- Most importantly, if you do transition to Office 365 retention policies, be sure not to remove the hold immediately after applying the retention policy; wait some time (e.g. at least 24 hours) for the retention policy to take effect.
- Different types of holds can exist side by side.
- If multiple holds are on a mailbox, there would be an order of precedence that is described here: https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#the-principles-of-retention-or-what-takes-precedence
- Retention policies can also be configured to delete content, which LitHold and InPlaceHolds don't do.

As an FYI, here's a topic about how to identify the different type of holds on a mailbox: https://docs.microsoft.com/en-us/office365/securitycompliance/identify-a-hold-on-an-exchange-online-mailbox

Hope this helps a little bit.
