### ISSUE TITLE
Would be great if you could list the specific Outlook version numbers

### ISSUE THREAD

**Issue by campbellkerr** [MicrosoftDocs/OfficeDocs-Exchange#772]
Eg, "Outlook 2010 SP2" - this can be difficult to track down, normally when checking versions it will show as 14.0.01888

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2016#network-and-directory-servers)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@campbellkerr, an interesting idea, but difficult to manage. The title of the section is "Supported clients (with latest updates)". The build number of each client to change month to month based on updates. So it doesn't particularly matter what your build number is, just as long as you are current.

Of course, if there was a minimum hotfix or security update that you needed to be at, we would say that.
