### ISSUE TITLE
2019 active directory with exchange 2016

### ISSUE THREAD

**Issue by googol13** [MicrosoftDocs/OfficeDocs-Exchange#776]
Why is this not supported yet? There's no domain or forest functional level. 
Why should I waste my time upgrading from 2012r2 to 2016 when I can go to 2019? Did someone forget to update the page? Server 2019 has been out for 6+ months. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by michelderooij** [comment]
Seems like an omission indeed, for reference
https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2019

**Comment by googol13** [comment]
That shows exchange 2019, this is for exchange 2016.

Need server 2019 directory server (AD) with exchange 2016 listed as supported.

**Comment by chrisda** [comment]
@googol13, @michelderooij, it's all about testing and fully vetting the experience. When it's ready, the announcement will be made in the EHLO blog https://blogs.technet.microsoft.com/exchange/ or (depending on the timing) its new home (see [this post](https://techcommunity.microsoft.com/t5/custom/page/page-id/Blogs) for details).

**Comment by googol13** [comment]
But it has been out for 6+ months? Theres only one attribute change, theres no FFL changes, so what else is there?
