### ISSUE TITLE
Update tracking for this page

### ISSUE THREAD

**Issue by sime3000** [MicrosoftDocs/OfficeDocs-Exchange#781]
Hello,
I've noticed that this page has been updated periodically over the last few months - thank you very much for that.
How can we determine what has changed when the page is updated ? - this is a rather lengthy article and it takes a long time to scan it and try and guess what changed.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cb35a6e-8f40-dd57-05e7-a60e18a7ba37
* Version Independent ID: c00115b5-4e3b-7764-8d3f-2023b913ccd0
* Content: [Exchange Server supportability matrix](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by michelderooij** [comment]
When you view the page on GitHub, there's a History button where you can view the the individual change commits (and drill down per change to see the differences), or view Blame where you can view the page as it is, and when a particular paragraph was modified and by whom.

**Comment by sime3000** [comment]
Thanks. I was looking at the blog page and not on GitHub.
On GitHub there isn't a "History button" that I see but if you select "Code" and drill down on some of those items you will get a history of sorts with many different paths that you can drill down even further on. Is that where the history of the changes to the "Exchange Server supportability matrix" page is?

**Comment by michelderooij** [comment]
It's in the individual commits, for an overview for the current status you can check Blame:
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blame/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md

**Comment by chrisda** [comment]
@sime3000, or when you click on [History](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/commits/public/Exchange/ExchangeServer/plan-and-deploy/supportability-matrix.md) and then click on the individual commit (the bold title on the left side of the page), it will show you the changes in that particular commit. Additions are green, deletions are red.
