### ISSUE TITLE
Need old exchange source files

### ISSUE THREAD

**Issue by MHMRD** [MicrosoftDocs/OfficeDocs-Exchange#782]
Dear Microsoft team
I need to download previous build numbers of MS Exchange 2016 ( Cu4).
I have to recover and old version of exchange server and now I don't have source files in place.

How can you help me?

**Comment by michelderooij** [comment]
Previous releases might be obtained by contacting support.

**Comment by chrisda** [comment]
@MHMRD, I updated [this topic](https://docs.microsoft.com/Exchange/high-availability/disaster-recovery/recover-exchange-servers?view=exchserver-2016) within the last year, and I was assured the following information is correct (like you, I was skeptical):

> You can recover a server using the latest available Cumulative Update (CU). Only the last two CUs are available for download. For more information, see [Updates for Exchange Server](https://docs.microsoft.com/Exchange/new-features/updates?view=exchserver-2016).

Report back here if this is incorrect.

**Comment by scanum** [comment]
@officedocsbot assign @scanum
