### ISSUE TITLE
Error running Exchange2003MBtoMEU.vbs

### ISSUE THREAD

**Issue by bigbruce7** [MicrosoftDocs/OfficeDocs-Exchange#783]
I get the following error when run the vbs script: Exchange2003MBtoMEU.vbs(37, 54) Microsoft VBScript compilation error: Expected ')' ***** script completed - exit code: 1 *****

I am novice when it comes to vbs any help would be appreciated.

Bruce Miller

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ccb7e0-b189-1164-2ddf-1bda22806ae9
* Version Independent ID: 202536f7-50bf-b1da-27ab-9a3f46e0f8a8
* Content: [Convert Exchange 2003 mailboxes to mail-enabled users](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-a-staged-migration/convert-exchange-2003-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-a-staged-migration/convert-exchange-2003-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-a-staged-migration/convert-exchange-2003-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@bigbruce7 sorry you are having issues with your migration. We are encouraging all customers to contact Microsoft FastTrack https://www.microsoft.com/fasttrack/?rtc=1 for help with their migrations.
