### ISSUE TITLE
Single node dag as recommendation

### ISSUE THREAD

**Issue by agowa338** [MicrosoftDocs/OfficeDocs-Exchange#785]
Please change the recommended setup to a single node cluster.
This has additional scalability benefits and also allows simplified automation of the whole setup procedure.
It has no downsides compared to a standalone setup without a DAG and should therefore be considered to be the standard method of installing exchange.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@agowa338  - thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make SharePoint better . They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice https://sharepoint.uservoice.com/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!

**Comment by scanum** [comment]
@officedocsbot close

**Comment by agowa338** [comment]
@scanum Wrong issue or just typo? I'm talking about Exchange not about Sharepoint.
