### ISSUE TITLE
synchronization of the users' on-premises data takes about 24h

### ISSUE THREAD

**Issue by Hoegimator** [MicrosoftDocs/OfficeDocs-Exchange#787]
We are setting up Intune and using hybrid Modern Authentication with Outlook for iOS and Android. On the first connection it takes about 24h until the user can see his emails.

**Comment by Left-HandCreations** [comment]
Good and thank you, it's worth waiting 24 hours if I can get my iCloud.com emails from iOS

**Comment by Hoegimator** [comment]
> Good and thank you, it's worth waiting 24 hours if I can get my iCloud.com emails from iOS

Not Good at all. If we integrate all our business phones and everybody is without email for 24 hours.

**Comment by scanum** [comment]
@Hoegimator  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
