### ISSUE TITLE
Problem with DAG parameters

### ISSUE THREAD

**Issue by MrSundh** [MicrosoftDocs/OfficeDocs-Exchange#789]
On step 1 when running "Manage-MCDB -ConfigureMCDBPrerequisite" it runs a background function named "Validate-DagParameters" witch validates that the folloeing parameters are not Null or 0:
- AutoDagDatabaseCopiesPerVolume
- AutoDagTotalNumberOfDatabases
- AutoDagDatabaseCopiesPerDatabase
- AutoDagTotalNumberOfServers

To set these you should use Set-Database​Availability​Group but 3 of these parameters only have "This parameter is reserved for internal Microsoft use." in the documentation.

Any input on this would be most helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9143a35-a7db-43f6-6a76-47a5ea08fc91
* Version Independent ID: 0cbd5f28-45fb-b438-0510-8958816d2995
* Content: [MetaCacheDatabase (MCDB) setup](https://docs.microsoft.com/en-us/exchange/high-availability/database-availability-groups/metacachedatabase-setup?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/high-availability/database-availability-groups/MetaCacheDatabase-setup.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/database-availability-groups/MetaCacheDatabase-setup.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lusassl-msft** [comment]
@MrSundh is your DAG ready for Auto-Reseed (https://docs.microsoft.com/en-us/Exchange/high-availability/database-availability-groups/autoreseed?view=exchserver-2019)? This is a requirement for MCDB.

**Comment by scanum** [comment]
@MrSundh  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by MrSundh** [comment]
Hi again.
Sorry for my lack of response.
Our DAG is configured for autoreseed as follows:

AutoDagSchemaVersion             : 1.0
AutoDagDatabaseCopiesPerDatabase : 1
AutoDagDatabaseCopiesPerVolume   : 1
AutoDagTotalNumberOfDatabases    : 0
AutoDagTotalNumberOfServers      : 0
AutoDagDatabasesRootFolderPath   : C:\ExchangeDatabases
AutoDagVolumesRootFolderPath     : C:\ExchangeVolumes
AutoDagAllServersInstalled       : False
AutoDagAutoReseedEnabled         : True
AutoDagDiskReclaimerEnabled      : True
AutoDagBitlockerEnabled          : False
AutoDagFIPSCompliant             : False
AutoDagAutoRedistributeEnabled   : True
AutoDagSIPEnabled                : False
AutoDagDiskReclaimerEnabled : True

The DAG contain 13 databases spanned across 6 server, each with 9 database disks. Only on database is stored per volume. Databases have 4 copies including 1 copy with 14 Days lag.
No online spare disks.
The database disks are 4GB each and there is 3 1GB SSD disks per server to handle the future MetaCacheDatabase.

The command used in my previous try to configure the MCDB was:

Manage-MCDB -DagName OurDAGName -ConfigureMCDBPrerequisite -SSDSizeInBytes 959925190660 -SSDCountPerServer 3 

What I see as a first step is to figure out values for AutoDagTotalNumberOfDatabases and AutoDagTotalNumberOfServers as they are 0 today.

AutoDagTotalNumberOfDatabases, spontaneously it feels like 13 in our case, but then the question is whether it is what is meant or if it is inclusive of all copies which would be 13 * 4 = 52.

AutoDagTotalNumberOfServers, should be 6 if it is not meant the number of servers a database copies span, then it should be 4.
