### ISSUE TITLE
Little spanish text fixing

### ISSUE THREAD

**Issue by vivesg** [MicrosoftDocs/OfficeDocs-Exchange#79]
https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/configure-custom-mailtips
"This mailbox is not monitored." -- En -- &gt; ES "Este buzón no se supervisa"
Set-Mailbox -MailTipTranslations @{Add="ES:Esta caja no se supervisa."}
Translation of the spanish text is wrong 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4cf8892-771b-e40d-2036-79672516de05
* Version Independent ID: fe2f2228-34b5-e10f-bca9-ce76deefd2d8
* Content: [Configure custom MailTips for recipients](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/configure-custom-mailtips)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/configure-custom-mailtips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/configure-custom-mailtips.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Hi, thank you for your feedback. Our documentation is localized into many languages, but code samples and examples, which is the case here, are not localized. Feel free to provide a correct translation of your own and we'll work to get it added to the source article.
