### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by smlgiorgetti** [MicrosoftDocs/OfficeDocs-Exchange#790]
https://go.microsoft.com/fwlink/p/?linkid=866249

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f41f96e-25f1-b5b2-0183-973d1f8e511e
* Version Independent ID: 22a4972e-4bab-c38f-0a96-5c9d97728f38
* Content: [Remote domains in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/remote-domains/remote-domains#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/remote-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/remote-domains/remote-domains.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@smlgiorgetti, OK. Fixed. The fwlink works now.

Thanks for the feedback.
