### ISSUE TITLE
Hybrid configuration with Exchange 2010 Edge server

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/OfficeDocs-Exchange#791]
When configuration a Hybrid relationship with a 2010 Edge server, the HCW does not pick up the Edge server unless custom scripting is executed on the environment to get them to sync, as such, we would need to have some specifications about what needs to done. Or then it would require a mention that it is not supported out of the box and requires additional steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1c5c767-7732-ddb7-d11d-63f659a65bf0
* Version Independent ID: 0ed7596b-3fd1-7b73-b555-299d8bea81ed
* Content: [Edge Transport servers with hybrid deployments](https://docs.microsoft.com/en-us/exchange/edge-transport-servers#feedback)
* Content Source: [Exchange/ExchangeHybrid/edge-transport-servers.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/edge-transport-servers.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by loumandich** [comment]
The Exchange Deployment Assistant contains the information on how to configure Edge w/Edge Sync when the HCW is used with Exchange 2010 and Edge configurations.

**Comment by v-olduch** [comment]
The reason for this comment was to provide a unique source of truth so that Edge Server configuration could be found in one location. Although useful, the Deployment assistant requires the user to go through the whole deployment guide. Admin tend to prefer to find the information in a document so they can retrieve the specific information they are looking for without having to go through the Deployment Assistant every time.

**Comment by lindspea** [comment]
@v-olduch Thank you for reaching out and helping improve MS Docs.  Are there any steps you recommend to have added to the article?

**Comment by v-olduch** [comment]
Hi Lindsay,

As a matter of fact I would have a few recommendations. Let me organize that in a structured manner and I can post that here shortly.

**Comment by lindspea** [comment]
@v-olduch Sounds great!  Thanks for the help, greatly appreciated.

**Comment by scanum** [comment]
@v-olduch Hi, any updates on this? Thanks!

**Comment by v-olduch** [comment]
Yes, sorry for the delay, I am redacting the content on the side while delivering presentations and workshops to customers. I am hoping to have the content finalized for this coming Friday (05/17).

**Comment by v-olduch** [comment]
Sorry for the delay, I was going towards something perhaps too specific and reviewed with colleagues. I would have three recommendations:

1. Need to state explicitly that an Edge Subscription is required for Exchange Hybrid.

2. Insert a note about how Edge server will impact your mail flow:
Installing an Edge server and establishing an Edge subscription will have an impact on your mail flow. This process automatically creates two Send connectors for Internet mail flow, one configured to send e-mail to all Internet domains and another to send e-mail from the Edge Transport server to the Hub Transport server. Please review the connectors and mail flow if this is not your intended mail flow scenario.

3. Link to the Exchange Server Deployment Assistant:
https://technet.microsoft.com/en-us/exdeploy2013/ (For Exchange 2010)
https://aka.ms/eda (Does not include guidance for Exch2010)

**Comment by scanum** [comment]
@v-olduch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
