### ISSUE TITLE
Troubling ambugity with units in Factor 2

### ISSUE THREAD

**Issue by ImperatorRuscal** [MicrosoftDocs/OfficeDocs-Exchange#793]
Under Factor 2 it is noted that "...we have achieved consistent 30 GB/hour throughput..."  This makes sense as GB (Gigabyte) is an appropriate and common measure for storage volume.
The condition where this was observed is listed as "Network 500-MB outbound pipe to the Internet..."  This doesn't make sense; network connection bandwidth is measured as volume/time, and the volume is commonly measured in bits instead of bytes.  Is this supposed to be 500 Mb/s (Mbps -- common network bandwidth uniti of measure)?   (500 MB/s would be the same as 4000 Mbps...)  I think it should be 500 Mbps, but the ambiguity has lead to questions from my management and I'd like to have the official source be more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e039381-d57f-0a0f-18d5-933193b3e46a
* Version Independent ID: db0172fb-26a7-6833-a8f3-6d5609a10e16
* Content: [Performance factors and best practices for hybrid migrations](https://docs.microsoft.com/en-us/exchange/performance-best-practices#feedback)
* Content Source: [Exchange/ExchangeHybrid/performance-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/performance-best-practices.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ImperatorRuscal Thanks for pointing this out and helping improve MS Docs.  I'm looking into this with the team and will revert soonest.

**Comment by scanum** [comment]
@ImperatorRuscal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
