### ISSUE TITLE
Setting -OutlookMobileGCCRestrictionsEnabled to $false does not re-enable add-ins

### ISSUE THREAD

**Issue by alanraylloyd** [MicrosoftDocs/OfficeDocs-Exchange#795]
Our tenant was recently moved over to the native sync technology, and with that, we decided to disable the Outlook Mobile GCC Restrictions because we didn't want to lose functionality of add-ins and multiple account types. 

Upon disabling the restrictions, our users regained the ability to add personal accounts into the app. However, add-ins still appear to be disabled. There is no add-in option in the settings menu, and none of our add-ons appear when pressing the vertical dots button on a message. 

Is this by design? If so, this page needs to be clarified to state that add-ins will not be available regardless of the setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba22add1-5185-c5b2-8520-c47855559a7a
* Version Independent ID: f79f12a8-fb77-5a0f-d152-441394373673
* Content: [Using Outlook for iOS and Android in the Government Community Cloud](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-in-the-government-cloud)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-in-the-government-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-in-the-government-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@alanraylloyd I raised your question with the product team and they say that this is a bug. The Add-ins should not be disabled. I don't have a timeline of when this will be fixed, but now that the product team is aware it hopefully shouldn't take too long. Thanks for the feedback and for bringing this to our attnetion.
