### ISSUE TITLE
Commands are no longer functional with the directions attached to setting up the modules 

### ISSUE THREAD

**Issue by buglessdr** [MicrosoftDocs/OfficeDocs-Exchange#796]
All the commands on this page need to be deprecated as they no longer use AzureRm but instead use: az

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45c04a0-138f-8241-0726-01fb09c3dfeb
* Version Independent ID: 730303a8-9c6f-472c-79f6-96453dea3013
* Content: [Exchange dev/test environment in Azure](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@buglessdr This was on my list to update. Thanks for the push. Te updated version of this article now uses the new Az command set.
