### ISSUE TITLE
Confusion about Organizational limits

### ISSUE THREAD

**Issue by CarolWangMS** [MicrosoftDocs/OfficeDocs-Exchange#798]
In the organizational limits section, the note says “Since the identity of unauthenticated (anonymous) senders can't be established, inbound messages from external senders are subject to the maximum sent message size organizational limit. Likewise, outbound messages to external recipients are subject to the maximum received message size organizational limit.”

This seems strange. I thought an inbound message from external sender should only subject to the max receive message size organizational limit and the outbound message to external recipient should only subject to the max send organizational limit. And the other document also says,
“The MaxReceiveSize parameter specifies the maximum message size that can be received by recipients in the organization. The default value is 10 MB.”
“The MaxSendSize parameter specifies the maximum message size that can be sent by senders in the organization. The default value is 10 MB.”
https://docs.microsoft.com/en-us/powershell/module/exchange/mail-flow/set-transportconfig?view=exchange-ps  

Do you mean any cross-organization message should subject to both max send and receive organizational limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a512e6f-47ab-f785-a792-ef82a552c50f
* Version Independent ID: 16869db1-342d-13f2-ce24-0e13a49ec68d
* Content: [Message size limits in Exchange Server](https://docs.microsoft.com/en-us/Exchange/mail-flow/message-size-limits?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/mail-flow/message-size-limits.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/message-size-limits.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@CarolWangMS, yeah, sorry about that. I was attempting to simplify an update request from last month: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/commit/22b6390f0470e717b327cfcc703d6701519a5e34#diff-77248a905dcb676d945cb49ff5935675 and I probably made it worse.

Outbound from Exchange to the internet is an internal sender and an external recipient. The internal sender can have Exchange user-specific message **send** limits applied to them, but the external recipient can only have the organizational message **receive** limits applied to them.

Inbound from the internet to Exchange is an external sender and an internal recipient. The internal recipient can have Exchange user-specific message **receive** limits applied to them, but the external sender can only have the organizational message **send** limits applied to them.

So, if you have large internal user send/receive max message sizes, but small organization send/receive max message sizes, the big messages won't make it to external recipients. Or, if you have big organization send/receive max message sizes, but small user send/receive message sizes for a specific subset of users, the internal users can't receive the big messages from external senders. This situation was already (mostly) explained in the "Order of precedence and placement of message size limits" section before the update request.

I updated the topic to make things more clear. Please comment if it's still confusing.

Thanks for the feedback

**Comment by CarolWangMS** [comment]
Thank you for you kind reply.
Take Outbound from Exchange to the internet as example. The message will subject to:
1) connector limits
2) server limit
3) mail flow limit
4) internal sender's user-specific message send limit
5) organizational message send limits for the internal sender
6) organizational message receive limits for the external recipient

Is this the right understanding?

**Comment by chrisda** [comment]
@CarolWangMS, basically, yes. If I understand correctly, # 5 (organization message send limits for the internal sender) won't apply; # 4 (user-specific message size send limit) takes precedence. From the topic:

> Recipient limits between authenticated senders and recipients (typically, internal message senders and recipients) are exempt from the organizational message size restrictions. Therefore, you can configure specific senders and recipients to exceed the default message size limits for your organization. For example, you can allow specific mailboxes to send and receive larger messages than the rest of the organization by configuring custom send and receive limits for those mailboxes.

> However, this exemption applies only to messages sent between authenticated senders and recipients (typically, internal senders and recipients). For messages sent between anonymous senders and recipients (typically, Internet senders or Internet recipients), the organizational limits apply. For example, suppose your organizational message size limit is 10 MB, but you configured the users in your marketing department to send and receive messages up to 50 MB. These users will be able to exchange large messages with each other, but not with Internet senders and recipients (unauthenticated senders and recipients).

But, that's a subtle point. Fundamentally, if an internal sender with a large message size limit tries to send a message to an external recipient that's larger that the organizational receive message size limit, the message can't be delivered.
