### ISSUE TITLE
No pre-authentication supported my MRS moves

### ISSUE THREAD

**Issue by nicsi1987** [MicrosoftDocs/OfficeDocs-Exchange#8]
It is known that MRS does not support pre-authentication when performing remote moves, nor SSL off-loading. It supports only SSL-bridging, but of course, this is not the same as standard pre-authentication.
Shouldn't this table be corrected with "Pre-Auth Supported" to 'NO'  also for Mailbox migrations part?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-itpro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by kenwith** [comment]
@nicsi1987 - I was able to get this into the backlog for the Exchange team. The team will get this prioritized and into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. And sorry for the long delay!

I made a note to request the team to update this when the work is complete.

**Comment by kevinblumenfeld** [comment]
@kenwith @nicsi1987 why was this closed?

**Comment by kevinblumenfeld** [comment]
Well I did get preauthentication to work in my lab ... so :-)

**Comment by dstrome** [comment]
I sincerely apologize for the delay in responding to this comment. I've requested information from the product team and will update when I hear back.

**Comment by scanum** [comment]
@dstrome Hi David, any updates on this? Thanks!

**Comment by dstrome** [comment]
Assigning to @chrisda as he owns this area now.

**Comment by scanum** [comment]
@chrisda Hi Chris, any updates on this? Thanks

**Comment by scanum** [comment]
@chrisda Hi Chris, following up on this, any updates? Thanks!

**Comment by chrisda** [comment]
I changed the value to No.

Closing
