### ISSUE TITLE
Android app config: "Allows app to control showing default signature for the account"

### ISSUE THREAD

**Issue by ketterp** [MicrosoftDocs/OfficeDocs-Exchange#800]
With android app config i can set the key "com.microsoft.outlook.Mail.DefaultSignatureEnabled". Theres no documentation for it. What does it mean exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#configuration-keys)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by smithre4** [comment]
Hi, thanks for the inquiry. This key isn't available for use (in that it does not affect the behavior of the app).  We'll be documenting the key once it is released. Stay tuned.

**Comment by seamonkey420** [comment]
ok.. so how many of these settings actually are real settings? why do you add non-functional settings to an app??   seriously, do the coders even use said apps or try to configure?  i know.. choir.. choir...

**Comment by smithre4** [comment]
@seamonkey420 - currently all the settings available in general app config work in the prod app, so not sure what issue you're referring.
