### ISSUE TITLE
Not a Signature Solution

### ISSUE THREAD

**Issue by mltytskr** [MicrosoftDocs/OfficeDocs-Exchange#801]
This is not a solution for signatures, the text is placed a the very bottom of the email, not after the reply or forward part of a message. For this to be a solution the disclaimer needs to be placed after the new message, not the entire email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a56bae-a3fc-43e8-1e5e-69c38971b2d8
* Version Independent ID: c68cbbac-56f7-32f5-1e9a-bbc1d58d091d
* Content: [Organization-wide disclaimers, signatures, footers, or headers in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/mail-flow-rules/signatures?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/signatures.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mail-flow-rules/signatures.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@mltytskr Thank you for reaching out.  If there are any changes to the actual MS doc that you think are necessary, please can you send me your suggestions and I can have them approved and implemented soonest. Your help is greatly appreciated.

**Comment by scanum** [comment]
@mltytskr  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by RamiroIsBack** [comment]
Hello, 
Is there any way to place the disclaimer after the new message you wrote when forwarded or replay?? I want to centralize signatures through exchange, not having everyone doing their own signature, but having them at the very bottom doesn't help.
Thanks.

**Comment by chrisda** [comment]
@RamiroIsBack, I'm pretty sure all you need to do is **not** include the exception that looks for the existing disclaimer text in the message. The rule should keep adding the disclaimer text on every reply or forward.

**Comment by RamiroIsBack** [comment]
thanks @chrisda for responding, my problem is that the disclaimer is added to the bottom of the message (after every message and reply history and not after what I just wrote in the last email) what means nobody sees it and you could end up with a pile of dozen signatures at the end of the conversation/mails if you don't add the exception, and even with the exception you get just one signature but just where ever in the chain of messages you wrote your first mail.
I hope this explains better the problem, I and many others would like the append disclaimer to be attached at the end of the message that I just wrote not at the very bottom. Thanks!

**Comment by mltytskr** [comment]
@scanum and @chrisda, I think references to using mail flow rules to create an org-wide "signature" should be removed from this document because that is not an accurate statement. If I send an email initially, the function works. However, if someone from outside my company sends me the initial email, when I reply, my "signature" is appended to the entire thread, below the original message. That isn't how signatures work. The signature should be placed after my message. My company requires that we have our signatures on all replies, and as @RamirolsBack said, all the signatures get collected at the very bottom.

**Comment by scanum** [comment]
@mltytskr  thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
