### ISSUE TITLE
Step 3 Clarify

### ISSUE THREAD

**Issue by jpenntnc** [MicrosoftDocs/OfficeDocs-Exchange#802]
Are you supposed to be running step 3 on the on-premise exchange server or exchange 365?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1812196b-e6c5-7f6e-fa82-49df2a47d73d
* Version Independent ID: cc06c76a-b7a0-7c21-0a73-c66b9b05a055
* Content: [Configure Exchange 2013 public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-modern-hybrid-public-folders#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-modern-hybrid-public-folders.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@jpenntnc, That step is supposed to be run on Exchange Online.

**Comment by jpenntnc** [comment]
Lindsay,

OK, thank you for the clarification.  I did run it online but I still have a user that can’t see the data in the public folder calendar.  I will keep digging.

James

**Comment by scanum** [comment]
@jpenntnc  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
