### ISSUE TITLE
Typo in Set-MailContact command

### ISSUE THREAD

**Issue by ThePoShWolf** [MicrosoftDocs/OfficeDocs-Exchange#805]
Under 'Use Exchange Online PowerShell to change mail contact properties' the command:

```powershell
Set-Contact "Kai Axford" _-Title Consultant -Department "Public Relations" -Company Fabrikam -Manager "Karen Toh"
```

Has an ```_``` in front of ```-Title``` that shouldn't be there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 601b7a39-638c-759b-4ba2-47171cdfd542
* Version Independent ID: f2f399ee-5d99-212b-5b21-0feb1c8aee08
* Content: [Manage mail contacts](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-contacts)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-contacts.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-mail-contacts.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@ThePoShWolf, thanks for the feedback. I fixed it. But, you can, too. See https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.

**Comment by ThePoShWolf** [comment]
@chrisda I usually do, but this month is turning into a rough one for me. Thanks for the reminder though! 👍
