### ISSUE TITLE
What OSI layer

### ISSUE THREAD

**Issue by JulioQc** [MicrosoftDocs/OfficeDocs-Exchange#807]
So does this apply to both L4 and L7 load-balancers? With NATing enabled or not? What specifics of load-balancer? 
Please specify as there is so many load-balancer out there and this does not work on a L7 config afaik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f017fd21-0284-df8b-145c-6d9ce21d01f1
* Version Independent ID: 57e366b8-5a87-e9c6-7527-009105dc9672
* Content: [Configure Kerberos authentication for load-balanced Client Access services](https://docs.microsoft.com/en-us/exchange/architecture/client-access/kerberos-auth-for-load-balanced-client-access?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/kerberos-auth-for-load-balanced-client-access.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/kerberos-auth-for-load-balanced-client-access.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@JulioQc Thank you for reaching out.  I'll look into this with the team and get back to you soonest.

**Comment by lindspea** [comment]
@JulioQc . Both L4 and L7 can be used, unless by L7 you mean effectively a full reverse proxy implementation at the LB including pre-auth (which some LB products are capable of)... then you would obviously be handling auth in a different manner. Let me know if that answers your questions.

**Comment by JulioQc** [comment]
Yes, that would describe my situation but I believe it would be known often as SSL re-encryption (my understanding this is the same as the reverse proxy L7 LB you describe)

Any Exchange related documentation pertaining to that setup would be greatly beneficial; even just a note in the existing doc would be great :)

**Comment by scanum** [comment]
@JulioQc Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
