### ISSUE TITLE
Corresponding content for Office 365 customers is missing

### ISSUE THREAD

**Issue by kellybosworth000** [MicrosoftDocs/OfficeDocs-Exchange#808]
It would be great to have similar content that explains what happens to deleted items for Exchange Online mailboxes. In addition to providing links for end users to restore content we should direct IT admins to https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/restore-recoverableitems?view=exchange-ps and https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/get-recoverableitems?view=exchange-ps. These options provide a way for an IT Pro to assist a customer in identifying missing items in the Recoverable items folder and then restoring to original mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef58ac9b-e0a9-51e9-787e-ce2a4e6b6bfa
* Version Independent ID: c567570c-1214-38a8-8a5c-9cae85b7aece
* Content: [Recoverable Items folder in Exchange Server](https://docs.microsoft.com/en-us/Exchange/policy-and-compliance/recoverable-items-folder/recoverable-items-folder?view=exchserver-2019&viewFallbackFrom=exchonline-ww)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/recoverable-items-folder/recoverable-items-folder.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/recoverable-items-folder/recoverable-items-folder.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@kellybosworth000, there is:

https://docs.microsoft.com/Exchange/security-and-compliance/recoverable-items-folder/recoverable-items-folder

Notice how the title in that one ends in "...in Exchange Online", while the one you referenced ends in "...Exchange Server".

You can always check your context at the top of the page:

![image](https://user-images.githubusercontent.com/33166947/56319681-3736ef80-6117-11e9-89c5-2d3e7e6e8860.png)
