### ISSUE TITLE
Inactive mailboxes in Exchange Online.

### ISSUE THREAD

**Issue by dkotars** [MicrosoftDocs/OfficeDocs-Exchange#81]
The link for "Inactive mailboxes in Exchange Online" redirects to "https://docs.microsoft.com/en-us/office365/securitycompliance/eop/exchange-online-protection-overview" no content on  Inactive mailboxes in Exchange Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c38acb1-6f67-3c4c-fa3f-7d0ca7b257c0
* Version Independent ID: 673af28f-4de4-ec12-6428-6346142d20d3
* Content: [In-Place Hold and Litigation Hold](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-and-litigation-holds)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-and-litigation-holds.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
fixed; this link now points to inactive mailbox overview topic.

https://docs.microsoft.com/en-us/exchange/security-and-compliance/security-and-compliance 

Note that on Aug. 21st this topic on inactive mailbox will be migrated to docs.
