### ISSUE TITLE
Extended Protection and Kernel mode

### ISSUE THREAD

**Issue by JulioQc** [MicrosoftDocs/OfficeDocs-Exchange#812]
I believe it would be relevant to specify for the sites having Windows Authentication enabled, if Extended Protection and/or kernel mode is recommended and what are the requirements/impacts of having them enabled/enforced. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49e79dae-29d0-b4a7-489d-83529e750c15
* Version Independent ID: 14fabcf0-5751-a091-5432-2d550932973a
* Content: [Default settings for Exchange virtual directories](https://docs.microsoft.com/en-us/exchange/clients/default-virtual-directory-settings?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/clients/default-virtual-directory-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/default-virtual-directory-settings.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@JulioQc Thank you for reaching out and helping improve MS Docs.  I'll chat to the team and see what can be added to the doc.

**Comment by JulioQc** [comment]
Thanks for taking the time! 
I'm asking because this is often recommended as a fix for various CVE and will often break Exchange when behind load-balancers or proxies. So providing this information would help sysadmin decide if the mitigation proposed is useful or harmful in their context.

**Comment by scanum** [comment]
@JulioQc Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by scanum** [comment]
@JulioQc  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
