### ISSUE TITLE
Regex patterns

### ISSUE THREAD

**Issue by parabolic123** [MicrosoftDocs/OfficeDocs-Exchange#813]
Does Microsoft publish the regex strings for individual pattern matches?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9fe18b-cc9f-6b30-234c-74852cf01657
* Version Independent ID: 550db174-df37-b217-1474-7047d019d61c
* Content: [What the sensitive information types in Exchange look for](https://docs.microsoft.com/en-us/exchange/what-the-sensitive-information-types-in-exchange-look-for-exchange-online-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/what-the-sensitive-information-types-in-exchange-look-for-exchange-online-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/what-the-sensitive-information-types-in-exchange-look-for-exchange-online-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @dstrome

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@parabolic123 No, the only strings that are published are the ones mentioned in the document. They do not publish any regex strings for individual patterns.

**Comment by scanum** [comment]
@parabolic123 We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
