### ISSUE TITLE
Why not able to search using Message-ID header as possible query item?

### ISSUE THREAD

**Issue by evandimsby** [MicrosoftDocs/OfficeDocs-Exchange#814]
It'd be very straight forward if we could use the header "message-id:" as search query instead of all the other "to" "from" "subject" "etc"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7393c45-1119-f0ea-67dc-36ecf42d2e08
* Version Independent ID: 29417cc2-6a03-bea3-f195-51ca55f9dc1a
* Content: [Message properties and search operators for In-Place eDiscovery](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/message-properties-and-search-operators.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@evandimsby Unfortunately, using message header properties in a search query isn't possible.
