### ISSUE TITLE
Target Delivery Domain Blank

### ISSUE THREAD

**Issue by rmaestas-fhprd** [MicrosoftDocs/OfficeDocs-Exchange#819]
Our organization has a new Office 365 tenant, running Hybrid Exchange with an on-premise Exchange 2016 server. I need to move a mailbox from Exchange Online back to the on-prem server, and I am following these steps.

When asked to specify a Target Delivery Domain, the dropdown contains nothing to select. Help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35bd8438-69fb-3da3-1c75-25576fc92fd4
* Version Independent ID: 4dd5a61d-ef30-f893-00c7-bdb9132e074d
* Content: [Move mailboxes between on-premises and Exchange Online organizations in hybrid deployments](https://docs.microsoft.com/en-us/Exchange/hybrid-deployment/move-mailboxes#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/move-mailboxes.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@rmaestas-fhprd  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
