### ISSUE TITLE
Where is the download link?

### ISSUE THREAD

**Issue by stylerOD** [MicrosoftDocs/OfficeDocs-Exchange#82]
There are lots of references to downloading the iso, but I've been diving into various links for 20 minutes and still can't find the correct link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355e223c-c419-9fc8-16a9-0329e4794034
* Version Independent ID: 035ae216-9973-3804-df10-01f1f330e6c1
* Content: [Install the Exchange 2016 management tools](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/install-management-tools)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/install-management-tools.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/post-installation-tasks/install-management-tools.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by dstrome** [comment]
hi @stylerOD ,

You can download the Exchange ISO by clicking on the "Updates for Exchange 2016" link in step one of the procedure on this page.
