### ISSUE TITLE
Missing Tracking Log Event Type

### ISSUE THREAD

**Issue by wshep007** [MicrosoftDocs/OfficeDocs-Exchange#821]
The Event Type "SENDEXTERNAL" and possibly more Event Types are missing from the documentation.  Please update.  Also please explain/show the difference between SEND and SENDEXTERNAL.

**Comment by chrisda** [comment]
@wshep007, are you talking about this topic:

https://docs.microsoft.com/Exchange/mail-flow/transport-logs/message-tracking

That topic is for Exchange Server 2016 and 2019. The SENDEXTERNAL even type appears to be about messages leaving Office 365.

**Comment by wshep007** [comment]
Yes that is the article.  I have an Exchange 2016 server that is using the SENDEXTERNAL event type.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@wshep007 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
