### ISSUE TITLE
Is Outlook for Mac 2016 not impacted by the EXO tenant OAUTH configuration at all?

### ISSUE THREAD

**Issue by ivratche** [MicrosoftDocs/OfficeDocs-Exchange#822]
This is worded very very confusing: "Other email clients that support modern authentication (for example, Outlook Mobile, Outlook for Mac 2016, and Exchange ActiveSync in iOS 11 or later) always use modern authentication to log in to Exchange Online mailboxes, regardless of whether you enable or disable modern authentication for Outlook 2013 or later clients as described in this topic." Outlook for Mac 2016 has nothing to do with Outlook 2013, not sure why it is even mentioned here. Did you mean to say Exchange Online instead of Outlook 2013? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3595c01-2eb7-a6e0-0424-12d7628fa25b
* Version Independent ID: 2368964f-83cb-e16f-c04c-832361e18c63
* Content: [Enable modern authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/enable-or-disable-modern-authentication-in-exchange-online.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@ivratche, no, I meant to say Outlook 2013 or later, but I can see how that's confusing.

The enable/disable Modern Auth setting (everything going on in the topic), **only** affects Windows based Outlook 2013 or later clients (2016 and 2019 at this point). It doesn't affect the other clients mentioned: Outlook Mobile, Outlook for Mac 2016, and Exchange ActiveSync in iOS 11 or later, or potentially other clients that also support Modern Auth.

So Modern Auth enabled = Modern Auth enabled for Outlook 2013, Outlook 2016 or Outlook 2019. Modern Auth disabled = Modern Auth disabled for Outlook 2013, Outlook 2016, or Outlook 2019.

I updated the topic to (hopefully) be more clear. Thanks for the feedback

**Comment by ivratche** [comment]
Thanks Chris, it is pretty clear now :). Thank you for modifying the text so quickly. Cheers!
