### ISSUE TITLE
Incorrect command

### ISSUE THREAD

**Issue by Rengasco** [MicrosoftDocs/OfficeDocs-Exchange#823]
"Get-PublicFolderStatistics -ResultSize Unlimited | Where {($_.Name -like "*\*") -or ($_.Name -like "*/*") } | Format-List Name, Identity" should be "Get-PublicFolderStatistics -ResultSize Unlimited | Where {($_.Name -like "*\*")} | Format-List Name, Identity"  r the sentence "If the name of a public folder contains a backslash \, the public folders will be created in the parent public folder when migration occurs. Before you migrate, we recommend that you rename any public folders that have a backslash in the name." is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8461539-6b09-70a8-f9f4-58e0c4a0618e
* Version Independent ID: 2b395f25-b532-dc97-e442-ae3f1842c95f
* Content: [Use batch migration to migrate public folders to Exchange 2013 from previous versions](https://docs.microsoft.com/en-us/exchange/use-batch-migration-to-migrate-public-folders-to-exchange-2013-from-previous-versions-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/use-batch-migration-to-migrate-public-folders-to-exchange-2013-from-previous-versions-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/use-batch-migration-to-migrate-public-folders-to-exchange-2013-from-previous-versions-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @dstrome

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@Rengasco Thank you for pointing this out and helping improve MS Docs.  I will make the necessary changes as suggested in your first point.  Could you let me know how you would suggest fixing the incorrect statement please?

**Comment by scanum** [comment]
@Rengasco We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
