### ISSUE TITLE
Reverse the process??

### ISSUE THREAD

**Issue by kwatson69** [MicrosoftDocs/OfficeDocs-Exchange#827]
Loved this article.  Few comments:
1. Office 365 support does NOT support this in fact they have suggested that this isn't possible.
2. I completed all of the steps and everything worked great for users that where migrated to 365 and users that still remained on the server.  One problem though, users from other forests that used my server as a resource server for Exchange did NOT work.  (ie: accounts using the linked-account feature would not work once migrated to 365).
3. I've migrated everyone to 365 and now I want to migrate my public folders.  Based on everything that I've read I'm going with the easy export to PST and then import option. However, I can't see any of the Public folders within 365.

So my question, how do I reverse these steps without losing anything?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45f5e210-5945-277a-12dc-f1eae01ba403
* Version Independent ID: a9a867e0-e3eb-ffbb-2013-47707a6b4364
* Content: [Configure legacy on-premises public folders for a hybrid deployment](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders#feedback)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@kwatson69 Thank you for reaching out and helping improve MS Docs.  I'll have the team look into this and let you know soonest.

**Comment by mohan1921** [comment]
you will not see public folder in O365 when u enable hybrid. the syncmailpubfolder script creates only contacts. you need to create the public folder mailboxes in O365 prior to migration as per the corresponding articles

**Comment by scanum** [comment]
@kwatson69 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by RescueWhale** [comment]
What article are you referring to @mohan1921?

If there are prerequisite steps to this, they need to be at least mentioned and ideally put into this article.
