### ISSUE TITLE
Instruction link name error

### ISSUE THREAD

**Issue by timmmay** [MicrosoftDocs/OfficeDocs-Exchange#828]
The link at the end of the article with the title "Use batch migration to migrate your Exchange 2013 public folders to Exchange Online" should read "Use batch migration to migrate your Exchange 2013 public folders to Office 365 Groups".  The actual link is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb586432-331c-fff4-953d-6e2b9d33f611
* Version Independent ID: 0e58d7c8-6d89-f854-cb8f-5a19c4169020
* Content: [Migrate your public folders to Office 365 Groups](https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/migrate-to-office-365-groups?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/collaboration/public-folders/migrate-to-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/collaboration/public-folders/migrate-to-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@timmmay Thank you, I will look into it.

**Comment by scanum** [comment]
@timmmay Thank you for your feedback and contribution to improving the docs. We understand this issue has been resolved.

Please re-open if you would like to add anything else. We encourage you to keep making the docs better!

**Comment by scanum** [comment]
@officedocsbot close
