### ISSUE TITLE
Options do not relflect what is available in the console

### ISSUE THREAD

**Issue by jimmyeao** [MicrosoftDocs/OfficeDocs-Exchange#829]
The 'Apply rule if' list does not match what is currently available, The only option for attachments is 'Any attachments content includes'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd230cd-1717-a932-a5c9-02db4f1b050c
* Version Independent ID: 24dcb706-d0d9-61d3-e99d-289db401ffaa
* Content: [Use mail flow rules to inspect message attachments in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/inspect-message-attachments#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/inspect-message-attachments.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jimmyeao, if you go to **Mail flow** \> **Rules** \> **New** and select **Create a new rule**, you only see **Any attachment's content includes** as you describe:

![image](https://user-images.githubusercontent.com/33166947/56678175-e70be000-6676-11e9-9caf-cfc2f51ce785.png)

But, if you click **More options** first (as the topic describes), everything changes and what you see matches the screenshot in the topic:

![image](https://user-images.githubusercontent.com/33166947/56678279-263a3100-6677-11e9-9335-ab201b3cae75.png)

The short names and long names for conditions are described in the topic [Mail flow rule conditions and exceptions (predicates) in Exchange Online](https://docs.microsoft.com/exchange/security-and-compliance/mail-flow-rules/conditions-and-exceptions)
