### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by CDavisSCC** [MicrosoftDocs/OfficeDocs-Exchange#830]
The hyperlink for 'How to reset the nickname and the automatic completion caches in Outlook' links to an article about Excel not Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59062d31-9618-f316-c6b9-1ed30319aa7f
* Version Independent ID: b5d5266d-ad7d-bc44-53a3-59aecf46391e
* Content: [How to migrate mailboxes from one Office 365 tenant to another](https://docs.microsoft.com/en-us/exchange/mailbox-migration/migrate-mailboxes-across-tenants#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrate-mailboxes-across-tenants.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@CDavisSCC Thank you, I will look into it.

**Comment by chrisda** [comment]
@CDavisSCC, confirmed. I updated the link and the surrounding text.

Thanks for the feedback.
