### ISSUE TITLE
Completely useless

### ISSUE THREAD

**Issue by bruce-simspace** [MicrosoftDocs/OfficeDocs-Exchange#840]
Although the page is advertised for exchange server 2019, all of the links lead to pages for Server 2008. All of them say that this material is no longer being maintained. Of course, it was useless even when it was maintained. Why useless? There are instructions for actually finding any trouble. "Configure a computer to troubleshoot Activie Directory domains" has no instructions on how to do so for any current software, or what to look for once you *have* figured it out on your own. "Troubleshooting Active Directory Replication Problems" requires a Master's degree in CompSci to figure out. There's no indication of why you would need Repadmin in addition to "Troubleshooting Active Directory Replication Problems" - you'd think the one would cover the other.

Of course, nothing here has any bearing on my problem: Trying to install the FIRST Exchange server into a brand new, just created forest with a SINGLE SERVER, tells me that it can't contact the Active Directory. A SINGLE 2016 AD server and a SINGLE Exchange server 2016. Why is this a "replication" problem? Of coure the real issue, why can't Microsoft get its act together and provide reasonable documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3cb6166-d33d-3f05-0ea9-a945c2e4f43d
* Version Independent ID: ae13756f-45f4-7340-28d0-5a26c9d6b17b
* Content: [Active Directory does not exist or cannot be contacted \[CannotAccessAD\]](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deployment-ref/ms-exch-setupreadiness-cannotaccessad?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deployment-ref/ms-exch-setupreadiness-cannotaccessad.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deployment-ref/ms-exch-setupreadiness-cannotaccessad.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@bruce-simspace, the links in the topic were fwlinks that, indeed, pointed to now outdated Windows Server topics. I updated the links to point to modern versions.

Regarding your installation problems:

- Confirm that you're using the [lastest available download for Exchange 2016](https://docs.microsoft.com/exchange/new-features/updates?view=exchserver-2016) (CU12 as of today), 

- Follow the steps in the [Installation Wizard](https://docs.microsoft.com/exchange/plan-and-deploy/deploy-new-installations/install-mailbox-role?view=exchserver-2016). Be sure to read and verify all of the prerequisites.

If it still doesn't work, please open a support ticket. The error message is clearly a red herring, unless you have some type of internal firewall or port blocking between the Exchange server and the DC in your org (not likely).

**Comment by scanum** [comment]
@bruce-simspace  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
