### ISSUE TITLE
Bad formatting on the output 

### ISSUE THREAD

**Issue by j0rt3g4** [MicrosoftDocs/OfficeDocs-Exchange#845]
https://docs.microsoft.com/en-us/exchange/policy-and-compliance/recoverable-items-folder/clean-up-deleted-items?view=exchserver-2019

A lot of !Important and !Notes inside Powershell Code not being showed properly

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@j0rt3g4, it looks like the indenting of the paragraphs within the numbered lists and bulleted lists was messed up (not far enough to the right), which can cause the surrounding text to be in PowerShell code as you described.

I cleaed everything up; it should look OK now.

Thanks for the feedback.

**Comment by j0rt3g4** [comment]
Hi @chrisda yeah, I've solved that on the PR #858
