### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-Exchange#85]
This link "Introduction to the basics of Office 365 mail flow" at top of page is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48c969ec-e02c-70b0-59ba-a4a868a522ce
* Version Independent ID: b01cc2c1-bb5b-b443-ecfb-77a45ae7a693
* Content: [Mail flow best practices for Exchange Online and Office 365 (overview)](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/mail-flow-best-practices)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/mail-flow-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/mail-flow-best-practices.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by dstrome** [comment]
@obhayes ,

Thanks very much for finding this broken link! @chrisda, please find a replacement link.

**Comment by chrisda** [comment]
The broken link https://technet.microsoft.com/library/840fd26f-5409-4325-8543-7cdaa2f8bb25.aspx took me to the Chinese TechNet page, but the topic was in English. Searching for the topic on the internet took me to https://technet.microsoft.com/fr-fr/library/mt491265(v=exchg.150).aspx (the French TechNet site) where the topic was in English.

Investigating

**Comment by chrisda** [comment]
@obhayes I replaced the bad link with a better one.

Thanks for the feedback.

**Comment by AndreaBarr** [comment]
@MK-Kamal Could you please investigate this?
