### ISSUE TITLE
Authentication to OWA, ECP fails when providing WAUTH parameter

### ISSUE THREAD

**Issue by rh1701** [MicrosoftDocs/OfficeDocs-Exchange#86]
A URL using the following format fails in my environment for Exchange 2013 OWA and ECP using AD FS authentication but works for my other WS-FED AD FS applications

https://sts.mydomain.com/adfs/ls/?wa=wsignin1.0&wtrealm=https://rp.mydomain.com &wauth=urn:oasis:names:tc:SAML:1.0:am:password

Purpose of using URL string is to allow Help desk and Admin users the ability to avoid WIA and use separate elevated credentials via Forms AuthN to Access EAC.  Currently admin users are forced to use a non-WIA browser (Firefox) to access EAC

Rich H

**Comment by dstrome** [comment]
hi @rh1701 ,

Please contact Microsoft Support to help you resolve this issue - https://support.microsoft.com/en-us/assistedsupportproducts.
