### ISSUE TITLE
Outlook on the Web v Outlook

### ISSUE THREAD

**Issue by IdahoR** [MicrosoftDocs/OfficeDocs-Exchange#865]
The first paragraph can be confusing by saying "Outlook on the web (Outlook)" and then just using "Outlook" later on, as that could be construed as meaning that Office Online Server is required for desktop Outlook to preview files.  This reference (https://support.office.com/en-ie/article/preview-attachments-in-outlook-6f61e4ad-a93d-408c-bb3a-bc95107f66be) states that Office Outlook uses the preview function of the other apps installed as part of the suite.  Please update to be clear about where Office Online Server is required, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e12237-20cc-007c-540b-4544269ec6a9
* Version Independent ID: 08d3e012-d918-c625-3d6c-d827636f34b5
* Content: [Install Office Online Server in an Exchange organization](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/install-office-online-server?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/install-office-online-server.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@IdahoR Thank you for reaching out and helping improve MS Docs.  Could you perhaps suggest which wording should be changed/added to avoid confusion, and in which sections please?

**Comment by chrisda** [comment]
@IdahoR, "...Outlook on the web (Outlook)..." should have said "...Outlook on the web (formerly known as Outlook Web App)...", so I fixed it.

Thanks for the feedback.
