### ISSUE TITLE
Default alias in Outlook app can't be changed after migration

### ISSUE THREAD

**Issue by tox1c90** [MicrosoftDocs/OfficeDocs-Exchange#866]
I am a consumer / outlook.com user and got migrated to the new Microsoft Sync Technology. Yesterday the Outlook Android app showed "updating email and calendar data" and after that the Client Type changed from REST to Outlook in Mobile Devices view. Also the app is now showing "Microsoft Sync Technology" in account settings. 
Unfortunately I noticed that after this migration it is no longer possible to change the default e-mail alias. In account advanced settings you have a list with all Aliases where you can press on any of them and make them default alias for new mails. After migration nothing happens when you click on one of the aliases. Even the button "Add new alias" does not work anymore.
It is reproducable - after reinstalling the app it first starts syncing with the old REST protocol. In this state, changing the default alias works. After closing and resuming the app, it changes to native sync technology and the default alias configuration is broken.

Is this a limitation of the new sync protocol? If yes, maybe it should be mentioned in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 398ae9a4-c12a-bbac-80b5-570b653867a5
* Version Independent ID: ad0617f6-897a-2f94-b109-a5fb6e6f31c1
* Content: [Outlook Exchange Online FAQ, Outlook for iOS Exchange FAQ, Outlook for Android FAQ, Outlook for iOS security concerns, Outlook for Android security concerns, Outlook for iOS cloud architecture, Outlook for Android cloud architecture, Outlook app Office 365 architecture, Outlook app attachment faq, Outlook app contacts faq, Outlook app license faq](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@tox1c90 - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
