### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/OfficeDocs-Exchange#868]
Hi, one question: in the Step "Create a sub-domain for mail routing to Office 365", 
I think option "Add another domain" should be selected instead of "Add a domain alias of fabrikaminc.net" since the "Overview of the process" image indicates that the gsuite.fabrikaminc.net domain corresponds to the users' Aliases. Something similar happens with Step "Create a sub-domain for mail routing to your G Suite domain". Is there an error in the documentation?. Thanks! Fernando

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@FernandoGualano Thank you for the feedback. We have found that the GSuite user interface changes frequently...things get moved or renamed on a regular bases. We do our best to keep those elements up to date in our articles but it's difficult to catch every change. We will add this to our work queue to update. Thanks again.

**Comment by Justthingsido** [comment]
@msdmaguire , what is the correct step? should `gsuite.fabrikaminc.net` be added as a **"domain alias"**, and `o365.fabrikaminc.net `be added as a **"another domain"** instead?

**Comment by msdmaguire** [comment]
@Justthingsido and @FernandoGualano, confirmed with product team that gsuite.fabrikaminc.net should be the "domain alias" and o365.fabrikam.net should be "another domain. The article has been updated and changes should appear by Monday. Thanks again for the feedback.
