### ISSUE TITLE
Regular Group that contains a Dynamic Group?

### ISSUE THREAD

**Issue by kelemvor33** [MicrosoftDocs/OfficeDocs-Exchange#87]
Is there any way to do something similar if I have a regular Distribution Group that contains multiple Dynamic Groups?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91a9ec7c-b6a2-11bc-00a8-66c0b762a5d8
* Version Independent ID: ce530938-ecfd-c52b-e70f-5db0ccd6e880
* Content: [View members of a dynamic distribution group](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-dynamic-distribution-groups/view-group-members)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/view-group-members.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-dynamic-distribution-groups/view-group-members.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by chrisda** [comment]
@kelemvor33 sure, it's possible. You could use a PowerShell script that:

Uses the Get-DistributionGroupMember cmdlet to parse through the membership of the specified regular distribution group to identify the dynamic distribution groups (DDGs) in the group (most likely, by keying off of the property and value "RecipientType -eq 'DynamicDistributionGroup'"). Then, for each DDG that's found, use the procedure described in the topic to expand the membership of the DDG.

It would be a semi-complex for-each nested script.
