### ISSUE TITLE
2016 Mailbox Server Prereqs

### ISSUE THREAD

**Issue by collinsw58** [MicrosoftDocs/OfficeDocs-Exchange#888]
Is KB3206632 still required?  Or did 3213522 or later cumulative update replace it?

**Comment by scanum** [comment]
@collinsw58  - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@collinsw58  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by collinsw58** [comment]
Hello. I’m not sure where the assumption was I have a tenant. We provide services on-premise.  I merely wanted to submit feedback that the document may be outdated after review as part of our update.  I cannot find where the kb referencing the update preview is still required as prerequisite software, and that it may be superseded by a cumulative monthly update.  But, was uncertain, hence the inquiry. 

Closing the request referring to tenant support, then asking me to provide the resolution back, just passes the buck and dilutes the quality of the doc.  I’m not going to do your job for you. 

Thanks!
