### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by Mitchell0069** [MicrosoftDocs/OfficeDocs-Exchange#891]
https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1546484847&rver=7.0.6738.0&wp=MBI_SSL&wreply=https:%2F%2Faccount.microsoft.com%2Fauth%2Fcomplete-signin%3Fru%3Dhttps%253A%252F%252Faccount.microsoft.com%252Fauth%252Fcomplete-signin%253Fru%253Dhttps%25253A%25252F%25252Faccount.microsoft.com%25252Frewards%25253Fru%25253Dhttps%2525253A%2525252F%2525252Faccount.microsoft.com%2525252Frewards%2526wa%253Dwsignin1.0%2526refd%253Daccount.microsoft.com&lc=1033&id=292666&username=16514341882&lw=1&fl=easi2&pcexp=false

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Mitchell0069 Thanks for submitting. Could you please specify your question?

**Comment by scanum** [comment]
@Mitchell0069 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
