### ISSUE TITLE
GroupWriteback permissions necessary?

### ISSUE THREAD

**Issue by KjetilEVRY** [MicrosoftDocs/OfficeDocs-Exchange#894]
Are the manual PS script necessary to run (in step 10), if you have the latest version of AAD Connect? The permissions are set automatically since version 1.1.880.0, ref "Adding support for permission granting on Group Writeback in AADConnect's installation wizard". And in the latest version (1.3.20.0), it says that GroupWriteback are finally out of preview and are now GA. Is the documentation on this page outdated, or is it still necessary to apply the PS script?

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/nb-no/exchange/hybrid-deployment/set-up-office-365-groups#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@KjetilEVRY  - Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@KjetilEVRY Thank you for reaching out.  I'll investigate with the team and revert soonest.

**Comment by lindspea** [comment]
@KjetilEVRY Thank you for reaching out and helping improve MS Docs. You don't need to explicitly run that script. ADConnect does that for you in the background.

**Comment by scanum** [comment]
@KjetilEVRY Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by RNalivaika** [comment]
Just installed Azure AD Connect version 1.5.30.0 and the install wizard did not set up the permissions right. Running the script fixed the issue and writeback startet working.
