### ISSUE TITLE
In Exchange Online, the maximum number of journal rules you can create is 10

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-Exchange#897]
The limit of 10 is incorrect. This has been increased to at least 100 last year. To avoid confusion for our customers, this article should have been updated a longtime ago (Jan 2018)
Related VSO: 432113

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d4ec80-7a55-398a-22e9-3f5df24a867b
* Version Independent ID: 4543c414-41d1-b8fe-8a58-4dc61ccf61ff
* Content: [Journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/journaling#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by joesuffceren** [comment]
ugh, just confirmed this. Limits doc needs updated, too: https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#journal-transport-and-inbox-rule-limits Had to do some gymnastics to combine multiple rules to stay underneath the documented limit of 10 when I could have simply created more. Frustrating.

**Comment by markjjo** [comment]
@JeroenDronkers @joesuffceren The current limit is 50 journaling rules; the service description has been updated and the EXO journaling topics will be updated to link to the service description.
