### ISSUE TITLE
After first time login, i try to login by using different user but every time login screen comes with previous user email id 

### ISSUE THREAD

**Issue by RahulFate** [MicrosoftDocs/OfficeDocs-Exchange#899]
i am working on one app. where i would like to login to outlook and fetch of that users email within my app. I login successfully and get all emails. But when i tried to login by different user, login screen opens with previous outlook logged user. Which i never want, i want every time fresh login screens with empty username and password textfield. Please Suggest ASAP.

**Comment by scanum** [comment]
@RahulFate  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
