### ISSUE TITLE
Passo a Passo

### ISSUE THREAD

**Issue by piercarlozanella** [MicrosoftDocs/OfficeDocs-Exchange#9]
na etapa numero 6 faltou o comando "MAIL" antes do "FROM" 
Digite o email FROM:chris@contoso.com e pressione Enter.
o correto seria:
Digite MAIL FROM:chris@contoso.com e pressione Enter.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: f8c08a22-e9ab-59be-4d3e-cc522e0bec99
* Version Independent ID: 8f2f67b1-1eb3-aeac-9af5-a07582080a38
* Content: [Usar Telnet para testar a comunicação SMTP em servidores do Exchange](https://docs.microsoft.com/pt-br/exchange/mail-flow/test-smtp-with-telnet)
* Content Source: [Exchange/ExchangeServer/mail-flow/test-smtp-with-telnet.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/test-smtp-with-telnet.md)
* Product: **exchange-server-itpro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by kenwith** [comment]
@piercarlozanella - looks like this is fixed now in the English version. It takes a little time for the translation to happen for other languages. If you still see the issue in the Content Source document above please re-open. Thanks for taking the time to provide feedback!
