### ISSUE TITLE
UCMA 4 requires Media Foundation

### ISSUE THREAD

**Issue by junecastillote** [MicrosoftDocs/OfficeDocs-Exchange#90]
Since UCMA 4 is required, and UCMA 4 itself requires Media Foundation, wouldn't it make sense to include Server-Media-Foundation in the Install-WindowsFeature install?

**Comment by dstrome** [comment]
hi @junecastillote ,

Thanks very much for finding that error. I've added the Server-Media-Foundation item to the prereq command for Windows Server 2016. And thanks for taking the time to send us feedback!

David.
