### ISSUE TITLE
Need to describe selection mechanism in case of multiple partner connectors are being used

### ISSUE THREAD

**Issue by thorstd** [MicrosoftDocs/OfficeDocs-Exchange#900]
In hybrid environments for which the mx records are pointing to on-prem customers often want to block direct delivery to EXO. This can be achieved by creating a partner inbound connector and restrict it to certain on-prem IPs (SenderIPAddresses) or a specific certificate (TlsSenderCertificateName). This setup is working. But if you want to make an exception for a specific sender domain creating an additional partner connector does not help when SenderIPAddresses and TlsSenderCertificateName are empty. Statement from the product group:

> You cannot have an "allow" by sender domain connector when there is a restrict by IP/Cert connector. The restrict connector will take precedence as partner connectors are pulled up by IP or Cert lookup when restriction and mail rejection is applied.  

PG also wrote:

> You should not have IPs and Cert configured in the same Partner connector. Please use separate connectors. Associated Accepted Domains is really shouldn't be used apart from maybe testing the connector only to a subset of the accepted domains/ recipient domains on the mail. 

**This article should be updated - we need a description of the selection process in case of having multiple inbound partner connectors.**

**Comment by scanum** [comment]
@thorstd Thanks for submitting, could you please reference article? Thanks!

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by thorstd** [comment]
> @thorstd Thanks for submitting, could you please reference article? Thanks!

I don't understand. Are you requesting a reference to the quotes I posted? They are from an MS-internal bug.

**Comment by lindspea** [comment]
@thorstd Thank you for reaching out and helping improve MS Docs. I'm investigating further and to help assist with this issue please could you send the article link that you are referencing here. Which article are you suggesting needs updating?

**Comment by scanum** [comment]
@thorstd We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by MaJoMS** [comment]
Hi, please reopen this request, as Thorsten is OOF at the moment. The request is for the article https://docs.microsoft.com/en-gb/exchange/mail-flow-best-practices/use-connectors-to-configure-mail-flow/use-connectors-to-configure-mail-flow
Many thanks
/Marc

**Comment by lindspea** [comment]
@MaJoMS @thorstd thank you for referencing that article.  Do you have any suggestions for the update or is there a specific link that you would like added to the article?

**Comment by scanum** [comment]
@officedocsbot reopen

**Comment by scanum** [comment]
@thorstd Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
