### ISSUE TITLE
On Exchange Datacenter Failover document, no explanation of a "partially failed datacenter"

### ISSUE THREAD

**Issue by WillMartin58** [MicrosoftDocs/OfficeDocs-Exchange#901]
On the Exchange disaster recovery datacenter switchover document, https://docs.microsoft.com/en-us/Exchange/high-availability/manage-ha/datacenter-switchovers?view=exchserver-2016, the term "partially failed datacenter" is used, but never defined.  It should be removed or at least defined such that it is obvious that all of the Exchange servers, as well as the Exchange fileshare witness, have been lost.  Anything short of that and the datacenter switchover is automatic - the remaining servers still have quorum.

**Comment by scanum** [comment]
@officedocsbot assign @scanum 

@WillMartin58 Thanks for submitting feedback. Currently investigating this.

**Comment by lindspea** [comment]
@WillMartin58 thank you for reaching out and helping improve MS Docs. Could you perhaps suggest any changes to wording that would make the article more useful.  All help is greatly appreciated.

**Comment by WillMartin58** [comment]
The current section on the page says:
"**Terminating a Partially Failed Datacenter

If any DAG members in the failed datacenter are still running, they should be terminated.**"

I'd suggest either removing the word "partially" from the header, or adding a paragraph after the header saying the following:
"When the Exchange DAG is in DAC mode, you can disable the servers in a failed datacenter with a single command.  This will allow you to mount the databases in another datacenter even if the DAG doesn't have quorum (more than half the members of the DAG available)."

**Comment by lindspea** [comment]
Thanks @WillMartin58 for your assistance!

**Comment by WillMartin58** [comment]
Glad I could help out …

**Comment by scanum** [comment]
@WillMartin58 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
