### ISSUE TITLE
Transport Rules versus Inbox Rules (Server vs Client Side)

### ISSUE THREAD

**Issue by jasonkatz424** [MicrosoftDocs/OfficeDocs-Exchange#902]
Hello,

I could not find anywhere that states whether Exchange Server side rules (Transport) take precedence over client-side rules in processing.

Is this the case that server side rules are always applied first?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afb24bb1-b515-0aa4-2164-c8ea3360562f
* Version Independent ID: f1179e68-e17b-c287-3709-a2d098417e66
* Content: [Best practices for configuring mail flow rules in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/configuration-best-practices#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/configuration-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/configuration-best-practices.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jasonkatz424, transport rules are evaluated (much) earlier in the transport pipeline than Inbox rules, so transport rules always go first.

If you are talking about client-side Inbox rules vs. server-side Inbox rules, the server-side rules always have the potential to run first, regardless of lower vs. higher priority (after all, if you don't open your Outlook client, a client-side rule can't run).

When Outlook is open, the rules should fire in their priority order as configured, regardless of client-side vs. server-side.

Does this make sense?

**Comment by jasonkatz424** [comment]
Thank you for your response chrisda.  This makes sense - Transport rules will always be evaluated first when compared to Inbox rules.  

I think I am a bit confused as to the difference between server-side rules and Transport rules.  I was under the impression they were the same thing.  Is this accurate?  And are Inbox rules and Client rules the same thing?

**Comment by chrisda** [comment]
@jasonkatz424, Inbox rules and transport rules are worlds apart. Transport rules are stored in Active Directory; Inbox-rules are stored in a hidden folder in the user's mailbox.

I would assume that "client rules" are the same as Inbox rules.

**Comment by scanum** [comment]
@jasonkatz424 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
