### ISSUE TITLE
More detail please

### ISSUE THREAD

**Issue by jsmosier** [MicrosoftDocs/OfficeDocs-Exchange#903]
It isn't defined how the aliases or forwarding addresses get set on the G-Suite side.  I assume this happens automatically as part of the migration process, but perhaps I missed something and I need to configure this manually.  If this does happen automatically, I'd appreciate a note being added at the appropriate step stating that it's happening automatically.  If I have to set these properties manually, please clearly state that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#provision-users-in-o365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jsmosier
Thank you for submitting this feedback.

I will get this over to for investigation. Thank you for reporting and making the docs better. Much appreciated.

**Comment by scanum** [comment]
@officesdocsbot assign @scanum

**Comment by msdmaguire** [comment]
@jsmosier The article has been updated to hopefully provide more clarity on those points. Thanks for your feedback.
