### ISSUE TITLE
my email

### ISSUE THREAD

**Issue by FeliciaAnnKelley** [MicrosoftDocs/OfficeDocs-Exchange#906]
[my email keeps having unexplained password changes]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c41fca7-c13b-20fe-83e6-34d91c5f9227
* Version Independent ID: 0844eadb-236e-15cb-5bbf-4963dc30a347
* Content: [Exchange Server Privacy Statement](https://docs.microsoft.com/en-us/Exchange/about-documentation/privacy-statement?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/about-documentation/privacy-statement.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/about-documentation/privacy-statement.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: slowdown2016
* Microsoft Alias: **FeliciaAnn**

**Comment by scanum** [comment]
@FeliciaAnnKelley  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
