### ISSUE TITLE
Update missing

### ISSUE THREAD

**Issue by hebagit** [MicrosoftDocs/OfficeDocs-Exchange#908]
"Update Rollup 27 for Exchange Server 2010 SP3" is missing on this overview: https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates

Why do you use two pages anyway, see: https://social.technet.microsoft.com/wiki/contents/articles/240.exchange-server-and-update-rollup-build-numbers.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf984bf-df1c-bcd5-6475-54b9ef24fe74
* Version Independent ID: 00547ab9-7b3b-f6b0-fa7f-429f5e2bea56
* Content: [Exchange Server build numbers and release dates](https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@hebagit, I added the information to the topic.

I have no idea about that other topic. It looks to be user-maintained.

Thanks for the feedback.
