### ISSUE TITLE
Pre-requirement for DAG monitoring using PS

### ISSUE THREAD

**Issue by firmank** [MicrosoftDocs/OfficeDocs-Exchange#911]
hi Expert

i am really newbie for this thing.  really appreciated if you could inform me, minimum user access credential level (is it possible read-only user/no admin).   any tools have to install, if i want running this PS on my PC monitoring.

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4037ba92-55ab-e01f-e4a6-86a3b428c5ac
* Version Independent ID: b689e896-bae1-8794-7f60-4e0c29c26ba8
* Content: [Monitor database availability groups](https://docs.microsoft.com/en-us/exchange/high-availability/manage-ha/monitor-dags?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/high-availability/manage-ha/monitor-dags.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/manage-ha/monitor-dags.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@firmank  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
