### ISSUE TITLE
DNS records section is unclear

### ISSUE THREAD

**Issue by DavidRawling** [MicrosoftDocs/OfficeDocs-Exchange#912]
> Using the federated domain proof strings created for each domain, create TXT records for each of these domains on your public DNS server. Depending on the update schedule of your public DNS host, replication of DNS changes may take 15 minutes or longer.

It's not clear whether the TXT records should be created for the domain being shared (example.com. TXT IN …), for the organisation identifier (FYDIBOHF25SPDLT.example.com. TXT IN …), for a combination of those, or for something else entirely. Just saying "a TXT record in the domain" is vague.

The working example should include the output of a Get-FederatedDomainProof command, and the output from all the successful NSLOOKUP or similar test cases, at a minimum. Also useful would be screenshots or dumps of DNS configuration (e.g. from an Azure-DNS lab environment).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 507ffc91-1824-3efb-0a11-82b7deff0135
* Version Independent ID: 18e4df24-7016-70d8-8d66-5bcdefc5d298
* Content: [Configure a federation trust: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/configure-a-federation-trust-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/configure-a-federation-trust-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/configure-a-federation-trust-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @dstrome

**Comment by scanum** [comment]
@officedocsbot assign @scanum 

@DavidRawling Thank you for submitting feedback. We are investigating this.

**Comment by lindspea** [comment]
@dstrome

**Comment by scanum** [comment]
@dstrome Hi David, hope you are doing well. Could you help us by checking with the product team on this issue? Thanks!

**Comment by msdmaguire** [comment]
@DavidRawling I got a response from the product group that I hope you find helpful:
The TXT record should be created for every domain that is being federated aka shared. If this is a Hybrid environment then all accepted domains that are validated in Exchange Online should have TXT records created.
