### ISSUE TITLE
Better way to get ADSyncADConnectorAccount name

### ISSUE THREAD

**Issue by mhendric** [MicrosoftDocs/OfficeDocs-Exchange#914]
Per the below article, the ADSync account is only titled AAD_* if AAD Connect is run on a Domain Controller. The instructions would be better if they had you obtain the ADSync account using Get-ADSyncADConnectorAccount. Then you don't have to guess the account name, or search for a potentially missing account.

https://docs.microsoft.com/en-us/azure/active-directory/hybrid/reference-connect-accounts-permissions#adsync-service-account

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by scanum** [comment]
@mhendric Thanks for submitting feedback, we are investigating this.

@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @mhendric Thanks for your feedback.
I created a Pull Request to improve the article based on your feedback, adding that method as an alternative to the current one presented on the article.
Thank you

**Comment by scanum** [comment]
@mhendric Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
