### ISSUE TITLE
Wrong Example Code

### ISSUE THREAD

**Issue by reikor0x** [MicrosoftDocs/OfficeDocs-Exchange#917]
Review the command box. 
Import-ExchangeCertificate -FileName "Import-ExchangeCertificate -FileName "\\FileServer01\Data\Contoso Cert.cer" -Password (ConvertTo-SecureString -String 'P@ssw0rd1' -AsPlainText -Force)

Should be
Import-ExchangeCertificate -FileName "\\FileServer01\Data\Contoso Cert.cer" -Password (ConvertTo-SecureString -String 'P@ssw0rd1' -AsPlainText -Force)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a68571b-a717-c500-c601-8c6d4e280491
* Version Independent ID: 6581f38e-b05a-5775-4de3-6b07bbf3be47
* Content: [Complete a pending Exchange Server certificate request](https://docs.microsoft.com/en-us/exchange/architecture/client-access/complete-pending-certificate-requests?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/complete-pending-certificate-requests.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/complete-pending-certificate-requests.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@reikor0x, I fixed it. But in the future, you can, too. See https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md.

Thanks for the feedback.
