### ISSUE TITLE
More detail when using Directory synchronization

### ISSUE THREAD

**Issue by poynter2** [MicrosoftDocs/OfficeDocs-Exchange#918]
Can you provide more detail on the provision users in O365 section when Directory sync is being used? 

I assume we need to populate the TargetAddress attribute in AD which will be the ExternalAddress attribute quoted in this page, but as I understand it in O365 the TargetAddress attribute is not writable. Also, during the migration how is this attribute removed by the migration tool if it is sync'd from AD?

Also, does a licence need assigning before or after the migration has completed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#provision-users-in-o365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by poynter2** [comment]
Also, https://docs.microsoft.com/en-gb/office365/enterprise/prepare-for-directory-synchronization?redirectSourcePath=%252fen-us%252farticle%252fPrepare-to-provision-users-through-directory-synchronization-to-Office-365-01920974-9e6f-4331-a370-13aea4e82b3e#directory-object-and-attribute-preparation

"It's required that the targetAddress attribute (for example, SMTP:tom@contoso.com) that's populated for the user must appear in the Office 365 GAL."

Does this mean we cant use will@gsuite.fabrikaminc.net in the documentation as this doesn't appear in the O365 GAL?

**Comment by scanum** [comment]
@poynter2 Thanks for submitting feedback, we are investigating this.

@officedocsbot assign @scanum

**Comment by poynter2** [comment]
Thanks, do you have a timescale on an update for this?

**Comment by scanum** [comment]
@poynter2 We are currently working on this issue. We will let you know once we have an update for this. Thanks for your patience.

**Comment by get-itips** [comment]
Hello @poynter2 
Thanks for your feedback.
The procedure mentions mail users, and a mail user _(also known as mail-enabled users) have email addresses and accounts in the Exchange organization, but they don't have Exchange mailboxes yet_ 
Until you run the migration batch, which should convert them to mailboxes and then you will need to license them.
Also, the attribute that you need to provision is ExternalEmailAddress as the guide describes in Provision users in O365 section.
Hope this info helps you.

**Comment by poynter2** [comment]
Hi, I'm sorry but its still not clear, can you confirm that the GMail migration works 100% when the users are sync'd from AD and how to set the ExternalEmailAddress attribute when the users are sync'd from AD.

**Comment by nakosenk** [comment]
I'm currently going through a migration with our directory users synced with Azure AD Connect along with Exchange in a hybrid configuration. The users we're migrating were set up as Mail Users, but once we assigned them an Office 365 license, they were automatically converted to mailbox users in Office 365. Since I had a few test users, I pushed forward with the migration to see if it would work.

The big issue that we ran into is that Exchange Online is unable to change any properties for our mail users created on-premises. Once the mail migration completed, we had to update the mail user's account in our on-premises Exchange server to change the primary external SMTP email address and reply to address to user1@o365.fabrikaminc.net. The second issue, unrelated to the migration was that the migrated users didn't have an ExchangeGUID associated with their on-premises mail user accounts, but did have one with Exchange Online so we were unable to migrate the mailboxes on-premises until they matched.

**Comment by scanum** [comment]
@get-itips

**Comment by DadiRJ** [comment]
Hi @Scanum,

Will this new G suite migration process include calendar and contact information or will this only migrate emails from G Suite to Office 365?

**Comment by msdmaguire** [comment]
@DadiRJ The migration process does include calendar and contact information as well as email.

**Comment by poynter2** [comment]
> Hi, I'm sorry but its still not clear, can you confirm that the GMail migration works 100% when the users are sync'd from AD and how to set the ExternalEmailAddress attribute when the users are sync'd from AD.

Any more update on this and syc'd users please?

**Comment by scanum** [comment]
@poynter2 thank you for submitting feedback.
I think the best way forward now is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by seanbnd** [comment]
@poynter2. Did you ever find a solution for this or anymore details? I'm in the exact situation you were in with ADsync and Mail users.
