### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by hpineapples** [MicrosoftDocs/OfficeDocs-Exchange#919]
It is worth noting that as part of 'Start the staged migration batch' step, the targetAddress attribute will be configured for the on-prem user account, forwarding all mail to the Office 365 mailbox from the time you start the initial batch sync.

The more detailed steps of a migration are outlined here:
https://docs.microsoft.com/en-us/exchange/mailbox-migration/what-to-know-about-a-staged-migration#how-does-staged-migration-work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5de7d44-2a25-a86f-0bc2-a2c4c8faed31
* Version Independent ID: 14d8d4d5-297c-43d2-c528-372aeda717e3
* Content: [Perform a staged migration of email to Office 365](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-a-staged-migration/perform-a-staged-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-a-staged-migration/perform-a-staged-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-a-staged-migration/perform-a-staged-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@hpineapples Thanks for submitting feedback, we are investigating this.

@officedocsbot assign @scanum

**Comment by get-itips** [comment]
Hello @hpineapples 
Thanks for your feedback.
I analyzed both articles and came to the conclusion that no further edits need to be done on the referenced article because, the article you reference is rightly the article that contains more information on the process that implies an _performing an stage migration_, that is why it is called _What you need to know about a staged email migration to Office 365_ and comes first in the index.

Thank you

**Comment by scanum** [comment]
@hpineapples Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
