### ISSUE TITLE
Exchange 2016 Unified messaging documentation missing

### ISSUE THREAD

**Issue by pjhutch50** [MicrosoftDocs/OfficeDocs-Exchange#920]
There doesn't seem to be any documentation on Unified Messaging for Exchange 2016. In particular I am looking up on setting up Dial Plans, UM Mailbox Policies, Auto Attendant and Hunt Group setup.

**Comment by scanum** [comment]
@officedocsbot assign @scanum 

@pjhutch50 Thanks for submitting feedback. We are investigating this.

**Comment by chrisda** [comment]
@pjhutch50, I added a very plain topic for Exchange 2016 Unified Messaging that states the feature is basically unchanged from 2013, and links off to the full-featured Exchange 2013 UM content. We probably should have done that a long time ago.

Thanks for the feedback.

**Comment by pjhutch50** [comment]
Thanks very much for adding the links.


Peter Hutchison MCP
Senior Network Systems Specialist
• 01484 473716
Networks Team
University of Huddersfield | Queensgate | Huddersfield | HD1 3DH

[logo_lftcert_sysadmin_small] [MCP_logo_small]  [ITIL Foundation small]
