### ISSUE TITLE
Migration Mai box size limit?

### ISSUE THREAD

**Issue by Cjojo** [MicrosoftDocs/OfficeDocs-Exchange#922]
Their is a mailbox size limit?
G-Mail Mailbox size : 80GB
Mailbox on 365 : 22GB with the statue Synced no error.

**Comment by scanum** [comment]
@officedocsbot assign @scanum
@Cjojo Thanks for submitting feedback. We are investigating this.

**Comment by scanum** [comment]
@Cjojo hank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
