### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by CyntheSYS** [MicrosoftDocs/OfficeDocs-Exchange#923]
The link to "Integrating your on-premises identities with Azure Active Directory" under Prerequisites is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by CyntheSYS** [comment]
The closest thing I can find for where that link might be referring to is a doc from 2016.  https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/azure-ad
Is there anything more up-to-date?

**Comment by scanum** [comment]
@CyntheSYS Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@CyntheSYS Thanks for reaching out to improve MS Doc, I'm looking into it.

**Comment by Reeced40** [comment]
@CyntheSYS Could this be the correct document for you - https://docs.microsoft.com/azure/architecture/reference-architectures/identity/

**Comment by scanum** [comment]
@CyntheSYS Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
