### ISSUE TITLE
Trailing comma on Windows Features PowerShell

### ISSUE THREAD

**Issue by allanrsmith** [MicrosoftDocs/OfficeDocs-Exchange#924]
Install-WindowsFeature AS-HTTP-Activation, Desktop-Experience, NET-Framework-45-Features, RPC-over-HTTP-proxy, RSAT-Clustering, RSAT-Clustering-CmdInterface, RSAT-Clustering-Mgmt, RSAT-Clustering-PowerShell, Web-Mgmt-Console, WAS-Process-Model, Web-Asp-Net45, Web-Basic-Auth, Web-Client-Auth, Web-Digest-Auth, Web-Dir-Browsing, Web-Dyn-Compression, Web-Http-Errors, Web-Http-Logging, Web-Http-Redirect, Web-Http-Tracing, Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Lgcy-Mgmt-Console, Web-Metabase, Web-Mgmt-Console, Web-Mgmt-Service, Web-Net-Ext45, Web-Request-Monitor, Web-Server, Web-Stat-Compression, Web-Static-Content, Web-Windows-Auth, Web-WMI, Windows-Identity-Foundation, RSAT-ADDS-Tools,
Restart-Computer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45c04a0-138f-8241-0726-01fb09c3dfeb
* Version Independent ID: 730303a8-9c6f-472c-79f6-96453dea3013
* Content: [Exchange dev/test environment in Azure](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/deploy-new-installations/create-azure-test-environments?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/deploy-new-installations/create-azure-test-environments.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by scanum** [comment]
@allanrsmith Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by Reeced40** [comment]
@allanrsmith Thanks for reaching out, could you please be a bit more specific on what needs to be changed in the document? Thanks.

**Comment by davidbmarker** [comment]
Fixed and PR #947

**Comment by scanum** [comment]
@allanrsmith Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
