### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Dynowarz90** [MicrosoftDocs/OfficeDocs-Exchange#925]
In the first paragraph, there's an extra letter capitalized in "THe."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c55eac72-c0ce-5ccf-e33d-f6439ea3dadc
* Version Independent ID: 364c5da3-822a-2350-4ae1-2ecf49672bf3
* Content: [Manage role groups in Exchange Online](https://docs.microsoft.com/en-us/exchange/permissions-exo/role-groups#feedback)
* Content Source: [Exchange/ExchangeOnline/permissions-exo/role-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/permissions-exo/role-groups.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@Dynowarz90 Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
@Dynowarz90, I fixed it. But in the future, you can, too. See https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/README.md

**Comment by Dynowarz90** [comment]
Thank you @Chris and @Manuela!
