### ISSUE TITLE
This article isn't for the right version

### ISSUE THREAD

**Issue by jgordner** [MicrosoftDocs/OfficeDocs-Exchange#926]
This section about how to manage deployments of Outlook add-ins is specifically in the Exchange Server 2013 section, however, it tells you to look at the documentation for Office 365. I don't have Office 365 which is why I am looking in this section. I'd like to know how to manage user access in Exchange 2013.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38495e74-f418-ad6d-51ea-da8428bfdc11
* Version Independent ID: f8b03cd0-9d8f-b2f6-e3d5-c64949b47632
* Content: [Manage user access to add-ins for Outlook in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/manage-user-access-to-add-ins#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/manage-user-access-to-add-ins.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/add-ins-for-outlook/manage-user-access-to-add-ins.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jgordner Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hello @jgordner 
You're looking at the wrong part of the documentation:
the links is here:
https://docs.microsoft.com/en-us/exchange/manage-user-access-to-add-ins-2013-help

**Comment by scanum** [comment]
@jgordner Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
