### ISSUE TITLE
Wrong ID for Microsoft Exchange Approval Assistant Mailbox

### ISSUE THREAD

**Issue by AndreyNov** [MicrosoftDocs/OfficeDocs-Exchange#93]
There are 2 different IDs used for Microsoft Exchange Approval Assistant Mailbox in 2 different places of the article.
SystemMailbox{1f05a927-9350-4efe-a823-5529c2d64109}
SystemMailbox{1f05a927-7709-4e35-9dbe-d0f608fb781a}
In our Exchange organization there are no System Mailboxes with such IDs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca0013eb-5599-a907-9869-569f40f1e725
* Version Independent ID: 9fd23081-2830-c87b-561b-582fb16fc09e
* Content: [Recreating arbitration mailboxes](https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/recreate-arbitration-mailboxes)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/recreate-arbitration-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@AndreyNov I confirmed your findings: on 3 different Exchange 2016 servers, I got 3 different names for the Microsoft Exchange Approval Assistant Mailbox, although they all started with "SystemMailbox{1f05a927-...".

I updated the topic accordingly, along with other general clean-up and fixes.

Thanks for the feedback.

**Comment by chrisda** [comment]
I heavily updated the topic; but I had some issues with the PR. I'll get it done as soon as I can.

**Comment by chrisda** [comment]
Updates to topic confirmed. Closing.
