### ISSUE TITLE
Missing 587 port in the load balancing table

### ISSUE THREAD

**Issue by reikor0x** [MicrosoftDocs/OfficeDocs-Exchange#930]
Also the port 587 (SMTP for client) should be balanced

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4bfd3e-15c4-d7ab-f4c8-579352581bb3
* Version Independent ID: 6178892e-ec14-d9de-cd17-aeee5302994b
* Content: [Load balancing in Exchange Server](https://docs.microsoft.com/en-us/exchange/architecture/client-access/load-balancing?view=exchserver-2016)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/load-balancing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/load-balancing.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@reikor0x Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solving issue with PR #1005

**Comment by scanum** [comment]
@reikor0x Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
