### ISSUE TITLE
PHPMailer und office.de

### ISSUE THREAD

**Issue by Ascawath** [MicrosoftDocs/OfficeDocs-Exchange#936]
Hello,
I tried for quite some time to work with PHPMailer and Wordpress 
via office.de and SMTP client submission, like [described](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3). Badly unsuccessful.
I tried different combination of port and encrypting (587,25,465 => tls,ssl) as well as SMTP_HOST (smtp.office.de, smtp.office.com, smtp.office365.de, smtp.office365.com).
Regardless of which combination I tried, not any works. PHPMailer only returns a timeout.

Since the description is for Office.com I don't know whether this issue is only for Office.de. I also checked the license of the mail address and can log in via Outlook, Thunderbird and webmail.
Only a log in via PHPMailer seems to be impossible. 

Is there anything I missed?
configuration:
define( 'SMTP_USER',   '*@*.de');              
define( 'SMTP_PASS',   '*****************************');                     
define( 'SMTP_HOST',   'smtp.office.de');                       
define( 'SMTP_FROM',   '*@*.de');   
define( 'SMTP_NAME',   'FooBar');     
define( 'SMTP_PORT',   '587');                                   
define( 'SMTP_SECURE', 'tls');
define( 'SMTP_AUTH',    true);                                 
define( 'SMTP_DEBUG', 4); 

Best regards

**Comment by scanum** [comment]
@Ascawath Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@Ascawath hank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
