### ISSUE TITLE
Error in Step 4 Creating Public Folder Mailboxes

### ISSUE THREAD

**Issue by jpenntnc** [MicrosoftDocs/OfficeDocs-Exchange#942]
I get the following error when running the Step 4 commands.  I verified that the account used for the command is in the Org Management group.  

A positional parameter cannot be found that accepts argument 'Mailbox2'.
    + CategoryInfo          : InvalidArgument: (:) [New-Mailbox], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,New-Mailbox
    + PSComputerName        : outlook.office365.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39afa127-7aec-9a5d-96cd-d0dfe5c63e52
* Version Independent ID: d2d5a81d-8c9c-9383-6335-e3dbd392feb8
* Content: [Use batch migration to migrate Exchange 2013 public folders to Exchange Online](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/batch-migration-of-exchange-2013-public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-exchange-2013-public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/batch-migration-of-exchange-2013-public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@jpenntnc Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by msdmaguire** [comment]
@jpenntnc One suggestion from the product team is to verify that no duplicate public folder mailboxes exist. If issues remain, please open a support ticket.

**Comment by jpenntnc** [comment]
I opened a ticket.
