### ISSUE TITLE
On-prem Exchange server still required with Pass-Through Authentication?

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/OfficeDocs-Exchange#943]
If we're in scenario 2, and move away from ADFS to pass-through authentication, we still need the on-premise Exchange server because of directory sync (Azure AD Connect) correct?
The article suggests that the dependency is due to ADFS, but is it actually on directory sync?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@dsolodow Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Solving issue on PR #1006

**Comment by dsolodow** [comment]
I'm not just talking about authentication though; write scope is important as well. If you have ADFS & Azure AD Connect, and you try to say hide a cloud mailbox from the GAL, it throws an error that it's outside the write scope as it's being synced from on-premise, and that you need to make the change there.
You still need an on-prem Exchange server to make such changes to the "remote mailbox".

**Comment by j0rt3g4** [comment]
@dsolodow  When you have an on-premise exchange and users in there you use the "GAL" that the exchange server uses when you don't have an exchange server because all the mailboxes are on the cloud, there are no GAL on-premises where you should do these changes (in my opinion) so it needs to be done on cloud.

Here's an interesting link about what we are discussing...
https://jackstromberg.com/2018/08/how-to-hide-users-from-the-gal-in-office-365-synchronized-from-on-premises/

**Comment by scanum** [comment]
@dsolodow Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close

**Comment by kstario** [comment]
Regarding Scenario 2 - The one thing I can't figure out is why not use the attribute editor tab in ADUC to edit the exchange attributes? Why is it required to leave Exchange installed when the Exchange attributes are in AD and can be edited via attribute editor?
