### ISSUE TITLE
Problem completing migration

### ISSUE THREAD

**Issue by jkieburtz** [MicrosoftDocs/OfficeDocs-Exchange#944]
### Each migration, from GSuite, sync's fine but when I complete the migration I get the messages below repeated over and over!

5/11/2019 2:18:55 PM [MWHPR14MB1245] The Microsoft Exchange Mailbox Replication service 'MWHPR14MB1245.namprd14.prod.outlook.com' (15.20.1878.22 ServerCaps:01FFFFFF, ProxyCaps:0FFFFFC7FD6DFDBF5FFFFFCB07EFFF, MailboxCaps:, legacyCaps:01FFFFFF) is examining the request.
5/11/2019 2:18:55 PM [MWHPR14MB1245] Connected to target mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)', database 'NAMPR14DG078-db127', Mailbox server 'MWHPR14MB1245.namprd14.prod.outlook.com' Version 15.20 (Build 1878.0).
5/11/2019 2:18:55 PM [MWHPR14MB1245] Replay sync state for request 807f6ea9-2463-4bc0-adc1-8dd1f9bf06a2 is null.
5/11/2019 2:18:57 PM [MWHPR14MB1245] Connected to source mailbox 'REDACTED-d504dd814635a87e44fd47983323a247@xxxxxxxxxxx.net (Unified)', database '', Mailbox server 'imap.gmail.com:993 (GmailSync)' Version 0.0 (Build 0.0), proxy server 'MWHPR14MB1245.namprd14.prod.outlook.com' 15.20.1878.22 ServerCaps:01FFFFFF, ProxyCaps:0FFFFFC7FD6DFDBF5FFFFFCB07EFFF, MailboxCaps:, legacyCaps:0FFFFFC7FD6DFDBF5FFFFFCB07EFFF.
5/11/2019 2:18:57 PM [MWHPR14MB1245] Request processing started.
5/11/2019 2:19:35 PM [MWHPR14MB1245] Stage: CopyingMessages. Percent complete: 95.
5/11/2019 2:19:35 PM [MWHPR14MB1245] Copy progress: 0/0 messages, 0 B (0 bytes)/0 B (0 bytes), 0/0 folders completed.
5/11/2019 2:19:36 PM [MWHPR14MB1245] Stage: IncrementalSync. Percent complete: 95.
5/11/2019 2:20:01 PM [MWHPR14MB1245] Content changes reported for mailbox 'REDACTED-d504dd814635a87e44fd47983323a247@xxxxxxxxxxx.net (Unified)': Folder 'Root//Spam [JunkEmail] [len=10, data=4A756E6B20456D61696C]' Batch 1, New 1, Changed 0, Deleted 3, Read 0, Unread 0, Item Updates 0 Total 4. 
5/11/2019 2:20:02 PM [MWHPR14MB1245] Total content changes applied to mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)': Folder '/Top of Information Store/Junk Email [JunkEmail]' New 1, Changed 0, Deleted 3, Read 0, Unread 0, Item Updates 0, Skipped 0, Total 4.
5/11/2019 2:22:46 PM [MWHPR14MB1245] Content changes reported for mailbox 'REDACTED-d504dd814635a87e44fd47983323a247@xxxxxxxxxxx.net (Unified)': Folder 'Root//All Mail [Archive] [len=8, data=416C6C204D61696C]' Batch 1, New 0, Changed 0, Deleted 135094, Read 0, Unread 0, Item Updates 0 Total 135094. 
5/11/2019 2:26:13 PM [MWHPR14MB1245] Total content changes applied to mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)': Folder '/Top of Information Store/Archive [Archive]' New 0, Changed 0, Deleted 0, Read 0, Unread 0, Item Updates 0, Skipped 0, Total 0.
5/11/2019 2:26:13 PM [MWHPR14MB1245] Total content changes applied to mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)': New 1, Changed 0, Deleted 3, Read 0, Unread 0, ItemUpdates 0, Skipped 0, Total 4.
5/11/2019 2:26:13 PM [MWHPR14MB1245] Incremental Sync 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)' completed: 0 hierarchy updates, 4 content changes.
5/11/2019 2:26:13 PM [MWHPR14MB1245] Source mailbox information:
Regular Items: 0, 0 B (0 bytes)
Regular Deleted Items: 0, 0 B (0 bytes)
FAI Items: 0, 0 B (0 bytes)
FAI Deleted Items: 0, 0 B (0 bytes)
5/11/2019 2:26:13 PM [MWHPR14MB1245] Target mailbox information:
Regular Items: 44289, 17.5 GB (18,785,559,449 bytes)
Regular Deleted Items: 81, 1.078 MB (1,130,231 bytes)
FAI Items: 49, 1.008 MB (1,057,252 bytes)
FAI Deleted Items: 0, 0 B (0 bytes)
5/11/2019 2:26:13 PM [MWHPR14MB1245] Copying messages is complete. Copying rules and security descriptors.
5/11/2019 2:26:13 PM [MWHPR14MB1245] Stage: IncrementalSync. Percent complete: 95.
5/12/2019 2:26:42 PM [CY4PR14MB1240] The Microsoft Exchange Mailbox Replication service 'CY4PR14MB1240.namprd14.prod.outlook.com' (15.20.1878.23 ServerCaps:01FFFFFF, ProxyCaps:0FFFFFC7FD6DFDBF5FFFFFCB07EFFF, MailboxCaps:, legacyCaps:01FFFFFF) is examining the request.
5/12/2019 2:26:42 PM [CY4PR14MB1240] Connected to target mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)', database 'NAMPR14DG078-db127', Mailbox server 'CY4PR14MB1240.namprd14.prod.outlook.com' Version 15.20 (Build 1878.0).
5/12/2019 2:26:43 PM [CY4PR14MB1240] Replay sync state for request 807f6ea9-2463-4bc0-adc1-8dd1f9bf06a2 is null.
5/12/2019 2:26:45 PM [CY4PR14MB1240] Connected to source mailbox 'REDACTED-d504dd814635a87e44fd47983323a247@xxxxxxxxxxx.net (Unified)', database '', Mailbox server 'imap.gmail.com:993 (GmailSync)' Version 0.0 (Build 0.0), proxy server 'CY4PR14MB1240.namprd14.prod.outlook.com' 15.20.1878.23 ServerCaps:01FFFFFF, ProxyCaps:0FFFFFC7FD6DFDBF5FFFFFCB07EFFF, MailboxCaps:, legacyCaps:0FFFFFC7FD6DFDBF5FFFFFCB07EFFF.
5/12/2019 2:26:45 PM [CY4PR14MB1240] Request processing started.
5/12/2019 2:27:19 PM [CY4PR14MB1240] Stage: IncrementalSync. Percent complete: 95.
5/12/2019 2:27:46 PM [CY4PR14MB1240] Content changes reported for mailbox 'REDACTED-d504dd814635a87e44fd47983323a247@xxxxxxxxxxx.net (Unified)': Folder 'Root//Spam [JunkEmail] [len=10, data=4A756E6B20456D61696C]' Batch 1, New 2, Changed 0, Deleted 0, Read 0, Unread 0, Item Updates 0 Total 2. 
5/12/2019 2:27:47 PM [CY4PR14MB1240] Stage: IncrementalSync. Percent complete: 95.
5/12/2019 2:27:47 PM [CY4PR14MB1240] Total content changes applied to mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)': Folder '/Top of Information Store/Junk Email [JunkEmail]' New 2, Changed 0, Deleted 0, Read 0, Unread 0, Item Updates 0, Skipped 0, Total 2.
5/12/2019 2:30:28 PM [CY4PR14MB1240] Content changes reported for mailbox 'REDACTED-d504dd814635a87e44fd47983323a247@xxxxxxxxxxx.net (Unified)': Folder 'Root//All Mail [Archive] [len=8, data=416C6C204D61696C]' Batch 1, New 0, Changed 0, Deleted 2, Read 0, Unread 0, Item Updates 0 Total 2. 
5/12/2019 2:30:28 PM [CY4PR14MB1240] Total content changes applied to mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)': Folder '/Top of Information Store/Archive [Archive]' New 0, Changed 0, Deleted 0, Read 0, Unread 0, Item Updates 0, Skipped 0, Total 0.
5/12/2019 2:30:28 PM [CY4PR14MB1240] Total content changes applied to mailbox 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)': New 2, Changed 0, Deleted 0, Read 0, Unread 0, ItemUpdates 0, Skipped 0, Total 2.
5/12/2019 2:30:28 PM [CY4PR14MB1240] Incremental Sync 'xxxxxxxxxxxnet.onmicrosoft.com\d727ea98-9f3c-4a77-aab6-3b42bca0c5de (Primary)' completed: 0 hierarchy updates, 2 content changes.
5/12/2019 2:30:28 PM [CY4PR14MB1240] Source mailbox information:

**Comment by scanum** [comment]
@jkieburtz thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
