### ISSUE TITLE
Link to download Exchange 2016 PDF is actually downloading 2019 version

### ISSUE THREAD

**Issue by zantutneto** [MicrosoftDocs/OfficeDocs-Exchange#945]
When navigating on **Exchange 2016** documentation and clicking on the Download PDF link on the bottom of the page is actually downloading the **Exchange 2019** pdf documentation.

The link on the bottom of the page directs to: https://docs.microsoft.com/en-us/Exchange/opbuildpdf/exchserver-dest/servertoc/toc.pdf?branch=live&view=exchserver-2016

On the begining of the documentation that is downloaded on this link, you can check:
"What's new in Exchange Server
ExchangeServer **2019** brings a new set of technologies, features,and services to ExchangeServer, the messaging platform that provides....."

![img1](https://user-images.githubusercontent.com/50669396/57785222-ad734580-7707-11e9-93ef-b8ef824fd700.png)
![img2](https://user-images.githubusercontent.com/50669396/57785223-ad734580-7707-11e9-88a4-254d0ac6fdcc.png)

**Comment by scanum** [comment]
@zantutneto  Thank you for submitting feedback and contributing to the docs. Could you please provide a link to the documentation? 

 @officedocsbot assign @scanum

**Comment by zantutneto** [comment]
This is the link. https://docs.microsoft.com/en-us/Exchange/exchange-server?view=exchserver-2016


I just want do download it as PDF for exchange 2016. But link from 2016 is downloading the PDF for 2019.

**Comment by j0rt3g4** [comment]
@zantutneto You are right on this.
The thing is that the commands for 2016 and 2019 are basically the same. That's the main reason what I'd suggest to try the 2019 versión on the topics you're requesting.

So far I'd let know @scanum if she can find on MS who can verify this link. Thank you for the report

**Comment by scanum** [comment]
@zantutneto thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
