### ISSUE TITLE
Some information missing for Exchange 2003 cutover

### ISSUE THREAD

**Issue by RobC-CTL** [MicrosoftDocs/OfficeDocs-Exchange#948]
There are a couple of important points that need adding for Exchange 2003 cutover migrations.

TCP 6001, 6002 and 6004 need to be opened on the firewall to allow Office 365 to connect to the Exchange server with RPC, with these ports you get an error when trying to validate the endpoint connection.

On the endpoint configuration, 2003 doesn't support autodisover.  In this case you need to click the "more options" box and set the authentication to basic and set the mailbox permission to either "Full Access" if using mailbox permissions in Exchange or "Domain Admin" if using a Domain Admin account.

Rob.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 721f096d-23d4-0fed-4f5e-0e0964798e8f
* Version Independent ID: 3af25c86-f5e9-1b9c-ffb6-d0d1afa7210e
* Content: [Migrate email using the Exchange cutover method](https://docs.microsoft.com/en-us/exchange/mailbox-migration/cutover-migration-to-office-365#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/cutover-migration-to-office-365.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@RobC-CTL Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@RobC-CTL Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
