### ISSUE TITLE
Please update this document for Exchange 2019

### ISSUE THREAD

**Issue by muszyngr** [MicrosoftDocs/OfficeDocs-Exchange#950]
this article states for Exchange 2016 we must install the Mailbox role on prem but that contradicts the latest Hybrid mode license agreement which says we should not install a mailbox role

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e6349f-a40f-ea78-03c8-1506b195f8fa
* Version Independent ID: d97e8315-ddf1-1372-e9aa-bdb40a7de2b8
* Content: [Exchange Server Hybrid Deployments](https://docs.microsoft.com/en-us/exchange/exchange-hybrid#feedback)
* Content Source: [Exchange/ExchangeHybrid/exchange-hybrid.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/exchange-hybrid.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by davidbmarker** [comment]
@muszyngr, what Hybrid Mode License Agreement are you looking at?

**Comment by scanum** [comment]
@muszyngr

**Comment by VLG17** [comment]
@muszyngr the information is correct. 

In order for a Hybrid Exchange configuration to exist, you need both Exchange Online and Exchange on-premises. In Exchange 2016, there is only the Mailbox Role (and Edge but it's not relevant for this discussion), so you need to install that on-premises

**Comment by scanum** [comment]
@muszyngr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
