### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by jamesamayes** [MicrosoftDocs/OfficeDocs-Exchange#954]
Import-Content : The term 'Import-Content' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cf11da-901c-8c9f-2aa3-887c05844e51
* Version Independent ID: 0a2b3d28-f0be-9317-6180-cca2bf89f879
* Content: [Use mail flow rules to route email based on a list of words, phrases, or patterns in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/use-rules-to-route-email#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-route-email.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/use-rules-to-route-email.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@jamesamayes Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by calvinscottforbes** [comment]
@jamesamayes @scanum I used Get-Content and it works well.

**Comment by chrisda** [comment]
@jamesamayes, I replaced Import-Content with Get-Content.

@calvinscottforbes, thanks for the assist.

**Comment by jamesamayes** [comment]
I'm new at this so bear with me.  When I view the page (https://docs.microsoft.com/en-us/exchange/security-and-compliance/mail-flow-rules/use-rules-to-route-email) it still shows import-content and the page shows it was last updated on 06‎/‎22‎/‎2018.  Does it take awhile for the page to update and the change to use Get-Content to show up?
