### ISSUE TITLE
Migration completion - not consistent info (https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)

### ISSUE THREAD

**Issue by maxstv** [MicrosoftDocs/OfficeDocs-Exchange#955]
Hello,

----------------------------------------------------------------------------------------
Question 1

Documentation article states -

===========================
During completion, another incremental sync is run to copy any changes that have been made to the G Suite mailbox. Additionally, the forwarding address that routes mail from O365 to G Suite is removed, and a forwarding address that routes mail from G Suite to O365 is added. This ensures that any messages received by migrated users at their G Suite mailboxes will be sent to their new Office 365 address. Similarly, if any user who has not yet been migrated receives a message at their Office 365 address, the message will get routed to their G Suite mailbox.
===========================

I have a question in regards of forwarding address that routes email from G Suite to O365 - where exactly it is being added? Gmail End-user routing has been discontinued as per screenshot below.

It does not look like this process is automated and requires additional extra step to upload recipient address mapping list in Gmail "Advanced Settings" (https://admin.google.com/AdminHome?hl=en&pli=1&fral=1#ServiceSettings/service=email&subtab=filters)

https://user-images.githubusercontent.com/15049286/57990028-fbac8e00-7ae5-11e9-9140-a8308959f190.png

----------------------------------------------------------------------------------------

Question 2

Sync is successful, however on completion we receive error which states that "COMPANY.mail.onmicrosoft.com" email alias is not found.

5/17/2019 9:51:45 AM [ME4PR03MB2238] Copying messages is complete. Copying rules and security descriptors.
5/17/2019 9:51:45 AM [ME4PR03MB2238] Stage: IncrementalSync. Percent complete: 95.
5/17/2019 9:51:45 AM [ME4PR03MB2238] Final sync has started.
5/17/2019 9:51:45 AM [ME4PR03MB2238] Target mailbox 'COMPANY.onmicrosoft.com\ce73f1b1-baef-4c8c-91ed-126de86da3ec (Primary)' was updated on domain controller 'MEXPR01A007DC05.AUSPR01A007.PROD.OUTLOOK.COM'.
5/17/2019 9:51:45 AM [ME4PR03MB2238] Fatal error TargetDeliveryDomainMismatchPermanentException has occurred.
----------------------------------------------------------------------------------------

Thanks.

**Comment by scanum** [comment]
@maxstv - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by wrall** [comment]
@maxstv 

Regarding the first question, the document indicates the routing is accomplished by automatically applying a [Forwarding Address](https://support.google.com/mail/answer/10957). 

For the second question, that indicates that there was an issue following steps either [using the sub-domain for routing to O365 as the target delivery domain](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-office-365) or ensuring that the users they [provisioned have an email address in their email addresses list that is at that routing domain](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#provision-users-in-o365). 

Please follow up with support for more information.

**Comment by maxstv** [comment]
> @maxstv
> 
> Regarding the first question, the document indicates the routing is accomplished by automatically applying a [Forwarding Address](https://support.google.com/mail/answer/10957).
> 
> For the second question, that indicates that there was an issue following steps either [using the sub-domain for routing to O365 as the target delivery domain](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-office-365) or ensuring that the users they [provisioned have an email address in their email addresses list that is at that routing domain](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#provision-users-in-o365).
> 
> Please follow up with support for more information.

Is there a way to automatically setup forwarding in Gmail?

What is happening is that Gmail users receive an email with authorization code which they require to confirm in order to setup forwarding from Gmail to O365 - it is manual task which involves actual user effort. Is there a way to set forwarding in Gmail without any user action?

**Comment by wrall** [comment]
> @maxstv
> Is there a way to automatically setup forwarding in Gmail?

Yes.  The tool uses a Gmail API to [create the forwarding address](https://developers.google.com/gmail/api/v1/reference/users/settings/forwardingAddresses/create) and another one to [set it as the auto-forwarding address in use](https://developers.google.com/gmail/api/v1/reference/users/settings/updateAutoForwarding).
 
> @maxstv
> What is happening is that Gmail users receive an email with authorization code which they require to confirm in order to setup forwarding from Gmail to O365 - it is manual task which involves actual user effort. Is there a way to set forwarding in Gmail without any user action?

If you verify the O365 routing domain (as suggested in the [instructions](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-office-365)), then the forwarding address will be verified automatically without requiring any user involvement/interaction.

**Comment by maxstv** [comment]
> > @maxstv
> > Is there a way to automatically setup forwarding in Gmail?
> 
> Yes. The tool uses a Gmail API to [create the forwarding address](https://developers.google.com/gmail/api/v1/reference/users/settings/forwardingAddresses/create) and another one to [set it as the auto-forwarding address in use](https://developers.google.com/gmail/api/v1/reference/users/settings/updateAutoForwarding).
> 
> > @maxstv
> > What is happening is that Gmail users receive an email with authorization code which they require to confirm in order to setup forwarding from Gmail to O365 - it is manual task which involves actual user effort. Is there a way to set forwarding in Gmail without any user action?
> 
> If you verify the O365 routing domain (as suggested in the [instructions](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#create-a-sub-domain-for-mail-routing-to-office-365)), then the forwarding address will be verified automatically without requiring any user involvement/interaction.

Brilliant! Thanks a lot for your help!

My mistakes here was that I was starting MS Exchange Online migration batch via GUI and custom "Target Delivery Domain" name was not in the list and I left it be default.

PowerShell resolves the issue, e.g. 
=====================
New-MigrationBatch -SourceEndpoint "gmail-migration" -Name "mailboxes_to_migrate" -CSVData $([System.IO.File]::ReadAllBytes("C:\mailboxes_to_migrate.csv")) -TargetDeliveryDomain "o365.domainname.net"
=====================
For some reasons, in GUI migration wizard, there is no custom "Target Delivery Domain" but only default "COMPANYNAME.mail.onmicrosoft.com" one. Using PowerShell command above resolves the issue and forwarding at Gmail is automatically set.

Another question though - in Gmail, forwarding automatically set to forward to O365 and keep a copy in Gmail mailbox. Is there a way to automatically set it to forward to O365 and DO NOT keep a copy in Gmail?

**Comment by wrall** [comment]
> @maxstv 
> For some reasons, in GUI migration wizard, there is no custom "Target Delivery Domain" but only default "COMPANYNAME.mail.onmicrosoft.com" one. Using PowerShell command above resolves the issue and forwarding at Gmail is automatically set.

Yep, for this reason we recently changed the documentation to indicate that the admin needs to "enter" (i.e. "type in") the Target Delivery Domain in the EAC New Migration Batch Wizard.  The UI doesn't have a way to determine what the admin used for a routing domain in advance.

> @maxstv 
> Another question though - in Gmail, forwarding automatically set to forward to O365 and keep a copy in Gmail mailbox. Is there a way to automatically set it to forward to O365 and DO NOT keep a copy in Gmail?

Not that I'm aware of.  As a current customer, I would suggest that you could ask them to add such a functionality.  You can say that Exchange/Office365 has that feature (called "Deliver To And Forward").  :-)
