### ISSUE TITLE
Google Contacts API vs Contacts API

### ISSUE THREAD

**Issue by JustinCredible-** [MicrosoftDocs/OfficeDocs-Exchange#956]
I had to enable the Contacts API to get the sync to work properly. The Google Contacts API was enabled but the logs were specifically showing an error because the Contacts API was not enabled. Did that and sync completed successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@JustinCredible- Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by wrall** [comment]
@scanum - @JustinCredible is correct.  I can fix this issue within the document and will add it to my current Pull Request.
