### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by vefaakinaktan** [MicrosoftDocs/OfficeDocs-Exchange#957]
Good
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40c92567-1479-8a19-9ee6-cc3563ed5bfc
* Version Independent ID: 313638dc-b9dc-9e58-50a9-b46245c8e35e
* Content: [Fix email delivery issues for error code 550 5.1.1 through 5.1.20 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online?redirectSourcePath=%252farticle%252f79e91ade-5c83-405b-a37d-d99c7d069b13)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-1-through-5-1-20-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@vefaakinaktan Thank you for your feedback. Is there anything that we can help you with? or anything that you suggest to add to the docs?

@officedocsbot assign @scanum

**Comment by vefaakinaktan** [comment]
Well i will write in a week. Thanks

**Comment by scanum** [comment]
@vefaakinaktan We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
