### ISSUE TITLE
Coexistence rule mismatch: consequences?

### ISSUE THREAD

**Issue by fdari** [MicrosoftDocs/OfficeDocs-Exchange#958]
Obviously, if a rule is not defined for Exchange 2010, Exchange 2010 servers will not process it. However, if a rule is not replicated (skipped/incompatible) to E2010, should it still work as long as the message is processed exclusively by Exchange 2016? I would think so, but I am experiencing difficulty with RouteMessageOutboundRequireTLS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42cb906e-a676-8a6f-825e-8da2dc04a2a3
* Version Independent ID: c1a7ff8b-34cf-3d14-8f5e-8a5c5487d91e
* Content: [Mail flow rules (transport rules) in Exchange 2013: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/mail-flow-rules-transport-rules-in-exchange-2013-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/mail-flow-rules-transport-rules-in-exchange-2013-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/mail-flow-rules-transport-rules-in-exchange-2013-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@fdari - Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@fdari Thank you for your feedback. This document is exclusive for exchange 2013 and you are correct about the transport rule as it should work as long as the message is processed on that Exchange server. You may need to contact support for the issue you are facing.

**Comment by scanum** [comment]
@fdari Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
