### ISSUE TITLE
Missing requirements for HCW

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/OfficeDocs-Exchange#959]
We need to specify the requirements for the HCW, however slim they are. E.g. need to mention it requires .Net framework 4.6.2 Full in order to run. This can be an issue for servers running Exchange 2010 as it runs on 3.5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@v-olduch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @v-olduch, thank you for your valuable feedback.

I have added this prerequisite.

You can install .net 4.6.2 on Exchange 2010. It's not a clear statement but you can see that in the second note:
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/supportability-matrix?view=exchserver-2019#exchange-2010-sp3

**Comment by v-olduch** [comment]
Wonderful! Thank you


Olivier Ducharme (Experis)
FastTrack Engineer – Office ProPlus SME
Microsoft Fasttrack Center
http://fasttrack.microsoft.com<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Ffasttrack.microsoft.com%2F&data=02%7C01%7C%7Cbe273a851f854a102ea108d602b8db61%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636699390303575606&sdata=Y8foqb62DknuM7ddlJxcIFWEvKwh16zo6WmFHmnNyPA%3D&reserved=0>
Office: +14384769938 (9AM -6PM EST)
v-olduch@microsoft.com<mailto:v-olduch@microsoft.com>

[cid:image005.jpg@01D43480.2FDC1E00]             [cid:image006.png@01D43480.2FDC1E00]


My goal is to offer you the best possible experience with the Microsoft FastTrack Center.
If you need any assistance that I am unable to offer, please contact my Team Lead: Shadi Saliqa at ssaliqa@microsoft.com<mailto:ssaliqa@microsoft.com> and +1 (438) 771-9984

Please note that if you have received this message in error, you are hereby notified that any dissemination of this communication is strictly prohibited. Please notify me immediately by reply e-Mail and delete all copies of the original message.

**Comment by scanum** [comment]
@v-olduch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
