### ISSUE TITLE
"FAQ: Public folders" link points to doc with same title for different product

### ISSUE THREAD

**Issue by kamereone** [MicrosoftDocs/OfficeDocs-Exchange#96]
The link for "FAQ: Public folders" (http://technet.microsoft.com/library/1cdcdcb7-f11b-45ca-ad23-7c38f640208c.aspx) points to an article written about migration for Exchange Server 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23fc906e-3899-1d89-836c-a441508b1107
* Version Independent ID: fce642c6-03fb-b344-ed2b-19fcdfc323ce
* Content: [Public folders in Office 365 and Exchange Online](https://docs.microsoft.com/en-us/Exchange/collaboration-exo/public-folders/public-folders)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/public-folders.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by AndreaBarr** [comment]
@kamereone Thank you for this feedback

I want to get this link corrected and thank you for pointing this out. I am getting this to the SharePoint team so we can get this addressed properly. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.
