### ISSUE TITLE
Outlook Anywhere

### ISSUE THREAD

**Issue by v-olduch** [MicrosoftDocs/OfficeDocs-Exchange#960]
Cannot find documentation stating whether this is needed, optional, or not required, relative to different Exchange server version. Would also need to have impact of not enabling Outlook anywhere specified for the sake of clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@v-olduch Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @v-olduch, thank you for your valuable feedback.

Outlook Anywhere is not required in a Exchange Hybrid deployment. Prerequisites not listed in this doc aren't required.

One exception could be if you want to configure public folders for a hybrid deployment:
https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders
https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders

**Comment by scanum** [comment]
@v-olduch Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
