### ISSUE TITLE
Not verifying o365.fabrikaminc.net in G Suite

### ISSUE THREAD

**Issue by nakosenk** [MicrosoftDocs/OfficeDocs-Exchange#962]
What does adding o365.fabrikaminc.net as a verified domain to G Suite accomplish? Is it included in the instructions so that users just need to add one email address in the CSV migration that covers both instances?

The reason I ask is because we are migrating users from a separate G Suite tenant to our Exchange services, but we also have an additional G Suite tenant that is synced by primary email address in Active Directory and we'd like to get the users we migrated up and running in the new primary G Suite using their o365.fabrikaminc.net addresses, but we're unable to verify the domain while the previous G Suite tenant has it verified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/perform-g-suite-migration#create-a-migration-batch-in-office-365)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
@nakosenk  Adding “o365.fabrikaminc.net” as a verified domain in G Suite allows the Migration tool to automatically add a forwarding address of the form “user1@o365.fabrikaminc.net” to a user without that user having to verify that forwarding address manually.  That forwarding address is used for mail routing during the coexistence period of a staged migration.  The easiest approach is to use some subdomain of your primary domain in G Suite as that will avoid having to do more advanced domain verification, but that subdomain doesn’t necessarily need to be “o365”.

**Comment by nakosenk** [comment]
Thanks for the info, I didn't realize that G Suite needed a verification to forward email to external addresses. You may want to update the documentation that specifically calls out that quirk of G Suite.

Since we're using directory synchronization in our environment, I need to manually update the user's email address in Exchange on-premises once their migration is complete. I'll get another subdomain verified and move them to that once the migration completes.

**Comment by msdmaguire** [comment]
@nakosenk Thank you for the feedback, we'll add it to our list of work items.
