### ISSUE TITLE
Clarify if shared mailbox is supported for alternate

### ISSUE THREAD

**Issue by cmcapellan** [MicrosoftDocs/OfficeDocs-Exchange#963]
This page doesn't specify if a shared mailbox is supported as the alternate journaling mailbox. For security, it would be preferable to always have direct login disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8d4ec80-7a55-398a-22e9-3f5df24a867b
* Version Independent ID: 4543c414-41d1-b8fe-8a58-4dc61ccf61ff
* Content: [Journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@cmcapellan, the journaling mailbox or alternate journaling mailbox can't be in Exchange Online, regardless of what kind of mailbox it is. If you have an on-premises Exchange Server organization, sure you could setup the journaling/alternate journaling mailboxes for Exchange Online there as shared mailboxes.

After that, Exchange Online doesn't care; you can lite

**Comment by cmcapellan** [comment]
Hi @chrisda, thanks for the reply! I do see the docs clearly say you can't have your primary journaling mailbox in EXO, but would be helpful to specify you can't have the alternate in EXO either.

We no longer have any on-prem Exchange, just the stub hybrid server. So I guess we can't have an alternate journaling mailbox period.

**Comment by scanum** [comment]
@cmcapellan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@cmcapellan Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
