### ISSUE TITLE
SafeSendersHash

### ISSUE THREAD

**Issue by walvisam** [MicrosoftDocs/OfficeDocs-Exchange#969]
Hello, maybe is good idea to update this article to add the following at least until today May 2019, IsInSafeSendersHash, IsInSafeRecipientsHash and IsInBlockedSendersHash are not syncing for shared mailboxes in Exchange Online, by default. So, EOP will no honor the safe sender list the shared mailbox has.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d60d2b1b-7f97-088e-9b2f-a655704017e9
* Version Independent ID: ebc575cb-5c3f-d069-6ccf-2990a7421935
* Content: [Safelist aggregation](https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antispam-protection/safelist-aggregation?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/safelist-aggregation.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/antispam-and-antimalware/antispam-protection/safelist-aggregation.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@walvisam thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
