### ISSUE TITLE
Incorrect procedure in "Step 6: Lock down the public folders on the legacy Exchange server for final migration"

### ISSUE THREAD

**Issue by QM-75** [MicrosoftDocs/OfficeDocs-Exchange#970]
It states that running "Set-OrganizationConfig -PublicFoldersLockedForMigration:$true" on Legacy sever (2007 in my case) and the  migration batch file does not finalize (PublicFolderMigrationComplete displays False), on the legacy server, restart the Information Store (IS). 
I did this several times, no change. To proceed  I ran the "Complete-MigrationBatch" cmd and proceeded the migration to success following the remaining steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8461539-6b09-70a8-f9f4-58e0c4a0618e
* Version Independent ID: 2b395f25-b532-dc97-e442-ae3f1842c95f
* Content: [Use batch migration to migrate public folders to Exchange 2013 from previous versions](https://docs.microsoft.com/en-us/exchange/use-batch-migration-to-migrate-public-folders-to-exchange-2013-from-previous-versions-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/use-batch-migration-to-migrate-public-folders-to-exchange-2013-from-previous-versions-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/use-batch-migration-to-migrate-public-folders-to-exchange-2013-from-previous-versions-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@QM-75 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msbemba** [comment]
@QM-75  Thank you for your feedback. You are correct, the note should have been in step 7 instead of 6. I have made the changes to the doc via PR https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/990

**Comment by scanum** [comment]
@officedocsbot close
