### ISSUE TITLE
OWAEnabled not found

### ISSUE THREAD

**Issue by pkothree** [MicrosoftDocs/OfficeDocs-Exchange#972]
I'm trying to use this command "Set-CASMailbox -Identity "Yan Li" -OWAEnabled $false", but PowerShell returns:
"A parameter cannot be found that matches parameter name 'OWAEnabled'.
    + CategoryInfo          : InvalidArgument: (:) [Set-CASMailbox], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-CASMailbox
    + PSComputerName        : outlook.office365.com"

It's a Exchange Online mailbox, session to Exchange was established, was able to get user information but not able to use -OWAEnabled. This parameter is also explained here: https://docs.microsoft.com/en-us/powershell/module/exchange/client-access/set-casmailbox?view=exchange-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c54f270-42bc-b363-35ae-9bd20657b3e6
* Version Independent ID: 0ff7501d-6606-b2b2-beb0-7bf27683fd27
* Content: [Enable or disable Outlook Web App for a mailbox](https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-outlook-web-app#feedback)
* Content Source: [Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-outlook-web-app.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/recipients-in-exchange-online/manage-user-mailboxes/enable-or-disable-outlook-web-app.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @KwekuA
* Microsoft Alias: **kwekua**

**Comment by scanum** [comment]
@pkothree thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
