### ISSUE TITLE
Additional control in Exchange can be added to this article

### ISSUE THREAD

**Issue by prsamant** [MicrosoftDocs/OfficeDocs-Exchange#975]
We can also add an option to the customers to block Outlook for Android and iOS App by using the Exchange command : Set-CASMailbox jane@contoso.com -EwsBlockList @{Add="Outlook-iOS/*","Outlook-Android/*"}  - Please consider this as we have seen issues been resolved and Outlook App for iOS and Android connections are blocked. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247b0890-a1fe-6243-5ed5-09caa093e942
* Version Independent ID: 5abcab3a-5288-d497-e56b-b0cc1d5eb2b8
* Content: [Outlook for iOS security, Outlook for Android security, Outlook for iOS data security, Outlook for Android data security, Outlook iOS Security MDM, Outlook Android security MDM, Outlook iOS security Exchange policies](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/secure-outlook-for-ios-and-android#exchange-online-controls)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/secure-outlook-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/secure-outlook-for-ios-and-android.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@prsamant Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@prsamant We appreciate any feedback that improves the content in the Microsoft docs and we will consider adding this in the future.

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
