### ISSUE TITLE
Please Fix Codew

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#976]
You have "$OABMBX = Get-Mailbox "SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}" -Arbitration (Get-ADUser 
$OABMBX.SamAccountName -Properties *).msExchCapabilityIdentifiers"

Please update so that "(Get-ADUser 
$OABMBX.SamAccountName -Properties *).msExchCapabilityIdentifiers" is on a new line or place a ";" between the commands.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @SquirrelAssassin 

Thank you for reaching out!

The sentence forms only one command not the two separate commands. Kindly check again and let us know if you still find it as an issue. 

$OABMBX = Get-Mailbox "SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}" -Arbitration (Get-ADUser $OABMBX.SamAccountName -Properties *).msExchCapabilityIdentifiers

Thank you.

**Comment by SquirrelAssassin** [comment]
What are you talking about where is $oabmbx instantiated so that you can call .samaccountname against it.  If that is one command you are missing a command to get $oabmbx as you can’t get samaccountname from nothing.

**Comment by msdmaguire** [comment]
@SquirrelAssassin please try:
    
$OABMBX = Get-Mailbox "SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}" -Arbitration 

(Get-ADUser $OABMBX.SamAccountName -Properties *).msExchCapabilityIdentifiers
    
$OABMBX = Get-Mailbox "SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c}" -Arbitration; (Get-ADUser $OABMBX.SamAccountName -Properties *).msExchCapabilityIdentifiers

If this doesn't work as expected, please open a support ticket.

**Comment by SquirrelAssassin** [comment]
Great you figured out that you either need new lines or ; between your statements, now update the documentation so others understand also. But don’t close a ticket until the actual document is updated ..... you know it’s the whole reason I posted this in the first place.
