### ISSUE TITLE
No enable command for SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}:

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#977]
Please update to add in the how to for SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9}, I setup but its not showing up as arbitration mailbox. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @SquirrelAssassin 

Thank you for reaching out!

We would suggest you to please contact support team by opening a service ticket in your tenant. They would definitely assist you. And please let us know if it is something that can be called out in the docs. Please follow this link to contact support for business.

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Thank you.

**Comment by SquirrelAssassin** [comment]
Umm I didn’t have to contact support it’s not a support issue.  It’s how it is.  I tested back to cu 18 and they all have the wrong names.  You need to update the documentation to update the names once updating a customers ad env as they all have the same name. And the customer needs to update the display name.

**Comment by msdmaguire** [comment]
Hi @SquirrelAssassin. When you run the command that we specified in the documentation, it should set the msExchCapabilityIdentifiers to be equal of the same account on a brand new Exchange installation.

**Comment by msdmaguire** [comment]
Hi @SquirrelAssassin. If get-mailbox -arbitration does not show the SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9} mailbox, we recommend that you contact support so they can help you remove the account and follow the official, supported recovery steps.

**Comment by SquirrelAssassin** [comment]
read back on #984
