### ISSUE TITLE
Commands not complete

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#978]
Please update the get-user commands to retrieve all users

"Get-User -resultsize unlimited ........"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @SquirrelAssassin 

Thanks for reaching out!

Based on your confirmation on this https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/984, can we close this issue now?

Kindly confirm. Thank you.
