### ISSUE TITLE
1f05a927-9350-4efe-a823-5529c2d64109

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#979]
shouldnt this mailbox have:
-MessageTracking:$True
and not bb558c35-97f1-4cb9-8ff7-d53741dc928c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @SquirrelAssassin 

Thank you for reaching out!

We would suggest you to please contact support team by opening a service ticket in your tenant. They would definitely assist you. And please let us know if it is something that can be called out in the docs. Please follow this link to contact support for business.

https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Thank you.

**Comment by SquirrelAssassin** [comment]
Nope I won’t this is bad documentation it should not be dealing with message tacking ie moderated distro groups.  Get with who wrote this and have them sit back down with the product team.

**Comment by SquirrelAssassin** [comment]
1f is shown in so many places for managed distro management not b55

**Comment by msdmaguire** [comment]
When you run the command that we specified in the documentation, it should set the msExchCapabilityIdentifiers to be equal of the same account on a brand new exchange installation.

**Comment by SquirrelAssassin** [comment]
Should it... are you testing with 2013 cu19 to cu 21 downloaded straight from your own website.  Because that’s not what’s happening in the adsetup area.  And is not the answer that people will look for when landing on this page. Go back to my #984 comment for the full list of commands that actually work.

**Comment by SquirrelAssassin** [comment]
#984 I’m done with this.
