### ISSUE TITLE
ran the command just as above

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#980]
[PS] C:\Users\xxxx\Desktop\cu21&gt;Enable-Mailbox -Arbitration -Identity "FederatedEmail.4c1f4d8b-8179-4148-93bf-00a95f
1e042"
This task does not support recipients of this type. The specified recipient
xxxxx/Users/FederatedEmail.4c1f4d8b-8179-4148-93bf-00a95fa1e042 is of type UserMailbox. Please make sure
that this recipient matches the required recipient type for this task.
    + CategoryInfo          : InvalidArgument: (...bf-00a95fa1e042:RecipientIdParameter) [Enable-Mailbo
   x], RecipientTaskException
    + FullyQualifiedErrorId : [Server=xxxxx,RequestId=fde5c283-bca6-47f4-839e-d31a84d908ed,TimeStamp=5/25/2019
   6:06:56 PM] [FailureCategory=Cmdlet-RecipientTaskException] 3CD6CA39,Microsoft.Exchange.Management.RecipientTasks.
  EnableMailbox
    + PSComputerName        : xxxxxx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @SquirrelAssassin 

Thank you for reaching out!

For technical issues like these please contact support team by opening a service ticket in your tenant. They would definitely assist you. And please let us know if it is something that can be called out in the docs. Please follow this link to contact support for business. 

https://docs.microsoft.com/office365/admin/contact-support-for-business-products 

Thank you.

**Comment by msdmaguire** [comment]
@SquirrelAssassin We were unable to reproduce the scenario you describe above, and we recommend that you open a support ticket (see above link) so you can work with Microsoft Support to delete and recreate the mailbox in question.
