### ISSUE TITLE
CU21 Package all wrong names

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#981]
Why do they all show up as "microsoft exchange approval", I used the cu21 package just downloaded from microsoft?

[PS] C:\Users\xxx\Desktop\cu21&gt;Get-Mailbox -Arbitration | Format-Table Name, DisplayName

Name                                                DisplayName
----                                                -----------
SystemMailbox{bb558c35-97f1-4cb9-8ff7-d53741dc928c} Microsoft Exchange Approval Assistant
Migration.8f3e7716-2011-43e4-96b1-aba62d229136      Microsoft Exchange Approval Assistant
FederatedEmail.4c1f4d8b-8179-4148-93bf-00a95fa1e042 Microsoft Exchange Approval Assistant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@SquirrelAssassin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by SquirrelAssassin** [comment]
umm nah we fixed it I posted the fix but I tried the update from cu20 / 21 / and 22 the bad code exists in all versions
