### ISSUE TITLE
ERROR After applying this when sending from on prem to moderated and accepting from cloud

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#982]
O365 when accepting a moderated message from on prem and accepting shows the following:
Microsoft Exchange Approval Assistant (SystemMailboxbb558c35-97f1-4cb9-8ff7-d53741dc928c@xxx)
Your message can't be delivered because delivery to this address is restricted.
 For more information about this issue see DSN code 5.7.1 in Exchange Online.

Why is the SystemMailboxbb558c35-97f1-4cb9-8ff7-d53741dc928c the designated mailbox should it not be 1f05a927-9350-4efe-a823-5529c2d64109

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by SquirrelAssassin** [comment]
the bb5 mailbox was accepting the mailtracking, I had to disable this

**Comment by scanum** [comment]
@SquirrelAssassin thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by SquirrelAssassin** [comment]
The error was resolved after we removed -MessageTracking:$True from the b55 guid arbitration mailbox,  that mailbox does not handle messagetracking
