### ISSUE TITLE
Incorrect GUID:  SystemMailbox{1f05a927-9350-4efe-a823-5529c2d64109}

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#983]
This guid is only the same across the board up to the first 8 #'s.  Please update.  
Mine is:
SystemMailbox{1f05a927-6f11-40c8-b45a-83af00148f3b}

This is well documented here:
https://docs.microsoft.com/en-us/exchange/architecture/mailbox-servers/recreate-arbitration-mailboxes?view=exchserver-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c580e0a7-cfe1-9630-8047-9cff5b4ea12c
* Version Independent ID: 2c405ac6-e19a-d8c9-0177-670842c7967f
* Content: [Recreating arbitration mailboxes: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/recreating-arbitration-mailboxes-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/recreating-arbitration-mailboxes-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by sowjanya365** [comment]
Hi @SquirrelAssassin 

Thank you for reaching out!

Mail box names are unique to organizations. Using the same name may not work. If you want to know more about it please open a service ticket in your tenant. And please share with us the outcome if you feel that the document needs to be modified. We will certainly do it. Hope this clarifies your query. Thank you.

**Comment by msdmaguire** [comment]
Thanks for the feedback, article has been updated!
