### ISSUE TITLE
Update with this info

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/OfficeDocs-Exchange#984]
Gosh this article cost me so much wasted time.  Here is what works.  After using the right commands .... the moderation started to come over as the correct address.  

E:\Setup.exe /IAcceptExchangeServerLicenseTerms /PrepareAD
Get-User -resultsize unlimited | Where {$_.Name –like "SystemMailbox*"} | Enable-Mailbox -Arbitration -force:$true
Get-User -resultsize unlimited | Where {$_.Name –like "FederatedEmail*"} | Enable-Mailbox –Arbitration -force:$true
GET-MAILBOX -RESULTSIZE UNLIMITED "SYSTEMMAILBOX{BB558C35-97F1-4CB9-8FF7-D53741DC928C}" -ARBITRATION | SET-MAILBOX -ARBITRATION -UMGRAMMAR:$TRUE -OABGEN:$TRUE -GMGEN:$TRUE -CLIENTEXTENSIONS:$TRUE -PSTPROVIDER:$TRUE -MAXSENDSIZE 1GB -FORCE
GET-MAILBOX -RESULTSIZE UNLIMITED "SystemMailbox{1f05a927*" -ARBITRATION | SET-MAILBOX -ARBITRATION -MessageTracking:$true -MAXSENDSIZE 1GB -FORCE
$OABMBX = GET-MAILBOX "SYSTEMMAILBOX{BB558C35-97F1-4CB9-8FF7-D53741DC928C}" -ARBITRATION
(GET-ADUSER $OABMBX.SAMACCOUNTNAME -PROPERTIES *).MSEXCHCAPABILITYIDENTIFIERS
SET-ADUSER $OABMBX.SAMACCOUNTNAME -ADD @{"MSEXCHCAPABILITYIDENTIFIERS"="40","42","43","44","47","51","52","46"}
Get-Mailbox –Identity "SystemMailbox{e0dc1c29*" –Arbitration | Set-Mailbox –Arbitration –DisplayName "Microsoft Exchange" -force:$true
Get-Mailbox –Identity "FederatedEmail.4c1f4d8b*" –Arbitration | Set-Mailbox –Arbitration –DisplayName "Microsoft Exchange Federation Mailbox" -force:$true
Get-Mailbox –Identity "Migration.8f3e7716*" –Arbitration | Set-Mailbox –Arbitration –DisplayName "Microsoft Exchange Migration" -force:$true
Get-Mailbox –Identity "SystemMailbox{1f05a927*" –Arbitration | Set-Mailbox –Arbitration –DisplayName "Microsoft Exchange Approval Assistant" -force:$true
Get-Mailbox –Identity "SystemMailbox{bb558c35*" –Arbitration | Set-Mailbox –Arbitration –DisplayName "Microsoft Exchange" -force:$true
Get-Mailbox –Arbitration –Identity "FederatedEmail*" | Set-Mailbox –Arbitration –ProhibitSendQuota 1MB
Get-Mailbox -Arbitration | Format-Table Name, DisplayName

**Comment by scanum** [comment]
@SquirrelAssassin Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@lusassl-msft Hi Lukas! Hope you are doing well. Just tagging you because you were comenting in this issue : https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/789

**Comment by SquirrelAssassin** [comment]
This was the ultimate fix.  Pieced together from many sites and tested ... and it works.

**Comment by scanum** [comment]
@officedocsbot close
