### ISSUE TITLE
Still problem with DAG parameters #789

### ISSUE THREAD

**Issue by MrSundh** [MicrosoftDocs/OfficeDocs-Exchange#987]
Reposting this as a new when my plea to reopen #789 has gone unnoticed.

So, in reference to #789.
Our DAG is configured for autoreseed as follows:
AutoDagSchemaVersion : 1.0
AutoDagDatabaseCopiesPerDatabase : 1
AutoDagDatabaseCopiesPerVolume : 1
AutoDagTotalNumberOfDatabases : 0
AutoDagTotalNumberOfServers : 0
AutoDagDatabasesRootFolderPath : C:\ExchangeDatabases
AutoDagVolumesRootFolderPath : C:\ExchangeVolumes
AutoDagAllServersInstalled : False
AutoDagAutoReseedEnabled : True
AutoDagDiskReclaimerEnabled : True
AutoDagBitlockerEnabled : False
AutoDagFIPSCompliant : False
AutoDagAutoRedistributeEnabled : True
AutoDagSIPEnabled : False
AutoDagDiskReclaimerEnabled : True
The DAG contain 13 databases spanned across 6 server, each with 9 database disks. Only on database is stored per volume. Databases have 4 copies including 1 copy with 14 Days lag.
No online spare disks.
The database disks are 4GB each and there is 3 1GB SSD disks per server to handle the future MetaCacheDatabase.
The command used in my previous try to configure the MCDB was:
Manage-MCDB -DagName OurDAGName -ConfigureMCDBPrerequisite -SSDSizeInBytes 959925190660 -SSDCountPerServer 3
What I see as a first step is to figure out values for AutoDagTotalNumberOfDatabases and AutoDagTotalNumberOfServers as they are 0 today.
AutoDagTotalNumberOfDatabases, spontaneously it feels like 13 in our case, but then the question is whether it is what is meant or if it is inclusive of all copies which would be 13 * 4 = 52.
AutoDagTotalNumberOfServers, should be 6 if it is not meant the number of servers a database copies span, then it should be 4.

**Comment by scanum** [comment]
@MrSundh Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@MrSundh thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
