### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by JakeMoe** [MicrosoftDocs/OfficeDocs-Exchange#989]
After I run:

Set-Mailbox -Identity &lt;user mailbox&gt; -DeliverToMailboxAndForward $true -ForwardingSMTPAddress &lt;external e-mail address&gt;

I then check the mailbox in the admin portal under mailbox features --&gt; Delivery Options --&gt; View Details, and the forwarding is *not* set up.  However, if I go to OWA for that mailbox, I can see the forward is turned on under &lt;gear&gt; --&gt; View All Outlook Settings --&gt; Mail --&gt; Forwarding, so I believe there's an administrative forward and a user forward available?

FWIW, I'm trying to get to the server-side forwarding through PowerShell (I would have thought through Get-Mailbox?), so I can find all the mailboxes that still have it turned on, in an effort to clean up some old forwards that shouldn't be happening anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afdaec1b-3f68-1f0e-db9e-1d8acf20ac4a
* Version Independent ID: fb622286-016d-86e5-a794-d2c3c9696cc5
* Content: [Configure email forwarding for a mailbox](https://docs.microsoft.com/en-us/exchange/recipients/user-mailboxes/email-forwarding?view=exchserver-2019&viewFallbackFrom=exchhybrid-ww#feedback)
* Content Source: [Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/user-mailboxes/email-forwarding.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@JakeMoe Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@JakeMoe thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
