### ISSUE TITLE
[LOC] Invalid fwlinks in several articles

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#991]
Hello,

 could you please check table below with broken fwlinks and update or remove it from the articles?

flwlink | topic | Live URL
-- | -- | --
https://go.microsoft.com/?linkid=9834898<br/>https://go.microsoft.com/?linkid=9834902<br/>https://go.microsoft.com/?linkid=9834903<br/>https://go.microsoft.com/?linkid=9834904<br/>https://go.microsoft.com/fwlink/?linkid=286258 | azure-help-identify-my-issue-with-automatic-checks-dns-records-exchange-2013-help.md | https://docs.microsoft.com/en-us/exchange/azure-help-identify-my-issue-with-automatic-checks-dns-records-exchange-2013-help
https://go.microsoft.com/fwlink/?linkid=846696 | decommission-on-premises-exchange.md | https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange
https://go.microsoft.com/fwlink/p/?LinkId=279920 | message-tracking.md | https://docs.microsoft.com/en-us/exchange/mail-flow/transport-logs/message-tracking?view=exchserver-2019
https://go.microsoft.com/fwlink/p/?LinkID=282327<br/>https://go.microsoft.com/fwlink/p/?LinkId=283968<br/>https://go.microsoft.com/fwlink/p/?LinkId=283969<br/>https://go.microsoft.com/fwlink/p/?LinkId=283975 | exchange-online-and-exchange-online-protection-service-upgrade.md | https://docs.microsoft.com/en-us/exchange/exchange-online-and-exchange-online-protection-service-upgrade
https://go.microsoft.com/fwlink/p/?linkId=50977 | sender-id.md | https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antispam-protection/sender-id?view=exchserver-2019
https://go.microsoft.com/fwlink/p/?LinkId=87385 | configure-certificate-based-auth.md | https://docs.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/configure-certificate-based-auth?view=exchserver-2019

Thank you

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by dariomws306** [comment]
Hi @OfficeGlobal, thank you for your feedback.

live url | my comments
-- | --
https://docs.microsoft.com/en-us/exchange/azure-help-identify-my-issue-with-automatic-checks-dns-records-exchange-2013-help | All the link are wrong here, so I think we should remove the whole article or maybe we can use this link to replace all of them: https://docs.microsoft.com/office365/enterprise/external-domain-name-system-records
https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange | I cannot find the fwlink, but I think this article needs a "hit refresh"
https://docs.microsoft.com/en-us/exchange/mail-flow/transport-logs/message-tracking?view=exchserver-2019 | I cannot find the fwlink and all the links look good
https://docs.microsoft.com/en-us/exchange/exchange-online-and-exchange-online-protection-service-upgrade | I think we should remove the article, there aren't good articles to replace fwlinks
https://docs.microsoft.com/en-us/exchange/antispam-and-antimalware/antispam-protection/sender-id?view=exchserver-2019 | I have replaced the fwlink (PR)
https://docs.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/configure-certificate-based-auth?view=exchserver-2019 | I have removed the fwlink (PR)

**Comment by OfficeGlobal** [comment]
Hello @dariomws306,

 suggestions seems to be fine for us.
Once you sync changes to Live repository, we'll pick it up for a localization.

**Comment by dariomws306** [comment]
@OfficeGlobal done!

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
