### ISSUE TITLE
[LOC] Invalid download link in a several articles

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeDocs-Exchange#992]
Hello,

 could you please check articles listed below and update / remove broken link https://www.microsoft.com/download/details.aspx?id=35718 ?

**Link text:** Update for Microsoft Office Outlook 2007 (KB2687404)
**Link URL:** https://www.microsoft.com/download/details.aspx?id=35718
**Affected topics:** 
 - https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-legacy-hybrid-public-folders
 - https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/set-up-exo-hybrid-public-folders
 - https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/configure-legacy-public-folders-for-hybrid?view=exchserver-2019

**Comment by scanum** [comment]
@OfficeGlobal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@Thank you for submitting feedback. We understand that this issue has been resolved on PR #1024 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
